URIVisionLibrary: binaryImage_main.cpp File Reference
binaryImage_main.cpp File Reference
#include <iostream>
#include "ImageReader.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray.h"
#include "RasterImage_binary.h"
#include "LabelRaster.h"
#include "GrayThresholdLabeler.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const string output_dir = OUTPUT_DIR_PATH
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbRowsSubwindows *kNbColsSubwindows]
bool gInitDone = false
RasterImage ** gMyImage = NULL
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int QUIT_MENU = 0
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 48 of file binaryImage_main.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 49 of file binaryImage_main.cpp.
#define kDefaultWidth 256
Definition at line 50 of file binaryImage_main.cpp.
#define kMaxWindowHeight 640
Definition at line 52 of file binaryImage_main.cpp.
#define kMaxWindowWidth 900
Definition at line 51 of file binaryImage_main.cpp.
#define kNbBckgndCols 5
Definition at line 111 of file binaryImage_main.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 44 of file binaryImage_main.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 46 of file binaryImage_main.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 43 of file binaryImage_main.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 45 of file binaryImage_main.cpp.
Referenced by main(), and myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 156 of file binaryImage_main.cpp.
Referenced by main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 132 of file binaryImage_main.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 170 of file binaryImage_main.cpp.
References filePath, uriVL::ImageRect::getBottom(), uriVL::ImageReader::getFrame(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), gImageHeight, gImageWidth, gray_dir, kNbImages, LOWER_LEFT, LOWER_RIGHT, myReader, uriVL::R_W_ACCESS, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     gMyImage = new RasterImage*[kNbImages];
     //-------------------------------------------------------------
     //  We read Image 0 from a file
     //-------------------------------------------------------------
     const string filePath = gray_dir + "Lena_256x256.tga";
     ImageReader myReader(const_cast<char*>(filePath.c_str()));
     gMyImage[UPPER_LEFT] = myReader.getFrame(true);
     if (gMyImage[UPPER_LEFT] ==NULL)
     {
         cout << "Error encountered while reading image file " << const_cast<char*>(filePath.c_str()) << endl;
         std::exit(-1);
     }
     gImageWidth = gMyImage[UPPER_LEFT]->getWidth();
     gImageHeight = gMyImage[UPPER_LEFT]->getHeight();
     //-------------------------------------------------------------
     //  Image 1 is a binary version of Image 0
     //-------------------------------------------------------------
     // Here the transformation [0-255] --> [0-1] is done by the CopyBits function
     // of QuickTime/QuickDraw.  It simply puts a threshold level at 127.  Below is 0,
     //  above is 1.
     gMyImage[UPPER_RIGHT] = new RasterImage_binary(gMyImage[UPPER_LEFT]);
     //-------------------------------------------------------------
     //  Image 3 is Image 1 to which I add 1 diagonal line
     //-------------------------------------------------------------
     gMyImage[LOWER_RIGHT] = new RasterImage_binary(gMyImage[UPPER_RIGHT]);
     //-------------------------------------------------------------
     //  Image 2 is created out of an attenuated copy of Image 0
     //-------------------------------------------------------------
     RasterImage_gray    *tempGray = new RasterImage_gray(gMyImage[UPPER_LEFT]);
     const unsigned char *const* grayIn = gMyImage[UPPER_LEFT]->getShiftedRaster2D();
     unsigned char *const* grayOut = tempGray->getShiftedRaster2D(R_W_ACCESS);
     //  ... and I proceedd to applying the 0.8 attenuation
     const ImageRect *rect = gMyImage[UPPER_LEFT]->getValidRect();
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             grayOut[i][j] = static_cast<unsigned char>(0.8 * grayIn[i][j]);
     //  Same coment as for Image 1.  The thresholding is done by QuickTime
     gMyImage[LOWER_LEFT] = new RasterImage_binary(tempGray);
     delete tempGray;
     //  Write a black cross on the image
     //--------------------------------------
         grayOut = ((RasterImage_binary *) gMyImage[LOWER_RIGHT])->getGrayRasterImage()->getShiftedGray2D(R_W_ACCESS);
     //  UL - LR diagonal
     for (int i=iLow, j=jLow; (i<=iHigh) && (j<=jHigh); i++, j++) {
         //  any non-zero value will count as 1 when binarized
         grayOut[i][j] = static_cast<unsigned char>(0);
         if (i>iLow)
             grayOut[i-1][j] = static_cast<unsigned char>(0);
         if (i>iLow+1)
             grayOut[i-2][j] = static_cast<unsigned char>(0);
         if (i<iHigh)
             grayOut[i+1][j] = static_cast<unsigned char>(0);
         if (i<iHigh-1)
             grayOut[i+2][j] = static_cast<unsigned char>(0);
     }
     //  UR - LL diagonal
     for (int i=iLow, j=jHigh; (i<=iHigh) && (j>=jLow); i++, j--) {
         //  any non-zero value will count as 1 when binarized
         grayOut[i][j] = static_cast<unsigned char>(0);
         if (i>iLow)
             grayOut[i-1][j] = static_cast<unsigned char>(0);
         if (i>iLow+1)
             grayOut[i-2][j] = static_cast<unsigned char>(0);
         if (i<iHigh)
             grayOut[i+1][j] = static_cast<unsigned char>(0);
         if (i<iHigh-1)
             grayOut[i+2][j] = static_cast<unsigned char>(0);
      }
 }
int main (int argc, char ** argv)
Definition at line 538 of file binaryImage_main.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), gImageHeight, gImageWidth, gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), and setupCamera().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {  myDisplay0, myDisplay1,
                                                       myDisplay2, myDisplay3};
     try {
                 glutInit(&argc, argv);
                 glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
                 initializeQTEnvironment();
                 loadImage();
                 //      I initialize my window's dimensions at the default values
                 gWinHeight = kNbRowsSubwindows*(gImageHeight + kBorder) + kBorder;
                 gWinWidth = kNbColsSubwindows*(gImageWidth + kBorder) + kBorder;
                 glutInitWindowSize(gWinWidth,gWinHeight);
                 gMainWindow = glutCreateWindow("Binary Image Application Demo");
                 glutKeyboardFunc(myKeyboard);
                 glutDisplayFunc(myDisplayMain);
                 glutIdleFunc(myIdle);
                 glClearColor(0.0, 0.0, 1.0, 1.0);
                 winID = 0;
                 glutSetWindow(gMainWindow);
                 for (int i=0; i<kNbRowsSubwindows; i++)
                         for (int j=0; j<kNbColsSubwindows; j++)
{
                                 gSubwindow[winID] = glutCreateSubWindow(
                                                                                                                 gMainWindow,
                                                                                                                 j*(gImageWidth + kBorder) + kBorder,
                                                                                                                 i*(gImageHeight + kBorder) + kBorder,
                                                                                                                 gImageWidth,
                                                                                                                 gImageHeight);
                                 //      I don't need to do this.  I just set a different "clear" color for
                                 //      each subwindow.
                                 backColor = kBackgroundColor[winID];
                                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                                 glutKeyboardFunc(myKeyboard);
                                 //      This calls maps "world" coordinates to "screen" coordinates.
                                 //      In this particular case I make them coincide.
                                 setupCamera(gImageWidth, gImageHeight);
                                 //      This *has* to be defined:  a "display" callback function for each subwindow
                                 glutDisplayFunc(displayFuncTable[winID++]);
                                 glutSetWindow(gMainWindow);
                         }
                 myInit();
                 //  and I inform drawable objects of the image's dimensions (in case they want to get
                 //  rendered "shifted")
                 DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
                 myDisplayMain();
                 glutMainLoop();
                 cleanupAndQuit(0);
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
     return 0;
 }
void myColorSubmenu (int value)
Definition at line 462 of file binaryImage_main.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
for ICPR paper
Definition at line 279 of file binaryImage_main.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), myDisplay(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_LEFT]!= NULL)
         gMyImage[UPPER_LEFT]->render();
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 293 of file binaryImage_main.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), myDisplay(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_RIGHT]!= NULL)
         gMyImage[UPPER_RIGHT]->render();
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 307 of file binaryImage_main.cpp.
References gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), myDisplay(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[LOWER_LEFT]!= NULL)
         gMyImage[LOWER_LEFT]->render();
     glutSwapBuffers();
 }
void myDisplay3 (void)
Definition at line 322 of file binaryImage_main.cpp.
References gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), myDisplay(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[LOWER_RIGHT]!= NULL)
         gMyImage[LOWER_RIGHT]->render();
     glutSwapBuffers();
 }
void myDisplayMain (void)
Definition at line 264 of file binaryImage_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 478 of file binaryImage_main.cpp.
References gInitDone, and gMainWindow.
Referenced by main().
 {
         if (gInitDone)
         {
                 glutSetWindow(gMainWindow);
             glutPostRedisplay();
         }
 }
void myInit (void)
Definition at line 489 of file binaryImage_main.cpp.
References gInitDone, gMainWindow, gSubwindow, kBckgndColStr, kNbBckgndCols, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), QUIT_MENU, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[0] = glutCreateMenu(myMenu0);
     glutAddSubMenu("Color", colorSubmenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[1] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     menu[2] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[3] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 369 of file binaryImage_main.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myMenu0 (int value)
Definition at line 401 of file binaryImage_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
             //  0 --> Exit/Quit
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 417 of file binaryImage_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 432 of file binaryImage_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 447 of file binaryImage_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 386 of file binaryImage_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myReshape (int w, int h)
Definition at line 338 of file binaryImage_main.cpp.
References setupCamera().
 {
     setupCamera(w, h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 352 of file binaryImage_main.cpp.
Referenced by main(), and myReshape().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 36 of file binaryImage_main.cpp.
Referenced by loadImage().
int gImageHeight = kDefaultHeight
Definition at line 92 of file binaryImage_main.cpp.
Referenced by loadImage(), and main().
int gImageWidth = kDefaultWidth
Definition at line 91 of file binaryImage_main.cpp.
Referenced by loadImage(), and main().
bool gInitDone = false
Definition at line 97 of file binaryImage_main.cpp.
Referenced by myIdle(), and myInit().
int gMainWindow
Definition at line 94 of file binaryImage_main.cpp.
Referenced by main(), myColorSubmenu(), myDisplayMain(), myIdle(), and myInit().
RasterImage** gMyImage = NULL
Definition at line 99 of file binaryImage_main.cpp.
const string gray_dir = GRAY_DIR_PATH
Definition at line 37 of file binaryImage_main.cpp.
Referenced by loadImage().
int gSubwindow[kNbRowsSubwindows *kNbColsSubwindows]
Definition at line 94 of file binaryImage_main.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
int gWinHeight
Definition at line 89 of file binaryImage_main.cpp.
Referenced by main().
int gWinWidth
Definition at line 89 of file binaryImage_main.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 113 of file binaryImage_main.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 119 of file binaryImage_main.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 103 of file binaryImage_main.cpp.
Referenced by loadImage(), myDisplay2(), and myInit().
const int LOWER_RIGHT = 3
Definition at line 104 of file binaryImage_main.cpp.
Referenced by loadImage(), myDisplay3(), and myInit().
const string output_dir = OUTPUT_DIR_PATH
Definition at line 38 of file binaryImage_main.cpp.
const int QUIT_MENU = 0
Definition at line 106 of file binaryImage_main.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int UPPER_LEFT = 0
Definition at line 101 of file binaryImage_main.cpp.
Referenced by loadImage(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 102 of file binaryImage_main.cpp.
Referenced by loadImage(), myDisplay1(), and myInit().