URIVisionLibrary: uriVL::Vector2D_F Class Reference
uriVL::Vector2D_F Class Reference
Implements the Vector2D_F class.
#include <Vector2D_F.h>
Public Member Functions
Vector2D_F (void)
Default Constructor.
Vector2D_F (float dx, float dy)
Constructor.
Vector2D_F (const float dxy[])
Constructor.
Vector2D_F (const Vector2D *vec)
Copy constructor.
Vector2D_F (const ImagePoint *pt1, const ImagePoint *pt2)
Constructor.
~Vector2D_F (void)
Destructor.
float getXF (void) const
Returns the vector's x coordinate.
float getYF (void) const
Returns the vector's y coordinate.
void setX (int val)
Assigns new x coordinate to the vector.
void setX (float val)
Assigns new x coordinate to the vector.
void setY (int val)
Assigns new y coordinate to the vector.
void setY (float val)
Assigns new y coordinate to the vector.
void setCoordinates (int valX, int valY)
Assigns new coordinates to the vector.
void setCoordinates (const int xy[])
Assigns new coordinates to the pixel.
void setCoordinates (float valX, float valY)
Assigns new coordinates to the pixel.
void setCoordinates (const float xy[])
Assigns new coordinates to the pixel.
void setCoordinates (const Vector2D *theVec)
Assigns new coordinates to the vector.
void setCoordinates (const ImagePoint *pt1, const ImagePoint *pt2)
Assigns new coordinates to the vector.
bool hasSubpixelPrecision (void) const
Indicates that this object has subpixel precision (overrides parent class's virtual function).
void applyRotation (const Rotation2D *theRot)
Applies a Rotation2D to this object.
void rotate (float angle)
Rotates the object by the angle specified (in radians)
Public Member Functions inherited from uriVL::Vector2D
Vector2D (void)
Default Constructor.
Vector2D (int dx, int dy)
Constructor.
Vector2D (const int dxy[])
Constructor.
Vector2D (const Vector2D *displ)
Copy constructor.
Vector2D (const ImagePoint *pt1, const ImagePoint *pt2)
Constructor.
virtual ~Vector2D (void)
Destructor.
int getX (void) const
Returns the pixel's x coordinate.
int getY (void) const
Returns the pixel's y coordinate.
Private Attributes
float xf_
The vector's x coordinate.
float yf_
The vector's y coordinate.
Additional Inherited Members
Protected Attributes inherited from uriVL::Vector2D
int x_
The vector's x coordinate.
int y_
The vector's y coordinate.
Detailed Description
Implements the Vector2D_F class.
A Vector2D_F should typically store an image displacement or an edge of a contour
Version history
2007/11/02 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 37 of file Vector2D_F.h.
Constructor & Destructor Documentation
Vector2D_F::Vector2D_F (void)
Default Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Definition at line 31 of file Vector2D_F.cpp.
                 :       Vector2D(),
                         //
                         xf_(0.f),
                         yf_(0.f)
 {
 }
Vector2D_F::Vector2D_F (float dx, float dy)
Constructor.
Creates and initializes an image displacement.
Parameters
dx x coordinate of the vector
dy y coordinate of the vector
Definition at line 40 of file Vector2D_F.cpp.
                 :       Vector2D(static_cast<int>(theX), static_cast<int>(theY)),
                         //
                         xf_(theX),
                         yf_(theY)
 {
 }
Vector2D_F::Vector2D_F (const float dxy[])
Constructor.
Creates and initializes an image displacement.
Parameters
dxy coordinate array of the vector
Definition at line 48 of file Vector2D_F.cpp.
                 :       Vector2D(static_cast<int>(xy[0]), static_cast<int>(xy[1])),
                         //
                         xf_(xy[0]),
                         yf_(xy[1])
 {
 }
 catch(...) {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to Vector2D_F constructor");
 }
Vector2D_F::Vector2D_F (const Vector2D * vec)
Copy constructor.
Creates a clone of the Vector2D object passed as parameter.
Parameters
vec pointer to the Vector2D object to clone
Definition at line 62 of file Vector2D_F.cpp.
References uriVL::ErrorReport::appendToMessage(), and setCoordinates().
                 :   Vector2D(),
                         //
                         xf_(0.f),
                         yf_(0.f)
 {
         try {
                 setCoordinates(theVec);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by Vector2D_F constructor.");
                 throw e;
         }
 }
Vector2D_F::Vector2D_F (const ImagePoint * pt1, const ImagePoint * pt2)
Constructor.
Creates and initializes an image displacement joining two image points.
Parameters
pt1 start point of the vector
pt2 end point of the vector
Definition at line 78 of file Vector2D_F.cpp.
References uriVL::ErrorReport::appendToMessage(), and setCoordinates().
                 :   Vector2D(),
                         //
                         xf_(0.f),
                         yf_(0.f)
 {
         try {
                 setCoordinates(pt1, pt2);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by Vector2D_F constructor.");
                 throw e;
         }
 }
Vector2D_F::~Vector2D_F (void)
Destructor.
Definition at line 93 of file Vector2D_F.cpp.
 {
 }
Member Function Documentation
void Vector2D_F::applyRotation (const Rotation2D * theRot) virtual
Applies a Rotation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Reimplemented from uriVL::Vector2D.
Definition at line 283 of file Vector2D_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
float Vector2D_F::getXF (void) const
Returns the vector's x coordinate.
Returns
x coordinate of the vector
Definition at line 232 of file Vector2D_F.cpp.
References xf_.
Referenced by uriVL::Disparity::setDisparity().
 {
     return xf_;
 }
float Vector2D_F::getYF (void) const
Returns the vector's y coordinate.
Returns
y coordinate of the vector
Definition at line 237 of file Vector2D_F.cpp.
References yf_.
Referenced by uriVL::Disparity::setDisparity().
 {
     return yf_;
 }
bool uriVL::Vector2D_F::hasSubpixelPrecision (void) const inline virtual
Indicates that this object has subpixel precision (overrides parent class's virtual function).
Reimplemented from uriVL::Vector2D.
Definition at line 161 of file Vector2D_F.h.
{
                                 return true;
                         }
void Vector2D_F::rotate (float angle) virtual
Rotates the object by the angle specified (in radians)
Parameters
angle the angle of the rotation (in radians)
Reimplemented from uriVL::Vector2D.
Definition at line 275 of file Vector2D_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void Vector2D_F::setCoordinates (int valX, int valY) virtual
Assigns new coordinates to the vector.
Parameters
valY new x coordinate for the vector
valY new y coordinate for the vector
Reimplemented from uriVL::Vector2D.
Definition at line 118 of file Vector2D_F.cpp.
References uriVL::Vector2D::x_, xf_, uriVL::Vector2D::y_, and yf_.
Referenced by uriVL::Disparity::setDisparity(), and Vector2D_F().
 {
     x_ = valX;
     y_ = valY;
     xf_ = valX;
     yf_ = valY;
 }
void Vector2D_F::setCoordinates (const int xy[]) virtual
Assigns new coordinates to the pixel.
Parameters
theXY coordinate array of the pixel
Reimplemented from uriVL::Vector2D.
Definition at line 126 of file Vector2D_F.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::Vector2D::x_, xf_, uriVL::Vector2D::y_, and yf_.
 {
         try {
                 x_ = xy[0];
                 y_ = xy[1];
                 xf_ = xy[0];
                 yf_ = xy[1];
         }
         catch (...) {
                 FAIL_CONDITION( xy == NULL,
                                                 kNullParameterError,
                                                 "null coordinate array passed to ImagePoint::setCoordinates");
                 FAIL_CONDITION( true,
                                                 kNullParameterError,
                                                 "invalid pointer passed to ImagePoint::setCoordinates");
         }
 }
void Vector2D_F::setCoordinates (float valX, float valY)
Assigns new coordinates to the pixel.
Parameters
valY new x coordinate for the vector
valY new y coordinate for the vector
Definition at line 144 of file Vector2D_F.cpp.
References uriVL::Vector2D::x_, xf_, uriVL::Vector2D::y_, and yf_.
 {
     xf_ = valX;
     yf_ = valY;
     x_=static_cast<int>(round(xf_));
     y_=static_cast<int>(round(yf_));
 }
void Vector2D_F::setCoordinates (const float xy[])
Assigns new coordinates to the pixel.
Parameters
theXY coordinate array of the vector
Definition at line 105 of file Vector2D_F.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::Vector2D::x_, xf_, uriVL::Vector2D::y_, and yf_.
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to ImagePoint::setCoordinates");
     xf_ = xy[0];
     yf_ = xy[1];
     //
     x_ = static_cast<int>(round(xf_));
     y_ = static_cast<int>(round(yf_));
 }
void Vector2D_F::setCoordinates (const Vector2D * theVec) virtual
Assigns new coordinates to the vector.
Parameters
theVec pointer to the Vector2D object to copy
Reimplemented from uriVL::Vector2D.
Definition at line 153 of file Vector2D_F.cpp.
References FAIL_CONDITION, uriVL::Vector2D::getX(), uriVL::Vector2D::getY(), uriVL::kNullParameterError, uriVL::Vector2D::setCoordinates(), uriVL::Vector2D::setX(), uriVL::Vector2D::setY(), xf_, and yf_.
 {
         FAIL_CONDITION( theVec == NULL,
                                         kNullParameterError,
                                         "null Vector2D pointer passed to ImagePoint::setCoordinates");
         try {
                 if (typeid(*theVec) == typeid(uriVL::Vector2D_F))
                 {
                         const Vector2D_F        *theVecF = (Vector2D_F*) theVec;
                         xf_ = theVecF->xf_;
                         yf_ = theVecF->yf_;
                         Vector2D::setX(theVec->getX());
                         Vector2D::setY(theVec->getY());
                 }
                 else
                 {
                         int x = theVec->getX(),
                                 y = theVec->getY();
                         Vector2D::setCoordinates(x, y);
                         xf_ = x;
                         yf_ = y;
                 }
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kNullParameterError,
                                                 "invalid Vector2D pointer passed to ImagePoint::setCoordinates");
         }
 }
void Vector2D_F::setCoordinates (const ImagePoint * pt1, const ImagePoint * pt2) virtual
Assigns new coordinates to the vector.
Parameters
pt1 start point of the vector
pt2 end point of the vector
Reimplemented from uriVL::Vector2D.
Definition at line 184 of file Vector2D_F.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint_F::getXF(), uriVL::ImagePoint::getY(), uriVL::kNullParameterError, uriVL::Vector2D::setCoordinates(), xf_, and yf_.
 {
     FAIL_CONDITION( (pt1 == NULL) || (pt2 == NULL),
                     kNullParameterError,
                     "null ImagePoint passed to Vector2D_F::setCoordinates");
     float dx=0.f, dy=0.f;
         try {
                 if (typeid(*pt2) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F      *pt2F = (ImagePoint_F*) pt2;
                         dx = pt2F->getXF();
                         dy = pt2F->getY();
                 }
                 else
                 {
                         dx = pt1->getX();
                         dy = pt1->getY();
                 }
                 if (typeid(*pt1) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F      *pt1F = (ImagePoint_F*) pt1;
                         dx -= pt1F->getXF();
                         dy -= pt1F->getY();
                 }
                 else
                 {
                         dx = pt1->getX();
                         dy = pt1->getY();
                 }
                 xf_ = dx;
                 yf_ = dy;
                 Vector2D::setCoordinates(static_cast<int>(roundf(xf_)), static_cast<int>(roundf(yf_)));
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kNullParameterError,
                                                 "invalid ImagePoint pointer passed to ImagePoint::setCoordinates");
         }
 }
void Vector2D_F::setX (int val) virtual
Assigns new x coordinate to the vector.
Parameters
val new x coordinate for the vector
Reimplemented from uriVL::Vector2D.
Definition at line 248 of file Vector2D_F.cpp.
References uriVL::Vector2D::x_, and xf_.
 {
     xf_ = theX;
         x_ = theX;
 }
void Vector2D_F::setX (float val)
Assigns new x coordinate to the vector.
Parameters
val new x coordinate for the vector
Definition at line 242 of file Vector2D_F.cpp.
References uriVL::Vector2D::x_, and xf_.
 {
     x_ = static_cast<int>(round(theX));
     xf_ = theX;
 }
void Vector2D_F::setY (int val) virtual
Assigns new y coordinate to the vector.
Parameters
val new y coordinate for the vector
Reimplemented from uriVL::Vector2D.
Definition at line 254 of file Vector2D_F.cpp.
References uriVL::Vector2D::y_, and yf_.
 {
     y_ = theY;
     yf_ = theY;
 }
void Vector2D_F::setY (float val)
Assigns new y coordinate to the vector.
Parameters
val new y coordinate for the vector
Definition at line 260 of file Vector2D_F.cpp.
References uriVL::Vector2D::y_, and yf_.
 {
     y_ = static_cast<int>(round(theY));
     yf_ = theY;
 }
Member Data Documentation
float uriVL::Vector2D_F::xf_ private
The vector's x coordinate.
Definition at line 181 of file Vector2D_F.h.
Referenced by getXF(), setCoordinates(), and setX().
float uriVL::Vector2D_F::yf_ private
The vector's y coordinate.
Definition at line 186 of file Vector2D_F.h.
Referenced by getYF(), setCoordinates(), and setY().
The documentation for this class was generated from the following files:
Vector2D_F.h
Vector2D_F.cpp