URIVisionLibrary: uriVL::NonMaximumSuppressor Class Reference
uriVL::NonMaximumSuppressor Class Reference
Implementation of the NonMaximumSuppressor class.
#include <NonMaximumSuppressor.h>
Public Member Functions
NonMaximumSuppressor (void)
Creates a NonMaximumSuppressor operator.
virtual ~NonMaximumSuppressor (void)
Destructor.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
VectorField * applyTo (const VectorField *vectIn)
Applies this operator to a VectorField, returns the result as a VectorField.
VectorField * applyTo (const VectorField *vectIn, const ImageRect *theRect)
Applies this operator to a VectorField within the rectangle specified and returns the result as a VectorField.
void applyInto (const VectorField *vectIn, VectorField *vectOut)
Applies this operator to a VectorField and writes the result into a second RasterImage received as parameter.
void applyInto (const VectorField *vectIn, const ImageRect *theRect, VectorField *vectOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Static Public Member Functions
static RasterImage * applyTo_st (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
static RasterImage * applyTo_st (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
static void applyInto_st (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
static void applyInto_st (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
static VectorField * applyTo_st (const VectorField *vectIn)
Applies this operator to a VectorField, returns the result as a VectorField.
static VectorField * applyTo_st (const VectorField *vectIn, const ImageRect *theRect)
Applies this operator to a VectorField within the rectangle specified and returns the result as a VectorField.
static void applyInto_st (const VectorField *vectIn, VectorField *vectOut)
Applies this operator to a VectorField and writes the result into a second RasterImage received as parameter.
static void applyInto_st (const VectorField *vectIn, const ImageRect *theRect, VectorField *vectOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Static Private Member Functions
static void applyInto_grayF_ (const RasterImage_gray_F *imgIn, const ImageRect *theRect, RasterImage_gray_F *imgOut)
Applies this operator to a RasterImage_gray_F within the rectangle specified and writes the result into the RasterImage_gray_F received as parameter.
static void applyInto_vectF_ (const VectorField_F *vectIn, const ImageRect *theRect, VectorField_F *vectOut)
Applies this operator to a VectorField_F within the rectangle specified and writes the result into the VectorField_F received as parameter.
Additional Inherited Members
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
Implementation of the NonMaximumSuppressor class.
This class is implemented as an instantiable static class. It is instantiable because it may be convenient at some point to case a NonMaximumSuppressor to an ImageOperator The nonmaximum suppressor eliminates (sets to zero) the pixels that are not ridge or peak pixels
Definition at line 40 of file NonMaximumSuppressor.h.
Constructor & Destructor Documentation
NonMaximumSuppressor::NonMaximumSuppressor (void)
Creates a NonMaximumSuppressor operator.
Definition at line 36 of file NonMaximumSuppressor.cpp.
         :       ImageOperator( )
 {
 }
NonMaximumSuppressor::~NonMaximumSuppressor (void) virtual
Destructor.
Definition at line 42 of file NonMaximumSuppressor.cpp.
 {}
Member Function Documentation
void NonMaximumSuppressor::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 67 of file NonMaximumSuppressor.cpp.
References applyInto_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by uriVL::EdgeDetector_Canny_F::applyInto().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     applyInto_st(imgIn, imgIn->getValidRect(), imgOut);
 }
void NonMaximumSuppressor::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 77 of file NonMaximumSuppressor.cpp.
References applyInto_st().
 {
     applyInto_st(imgIn, theRect, imgOut);
 }
void NonMaximumSuppressor::applyInto (const VectorField * vectIn, VectorField * vectOut)
Applies this operator to a VectorField and writes the result into a second RasterImage received as parameter.
Parameters
vectIn the RasterImage to which the operator is applied
vectOut the VectorField into which the output is written
Definition at line 244 of file NonMaximumSuppressor.cpp.
References applyInto_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     vectIn == NULL,
                     kNullRasterImageError,
                     "NULL input vector field passed as parameter");
     applyInto_st(vectIn, vectIn->getValidRect(), vectOut);
 }
void NonMaximumSuppressor::applyInto (const VectorField * vectIn, const ImageRect * theRect, VectorField * vectOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
vectIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 254 of file NonMaximumSuppressor.cpp.
References applyInto_st().
 {
     applyInto_st(vectIn, theRect, vectOut);
 }
void NonMaximumSuppressor::applyInto_grayF_ (const RasterImage_gray_F * imgIn, const ImageRect * theRect, RasterImage_gray_F * imgOut) static private
Applies this operator to a RasterImage_gray_F within the rectangle specified and writes the result into the RasterImage_gray_F received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Definition at line 381 of file NonMaximumSuppressor.cpp.
References FAIL_CONDITION, and uriVL::kNoCode.
Referenced by applyInto_st().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //                    iHigh = theRect->getBottom(),
 //                            jLow = theRect->getLeft(),
 //                                   jHigh = theRect->getRight();
 //     float   **inGray = imgIn->getShiftedGrayF2D();
 //     float   **outGray = imgOut->getShiftedGrayF2D();
     FAIL_CONDITION( true,
                     kNoCode,
                     "not open for business");
 }
void NonMaximumSuppressor::applyInto_st (const RasterImage * imgIn, RasterImage * imgOut) static
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Definition at line 149 of file NonMaximumSuppressor.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyInto(), applyInto_st(), and applyTo_st().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     applyInto_st(imgIn, imgIn->getValidRect(), imgOut);
 }
void NonMaximumSuppressor::applyInto_st (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) static
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Definition at line 159 of file NonMaximumSuppressor.cpp.
References applyInto_grayF_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
     //----------------------------------------------------------------
     //  STEP 0:         Test for null or invalid type parameters
     //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in NonMaximumSuppressor::applyInto");
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter");
     //----------------------------------------------------------------
     //  STEP 1:         Test for rectangle intersection
     //----------------------------------------------------------------
     //  determine the output rectangle that the input image can produce.
     ImageRect   *destRect = ImageRect::intersection(imgIn->getValidRect(), theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!imgOut->contains(destRect))
         imgOut->setBoundRect(destRect);
     //----------------------------------------------------------------
     //  STEP 2:         Check out the type of the input and output images
     //                          and call the appropriate function
     //----------------------------------------------------------------
     //  So far I only work with RasterImage_gray_F input and destination images.
     FAIL_CONDITION( (typeid(*imgIn) != typeid(uriVL::RasterImage_gray_F)) ,
                     kInvalidRasterType,
                     "NonMaximumSuppressor::applyInto only accepts RasterImage_gray_F images as input");
     FAIL_CONDITION( (typeid(*imgOut) != typeid(uriVL::RasterImage_gray_F)) ,
                     kInvalidRasterType,
                     "NonMaximumSuppressor::applyInto only accepts RasterImage_gray_F images as destination");
     applyInto_grayF_((RasterImage_gray_F *) imgIn, destRect, (RasterImage_gray_F *) imgOut);
     //----------------------------------------------------------------
     //  STEP 3:         Set rectangle
     //----------------------------------------------------------------
     //  Very important:  At the end of the computation, don't forget to set the
     //  output's valid data rectangle.  In "safe" mode, the library has no way to guess
     //  what the valid data rectangle should be and sets it to its minimum value... empty
     imgOut->setValidRect(destRect);
     //imgOut->setFloatRasterAsReference();
     //  ((RasterImage_gray_F *) imgOut)->setFloatConversionMode(floatConversionMode_);
     //----------------------------------------------------------------
     //  STEP 4:         Free temporary storage (if needed)
     //----------------------------------------------------------------
     delete destRect;
 }
void NonMaximumSuppressor::applyInto_st (const VectorField * vectIn, VectorField * vectOut) static
Applies this operator to a VectorField and writes the result into a second RasterImage received as parameter.
Parameters
vectIn the VectorField to which the operator is applied
vectOut the VectorField into which the output is written
Definition at line 302 of file NonMaximumSuppressor.cpp.
References applyInto_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     vectIn == NULL,
                     kNullRasterImageError,
                     "NULL input vector field passed as parameter");
     applyInto_st(vectIn, vectIn->getValidRect(), vectOut);
 }
void NonMaximumSuppressor::applyInto_st (const VectorField * vectIn, const ImageRect * theRect, VectorField * vectOut) static
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
vectIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 312 of file NonMaximumSuppressor.cpp.
References applyInto_vectF_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::forceRasterUpdate(), uriVL::DrawableObject2D::getValidRect(), uriVL::VectorField::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kInvalidRasterType, uriVL::kNullRectangleError, uriVL::kNullVectorFieldError, uriVL::ImageRect::removeAllAround(), uriVL::DrawableObject2D::setBoundRect(), uriVL::VectorField::setRasterAsReference(), and uriVL::DrawableObject2D::setValidRect().
 {
     //----------------------------------------------------------------
     //  STEP 0:         Test for null or invalid type parameters
     //----------------------------------------------------------------
     FAIL_CONDITION(     vectIn == NULL,
                     kNullVectorFieldError,
                     "NULL input vector field passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in NonMaximumSuppressor::applyInto");
     FAIL_CONDITION(     vectOut == NULL,
                     kNullVectorFieldError,
                     "NULL output vector field passed as parameter");
     //----------------------------------------------------------------
     //  STEP 1:         Test for rectangle intersection
     //----------------------------------------------------------------
     //  determine the output rectangle that the input image can produce.
     ImageRect   *inRect = new ImageRect(vectIn->getValidRect());
     inRect->removeAllAround(1);
     ImageRect   *destRect = ImageRect::intersection(inRect, theRect);
     delete inRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!vectOut->contains(destRect))
         vectOut->setBoundRect(destRect);
     //----------------------------------------------------------------
     //  STEP 2:         Check out the type of the input and output vector fields
     //                          and call the appropriate function
     //----------------------------------------------------------------
     //  So far I only work with VectorField_F as input and destination.
     FAIL_CONDITION( !vectIn->hasFloatRaster(),
                     kInvalidRasterType,
                     "NonMaximumSuppressor::applyInto only accepts VectorField_F as input");
     FAIL_CONDITION( !vectOut->hasFloatRaster(),
                     kInvalidRasterType,
                     "NonMaximumSuppressor::applyInto only accepts VectorField_F as destination");
     applyInto_vectF_((VectorField_F *) vectIn, destRect, (VectorField_F *) vectOut);
     //----------------------------------------------------------------
     //  STEP 3:         Set rectangle
     //----------------------------------------------------------------
     //  Very important:  At the end of the computation, don't forget to set the
     //  output's valid data rectangle.  In "safe" mode, the library has no way to guess
     //  what the valid data rectangle should be and sets it to its minimum value... empty
     vectOut->setValidRect(destRect);
     vectOut->setRasterAsReference();
     vectOut->forceRasterUpdate();
     //----------------------------------------------------------------
     //  STEP 4:         Free temporary storage (if needed)
     //----------------------------------------------------------------
     delete destRect;
 }
void NonMaximumSuppressor::applyInto_vectF_ (const VectorField_F * vectIn, const ImageRect * theRect, VectorField_F * vectOut) static private
Applies this operator to a VectorField_F within the rectangle specified and writes the result into the VectorField_F received as parameter.
Parameters
vectIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 402 of file NonMaximumSuppressor.cpp.
References uriVL::VectorField::computeNormAndPhase(), FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::VectorField::getNormAsRasterImage(), uriVL::VectorField::getPhaseAsRasterImage(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::kNoCode, kNormThreshold, PI, and uriVL::R_W_ACCESS.
Referenced by applyInto_st().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     const int   iLow  = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     //  Get a reference to the coordinate rasters of the input and output vector fields
     const float* const* vxIn = static_cast<const float* const*>(vectIn->getShiftedRasterX2D());
     const float* const* vyIn = static_cast<const float* const*>(vectIn->getShiftedRasterY2D());
     float   **vxOut = static_cast<float** >(vectOut->getShiftedRasterX2D(R_W_ACCESS)),
             **vyOut = static_cast<float** >(vectOut->getShiftedRasterY2D(R_W_ACCESS));
     //  Make sure that the norm and phase we have for the input vector field are up-to-date
     //  and then get a reference to these rasters.  Here I call "compute" first to get a bit
     //  of speedup in case both rasters need to be calculated (typically)
     vectIn->computeNormAndPhase();
     const RasterImage_gray_F* normImg = vectIn->getNormAsRasterImage();
         const RasterImage_gray_F* phaseImg = vectIn->getPhaseAsRasterImage();
     const float* const* normIn = normImg->getShiftedGrayF2D();
     const float* const* phaseIn = phaseImg->getShiftedGrayF2D();
     const float FOUR_DIV_PI = static_cast<float>(4.L / PI);
     int   gradDirIndex;
     float   dx, dy, normE1, normE2;
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             float   norm = normIn[i][j];
             float   phase = phaseIn[i][j];
             //  small values are directly eliminated
             if (norm < kNormThreshold)
             {
                 vxOut[i][j] = vyOut[i][j] = 0.f;
             }
             //  for the other ones, we determined whether the direction of
             //  the edge (perp. to the gradient) is predominantly vert. or hor.
             else
             {
                 gradDirIndex = 4 + static_cast<int>(FOUR_DIV_PI * phase);
                 switch(gradDirIndex)
                 {
                         //  [0, pi/4] or [-pi, -3pi/4]
                     case 0:
                     case 4:
                         dy = vyIn[i][j] / vxIn[i][j];
                         normE1 = dy * normIn[i-1][j+1] + (1.f - dy) * normIn[i][j+1];
                         if (norm > normE1)
{
                             normE2 = dy * normIn[i+1][j-1] + (1.f - dy) * normIn[i][j-1];
                             if (norm > normE2)
{
                                 vxOut[i][j] = vxIn[i][j];
                                 vyOut[i][j] = vyIn[i][j];
                             }
                             else
                                 vxOut[i][j] = vyOut[i][j] = 0.f;
                             break;
                         }
                         else
                             vxOut[i][j] = vyOut[i][j] = 0.f;
                         break;
                         //  [pi/4, pi/2] or [-3pi/4, -pi/2]
                     case 1:
                     case 5:
                         dx = vxIn[i][j] / vyIn[i][j];
                         normE1 = dx * normIn[i-1][j+1] + (1.f - dx) * normIn[i-1][j];
                         if (norm > normE1)
{
                             normE2 = dx * normIn[i+1][j-1] + (1.f - dx) * normIn[i+1][j];
                             if (norm > normE2)
{
                                 vxOut[i][j] = vxIn[i][j];
                                 vyOut[i][j] = vyIn[i][j];
                             }
                             else
                                 vxOut[i][j] = vyOut[i][j] = 0.f;
                             break;
                         }
                         else
                             vxOut[i][j] = vyOut[i][j] = 0.f;
                         break;
                         //  [pi/2, 3pi/4] or [-pi/2, -pi/4]
                     case 2:
                     case 6:
                         dx = -vxIn[i][j] / vyIn[i][j];
                         normE1 = dx * normIn[i-1][j-1] + (1.f - dx) * normIn[i-1][j];
                         if (norm > normE1)
{
                             normE2 = dx * normIn[i+1][j+1] + (1.f - dx) * normIn[i+1][j];
                             if (norm > normE2)
{
                                 vxOut[i][j] = vxIn[i][j];
                                 vyOut[i][j] = vyIn[i][j];
                             }
                             else
                                 vxOut[i][j] = vyOut[i][j] = 0.f;
                             break;
                         }
                         else
                             vxOut[i][j] = vyOut[i][j] = 0.f;
                         break;
                         //  [3pi/4, pi] or [pi/4, 0]
                     case 3:
                     case 7:
                         dy = -vyIn[i][j] / vxIn[i][j];
                         normE1 = dy * normIn[i-1][j-1] + (1.f - dy) * normIn[i][j-1];
                         if (norm > normE1)
{
                             normE2 = dy * normIn[i+1][j+1] + (1.f - dy) * normIn[i][j+1];
                             if (norm > normE2)
{
                                 vxOut[i][j] = vxIn[i][j];
                                 vyOut[i][j] = vyIn[i][j];
                             }
                             else
                                 vxOut[i][j] = vyOut[i][j] = 0.f;
                             break;
                         }
                         else
                             vxOut[i][j] = vyOut[i][j] = 0.f;
                         break;
                     default:
                         FAIL_CONDITION( true,
                                         kNoCode,
                                         "should not happen");
                         break;
                 }
             }
         }
     }
 }
RasterImage * NonMaximumSuppressor::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 52 of file NonMaximumSuppressor.cpp.
References applyTo_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     return applyTo_st(imgIn, imgIn->getValidRect());
 }
RasterImage * NonMaximumSuppressor::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 61 of file NonMaximumSuppressor.cpp.
References applyTo_st().
 {
     return applyTo_st(imgIn, theRect);
 }
VectorField * NonMaximumSuppressor::applyTo (const VectorField * vectIn)
Applies this operator to a VectorField, returns the result as a VectorField.
The VectorField returned is of the same base type as the input field. For example, if vectIn was VectorField_F, then so is the vector field returned.
Parameters
vectIn the VectorField to which the operator is applied
Returns
the VectorField obtained by applying the operator to vectIn
Definition at line 229 of file NonMaximumSuppressor.cpp.
References applyTo_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullVectorFieldError.
 {
     FAIL_CONDITION(     vectIn == NULL,
                     kNullVectorFieldError,
                     "NULL input vector field passed as parameter");
     return applyTo_st(vectIn, vectIn->getValidRect());
 }
VectorField * NonMaximumSuppressor::applyTo (const VectorField * vectIn, const ImageRect * theRect)
Applies this operator to a VectorField within the rectangle specified and returns the result as a VectorField.
The VectorField returned is of the same base type as the input field. For example, if vectIn was VectorField_F, then so is the vector field returned.
Parameters
vectIn the VectorField to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the VectorField obtained by applying the operator to imgIn
Definition at line 238 of file NonMaximumSuppressor.cpp.
References applyTo_st().
 {
     return applyTo_st(vectIn, theRect);
 }
RasterImage * NonMaximumSuppressor::applyTo_st (const RasterImage * imgIn) static
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Definition at line 89 of file NonMaximumSuppressor.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo(), and applyTo_st().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     return applyTo_st(imgIn, imgIn->getValidRect());
 }
RasterImage * NonMaximumSuppressor::applyTo_st (const RasterImage * imgIn, const ImageRect * theRect) static
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the RasterImage obtained by applying the operator to imgIn
Definition at line 98 of file NonMaximumSuppressor.cpp.
References applyInto_st(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kGrayRaster, uriVL::kNoCode, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     ImageRect   *destRect = ImageRect::intersection(imgIn->getValidRect(), theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     RasterImage *imgOut = NULL;
     switch (imgIn->getBaseRasterType())
     {
         case kGrayRaster:
             imgOut = new RasterImage_gray_F(destRect);
             break;
         case kRGB24Raster:
             FAIL_CONDITION(     true,
                             kNoCode,
                             "image type not suported yet by NonMaximumSuppressor");
             //            imgOut = new RasterImage_RGB_F(destRect);
             break;
         case kRGBa32Raster:
             FAIL_CONDITION(     true,
                             kNoCode,
                             "image type not suported yet by NonMaximumSuppressor");
             //            imgOut = new RasterImage_RGBa_F(destRect);
             break;
         default:
             FAIL_CONDITION(     true,
                             kNoCode,
                             "image type not suported yet by NonMaximumSuppressor");
             break;
     }
     applyInto_st(imgIn, theRect, imgOut);
     delete destRect;
     return imgOut;
 }
VectorField * NonMaximumSuppressor::applyTo_st (const VectorField * vectIn) static
Applies this operator to a VectorField, returns the result as a VectorField.
The VectorField returned is of the same base type as the input field. For example, if vectIn was VectorField_F, then so is the vector field returned.
Parameters
vectIn the VectorField to which the operator is applied
Returns
the VectorField obtained by applying the operator to vectIn
Definition at line 265 of file NonMaximumSuppressor.cpp.
References applyTo_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullVectorFieldError.
 {
     FAIL_CONDITION(     vectIn == NULL,
                     kNullVectorFieldError,
                     "NULL input vector field passed as parameter");
     return applyTo_st(vectIn, vectIn->getValidRect());
 }
VectorField * NonMaximumSuppressor::applyTo_st (const VectorField * vectIn, const ImageRect * theRect) static
Applies this operator to a VectorField within the rectangle specified and returns the result as a VectorField.
The VectorField returned is of the same base type as the input field. For example, if vectIn was VectorField_F, then so is the vector field returned.
Parameters
vectIn the VectorField to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the VectorField obtained by applying the operator to imgIn
Definition at line 274 of file NonMaximumSuppressor.cpp.
References applyInto_st(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::VectorField::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, and uriVL::kNullVectorFieldError.
 {
     FAIL_CONDITION(     vectIn == NULL,
                     kNullVectorFieldError,
                     "NULL input vector field passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     ImageRect   *destRect = ImageRect::intersection(vectIn->getValidRect(), theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     VectorField *vectOut = NULL;
     if (vectIn->hasFloatRaster())
         vectOut = new VectorField_F(destRect);
     else
         vectOut = new VectorField_I(destRect);
     applyInto_st(vectIn, theRect, vectOut);
     delete destRect;
     return vectOut;
 }
The documentation for this class was generated from the following files:
NonMaximumSuppressor.h
NonMaximumSuppressor.cpp