URIVisionLibrary: uriVL::StereoMatchRecord Class Reference
uriVL::StereoMatchRecord Class Reference
A StereoMatchRecord stores a matching point and matching score resulting from a call to a stereo matcher.
#include <StereoMatchRecord.h>
Public Member Functions
StereoMatchRecord (void)
Default constructor.
StereoMatchRecord (StereoMatchRecord *disp)
Cloner constructor.
StereoMatchRecord (ImagePoint *disp, float conf, bool isLeft)
Constructor.
StereoMatchRecord (int dx, int dy, float conf, bool isLeft)
Constructor.
~StereoMatchRecord (void)
Destructor.
bool isLeftMatch (void)
Indicates whether the disparity stored works from the left to the right.
bool isRectifiedStereoMatch (void)
Indicates whether this match is computed for a rectified stereo system.
void setIsRectifiedStereoMatch (bool isRect)
Sets the flag indicating whether this match is computed for a rectified stereo system.
bool isSubpixelMatch (void)
Indicates whether the match computed uses integers of floating point (subpixel) numbers.
void setIsSubpixelMatch (bool isSubpixel)
Sets the flag indicating whether this is a subpixel disparity record.
void copy (StereoMatchRecord *disp)
Copies into this object the data from the one received as parameter.
float getScore (void)
Returns the score of the best match found.
ImagePoint * getBestMatch (void)
Returns the location of the best match.
void setScore (float score)
Sets the score.
void setBestMatch (int x, int y)
Sets the coordinates of the best match.
void setBestMatch (ImagePoint *bestMatch)
Sets the coordinates of the best match.
Protected Member Functions
StereoMatchRecord (const StereoMatchRecord &theObj)
Copy Constructor.
const StereoMatchRecord & operator= (const StereoMatchRecord &theObj)
Copy operator.
Protected Attributes
ImagePoint * bestMatch_
Stores the best match found.
float score_
Matching confidence, in [0, 1].
bool isSubpixelMatch_
Indicates whether the stereo match was calculated with subpixel accuracy.
bool isLeftMatch_
True if this object stores a point in the left image.
bool isRectifiedStereoMatch_
Indicates whether this disparity is computed for a rectified stereo system.
Detailed Description
A StereoMatchRecord stores a matching point and matching score resulting from a call to a stereo matcher.
Definition at line 30 of file StereoMatchRecord.h.
Constructor & Destructor Documentation
StereoMatchRecord::StereoMatchRecord (void)
Default constructor.
Should only be used by subclasses that don't need to allocate the disparity point
Definition at line 21 of file StereoMatchRecord.cpp.
                 :       bestMatch_(new ImagePoint(0, 0)),
                         score_(0.f),
                         isSubpixelMatch_(false),
                         isLeftMatch_(false),
                         isRectifiedStereoMatch_(false)
 {
 }
StereoMatchRecord::StereoMatchRecord (StereoMatchRecord * disp)
Cloner constructor.
Parameters
disp disparity object to clone
Definition at line 30 of file StereoMatchRecord.cpp.
                 :       bestMatch_(new ImagePoint(disp->bestMatch_)),
                         score_(disp->score_),
                         isSubpixelMatch_(disp->isSubpixelMatch_),
                         isLeftMatch_(disp->isLeftMatch_),
                         isRectifiedStereoMatch_(disp->isRectifiedStereoMatch_)
 {
 }
StereoMatchRecord::StereoMatchRecord (ImagePoint * disp, float conf, bool isLeft)
Constructor.
Allocates a stereo disparity with a confidence.
Parameters
disp disparity
conf confidence
isLeft true if this match was computed in the left image (right to left stereo match)
Definition at line 39 of file StereoMatchRecord.cpp.
                 :       bestMatch_(new ImagePoint(bestMatch)),
                         score_(score),
                         isSubpixelMatch_(false),
                         isLeftMatch_(isLeft),
                         isRectifiedStereoMatch_(false)
 {
 }
StereoMatchRecord::StereoMatchRecord (int dx, int dy, float conf, bool isLeft)
Constructor.
Allocates a disparity with a confidence.
Parameters
dx horizontal component of disparity
dy vertical coordinate of disparity
conf confidence
isLeft true if this match was computed in the left image (right to left stereo match)
Definition at line 48 of file StereoMatchRecord.cpp.
                 :       bestMatch_(new ImagePoint(x, y)),
                         score_(score),
                         isSubpixelMatch_(false),
                         isLeftMatch_(isLeft),
                         isRectifiedStereoMatch_(false)
 {
 }
StereoMatchRecord::~StereoMatchRecord (void)
Destructor.
Definition at line 71 of file StereoMatchRecord.cpp.
References bestMatch_.
 {
         delete bestMatch_;
 }
StereoMatchRecord::StereoMatchRecord (const StereoMatchRecord & theObj) protected
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 58 of file StereoMatchRecord.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       bestMatch_(NULL),
                         score_(0.f),
                         isSubpixelMatch_(false),
                         isLeftMatch_(false),
                         isRectifiedStereoMatch_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoMatchRecord copy constructor not implemented");
 }
Member Function Documentation
void uriVL::StereoMatchRecord::copy (StereoMatchRecord * disp)
Copies into this object the data from the one received as parameter.
Parameters
the object to copy data from
ImagePoint * StereoMatchRecord::getBestMatch (void)
Returns the location of the best match.
Definition at line 96 of file StereoMatchRecord.cpp.
References bestMatch_.
Referenced by uriVL::StereoMatcher::disparity().
 {
     return bestMatch_;
 }
float StereoMatchRecord::getScore (void)
Returns the score of the best match found.
Definition at line 90 of file StereoMatchRecord.cpp.
References score_.
Referenced by uriVL::StereoMatcher::disparity().
 {
     return score_;
 }
bool StereoMatchRecord::isLeftMatch (void)
Indicates whether the disparity stored works from the left to the right.
Returns
true if the disparity stored works from the left to the right
Definition at line 149 of file StereoMatchRecord.cpp.
References isLeftMatch_.
 {
     return isLeftMatch_;
 }
bool StereoMatchRecord::isRectifiedStereoMatch (void)
Indicates whether this match is computed for a rectified stereo system.
Returns
true if this match was computed for a rectified stereo system
Definition at line 139 of file StereoMatchRecord.cpp.
References isRectifiedStereoMatch_.
 {
     return isRectifiedStereoMatch_;
 }
bool StereoMatchRecord::isSubpixelMatch (void)
Indicates whether the match computed uses integers of floating point (subpixel) numbers.
Returns
true if the stereo matcher computes subpixel disparity
Definition at line 129 of file StereoMatchRecord.cpp.
References isSubpixelMatch_.
 {
     return isSubpixelMatch_;
 }
const StereoMatchRecord & StereoMatchRecord::operator= (const StereoMatchRecord & theObj) protected
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 76 of file StereoMatchRecord.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoMatchRecord copy operator not implemented");
         return *this;
 }
void StereoMatchRecord::setBestMatch (int x, int y)
Sets the coordinates of the best match.
Parameters
x new x coordinate for this record's best match point
y new y coordinate for this record's best match point
Definition at line 107 of file StereoMatchRecord.cpp.
References bestMatch_, and uriVL::ImagePoint::setCoordinates().
Referenced by uriVL::StereoMatcher::match(), and uriVL::RectifiedStereoMatcher_corr::match_().
 {
     if (bestMatch_ == NULL)
         bestMatch_ = new ImagePoint(x, y);
     else
         bestMatch_->setCoordinates(x, y);
 }
void StereoMatchRecord::setBestMatch (ImagePoint * bestMatch)
Sets the coordinates of the best match.
Parameters
bestMatch new best match point for this record
Definition at line 116 of file StereoMatchRecord.cpp.
References bestMatch_, FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kNullImagePointError, and uriVL::ImagePoint::setCoordinates().
 {
     FAIL_CONDITION( bestMatch == NULL,
                     kNullImagePointError,
                     "null ImagePoint passed to StereoMatchRecord::setBestMatch");
     if (bestMatch_ == NULL)
         bestMatch_ = new ImagePoint(bestMatch);
     else
         bestMatch_->setCoordinates(bestMatch->getX(), bestMatch->getY());
 }
void StereoMatchRecord::setIsRectifiedStereoMatch (bool isRect)
Sets the flag indicating whether this match is computed for a rectified stereo system.
Parameters
isSubpixel true if this match is computed for a rectified stereo pair
Definition at line 144 of file StereoMatchRecord.cpp.
References isRectifiedStereoMatch_.
 {
     isRectifiedStereoMatch_ = isRect;
 }
void StereoMatchRecord::setIsSubpixelMatch (bool isSubpixel)
Sets the flag indicating whether this is a subpixel disparity record.
Typically set by a StereoMatcher object.
Parameters
isSubpixel true if this disparity can return a floating point, subpixel disparity value
Definition at line 134 of file StereoMatchRecord.cpp.
References isSubpixelMatch_.
 {
     isSubpixelMatch_ = isSubpixel;
 }
void StereoMatchRecord::setScore (float score)
Sets the score.
Parameters
score the new score for this record
Definition at line 101 of file StereoMatchRecord.cpp.
References score_.
Referenced by uriVL::StereoMatcher::match(), and uriVL::RectifiedStereoMatcher_corr::match_().
 {
     score_ = score;
 }
Member Data Documentation
ImagePoint* uriVL::StereoMatchRecord::bestMatch_ protected
Stores the best match found.
Definition at line 141 of file StereoMatchRecord.h.
Referenced by getBestMatch(), setBestMatch(), and ~StereoMatchRecord().
bool uriVL::StereoMatchRecord::isLeftMatch_ protected
True if this object stores a point in the left image.
Definition at line 156 of file StereoMatchRecord.h.
Referenced by isLeftMatch().
bool uriVL::StereoMatchRecord::isRectifiedStereoMatch_ protected
Indicates whether this disparity is computed for a rectified stereo system.
Definition at line 160 of file StereoMatchRecord.h.
Referenced by isRectifiedStereoMatch(), and setIsRectifiedStereoMatch().
bool uriVL::StereoMatchRecord::isSubpixelMatch_ protected
Indicates whether the stereo match was calculated with subpixel accuracy.
Definition at line 151 of file StereoMatchRecord.h.
Referenced by isSubpixelMatch(), and setIsSubpixelMatch().
float uriVL::StereoMatchRecord::score_ protected
Matching confidence, in [0, 1].
Definition at line 145 of file StereoMatchRecord.h.
Referenced by getScore(), and setScore().
The documentation for this class was generated from the following files:
StereoMatchRecord.h
StereoMatchRecord.cpp