URIVisionLibrary: uriVL::VectorField_F Class Reference
uriVL::VectorField_F Class Reference
VectorField_F class.
#include <VectorField_F.h>
Public Member Functions
VectorField_F (int theNbRows, int theNbCols)
Initializes a float vector field at the specified dimensions.
VectorField_F (const ImageRect *theRect)
Initializes a double vector field at the specified dimensions.
VectorField_F (VectorField *theField)
Cloner Constructor.
VectorField_F (int theNbRows, int theNbCols, const float *theRastX, const float *theRastY)
Initializes a float vector field at the specified dimensions and values.
~VectorField_F (void)
Destructor.
void copyInto (VectorField *out) const
Copies this vector field into the one received as parameter.
void copyInto (VectorField *out, const ImageRect *theRect) const
Copies this vector field into the one received as parameter using the specified copy rectangle.
const void * getRasterX (void) const
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
void * getRasterX (ReadWriteStatus rw)
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
const void * getRasterY (void) const
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
void * getRasterY (ReadWriteStatus rw)
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
const void * getRasterX2D (void) const
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
void * getRasterX2D (ReadWriteStatus rw)
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
const void * getRasterY2D (void) const
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
void * getRasterY2D (ReadWriteStatus rw)
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
const void * getShiftedRasterX2D (void) const
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
void * getShiftedRasterX2D (ReadWriteStatus rw)
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
const void * getShiftedRasterY2D (void) const
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
void * getShiftedRasterY2D (ReadWriteStatus rw)
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
void getMinMax (float *theMinX, float *theMaxX, float *theMinY, float *theMaxY) const
Calculates the min and max values of the vector field along its X and Y directions.
void getMinMaxX (float *theMinX, float *theMaxX) const
Calculates the min and max values of the vector field along its X direction.
void getMinMaxY (float *theMinY, float *theMaxY) const
Calculates the min and max values of the vector field along its Y direction.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Public Member Functions inherited from uriVL::VectorField
virtual ~VectorField (void)
Destructor.
void copyInto (VectorField *out) const
Copies this vector field into the one received as parameter.
virtual const RasterImage_gray_F * getNormAsRasterImage (void) const
Returns the vector field's norm as gray-level raster image.
virtual RasterImage_gray_F * getNormAsRasterImage (ReadWriteStatus rw)
Returns the vector field's norm as gray-level raster image.
virtual const RasterImage_gray_F * getNormSquaredAsRasterImage (void) const
Returns the vector field's norm squared as gray-level raster image.
virtual RasterImage_gray_F * getNormSquaredAsRasterImage (ReadWriteStatus rw)
Returns the vector field's norm squared as gray-level raster image.
virtual const RasterImage_gray_F * getPhaseAsRasterImage (void) const
Returns the vector field's phase as gray-level raster image.
virtual RasterImage_gray_F * getPhaseAsRasterImage (ReadWriteStatus rw)
Returns the vector field's phase as gray-level raster image.
virtual void getNormAsRasterImage (RasterImage_gray *normOut)
Returns the vector field's norm as gray-level raster image.
virtual void getNormSquaredAsRasterImage (RasterImage_gray *norm2Out)
Returns the vector field's norm squared as gray-level raster image.
virtual void getPhaseAsRasterImage (RasterImage_gray *phaseOut)
Returns the vector field's phase as gray-level raster image.
virtual void getNormAndPhaseAsRasterImages (RasterImage_gray *normOut, RasterImage_gray *phaseOut)
Returns the vector field's norm and phase as gray-level raster images.
virtual void getNormSquaredAndPhaseAsRasterImages (RasterImage_gray *norm2Out, RasterImage_gray *phaseOut)
Returns the vector field's squared norm and phase as gray-level raster images.
void computeNorm (void) const
Computes vector field's norm as a gray-level raster image and stores it as an instance variable.
void computeNormSquared (void) const
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
void computePhase (void) const
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
void computeNormAndPhase (void) const
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
void computeNormSquaredAndPhase (void)
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
void setVectResolution (int nPts)
Sets the resolution of the vector field's rendering (distance between needles in pixel)
bool hasFloatRaster (void) const
true if the vector field has a float raster
void forceRasterUpdate (void)
Forces an update of the raster (for rendering)
void setRasterAsReference (void)
Sets this vector field's base raster as the reference.
void setNormAndPhaseAsReference (void)
Sets this vector field's norm and phase as the reference (fails either one was NULL)
void setNormSquaredAndPhaseAsReference (void)
Sets this vector field's norm squared and phase as the reference (fails either one was NULL)
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this vector field has been modified.
void setReferenceHasChanged (void) const
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Private Member Functions
VectorField_F (const VectorField_F &theField)
Copy Constructor.
const VectorField_F & operator= (const VectorField_F &theField)
Copy operator.
void computeNorm_ (RasterImage_gray_F *norm) const
Computes vector field's norm as a gray-level raster image.
void computeNormSquared_ (RasterImage_gray_F *normSq) const
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
void computePhase_ (RasterImage_gray_F *phase) const
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
void computeNormAndPhase_ (RasterImage_gray_F *norm, RasterImage_gray_F *phase) const
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
void computeNormSquaredAndPhase_ (RasterImage_gray_F *normSq, RasterImage_gray_F *phase) const
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
void renderNeedles_ (int nVectRes, float scaleVect) const
Render the vector field as a regularly sampled array of needles.
void prepareVectFieldForRendering_ (int nVectRes, float &scaleVect, float &normMax) const
Computes the shifting and scaling factors to properly render the vectors as needles the next time render_ is called.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D base rasters.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base rasters.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted rasters.
void translateShiftedRaster2D_ (int rowShoft, int colShift)
Translates the 2D shifted base rasters by the specified amount.
void deleteShiftedRaster2D_ (void)
Deletes the 2D shifted base raster.
void initializeRasters_ (const float *rasterX, const float *rasterY)
Initializes this VectorField's rasters with the arrays received as parameters.
Private Attributes
float * vx_
stores the x component of the vector field
float * vy_
stores the y component of the vector field
float ** vx2D_
2D array mapped over vx_
float ** vy2D_
2D array mapped over vy_
float ** shiftedVx2D_
"shifted" 2D array mapped over vx_.
float ** shiftedVy2D_
"shifted" 2D array mapped over vyu_.
Friends
class VectorField
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions inherited from uriVL::VectorField
VectorField (int theNbRows, int theNbCols, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions and values.
VectorField (const ImageRect *theRect, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions.
VectorField (const ImageRect &theRect, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions.
VectorField (const VectorField *theField, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Copy Constructor.
VectorField (const VectorField &theField)
Copy Constructor.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Static Protected Attributes inherited from uriVL::VectorField
static float NEEDLE_DOT_RADIUS = 2.f
Radius of the circular dot used to render a vertex.
Detailed Description
VectorField_F class.
A VectorField_F is a "float" vector field defined over a 2d array. I haven't quite made up my mind on the opacity of this class. For the moment, the getRaster method returns the data's master pointer. In the future I may decide to clone the data and return the clone's master pointer. In any case, this would not change the class's API.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 37 of file VectorField_F.h.
Constructor & Destructor Documentation
VectorField_F::VectorField_F (int theNbRows, int theNbCols)
Initializes a float vector field at the specified dimensions.
Parameters
nbRows number of rows of the vector field
nbCols number of columns of vector field
Definition at line 35 of file VectorField_F.cpp.
References allocateRaster2D_(), and allocateShiftedRaster2D_().
                         :       VectorField(theNbRows, theNbCols, true),
                                 //
                                 vx_(NULL),
                                 vy_(NULL),
                                 vx2D_(NULL),
                                 vy2D_(NULL),
                                 shiftedVx2D_(NULL),
                                 shiftedVy2D_(NULL)
 {
     allocateRaster2D_(theNbRows, theNbCols);
     allocateShiftedRaster2D_(theNbRows, theNbCols, 0, 0);
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField_F constructor");
 }
VectorField_F::VectorField_F (const ImageRect * theRect)
Initializes a double vector field at the specified dimensions.
Parameters
theRect rectangle at which to allocate the vector field
Definition at line 62 of file VectorField_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), and uriVL::ImageRect::getWidth().
                         :       VectorField(theRect, true),
                                 //
                                 vx_(NULL),
                                 vy_(NULL),
                                 vx2D_(NULL),
                                 vy2D_(NULL),
                                 shiftedVx2D_(NULL),
                                 shiftedVy2D_(NULL)
 {
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(), theRect->getTop(), theRect->getLeft());
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField_F constructor");
 }
VectorField_F::VectorField_F (VectorField * theField)
Cloner Constructor.
Initializes a float vector field at the dimensions and values of the VectorField received as parameter.
Parameters
theField pointer to the VectorField object to clone
Definition at line 137 of file VectorField_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::VectorField::copyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), and uriVL::kNullVectorFieldError.
                         :       VectorField(theField, true),
                                 //
                                 vx_(NULL),
                                 vy_(NULL),
                                 vx2D_(NULL),
                                 vy2D_(NULL),
                                 shiftedVx2D_(NULL),
                                 shiftedVy2D_(NULL)
 {
     FAIL_CONDITION(     theField == NULL,
                     kNullVectorFieldError,
                     "NULL VectorField_F passed as argument to VectorField_F clone constructor");
     allocateRaster2D_(theField->getHeight(), theField->getWidth());
     allocateShiftedRaster2D_(theField->getHeight(), theField->getWidth(), theField->getTop(), theField->getLeft());
     try
         {
                 theField->copyInto(this);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by VectorField_F constructor");
                 throw e;
         }
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField_F constructor");
 }
VectorField_F::VectorField_F (int theNbRows, int theNbCols, const float * theRastX, const float * theRastY)
Initializes a float vector field at the specified dimensions and values.
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
theRastX X component for the VectorField
theRastY Y component for the VectorField
Definition at line 92 of file VectorField_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), initializeRasters_(), uriVL::kMemoryCopyError, uriVL::kNullRasterError, and uriVL::DrawableObject2D::setValidRect().
                         :       VectorField(theNbRows, theNbCols, true),
                                 //
                                 vx_(NULL),
                                 vy_(NULL),
                                 vx2D_(NULL),
                                 vy2D_(NULL),
                                 shiftedVx2D_(NULL),
                                 shiftedVy2D_(NULL)
 {
     FAIL_CONDITION(     (theRastX == NULL) || (theRastY==NULL),
                     kNullRasterError,
                     "NULL array passed as argument to VectorField_F constructor");
     allocateRaster2D_(theNbRows, theNbCols);
     allocateShiftedRaster2D_(theNbRows, theNbCols, 0, 0);
     try
         {
                 initializeRasters_(theRastX, theRastY);
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "Memory copy error in VectorField_F constructor");
         }
         setValidRect(getBoundRect());
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField_F constructor");
 }
VectorField_F::~VectorField_F (void)
Destructor.
Definition at line 215 of file VectorField_F.cpp.
References deleteRaster2D_(), and deleteShiftedRaster2D_().
 {
     deleteShiftedRaster2D_();
     deleteRaster2D_( );
 }
VectorField_F::VectorField_F (const VectorField_F & theField) private
Copy Constructor.
Disabled
Parameters
theField reference to the VectorField object to copy
Definition at line 179 of file VectorField_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), copyInto(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), and uriVL::DrawableObject2D::getWidth().
                         :       VectorField(theField),
                                 //
                                 vx_(NULL),
                                 vy_(NULL),
                                 vx2D_(NULL),
                                 vy2D_(NULL),
                                 shiftedVx2D_(NULL),
                                 shiftedVy2D_(NULL)
 {
     allocateRaster2D_(theField.getHeight(), theField.getWidth());
     allocateShiftedRaster2D_(theField.getHeight(), theField.getWidth(), theField.getTop(), theField.getLeft());
     try
         {
                 theField.copyInto(this);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by VectorField_F constructor");
                 throw e;
         }
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField_F constructor");
 }
Member Function Documentation
void VectorField_F::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D base rasters.
Parameters
nbRows number of rows of the field
nbCols number of columns of the field
Implements uriVL::VectorField.
Definition at line 750 of file VectorField_F.cpp.
References FAIL_CONDITION, uriVL::kRasterAllocationFailure, vx2D_, vx_, vy2D_, and vy_.
Referenced by VectorField_F().
 {
     long    nbPixels = nbRows*nbCols;
     vx_ = vy_ = NULL;
     vx2D_ = vy2D_ = NULL;
     vx_ = new float[nbPixels];
     FAIL_CONDITION(     vx_ == NULL,
                     kRasterAllocationFailure,
                     "float vector raster allocation failed");
     vy_ = new float[nbPixels];
     FAIL_CONDITION(     vy_ == NULL,
                     kRasterAllocationFailure,
                     "float vector raster allocation failed");
     vx2D_ = new float*[nbRows];
     FAIL_CONDITION(     vx2D_ == NULL,
                     kRasterAllocationFailure,
                     "2D float vector raster allocation failed");
     vy2D_ = new float*[nbRows];
     FAIL_CONDITION(     vy2D_ == NULL,
                     kRasterAllocationFailure,
                     "2D float vector raster allocation failed");
     vx2D_[0] = vx_;
     vy2D_[0] = vy_;
     for (int i = 0; i < nbRows-1; i++)
     {
         vx2D_[i+1] = vx2D_[i] + nbCols;
         vy2D_[i+1] = vy2D_[i] + nbCols;
     }
 }
void VectorField_F::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted rasters.
Parameters
jLow X coordinate of the image's origin
iLow Y coordinate of the image's origin
nbRows number of rows of the field
nbCols number of columns of the field
Implements uriVL::VectorField.
Definition at line 804 of file VectorField_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::kRasterAllocationFailure, shiftedVx2D_, shiftedVy2D_, vx_, and vy_.
Referenced by VectorField_F().
 {
     //  if the vector field has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
     {
         const int   iHigh = iLow + nbRows - 1;
         shiftedVx2D_ = shiftedVy2D_ = NULL;
         shiftedVx2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedVx2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D float vector raster allocation failed");
         shiftedVy2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedVy2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D float vector raster allocation failed");
         shiftedVx2D_ -= iLow;
         shiftedVy2D_ -= iLow;
         //
         shiftedVx2D_[iLow] = vx_ - jLow;
         shiftedVy2D_[iLow] = vy_ - jLow;
         for (int i = iLow; i < iHigh; i++)
         {
             shiftedVx2D_[i+1] = shiftedVx2D_[i] + nbCols;
             shiftedVy2D_[i+1] = shiftedVy2D_[i] + nbCols;
         }
     }
     else
     {
         //      I do this to unearth parts of the library where I access the rasters
         //      directly rather than through the access functions.
         //      shiftedVx2D_ = vx2D_;
         //      shiftedVy2D_ = vy2D_;
         shiftedVx2D_ = NULL;
         shiftedVy2D_ = NULL;
     }
 }
void VectorField_F::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implements uriVL::DrawableObject2D.
Definition at line 612 of file VectorField_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void VectorField_F::computeNorm_ (RasterImage_gray_F * norm) const private virtual
Computes vector field's norm as a gray-level raster image.
Parameters
norm pointer to the vector field's private norm variable
Implements uriVL::VectorField.
Definition at line 406 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::R_W_ACCESS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float*const* flNorm = norm->getShiftedGrayF2D(R_W_ACCESS);
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             flNorm[i][j] = sqrtf(vx[i][j]*vx[i][j] + vy[i][j]*vy[i][j]);
 }
void VectorField_F::computeNormAndPhase_ (RasterImage_gray_F * norm, RasterImage_gray_F * phase) const private virtual
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
Parameters
norm pointer to the vector field's private norm variable
phase pointer to the vector field's private phase variable
Implements uriVL::VectorField.
Definition at line 463 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::R_W_ACCESS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float*const* flNorm = norm->getShiftedGrayF2D(R_W_ACCESS);
     float*const* flPhase = phase->getShiftedGrayF2D(R_W_ACCESS);
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     for (int i=iLow; i<=iHigh; i++)
     {
             for (int j=jLow; j<=jHigh; j++)
         {
             flNorm[i][j] = sqrtf(vx[i][j]*vx[i][j] + vy[i][j]*vy[i][j]);
             flPhase[i][j] = atan2f(vy[i][j], vx[i][j]);
         }
         }
 }
void VectorField_F::computeNormSquared_ (RasterImage_gray_F * normSq) const private virtual
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
Parameters
normSq pointer to the vector field's private norm squared variable
Implements uriVL::VectorField.
Definition at line 425 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::R_W_ACCESS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float*const* flNorm2 = normSq->getShiftedGrayF2D(R_W_ACCESS);
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             flNorm2[i][j] = vx[i][j]*vx[i][j] + vy[i][j]*vy[i][j];
 }
void VectorField_F::computeNormSquaredAndPhase_ (RasterImage_gray_F * normSq, RasterImage_gray_F * phase) const private virtual
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
Parameters
normSq pointer to the vector field's private norm squared variable
phase pointer to the vector field's private phase variable
Implements uriVL::VectorField.
Definition at line 488 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::R_W_ACCESS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float*const* flPhase = phase->getShiftedGrayF2D(R_W_ACCESS);
     float*const* flNorm2 = normSq->getShiftedGrayF2D(R_W_ACCESS);
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     for (int i=iLow; i<=iHigh; i++)
     {
             for (int j=jLow; j<=jHigh; j++)
         {
             flNorm2[i][j] = vx[i][j]*vx[i][j] + vy[i][j]*vy[i][j];
             flPhase[i][j] = atan2f(vy[i][j], vx[i][j]);
         }
         }
 }
void VectorField_F::computePhase_ (RasterImage_gray_F * phase) const private virtual
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
Parameters
phase pointer to the vector field's private phase variable
Implements uriVL::VectorField.
Definition at line 444 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::R_W_ACCESS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float*const* flPhase = phase->getShiftedGrayF2D(R_W_ACCESS);
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             flPhase[i][j] = atan2f(vy[i][j], vx[i][j]);
 }
void VectorField_F::copyInto (VectorField * out) const
Copies this vector field into the one received as parameter.
If the destination vector field does not have the same dimensions as this vector field (source), its rasters are reallocated. Only the data within the validRect_ rectangle need to be be copied. The bouding rectangle and valid data rectangle of the destination are equal to that of the source.
Parameters
vectOut destination vector field
Definition at line 239 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by VectorField_F().
 {
     copyInto(vectOut, getValidRect());
 }
void VectorField_F::copyInto (VectorField * out, const ImageRect * theRect) const virtual
Copies this vector field into the one received as parameter using the specified copy rectangle.
The call fails if the rectangle specified is not contained within the source.
Parameters
vectOut destination vector field
theRect region of the vector field to copy
Reimplemented from uriVL::VectorField.
Definition at line 244 of file VectorField_F.cpp.
References uriVL::VectorField::copyInto(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::VectorField::hasFloatRaster(), uriVL::VectorField::setReferenceHasChanged(), shiftedVx2D_, and shiftedVy2D_.
 {
     //  All the rectangle testing and resizing is done in the parent class' function
     VectorField::copyInto(vectOut, theRect);
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     if (vectOut->hasFloatRaster())
     {
         float   **xOut = (float** ) (((VectorField_F *) vectOut)->getShiftedRasterX2D());
         float   **yOut = (float** ) (((VectorField_F *) vectOut)->getShiftedRasterY2D());
         for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow; j<=jHigh; j++)
             {
                 xOut[i][j] = shiftedVx2D_[i][j];
                 yOut[i][j] = shiftedVy2D_[i][j];
             }
                 }
     }
     else
     {
         int** xOut = (int** ) (((VectorField_I *) vectOut)->getShiftedRasterX2D());
         int** yOut = (int** ) (((VectorField_I *) vectOut)->getShiftedRasterY2D());
         for (int i=iLow; i<=iHigh; i++)
                 {
             for (int j=jLow; j<=jHigh; j++)
             {
                 xOut[i][j] = int(shiftedVx2D_[i][j]);
                 yOut[i][j] = int(shiftedVy2D_[i][j]);
             }
                 }
     }
         vectOut->setReferenceHasChanged();
 }
void VectorField_F::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base rasters.
Implements uriVL::VectorField.
Definition at line 786 of file VectorField_F.cpp.
References vx2D_, vx_, vy2D_, and vy_.
Referenced by ~VectorField_F().
 {
     if (vx2D_ != NULL)
         delete []vx2D_;
     if (vy2D_ != NULL)
         delete []vy2D_;
     if (vx_ != NULL)
         delete []vx_;
     if (vy_ != NULL)
         delete []vy_;
     vx_ = vy_ = NULL;
     vx2D_ = vy2D_ = NULL;
 }
void VectorField_F::deleteShiftedRaster2D_ (void) private virtual
Deletes the 2D shifted base raster.
Implements uriVL::VectorField.
Definition at line 867 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), shiftedVx2D_, and shiftedVy2D_.
Referenced by ~VectorField_F().
 {
     if ((getTop() != 0) || (getLeft() != 0))
     {
         int   iLow  = getTop();
         if (shiftedVx2D_ != NULL)
         {
             shiftedVx2D_ += iLow;
             delete []shiftedVx2D_;
         }
         if (shiftedVy2D_ != NULL)
         {
             shiftedVy2D_ += iLow;
             delete []shiftedVy2D_;
         }
     }
     shiftedVx2D_ = shiftedVy2D_ = NULL;
 }
void VectorField_F::getMinMax (float * theMinX, float * theMaxX, float * theMinY, float * theMaxY) const
Calculates the min and max values of the vector field along its X and Y directions.
Parameters
theMinX pointer to min value along X direction
theMaxX pointer to max value along X direction
theMinY pointer to min value along Y direction
theMaxY pointer to max value along Y direction
Definition at line 518 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::DrawableObject2D::getValidRect().
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     float       myMinX = vx[iLow][jLow], myMaxX = myMinX;
     float       myMinY = vy[iLow][jLow], myMaxY = myMinY;
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
             if (vx[i][j] < myMinX)
                 myMinX = vx[i][j];
             if (vx[i][j] > myMaxX)
                 myMaxX = vx[i][j];
             //
             if (vy[i][j] < myMinY)
                 myMinY = vy[i][j];
             if (vy[i][j] > myMaxY)
                 myMaxY = vy[i][j];
         }
     *theMinX = myMinX;
     *theMaxX = myMaxX;
     *theMinY = myMinY;
     *theMaxY = myMaxY;
 }
void VectorField_F::getMinMaxX (float * theMinX, float * theMaxX) const
Calculates the min and max values of the vector field along its X direction.
Parameters
theMinX pointer to min value along X direction
theMaxX pointer to max value along X direction
Definition at line 551 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterX2D(), uriVL::ImageRect::getTop(), and uriVL::DrawableObject2D::getValidRect().
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     const float* const* vx = static_cast<const float* const*>(getShiftedRasterX2D());
     float       myMinX = vx[iLow][jLow], myMaxX = myMinX;
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
             if (vx[i][j] < myMinX)
                 myMinX = vx[i][j];
             if (vx[i][j] > myMaxX)
                 myMaxX = vx[i][j];
         }
     *theMinX = myMinX;
     *theMaxX = myMaxX;
 }
void VectorField_F::getMinMaxY (float * theMinY, float * theMaxY) const
Calculates the min and max values of the vector field along its Y direction.
Parameters
theMinY pointer to min value along Y direction
theMaxY pointer to max value along Y direction
Definition at line 574 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::DrawableObject2D::getValidRect().
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     const float* const* vy = static_cast<const float* const*>(getShiftedRasterY2D());
     float       myMinY = vy[iLow][jLow], myMaxY = myMinY;
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
             if (vy[i][j] < myMinY)
                 myMinY = vy[i][j];
             if (vy[i][j] > myMaxY)
                 myMaxY = vy[i][j];
         }
     *theMinY = myMinY;
     *theMaxY = myMaxY;
 }
const void * VectorField_F::getRasterX (void) const virtual
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
Returns
the vector field's X component's 1D base raster
Implements uriVL::VectorField.
Definition at line 295 of file VectorField_F.cpp.
References vx_.
 {
     return (void *) vx_;
 }
void * VectorField_F::getRasterX (ReadWriteStatus rw) virtual
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 1D base raster
Implements uriVL::VectorField.
Definition at line 300 of file VectorField_F.cpp.
References uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), and vx_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     return (void *) vx_;
 }
const void * VectorField_F::getRasterX2D (void) const virtual
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
Returns
the vector field's X component's 2D base raster
Implements uriVL::VectorField.
Definition at line 319 of file VectorField_F.cpp.
References vx2D_.
 {
     return (void *) vx2D_;
 }
void * VectorField_F::getRasterX2D (ReadWriteStatus rw) virtual
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 2D base raster
Implements uriVL::VectorField.
Definition at line 324 of file VectorField_F.cpp.
References uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), and vx2D_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     return (void *) vx2D_;
 }
const void * VectorField_F::getRasterY (void) const virtual
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
Returns
the vector field's Y component's 1D base raster
Implements uriVL::VectorField.
Definition at line 307 of file VectorField_F.cpp.
References vy_.
 {
     return (void *) vy_;
 }
void * VectorField_F::getRasterY (ReadWriteStatus rw) virtual
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 1D base raster
Implements uriVL::VectorField.
Definition at line 312 of file VectorField_F.cpp.
References uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), and vy_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     return (void *) vy_;
 }
const void * VectorField_F::getRasterY2D (void) const virtual
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
Returns
the vector field's Y component's 2D base raster
Implements uriVL::VectorField.
Definition at line 331 of file VectorField_F.cpp.
References vy2D_.
 {
     return (void *) vy2D_;
 }
void * VectorField_F::getRasterY2D (ReadWriteStatus rw) virtual
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 2D base raster
Implements uriVL::VectorField.
Definition at line 336 of file VectorField_F.cpp.
References uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), and vy2D_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     return (void *) vy2D_;
 }
const void * VectorField_F::getShiftedRasterX2D (void) const virtual
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
Returns
the vector field's X component's 2D "shifted" raster
Implements uriVL::VectorField.
Definition at line 343 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), shiftedVx2D_, and vx2D_.
Referenced by uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ActiveContourDetector_balloon::calculateEdgeForce_(), computeNorm_(), computeNormAndPhase_(), computeNormSquared_(), computeNormSquaredAndPhase_(), computePhase_(), copyInto(), CreateImageAndField(), getMinMax(), getMinMaxX(), prepareVectFieldForRendering_(), and renderNeedles_().
 {
     //  if the vector field has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
         return (void *) shiftedVx2D_;
     else
         return (void *) vx2D_;
 }
void * VectorField_F::getShiftedRasterX2D (ReadWriteStatus rw) virtual
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 2D "shifted" raster
Implements uriVL::VectorField.
Definition at line 355 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), shiftedVx2D_, and vx2D_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     //  if the vector field has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
         return (void *) shiftedVx2D_;
     else
         return (void *) vx2D_;
 }
const void * VectorField_F::getShiftedRasterY2D (void) const virtual
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
Returns
the vector field's Y component's 2D "shifted" raster
Implements uriVL::VectorField.
Definition at line 370 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), shiftedVy2D_, and vy2D_.
Referenced by uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ActiveContourDetector_balloon::calculateEdgeForce_(), computeNorm_(), computeNormAndPhase_(), computeNormSquared_(), computeNormSquaredAndPhase_(), computePhase_(), copyInto(), CreateImageAndField(), getMinMax(), getMinMaxY(), prepareVectFieldForRendering_(), and renderNeedles_().
 {
     //  if the vector field has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
         return (void *) shiftedVy2D_;
     else
         return (void *) vy2D_;
 }
void * VectorField_F::getShiftedRasterY2D (ReadWriteStatus rw) virtual
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 2D "shifted" raster
Implements uriVL::VectorField.
Definition at line 382 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::VectorField::setRasterAsReference(), uriVL::VectorField::setReferenceHasChanged(), shiftedVy2D_, and vy2D_.
 {
         setRasterAsReference();
         setReferenceHasChanged();
     //  if the vector field has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
         return (void *) shiftedVy2D_;
     else
         return (void *) vy2D_;
 }
void VectorField_F::initializeRasters_ (const float * rasterX, const float * rasterY) private
Initializes this VectorField's rasters with the arrays received as parameters.
Parameters
rasterX values for the vector field's x components
rasterY values for the vector field's y components
Definition at line 735 of file VectorField_F.cpp.
References uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), vx_, and vy_.
Referenced by VectorField_F().
 {
     int   nbRows = getHeight(),
             nbCols = getWidth();
     unsigned long  nbBytes = nbRows * nbCols * sizeof(float);
     memcpy(vx_, theRastX, nbBytes);
     memcpy(vy_, theRastY, nbBytes);
 cout << "First 100 elements of the vfield:" << endl;
 for (int i=0; i<100; i++)
         cout << "(" << vx_[i] << ", " << vy_[i] << "),  ";
 cout << endl;
 }
const VectorField_F & VectorField_F::operator= (const VectorField_F & theField) private
Copy operator.
Disabled
Parameters
theField reference to the VectorField object to copy
Definition at line 229 of file VectorField_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "VectorField copy operator not implemented");
         return *this;
 }
void VectorField_F::prepareVectFieldForRendering_ (int nVectRes, float & scaleVect, float & normMax) const private virtual
Computes the shifting and scaling factors to properly render the vectors as needles the next time render_ is called.
Parameters
nVectRes resolution of vector field's rendering
scaleVect scale factor for vectors' needles (gets updated)
normMax max value of the vector field's norm (gets updated)
Implements uriVL::VectorField.
Definition at line 681 of file VectorField_F.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and kLengthNeedles.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float       vx, vy, vVal;
     const float* const* vx2D = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy2D = static_cast<const float* const*>(getShiftedRasterY2D());
     //  Determine the maximum Euclidean norm of the vector field over a
     //  uniformly-spaced grid of image points
     normMax = 0.f;
     int   iRes = (iHigh-iLow+1) - (nVectRes)*((iHigh-iLow+1)/nVectRes - 1),
           jRes = (jHigh-jLow+1) - (nVectRes)*((jHigh-jLow+1)/nVectRes - 1);
     int   iFirst = iLow + iRes/2,
           jFirst = jLow + jRes/2;
     for (int i = iFirst; i <= iHigh; i += nVectRes)
     {
         for (int j = jFirst; j <= jHigh; j += nVectRes)
         {
             vx = vx2D[i][j];
             vy = vy2D[i][j];
             vVal = vx * vx + vy * vy;
             if (vVal > normMax)
                 normMax = vVal;
         }
     }
     //  Knowing the maximum length of the vector over the grid, we can compute a scale
     //  factor for proper rendering.
     if (normMax > 0.f)
     {
         normMax = sqrtf(normMax);
         scaleVect = kLengthNeedles * nVectRes / normMax;
     }
     else
         scaleVect = 0.f;
 }
void VectorField_F::renderNeedles_ (int nVectRes, float scaleVect) const private virtual
Render the vector field as a regularly sampled array of needles.
Parameters
nVectRes resolution of vector field's rendering
scaleVect scale factor for vectors' needles
Implements uriVL::VectorField.
Definition at line 628 of file VectorField_F.cpp.
References uriVL::fillCircularDot(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), getShiftedRasterX2D(), getShiftedRasterY2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), and uriVL::VectorField::NEEDLE_DOT_RADIUS.
 {
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
     float       vx, vy;
     const float* const* vx2D = static_cast<const float* const*>(getShiftedRasterX2D());
     const float* const* vy2D = static_cast<const float* const*>(getShiftedRasterY2D());
     int   iRes = (iHigh-iLow+1) - (nVectRes)*((iHigh-iLow+1)/nVectRes - 1),
           jRes = (jHigh-jLow+1) - (nVectRes)*((jHigh-jLow+1)/nVectRes - 1);
     int   iFirst = iLow + iRes/2,
           jFirst = jLow + jRes/2;
     glTranslatef(jFirst - getLeft(), iFirst - getTop(), 0.f);
     for (int i = iFirst; i <= iHigh; i += nVectRes)
     {
         //      save the row's leftmost point
         glPushMatrix();
         for (int j = jFirst; j <= jHigh; j += nVectRes)
         {
             //  draw the vector proper as a line segment
             vx = vx2D[i][j] * scaleVect;
             vy = vy2D[i][j] * scaleVect;
             glBegin(GL_LINES);
             glVertex3f(0.f, 0.f, 0);
             glVertex3f(vx, vy, 0);
             glEnd();
             //  draw a small disk
                         glPushMatrix();
                                 glScalef(NEEDLE_DOT_RADIUS, NEEDLE_DOT_RADIUS, 1.f);
                                 uriVL::fillCircularDot();
                         glPopMatrix();
             //  Move to the next rendering spot
             glTranslatef(nVectRes, 0.f, 0.f);
         }
         //      return to the row's leftmost point
         glPopMatrix();
         //      and go down to the next row
         glTranslatef(0.f, nVectRes, 0.f);
     }
 }
void VectorField_F::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implements uriVL::DrawableObject2D.
Definition at line 604 of file VectorField_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void VectorField_F::translateShiftedRaster2D_ (int rowShoft, int colShift) private virtual
Translates the 2D shifted base rasters by the specified amount.
Parameters
rowShift displacement of the row index
colShift displacement of the column index
Implements uriVL::VectorField.
Definition at line 848 of file VectorField_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getBottom(), uriVL::DrawableObject2D::getTop(), uriVL::kFunctionNotImplemented, shiftedVx2D_, and shiftedVy2D_.
 {
     int   iLow  = getTop(),
           iHigh = getBottom();
     for (int i = iLow; i < iHigh; i++)
     {
         shiftedVx2D_[i+1] -= colShift;
         shiftedVy2D_[i+1] -= colShift;
     }
     shiftedVx2D_ -= rowShift;
     shiftedVy2D_ -= rowShift;
     FAIL_CONDITION(     true,
                     kFunctionNotImplemented,
                     "Function temporarily out of  service");
 }
Friends And Related Function Documentation
friend class VectorField friend
Definition at line 353 of file VectorField_F.h.
Member Data Documentation
float** uriVL::VectorField_F::shiftedVx2D_ private
"shifted" 2D array mapped over vx_.
Uses the true values of the indices as given by the bounding and valid data rectangles
Definition at line 240 of file VectorField_F.h.
Referenced by allocateShiftedRaster2D_(), copyInto(), deleteShiftedRaster2D_(), getShiftedRasterX2D(), and translateShiftedRaster2D_().
float** uriVL::VectorField_F::shiftedVy2D_ private
"shifted" 2D array mapped over vyu_.
Uses the true values of the indices as given by the bounding and valid data rectangles
Definition at line 245 of file VectorField_F.h.
Referenced by allocateShiftedRaster2D_(), copyInto(), deleteShiftedRaster2D_(), getShiftedRasterY2D(), and translateShiftedRaster2D_().
float** uriVL::VectorField_F::vx2D_ private
2D array mapped over vx_
Definition at line 231 of file VectorField_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getRasterX2D(), and getShiftedRasterX2D().
float* uriVL::VectorField_F::vx_ private
stores the x component of the vector field
Definition at line 223 of file VectorField_F.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), getRasterX(), and initializeRasters_().
float** uriVL::VectorField_F::vy2D_ private
2D array mapped over vy_
Definition at line 235 of file VectorField_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getRasterY2D(), and getShiftedRasterY2D().
float* uriVL::VectorField_F::vy_ private
stores the y component of the vector field
Definition at line 227 of file VectorField_F.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), getRasterY(), and initializeRasters_().
The documentation for this class was generated from the following files:
VectorField_F.h
VectorField_F.cpp