URIVisionLibrary: uriVL::ReferenceFrame3D Class Reference
uriVL::ReferenceFrame3D Class Reference
A ReferenceFrame3D is the object relative to which any Entity3D is defined.
#include <ReferenceFrame3D.h>
Public Member Functions
ReferenceFrame3D (const ReferenceFrame3D *theRef)
Constructor.
ReferenceFrame3D (const RigidTransformation3D *theTransf)
Constructor.
ReferenceFrame3D (const ReferenceFrame3D *theRef, const RigidTransformation3D *theTransf)
Constructor.
const ReferenceFrame3D * getParentFrame (void)
Returns the reference frame relative to which the 3D entity is defined.
void notifyUseAsReference (const Entity3D *theEntity) const
Called by a 3D entity that reports itself to this reference frame to tell it that it uses it as a reference.
void notifyReleaseReference (const Entity3D *theEntity) const
Called by a 3D entity that reports itself to this reference frame to tell it that it does not use it anymore as a reference.
void setTransformation (const RigidTransformation3D *thePose)
Sets a new transformation to this frame from the one it is defined relative to.
void applyTransformation (const RigidTransformation3D *theTransf)
Applies a rigid transformation to this reference frame, to change it pose relative to the reference frame it is defined relative to.
void applyTransformation (const Rotation3D *theRot)
Applies a rotation to this reference frame, to change its pose relative to the reference frame it is defined relative to.
void applyTransformation (const Translation3D *theTrans)
Applies a translation to this reference frame, to change its pose relative to the reference frame it is defined relative to.
const RigidTransformation3D * getTransformation (ReferenceFrameShortcut ref) const
Calculates and returns the rigid transformation from this reference frame to the one given by the shortcut.
const RigidTransformation3D * getTransformation (const ReferenceFrame3D *theFrame) const
Calculates and returns the rigid transformation from this reference frame to the one received as parameter.
Static Public Member Functions
static const RigidTransformation3D * getTransformation (const ReferenceFrame3D *startFrame, const ReferenceFrame3D *endFrame)
Calculates and returns the transformation from this reference frame to the one received as parameter.
static const ReferenceFrame3D * getGlobalReferenceFrame (void)
Returns the root "global" reference frame.
static void setViewerFrame (const ReferenceFrame3D *viewerFrame)
Sets the current viewer reference frame.
static bool deleteFrame (ReferenceFrame3D *ref)
Attempts to delete the ReferenceFrame3D object passed as parameter but first check if the ReferenceFrame3D still has Entity3D objects attached to it.
Private Member Functions
~ReferenceFrame3D (void)
Destructor.
ReferenceFrame3D (void)
Private constructor for the root (global) reference frame.
ReferenceFrame3D (const ReferenceFrame3D &theRef)
Copy Constructor.
const ReferenceFrame3D & operator= (const ReferenceFrame3D &theRef)
Copy Operator.
Private Attributes
int id_
A ReferenceFrame3D has its own unique id.
const ReferenceFrame3D * ref_
The reference frame relative to which this one is defined.
RigidTransformation3D * transf_
The rigid transformation between this reference frame and the one it is
defined relative to.
std::list< const Entity3D * > entitiesReferenced_
List of all 3D entities that are defined relative to this.
Static Private Attributes
static int frameCounter_ = 0
Counter for all the ReferenceFrame3D objects in the application.
static ReferenceFrame3D * rootFrame_ = new ReferenceFrame3D()
the root (global) reference frame
static const ReferenceFrame3D * viewerFrame_ = NULL
Current viewer frame.
Detailed Description
A ReferenceFrame3D is the object relative to which any Entity3D is defined.
The notion of ReferenceFrame3D is closely related to that of RigidTransformation3D. Any ReferenceFrame3D is defined relative to another ReferenceFrame3D, down to the "world" ReferenceFrame3D, which is a static variable of this class. A ReferenceFrame3D is related to its reference ReferenceFrame3D through a RigidTransformation3D object.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 52 of file ReferenceFrame3D.h.
Constructor & Destructor Documentation
ReferenceFrame3D::ReferenceFrame3D (const ReferenceFrame3D * theRef)
Constructor.
Creates a 3D reference frame defined relative to an external reference frame with which it initially coincides.
Parameters
theRef external frame relative to which this one is defined
Definition at line 50 of file ReferenceFrame3D.cpp.
References frameCounter_.
         :   id_(frameCounter_),
             ref_(theRef),
             transf_(NULL),
             entitiesReferenced_(list<const Entity3D*>())
 {
     frameCounter_++;
 }
ReferenceFrame3D::ReferenceFrame3D (const RigidTransformation3D * theTransf)
Constructor.
Creates a 3D reference frame defined relative to the global reference frame.
Parameters
theTransf rigid transformation from the global reference frame to this one
Definition at line 59 of file ReferenceFrame3D.cpp.
References frameCounter_.
         :   id_(frameCounter_),
             ref_(rootFrame_),
             transf_(new RigidTransformation3D(theTransf)),
             entitiesReferenced_(list<const Entity3D*>())
 {
     frameCounter_++;
 }
ReferenceFrame3D::ReferenceFrame3D (const ReferenceFrame3D * theRef, const RigidTransformation3D * theTransf)
Constructor.
Creates a 3D reference frame defined relative to an external reference frame.
Parameters
theRef external frame relative to which this one is defined
theTransf rigid transformation from the external frame to this one
Definition at line 68 of file ReferenceFrame3D.cpp.
References frameCounter_.
         :   id_(frameCounter_),
             ref_(theRef),
             transf_(new RigidTransformation3D(theTransf)),
             entitiesReferenced_(list<const Entity3D*>())
 {
     frameCounter_++;
 }
ReferenceFrame3D::~ReferenceFrame3D (void) private
Destructor.
Definition at line 107 of file ReferenceFrame3D.cpp.
 {
 }
ReferenceFrame3D::ReferenceFrame3D (void) private
Private constructor for the root (global) reference frame.
Definition at line 39 of file ReferenceFrame3D.cpp.
References frameCounter_.
         :   id_(0),
             ref_(rootFrame_),
             transf_(NULL),
             entitiesReferenced_(list<const Entity3D*>())
 {
     frameCounter_++;
 }
ReferenceFrame3D::ReferenceFrame3D (const ReferenceFrame3D & theRef) private
Copy Constructor.
Disabled
Parameters
theRef external frame relative to copy
Definition at line 77 of file ReferenceFrame3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   id_(0),
             ref_(NULL),
             transf_(NULL),
             entitiesReferenced_(list<const Entity3D*>())
 {
     FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "ReferenceFrame3D copy constructor is disabled");;
 }
Member Function Documentation
void ReferenceFrame3D::applyTransformation (const RigidTransformation3D * theTransf)
Applies a rigid transformation to this reference frame, to change it pose relative to the reference frame it is defined relative to.
The transformation to apply must be defined relative to the current/moving frame.
Parameters
theTransf the transformation to apply to this reference frame
Definition at line 150 of file ReferenceFrame3D.cpp.
References transf_.
 {
     if (transf_ != NULL) {
         ((RigidTransformation3D*) transf_)->postComposeTransformation(theTransf);
     }
     else {
         transf_ = new RigidTransformation3D(theTransf);
     }
 }
void ReferenceFrame3D::applyTransformation (const Rotation3D * theRot)
Applies a rotation to this reference frame, to change its pose relative to the reference frame it is defined relative to.
The rotation to apply must be defined relative to the current/moving frame.
Parameters
theRot the rotation to apply to this reference frame
Definition at line 160 of file ReferenceFrame3D.cpp.
References transf_.
 {
     if (transf_ != NULL) {
         ((RigidTransformation3D*) transf_)->postComposeTransformation(theRot);
     }
     else {
         transf_ = new RigidTransformation3D(theRot);
     }
 }
void ReferenceFrame3D::applyTransformation (const Translation3D * theTrans)
Applies a translation to this reference frame, to change its pose relative to the reference frame it is defined relative to.
The translation to apply must be defined relative to the current/moving frame.
Parameters
theTrans the translation to apply to this reference frame
Definition at line 170 of file ReferenceFrame3D.cpp.
References transf_.
 {
     if (transf_ != NULL) {
         ((RigidTransformation3D*) transf_)->postComposeTransformation(theTrans);
     }
     else {
         transf_ = new RigidTransformation3D(theTrans);
     }
 }
bool ReferenceFrame3D::deleteFrame (ReferenceFrame3D * ref) static
Attempts to delete the ReferenceFrame3D object passed as parameter but first check if the ReferenceFrame3D still has Entity3D objects attached to it.
If it does, the deletion attempt fails and the function returns falsel otherwise the object is properly freed and the function returnd true;
Parameters
ref the ReferenceFrame3D object we want to delete
Returns
true of the cal succeeded, false otherwise
Definition at line 96 of file ReferenceFrame3D.cpp.
References entitiesReferenced_.
 {
     if (ref->entitiesReferenced_.empty()) {
         delete ref;
         return true;
     }
     else
         return false;
 }
const ReferenceFrame3D * ReferenceFrame3D::getGlobalReferenceFrame (void) static
Returns the root "global" reference frame.
Returns
the root "global" reference frame
Definition at line 228 of file ReferenceFrame3D.cpp.
References rootFrame_.
 {
     return rootFrame_;
 }
const ReferenceFrame3D * ReferenceFrame3D::getParentFrame (void)
Returns the reference frame relative to which the 3D entity is defined.
Definition at line 119 of file ReferenceFrame3D.cpp.
References ref_.
 {
     return ref_;
 }
const RigidTransformation3D * ReferenceFrame3D::getTransformation (ReferenceFrameShortcut ref) const
Calculates and returns the rigid transformation from this reference frame to the one given by the shortcut.
Parameters
ref indicates the frame relative to which we want the transformation
Returns
the rigid trasnformation from this reference frame to the one identified by the shortcut
Definition at line 180 of file ReferenceFrame3D.cpp.
References uriVL::PARENT_FRAME, rootFrame_, transf_, uriVL::VIEWER_FRAME, viewerFrame_, and uriVL::WORLD_FRAME.
Referenced by getTransformation().
 {
         switch (ref)
         {
                 case WORLD_FRAME:
                         return getTransformation(rootFrame_, this);
                         break;
                 case VIEWER_FRAME:
                         return getTransformation(viewerFrame_, this);
                         break;
                 case PARENT_FRAME:
                 default:
                         return transf_;
                         break;
         }
 }
const RigidTransformation3D * ReferenceFrame3D::getTransformation (const ReferenceFrame3D * theFrame) const
Calculates and returns the rigid transformation from this reference frame to the one received as parameter.
Returns NULL if such a transformation cannot be calculated.
Parameters
theFrame the frame whose pose relative to this frame must be calculated
Returns
the rigid trasnformation from this reference frame to theFrame
Definition at line 200 of file ReferenceFrame3D.cpp.
References getTransformation().
 {
     return getTransformation(theFrame, this);
 }
const RigidTransformation3D * ReferenceFrame3D::getTransformation (const ReferenceFrame3D * startFrame, const ReferenceFrame3D * endFrame) static
Calculates and returns the transformation from this reference frame to the one received as parameter.
Returns NULL if such a transformation cannot be calculated.
Parameters
startFrame the frame relative to which the pose is calculated
endFrame the frame whose pose relative to startFrame must be calculated
Returns
the rigid transformation from startFrame to endFrame
Definition at line 205 of file ReferenceFrame3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
         //      Build the descendance list from rootFrame_ to endFrame
         //      now start building the ascendance list from the start frame.  When we find an element that is
         //      on the previous list we stop and compute the complete transformation
     return NULL;
 }
void ReferenceFrame3D::notifyReleaseReference (const Entity3D * theEntity) const
Called by a 3D entity that reports itself to this reference frame to tell it that it does not use it anymore as a reference.
Parameters
theEntity Entity3D that reports not using this frame as reference anymore
Definition at line 129 of file ReferenceFrame3D.cpp.
References entitiesReferenced_.
Referenced by uriVL::Entity3D::setReferenceFrame(), and uriVL::Entity3D::~Entity3D().
 {
         entitiesReferenced_.remove(theEntity);
 }
void ReferenceFrame3D::notifyUseAsReference (const Entity3D * theEntity) const
Called by a 3D entity that reports itself to this reference frame to tell it that it uses it as a reference.
Parameters
theEntity Entity3D that reports using this frame as reference
Definition at line 124 of file ReferenceFrame3D.cpp.
References entitiesReferenced_.
Referenced by uriVL::Entity3D::Entity3D(), uriVL::Point3D::Point3D(), and uriVL::Entity3D::setReferenceFrame().
 {
     entitiesReferenced_.push_back(theEntity);
 }
const ReferenceFrame3D & ReferenceFrame3D::operator= (const ReferenceFrame3D & theRef) private
Copy Operator.
Disabled
Parameters
theRef external frame relative to copy
Definition at line 88 of file ReferenceFrame3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "ReferenceFrame3D copy operator is disabled");;
         return *this;
 }
void ReferenceFrame3D::setTransformation (const RigidTransformation3D * thePose)
Sets a new transformation to this frame from the one it is defined relative to.
Parameters
thePose new rigid transformation between this reference frame and the one it is defined relative to
Definition at line 143 of file ReferenceFrame3D.cpp.
References transf_.
 {
     if (transf_ != NULL)
         delete transf_;
     transf_ = new RigidTransformation3D(thePose);
 }
void ReferenceFrame3D::setViewerFrame (const ReferenceFrame3D * viewerFrame) static
Sets the current viewer reference frame.
Parameters
the current viewer frame for the application
Definition at line 233 of file ReferenceFrame3D.cpp.
References viewerFrame_, and viewerFrameLock.
 {
         pthread_mutex_lock(viewerFrameLock);
         viewerFrame_ = viewerFrame;
         pthread_mutex_unlock(viewerFrameLock);
 }
Member Data Documentation
std::list<const Entity3D*> uriVL::ReferenceFrame3D::entitiesReferenced_ mutable private
List of all 3D entities that are defined relative to this.
Definition at line 214 of file ReferenceFrame3D.h.
Referenced by deleteFrame(), notifyReleaseReference(), and notifyUseAsReference().
int ReferenceFrame3D::frameCounter_ = 0 static private
Counter for all the ReferenceFrame3D objects in the application.
Used to generate id_ for a new ReferenceFrame3D object
Definition at line 220 of file ReferenceFrame3D.h.
Referenced by ReferenceFrame3D().
int uriVL::ReferenceFrame3D::id_ private
A ReferenceFrame3D has its own unique id.
Definition at line 197 of file ReferenceFrame3D.h.
const ReferenceFrame3D* uriVL::ReferenceFrame3D::ref_ private
The reference frame relative to which this one is defined.
Definition at line 202 of file ReferenceFrame3D.h.
Referenced by getParentFrame().
ReferenceFrame3D * ReferenceFrame3D::rootFrame_ = new ReferenceFrame3D() static private
the root (global) reference frame
Definition at line 225 of file ReferenceFrame3D.h.
Referenced by getGlobalReferenceFrame(), and getTransformation().
RigidTransformation3D* uriVL::ReferenceFrame3D::transf_ private
The rigid transformation between this reference frame and the one it is
defined relative to.
If this variable is NULL this corresponds to an identity transformation.
Definition at line 209 of file ReferenceFrame3D.h.
Referenced by applyTransformation(), getTransformation(), and setTransformation().
const ReferenceFrame3D * ReferenceFrame3D::viewerFrame_ = NULL static private
Current viewer frame.
At a given time, there can be only one viewer frame for the entire application. Access to this frame is protected by a mutex lock.
Definition at line 230 of file ReferenceFrame3D.h.
Referenced by getTransformation(), and setViewerFrame().
The documentation for this class was generated from the following files:
ReferenceFrame3D.h
ReferenceFrame3D.cpp