URIVisionLibrary: uriVL::Point3D Class Reference
uriVL::Point3D Class Reference
Implements the Point3D class.
#include <Point3D.h>
Public Member Functions
Point3D (double X, double Y, double Z, const ReferenceFrame3D *theRef)
Constructor.
Point3D (const double theXYZ[], const ReferenceFrame3D *theRef)
Constructor.
Point3D (const Point3D *thePt)
Clone constructor.
Point3D (double X, double Y, double Z)
Constructor.
Point3D (const double theXYZ[])
Constructor.
virtual ~Point3D (void)
Destructor.
const double getX (void) const
Returns the point's X coordinate.
const double getY (void) const
Returns the point's Y coordinate.
const double getZ (void) const
Returns the point's Z coordinate.
const double * getXYZ (void) const
Returns the point's coordinates vector.
void setPosition (const double XYZ[])
Assigns new x coordinate to the point.
void setPosition (double X, double Y, double Z)
Assigns new x coordinate to the point.
double distanceTo (const Point3D *p) const
Returns the distance between this point and the one received as parameter.
Public Member Functions inherited from uriVL::Entity3D
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Private Attributes
double XYZ_ [3]
The point's X, Y, and Z coordinates.
Additional Inherited Members
Protected Member Functions inherited from uriVL::Entity3D
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Detailed Description
Implements the Point3D class.
A Point3D object stores the 3D coordinates of a point relative to a given reference frame.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 42 of file Point3D.h.
Constructor & Destructor Documentation
Point3D::Point3D (double X, double Y, double Z, const ReferenceFrame3D * theRef)
Constructor.
Creates a 3D point in the reference frame received as parameter
Parameters
X X coordinate of the point
Y Y coordinate of the point
Z Z coordinate of the point
theRef the reference frame relative to which this point is defined
Definition at line 22 of file Point3D.cpp.
References uriVL::Entity3D::frame_, uriVL::ReferenceFrame3D::notifyUseAsReference(), and XYZ_.
 {
     frame_ = theRef;
     frame_->notifyUseAsReference(this);
     XYZ_[0] = X;
     XYZ_[1] = Y;
     XYZ_[2] = Z;
 }
Point3D::Point3D (const double theXYZ[], const ReferenceFrame3D * theRef)
Constructor.
Creates a 3D point in the reference frame received as parameter
Parameters
theXYZ coordinate array of the point
theRef the reference frame relative to which this point is defined
Definition at line 32 of file Point3D.cpp.
References XYZ_.
                         :       Entity3D(theRef)
 {
     for (int i=0; i<3; i++)
         XYZ_[i] = theXYZ[i];
 }
Point3D::Point3D (const Point3D * thePt)
Clone constructor.
Creates a clone of the Point3D object passed as parameter (including that point's reference frame).
Parameters
thePt pointer to the Point3D object to clone
Definition at line 39 of file Point3D.cpp.
References FAIL_CONDITION, uriVL::kNullEntity3D, and XYZ_.
                 :       Entity3D()
 {
     FAIL_CONDITION( thePt==NULL,
                     kNullEntity3D,
                     "Attempt to clone a NULL Point3D");
     for (int i=0; i<3; i++)
         XYZ_[i] = thePt->XYZ_[i];
 }
Point3D::Point3D (double X, double Y, double Z)
Constructor.
Creates a 3D point in the default reference frame. This constructor should only be used by an object that stores a set of points when all these points are defiend relative to the object's internal reference frame. It would be dangerous to send such an unreferenced point out "in the wild."
Parameters
theX X coordinate of the point
theY Y coordinate of the point
theZ Z coordinate of the point
Definition at line 50 of file Point3D.cpp.
References XYZ_.
 {
     XYZ_[0] = X;
     XYZ_[1] = Y;
     XYZ_[2] = Z;
 }
Point3D::Point3D (const double theXYZ[])
Constructor.
Creates a 3D point in the default reference frame. This constructor should only be used by an object that stores a set of points when all these points are defiend relative to the object's internal reference frame. It would be dangerous to send such an unreferenced point out "in the wild."
Parameters
theXYZ coordinate array of the point
Definition at line 57 of file Point3D.cpp.
References XYZ_.
                 :       Entity3D()
 {
     for (int i=0; i<3; i++)
         XYZ_[i] = theXYZ[i];
 }
Point3D::~Point3D (void) virtual
Destructor.
Definition at line 64 of file Point3D.cpp.
 {
 }
Member Function Documentation
double Point3D::distanceTo (const Point3D * p) const
Returns the distance between this point and the one received as parameter.
Parameters
p the point to which the distance must be computed
Returns
the distnace between this point and p
Definition at line 102 of file Point3D.cpp.
References FAIL_CONDITION, uriVL::Entity3D::frame_, uriVL::kInvalidTransformation3D, uriVL::kNullEntity3D, and XYZ_.
Referenced by uriVL::VirtualPoint3D::distanceTo().
 {
     FAIL_CONDITION( p==NULL,
                     kNullEntity3D,
                     "Attempt to calculate distance to a NULL Point3D");
     double   pXYZ[3] = {p->XYZ_[0], p->XYZ_[1], p->XYZ_[2]};
     //  the code for computing the transformation matrix between two
     //  arbitrary reference frames does not exist yet
     if (frame_ != p->frame_)
     {
         FAIL_CONDITION( true,
                         kInvalidTransformation3D,
                         "cannot calculate transformation between arbitrary frames (yet)");
         //  something would happen to pXYZ
     }
     for (int i=0; i<3; i++)
         pXYZ[i] -= XYZ_[i];
     return double(sqrt(pXYZ[0]*pXYZ[0] + pXYZ[1]*pXYZ[1] + pXYZ[2]*pXYZ[2]));
 }
const double Point3D::getX (void) const
Returns the point's X coordinate.
Returns
X coordinate of the point
Definition at line 69 of file Point3D.cpp.
References XYZ_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::Camera::getImagePoint(), uriVL::VirtualPoint3D::getX(), and uriVL::VirtualPoint3D::render_().
 {
     return XYZ_[0];
 }
const double * Point3D::getXYZ (void) const
Returns the point's coordinates vector.
Returns
a pointer to the object's private coordinate vector.
Definition at line 84 of file Point3D.cpp.
References XYZ_.
Referenced by uriVL::VirtualPoint3D::getXYZ().
 {
     return XYZ_;
 }
const double Point3D::getY (void) const
Returns the point's Y coordinate.
Returns
Y coordinate of the point
Definition at line 74 of file Point3D.cpp.
References XYZ_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::Camera::getImagePoint(), uriVL::VirtualPoint3D::getY(), and uriVL::VirtualPoint3D::render_().
 {
     return XYZ_[1];
 }
const double Point3D::getZ (void) const
Returns the point's Z coordinate.
Returns
Z coordinate of the point
Definition at line 79 of file Point3D.cpp.
References XYZ_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::Camera::getImagePoint(), uriVL::VirtualPoint3D::getZ(), and uriVL::VirtualPoint3D::render_().
 {
     return XYZ_[2];
 }
void Point3D::setPosition (const double XYZ[])
Assigns new x coordinate to the point.
Parameters
XYZ new coordinate array for the 3D point
Definition at line 89 of file Point3D.cpp.
References XYZ_.
Referenced by uriVL::VirtualPoint3D::setPosition().
 {
     for (int i=0; i<3; i++)
         XYZ_[i] = XYZ[i];
 }
void Point3D::setPosition (double X, double Y, double Z)
Assigns new x coordinate to the point.
Parameters
X X coordinate of the point
Y Y coordinate of the point
Z Z coordinate of the point
Definition at line 95 of file Point3D.cpp.
References XYZ_.
 {
     XYZ_[0] = X;
     XYZ_[1] = Y;
     XYZ_[2] = Z;
 }
Member Data Documentation
double uriVL::Point3D::XYZ_[3] private
The point's X, Y, and Z coordinates.
Definition at line 151 of file Point3D.h.
Referenced by distanceTo(), getX(), getXYZ(), getY(), getZ(), Point3D(), and setPosition().
The documentation for this class was generated from the following files:
Point3D.h
Point3D.cpp