URIVisionLibrary: uriVL::ImageLaplacian_Gaussian_I Class Reference
uriVL::ImageLaplacian_Gaussian_I Class Reference
Image operator that computes the Laplacian of a raster image using a "Laplacian of Gaussian" filter.
#include <ColorImageLaplacian_Gaussian_I.h>
Public Member Functions
ImageLaplacian_Gaussian_I (double theScale)
Defines a Laplacian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
ImageLaplacian_Gaussian_I (int theWidth)
Defines a Laplacian Filter with a specified "radius".
~ImageLaplacian_Gaussian_I (void)
Destructor.
RasterImage * applyTo (RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
ImageLaplacian_Gaussian_I (double theScale)
Defines a Laplacian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
ImageLaplacian_Gaussian_I (int theWidth)
Defines a Laplacian Filter with a specified "radius".
virtual ~ImageLaplacian_Gaussian_I (void)
Destructor.
float getScale (void) const
Returns the scale of the operator.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::ImageLaplacian
~ImageLaplacian (void)
Destructor.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ImageLaplacian_Gaussian_I (const ImageLaplacian_Gaussian_I &obj)
Copy constructor (disabled)
const ImageLaplacian_Gaussian_I & operator= (const ImageLaplacian_Gaussian_I &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
void applyInto_3x3_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 3x3 Laplacian filter.
void applyInto_5x5_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 5x5 Laplacian filter.
void applyInto_7x7_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 7x7 Laplacian filter.
void applyInto_9x9_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 9x9 Laplacian filter.
void applyInto_11x11_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 11x11 Laplacian filter.
void applyInto_13x13_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 13x13 Laplacian filter.
void applyInto_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Function that implements a generic (width greater than 13) Laplacian filter.
Protected Member Functions inherited from uriVL::ImageLaplacian
ImageLaplacian (int theWidth, int theHeight, bool isIntOperator)
Constructor.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
Box (const Box &obj)
Copy constructor (disabled)
const Box & operator= (const Box &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
void applyInto_3x3_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 3x3 Laplacian filter.
void applyInto_5x5_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 5x5 Laplacian filter.
void applyInto_7x7_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 7x7 Laplacian filter.
void applyInto_9x9_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 9x9 Laplacian filter.
void applyInto_11x11_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 11x11 Laplacian filter.
void applyInto_13x13_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 13x13 Laplacian filter.
void applyInto_ (RasterImage *imgIn, ImageRect *theRect, RasterImage *imgOut)
Function that implements a generic (width greater than 13) Laplacian filter.
Private Attributes
double scale_
the scale sigma of this filter
int * iL_
Stores into a 1D array (radial distances squared) the filter's coefficients.
int iDenum_
denumerator by which to divide the weighted summation computed using the coefficients of iL_
Detailed Description
Image operator that computes the Laplacian of a raster image using a "Laplacian of Gaussian" filter.
This class has not been implemented yet
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file ColorImageLaplacian_Gaussian_I.h.
Constructor & Destructor Documentation
ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I (double theScale)
Defines a Laplacian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
Parameters
theScale scale parameter sigma of the 2D Laplacian filter
Definition at line 22 of file ColorImageLaplacian_Gaussian_I.cpp.
References initializeFilter_(), uriVL::ImageOperator::isIntegerOperator_, uriVL::ImageOperator::rect_, and scale_.
         :       ImageLaplacian( )
 {
         scale_ = (float)theScale;
         int     m = ((int) (5*theScale))/2;
         width_ = 2*m + 1;
         rect_ = new ImageRect(-m, -m, width_, width_);
         isIntegerOperator_ = true;
     initializeFilter_( );
 }
ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I (int theWidth)
Defines a Laplacian Filter with a specified "radius".
The scale of the filter is the square root of the variance of the associated distrinution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Laplacian filter
Definition at line 35 of file ColorImageLaplacian_Gaussian_I.cpp.
References initializeFilter_(), uriVL::ImageOperator::isIntegerOperator_, uriVL::ImageOperator::rect_, and scale_.
         :       ImageLaplacian( )
 {
         scale_ = 0.2L*theWidth;
     int   m = theWidth/2;
         width_ = 2*m+1;
         rect_ = new ImageRect(-m, -m, width_, width_);
         isIntegerOperator_ = false;
     initializeFilter_( );
 }
ImageLaplacian_Gaussian_I::~ImageLaplacian_Gaussian_I (void)
Destructor.
Definition at line 48 of file ColorImageLaplacian_Gaussian_I.cpp.
 {
 }
uriVL::ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I (double theScale)
Defines a Laplacian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
Parameters
theScale scale parameter sigma of the 2D Laplacian filter
uriVL::ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I (int theWidth)
Defines a Laplacian Filter with a specified "radius".
The scale of the filter is the square root of the variance of the associated distrinution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Laplacian filter
virtual uriVL::ImageLaplacian_Gaussian_I::~ImageLaplacian_Gaussian_I (void) virtual
Destructor.
ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I (const ImageLaplacian_Gaussian_I & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 61 of file ImageLaplacian_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ImageLaplacian(theObj),
                                 //
                                 scale_(0.L),
                                 iL_(NULL),
                                 iDenum_(0)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageLaplacian_Gaussian_I copy constructor not implemented.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageLaplacian_Gaussian_I constructor");
         throw e;
 }
Member Function Documentation
void ImageLaplacian_Gaussian_I::applyInto (RasterImage * imgIn, RasterImage * imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Definition at line 111 of file ColorImageLaplacian_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyInto(), and applyTo().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void ImageLaplacian_Gaussian_I::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 156 of file ImageLaplacian_Gaussian_I.cpp.
References applyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void uriVL::ImageLaplacian_Gaussian_I::applyInto (RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
void ImageLaplacian_Gaussian_I::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 165 of file ImageLaplacian_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "not implemented yet");
 }
void uriVL::ImageLaplacian_Gaussian_I::applyInto_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Function that implements a generic (width greater than 13) Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Function that implements a generic (width greater than 13) Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_11x11_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 11x11 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_11x11_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 11x11 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_13x13_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 13x13 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_13x13_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 13x13 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_3x3_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 3x3 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_3x3_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 3x3 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_5x5_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 5x5 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_5x5_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 5x5 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_7x7_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 7x7 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_7x7_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 7x7 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_9x9_ (RasterImage * imgIn, ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 9x9 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
void uriVL::ImageLaplacian_Gaussian_I::applyInto_9x9_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Hard-coded function that implements a 9x9 Laplacian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
RasterImage * ImageLaplacian_Gaussian_I::applyTo (RasterImage * imgIn)
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Definition at line 75 of file ColorImageLaplacian_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * ImageLaplacian_Gaussian_I::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 120 of file ImageLaplacian_Gaussian_I.cpp.
References applyTo(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage* uriVL::ImageLaplacian_Gaussian_I::applyTo (RasterImage * imgIn, const ImageRect * theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
RasterImage * ImageLaplacian_Gaussian_I::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 129 of file ImageLaplacian_Gaussian_I.cpp.
References applyInto(), FAIL_CONDITION, uriVL::RasterImage::floatRasterIsReference(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
         ImageRect       *usableRect = new ImageRect(imgIn->getValidRect());
         usableRect->removeAllAround(1);
         ImageRect       *destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     RasterImage *imgOut;
     if (imgIn->hasFloatRaster() && imgIn->floatRasterIsReference())
         imgOut = new RasterImage_gray_F(destRect);
     else
         imgOut = new RasterImage_gray(destRect);
     applyInto(imgIn, theRect, imgOut);
         delete destRect;
         delete usableRect;
         return imgOut;
 }
uriVL::ImageLaplacian_Gaussian_I::Box (const Box & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
float ImageLaplacian_Gaussian_I::getScale (void) const virtual
Returns the scale of the operator.
Returns
scale of the operator
Implements uriVL::ImageLaplacian.
Definition at line 105 of file ImageLaplacian_Gaussian_I.cpp.
References scale_.
 {
     return static_cast<float>(scale_);
 }
void ImageLaplacian_Gaussian_I::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
iL_
Definition at line 133 of file ColorImageLaplacian_Gaussian_I.cpp.
Referenced by ImageLaplacian_Gaussian_I().
 {
 }
void uriVL::ImageLaplacian_Gaussian_I::initializeFilter_ (void) protected
Initializes the coefficients' array.
See also
iL_
const Box& uriVL::ImageLaplacian_Gaussian_I::operator= (const Box & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
const ImageLaplacian_Gaussian_I & ImageLaplacian_Gaussian_I::operator= (const ImageLaplacian_Gaussian_I & obj) protected
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 87 of file ImageLaplacian_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageLaplacian_Gaussian_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
int uriVL::ImageLaplacian_Gaussian_I::iDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of iL_
Definition at line 119 of file ColorImageLaplacian_Gaussian_I.h.
int * uriVL::ImageLaplacian_Gaussian_I::iL_ private
Stores into a 1D array (radial distances squared) the filter's coefficients.
Definition at line 114 of file ColorImageLaplacian_Gaussian_I.h.
double uriVL::ImageLaplacian_Gaussian_I::scale_ private
the scale sigma of this filter
Definition at line 110 of file ColorImageLaplacian_Gaussian_I.h.
Referenced by getScale(), and ImageLaplacian_Gaussian_I().
The documentation for this class was generated from the following files:
ColorImageLaplacian_Gaussian_I.h
ImageLaplacian_Gaussian_I.h
ColorImageLaplacian_Gaussian_I.cpp
ImageLaplacian_Gaussian_I.cpp