URIVisionLibrary: uriVL::NonlinearOptimizer1D Class Reference
uriVL::NonlinearOptimizer1D Class Reference abstract
Pure virtual parent class for all 1-dimensional optimizers Its subclasses will actually implement an optimization algorithm, i.e.
#include <NonlinearOptimizer1D.h>
Public Member Functions
NonlinearOptimizer1D (void)
Creates a new 1D optimizer.
NonlinearOptimizer1D (const Function1D *f)
Creates a new 1D optimizer for a specific function.
NonlinearOptimizer1D (const Function1D_F *f)
Creates a new 1D optimizer for a specific function.
virtual ~NonlinearOptimizer1D (void)
Destructor.
void setFunction (const Function1D *f)
Assigns a new double 1D function to this optimizer.
void setFunction (const Function1D_F *f)
Assigns a new float 1D function to this optimizer.
bool isOptimizationFunction (const Function1D *f)
Checks if the function passed as parameter is the one set for this optimization problem.
bool isOptimizationFunction (const Function1D_F *f)
Checks if the function passed as parameter is the one set for this optimization problem.
const OptimizerRecord1D * minimize (const Function1D *f, double startX, double xMin, double xMax, double tol)
Finds and returns a (local) minimum for a double function over a specific range.
const OptimizerRecord1D * minimize (const Function1D_F *f, float startX, float xMin, float xMax, float tol)
Finds and returns a (local) minimum for a float function over a specific range.
void minimize (const Function1D *f, double startX, double xMin, double xMax, double tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a double function over a specific range.
void minimize (const Function1D_F *f, float startX, float xMin, float xMax, float tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a float function over a specific range.
Private Member Functions
NonlinearOptimizer1D (const NonlinearOptimizer1D &obj)
Disabled copy constructor.
const NonlinearOptimizer1D & operator= (const NonlinearOptimizer1D &obj)
Disabled copy operator.
virtual void setFunction_ (const Function1D *f)
Called by this class's public function prior to changing the value of the instance variable.
virtual void setFunction_ (const Function1D_F *f)
Called by this class's public function prior to changing the value of the instance variable.
virtual void minimize_ (const Function1D *f, double startX, double xMin, double xMax, double tol, OptimizerRecord1D *optRec)=0
Finds a (local) minimum for a double function over a specific range.
virtual void minimize_ (const Function1D_F *f, float startX, float xMin, float xMax, float tol, OptimizerRecord1D *optRec)=0
Finds a (local) minimum for a double function over a specific range.
Private Attributes
const Function1D * fD_
Stores a pointer to the nD function of the minimization problem (if it has been defined)
const Function1D_F * fF_
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Detailed Description
Pure virtual parent class for all 1-dimensional optimizers Its subclasses will actually implement an optimization algorithm, i.e.
golden section search.
   I have flip-flopped for a while on a couple of questions regarding optimizers:
   <ul>
           <li>Inheritance:  Is there any point at all to using inheritance for these
                   classes, and wouldn't it be simpler to simple propose a flat list of
                   implementations with no common parent class?  All the more so since most of
                   the functions in these classes could very well be static.
                   I opted for a class hierarchy because this allows me in the future to define
                   a "processing pipeline" with a generic 1d optimizer, and then pick the
                   particular optimizer subclass to use w/o having to redefine the pipeline.</li>
           <li>Should an optimizer store a reference to the 1d function of the optimization
                   problem, since all my minimize_ functions take the 1d function asone of their
                   parameters?  The answer is yes, because setting the function allows to
                   preallocate whatever arrays/structures may be needed by the specific algorithm.
                   Now, if the user wants to change the 1d funtion each time they solve a
                   minimization problem, this is their problem.</li>
           <li>What about a set of "maximize" functions?  No time, and not convinced that
                   it's worth it.  Since the user has to define & implement the function to
                   optimize, nothing prevents implenting -f  or bigNumber - f and run through
                   minimization to get the maximum of +f.</li>
           </ul>
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 55 of file NonlinearOptimizer1D.h.
Constructor & Destructor Documentation
NonlinearOptimizer1D::NonlinearOptimizer1D (void)
Creates a new 1D optimizer.
Definition at line 26 of file NonlinearOptimizer1D.cpp.
                 :       fD_(NULL),
                         fF_(NULL)
 {
 }
NonlinearOptimizer1D::NonlinearOptimizer1D (const Function1D * f)
Creates a new 1D optimizer for a specific function.
This is the version of the constructor to invoke if the same function will be used over and over for optimization.
Parameters
f the function to optimize
Definition at line 33 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, and uriVL::kNullFunctionError.
                 :       fD_(f),
                         fF_(NULL)
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D constructor");
 }
NonlinearOptimizer1D::NonlinearOptimizer1D (const Function1D_F * f)
Creates a new 1D optimizer for a specific function.
This is the version of the constructor to invoke if the same function will be used over and over for optimization.
Parameters
f the function to optimize
Definition at line 44 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, and uriVL::kNullFunctionError.
                 :       fD_(NULL),
                         fF_(f)
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D constructor");
 }
NonlinearOptimizer1D::~NonlinearOptimizer1D (void) virtual
Destructor.
Definition at line 56 of file NonlinearOptimizer1D.cpp.
 {
 }
uriVL::NonlinearOptimizer1D::NonlinearOptimizer1D (const NonlinearOptimizer1D & obj) private
Disabled copy constructor.
Member Function Documentation
bool uriVL::NonlinearOptimizer1D::isOptimizationFunction (const Function1D * f)
Checks if the function passed as parameter is the one set for this optimization problem.
Why this function: Because the library (still) admits double and float versions of the Function1D class, we can't have a getFunction function, and I don't like the idea of using protected variables much.
Returns
true if f is the function of this optimizaton problem
bool uriVL::NonlinearOptimizer1D::isOptimizationFunction (const Function1D_F * f)
Checks if the function passed as parameter is the one set for this optimization problem.
Why this function: Because the library (still) admits double and float versions of the Function1D class, we can't have a getFunction function, and I don't like the idea of using protected variables much.
Returns
true if f is the function of this optimizaton problem
const OptimizerRecord1D * NonlinearOptimizer1D::minimize (const Function1D * f, double startX, double xMin, double xMax, double tol)
Finds and returns a (local) minimum for a double function over a specific range.
Note that the rule of thumb for the (relative) tolerance is that typically it should not be smaller than sqrt(machine's floating point prevision), that is, 1.e-04 for float, and 3.e-08 for double (so sez Numerical Recipes)
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
Returns
result of the optimization
Definition at line 114 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, uriVL::kNullFunctionError, and minimize_().
Referenced by main(), and uriVL::NonlinearOptimizerND_conjDir::minimize_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( !f->isDefinedAt(xMin) || !f->isDefinedAt(xMax),
                     kDataRangeError,
                     "function not defined on the entire search range in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( (startX<xMin) || (startX>xMax),
                     kDataRangeError,
                     "starting point not in search range in NonlinearOptimizer1D::minimize");
     OptimizerRecord1D* optRec = new OptimizerRecord1D();
     minimize_(f, startX, xMin, xMax, tol, optRec);
     return optRec;
 }
const OptimizerRecord1D * NonlinearOptimizer1D::minimize (const Function1D_F * f, float startX, float xMin, float xMax, float tol)
Finds and returns a (local) minimum for a float function over a specific range.
Note that the rule of thumb for the (relative) tolerance is that typically it should not be smaller than sqrt(machine's floating point prevision), that is, 1.e-04 for float, and 3.e-08 for double (so sez Numerical Recipes)
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
Returns
result of the optimization
Definition at line 153 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, uriVL::kNullFunctionError, and minimize_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( !f->isDefinedAt(xMin) || !f->isDefinedAt(xMax),
                     kDataRangeError,
                     "function not defined on the entire search range in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( (startX<xMin) || (startX>xMax),
                     kDataRangeError,
                     "starting point not in search range in NonlinearOptimizer1D::minimize");
     OptimizerRecord1D* optRec = new OptimizerRecord1D();
     minimize_(f, startX, xMin, xMax, tol, optRec);
     return optRec;
 }
void NonlinearOptimizer1D::minimize (const Function1D * f, double startX, double xMin, double xMax, double tol, OptimizerRecord1D * optRec)
Finds a (local) minimum for a double function over a specific range.
Note that the rule of thumb for the (relative) tolerance is that typically it should not be smaller than sqrt(machine's floating point prevision), that is, 1.e-04 for float, and 3.e-08 for double (so sez Numerical Recipes)
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Definition at line 133 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, uriVL::kNullFunctionError, uriVL::kNullParameterError, and minimize_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( optRec == NULL,
                     kNullParameterError,
                     "null optimizer record as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( !f->isDefinedAt(xMin) || !f->isDefinedAt(xMax),
                     kDataRangeError,
                     "function not defined on the entire search range in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( (startX<xMin) || (startX>xMax),
                     kDataRangeError,
                     "starting point not in search range in NonlinearOptimizer1D::minimize");
     minimize_(f, startX, xMin, xMax, tol, optRec);
 }
void NonlinearOptimizer1D::minimize (const Function1D_F * f, float startX, float xMin, float xMax, float tol, OptimizerRecord1D * optRec)
Finds a (local) minimum for a float function over a specific range.
Note that the rule of thumb for the (relative) tolerance is that typically it should not be smaller than sqrt(machine's floating point prevision), that is, 1.e-04 for float, and 3.e-08 for double (so sez Numerical Recipes)
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Definition at line 171 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, uriVL::kNullFunctionError, uriVL::kNullParameterError, and minimize_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( optRec == NULL,
                     kNullParameterError,
                     "null optimizer record as parameter in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( !f->isDefinedAt(xMin) || !f->isDefinedAt(xMax),
                     kDataRangeError,
                     "function not defined on the entire search range in NonlinearOptimizer1D::minimize");
     FAIL_CONDITION( (startX<xMin) || (startX>xMax),
                     kDataRangeError,
                     "starting point not in search range in NonlinearOptimizer1D::minimize");
     minimize_(f, startX, xMin, xMax, tol, optRec);
 }
virtual void uriVL::NonlinearOptimizer1D::minimize_ (const Function1D * f, double startX, double xMin, double xMax, double tol, OptimizerRecord1D * optRec) private pure virtual
Finds a (local) minimum for a double function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizer1D_parab, uriVL::NonlinearOptimizer1D_gss, and uriVL::NonlinearOptimizer1D_Brent.
Referenced by minimize().
virtual void uriVL::NonlinearOptimizer1D::minimize_ (const Function1D_F * f, float startX, float xMin, float xMax, float tol, OptimizerRecord1D * optRec) private pure virtual
Finds a (local) minimum for a double function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizer1D_parab, uriVL::NonlinearOptimizer1D_gss, and uriVL::NonlinearOptimizer1D_Brent.
const NonlinearOptimizer1D& uriVL::NonlinearOptimizer1D::operator= (const NonlinearOptimizer1D & obj) private
Disabled copy operator.
void NonlinearOptimizer1D::setFunction (const Function1D * f)
Assigns a new double 1D function to this optimizer.
Note that an optimizer cannot have a double and float function assigned to it. The last function assigned simply replaces the previous one, regardless of type.
Parameters
f the function of the optimization problem
Definition at line 69 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, fD_, fF_, uriVL::kNullFunctionError, and setFunction_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D constructor");
         //      don't waste time
         if (f != fD_)
         {
                 //      call the private setting function (possibly overriden by child class)
                 setFunction_(f);
                 //      sets the variables
                 fF_ = NULL;
                 fD_ = f;
         }
 }
void NonlinearOptimizer1D::setFunction (const Function1D_F * f)
Assigns a new float 1D function to this optimizer.
Note that an optimizer cannot have a double and float function assigned to it. The last function assigned simply replaces the previous one, regardless of type.
Parameters
f the function of the optimization problem
Definition at line 88 of file NonlinearOptimizer1D.cpp.
References FAIL_CONDITION, fD_, fF_, uriVL::kNullFunctionError, and setFunction_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizer1D constructor");
         //      don't waste time
         if (f != fF_)
         {
                 //      call the private setting function (possibly overriden by child class)
                 setFunction_(f);
                 //      sets the variables
                 fD_ = NULL;
                 fF_ = f;
         }
 }
virtual void uriVL::NonlinearOptimizer1D::setFunction_ (const Function1D * f) inline private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Definition at line 201 of file NonlinearOptimizer1D.h.
Referenced by setFunction().
{
                                 //      nothing.  Override if needed
                         }
virtual void uriVL::NonlinearOptimizer1D::setFunction_ (const Function1D_F * f) inline private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Definition at line 211 of file NonlinearOptimizer1D.h.
{
                                 //      nothing.  Override if needed
                         }
Member Data Documentation
const Function1D* uriVL::NonlinearOptimizer1D::fD_ private
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Definition at line 180 of file NonlinearOptimizer1D.h.
Referenced by setFunction().
const Function1D_F* uriVL::NonlinearOptimizer1D::fF_ private
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Definition at line 184 of file NonlinearOptimizer1D.h.
Referenced by setFunction().
The documentation for this class was generated from the following files:
NonlinearOptimizer1D.h
NonlinearOptimizer1D.cpp