URIVisionLibrary: uriVL::MedianFilter_F Class Reference
uriVL::MedianFilter_F Class Reference
MedianFilter class.
#include <MedianFilter_F.h>
Public Member Functions
MedianFilter_F (int theWidth)
Defines a median filter with a specified width.
MedianFilter_F (int theWidth, int theHeight)
Defines a median filter with a specified width and height.
MedianFilter_F (const ImageRect *theRect)
Defines a median filter with a dimensions rectangle.
~MedianFilter_F (void)
Destructor.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::MedianFilter
~MedianFilter (void)
Destructor.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
MedianFilter_F (const MedianFilter_F &obj)
Copy constructor (disabled)
const MedianFilter_F & operator= (const MedianFilter_F &obj)
Copy operator: disabled.
Private Attributes
float * data_
Private data array for median computation.
Additional Inherited Members
Protected Member Functions inherited from uriVL::MedianFilter
MedianFilter (void)
Defines a median filter without a specified width and height.
MedianFilter (int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Defines a median filter with a specified width and height.
MedianFilter (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Defines a median filter with a dimensions rectangle.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
MedianFilter class.
A median filter is an image operator that replaces the value at each pixel by the median value of a rectangular window centered at that pixel
Definition at line 30 of file MedianFilter_F.h.
Constructor & Destructor Documentation
MedianFilter_F::MedianFilter_F (int theWidth)
Defines a median filter with a specified width.
The filter will be centered at the pixel where it is applied.
Parameters
theWidth desired width of the median filter
Definition at line 44 of file MedianFilter_F.cpp.
                         :       MedianFilter(theWidth, theWidth, false, kPositiveFloat),
                                 //
                                 data_(new float[theWidth*theWidth])
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by MedianFilter_F constructor");
         throw e;
 }
MedianFilter_F::MedianFilter_F (int theWidth, int theHeight)
Defines a median filter with a specified width and height.
The filter will be centered at the pixel where it is applied.
Parameters
theWidth desired width of the median filter
theHeight desired width of the median filter
Definition at line 55 of file MedianFilter_F.cpp.
References data_.
                         :       MedianFilter(theWidth, theHeight, false, kPositiveFloat),
                                 //
                                 data_(new float[theHeight*theWidth])
 {
         //  Allocate the array that we will use to compute the median
         data_ = new float[theHeight*theWidth];
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by MedianFilter_F constructor");
         throw e;
 }
MedianFilter_F::MedianFilter_F (const ImageRect * theRect)
Defines a median filter with a dimensions rectangle.
It is up to the user to make sure that the dimensions of the filter make sense (the "left" and "top" values should be negative, opposite of "right" and bottom")
Parameters
theRect desired dimensions of the median filter
Definition at line 68 of file MedianFilter_F.cpp.
References data_, uriVL::ImageRect::getHeight(), and uriVL::ImageRect::getWidth().
                         :       MedianFilter(theRect, false, kPositiveFloat),
                                 //
                                 data_(new float[theRect->getWidth()*theRect->getHeight()])
 {
         //  Allocate the array that we will use to compute the median
         data_ = new float[theRect->getWidth()*theRect->getHeight()];
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by MedianFilter_F constructor");
         throw e;
 }
MedianFilter_F::~MedianFilter_F (void)
Destructor.
Definition at line 94 of file MedianFilter_F.cpp.
References data_.
 {
     delete []data_;
 }
MedianFilter_F::MedianFilter_F (const MedianFilter_F & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 82 of file MedianFilter_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       MedianFilter(),
                                 //
                                 data_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "MedianFilter_F copy constructor not implemented.");
 }
Member Function Documentation
void MedianFilter_F::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 173 of file MedianFilter_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo(), and myMenu3().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void MedianFilter_F::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 183 of file MedianFilter_F.cpp.
References uriVL::ImageRect::contains(), data_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), getMedian_(), uriVL::ImageOperator::getRect(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::RasterImage_gray::localRasterGray(), MAX, MIN, uriVL::R_W_ACCESS, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
         //----------------------------------------------------------------
         //      STEP 0:         Test for null or invalid type parameters
         //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     FAIL_CONDITION(     imgOut == NULL,
                                 kNullRasterImageError,
                                 "NULL output raster image passed as parameter");
         FAIL_CONDITION( (imgOut->getBaseRasterType() != kGrayRaster) ||
                     (!imgOut->hasFloatRaster()),
                         kInvalidRasterType,
                         "MedianFilter_F::applyInto only accepts RasterImage_gray_F images as destination");
         //----------------------------------------------------------------
         //      STEP 1:         Test for rectangle intersection
         //----------------------------------------------------------------
         //  determine the output rectangle that the input image can produce.
         //              Here, it is the entire valid data rectangle.
     const ImageRect   *outRect = imgIn->getValidRect();
         //      ... and determine its intersection with the user-specified output rectangle
         ImageRect       *destRect = ImageRect::intersection(theRect, outRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!outRect->contains(destRect))
         imgOut->setBoundRect(destRect);
         //----------------------------------------------------------------
         //      STEP 2:         Get a gray-level input image
         //----------------------------------------------------------------
     bool    localGray = false;
     const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
         //----------------------------------------------------------------
         //      STEP 3:         Perform the calculations
         //----------------------------------------------------------------
     const int   iLow = destRect->getTop(),
                 iHigh = destRect->getBottom(),
                 jLow = destRect->getLeft(),
                 jHigh = destRect->getRight();
         const ImageRect* operRect = getRect();
     const int   recTop = operRect->getTop(),
                 recBottom = operRect->getBottom(),
                 recLeft = operRect->getLeft(),
                 recRight = operRect->getRight();
         if (imgIn->hasFloatRaster())
         {
             const float* const* fGrayIn = ((RasterImage_gray_F *)grayImg)->getShiftedGrayF2D();
         float* const* grayOut = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
             for (int i=iLow; i<= iHigh; i++)
             {
                 const int kLow = MAX(i+recTop, iLow);
                 const int kHigh = MIN(i+recBottom, iHigh);
                 //
                 for (int j=jLow; j<=jHigh; j++)
                 {
                     //  collect the data around the pixel.
                     const int lLow = MAX(j+recLeft, jLow);
                     const int lHigh = MIN(j+recRight, jHigh);
                     int  n = 0;
                     //
                     for (int k=kLow; k<=kHigh; k++)
                         for (int l=lLow; l<=lHigh; l++)
                             data_[n++] = fGrayIn[k][l];
                     grayOut[i][j] = getMedian_(data_, n);
                 }
             }
         }
         else
         {
             const unsigned char* const* iGrayIn = grayImg->getShiftedGray2D();
         float* const* grayOut = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
             for (int i=iLow; i<= iHigh; i++)
             {
                 const int kLow = MAX(i+recTop, iLow);
                 const int kHigh = MIN(i+recBottom, iHigh);
                 //
                 for (int j=jLow; j<=jHigh; j++)
                 {
                     //  collect the data around the pixel.
                     const int lLow = MAX(j+recLeft, jLow);
                     const int lHigh = MIN(j+recRight, jHigh);
                     int n = 0;
                     //
                     for (int k=kLow; k<=kHigh; k++)
                     for (int l=lLow; l<=lHigh; l++)
                         data_[n++] = iGrayIn[k][l];
                     grayOut[i][j] = getMedian_(data_, n);
                 }
             }
         }
         //      Very important:  At the end of the computation, don't forget to set the
         //      output's valid data rectangle.  In "safe" mode, the library has no way to guess
         //      what the valid data rectangle should be and sets it to its minimum value... empty
         imgOut->setValidRect(outRect);
         imgOut->requestRasterUpdate();
     //  cleanup
     if (localGray)
         delete grayImg;
 }
RasterImage * MedianFilter_F::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 116 of file MedianFilter_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to MedianFilter_F::applyTo");
         return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * MedianFilter_F::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 126 of file MedianFilter_F.cpp.
References uriVL::ErrorReport::appendToMessage(), applyInto(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getBoundRect(), uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kImageProcessingError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to MedianFilter_F::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in to MedianFilter_F::applyTo");
         RasterImage* imgOut = NULL;
         try {
                 switch (imgIn->getBaseRasterType())
                 {
                         case kGrayRaster:
                                 imgOut = new RasterImage_gray_F(imgIn->getBoundRect());
                                 break;
                         case kRGBa32Raster:
                                 imgOut = new RasterImage_RGBa_F(imgIn->getBoundRect());
                                 break;
                         default:
                                 FAIL_CONDITION( true,
                                                                 kFunctionNotImplemented,
                                                                 "image type not suported by median filter yet");
                                 break;
                 }
                 applyInto(imgIn, theRect, imgOut);
     }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by MedianFilter_F::applyTo");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Error in the computation of MedianFilter_F::applyTo");
         }
         return imgOut;
 }
const MedianFilter_F & MedianFilter_F::operator= (const MedianFilter_F & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 99 of file MedianFilter_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "MedianFilter_F copy operator not implemented.");
         return *this;
 }
Member Data Documentation
float* uriVL::MedianFilter_F::data_ private
Private data array for median computation.
Definition at line 107 of file MedianFilter_F.h.
Referenced by applyInto(), MedianFilter_F(), and ~MedianFilter_F().
The documentation for this class was generated from the following files:
MedianFilter_F.h
MedianFilter_F.cpp