URIVisionLibrary: uriVL::Vector2D Class Reference
uriVL::Vector2D Class Reference
Implements the Vector2D class.
#include <Vector2D.h>
Public Member Functions
Vector2D (void)
Default Constructor.
Vector2D (int dx, int dy)
Constructor.
Vector2D (const int dxy[])
Constructor.
Vector2D (const Vector2D *displ)
Copy constructor.
Vector2D (const ImagePoint *pt1, const ImagePoint *pt2)
Constructor.
virtual ~Vector2D (void)
Destructor.
int getX (void) const
Returns the pixel's x coordinate.
int getY (void) const
Returns the pixel's y coordinate.
virtual void setX (int val)
Assigns new x coordinate to the vector.
virtual void setY (int val)
Assigns new y coordinate to the vector.
virtual void setCoordinates (int valX, int valY)
Assigns new coordinates to the vector.
virtual void setCoordinates (const int dxy[])
Assigns new coordinates to the vector.
virtual void setCoordinates (const Vector2D *theVect)
Assigns new coordinates to the vector.
virtual void setCoordinates (const ImagePoint *pt1, const ImagePoint *pt2)
Assigns new coordinates to the vector.
virtual bool hasSubpixelPrecision (void) const
Indicates whether this object has subpixel precision.
virtual void applyRotation (const Rotation2D *theRot)
Applies a Rotation2D to this object.
virtual void rotate (float angle)
Rotates the object by the angle specified (in radians)
Protected Attributes
int x_
The vector's x coordinate.
int y_
The vector's y coordinate.
Detailed Description
Implements the Vector2D class.
A Vector2D should typically store an image displacement or an edge of a contour
Version history
2007/11/02 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 40 of file Vector2D.h.
Constructor & Destructor Documentation
Vector2D::Vector2D (void)
Default Constructor.
Creates a (0, 0) image displacement.
Definition at line 27 of file Vector2D.cpp.
                 :       x_(0),
                         y_(0)
 {
 }
Vector2D::Vector2D (int dx, int dy)
Constructor.
Creates and initializes an image displacement.
Parameters
dX x displacement
dY y displacement
Definition at line 34 of file Vector2D.cpp.
                 :       x_(theX),
                         y_(theY)
 {
 }
Vector2D::Vector2D (const int dxy[])
Constructor.
Creates and initializes an image displacement.
Parameters
dxy displacement vector
Definition at line 40 of file Vector2D.cpp.
                 :       x_(xy[0]),
                         y_(xy[1])
 {
 }
 catch(...) {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to Vector2D constructor");
 }
Vector2D::Vector2D (const Vector2D * displ)
Copy constructor.
Creates a clone of the Vector2D object passed as parameter.
Parameters
displ pointer to the Vector2D object to copy
Definition at line 51 of file Vector2D.cpp.
                 :       x_(theVect->x_),
                         y_(theVect->y_)
 {
 }
 catch(...) {
     FAIL_CONDITION( theVect == NULL,
                     kNullParameterError,
                     "null Vector2D passed to copy constructor constructor");
 }
Vector2D::Vector2D (const ImagePoint * pt1, const ImagePoint * pt2)
Constructor.
Creates and initializes an image displacement joining two image points.
Parameters
pt1 start point of the vector
pt2 end point of the vector
Definition at line 63 of file Vector2D.cpp.
                 :       x_(pt2->getX() - pt1->getX()),
                         y_(pt2->getY() - pt1->getY())
 {
 }
 catch(...) {
     FAIL_CONDITION( (pt1 == NULL) || (pt2 == NULL),
                     kNullParameterError,
                     "null Point2D passed to Vector2D constructor constructor");
 }
Vector2D::~Vector2D (void) virtual
Destructor.
Definition at line 75 of file Vector2D.cpp.
 {
 }
Member Function Documentation
void Vector2D::applyRotation (const Rotation2D * theRot) virtual
Applies a Rotation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Reimplemented in uriVL::Vector2D_F.
Definition at line 161 of file Vector2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
int Vector2D::getX (void) const
Returns the pixel's x coordinate.
Returns
x coordinate of the pixel
Definition at line 88 of file Vector2D.cpp.
References x_.
Referenced by uriVL::Vector2D_F::setCoordinates(), and uriVL::Disparity::setDisparity().
 {
     return x_;
 }
int Vector2D::getY (void) const
Returns the pixel's y coordinate.
Returns
y coordinate of the pixel
Definition at line 93 of file Vector2D.cpp.
References y_.
Referenced by uriVL::Vector2D_F::setCoordinates(), and uriVL::Disparity::setDisparity().
 {
     return y_;
 }
virtual bool uriVL::Vector2D::hasSubpixelPrecision (void) const inline virtual
Indicates whether this object has subpixel precision.
Should be overridden by a subclass that has floating point precision
Reimplemented in uriVL::Vector2D_F.
Definition at line 141 of file Vector2D.h.
{
                                 return false;
                         }
void Vector2D::rotate (float angle) virtual
Rotates the object by the angle specified (in radians)
Parameters
angle the angle of the rotation (in radians)
Reimplemented in uriVL::Vector2D_F.
Definition at line 153 of file Vector2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void Vector2D::setCoordinates (int valX, int valY) virtual
Assigns new coordinates to the vector.
Parameters
valY new x coordinate for the pixel
valY new y coordinate for the pixel
Reimplemented in uriVL::Vector2D_F.
Definition at line 108 of file Vector2D.cpp.
References x_, and y_.
Referenced by uriVL::Vector2D_F::setCoordinates().
 {
     x_ = valX;
     y_ = valY;
 }
void Vector2D::setCoordinates (const int dxy[]) virtual
Assigns new coordinates to the vector.
Parameters
dxy coordinate array of the pixel
Reimplemented in uriVL::Vector2D_F.
Definition at line 114 of file Vector2D.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, x_, and y_.
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to Vector2D::setCoordinates");
     x_ = xy[0];
     y_ = xy[1];
 }
void Vector2D::setCoordinates (const Vector2D * theVect) virtual
Assigns new coordinates to the vector.
Parameters
theVect pointer to the Vector2D object to copy
Reimplemented in uriVL::Vector2D_F.
Definition at line 124 of file Vector2D.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, x_, and y_.
 {
     FAIL_CONDITION( theVect == NULL,
                     kNullParameterError,
                     "null Vector2D passed to Vector2D::setCoordinates");
     x_ = theVect->x_;
     y_ = theVect->y_;
 }
void Vector2D::setCoordinates (const ImagePoint * pt1, const ImagePoint * pt2) virtual
Assigns new coordinates to the vector.
Parameters
pt1 start point of the vector
pt2 end point of the vector
Reimplemented in uriVL::Vector2D_F.
Definition at line 134 of file Vector2D.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kNullParameterError, x_, and y_.
 {
     FAIL_CONDITION( (pt1 == NULL) || (pt2 == NULL),
                     kNullParameterError,
                     "null Point2D passed to Vector2D::setCoordinates");
     x_ = pt2->getX() - pt1->getX();
     y_ = pt2->getY() - pt1->getY();
 }
void Vector2D::setX (int val) virtual
Assigns new x coordinate to the vector.
Parameters
val new x coordinate for the pixel
Reimplemented in uriVL::Vector2D_F.
Definition at line 98 of file Vector2D.cpp.
References x_.
Referenced by uriVL::Vector2D_F::setCoordinates().
 {
     x_ = theX;
 }
void Vector2D::setY (int val) virtual
Assigns new y coordinate to the vector.
Parameters
val new y coordinate for the pixel
Reimplemented in uriVL::Vector2D_F.
Definition at line 103 of file Vector2D.cpp.
References y_.
Referenced by uriVL::Vector2D_F::setCoordinates().
 {
     y_ = theY;
 }
Member Data Documentation
int uriVL::Vector2D::x_ protected
The vector's x coordinate.
Definition at line 162 of file Vector2D.h.
Referenced by getX(), setCoordinates(), uriVL::Vector2D_F::setCoordinates(), setX(), and uriVL::Vector2D_F::setX().
int uriVL::Vector2D::y_ protected
The vector's y coordinate.
Definition at line 167 of file Vector2D.h.
Referenced by getY(), setCoordinates(), uriVL::Vector2D_F::setCoordinates(), setY(), and uriVL::Vector2D_F::setY().
The documentation for this class was generated from the following files:
Vector2D.h
Vector2D.cpp