URIVisionLibrary: uriVL::ImageWarper Class Reference
uriVL::ImageWarper Class Reference abstract
Virtual parent class for all image warper object.
#include <ImageWarper.h>
Public Member Functions
ImageWarper (ImageWarperType type, const InnerWarpingMode innerMode=INNER_FREE, const BorderWarpingMode outerMode=BORDER_FREE)
Creates a new ImageWarper whose grid points conform to the displacement modes specified.
virtual ~ImageWarper (void)
Destructor.
ImageWarperType getWarperType (void) const
Indicates the type of warping algorithm used by this warper (e.g.
virtual void setImages (const RasterImage *imgIn, RasterImage *imgOut)
Defines an input image and an output image(for multiple warpings).
virtual void setGrid (int gridRows, int gridCols)
Sets the dimensions of the warping grid (should be at least 3x3)
float ***const newWarpingGrid (void) const
Returns a new grid of points allocated at the grid dimensions of this warper and initialized as a regular rectangular grid.
const RasterImage * getInputImage (void) const
Returns the warper's input image.
RasterImage * getOutputImage (void) const
Returns the warper's output image.
virtual bool isValidDisplacement (float ***xy) const
Indicates whether a point grid is consistent with the displacement modes of of this warper.
void warp (float ***xy, const RasterImage *imgIn, RasterImage *imgOut)
Warps the image.
void warp (float ***xy)
warp the image using the new grid point coordinates specified
int getNbGridRows (void) const
Returns the number of rows on this warper's grid.
int getNbGridCols (void) const
Returns the number of columns on this warper's grid.
bool isSetUp (void) const
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
InnerWarpingMode getInnerWarpingMode (void) const
Returns the warper's inner warping mode.
BorderWarpingMode getBorderWarpingMode (void) const
Returns the warper's border warping mode.
virtual void getImageSuitableDimensions (int imgWidth, int imgHeight, int *lowImgWidth, int *lowImgHeight, int *highImgWidth, int *highImgHeight) const =0
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
virtual int getEffectivePixelsPerRow (const int nominalWidth) const =0
Returns the "true" number of pixels on a row of the input image (possibly larger than the nominal width, due to row padding).
Protected Member Functions
virtual void warp_ (float ***xy)=0
warp the (pre-specified) input image into the (prespecified) output image using the new grid point coordinates specified
bool isValidDisplacement_ (const float ***const xy) const
Checks whether the grid coordinates specified conform to the grid displacement modes set.
void allocateGrids_ (void)
Allocates new grids of points at the (pre-approved) dimensions.
void initializeGrids_ (void)
Initializes the grids once its dimensions and that of the image are known.
void deleteGrids_ (void)
Deletes the pre-allocates grids of points (grid resize or destruction)
ImageWarper (const ImageWarper &obj)
Copy constructor (disabled)
const ImageWarper & operator= (const ImageWarper &obj)
Copy operator: disabled.
Protected Attributes
ImageWarperType warperType_
Indicates the type of warping algorithm used by this warper (e.g.
InnerWarpingMode innerMode_
Warping mode if the grid's inner points.
BorderWarpingMode outerMode_
Warping mode if the grid's border points.
bool isSetUp_
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
int imgHeight_
Height of the image to warp.
int imgWidth_
Width of the image to warp.
int effImgWidth_
Effective width of the image to warp (taking into account row padding)
BaseRasterType rasterType_
Type of the input image's raster (only RGBa32 and gray supported so far)
int gridRows_
number of rows of the warping grid
int gridCols_
number of cols of the warping grid
float *** xy_
gridRows_ x gridCols_ array of 2D grid points
float *** xy0_
gridRows_ x gridCols_ array of original 2D grid points
float verticalSpacing_
distance between vertical grid points
float horizontalSpacing_
distance between horizontal grid points
const RasterImage * imgIn_
texture image
RasterImage * imgOut_
output image
const unsigned char * imgIn1D_
1D raster of the texture image
unsigned char * imgOut1D_
1D raster of output image
Detailed Description
Virtual parent class for all image warper object.
Subclasses will implement a particular kind of warping algorithm (for example, by OpenGL-based texture mapping.
Author
Meng Wan, 3D Group for Interactive Visualization, Dept of Computer Science, University of Rhode Island
jean-yves herve', 3D Group for Interactive Visualization, Dept of Computer Science, University of Rhode Island
Definition at line 61 of file ImageWarper.h.
Constructor & Destructor Documentation
ImageWarper::ImageWarper (ImageWarperType type, const InnerWarpingMode innerMode = INNER_FREE, const BorderWarpingMode outerMode = BORDER_FREE)
Creates a new ImageWarper whose grid points conform to the displacement modes specified.
If modes other than INNER_FREE and BORDER_FREE are specified, then the warper will verify that the point coordinates specified are conform to its set motion modes prior to applying a warping.
Parameters
type type of this warper
innerMode grid inner warping mode for this warper
outerMode grid outer warping mode for this warper
Definition at line 29 of file ImageWarper.cpp.
      :          warperType_(type),
                         innerMode_(innerMode),
                         outerMode_(outerMode),
                         isSetUp_(),
                         imgHeight_(0),
                         imgWidth_(0),
                         effImgWidth_(),
                         rasterType_(),
                         gridRows_(0),
                         gridCols_(0),
                         xy_(NULL),
                         xy0_(NULL),
                         verticalSpacing_(0),
                         horizontalSpacing_(0),
                         imgIn_(NULL),
                         imgOut_(NULL),
                         imgIn1D_(NULL),
                         imgOut1D_(NULL)
 {
 }
ImageWarper::~ImageWarper (void) virtual
Destructor.
Definition at line 81 of file ImageWarper.cpp.
References deleteGrids_().
 {
     deleteGrids_();
 }
ImageWarper::ImageWarper (const ImageWarper & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 54 of file ImageWarper.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
      :          warperType_(),
                         innerMode_(),
                         outerMode_(),
                         isSetUp_(),
                         imgHeight_(0),
                         imgWidth_(0),
                         effImgWidth_(),
                         rasterType_(),
                         gridRows_(0),
                         gridCols_(0),
                         xy_(NULL),
                         xy0_(NULL),
                         verticalSpacing_(0),
                         horizontalSpacing_(0),
                         imgIn_(NULL),
                         imgOut_(NULL),
                         imgIn1D_(NULL),
                         imgOut1D_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageWarper copy constructor not implemented.");
 }
Member Function Documentation
void ImageWarper::allocateGrids_ (void) protected
Allocates new grids of points at the (pre-approved) dimensions.
Definition at line 299 of file ImageWarper.cpp.
References gridCols_, gridRows_, xy0_, and xy_.
Referenced by setGrid().
 {
         xy_ = new float**[gridRows_];
         xy0_ = new float**[gridRows_];
         for (int i=0; i<gridRows_; i++)
         {
                 xy_[i] = new float*[gridCols_];
                 xy0_[i] = new float*[gridCols_];
                 for (int j=0; j<gridCols_; j++)
                 {
                         xy_[i][j] = new float[2];
                         xy0_[i][j] = new float[2];
                 }
         }
 }
void ImageWarper::deleteGrids_ (void) protected
Deletes the pre-allocates grids of points (grid resize or destruction)
Definition at line 337 of file ImageWarper.cpp.
References gridCols_, gridRows_, xy0_, and xy_.
Referenced by setGrid(), and ~ImageWarper().
 {
     if (xy_ != NULL)
     {
         for (int i=0; i<gridRows_; i++)
         {
                 for (int j=0; j<gridCols_; j++)
                         delete []xy_[i][j];
                 delete []xy_[i];
         }
         delete []xy_;
         xy_ = NULL;
     }
     if (xy_ != NULL)
     {
         for (int i=0; i<gridRows_; i++)
         {
                 for (int j=0; j<gridCols_; j++)
                         delete []xy0_[i][j];
                 delete []xy0_[i];
         }
         delete []xy0_;
         xy0_ = NULL;
     }
 }
BorderWarpingMode ImageWarper::getBorderWarpingMode (void) const
Returns the warper's border warping mode.
Definition at line 228 of file ImageWarper.cpp.
References outerMode_.
Referenced by uriVL::WarpMatchScoreFunctionND::WarpMatchScoreFunctionND().
 {
     return outerMode_;
 }
virtual int uriVL::ImageWarper::getEffectivePixelsPerRow (const int nominalWidth) const pure virtual
Returns the "true" number of pixels on a row of the input image (possibly larger than the nominal width, due to row padding).
Parameters
nominalWidth nominal width of the input image
Returns
"true" width of the image stored
Implemented in uriVL::ImageWarper_GL.
Referenced by setImages().
virtual void uriVL::ImageWarper::getImageSuitableDimensions (int imgWidth, int imgHeight, int * lowImgWidth, int * lowImgHeight, int * highImgWidth, int * highImgHeight) const pure virtual
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
Some warpers require specific image dimensions/ratios (e.g. a GL warper only takes 2^n x 2^n images). Furthermore, QuickTime GraphWorld rasters are padded on some platforms. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
If you want to warp an image, it is therefore recommended that you check what are the closest suitable dimensions for the type of warper you are using.
Parameters
imgWidth input image width
imgHeight input image height
lowImgWidth closest lower suitable width
lowImgHeight closest lower suitable height
highImgWidth closest higher suitable width
highImgHeight closest higher suitable height
Implemented in uriVL::ImageWarper_GL.
Referenced by uriVL::WarpMatchScoreFunctionND::getImageSuitableDimensions(), uriVL::WarpMatchScoreFunctionND::setImage(), and setImages().
InnerWarpingMode ImageWarper::getInnerWarpingMode (void) const
Returns the warper's inner warping mode.
Definition at line 223 of file ImageWarper.cpp.
References innerMode_.
Referenced by uriVL::WarpMatchScoreFunctionND::WarpMatchScoreFunctionND().
 {
     return innerMode_;
 }
const RasterImage * ImageWarper::getInputImage (void) const
Returns the warper's input image.
Definition at line 233 of file ImageWarper.cpp.
References imgIn_.
 {
     return imgIn_;
 }
int ImageWarper::getNbGridCols (void) const
Returns the number of columns on this warper's grid.
Definition at line 188 of file ImageWarper.cpp.
References gridCols_.
Referenced by uriVL::PatternMatcher2D_warp::PatternMatcher2D_warp(), and uriVL::WarpMatchScoreFunctionND::WarpMatchScoreFunctionND().
 {
         return gridCols_;
 }
int ImageWarper::getNbGridRows (void) const
Returns the number of rows on this warper's grid.
Definition at line 183 of file ImageWarper.cpp.
References gridRows_.
Referenced by uriVL::PatternMatcher2D_warp::PatternMatcher2D_warp(), and uriVL::WarpMatchScoreFunctionND::WarpMatchScoreFunctionND().
 {
         return gridRows_;
 }
RasterImage * ImageWarper::getOutputImage (void) const
Returns the warper's output image.
Definition at line 238 of file ImageWarper.cpp.
References imgOut_.
 {
     return imgOut_;
 }
ImageWarperType ImageWarper::getWarperType (void) const
Indicates the type of warping algorithm used by this warper (e.g.
OpenGL)
Definition at line 97 of file ImageWarper.cpp.
References warperType_.
 {
     return warperType_;
 }
void ImageWarper::initializeGrids_ (void) protected
Initializes the grids once its dimensions and that of the image are known.
Definition at line 316 of file ImageWarper.cpp.
References gridCols_, gridRows_, horizontalSpacing_, imgHeight_, imgWidth_, isSetUp_, verticalSpacing_, xy0_, and xy_.
Referenced by setGrid(), and setImages().
 {
         verticalSpacing_ = (1.f * imgHeight_) / (gridRows_ - 1),
         horizontalSpacing_ = (1.f * imgWidth_) / (gridCols_ - 1);
         for (int i=0; i<gridRows_; i++)
         {
 //jyh
 //              int ip1 = i + 1;
                 for (int j=0; j<gridCols_; j++)
                 {
                         // point grid x and y calculations
                         xy_[i][j][0] = xy0_[i][j][0] = (int)(j * horizontalSpacing_ + 0.5f);
                         xy_[i][j][1] = xy0_[i][j][1] = (int)(i * verticalSpacing_ + 0.5f);
                 }
         }
         isSetUp_ = true;
 }
bool ImageWarper::isSetUp (void) const
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
Definition at line 193 of file ImageWarper.cpp.
References isSetUp_.
 {
         return isSetUp_;
 }
bool ImageWarper::isValidDisplacement (float *** xy) const virtual
Indicates whether a point grid is consistent with the displacement modes of of this warper.
Parameters
xy grid to validate
Returns
true if the point coordinates are appropriate for this warper
Definition at line 251 of file ImageWarper.cpp.
References uriVL::BORDER_FREE, uriVL::INNER_FREE, innerMode_, and outerMode_.
Referenced by myMouse(), and warp().
 {
     bool    isValid = true;
     if (innerMode_ != INNER_FREE)
     {
     }
     if (outerMode_ != BORDER_FREE)
     {
     }
     return isValid;
 }
bool uriVL::ImageWarper::isValidDisplacement_ (const float ***const xy) const protected
Checks whether the grid coordinates specified conform to the grid displacement modes set.
Parameters
grid displacement array to check
See also
innerMode_
outerMode_
float ***const ImageWarper::newWarpingGrid (void) const
Returns a new grid of points allocated at the grid dimensions of this warper and initialized as a regular rectangular grid.
This function can only be called after the grid dimensions and input image have been set. The user is responsible for deleting this grid when it is not needed anymore.
Returns
a new warping grid to be used with this warper
Definition at line 198 of file ImageWarper.cpp.
References FAIL_CONDITION, gridCols_, gridRows_, isSetUp_, uriVL::kNoninitializedObjectError, and xy0_.
Referenced by uriVL::WarpMatchScoreFunctionND::newWarpingGrid(), uriVL::WarpMatchScoreFunctionND::setImage(), and setupWarper().
 {
     FAIL_CONDITION( !isSetUp_,
                     kNoninitializedObjectError,
                     "A Warper must be completely set up before it can produce a new grid");
     float*** grid = new float** [gridRows_];
     for (int i=0; i<gridRows_; i++)
     {
         grid[i] = new float*[gridCols_];
         for (int j=0; j<gridCols_; j++)
             grid[i][j] = new float[2];
     }
     for (int i=0; i<gridRows_; i++)
     {
         for (int j=0; j<gridCols_; j++)
         {
                         grid[i][j][0] = xy0_[i][j][0];
                         grid[i][j][1] = xy0_[i][j][1];
         }
     }
     return grid;
 }
const ImageWarper & ImageWarper::operator= (const ImageWarper & obj) protected
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 87 of file ImageWarper.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageWarper copy operator not implemented.");
         return *this;
 }
void ImageWarper::setGrid (int gridRows, int gridCols) virtual
Sets the dimensions of the warping grid (should be at least 3x3)
Parameters
gridRows number of rows of the warping grid
gridCols number of columns of the warping grid
Reimplemented in uriVL::ImageWarper_GL.
Definition at line 155 of file ImageWarper.cpp.
References allocateGrids_(), deleteGrids_(), FAIL_CONDITION, gridCols_, gridRows_, imgIn1D_, initializeGrids_(), and uriVL::kInvalidParameterError.
Referenced by uriVL::ImageWarper_GL::setGrid(), and uriVL::WarpMatchScoreFunctionND::WarpMatchScoreFunctionND().
 {
     FAIL_CONDITION(     gridRows < 3 || gridCols < 3,
                     kInvalidParameterError,
                     "gridRows and gridCols must >= 3");
     //  if the user changed the grid's dimensions, we must delete the
     //  old grids first
     if ((gridRows != gridRows_) || (gridCols != gridCols_))
         deleteGrids_();
     //  set the grid's dimensions
         gridRows_ = gridRows;
         gridCols_ = gridCols;
     allocateGrids_();
     //  if an image was previously set, we can also initialize the grid
     if (imgIn1D_ != NULL)
         initializeGrids_();
 }
void ImageWarper::setImages (const RasterImage * imgIn, RasterImage * imgOut) virtual
Defines an input image and an output image(for multiple warpings).
Note that the dimensions of the image must be in agreement with values produced by imageEffectiveDimensions: Some warpers require specific image dimensios/ratios (e.g. a GL warper only takes 2^n x 2^n images). Furthermore, QuickTime GraphWorld rasters are padded on some platforms. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
Parameters
imgIn input image for (multiple) subsequent warpings
Reimplemented in uriVL::ImageWarper_GL.
Definition at line 106 of file ImageWarper.cpp.
References uriVL::DrawableObject2D::contains(), effImgWidth_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getBoundRect(), getEffectivePixelsPerRow(), uriVL::DrawableObject2D::getHeight(), getImageSuitableDimensions(), uriVL::RasterImage::getRaster(), uriVL::DrawableObject2D::getWidth(), imgHeight_, imgIn1D_, imgIn_, imgOut1D_, imgOut_, imgWidth_, initializeGrids_(), uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, uriVL::R_W_ACCESS, rasterType_, uriVL::DrawableObject2D::setBoundRect(), and xy_.
Referenced by uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::ImageWarper_GL::setImages(), and warp().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null input image assigned to an ImageWarper");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output image assigned to an ImageWarper");
     //  So far we only warp RGBa32 and gray rasters
         BaseRasterType  rasterType = imgIn->getBaseRasterType();
     FAIL_CONDITION((rasterType != kGrayRaster) && (rasterType != kRGBa32Raster),
                     kInvalidParameterError,
                     "only RGBa32 and gray rasters supported yet");
     FAIL_CONDITION( imgOut->getBaseRasterType() != rasterType,
                     kInvalidParameterError,
                     "input and output raster types must match (so far)");
         rasterType_ = rasterType;
     //  Verify that the input image specified has dimensions that are
     //  suitable to the warper
     const int   imgHeight = imgIn->getHeight(),
                 imgWidth = imgIn->getWidth();
     int     loWidth, hiWidth, loHeight, hiHeight;
     getImageSuitableDimensions(imgWidth, imgHeight, &loWidth, &loHeight, &hiWidth, &hiHeight);
     FAIL_CONDITION(((loWidth != imgWidth) && (hiWidth != imgWidth)) ||
                    ((loHeight != imgHeight) && (hiHeight != imgHeight)),
                     kInvalidParameterError,
                     "input image has improper dimensions for warping");
     imgWidth_ = imgWidth;
     imgHeight_ = imgHeight;
     effImgWidth_ = getEffectivePixelsPerRow(imgWidth);
     imgIn_ = imgIn;
     imgIn1D_ = imgIn->getRaster();
     //  make sure that the output image is large enough to store the result
     //  of the warping
     if (!imgOut->contains(imgIn))
         imgOut->setBoundRect(imgIn->getBoundRect());
     imgOut_ = imgOut;
     imgOut1D_ = imgOut->getRaster(R_W_ACCESS);
 //    imgOut_->setValidRect(imgIn->getValidRect());
     //  if grid dimensions were previously set, we can now initialize the grids
     if (xy_ != NULL)
         initializeGrids_();
 }
void ImageWarper::warp (float *** xy, const RasterImage * imgIn, RasterImage * imgOut)
Warps the image.
If this warper's grid motion modes are other than INNER_FREE and BORDER_FREE then will only apply a warping that is conform to its motion modes. Note that the dimensions of the image must be in agreement with values produced by imageEffectiveDimensions: Some warpers require specific image dimensions/ratios (e.g. a GL warper only takes 2^n x 2^n images).
Parameters
xy new coordinates of the grid points
imgIn input image
imgOut output image
See also
setImage
Definition at line 266 of file ImageWarper.cpp.
References FAIL_CONDITION, isValidDisplacement(), uriVL::kInvalidParameterError, uriVL::kNoninitializedObjectError, uriVL::kNullParameterError, setImages(), warp_(), and xy_.
Referenced by applyWarp(), and uriVL::WarpMatchScoreFunctionND::func().
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null grid coordinate array passed to ImageWarper::warp");
     FAIL_CONDITION( xy_ == NULL,
                     kNoninitializedObjectError,
                     "A warping grid must be specified before images can be warped");
     FAIL_CONDITION( !isValidDisplacement(xy),
                     kInvalidParameterError,
                     "Grid displacement specified not conform to this warper's grid modes");
     setImages(imgIn, imgOut);
     warp_(xy);
 }
void ImageWarper::warp (float *** xy)
warp the image using the new grid point coordinates specified
Parameters
xy new coordinates of the grid points
Definition at line 284 of file ImageWarper.cpp.
References FAIL_CONDITION, isSetUp_, isValidDisplacement(), uriVL::kInvalidParameterError, uriVL::kNoninitializedObjectError, and warp_().
 {
     FAIL_CONDITION( !isSetUp_,
                     kNoninitializedObjectError,
                     "A Warper must be completely set up before it can be used");
     FAIL_CONDITION( !isValidDisplacement(xy),
                     kInvalidParameterError,
                     "Grid displacement specified not conform to this warper's grid modes");
     warp_(xy);
 }
virtual void uriVL::ImageWarper::warp_ (float *** xy) protected pure virtual
warp the (pre-specified) input image into the (prespecified) output image using the new grid point coordinates specified
Parameters
xy new coordinates of the grid points
Implemented in uriVL::ImageWarper_GL.
Referenced by warp().
Member Data Documentation
int uriVL::ImageWarper::effImgWidth_ protected
Effective width of the image to warp (taking into account row padding)
Definition at line 226 of file ImageWarper.h.
Referenced by setImages().
int uriVL::ImageWarper::gridCols_ protected
number of cols of the warping grid
Definition at line 238 of file ImageWarper.h.
Referenced by allocateGrids_(), deleteGrids_(), getNbGridCols(), initializeGrids_(), newWarpingGrid(), uriVL::ImageWarper_GL::setGrid(), setGrid(), uriVL::ImageWarper_GL::setImages(), uriVL::ImageWarper_GL::warp_(), and uriVL::ImageWarper_GL::~ImageWarper_GL().
int uriVL::ImageWarper::gridRows_ protected
number of rows of the warping grid
Definition at line 234 of file ImageWarper.h.
Referenced by allocateGrids_(), deleteGrids_(), getNbGridRows(), initializeGrids_(), newWarpingGrid(), uriVL::ImageWarper_GL::setGrid(), setGrid(), uriVL::ImageWarper_GL::setImages(), uriVL::ImageWarper_GL::warp_(), and uriVL::ImageWarper_GL::~ImageWarper_GL().
float uriVL::ImageWarper::horizontalSpacing_ protected
distance between horizontal grid points
Definition at line 254 of file ImageWarper.h.
Referenced by initializeGrids_().
int uriVL::ImageWarper::imgHeight_ protected
Height of the image to warp.
Definition at line 218 of file ImageWarper.h.
Referenced by initializeGrids_(), uriVL::ImageWarper_GL::setGrid(), uriVL::ImageWarper_GL::setImages(), setImages(), and uriVL::ImageWarper_GL::warp_().
const unsigned char* uriVL::ImageWarper::imgIn1D_ protected
1D raster of the texture image
Definition at line 266 of file ImageWarper.h.
Referenced by uriVL::ImageWarper_GL::setGrid(), setGrid(), uriVL::ImageWarper_GL::setImages(), and setImages().
const RasterImage* uriVL::ImageWarper::imgIn_ protected
texture image
Definition at line 258 of file ImageWarper.h.
Referenced by getInputImage(), and setImages().
unsigned char* uriVL::ImageWarper::imgOut1D_ protected
1D raster of output image
Definition at line 270 of file ImageWarper.h.
Referenced by setImages(), and uriVL::ImageWarper_GL::warp_().
RasterImage* uriVL::ImageWarper::imgOut_ protected
output image
Definition at line 262 of file ImageWarper.h.
Referenced by getOutputImage(), and setImages().
int uriVL::ImageWarper::imgWidth_ protected
Width of the image to warp.
Definition at line 222 of file ImageWarper.h.
Referenced by initializeGrids_(), uriVL::ImageWarper_GL::setGrid(), and setImages().
InnerWarpingMode uriVL::ImageWarper::innerMode_ protected
Warping mode if the grid's inner points.
Definition at line 205 of file ImageWarper.h.
Referenced by getInnerWarpingMode(), and isValidDisplacement().
bool uriVL::ImageWarper::isSetUp_ protected
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
Definition at line 214 of file ImageWarper.h.
Referenced by initializeGrids_(), isSetUp(), newWarpingGrid(), and warp().
BorderWarpingMode uriVL::ImageWarper::outerMode_ protected
Warping mode if the grid's border points.
Definition at line 209 of file ImageWarper.h.
Referenced by getBorderWarpingMode(), and isValidDisplacement().
BaseRasterType uriVL::ImageWarper::rasterType_ protected
Type of the input image's raster (only RGBa32 and gray supported so far)
Definition at line 230 of file ImageWarper.h.
Referenced by uriVL::ImageWarper_GL::setImages(), setImages(), and uriVL::ImageWarper_GL::warp_().
float uriVL::ImageWarper::verticalSpacing_ protected
distance between vertical grid points
Definition at line 250 of file ImageWarper.h.
Referenced by initializeGrids_().
ImageWarperType uriVL::ImageWarper::warperType_ protected
Indicates the type of warping algorithm used by this warper (e.g.
OpenGL)
Definition at line 201 of file ImageWarper.h.
Referenced by getWarperType().
float*** uriVL::ImageWarper::xy0_ protected
gridRows_ x gridCols_ array of original 2D grid points
Definition at line 246 of file ImageWarper.h.
Referenced by allocateGrids_(), deleteGrids_(), initializeGrids_(), and newWarpingGrid().
float*** uriVL::ImageWarper::xy_ protected
gridRows_ x gridCols_ array of 2D grid points
Definition at line 242 of file ImageWarper.h.
Referenced by allocateGrids_(), deleteGrids_(), initializeGrids_(), setImages(), and warp().
The documentation for this class was generated from the following files:
ImageWarper.h
ImageWarper.cpp