URIVisionLibrary: uriVL::Box3D Class Reference
uriVL::Box3D Class Reference
Box3D class.
#include <Box3D.h>
Public Member Functions
Box3D (GLfloat *origin, GLfloat **axes, bool isClosed)
Constructor.
~Box3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Inoperative for this type of object (for the time being)
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
Box3D (const Box3D &obj)
Copy constructor (disabled)
const Box3D & operator= (const Box3D &obj)
Copy operator: disabled.
void init_ (GLfloat *origin, GLfloat **axes)
Initialize the box.
void deleteArrays_ (void)
Delete all allocated arrays.
Private Attributes
GLfloat ** vertex_
0-based list of vertices
GLfloat ** normal_
0-based list of normals
bool closedBox_
Is the box closed? (top and bottom faces are drawn)
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
Box3D class.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 44 of file Box3D.h.
Constructor & Destructor Documentation
Box3D::Box3D (GLfloat * origin, GLfloat ** axes, bool isClosed)
Constructor.
Parameters
origin coordinates of the box's origin (at one corner of the box)
axes the 3 axes of the box
isClosed true if the box's top and bottom faces should be drawn
Definition at line 37 of file Box3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), and init_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(GlUtils::glfMatrix(0, 7, 0, 2)),
                         normal_(isClosed ? GlUtils::glfMatrix(0, 5, 0, 2) : GlUtils::glfMatrix(0, 3, 0, 2)),
                         closedBox_(isClosed)
 {
         try {
                 init_(origin, axes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from Box3D constructor.");
                 throw e;
         }
 }
Box3D::~Box3D (void)
Destructor.
Definition at line 76 of file Box3D.cpp.
References deleteArrays_().
 {
         deleteArrays_();
 }
Box3D::Box3D (const Box3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 55 of file Box3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         closedBox_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Box3D copy constructor not implemented.");
 }
Member Function Documentation
void Box3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 244 of file Box3D.cpp.
References closedBox_, uriVL::GlUtils::free_glfMatrix(), normal_, and vertex_.
Referenced by Box3D(), and ~Box3D().
 {
         if (vertex_!=NULL)
         {
                 GlUtils::free_glfMatrix(vertex_, 0, 7, 0, 2);
                 vertex_ = NULL;
         }
         if (normal_!=NULL)
         {
                 if (closedBox_)
                         GlUtils::free_glfMatrix(normal_, 0,  5, 0, 2);
                 else
                         GlUtils::free_glfMatrix(normal_, 0,  3, 0, 2);
         }
 }
void Box3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 128 of file Box3D.cpp.
References closedBox_, uriVL::GraphicComponent3D::draw(), normal_, and vertex_.
 {
         int     i;
         GraphicComponent3D::draw();
         glBegin(GL_QUADS);
                 glNormal3fv(normal_[0]);
                 glVertex3fv(vertex_[4]);
                 glVertex3fv(vertex_[0]);
                 glVertex3fv(vertex_[1]);
                 glVertex3fv(vertex_[5]);
                 //
                 glNormal3fv(normal_[1]);
                 glVertex3fv(vertex_[5]);
                 glVertex3fv(vertex_[1]);
                 glVertex3fv(vertex_[2]);
                 glVertex3fv(vertex_[6]);
                 //
                 glNormal3fv(normal_[2]);
                 glVertex3fv(vertex_[6]);
                 glVertex3fv(vertex_[2]);
                 glVertex3fv(vertex_[3]);
                 glVertex3fv(vertex_[7]);
                 //
                 glNormal3fv(normal_[3]);
                 glVertex3fv(vertex_[7]);
                 glVertex3fv(vertex_[3]);
                 glNormal3fv(normal_[0]);
                 glVertex3fv(vertex_[0]);
                 glVertex3fv(vertex_[4]);
         glEnd();
         if (closedBox_)
         {
                 glBegin(GL_QUADS);
                         glNormal3fv(normal_[4]);
                         for (i=4; i<8; i++)
                                 glVertex3fv(vertex_[i]);
                         //
                         glNormal3fv(normal_[5]);
                         for (i=3; i>=0; i--)
                                 glVertex3fv(vertex_[i]);
                 glEnd();
         }
 }
void Box3D::init_ (GLfloat * origin, GLfloat ** axes) private
Initialize the box.
Parameters
origin coordinates of the box's origin (at one corner of the box)
axes the 3 axes of the box
Definition at line 197 of file Box3D.cpp.
References closedBox_, uriVL::GraphicComponent3D::commonNormalVector(), FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, normal_, and vertex_.
Referenced by Box3D().
 {
         int             k;
         FAIL_CONDITION( (origin == NULL) || (a == NULL),
                                         kNullParameterError,
                                         "null array passed to Box3D::init_");
         try {
                 commonNormalVector(a[0], a[2], normal_[0]);
                 commonNormalVector(a[1], a[2], normal_[1]);
                 for (k=0; k<3; k++)
                 {
                         vertex_[0][k] = origin[k];
                         vertex_[1][k] = origin[k] + a[0][k];
                         vertex_[3][k] = origin[k] + a[1][k];
                         vertex_[2][k] = vertex_[1][k] + a[1][k];
                         //
                         vertex_[4][k] = origin[k] + a[2][k];
                         vertex_[5][k] = vertex_[4][k] + a[0][k];
                         vertex_[7][k] = vertex_[4][k] + a[1][k];
                         vertex_[6][k] = vertex_[5][k] + a[1][k];
                         normal_[2][k] = -normal_[0][k];
                         normal_[3][k] = -normal_[1][k];
                 }
                 //      if this is a closed box, then we must also compute the normal
                 //      vector for the top and bottom faces.
                 if (closedBox_)
                 {
                         commonNormalVector(a[0], a[1], normal_[4]);
                         for (k=0; k<3; k++)
                                 normal_[5][k] = - normal_[4][k];
                 }
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid array passed to Box3D::init_");
         }
 }
const Box3D & Box3D::operator= (const Box3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 81 of file Box3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Box3D copy operator not implemented.");
         return *this;
 }
void Box3D::setResolution (ResolutionLevel res) virtual
Inoperative for this type of object (for the time being)
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 111 of file Box3D.cpp.
 {
 //      setResolution(res, res);
 }
Member Data Documentation
bool uriVL::Box3D::closedBox_ private
Is the box closed? (top and bottom faces are drawn)
Definition at line 81 of file Box3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat** uriVL::Box3D::normal_ private
0-based list of normals
Definition at line 76 of file Box3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat** uriVL::Box3D::vertex_ private
0-based list of vertices
Definition at line 72 of file Box3D.h.
Referenced by deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
Box3D.h
Box3D.cpp