URIVisionLibrary: uriVL::Cluster Class Reference
uriVL::Cluster Class Reference
Cluster using average distance.
#include <Cluster.h>
Public Member Functions
Cluster (Blob *blob)
Default constructor.
~Cluster (void)
Destructor.
void join (Cluster *cluster)
double distance (Cluster *cluster)
Blob ** getBlobList (void)
int getNbBlobs (void)
Private Member Functions
Cluster (const Cluster &obj)
Copy constructor (disabled)
const Cluster & operator= (const Cluster &obj)
Copy operator: disabled.
Private Attributes
Blob ** blobList_
int nbBlobs_
Detailed Description
Cluster using average distance.
Definition at line 38 of file Cluster.h.
Constructor & Destructor Documentation
Cluster::Cluster (Blob * blob)
Default constructor.
Constructor
Definition at line 35 of file Cluster.cpp.
 {
 /*
         blobList_.clear();
         blobList_.push_back(blob);
 */
         blobList_ = new Blob*[1];
         blobList_[0] = blob;
         nbBlobs_ = 1;
 }
Cluster::~Cluster (void)
Destructor.
Definition at line 46 of file Cluster.cpp.
 {
 /*
         if(!blobList_.empty())
                 blobList_.erase(blobList_.begin(), blobList_.end());
 */
         delete blobList_;
 }
Cluster::Cluster (const Cluster & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 55 of file Cluster.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         closedBox_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cluster copy constructor not implemented.");
 }
Member Function Documentation
double Cluster::distance (Cluster * cluster)
Definition at line 112 of file Cluster.cpp.
References blobList_, uriVL::DrawableObject2D::getCentroid(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and nbBlobs_.
 {
 /*
         BlobList::iterator iter1        = cl->getBlobList().begin(),
                                                 iter2   = blobList_.begin();
         float   avg1 = 0.f;
         for( ; iter1 != cl->getBlobList().end(); iter1++){
                 float avg2 = 0.f;
                 for( ; iter2 != blobList_.end(); iter2++){
                         avg2 += sqrt(  ((*iter1)->getCentroid()->getX() - (*iter2)->getCentroid()->getX())
                                                         * ((*iter1)->getCentroid()->getX() - (*iter2)->getCentroid()->getX())
                                                  + ((*iter1)->getCentroid()->getY() - (*iter2)->getCentroid()->getY())
                                                         * ((*iter1)->getCentroid()->getY() - (*iter2)->getCentroid()->getY()));
                 }
                 avg2 /= blobList_.size();
                 avg1 += avg2;
         }
         avg1 /= cl->getBlobList().size();
 */
         float   avg1 = 0.f;
         for(int i=0; i<cl->nbBlobs_; i++) {
                 float avg2 = 0.f;
                 for (int j=0; j<nbBlobs_; j++) {
                         avg2 += sqrt(  (cl->blobList_[i]->getCentroid()->getX() - blobList_[j]->getCentroid()->getX())
                                                         * (cl->blobList_[i]->getCentroid()->getX() - blobList_[j]->getCentroid()->getX())
                                                  + (cl->blobList_[i]->getCentroid()->getY() - blobList_[j]->getCentroid()->getY())
                                                         * (cl->blobList_[i]->getCentroid()->getY() - blobList_[j]->getCentroid()->getY()));
                 }
                 avg2 /= nbBlobs_;
                 avg1 += avg2;
         }
         avg1 /= cl->nbBlobs_;
         return avg1;
 }
Blob ** Cluster::getBlobList (void)
Definition at line 158 of file Cluster.cpp.
References blobList_.
 {
         return blobList_;
 }
int Cluster::getNbBlobs (void)
Definition at line 162 of file Cluster.cpp.
References nbBlobs_.
 {
         return nbBlobs_;
 }
void Cluster::join (Cluster * cluster)
Definition at line 87 of file Cluster.cpp.
References blobList_, and nbBlobs_.
 {
 /*
 cout << "joining to a list with " << blobList_.size() << "elements "
      << "a list with " << cl->getBlobList().size() << " elements" << endl;
 int i=0;
         BlobList::iterator iter = (cl->getBlobList()).begin();
         for( ; (iter != (cl->getBlobList()).end()) &&
                         (i < (cl->getBlobList()).size()); iter++)
         {
                 cout << "in join" << " i = " << i++ << endl;
                 blobList_.push_back(*iter);
         }
 */
         Blob** temp = new Blob*[nbBlobs_ + cl->nbBlobs_];
         for (int i=0; i<nbBlobs_; i++)
                 temp[i] = blobList_[i];
         for (int i=0; i<cl->nbBlobs_; i++)
                 temp[i + nbBlobs_] = cl->blobList_[i];
         nbBlobs_ += cl->nbBlobs_;
         delete []blobList_;
         blobList_ = temp;
 }
const Cluster & Cluster::operator= (const Cluster & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 69 of file Cluster.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cluster copy operator not implemented.");
         return *this;
 }
Member Data Documentation
Blob** uriVL::Cluster::blobList_ private
Definition at line 79 of file Cluster.h.
Referenced by distance(), getBlobList(), and join().
int uriVL::Cluster::nbBlobs_ private
Definition at line 80 of file Cluster.h.
Referenced by distance(), getNbBlobs(), and join().
The documentation for this class was generated from the following files:
Cluster.h
Cluster.cpp