URIVisionLibrary: uriVL::ImageTransformation Class Reference
uriVL::ImageTransformation Class Reference
This class only contains static functions to rotate, scale, skew, and translate images.
#include <ImageTransformation.h>
Static Public Member Functions
static RasterImage * translate (const RasterImage *imgIn, int dx, int dy)
Produces a new RasterImage object that is obtained by translating the in put image by the amounts specified.
static void translateInPlace (RasterImage *imgIn, int dx, int dy)
Applies in-place translation to the image received as parameter by the amounts specified.
static RasterImage * scale (const RasterImage *imgIn, float sx, float sy, const ImagePoint *origin=NULL)
Produces a new RasterImage object that is obtained by scaling the input image by the amounts specified and from the origin specified.
static RasterImage * rotate (const RasterImage *imgIn, float angle, const ImagePoint *center=NULL)
Produces a new RasterImage object that is obtained by rotating the input image by the angle specified and around the centerspecified.
Private Member Functions
ImageTransformation (void)
Disabled default constructor.
ImageTransformation (const ImageTransformation &obj)
Disabled copy constructor.
~ImageTransformation (void)
const ImageTransformation & operator= (const ImageTransformation &obj)
Disabled copy operator.
Detailed Description
This class only contains static functions to rotate, scale, skew, and translate images.
The constructors and = operator are private and should not be implemented.
Definition at line 29 of file ImageTransformation.h.
Constructor & Destructor Documentation
uriVL::ImageTransformation::ImageTransformation (void) inline private
Disabled default constructor.
Definition at line 97 of file ImageTransformation.h.
 { }
uriVL::ImageTransformation::ImageTransformation (const ImageTransformation & obj) inline private
Disabled copy constructor.
Parameters
obj the object not to copy
Definition at line 102 of file ImageTransformation.h.
 { }
uriVL::ImageTransformation::~ImageTransformation (void) inline private
Definition at line 104 of file ImageTransformation.h.
 { }
Member Function Documentation
const ImageTransformation& uriVL::ImageTransformation::operator= (const ImageTransformation & obj) inline private
Disabled copy operator.
Parameters
obj the object not to copy
Returns
should not
Definition at line 110 of file ImageTransformation.h.
 { return *this; }
RasterImage * ImageTransformation::rotate (const RasterImage * imgIn, float angle, const ImagePoint * center = NULL) static
Produces a new RasterImage object that is obtained by rotating the input image by the angle specified and around the centerspecified.
Note that:
If no center is pecified, or if a NULL pointer is passed for the center, then the rotatio is performed around the geometric center of the image's valid data rectangle.
Rotation angles are measured counterclockwise in degree.
Dimensions of the rotated image are converted to nearest ≤ integer.
Note that for For 1-bit images (such as RasterImage_binary objects), the only admissible values for the rotation angle are multiple of 90° (e.g. –90, 90, 180, 270). A NULL value is returned for other angles.
Parameters
imgIn the image to apply the rotation to
angle counterclockwise rotation angle in degree
center pointer to the point around which the rotation will be perfomed
Returns
pointer to the rotated image produced;
Definition at line 109 of file ImageTransformation.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kBinaryRaster, uriVL::kFunctionNotImplemented, and uriVL::kImageProcessingError.
 {
         RasterImage* imgOut = NULL;
         try
         {
                 //      First, treat the case of an attempt to rotate a binary image by an
                 //      angle that is not a multiple of 90 degree --> return NULL
                 BaseRasterType rasterType = imgIn->getBaseRasterType();
                 if (rasterType == kBinaryRaster)
                 {
                         const float angleDiv90 = angle/90.f;
                         if (floorf(angleDiv90) != angleDiv90)
                                 return NULL;
                 }
                 //      All other cases
                 #if URIVL_USE_QUICKTIME
                         return _ImageTransformation_QT::rotate_(imgIn, angle, center);
                 #elif URIVL_USE_FREEIMAGE
                         return _ImageTransformation_FreeImage::rotate_(imgIn, angle, center);
                 #else
                         FAIL_CONDITION( true,
                                                         kFunctionNotImplemented,
                                                         "Only the QuickTime and FreeImage versions implement ImageTransformation::rotate");
                 #endif
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageTransformation::rotate");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Unexpected error encountered in ImageTransformation::rotate");
         }
         return imgOut;
 }
RasterImage * ImageTransformation::scale (const RasterImage * imgIn, float sx, float sy, const ImagePoint * origin = NULL) static
Produces a new RasterImage object that is obtained by scaling the input image by the amounts specified and from the origin specified.
Note that:
If no origin is pecified, or if a NULL pointer is passed for the origin, then the scaling is done from (0, 0).
Negative scaling along a direction will result in flipping the image along that direction.
Dimensions of the scaled image are converted to nearest ≤ integer, so that any image produced by this function will be at least 1 x 1.
Parameters
imgIn the image to apply the scaling to
sx amount of scaling along the horizontal axis
sy amount of scaling along the vertical axis
origin pointer to the point from which the scaling will be perfomed
Returns
pointer to the scaled image produced;
Definition at line 74 of file ImageTransformation.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kFunctionNotImplemented, and uriVL::kImageProcessingError.
 {
         RasterImage* imgOut = NULL;
         try
         {
                 #if URIVL_USE_QUICKTIME
                 #elif URIVL_USE_FREEIMAGE
                 #else
                         FAIL_CONDITION( true,
                                                         kFunctionNotImplemented,
                                                         "Only the QuickTime and FreeImage versions implement ImageTransformation::scale");
                 #endif
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageTransformation::scale");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Unexpected error encountered in ImageTransformation::scale");
         }
         return imgOut;
 }
RasterImage * ImageTransformation::translate (const RasterImage * imgIn, int dx, int dy) static
Produces a new RasterImage object that is obtained by translating the in put image by the amounts specified.
In practice, in RI this is done by translating the bounding and valid data rects of the destination image.
Parameters
imgIn the image to apply the translation to
dx amount of translation along the horizontal axis
dy amount of translation along the vertical axis
Returns
pointer to the translated image produced;
Definition at line 23 of file ImageTransformation.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::createCopy(), FAIL_CONDITION, uriVL::kImageProcessingError, and uriVL::DrawableObject2D::translate().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 imgOut = RasterImage::createCopy(imgIn);
                 imgOut->translate(dx, dy);
         }
         catch (ErrorReport& e)
         {
                 if (imgOut != NULL)
                         delete imgOut;
                 imgOut = NULL;
                 e.appendToMessage("called by ImageTransformation::translate");
                 throw e;
         }
         catch (...)
         {
                 if (imgOut != NULL)
                         delete imgOut;
                 imgOut = NULL;
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Unexpected error encountered in ImageTransformation::translate");
         }
         return imgOut;
 }
void ImageTransformation::translateInPlace (RasterImage * imgIn, int dx, int dy) static
Applies in-place translation to the image received as parameter by the amounts specified.
In practice, in RI this is done by translating the bounding and valid data rects of the image.
Parameters
imgIn the image to apply the translation to
dx amount of translation along the horizontal axis
dy amount of translation along the vertical axis
Definition at line 55 of file ImageTransformation.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kImageProcessingError, and uriVL::DrawableObject2D::translate().
 {
         try
         {
                 imgIn->translate(dx, dy);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageTransformation::translateInPlace");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Unexpected error encountered in ImageTransformation::translateInPlace");
         }
 }
The documentation for this class was generated from the following files:
ImageTransformation.h
ImageTransformation.cpp