URIVisionLibrary: uriVL::Camera Class Reference
uriVL::Camera Class Reference abstract
The base virtual Camera class.
#include <Camera.h>
Public Member Functions
virtual ~Camera (void)
Non-operative destructor.
int getWidth (void)
Returns the width (in pixels) of the raster digitized.
int getHeight (void)
Returns the height (in pixels) of the raster digitized.
void getImagePoint (const float X, const float Y, const float Z, float *x, float *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double X, const double Y, const double Z, double *x, double *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const float *XYZ, float *x, float *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double *XYZ, double *x, double *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const float *XYZ, float *xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double *XYZ, double *xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const float X, const float Y, const float Z, float *xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double X, const double Y, const double Z, double *xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const Point3D *pt3D, float *x, float *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const Point3D *pt3D, double *x, double *y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const Point3D *pt3D, ImagePoint_F *imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const float *XYZ, ImagePoint_F *imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double *XYZ, ImagePoint_F *imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const float X, const float Y, const float Z, ImagePoint_F *imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
void getImagePoint (const double X, const double Y, const double Z, ImagePoint_F *imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
ImagePoint_F * getImagePoint (const float *XYZ)
Computes the image projection of the 3D point whose coordinates were received as parameters.
ImagePoint_F * getImagePoint (const double *XYZ)
Computes the image projection of the 3D point whose coordinates were received as parameters.
ImagePoint_F * getImagePoint (const float X, const float Y, const float Z)
Computes the image projection of the 3D point whose coordinates were received as parameters.
ImagePoint_F * getImagePoint (const double X, const double Y, const double Z)
Computes the image projection of the 3D point whose coordinates were received as parameters.
const RigidTransformation3D * getCamToWorldTransf (void)
Returns the transformation from this camera's reference frame to the world reference frame, in read-only form.
RigidTransformation3D * getCamToWorldTransf (ReadWriteStatus rwa)
Returns the transformation from this camera's reference frame to the world reference frame, in writable form.
void setCamToWorldTransf (RigidTransformation3D *transf)
Sets "to-world" transformation fpor this camera.
const IntrinsicParameters * getIntrinsicParameters (void) const
Returns the camera's intrinsic parameters, in read-only form.
IntrinsicParameters * getIntrinsicParameters (ReadWriteStatus rwa) const
Returns the camera's intrinsic parameters, in writeable form.
Public Member Functions inherited from uriVL::Entity3D
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Protected Member Functions
Camera (IntrinsicParameters *params, RigidTransformation3D *transf=NULL)
Rigid transformation (rotation * translation between the two cameras)
virtual void getImagePoint_ (const float X, const float Y, const float Z, float *x, float *y)=0
Computes the image projection of the 3D point whose coordinates were received as parameters.
virtual void getImagePoint_ (const double X, const double Y, const double Z, double *x, double *y)=0
Computes the image projection of the 3D point whose coordinates were received as parameters.
Protected Member Functions inherited from uriVL::Entity3D
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Protected Attributes
RigidTransformation3D * cam2World_
Transformation from camera to world reference frame.
bool cam2WorldIsUpToDate_
Indicates whether the transformation from camera to world reference frame is up to date.
IntrinsicParameters * intrinsic_
Intrinsic parameters for this camera.
Private Member Functions
Camera (const Camera &obj)
Copy constructor.
const Camera & operator= (const Camera &obj)
Copy operator.
Detailed Description
The base virtual Camera class.
A Camera object projects geometric 3D points onto the image plane to get 2D image points. This class provides a ridiculous number of functions performing this projection, defined for different numbers and types of parameters. A Camera object is characterized by a set of extrinsinc and intrinsic parameters.
Version history
        - 2004/06/19 [jyh]              first "implementation"
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 45 of file Camera.h.
Constructor & Destructor Documentation
Camera::~Camera (void) virtual
Non-operative destructor.
The class destructor has nothing to do.
Definition at line 41 of file Camera.cpp.
References cam2World_.
 {
     delete cam2World_;
 }
Camera::Camera (IntrinsicParameters * params, RigidTransformation3D * transf = NULL) protected
Rigid transformation (rotation * translation between the two cameras)
The new camera stores the pointer to the IntrinsicParameter object passed as parameter, but it makes a copy of the rigid transformation data.
Parameters
params pointer to intrinsic parameter object that this camera will refer to
transf rigid transformation data that this camera will make a copy of
Definition at line 19 of file Camera.cpp.
         :   Entity3D(),
             //
             cam2World_(transf != NULL ? new RigidTransformation3D(transf) : new RigidTransformation3D()),
             cam2WorldIsUpToDate_(true),
             intrinsic_(params)
 {
 }
Camera::Camera (const Camera & obj) private
Copy constructor.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 28 of file Camera.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   Entity3D(),
             //
             cam2World_(NULL),
             cam2WorldIsUpToDate_(true),
             intrinsic_(NULL)
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "Camera copy constructor not implemented");
 }
Member Function Documentation
const RigidTransformation3D * Camera::getCamToWorldTransf (void)
Returns the transformation from this camera's reference frame to the world reference frame, in read-only form.
If needed, recalculates/updates this transformation
Returns
pointer to the camera's extrinsic parameters
Definition at line 233 of file Camera.cpp.
References cam2World_.
Referenced by uriVL::VirtualObject3D::render().
 {
         return cam2World_;
 }
RigidTransformation3D * Camera::getCamToWorldTransf (ReadWriteStatus rwa)
Returns the transformation from this camera's reference frame to the world reference frame, in writable form.
If needed, recalculates/updates this transformation. Pretty much only Calibration3D and Registration3D subclasses have any business calling that one.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
pointer to the camera's extrinsic parameters
Definition at line 238 of file Camera.cpp.
References cam2World_.
 {
         return cam2World_;
 }
int Camera::getHeight (void)
Returns the height (in pixels) of the raster digitized.
Returns
height (in pixels) of the raster digitized
Definition at line 65 of file Camera.cpp.
References uriVL::IntrinsicParameters::getHeight(), and intrinsic_.
 {
         return intrinsic_ != NULL ? intrinsic_->getHeight() : 0;
 }
void Camera::getImagePoint (const float X, const float Y, const float Z, float * x, float * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
This function must be implemented by child classes. All other "float" getImagePoint methods in this class call this method (and are therefore implemented in this class.
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
x x coordinate of projected image point
y y coordinate of projected image point
Definition at line 79 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(X, Y, Z, x, y);
 }
void Camera::getImagePoint (const double X, const double Y, const double Z, double * x, double * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
This functon must be implemented by child classes. All other "double" getImagePoint methods in this class call this method (and are therefore implemented in this class.
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
x address of x coordinate of projected image point
y address of y coordinate of projected image point
Definition at line 84 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(X, Y, Z, x, y);
 }
void Camera::getImagePoint (const float * XYZ, float * x, float * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
x address of x coordinate of projected image point
y address of y coordinate of projected image point
Definition at line 89 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), and uriVL::kNullArrayError.
 {
     FAIL_CONDITION( XYZ == NULL,
                     kNullArrayError,
                     "null coordinate array passed as parameter to CAmera::getImagePoint");
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], x, y);
 }
void Camera::getImagePoint (const double * XYZ, double * x, double * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
x address of x coordinate of projected image point
y address of y coordinate of projected image point
Definition at line 97 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), and uriVL::kNullArrayError.
 {
     FAIL_CONDITION( XYZ == NULL,
                     kNullArrayError,
                     "null coordinate array passed as parameter to CAmera::getImagePoint");
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], x, y);
 }
void Camera::getImagePoint (const float * XYZ, float * xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
xy array of image coordinates of projected point
Definition at line 105 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], xy, xy+1);
 }
void Camera::getImagePoint (const double * XYZ, double * xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
xy array of image coordinates of projected point
Definition at line 110 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], xy, xy+1);
 }
void Camera::getImagePoint (const float X, const float Y, const float Z, float * xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
xy array of image coordinates of projected point
Definition at line 115 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(X, Y, Z, xy, xy+1);
 }
void Camera::getImagePoint (const double X, const double Y, const double Z, double * xy)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
xy array of image coordinates of projected point
Definition at line 120 of file Camera.cpp.
References getImagePoint_().
 {
     getImagePoint_(X, Y, Z, xy, xy+1);
 }
void Camera::getImagePoint (const Point3D * pt3D, float * x, float * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
pt3D reference to the 3D point to project
x x coordinate of projected image point
y y coordinate of projected image point
Definition at line 125 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::Point3D::getX(), uriVL::Point3D::getY(), uriVL::Point3D::getZ(), and uriVL::kNullParameterError.
 {
     FAIL_CONDITION( pt3D == NULL,
                     kNullParameterError,
                     "null 3DPoint passed as parameter to CAmera::getImagePoint");
     getImagePoint_(static_cast<float>(pt3D->getX()), static_cast<float>(pt3D->getY()),
                     static_cast<float>(pt3D->getZ()), x, y);
 }
void Camera::getImagePoint (const Point3D * pt3D, double * x, double * y)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
pt3D reference to the 3D point to project
x x coordinate of projected image point
y y coordinate of projected image point
Definition at line 134 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::Point3D::getX(), uriVL::Point3D::getY(), uriVL::Point3D::getZ(), and uriVL::kNullParameterError.
 {
     FAIL_CONDITION( pt3D == NULL,
                     kNullParameterError,
                     "null 3DPoint passed as parameter to CAmera::getImagePoint");
     getImagePoint_(pt3D->getX(), pt3D->getY(), pt3D->getZ(), x, y);
 }
void Camera::getImagePoint (const Point3D * pt3D, ImagePoint_F * imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
pt3D reference to the 3D point to project
imgPt reference to the corresponding image point
Definition at line 142 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::Point3D::getX(), uriVL::Point3D::getY(), uriVL::Point3D::getZ(), uriVL::kNullParameterError, and uriVL::ImagePoint_F::setCoordinates().
 {
     FAIL_CONDITION( pt3D == NULL,
                     kNullParameterError,
                     "null 3DPoint passed as parameter to CAmera::getImagePoint");
     FAIL_CONDITION( imgPt == NULL,
                     kNullParameterError,
                     "null ImagePoint_F passed as parameter to CAmera::getImagePoint");
     float   x, y;
     getImagePoint_(static_cast<float>(pt3D->getX()), static_cast<float>(pt3D->getY()),
                     static_cast<float>(pt3D->getZ()), &x, &y);
     imgPt->setCoordinates(x, y);
 }
void Camera::getImagePoint (const float * XYZ, ImagePoint_F * imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
imgPt reference to the corresponding image point
Definition at line 156 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::kNullParameterError, and uriVL::ImagePoint_F::setCoordinates().
 {
     FAIL_CONDITION( imgPt == NULL,
                     kNullParameterError,
                     "null ImagePoint_F passed as parameter to CAmera::getImagePoint");
     float   x, y;
     getImagePoint_(XYZ[0], XYZ[0], XYZ[2], &x, &y);
     imgPt->setCoordinates(x, y);
 }
void Camera::getImagePoint (const double * XYZ, ImagePoint_F * imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
imgPt reference to the corresponding image point
Definition at line 166 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::kNullParameterError, and uriVL::ImagePoint_F::setCoordinates().
 {
     FAIL_CONDITION( imgPt == NULL,
                     kNullParameterError,
                     "null ImagePoint_F passed as parameter to CAmera::getImagePoint");
     double   x, y;
     getImagePoint_(XYZ[0], XYZ[0], XYZ[2], &x, &y);
     imgPt->setCoordinates((float) x, (float) y);
 }
void Camera::getImagePoint (const float X, const float Y, const float Z, ImagePoint_F * imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
imgPt reference to the corresponding image point
Definition at line 176 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::kNullParameterError, and uriVL::ImagePoint_F::setCoordinates().
 {
     FAIL_CONDITION( imgPt == NULL,
                     kNullParameterError,
                     "null ImagePoint_F passed as parameter to CAmera::getImagePoint");
     float   x, y;
     getImagePoint_(X, Y, Z, &x, &y);
     imgPt->setCoordinates(x, y);
 }
void Camera::getImagePoint (const double X, const double Y, const double Z, ImagePoint_F * imgPt)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
imgPt reference to the corresponding image point
Definition at line 186 of file Camera.cpp.
References FAIL_CONDITION, getImagePoint_(), uriVL::kNullParameterError, and uriVL::ImagePoint_F::setCoordinates().
 {
     FAIL_CONDITION( imgPt == NULL,
                     kNullParameterError,
                     "null ImagePoint_F passed as parameter to CAmera::getImagePoint");
     double   x, y;
     getImagePoint_(X, Y, Z, &x, &y);
     imgPt->setCoordinates((float) x, (float) y);
 }
ImagePoint_F * Camera::getImagePoint (const float * XYZ)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
Returns
corresponding image point
Definition at line 196 of file Camera.cpp.
References getImagePoint_().
 {
     float   x, y;
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], &x, &y);
     return new ImagePoint_F(x, y);
 }
ImagePoint_F * Camera::getImagePoint (const double * XYZ)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
XYZ array of coordinates of 3D point to project
Returns
corresponding image point
Definition at line 203 of file Camera.cpp.
References getImagePoint_().
 {
     double   x, y;
     getImagePoint_(XYZ[0], XYZ[1], XYZ[2], &x, &y);
     return new ImagePoint_F((float) x, (float) y);
 }
ImagePoint_F * Camera::getImagePoint (const float X, const float Y, const float Z)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
Returns
corresponding image point
Definition at line 210 of file Camera.cpp.
References getImagePoint_().
 {
     float   x, y;
     getImagePoint_(X, Y, Z, &x, &y);
     return new ImagePoint_F(x, y);
 }
ImagePoint_F * Camera::getImagePoint (const double X, const double Y, const double Z)
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
Returns
corresponding image point
Definition at line 217 of file Camera.cpp.
References getImagePoint_().
 {
     double   x, y;
     getImagePoint_(X, Y, Z, &x, &y);
     return new ImagePoint_F((float) x, (float) y);
 }
virtual void uriVL::Camera::getImagePoint_ (const float X, const float Y, const float Z, float * x, float * y) protected pure virtual
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses float</float> numbers as parameters
This function must be implemented by child classes. All other "float" getImagePoint methods in this class call this method (and are therefore implemented in this class.
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
x x coordinate of projected image point
y y coordinate of projected image point
Implemented in uriVL::WeakPerspectiveCamera, uriVL::OrthographicCamera, and uriVL::PerspectiveCamera.
Referenced by getImagePoint().
virtual void uriVL::Camera::getImagePoint_ (const double X, const double Y, const double Z, double * x, double * y) protected pure virtual
Computes the image projection of the 3D point whose coordinates were received as parameters.
This version of the function uses double</float> numbers as parameters
This function must be implemented by child classes. All other "double" getImagePoint methods in this class call this method (and are therefore implemented in this class.
Parameters
X X coordinate of 3D point to project
Y Y coordinate of 3D point to project
Z Z coordinate of 3D point to project
x address of x coordinate of projected image point
y address of y coordinate of projected image point
Implemented in uriVL::WeakPerspectiveCamera, uriVL::OrthographicCamera, and uriVL::PerspectiveCamera.
const IntrinsicParameters * Camera::getIntrinsicParameters (void) const
Returns the camera's intrinsic parameters, in read-only form.
This is the version that most applications should use
Returns
pointer to the camera's intrinsic parameters
Definition at line 243 of file Camera.cpp.
References intrinsic_.
Referenced by uriVL::Calibration3D_Kim::calibrate().
 {
     return intrinsic_;
 }
IntrinsicParameters * Camera::getIntrinsicParameters (ReadWriteStatus rwa) const
Returns the camera's intrinsic parameters, in writeable form.
Pretty much only Calibration3D and Registration3D subclasses have any business calling that one.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
pointer to the camera's intrinsic parameters
Definition at line 249 of file Camera.cpp.
References intrinsic_.
 {
     return intrinsic_;
 }
int Camera::getWidth (void)
Returns the width (in pixels) of the raster digitized.
Returns
width (in pixels) of the raster digitized
Definition at line 60 of file Camera.cpp.
References uriVL::IntrinsicParameters::getWidth(), and intrinsic_.
 {
         return intrinsic_ != NULL ? intrinsic_->getWidth() : 0;
 }
const Camera & Camera::operator= (const Camera & obj) private
Copy operator.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 52 of file Camera.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "Camera copy operator not implemented");
     return *this;
 }
void Camera::setCamToWorldTransf (RigidTransformation3D * transf)
Sets "to-world" transformation fpor this camera.
Parameters
transf new camera to world transformation
Definition at line 228 of file Camera.cpp.
References cam2World_.
 {
         cam2World_ = new RigidTransformation3D(transf);
 }
Member Data Documentation
RigidTransformation3D* uriVL::Camera::cam2World_ protected
Transformation from camera to world reference frame.
Definition at line 312 of file Camera.h.
Referenced by getCamToWorldTransf(), setCamToWorldTransf(), and ~Camera().
bool uriVL::Camera::cam2WorldIsUpToDate_ protected
Indicates whether the transformation from camera to world reference frame is up to date.
Definition at line 317 of file Camera.h.
IntrinsicParameters* uriVL::Camera::intrinsic_ protected
Intrinsic parameters for this camera.
Definition at line 321 of file Camera.h.
Referenced by getHeight(), uriVL::PerspectiveCamera::getImagePoint_(), getIntrinsicParameters(), and getWidth().
The documentation for this class was generated from the following files:
Camera.h
Camera.cpp