URIVisionLibrary: uriVL::GrayThresholdLabeler Class Reference
uriVL::GrayThresholdLabeler Class Reference
A GrayThresholdLabeler segments an image into regions based on a set of predefined gray-level modes.
#include <GrayThresholdLabeler.h>
Public Member Functions
GrayThresholdLabeler (void)
Default constructor for the class.
GrayThresholdLabeler (int theWidth, int theHeight)
constructor
~GrayThresholdLabeler (void)
Destructor.
LabelRaster * applyTo (const RasterImage *imgIn, const ColorSegParams *params, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params, const ImageRect *theRect, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const char *params, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const char *params, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Public Member Functions inherited from uriVL::Labeler
virtual ~Labeler (void)
Destructor.
Private Member Functions
void applyInto_ (const RasterImage *imgIn, const ColorSegParams *colorParams, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor)
Private function that applies this operator to an image, writes the result into a LabelRaster.
void applyInto_ (const RasterImage *imgIn, const ColorSegParams *Params, const ImageRect *theRect, RasterImage_RGBa *imgOut)
Private function that applies this operator to an image, writes the result into an RGBA raster image.
void applyInto_ (const RasterImage *imgIn, const ColorSegParams *Params, const ImageRect *theRect, RasterImage_gray *imgOut)
Private function that applies this operator to an image, writes the result into a gray-level raster image.
void connectNeighbors_ (const ImageRect *destRect, int nbRegions, LabelRaster *label, LabelRaster *tempLabel, char noMatchVal)
connect neighbor pixels based on each pixel's 8-neighborhood label values
Additional Inherited Members
Protected Member Functions inherited from uriVL::Labeler
Labeler (void)
default constructor
Labeler (int theWidth, int theHeight)
constructor
Protected Attributes inherited from uriVL::Labeler
LabelRaster * tempLabel_
Detailed Description
A GrayThresholdLabeler segments an image into regions based on a set of predefined gray-level modes.
Note: So far this class does not do much in the way of data validation. For example, if the user defines gray level or color domains I simply assume that these domains do not overlap, without checking for it.
Author
Fang Han and jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 40 of file GrayThresholdLabeler.h.
Constructor & Destructor Documentation
GrayThresholdLabeler::GrayThresholdLabeler (void)
Default constructor for the class.
Definition at line 26 of file GrayThresholdLabeler.cpp.
         :   Labeler()
 {
 }
GrayThresholdLabeler::GrayThresholdLabeler (int theWidth, int theHeight)
constructor
Parameters
theWidth number of columns
theHeight number of rows
Definition at line 31 of file GrayThresholdLabeler.cpp.
         :   Labeler(theWidth, theHeight)
 {
 }
GrayThresholdLabeler::~GrayThresholdLabeler (void)
Destructor.
Definition at line 37 of file GrayThresholdLabeler.cpp.
 {
 }
Member Function Documentation
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, LabelRaster * labelOut, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 108 of file GrayThresholdLabeler.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, and uriVL::kNullRasterImageError.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::BlobTracker2DController::action(), applyInto(), handleMouseDrag(), initThresholds(), myIdle(), myMouse2(), and myMouse3().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     applyInto(imgIn, params, imgIn->getValidRect(), labelOut, connectNeighbor);
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 125 of file GrayThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in GrayThresholdLabeler::applyTo");
     applyInto_(imgIn, params, theRect, labelOut, connectNeighbor);
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, LabelRaster * labelOut, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 146 of file GrayThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, labelOut, connectNeighbor);
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor = false) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 153 of file GrayThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, theRect, labelOut, connectNeighbor);
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, RasterImage * imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
ingOut the RasterImage obtained by applying the operator to imgIn
Definition at line 161 of file GrayThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kRasterImageError, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     //  we accept RGBa images as destination
     if (imgOut->getBaseRasterType() == kRGBa32Raster)
         applyInto_(imgIn, params, imgIn->getValidRect(), (RasterImage_RGBa* ) imgOut);
     //  ...as well as gray-level images when a single mode has been specified
     //  for the search [the test for the number of modes is done in the function called,
     //  to produce distinct error messages].
     else
         if (imgOut->getBaseRasterType() == kGrayRaster)
             applyInto_(imgIn, params, imgIn->getValidRect(), (RasterImage_gray* ) imgOut);
     //  otherwise we just refuse to deal with the image
         else
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "only RGBa and (some) gray outputs accepted in GrayThresholdLabeler::applyInto so far");
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, RasterImage * imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
Definition at line 193 of file GrayThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRasterImageError, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in GrayThresholdLabeler::applyTo");
     //  we accept RGBa images as destination
     if (imgOut->getBaseRasterType() == kRGBa32Raster)
         applyInto_(imgIn, params, theRect, (RasterImage_RGBa* ) imgOut);
     //  ...as well as gray-level images when a single mode has been specified
     //  for the search [the test for the number of modes is done in the function called,
     //  to produce distinct error messages].
     else
         if (imgOut->getBaseRasterType() == kGrayRaster)
             applyInto_(imgIn, params, theRect, (RasterImage_gray* ) imgOut);
     //  otherwise we just refuse to deal with the image
         else
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "only RGBa and (some) gray outputs accepted in GrayThresholdLabeler::applyInto so far");
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, RasterImage * imgOut) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
ingOut the RasterImage obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 229 of file GrayThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, imgOut);
 }
void GrayThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 237 of file GrayThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, theRect, imgOut);
 }
void GrayThresholdLabeler::applyInto_ (const RasterImage * imgIn, const ColorSegParams * colorParams, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor) private
Private function that applies this operator to an image, writes the result into a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 253 of file GrayThresholdLabeler.cpp.
References connectNeighbors_(), FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::ColorSegParams::grayReg, uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::GrayRegion::label, uriVL::RasterImage_gray::localRasterGray(), uriVL::ColorSegParams::nbModes, uriVL::ColorSegParams::noMatchVal, uriVL::R_W_ACCESS, uriVL::LabelRaster::setValidRect(), uriVL::Labeler::tempLabel_, and uriVL::GrayRegion::vMax.
Referenced by applyInto(), and applyTo().
 {
     ImageRect* destRect = ImageRect::intersection(imgIn->getValidRect(), theRect);
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid date rect and output rectangles must overlap");
     bool localGray;
     const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
     GrayRegion          *graySought = grayParams->grayReg;
     const unsigned char* const* gray = grayImg->getShiftedGray2D();
     char** label = labelOut->getShiftedLabel2D(R_W_ACCESS);
     const int   nbRegions = grayParams->nbModes;
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     bool        matchFound;
         char    noMatchVal = grayParams->noMatchVal;
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             matchFound = false;
             for (int k=0; (k<nbRegions) && !matchFound; k++)
                 if ((gray[i][j]>=graySought[k].vMin) &&
                         (gray[i][j]<=graySought[k].vMax))
                 {
                     label[i][j] = graySought[k].label;
                     matchFound = true;
                 }
             if (!matchFound)
             {
                 label[i][j] = noMatchVal;
             }
         }
     }
     //  do connect-neighbor operation
     if (connectNeighbor)
     {
         bool tempLabelIsLocal = false;
         if (tempLabel_ == NULL)
         {
                 tempLabel_ = new LabelRaster(theRect);
                 tempLabelIsLocal = true;
         }
         connectNeighbors_(theRect, nbRegions, labelOut, tempLabel_, noMatchVal);
         if (tempLabelIsLocal)
         {
                 delete tempLabel_;
                 tempLabel_ = NULL;
         }
     }
     //  cleanup if needed
     if (localGray)
         delete grayImg;
     delete destRect;
     labelOut->setValidRect(theRect);
 }
void GrayThresholdLabeler::applyInto_ (const RasterImage * imgIn, const ColorSegParams * Params, const ImageRect * theRect, RasterImage_RGBa * imgOut) private
Private function that applies this operator to an image, writes the result into an RGBA raster image.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 326 of file GrayThresholdLabeler.cpp.
References FAIL_CONDITION, uriVL::GrayRegion::fillColor, uriVL::ColorSegParams::fillMode, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::RasterImage::getPixelDepth(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::ColorSegParams::grayReg, uriVL::ImageRect::intersection(), uriVL::kBlackFill, uriVL::kGrayRaster, uriVL::kIdentityFill, uriVL::kInvalidRectangleError, uriVL::kMediumGrayFill, uriVL::kOrigColorFill, uriVL::kOrigGrayFill, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kWhiteFill, uriVL::RasterImage_gray::localRasterGray(), uriVL::ColorSegParams::nbModes, uriVL::R_W_ACCESS, uriVL::DrawableObject2D::setValidRect(), and uriVL::GrayRegion::vMax.
 {
     ImageRect* destRect = ImageRect::intersection(imgIn->getValidRect(), theRect);
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid date rect and output rectangles must overlap");
     bool localGray;
     const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
     GrayRegion  *graySought = grayParams->grayReg;
     unsigned char* const* rgbaOut = imgOut->getShiftedRGBa2D(R_W_ACCESS);
     const unsigned char* const* gray = grayImg->getShiftedGray2D();
     const unsigned char* const* rasterIn = imgIn->getShiftedRaster2D();
     const BaseRasterType inType = imgIn->getBaseRasterType();
     const int inDepth = imgIn->getPixelDepth()/8;
     const int   nbRegions = grayParams->nbModes;
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     bool        matchFound;
     FillingMode fillMode = grayParams->fillMode;
     switch (fillMode)
     {
         //      The output is an unmodified copy of the input
         case kIdentityFill:
             //jyh   fix later
             //imgIn->copyInto(imgOut, imgIn->getType());
             //imgIn->copyInto(imgOut);
             break;
         //      Simply overlay thresholded regions on the original image
         case kOrigColorFill:
             switch (inType)
             {
                 case kGrayRaster:
                     for (int i=iLow; i<=iHigh; i++)
                     {
                         //  j is the pixel index in the hsv rasters
                         //  l is the byte index in the output image
                         //  m is the byte index in the input image
                         for (int j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
{
                             matchFound = false;
                             for (int k=0; (k<nbRegions) && !matchFound; k++)
                                 if ((gray[i][j]>=graySought[k].vMin) &&
                                         (gray[i][j]<=graySought[k].vMax))
{
                                     rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                                     rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                                     rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                                     rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                                     m+=inDepth;
                                     matchFound = true;
                                 }
                             if (!matchFound)
{
                                 unsigned char   val = rasterIn[i][m++];
                                 rgbaOut[i][l++] = val;
                                 rgbaOut[i][l++] = val;
                                 rgbaOut[i][l++] = val;
                                 rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             }
                         }
                     }
                     break;
                  case kRGB24Raster:
                     for (int i=iLow; i<=iHigh; i++)
                     {
                         //  j is the pixel index in the hsv rasters
                         //  l is the byte index in the output image
                         //  m is the byte index in the input image
                         for (int j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
{
                             matchFound = false;
                             for (int k=0; (k<nbRegions) && !matchFound; k++)
                                 if ((gray[i][j]>=graySought[k].vMin) &&
                                         (gray[i][j]<=graySought[k].vMax))
{
                                     rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                                     rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                                     rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                                     rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                                     m+=inDepth;
                                     matchFound = true;
                                 }
                             if (!matchFound)
{
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             }
                         }
                     }
                     break;
                 case kRGBa32Raster:
                     for (int i=iLow; i<=iHigh; i++)
                     {
                         //  j is the pixel index in the hsv rasters
                         //  l is the byte index in the output image
                         //  m is the byte index in the input image
                         for (int j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
{
                             matchFound = false;
                             for (int k=0; (k<nbRegions) && !matchFound; k++)
                                 if ((gray[i][j]>=graySought[k].vMin) &&
                                         (gray[i][j]<=graySought[k].vMax))
{
                                     rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                                     rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                                     rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                                     rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                                     m+=inDepth;
                                     matchFound = true;
                                 }
                             if (!matchFound)
{
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                             }
                         }
                     }
                 default:
                     break;
             }
             break;
         //      Display the thresholded regions over a black background
         case kBlackFill:
             for (int i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byet index in the input image
                 for (int j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (int k=0; (k<nbRegions) && !matchFound; k++)
                         if ((gray[i][j]>=graySought[k].vMin) &&
                                 (gray[i][j]<=graySought[k].vMax))
{
                             rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                     }
                 }
             }
             break;
         //      Display the thresholded regions over a white background
         case kWhiteFill:
             for (int i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byet index in the input image
                 for (int j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (int k=0; (k<nbRegions) && !matchFound; k++)
                         if ((gray[i][j]>=graySought[k].vMin) &&
                                 (gray[i][j]<=graySought[k].vMax))
{
                             rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
         //      Display the thresholded regions over a medium gray background
         case kMediumGrayFill:
             for (int i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byet index in the input image
                 for (int j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (int k=0; (k<nbRegions) && !matchFound; k++)
                         if ((gray[i][j]>=graySought[k].vMin) &&
                                 (gray[i][j]<=graySought[k].vMax))
{
                             rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
         //      Display the thresholded regions over the original gray-level image
         case kOrigGrayFill:
             for (int i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byet index in the input image
                 for (int j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (int k=0; (k<nbRegions) && !matchFound; k++)
                         if ((gray[i][j]>=graySought[k].vMin) &&
                                 (gray[i][j]<=graySought[k].vMax))
{
                             rgbaOut[i][l++] = graySought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = graySought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = graySought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             m++;
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         unsigned char   val = gray[i][m++];
                         rgbaOut[i][l++] = val;
                         rgbaOut[i][l++] = val;
                         rgbaOut[i][l++] = val;
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
         default:
             break;
     }
     if (localGray)
         delete grayImg;
     delete destRect;
     imgOut->setValidRect(theRect);
 }
void GrayThresholdLabeler::applyInto_ (const RasterImage * imgIn, const ColorSegParams * Params, const ImageRect * theRect, RasterImage_gray * imgOut) private
Private function that applies this operator to an image, writes the result into a gray-level raster image.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 621 of file GrayThresholdLabeler.cpp.
References uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::GrayRegion::fillColor, uriVL::ColorSegParams::fillMode, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::ColorSegParams::grayReg, uriVL::ImageRect::intersection(), uriVL::kBlackFill, uriVL::kIdentityFill, uriVL::kInvalidParameterError, uriVL::kInvalidRectangleError, uriVL::kMediumGrayFill, uriVL::kOrigColorFill, uriVL::kOrigGrayFill, uriVL::kWhiteFill, uriVL::RasterImage_gray::localRasterGray(), uriVL::ColorSegParams::nbModes, uriVL::R_W_ACCESS, uriVL::DrawableObject2D::setValidRect(), uriVL::GrayRegion::vMax, and uriVL::GrayRegion::vMin.
 {
     ImageRect* destRect = ImageRect::intersection(imgIn->getValidRect(), theRect);
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid date rect and output rectangles must overlap");
         //      should be computed only for theRect
     bool localGray;
     const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
     //  When the output is a gray-level image, then we accept only a single mode for the
     //  thresholding
     int nbRegions = grayParams->nbModes;
     FAIL_CONDITION(     nbRegions != 1,
                     kInvalidParameterError,
                     "thresholding into a gray level image is only permitted ");
     GrayRegion      *graySought = grayParams->grayReg;
     unsigned char* const* grayOut = imgOut->getShiftedGray2D(R_W_ACCESS);
     const unsigned char* const* grayIn = grayImg->getShiftedGray2D();
     //  just trying to compensate for Nature's way of producing ever
     //  more performant idiots
     unsigned char   fillVal = static_cast<unsigned char>((graySought[0].fillColor[0] +
                                                           graySought[0].fillColor[1] +
                                                           graySought[0].fillColor[1]) / 3);
     unsigned char   vMin = graySought[0].vMin,
                     vMax = graySought[0].vMax;
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     FillingMode     fillMode = grayParams->fillMode;
     switch (fillMode)
     {
         //      The output is an unmodified copy of the input
         //  ???? Why ???  What exactly did I write this for????
         case kIdentityFill:
             //jyh   fix later
             //imgIn->copyInto(imgOut, imgIn->getType());
             imgIn->copyInto(imgOut);
             break;
             //  Display the thresholded regions over a black background [better hope that the
             //  filling color is not black too]
         case kBlackFill:
             for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                     if ((grayIn[i][j] >= vMin) && (grayIn[i][j] <= vMax))
                         grayOut[i][j] = fillVal;
                     else
                         grayOut[i][j] = (unsigned char) 0;
             break;
         //      Display the thresholded regions over a white background [better hope that the
         //  filling color is not white too]
         case kWhiteFill:
             for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                     if ((grayIn[i][j] >= vMin) && (grayIn[i][j] <= vMax))
                         grayOut[i][j] = fillVal;
                     else
                         grayOut[i][j] = (unsigned char) 255;
             break;
         //      Display the thresholded regions over a medium gray background
         case kMediumGrayFill:
             for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                     if ((grayIn[i][j] >= vMin) && (grayIn[i][j] <= vMax))
                         grayOut[i][j] = fillVal;
                     else
                         grayOut[i][j] = (unsigned char) 127;
             break;
         //      Simply overlay thresholded regions on the original image
         case kOrigColorFill:
         case kOrigGrayFill:
             for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                     if ((grayIn[i][j] >= vMin) && (grayIn[i][j] <= vMax))
                         grayOut[i][j] = fillVal;
                     else
                         grayOut[i][j] = grayIn[i][j];
             break;
         default:
             break;
     }
     if (localGray)
         delete grayImg;
     delete destRect;
     imgOut->setValidRect(theRect);
 }
LabelRaster * GrayThresholdLabeler::applyTo (const RasterImage * imgIn, const ColorSegParams * params, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 59 of file GrayThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, and uriVL::kRasterAllocationFailure.
Referenced by applyTo(), and initThresholds().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION(     labelOut == NULL,
                     kRasterAllocationFailure,
                     "output LabelRaster  allocation failed in GrayThresholdLabeler::applyTo");
     applyInto_(imgIn, params, imgIn->getValidRect(), labelOut, connectNeighbor);
     return labelOut;
 }
LabelRaster * GrayThresholdLabeler::applyTo (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 80 of file GrayThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in GrayThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in GrayThresholdLabeler::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "output LabelRaster  allocation failed in GrayThresholdLabeler::applyTo");
     applyInto_(imgIn, params, theRect, labelOut, connectNeighbor);
     return labelOut;
 }
LabelRaster * GrayThresholdLabeler::applyTo (const RasterImage * imgIn, const char * params, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 46 of file GrayThresholdLabeler.cpp.
References applyTo().
 {
     return applyTo(imgIn, (const ColorSegParams *)params, connectNeighbor);
 }
LabelRaster * GrayThresholdLabeler::applyTo (const RasterImage * imgIn, const char * params, const ImageRect * theRect, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to void)
theRect the rectangle within which to apply the labeler
Returns
the LabelRaster obtained by applying the operator to imgIn
Parameters
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 52 of file GrayThresholdLabeler.cpp.
References applyTo().
 {
     return applyTo(imgIn, (const ColorSegParams*)params, theRect, connectNeighbor);
 }
void GrayThresholdLabeler::connectNeighbors_ (const ImageRect * destRect, int nbRegions, LabelRaster * label, LabelRaster * tempLabel, char noMatchVal) private
connect neighbor pixels based on each pixel's 8-neighborhood label values
Parameters
destRect destination bounding rectangle
nbRegions number of regions
label original LabelRaster
tempLabel temporary LabelRaster for storing label values
Definition at line 737 of file GrayThresholdLabeler.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
Referenced by applyInto_().
 {
         const int       iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
         const int       hT = 5,                                 // high threshold on number of neighbors
                         lT = 3;                                 // low threshold on number of neighbors
         char    **label2D = label->getShiftedLabel2D(R_W_ACCESS),
                         **tempLabel2D = tempLabel->getShiftedLabel2D(R_W_ACCESS);
         // array of label values
         char    *labelArray = new char[nbRegions];
         int             *vote = new int[nbRegions];             // number of each pixel's same neighbor
         int             maxIndex = 0;                                   // index of vote that has max votes
         for (int i=0; i<nbRegions; i++)
         {
                 labelArray[i] = static_cast<char>(i+1);                         // label values begins from 1
                 vote[i] = 0;
         }
         // peripheral points are not processed in this operation, so these values
         // are kept same between label2D and tempLabel2D
         for (int j=jLow; j<=jHigh; j++)
         {
                 tempLabel2D[iLow][j] = label2D[iLow][j];
                 tempLabel2D[iHigh][j] = label2D[iHigh][j];
         }
         for (int i=iLow; i<=iHigh; i++)
         {
                 tempLabel2D[i][jLow] = label2D[i][jLow];
                 tempLabel2D[i][jHigh] = label2D[i][jHigh];
         }
         // process internal points
         for (int i=iLow+1; i<iHigh; i++)
                 for (int j=jLow+1; j<jHigh; j++)
                 {
                         for (int k=0; k<nbRegions; k++)
{
                                 if (labelArray[k] == label2D[i-1][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i-1][j])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i-1][j+1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i][j+1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j+1])
                                         vote[k]++;
                                 if (vote[k]>vote[maxIndex])
                                         maxIndex = k;
                         }
                         // decide the pixel value based upon vote value
                         if (vote[maxIndex] >= hT)
                                 tempLabel2D[i][j] = labelArray[maxIndex];       // adapt it to majority
                         else if (vote[maxIndex] >= lT)
                                 tempLabel2D[i][j] = label2D[i][j];                      // keep its value
                         else
                                 tempLabel2D[i][j] = noMatchVal;                                         // set to -1
                         // initialize vote back to 0 for next loop
                         for (int k=0; k<nbRegions; k++)
                                 vote[k] = 0;
                 }
         // copy tempLabel2D into label2D
         for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                 {
                         label2D[i][j] = tempLabel2D[i][j];
                 }
 }
The documentation for this class was generated from the following files:
GrayThresholdLabeler.h
GrayThresholdLabeler.cpp