URIVisionLibrary: uriComputerVision::BackgroundRemoverTester Class Reference
uriComputerVision::BackgroundRemoverTester Class Reference
#include <BackgroundRemoverTester.h>
Public Member Functions
BackgroundRemoverTester (int nbRects, RasterImage *firstBackground)
Constructor.
virtual ~BackgroundRemoverTester (void)
Destructor.
void test (RasterImage *img, BkgdTestCase testCase_, int rectStep=1)
testing
int ** getDiffData (void)
get the difference of 2 images as a 2-D array int data
int *** getDiffData3D (void)
RasterImage_gray * getDiffImg (void)
get the difference of 2 images as a RasterImage_gray
double getTotalIntensity (void)
get the total intensity of the current image
float getCoveredPercent (void)
get the percentage of covered (by objects) area
float getCoveredPctNoSmooth (void)
get the percentage of covered (by objects) area with only fitting (no smoothing)
RasterImage * getBackground (void)
get the current background Image within remover_, which is a BackgroundRemover_dynamic_MW
int getRightThreshold (void)
get a right threshold such that we can find no blobs in thresholded diffImg_, when there is not any in real image
int getDimX (void)
get the difference of 2 images as a RasterImage_gray
int getDimY (void)
get the difference of 2 images as a RasterImage_gray
int getXUnit (void)
get xUnit_ in backgroundRemover
int getYUnit (void)
get yUnit_ in backgroundRemover
float ** getRatio (void)
get intensity ratio of currentImage and firstBackground
RasterImage_gray_F * getRatioAsRasterImage (void)
RasterImage_gray_F * getFittedRatioAsRasterImage (void)
float * getCoveredPercNoSmooth (void)
int getNbIncreaseRect (void)
RasterImage * getFirstBackground (void)
Protected Member Functions
void test0_ (RasterImage *img)
BkgdTestCase : INTENSITY_RATIO.
void test1_ (RasterImage *img)
BkgdTestCase : THRESHOLD_NO_OBJECT.
void test21_ (RasterImage *img)
BkgdTestCase : PERCENTAGE_NO_SMOOTHING.
void test22_ (RasterImage *img)
BkgdTestCase : PERCENTAGE_NO_OBJECT.
void test3_ (RasterImage *img)
BkgdTestCase : ALL_OBJECT.
void test4_ (RasterImage *img)
BkgdTestCase : MISS_SOME_OBJECT.
Protected Attributes
RasterImage * firstBackground_
BackgroundRemover_dynamic_MW * remover_
int frameCount_
int nbRects_
int rectStep_
RectList rectList_
int top_
int left_
int height_
int width_
int rectSize_
RasterImage * estimateImg_
RasterImage_gray * diffImg_
difference as a RasterImage_gray
int ** diffData_
difference as a 2-D array of int data
int *** diffData3D_
int dimX_
int dimY_
int totalRects_
total amount of rectangles divided in remover_
GrayThresholdLabeler * thresholder_
ColorSegParams * grayParams_
LabelRaster * label_
RasterImage_gray_F * grayRatio_
RasterImage_gray_F * fittedGrayRatio_
char * target_
long blobMinSize_
BlobFinder * blobFinder_
BlobList * blobList_
int minThreshold_
int noiseSize_
BkgdTestCase testCase_
bool objectMatched_
list< bool > objectDetectList_
int nbObjectMissed_
float ** intensityRatio_
float ** intensityBg_
float ** intensityImg_
double totalIntensity_
float coveredPercent_
float coveredPctNoSmooth_
int nbIncreaseRect_
float * coveredPercNoSmooth_
unsigned char ** firstBg2D_
Detailed Description
Definition at line 36 of file BackgroundRemoverTester.h.
Constructor & Destructor Documentation
BackgroundRemoverTester::BackgroundRemoverTester (int nbRects, RasterImage * firstBackground)
Constructor.
Definition at line 25 of file BackgroundRemoverTester.cpp.
References uriVL::kOrigColorFill, and uriComputerVision::THRESHOLD_NO_OBJECT.
 {
         firstBackground_ = firstBackground;
         remover_ = new BackgroundRemover_dynamic_MW();
         nbRects_ = nbRects;
         rectStep_ = 1;
         top_ = 0;
         left_ = 0;
         height_ = 0;
         width_ = 0;
         dimX_ = 0;
         dimY_ = 0;
         diffImg_ = NULL;
         diffData_ = NULL;
         estimateImg_ = NULL;
         frameCount_ = 0;
         rectSize_ = 10;
         thresholder_    = new GrayThresholdLabeler();
         grayParams_             = new ColorSegParams;
         label_                  = NULL;
         blobFinder_             = new BlobFinder();
         target_                 = new char[1];
         blobMinSize_    = 5;
         minThreshold_   = 64;
         noiseSize_              = 30;
     grayParams_->nbModes = 1;
     grayParams_->colorMode = false;
     grayParams_->colorReg = NULL;
     grayParams_->grayReg = new GrayRegion[grayParams_->nbModes];
     grayParams_->fillMode = kOrigColorFill;
     grayParams_->grayReg[0].labelStr =  "experimental difference";
     grayParams_->grayReg[0].vMin = minThreshold_;
     grayParams_->grayReg[0].vMax = 255;
     grayParams_->grayReg[0].fillColor[0] = (unsigned char) 255;
     grayParams_->grayReg[0].fillColor[1] = 0;
     grayParams_->grayReg[0].fillColor[2] = (unsigned char) 0;
     grayParams_->grayReg[0].label = (char) 1;                   //  must begin from n>0
     target_[0] = grayParams_->grayReg[0].label;
         blobList_       = new BlobList[1];
         testCase_ = THRESHOLD_NO_OBJECT;
         objectMatched_ = false;
         nbObjectMissed_ = 0;
         nbIncreaseRect_ = 0;
 }
BackgroundRemoverTester::~BackgroundRemoverTester (void) virtual
Destructor.
Definition at line 77 of file BackgroundRemoverTester.cpp.
 {
         delete remover_;
         delete estimateImg_;
         int i;
         for(i=0; i<dimX_; i++)
                 delete []diffData_[i];
         delete []diffData_;
         delete diffImg_;
         rectList_.clear();
         delete label_;
         delete []grayParams_->grayReg;
         delete grayParams_;
         delete thresholder_;
         delete blobFinder_;
         delete []target_;
         blobList_[0].clear();
         delete []blobList_;
 }
Member Function Documentation
RasterImage * BackgroundRemoverTester::getBackground (void)
get the current background Image within remover_, which is a BackgroundRemover_dynamic_MW
Definition at line 136 of file BackgroundRemoverTester.cpp.
 {
         return estimateImg_;
 }
float uriComputerVision::BackgroundRemoverTester::getCoveredPctNoSmooth (void)
get the percentage of covered (by objects) area with only fitting (no smoothing)
float BackgroundRemoverTester::getCoveredPercent (void)
get the percentage of covered (by objects) area
Definition at line 127 of file BackgroundRemoverTester.cpp.
 {
         return coveredPercent_;
 }
float * BackgroundRemoverTester::getCoveredPercNoSmooth (void)
Definition at line 200 of file BackgroundRemoverTester.cpp.
 {
         return coveredPercNoSmooth_;
 }
int ** BackgroundRemoverTester::getDiffData (void)
get the difference of 2 images as a 2-D array int data
Definition at line 107 of file BackgroundRemoverTester.cpp.
 {
         return diffData_;
 }
int *** BackgroundRemoverTester::getDiffData3D (void)
Definition at line 112 of file BackgroundRemoverTester.cpp.
 {
         return diffData3D_;
 }
RasterImage_gray * BackgroundRemoverTester::getDiffImg (void)
get the difference of 2 images as a RasterImage_gray
Definition at line 117 of file BackgroundRemoverTester.cpp.
 {
         return diffImg_;
 }
int BackgroundRemoverTester::getDimX (void)
get the difference of 2 images as a RasterImage_gray
Definition at line 165 of file BackgroundRemoverTester.cpp.
 {
         return dimX_;
 }
int BackgroundRemoverTester::getDimY (void)
get the difference of 2 images as a RasterImage_gray
Definition at line 170 of file BackgroundRemoverTester.cpp.
 {
         return dimY_;
 }
RasterImage * BackgroundRemoverTester::getFirstBackground (void)
Definition at line 132 of file BackgroundRemoverTester.cpp.
 {
         return firstBackground_;
 }
RasterImage_gray_F * BackgroundRemoverTester::getFittedRatioAsRasterImage (void)
Definition at line 195 of file BackgroundRemoverTester.cpp.
 {
         return fittedGrayRatio_;
 }
int BackgroundRemoverTester::getNbIncreaseRect (void)
Definition at line 205 of file BackgroundRemoverTester.cpp.
 {
         return nbIncreaseRect_;
 }
float ** BackgroundRemoverTester::getRatio (void)
get intensity ratio of currentImage and firstBackground
Definition at line 185 of file BackgroundRemoverTester.cpp.
 {
         return intensityRatio_;
 }
RasterImage_gray_F * BackgroundRemoverTester::getRatioAsRasterImage (void)
Definition at line 190 of file BackgroundRemoverTester.cpp.
 {
         return grayRatio_;
 }
int BackgroundRemoverTester::getRightThreshold (void)
get a right threshold such that we can find no blobs in thresholded diffImg_, when there is not any in real image
Definition at line 141 of file BackgroundRemoverTester.cpp.
References FAIL_CONDITION, and uriVL::kImageProcessingError.
 {
     FAIL_CONDITION( diffImg_ == NULL,
                     kImageProcessingError,
                     "Should firstly call test before BackgroundRemoverTester::getRightThreshold");
         for(minThreshold_=1; minThreshold_<255; minThreshold_++)
         {
                 if(label_ == NULL)
                         label_  = new LabelRaster(diffImg_->getValidRect());
                 grayParams_->grayReg[0].vMin = minThreshold_;
                 thresholder_->applyInto(diffImg_, grayParams_, label_);
                 blobFinder_->findAllBlobs(label_, grayParams_->nbModes,
                                                                         target_, blobMinSize_, blobList_);
                 if(blobList_[0].size() == 0)            // already get the right minThreshold_
                         break;
         }
         return minThreshold_;
 }
double BackgroundRemoverTester::getTotalIntensity (void)
get the total intensity of the current image
Definition at line 122 of file BackgroundRemoverTester.cpp.
 {
         return totalIntensity_;
 }
int BackgroundRemoverTester::getXUnit (void)
get xUnit_ in backgroundRemover
Definition at line 175 of file BackgroundRemoverTester.cpp.
 {
         return (remover_->xUnit_-1);
 }
int BackgroundRemoverTester::getYUnit (void)
get yUnit_ in backgroundRemover
Definition at line 180 of file BackgroundRemoverTester.cpp.
 {
         return (remover_->yUnit_-1);
 }
void BackgroundRemoverTester::test (RasterImage * img, BkgdTestCase testCase_, int rectStep = 1)
testing
Definition at line 210 of file BackgroundRemoverTester.cpp.
References uriComputerVision::ALL_OBJECT, uriComputerVision::INTENSITY_RATIO, uriComputerVision::MISS_SOME_OBJECT, uriComputerVision::PERCENTAGE_NO_OBJECT, uriComputerVision::PERCENTAGE_NO_SMOOTHING, and uriComputerVision::THRESHOLD_NO_OBJECT.
 {
         rectStep_ = rectStep;
         switch (testCase_)
         {
                 case INTENSITY_RATIO:
                         test0_(img);
                         break;
                 case THRESHOLD_NO_OBJECT:
                         test1_(img);
                         break;
                 case PERCENTAGE_NO_SMOOTHING:
                         test21_(img);
                         break;
                 case PERCENTAGE_NO_OBJECT:
                         test22_(img);
                         break;
                 case ALL_OBJECT:
                         test3_(img);
                         break;
                 case MISS_SOME_OBJECT:
                         test4_(img);
                         break;
                 default:        // this should not happen
                         break;
         }
 }
void BackgroundRemoverTester::test0_ (RasterImage * img) protected
BkgdTestCase : INTENSITY_RATIO.
Definition at line 251 of file BackgroundRemoverTester.cpp.
References uriVL::RasterImage::getShiftedRaster2D(), uriVL::kRangeFloat, and uriVL::RasterImage_gray_F::setFloatConversionMode().
 {
         int i,j;
         int     xSqLf   = 0,                                                    // square's lf
                 xSqRt   = 0,                                                    // square's rt
                 ySqTp   = 0,                                                    // square's tp
                 ySqBt   = 0;                                                    // square's bt
         double  a0      = (remover_->a0_[0] + remover_->a0_[1] + remover_->a0_[2]) / 3,
                         a1      = (remover_->a1_[0] + remover_->a1_[1] + remover_->a1_[2]) / 3,
                         a2      = (remover_->a2_[0] + remover_->a2_[1] + remover_->a2_[2]) / 3,
                         a3      = (remover_->a3_[0] + remover_->a3_[1] + remover_->a3_[2]) / 3,
                         a4      = (remover_->a4_[0] + remover_->a4_[1] + remover_->a4_[2]) / 3,
                         a5      = (remover_->a5_[0] + remover_->a5_[1] + remover_->a5_[2]) / 3,
                         a6      = (remover_->a6_[0] + remover_->a6_[1] + remover_->a6_[2]) / 3,
                         a7      = (remover_->a7_[0] + remover_->a7_[1] + remover_->a7_[2]) / 3,
                         a8      = (remover_->a8_[0] + remover_->a8_[1] + remover_->a8_[2]) / 3,
                         a9      = (remover_->a9_[0] + remover_->a9_[1] + remover_->a9_[2]) / 3;
         //      set first video-image as first background
         //      memory allocation & initialization only once
         if(frameCount_ == 0)
         {
                 //      remover_->xUnit_, yUnit_ are both set in setBackground method
                 remover_->setBackground(firstBackground_);
                 intensityBg_            = new float*[remover_->yUnit_-1];// array of firstBG squares' internal intensity
                 intensityImg_           = new float*[remover_->yUnit_-1];// array of currImg squares' internal intensity
                 intensityRatio_         = new float*[remover_->yUnit_-1];// array of ratio value
                 grayRatio_                      = new RasterImage_gray_F(firstBackground_->getBoundRect());
                 grayRatio_->setFloatConversionMode(kRangeFloat);
                 fittedGrayRatio_ = new RasterImage_gray_F(firstBackground_->getBoundRect());
                 fittedGrayRatio_->setFloatConversionMode(kRangeFloat);
                 for(i=0; i<(remover_->yUnit_-1); i++)
                 {
                         intensityBg_[i]         = new float[remover_->xUnit_-1];
                         intensityImg_[i]        = new float[remover_->xUnit_-1];
                         //fittedIntensityImg_[i]        = new float[remover_->xUnit_-1];
                         intensityRatio_[i]      = new float[remover_->xUnit_-1];
                         //fittedIntensityRatio_[i] = new float[remover_->xUnit_-1];
                 }
                 firstBg2D_ = (remover_->firstBackground_)->getShiftedRaster2D();
                 //      1st frame, compute squares' intensity in static first background
                 //      outer loop, for all squares inside image except for those having border outside
                 //  (that's why unit-1)
                 for(i=0; i<(remover_->yUnit_-1); i++)
                 {
                         ySqTp = i*(remover_->size_);
                         ySqBt = ySqTp + (remover_->size_)-1;
                         for(j=0; j<remover_->xUnit_-1; j++)
{
                                 intensityBg_[i][j] = 0;
                                 xSqLf = j*(remover_->size_);
                                 xSqRt = xSqLf + (remover_->size_)-1;
                             int p, q;
                             //  inner loop within each square
                                 for(p=ySqTp; p<=ySqBt; p++)
{
                                         long l = 4*xSqLf;
                                         for(q=xSqLf; q<=xSqRt; q++)
{
                                                 float temp = 0.f;
                                                 // AVERAGE INTENSITY
                                                 int r;
                                                 for(r=0; r<3; r++, l++){
                                                         temp += firstBg2D_[p][l];
                                                 temp /= 3;
                                                 }
                                                 l++;
                                                 // MAX INTENSITY
                                                 //int r;
                                                 //for(r=0; r<3; r++, l++)
                                                 //{
                                                 //      temp = max(temp, (float)(firstBg2D_[p][l]));
                                                 //}
                                                 //l++;
                                                 intensityBg_[i][j]      += temp;
                                         }
                                 }
                         }
                 }
         }
         //      2nd frame on, compute squares' intensity in current image
         else{
                 unsigned char **currImg2D = img->getShiftedRaster2D();
                 float   **ratio = grayRatio_->getShiftedGrayF2D(),
                                 **fittedRatio = fittedGrayRatio_->getShiftedGrayF2D();
                 //      outer loop, for all squares inside image except for those having border outside(that's why size-1)
                 for(i=0; i<(remover_->yUnit_-1); i++)
                 {
                         ySqTp = i*(remover_->size_);
                         ySqBt = ySqTp + (remover_->size_)-1;
                         for(j=0; j<remover_->xUnit_-1; j++)
{
                                 intensityImg_[i][j]     = 0;
                                 xSqLf = j*(remover_->size_);
                                 xSqRt = xSqLf + (remover_->size_)-1;
                             int p, q;
                             //  inner loop within each square
                             //  compute intensityImg_ & fittedIntensityImg_
                                 for(p=ySqTp; p<=ySqBt; p++)
{
                                         long l = 4*xSqLf;
                                         for(q=xSqLf; q<=xSqRt; q++)
{
                                                 float   temp    = 0.f;
                                                 // AVERAGE INTENSITY
                                                 int r;
                                                 for(r=0; r<3; r++, l++){
                                                         temp += currImg2D[p][l];
                                                 temp /= 3;
                                                 l++;
                                                 }
                                                 // MAX INTENSITY
                                                 //int r;
                                                 //for(r=0; r<3; r++, l++)
                                                 //{
                                                 //      temp = max(temp, (float)(currImg2D[p][l]));
                                                 //}
                                                 //l++;
                         fittedRatio[p][q] = (a0*p*p*p
                                                                                         + a1*q*q*q
                                                                                         + a2*p*p*q
                                                                                         + a3*p*q*q
                                                                                         + a4*p*p
                                                                                         + a5*q*q
                                                                                         + a6*p*q
                                                                                         + a7*p
                                                                                         + a8*q
                                                                                         + a9);
                                                 intensityImg_[i][j]     += temp;
                                         }
                                 }
                                 //      get ratio of each square
                                 //cout << "intensityImg_[i][j]: " << intensityImg_[i][j] << endl;
                                 //cout << "intensityBg_[i][j]: " << intensityBg_[i][j] << endl;
                                 intensityRatio_[i][j] = intensityImg_[i][j] / intensityBg_[i][j];
                                 for(p=ySqTp; p<=ySqBt; p++)
                                         for(q=xSqLf; q<=xSqRt; q++)
{
                                             ratio[p][q] = intensityRatio_[i][j];
                                         }
                         }
                 }
                 //      produce grayRatio_ as a gray_F
                 grayRatio_->setValidRect(0, 0, (remover_->xUnit_-1)*remover_->size_,
                                                 (remover_->yUnit_-1)*remover_->size_);
                 grayRatio_->requestRasterUpdate();
                 //      produce fittedRatio_ as a gray_F
                 fittedGrayRatio_->setValidRect(0, 0, (remover_->xUnit_-1)*remover_->size_,
                                                 (remover_->yUnit_-1)*remover_->size_);
                 fittedGrayRatio_->requestRasterUpdate();
         }
         //      update background
         rectList_.push_back(NULL);
         remover_->updateBackground(img, rectList_);
         rectList_.clear();
         frameCount_++;
 }
void BackgroundRemoverTester::test1_ (RasterImage * img) protected
BkgdTestCase : THRESHOLD_NO_OBJECT.
Definition at line 432 of file BackgroundRemoverTester.cpp.
References uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getRight(), and uriVL::DrawableObject2D::getWidth().
 {
         int i, j, rt, bt;
         //--------------------------------------------
         //      set first video-image as first background
         //      memory allocation & initialization only once
         //--------------------------------------------
         if(frameCount_ == 0)
         {
                 remover_->setBackground(firstBackground_);
                 dimX_ = img->getWidth();
                 dimY_ = img->getHeight();
                 diffImg_ = new RasterImage_gray(firstBackground_->getBoundRect());
                 label_  = new LabelRaster(firstBackground_->getBoundRect());
                 rt = img->getBoundRect()->getRight();
                 bt = img->getBoundRect()->getBottom();
         }
         //--------------------------------------------
         //      make estimation, compare, and then update
         //--------------------------------------------
         //      get the comparison result from 2nd frame on
         if(frameCount_ > 0)
         {
                 estimateImg_ = remover_->getBackground();
                 remover_->difference(estimateImg_, img, diffImg_);
                 // get the right threshold such that no blobs can be found
                 for(minThreshold_=1; minThreshold_<255; minThreshold_++)
                 {
                         grayParams_->grayReg[0].vMin = minThreshold_;
                         thresholder_->applyInto(diffImg_, grayParams_, label_);
                         blobFinder_->findAllBlobs(label_, grayParams_->nbModes,
                                                                                 target_, blobMinSize_, blobList_);
                         // already get the right minThreshold_, break the loop
                         // case 1, no blobs found
                         if(blobList_[0].size() == 0)
                                 break;
                         // case 2, blobs are all considered noise
                         else
{
                                 bool needBreak = true;
                                 BlobList::iterator iter = blobList_[0].begin();
                                 // if all blobs are noise, we break the loop
                                 // of finding minThreshold_
                                 for( ; iter!=blobList_[0].end(); iter++)
{
                                         if((*iter)->getNbPixels() >= noiseSize_)
{
                                                 needBreak = false;
                                                 break;
                                         }
                                 }
                                 if(needBreak)
                                         break;
                         }
                 }
         }
         int xEntry, yEntry;
         remover_->initializedByTester_ = true;
         for(i=0; i<remover_->yUnit_ ;i++)
             for(j=0; j<remover_->xUnit_; j++)
                 remover_->goodSquare_[i][j] = true;     // initialize goodSquare_
         // random squares moving at the speed of 1 squareSize/frame
         for(i=0; i<nbRects_; i++)
         {
                 srand(i);
                 // in case of overlap, use a loop to produce a new square
                 do
                 {
                         //yEntry = rand() % remover_->yUnit_;
                         //xEntry = rand() % remover_->xUnit_;
                         yEntry = (rand()+frameCount_) % remover_->yUnit_;
                         xEntry = (rand()+frameCount_) % remover_->xUnit_;
                 } while (remover_->goodSquare_[yEntry][xEntry]==false);
                 //      set the square to be invalid
                 remover_->goodSquare_[yEntry][xEntry] = false;
                 //cout << "yEntry:" << yEntry << endl;
         }
 ///*
         // a bad region of nbRects_*nbRects_ in the image
         // moving at the speed of 1 squareSize/frame
         yEntry = 6;
         xEntry = 6;
         int xTemp, yTemp;
         //      set the square to be invalid
         remover_->goodSquare_[yEntry][xEntry] = false;
         for(i=0; i<nbRects_; i++)
         {
                 yEntry++;
                 xEntry = 6;
                 for(j=0; j<nbRects_; j++)
                 {
                         xEntry++;
                         xTemp  = xEntry%remover_->xUnit_;
                         yTemp  = yEntry%remover_->yUnit_;
                         //xTemp  = (xEntry+frameCount_)%remover_->xUnit_;
                         //yTemp  = (yEntry+frameCount_)%remover_->yUnit_;
                         remover_->goodSquare_[yTemp][xTemp] = false;
                 }
         }
 //*/
         //      update background
         if(rectList_.empty())
                 rectList_.push_back(NULL);
         remover_->updateBackground(img, rectList_);
         rectList_.clear();
         frameCount_++;
 }
void BackgroundRemoverTester::test21_ (RasterImage * img) protected
BkgdTestCase : PERCENTAGE_NO_SMOOTHING.
Definition at line 555 of file BackgroundRemoverTester.cpp.
References uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), and uriVL::DrawableObject2D::getWidth().
 {
         int i, j, index=0, rt, bt;
         remover_->noSmoothing_ = true;
         //--------------------------------------------
         //      set first video-image as first background
         //      memory allocation & initialization only once
         //--------------------------------------------
         if(frameCount_ == 0)
         {
                 remover_->setBackground(firstBackground_);
                 dimX_ = img->getWidth();
                 dimY_ = img->getHeight();
                 totalRects_ = remover_->yUnit_*remover_->xUnit_;
                 rt = img->getBoundRect()->getRight();
                 bt = img->getBoundRect()->getBottom();
                 diffImg_ = new RasterImage_gray(firstBackground_->getBoundRect());
                 nbIncreaseRect_ = (totalRects_-10)/rectStep_;
                 coveredPercNoSmooth_ = new float[nbIncreaseRect_];
                 diffData3D_ = new int**[nbIncreaseRect_];
                 for (index=0; index<nbIncreaseRect_; index++)
                 {
                         diffData3D_[index] = new int*[dimY_];
                         for(i=0; i<dimY_; i++)
{
                                 diffData3D_[index][i] = new int[dimX_];
                         }
                 }
                 for(i=0; i<nbIncreaseRect_; i++)
                 for(nbRects_=rectStep_,i=0; i<nbIncreaseRect_; i++,nbRects_ += rectStep_)
                         coveredPercNoSmooth_[i] = ((float)nbRects_)/ totalRects_;
         }
         //--------------------------------------------
         //      make estimation, compare, and then update
         //--------------------------------------------
         //      get the comparison result from 2nd frame on
         if(frameCount_ > 0)
         {
                 //      add all rectangles, using goodSquare_ in remover_
                 int xEntry, yEntry;
                 remover_->initializedByTester_ = true;
                 //      compute totalIntensity_
                 totalIntensity_ = 0.L;
                 unsigned char **currImg = img->getShiftedRaster2D();
                 for(i=0; i<dimY_; i++)
                         for(j=0; j<dimX_; j++)
{
                                 totalIntensity_ += currImg[i][j];
                         }
                 //      each frame, keep increasing nbRects till >=10 good square left
                 for(nbRects_=rectStep_;nbRects_<totalRects_-10;nbRects_ += rectStep_)
                 {
                         estimateImg_ = remover_->getBackground();
                         //delete diffImg_;
                         //diffImg_ = new RasterImage_gray(estimateImg_->getBoundRect());
                         remover_->difference(estimateImg_, img, diffImg_);
                         unsigned char **temp;
                         temp = diffImg_->getShiftedGray2D();
                         for(i=0; i<dimY_; i++)
                                 for(j=0; j<dimX_; j++)
{
                                         diffData3D_[index][i][j] = temp[i][j];
                                 }
                         for(i=0; i<remover_->yUnit_ ;i++)
                             for(j=0; j<remover_->xUnit_; j++)
                                 remover_->goodSquare_[i][j] = true;     // initialize goodSquare_
                         // random squares moving at the speed of 1 squareSize/frame
                         for(i=0; i<nbRects_; i++)
{
                                 srand(i);
                                 // in case of overlap, use a loop to produce a new square
                                 do
{
                                         //yEntry = rand() % remover_->yUnit_;
                                         //xEntry = rand() % remover_->xUnit_;
                                         yEntry = (rand()+frameCount_) % remover_->yUnit_;
                                         xEntry = (rand()+frameCount_) % remover_->xUnit_;
                                 } while (remover_->goodSquare_[yEntry][xEntry]==false);
                                 //      set the square to be invalid
                                 remover_->goodSquare_[yEntry][xEntry] = false;
                                 //cout << "yEntry:" << yEntry << endl;
                         }
                         //      update background
                         if(rectList_.empty())
                                 rectList_.push_back(NULL);
                         remover_->updateBackground(img, rectList_);
                         rectList_.clear();
                         index++;
                 }
         }
         frameCount_++;
 }
void BackgroundRemoverTester::test22_ (RasterImage * img) protected
BkgdTestCase : PERCENTAGE_NO_OBJECT.
Definition at line 666 of file BackgroundRemoverTester.cpp.
References uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage::getShiftedRaster2D(), and uriVL::DrawableObject2D::getWidth().
 {
         int i, j, rt, bt;
         //--------------------------------------------
         //      set first video-image as first background
         //      memory allocation & initialization only once
         //--------------------------------------------
         if(frameCount_ == 0)
         {
                 remover_->setBackground(firstBackground_);
                 dimX_ = img->getWidth();
                 dimY_ = img->getHeight();
                 totalRects_ = remover_->yUnit_*remover_->xUnit_;
                 rt = img->getBoundRect()->getRight();
                 bt = img->getBoundRect()->getBottom();
                 diffData_ = new int*[dimY_];
                 for(i=0; i<dimX_; i++)
                         diffData_[i] = new int[dimX_];
                 //cout << "dimX: " << dimX_ << endl;
                 //cout << "dimY: " << dimY_ << endl;
                 diffImg_ = new RasterImage_gray(firstBackground_->getBoundRect());
         }
         //--------------------------------------------
         //      make estimation, compare, and then update
         //--------------------------------------------
         //      get the comparison result from 2nd frame on
         if(frameCount_ > 0)
         {
                 estimateImg_ = remover_->getBackground();
                 //delete diffImg_;
                 //diffImg_ = new RasterImage_gray(estimateImg_->getBoundRect());
                 remover_->difference(estimateImg_, img, diffImg_);
                 unsigned char **temp;
                 temp = diffImg_->getShiftedGray2D();
                 for(i=0; i<dimY_; i++)
                         for(j=0; j<dimX_; j++)
{
                                 diffData_[i][j] = temp[i][j];
                                 //cout << "diffData[" << i << "][" << j << "]:"
                                 //      << diffData_[i][j] << endl;
                         }
                 //      add all rectangles, using goodSquare_ in remover_
                 int xEntry, yEntry;
                 remover_->initializedByTester_ = true;
                 for(i=0; i<remover_->yUnit_ ;i++)
                     for(j=0; j<remover_->xUnit_; j++)
                         remover_->goodSquare_[i][j] = true;     // initialize goodSquare_
                 // random squares moving at the speed of 1 squareSize/frame
                 for(i=0; i<nbRects_; i++)
                 {
                         srand(i);
                         // in case of overlap, use a loop to produce a new square
                         do
{
                                 //yEntry = rand() % remover_->yUnit_;
                                 //xEntry = rand() % remover_->xUnit_;
                                 yEntry = (rand()+frameCount_) % remover_->yUnit_;
                                 xEntry = (rand()+frameCount_) % remover_->xUnit_;
                         } while (remover_->goodSquare_[yEntry][xEntry]==false);
                         //      set the square to be invalid
                         remover_->goodSquare_[yEntry][xEntry] = false;
                         //cout << "yEntry:" << yEntry << endl;
                 }
                 coveredPercent_ = ((float)nbRects_) / totalRects_;
                 cout << "coveredPercent_: " << coveredPercent_ << endl;
                 cout << "nbRects_: " << nbRects_ << endl;
                 //      because we need at least 10 equations for LSE, so at least
                 //      10 rects should be reserved as good square in remover_
                 if(nbRects_ < (totalRects_-23-rectStep_))
                         nbRects_ += rectStep_;
         }
         //      update background
         if(rectList_.empty())
                 rectList_.push_back(NULL);
         remover_->updateBackground(img, rectList_);
         rectList_.clear();
         //      compute totalIntensity_
         totalIntensity_ = 0.L;
         unsigned char **currImg = img->getShiftedRaster2D();
         for(i=0; i<dimY_; i++)
                 for(j=0; j<dimX_; j++)
                 {
                         totalIntensity_ += currImg[i][j];
                 }
         frameCount_++;
 }
void BackgroundRemoverTester::test3_ (RasterImage * img) protected
BkgdTestCase : ALL_OBJECT.
Definition at line 769 of file BackgroundRemoverTester.cpp.
References uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getRight(), and uriVL::DrawableObject2D::getWidth().
 {
         int /* i,  unused var. -CJC */ rt, bt;
         //--------------------------------------------
         //      set pointed image as first background (only once)
         //--------------------------------------------
         if(frameCount_ == 0)
         {
                 remover_->setBackground(firstBackground_);
                 dimX_ = img->getWidth();
                 dimY_ = img->getHeight();
                 diffImg_ = new RasterImage_gray(firstBackground_->getBoundRect());
                 rt = img->getBoundRect()->getRight();
                 bt = img->getBoundRect()->getBottom();
         }
         //--------------------------------------------
         //      make estimation, compare, and then update
         //--------------------------------------------
         //      get the comparison result from 1st frame on
         estimateImg_ = remover_->getBackground();
         //diffImg_ = new RasterImage_gray(estimateImg_->getBoundRect());
         remover_->difference(estimateImg_, img, diffImg_);
         // test whether detected blobs found are same with real ones in image
         if(label_ == NULL)
                 label_  = new LabelRaster(diffImg_->getValidRect());
         grayParams_->grayReg[0].vMin = minThreshold_;
         thresholder_->applyInto(diffImg_, grayParams_, label_);
         blobFinder_->findAllBlobs(label_, grayParams_->nbModes,
                                                                         target_, blobMinSize_, blobList_);
         // here we only check number, we may also test other state of the blobs
         objectDetectList_.clear();
         if(static_cast<int>(blobList_[0].size()) == nbRects_)
                 objectMatched_ = true;
         objectDetectList_.push_back(objectMatched_);
         objectMatched_ = false;
         if (objectMatched_)
                 cout << "match? yes" << endl;
         else
                 cout << "match? no" << endl;
         //      get all rectangles
         BlobList::iterator iter = blobList_[0].begin();
         for( ; iter!=blobList_[0].end(); iter++)
         {
                 rectList_.push_back((*iter)->getBoundRect());
         }
         //      update background
         if(rectList_.empty())
                 rectList_.push_back(NULL);
         remover_->updateBackground(img, rectList_);
         rectList_.clear();
         frameCount_++;
 }
void BackgroundRemoverTester::test4_ (RasterImage * img) protected
BkgdTestCase : MISS_SOME_OBJECT.
Definition at line 831 of file BackgroundRemoverTester.cpp.
References uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getRight(), and uriVL::DrawableObject2D::getWidth().
 {
         int i, rt, bt;
         //--------------------------------------------
         //      set pointed image as first background (only once)
         //--------------------------------------------
         if(frameCount_ == 0)
         {
                 remover_->setBackground(firstBackground_);
                 dimX_ = img->getWidth();
                 dimY_ = img->getHeight();
                 diffImg_ = new RasterImage_gray(firstBackground_->getBoundRect());
                 rt = img->getBoundRect()->getRight();
                 bt = img->getBoundRect()->getBottom();
         }
         //--------------------------------------------
         //      make estimation, compare, and then update
         //--------------------------------------------
         //      get the comparison result from 1st frame on
         estimateImg_ = remover_->getBackground();
         //diffImg_ = new RasterImage_gray(estimateImg_->getBoundRect());
         remover_->difference(estimateImg_, img, diffImg_);
         // test whether detected blobs found are same with real ones in image
         if(label_ == NULL)
                 label_  = new LabelRaster(diffImg_->getValidRect());
         grayParams_->grayReg[0].vMin = minThreshold_;
         thresholder_->applyInto(diffImg_, grayParams_, label_);
         blobFinder_->findAllBlobs(label_, grayParams_->nbModes,
                                                                         target_, blobMinSize_, blobList_);
         // here we only check number, we may also test other state of the blobs
         if(static_cast<int>(blobList_[0].size()) == nbRects_)
                 objectMatched_ = true;
         objectDetectList_.push_back(objectMatched_);
         objectMatched_ = false;
         if (objectMatched_)
                 cout << "match? yes" << endl;
         else
                 cout << "match? no" << endl;
         //      get all rectangles, and put some of them into rectList_ for later update
         BlobList::iterator iter = blobList_[0].begin();
         for( ; iter!=blobList_[0].end(); iter++)
         {
                 rectList_.push_back((*iter)->getBoundRect());
         }
         for(i=0; i<nbObjectMissed_; i++)
                 rectList_.pop_back();
         //      update background
         if(rectList_.empty())
                 rectList_.push_back(NULL);
         remover_->updateBackground(img, rectList_);
         rectList_.clear();
         frameCount_++;
 }
Member Data Documentation
BlobFinder* uriComputerVision::BackgroundRemoverTester::blobFinder_ protected
Definition at line 193 of file BackgroundRemoverTester.h.
BlobList* uriComputerVision::BackgroundRemoverTester::blobList_ protected
Definition at line 195 of file BackgroundRemoverTester.h.
long uriComputerVision::BackgroundRemoverTester::blobMinSize_ protected
Definition at line 191 of file BackgroundRemoverTester.h.
float uriComputerVision::BackgroundRemoverTester::coveredPctNoSmooth_ protected
Definition at line 232 of file BackgroundRemoverTester.h.
float uriComputerVision::BackgroundRemoverTester::coveredPercent_ protected
Definition at line 228 of file BackgroundRemoverTester.h.
float* uriComputerVision::BackgroundRemoverTester::coveredPercNoSmooth_ protected
Definition at line 238 of file BackgroundRemoverTester.h.
int*** uriComputerVision::BackgroundRemoverTester::diffData3D_ protected
Definition at line 167 of file BackgroundRemoverTester.h.
int** uriComputerVision::BackgroundRemoverTester::diffData_ protected
difference as a 2-D array of int data
Definition at line 165 of file BackgroundRemoverTester.h.
RasterImage_gray* uriComputerVision::BackgroundRemoverTester::diffImg_ protected
difference as a RasterImage_gray
Definition at line 160 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::dimX_ protected
Definition at line 169 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::dimY_ protected
Definition at line 171 of file BackgroundRemoverTester.h.
RasterImage* uriComputerVision::BackgroundRemoverTester::estimateImg_ protected
Definition at line 155 of file BackgroundRemoverTester.h.
RasterImage* uriComputerVision::BackgroundRemoverTester::firstBackground_ protected
Definition at line 133 of file BackgroundRemoverTester.h.
unsigned char** uriComputerVision::BackgroundRemoverTester::firstBg2D_ protected
Definition at line 240 of file BackgroundRemoverTester.h.
RasterImage_gray_F* uriComputerVision::BackgroundRemoverTester::fittedGrayRatio_ protected
Definition at line 187 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::frameCount_ protected
Definition at line 137 of file BackgroundRemoverTester.h.
ColorSegParams* uriComputerVision::BackgroundRemoverTester::grayParams_ protected
Definition at line 181 of file BackgroundRemoverTester.h.
RasterImage_gray_F* uriComputerVision::BackgroundRemoverTester::grayRatio_ protected
Definition at line 185 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::height_ protected
Definition at line 149 of file BackgroundRemoverTester.h.
float** uriComputerVision::BackgroundRemoverTester::intensityBg_ protected
Definition at line 216 of file BackgroundRemoverTester.h.
float** uriComputerVision::BackgroundRemoverTester::intensityImg_ protected
Definition at line 219 of file BackgroundRemoverTester.h.
float** uriComputerVision::BackgroundRemoverTester::intensityRatio_ protected
Definition at line 210 of file BackgroundRemoverTester.h.
LabelRaster* uriComputerVision::BackgroundRemoverTester::label_ protected
Definition at line 183 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::left_ protected
Definition at line 147 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::minThreshold_ protected
Definition at line 197 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::nbIncreaseRect_ protected
Definition at line 235 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::nbObjectMissed_ protected
Definition at line 207 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::nbRects_ protected
Definition at line 139 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::noiseSize_ protected
Definition at line 199 of file BackgroundRemoverTester.h.
list<bool> uriComputerVision::BackgroundRemoverTester::objectDetectList_ protected
Definition at line 205 of file BackgroundRemoverTester.h.
bool uriComputerVision::BackgroundRemoverTester::objectMatched_ protected
Definition at line 203 of file BackgroundRemoverTester.h.
RectList uriComputerVision::BackgroundRemoverTester::rectList_ protected
Definition at line 143 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::rectSize_ protected
Definition at line 153 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::rectStep_ protected
Definition at line 141 of file BackgroundRemoverTester.h.
BackgroundRemover_dynamic_MW* uriComputerVision::BackgroundRemoverTester::remover_ protected
Definition at line 135 of file BackgroundRemoverTester.h.
char* uriComputerVision::BackgroundRemoverTester::target_ protected
Definition at line 189 of file BackgroundRemoverTester.h.
BkgdTestCase uriComputerVision::BackgroundRemoverTester::testCase_ protected
Definition at line 201 of file BackgroundRemoverTester.h.
GrayThresholdLabeler* uriComputerVision::BackgroundRemoverTester::thresholder_ protected
Definition at line 179 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::top_ protected
Definition at line 145 of file BackgroundRemoverTester.h.
double uriComputerVision::BackgroundRemoverTester::totalIntensity_ protected
Definition at line 225 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::totalRects_ protected
total amount of rectangles divided in remover_
Definition at line 176 of file BackgroundRemoverTester.h.
int uriComputerVision::BackgroundRemoverTester::width_ protected
Definition at line 151 of file BackgroundRemoverTester.h.
The documentation for this class was generated from the following files:
BackgroundRemoverTester.h
BackgroundRemoverTester.cpp