URIVisionLibrary: uriVL::PolynomialFunction1D_F Class Reference
uriVL::PolynomialFunction1D_F Class Reference
Class that implements 1-dimensional polynomial functions and their derivative.
#include <PolynomialFunction1D_F.h>
Public Member Functions
PolynomialFunction1D_F (int n, const float *a)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
PolynomialFunction1D_F (int n, const float *a, const float xMin, const float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
~PolynomialFunction1D_F (void)
Destructor.
float func (float x) const
Evaluates the function at the point specified.
float dfunc (float x) const
Evaluates the first derivative of the function at the point specified.
float d2func (float x) const
Evaluates the second derivative of the function at the point specified.
float dnfunc (float x, int n) const
Evaluates the nth derivative of the function at the point specified.
bool firstDerivativeIsImplemented (void) const
Indicates that the function implements its own first derivative function.
bool secondDerivativeIsImplemented (void) const
Indicates whether the function implements its own second derivative function.
Public Member Functions inherited from uriVL::Function1D_F
Function1D_F (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Function1D_F (float xMin, float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
virtual ~Function1D_F (void)
Destructor.
virtual float dfunc (float x, int n) const
Evaluates the first derivative of the function at the point specified.
float getLowerBound (void) const
returns the lower bound of this function's domain of definition
float getUpperBound (void) const
returns the upper bound of this function's domain of definition
bool isDefinedAt (float x) const
Indicates whther a point is within the domain of definition of this function.
Private Member Functions
void initCoeffArray_ (int n, const float *a)
Initializes the array of coefficients of the polynomial and of its derivatives.
Private Attributes
int n_
degree of the polynomial
float ** a_
array of coefficients of the polynomial and of all of its derivatives
Additional Inherited Members
Protected Attributes inherited from uriVL::Function1D_F
float xMin_
lower bound of this function's domain of definition
float xMax_
upper bound of this function's domain of definition
bool isBounded_
True if finite bounds were set for the function.
Detailed Description
Class that implements 1-dimensional polynomial functions and their derivative.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 32 of file PolynomialFunction1D_F.h.
Constructor & Destructor Documentation
PolynomialFunction1D_F::PolynomialFunction1D_F (int n, const float * a)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Parameters
n degree of the polynomial function
a array of n+1 coefficients of the polynomial function (array index corresponds to power of the monomial)
Definition at line 19 of file PolynomialFunction1D_F.cpp.
References initCoeffArray_().
     :   Function1D_F()
 {
     initCoeffArray_(n, a);
 }
PolynomialFunction1D_F::PolynomialFunction1D_F (int n, const float * a, const float xMin, const float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
n degree of the polynomial function
a array of n+1 coefficients of the polynomial function (array index corresponds to power of the monomial)
Definition at line 26 of file PolynomialFunction1D_F.cpp.
References initCoeffArray_().
     :   Function1D_F(xMin, xMax)
 {
     initCoeffArray_(n, a);
 }
PolynomialFunction1D_F::~PolynomialFunction1D_F (void)
Destructor.
Definition at line 32 of file PolynomialFunction1D_F.cpp.
 {
 }
Member Function Documentation
float PolynomialFunction1D_F::d2func (float x) const virtual
Evaluates the second derivative of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the second derivative of the function at x
Reimplemented from uriVL::Function1D_F.
Definition at line 68 of file PolynomialFunction1D_F.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D_F::dfunc2");
         int mdeg = n_ - 2;
         float val = a_[2][mdeg];
         for (int i=mdeg-1; i>=0; i--)
                 val = val*x + a_[2][i];
         return val;
 }
float PolynomialFunction1D_F::dfunc (float x) const virtual
Evaluates the first derivative of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the first derivative of the function at x
Reimplemented from uriVL::Function1D_F.
Definition at line 53 of file PolynomialFunction1D_F.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D_F::dfunc");
         int mdeg = n_ - 1;
         float val = a_[1][mdeg];
         for (int i=mdeg-1; i>=0; i--)
                 val = val*x + a_[1][i];
         return val;
 }
float PolynomialFunction1D_F::dnfunc (float x, int n) const
Evaluates the nth derivative of the function at the point specified.
Parameters
x where the function should be evaluated
n the order of the derivative
Returns
the nth derivative of the function at x
Definition at line 83 of file PolynomialFunction1D_F.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, uriVL::kInvalidParameterError, and n_.
Referenced by main().
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D::dfunc");
     FAIL_CONDITION( m < 0,
                     kInvalidParameterError,
                     "Negative derivative order passed to PolynomialFunction1D::dfunc");
         float val = 0.L;
     if (m <= n_)
     {
         int mdeg = n_ - m;
         val = a_[m][mdeg];
         for (int i=mdeg-1; i>=0; i--)
             val = val*x + a_[m][i];
     }
         return val;
 }
bool uriVL::PolynomialFunction1D_F::firstDerivativeIsImplemented (void) const inline virtual
Indicates that the function implements its own first derivative function.
Returns
true
Implements uriVL::Function1D_F.
Definition at line 88 of file PolynomialFunction1D_F.h.
{
                                 return true;
                         }
float PolynomialFunction1D_F::func (float x) const virtual
Evaluates the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implements uriVL::Function1D_F.
Definition at line 40 of file PolynomialFunction1D_F.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D_F::dfunc");
     float val = a_[0][n_];
     for (int i=n_-1; i>=0; i--)
         val = val*x + a_[0][i];
     return val;
 }
void PolynomialFunction1D_F::initCoeffArray_ (int n, const float * a) private
Initializes the array of coefficients of the polynomial and of its derivatives.
Definition at line 111 of file PolynomialFunction1D_F.cpp.
References a_, FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, and n_.
Referenced by PolynomialFunction1D_F().
 {
     FAIL_CONDITION( a == NULL,
                     kNullParameterError,
                     "Null coefficient array passed to PolynomialFunction1D constructor");
     FAIL_CONDITION( n < 0,
                     kInvalidParameterError,
                     "Negative degree passed to PolynomialFunction1D constructor");
     n_ = n;
     a_ = new float*[n+1];
     for (int i=0; i<=n; i++)
     {
          if (i==0)
                 {
                         a_[0] = new float[n + 1];
             for (int j=0; j<=n; j++)
                 a_[0][j] = a[j];
         }
                 else
         {
                         int nd = n - i + 1;
                         a_[i] = new float[nd];
                     for (int j=0; j<nd; j++)
                 a_[i][j] = (j+1)*a_[i-1][j+1];
         }
     }
 }
bool uriVL::PolynomialFunction1D_F::secondDerivativeIsImplemented (void) const inline virtual
Indicates whether the function implements its own second derivative function.
Returns
true
Implements uriVL::Function1D_F.
Definition at line 96 of file PolynomialFunction1D_F.h.
{
                                 return true;
                         }
Member Data Documentation
float** uriVL::PolynomialFunction1D_F::a_ private
array of coefficients of the polynomial and of all of its derivatives
Definition at line 109 of file PolynomialFunction1D_F.h.
Referenced by d2func(), dfunc(), dnfunc(), func(), and initCoeffArray_().
int uriVL::PolynomialFunction1D_F::n_ private
degree of the polynomial
Definition at line 105 of file PolynomialFunction1D_F.h.
Referenced by d2func(), dfunc(), dnfunc(), func(), and initCoeffArray_().
The documentation for this class was generated from the following files:
PolynomialFunction1D_F.h
PolynomialFunction1D_F.cpp