URIVisionLibrary: uriVL::Contour_F Class Reference
uriVL::Contour_F Class Reference
Set of float ImagePoint objects which compose a closed curve.
#include <Contour_F.h>
Public Member Functions
Contour_F (void)
default constructor
Contour_F (const Contour_F &ct)
Copy Constructor.
Contour_F (int theNumPts)
Creates a contour with the number of vertices specified.
Contour_F (int n, const ImagePoint_F *const *pts)
Creates a contour and initializes it with the points recived as parameters.
Contour_F (const ImagePointList *ptsList)
Creates a contour and initializes it with the points recived as parameters.
~Contour_F (void)
Destructor.
void copyInto (Contour *contourOut) const
Copies this contour into the one received as parameter.
bool hasSubpixelPrecision (void) const
Indicates that the image point has subpixel precision coordinates.
void insertPoint (int position, float xVal, float yVal)
Creates a new imagepoint at the iterator position.
int getNbPoints (void) const
Gives the number of points along the contour.
const std::list< ImagePoint_F * > * getPoints (void) const
Returns the contour's private list of image points.
std::list< ImagePoint_F * > * getPoints (ReadWriteStatus rw)
Returns a writable version of the contour's private list of image points.
const std::list< ImagePoint_F * > * getEdgeList (void)
Computes the edges along the closed contour and returns it as a list of image points.
bool contains (int x, int y) const
Checks whether the point passed as parameter is inside the contour.
bool contains (const ImagePoint_F *pt) const
Checks whether the point passed as parameter is inside the contour.
bool contains (const ImagePoint *pt) const
Checks whether the point passed as parameter is inside the contour.
bool contains (float x, float y) const
Checks whether the point passed as parameter is inside the contour.
bool isInside (const Contour_I *pt) const
Checks whether this contour is completely inside the one passed as parameter.
bool isInside (const Contour_F *pt) const
Checks whether this contour is completely inside the one passed as parameter.
bool contains (const Contour_I *pt) const
Checks whether this contour completely contains the one passed as parameter.
bool contains (const Contour_F *pt) const
Checks whether this contour completely contains the one passed as parameter.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
void translate (float dx, float dy)
Translates the contour by the amounts specified.
void setPoint (int index, float x, float y)
Set the coordinates of the contour's vertex whose index is provided.
Public Member Functions inherited from uriVL::Contour
virtual ~Contour (void)
Destructor.
void initialize (int nbPts, ContourInitializer contourType, const ImageRect *rect, int padding=0)
Initializes the contour about a rectangular box.
void initialize (int nbPts, ContourInitializer contourType, const ImagePoint &center, float width, float height, float angle=0.f)
Initializes the contour along the edges of a rectangular box.
const std::list< float > * getInterPointDistances (void) const
Computes the distances between image points and returns it as a list of float numbers.
void setVertexColor (float red, float green, float blue)
Assigns a rendering color to the contour's vertices (alpha is set to 1)
void setVertexColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour (alpha is set to 1)
void setVertexColor (const float theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setVertexColor (const unsigned char theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setDrawPoints (bool drawPointCircle)
Sets whether to draw points at each vertex.
void pointsHaveMoved (void)
To be called by a user who has modified the list of points or the points themselves.
Public Member Functions inherited from uriVL::ImageFeature
ImageFeature (void)
Default constructor.
ImageFeature (const ImageFeature &obj)
Copy constructor.
virtual ~ImageFeature (void)
Destructor.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Private Member Functions
const Contour_F & operator= (const Contour_F &theObj)
Copy operator.
void initializeBox_ (const ImageRect &rect, int padding=0)
Initializes the contour along the edges of a rectangular box.
void initializeBox_ (int nbPts, const ImagePoint &upperLeft, const ImagePoint &upperRight, const ImagePoint &lowerLeft, const ImagePoint &lowerRight)
Initializes the contour about a rectangular box specified by a Rectangle .
void initializeOval_ (int nbPts, const ImagePoint &center, float width, float height, float angle=0.f)
Initializes the contour along the edges of a oval.
void computeInterPointDistances_ (void) const
Computes the distances between image points.
void computeEdgeVectorList_ (void) const
Computes the edges along the closed contour and returns it as a list of image points.
void computeBoundingRect_ (ImageRect &rect) const
Calculates the object's bounding rect.
void computeValidRect_ (ImageRect &rect) const
Calculates the object's valid box.
void computeCentroid_ (ImagePoint_F &cent) const
Computes the contour's centroid.
void computeCenterOfMass_ (ImagePoint_F &cent) const
Computes the object's center of mass by calculating the average point.
void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders the contour at the depth and location specified.
Private Attributes
std::list< ImagePoint_F * > contourList_
The contour proper, stored as a list of image points.
std::list< ImagePoint_F * > edgeList_
List of edges of the contour.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions inherited from uriVL::Contour
Contour (bool isFloatingPoint=false)
Constructor.
Contour (const Contour &ct)
Copy Constructor.
void setInterPointDistancesAreUpToDate_ (void) const
Allows a child class whose content has been changed to force recomputation of the inter-point distances.
void setEdgeVectorsAreUpToDate_ (void) const
Allows a child class whose content has been changed to force recomputation of the edge vectors.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Static Protected Attributes inherited from uriVL::Contour
static float VERTEX_DOT_RADIUS = 4.f
Radius of the circular dot used to render a vertex.
Detailed Description
Set of float ImagePoint objects which compose a closed curve.
Author
Clifford Manzanillo, jyh Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file Contour_F.h.
Constructor & Destructor Documentation
Contour_F::Contour_F (void)
default constructor
Definition at line 63 of file Contour_F.cpp.
                 :   Contour(),
                         //
                         contourList_(list <ImagePoint_F*>()),
                         edgeList_(list <ImagePoint_F*>())
 {
 }
Contour_F::Contour_F (const Contour_F & ct)
Copy Constructor.
Parameters
ct reference to the object to copy
Definition at line 30 of file Contour_F.cpp.
References contourList_, and edgeList_.
                 :   Contour(ct),
                         //
                         contourList_(list <ImagePoint_F*>()),
                         edgeList_(list <ImagePoint_F *>())
 {
     list<ImagePoint_F *>::const_iterator iter0, iter1;
     list<float>::const_iterator iter2;
     if (!(ct.contourList_.empty()))
     {
             iter0 = ct.contourList_.begin();
             for( ; iter0!=ct.contourList_.end(); iter0++)
                 contourList_.push_back(new ImagePoint_F(*iter0));
         }
     if (!(ct.edgeList_.empty()))
     {
             iter1 = ct.edgeList_.begin();
             for( ; iter1!=ct.edgeList_.end(); iter1++)
                 edgeList_.push_back(new ImagePoint_F(*iter1));
         }
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by Contour_F constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter passed to Contour_F constructor");
 }
Contour_F::Contour_F (int theNumPts)
Creates a contour with the number of vertices specified.
Parameters
theNumPts number of points of the contour to create
Definition at line 117 of file Contour_F.cpp.
References contourList_.
                 :   Contour(false),
                         contourList_(list <ImagePoint_F*>()),
                         edgeList_(list <ImagePoint_F *>())
 {
     for(int i = 0;i < theNumPts; i++)
     {
         contourList_.push_back(new ImagePoint_F(0.f, 0.f));
     }
 }
Contour_F::Contour_F (int n, const ImagePoint_F *const * pts)
Creates a contour and initializes it with the points recived as parameters.
Parameters
n number of points of the contour to create
pts array of points to initialize thed contour with
Definition at line 96 of file Contour_F.cpp.
References contourList_, FAIL_CONDITION, uriVL::kInvalidParameterError, and uriVL::kNullParameterError.
                 :   Contour(true),
                         //
                         contourList_(list <ImagePoint_F*>()),
                         edgeList_(list <ImagePoint_F *>())
 {
         try {
                 for(int i = 0;i < theNumPts; i++)
                         contourList_.push_back(new ImagePoint_F(theContourPts[i]));
         }
         catch (...)
         {
                 FAIL_CONDITION( theContourPts == NULL,
                                                 kNullParameterError,
                                                 "Null array passed to Contour_F constructor");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid parameter passed to Contour_F constructor");
         }
 }
Contour_F::Contour_F (const ImagePointList * ptsList)
Creates a contour and initializes it with the points recived as parameters.
Parameters
ptsList ImagePointList
Definition at line 71 of file Contour_F.cpp.
References contourList_, FAIL_CONDITION, uriVL::kInvalidParameterError, and uriVL::kNullParameterError.
                 :   Contour(true),
                         //
                         contourList_(list <ImagePoint_F*>()),
                         edgeList_(list <ImagePoint_F *>())
 {
         try {
                 for(ImagePoint_FList::const_iterator iter = ptsList->begin() ;iter!=ptsList->end(); iter++)
                 {
                         contourList_.push_back(new ImagePoint_F(*iter));
                 }
         }
         catch (...)
         {
                 FAIL_CONDITION( ptsList == NULL,
                                                 kNullParameterError,
                                                 "Null pointer to point list passed to Contour_F constructor");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid parameter passed to Contour_F constructor");
         }
 }
Contour_F::~Contour_F (void)
Destructor.
Definition at line 129 of file Contour_F.cpp.
References contourList_, and edgeList_.
 {
         //      delete the point list
         list<ImagePoint_F*>::iterator   endPtList = contourList_.end();
         for(list<ImagePoint_F*>::iterator iter = contourList_.begin(); iter!=endPtList; iter++)
                 delete (*iter);
         contourList_.clear();
         //      delete the edge list
         list<ImagePoint_F*>::iterator   endEdgeList = edgeList_.end();
         for(list<ImagePoint_F*>::iterator iter = edgeList_.begin(); iter!=endEdgeList; iter++)
                 delete (*iter);
         edgeList_.clear();
 }
Member Function Documentation
void Contour_F::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implements uriVL::DrawableObject2D.
Definition at line 245 of file Contour_F.cpp.
References FAIL_CONDITION, uriVL::RigidTransformation2D::getAngle(), uriVL::RigidTransformation2D::getTransX(), uriVL::RigidTransformation2D::getTransY(), uriVL::Transformation2D::isRigidTransformation(), uriVL::kFunctionNotImplemented, uriVL::kNullParameterError, uriVL::Contour::pointsHaveMoved(), rotate(), and translate().
 {
     FAIL_CONDITION( theTransf == NULL,
                     kNullParameterError,
                     "null Transformation2D passed to Contour_F::applyTransformation");
     if (theTransf->isRigidTransformation())
     {
         RigidTransformation2D   *rigidTransf = (RigidTransformation2D*) theTransf;
         rotate(rigidTransf->getAngle());
         translate(rigidTransf->getTransX(), rigidTransf->getTransY());
         }
     else
         FAIL_CONDITION( true,
                         kFunctionNotImplemented,
                         "Function not implemented yet");
     pointsHaveMoved();
 }
void Contour_F::computeBoundingRect_ (ImageRect & rect) const private virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 466 of file Contour_F.cpp.
References contourList_, and uriVL::ImageRect::setRect().
 {
         list<ImagePoint_F*>::const_iterator firstIter = contourList_.begin();
         float   maxX = (*firstIter)->getXF(),
                         minX = maxX,
                         maxY = (*firstIter)->getYF(),
                         minY = maxY;
         list<ImagePoint_F*>::const_iterator endIter = contourList_.end();
     for(list<ImagePoint_F*>::const_iterator iter = firstIter; iter != endIter; iter++)
         {
                 float   xi  = (*iter)->getXF(),
                                 yi = (*iter)->getYF();
                 if (xi > maxX)
                         maxX = xi;
                 else if(xi < minX)
                         minX = xi;
                 if(yi > maxY)
                         maxY = yi;
                 else if(yi < minY)
                         minY = yi;
         }
         rect.setRect(static_cast<int>(minX), static_cast<int>(minY),
                                 static_cast<int>(maxX - minX + 1.5f), static_cast<int>(maxY - minY + 1.5f));
 }
void Contour_F::computeCenterOfMass_ (ImagePoint_F & cent) const private virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implements uriVL::DrawableObject2D.
Definition at line 395 of file Contour_F.cpp.
References contourList_, and uriVL::ImagePoint_F::setCoordinates().
{
         int             theNumPts = 0;
         float   averageX = 0.f,
                         averageY = 0.f;
         //iterate through the list and add the coordinate values.
         list<ImagePoint_F*>::const_iterator iter, endList = contourList_.end();
         for(iter = contourList_.begin(); iter != endList; iter++){
                 theNumPts++;
                 averageX += (*iter)->getXF();
                 averageY += (*iter)->getYF();
         }
         averageX /= theNumPts;
         averageY /= theNumPts;
         cent.setCoordinates(averageX, averageY);
 }
void Contour_F::computeCentroid_ (ImagePoint_F & cent) const private virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implements uriVL::DrawableObject2D.
Definition at line 370 of file Contour_F.cpp.
References contourList_, HUGE_VALF, and uriVL::ImagePoint_F::setCoordinates().
{
         list<ImagePoint_F*>::const_iterator iter = contourList_.begin();
         float   maxX = -HUGE_VALF,
                         minX = HUGE_VALF,
                         maxY = -HUGE_VALF,
                         minY = HUGE_VALF;
         for(iter = contourList_.begin(); iter != contourList_.end(); iter++){
                 float   xi  = (*iter)->getXF(),
                                 yi = (*iter)->getYF();
                 if (xi > maxX)
                         maxX = xi;
                 else if(xi < minX)
                         minX = xi;
                 if(yi > maxY)
                         maxY = yi;
                 else if(yi < minY)
                         minY = yi;
         }
         cent.setCoordinates((maxX-minX)/2, (maxY-minY)/2);
 }
void Contour_F::computeEdgeVectorList_ (void) const private virtual
Computes the edges along the closed contour and returns it as a list of image points.
Admittedly, it is not pretty to use an ImagePoint object to store a vector. This will have to be changed in the not-too-distant future;
This function returns private data of the contour object. Do not modify it.
See also
getEdgeList
edgeList_
Implements uriVL::Contour.
Definition at line 441 of file Contour_F.cpp.
References contourList_, edgeList_, and uriVL::Contour::edgeVectorsAreUpToDate_.
Referenced by computeInterPointDistances_(), and getEdgeList().
{
         if (!edgeVectorsAreUpToDate_){
                 ImagePoint_F *myPoint;
                 edgeList_.clear();
                 list<ImagePoint_F*>::const_iterator     iter, itp1,
                                                                 firstList = contourList_.begin(),
                                                                 endList = contourList_.end();
                 for(iter = firstList, itp1 = firstList; iter != endList; iter++){
                         itp1++;
                         if(itp1 == contourList_.end() )
                         itp1 = contourList_.begin();
                         myPoint = new ImagePoint_F((*itp1)->getXF() - (*iter)->getXF(),
                                                                         (*itp1)->getYF() - (*iter)->getYF());
                         edgeList_.push_back(myPoint);
                 }
                 edgeVectorsAreUpToDate_ = true;
         }
 }
void Contour_F::computeInterPointDistances_ (void) const private virtual
Computes the distances between image points.
See also
getInterPointDistances
ptDistance_
Implements uriVL::Contour.
Definition at line 414 of file Contour_F.cpp.
References computeEdgeVectorList_(), contourList_, uriVL::Contour::edgeVectorsAreUpToDate_, uriVL::Contour::interPointDistancesAreUpToDate_, and uriVL::Contour::ptDistance_.
{
         if (!interPointDistancesAreUpToDate_){
                 if (!edgeVectorsAreUpToDate_)
                         computeEdgeVectorList_();
                 ptDistance_.clear();
                 list<ImagePoint_F*>::const_iterator     iter, itp1,
                                                                                                 firstList = contourList_.begin(),
                                                                                                 endList = contourList_.end();
                 for(iter = firstList, itp1 = firstList; iter != endList; iter++){
                         itp1++;
                         if(itp1 == contourList_.end())
                                 itp1 = contourList_.begin();
                         // calculate the distance from the current point to
                         // the next
                         float   dx = (*itp1)->getXF() - (*iter)->getXF(),
                                         dy = (*itp1)->getYF() - (*iter)->getYF();
                         ptDistance_.push_back( sqrtf(dx*dx + dy*dy));
                 }
                 interPointDistancesAreUpToDate_ = true;
         }
 }
void Contour_F::computeValidRect_ (ImageRect & rect) const private virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 495 of file Contour_F.cpp.
References uriVL::DrawableObject2D::getBoundRect(), and uriVL::ImageRect::setRect().
 {
         //      the valid rect is the same as the bounding rect.  If the bounding rect
         //      is up to date, use its dimensions, else recompute it first
         rect.setRect(getBoundRect());
 }
bool Contour_F::contains (int x, int y) const virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
Returns
true if pt is inside this contour
Implements uriVL::Contour.
Definition at line 300 of file Contour_F.cpp.
Referenced by contains().
 {
         return contains((float) x, (float) y);
 }
bool Contour_F::contains (const ImagePoint_F * pt) const virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
pt the point to check
Returns
true if pt is inside this contour
Implements uriVL::Contour.
Definition at line 321 of file Contour_F.cpp.
References contains(), FAIL_CONDITION, uriVL::ImagePoint_F::getXF(), uriVL::ImagePoint_F::getYF(), and uriVL::kNullImagePointError.
 {
     FAIL_CONDITION( pt == NULL,
                     kNullImagePointError,
                     "null ImagePoint in Contour_F::contains");
     return contains(pt->getXF(), pt->getYF());
 }
bool Contour_F::contains (const ImagePoint * pt) const virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
pt the point to check
Returns
true if pt is inside this contour
Implements uriVL::Contour.
Definition at line 313 of file Contour_F.cpp.
References contains(), FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and uriVL::kNullImagePointError.
 {
     FAIL_CONDITION( pt == NULL,
                     kNullImagePointError,
                     "null ImagePoint in Contour_F::contains");
     return contains((float) (pt->getX()), (float) (pt->getY()));
 }
bool Contour_F::contains (float x, float y) const virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
Returns
true if pt is inside this contour
Implements uriVL::Contour.
Definition at line 305 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "not implemented yet");
         return false;
 }
bool Contour_F::contains (const Contour_I * pt) const
Checks whether this contour completely contains the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour contains theContour
Definition at line 329 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     return false;
 }
bool Contour_F::contains (const Contour_F * pt) const
Checks whether this contour completely contains the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour contains theContour
Definition at line 337 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     return false;
 }
void Contour_F::copyInto (Contour * contourOut) const virtual
Copies this contour into the one received as parameter.
Parameters
contourOut The contour to copy this one into
Implements uriVL::Contour.
Definition at line 162 of file Contour_F.cpp.
References FAIL_CONDITION, uriVL::kFunctionNotImplemented, and uriVL::kInvalidRasterType.
 {
         //  so far I only accept another Contour_F as a destination
         FAIL_CONDITION( typeid(*contourOut) != typeid(uriVL::Contour_F),
                                         kInvalidRasterType,
                                         "Contour_F::copyInto only accepts Contour_F contours as destination");
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "not implemented yet");
 }
const list< ImagePoint_F * > * Contour_F::getEdgeList (void)
Computes the edges along the closed contour and returns it as a list of image points.
Admittedly, it is not pretty to use an ImagePoint object to store a vector. This will have to be changed in the not-too-distant future;
This function returns private data of the contour object. Do not modify it.
See also
computeEdgeVectorList
edgeList_
Definition at line 184 of file Contour_F.cpp.
References computeEdgeVectorList_(), edgeList_, and uriVL::Contour::edgeVectorsAreUpToDate_.
Referenced by uriVL::ActiveContourDetector_balloon::calculateShrinkForce_().
 {
         if (!edgeVectorsAreUpToDate_)
                 computeEdgeVectorList_();
         return &edgeList_;
 }
int Contour_F::getNbPoints (void) const virtual
Gives the number of points along the contour.
Returns
number of points along the contour
Implements uriVL::Contour.
Definition at line 221 of file Contour_F.cpp.
References contourList_.
Referenced by uriVL::ContourForce::addForce(), uriVL::ContourForce::applyForceToContour(), and uriVL::ContourForce::mapToContour().
{
         return static_cast<int>(contourList_.size());
 }
const list< ImagePoint_F * > * Contour_F::getPoints (void) const
Returns the contour's private list of image points.
Definition at line 225 of file Contour_F.cpp.
References contourList_.
Referenced by uriVL::ContourForce::applyForceToContour(), uriVL::ActiveContourDetector_balloon::calculateEdgeForce_(), uriVL::ActiveContourDetector::calculateInternalForce_(), uriVL::ActiveContourDetector_balloon::calculateShrinkForce_(), uriVL::ContourForce::render_(), and uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_().
 {
         return &contourList_;
 }
list< ImagePoint_F * > * Contour_F::getPoints (ReadWriteStatus rw)
Returns a writable version of the contour's private list of image points.
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 230 of file Contour_F.cpp.
References contourList_.
{
         return &contourList_;
 }
bool uriVL::Contour_F::hasSubpixelPrecision (void) const inline virtual
Indicates that the image point has subpixel precision coordinates.
Returns
true if image point has subpixel precision
Implements uriVL::Contour.
Definition at line 79 of file Contour_F.h.
{
                                 return true;
                         }
void Contour_F::initializeBox_ (const ImageRect & rect, int padding = 0) private virtual
Initializes the contour along the edges of a rectangular box.
Parameters
rect rectangular box
padding distance away from the box at which to initialize the contour (positive: outer padding; negative: inner padding)
Implements uriVL::Contour.
Definition at line 560 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "This contour intializer is not implemented yet.");
 }
void Contour_F::initializeBox_ (int nbPts, const ImagePoint & upperLeft, const ImagePoint & upperRight, const ImagePoint & lowerLeft, const ImagePoint & lowerRight) private virtual
Initializes the contour about a rectangular box specified by a Rectangle .
This function wil be called by the parent class Contour and it can be safely assumed that the
Parameters
nbPts number of points to create along the contour
upperLeft coordinates of the box's upper-left corner
Implements uriVL::Contour.
Definition at line 569 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
 //      int     balloonXPtMin = rect->getLeft() + 2*padding + 1,
 //              balloonYPtMin = rect->getTop() + 2*padding + 1,
 //              balloonHeight = rect->getHeight() - 4*padding - 2,
 //              balloonWidth = rect->getWidth() - 4*padding - 2;
 //
 //      //number of contour points
 //      float   lengthPlusWidth = (balloonWidth + balloonHeight),
 //                      doubleWidth = balloonWidth * 2,
 //                      perimeter = 2 * lengthPlusWidth,
 //                      distBetweenPts =  perimeter / getNbPoints();
 //
 //      //set the initial positions of contour points around frame evenly, counter clockwise.
 //      //since the lower-left corner is the origin point, so all coordinates are positive
 //      int i = 0;
 //
 //      list<ImagePoint_F*>::iterator iter, endList = contourList_.end();
 //      for(iter = contourList_.begin(); iter != endList; i++, iter++){
 //              float arcLengthOfPerimeter = (i * distBetweenPts);
 //
 //              if (arcLengthOfPerimeter < balloonWidth){
 //                      (*iter)->setCoordinates(balloonXPtMin + arcLengthOfPerimeter,
 //                                                              static_cast<float>(balloonYPtMin));
 //              }else if ((arcLengthOfPerimeter >= balloonWidth) &&
 //                              (arcLengthOfPerimeter < lengthPlusWidth)){
 //                      (*iter)->setCoordinates(static_cast<float>(balloonXPtMin + balloonWidth),
 //                                                              balloonYPtMin + arcLengthOfPerimeter - balloonWidth);
 //
 //              }else if ((arcLengthOfPerimeter >= lengthPlusWidth)
 //                              && (arcLengthOfPerimeter < (doubleWidth + balloonHeight))){
 //                      (*iter)->setCoordinates(balloonXPtMin + doubleWidth + balloonHeight - arcLengthOfPerimeter,
 //                                                              static_cast<float>(balloonYPtMin + balloonHeight));
 //              }else{
 //                      (*iter)->setCoordinates(static_cast<float>(balloonXPtMin),
 //                                                              balloonYPtMin + perimeter - arcLengthOfPerimeter);
 //              }
 //      }
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "This contour intializer is not implemented yet.");
 }
void Contour_F::initializeOval_ (int nbPts, const ImagePoint & center, float width, float height, float angle = 0.f) private virtual
Initializes the contour along the edges of a oval.
Parameters
nbPts number of points to create along the contour
contourType the type of contour to initialize this one to
center coordinates of the contour's center
width width of the box or ellipse
height height of the box or ellipse
angle orientation of the contour
Implements uriVL::Contour.
Definition at line 617 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "This contour intializer is not implemented yet.");
 }
void Contour_F::insertPoint (int position, float xVal, float yVal)
Creates a new imagepoint at the iterator position.
Parameters
xVal x coordinate of the new point
yVal y coordinate of the new point
Definition at line 211 of file Contour_F.cpp.
References contourList_.
Referenced by uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_().
{
         ImagePoint_F  *newPoint = new ImagePoint_F(xVal, yVal);
         list<ImagePoint_F*>::iterator iter = contourList_.begin();
         for(int i = 0; i < pointIndex; i++){
                 iter++;
         }
         contourList_.insert(iter, newPoint);
 }
bool Contour_F::isInside (const Contour_I * pt) const virtual
Checks whether this contour is completely inside the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour is inside theContour
Implements uriVL::Contour.
Definition at line 345 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     return false;
 }
bool Contour_F::isInside (const Contour_F * pt) const virtual
Checks whether this contour is completely inside the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour is inside theContour
Implements uriVL::Contour.
Definition at line 353 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     return false;
 }
const Contour_F & Contour_F::operator= (const Contour_F & theObj) private
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 152 of file Contour_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Contour_F copy operator not implemented");
         return *this;
 }
void Contour_F::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private virtual
Renders the contour at the depth and location specified.
A drawable object can be rendered with its valid data rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
Implements uriVL::DrawableObject2D.
Definition at line 510 of file Contour_F.cpp.
References contourList_, uriVL::Contour::drawPoints_, uriVL::fillCircularDot(), uriVL::DrawableObject2D::getColor(), uriVL::DrawableObject2D::getRenderingScaleX(), uriVL::DrawableObject2D::getRenderingScaleY(), uriVL::Contour::VERTEX_DOT_RADIUS, and uriVL::Contour::vertexColor_.
 {
         //--------------------------------------------------------------
         //      Render the contour
         //--------------------------------------------------------------
         //
         glPushMatrix();
         glLoadIdentity();
         glTranslatef(scaledLeft, scaledTop, theZ);
         glScalef(getRenderingScaleX(), -getRenderingScaleY(), 1.f);
         glColor4fv(getColor());
         list<ImagePoint_F*>::const_iterator endList = contourList_.end();
         glBegin(GL_LINE_LOOP);
                 for(list<ImagePoint_F*>::const_iterator iter = contourList_.begin(); iter != endList; iter++)
                 {
                         glVertex2f( (*iter)->getXF(), (*iter)->getYF());
                 }
         glEnd();
         if(drawPoints_){
                 glColor4fv(vertexColor_);
         for(list<ImagePoint_F*>::const_iterator iter = contourList_.begin(); iter != endList; iter++)
                 {
             glPushMatrix();
             glTranslatef((*iter)->getXF(), (*iter)->getYF(), 0);
                         glScalef(VERTEX_DOT_RADIUS, VERTEX_DOT_RADIUS, 1.f);
                         uriVL::fillCircularDot();
             glPopMatrix();
         }
         }
         glPopMatrix();
 }
void Contour_F::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implements uriVL::DrawableObject2D.
Definition at line 265 of file Contour_F.cpp.
References contourList_, and uriVL::Contour::pointsHaveMoved().
Referenced by applyTransformation().
{
         float   cosA = cosf(angle),
             sinA = sinf(angle);
         list<ImagePoint_F*>::iterator   iter;
         for(iter = contourList_.begin(); iter != contourList_.end(); iter++){
                 float   copyOfCntourPtsX = (*iter)->getXF(),
                                 copyOfCntourPtsY = (*iter)->getY();
                 (*iter)->setCoordinates(copyOfCntourPtsX * cosA - copyOfCntourPtsY * sinA,
                                                         copyOfCntourPtsX * sinA + copyOfCntourPtsY * cosA);
         }
         pointsHaveMoved();
 }
void Contour_F::setPoint (int index, float x, float y) virtual
Set the coordinates of the contour's vertex whose index is provided.
Fails if the index is larger that the number of vertices of the contour.
Parameters
index index of the vertex to modify
x new x coordinate of the vertex
y new y coordinate of the vertex
Implements uriVL::Contour.
Definition at line 196 of file Contour_F.cpp.
References contourList_.
 {
         if (static_cast<unsigned int>(pointIndex) <= contourList_.size())
         {
                 list<ImagePoint_F*>::iterator iter = contourList_.begin();
                 for(int i = 0; i <= pointIndex; i++)
                 {
                         iter++;
                 }
                 (*iter)->setCoordinates(x, y);
         }
 }
void Contour_F::translate (float dx, float dy) virtual
Translates the contour by the amounts specified.
Parameters
dx x translation to apply
dy y translation to apply
Reimplemented from uriVL::DrawableObject2D.
Definition at line 282 of file Contour_F.cpp.
References contourList_, and uriVL::Contour::pointsHaveMoved().
Referenced by applyTransformation().
{
         list<ImagePoint_F*>::iterator   iter,
                                                         endList = contourList_.end();
         for(iter = contourList_.begin(); iter != endList; iter++)
                 (*iter)->translate(tx, ty);
 //TODO: should not have to recompute center of mass and rect:  only translate them as well
         pointsHaveMoved();
 }
Member Data Documentation
std::list<ImagePoint_F*> uriVL::Contour_F::contourList_ private
The contour proper, stored as a list of image points.
Definition at line 202 of file Contour_F.h.
Referenced by computeBoundingRect_(), computeCenterOfMass_(), computeCentroid_(), computeEdgeVectorList_(), computeInterPointDistances_(), Contour_F(), getNbPoints(), getPoints(), insertPoint(), render_(), rotate(), setPoint(), translate(), and ~Contour_F().
std::list<ImagePoint_F *> uriVL::Contour_F::edgeList_ mutable private
List of edges of the contour.
Definition at line 206 of file Contour_F.h.
Referenced by computeEdgeVectorList_(), Contour_F(), getEdgeList(), and ~Contour_F().
The documentation for this class was generated from the following files:
Contour_F.h
Contour_F.cpp