URIVisionLibrary: uriVL::BackgroundRemover_dynamic Class Reference
uriVL::BackgroundRemover_dynamic Class Reference abstract
This class cannot be instantiated Inherited from: BackgroundRemover_dynamic Deal with changing background.
#include <BackgroundRemover_dynamic.h>
Public Member Functions
virtual ~BackgroundRemover_dynamic (void)
Destructor.
void setBackground (RasterImage *bkgd)
Overidden virtual func.
virtual void updateBackground (RasterImage *img, ConstRectList rectList)=0
virtual func Update background_
Public Member Functions inherited from uriVL::BackgroundRemover
BackgroundRemover (void)
Default constructor.
virtual ~BackgroundRemover (void)
Destructor.
RasterImage_gray * removeBackground (RasterImage *imgIn)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images)
RasterImage_gray * removeBackground (RasterImage *imgIn, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images) into a gray-level raster image received as parameter.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background into a gray-level raster image received as parameter.
void setColorDifferenceMode (ColorDifferenceMode mode)
Sets the default color difference mode for this object.
RasterImage * getBackground (void)
get background_;
ColorDifferenceMode getColorDifferenceMode (void)
Reports what is the color difference mode for this object.
Protected Member Functions
RasterImage * getFirstBackground_ (void)
Returns a pointer to the first background image.
BackgroundRemover_dynamic (void)
Default constructor.
Protected Member Functions inherited from uriVL::BackgroundRemover
void assignBackground_ (RasterImage *img)
Private Member Functions
BackgroundRemover_dynamic (const BackgroundRemover_dynamic &obj)
Copy constructor disabled.
const BackgroundRemover_dynamic & operator= (const BackgroundRemover_dynamic &obj)
Copy operator disabled.
Private Attributes
RasterImage * firstBackground_
First background image.
Detailed Description
This class cannot be instantiated Inherited from: BackgroundRemover_dynamic Deal with changing background.
Definition at line 32 of file BackgroundRemover_dynamic.h.
Constructor & Destructor Documentation
BackgroundRemover_dynamic::~BackgroundRemover_dynamic (void) virtual
Destructor.
Definition at line 26 of file BackgroundRemover_dynamic.cpp.
 {
         delete firstBackground_;
 }
BackgroundRemover_dynamic::BackgroundRemover_dynamic (void) protected
Default constructor.
Definition at line 48 of file BackgroundRemover_dynamic.cpp.
             :   BackgroundRemover(),
                 //
                 firstBackground_(NULL)
 {
 }
BackgroundRemover_dynamic::BackgroundRemover_dynamic (const BackgroundRemover_dynamic & obj) private
Copy constructor disabled.
Parameters
obj the object to copy
Definition at line 61 of file BackgroundRemover_dynamic.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
             :   BackgroundRemover(),
                 //
                 firstBackground_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "BackgroundRemover_dynamic copy constructor disabled");
 }
Member Function Documentation
RasterImage * BackgroundRemover_dynamic::getFirstBackground_ (void) protected
Returns a pointer to the first background image.
Returns
pointer to the first background image
Definition at line 55 of file BackgroundRemover_dynamic.cpp.
References firstBackground_.
Referenced by uriVL::BackgroundRemover_dynamic_MW::updateBackground().
 {
     return firstBackground_;
 }
const BackgroundRemover_dynamic & BackgroundRemover_dynamic::operator= (const BackgroundRemover_dynamic & obj) private
Copy operator disabled.
Parameters
obj the object to copy
Definition at line 74 of file BackgroundRemover_dynamic.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "BackgroundRemover_dynamic copy operator disabled");
     return *this;
 }
void BackgroundRemover_dynamic::setBackground (RasterImage * bkgd) virtual
Overidden virtual func.
Stores a copy of img to use as firstBackground_(NOT background_) for future image difference computations
Parameters
bkgd raster image to store as firstBackground_
Implements uriVL::BackgroundRemover.
Reimplemented in uriVL::BackgroundRemover_dynamic_MW.
Definition at line 32 of file BackgroundRemover_dynamic.cpp.
References uriVL::ErrorReport::appendToMessage().
Referenced by uriVL::BackgroundRemover_dynamic_MW::setBackground().
 {
     try {
         assignBackground_(bkgd);
     }
     catch (ErrorReport& e) {
         e.appendToMessage("called by BackgroundRemover_dynamic::setBackground.");
         throw e;
     }
     firstBackground_    = new RasterImage_gray(getBackground());
 }
virtual void uriVL::BackgroundRemover_dynamic::updateBackground (RasterImage * img, ConstRectList rectList) pure virtual
virtual func Update background_
Implemented in uriVL::BackgroundRemover_dynamic_MW.
Member Data Documentation
RasterImage* uriVL::BackgroundRemover_dynamic::firstBackground_ private
First background image.
Definition at line 72 of file BackgroundRemover_dynamic.h.
Referenced by getFirstBackground_(), uriVL::BackgroundRemover_dynamic_MW::updateBackground(), and uriVL::BackgroundRemover_dynamic_MW::updateBackground_().
The documentation for this class was generated from the following files:
BackgroundRemover_dynamic.h
BackgroundRemover_dynamic.cpp