URIVisionLibrary: uriVL::RandomGenerator_MT Class Reference
uriVL::RandomGenerator_MT Class Reference
Random number generator class that uses the Mersenne Twister algorithm of Matsumoto and Nishimura implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
#include <RandomGenerator_MT.h>
Public Member Functions
RandomGenerator_MT (void)
Constructor.
RandomGenerator_MT (long theSeed)
Creates a new RandomGenerator object seeded with the value received as parameter.
~RandomGenerator_MT (void)
Destructor.
unsigned long nextULong (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
double nextDouble (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
double nextDouble (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
void setSeed (long theSeed)
Sets a new seed for this generator.
Public Member Functions inherited from uriVL::RandomGenerator
virtual ~RandomGenerator (void)
Destructor.
virtual unsigned int nextUInt (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
virtual int nextInt (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
virtual long nextLong (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
virtual float nextFloat (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
virtual float nextFloat (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
virtual double nextGaussian (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Static Public Member Functions
static unsigned int nextUInt_st (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
static int nextInt_st (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
static unsigned long nextULong_st (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
static long nextLong_st (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
static float nextFloat_st (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
static float nextFloat_st (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
static double nextDouble_st (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
static double nextDouble_st (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
static double nextGaussian_st (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
static void setSeed_st (long theSeed)
Sets a new seed for this generator.
Private Attributes
unsigned int seed_
the generator's seed
Static Private Attributes
static RandomGenerator_MT * rg_ = new RandomGenerator_MT()
The unique object of this class, stored as a static member.
Additional Inherited Members
Protected Member Functions inherited from uriVL::RandomGenerator
RandomGenerator (void)
Creates a new RandomGenerator object.
Static Protected Attributes inherited from uriVL::RandomGenerator
static const bool INT_IS_LONG = (sizeof(int) == sizeof(long))
Indicates whether an int has the same length as a long (should be true non most platforms.
Detailed Description
Random number generator class that uses the Mersenne Twister algorithm of Matsumoto and Nishimura implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
I have tried as much as possible to preserve the original code and comments. The main change is the implementation of setSeed.
Definition at line 33 of file RandomGenerator_MT.h.
Constructor & Destructor Documentation
RandomGenerator_MT::RandomGenerator_MT (void)
Constructor.
Definition at line 36 of file RandomGenerator_MT.cpp.
     :   RandomGenerator(),
                 //
                 seed_(time(NULL))
 {
 }
uriVL::RandomGenerator_MT::RandomGenerator_MT (long theSeed)
Creates a new RandomGenerator object seeded with the value received as parameter.
Parameters
theSeed new seed value for this generator
RandomGenerator_MT::~RandomGenerator_MT (void)
Destructor.
Definition at line 44 of file RandomGenerator_MT.cpp.
 {
 }
Member Function Documentation
double RandomGenerator_MT::nextDouble (double lowVal, double highVal) virtual
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Implements uriVL::RandomGenerator.
Definition at line 58 of file RandomGenerator_MT.cpp.
References INV_MAX_ULONG, and nextULong().
Referenced by nextDouble_st().
 {
     return INV_MAX_ULONG * nextULong() * (highVal - lowVal) + lowVal;
 }
double RandomGenerator_MT::nextDouble (void) virtual
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Implements uriVL::RandomGenerator.
Definition at line 64 of file RandomGenerator_MT.cpp.
References INV_MAX_ULONG, and nextULong().
 {
     return INV_MAX_ULONG * nextULong();
 }
double RandomGenerator_MT::nextDouble_st (void) static
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Definition at line 108 of file RandomGenerator_MT.cpp.
References nextDouble(), and rg_.
 {
     return rg_->nextDouble();
 }
double RandomGenerator_MT::nextDouble_st (double lowVal, double highVal) static
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Definition at line 113 of file RandomGenerator_MT.cpp.
References nextDouble(), and rg_.
 {
     return rg_->nextDouble(lowVal, highVal);
 }
float RandomGenerator_MT::nextFloat_st (void) static
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
Returns
new float pseudo-random value in the range [0, 1[
Definition at line 98 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat();
 }
float RandomGenerator_MT::nextFloat_st (float lowVal, float highVal) static
Returns a new uniformly-distributed float pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new float pseudo-random value in thhe range [lowVal, highVal[
Definition at line 103 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat(lowVal, highVal);
 }
double RandomGenerator_MT::nextGaussian_st (double sigma = 1.L) static
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Parameters
sigma standard deviation of the distribution
Returns
new normally-distributed double pseudo-random value in the range [0, 1[
Definition at line 118 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextGaussian(), and rg_.
 {
     return rg_->nextGaussian(sigma);
 }
int RandomGenerator_MT::nextInt_st (int lowVal, int highVal) static
Returns a new uniformly-distributed int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 83 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextInt(), and rg_.
 {
     return rg_->nextInt(lowVal, highVal);
 }
long RandomGenerator_MT::nextLong_st (long lowVal, long highVal) static
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 93 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextLong(), and rg_.
 {
     return rg_->nextLong(lowVal, highVal);
 }
unsigned int RandomGenerator_MT::nextUInt_st (void) static
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned int pseudo-random value
Definition at line 78 of file RandomGenerator_MT.cpp.
References uriVL::RandomGenerator::nextUInt(), and rg_.
 {
     return rg_->nextUInt();
 }
unsigned long RandomGenerator_MT::nextULong (void) virtual
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Implements uriVL::RandomGenerator.
Definition at line 53 of file RandomGenerator_MT.cpp.
Referenced by nextDouble(), and nextULong_st().
 {
     return 0L;
 }
unsigned long RandomGenerator_MT::nextULong_st (void) static
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Definition at line 88 of file RandomGenerator_MT.cpp.
References nextULong(), and rg_.
 {
     return rg_->nextULong();
 }
void RandomGenerator_MT::setSeed (long theSeed) virtual
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Implements uriVL::RandomGenerator.
Definition at line 48 of file RandomGenerator_MT.cpp.
References seed_.
Referenced by setSeed_st().
 {
         seed_ = theSeed;
 }
void RandomGenerator_MT::setSeed_st (long theSeed) static
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Definition at line 73 of file RandomGenerator_MT.cpp.
References rg_, and setSeed().
 {
     rg_->setSeed(theSeed);
 }
Member Data Documentation
RandomGenerator_MT * RandomGenerator_MT::rg_ = new RandomGenerator_MT() static private
The unique object of this class, stored as a static member.
Definition at line 147 of file RandomGenerator_MT.h.
Referenced by nextDouble_st(), nextFloat_st(), nextGaussian_st(), nextInt_st(), nextLong_st(), nextUInt_st(), nextULong_st(), and setSeed_st().
unsigned int uriVL::RandomGenerator_MT::seed_ private
the generator's seed
Definition at line 151 of file RandomGenerator_MT.h.
Referenced by setSeed().
The documentation for this class was generated from the following files:
RandomGenerator_MT.h
RandomGenerator_MT.cpp