URIVisionLibrary: uriVL::Prism3D Class Reference
uriVL::Prism3D Class Reference
Prism3D class.
#include <Prism3D.h>
Public Member Functions
Prism3D (int n, GLfloat **topFace, GLfloat **bottomFace, bool isClosed, bool isSmooth)
Prism3D (int n, GLfloat **bottomFace, GLfloat *axis, bool isClosed, bool isSmooth)
~Prism3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
Prism3D (const Prism3D &obj)
Copy constructor (disabled)
const Prism3D & operator= (const Prism3D &obj)
Copy operator: disabled.
void init_ (GLfloat **topFace, GLfloat **bottomFace)
void deleteArrays_ (void)
Delete all allocated arrays.
Private Attributes
GLfloat *** vertex_
0-based list of vertices
GLfloat ** normalF_
0-based list of normals
GLfloat *** normalV_
0-based list of normals
GLfloat normalTop_ [3]
Normal to the top face.
GLfloat normalBottom_ [3]
Normal to the bottom face.
int nbPtsPerSlice_
Display resolution along slice.
int slabStep_
Display resolution along a slab (main axis)
bool closedPrism_
Is the prism closed on the top and bottom faces?
bool smoothPrism_
Is the prism smooth (with vertex normals computed)?
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
Prism3D class.
A Prism3D can be closed or open, and smooth or not smooth. A smooth prism has normal vectors attached to the vertices of the mesh, whereas a non-smooth prism has average normals attached to the faces of the mesh.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 52 of file Prism3D.h.
Constructor & Destructor Documentation
Prism3D::Prism3D (int n, GLfloat ** topFace, GLfloat ** bottomFace, bool isClosed, bool isSmooth)
Definition at line 43 of file Prism3D.cpp.
References init_().
                 :       GraphicComponent3D(),
                 vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normalF_(NULL),
                         normalV_(NULL),
                         nbPtsPerSlice_(n),
                         slabStep_(kCoarseResolution),
                         closedPrism_(isClosed),
                         smoothPrism_(isSmooth)
 {
         init_(topFace, bottomFace);
 }
Prism3D::Prism3D (int n, GLfloat ** bottomFace, GLfloat * axis, bool isClosed, bool isSmooth)
Definition at line 71 of file Prism3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), init_(), uriVL::kCoarseResolution, and setResolution().
                 :       GraphicComponent3D(),
                 vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normalF_(),
                         normalV_(),
                         nbPtsPerSlice_(n),
                         slabStep_(),
                         closedPrism_(isClosed),
                         smoothPrism_(isSmooth)
 {
         //      Allocate the (local) array of top vertices
         GLfloat** topFace = GlUtils::glfMatrix(0, n-1, 0, 2);
         for (int i=0; i<n; i++)
                 for (int k=0; k<3; k++)
                         topFace[i][k] = bottomFace[i][k] + axis[k];
         //      ---> NOW we are exactly in the same situation as with the other constructor
         //      settle for a low slab resolution initially
         setResolution(kCoarseResolution);
         init_(topFace, bottomFace);
         GlUtils::free_glfMatrix(topFace, 0, n-1, 0, 2);
 }
Prism3D::~Prism3D (void)
Destructor.
Definition at line 130 of file Prism3D.cpp.
References deleteArrays_().
 {
         deleteArrays_();
 }
Prism3D::Prism3D (const Prism3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj pointer to the object to copy
Definition at line 98 of file Prism3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                 vertex_(NULL),
                         normalF_(NULL),
                         normalV_(NULL),
                         nbPtsPerSlice_(0),
                         slabStep_(kCoarseResolution),
                         closedPrism_(false),
                         smoothPrism_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Prism3D copy constructor not implemented.");
 }
Member Function Documentation
void Prism3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 356 of file Prism3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), kVeryHighDefSlabs, nbPtsPerSlice_, normalF_, normalV_, smoothPrism_, and vertex_.
Referenced by ~Prism3D().
 {
         if (vertex_!=NULL)
         {
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         GlUtils::free_glfMatrix(vertex_[i], 0,  nbPtsPerSlice_-1, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (smoothPrism_)
         {
                 if (normalV_!=NULL)
                 {
                         for (int i=0; i<=kVeryHighDefSlabs; i++)
                                 GlUtils::free_glfMatrix(normalV_[i], 0,  nbPtsPerSlice_-1, 0, 2);
                         delete [] normalV_;
                         normalV_ = NULL;
                 }
         }
         else
         {
                 if (normalF_!=NULL)
                 {
                         GlUtils::free_glfMatrix(normalF_, 0,  nbPtsPerSlice_-1, 0, 2);
                         normalF_ = NULL;
                 }
         }
 }
void Prism3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 198 of file Prism3D.cpp.
References closedPrism_, uriVL::GraphicComponent3D::draw(), kVeryHighDefSlabs, nbPtsPerSlice_, normalBottom_, normalF_, normalTop_, normalV_, slabStep_, smoothPrism_, and vertex_.
 {
         GraphicComponent3D::draw();
         if (smoothPrism_)
         {
                 for (int i=0; i<=kVeryHighDefSlabs-slabStep_; i+=slabStep_)
                 {
                         glBegin(GL_TRIANGLE_STRIP);
                                 for (int j=0; j<nbPtsPerSlice_; j++)
{
                                         glNormal3fv(normalV_[i+slabStep_][j]);
                                         glVertex3fv(vertex_[i+slabStep_][j]);
                                         glNormal3fv(normalV_[i][j]);
                                         glVertex3fv(vertex_[i][j]);
                                 }
                                 glNormal3fv(normalV_[i+slabStep_][0]);
                                 glVertex3fv(vertex_[i+slabStep_][0]);
                                 glNormal3fv(normalV_[i][0]);
                                 glVertex3fv(vertex_[i][0]);
                         glEnd();
                 }
         }
         else
         {
                 for (int j=0; j<nbPtsPerSlice_-1; j++)
                 {
                         glNormal3fv(normalF_[j]);
                         glBegin(GL_TRIANGLE_STRIP);
                                 for (int i=0; i<=kVeryHighDefSlabs; i+=slabStep_)
{
                                         glVertex3fv(vertex_[i][j]);
                                         glVertex3fv(vertex_[i][j+1]);
                                 }
                         glEnd();
                 }
                 glBegin(GL_TRIANGLE_STRIP);
                         glNormal3fv(normalF_[nbPtsPerSlice_-1]);
                         for (int i=0; i<=kVeryHighDefSlabs; i+=slabStep_)
{
                                 glVertex3fv(vertex_[i][nbPtsPerSlice_-1]);
                                 glVertex3fv(vertex_[i][0]);
                         }
                 glEnd();
         }
         if (closedPrism_)
         {
                 glNormal3fv(normalTop_);
                 glBegin(GL_POLYGON);
                         for (int j=0; j<nbPtsPerSlice_; j++)
                                 glVertex3fv(vertex_[kVeryHighDefSlabs][j]);
                 glEnd();
                 //
                 glNormal3fv(normalBottom_);
                 glBegin(GL_POLYGON);
                         for (int j=nbPtsPerSlice_-1; j>=0; j--)
                                 glVertex3fv(vertex_[0][j]);
                 glEnd();
         }
 }
void Prism3D::init_ (GLfloat ** topFace, GLfloat ** bottomFace) private
Definition at line 284 of file Prism3D.cpp.
References closedPrism_, uriVL::GraphicComponent3D::faceAverageNormal(), FAIL_CONDITION, uriVL::GlUtils::glfMatrix(), uriVL::kOpenGLNumAllocError, kVeryHighDefSlabs, MOD, nbPtsPerSlice_, normalBottom_, normalF_, normalTop_, normalV_, smoothPrism_, vertex_, and uriVL::GraphicComponent3D::vertexAverageNormal().
Referenced by Prism3D().
 {
         //      Allocate the arrays of vertices and normal vectors
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, nbPtsPerSlice_-1, 0, 2);
         //      if we have a smooth prism, then there is one normal vector per vertex
         if (smoothPrism_)
         {
                 normalV_ = new GLfloat** [kVeryHighDefSlabs+1];
                 FAIL_CONDITION( normalV_==NULL,
                                 kOpenGLNumAllocError,
                                 "Error while allocating array of GL numbers");
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         normalV_[i] = GlUtils::glfMatrix(0, nbPtsPerSlice_-1, 0, 2);
         }
         //      if the prism is not smooth, then there is one normal vector per face.
         else
                 normalF_ = GlUtils::glfMatrix(0, nbPtsPerSlice_-1, 0, 2);
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         d[3];
         for (int j=0; j< nbPtsPerSlice_; j++)
         {
                 d[0] = dirStep*(topFace[j][0] - bottomFace[j][0]);
                 d[1] = dirStep*(topFace[j][1] - bottomFace[j][1]);
                 d[2] = dirStep*(topFace[j][2] - bottomFace[j][2]);
                 vertex_[0][j][0] = bottomFace[j][0];
                 vertex_[0][j][1] = bottomFace[j][1];
                 vertex_[0][j][2] = bottomFace[j][2];
                 for (int i=1; i<=kVeryHighDefSlabs; i++)
                 {
                         vertex_[i][j][0] = vertex_[i-1][j][0] + d[0];
                         vertex_[i][j][1] = vertex_[i-1][j][1] + d[1];
                         vertex_[i][j][2] = vertex_[i-1][j][2] + d[2];
                 }
         }
         if (smoothPrism_)
         {
                 for (int j=0; j< nbPtsPerSlice_; j++)
                         for (int i=0; i<=kVeryHighDefSlabs; i++)
                                 vertexAverageNormal(vertex_[i][j], vertex_[i][MOD(j-1, nbPtsPerSlice_)],
                                                                         vertex_[i][MOD(j+1, nbPtsPerSlice_)], d, normalV_[i][j]);
         }
         else
         {
                 for (int j=0; j< nbPtsPerSlice_; j++)
                         faceAverageNormal(vertex_[0][j], vertex_[0][MOD(j+1, nbPtsPerSlice_)],
                                                                 vertex_[kVeryHighDefSlabs][MOD(j+1, nbPtsPerSlice_)],
                                                                 vertex_[kVeryHighDefSlabs][j], normalF_[j]);
         }
         //      if this is a closed cylinder, then we must also compute the normal
         //      vector for the top and bottom faces.
         if (closedPrism_)
         {
                 faceAverageNormal(nbPtsPerSlice_, vertex_[0], normalBottom_);
                 //      don't forget that the bottom points are listed clockwise.
                 normalBottom_[0] = -normalBottom_[0];
                 normalBottom_[1] = -normalBottom_[1];
                 normalBottom_[2] = -normalBottom_[2];
                 faceAverageNormal(nbPtsPerSlice_, vertex_[kVeryHighDefSlabs], normalTop_);
         }
 }
const Prism3D & Prism3D::operator= (const Prism3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 114 of file Prism3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Prism3D copy operator not implemented.");
         return *this;
 }
void Prism3D::setResolution (ResolutionLevel res) virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 155 of file Prism3D.cpp.
References kCoarseDefSlabScale, uriVL::kCoarseResolution, kFineDefSlabScale, uriVL::kFineResolution, kMediumDefSlabScale, uriVL::kMediumResolution, uriVL::kVeryHighResolution, kVeryLowDefSlabScale, uriVL::kVeryLowResolution, and slabStep_.
Referenced by Prism3D().
 {
         switch (theRes)
         {
                 case kVeryHighResolution:
                         slabStep_ = 1;
                         break;
                 case kFineResolution:
                         slabStep_ = kFineDefSlabScale;
                         break;
                 case kMediumResolution:
                         slabStep_ = kMediumDefSlabScale;
                         break;
                 case kCoarseResolution:
                         slabStep_ = kCoarseDefSlabScale;
                         break;
                 case kVeryLowResolution:
                         slabStep_ = kVeryLowDefSlabScale;
                         break;
                 default:
                         break;
         }
 }
Member Data Documentation
bool uriVL::Prism3D::closedPrism_ private
Is the prism closed on the top and bottom faces?
Definition at line 108 of file Prism3D.h.
Referenced by draw(), and init_().
int uriVL::Prism3D::nbPtsPerSlice_ private
Display resolution along slice.
Definition at line 100 of file Prism3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::Prism3D::normalBottom_[3] private
Normal to the bottom face.
Definition at line 96 of file Prism3D.h.
Referenced by draw(), and init_().
GLfloat** uriVL::Prism3D::normalF_ private
0-based list of normals
Definition at line 84 of file Prism3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::Prism3D::normalTop_[3] private
Normal to the top face.
Definition at line 92 of file Prism3D.h.
Referenced by draw(), and init_().
GLfloat*** uriVL::Prism3D::normalV_ private
0-based list of normals
Definition at line 88 of file Prism3D.h.
Referenced by deleteArrays_(), draw(), and init_().
int uriVL::Prism3D::slabStep_ private
Display resolution along a slab (main axis)
Definition at line 104 of file Prism3D.h.
Referenced by draw(), and setResolution().
bool uriVL::Prism3D::smoothPrism_ private
Is the prism smooth (with vertex normals computed)?
Definition at line 112 of file Prism3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat*** uriVL::Prism3D::vertex_ private
0-based list of vertices
Definition at line 80 of file Prism3D.h.
Referenced by deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
Prism3D.h
Prism3D.cpp