URIVisionLibrary: uriVL::TubularSection3D Class Reference
uriVL::TubularSection3D Class Reference
TubularSection3D class.
#include <TubularSection3D.h>
Public Member Functions
TubularSection3D (GLfloat *origin, GLfloat **axes, GLfloat theta0, GLfloat thetaf)
Constructor.
TubularSection3D (GLfloat *origin, GLfloat *dirAxis, GLfloat radius, GLfloat theta0, GLfloat thetaf)
Constructor.
~TubularSection3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
TubularSection3D (const TubularSection3D &obj)
Copy constructor (disabled)
const TubularSection3D & operator= (const TubularSection3D &obj)
Copy operator: disabled.
void init_ (GLfloat *origin, GLfloat **axes, GLfloat theta0, GLfloat dTheta)
Initialize the cone.
void deleteArrays_ (void)
Delete all allocated arrays.
Private Attributes
GLfloat *** vertex_
0-based list of vertices
GLfloat ** normal_
0-based list of normals
GLfloat normalTop_ [3]
Normal to the top faced.
GLfloat normalBottom_ [3]
Normal to the bottom faced.
int circStep_
Display resolution along a circular/elliptic face.
int slabStep_
Display resolution along a slab (main axis)
GLfloat startAngle_
Start angle of the tube.
GLfloat stopAngle_
End angle of the tube.
int nbCircSegs_
Number of segments that defined a partial circle/ellipse.
TubeType tubeType_
What kind of tube we're dealing with here.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
TubularSection3D class.
A "tubular section" is a section of an elliptic cylinder defined for a range of angles.
This code is derived from the one I wrote for my personal "multiple-site" version
of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 63 of file TubularSection3D.h.
Constructor & Destructor Documentation
TubularSection3D::TubularSection3D (GLfloat * origin, GLfloat ** axes, GLfloat theta0, GLfloat thetaf)
Constructor.
Creates a tubular section from the location of its origin, the directions of the 2 axes of its elliptic bottom face, and the direction of its main axis.
Parameters
origin coordinates of the tubular section's origin (at one corner of the box)
axes the 2 axes of the tubular section's base ellipse
theta0 start angle of the tubular section
thetaf end angle of the tubular section
Definition at line 41 of file TubularSection3D.cpp.
References uriVL::ABOUT_3_QUARTER_TUBE, uriVL::ABOUT_HALF_TUBE, uriVL::ABOUT_QUARTER_CUBE, FAIL_CONDITION, init_(), uriVL::kOpenGLNumAllocError, kVeryHighDefCircPts, uriVL::LESS_THAN_QUARTER_CUBE, nbCircSegs_, uriVL::NEARLY_FULL_TUBE, PI, and tubeType_.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         startAngle_(theta0),
                         stopAngle_(thetaf),
                         nbCircSegs_(0),
                         tubeType_(FULL_TUBE)
 {
         //      First determine how much of a fraction of a tube we actually must draw
         //       Note: I only care about powers of two
         GLfloat dTheta = thetaf - theta0;
         FAIL_CONDITION( (dTheta < 0.L) || (dTheta > 2.L*PI),
                             kOpenGLNumAllocError,
                             "incorrect tubular section");
         double thetaFrac = dTheta / (2.L*PI);
         //
         //      closer to the full tube
         if ( thetaFrac > 7.L/8.L )
         {
                 nbCircSegs_ = kVeryHighDefCircPts;
                 tubeType_ = NEARLY_FULL_TUBE;
         }
         //
         //      closer to the 3/4 tube
         else if ( thetaFrac > 5.L/8.L )
         {
                 nbCircSegs_ = 3*kVeryHighDefCircPts/2;
                 tubeType_ = ABOUT_3_QUARTER_TUBE;
         }
         //
         //      closer to the 1/2 tube
         else if ( thetaFrac > 3.L/8.L )
         {
                 nbCircSegs_ = kVeryHighDefCircPts/2;
                 tubeType_ = ABOUT_HALF_TUBE;
         }
         //
         //      closer to the quarter tube
         else if ( thetaFrac > 3.L/16.L )
         {
                 nbCircSegs_ = 18;
                 tubeType_ = ABOUT_QUARTER_CUBE;
         }
         //
         else // about 1/8 tube or less
         {
                 nbCircSegs_ = kVeryHighDefCircPts/4;
                 tubeType_ = LESS_THAN_QUARTER_CUBE;
         }
         dTheta /= nbCircSegs_;
         init_(origin, axes, theta0, dTheta);
 }
TubularSection3D::TubularSection3D (GLfloat * origin, GLfloat * dirAxis, GLfloat radius, GLfloat theta0, GLfloat thetaf)
Constructor.
Creates a circular tubular section from the location of its origin, the directions of the 2 axes of its circular bottom face, and the direction of its main axis.
Parameters
origin coordinates of the tubular section's origin (at one corner of the box)
dirAxis the 2 axes of the tubular section's base ellipse
theta0 start angle of the tubular section
thetaf end angle of the tubular section
Definition at line 113 of file TubularSection3D.cpp.
References uriVL::ABOUT_3_QUARTER_TUBE, uriVL::ABOUT_HALF_TUBE, uriVL::ABOUT_QUARTER_CUBE, uriVL::GraphicComponent3D::commonNormalVector(), deleteArrays_(), FAIL_CONDITION, uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), init_(), uriVL::kInvalidParameterError, uriVL::kOpenGLNumAllocError, kVeryHighDefCircPts, uriVL::LESS_THAN_QUARTER_CUBE, nbCircSegs_, uriVL::NEARLY_FULL_TUBE, PI, and tubeType_.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         startAngle_(theta0),
                         stopAngle_(thetaf),
                         nbCircSegs_(0),
                         tubeType_(FULL_TUBE)
 {
         //      First determine how much of a fraction of a tube we actually must draw
         //       Note: I only care about powers of two
         double dTheta = thetaf - theta0;
         FAIL_CONDITION( (dTheta < 0.L) || (dTheta > 2.L*PI),
                             kOpenGLNumAllocError,
                             "incorrect tubular section");
         double thetaFrac = dTheta / (2.L*PI);
         //
         //      closer to the full tube
         if ( thetaFrac > 7.L/8.L )
         {
                 nbCircSegs_ = kVeryHighDefCircPts;
                 tubeType_ = NEARLY_FULL_TUBE;
         }
         //
         //      closer to the 3/4 tube
         else if ( thetaFrac > 5.L/8.L )
         {
                 nbCircSegs_ = 3*kVeryHighDefCircPts/2;
                 tubeType_ = ABOUT_3_QUARTER_TUBE;
         }
         //
         //      closer to the 1/2 tube
         else if ( thetaFrac > 3.L/8.L )
         {
                 nbCircSegs_ = kVeryHighDefCircPts/2;
                 tubeType_ = ABOUT_HALF_TUBE;
         }
         //
         //      closer to the quarter tube
         else if ( thetaFrac > 3.L/16.L )
         {
                 nbCircSegs_ = 18;
                 tubeType_ = ABOUT_QUARTER_CUBE;
         }
         //
         else // about 1/8 tube or less
         {
                 nbCircSegs_ = kVeryHighDefCircPts/4;
                 tubeType_ = LESS_THAN_QUARTER_CUBE;
         }
         dTheta /= nbCircSegs_;
         GLfloat**       axes = GlUtils::glfMatrix(0, 2, 0, 2);
         try
         {
                 //      dirAxis is the direction axis of the cylinder
                 axes[2][0] = dirAxis[0];
                 axes[2][1] = dirAxis[1];
                 axes[2][2] = dirAxis[2];
                 //
                 //      For the major axis, we need to build a vector orthogonal to dirAxis.
                 if ((dirAxis[0]!= 0.f) || (dirAxis[2]!= 0.f))   //      this is not the local Y axis
                 {
                         GLfloat w[3] = {0.f, 1.f, 0.f};
                         commonNormalVector(w, dirAxis, axes[0]);                //      "X" = "Y" x "Z"
                         commonNormalVector(dirAxis, axes[0], axes[1]);  //      "Y" = "Z" x "X"
                         //
                         //      and now we can multiply by the radius
                         for (int i=0; i<3; i++)
{
                                 axes[0][i] *= radius;
                                 axes[1][i] *= radius;
                         }
                 }
                 //      if dirAxis was the local Y axis, then I can take Z and X as major and minor
                 else
                 {
                         axes[0][0] = axes[0][1] = axes[1][1] = axes[1][2] = 0.f;
                         axes[0][2] = axes[1][0] = radius;
                 }
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to TubularSection3D constructor");
         }
         try
         {
                 init_(origin, axes, theta0, static_cast<GLfloat>(dTheta));
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to TubularSection3D constructor");
         }
         GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
 }
TubularSection3D::~TubularSection3D (void)
Destructor.
Definition at line 233 of file TubularSection3D.cpp.
 {
 }
uriVL::TubularSection3D::TubularSection3D (const TubularSection3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Member Function Documentation
void TubularSection3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 459 of file TubularSection3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), kVeryHighDefSlabs, nbCircSegs_, normal_, and vertex_.
Referenced by TubularSection3D().
 {
         if (vertex_!=NULL)
         {
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         GlUtils::free_glfMatrix(vertex_[i], 0,  nbCircSegs_, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (normal_!=NULL)
         {
                 GlUtils::free_glfMatrix(normal_, 0,  nbCircSegs_, 0, 2);
                 normal_ = NULL;
         }
 }
void TubularSection3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 356 of file TubularSection3D.cpp.
References circStep_, uriVL::GraphicComponent3D::draw(), kVeryHighDefSlabs, nbCircSegs_, normal_, slabStep_, and vertex_.
Referenced by uriVL::HalfCylinder3D::draw().
 {
         int     i, j;
         GraphicComponent3D::draw();
         for (i=0; i<=kVeryHighDefSlabs-slabStep_; i+=slabStep_)
         {
                 glBegin(GL_TRIANGLE_STRIP);
                         for (j=0; j<=nbCircSegs_; j+=circStep_)
{
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i+slabStep_][j]);
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i][j]);
                         }
                 glEnd();
         }
 }
void TubularSection3D::init_ (GLfloat * origin, GLfloat ** axes, GLfloat theta0, GLfloat dTheta) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
theta0 start angle of the tubular section
thetaf end angle of the tubular section
dTheta angle increment for circular/ellptic segments
Definition at line 403 of file TubularSection3D.cpp.
References uriVL::GraphicComponent3D::crossProduct(), uriVL::GlUtils::glfMatrix(), kVeryHighDefSlabs, nbCircSegs_, normal_, uriVL::GraphicComponent3D::normalizeVector(), and vertex_.
Referenced by TubularSection3D().
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         dir[kVeryHighDefSlabs+1][3],
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radial_j[3],
                         majCross[3], minCross[3];
         //      Allocate the arrays of vertices and normal vectors
         vertex_ = new GLfloat** [kVeryHighDefSlabs+1];
         normal_ = GlUtils::glfMatrix(0, nbCircSegs_, 0, 2);
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, nbCircSegs_, 0, 2);
         //      majCross = a[0] x a[2] (major axis x direction)
         crossProduct(a[0], a[2], majCross);
         //      minCross = a[1] x a[2] (minor axis x direction)
         crossProduct(a[1], a[2], minCross);
         //      First, we precompute the graduation steps for the slabs along
         //      the "direction" axis (a[2]).
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 for (int k=0; k<3; k++)
                         dir[i][k] = i*dirStep*a[2][k];
         GLfloat theta_j = theta0;
         for (int j=0; j<= nbCircSegs_; j++)
         {
                 GLfloat cos_tj = cosf(theta_j);
                 GLfloat sin_tj = sinf(theta_j);
                 radial_j[0] = cos_tj*a[0][0] + sin_tj*a[1][0];
                 normal_[j][0] = cos_tj*minCross[0] - sin_tj*majCross[0];
                 //
                 radial_j[1] = cos_tj*a[0][1] + sin_tj*a[1][1];
                 normal_[j][1] = cos_tj*minCross[1] - sin_tj*majCross[1];
                 //
                 radial_j[2] = cos_tj*a[0][2] + sin_tj*a[1][2];
                 normal_[j][2] = cos_tj*minCross[2] - sin_tj*majCross[2];
                 normalizeVector(normal_[j]);
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                 {
                         //      M = origin + cos[u] major + sin[u] minor + v direction
                         vertex_[i][j][0] = origin[0] + radial_j[0] + dir[i][0];
                         vertex_[i][j][1] = origin[1] + radial_j[1] + dir[i][1];
                         vertex_[i][j][2] = origin[2] + radial_j[2] + dir[i][2];
                 }
                 theta_j += dTheta;
         }
 }
const TubularSection3D& uriVL::TubularSection3D::operator= (const TubularSection3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
void TubularSection3D::setResolution (ResolutionLevel res) virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 257 of file TubularSection3D.cpp.
 {
         setResolution(res, res);
 }
void TubularSection3D::setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
Parameters
circRes resolution to assign along a circular/elliptic face
slabRes resolution to assign along the main axis
Definition at line 278 of file TubularSection3D.cpp.
References uriVL::ABOUT_QUARTER_CUBE, circStep_, kCoarseDefCircScale, kCoarseDefSlabScale, uriVL::kCoarseResolution, kFineDefCircScale, kFineDefSlabScale, uriVL::kFineResolution, kMediumDefCircScale, kMediumDefSlabScale, uriVL::kMediumResolution, uriVL::kVeryHighResolution, kVeryLowDefCircScale, kVeryLowDefSlabScale, uriVL::kVeryLowResolution, uriVL::LESS_THAN_QUARTER_CUBE, slabStep_, and tubeType_.
 {
         //       no coarse resolution for quarter tubes --> set to medium
         if ((tubeType_ == ABOUT_QUARTER_CUBE) && (circRes == kCoarseResolution))
                 circRes = kMediumResolution;
         //       no very low resolution for 1/8 tubes --> set to coarse
         else if ((tubeType_ == LESS_THAN_QUARTER_CUBE) && (circRes == kVeryLowResolution))
                 circRes = kCoarseResolution;
         switch (circRes)
         {
                 case kVeryHighResolution:
                         circStep_ = 1;
                         break;
                 case kFineResolution:
                         circStep_ = kFineDefCircScale;
                         break;
                 case kMediumResolution:
                         circStep_ = kMediumDefCircScale;
                         break;
                 case kCoarseResolution:
                         circStep_ = kCoarseDefCircScale;
                         break;
                 case kVeryLowResolution:
                         circStep_ = kVeryLowDefCircScale;
                         break;
                 default:
                         circStep_ = kMediumDefCircScale;
                         break;
         }
         switch (slabRes)
         {
                 case kVeryHighResolution:
                         slabStep_ = 1;
                         break;
                 case kFineResolution:
                         slabStep_ = kFineDefSlabScale;
                         break;
                 case kMediumResolution:
                         slabStep_ = kMediumDefSlabScale;
                         break;
                 case kCoarseResolution:
                         slabStep_ = kCoarseDefSlabScale;
                         break;
                 case kVeryLowResolution:
                         slabStep_ = kVeryLowDefSlabScale;
                         break;
                 default:
                         slabStep_ = kMediumDefSlabScale;
                         break;
         }
 }
Member Data Documentation
int uriVL::TubularSection3D::circStep_ private
Display resolution along a circular/elliptic face.
Definition at line 127 of file TubularSection3D.h.
Referenced by draw(), and setResolution().
int uriVL::TubularSection3D::nbCircSegs_ private
Number of segments that defined a partial circle/ellipse.
Definition at line 143 of file TubularSection3D.h.
Referenced by deleteArrays_(), draw(), init_(), and TubularSection3D().
GLfloat** uriVL::TubularSection3D::normal_ private
0-based list of normals
Definition at line 115 of file TubularSection3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::TubularSection3D::normalBottom_[3] private
Normal to the bottom faced.
Definition at line 123 of file TubularSection3D.h.
GLfloat uriVL::TubularSection3D::normalTop_[3] private
Normal to the top faced.
Definition at line 119 of file TubularSection3D.h.
int uriVL::TubularSection3D::slabStep_ private
Display resolution along a slab (main axis)
Definition at line 131 of file TubularSection3D.h.
Referenced by draw(), and setResolution().
GLfloat uriVL::TubularSection3D::startAngle_ private
Start angle of the tube.
Definition at line 135 of file TubularSection3D.h.
GLfloat uriVL::TubularSection3D::stopAngle_ private
End angle of the tube.
Definition at line 139 of file TubularSection3D.h.
TubeType uriVL::TubularSection3D::tubeType_ private
What kind of tube we're dealing with here.
Definition at line 147 of file TubularSection3D.h.
Referenced by setResolution(), and TubularSection3D().
GLfloat*** uriVL::TubularSection3D::vertex_ private
0-based list of vertices
Definition at line 111 of file TubularSection3D.h.
Referenced by deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
TubularSection3D.h
TubularSection3D.cpp