URIVisionLibrary: uriVL::PatternMatcher2D_scaledDiff Class Reference
uriVL::PatternMatcher2D_scaledDiff Class Reference
One of the simplest possible subclasses of PatternMatcher2D.
#include <PatternMatcher2D_scaledDiff.h>
Public Member Functions
PatternMatcher2D_scaledDiff (void)
Default constructor.
~PatternMatcher2D_scaledDiff (void)
Destructor.
void setPattern (const RasterImage *patImg, const Blob *patBlob=NULL)
Called to define the pattern used for subsequent covariance calculations.
void setPattern (const Pattern2D *pattern)
Called to define the pattern used for subsequent covariance calculations This function is called by the match_ function.
void setImage (const RasterImage *img)
Called to define the image used for subsequent covariance calculations.
void covariance (const RasterImage_RGBa *img, int x, int y, float *cov, float *corrScale)
Computes the correlation score between the pattern stored and an image at the location indicated.
void covariance (const RasterImage_gray *img, int x, int y, float *cov, float *corrScale)
Computes the correlation score between the pattern stored and an image at the location indicated.
void patternCorrScale (const RasterImage_RGBa *patImg, float *patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
void patternCorrScale (const RasterImage_gray *patImg, float *patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
void patternCorrScale (const RasterImage_RGBa *patImg, const Blob *patBlob, float *patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
void patternCorrScale (const RasterImage_gray *patImg, const Blob *patBlob, float *patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
Public Member Functions inherited from uriVL::PatternMatcher2D
PatternMatcher2D (void)
Default constructor.
virtual ~PatternMatcher2D (void)
Destructor.
BasePatternMatcher2DType getBaseMatcherType (void) const
If the matcher is one of the basic types, indicates which.
bool isSubpixelMatcher (void)
Indicates whether the matcher returns an integer of floating point (subpixel) best match.
virtual void setImage (const RasterImage *img, const ImagePoint *matchPoint=NULL)
Called to define the image used for subsequent covariance calculations.
Pattern2DMatchRecord * match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
Pattern2DMatchRecord * match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, std::list< Blob * > *occluder)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
void match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, Pattern2DMatchRecord *matchRecord)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
void match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, Pattern2DMatchRecord *matchRecord, std::list< Blob * > *occluder)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
Protected Member Functions
void match_ (const RasterImage_RGBa *patImg, const ImageRect *searchRect, const RasterImage_RGBa *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in an rgba image.
void match_ (const RasterImage_gray *patImg, const ImageRect *searchRect, const RasterImage_gray *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in a gray-level image.
void match_ (const RasterImage_RGBa *patImg, const Blob *patBlob, const ImageRect *searchRect, const RasterImage_RGBa *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in an rgba image.
void match_ (const RasterImage_gray *patImg, const Blob *patBlob, const ImageRect *searchRect, const RasterImage_gray *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in a gray-level image.
Protected Attributes
const Blob * patBlob_
Blob information of the pattern we are seeking.
BaseRasterType patRasterType_
Raster type of the pattern sought.
const RasterImage * patImg_
Pointer to the pattern's raster.
const RasterImage * img_
Pointer to the search image's raster.
float ** grayPat_
copy of a gray-level pattern's raster
float ** grayImg_
copy of a gray-level image region's raster
float *** rgbaPat_
copy of a color rgba pattern's raster
float *** rgbaImg_
copy of a color rgba image region's raster
float * patExp_
Expected value(s) of the pattern raster.
int patWidth_
Width of the temporary rasters currently alocated.
int patHeight_
Height of the temporary rasters currently alocated.
Protected Attributes inherited from uriVL::PatternMatcher2D
BasePatternMatcher2DType baseMatcherType_
If the matcher is one of the basic types, indicates which.
bool isSubpixelMatcher_
Indicates whether the matcher returns an integer of floating point (subpixel) best match.
const Blob * patBlob_
Blob information of the pattern we are seeking.
BaseRasterType patRasterType_
Raster type of the pattern sought.
const RasterImage * patImg_
Pointer to the pattern's raster.
const RasterImage * img_
Pointer to the search image's raster.
float ** grayPat_
copy of a gray-level pattern's raster
float ** grayImg_
copy of a gray-level image region's raster
float *** rgbaPat_
copy of a color rgba pattern's raster
float *** rgbaImg_
copy of a color rgba image region's raster
unsigned char ** patMask_
mask corresponding to the part of the pattern's bounding box to be used for matching calculations.
int patWidth_
Width of the temporary rasters currently alocated.
int patHeight_
Height of the temporary rasters currently alocated.
Private Member Functions
void covarianceRGBa_ (const unsigned char *const *rgbaImg, int x, int y, float *cov, float *corrScale)
Computes the correlation score between a rectangular pattern and an image at the location indicated.
void covarianceGray_ (const unsigned char *const *grayImg, int x, int y, float *cov, float *corrScale)
Computes the correlation score between a rectangular pattern and an image at the location indicated.
void covarianceRGBaBlob_ (const unsigned char *const *rgbaImg, int x, int y, float *cov, float *corrScale)
Computes the correlation score between a blob pattern and an image at the location indicated.
void covarianceGrayBlob_ (const unsigned char *const *grayImg, int x, int y, float *cov, float *corrScale)
Computes the correlation score between a blob pattern and an image at the location indicated.
void patternCorrScale_ (const RasterImage_RGBa *patImg, float *patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
void patternCorrScale_ (const RasterImage_gray *patImg, float *patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
void patternCorrScale_ (const RasterImage_RGBa *patImg, const Blob *patBlob, float *patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
void patternCorrScale_ (const RasterImage_gray *patImg, const Blob *patBlob, float *patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
bool isProperMatchRecordType_ (const Pattern2DMatchRecord *matchRecord) const
Checks whether the Pattern2DMatchRecord sent has the proper subtype for the matcher.
Pattern2DMatchRecord * newPattern2DMatchRecord_ (void)
Allocates a Pattern2DMatchRecord that has the proper subtype for the matcher.
void allocateRasters_ (const RasterImage *patImg, const Blob *patBlob)
Allocates private computation rasters for the pattern and the image.
void deleteRasters_ (void)
Deletes the private computation rasters.
Detailed Description
One of the simplest possible subclasses of PatternMatcher2D.
Selects the best match based on the correlation coefficient of the pattern and of the image
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 38 of file PatternMatcher2D_scaledDiff.h.
Constructor & Destructor Documentation
PatternMatcher2D_scaledDiff::PatternMatcher2D_scaledDiff (void)
Default constructor.
This constructor does not allocate temporary storage rasters.
Definition at line 27 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::PatternMatcher2D::baseMatcherType_, grayImg_, grayPat_, uriVL::PatternMatcher2D::isSubpixelMatcher_, uriVL::kUndefRasterType, patBlob_, patHeight_, uriVL::PatternMatcher2D::patMask_, patRasterType_, uriVL::PATTERN_MATCHER_2D_CORR, patWidth_, rgbaImg_, and rgbaPat_.
     :   PatternMatcher2D( )
 {
     isSubpixelMatcher_ = false;
     grayPat_ = grayImg_ = NULL;
     rgbaPat_ = rgbaImg_ = NULL;
     patBlob_ = NULL;
     patMask_ = NULL;
     patWidth_ = patHeight_ = -1;
     patRasterType_ = kUndefRasterType;
     baseMatcherType_ = PATTERN_MATCHER_2D_CORR;
 }
PatternMatcher2D_scaledDiff::~PatternMatcher2D_scaledDiff (void)
Destructor.
Does nothing
Definition at line 42 of file PatternMatcher2D_scaledDiff.cpp.
References deleteRasters_().
 {
     deleteRasters_();
 }
Member Function Documentation
void PatternMatcher2D_scaledDiff::allocateRasters_ (const RasterImage * patImg, const Blob * patBlob) private virtual
Allocates private computation rasters for the pattern and the image.
Parameters
patImg pointer to the pattern's image to allocate rasters for
patBlob pointer to the pattern's blob (possibly NULL)
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 843 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::PatternMatcher2D::allocateRasters_(), uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), uriVL::kGrayRaster, uriVL::kRGBa32Raster, patExp_, patHeight_, patRasterType_, and patWidth_.
Referenced by setPattern().
 {
     int patWidth = patImg->getWidth(),
         patHeight = patImg->getHeight();
     BaseRasterType  rasterType = patImg->getBaseRasterType();
     bool    mustReallocPatExp = (rasterType!=patRasterType_) ||
                                 (patWidth>patWidth_) ||
                                 (patHeight>patHeight_);
     PatternMatcher2D::allocateRasters_(patImg, patBlob);
     if ( mustReallocPatExp )
     {
         switch (rasterType)
         {
             case kGrayRaster:
                 patExp_ = new float[1];
                 break;
             case kRGBa32Raster:
                 patExp_ = new float[3];
                 break;
             default:
                 break;
         }
    }
 }
void PatternMatcher2D_scaledDiff::covariance (const RasterImage_RGBa * img, int x, int y, float * cov, float * corrScale)
Computes the correlation score between the pattern stored and an image at the location indicated.
Parameters
img the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 277 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceRGBa_(), covarianceRGBaBlob_(), FAIL_CONDITION, uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patBlob_.
 {
     FAIL_CONDITION(     cov == NULL,
                     kNullParameterError,
                     "NULL covariance array sent to PatternMatcher2D_scaledDiff::covariance");
     FAIL_CONDITION(     corrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::covariance");
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL raster image sent to PatternMatcher2D_scaledDiff::covariance");
     const unsigned char* const* rgbaImg = img->getShiftedRGBa2D();
     if (patBlob_==NULL)
     {
 //         ImageRect   *patRect = patImg_->getValidRect();   // unused variable -CJC
         covarianceRGBa_(rgbaImg, x, y, cov, corrScale);
     }
     else
         covarianceRGBaBlob_(rgbaImg, x, y, cov, corrScale);
 }
void PatternMatcher2D_scaledDiff::covariance (const RasterImage_gray * img, int x, int y, float * cov, float * corrScale)
Computes the correlation score between the pattern stored and an image at the location indicated.
Parameters
img the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 302 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceGray_(), covarianceGrayBlob_(), FAIL_CONDITION, uriVL::RasterImage_gray::getShiftedGray2D(), grayImg, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patBlob_.
 {
     FAIL_CONDITION(     cov == NULL,
                     kNullParameterError,
                     "NULL covariance array sent to PatternMatcher2D_scaledDiff::covariance");
     FAIL_CONDITION(     corrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::covariance");
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL raster image sent to PatternMatcher2D_scaledDiff::covariance");
     const unsigned char* const* grayImg = img->getShiftedGray2D();
     if (patBlob_==NULL)
     {
 //         ImageRect   *patRect = patImg_->getValidRect(); // unused variable -CJC
         covarianceGray_(grayImg, x, y, cov, corrScale);
     }
     else
         covarianceGrayBlob_(grayImg, x, y, cov, corrScale);
 }
void PatternMatcher2D_scaledDiff::covarianceGray_ (const unsigned char *const * grayImg, int x, int y, float * cov, float * corrScale) private
Computes the correlation score between a rectangular pattern and an image at the location indicated.
Parameters
patRows height of the pattern
patCols width of the pattern
grayImg 2D gray raster of the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 397 of file PatternMatcher2D_scaledDiff.cpp.
References grayImg_, grayPat_, patHeight_, and patWidth_.
Referenced by covariance(), and match_().
 {
     const int   nbPatPixels = patHeight_ * patWidth_;
     const float nbPixelsScale = 1.f / nbPatPixels;
     //-------------------------------------------------------------------------
     //  Part 1: Compute expected value and scaling factor for this part of the
     //          image
     //-------------------------------------------------------------------------
     float   imgSum = 0, imgSumSq = 0, imgExp;
     for (int kP=0, kI=y; kP<patHeight_; kP++, kI++)
         for (int lP=0, lI=x; lP<patWidth_; lP++, lI++)
         {
             imgSum += (grayImg_[kP][lP] = grayImg[kI][lI]);
             imgSumSq += grayImg_[kP][lP]*grayImg_[kP][lP];
         }
     imgExp = imgSum * nbPixelsScale;
     *corrScale = 1.f / sqrtf(imgSumSq*nbPixelsScale - imgExp*imgExp);
     //-------------------------------------------------------------------------
     //  Part 2: Now actually compute the covariance
     //-------------------------------------------------------------------------
     float covSum = 0.f;
     for (int kP=0; kP< patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             covSum += grayPat_[kP][lP] * (grayImg_[kP][lP] - imgExp);
     *cov = covSum * nbPixelsScale;
 }
void PatternMatcher2D_scaledDiff::covarianceGrayBlob_ (const unsigned char *const * grayImg, int x, int y, float * cov, float * corrScale) private
Computes the correlation score between a blob pattern and an image at the location indicated.
Parameters
grayImg 2D gray raster of the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 523 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::Blob::getNbPixels(), grayImg_, grayPat_, patBlob_, patHeight_, uriVL::PatternMatcher2D::patMask_, and patWidth_.
Referenced by covariance(), and match_().
 {
     const   float   nbPixelsScale = 1.f / patBlob_->getNbPixels();
     //-------------------------------------------------------------------------
     //  Part 1: Compute expected value and scaling factor for this part of the
     //          image
     //-------------------------------------------------------------------------
     float   imgSum = 0, imgSumSq = 0, imgExp;
     for (int kP=0, kI=y; kP<patHeight_; kP++, kI++)
         for (int lP=0, lI=x; lP<patWidth_; lP++, lI++)
         {
             if (patMask_[kP][lP])
             {
                 imgSum += (grayImg_[kP][lP] = grayImg[kI][lI]);
                 imgSumSq += grayImg_[kP][lP]*grayImg_[kP][lP];
             }
         }
     imgExp = imgSum * nbPixelsScale;
     *corrScale = 1.f / sqrtf(imgSumSq*nbPixelsScale - imgExp*imgExp);
     //-------------------------------------------------------------------------
     //  Part 2: Now actually compute the covariance
     //-------------------------------------------------------------------------
     float covSum = 0.f;
     for (int kP=0; kP< patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             if (patMask_[kP][lP])
                 covSum += grayPat_[kP][lP] * (grayImg_[kP][lP] - imgExp);
     *cov = covSum * nbPixelsScale;
 }
void PatternMatcher2D_scaledDiff::covarianceRGBa_ (const unsigned char *const * rgbaImg, int x, int y, float * cov, float * corrScale) private
Computes the correlation score between a rectangular pattern and an image at the location indicated.
Parameters
rgbaImg 2D RGBa raster of the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 327 of file PatternMatcher2D_scaledDiff.cpp.
References patHeight_, patWidth_, rgbaImg_, and rgbaPat_.
Referenced by covariance(), and match_().
 {
     const int   nbPatPixels = patWidth_ * patHeight_;
     const float nbPixelsScale = 1.f / nbPatPixels;
     float   imgRedSum = 0, imgRedSumSq = 0, imgRedExp;
     float   imgGreenSum = 0, imgGreenSumSq = 0, imgGreenExp;
     float   imgBlueSum = 0, imgBlueSumSq = 0, imgBlueExp;
     //-------------------------------------------------------------------------
     //  Part 1: Compute expected value and scaling factor for this part of the
     //          image
     //-------------------------------------------------------------------------
 // unused variables ... -CJC
 //     const int   kMin = y, kMax = y + patHeight_ - 1,
 //                 lMin = x, lMax = x + patWidth_ - 1;
     for (int kP=0, kI=y; kP<patHeight_; kP++, kI++)
     {
         for (int lP=0, lI=x, fourLI=4*lI; lP<patWidth_; lP++, lI++, fourLI+=2)
         {
             //  red component
             imgRedSum += (rgbaImg_[kP][lP][0] = rgbaImg[kI][fourLI]);
             imgRedSumSq += rgbaImg_[kP][lP][0]*rgbaImg_[kP][lP][0];
             //  green component
             imgGreenSum += (rgbaImg_[kP][lP][1] = rgbaImg[kI][++fourLI]);
             imgGreenSumSq += rgbaImg_[kP][lP][1]*rgbaImg_[kP][lP][1];
             //  blue component
             imgBlueSum += (rgbaImg_[kP][lP][2] = rgbaImg[kI][++fourLI]);
             imgBlueSumSq += rgbaImg_[kP][lP][2]*rgbaImg_[kP][lP][2];
         }
     }
     imgRedExp = imgRedSum * nbPixelsScale;
     corrScale[0] = 1.f / sqrtf(imgRedSumSq*nbPixelsScale - imgRedExp*imgRedExp);
     imgGreenExp = imgGreenSum * nbPixelsScale;
     corrScale[1] = 1.f / sqrtf(imgGreenSumSq*nbPixelsScale - imgGreenExp*imgGreenExp);
     imgBlueExp = imgBlueSum * nbPixelsScale;
     corrScale[2] = 1.f / sqrtf(imgBlueSumSq*nbPixelsScale - imgBlueExp*imgBlueExp);
     //-------------------------------------------------------------------------
     //  Part 2: Now actually compute the covariance
     //-------------------------------------------------------------------------
     float   covRedSum = 0, covGreenSum = 0, covBlueSum = 0;
     for (int kP=0; kP<patHeight_; kP++)
     {
         for (int lP=0; lP<patWidth_; lP++)
         {
             //  red component
             covRedSum += rgbaPat_[kP][lP][0] *
                           (rgbaImg_[kP][lP][0] - imgRedExp);
             //  green component
             covGreenSum += rgbaPat_[kP][lP][1] *
                             (rgbaImg_[kP][lP][1] - imgGreenExp);
             //  blue component
             covBlueSum += rgbaPat_[kP][lP][2] *
                            (rgbaImg_[kP][lP][2] - imgBlueExp);
         }
     }
     cov[0] = covRedSum * nbPixelsScale;
     cov[1] = covGreenSum * nbPixelsScale;
     cov[2] = covBlueSum * nbPixelsScale;
 }
void PatternMatcher2D_scaledDiff::covarianceRGBaBlob_ (const unsigned char *const * rgbaImg, int x, int y, float * cov, float * corrScale) private
Computes the correlation score between a blob pattern and an image at the location indicated.
Parameters
rgbaImg 2D RGBa raster of the image in which to search for a best match
x horizontal coordinate of where to compute a score
y vertical coordinate of where to compute a score
cov covariance of the two signals
corrScale scaling factor for the image region. The covariance should be mutiplied by this number and by the scaling factor for the pattern returned by patternCorrScale
Definition at line 428 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::Blob::getNbPixels(), patBlob_, patHeight_, uriVL::PatternMatcher2D::patMask_, patWidth_, rgbaImg_, and rgbaPat_.
Referenced by covariance(), and match_().
 {
     const   float   nbPixelsScale = 1.f / patBlob_->getNbPixels();
     float   imgRedSum = 0, imgRedSumSq = 0, imgRedExp;
     float   imgGreenSum = 0, imgGreenSumSq = 0, imgGreenExp;
     float   imgBlueSum = 0, imgBlueSumSq = 0, imgBlueExp;
     //-------------------------------------------------------------------------
     //  Part 1: Compute expected value and scaling factor for this part of the
     //          image
     //-------------------------------------------------------------------------
 // unused variables... -CJC
 //     const int   kMin = y, kMax = y + patHeight_ - 1,
 //                 lMin = x, lMax = x + patWidth_ - 1;
     for (int kP=0, kI=y; kP<patHeight_; kP++, kI++)
     {
         for (int lP=0, lI=x, fourLI=4*lI; lP<patWidth_; lP++, lI++)
         {
                 if (patMask_[kP][lP])
                 {
                     //  red component
                     imgRedSum += (rgbaImg_[kP][lP][0] = rgbaImg[kI][fourLI]);
                     imgRedSumSq += rgbaImg_[kP][lP][0]*rgbaImg_[kP][lP][0];
                     //  green component
                     imgGreenSum += (rgbaImg_[kP][lP][1] = rgbaImg[kI][++fourLI]);
                     imgGreenSumSq += rgbaImg_[kP][lP][1]*rgbaImg_[kP][lP][1];
                     //  blue component
                     imgBlueSum += (rgbaImg_[kP][lP][2] = rgbaImg[kI][++fourLI]);
                     imgBlueSumSq += rgbaImg_[kP][lP][2]*rgbaImg_[kP][lP][2];
                     fourLI+=2;
             }
             else
                 fourLI+=4;
         }
     }
     imgRedExp = imgRedSum * nbPixelsScale;
     corrScale[0] = 1.f / sqrtf(imgRedSumSq*nbPixelsScale - imgRedExp*imgRedExp);
     imgGreenExp = imgGreenSum * nbPixelsScale;
     corrScale[1] = 1.f / sqrtf(imgGreenSumSq*nbPixelsScale - imgGreenExp*imgGreenExp);
     imgBlueExp = imgBlueSum * nbPixelsScale;
     corrScale[2] = 1.f / sqrtf(imgBlueSumSq*nbPixelsScale - imgBlueExp*imgBlueExp);
 /*
 float   patRedTerm = 0,
         patGreenTerm = 0,
         patBlueTerm = 0,
         imgRedTerm = 0,
         imgGreenTerm = 0,
         imgBlueTerm = 0;
 */
     //-------------------------------------------------------------------------
     //  Part 2: Now actually compute the covariance
     //-------------------------------------------------------------------------
     float   covRedSum = 0, covGreenSum = 0, covBlueSum = 0;
     for (int kP=0; kP<patHeight_; kP++)
     {
         for (int lP=0; lP<patWidth_; lP++)
         {
             if (patMask_[kP][lP])
             {
 /*
 patRedTerm += rgbaPat_[kP][lP][0];
 patGreenTerm += rgbaPat_[kP][lP][1];
 patBlueTerm += rgbaPat_[kP][lP][2];
 imgRedTerm += (rgbaImg_[kP][lP][0] - imgRedExp);
 imgGreenTerm += (rgbaImg_[kP][lP][1] - imgGreenExp);
 imgBlueTerm += (rgbaImg_[kP][lP][2] - imgBlueExp);
 */
                 //  red component
                 covRedSum += rgbaPat_[kP][lP][0] *
                               (rgbaImg_[kP][lP][0] - imgRedExp);
                 //  green component
                 covGreenSum += rgbaPat_[kP][lP][1] *
                                 (rgbaImg_[kP][lP][1] - imgGreenExp);
                 //  blue component
                 covBlueSum += rgbaPat_[kP][lP][2] *
                                (rgbaImg_[kP][lP][2] - imgBlueExp);
             }
         }
     }
 //float xxx = patRedTerm + patGreenTerm + patBlueTerm + imgRedTerm + imgGreenTerm + imgBlueTerm;
     cov[0] = covRedSum * nbPixelsScale;
     cov[1] = covGreenSum * nbPixelsScale;
     cov[2] = covBlueSum * nbPixelsScale;
 }
void PatternMatcher2D_scaledDiff::deleteRasters_ (void) private virtual
Deletes the private computation rasters.
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 835 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::PatternMatcher2D::deleteRasters_(), and patExp_.
Referenced by ~PatternMatcher2D_scaledDiff().
 {
     PatternMatcher2D::deleteRasters_();
     if (patExp_ != NULL)
         delete []patExp_;
 }
bool PatternMatcher2D_scaledDiff::isProperMatchRecordType_ (const Pattern2DMatchRecord * matchRecord) const private virtual
Checks whether the Pattern2DMatchRecord sent has the proper subtype for the matcher.
Parameters
matchRecord Pattern2DMatchRecord to check
Implements uriVL::PatternMatcher2D.
Definition at line 822 of file PatternMatcher2D_scaledDiff.cpp.
 {
     //  the correlation matcher only requires a generic match record
     return true;
 }
void PatternMatcher2D_scaledDiff::match_ (const RasterImage_RGBa * patImg, const ImageRect * searchRect, const RasterImage_RGBa * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in an rgba image.
The correlation computed is the average of that of the three color components. The search region is specified by an image rectangle. The pattern is a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangular image pattern to search for in img.
searchRect the region of the search
img the image in which to search for a best match
matchRecord Pattern2DMatchRecord of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 87 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceRGBa_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::ImageRect::getTop(), patternCorrScale_(), uriVL::Pattern2DMatchRecord::setBestMatch(), and uriVL::Pattern2DMatchRecord::setScore().
 {
     const float ONE_THIRD = 1.f / 3.f;
     const int   iLow = searchRect->getTop(),
                 iHigh = searchRect->getBottom(),
                 jLow = searchRect->getLeft(),
                 jHigh = searchRect->getRight();
     const unsigned char* const* rgbaImg = img->getShiftedRGBa2D();
     float   patCorrScale[3] = {0, 0, 0};
     float   cov[3] = {0, 0, 0},
             corrScale[3] = {0, 0, 0},
             corr,
             bestScore = -2;
     int     bestI=-1, bestJ=-1;
     //  Compute the pattern's correlation scale factor
     patternCorrScale_(patImg, patCorrScale);
     //  For each possible location of the upper-left corner of the pattern
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
             //  compute the variance and scaling factor
             covarianceRGBa_(rgbaImg, j, i, cov, corrScale);
             //  Compute the actual correlation value and compare it to best so far
             corr = ONE_THIRD * (cov[0] * corrScale[0] * patCorrScale[0] +
                                 cov[1] * corrScale[1] * patCorrScale[1] +
                                 cov[2] * corrScale[2] * patCorrScale[2]);
             if (corr > bestScore)
             {
                 bestScore = corr;
                 bestI = i;
                 bestJ = j;
             }
         }
     //  At the end of the loop, we report the best correlation score and its location.
     //  Note that the "best" is not necessarily good.
     matchRecord->setScore(bestScore);
     matchRecord->setBestMatch(bestJ, bestI);
 }
void PatternMatcher2D_scaledDiff::match_ (const RasterImage_gray * patImg, const ImageRect * searchRect, const RasterImage_gray * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in a gray-level image.
The search region is specified by an image rectangle. The pattern is a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangular image pattern to search for in img.
searchRect the region of the search
img the image in which to search for a best match
matchRecord Pattern2DMatchRecord of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 134 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceGray_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), grayImg, patternCorrScale_(), uriVL::Pattern2DMatchRecord::setBestMatch(), and uriVL::Pattern2DMatchRecord::setScore().
 {
     const int   iLow = searchRect->getTop(),
                 iHigh = searchRect->getBottom(),
                 jLow = searchRect->getLeft(),
                 jHigh = searchRect->getRight();
     const unsigned char* const* grayImg = img->getShiftedGray2D();
     //  Compute the pattern's correlation scale factor
     float       patCorrScale = 0;
     patternCorrScale_(patImg, &patCorrScale);
     float   cov = 0, corr, corrScale = 0, bestScore = -2;
     int     bestI=-1, bestJ=-1;
     //  For each possible location of the upper-left corner of the pattern
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             //  compute the variance and scaling factor
             covarianceGray_(grayImg, j, i, &cov, &corrScale);
             //  Compute the actual correlation value and compare it to best so far
             corr = cov * corrScale * patCorrScale;
             if (corr > bestScore)
             {
                 bestScore = corr;
                 bestI = i;
                 bestJ = j;
             }
         }
     }
     //  At the end of the loop, we report the best correlation score and its location.
     //  Note that the "best" is not necessarily good.
     matchRecord->setScore(bestScore);
     matchRecord->setBestMatch(bestJ, bestI);
 }
void PatternMatcher2D_scaledDiff::match_ (const RasterImage_RGBa * patImg, const Blob * patBlob, const ImageRect * searchRect, const RasterImage_RGBa * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in an rgba image.
The correlation computed is the average of that of the three color components. The search region is specified by an image rectangle. The pattern is a blob defined over a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangular image pattern to search for in img.
patBlob the blob that defines the actual geometry of the pattern
searchRect the region of the search
img the image in which to search for a best match
matchRecord Pattern2DMatchRecord of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 178 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceRGBaBlob_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::ImageRect::getTop(), patternCorrScale_(), uriVL::Pattern2DMatchRecord::setBestMatch(), and uriVL::Pattern2DMatchRecord::setScore().
 {
     const   float   ONE_THIRD = 1.f / 3.f;
     const int   iLow = searchRect->getTop(),
                 iHigh = searchRect->getBottom(),
                 jLow = searchRect->getLeft(),
                 jHigh = searchRect->getRight();
     const unsigned char* const* rgbaImg = img->getShiftedRGBa2D();
     float   patCorrScale[3] = {0, 0, 0},
             cov[3] = {0, 0, 0},
             corrScale[3] = {0, 0, 0},
             corr,
             bestScore = -2;
     int     bestI=-1, bestJ=-1;
     //  Compute the pattern's correlation scale factor
     patternCorrScale_(patImg, patBlob, patCorrScale);
     //  For each possible location of the upper-left corner of the pattern
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             //  compute the variance and scaling factor
             covarianceRGBaBlob_(rgbaImg, j, i, cov, corrScale);
             //  Compute the actual correlation value and compare it to best so far
             corr = ONE_THIRD * (cov[0] * corrScale[0] * patCorrScale[0] +
                                 cov[1] * corrScale[1] * patCorrScale[1] +
                                 cov[2] * corrScale[2] * patCorrScale[2]);
             if (corr > bestScore)
             {
                 bestScore = corr;
                 bestI = i;
                 bestJ = j;
             }
         }
     }
     //  At the end of the loop, we report the best correlation score and its location.
     //  Note that the "best" is not necessarily good.
     matchRecord->setScore(bestScore);
     matchRecord->setBestMatch(bestJ, bestI);
 }
void PatternMatcher2D_scaledDiff::match_ (const RasterImage_gray * patImg, const Blob * patBlob, const ImageRect * searchRect, const RasterImage_gray * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in a gray-level image.
The search region is specified by an image rectangle. The pattern is a blob defined over a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangular image pattern to search for in img.
patBlob the blob that defines the actual geometry of the pattern
searchRect the region of the search
img the image in which to search for a best match
matchRecord Pattern2DMatchRecord of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 226 of file PatternMatcher2D_scaledDiff.cpp.
References covarianceGrayBlob_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), grayImg, patternCorrScale_(), uriVL::Pattern2DMatchRecord::setBestMatch(), and uriVL::Pattern2DMatchRecord::setScore().
 {
     const int   iLow = searchRect->getTop(),
                 iHigh = searchRect->getBottom(),
                 jLow = searchRect->getLeft(),
                 jHigh = searchRect->getRight();
     const unsigned char* const* grayImg = img->getShiftedGray2D();
     float   patCorrScale = 0.f,
             corr = 0.f,
             corrScale = 0.f,
             cov = 0.f,
             bestScore = -2;
     int     bestI=-1, bestJ=-1;
     //  Compute the pattern's correlation scale factor
     patternCorrScale_(patImg, patBlob, &patCorrScale);
     //  For each possible location of the upper-left corner of the pattern
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             //  compute the variance and scaling factor
             covarianceGrayBlob_(grayImg, j, i, &cov, &corrScale);
             //  Compute the actual correlation value and compare it to best so far
             corr = cov * corrScale * patCorrScale;
             if (corr > bestScore)
             {
                 bestScore = corr;
                 bestI = i;
                 bestJ = j;
             }
         }
     }
     //  At the end of the loop, we report the best correlation score and its location.
     //  Note that the "best" is not necessarily good.
     matchRecord->setScore(bestScore);
     matchRecord->setBestMatch(bestJ, bestI);
 }
Pattern2DMatchRecord * PatternMatcher2D_scaledDiff::newPattern2DMatchRecord_ (void) private virtual
Allocates a Pattern2DMatchRecord that has the proper subtype for the matcher.
Returns
a match recordthat has the proper subtype for the matcher
Implements uriVL::PatternMatcher2D.
Definition at line 828 of file PatternMatcher2D_scaledDiff.cpp.
 {
     //  the correlaton matcher only requires a generic match record
     return new Pattern2DMatchRecord();
 }
void PatternMatcher2D_scaledDiff::patternCorrScale (const RasterImage_RGBa * patImg, float * patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
The expected values are kept stored in this object and will be used to compute the variance. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the rectangular image pattern to compute the scale factor for.
patCorrScale the correlation scaling factors for the pattern
Definition at line 562 of file PatternMatcher2D_scaledDiff.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patternCorrScale_().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL pattern passed as parameter to PatternMatcher2D_scaledDiff::patternCorrScale");
     FAIL_CONDITION(     patCorrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::patternCorrScale");
     patternCorrScale_(patImg, patCorrScale);
 }
void PatternMatcher2D_scaledDiff::patternCorrScale (const RasterImage_gray * patImg, float * patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
The expected value is kept stored in this object and will be used to compute the variance. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the rectangular image pattern to compute the scale factor for.
patCorrScale the correlation scaling factor for the pattern
Definition at line 574 of file PatternMatcher2D_scaledDiff.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patternCorrScale_().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL pattern passed as parameter to PatternMatcher2D_scaledDiff::patternCorrScale");
     FAIL_CONDITION(     patCorrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::patternCorrScale");
     patternCorrScale_(patImg, patCorrScale);
 }
void PatternMatcher2D_scaledDiff::patternCorrScale (const RasterImage_RGBa * patImg, const Blob * patBlob, float * patCorrScale)
Computes the correlation scaling factor and expected color intensity values for the pattern.
The expected values are kept stored in this object and will be used to compute the variance. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the blob image pattern to compute the scale factor for.
patBlob the blob that defines the actual geometry of the pattern
patCorrScale the correlation scaling factors for the pattern
Definition at line 586 of file PatternMatcher2D_scaledDiff.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patternCorrScale_().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL pattern passed as parameter to PatternMatcher2D_scaledDiff::patternCorrScale");
     FAIL_CONDITION(     patCorrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::patternCorrScale");
     if (patBlob == NULL)
         patternCorrScale_(patImg, patCorrScale);
     else
         patternCorrScale_(patImg, patBlob, patCorrScale);
 }
void PatternMatcher2D_scaledDiff::patternCorrScale (const RasterImage_gray * patImg, const Blob * patBlob, float * patCorrScale)
Computes the correlation scaling factor and expected gray intensity value for the pattern.
The expected value is kept stored in this object and will be used to compute the variance. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the blob image pattern to compute the scale factor for.
patBlob the blob that defines the actual geometry of the pattern
patCorrScale the correlation scaling factor for the pattern
Definition at line 603 of file PatternMatcher2D_scaledDiff.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and patternCorrScale_().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL pattern passed as parameter to PatternMatcher2D_scaledDiff::patternCorrScale");
     FAIL_CONDITION(     patCorrScale == NULL,
                     kNullParameterError,
                     "NULL correlation scale array sent to PatternMatcher2D_scaledDiff::patternCorrScale");
     if (patBlob == NULL)
         patternCorrScale_(patImg, patCorrScale);
     else
         patternCorrScale_(patImg, patBlob, patCorrScale);
 }
void PatternMatcher2D_scaledDiff::patternCorrScale_ (const RasterImage_RGBa * patImg, float * patCorrScale) private
Computes the correlation scaling factor and expected color intensity values for the pattern.
The expected values are to be used by the covariance computation function. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the rectangular image pattern to compute the scale factor for.
patCorrScale the correlation scaling factors for the pattern
Definition at line 621 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::RasterImage_RGBa::getRGBa2D(), patExp_, patHeight_, patWidth_, rgbaPat_, and setPattern().
Referenced by match_(), and patternCorrScale().
 {
     setPattern(patImg);
     const unsigned char* const* rgbaPat = patImg->getRGBa2D();
     const int   nbPatPixels = patWidth_ * patHeight_;
     const float nbPixelsScale = 1.f / nbPatPixels;
     //  Calculate normalizing factor for the pattern.  I know that we are off by a factor
     //  of 1/sqrt(nbPixels).   I correct that when I multiply the two scaling factors
     float   patRedSum = 0, patRedSumSq = 0;
     float   patGreenSum = 0, patGreenSumSq = 0;
     float   patBlueSum = 0, patBlueSumSq = 0;
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0, fourLP=0; lP<patWidth_; lP++, fourLP+=2)
         {
             //  red component
             patRedSum += rgbaPat[kP][fourLP];
             patRedSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
             //  green component
             patGreenSum += rgbaPat[kP][++fourLP];
             patGreenSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
             //  blue component
             patBlueSum += rgbaPat[kP][++fourLP];
             patBlueSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
         }
     patExp_[0] = patRedSum * nbPixelsScale;
     patCorrScale[0] = 1.f / sqrtf(patRedSumSq*nbPixelsScale - patExp_[0]*patExp_[0]);
     patExp_[1] = patGreenSum * nbPixelsScale;
     patCorrScale[1] = 1.f / sqrtf(patGreenSumSq*nbPixelsScale - patExp_[1]*patExp_[1]);
     patExp_[2] = patBlueSum * nbPixelsScale;
     patCorrScale[2] = 1.f / sqrtf(patBlueSumSq*nbPixelsScale - patExp_[2]*patExp_[2]);
     //  copy pattern data shifted by mean value
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0, fourLP=0; lP<patWidth_; lP++, fourLP++)
         {
             rgbaPat_[kP][lP][0] = rgbaPat[kP][fourLP++] - patExp_[0];
             rgbaPat_[kP][lP][1] = rgbaPat[kP][fourLP++] - patExp_[1];
             rgbaPat_[kP][lP][2] = rgbaPat[kP][fourLP++] - patExp_[2];
         }
 }
void PatternMatcher2D_scaledDiff::patternCorrScale_ (const RasterImage_gray * patImg, float * patCorrScale) private
Computes the correlation scaling factor and expected gray intensity value for the pattern.
The expected value is to be used by the covariance computation function. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the rectangular image pattern to compute the scale factor for.
patCorrScale the correlation scaling factor for the pattern
Definition at line 666 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::RasterImage_gray::getGray2D(), grayPat_, patExp_, patHeight_, patWidth_, and setPattern().
 {
     setPattern(patImg);
     const unsigned char* const* grayPat = patImg->getGray2D();
     const int   nbPatPixels = patWidth_ * patHeight_;
     const float nbPixelsScale = 1.f / nbPatPixels;
     //  Calculate normalizing factor for the pattern.
     float   patSum = 0, patSumSq = 0;
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
         {
             patSum += grayPat[kP][lP];
             patSumSq += grayPat[kP][lP]*grayPat[kP][lP];
         }
     patExp_[0] = patSum * nbPixelsScale;
     *patCorrScale = 1.f / sqrtf(patSumSq*nbPixelsScale - patExp_[0]*patExp_[0]);
     //  copy pattern data shifted by mean value
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             grayPat_[kP][lP] = grayPat[kP][lP] - patExp_[0];
 }
void PatternMatcher2D_scaledDiff::patternCorrScale_ (const RasterImage_RGBa * patImg, const Blob * patBlob, float * patCorrScale) private
Computes the correlation scaling factor and expected color intensity values for the pattern.
The expected values are to be used by the covariance computation function. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the blob image pattern to compute the scale factor for.
patBlob the blob that defines the actual geometry of the pattern
patCorrScale the correlation scaling factors for the pattern
Definition at line 693 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::Blob::getNbPixels(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::Blob::getSegDeque(), uriVL::HorizontalSegment::leftX, patExp_, patHeight_, uriVL::PatternMatcher2D::patMask_, patWidth_, rgbaPat_, setPattern(), and uriVL::HorizontalSegment::y.
 {
     setPattern(patImg, patBlob);
     const unsigned char* const* rgbaPat = patImg->getRGBa2D();
     const int   nbPatPixels = patBlob->getNbPixels();
     const float nbPixelsScale = 1.f / nbPatPixels;
     //  First, reset the pattern mask
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             patMask_[kP][lP] = (unsigned char) 0;
         //      Then go through the deque-list structure
     const LineSegDeque segDeque = patBlob->getSegDeque();
     HorizontalSegment   *theSeg;
     float   patRedSum = 0, patRedSumSq = 0;
     float   patGreenSum = 0, patGreenSumSq = 0;
     float   patBlueSum = 0, patBlueSumSq = 0;
     //  Calculate normalizing factor for the pattern.
     LineSegDeque::const_iterator lastLine = segDeque.end();
     for (LineSegDeque::const_iterator lineIter = segDeque.begin(); lineIter != lastLine; lineIter++)
     {
         list<HorizontalSegment*>::const_iterator lastSeg = (*lineIter)->end();
         for (list<HorizontalSegment*>::const_iterator segIter = (*lineIter)->begin(); segIter != lastSeg; segIter++)
         {
             theSeg = (*segIter);
             int kP = theSeg->y;
             for (int lP = theSeg->leftX, fourLP=4*lP; lP<=theSeg->rightX; lP++, fourLP+=2)
             {
                 //  red component
                 patRedSum += rgbaPat[kP][fourLP];
                 patRedSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
                 //  green component
                 patGreenSum += rgbaPat[kP][++fourLP];
                 patGreenSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
                 //  blue component
                 patBlueSum += rgbaPat[kP][++fourLP];
                 patBlueSumSq += rgbaPat[kP][fourLP]*rgbaPat[kP][fourLP];
                 patMask_[kP][lP] = (unsigned char) 1;
             }
         }
     }
     patExp_[0] = patRedSum * nbPixelsScale;
     patCorrScale[0] = 1.f / sqrtf(patRedSumSq*nbPixelsScale - patExp_[0]*patExp_[0]);
     patExp_[1] = patGreenSum * nbPixelsScale;
     patCorrScale[1] = 1.f / sqrtf(patGreenSumSq*nbPixelsScale - patExp_[1]*patExp_[1]);
     patExp_[2] = patBlueSum * nbPixelsScale;
     patCorrScale[2] = 1.f / sqrtf(patBlueSumSq*nbPixelsScale - patExp_[2]*patExp_[2]);
 float sumRed = 0;
 //cout << "patCorrScale  ";
     //  copy pattern data shifted by mean value.  I think it is probably faster to
     //  apply the shift over the entire bounding rectangle than to check the mask
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0, fourLP=0; lP<patWidth_; lP++, fourLP++)
         {
             rgbaPat_[kP][lP][0] = rgbaPat[kP][fourLP++] - patExp_[0];
             rgbaPat_[kP][lP][1] = rgbaPat[kP][fourLP++] - patExp_[1];
             rgbaPat_[kP][lP][2] = rgbaPat[kP][fourLP++] - patExp_[2];
             if (patMask_[kP][lP]) {
                 sumRed += rgbaPat_[kP][lP][0];
 //                cout << rgbaPat_[kP][lP][0] << " ";
             }
         }
 //    cout << endl << "sumRed = " << sumRed << endl;
 }
void PatternMatcher2D_scaledDiff::patternCorrScale_ (const RasterImage_gray * patImg, const Blob * patBlob, float * patCorrScale) private
Computes the correlation scaling factor and expected gray intensity value for the pattern.
The expected value is to be used by the covariance computation function. The scale factor should be used to multiply the result of the covariance if the correlation coefficient is desired.
Parameters
patImg the blob image pattern to compute the scale factor for.
patBlob the blob that defines the actual geometry of the pattern
patCorrScale the correlation scaling factor for the pattern
Definition at line 768 of file PatternMatcher2D_scaledDiff.cpp.
References uriVL::RasterImage_gray::getGray2D(), uriVL::Blob::getNbPixels(), uriVL::Blob::getSegDeque(), grayPat_, uriVL::HorizontalSegment::leftX, patExp_, patHeight_, uriVL::PatternMatcher2D::patMask_, patWidth_, setPattern(), and uriVL::HorizontalSegment::y.
 {
     setPattern(patImg, patBlob);
     const unsigned char* const* grayPat = patImg->getGray2D();
     const int   nbPatPixels = patBlob->getNbPixels();
     const float nbPixelsScale = 1.f / nbPatPixels;
     //  First, reset the pattern mask
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             patMask_[kP][lP] = (unsigned char) 0;
         //      Then go through the deque-list structure
     const LineSegDeque segDeque = patBlob->getSegDeque();
     HorizontalSegment   *theSeg;
     float   patSum = 0.f, patSumSq = 0.f;
     //  Calculate normalizing factor for the pattern.  I know that we are off by a factor
     //  of 1/sqrt(nbPixels).   I correct that when I multiply the two scaling factors
     LineSegDeque::const_iterator lastLine = segDeque.end();
     for (LineSegDeque::const_iterator lineIter = segDeque.begin(); lineIter != lastLine; lineIter++)
     {
         list<HorizontalSegment*>::iterator  segIter, lastSeg = (*lineIter)->end();
         for (segIter = (*lineIter)->begin(); segIter != lastSeg; segIter++)
         {
             theSeg = (*segIter);
             int kP = theSeg->y;
             for (int lP = theSeg->leftX; lP<=theSeg->rightX; lP++)
             {
                 patSum += grayPat[kP][lP];
                 patSumSq += grayPat[kP][lP]*grayPat[kP][lP];
                 patMask_[kP][lP] = (unsigned char) 1;
             }
         }
     }
     patExp_[0] = patSum * nbPixelsScale;
     *patCorrScale = 1.f / sqrtf(patSumSq*nbPixelsScale - patExp_[0]*patExp_[0]);
     //  copy pattern data shifted by mean value.  I think it is probably faster to
     //  apply the shift over the entire bounding rectangle than to check the mask
     for (int kP=0; kP<patHeight_; kP++)
         for (int lP=0; lP<patWidth_; lP++)
             grayPat_[kP][lP] = grayPat[kP][lP] - patExp_[0];
 }
void uriVL::PatternMatcher2D_scaledDiff::setImage (const RasterImage * img)
Called to define the image used for subsequent covariance calculations.
Currently, the image's base raster type should match that of the pattern (which implies that the pattern should have been set before this function is called)
Parameters
img the image in which we seek a best match for the pattern
See also
setPattern
void PatternMatcher2D_scaledDiff::setPattern (const RasterImage * patImg, const Blob * patBlob = NULL) virtual
Called to define the pattern used for subsequent covariance calculations.
This function is called by the match_ function. It (and setImage) should be called prior to a call to covariance(). Currently only RGBa and gray-level patterns are accepted.
Parameters
patImg the rectangular pattern we are seaking
patBlob the blob that defines the actual geometry of the pattern
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 59 of file PatternMatcher2D_scaledDiff.cpp.
References allocateRasters_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, patBlob_, and patImg_.
Referenced by patternCorrScale_(), and setPattern().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL image sent as parameter to PatternMatcher2D_scaledDiff::setPattern");
     BaseRasterType patRasterType = patImg->getBaseRasterType();
     FAIL_CONDITION(     (patRasterType != kGrayRaster) && (patRasterType != kRGBa32Raster),
                     kInvalidParameterError,
                     "PatternMatcher2D_scaledDiff::setPattern only takes gray and RGBa images");
     //  if needed, allocate new temporary storage raster for the pattern and image
     allocateRasters_(patImg, patBlob);
     patBlob_ = patBlob;
     patImg_ = patImg;
 }
void PatternMatcher2D_scaledDiff::setPattern (const Pattern2D * pattern) virtual
Called to define the pattern used for subsequent covariance calculations This function is called by the match_ function.
It (and setImage) should be called prior to a call to covariance(). Currently only RGBa and gray-level patterns are accepted.
Parameters
pattern the pattern we are seaking
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 51 of file PatternMatcher2D_scaledDiff.cpp.
References FAIL_CONDITION, uriVL::Pattern2D::getBlob(), uriVL::Pattern2D::getPattern(), uriVL::kNullParameterError, and setPattern().
 {
     FAIL_CONDITION(     pat == NULL,
                     kNullParameterError,
                     "NULL pattern sent as parameter to PatternMatcher2D_scaledDiff::setPattern");
     setPattern(pat->getPattern(), pat->getBlob());
 }
Member Data Documentation
float** uriVL::PatternMatcher2D_scaledDiff::grayImg_ protected
copy of a gray-level image region's raster
Definition at line 180 of file PatternMatcher2D_scaledDiff.h.
Referenced by covarianceGray_(), covarianceGrayBlob_(), and PatternMatcher2D_scaledDiff().
float** uriVL::PatternMatcher2D_scaledDiff::grayPat_ protected
copy of a gray-level pattern's raster
Definition at line 176 of file PatternMatcher2D_scaledDiff.h.
Referenced by covarianceGray_(), covarianceGrayBlob_(), patternCorrScale_(), and PatternMatcher2D_scaledDiff().
const RasterImage* uriVL::PatternMatcher2D_scaledDiff::img_ protected
Pointer to the search image's raster.
Definition at line 172 of file PatternMatcher2D_scaledDiff.h.
const Blob* uriVL::PatternMatcher2D_scaledDiff::patBlob_ protected
Blob information of the pattern we are seeking.
Definition at line 160 of file PatternMatcher2D_scaledDiff.h.
Referenced by covariance(), covarianceGrayBlob_(), covarianceRGBaBlob_(), PatternMatcher2D_scaledDiff(), and setPattern().
float* uriVL::PatternMatcher2D_scaledDiff::patExp_ protected
Expected value(s) of the pattern raster.
If the pattern has a gray-level image, the array sotres asingle element
Definition at line 193 of file PatternMatcher2D_scaledDiff.h.
Referenced by allocateRasters_(), deleteRasters_(), and patternCorrScale_().
int uriVL::PatternMatcher2D_scaledDiff::patHeight_ protected
Height of the temporary rasters currently alocated.
Definition at line 201 of file PatternMatcher2D_scaledDiff.h.
Referenced by allocateRasters_(), covarianceGray_(), covarianceGrayBlob_(), covarianceRGBa_(), covarianceRGBaBlob_(), patternCorrScale_(), and PatternMatcher2D_scaledDiff().
const RasterImage* uriVL::PatternMatcher2D_scaledDiff::patImg_ protected
Pointer to the pattern's raster.
Definition at line 168 of file PatternMatcher2D_scaledDiff.h.
Referenced by setPattern().
BaseRasterType uriVL::PatternMatcher2D_scaledDiff::patRasterType_ protected
Raster type of the pattern sought.
Definition at line 164 of file PatternMatcher2D_scaledDiff.h.
Referenced by allocateRasters_(), and PatternMatcher2D_scaledDiff().
int uriVL::PatternMatcher2D_scaledDiff::patWidth_ protected
Width of the temporary rasters currently alocated.
Definition at line 197 of file PatternMatcher2D_scaledDiff.h.
Referenced by allocateRasters_(), covarianceGray_(), covarianceGrayBlob_(), covarianceRGBa_(), covarianceRGBaBlob_(), patternCorrScale_(), and PatternMatcher2D_scaledDiff().
float*** uriVL::PatternMatcher2D_scaledDiff::rgbaImg_ protected
copy of a color rgba image region's raster
Definition at line 188 of file PatternMatcher2D_scaledDiff.h.
Referenced by covarianceRGBa_(), covarianceRGBaBlob_(), and PatternMatcher2D_scaledDiff().
float*** uriVL::PatternMatcher2D_scaledDiff::rgbaPat_ protected
copy of a color rgba pattern's raster
Definition at line 184 of file PatternMatcher2D_scaledDiff.h.
Referenced by covarianceRGBa_(), covarianceRGBaBlob_(), patternCorrScale_(), and PatternMatcher2D_scaledDiff().
The documentation for this class was generated from the following files:
PatternMatcher2D_scaledDiff.h
PatternMatcher2D_scaledDiff.cpp