URIVisionLibrary: uriVL::RandomGenerator Class Reference
uriVL::RandomGenerator Class Reference abstract
Pure virtual parent class for pseudorandom number generators.
#include <RandomGenerator.h>
Public Member Functions
virtual ~RandomGenerator (void)
Destructor.
virtual unsigned int nextUInt (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
virtual int nextInt (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
virtual unsigned long nextULong (void)=0
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
virtual long nextLong (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
virtual float nextFloat (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
virtual float nextFloat (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
virtual double nextDouble (void)=0
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
virtual double nextDouble (double lowVal, double highVal)=0
Returns a new uniformly distributed double pseudo-random number in the range specified.
virtual double nextGaussian (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
virtual void setSeed (long theSeed)=0
Sets a new seed for this generator.
Protected Member Functions
RandomGenerator (void)
Creates a new RandomGenerator object.
Static Protected Attributes
static const bool INT_IS_LONG = (sizeof(int) == sizeof(long))
Indicates whether an int has the same length as a long (should be true non most platforms.
Detailed Description
Pure virtual parent class for pseudorandom number generators.
The API for this class is largely inspired from that of the Random class of Java.
This class class was initially created just as a way to simply create random matrices and vectors to test the classes of uriVL. Then I decided to implement several different algorithms (basically just embedding into my classes public domain or other open-source code posted online by people who know alo more about random generators.
If you are really concerned about performance of the random generator, then you should probably use directly the original code rather than the wrapper classes of this hierarchy.
Author
jean-yves herve', 3D Group for Interactive Visualization, Dept. of Computer Science and Statistics, University of Rhode Island.
Definition at line 39 of file RandomGenerator.h.
Constructor & Destructor Documentation
RandomGenerator::~RandomGenerator (void) virtual
Destructor.
Definition at line 32 of file RandomGenerator.cpp.
 { }
RandomGenerator::RandomGenerator (void) protected
Creates a new RandomGenerator object.
Definition at line 29 of file RandomGenerator.cpp.
 { }
Member Function Documentation
virtual double uriVL::RandomGenerator::nextDouble (void) pure virtual
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Implemented in uriVL::RandomGenerator_R250_R521, uriVL::RandomGenerator_C, uriVL::RandomGenerator_MT, and uriVL::RandomGenerator_Knuth.
Referenced by nextFloat(), nextInt(), and nextLong().
virtual double uriVL::RandomGenerator::nextDouble (double lowVal, double highVal) pure virtual
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Implemented in uriVL::RandomGenerator_R250_R521, uriVL::RandomGenerator_C, and uriVL::RandomGenerator_MT.
float RandomGenerator::nextFloat (void) virtual
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
Returns
new float pseudo-random value in the range [0, 1[
Definition at line 54 of file RandomGenerator.cpp.
References nextDouble().
Referenced by uriVL::RandomGenerator_MT::nextFloat_st(), uriVL::RandomGenerator_C::nextFloat_st(), and uriVL::RandomGenerator_R250_R521::nextFloat_st().
 {
     return static_cast<long>(nextDouble());
 }
float RandomGenerator::nextFloat (float lowVal, float highVal) virtual
Returns a new uniformly-distributed float pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new float pseudo-random value in thhe range [lowVal, highVal[
Definition at line 59 of file RandomGenerator.cpp.
References nextDouble().
 {
     return static_cast<float>(nextDouble() * (highVal - lowVal)) + lowVal;
 }
double RandomGenerator::nextGaussian (double sigma = 1.L) virtual
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Parameters
sigma standard deviation of the distribution
Returns
new normally-distributed double pseudo-random value in the range [0, 1[
Definition at line 64 of file RandomGenerator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by uriVL::RandomGenerator_MT::nextGaussian_st(), uriVL::RandomGenerator_C::nextGaussian_st(), and uriVL::RandomGenerator_R250_R521::nextGaussian_st().
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
     return 0.L;
 }
int RandomGenerator::nextInt (int lowVal, int highVal) virtual
Returns a new uniformly-distributed int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 44 of file RandomGenerator.cpp.
References nextDouble().
Referenced by uriVL::RandomGenerator_MT::nextInt_st(), uriVL::RandomGenerator_C::nextInt_st(), and uriVL::RandomGenerator_R250_R521::nextInt_st().
 {
     return static_cast<int>(nextDouble() * (highVal - lowVal + 1)) + lowVal;
 }
long RandomGenerator::nextLong (long lowVal, long highVal) virtual
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 49 of file RandomGenerator.cpp.
References nextDouble().
Referenced by uriVL::RandomGenerator_MT::nextLong_st(), uriVL::RandomGenerator_C::nextLong_st(), and uriVL::RandomGenerator_R250_R521::nextLong_st().
 {
     return static_cast<long>(nextDouble() * (highVal - lowVal + 1)) + lowVal;
 }
unsigned int RandomGenerator::nextUInt (void) virtual
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned int pseudo-random value
Definition at line 35 of file RandomGenerator.cpp.
References INT_IS_LONG, and nextULong().
Referenced by uriVL::RandomGenerator_MT::nextUInt_st(), uriVL::RandomGenerator_C::nextUInt_st(), and uriVL::RandomGenerator_R250_R521::nextUInt_st().
 {
     if (INT_IS_LONG)
         return  static_cast<unsigned int>(nextULong());
     else
         //  otherwise return most significant part of the unsigned long
         return static_cast<unsigned int>(nextULong() >> 16);
 }
virtual unsigned long uriVL::RandomGenerator::nextULong (void) pure virtual
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Implemented in uriVL::RandomGenerator_R250_R521, uriVL::RandomGenerator_C, uriVL::RandomGenerator_MT, and uriVL::RandomGenerator_Knuth.
Referenced by nextUInt().
virtual void uriVL::RandomGenerator::setSeed (long theSeed) pure virtual
Sets a new seed for this generator.
Parameters
theSeed new theSeed value for this generator
Implemented in uriVL::RandomGenerator_R250_R521, uriVL::RandomGenerator_C, uriVL::RandomGenerator_MT, and uriVL::RandomGenerator_Knuth.
Member Data Documentation
const bool RandomGenerator::INT_IS_LONG = (sizeof(int) == sizeof(long)) static protected
Indicates whether an int has the same length as a long (should be true non most platforms.
Definition at line 119 of file RandomGenerator.h.
Referenced by nextUInt(), uriVL::RandomGenerator_C::setSeed(), and uriVL::RandomGenerator_R250_R521::setSeed().
The documentation for this class was generated from the following files:
RandomGenerator.h
RandomGenerator.cpp