URIVisionLibrary: uriVL::ImageReader Class Reference
uriVL::ImageReader Class Reference
ImageReader objects read a raster image from an image file specified either by its file path or FSSpec descriptor, or selected via a dialog window.
#include <ImageReader.h>
Public Member Functions
ImageReader (void)
Default constructor.
ImageReader (const char *filePath)
Constructor that initializes the source for image input using a file's path.
~ImageReader (void)
Destructor.
void setSource (void)
Select the input image file via a dialog window.
void setSource (const char *fileName)
Select the input image file using a file path.
RasterImage * getFrame (void)
Get an image frame from the preselected source.
RasterImage * getFrame (bool upsideDown=false)
Get an image frame from the preselected source.
void getFrame (RasterImage *img)
Get an image frame from the preselected source.
void getFrame (RasterImage *img, bool upsideDown=false)
Get an image frame from the preselected source.
Public Member Functions inherited from uriVL::VideoSource
VideoSource (void)
Default constructor.
virtual ~VideoSource (void)
Destructor (frees the video source)
int getWidth (void)
Returns the preselected movie's width (-1 if no movie was selected)
int getHeight (void)
Returns the preselected movie's height (-1 if no movie was selected)
Static Public Member Functions
static RasterImage * readImage (bool upsideDown=false)
Read an image frame from a source file selected through a dialog window.
static RasterImage * readImage (const char *filePath, bool upsideDown=false)
Read an image frame from the designated source file.
Private Member Functions
ImageReader (const ImageReader &reader)
Copy constructor.
const ImageReader & operator= (const ImageReader &reader)
Copy operator.
Additional Inherited Members
Static Protected Member Functions inherited from uriVL::VideoSource
static void updateImageRasterStatus_ (RasterImage *img)
This function is a bit of a hack.
Detailed Description
ImageReader objects read a raster image from an image file specified either by its file path or FSSpec descriptor, or selected via a dialog window.
Currently handles only the following image formats:
PPM [both ASCII and binary]
PGM [both ASCII and binary]
tga (Targa) [Both 24 and 8 bit formats, but has problems with comments in images]
My plan is still to scrap most of this code to use the QuickTime importers when possible.
Origins of this code: The PPM code is mine. The TGA code is not. I lifted it from my student Claude Duchesne's augmented reality project [GRPR, EPM, 1999-2002]. I have seen minor variations of that code in many programs that I have downloaded, but I do not know who was the original author.
Versions:
01/10/2003 basic code for reading PPM/tga files
02/10/2003 cleanup and bug fixes
Definition at line 88 of file ImageReader.h.
Constructor & Destructor Documentation
ImageReader::ImageReader (void)
Default constructor.
Definition at line 36 of file ImageReader.cpp.
         : VideoSource( ),
         //
         reader_(NULL)
 {
     #if URIVL_USE_QUICKTIME
         reader_ = new _ImageReader_QT( );
          #elif URIVL_USE_FREEIMAGE
                 reader_ = new _ImageReader_FreeImage( );
          #elif  URIVL_USE_HACK_RW
                 reader_ = new _ImageReader_hack( );
     #else
                 #error No reader defined in ImageReader::ImageReader(void)
     #endif
 }
ImageReader::ImageReader (const char * filePath)
Constructor that initializes the source for image input using a file's path.
Parameters
filePath path of the input image file
Definition at line 52 of file ImageReader.cpp.
         : VideoSource( ),
         //
         reader_(NULL)
 {
          #if URIVL_USE_QUICKTIME
         reader_ = new _ImageReader_QT(theFilePath);
          #elif URIVL_USE_FREEIMAGE
                 reader_ = new _ImageReader_FreeImage(theFilePath);
          #elif  URIVL_USE_HACK_RW
                 reader_ = new _ImageReader_hack(theFilePath);
     #else
                 #error No reader defined in ImageReader::ImageReader(const char* theFilePath)
     #endif
 }
ImageReader::~ImageReader (void)
Destructor.
Definition at line 79 of file ImageReader.cpp.
 {
         if (reader_ != NULL)
         {
                 delete reader_;
         }
 }
ImageReader::ImageReader (const ImageReader & reader) private
Copy constructor.
not implemented
Parameters
img image to copy
Definition at line 69 of file ImageReader.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         : VideoSource( ),
         //
         reader_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Copy constructor not implemented in ImageReader class");
 }
Member Function Documentation
RasterImage * ImageReader::getFrame (void) virtual
Get an image frame from the preselected source.
Parameters
upsideDown is true if the image should be read upside down
Returns
RasterImage object containing the image read
Implements uriVL::VideoSource.
Definition at line 184 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage().
Referenced by createRasterImageObj(), getFrame(), initImagesAndWarper(), loadImage(), loadImages(), and myIdle().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 imgOut = getFrame(false);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::getFrame");
                 throw e;
         }
         return imgOut;
 }
RasterImage * ImageReader::getFrame (bool upsideDown = false)
Get an image frame from the preselected source.
Parameters
upsideDown is true if the image should be read upside down
Returns
RasterImage object containing the image read
Definition at line 202 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kNoCode, and uriVL::VideoSource::updateImageRasterStatus_().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 imgOut = reader_->getFrame_(readUpsideDown);
                 updateImageRasterStatus_(imgOut);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::readImage");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kNoCode,
                                                 "Unexpected error encountered in ImageReader::readImage");
         }
         return imgOut;
 }
void ImageReader::getFrame (RasterImage * img) virtual
Get an image frame from the preselected source.
Parameters
img RasterImage object into which the image should be read
Implements uriVL::VideoSource.
Definition at line 227 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage(), and getFrame().
 {
         try
         {
                 getFrame(imgOut, false);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::getFrame");
                 throw e;
         }
 }
void ImageReader::getFrame (RasterImage * img, bool upsideDown = false)
Get an image frame from the preselected source.
Parameters
img RasterImage object into which the image should be read
upsideDown is true if the image should be read upside down
Definition at line 241 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kNoCode, uriVL::kNullRasterImageError, and uriVL::VideoSource::updateImageRasterStatus_().
 {
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "Nuul image passed as destination to an ImageReader");
         try
         {
                 reader_->getFrame_(imgOut, readUpsideDown);
                 updateImageRasterStatus_(imgOut);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::getFrame");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kNoCode,
                                                 "Unexpected error encountered in ImageReader::getFrame");
         }
 }
const ImageReader & ImageReader::operator= (const ImageReader & reader) private
Copy operator.
not implemented
Parameters
img image to copy
Definition at line 91 of file ImageReader.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
{
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Copy operator not implemented in ImageReader class");
         return *this;
 }
RasterImage * ImageReader::readImage (bool upsideDown = false) static
Read an image frame from a source file selected through a dialog window.
Parameters
upsideDown is true if the image should be read upside down
Returns
RasterImage object containing the image read
Definition at line 117 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kNoCode, and uriVL::VideoSource::updateImageRasterStatus_().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 #if URIVL_USE_QUICKTIME
                         imgOut = _ImageReader_QT::readImage_(readUpsideDown);
                 #elif URIVL_USE_FREEIMAGE
                         imgOut = _ImageReader_FreeImage::readImage_(readUpsideDown);
                 #elif  URIVL_USE_HACK_RW
                         imgOut = _ImageReader_hack::readImage_(readUpsideDown);
                 #else
                         #error No reader defined in ImageReader::ImageReader(const char* theFilePath)
                 #endif
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::readImage");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kNoCode,
                                                 "Unexpected error encountered in ImageReader::readImage");
         }
         updateImageRasterStatus_(imgOut);
         return imgOut;
 }
RasterImage * ImageReader::readImage (const char * filePath, bool upsideDown = false) static
Read an image frame from the designated source file.
Parameters
filePath path of the input image file
upsideDown is true if the image should be read upside down
Returns
RasterImage object containing the image read
Definition at line 151 of file ImageReader.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kFileIOError, and uriVL::VideoSource::updateImageRasterStatus_().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 #if URIVL_USE_QUICKTIME
                         imgOut = _ImageReader_QT::readImage_(thePath, readUpsideDown);
                 #elif URIVL_USE_FREEIMAGE
                         imgOut = _ImageReader_FreeImage::readImage_(thePath, readUpsideDown);
                 #elif  URIVL_USE_HACK_RW
                         imgOut = _ImageReader_hack::readImage_(thePath, readUpsideDown);
                 #else
                         //      we should not make it there
                         #error No reader defined in ImageReader::readImage(const char* thePath, bool readUpsideDown)
                 #endif
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageReader::readImage");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kFileIOError,
                                                 "Unexpected error encountered in ImageReader::readImage");
         }
         updateImageRasterStatus_(imgOut);
         return imgOut;
 }
void ImageReader::setSource (void) virtual
Select the input image file via a dialog window.
Implements uriVL::VideoSource.
Definition at line 101 of file ImageReader.cpp.
Referenced by loadImage(), and loadImages().
 {
     reader_->setSource_();
 }
void ImageReader::setSource (const char * fileName)
Select the input image file using a file path.
Parameters
fileName path of the input image file
Definition at line 107 of file ImageReader.cpp.
 {
     reader_->setSource_(thePath);
 }
The documentation for this class was generated from the following files:
ImageReader.h
ImageReader.cpp