URIVisionLibrary: uriVL::ColorMedianFilter_I Class Reference
uriVL::ColorMedianFilter_I Class Reference
ColorMedianFilter class.
#include <ColorMedianFilter_I.h>
Public Member Functions
ColorMedianFilter_I (int theWidth)
Defines a median filter with a specified width.
ColorMedianFilter_I (int theHeight, int theWidth)
Defines a median filter with a specified width and height.
ColorMedianFilter_I (const ImageRect *theRect)
Defines a median filter with a dimensions rectangle.
~ColorMedianFilter_I (void)
Destructor.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::ColorMedianFilter
~ColorMedianFilter (void)
Destructor.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ColorMedianFilter_I (const ColorMedianFilter_I &obj)
Copy constructor (disabled)
const ColorMedianFilter_I & operator= (const ColorMedianFilter_I &obj)
Copy operator: disabled.
Protected Member Functions inherited from uriVL::ColorMedianFilter
ColorMedianFilter (void)
Defines a median filter without a specified width and height.
ColorMedianFilter (int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Defines a median filter with a specified width and height.
ColorMedianFilter (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Defines a median filter with a dimensions rectangle.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Protected Attributes
unsigned char * redData_
Local storage for red median computation.
unsigned char * greenData_
Local storage for green median computation.
unsigned char * blueData_
Local storage for blue median computation.
Detailed Description
ColorMedianFilter class.
This class has not been implemented yet
A median filter is an image operator that replaces the value at each pixel by the median value of a rectangular window centered at that pixel
Definition at line 32 of file ColorMedianFilter_I.h.
Constructor & Destructor Documentation
ColorMedianFilter_I::ColorMedianFilter_I (int theWidth)
Defines a median filter with a specified width.
The filter will be centered at the pixel where it is applied.
Parameters
theWidth desired width of the median filter
Definition at line 45 of file ColorMedianFilter_I.cpp.
                         :       ColorMedianFilter(theWidth, theWidth, true),
                                 //
                                 redData_(new unsigned char[theWidth*theWidth]),
                                 greenData_(new unsigned char[theWidth*theWidth]),
                                 blueData_(new unsigned char[theWidth*theWidth])
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorMedianFilter_I constructor");
         throw e;
 }
ColorMedianFilter_I::ColorMedianFilter_I (int theHeight, int theWidth)
Defines a median filter with a specified width and height.
The filter will be centered at the pixel where it is applied.
Parameters
theWidth desired width of the median filter
theHeight desired width of the median filter
Definition at line 58 of file ColorMedianFilter_I.cpp.
                         :       ColorMedianFilter(theWidth, theHeight, true),
                                 //
                                 redData_(new unsigned char[theWidth*theHeight]),
                                 greenData_(new unsigned char[theWidth*theHeight]),
                                 blueData_(new unsigned char[theWidth*theHeight])
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorMedianFilter_I constructor");
         throw e;
 }
ColorMedianFilter_I::ColorMedianFilter_I (const ImageRect * theRect)
Defines a median filter with a dimensions rectangle.
It is up to the user to make sure that the dimensions of the filter make sense (the "left" and "top" values should be negative, opposite of "right" and bottom")
Parameters
theRect desired dimensions of the median filter
Definition at line 71 of file ColorMedianFilter_I.cpp.
                         :       ColorMedianFilter(theRect, false, kPositiveFloat),
                                 //
                                 redData_(new unsigned char[theRect->getWidth() * theRect->getHeight()]),
                                 greenData_(new unsigned char[theRect->getWidth() * theRect->getHeight()]),
                                 blueData_(new unsigned char[theRect->getWidth() * theRect->getHeight()])
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorMedianFilter_I constructor");
         throw e;
 }
ColorMedianFilter_I::~ColorMedianFilter_I (void)
Destructor.
Definition at line 98 of file ColorMedianFilter_I.cpp.
References blueData_, greenData_, and redData_.
 {
     delete []redData_;
     delete []greenData_;
     delete []blueData_;
 }
ColorMedianFilter_I::ColorMedianFilter_I (const ColorMedianFilter_I & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 85 of file ColorMedianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ColorMedianFilter(),
                                 //
                                 redData_(NULL),
                                 greenData_(NULL),
                                 blueData_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorMedianFilter_I copy constructor not implemented.");
 }
Member Function Documentation
void ColorMedianFilter_I::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 207 of file ColorMedianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo(), and myMenu3().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void ColorMedianFilter_I::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 216 of file ColorMedianFilter_I.cpp.
References blueData_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), getColorMedian_(), uriVL::ImageRect::getLeft(), uriVL::ImageOperator::getRect(), uriVL::ImageRect::getRight(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), greenData_, uriVL::ImageRect::intersection(), uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGBa32Raster, uriVL::RasterImage_RGBa::localRasterRGBa(), MAX, MIN, uriVL::R_W_ACCESS, redData_, uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
         //----------------------------------------------------------------
         //      STEP 0:         Test for null or invalid type parameters
         //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     FAIL_CONDITION(     imgOut == NULL,
                                 kNullRasterImageError,
                                 "NULL output raster image passed as parameter");
     //  so far I only accept a RasterImage_RGBa as a destination
         FAIL_CONDITION( imgOut->getBaseRasterType() != kRGBa32Raster,
                         kInvalidRasterType,
                         "GaussianFilter_F::applyInto only accepts RasterImage_RGBa images as destination");
         //----------------------------------------------------------------
         //      STEP 1:         Test for rectangle intersection
         //----------------------------------------------------------------
         //  determine the output rectangle that the input image can produce.
         //              Here, it is the entire valid data rectangle.
     const ImageRect   *outRect = imgIn->getValidRect();
         //      ... and determine its intersection with the user-specified output rectangle
         ImageRect       *destRect = ImageRect::intersection(theRect, outRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!outRect->contains(destRect))
         imgOut->setBoundRect(destRect);
         //----------------------------------------------------------------
         //      STEP 2:         Get an RGBa input image
         //----------------------------------------------------------------
     bool    localRGBa = false;
     const RasterImage_RGBa* rgbaImg = RasterImage_RGBa::localRasterRGBa(imgIn, &localRGBa);
         //----------------------------------------------------------------
         //      STEP 3:         Perform the calculations
         //----------------------------------------------------------------
     const int   iLow = destRect->getTop(),
                 iHigh = destRect->getBottom(),
                 jLow = destRect->getLeft(),
                 jHigh = destRect->getRight();
         const ImageRect* operRect = getRect();
     const int   recTop = operRect->getTop(),
                 recBottom = operRect->getBottom(),
                 recLeft = operRect->getLeft(),
                 recRight = operRect->getRight();
     const unsigned char* const* rgbaIn = rgbaImg->getShiftedRGBa2D();
     unsigned char* const* rgbaOut = (static_cast<RasterImage_RGBa*>(imgOut))->getShiftedRGBa2D(R_W_ACCESS);
     for (int i=iLow; i<= iHigh; i++)
     {
         const int kLow = MAX(i+recTop, iLow);
         const int kHigh = MIN(i+recBottom, iHigh);
         int fourj = 4*jLow;
         for (int j=jLow; j<=jHigh; j++)
         {
             //  collect the data around the pixel.
             const int lLow = MAX(j+recLeft, jLow);
             const int lHigh = MIN(j+recRight, jHigh);
             const int fourlMin = 4*lLow;
             int  n = 0;
             for (int k=kLow; k<=kHigh; k++)
             {
                 int fourl = fourlMin;
                 for (int l=lLow; l<=lHigh; l++)
                 {
                     redData_[n] = rgbaIn[k][fourl++];
                     greenData_[n] = rgbaIn[k][fourl++];
                     blueData_[n++] = rgbaIn[k][fourl++];
                     fourl++;
                 }
             }
             rgbaOut[i][fourj++] = getColorMedian_(redData_, n);
             rgbaOut[i][fourj++] = getColorMedian_(greenData_, n);
             rgbaOut[i][fourj++] = getColorMedian_(blueData_, n);
             rgbaOut[i][fourj++] = static_cast<unsigned char>(255);
         }
     }
         //      Very important:  At the end of the computation, don't forget to set the
         //      output's valid data rectangle.  In "safe" mode, the library has no way to guess
         //      what the valid data rectangle should be and sets it to its minimum value... empty
         imgOut->setValidRect(outRect);
     //  cleanup
     if (localRGBa)
         delete rgbaImg;
 }
RasterImage * ColorMedianFilter_I::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 124 of file ColorMedianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to ColorMedianFilter_I::applyTo");
         return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * ColorMedianFilter_I::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 134 of file ColorMedianFilter_I.cpp.
References uriVL::ErrorReport::appendToMessage(), applyInto(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getBoundRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kImageProcessingError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ColorMedianFilter_F::applyTo");
         RasterImage     *imgOut = NULL;
         try {
                 if (imgIn->hasFloatRaster())
                 {
                         switch (imgIn->getBaseRasterType())
{
                                 case kGrayRaster:
                                         imgOut = new RasterImage_gray_F(imgIn->getBoundRect());
                                         break;
                                 case kRGBa32Raster:
                                         imgOut = new RasterImage_RGBa_F(imgIn->getBoundRect());
                                         break;
                                 default:
                                         FAIL_CONDITION( true,
                                                                         kFunctionNotImplemented,
                                                                         "image type not suported by Gaussian filter yet");
                                         break;
                         }
                 }
                 else
                 {
                         switch (imgIn->getBaseRasterType())
{
                                 case kGrayRaster:
                                         imgOut = new RasterImage_gray(imgIn->getBoundRect());
                                         break;
                                 case kRGB24Raster:
                                         imgOut = new RasterImage_RGB(imgIn->getBoundRect());
                                         break;
                                 case kRGBa32Raster:
                                         imgOut = new RasterImage_RGBa(imgIn->getBoundRect());
                                         break;
                                 default:
                                         FAIL_CONDITION( true,
                                                                         kFunctionNotImplemented,
                                                                         "image type not suported by Gaussian filter yet");
                                         break;
                         }
                 }
                 applyInto(imgIn, theRect, imgOut);
     }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by ColorMedianFilter_I::applyTo");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kImageProcessingError,
                                                 "Error in the computation of ColorMedianFilter_I::applyTo");
         }
         return imgOut;
 }
const ColorMedianFilter_I & ColorMedianFilter_I::operator= (const ColorMedianFilter_I & obj) protected
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 106 of file ColorMedianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorMedianFilter_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
unsigned char* uriVL::ColorMedianFilter_I::blueData_ protected
Local storage for blue median computation.
Definition at line 119 of file ColorMedianFilter_I.h.
Referenced by applyInto(), and ~ColorMedianFilter_I().
unsigned char* uriVL::ColorMedianFilter_I::greenData_ protected
Local storage for green median computation.
Definition at line 115 of file ColorMedianFilter_I.h.
Referenced by applyInto(), and ~ColorMedianFilter_I().
unsigned char* uriVL::ColorMedianFilter_I::redData_ protected
Local storage for red median computation.
Definition at line 111 of file ColorMedianFilter_I.h.
Referenced by applyInto(), and ~ColorMedianFilter_I().
The documentation for this class was generated from the following files:
ColorMedianFilter_I.h
ColorMedianFilter_I.cpp