URIVisionLibrary: uriVL::VideoSource Class Reference
uriVL::VideoSource Class Reference abstract
VideoSource pure virtual parent class.
#include <VideoSource.h>
Public Member Functions
VideoSource (void)
Default constructor.
virtual ~VideoSource (void)
Destructor (frees the video source)
virtual void setSource (void)=0
Select the video source via a dialog window.
virtual RasterImage * getFrame (void)=0
Get an image frame from the selected input.
virtual void getFrame (RasterImage *img)=0
Get an image frame from the selected input.
int getWidth (void)
Returns the preselected movie's width (-1 if no movie was selected)
int getHeight (void)
Returns the preselected movie's height (-1 if no movie was selected)
Static Protected Member Functions
static void updateImageRasterStatus_ (RasterImage *img)
This function is a bit of a hack.
Detailed Description
VideoSource pure virtual parent class.
All sources of images (live CCTV camera, FireWire camera, analog frame grabber, movie file, image file, folder of image files or image stack) are implemented as subclasses of this class, and provide therefore the same basic interface.
Definition at line 50 of file VideoSource.h.
Constructor & Destructor Documentation
VideoSource::VideoSource (void)
Default constructor.
Definition at line 26 of file VideoSource.cpp.
 {
 }
VideoSource::~VideoSource (void) virtual
Destructor (frees the video source)
Definition at line 30 of file VideoSource.cpp.
 {
 }
Member Function Documentation
virtual RasterImage* uriVL::VideoSource::getFrame (void) pure virtual
Get an image frame from the selected input.
Returns
RasterImage object containing the image read
Implemented in uriVL::ImageReader, and uriVL::SequenceGrabber.
Referenced by myIdle().
virtual void uriVL::VideoSource::getFrame (RasterImage * img) pure virtual
Get an image frame from the selected input.
Parameters
img RasterImage object into which the frame should be read
Implemented in uriVL::ImageReader, and uriVL::SequenceGrabber.
int uriVL::VideoSource::getHeight (void)
Returns the preselected movie's height (-1 if no movie was selected)
Returns
the preselected movie's height (-1 if no movie was selected)
int uriVL::VideoSource::getWidth (void)
Returns the preselected movie's width (-1 if no movie was selected)
Returns
the preselected movie's width (-1 if no movie was selected)
virtual void uriVL::VideoSource::setSource (void) pure virtual
Select the video source via a dialog window.
Implemented in uriVL::ImageReader, and uriVL::SequenceGrabber.
void VideoSource::updateImageRasterStatus_ (RasterImage * img) static protected
This function is a bit of a hack.
One problem with subclasses of RasterImage that have redundant storage (e.g. RasterImage_HSV) is that we must make sure that we keep track of which raster stores the reference. This function should be called by any subclass of VideoSource. It ensures that the raster that got read into is marked as reference and modified.
Parameters
img the RasterImage object whose status needs updating
Definition at line 34 of file VideoSource.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::RasterImage::hasFloatRaster(), uriVL::kBinaryRaster, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), and uriVL::RasterImage::setReferenceHasChanged_().
Referenced by uriVL::ImageReader::getFrame(), and uriVL::ImageReader::readImage().
 {
 //wlcfixme this was done as a part of FreeImage reader and writer addition
 #if URIVL_USE_FREEIMAGE // new way that lets a float raster be reference if it exists
         if (img->hasFloatRaster())
         {
                 img->setFloatRasterAsReference_();
         }
         else
         {
                 int nRasterType = img->getBaseRasterType( );
                 // DO NOT set gworld as reference for binary
                 if (nRasterType != kBinaryRaster)
                 {
                         img->setGraphWorldAsReference_();
                 }
         }
         img->setReferenceHasChanged_(true);
 #else // original way that forces graph world raster to be reference
         img->setGraphWorldAsReference_();
         img->setReferenceHasChanged_(true);
 #endif
 }
The documentation for this class was generated from the following files:
VideoSource.h
VideoSource.cpp