URIVisionLibrary: uriVL::RandomGenerator_R250_R521 Class Reference
uriVL::RandomGenerator_R250_R521 Class Reference
Random number generator class that uses the combined R250-R521 algorithm implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
#include <RandomGenerator_R250_521.h>
Public Member Functions
RandomGenerator_R250_R521 (void)
Constructor.
RandomGenerator_R250_R521 (long theSeed)
Creates a new RandomGenerator object seeded with the value received as parameter.
~RandomGenerator_R250_R521 (void)
Destructor.
unsigned long nextULong (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
double nextDouble (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
double nextDouble (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
void setSeed (long theSeed)
Sets a new seed for this generator.
Public Member Functions inherited from uriVL::RandomGenerator
virtual ~RandomGenerator (void)
Destructor.
virtual unsigned int nextUInt (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
virtual int nextInt (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
virtual long nextLong (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
virtual float nextFloat (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
virtual float nextFloat (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
virtual double nextGaussian (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Static Public Member Functions
static unsigned int nextUInt_st (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
static int nextInt_st (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
static unsigned long nextULong_st (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
static long nextLong_st (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
static float nextFloat_st (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
static float nextFloat_st (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
static double nextDouble_st (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
static double nextDouble_st (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
static double nextGaussian_st (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
static void setSeed_st (long theSeed)
Sets a new seed for this generator.
Static Public Attributes
static const int FULL_IN_ULONG = ((8*sizeof(unsigned long)) / MAX_BITS_IN_RAND)
number of full outputs of the C generator fitting in a long
static const int RES_TO_ULONG
number of residual bits of a output of the C generator to dd to make a long
static const int FULL_IN_UINT = ((8*sizeof(unsigned int)) / MAX_BITS_IN_RAND)
number of full outputs of the C generator fitting in an int
static const int RES_TO_UINT
number of residual bits of a output of the C generator to dd to make an int
Private Attributes
int r250_index_
index of the R250 algorrithm
int r521_index_
index of the R521 algorrithm
unsigned long r250_buffer_ [R250_LEN]
buffer of the R250 algorrithm
unsigned long r521_buffer_ [R521_LEN]
buffer of the R521 algorrithm
Static Private Attributes
static RandomGenerator_R250_R521 * rg_ = new RandomGenerator_R250_R521()
The unique object of this class, stored as a static member.
Additional Inherited Members
Protected Member Functions inherited from uriVL::RandomGenerator
RandomGenerator (void)
Creates a new RandomGenerator object.
Static Protected Attributes inherited from uriVL::RandomGenerator
static const bool INT_IS_LONG = (sizeof(int) == sizeof(long))
Indicates whether an int has the same length as a long (should be true non most platforms.
Detailed Description
Random number generator class that uses the combined R250-R521 algorithm implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
I have tried as much as possible to preserve the original code and comments. The main change is the implementation of setSeed.
Definition at line 35 of file RandomGenerator_R250_521.h.
Constructor & Destructor Documentation
RandomGenerator_R250_R521::RandomGenerator_R250_R521 (void)
Constructor.
Definition at line 52 of file RandomGenerator_R250_521.cpp.
References setSeed().
     :   RandomGenerator(),
                 //
                 r250_index_(0),
                 r521_index_(0)
 {
     setSeed(time(NULL));
 }
uriVL::RandomGenerator_R250_R521::RandomGenerator_R250_R521 (long theSeed)
Creates a new RandomGenerator object seeded with the value received as parameter.
Parameters
theSeed new seed value for this generator
RandomGenerator_R250_R521::~RandomGenerator_R250_R521 (void)
Destructor.
Definition at line 62 of file RandomGenerator_R250_521.cpp.
 {
 }
Member Function Documentation
double RandomGenerator_R250_R521::nextDouble (double lowVal, double highVal) virtual
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Implements uriVL::RandomGenerator.
Definition at line 161 of file RandomGenerator_R250_521.cpp.
References INV_MAX_ULONG, and nextULong().
Referenced by nextDouble_st().
 {
     return INV_MAX_ULONG * nextULong() * (highVal - lowVal) + lowVal;
 }
double RandomGenerator_R250_R521::nextDouble (void) virtual
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Implements uriVL::RandomGenerator.
Definition at line 167 of file RandomGenerator_R250_521.cpp.
References INV_MAX_ULONG, and nextULong().
 {
     return INV_MAX_ULONG * static_cast<double>(nextULong());
 }
double RandomGenerator_R250_R521::nextDouble_st (void) static
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Definition at line 211 of file RandomGenerator_R250_521.cpp.
References nextDouble(), and rg_.
 {
     return rg_->nextDouble();
 }
double RandomGenerator_R250_R521::nextDouble_st (double lowVal, double highVal) static
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Definition at line 216 of file RandomGenerator_R250_521.cpp.
References nextDouble(), and rg_.
 {
     return rg_->nextDouble(lowVal, highVal);
 }
float RandomGenerator_R250_R521::nextFloat_st (void) static
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
Returns
new float pseudo-random value in the range [0, 1[
Definition at line 201 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat();
 }
float RandomGenerator_R250_R521::nextFloat_st (float lowVal, float highVal) static
Returns a new uniformly-distributed float pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new float pseudo-random value in thhe range [lowVal, highVal[
Definition at line 206 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat(lowVal, highVal);
 }
double RandomGenerator_R250_R521::nextGaussian_st (double sigma = 1.L) static
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Parameters
sigma standard deviation of the distribution
Returns
new normally-distributed double pseudo-random value in the range [0, 1[
Definition at line 221 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextGaussian(), and rg_.
 {
     return rg_->nextGaussian(sigma);
 }
int RandomGenerator_R250_R521::nextInt_st (int lowVal, int highVal) static
Returns a new uniformly-distributed int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 186 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextInt(), and rg_.
 {
     return rg_->nextInt(lowVal, highVal);
 }
long RandomGenerator_R250_R521::nextLong_st (long lowVal, long highVal) static
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 196 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextLong(), and rg_.
 {
     return rg_->nextLong(lowVal, highVal);
 }
unsigned int RandomGenerator_R250_R521::nextUInt_st (void) static
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned int pseudo-random value
Definition at line 181 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::nextUInt(), and rg_.
 {
     return rg_->nextUInt();
 }
unsigned long RandomGenerator_R250_R521::nextULong (void) virtual
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Implements uriVL::RandomGenerator.
Definition at line 118 of file RandomGenerator_R250_521.cpp.
References r250_buffer_, R250_IA, R250_IB, r250_index_, uriVL::R250_LEN, r521_buffer_, R521_IA, R521_IB, r521_index_, and uriVL::R521_LEN.
Referenced by nextDouble(), nextULong_st(), and setSeed().
 {
     /*Michael Brundage
     I prescale the indices by sizeof(unsigned long) to eliminate
     four shlwi instructions in the compiled code.  This minor optimization
     increased perf by about 12%.
     I also carefully arrange index increments and comparisons to minimize
     instructions.  gcc 3.3 seems a bit weak on instruction reordering. The
     j1/j2 branches are mispredicted, but nevertheless these optimizations
     increased perf by another 10%.
     */
     int i1 = r250_index_;
     int i2 = r521_index_;
     unsigned char*  b1 = (unsigned char*)r250_buffer_;
     unsigned char*  b2 = (unsigned char*)r521_buffer_;
     unsigned long * tmp1, * tmp2;
     unsigned long r, s;
     int j1, j2;
     j1 = i1 - R250_IB;
     if (j1 < 0)
         j1 = i1 + R250_IA;
     j2 = i2 - R521_IB;
     if (j2 < 0)
         j2 = i2 + R521_IA;
     tmp1 = (unsigned long *)(b1 + i1);
     r = (*(unsigned long *)(b1 + j1)) ^ (*tmp1);
     *tmp1 = r;
     tmp2 = (unsigned long *)(b2 + i2);
     s = (*(unsigned long *)(b2 + j2)) ^ (*tmp2);
     *tmp2 = s;
     i1 = (i1 != sizeof(unsigned long)*(R250_LEN-1)) ? (i1 + sizeof(unsigned long)) : 0;
     r250_index_ = i1;
     i2 = (i2 != sizeof(unsigned long)*(R521_LEN-1)) ? (i2 + sizeof(unsigned long)) : 0;
     r521_index_ = i2;
     return r ^ s;
 }
unsigned long RandomGenerator_R250_R521::nextULong_st (void) static
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Definition at line 191 of file RandomGenerator_R250_521.cpp.
References nextULong(), and rg_.
 {
     return rg_->nextULong();
 }
void RandomGenerator_R250_R521::setSeed (long theSeed) virtual
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Implements uriVL::RandomGenerator.
Definition at line 70 of file RandomGenerator_R250_521.cpp.
References uriVL::RandomGenerator::INT_IS_LONG, lrand(), nextULong(), r250_buffer_, r250_index_, uriVL::R250_LEN, r521_buffer_, r521_index_, and uriVL::R521_LEN.
Referenced by RandomGenerator_R250_R521(), and setSeed_st().
 {
     //jyh
     //I use a seed to initialize the C random generator
     unsigned int mySeed;
     if (INT_IS_LONG)
         mySeed = static_cast<unsigned int>(theSeed);
     else
     {
         //  keep the most significant bits of the time stamp to be the seed
         mySeed = static_cast<unsigned int>(theSeed >> (sizeof(long)-sizeof(int)));
     }
     srand(mySeed);
     int i = R521_LEN;
     unsigned long mask1 = 1;
     unsigned long mask2 = 0xFFFFFFFF;
         //jyh
     while (i-- > R250_LEN) {
         r521_buffer_[i] = lrand();
     }
     while (i-- > 31) {
         r250_buffer_[i] = lrand();
         r521_buffer_[i] = lrand();
     }
     /*Michael Brundage
     Establish linear independence of the bit columns
     by setting the diagonal bits and clearing all bits above
     */
     while (i-- > 0) {
         r250_buffer_[i] = (lrand() | mask1) & mask2;
         r521_buffer_[i] = (lrand() | mask1) & mask2;
         mask2 ^= mask1;
         mask1 >>= 1;
     }
     r250_buffer_[0] = mask1;
     r521_buffer_[0] = mask2;
     r250_index_ = 0;
     r521_index_ = 0;
     //jyh
     //I call nextULong to get rid of the first number in the generator, which is
     //always an extremely large one (would make a nextDouble of 0.99x)
     nextULong();
 }
void RandomGenerator_R250_R521::setSeed_st (long theSeed) static
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Definition at line 176 of file RandomGenerator_R250_521.cpp.
References rg_, and setSeed().
 {
     rg_->setSeed(theSeed);
 }
Member Data Documentation
const int RandomGenerator_R250_R521::FULL_IN_UINT = ((8*sizeof(unsigned int)) / MAX_BITS_IN_RAND) static
number of full outputs of the C generator fitting in an int
Definition at line 49 of file RandomGenerator_R250_521.h.
const int RandomGenerator_R250_R521::FULL_IN_ULONG = ((8*sizeof(unsigned long)) / MAX_BITS_IN_RAND) static
number of full outputs of the C generator fitting in a long
Definition at line 41 of file RandomGenerator_R250_521.h.
Referenced by lrand().
unsigned long uriVL::RandomGenerator_R250_R521::r250_buffer_[R250_LEN] private
buffer of the R250 algorrithm
Definition at line 177 of file RandomGenerator_R250_521.h.
Referenced by nextULong(), and setSeed().
int uriVL::RandomGenerator_R250_R521::r250_index_ private
index of the R250 algorrithm
Definition at line 169 of file RandomGenerator_R250_521.h.
Referenced by nextULong(), and setSeed().
unsigned long uriVL::RandomGenerator_R250_R521::r521_buffer_[R521_LEN] private
buffer of the R521 algorrithm
Definition at line 181 of file RandomGenerator_R250_521.h.
Referenced by nextULong(), and setSeed().
int uriVL::RandomGenerator_R250_R521::r521_index_ private
index of the R521 algorrithm
Definition at line 173 of file RandomGenerator_R250_521.h.
Referenced by nextULong(), and setSeed().
const int RandomGenerator_R250_R521::RES_TO_UINT static
Initial value:
= ((8*sizeof(unsigned int)) -
                                            FULL_IN_UINT*MAX_BITS_IN_RAND)
number of residual bits of a output of the C generator to dd to make an int
Definition at line 53 of file RandomGenerator_R250_521.h.
const int RandomGenerator_R250_R521::RES_TO_ULONG static
Initial value:
= ((8*sizeof(unsigned long)) -
                                             FULL_IN_ULONG*MAX_BITS_IN_RAND)
number of residual bits of a output of the C generator to dd to make a long
Definition at line 45 of file RandomGenerator_R250_521.h.
Referenced by lrand().
RandomGenerator_R250_R521 * RandomGenerator_R250_R521::rg_ = new RandomGenerator_R250_R521() static private
The unique object of this class, stored as a static member.
Definition at line 165 of file RandomGenerator_R250_521.h.
Referenced by nextDouble_st(), nextFloat_st(), nextGaussian_st(), nextInt_st(), nextLong_st(), nextUInt_st(), nextULong_st(), and setSeed_st().
The documentation for this class was generated from the following files:
RandomGenerator_R250_521.h
RandomGenerator_R250_521.cpp