URIVisionLibrary: uriVL::PatternMatcher2D_warp Class Reference
uriVL::PatternMatcher2D_warp Class Reference
Pattern matcher that uses an image warper to compute a best match for a deformable template.
#include <PatternMatcher2D_warp.h>
Public Member Functions
PatternMatcher2D_warp (BasePatternMatcher2DType matcherType, PowellMethodCode code, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Creates a new warping-based pattern matcher.
PatternMatcher2D_warp (PatternMatcher2D *matcher, PowellMethodCode code, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Creates a new warping-based pattern matcher.
PatternMatcher2D_warp (BasePatternMatcher2DType matcherType, PowellMethodCode code, ImageWarper *warper)
Creates a new warping-based pattern matcher.
PatternMatcher2D_warp (PatternMatcher2D *matcher, PowellMethodCode code, ImageWarper *warper)
Creates a new warping-based pattern matcher.
~PatternMatcher2D_warp (void)
Destructor.
void setPattern (const RasterImage *patImg, const Blob *patBlob=NULL)
Called to define the pattern used for subsequent covariance calculations.
void setPattern (const Pattern2D *pattern)
Called to define the pattern used for subsequent covariance calculations This function is called by the match_ function.
void setImage (const RasterImage *img, const ImagePoint *matchPoint)
Called to define the image used for subsequent covariance calculations.
void getImageSuitableDimensions (int imgWidth, int imgHeight, int *lowImgWidth, int *lowImgHeight, int *highImgWidth, int *highImgHeight)
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
RasterImage * getWarpedImage (void)
Returns the "optimal" warped image corresponding to the best match.
float ***const getInitGrid (void)
Returns a pointer to the array of initial grid coordinates.
Pattern2DMatchRecord * match (const Pattern2D *patt2D, const ImagePoint *matchPoint, const RasterImage *img)
own match function
void match (const Pattern2D *patt2D, const ImagePoint *matchPoint, const RasterImage *img, Pattern2DMatchRecord *matchRecord)
own match function
Pattern2DMatchRecord * match (const RasterImage *pat, const ImagePoint *matchPoint, const RasterImage *img)
own match function
void match (const RasterImage *pat, const ImagePoint *matchPoint, const RasterImage *img, Pattern2DMatchRecord *matchRecord)
own match function
Public Member Functions inherited from uriVL::PatternMatcher2D
PatternMatcher2D (void)
Default constructor.
virtual ~PatternMatcher2D (void)
Destructor.
BasePatternMatcher2DType getBaseMatcherType (void) const
If the matcher is one of the basic types, indicates which.
bool isSubpixelMatcher (void)
Indicates whether the matcher returns an integer of floating point (subpixel) best match.
Pattern2DMatchRecord * match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
Pattern2DMatchRecord * match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, std::list< Blob * > *occluder)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
void match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, Pattern2DMatchRecord *matchRecord)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
void match (const Pattern2D *patternSought, const ImageRect *searchRect, const RasterImage *img, Pattern2DMatchRecord *matchRecord, std::list< Blob * > *occluder)
Determines the Pattern2DMatchRecord of the best match for a target pattern in an image.
Protected Member Functions
void match_ (const RasterImage_RGBa *patImg, const ImageRect *searchRect, const RasterImage_RGBa *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in an rgba image.
void match_ (const RasterImage_gray *patImg, const ImageRect *searchRect, const RasterImage_gray *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in a gray-level image.
void match_ (const RasterImage_RGBa *patImg, const Blob *patBlob, const ImageRect *searchRect, const RasterImage_RGBa *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in an rgba image.
void match_ (const RasterImage_gray *patImg, const Blob *patBlob, const ImageRect *searchRect, const RasterImage_gray *img, Pattern2DMatchRecord *matchRecord)
Determines the location and score of the best match for a target pattern in a gray-level image.
void reverseWarp_ (const Pattern2D *patt2D, const ImagePoint *matchPoint)
reverse warping & get reverse warped contour
bool isProperMatchRecordType_ (const Pattern2DMatchRecord *matchRecord) const
Checks whether the Pattern2DMatchRecord sent has the proper subtype for the matcher.
Pattern2DMatchRecord * newPattern2DMatchRecord_ (void)
Allocates a Pattern2DMatchRecord that has the proper subtype for the matcher.
void deleteGrids_ (void)
deletes the grids and arrays of warp point coordinates stored by this object
void computeGridBounds_ (void)
Initializes the min and max arrays of xy values This function should be moved to the ImageWarper class.
Protected Member Functions inherited from uriVL::PatternMatcher2D
virtual void allocateRasters_ (const RasterImage *patImg, const Blob *patBlob)
Allocates private computation rasters for the pattern and the image.
virtual void deleteRasters_ (void)
Deletes the private computation rasters.
Protected Attributes
NonlinearOptimizerND_conjDir_Powell * optN_
an embedded minimizer
WarpMatchScoreFunctionND * wcf_
an embedded WarpCorrFunctionND
OptimizerRecordND * optRecND_
OptimizerRecordND.
int nDim_
dimension of the NonlinearOptimizerND_conjDir_Powell
int gridRows_
nb of rows of grid in warper
int gridCols_
nb of rows of grid in warper
float * xyStart_
starting ND int array
float * xyMin_
min ND int array
float * xyMax_
max ND int array
float *** gridInit_
initial points of warper_->originalPoints_ computed right after the allocation of wcf_
float *** gridRev_
reverse warped version of initPoints
Contour_I * rwContour_
contour after reverse warping
Protected Attributes inherited from uriVL::PatternMatcher2D
BasePatternMatcher2DType baseMatcherType_
If the matcher is one of the basic types, indicates which.
bool isSubpixelMatcher_
Indicates whether the matcher returns an integer of floating point (subpixel) best match.
const Blob * patBlob_
Blob information of the pattern we are seeking.
BaseRasterType patRasterType_
Raster type of the pattern sought.
const RasterImage * patImg_
Pointer to the pattern's raster.
const RasterImage * img_
Pointer to the search image's raster.
float ** grayPat_
copy of a gray-level pattern's raster
float ** grayImg_
copy of a gray-level image region's raster
float *** rgbaPat_
copy of a color rgba pattern's raster
float *** rgbaImg_
copy of a color rgba image region's raster
unsigned char ** patMask_
mask corresponding to the part of the pattern's bounding box to be used for matching calculations.
int patWidth_
Width of the temporary rasters currently alocated.
int patHeight_
Height of the temporary rasters currently alocated.
Static Protected Attributes
static const float OPT_TOL = static_cast<float>(3.0e-02)
Tolerance of numerical optimization process.
Detailed Description
Pattern matcher that uses an image warper to compute a best match for a deformable template.
Definition at line 33 of file PatternMatcher2D_warp.h.
Constructor & Destructor Documentation
PatternMatcher2D_warp::PatternMatcher2D_warp (BasePatternMatcher2DType matcherType, PowellMethodCode code, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE)
Creates a new warping-based pattern matcher.
Parameters
matcherType type of basic matcher this one is based on
powellCode type of conjugate direction algorithm used
warperType type of image warper used by this object
gridRows number of rows of the warping grid
gridCols number of columns of the warping grid
innerMode grid inner warping mode for this warper
outerMode grid outer warping mode for this warper
Definition at line 34 of file PatternMatcher2D_warp.cpp.
References uriVL::PatternMatcher2D::baseMatcherType_, gridCols_, gridInit_, gridRev_, gridRows_, uriVL::PatternMatcher2D::isSubpixelMatcher_, nDim_, uriVL::WarpMatchScoreFunctionND::newVarArray(), optN_, optRecND_, uriVL::PATTERN_MATCHER_2D_NON_BASIC, rwContour_, wcf_, xyMax_, xyMin_, and xyStart_.
             : PatternMatcher2D()
 {
     isSubpixelMatcher_ = true;
     wcf_ = new WarpMatchScoreFunctionND(matcherType, warperType, gridRows, gridCols,
                                                     innerMode, outerMode);
     optN_ = new NonlinearOptimizerND_conjDir_Powell(wcf_, powellCode);
     nDim_ = optN_->getDimension();
     optRecND_ = new OptimizerRecordND(nDim_);
         xyStart_ = wcf_->newVarArray();
         xyMin_ = wcf_->newVarArray();
         xyMax_ = wcf_->newVarArray();
         gridRows_ = gridRows;
         gridCols_ = gridCols;
         gridInit_ = NULL;
         gridRev_ = NULL;
         rwContour_ = NULL;
         baseMatcherType_ = PATTERN_MATCHER_2D_NON_BASIC;
 }
PatternMatcher2D_warp::PatternMatcher2D_warp (PatternMatcher2D * matcher, PowellMethodCode code, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE)
Creates a new warping-based pattern matcher.
Parameters
predefined basic pattern matcher (e.g. correlation) to use
powellCode type of conjugate direction algorithm used
warperType type of image warper used by this object
gridRows number of rows of the warping grid
gridCols number of columns of the warping grid
innerMode grid inner warping mode for this warper
outerMode grid outer warping mode for this warper
Definition at line 92 of file PatternMatcher2D_warp.cpp.
References uriVL::PatternMatcher2D::baseMatcherType_, gridCols_, gridInit_, gridRev_, gridRows_, uriVL::PatternMatcher2D::isSubpixelMatcher_, nDim_, uriVL::WarpMatchScoreFunctionND::newVarArray(), optN_, optRecND_, uriVL::PATTERN_MATCHER_2D_NON_BASIC, rwContour_, wcf_, xyMax_, xyMin_, and xyStart_.
             : PatternMatcher2D()
 {
     isSubpixelMatcher_ = true;
     wcf_ = new WarpMatchScoreFunctionND(matcher, warperType, gridRows, gridCols,
                                                     innerMode, outerMode);
     optN_ = new NonlinearOptimizerND_conjDir_Powell(wcf_, powellCode);
     nDim_ = optN_->getDimension();
     optRecND_ = new OptimizerRecordND(nDim_);
         xyStart_ = wcf_->newVarArray();
         xyMin_ = wcf_->newVarArray();
         xyMax_ = wcf_->newVarArray();
         gridRows_ = gridRows;
         gridCols_ = gridCols;
         gridInit_ = NULL;
         gridRev_ = NULL;
         rwContour_ = NULL;
         baseMatcherType_ = PATTERN_MATCHER_2D_NON_BASIC;
 }
PatternMatcher2D_warp::PatternMatcher2D_warp (BasePatternMatcher2DType matcherType, PowellMethodCode code, ImageWarper * warper)
Creates a new warping-based pattern matcher.
Parameters
matcherType type of basic matcher this one is based on
powellCode type of conjugate direction algorithm used
predefined image warper (e.g. GL-based) to use
Definition at line 65 of file PatternMatcher2D_warp.cpp.
References uriVL::PatternMatcher2D::baseMatcherType_, uriVL::ImageWarper::getNbGridCols(), uriVL::ImageWarper::getNbGridRows(), gridCols_, gridInit_, gridRev_, gridRows_, uriVL::PatternMatcher2D::isSubpixelMatcher_, nDim_, uriVL::WarpMatchScoreFunctionND::newVarArray(), optN_, optRecND_, uriVL::PATTERN_MATCHER_2D_NON_BASIC, rwContour_, wcf_, xyMax_, xyMin_, and xyStart_.
             : PatternMatcher2D()
 {
     isSubpixelMatcher_ = true;
     wcf_ = new WarpMatchScoreFunctionND(matcherType, warper);
     optN_ = new NonlinearOptimizerND_conjDir_Powell(wcf_, powellCode);
     nDim_ = optN_->getDimension();
     optRecND_ = new OptimizerRecordND(nDim_);
         xyStart_ = wcf_->newVarArray();
         xyMin_ = wcf_->newVarArray();
         xyMax_ = wcf_->newVarArray();
         gridRows_ = warper->getNbGridRows();
         gridCols_ = warper->getNbGridCols();
         gridInit_ = NULL;
         gridRev_ = NULL;
         rwContour_ = NULL;
         baseMatcherType_ = PATTERN_MATCHER_2D_NON_BASIC;
 }
PatternMatcher2D_warp::PatternMatcher2D_warp (PatternMatcher2D * matcher, PowellMethodCode code, ImageWarper * warper)
Creates a new warping-based pattern matcher.
Parameters
predefined basic pattern matcher (e.g. correlation) to use
powellCode type of conjugate direction algorithm used
predefined image warper (e.g. GL-based) to use
Definition at line 123 of file PatternMatcher2D_warp.cpp.
References uriVL::PatternMatcher2D::baseMatcherType_, uriVL::ImageWarper::getNbGridCols(), uriVL::ImageWarper::getNbGridRows(), gridCols_, gridInit_, gridRev_, gridRows_, uriVL::PatternMatcher2D::isSubpixelMatcher_, nDim_, uriVL::WarpMatchScoreFunctionND::newVarArray(), optN_, optRecND_, uriVL::PATTERN_MATCHER_2D_NON_BASIC, rwContour_, wcf_, xyMax_, xyMin_, and xyStart_.
             : PatternMatcher2D()
 {
     isSubpixelMatcher_ = true;
     wcf_ = new WarpMatchScoreFunctionND(matcher, warper);
     optN_ = new NonlinearOptimizerND_conjDir_Powell(wcf_, powellCode);
     nDim_ = optN_->getDimension();
     optRecND_ = new OptimizerRecordND(nDim_);
         xyStart_ = wcf_->newVarArray();
         xyMin_ = wcf_->newVarArray();
         xyMax_ = wcf_->newVarArray();
         gridRows_ = warper->getNbGridRows();
         gridCols_ = warper->getNbGridCols();
         gridInit_ = NULL;
         gridRev_ = NULL;
         rwContour_ = NULL;
         baseMatcherType_ = PATTERN_MATCHER_2D_NON_BASIC;
 }
PatternMatcher2D_warp::~PatternMatcher2D_warp (void)
Destructor.
Definition at line 152 of file PatternMatcher2D_warp.cpp.
References deleteGrids_(), optN_, optRecND_, rwContour_, and wcf_.
 {
         delete optN_;
         delete optRecND_;
         delete wcf_;
         if (rwContour_ != NULL)
             delete rwContour_;
         deleteGrids_();
 }
Member Function Documentation
void PatternMatcher2D_warp::computeGridBounds_ (void) protected
Initializes the min and max arrays of xy values This function should be moved to the ImageWarper class.
Definition at line 746 of file PatternMatcher2D_warp.cpp.
References gridCols_, gridInit_, gridRev_, gridRows_, uriVL::WarpMatchScoreFunctionND::newWarpingGrid(), wcf_, xyMax_, xyMin_, and xyStart_.
Referenced by setImage().
 {
 //      ImageRect* rect = img_->getValidRect();  // unused variable. -CJC
 //      int     imgHeight = rect->getHeight(),  // unused variable. -CJC
 //              imgWidth = rect->getWidth(),       // unused variable. -CJC
         int t = 0;
 //--------------------------------------------------------------------------------
 //  all this is only valid when the warping modes are INNER_BOUNDS & BORDER_FIXED
 //--------------------------------------------------------------------------------
                 //      initialize the grid
                 if (gridInit_ == NULL)
                     gridInit_ = wcf_->newWarpingGrid();
                 if (gridRev_ == NULL)
                     gridRev_ = wcf_->newWarpingGrid();
                 t = 0;
                 for (int i=1; i<gridRows_-1; i++)
                         for (int j=1; j<gridCols_-1; j++)
{
                                 xyStart_[t++] = gridInit_[i][j][0];
                                 xyStart_[t++] = gridInit_[i][j][1];
                         }
                 //      distance in x and y between neighbor grid points
                 int xDist = static_cast<int>(gridInit_[0][1][0] - gridInit_[0][0][0]),
                         yDist = static_cast<int>(gridInit_[1][0][1] - gridInit_[0][0][1]);
 /*
                 int xRange = xDist / 2,
                         yRange = yDist / 2;
 */
 int xRange = 2*xDist/3,
         yRange = 2*yDist/3;
                 int xRange23 = 2*xDist/3,
                         yRange23 = 2*yDist/3;
                 //      initialize xyMin_ and xyMax_
                 t = 0;
                 //      corner 0 -- 0 of the inner grid
                 xyMin_[t] = xyStart_[t] - xRange23;
                 xyMax_[t] = xyStart_[t] + xRange;
                 t++;
                 xyMin_[t] = xyStart_[t] - yRange23;
                 xyMax_[t] = xyStart_[t] + yRange;
                 t++;
                 //  top row of the inner grid
                 for (int j=2; j<gridCols_-2; j++)
                 {
                         xyMin_[t] = xyStart_[t] - xRange;
                         xyMax_[t] = xyStart_[t] + xRange;
                         t++;
                         xyMin_[t] = xyStart_[t] - yRange23;
                         xyMax_[t] = xyStart_[t] + yRange;
                         t++;
                 }
                 //      corner 0 -- cols-1 of the inner grid
                 xyMin_[t] = xyStart_[t] - xRange;
                 xyMax_[t] = xyStart_[t] + xRange23;
                 t++;
                 xyMin_[t] = xyStart_[t] - yRange23;
                 xyMax_[t] = xyStart_[t] + yRange;
                 t++;
                 for (int i=2; i<gridRows_-2; i++)
                 {
                         //      border i -- 0 of the inner grid
                         xyMin_[t] = xyStart_[t] - xRange23;
                         xyMax_[t] = xyStart_[t] + xRange;
                         t++;
                         xyMin_[t] = xyStart_[t] - yRange;
                         xyMax_[t] = xyStart_[t] + yRange;
                         t++;
                         for (int j=2; j<gridCols_-2; j++)
{
                                 xyMin_[t] = xyStart_[t] - xRange;
                                 xyMax_[t] = xyStart_[t] + xRange;
                                 t++;
                                 xyMin_[t] = xyStart_[t] - yRange;
                                 xyMax_[t] = xyStart_[t] + yRange;
                                 t++;
                         }
                         //      border i -- cols-1 of the inner grid
                         xyMin_[t] = xyStart_[t] - xRange;
                         xyMax_[t] = xyStart_[t] + xRange23;
                         t++;
                         xyMin_[t] = xyStart_[t] - yRange;
                         xyMax_[t] = xyStart_[t] + yRange;
                         t++;
                 }
                 //      corner rows-1 -- 0 of the inner grid
                 xyMin_[t] = xyStart_[t] - xRange23;
                 xyMax_[t] = xyStart_[t] + xRange;
                 t++;
                 xyMin_[t] = xyStart_[t] - yRange;
                 xyMax_[t] = xyStart_[t] + yRange23;
                 t++;
                 for (int j=2; j<gridCols_-2; j++)
                 {
                         xyMin_[t] = xyStart_[t] - xRange;
                         xyMax_[t] = xyStart_[t] + xRange;
                         t++;
                         xyMin_[t] = xyStart_[t] - yRange;
                         xyMax_[t] = xyStart_[t] + yRange23;
                         t++;
                 }
                 //      corner rows-1 -- cols-1
                 xyMin_[t] = xyStart_[t] - xRange;
                 xyMax_[t] = xyStart_[t] + xRange23;
                 t++;
                 xyMin_[t] = xyStart_[t] - yRange;
                 xyMax_[t] = xyStart_[t] + yRange23;
 }
void PatternMatcher2D_warp::deleteGrids_ (void) protected
deletes the grids and arrays of warp point coordinates stored by this object
Definition at line 709 of file PatternMatcher2D_warp.cpp.
References gridInit_, gridRev_, gridRows_, xyMax_, xyMin_, and xyStart_.
Referenced by ~PatternMatcher2D_warp().
 {
         if (gridInit_ != NULL)
         {
             for (int i=0; i<gridRows_; i++)
                 delete []gridInit_[i];
             delete []gridInit_;
             gridInit_ = NULL;
         }
         if (gridRev_ != NULL)
         {
             for (int i=0; i<gridRows_; i++)
                 delete []gridRev_[i];
             delete []gridRev_;
             gridRev_ = NULL;
         }
         if (xyStart_ != NULL)
         {
             delete []xyStart_;
             xyStart_ = NULL;
         }
         if (xyMin_ != NULL)
         {
             delete []xyMin_;
             xyMin_ = NULL;
         }
         if (xyMax_ != NULL)
         {
             delete []xyMax_;
             xyMax_ = NULL;
         }
 }
void PatternMatcher2D_warp::getImageSuitableDimensions (int imgWidth, int imgHeight, int * lowImgWidth, int * lowImgHeight, int * highImgWidth, int * highImgHeight)
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
Some warpers require specific image dimensions/ratios (e.g. a GL warper only takes 2^n x 2^n images). Furthermore, QuickTime GraphWorld rasters are padded on some platforms. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
If you want to warp an image, it is therefore recommended that you check what are the closest suitable dimensions for the type of warper you are using.
Parameters
imgWidth input image width
imgHeight input image height
lowImgWidth closest lower suitable width
lowImgHeight closest lower suitable height
highImgWidth closest higher suitable width
highImgHeight closest higher suitable height
Definition at line 218 of file PatternMatcher2D_warp.cpp.
References uriVL::WarpMatchScoreFunctionND::getImageSuitableDimensions(), and wcf_.
Referenced by uriVL::PatternTracker2D::grabImage_().
 {
     wcf_->getImageSuitableDimensions(imgWidth, imgHeight, lowImgWidth, lowImgHeight,
                                         highImgWidth, highImgHeight);
 }
float ***const PatternMatcher2D_warp::getInitGrid (void)
Returns a pointer to the array of initial grid coordinates.
Definition at line 233 of file PatternMatcher2D_warp.cpp.
References gridInit_.
 {
     return gridInit_;
 }
RasterImage * PatternMatcher2D_warp::getWarpedImage (void)
Returns the "optimal" warped image corresponding to the best match.
Definition at line 228 of file PatternMatcher2D_warp.cpp.
References uriVL::WarpMatchScoreFunctionND::getWarpedImage(), and wcf_.
 {
     return wcf_->getWarpedImage();
 }
bool PatternMatcher2D_warp::isProperMatchRecordType_ (const Pattern2DMatchRecord * matchRecord) const protected virtual
Checks whether the Pattern2DMatchRecord sent has the proper subtype for the matcher.
Parameters
matchRecord Pattern2DMatchRecord to check
Implements uriVL::PatternMatcher2D.
Definition at line 695 of file PatternMatcher2D_warp.cpp.
References uriVL::Pattern2DMatchRecord::getRecordType().
Referenced by match().
 {
 //    return (typeid(*matchRecord) == typeid(uriVL::Pattern2DMatchRecord_warp));
     string s1 = matchRecord->getRecordType();
     return (s1.compare("warp match record") == 0);
 }
Pattern2DMatchRecord * PatternMatcher2D_warp::match (const Pattern2D * patt2D, const ImagePoint * matchPoint, const RasterImage * img)
own match function
Definition at line 245 of file PatternMatcher2D_warp.cpp.
Referenced by match(), and uriVL::PatternTracker2D::track().
 {
         Pattern2DMatchRecord_warp *matchRecord = new Pattern2DMatchRecord_warp();
         match(patt2D, matchPoint, img, matchRecord);
         return matchRecord;
 }
void PatternMatcher2D_warp::match (const Pattern2D * patt2D, const ImagePoint * matchPoint, const RasterImage * img, Pattern2DMatchRecord * matchRecord)
own match function
Definition at line 256 of file PatternMatcher2D_warp.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::Pattern2D::getBlob(), uriVL::Pattern2D::getPattern(), uriVL::WarpMatchScoreFunctionND::getWarpingGrid(), isProperMatchRecordType_(), uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kRGBa32Raster, match_(), reverseWarp_(), rwContour_, setImage(), setPattern(), uriVL::Pattern2DMatchRecord_warp::setReverseWarpContour(), uriVL::Pattern2DMatchRecord_warp::setWarpingGrid(), and wcf_.
 {
     FAIL_CONDITION( !isProperMatchRecordType_(matchRecord),
                     kInvalidParameterError,
                     "Pattern2DMatchRecord_warp required");
     Pattern2DMatchRecord_warp *warpMatchRecord = (Pattern2DMatchRecord_warp*) matchRecord;;
     setPattern(patt2D);
     setImage(img, matchPoint);
         switch (img->getBaseRasterType())
         {
                 case kGrayRaster:
                         match_((RasterImage_gray* ) patt2D->getPattern(), patt2D->getBlob(), NULL,
                                    (RasterImage_gray* ) img, (Pattern2DMatchRecord_warp*) matchRecord);
                         break;
                 case kRGBa32Raster:
                         match_((RasterImage_RGBa* ) patt2D->getPattern(), patt2D->getBlob(), NULL,
                                (RasterImage_RGBa* ) img, (Pattern2DMatchRecord_warp*) matchRecord);
                         break;
                 default:
                         break;
         }
     warpMatchRecord->setWarpingGrid(wcf_->getWarpingGrid());
         //-----------------------------
         //      reverse warping & get rwContour
         //-----------------------------
         reverseWarp_(patt2D, matchPoint);
 //    warpMatchRecord->setReverseWarpingGrid(gridRev_);
         warpMatchRecord->setReverseWarpContour(rwContour_);
 }
Pattern2DMatchRecord * PatternMatcher2D_warp::match (const RasterImage * pat, const ImagePoint * matchPoint, const RasterImage * img)
own match function
Definition at line 295 of file PatternMatcher2D_warp.cpp.
References match(), and newPattern2DMatchRecord_().
 {
         Pattern2DMatchRecord* matchRecord = newPattern2DMatchRecord_();
         match(pat, matchPoint, img, matchRecord);
         return matchRecord;
 }
void PatternMatcher2D_warp::match (const RasterImage * pat, const ImagePoint * matchPoint, const RasterImage * img, Pattern2DMatchRecord * matchRecord)
own match function
Definition at line 306 of file PatternMatcher2D_warp.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), isProperMatchRecordType_(), uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kRGBa32Raster, match_(), setImage(), and setPattern().
 {
     FAIL_CONDITION( !isProperMatchRecordType_(matchRecord),
                     kInvalidParameterError,
                     "Pattern2DMatchRecord_warp required");
     setPattern(pat, NULL);
     setImage(img, matchPoint);
         switch (img->getBaseRasterType())
         {
                 case kGrayRaster:
                         match_(static_cast<const RasterImage_gray*>(pat), NULL,
                                    static_cast<const RasterImage_gray*>(img),
                                (Pattern2DMatchRecord_warp*) matchRecord);
                         break;
                 case kRGBa32Raster:
                         match_(static_cast<const RasterImage_RGBa*>(pat), NULL,
                                    static_cast<const RasterImage_RGBa*>(img),
                                (Pattern2DMatchRecord_warp*) matchRecord);
                         break;
                 default:
                         break;
         }
 }
void PatternMatcher2D_warp::match_ (const RasterImage_RGBa * patImg, const ImageRect * searchRect, const RasterImage_RGBa * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in an rgba image.
The search region is specified by an image rectangle. The pattern is a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangluar image pattern to search for in img.
searchRect the region of the search
img the image in which to search for a best match
matchRecord matching record of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 347 of file PatternMatcher2D_warp.cpp.
References OPT_TOL, optN_, uriVL::Pattern2DMatchRecord_warp::optRecND_, optRecND_, uriVL::OptimizerRecordND::optVal, uriVL::Pattern2DMatchRecord::setScore(), xyMax_, xyMin_, and xyStart_.
Referenced by match().
 {
         //float score = wcf_->func(xyStart_);
     optN_->minimize(xyStart_, xyMin_, xyMax_, OPT_TOL, optRecND_);
         //-------------------------
     //  get matchRecord
         //-------------------------
     Pattern2DMatchRecord_warp *warpMatchRecord = (Pattern2DMatchRecord_warp*) matchRecord;
     matchRecord->setScore(static_cast<float>(optRecND_->optVal));
     warpMatchRecord->optRecND_ = optRecND_;
 }
void PatternMatcher2D_warp::match_ (const RasterImage_gray * patImg, const ImageRect * searchRect, const RasterImage_gray * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in a gray-level image.
The search region is specified by an image rectangle. The pattern is a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangluar image pattern to search for in img.
searchRect the region of the search
img the image in which to search for a best match
matchRecord matching record of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 364 of file PatternMatcher2D_warp.cpp.
References OPT_TOL, optN_, uriVL::Pattern2DMatchRecord_warp::optRecND_, optRecND_, uriVL::OptimizerRecordND::optVal, uriVL::Pattern2DMatchRecord::setScore(), xyMax_, xyMin_, and xyStart_.
 {
     optN_->minimize(xyStart_, xyMin_, xyMax_, OPT_TOL, optRecND_);
         //-------------------------
     //  get matchRecord
         //-------------------------
     Pattern2DMatchRecord_warp *warpMatchRecord = (Pattern2DMatchRecord_warp*) matchRecord;
     matchRecord->setScore(static_cast<float>(optRecND_->optVal));
     warpMatchRecord->optRecND_ = optRecND_;
 }
void PatternMatcher2D_warp::match_ (const RasterImage_RGBa * patImg, const Blob * patBlob, const ImageRect * searchRect, const RasterImage_RGBa * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in an rgba image.
The search region is specified by an image rectangle. The pattern is a blob defined over a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangluar image pattern to search for in img.
patBlob the blob that defines the actual geometry of the pattern
searchRect the region of the search
img the image in which to search for a best match
matchRecord matching record of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 379 of file PatternMatcher2D_warp.cpp.
References OPT_TOL, optN_, uriVL::Pattern2DMatchRecord_warp::optRecND_, optRecND_, uriVL::OptimizerRecordND::optVal, uriVL::Pattern2DMatchRecord::setScore(), xyMax_, xyMin_, and xyStart_.
 {
     optN_->minimize(xyStart_, xyMin_, xyMax_, OPT_TOL, optRecND_);
         //-------------------------
     //  get matchRecord
         //-------------------------
     Pattern2DMatchRecord_warp *warpMatchRecord = (Pattern2DMatchRecord_warp*) matchRecord;
     matchRecord->setScore(static_cast<float>(optRecND_->optVal));
     warpMatchRecord->optRecND_ = optRecND_;
 }
void PatternMatcher2D_warp::match_ (const RasterImage_gray * patImg, const Blob * patBlob, const ImageRect * searchRect, const RasterImage_gray * img, Pattern2DMatchRecord * matchRecord) protected virtual
Determines the location and score of the best match for a target pattern in a gray-level image.
The search region is specified by an image rectangle. The pattern is a blob defined over a (small) rectangular image patch
If the search region selected extends out of the image's valid data rectangle, then a smaller effective search region is used instead.
Note for developers of stereo or motion matchers: the origin of a pattern is in its upper-left corner. You will need to translate the best match found by half the dimensions of the target pattern if you want to do point-to-point matching (disparity)
Parameters
patImg the rectangluar image pattern to search for in img.
patBlob the blob that defines the actual geometry of the pattern
searchRect the region of the search
img the image in which to search for a best match
matchRecord matching record of the best match found
Implements uriVL::PatternMatcher2D.
Definition at line 394 of file PatternMatcher2D_warp.cpp.
References OPT_TOL, optN_, uriVL::Pattern2DMatchRecord_warp::optRecND_, optRecND_, uriVL::OptimizerRecordND::optVal, uriVL::Pattern2DMatchRecord::setScore(), xyMax_, xyMin_, and xyStart_.
 {
     optN_->minimize(xyStart_, xyMin_, xyMax_, OPT_TOL, optRecND_);
         //-------------------------
     //  get matchRecord
         //-------------------------
     Pattern2DMatchRecord_warp *warpMatchRecord = (Pattern2DMatchRecord_warp*) matchRecord;
     matchRecord->setScore(static_cast<float>(optRecND_->optVal));
     warpMatchRecord->optRecND_ = optRecND_;
 }
Pattern2DMatchRecord * PatternMatcher2D_warp::newPattern2DMatchRecord_ (void) protected virtual
Allocates a Pattern2DMatchRecord that has the proper subtype for the matcher.
Returns
a match recordthat has the proper subtype for the matcher
Implements uriVL::PatternMatcher2D.
Definition at line 704 of file PatternMatcher2D_warp.cpp.
Referenced by match().
 {
     return new Pattern2DMatchRecord_warp();
 }
void PatternMatcher2D_warp::reverseWarp_ (const Pattern2D * patt2D, const ImagePoint * matchPoint) protected
reverse warping & get reverse warped contour
Parameters
patt2D reference 2D pattern
matchPoint matching point
Definition at line 413 of file PatternMatcher2D_warp.cpp.
References uriVL::Pattern2D::getBlob(), uriVL::Blob::getContour(), uriVL::Contour_I::getPoints(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), gridCols_, gridInit_, gridRev_, gridRows_, optRecND_, uriVL::OptimizerRecordND::optX, uriVL::R_W_ACCESS, and rwContour_.
Referenced by match().
 {
         double  *warpXY = optRecND_->optX;
         float   x1, x2, x3, x4, y1, y2, y3, y4,
                         dx, dx1, dx2, dy, dy1, dy2,
                         ratio1, ratio2,
                         a, b, c,
                         hRatio, vRatio,
                         hSol1, hSol2, vSol1, vSol2,
                         temp1, temp2, //temp3, // unused variable. -CJC
                         xFactor1, xFactor2, xFactor3, xFactor4, xFactor5,
                         yFactor1, yFactor2, yFactor3, yFactor4, yFactor5;;
         int             i, j, x, y, newX, newY;
         //      get gridRev_
         int k=0;
         for (i=0; i<gridRows_; i++)
         {
                 for (j=0; j<gridCols_; j++)
                 {
                         //      simple version of reverse warping
                         if ((i>0) && (i<gridRows_-1) && (j>0) && (j<gridCols_-1))
{
                                 gridRev_[i][j][0] = static_cast<float>(warpXY[k++]);
                                 gridRev_[i][j][1] = static_cast<float>(warpXY[k++]);
                         }
                         else
{
                                 gridRev_[i][j][0] = gridInit_[i][j][0];
                                 gridRev_[i][j][1] = gridInit_[i][j][1];
                         }
                 }
         }
         //      compute the contour's updated positions after reverse warping
         const Contour_I *ct = patt2D->getBlob()->getContour();
         if (rwContour_ != NULL)
                 delete rwContour_;
         rwContour_ = new Contour_I();
         const list<ImagePoint*> *pointList = ct->getPoints();
         list<ImagePoint*>::const_iterator endIter = pointList->end(), ptListIter;
         list<ImagePoint* > *ptList = rwContour_->getPoints(R_W_ACCESS);
         //      iterate each point of contour
         for (list<ImagePoint*>::const_iterator iter=pointList->begin(); iter!=endIter; iter++)
         {
                 //      translate x, y to start from the matchPoint in img
                 x = (*iter)->getX() + matchPoint->getX();
                 y = (*iter)->getY() + matchPoint->getY();
                 bool found = false;
                 for (i=0; i<gridRows_-1 && !found; i++)
                 {
                         int ip1 = i + 1;
                         for (j=0; j<gridCols_-1 && !found; j++)
{
                                 int jp1 = j + 1;
                                 x1 = gridRev_[i][j][0];
                                 x2 = gridRev_[i][jp1][0];
                                 x3 = gridRev_[ip1][j][0];
                                 x4 = gridRev_[ip1][jp1][0];
                                 y1 = gridRev_[i][j][1];
                                 y2 = gridRev_[i][jp1][1];
                                 y3 = gridRev_[ip1][j][1];
                                 y4 = gridRev_[ip1][jp1][1];
                                 //      compute whether the point overlap with one of the four vertices
                                 if (x==x1 && y==y1)
{
                                         newX = int(gridInit_[i][j][0]);
                                         newY = int(gridInit_[i][j][1]);
                                         ptList->push_back(new ImagePoint(newX, newY));
                                         found = true;
                                 }
                                 else if (x==x2 && y==y2)
{
                                         newX = int(gridInit_[i][jp1][0]);
                                         newY = int(gridInit_[i][jp1][1]);
                                         ptList->push_back(new ImagePoint(newX, newY));
                                         found = true;
                                 }
                                 else if (x==x3 && y==y3)
{
                                         newX = int(gridInit_[ip1][j][0]);
                                         newY = int(gridInit_[ip1][j][1]);
                                         ptList->push_back(new ImagePoint(newX, newY));
                                         found = true;
                                 }
                                 else if (x==x4 && y==y4)
{
                                         newX = int(gridInit_[ip1][jp1][0]);
                                         newY = int(gridInit_[ip1][jp1][1]);
                                         ptList->push_back(new ImagePoint(newX, newY));
                                         found = true;
                                 }
                                 //      compute whether inside either of the two triangles of this square
                                 else
{
                                         bool inside = false;
                                         //      try first triangle
                                         dx = x - x3;
                                         dx1 = x1 - x3;
                                         dx2 = x4 - x3;
                                         dy = y - y3;
                                         dy1 = y1 - y3;
                                         dy2 = y4 - y3;
                                         ratio1 = dx*dy1 - dy*dx1;
                                         ratio2 = dx*dy2 - dy*dx2;
                                         //      if on one of the 2 borders of the first triangle
                                         if (ratio1 == 0)
{
                                                 vRatio = dy / dy1;
                                                 newY = int(vRatio * gridInit_[i][j][1] + (1 - vRatio) * gridInit_[ip1][j][1]);
                                                 newX = int(gridInit_[i][j][0]);
                                                 ptList->push_back(new ImagePoint(newX, newY));
                                                 found = true;
                                         }
                                         //      if on the other of the 2 borders of the first triangle
                                         else if (ratio2 == 0)
{
                                                 hRatio = dx / dx2;
                                                 newX = int(hRatio * gridInit_[ip1][jp1][0] + (1 - hRatio) * gridInit_[ip1][j][0]);
                                                 newY = int(gridInit_[ip1][j][1]);
                                                 ptList->push_back(new ImagePoint(newX, newY));
                                                 found = true;
                                         }
                                         //      on neither border of the first triangle
                                         else
{
                                                 ratio1 /= (dx2*dy1 - dy2*dx1);
                                                 ratio2 /= -(dx2*dy1 - dy2*dx1);
                                                 if (ratio1 > 0 && ratio2 > 0 && (ratio1+ratio2) <= 1)
                                                         inside = true;
                                                 //      if not inside the first triangle, then try the second triangle
                                                 if (!inside)
{
                                                         dx = x - x2;
                                                         dx2 = x1 - x2;
                                                         dx1 = x4 - x2;
                                                         dy = y - y2;
                                                         dy2 = y1 - y2;
                                                         dy1 = y4 - y2;
                                                         ratio1 = dx*dy1 - dy*dx1;
                                                         ratio2 = dx*dy2 - dy*dx2;
                                                         //      if on one of the 2 borders of the second triangle
                                                         if (ratio1 == 0)
{
                                                                 vRatio = dy / dy1;
                                                                 newY = int(vRatio * gridInit_[ip1][jp1][1] + (1 - vRatio) * gridInit_[i][jp1][1]);
                                                                 newX = int(gridInit_[ip1][jp1][0]);
                                                                 ptList->push_back(new ImagePoint(newX, newY));
                                                                 found = true;
                                                         }
                                                         //      if on the other of the 2 borders of the second triangle
                                                         else if (ratio2 == 0)
{
                                                                 hRatio = dx / dx2;
                                                                 newX = int(hRatio * gridInit_[i][j][0] + (1 - hRatio) * gridInit_[i][jp1][0]);
                                                                 newY = int(gridInit_[i][jp1][1]);
                                                                 ptList->push_back(new ImagePoint(newX, newY));
                                                                 found = true;
                                                         }
                                                         //      on neither border of the second triangle
                                                         else
{
                                                                 ratio1 /= (dx2*dy1 - dy2*dx1);
                                                                 ratio2 /= -(dx2*dy1 - dy2*dx1);
                                                                 if (ratio1 > 0 && ratio2 > 0 && (ratio1+ratio2) <= 1)
                                                                         inside = true;
                                                         }
                                                 }
                                                 //      found the right square, compute the point's new coordinate
                                                 if (inside)
{
                                                         xFactor1 = x1 - x;
                                                         xFactor2 = x1 - x2;
                                                         xFactor3 = x1 - x3;
                                                         xFactor4 = x3 - x4;
                                                         xFactor5 = x3 - x;
                                                         //      compute hRatio
                                                         a = xFactor4 * (y1 - y2) - xFactor2 * (y3 - y4);
                                                         b = (xFactor4 - xFactor2) * y - (xFactor5 + xFactor4) * y1
                                                                 + xFactor5 * y2 + (xFactor1 + xFactor2) * y3 - xFactor1 * y4;
                                                         c = xFactor3 * y + xFactor5 * y1 - xFactor1 * y3;
                                                         if (a==0)
                                                                 hRatio = -c / b;
                                                         else
{
                                                                 temp1 = 2.f*a;
                                                                 temp2 = sqrtf(b*b - 4.f*a*c + 1.f);
                                                                 hSol1 = (-b + temp2) / temp1;
                                                                 hSol2 = (-b - temp2) / temp1;
                                                                 hRatio = (hSol1 >= 0 && hSol1 <= 1) ? hSol1 : hSol2;
                                                         }
                                                         //newX = round((1-hRatio)*gridInit_[i][j][0] + hRatio*gridInit_[i][jp1][0]);
                                                         newX = int((1-hRatio)*gridInit_[i][j][0] + hRatio*gridInit_[i][jp1][0] + 0.5f);
                                                         yFactor1 = y1 - y;
                                                         yFactor2 = y1 - y3;
                                                         yFactor3 = y1 - y2;
                                                         yFactor4 = y2 - y4;
                                                         yFactor5 = y2 - y;
                                                         //      compute hRatio
                                                         a = yFactor4 * (x1 - x3) - yFactor2 * (x2 - x4);
                                                         b = (yFactor4 - yFactor2) * x - (yFactor5 + yFactor4) * x1
                                                                 + yFactor5 * x3 + (yFactor1 + yFactor2) * x2 - yFactor1 * x4;
                                                         c = yFactor3 * x + yFactor5 * x1 - yFactor1 * x2;
                                                         if (a==0)
                                                                 vRatio = -c / b;
                                                         else
{
                                                                 temp1 = 2.f*a;
                                                                 temp2 = sqrtf(b*b - 4.f*a*c + 1.f);
                                                                 vSol1 = (-b + temp2) / temp1;
                                                                 vSol2 = (-b - temp2) / temp1;
                                                                 vRatio = (vSol1 >= 0 && vSol1 <= 1) ? vSol1 : vSol2;
                                                         }
                                                         //newX = round((1-hRatio)*gridInit_[i][j][0] + hRatio*gridInit_[i][jp1][0]);
                                                         newY = int((1-vRatio)*gridInit_[i][j][1] + vRatio*gridInit_[ip1][j][1] + 0.5f);
 /*
                                                         //      compute vRatio
                                                         temp3 = -xFactor3 + (xFactor2 - xFactor4) * hRatio;
                                                         #if DEBUG
                                                         if (temp1 == 0)
                                                                 int dbg1 = temp1;
                                                         if (temp3 == 0)
                                                                 int dbg3 = temp3;
                                                         #endif
                                                         vRatio = (-xFactor1 + xFactor2 * hRatio) / temp3;
                                                         if (vRatio > 1)
                                                                 vRatio = 1;
                                                         if (vRatio < 0)
                                                                 vRatio = 0;
                                                         //newY = round((1-vRatio)*gridInit_[i][j][1] + vRatio*gridInit_[ip1][j][1]);
                                                         newY = int((1-vRatio)*gridInit_[i][j][1] + vRatio*gridInit_[ip1][j][1]);
 */
                                                         //      get reverse warped contour
                                                         bool samePoint = false;
                                                         if (!ptList->empty())
{
                                                                 ptListIter = ptList->end();
                                                                 ptListIter--;
                                                                 if ((*ptListIter)->getX() == newX && (*ptListIter)->getY() == newY)
                                                                         samePoint = true;
                                                         }
                                                         if (!samePoint)
                                                                 ptList->push_back(new ImagePoint(newX, newY));
                                                         found = true;
                                                 }
                                         }
                                 }
                         }
                 }
         }
 }
void PatternMatcher2D_warp::setImage (const RasterImage * img, const ImagePoint * matchPoint) virtual
Called to define the image used for subsequent covariance calculations.
Currently, the image's base raster type should match that of the pattern (which implies that the pattern should have been set before this function is called)
Parameters
img the image in which we seek a best match for the pattern
matchPoint origin of the search
See also
setPattern
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 200 of file PatternMatcher2D_warp.cpp.
References computeGridBounds_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::PatternMatcher2D::img_, uriVL::kInvalidParameterError, uriVL::kNullRasterImageError, optN_, uriVL::PatternMatcher2D::patRasterType_, uriVL::WarpMatchScoreFunctionND::setImage(), and wcf_.
Referenced by match().
 {
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL image sent as parameter to PatternMatcher2D_corr::setImage");
     FAIL_CONDITION(     img->getBaseRasterType() != patRasterType_,
                     kInvalidParameterError,
                     "image type must match pattern type (so far)");
     wcf_->setImage(img, matchPoint);
         optN_->setFunction(wcf_);
     img_ = img;
     computeGridBounds_();
 }
void PatternMatcher2D_warp::setPattern (const RasterImage * patImg, const Blob * patBlob = NULL) virtual
Called to define the pattern used for subsequent covariance calculations.
This function is called by the match_ function. It (and setImage) should be called prior to a call to covariance(). Currently only RGBa and gray-level patterns are accepted.
Parameters
patImg the rectangular pattern we are seaking
patBlob the blob that defines the actual geometry of the pattern
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 181 of file PatternMatcher2D_warp.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, optN_, uriVL::PatternMatcher2D::patBlob_, uriVL::PatternMatcher2D::patImg_, uriVL::PatternMatcher2D::patRasterType_, uriVL::WarpMatchScoreFunctionND::setPattern(), and wcf_.
Referenced by match(), and setPattern().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL image sent as parameter to PatternMatcher2D_warp::setPattern");
     BaseRasterType patRasterType = patImg->getBaseRasterType();
     FAIL_CONDITION(     (patRasterType != kGrayRaster) && (patRasterType != kRGBa32Raster),
                     kInvalidParameterError,
                     "PatternMatcher2D_corr::setPattern only takes gray and RGBa images");
     wcf_->setPattern(patImg, patBlob);
         optN_->setFunction(wcf_);
     patImg_ = patImg;
     patBlob_ = patBlob;
     patRasterType_ = patImg->getBaseRasterType();
 }
void PatternMatcher2D_warp::setPattern (const Pattern2D * pattern) virtual
Called to define the pattern used for subsequent covariance calculations This function is called by the match_ function.
It (and setImage) should be called prior to a call to covariance(). Currently only RGBa and gray-level patterns are accepted.
Parameters
pattern the pattern we are seaking
Reimplemented from uriVL::PatternMatcher2D.
Definition at line 173 of file PatternMatcher2D_warp.cpp.
References FAIL_CONDITION, uriVL::Pattern2D::getBlob(), uriVL::Pattern2D::getPattern(), uriVL::kNullParameterError, and setPattern().
 {
     FAIL_CONDITION(     pat == NULL,
                     kNullParameterError,
                     "NULL pattern sent as parameter to PatternMatcher2D_warp::setPattern");
     setPattern(pat->getPattern(), pat->getBlob());
 }
Member Data Documentation
int uriVL::PatternMatcher2D_warp::gridCols_ protected
nb of rows of grid in warper
Definition at line 213 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), PatternMatcher2D_warp(), and reverseWarp_().
float*** uriVL::PatternMatcher2D_warp::gridInit_ protected
initial points of warper_->originalPoints_ computed right after the allocation of wcf_
Definition at line 230 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), getInitGrid(), PatternMatcher2D_warp(), and reverseWarp_().
float*** uriVL::PatternMatcher2D_warp::gridRev_ protected
reverse warped version of initPoints
Definition at line 234 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), PatternMatcher2D_warp(), and reverseWarp_().
int uriVL::PatternMatcher2D_warp::gridRows_ protected
nb of rows of grid in warper
Definition at line 209 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), PatternMatcher2D_warp(), and reverseWarp_().
int uriVL::PatternMatcher2D_warp::nDim_ protected
dimension of the NonlinearOptimizerND_conjDir_Powell
Definition at line 205 of file PatternMatcher2D_warp.h.
Referenced by PatternMatcher2D_warp().
const float PatternMatcher2D_warp::OPT_TOL = static_cast<float>(3.0e-02) static protected
Tolerance of numerical optimization process.
Definition at line 243 of file PatternMatcher2D_warp.h.
Referenced by match_().
NonlinearOptimizerND_conjDir_Powell* uriVL::PatternMatcher2D_warp::optN_ protected
an embedded minimizer
Definition at line 193 of file PatternMatcher2D_warp.h.
Referenced by match_(), PatternMatcher2D_warp(), setImage(), setPattern(), and ~PatternMatcher2D_warp().
OptimizerRecordND* uriVL::PatternMatcher2D_warp::optRecND_ protected
OptimizerRecordND.
Definition at line 201 of file PatternMatcher2D_warp.h.
Referenced by match_(), PatternMatcher2D_warp(), reverseWarp_(), and ~PatternMatcher2D_warp().
Contour_I* uriVL::PatternMatcher2D_warp::rwContour_ protected
contour after reverse warping
Definition at line 238 of file PatternMatcher2D_warp.h.
Referenced by match(), PatternMatcher2D_warp(), reverseWarp_(), and ~PatternMatcher2D_warp().
WarpMatchScoreFunctionND* uriVL::PatternMatcher2D_warp::wcf_ protected
an embedded WarpCorrFunctionND
Definition at line 197 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), getImageSuitableDimensions(), getWarpedImage(), match(), PatternMatcher2D_warp(), setImage(), setPattern(), and ~PatternMatcher2D_warp().
float* uriVL::PatternMatcher2D_warp::xyMax_ protected
max ND int array
Definition at line 225 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), match_(), and PatternMatcher2D_warp().
float* uriVL::PatternMatcher2D_warp::xyMin_ protected
min ND int array
Definition at line 221 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), match_(), and PatternMatcher2D_warp().
float* uriVL::PatternMatcher2D_warp::xyStart_ protected
starting ND int array
Definition at line 217 of file PatternMatcher2D_warp.h.
Referenced by computeGridBounds_(), deleteGrids_(), match_(), and PatternMatcher2D_warp().
The documentation for this class was generated from the following files:
PatternMatcher2D_warp.h
PatternMatcher2D_warp.cpp