URIVisionLibrary: uriVL::RowVector Class Reference
uriVL::RowVector Class Reference
Implements the RowVector class of Linear Algebra row vectors.
#include <RowVector.h>
Public Member Functions
RowVector (int nbCols)
Creates a new zero row vector at the dimensions specified.
RowVector (int nbCols, double v)
Creates a new constant row vector at the dimensions specified.
RowVector (int nbCols, const double *v)
Creates a new row vector at the dimensions specified and initializes it with the values of a 1D array.
RowVector (const RowVector *b)
Copy constructor.
~RowVector (void)
Destructor.
double norm2 (void) const
Resizes the RowVector at the new dimension specified.
double dotProduct (const RowVector *b) const
Computes the dot product of this vector and of the row vector received as parameter.
double dotProduct (const ColumnVector *b) const
Computes the dot product of this vector and of the column vector received as parameter.
Matrix * outerProduct (const RowVector *b) const
Computes the outer product matrix of this mx1 column vector and of the 1xn row vector received as parameter.
Matrix * outerProduct (const ColumnVector *b) const
Computes the outer product matrix of this mx1 column vector and of the 1xn row vector received as parameter.
Matrix * transposition (void) const
Computes the transpose of this vector, which is a column vector.
void normalize1 (void)
Normalize the vector according to norm N1.
void normalize2 (void)
Normalize the vector according to norm N2.
void normalizeInf (void)
Normalize the vector according to norm Ninf.
Public Member Functions inherited from uriVL::Matrix
Matrix (int nbRows, int nbCols)
Creates a nbRows x nbCols matrix whose elements have not been initialized.
Matrix (int nbRows, int nbCols, double v)
"v-valued" constructor of Matrix class.
Matrix (const Matrix *b)
Copy constructor.
Matrix (const Matrix &b)
Copy constructor.
Matrix (int nbRows, int nbCols, double **m, bool safe=true, const MatrixIndicators *matrixIndic=NULL)
"array" constructor of Matrix class.
virtual ~Matrix (void)
Destructor.
int getNbRows (void) const
This function returns a int corresponding to the number of rows in this
int getNbCols (void) const
This function returns a int corresponding to the number of columns in this
const double *const * getMatrix (void) const
Returns a read-only pointer to the matrix data.
double *const * getMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
TriState isSymmetric (void)
Check whether the matrix is symmetric.
TriState isAntisymmetric (void)
Check whether the matrix is antisymmetric.
TriState isOrthogonal (void)
Check whether the matrix is orthogonal.
TriState isDiagonal (void)
Check whether the matrix is diagonal.
TriState isIdentity (void)
Check whether the matrix is an identity matrix.
TriState isUpperTriangular (void)
Check whether the matrix is upper-triangular.
TriState isLowerTriangular (void)
Check whether the matrix is lower-triangular.
double checkSymmetryStatus (void)
Check whether the matrix is symmetric.
double checkAntisymmetryStatus (void)
Check whether the matrix is antisymmetric.
double checkOrthogonalityStatus (void)
Check whether the matrix is orthogonal.
double checkDiagonalityStatus (void)
Check whether the matrix is diagonal.
double checkIdentityStatus (void)
Check whether the matrix is an identity matrix.
double checkUpperTriangularityStatus (void)
Check whether the matrix is upper-triangular.
double checkLowerTriangularityStatus (void)
Check whether the matrix is lower-triangular.
double checkNormalization1Status (void)
Check whether the matrix is normalized according to Norm 1.
double checkNormalization2Status (void)
Check whether the matrix is normalized according to Norm 2.
double checkNormalizationInfStatus (void)
Check whether the matrix is normalized according to Norm 1.
void enforceSymmetry (void)
Forces a matrix that passes the test for symmetry of checkIsSymmetric_ to be exactly symmetric.
void enforcesAntisymmetry (void)
Forces a matrix that passes the test for antisymmetry of checkIsAntisymmetric_ to be exactly antisymmetric.
void enforceOthogonality (void)
Forces a matrix that passes the test for orthogonality of checkIsSymmetric_ to be exactly orthogonality.
void enforceDiagonality (void)
Forces a matrix that passes the test for diagonality of checkIsDiagonal_ to be exactly diagonal.
void enforceIdentity (void)
Forces a matrix that passes the test for identity of checkIsIdentity_ to be exactly identity.
void enforceUpperTriangularity (void)
Forces a matrix that passes the test for upper-triangularity of checkIsUpperTriangular_ to be exactly upper-triangular.
void enforceLowerTriangularity (void)
Forces a matrix that passes the test for lower-triangularity of checkIsLowerTriangular_ to be exactly lower-triangular.
void operator+= (const Matrix &b)
This function adds the parameter Matrix b to this thereby modifying this.
virtual void operator-= (const Matrix &b)
This function subtracts the parameter Matrix from this thereby modifying this.
virtual void operator*= (const double s)
This function multiplies every element of this by the scalar parameter thereby modifying this.
virtual void operator*= (const Matrix &b)
This function premultiplies the parameter Matrix b by this thereby modifying this.
virtual void preMultiplyBy (const Matrix *b)
This function premultiplies this by the parameter Matrix b thereby modifying this
virtual void postMultiplyBy (const Matrix *b)
This function postmultiplies this by the parameter Matrix b thereby modifying this
const Matrix & operator= (const Matrix &b)
Assigns to this matrix the matrix received as parameter (resizes it if necessary.
TriState operator== (const Matrix &b) const
This function does an element-wise comparison to the parameter Matrix b with this.
double operator() (int theRow, int theCol) const
This function returns the element of the Matrix at row theRow and column theCol.
void rowSwap (int r1, int r2)
This function swaps rows of the Matrix (rather, of mat_)
void colSwap (int c1, int c2)
This function swaps columns of the Matrix (rather, of mat_)
double norm1 (void) const
This function returns a double corresponding to the "1" norm of the Matrix this.
double normInf (void) const
This function returns a double corresponding to the "Infinity" norm of the Matrix this.
double determinant (void) const
This function returns a double corresponding to the determinant of the Matrix this.
virtual void transpose (void)
This function transposes this, thereby altering this.
virtual Matrix * inverse (void) const
This function creates a new Matrix corresponding to the inverse of this (if nonsingular).
virtual void invert (void)
This function inverts this (if nonsingular), thereby modifying this.
string toString (void) const
This function returns a string corresponding to the matrix using the static delimiting strings for the Matrix class.
string toString (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) const
This function returns a string corresponding to the matrix using the parameters as delimiting strings.
Static Public Member Functions
static RowVector * randomVector (int nbCols, double lowerBound, double upperBound)
produces a new column vector filled with random values between lowerBound (inclusive) and upperBound (exclusive)
Static Public Member Functions inherited from uriVL::Matrix
static Matrix * copyMatrix (int nbRows, int nbCols, const double *const *m)
Creates a new nbRows x nbCols matrix and copies into it the elements of the 2D array referenced by m.
static Matrix * nullMatrix (int nbRows, int nbCols)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements to zero.
static Matrix * diagonalMatrix (int nbRows, int nbCols, double v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * diagonalMatrix (int nbRows, int nbCols, const double *v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * identityMatrix (int n)
Produces a new identity matrix at the dimensions specified.
static Matrix * randomMatrix (int nbRows, int nbCols, double lowerBound, double upperBound)
produces a new matrix filled with random values between lowerBound (inclusive) and upperBound (exclusive)
static void setToStringFormat (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor)
This function resets the delimiting strings used when generating a string representation for a given matrix.
Friends
class ColumnVector
Detailed Description
Implements the RowVector class of Linear Algebra row vectors.
Definition at line 29 of file RowVector.h.
Constructor & Destructor Documentation
RowVector::RowVector (int nbCols)
Creates a new zero row vector at the dimensions specified.
Parameters
nbCols number of columns of the new row vector
Definition at line 21 of file RowVector.cpp.
Referenced by randomVector().
     :   Matrix(1, nbCols)
 {
 }
RowVector::RowVector (int nbCols, double v)
Creates a new constant row vector at the dimensions specified.
Parameters
nbCols number of columns of the new row vector
v the value at which to initialize all elements of the vector
Definition at line 27 of file RowVector.cpp.
     :   Matrix(1, nbCols, v)
 {
 }
RowVector::RowVector (int nbCols, const double * v)
Creates a new row vector at the dimensions specified and initializes it with the values of a 1D array.
Parameters
nbCols number of columns of the new row vector
v the array of values at which to initialize the elements of the vector
Definition at line 33 of file RowVector.cpp.
References uriVL::Matrix::mat_, and uriVL::Matrix::nbCols_.
     :   Matrix(1, nbCols)
 {
     for (int j=0; j<nbCols_; j++)
         mat_[0][j] = v[j];
 }
RowVector::RowVector (const RowVector * b)
Copy constructor.
Parameters
b the RowVector to copy
Definition at line 41 of file RowVector.cpp.
References uriVL::Matrix::isNormalized1_, uriVL::Matrix::isNormalized2_, and uriVL::Matrix::isNormalizedInf_.
 :   Matrix(b)
 {
     isNormalized1_ = b->isNormalized1_;
     isNormalized2_ = b->isNormalized2_;
     isNormalizedInf_ = b->isNormalizedInf_;
 }
RowVector::~RowVector (void)
Destructor.
Definition at line 49 of file RowVector.cpp.
 {
 }
Member Function Documentation
double uriVL::RowVector::dotProduct (const RowVector * b) const
Computes the dot product of this vector and of the row vector received as parameter.
Fails (throws an exception or aborts) if the vectors' dimensions don't match.
Parameters
b the row vector to compute the
Returns
the dot product of the two vectors
double uriVL::RowVector::dotProduct (const ColumnVector * b) const
Computes the dot product of this vector and of the column vector received as parameter.
Fails (throws an exception or aborts) if the vectors' dimensions don't match.
Parameters
b the row vector to compute the
Returns
the dot product of the two vectors
double RowVector::norm2 (void) const
Resizes the RowVector at the new dimension specified.
If this new dimension is less than the previous number of storage columns, only nbCols_ is modified, otherwise the mat_ array is reallocated.
Parameters
newNbCols new number of columns for this matrix Returns the Euclidean norm of this vector
Returns
the Euclidean norm of this vector
Definition at line 70 of file RowVector.cpp.
References uriVL::Matrix::mat_, and uriVL::Matrix::nbCols_.
Referenced by normalize2().
 {
     double sum = 0.L;
     for (int j=0; j<nbCols_; j++)
         sum += mat_[0][j] * mat_[0][j];
     return sqrt(sum);
 }
void RowVector::normalize1 (void)
Normalize the vector according to norm N1.
Definition at line 103 of file RowVector.cpp.
References uriVL::Matrix::mat_, uriVL::Matrix::nbCols_, and uriVL::Matrix::norm1().
 {
     double  normVal = norm1();
     if (normVal != 0)
     {
         double  normScale = 1.L / normVal;
         for (int j=0; j<nbCols_; j++)
             mat_[0][j] *= normScale;
     }
 }
void RowVector::normalize2 (void)
Normalize the vector according to norm N2.
Definition at line 115 of file RowVector.cpp.
References uriVL::Matrix::mat_, uriVL::Matrix::nbCols_, and norm2().
 {
     double  normVal = norm2();
     if (normVal != 0)
     {
         double  normScale = 1.L / normVal;
         for (int j=0; j<nbCols_; j++)
             mat_[0][j] *= normScale;
     }
 }
void RowVector::normalizeInf (void)
Normalize the vector according to norm Ninf.
Definition at line 126 of file RowVector.cpp.
References uriVL::Matrix::mat_, uriVL::Matrix::nbCols_, and uriVL::Matrix::normInf().
 {
     double  normVal = normInf();
     if (normVal != 0)
     {
         double  normScale = 1.L / normVal;
         for (int j=0; j<nbCols_; j++)
             mat_[0][j] *= normScale;
     }
 }
Matrix* uriVL::RowVector::outerProduct (const RowVector * b) const
Computes the outer product matrix of this mx1 column vector and of the 1xn row vector received as parameter.
The output matrix will be mxn, and is in fact simply computed as the regular matrix product of this and b
Parameters
b the row vector to compute the outer product with
Returns
the dot product of the two vectors
Matrix* uriVL::RowVector::outerProduct (const ColumnVector * b) const
Computes the outer product matrix of this mx1 column vector and of the 1xn row vector received as parameter.
The output matrix will be mxn.
Parameters
b the row vector to compute the outer product with
Returns
the dot product of the two vectors
RowVector * RowVector::randomVector (int nbCols, double lowerBound, double upperBound) static
produces a new column vector filled with random values between lowerBound (inclusive) and upperBound (exclusive)
Parameters
nbCols the number of columns in the vector
lowerBound lower bound for the range of random values
upperBound upper bound for the range of random values
Returns
a new nbRows x nbCols random matrix
Definition at line 53 of file RowVector.cpp.
References uriVL::RandomGenerator_C::nextDouble_st(), and RowVector().
 {
     RowVector *v = new RowVector(nbCols);
     for (int j = 0; j < nbCols; j++)
         v->mat_[0][j] = RandomGenerator_C::nextDouble_st(upperBound, lowerBound);
     return v;
 }
Matrix * RowVector::transposition (void) const virtual
Computes the transpose of this vector, which is a column vector.
Returns
the transpose of this row vector: a column vector
Reimplemented from uriVL::Matrix.
Definition at line 92 of file RowVector.cpp.
References ColumnVector, uriVL::Matrix::mat_, and uriVL::Matrix::nbCols_.
 {
     ColumnVector *colVect = new ColumnVector(nbCols_);
     for (int j=0; j<nbCols_; j++)
         colVect->mat_[j][0] = mat_[0][j];
     return colVect;
 }
Friends And Related Function Documentation
friend class ColumnVector friend
Definition at line 31 of file RowVector.h.
Referenced by transposition().
The documentation for this class was generated from the following files:
RowVector.h
RowVector.cpp