URIVisionLibrary: uriVL::ErrorReport Class Reference
uriVL::ErrorReport Class Reference
Implements the ErrorReport class.
#include <ErrorReport.h>
Public Member Functions
ErrorReport (ErrorCode theCode, const std::string &theMessage)
Creates a new ErrorCode object to throw.
~ErrorReport (void)
Destructor.
ErrorCode getCode (void) const
Returns this object's error code.
void appendToMessage (const std::string &addMsg)
Appends a string to the error message.
const char * getMessage (void) const
When you call this, you're responsible for delete[]'ing the returned pointer.
Private Attributes
ErrorCode code_
Code identifying the type of error encountered.
std::string message_
String giving the type of the error and its call sequence.
Detailed Description
Implements the ErrorReport class.
An ErrorReport is a form of exception. Instead of defining a class hierarchy for exceptions in the library, we have chosen the path of having a single class with an error code and an error string as instance variables.
Version history
2004/02/20 [jyh] first implementation.
2008/x/x [jyh] added appendToMessage
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 198 of file ErrorReport.h.
Constructor & Destructor Documentation
ErrorReport::ErrorReport (ErrorCode theCode, const std::string & theMessage)
Creates a new ErrorCode object to throw.
Parameters
theCode code identifying the type of error encountered
theMessage string with an error message
Definition at line 30 of file ErrorReport.cpp.
         :       code_(theCode),
         message_(theMessage)
 {
 }
ErrorReport::~ErrorReport (void)
Destructor.
Definition at line 37 of file ErrorReport.cpp.
 {
 }
Member Function Documentation
void ErrorReport::appendToMessage (const std::string & addMsg)
Appends a string to the error message.
Parameters
addMsg the string to add to the message
Definition at line 58 of file ErrorReport.cpp.
References message_.
Referenced by uriVL::MedianFilter_F::applyTo(), uriVL::MedianFilter_I::applyTo(), uriVL::ColorMedianFilter_F::applyTo(), uriVL::ColorMedianFilter_I::applyTo(), uriVL::Box3D::Box3D(), checkIfSearchStartPointIsValid_(), uriVL::DrawableObject2D::coincidesWith(), uriVL::ColorGaussianFilter::ColorGaussianFilter(), uriVL::Cone3D::Cone3D(), uriVL::DrawableObject2D::contains(), uriVL::LabelRaster::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::RasterImage::createCopy(), uriVL::Cylinder3D::Cylinder3D(), uriVL::FeatureDetector::FeatureDetector(), uriVL::BlobFinder::findAllBlobs(), SimpleFunctionND::func(), SimpleFunction1D::func(), uriVL::FunctionND::func(), uriVL::FunctionND_F::func(), uriVL::GaussianFilter::GaussianFilter(), uriVL::ImageReader::getFrame(), uriVL::FunctionND_F::gradient(), uriVL::FunctionND::gradient(), uriVL::HalfCone3D::HalfCone3D(), uriVL::HalfCylinder3D::HalfCylinder3D(), uriVL::FunctionND::hessian(), uriVL::ImageGradient_Gaussian_F::ImageGradient_Gaussian_F(), uriVL::DrawableObject2D::isContainedBy(), uriVL::FunctionND::isDefinedAt(), uriVL::LabelRaster::LabelRaster(), uriVL::NonlinearOptimizerND::minimize(), uriVL::BlobTrackingState::operator=(), uriVL::TrackingState::operator=(), uriVL::DrawableObject2D::overlaps(), uriVL::PolyMesh3D::PolyMesh3D(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::ImageReader::readImage(), uriVL::Blob::renderInto(), uriVL::ImageTransformation::rotate(), uriVL::ImageTransformation::scale(), uriVL::BackgroundRemover_dynamic::setBackground(), uriVL::BackgroundRemover_dynamic_MW::setBackground(), uriVL::BackgroundRemover_static::setBackground(), uriVL::TrackingState::setPos(), uriVL::FeatureDetector::setSearchRect(), uriVL::Transformation2D::Transformation2D(), uriVL::ImageTransformation::translate(), uriVL::ImageTransformation::translateInPlace(), uriVL::Vector2D_F::Vector2D_F(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), and uriVL::ImageWriter::writeImage().
 {
         message_ = message_ + "\r\t" + addMsg;
 }
ErrorCode ErrorReport::getCode (void) const
Returns this object's error code.
Returns
this object's error code
Definition at line 41 of file ErrorReport.cpp.
References code_.
 {
     return code_;
 }
const char * ErrorReport::getMessage (void) const
When you call this, you're responsible for delete[]'ing the returned pointer.
Returns
a const C-style error string with an error message
Definition at line 46 of file ErrorReport.cpp.
References message_.
Referenced by main().
 {
     // Some day this should probably just return a "const string&" that refers
     // to this->message_.  Until then though, keep a good "const char*"
     // interface.
     char        *theMessage = new char[message_.length() + 1];
     strcpy(theMessage, message_.c_str());
     return theMessage;
 }
Member Data Documentation
ErrorCode uriVL::ErrorReport::code_ private
Code identifying the type of error encountered.
Definition at line 233 of file ErrorReport.h.
Referenced by getCode().
std::string uriVL::ErrorReport::message_ private
String giving the type of the error and its call sequence.
Definition at line 237 of file ErrorReport.h.
Referenced by appendToMessage(), and getMessage().
The documentation for this class was generated from the following files:
ErrorReport.h
ErrorReport.cpp