URIVisionLibrary: uriVL::RasterImage_RGBa_F Class Reference
uriVL::RasterImage_RGBa_F Class Reference
RasterImage_RGBa_F class.
#include <RasterImage_RGBa_F.h>
Public Member Functions
RasterImage_RGBa_F (int nbRows, int nbCols)
Allocates a float RGBa color raster image at the dimensions specified.
RasterImage_RGBa_F (int nbRows, int nbCols, const unsigned char *theRGBa)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
RasterImage_RGBa_F (int nbRows, int nbCols, const float *theRed, const float *theGreen, const float *theBlue)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
RasterImage_RGBa_F (const ImageRect *theRect)
Allocates a float RGBa color raster image at the specified dimensions.
RasterImage_RGBa_F (const ImageRect *theRect, const unsigned char *theRGBa)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
RasterImage_RGBa_F (const ImageRect *theRect, const float *theRed, const float *theGreen, const float *theBlue)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
RasterImage_RGBa_F (const GraphWorld *gworld)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the GraphWorld object received as parameter.
RasterImage_RGBa_F (GraphWorld *gworld, bool keepThisGraphWorld)
Assigns to this raster image object the GraphWorld object received as parameter.
RasterImage_RGBa_F (const RasterImage *img)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
RasterImage_RGBa_F (const RasterImage *img, const ImageRect *theRect)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
~RasterImage_RGBa_F (void)
Destructor.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
const unsigned char * getRGBa (void) const
Returns the 32-bit rgba base raster as a read-only 1D array.
unsigned char * getRGBa (ReadWriteStatus rw)
Returns the 32-bit rgba base raster as a read-write 1D array.
const unsigned char *const * getRGBa2D (void) const
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
unsigned char *const * getRGBa2D (ReadWriteStatus rw)
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
const unsigned char *const * getShiftedRGBa2D () const
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
unsigned char *const * getShiftedRGBa2D (ReadWriteStatus rw)
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
const float * getRedF (void) const
Returns the base address of this objet's private 1D raster for the red channel.
float * getRedF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the red channel.
const float * getGreenF (void) const
Returns the base address of this objet's private 1D raster for the red channel.
float * getGreenF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the red channel.
const float * getBlueF (void) const
Returns the base address of this objet's private 1D raster for the blue channel.
float * getBlueF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the blue channel.
const float *const * getRedF2D (void) const
Returns the base address of this objet's private 2D raster for the red channel.
float *const * getRedF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 2D raster for the red channel.
const float *const * getGreenF2D (void) const
Returns the base address of this objet's private 1D raster for the green channel.
float *const * getGreenF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the green channel.
const float *const * getBlueF2D (void) const
Returns the base address of this objet's private 2D raster for the blue channel.
float *const * getBlueF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 2D raster for the blue channel.
const float *const * getShiftedRedF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the red channel.
float *const * getShiftedRedF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the red channel.
const float *const * getShiftedGreenF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the green channel.
float *const * getShiftedGreenF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the green channel.
const float *const * getShiftedBlueF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the blue channel.
float *const * getShiftedBlueF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the blue channel.
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets an individual conversion mode from float to gray for this image.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image's conversion mode from float to gray.
Public Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
RasterImage_RGBa (const ImageRect *theRect)
Allocates a 32-bit RGBa color raster image at the specified dimensions.
RasterImage_RGBa (int nbRows, int nbCols, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const ImageRect *theRect, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (GraphWorld *gworld, bool keepThisGraphWorld=false)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img)
Initializes an rgba raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img, const ImageRect *theRect)
Initializes an rgba raster image at the specified dimensions and values.
virtual ~RasterImage_RGBa (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void setDefaultFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode from float to gray for this class.
static void convertToGray (const float *redSource, const float *greenSource, const float *blueSource, unsigned char *theDestination, long nbPixels, const float convWeight[], ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
static void convertToGray (const float *redSource, const float *greenSource, const float *blueSource, float *theDestination, long nbPixels, const float convWeight[], ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
Static Public Member Functions inherited from uriVL::RasterImage_RGBa
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Copies a 1D RGBa32 raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 16-bit aRGB16 raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, bool *localRGBa)
Allocates a read-only RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Private Member Functions
RasterImage_RGBa_F (void)
Creates an undimensioned RGBa float color raster image.
RasterImage_RGBa_F (const RasterImage_RGBa_F &img)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
const RasterImage_RGBa_F & operator= (const RasterImage_RGBa_F &img)
This operator has not been implemented.
void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void allocateRaster_ (void)
Allocates the object's private rasters.
void deleteRaster_ (void)
Deletes the object's private rasters.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
void updateRaster_ (void) const
Updates the image's base raster (if it is not the reference).
void calculateFloatConversionParams_ (void) const
Calculates the parameters of a conversion to (unsigned char) RGBa.
Static Private Member Functions
static void convertToGray_ (const float *redSource, const float *greenSource, const float *blueSource, unsigned char *theDestination, long nbPixels, float valMin, float convScale, ConversionToGrayMode myGrayConv=kAverageConversion, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D float RGB raster into a 1D gray-level raster.
static void convertToGray_ (const float *redSource, const float *greenSource, const float *blueSource, float *theDestination, long nbPixels, float valMin, float convScale, ConversionToGrayMode myGrayConv=kAverageConversion, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D float RGB raster into a 1D float gray-level raster.
static void convertToRGBa_ (const float *redSource, const float *greenSource, const float *blueSource, unsigned char *theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D float RGB raster into a 1D 32-bit rgba raster.
static void convertToRGB_ (const float *redSource, const float *greenSource, const float *blueSource, unsigned char *theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D float RGB raster into a 1D 24-bit rgb raster.
static void convertToARGB16_ (const float *redSource, const float *greenSource, const float *blueSource, unsigned char *theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts a 1D float RGB raster into a 1D 16-bit argb raster.
Private Attributes
float * red_
private 1D raster for the red channel
float * green_
private 1D raster for the green channel
float * blue_
private 1D raster for the blue channel
float ** red2D_
private 2D raster for the red channel
float ** green2D_
private 2D raster for the green channel
float ** blue2D_
private 2D raster for the blue channel
float ** shiftedRed2D_
private shifted 2D raster for the red channel
float ** shiftedGreen2D_
private shifted 2D raster for the green channel
float ** shiftedBlue2D_
private shifted 2D raster for the blue channel
bool hasIndivFloatConvMode_
True if an algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
ConversionFromFloatMode floatConv_
Code for the algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
float convScale_
Scale factor to apply in a float to gray conversion.
float convScaleRed_
Scale factor to apply in a float to red conversion.
float convScaleGreen_
Scale factor to apply in a float to green conversion.
float convScaleBlue_
Scale factor to apply in a float to blue conversion.
float valMin_
Minimum value over the raster (r-g-b combined)
float valMax_
Minimum value over the raster (r-g-b combined)
float valMinRed_
Minimum value over the red raster.
float valMaxRed_
Maximum value over the red raster.
float valMinGreen_
Minimum value over the green raster.
float valMaxGreen_
Maximum value over the green raster.
float valMinBlue_
Minimum value over the blue raster.
float valMaxBlue_
Maximum value over the blue raster.
Static Private Attributes
static ConversionFromFloatMode defaultFloatConv_ = kSaturatedPositive
Code for the default algorithm for conversion from float to gray.
Friends
class RasterImage_RGBa
Additional Inherited Members
Protected Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (void)
Protected default constructor.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Detailed Description
RasterImage_RGBa_F class.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 30 of file RasterImage_RGBa_F.h.
Constructor & Destructor Documentation
RasterImage_RGBa_F::RasterImage_RGBa_F (int nbRows, int nbCols)
Allocates a float RGBa color raster image at the dimensions specified.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster to zero values (black). Row and column indices of the new raster start at 0
Parameters
nbRows number of rows of the raster
nbCols number of columns of the raster
Definition at line 69 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::RasterImage::setFloatRasterAsReference_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(nbRows, nbCols),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
         //
     setFloatRasterAsReference_();
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (int nbRows, int nbCols, const unsigned char * theRGBa)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster using the values stored in the 1D raster received as parameter.
Parameters
nbRows number of rows of the raster
nbCols number of columns of the raster
theRGBa 1D RGBa raster (4 bytes/pixel) to unitialize the new raster image with
Definition at line 111 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), and allocateShiftedRaster2D_().
                         :       RasterImage_RGBa(nbRows, nbCols, theRGBa),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kPositiveFloat),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (int nbRows, int nbCols, const float * theRed, const float * theGreen, const float * theBlue)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster using the values stored in the 1D raster received as parameter.
Parameters
nbRows number of rows of the raster
nbCols number of columns of the raster
theRed 1D raster (1 bytes/pixel) to unitialize the new image's red channel with
theGreen 1D raster (1 bytes/pixel) to unitialize the new image's green channel with
theBlue 1D raster (1 bytes/pixel) to unitialize the new image's blue channel with
Definition at line 150 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), blue2D_, green2D_, red2D_, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and uriVL::DrawableObject2D::setValidRect().
                         :       RasterImage_RGBa(nbRows, nbCols),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     long lSource = 0;
     for (int i=0; i<nbRows; i++) {
         for (int j=0; j<nbCols; j++)
         {
             red2D_[i][j] = theRed[lSource];
             green2D_[i][j] = theGreen[lSource];
             blue2D_[i][j] = theBlue[lSource];
         }
         }
         setValidRect(0, 0, nbCols, nbRows);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const ImageRect * theRect)
Allocates a float RGBa color raster image at the specified dimensions.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 204 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::RasterImage::setGraphWorldAsReference_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(theRect),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
     setGraphWorldAsReference_();
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const ImageRect * theRect, const unsigned char * theRGBa)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster using the values stored in the 1D raster received as parameter.
Parameters
theRect ImageRect specifying the image's bounding rectangle
theRGBa 1D RGBa raster (4 bytes/pixel) to unitialize the new raster image with
Definition at line 248 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), and uriVL::RasterImage::setHasFloatRaster_().
                         :       RasterImage_RGBa(theRect, theRGBa),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
 //    const int   iLow = theRect->getTop(),
 //                      iHigh = theRect->getBottom(),
 //                      jLow = theRect->getLeft(),
 //                      jHigh = theRect->getRight();
 //      allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
 //      try {
 //              long lSource = 0;
 //              for (int i=iLow; i<=iHigh; i++)
 //                      for (int j=jLow; j<=jHigh; j++)
 //                      {
 //                              red2D_[i][j] = theRed[lSource];
 //                              green2D_[i][j] = theGreen[lSource];
 //                              blue2D_[i][j] = theBlue[lSource];
 //                      }
 //      }
 //      catch(...) {
 //              FAIL_CONDITION( true,
 //                                              kMemoryCopyError,
 //                                              "Data copy error in RasterImage_RGBa_F constructor");
 //      }
 //      setValidRect(theRect);
     setHasFloatRaster_(true);
 //    setFloatRasterAsReference_();
 //    setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const ImageRect * theRect, const float * theRed, const float * theGreen, const float * theBlue)
Allocates a float RGBa color raster image at the specified dimensions and initializes it.
Allocates a float RGBa color raster at the specified dimensions and initializes this raster using the values stored in the 1D raster received as parameter.
Parameters
theRect ImageRect specifying the image's bounding rectangle
theRed 1D raster (1 bytes/pixel) to unitialize the new image's red channel with
theGreen 1D raster (1 bytes/pixel) to unitialize the new image's green channel with
theBlue 1D raster (1 bytes/pixel) to unitialize the new image's blue channel with
Definition at line 316 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), blue2D_, FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::getWidth(), green2D_, uriVL::kMemoryCopyError, uriVL::kNullRasterError, red2D_, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setHasFloatRaster_(), uriVL::RasterImage::setReferenceHasChanged_(), and uriVL::DrawableObject2D::setValidRect().
                         :       RasterImage_RGBa(theRect),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( theRed == NULL,
                     kNullRasterError,
                     "null raster as parameter in RasterImage_RGBa_F constructor");
     FAIL_CONDITION( theGreen == NULL,
                     kNullRasterError,
                     "null raster as parameter in RasterImage_RGBa_F constructor");
     FAIL_CONDITION( theBlue == NULL,
                     kNullRasterError,
                     "null raster as parameter in RasterImage_RGBa_F constructor");
 //      allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
         const ImageRect* validRect = getValidRect();
     const int   iLow = validRect->getTop(),
                 iHigh = validRect->getBottom(),
                 jLow = validRect->getLeft(),
                 jHigh = validRect->getRight();
         try {
                 long lSource = 0;
                 for (int i=iLow; i<=iHigh; i++)
                         for (int j=jLow; j<=jHigh; j++)
{
                                 red2D_[i][j] = theRed[lSource];
                                 green2D_[i][j] = theGreen[lSource];
                                 blue2D_[i][j] = theBlue[lSource];
                         }
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "Data copy error in RasterImage_RGBa_F constructor");
         }
         setValidRect(theRect);
     setHasFloatRaster_(true);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const GraphWorld * gworld)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the GraphWorld object received as parameter.
Parameters
gworld The GraphWolrd to initialize this image with
Definition at line 397 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, and uriVL::kRasterImageError.
                         :       RasterImage_RGBa(),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( true, kRasterImageError,
                     "RasterImage_RGBa_F GraphWorld clone constructor is not operative yet");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (GraphWorld * gworld, bool keepThisGraphWorld)
Assigns to this raster image object the GraphWorld object received as parameter.
There is no copying of the data here, only of the address.
Parameters
gworld The GraphWolrd to initialize this image with
Definition at line 436 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, and uriVL::kRasterImageError.
                         :       RasterImage_RGBa(),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( true, kRasterImageError,
                     "RasterImage_RGBa_F GraphWorld clone constructor is not operative yet");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const RasterImage * img)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
If the image is not of type RGBa32, does a conversion.
Parameters
img The raster image to initialize this image with
Definition at line 475 of file RasterImage_RGBa_F.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setHasFloatRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(img),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGBa_F constructor");
     //  Although technically the float raster does not exist yet,
     //  we do this to force the writing to take place in the float
     //  raster rather than in the GraphWorld.
     setHasFloatRaster_(true);
         try {
                 img->copyInto(this, img->getValidRect());
         }
         catch(ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa_F constructor");
                 throw e;
         }
     setHasFloatRaster_(true);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const RasterImage * img, const ImageRect * theRect)
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
If the image is not of type RGBa32, does a conversion.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 533 of file RasterImage_RGBa_F.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::RasterImage::setHasFloatRaster_().
                         :       RasterImage_RGBa(img, theRect),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kPositiveFloat),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGBa_F constructor");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in RasterImage_RGBa_F constructor");
     //  Although technically the float raster does not exist yet,
     //  we do this to force the writing to take place in the float
     //  raster rather than in the GraphWorld.
     setHasFloatRaster_(true);
         try {
                 img->copyInto(this, theRect);
         }
         catch(ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa_F constructor");
                 throw e;
         }
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
RasterImage_RGBa_F::~RasterImage_RGBa_F (void)
Destructor.
Definition at line 632 of file RasterImage_RGBa_F.cpp.
References deleteRaster2D_(), deleteShiftedRaster2D_(), and uriVL::DrawableObject2D::getTop().
 {
     deleteShiftedRaster2D_(getTop());
     deleteRaster2D_();
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (void) private
Creates an undimensioned RGBa float color raster image.
Definition at line 37 of file RasterImage_RGBa_F.cpp.
                         :       RasterImage_RGBa(),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
 }
RasterImage_RGBa_F::RasterImage_RGBa_F (const RasterImage_RGBa_F & img) private
Allocates a float RGBa color raster image at the dimensions and with the values specified by the RasterImage object received as parameter.
If the image is not of type RGBa32, does a conversion. This copy contructor is not operative, and was only declared to eliminate compiler warnings.
Parameters
img The raster image to initialize this image with
Definition at line 591 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       RasterImage_RGBa(),
                                 //
                                 red_(NULL),
                                 green_(NULL),
                                 blue_(NULL),
                                 red2D_(NULL),
                                 green2D_(NULL),
                                 blue2D_(NULL),
                                 shiftedRed2D_(NULL),
                                 shiftedGreen2D_(NULL),
                                 shiftedBlue2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kPositiveFloat),
                                 //
                                 convScale_(1.f),
                                 convScaleRed_(1.f),
                                 convScaleGreen_(1.f),
                                 convScaleBlue_(1.f),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 valMinRed_(+HUGE_VALF),
                                 valMaxRed_(-HUGE_VALF),
                                 valMinGreen_(+HUGE_VALF),
                                 valMaxGreen_(-HUGE_VALF),
                                 valMinBlue_(+HUGE_VALF),
                                 valMaxBlue_(-HUGE_VALF)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "copy consyructor not implemented in RasterImage_RGBa_F");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa_F constructor");
         throw e;
 }
Member Function Documentation
void RasterImage_RGBa_F::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 1904 of file RasterImage_RGBa_F.cpp.
References blue2D_, blue_, FAIL_CONDITION, green2D_, green_, uriVL::kRasterAllocationFailure, red2D_, red_, and uriVL::RasterImage::setHasFloatRaster_().
Referenced by RasterImage_RGBa_F(), and setBoundRect_().
 {
     red_ = new float[nbRows*nbCols];
     FAIL_CONDITION(red_ == NULL, kRasterAllocationFailure,
                    "Could not allocate red_ array");
     green_ = new float[nbRows*nbCols];
     FAIL_CONDITION(green_ == NULL, kRasterAllocationFailure,
                    "Could not allocate green_ array");
     blue_ = new float[nbRows*nbCols];
     FAIL_CONDITION(blue_ == NULL, kRasterAllocationFailure,
                    "Could not allocate blue_ array");
     red2D_ = new float*[nbRows];
     FAIL_CONDITION(red2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate red2D_ array");
     green2D_ = new float*[nbRows];
     FAIL_CONDITION(green2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate green2D_ array");
     blue2D_ = new float*[nbRows];
     FAIL_CONDITION(blue2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate blue2D_ array");
     red2D_[0] = red_;
     green2D_[0] = green_;
     blue2D_[0] = blue_;
     for (int i=1; i<nbRows; i++){
         red2D_[i] = red2D_[i-1] + nbCols;
         green2D_[i] = green2D_[i-1] + nbCols;
         blue2D_[i] = blue2D_[i-1] + nbCols;
     }
     setHasFloatRaster_(true);
 }
void uriVL::RasterImage_RGBa_F::allocateRaster_ (void) private
Allocates the object's private rasters.
void RasterImage_RGBa_F::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 1959 of file RasterImage_RGBa_F.cpp.
References deleteShiftedRaster2D_(), FAIL_CONDITION, getBlueF(), getGreenF(), uriVL::DrawableObject2D::getLeft(), getRedF(), uriVL::DrawableObject2D::getTop(), uriVL::kRasterAllocationFailure, uriVL::R_W_ACCESS, shiftedBlue2D_, shiftedGreen2D_, and shiftedRed2D_.
Referenced by RasterImage_RGBa_F(), and setBoundRect_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
     {
         const int   iHigh = iLow + nbRows - 1;
         deleteShiftedRaster2D_(iLow);
         shiftedRed2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedRed2D_ == NULL,
                         kRasterAllocationFailure,
                         "shiftedRed2D_ allocation failed");
         shiftedGreen2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedGreen2D_ == NULL,
                         kRasterAllocationFailure,
                         "shiftedGreen2D_ allocation failed");
         shiftedBlue2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedBlue2D_ == NULL,
                         kRasterAllocationFailure,
                         "shiftedBlue2D_ allocation failed");
         shiftedRed2D_ -= iLow;
         shiftedGreen2D_ -= iLow;
         shiftedBlue2D_ -= iLow;
         //
         shiftedRed2D_[iLow] = getRedF(R_W_ACCESS) - jLow;
         shiftedGreen2D_[iLow] = getGreenF(R_W_ACCESS) - jLow;
         shiftedBlue2D_[iLow] = getBlueF(R_W_ACCESS) - jLow;
         for (int i = iLow; i < iHigh; i++){
             shiftedRed2D_[i+1] = shiftedRed2D_[i] + nbCols;
             shiftedGreen2D_[i+1] = shiftedGreen2D_[i] + nbCols;
             shiftedBlue2D_[i+1] = shiftedBlue2D_[i] + nbCols;
         }
     }
     else{
         shiftedRed2D_ = NULL;
         shiftedGreen2D_ = NULL;
         shiftedBlue2D_ = NULL;
     }
 }
void RasterImage_RGBa_F::calculateFloatConversionParams_ (void) const private
Calculates the parameters of a conversion to (unsigned char) RGBa.
Definition at line 1305 of file RasterImage_RGBa_F.cpp.
References blue2D_, convScale_, defaultFloatConv_, floatConv_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), getShiftedBlueF2D(), getShiftedGreenF2D(), getShiftedRedF2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), green2D_, hasIndivFloatConvMode_, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kSignedFloat, red2D_, shiftedBlue2D_, shiftedGreen2D_, shiftedRed2D_, valMax_, and valMin_.
Referenced by updateRaster_(), and writeInto_().
 {
         const ImageRect* validRect = getValidRect();
     const int iLow = validRect->getTop(),
               iHigh = validRect->getBottom(),
               jLow = validRect->getLeft(),
               jHigh = validRect->getRight();
     const float* const* redSource = getShiftedRedF2D();
     const float* const* greenSource = getShiftedGreenF2D();
     const float* const* blueSource = getShiftedBlueF2D();
     if ((getTop()==0) && (getLeft()==0))
     {
         redSource = red2D_;
         greenSource = green2D_;
         blueSource = blue2D_;
     }
     else
     {
         redSource = shiftedRed2D_;
         greenSource = shiftedGreen2D_;
         blueSource = shiftedBlue2D_;
     }
     ConversionFromFloatMode convType;
     if (hasIndivFloatConvMode_)
         convType = floatConv_;
     else
         convType = defaultFloatConv_;
     valMin_ = valMax_ = redSource[iLow][jLow];
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
             if (redSource[i][j] > valMax_)
                 valMax_ = redSource[i][j];
             else if (redSource[i][j] < valMin_)
                 valMin_ = redSource[i][j];
             if (greenSource[i][j] > valMax_)
                 valMax_ = greenSource[i][j];
             else if (greenSource[i][j] < valMin_)
                 valMin_ = greenSource[i][j];
             if (blueSource[i][j] > valMax_)
                 valMax_ = blueSource[i][j];
             else if (blueSource[i][j] < valMin_)
                 valMin_ = blueSource[i][j];
         }
     switch (convType)
     {
             // We don't care about the MIN, simply rescale the MAX to 255
         case kPositiveFloat:
             valMin_ = 0.f;
             convScale_ = 255.0f/valMax_;
             break;
             //  We rescale to 0 255, with 0 at 128
         case kSignedFloat:
             if (valMax_ > -valMin_)
                 valMin_ = -valMax_;
             else
                 valMax_ = -valMin_;
             convScale_ = 127.5f/valMax_;
             break;
         case kRangeFloat:
             convScale_ = 255.f/(valMax_ - valMin_);
             break;
         default:
             break;
     }
 }
void RasterImage_RGBa_F::convertToARGB16_ (const float * redSource, const float * greenSource, const float * blueSource, unsigned char * theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts a 1D float RGB raster into a 1D 16-bit argb raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myFloatConv the conversion mode from float desired
Definition at line 1605 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
static void uriVL::RasterImage_RGBa_F::convertToGray (const float * redSource, const float * greenSource, const float * blueSource, unsigned char * theDestination, long nbPixels, const float convWeight[], ConversionFromFloatMode myFloatConv = kUndefFloatConv) static
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
myFloatConv the conversion mode from float desired
static void uriVL::RasterImage_RGBa_F::convertToGray (const float * redSource, const float * greenSource, const float * blueSource, float * theDestination, long nbPixels, const float convWeight[], ConversionFromFloatMode myFloatConv = kUndefFloatConv) static
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
myFloatConv the conversion mode from float desired
void RasterImage_RGBa_F::convertToGray_ (const float * redSource, const float * greenSource, const float * blueSource, unsigned char * theDestination, long nbPixels, float valMin, float convScale, ConversionToGrayMode myGrayConv = kAverageConversion, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts a 1D float RGB raster into a 1D gray-level raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myGrayConv the gray conversion mode desired
myFloatConv the conversion mode from float desired
Definition at line 1625 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getDefaultConversionWeights(), uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kSaturatedPositive, uriVL::kSaturatedSigned, uriVL::kSignedFloat, uriVL::kWeightedAverageConversion, and MAX.
Referenced by writeInto_().
 {
     const float div3 = 1.f/3.f;
     float   sum;
     float   val;
     const float* redIn = sourceRed,
                 *greenIn = sourceGreen,
                 *blueIn = sourceBlue;
     unsigned char* dest = theDestination;
         const float* convWeight = getDefaultConversionWeights();
     //  How do we convert from float to unsigned char?
     switch (myFloatConv)
     {
         case kSignedFloat:
         case kPositiveFloat:
         case kRangeFloat:
 //            calculateFloatConversionParams_( );
             //  How do we convert from RGBa to gray?
             switch (myGrayConv)
             {
                 case kMaxFieldConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         //  optimization "in the small" left for a more clever programmer
                         float   red = *(redIn++),
                                 green = *(greenIn++),
                                 blue = *(blueIn++);
                         val = MAX(red, MAX(green, blue));
                         *(dest++) = static_cast<unsigned char>(convScale*(val-valMin));
                     }
                     break;
                 case kAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         sum = *(redIn++) + *(greenIn++) + *(blueIn++);
                         val = sum * div3;
                         *(dest++) = static_cast<unsigned char>(convScale*(val-valMin));
                     }
                     break;
                 case kWeightedAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         val = convWeight[0] ** (redIn++) +
                               convWeight[1] ** (greenIn++) +
                               convWeight[2] ** (blueIn++);
                         *(dest++) = static_cast<unsigned char>(convScale*(val - valMin));
                     }
                     break;
                 default:
                     FAIL_CONDITION( true, kRasterImageError,
                                     "unknown conversion to gray mode encountered");
                     break;
             }
             break;
         case kSaturatedPositive:
             //  How do we convert from RGBa to gray?
             switch (myGrayConv)
             {
                 case kMaxFieldConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         //  optimization "in the small" left for a more clever programmer
                         float   red = *(redIn++),
                                 green = *(greenIn++),
                                 blue = *(blueIn++);
                         val = MAX(red, MAX(green, blue));
                         if (val >= 0.f)
                             if (val <= 255.f)
                                 *(dest++) = static_cast<unsigned char>(val);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 case kAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         sum = *(redIn++) + *(greenIn++) + *(blueIn++);
                         val = sum * div3;
                         if (val >= 0.f)
                             if (val <= 255.f)
                                 *(dest++) = static_cast<unsigned char>(val);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 case kWeightedAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         val = convWeight[0] ** (redIn++) +
                               convWeight[1] ** (greenIn++) +
                               convWeight[2] ** (blueIn++);
                         if (val >= 0.f)
                             if (val <= 255.f)
                                 *(dest++) = static_cast<unsigned char>(val);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 default:
                     FAIL_CONDITION( true, kRasterImageError,
                                     "unknown conversion to gray mode encountered");
                     break;
             }
             break;
         case kSaturatedSigned:
             //  How do we convert from RGBa to gray?
             switch (myGrayConv)
             {
                 case kMaxFieldConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         //  optimization "in the small" left for a more clever programmer
                         float   red = *(redIn++),
                                 green = *(greenIn++),
                                 blue = *(blueIn++);
                         val = MAX(red, MAX(green, blue));
                         if (val >= -128.f)
                             if (val <= 127.f)
                                 *(dest++) = static_cast<unsigned char>(val + 128);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 case kAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         sum = *(redIn++) + *(greenIn++) + *(blueIn++);
                         val = sum * div3;
                         if (val >= -128.f)
                             if (val <= 127.f)
                                 *(dest++) = static_cast<unsigned char>(val + 128);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 case kWeightedAverageConversion:
                     for (long j=0; j<nbPixels; j++)
                     {
                         val = convWeight[0] ** (redIn++) +
                               convWeight[1] ** (greenIn++) +
                               convWeight[2] ** (blueIn++);
                          if (val >= -128.f)
                             if (val <= 127.f)
                                 *(dest++) = static_cast<unsigned char>(val + 128);
                             else
                                 *(dest++) = static_cast<unsigned char>(255);
                         else
                             *(dest++) = static_cast<unsigned char>(0);
                     }
                     break;
                 default:
                     FAIL_CONDITION( true, kRasterImageError,
                                     "unknown conversion to gray mode encountered");
                     break;
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Unknown float to gray conversion mode");
             break;
     }
 }
void RasterImage_RGBa_F::convertToGray_ (const float * redSource, const float * greenSource, const float * blueSource, float * theDestination, long nbPixels, float valMin, float convScale, ConversionToGrayMode myGrayConv = kAverageConversion, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts a 1D float RGB raster into a 1D float gray-level raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myGrayConv the gray conversion mode desired
myFloatConv the conversion mode from float desired
Definition at line 1833 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getDefaultConversionWeights(), uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kRasterImageError, uriVL::kWeightedAverageConversion, and MAX.
 {
     const float div3 = 1.f/3.f;
     const float* redIn = sourceRed,
                 *greenIn = sourceGreen,
                 *blueIn = sourceBlue;
     float   *dest = theDestination;
         const float* convWeight = getDefaultConversionWeights();
     float   sum;
     //  how do we convert from rgb to gray?
     switch (myGrayConv)
     {
         case kMaxFieldConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 //  optimization "in the small" left for a more clever programmer
                 float   red = *(redIn++),
                         green = *(greenIn++),
                         blue = *(blueIn++);
                 *(dest++) = MAX(red, MAX(green, blue));
             }
             break;
         case kAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = *(redIn++) + *(greenIn++) + *(blueIn++);
                 *(dest++) = sum * div3;
             }
             break;
         case kWeightedAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 *(dest++) = convWeight[0] ** (redIn++) +
                             convWeight[1] ** (greenIn++) +
                             convWeight[2] ** (blueIn++);
             }
             break;
         default:
             FAIL_CONDITION( true, kRasterImageError,
                             "unknown conversion to gray mode encountered");
             break;
     }
 }
void RasterImage_RGBa_F::convertToRGB_ (const float * redSource, const float * greenSource, const float * blueSource, unsigned char * theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts a 1D float RGB raster into a 1D 24-bit rgb raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myFloatConv the conversion mode from float desired
Definition at line 1497 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kSaturatedPositive, uriVL::kSaturatedSigned, and uriVL::kSignedFloat.
 {
     const float     *redIn = redSource,
                     *greenIn = greenSource,
                     *blueIn = blueSource;
     unsigned char   *rgbOut = theDestination;
     switch (myFloatConv)
     {
         case kSignedFloat:
         case kPositiveFloat:
         case kRangeFloat:
 //            calculateFloatConversionParams_( );
             for (long l=0; l<nbPixels; l++)
             {
                 *(rgbOut++) = static_cast<unsigned char>(convScale*(*(redIn++)-valMin));
                 *(rgbOut++) = static_cast<unsigned char>
                                     (convScale*(*(greenIn++)-valMin));
                 *(rgbOut++) = static_cast<unsigned char>(convScale*(*(blueIn++)-valMin));
             }
             break;
         case kSaturatedPositive:
             for (long l=0; l<nbPixels; l++)
             {
                 //  Red channel
                 float val = *(redIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
                 //  Green channel
                 val = *(greenIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
                 //  Blue channel
                 val = *(blueIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
             }
             break;
         case kSaturatedSigned:
             for (long l=0; l<nbPixels; l++)
             {
                 //  Red channel
                 float val = *(redIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
                 //  Green channel
                 val = *(greenIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
                 //  Blue channel
                 val = *(blueIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbOut++) = static_cast<unsigned char>(0);
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Unknown float to gray conversion mode");
             break;
     }
 }
void RasterImage_RGBa_F::convertToRGBa_ (const float * redSource, const float * greenSource, const float * blueSource, unsigned char * theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts a 1D float RGB raster into a 1D 32-bit rgba raster.
Parameters
redSource starting point of the red raster to convert
greenSource starting point of the green raster to convert
blueSource starting point of the blue raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myFloatConv the conversion mode from float desired
Definition at line 1384 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kSaturatedPositive, uriVL::kSaturatedSigned, and uriVL::kSignedFloat.
Referenced by updateRaster_(), and writeInto_().
 {
     const float     *redIn = redSource,
                     *greenIn = greenSource,
                     *blueIn = blueSource;
     unsigned char   *rgbaOut = theDestination;
     switch (myFloatConv)
     {
         case kSignedFloat:
         case kPositiveFloat:
         case kRangeFloat:
 //            calculateFloatConversionParams_( );
             for (long l=0; l<nbPixels; l++)
             {
                 *(rgbaOut++) = static_cast<unsigned char>(convScale*(*(redIn++)-valMin));
                 *(rgbaOut++) = static_cast<unsigned char>(convScale*(*(greenIn++)-valMin));
                 *(rgbaOut++) = static_cast<unsigned char>(convScale*(*(blueIn++)-valMin));
                 *(rgbaOut++) = static_cast<unsigned char>(255);
             }
             break;
         case kSaturatedPositive:
             for (long l=0; l<nbPixels; l++)
             {
                 //  Red channel
                 float val = *(redIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Green channel
                 val = *(greenIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Blue channel
                 val = *(blueIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Alpha channel
                 *(rgbaOut++) = static_cast<unsigned char>(255);
             }
             break;
         case kSaturatedSigned:
             for (long l=0; l<nbPixels; l++)
             {
                 //  Red channel
                 float val = *(redIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Green channel
                 val = *(greenIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Blue channel
                 val = *(blueIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(rgbaOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(rgbaOut++) = static_cast<unsigned char>(255);
                 else
                     *(rgbaOut++) = static_cast<unsigned char>(0);
                 //  Alpha channel
                 *(rgbaOut++) = static_cast<unsigned char>(255);
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Unknown float to gray conversion mode");
             break;
     }
 }
void RasterImage_RGBa_F::copyInto (RasterImage * imgOut) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 654 of file RasterImage_RGBa_F.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by copyInto().
 {
     copyInto(imgOut, getValidRect(), NULL);
 }
void RasterImage_RGBa_F::copyInto (RasterImage * imgOut, const ImageRect * theRect) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab).
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 660 of file RasterImage_RGBa_F.cpp.
References copyInto().
 {
     copyInto(imgOut, theRect, NULL);
 }
void RasterImage_RGBa_F::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 666 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::RasterImage::floatRasterIsReference(), and writeInto_().
 {
     //  If this image's float raster is not the reference, what we are
     //  trying to copy is just a "normal" RGBa level image.
     if (!floatRasterIsReference())
         RasterImage_RGBa::copyInto(imgOut, theRect, origin);
         //      If the float raster is the reference, then we use this class's copy mechanism
     else
     {
         //  All the rectangle testing and resizing is done in the parent class's function
         RasterImage::copyInto_(imgOut, theRect, origin);
         writeInto_(imgOut, theRect, origin);
     }
 }
void RasterImage_RGBa_F::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 1939 of file RasterImage_RGBa_F.cpp.
References blue2D_, blue_, green2D_, green_, red2D_, red_, and uriVL::RasterImage::setHasFloatRaster_().
Referenced by setBoundRect_(), and ~RasterImage_RGBa_F().
 {
     if(red_ != NULL)
         delete []red_;
     if(green_ != NULL)
         delete []green_;
     if(blue_ != NULL)
         delete []blue_;
     if(red2D_ != NULL)
         delete []red2D_;
     if(green2D_ != NULL)
         delete []green2D_;
     if(blue2D_ != NULL)
         delete []blue2D_;
     setHasFloatRaster_(false);
 }
void uriVL::RasterImage_RGBa_F::deleteRaster_ (void) private
Deletes the object's private rasters.
void RasterImage_RGBa_F::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 2003 of file RasterImage_RGBa_F.cpp.
References shiftedBlue2D_, shiftedGreen2D_, and shiftedRed2D_.
Referenced by allocateShiftedRaster2D_(), setBoundRect_(), and ~RasterImage_RGBa_F().
 {
     //  delete the shifted float raster s
     if (shiftedRed2D_ != NULL)
     {
         shiftedRed2D_ += iLow;
         delete []shiftedRed2D_;
         shiftedRed2D_ = NULL;
     }
     if (shiftedGreen2D_ != NULL)
     {
         shiftedGreen2D_ += iLow;
         delete []shiftedGreen2D_;
         shiftedGreen2D_ = NULL;
     }
     if (shiftedBlue2D_ != NULL)
     {
         shiftedBlue2D_ += iLow;
         delete []shiftedBlue2D_;
         shiftedBlue2D_ = NULL;
     }
 }
const float * RasterImage_RGBa_F::getBlueF (void) const
Returns the base address of this objet's private 1D raster for the blue channel.
Definition at line 1017 of file RasterImage_RGBa_F.cpp.
References blue_.
Referenced by allocateShiftedRaster2D_().
 {
     return blue_;
 }
float * RasterImage_RGBa_F::getBlueF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the blue channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1022 of file RasterImage_RGBa_F.cpp.
References blue_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return blue_;
 }
const float *const * RasterImage_RGBa_F::getBlueF2D (void) const
Returns the base address of this objet's private 2D raster for the blue channel.
Definition at line 1074 of file RasterImage_RGBa_F.cpp.
References blue2D_.
 {
     return blue2D_;
 }
float *const * RasterImage_RGBa_F::getBlueF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 2D raster for the blue channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1079 of file RasterImage_RGBa_F.cpp.
References blue2D_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return blue2D_;
 }
ConversionFromFloatMode RasterImage_RGBa_F::getFloatConversionMode (void) const
Returns the image's conversion mode from float to gray.
Returns
conversion mode for this image
See also
setFloatConversionMode
setDefaultFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 1297 of file RasterImage_RGBa_F.cpp.
References defaultFloatConv_, floatConv_, and hasIndivFloatConvMode_.
Referenced by writeInto_().
 {
     if (hasIndivFloatConvMode_)
         return floatConv_;
     else
         return defaultFloatConv_;
 }
const float * RasterImage_RGBa_F::getGreenF (void) const
Returns the base address of this objet's private 1D raster for the red channel.
Definition at line 998 of file RasterImage_RGBa_F.cpp.
References green_.
Referenced by allocateShiftedRaster2D_().
 {
     return green_;
 }
float * RasterImage_RGBa_F::getGreenF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the red channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1003 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage::graphWorldIsReference(), green_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return green_;
 }
const float *const * RasterImage_RGBa_F::getGreenF2D (void) const
Returns the base address of this objet's private 1D raster for the green channel.
Definition at line 1055 of file RasterImage_RGBa_F.cpp.
References green2D_.
 {
     return green2D_;
 }
float *const * RasterImage_RGBa_F::getGreenF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the green channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1060 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage::graphWorldIsReference(), green2D_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return green2D_;
 }
const float * RasterImage_RGBa_F::getRedF (void) const
Returns the base address of this objet's private 1D raster for the red channel.
Definition at line 979 of file RasterImage_RGBa_F.cpp.
References red_.
Referenced by allocateShiftedRaster2D_().
 {
     return red_;
 }
float * RasterImage_RGBa_F::getRedF (ReadWriteStatus rw)
Returns the base address of this objet's private 1D raster for the red channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 984 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage::graphWorldIsReference(), red_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return red_;
 }
const float *const * RasterImage_RGBa_F::getRedF2D (void) const
Returns the base address of this objet's private 2D raster for the red channel.
Definition at line 1036 of file RasterImage_RGBa_F.cpp.
References red2D_.
 {
     return red2D_;
 }
float *const * RasterImage_RGBa_F::getRedF2D (ReadWriteStatus rw)
Returns the base address of this objet's private 2D raster for the red channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1041 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage::graphWorldIsReference(), red2D_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return red2D_;
 }
const unsigned char * RasterImage_RGBa_F::getRGBa (void) const virtual
Returns the 32-bit rgba base raster as a read-only 1D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 880 of file RasterImage_RGBa_F.cpp.
References uriVL::GraphWorld::getRaster(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return gworld_->getRaster();
 }
unsigned char * RasterImage_RGBa_F::getRGBa (ReadWriteStatus rw) virtual
Returns the 32-bit rgba base raster as a read-write 1D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 894 of file RasterImage_RGBa_F.cpp.
References uriVL::GraphWorld::getRaster(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return gworld_->getRaster();
 }
const unsigned char *const * RasterImage_RGBa_F::getRGBa2D (void) const virtual
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 914 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return RasterImage_RGBa::getRGBa2D();
 }
unsigned char *const * RasterImage_RGBa_F::getRGBa2D (ReadWriteStatus rw) virtual
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 927 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return RasterImage_RGBa::getRGBa2D(R_W_ACCESS);
 }
const float *const * RasterImage_RGBa_F::getShiftedBlueF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the blue channel.
Definition at line 1157 of file RasterImage_RGBa_F.cpp.
References blue2D_, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), and shiftedBlue2D_.
Referenced by uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), calculateFloatConversionParams_(), uriVL::ColorImageGradient::getShiftedAltTempBlueF2D_(), uriVL::ColorImageGradient::getShiftedTempBlueF2D_(), uriVL::ColorGaussianFilter::getShiftedTempBlueF2D_(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), and writeInto_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return blue2D_;
     else
         return shiftedBlue2D_;
 }
float *const * RasterImage_RGBa_F::getShiftedBlueF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the blue channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1168 of file RasterImage_RGBa_F.cpp.
References blue2D_, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), shiftedBlue2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return blue2D_;
     else
         return shiftedBlue2D_;
 }
const float *const * RasterImage_RGBa_F::getShiftedGreenF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the green channel.
Definition at line 1126 of file RasterImage_RGBa_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), green2D_, and shiftedGreen2D_.
Referenced by uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), calculateFloatConversionParams_(), uriVL::ColorImageGradient::getShiftedAltTempGreenF2D_(), uriVL::ColorImageGradient::getShiftedTempGreenF2D_(), uriVL::ColorGaussianFilter::getShiftedTempGreenF2D_(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), and writeInto_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return green2D_;
     else
         return shiftedGreen2D_;
 }
float *const * RasterImage_RGBa_F::getShiftedGreenF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the green channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1137 of file RasterImage_RGBa_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), green2D_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), shiftedGreen2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return green2D_;
     else
         return shiftedGreen2D_;
 }
const float *const * RasterImage_RGBa_F::getShiftedRedF2D (void) const
Returns the base address of this objet's private shifted 2D raster for the red channel.
Definition at line 1093 of file RasterImage_RGBa_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), red2D_, and shiftedRed2D_.
Referenced by uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), calculateFloatConversionParams_(), uriVL::ColorImageGradient::getShiftedAltTempRedF2D_(), uriVL::ColorImageGradient::getShiftedTempRedF2D_(), uriVL::ColorGaussianFilter::getShiftedTempRedF2D_(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), and writeInto_().
 {
 //    return shiftedRed2D_;
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return red2D_;
     else
         return shiftedRed2D_;
 }
float *const * RasterImage_RGBa_F::getShiftedRedF2D (ReadWriteStatus rw)
Returns the base address of this objet's private shifted 2D raster for the red channel.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Definition at line 1106 of file RasterImage_RGBa_F.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), red2D_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), shiftedRed2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getXXXF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return red2D_;
     else
         return shiftedRed2D_;
 }
const unsigned char *const * RasterImage_RGBa_F::getShiftedRGBa2D (void) const virtual
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 946 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
Referenced by writeInto_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return RasterImage_RGBa::getShiftedRGBa2D();
 }
unsigned char *const * RasterImage_RGBa_F::getShiftedRGBa2D (ReadWriteStatus rw) virtual
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 959 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (gworld_ == NULL) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return RasterImage_RGBa::getShiftedRGBa2D(R_W_ACCESS);
 }
const RasterImage_RGBa_F & RasterImage_RGBa_F::operator= (const RasterImage_RGBa_F & img) private
This operator has not been implemented.
Parameters
img The raster image to initialize this image with
Definition at line 645 of file RasterImage_RGBa_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "copy operator not implemented in RasterImage_RGBa_F");
         return *this;
 }
void RasterImage_RGBa_F::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function may be called or overridden by child classes that have their own raster
Parameters
x horizontal coordinate of upper left corner
y vertical coordinate of upper left corner
theWidth desired width of the image
theHeight desired height of the image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 2034 of file RasterImage_RGBa_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked(), uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_RGBa::setBoundRect_(), shiftedBlue2D_, shiftedGreen2D_, and shiftedRed2D_.
 {
     FAIL_CONDITION( propertiesAreLocked(),
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  if width and height have not changed, then the operation is just a translation.
     //  All we need to do is update the "shifted" array (no re-allocation needed)
     //  since the parent class will take care of the rectangle itself
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             //  Since the rasters have the same dimensions, there is no need
             //  to delete and reallocate the shifted rasters.  Just apply a
             //  relative shift to them
             const int   iLow  = getTop(),
                                                 iHigh = getBottom(),
                                                 jLow = getLeft(),
                                                 rowShift = y - iLow,
                                                 colShift = x - jLow;
 //jyh   is this really needed?
 if (shiftedRed2D_)
 {
             for (int i=iLow; i<=iHigh; i++)
             {
                 shiftedRed2D_[i] += colShift;
                 shiftedGreen2D_[i] += colShift;
                 shiftedBlue2D_[i] += colShift;
             }
             shiftedRed2D_ += rowShift;
             shiftedGreen2D_ += rowShift;
             shiftedBlue2D_ += rowShift;
 }
             //  if the image has an integer raster, then we let the parent class do
             //  the rectangle resizing
         if (!graphWorldIsNull_())
                 RasterImage_RGBa::setBoundRect(x, y, theWidth, theHeight);
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangles are different, then we must delete
     //  and reallocate the 0-based 2D raster.
     else
     {
         deleteShiftedRaster2D_(y);
         deleteRaster2D_();
         //  if the image has an integer raster, then we let the parent class do
         //  the rectangle resizing
         if (!graphWorldIsNull_())
             RasterImage_RGBa::setBoundRect_(x, y, theWidth, theHeight);
                 allocateRaster2D_(theHeight, theWidth);
                 allocateShiftedRaster2D_(theHeight, theWidth, y, x);
     }
 }
void RasterImage_RGBa_F::setDefaultFloatConversionMode (ConversionFromFloatMode theMode) static
Sets the default conversion mode from float to gray for this class.
Parameters
theMode individual convcersion mode for the class
See also
getFloatConversionMode
setFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 1286 of file RasterImage_RGBa_F.cpp.
References defaultFloatConv_.
 {
     defaultFloatConv_ = theMode;
 }
void RasterImage_RGBa_F::setFloatConversionMode (ConversionFromFloatMode theMode)
Sets an individual conversion mode from float to gray for this image.
Parameters
theMode individual convcersion mode for this image
See also
getFloatConversionMode
setDefaultFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 1291 of file RasterImage_RGBa_F.cpp.
References floatConv_, and hasIndivFloatConvMode_.
 {
     floatConv_ = theMode;
     hasIndivFloatConvMode_ = true;
 }
void RasterImage_RGBa_F::updateRaster_ (void) const private virtual
Updates the image's base raster (if it is not the reference).
Overrides the virtual method of the RasterImage class.
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 1190 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage_RGBa::allocateGraphWorld_(), blue2D_, calculateFloatConversionParams_(), convertToRGBa_(), convScale_, defaultFloatConv_, FAIL_CONDITION, floatConv_, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), green2D_, hasIndivFloatConvMode_, uriVL::kGWorldAllocationError, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kSignedFloat, uriVL::R_W_ACCESS, red2D_, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), shiftedBlue2D_, shiftedGreen2D_, shiftedRed2D_, and valMin_.
Referenced by getBlueF(), getBlueF2D(), getGreenF(), getGreenF2D(), getRedF(), getRedF2D(), getRGBa(), getRGBa2D(), getShiftedBlueF2D(), getShiftedGreenF2D(), getShiftedRedF2D(), getShiftedRGBa2D(), and uriVL::RasterImage_RGBa::updateRaster_().
 {
         const ImageRect* validRect = getValidRect();
     const int   iLow = validRect->getTop(),
                 iHigh = validRect->getBottom(),
                 jLow = validRect->getLeft(),
                 jHigh = validRect->getRight();
     unsigned char *const* rgba;
     float *const* fRed;
     float *const* fGreen;
     float *const* fBlue;
         //      Before we call functions of the parent class with side effects on the
         //      "reference" flags, we copy their values to know what actually needs
         //      to be updated
         bool isCharToFloatUpdate = graphWorldIsReference();
         //      Not the prettiest solution, but gets the job done to preserve logical constness
         RasterImage_RGBa_F* updateableThis = const_cast<RasterImage_RGBa_F*>(this);
     //  if the GWorld  has not been allocated (typically
     //  the first time we render a RasterImage_RGBa_F object) then we must allocate
     //  it at the same dimensions (bounding rectangle) as the float raster
     if (graphWorldIsNull_())
     {
         updateableThis->allocateGraphWorld_(getHeight(), getWidth());
         FAIL_CONDITION( graphWorldIsNull_(),
                         kGWorldAllocationError,
                         "GraphWorld allocation failed in RasterImage_RGBa_F::updateRaster_");
         updateableThis->RasterImage_RGBa::allocateRaster2D_(getHeight(), getWidth());
         updateableThis->RasterImage_RGBa::allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     }
     //  if the bounding rectangle has its origin at (0, 0) then the shifted
     //  raster was never allocated or it is equal to the unshifted raster
     if ((getTop()==0) && (getLeft()==0))
     {
         rgba = updateableThis->RasterImage_RGBa::getRGBa2D(R_W_ACCESS);
         fRed = red2D_;
         fGreen = green2D_;
         fBlue = blue2D_;
     }
     //  otherwise I use the shifted raster
     else
     {
         rgba = updateableThis->RasterImage_RGBa::getRGBa2D(R_W_ACCESS);
         fRed = shiftedRed2D_;
         fGreen = shiftedGreen2D_;
         fBlue = shiftedBlue2D_;
     }
     //  First find out which raster is the reference to update from
     if (isCharToFloatUpdate)
     {
         for (int i=iLow; i<=iHigh; i++)
             for (int j=jLow, k=4*jLow; j<=jHigh; j++)
             {
                 fRed[i][j] = rgba[i][k++];
                 fGreen[i][j] = rgba[i][k++];
                 fBlue[i][j] = rgba[i][k++];
             }
     }
     else
     {
         ConversionFromFloatMode convMode;
         if (hasIndivFloatConvMode_)
             convMode = floatConv_;
         else
             convMode = defaultFloatConv_;
                 if ((convMode==kSignedFloat) || (convMode==kPositiveFloat) || (convMode==kRangeFloat))
                         calculateFloatConversionParams_( );
         long nbCols = jHigh - jLow + 1;
         for (int i=iLow; i<=iHigh; i++)
             updateableThis->convertToRGBa_(fRed[i]+jLow, fGreen[i]+jLow, fBlue[i]+jLow,
                                                                                    rgba[i]+4*jLow, nbCols, valMin_, convScale_, convMode);
     }
         if (isCharToFloatUpdate)
                 setGraphWorldAsReference_();
         else
                 setFloatRasterAsReference_();
 }
void RasterImage_RGBa_F::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const private virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 684 of file RasterImage_RGBa_F.cpp.
References uriVL::RasterImage::allocateRaster2D_(), uriVL::RasterImage::allocateShiftedRaster2D_(), calculateFloatConversionParams_(), convertToGray_(), convertToRGBa_(), convScale_, defaultFloatConv_, uriVL::RasterImage::defaultGrayConv_, FAIL_CONDITION, floatConv_, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), getFloatConversionMode(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), getShiftedBlueF2D(), getShiftedGreenF2D(), getShiftedRedF2D(), getShiftedRGBa2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::hasFloatRaster(), hasIndivFloatConvMode_, uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kSignedFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), uriVL::RasterImage::setOtherRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), valMin_, and uriVL::RasterImage_RGBa::writeInto_().
Referenced by copyInto().
 {
     //  If the float raster is not the reference then we really should not be here.
     if (graphWorldIsReference() && referenceHasChanged())
         {
         RasterImage_RGBa::writeInto_(imgOut, copyRect, origin);
         }
         //  Converting from the float raster
         else
         {
                 //  The GWorld only works with unshifted rasters so we need to compute
                 //  the "true" copy rectangles first
                 ImageRect*  sourceRect = new ImageRect(copyRect->getLeft() - getLeft(),
                                                                                            copyRect->getTop() - getTop(),
                                                                                            copyRect->getWidth(), copyRect->getHeight());
                 ImageRect*  destRect =  origin == NULL ?
                                                                 new ImageRect(copyRect->getLeft() - imgOut->getLeft(),
                                                                                           copyRect->getTop() - imgOut->getTop(),
                                                                                           copyRect->getWidth(), copyRect->getHeight())
                                                                 :
                                                                 new ImageRect(origin->getX() - imgOut->getLeft(),
                                                                                           origin->getY() - imgOut->getTop(),
                                                                                           copyRect->getWidth(), copyRect->getHeight());
                 const float* const* redSource = getShiftedRedF2D();
                 const float* const* greenSource = getShiftedGreenF2D();
                 const float* const* blueSource = getShiftedBlueF2D();
                 const int   iLowSource = sourceRect->getTop(),
                                         iLowDest = destRect->getTop(),
                                         iHighSource = sourceRect->getBottom(),
                                         jLowSource = sourceRect->getLeft(),
                                         jLowDest = destRect->getLeft();
                 const int       nbRows = sourceRect->getHeight(),
                                         nbCols = sourceRect->getWidth();
                 switch( imgOut->getBaseRasterType() )
                 {
                         case kBinaryRaster:
                                 imgOut->setOtherRasterAsReference_();
                                 imgOut->setReferenceHasChanged_(true);
                                 FAIL_CONDITION( true,
                                                                 kFunctionNotImplemented,
                                                                 "rgba_F to binary copies not handled yet by RasterImage_RGBa_F::writeInto_");
                                 break;
                         case kGrayRaster:
                                 //  if we are dealing with a plain gray raster image
                                 if (!imgOut->hasFloatRaster())
{
                                         unsigned char* const* grayDest = ((RasterImage_gray* )imgOut)->getShiftedGray2D(R_W_ACCESS);
                                         ConversionFromFloatMode floatConvMode;
                                         if (hasIndivFloatConvMode_)
                                                 floatConvMode = floatConv_;
                                         else
                                                 floatConvMode = defaultFloatConv_;
                                         if ((floatConvMode==kSignedFloat) || (floatConvMode==kPositiveFloat) ||
                                                 (floatConvMode==kRangeFloat))
                                                 calculateFloatConversionParams_( );
                                         for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
                                                 convertToGray_(redSource[i]+jLowSource,
                                                                            greenSource[i]+jLowSource,
                                                                            blueSource[i]+jLowSource,
                                                                            grayDest[iDest]+jLowDest,
                                                                            nbCols, valMin_, convScale_, defaultGrayConv_, floatConvMode);
                                         imgOut->setGraphWorldAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 }
                                 //
                                 //  if imgOut has a float raster, we had better use it
                                 else
{
                                         float* const* fGrayDest = ((RasterImage_gray_F *)imgOut)->getShiftedGrayF2D(R_W_ACCESS);
                                         //      This call may have been made from within the RasterImage_gray_F constructor of imgOut,
                                         //      in which case grayDest has not been allocated yet
                                         if (fGrayDest == NULL)
{
                                                 imgOut->allocateRaster2D_(nbRows, nbCols);
                                                 imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                                 fGrayDest = ((RasterImage_gray_F *)imgOut)->getShiftedGrayF2D(R_W_ACCESS);
                                         }
                                         for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
                                                 convertToGray_(redSource[i]+jLowSource,
                                                                            greenSource[i]+jLowSource,
                                                                            blueSource[i]+jLowSource,
                                                                            fGrayDest[iDest]+jLowDest,
                                                                            nbCols, valMin_, convScale_,
                                                                            defaultGrayConv_);
                                         imgOut->setFloatRasterAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 }
                                 break;
                         case kRGB24Raster:
                                 //  if we are dealing with a plain RGB raster image, just copy the bytes
                                 FAIL_CONDITION( true,
                                                                 kRasterImageError,
                                                                 "RGBA_F to RGB copies not handled yet");
                                 imgOut->setGraphWorldAsReference_();
                                 imgOut->setReferenceHasChanged_(true);
                                 break;
                         case kaRGB16Raster:
                                         //  if we are dealing with a plain aRGB16 raster image, just copy the bytes
                                         FAIL_CONDITION( true,
                                                                         kFunctionNotImplemented,
                                                                         "Gray_F to aRGB16 copies not handled yet");
                                         imgOut->setGraphWorldAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 break;
                         case kRGBa32Raster:
                                 //  if we are dealing with a RGBa raster image, convert float to uc
                                 if (!imgOut->hasFloatRaster())
{
                                         unsigned char*const* rgbaDest = static_cast<RasterImage_RGBa* >(imgOut)->getShiftedRGBa2D(R_W_ACCESS);
                                         ConversionFromFloatMode floatConvMode =  hasIndivFloatConvMode_ ? floatConv_ : defaultFloatConv_;
                                         if ((floatConvMode==kSignedFloat) || (floatConvMode==kPositiveFloat) ||
                                                 (floatConvMode==kRangeFloat))
                                                 calculateFloatConversionParams_( );
                                         for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
                                                 convertToRGBa_(redSource[i]+jLowSource, greenSource[i]+jLowSource,
                                                                            blueSource[i]+jLowSource, rgbaDest[iDest]+jLowDest,
                                                                            nbCols, valMin_, convScale_, floatConvMode);
                                         imgOut->setGraphWorldAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 }
                                 //
                                 //  if imgOut has a float raster, we had better use it
                                 else
{
                                         float*const* fRedDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                                         float*const* fGreenDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                                         float*const* fBlueDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                         //      This call may have been made from within the RasterImage_RGBa_F constructor of imgOut,
                                         //      in which case grayDest has not been allocated yet
                                         if ((fRedDest == NULL) || (fGreenDest == NULL)  || (fBlueDest == NULL))
{
                                                 imgOut->allocateRaster2D_(nbRows, nbCols);
                                                 imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                                 fRedDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                                                 fGreenDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                                                 fBlueDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                         }
                                         int     byteShiftSource = static_cast<int>(sizeof(float)*jLowSource),
                                                         byteShiftDest = static_cast<int>(sizeof(float)*jLowDest);
                                         long    bytesPerRow = static_cast<long>(sizeof(float)*nbCols);
                                         for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
{
                                                 memcpy(fRedDest[iDest] + byteShiftDest,
                                                            redSource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                                                 memcpy(fGreenDest[iDest] + byteShiftDest,
                                                            greenSource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                                                 memcpy(fBlueDest[iDest] + byteShiftDest,
                                                            blueSource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                                         }
                                         imgOut->setFloatRasterAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                                 //  assign to imgOut the same float conversion as this image
                                                 ((RasterImage_RGBa_F *)imgOut)->setFloatConversionMode(this->getFloatConversionMode());
                                 }
                                 break;
                         default:
                                 FAIL_CONDITION( true,
                                                                 kRasterImageError,
                                                                 "Invalid image type in RasterImage_gray::copyInto");
                                 break;
                 }
         }
 }
Friends And Related Function Documentation
friend class RasterImage_RGBa friend
Definition at line 799 of file RasterImage_RGBa_F.h.
Member Data Documentation
float** uriVL::RasterImage_RGBa_F::blue2D_ private
private 2D raster for the blue channel
Definition at line 509 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), calculateFloatConversionParams_(), deleteRaster2D_(), getBlueF2D(), getShiftedBlueF2D(), RasterImage_RGBa_F(), and updateRaster_().
float* uriVL::RasterImage_RGBa_F::blue_ private
private 1D raster for the blue channel
Definition at line 497 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), and getBlueF().
float uriVL::RasterImage_RGBa_F::convScale_ mutable private
Scale factor to apply in a float to gray conversion.
Definition at line 543 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_(), updateRaster_(), and writeInto_().
float uriVL::RasterImage_RGBa_F::convScaleBlue_ mutable private
Scale factor to apply in a float to blue conversion.
Definition at line 555 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::convScaleGreen_ mutable private
Scale factor to apply in a float to green conversion.
Definition at line 551 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::convScaleRed_ mutable private
Scale factor to apply in a float to red conversion.
Definition at line 547 of file RasterImage_RGBa_F.h.
ConversionFromFloatMode RasterImage_RGBa_F::defaultFloatConv_ = kSaturatedPositive static private
Code for the default algorithm for conversion from float to gray.
An image instance can override this default mode by setting its floatConv_ field to an other value.
See also
hasIndivFloatConvMode_
Definition at line 596 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setDefaultFloatConversionMode(), updateRaster_(), and writeInto_().
ConversionFromFloatMode uriVL::RasterImage_RGBa_F::floatConv_ private
Code for the algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
Only relevant if hasIndivFloatConvMode_ is true.
See also
hasIndivFloatConvMode_
Definition at line 539 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setFloatConversionMode(), updateRaster_(), and writeInto_().
float** uriVL::RasterImage_RGBa_F::green2D_ private
private 2D raster for the green channel
Definition at line 505 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), calculateFloatConversionParams_(), deleteRaster2D_(), getGreenF2D(), getShiftedGreenF2D(), RasterImage_RGBa_F(), and updateRaster_().
float* uriVL::RasterImage_RGBa_F::green_ private
private 1D raster for the green channel
Definition at line 493 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), and getGreenF().
bool uriVL::RasterImage_RGBa_F::hasIndivFloatConvMode_ private
True if an algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
See also
floatConv_
Definition at line 529 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setFloatConversionMode(), updateRaster_(), and writeInto_().
float** uriVL::RasterImage_RGBa_F::red2D_ private
private 2D raster for the red channel
Definition at line 501 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), calculateFloatConversionParams_(), deleteRaster2D_(), getRedF2D(), getShiftedRedF2D(), RasterImage_RGBa_F(), and updateRaster_().
float* uriVL::RasterImage_RGBa_F::red_ private
private 1D raster for the red channel
Definition at line 489 of file RasterImage_RGBa_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), and getRedF().
float** uriVL::RasterImage_RGBa_F::shiftedBlue2D_ private
private shifted 2D raster for the blue channel
Definition at line 521 of file RasterImage_RGBa_F.h.
Referenced by allocateShiftedRaster2D_(), calculateFloatConversionParams_(), deleteShiftedRaster2D_(), getShiftedBlueF2D(), setBoundRect_(), and updateRaster_().
float** uriVL::RasterImage_RGBa_F::shiftedGreen2D_ private
private shifted 2D raster for the green channel
Definition at line 517 of file RasterImage_RGBa_F.h.
Referenced by allocateShiftedRaster2D_(), calculateFloatConversionParams_(), deleteShiftedRaster2D_(), getShiftedGreenF2D(), setBoundRect_(), and updateRaster_().
float** uriVL::RasterImage_RGBa_F::shiftedRed2D_ private
private shifted 2D raster for the red channel
Definition at line 513 of file RasterImage_RGBa_F.h.
Referenced by allocateShiftedRaster2D_(), calculateFloatConversionParams_(), deleteShiftedRaster2D_(), getShiftedRedF2D(), setBoundRect_(), and updateRaster_().
float uriVL::RasterImage_RGBa_F::valMax_ mutable private
Minimum value over the raster (r-g-b combined)
Definition at line 563 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_().
float uriVL::RasterImage_RGBa_F::valMaxBlue_ mutable private
Maximum value over the blue raster.
Definition at line 587 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::valMaxGreen_ mutable private
Maximum value over the green raster.
Definition at line 579 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::valMaxRed_ mutable private
Maximum value over the red raster.
Definition at line 571 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::valMin_ mutable private
Minimum value over the raster (r-g-b combined)
Definition at line 559 of file RasterImage_RGBa_F.h.
Referenced by calculateFloatConversionParams_(), updateRaster_(), and writeInto_().
float uriVL::RasterImage_RGBa_F::valMinBlue_ mutable private
Minimum value over the blue raster.
Definition at line 583 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::valMinGreen_ mutable private
Minimum value over the green raster.
Definition at line 575 of file RasterImage_RGBa_F.h.
float uriVL::RasterImage_RGBa_F::valMinRed_ mutable private
Minimum value over the red raster.
Definition at line 567 of file RasterImage_RGBa_F.h.
The documentation for this class was generated from the following files:
RasterImage_RGBa_F.h
RasterImage_RGBa_F.cpp