URIVisionLibrary: uriVL::UriVL Class Reference
uriVL::UriVL Class Reference
UriVL class only contains static functions.
#include <uriVisionLib.h>
Static Public Member Functions
static void setValidDataRectSafeMode (bool mode)
static bool validDataRectIsSafe (void)
Private Member Functions
UriVL (void)
Static Private Attributes
static bool validDataRectIsSafe_ = true
Detailed Description
UriVL class only contains static functions.
It is there to define static variables used globally in the library.
Definition at line 594 of file uriVisionLib.h.
Constructor & Destructor Documentation
uriVL::UriVL::UriVL (void) inline private
Definition at line 613 of file uriVisionLib.h.
 { };
Member Function Documentation
static void uriVL::UriVL::setValidDataRectSafeMode (bool mode) inline static
Definition at line 599 of file uriVisionLib.h.
References validDataRectIsSafe_.
{
                                 validDataRectIsSafe_ = mode;
                         };
static bool uriVL::UriVL::validDataRectIsSafe (void) inline static
Definition at line 604 of file uriVisionLib.h.
References validDataRectIsSafe_.
Referenced by uriVL::LabelRaster::LabelRaster(), uriVL::RasterImage::RasterImage(), and uriVL::DrawableObject2D::setBoundRect().
{
                                 return validDataRectIsSafe_;
                         };
Member Data Documentation
bool UriVL::validDataRectIsSafe_ = true static private
Definition at line 607 of file uriVisionLib.h.
Referenced by setValidDataRectSafeMode(), and validDataRectIsSafe().
The documentation for this class was generated from the following files:
uriVisionLib.h
ErrorReport.cpp