URIVisionLibrary: uriVL::Entity3D Class Reference
uriVL::Entity3D Class Reference
The base virtual Entity3D class.
#include <Entity3D.h>
Public Member Functions
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Protected Member Functions
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Private Member Functions
Entity3D (const Entity3D &theFrame)
Copy contructor.
const Entity3D & operator= (const Entity3D &theFrame)
Copy operator.
Private Attributes
const ReferenceFrame3D * frame_
The reference frame relative to which the entity's is defined.
Friends
class Point3D
class Object3D
Detailed Description
The base virtual Entity3D class.
Entity3D is the base class for all geometric 3D objects in the library. An Entity3D is always defined relative to an external reference frame. An Entity3D could in fact
Version history
2004/07/10 [jyh] first "implementation"
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file Entity3D.h.
Constructor & Destructor Documentation
Entity3D::~Entity3D (void) virtual
Non-operative destructor.
The class destructor has nothing to do.
Definition at line 51 of file Entity3D.cpp.
References frame_, and uriVL::ReferenceFrame3D::notifyReleaseReference().
 {
     frame_->notifyReleaseReference(this);
 }
Entity3D::Entity3D (const ReferenceFrame3D * theFrame) protected
Contructor.
This constructor simply sets to 0 or NULL the basic instance variables
Parameters
theFrame the object to copy
Definition at line 28 of file Entity3D.cpp.
References frame_, and uriVL::ReferenceFrame3D::notifyUseAsReference().
         :   frame_(theFrame)
 {
     frame_->notifyUseAsReference(this);
 }
Entity3D::Entity3D (void) protected
Default contructor.
This constructor simply sets to 0 or NULL the basic instance variables
Definition at line 19 of file Entity3D.cpp.
References frame_, and uriVL::ReferenceFrame3D::notifyUseAsReference().
         :   frame_(new ReferenceFrame3D(ReferenceFrame3D::getGlobalReferenceFrame( )))
 {
     frame_->notifyUseAsReference(this);
 }
Entity3D::Entity3D (const Entity3D & theFrame) private
Copy contructor.
Disabled
           @param  theFrame        the object to copy
Definition at line 34 of file Entity3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       frame_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Entity3D copy constructor is disabled.");
 }
Member Function Documentation
void Entity3D::addMember (const Entity3D * member)
Function to invoke to add an Entity3D to this group.
This function and the function addTo of the same class accomplish the same thing. The function to call is a pure matter of preference
Parameters
member the Entity3D to add to this group object
Definition at line 74 of file Entity3D.cpp.
 {
 }
void Entity3D::addToGroup (const Entity3D * group)
Function to invoke to add this Entity3D to a group.
This function and the function addMember of the same class accomplish the same thing. The function to call is a pure matter of preference
Parameters
group the group Entity3D to which to add this object
Definition at line 70 of file Entity3D.cpp.
 {
 }
const ReferenceFrame3D * Entity3D::getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
Definition at line 64 of file Entity3D.cpp.
References frame_.
Referenced by uriVL::VirtualPart3D::addVertex().
 {
     return frame_;
 }
bool uriVL::Entity3D::isGrouped (void) const
Indicates whether this object belongs to a group.
Returns
true if this object belongs to a group
void uriVL::Entity3D::leaveGroup (void)
This function releases this object from the group it belongs to.
This object is removed from the group's member list and gets its own reference frame that coincides with that of the group.
const Entity3D & Entity3D::operator= (const Entity3D & theFrame) private
Copy operator.
Disabled
           @param  theFrame        the object to copy
Definition at line 42 of file Entity3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Entity3D copy operator is disabled.");
         return *this;
 }
void Entity3D::setReferenceFrame (const ReferenceFrame3D * ref)
Sets the reference frame relative to which the 3D entity is defined.
Definition at line 56 of file Entity3D.cpp.
References frame_, uriVL::ReferenceFrame3D::notifyReleaseReference(), and uriVL::ReferenceFrame3D::notifyUseAsReference().
Referenced by uriVL::VirtualPart3D::addVertex().
 {
     frame_->notifyReleaseReference(this);
     frame_ = ref;
     frame_->notifyUseAsReference(this);
 }
Friends And Related Function Documentation
friend class Object3D friend
Definition at line 123 of file Entity3D.h.
friend class Point3D friend
Definition at line 122 of file Entity3D.h.
Member Data Documentation
const ReferenceFrame3D* uriVL::Entity3D::frame_ private
The reference frame relative to which the entity's is defined.
Definition at line 107 of file Entity3D.h.
Referenced by uriVL::Point3D::distanceTo(), Entity3D(), getReferenceFrame(), uriVL::Point3D::Point3D(), setReferenceFrame(), and ~Entity3D().
The documentation for this class was generated from the following files:
Entity3D.h
Entity3D.cpp