URIVisionLibrary: uriVL::GraphWorld Class Reference
uriVL::GraphWorld Class Reference
Implements the GraphWorld class.
#include <GraphWorld.h>
Public Member Functions
GraphWorld (int pixelDepth, const ImageRect *boundsRect)
Constructor.
GraphWorld (int pixelDepth, int nbRows, int nbCols)
Constructor.
GraphWorld (const GraphWorld *theGWorld)
Copy constructor.
GraphWorld (const GraphWorld &theGWorld)
Copy constructor.
~GraphWorld (void)
Destructor.
const GraphWorld & operator= (const GraphWorld &theGWorld)
Copy constructor.
int getPixelDepth (void) const
Returns the number of bits per pixel (pixel depth)
int getBaseRasterType (void) const
Returns the index of the base raster type for this GWorld.
int getEffectiveNbCols (void) const
Returns the effective number of columns in the GraphWorld.
int getNbRows (void) const
Returns the number of rows in the GraphWorld.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the GraphWorld.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the GraphWorld.
void copyInto (GraphWorld *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray) const
void draw (void)
Renders the raster, using the OpenGL drawPixel function.
unsigned char * getRaster (void)
Returns the base address of the Graphworld's raster (QuickDraw PixMap)
void setAsMovieGraphWorld (Movie theMovie)
Sets this GraphWorld object as the destination of a movie.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this GraphWorld object as destination for a graphic importer.
void setGraphWorld (const GraphWorld *theGWorld)
Sets this GraphWorld as destination for a video capture.
void restoreGraphWorld (void)
Restores previous current GraphWorld and graphic device settings.
Protected Attributes
_GraphWorld_gen * graphWorld_
Platform-specific implementation of the graphworld: "generic version.
Friends
class _FrameGrabber_libvidcap
Detailed Description
Implements the GraphWorld class.
Graphworld was originally a wrapper class for the GWorld structure of QuickDraw and QuickTime (hence some of the remaining QT-isms in the names of its members). This class is now a pure virtual subclass, with the following subclasses:
_GraphWorld_QT: QuickTime implementation
_GraphWorld_gen: "generic" implementation, independent from any library other than standard C++
maybe later (not by me) GraphWorld_DX: DirectX implementation
Basically, I had the choice between two implementations:
public inheritance: Define GraphWorld as a pure virtual class and provide complete implementations in subclasses Graphworld_QT, _GraphWorld_gen, GraphWorld_DX, etc.
composition: Define variables of type Graphworld_QT or _GraphWorld_gen inside the Graphworld class.
I opted for the second solution because it allows me to restrict the platform-testing code to a single class. Otherwise I would have had to put platform-specific code into all of the RasterImage classes.
The base subclasses of RasterImage correspond to the base raster types. They are:
RasterImage_gray for 8-bit gray level images
RasterImage_rgb16 for 16-bit [1 alpha, 5 red, 5 green, 5 blue] color images
RasterImage_RGB for 24-bit [8 red, 8 green, 8 blue] color images
RasterImage_RGBa for 32-bit [8 alpha, 8 red, 8 green, 8 blue] color images These base subclasses can be instanciated and are the ones most commonly used for image processing and computer vision purposes.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 112 of file GraphWorld.h.
Constructor & Destructor Documentation
GraphWorld::GraphWorld (int pixelDepth, const ImageRect * boundsRect)
Constructor.
Creates a new GraphWorld at the dimensions and pixel depth specified.
Parameters
pixelDepth number of bits per pixel (8, 16, 24, 32)
boundsRect bounding rectangle for this raster
Definition at line 42 of file GraphWorld.cpp.
                 :       graphWorld_(
                                                 #if URIVL_USE_QUICKTIME
                                                         new _GraphWorld_QT(pixelDepth, boundsRect)
                                                 #else
                                                         new _GraphWorld_gen(pixelDepth, boundsRect)
                                                 #endif
                                                 )
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GraphWorld constructor");
         throw e;
 }
GraphWorld::GraphWorld (int pixelDepth, int nbRows, int nbCols)
Constructor.
Creates a new GraphWorld at the dimensions and pixel depth specified.
Parameters
pixelDepth number of bits per pixel (8, 16, 24, 32)
nbRows number of rows of the raster
nbCols number of columns of the raster
Definition at line 58 of file GraphWorld.cpp.
                 :       graphWorld_(
                                                 #if URIVL_USE_QUICKTIME
                                                         new _GraphWorld_QT(pixelDepth, nbRows, nbCols)
                                                 #else
                                                         new _GraphWorld_gen(pixelDepth, nbRows, nbCols)
                                                 #endif
                                                 )
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GraphWorld constructor");
         throw e;
 }
GraphWorld::GraphWorld (const GraphWorld * theGWorld)
Copy constructor.
Parameters
theGWorld the GraphWorld to clone
Definition at line 74 of file GraphWorld.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       graphWorld_(NULL)
 {
 //    PixMapHandle    thePixmap = GetGWorldPixMap(theGWorld->gworld_);
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "GraphWorld clone constructor is not operative yet");
 }
GraphWorld::GraphWorld (const GraphWorld & theGWorld)
Copy constructor.
Parameters
theGWorld the GraphWorld to clone
Definition at line 85 of file GraphWorld.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       graphWorld_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "GraphWorld clone constructor is not operative yet");
 }
GraphWorld::~GraphWorld (void)
Destructor.
Definition at line 93 of file GraphWorld.cpp.
References graphWorld_.
 {
     delete graphWorld_;
 }
Member Function Documentation
void GraphWorld::copyInto (GraphWorld * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) const
Definition at line 158 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::copyInto_(), and graphWorld_.
Referenced by uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), and uriVL::RasterImage_binary::writeInto_().
 {
     graphWorld_->copyInto_(destination->graphWorld_, sourceRect, destRect, inverseGray);
 }
void GraphWorld::draw (void)
Renders the raster, using the OpenGL drawPixel function.
Definition at line 164 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::draw_(), and graphWorld_.
Referenced by uriVL::RasterImage::render_().
 {
     graphWorld_->draw_();
 }
int GraphWorld::getBaseRasterType (void) const
Returns the index of the base raster type for this GWorld.
The base raster type is one of those defined by the BaseRasterType enum type.
Returns
index of the base raster type for this GWorld
See also
BaseRasterType
Definition at line 115 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getBaseRasterType_(), and graphWorld_.
 {
     return graphWorld_->getBaseRasterType_();
 }
int GraphWorld::getBytesPerRow (void) const
Returns the number of bytes on each row of the GraphWorld.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of bytes on a row of the GraphWorld
Definition at line 120 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getBytesPerRow_(), and graphWorld_.
Referenced by uriVL::RasterImage_RGB::allocateRaster2D_(), uriVL::RasterImage_RGBa::allocateRaster2D_(), uriVL::RasterImage_aRGB16::allocateRaster2D_(), uriVL::RasterImage_gray::allocateRaster2D_(), uriVL::RasterImage::getBytesPerRow(), and getTotalByteCount().
 {
     return graphWorld_->getBytesPerRow_();
 }
int GraphWorld::getEffectiveNbCols (void) const
Returns the effective number of columns in the GraphWorld.
Base rasters have padded rows. This function returns the number of bytes per row divided by the pixel depth.
Returns
effective number of columns in the GraphWorld
Definition at line 130 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getEffectiveNbCols_(), and graphWorld_.
Referenced by uriVL::RasterImage::RasterImage().
 {
     return graphWorld_->getEffectiveNbCols_();
 }
int GraphWorld::getNbRows (void) const
Returns the number of rows in the GraphWorld.
Returns
number of rows in the GraphWorld
Definition at line 135 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getNbRows_(), and graphWorld_.
Referenced by uriVL::RasterImage::RasterImage().
 {
     return graphWorld_->getNbRows_();
 }
int GraphWorld::getPixelDepth (void) const
Returns the number of bits per pixel (pixel depth)
Returns
pixel depth
Definition at line 125 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getPixelDepth_(), and graphWorld_.
Referenced by uriVL::RasterImage::getPixelDepth().
 {
     return graphWorld_->getPixelDepth_();
 }
unsigned char * GraphWorld::getRaster (void)
Returns the base address of the Graphworld's raster (QuickDraw PixMap)
Returns
base address of the Graphworld's raster
Definition at line 145 of file GraphWorld.cpp.
References uriVL::_GraphWorld_gen::getRaster_(), and graphWorld_.
Referenced by uriVL::RasterImage_RGB::allocateRaster2D_(), uriVL::RasterImage_RGBa::allocateRaster2D_(), uriVL::RasterImage_aRGB16::allocateRaster2D_(), uriVL::RasterImage_gray::allocateRaster2D_(), uriVL::RasterImage_gray::allocateShiftedRaster2D_(), uriVL::RasterImage_aRGB16::getARGB(), uriVL::RasterImage_gray::getGray(), uriVL::RasterImage_RGB::getRGB(), uriVL::RasterImage_RGBa::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa(), and uriVL::RasterImage_HSV::getRGBa().
 {
     return graphWorld_->getRaster_();
 }
long GraphWorld::getTotalByteCount (void) const
Returns the number of total number of bytes in the GraphWorld.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of bytes in the GraphWorld
Definition at line 140 of file GraphWorld.cpp.
References getBytesPerRow(), uriVL::_GraphWorld_gen::getNbRows_(), and graphWorld_.
Referenced by uriVL::RasterImage::getTotalByteCount().
 {
     return (long) graphWorld_->getNbRows_() * getBytesPerRow();
 }
const GraphWorld & GraphWorld::operator= (const GraphWorld & theGWorld)
Copy constructor.
Parameters
theGWorld the GraphWorld to clone
Definition at line 98 of file GraphWorld.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "GraphWorld = operator is not operative yet");
         return *this;
 }
void GraphWorld::restoreGraphWorld (void)
Restores previous current GraphWorld and graphic device settings.
Definition at line 204 of file GraphWorld.cpp.
References graphWorld_, and uriVL::_GraphWorld_gen::restoreGraphWorld_().
Referenced by uriVL::RasterImage::restoreGraphWorld().
 {
     graphWorld_->restoreGraphWorld_();
 }
void GraphWorld::setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this GraphWorld object as destination for a graphic importer.
When data is read from an image file, a GWorld must be set as the destination for the graphic importer. This member function allows to define this GraphWorld as the destination for the importer, so as to avoid unnecessary blitting between buffers.
Parameters
importer the graphic importer that will draw into this object
See also
restoreGraphWorld
Definition at line 178 of file GraphWorld.cpp.
References graphWorld_, and uriVL::_GraphWorld_gen::setAsImporterGraphWorld_().
Referenced by uriVL::RasterImage::setAsImporterGraphWorld().
 {
     return graphWorld_->setAsImporterGraphWorld_(importer);
 }
void GraphWorld::setAsMovieGraphWorld (Movie theMovie)
Sets this GraphWorld object as the destination of a movie.
The movie will play (render) into this object
Parameters
theMovie the movie that will play into this object
Definition at line 173 of file GraphWorld.cpp.
References graphWorld_, and uriVL::_GraphWorld_gen::setAsMovieGraphWorld_().
Referenced by uriVL::RasterImage::setAsMovieGraphWorld().
 {
     graphWorld_->setAsMovieGraphWorld_(theMovie);
 }
void GraphWorld::setGraphWorld (const GraphWorld * theGWorld)
Sets this GraphWorld as destination for a video capture.
When a movie is played or live video is grabbed, a GWorld must be set as the destination for the video stream. This member function allows to define the RasterImage's base raster as the destination for the video stream, so as to avoid unnecessary blitting between buffers.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
Parameters
grabber the FrameGrabber that will play into this object
Returns
error code (0 if all OK)
See also
restoreGraphWorldSets this object as the current GWorld for the QuickDraw engine, preserves the previous GWorld and graphic device in objects defined by the caller. Stores copies of these references to restore them later.
Parameters
theGWorld reference to GraphWorld where to store previous settings
Definition at line 198 of file GraphWorld.cpp.
References graphWorld_, and uriVL::_GraphWorld_gen::setGraphWorld_().
Referenced by uriVL::RasterImage::setAsCurrentGraphWorld().
 {
     graphWorld_->setGraphWorld_(theGWorld->graphWorld_);
 }
Friends And Related Function Documentation
friend class _FrameGrabber_libvidcap friend
Definition at line 305 of file GraphWorld.h.
Member Data Documentation
_GraphWorld_gen* uriVL::GraphWorld::graphWorld_ protected
Platform-specific implementation of the graphworld: "generic version.
Definition at line 298 of file GraphWorld.h.
Referenced by copyInto(), draw(), getBaseRasterType(), getBytesPerRow(), getEffectiveNbCols(), getNbRows(), getPixelDepth(), getRaster(), getTotalByteCount(), restoreGraphWorld(), setAsImporterGraphWorld(), setAsMovieGraphWorld(), setGraphWorld(), and ~GraphWorld().
The documentation for this class was generated from the following files:
GraphWorld.h
GraphWorld.cpp