URIVisionLibrary: uriVL::DrawableObject2D Class Reference
uriVL::DrawableObject2D Class Reference abstract
Virtual base DrawableObject2D class.
#include <DrawableObject2D.h>
Public Member Functions
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void applyTransformation (const Transformation2D *theTransf)=0
Applies a Transformation2D to this object.
virtual void rotate (float angle, const ImagePoint *rotCenter=NULL)=0
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Private Member Functions
const DrawableObject2D & operator= (const DrawableObject2D &thePt)
Equal operator.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)=0
Sets a new bounding rectangle for the drawable object.
virtual void setValidRect_ (int x, int y, int theWidth, int theHeight)=0
Sets a new valid data rectangle for the drawable object.
virtual void computeBoundingRect_ (ImageRect &rect) const =0
Calculates the object's bounding rect.
virtual void computeValidRect_ (ImageRect &rect) const =0
Calculates the object's valid box.
virtual void computeCentroid_ (ImagePoint_F &cent) const =0
Computes the contour's centroid.
virtual void computeCenterOfMass_ (ImagePoint_F &cent) const =0
Computes the object's center of mass by calculating the average point.
void computeScaledCorners_ (int theLeft, int theTop, int theRight, int theBottom, bool shifted, const ImagePoint *origin, int &scaledLeft, int &scaledTop, int &scaledRight, int &scaledBottom) const
Computes updated values for the object's corners when rendered scaled.
virtual void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const =0
Renders the drawable object at the depth and location specified.
Private Attributes
ImageRect boundRect_
Bounding rectangle for this drawable object.
ImageRect validRect_
Bounding rectangle of the valid data region for this drawable object.
ImagePoint_F centroid_
The contour's centroid.
ImagePoint_F centerOfMass_
The contour's ccenter of mass.
bool boundingRectIsUpToDate_
Indicates whether the bonding box stored is valid.
bool validRectIsUpToDate_
Indicates whether the bonding box stored is valid.
bool centroidIsUpToDate_
Indicates whether the centroid coordinates stored are valid.
bool centerOfMassIsUpToDate_
Indicates whether the centroid coordinates stored are valid.
float scaleX_
Horizontal scale at which this image is to be rendered.
float scaleY_
Vertical scale at which this image is to be rendered.
bool isRenderedScaled_
True when the image should be rendered at a scale other than 1.
int scaledLeft_
x coordinate of the object's upper-left corner when rendered scaled
int scaledTop_
y coordinate of the object's upper-left corner when rendered scaled
int scaledRight_
x coordinate of the object's lower-right corner when rendered scaled
int scaledBottom_
y coordinate of the object's lower-right corner when rendered scaled
bool dimensionsHaveChangedSinceLastRender_
flag used to minimize the number of times the scaledXXX_ variables are recomputed prior to a render
DrawableInformationType drawableInfoType_
Stores the type of information (as opposed to "data type" stored in the drawable object.
int windowWidth_
Individual rendering window width for this object.
int windowHeight_
Individual rendering window height for this object.
bool hasIndivWindowDimensions_
Indicate whether individual rendering dimensions have been defined for this object.
float renderZ_
Depth at which this object is to be rendered.
GLfloat * frameColor_
Color used for drawing a frame for the image when it is rendered.
bool mustDrawFrame_
True when a frame should be drawn around the image when it is rendered.
float color_ [4]
The object's rendering color.
bool mustDrawValidDataFrame_
True when a frame should be drawn around the image's valid data rectangle when it is rendered.
Static Private Attributes
static int defaultWindowWidth_ = -1
Default rendering window height for all drawable objects.
static int defaultWindowHeight_ = -1
Default rendering window height for all drowable objects.
static bool defaultDimensionsHaveChangedSinceLastRender_ = true
flag used to minimize the number of times the scaledXXX_ variables are recomputed prior to a render
Detailed Description
Virtual base DrawableObject2D class.
DrawableObject2D is the base class for all classes of 2D objects that can be drawn in by OpenGL: RasterImage, VectorField, Blob, etc.
    Any (direct or indirect) non-pure-virtual subclass of DrawableObject2D that does not
    inherit implementations of computeBoundingRect_, computeValidRect_, computeCentroid_,
    computeCenterOfMass_ along its inheritance chain <b>must</b> implement these functions
    and declare DrawableObject2D as a friend class.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 63 of file DrawableObject2D.h.
Constructor & Destructor Documentation
DrawableObject2D::~DrawableObject2D (void) virtual
Destructor.
Definition at line 222 of file DrawableObject2D.cpp.
References frameColor_.
 {
     if (frameColor_ != NULL)
         delete []frameColor_;
 }
DrawableObject2D::DrawableObject2D (DrawableInformationType drawableInfoType = kUndetermined) protected
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
drawableInfoType what kind of information is this object made of
Definition at line 36 of file DrawableObject2D.cpp.
References color_.
         :           boundRect_(ImageRect()),
             validRect_(ImageRect()),
             centroid_(ImagePoint_F()),
             centerOfMass_(ImagePoint_F()),
                         //
                         boundingRectIsUpToDate_(false),
                         validRectIsUpToDate_(false),
                         centroidIsUpToDate_(false),
                         centerOfMassIsUpToDate_(false),
                         //
                         scaleX_(1.f),
                         scaleY_(1.f),
                         isRenderedScaled_(false),
                         scaledLeft_(-1),
                         scaledTop_(-1),
                         scaledRight_(-1),
                         scaledBottom_(-1),
                         dimensionsHaveChangedSinceLastRender_(true),
                         drawableInfoType_(drawableInfoType),
                         //
                         windowWidth_(-1),
                         windowHeight_(-1),
                         hasIndivWindowDimensions_(false),
                         //
                         renderZ_(-1.f),
                         frameColor_(NULL),
                         mustDrawFrame_(false),
                         mustDrawValidDataFrame_(false)
 {
         //      default color is black
     color_[0] = color_[1] = color_[2] = 0.f;
     color_[3] = 1.0f;
 }
DrawableObject2D::DrawableObject2D (const ImageRect & rect, DrawableInformationType drawableInfoType = kUndetermined) protected
This constructor also sets the bounding rectangle of the object.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
rect the bounding rectangle for this object (will also be the valid data rect in "unsafe" mode
drawableInfoType what kind of information is this object made of
Definition at line 71 of file DrawableObject2D.cpp.
References color_.
                 :       boundRect_(rect),
             validRect_(UriVL::validDataRectIsSafe() ? ImageRect() : rect),
             centroid_(ImagePoint_F()),
             centerOfMass_(ImagePoint_F()),
                         //
                         boundingRectIsUpToDate_(false),
                         validRectIsUpToDate_(false),
                         centroidIsUpToDate_(false),
                         centerOfMassIsUpToDate_(false),
                         //
                         scaleX_(1.f),
                         scaleY_(1.f),
                         isRenderedScaled_(false),
                         scaledLeft_(-1),
                         scaledTop_(-1),
                         scaledRight_(-1),
                         scaledBottom_(-1),
                         dimensionsHaveChangedSinceLastRender_(true),
                         drawableInfoType_(drawableInfoType),
                         //
                         windowWidth_(-1),
                         windowHeight_(-1),
                         hasIndivWindowDimensions_(false),
                         //
                         renderZ_(-1.f),
                         frameColor_(NULL),
                         mustDrawFrame_(false),
                         mustDrawValidDataFrame_(false)
 {
         //      default color is black
     color_[0] = color_[1] = color_[2] = 0.f;
     color_[3] = 1.0f;
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by DrawableObject2D constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ImageRect parameter error in DrawableObject2D constructor");
 }
DrawableObject2D::DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType = kUndetermined) protected
This constructor also sets the bounding rectangle of the object.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
nbRows number of rows of the object to create
nbCols number of columns of the object to create
drawableInfoType what kind of information is this object made of
Definition at line 117 of file DrawableObject2D.cpp.
References color_, FAIL_CONDITION, and uriVL::kRasterInvalidDimensions.
                 :       boundRect_(ImageRect(0, 0, nbCols, nbRows)),
             validRect_(UriVL::validDataRectIsSafe() ? ImageRect() : ImageRect(0, 0, nbCols, nbRows)),
             centroid_(ImagePoint_F()),
             centerOfMass_(ImagePoint_F()),
                         //
                         boundingRectIsUpToDate_(false),
                         validRectIsUpToDate_(false),
                         centroidIsUpToDate_(false),
                         centerOfMassIsUpToDate_(false),
                         //
                         scaleX_(1.f),
                         scaleY_(1.f),
                         isRenderedScaled_(false),
                         scaledLeft_(-1),
                         scaledTop_(-1),
                         scaledRight_(-1),
                         scaledBottom_(-1),
                         dimensionsHaveChangedSinceLastRender_(true),
                         drawableInfoType_(drawableInfoType),
                         //
                         windowWidth_(-1),
                         windowHeight_(-1),
                         hasIndivWindowDimensions_(false),
                         //
                         renderZ_(-1.f),
                         frameColor_(NULL),
                         mustDrawFrame_(false),
                         mustDrawValidDataFrame_(false)
 {
     FAIL_CONDITION( (nbRows<0) || (nbCols<0),
                     kRasterInvalidDimensions,
                     "Invalid dimensions in DrawableObject2D constructor");
         //      default color is black
     color_[0] = color_[1] = color_[2] = 0.f;
     color_[3] = 1.0f;
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by DrawableObject2D constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid dimension parameter error in DrawableObject2D constructor");
 }
DrawableObject2D::DrawableObject2D (const DrawableObject2D & thePt) protected
Copy constructor.
Creates a clone of the DrawableObject2D object passed as parameter.
Parameters
thePt reference to the DrawableObject2D object to copy
Definition at line 169 of file DrawableObject2D.cpp.
References color_, and frameColor_.
            :    boundRect_(theObj.boundRect_),
                         validRect_(theObj.validRect_),
                         centroid_(theObj.centroid_),
                         centerOfMass_(theObj.centerOfMass_),
                         //
                         boundingRectIsUpToDate_(theObj.boundingRectIsUpToDate_),
                         validRectIsUpToDate_(theObj.validRectIsUpToDate_),
                         centroidIsUpToDate_(theObj.centroidIsUpToDate_),
                         centerOfMassIsUpToDate_(theObj.centerOfMassIsUpToDate_),
                         //
                         scaleX_(theObj.scaleX_),
                         scaleY_(theObj.scaleY_),
                         isRenderedScaled_(theObj.isRenderedScaled_),
                         scaledLeft_(-1),
                         scaledTop_(-1),
                         scaledRight_(-1),
                         scaledBottom_(-1),
                         dimensionsHaveChangedSinceLastRender_(true),
                         drawableInfoType_(theObj.drawableInfoType_),
                         //
                         windowWidth_(theObj.windowWidth_),
                         windowHeight_(theObj.windowHeight_),
                         hasIndivWindowDimensions_(theObj.hasIndivWindowDimensions_),
                         //
                         renderZ_(theObj.renderZ_),
                         frameColor_(NULL),
                         mustDrawFrame_(theObj.mustDrawFrame_),
                         mustDrawValidDataFrame_(theObj.mustDrawValidDataFrame_)
 {
         if (theObj.frameColor_ != NULL)
         {
                 frameColor_ = new GLfloat[4];
                 frameColor_[0] = theObj.frameColor_[0];
                 frameColor_[1] = theObj.frameColor_[1];
                 frameColor_[2] = theObj.frameColor_[2];
                 frameColor_[3] = theObj.frameColor_[3];
         }
         //      default color is black
     color_[0] = color_[1] = color_[2] = 0.f;
     color_[3] = 1.0f;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid reference passed to DrawableObject2D constructor.");
 }
Member Function Documentation
virtual void uriVL::DrawableObject2D::applyTransformation (const Transformation2D * theTransf) pure virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implemented in uriVL::RasterImage, uriVL::Pattern2D, uriVL::Histogram, uriVL::VectorField_F, uriVL::VectorField_I, uriVL::ContourForce, uriVL::Blob, uriVL::Contour_I, and uriVL::Contour_F.
bool DrawableObject2D::boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
Returns
true if the bounding rect is empty
Definition at line 287 of file DrawableObject2D.cpp.
References boundRect_, uriVL::ImageRect::getHeight(), and uriVL::ImageRect::getWidth().
Referenced by uriVL::RasterImage::copyInto_().
 {
         return ((boundRect_.getWidth() == 0) && (boundRect_.getHeight() == 0));
 }
bool DrawableObject2D::coincidesWith (DrawableObject2D * obj) const virtual
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
Parameters
img the image to test agains this image
Returns
true if the two rectangles coincide, false otherwise
Definition at line 345 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::coincidesWith(), FAIL_CONDITION, getBoundRect(), and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.coincidesWith(theObj->getBoundRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::coincidesWith.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::coincidesWith");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::coincidesWith (const ImageRect * rect) const virtual
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
Parameters
rect the rectangle to test agains that of this image
Returns
true if the two rectangles coincide, false otherwise
Definition at line 364 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::coincidesWith(), FAIL_CONDITION, and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.coincidesWith(theRect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::coincidesWith.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::coincidesWith");
                 //      for compiler
                 return false;
         }
 }
virtual void uriVL::DrawableObject2D::computeBoundingRect_ (ImageRect & rect) const private pure virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
See also
boundingRectIsUpToDate_
boundRect_
Implemented in uriVL::RasterImage, uriVL::VectorField, uriVL::Pattern2D, uriVL::Blob, uriVL::Histogram, uriVL::Contour_I, uriVL::ContourForce, and uriVL::Contour_F.
Referenced by getBoundRect().
virtual void uriVL::DrawableObject2D::computeCenterOfMass_ (ImagePoint_F & cent) const private pure virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implemented in uriVL::RasterImage, uriVL::VectorField, uriVL::Pattern2D, uriVL::Blob, uriVL::Histogram, uriVL::Contour_I, uriVL::ContourForce, and uriVL::Contour_F.
Referenced by getCenterOfMass().
virtual void uriVL::DrawableObject2D::computeCentroid_ (ImagePoint_F & cent) const private pure virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implemented in uriVL::RasterImage, uriVL::VectorField, uriVL::Pattern2D, uriVL::Blob, uriVL::Histogram, uriVL::Contour_I, uriVL::ContourForce, and uriVL::Contour_F.
Referenced by getCentroid().
void DrawableObject2D::computeScaledCorners_ (int theLeft, int theTop, int theRight, int theBottom, bool shifted, const ImagePoint * origin, int & scaledLeft, int & scaledTop, int & scaledRight, int & scaledBottom) const private
Computes updated values for the object's corners when rendered scaled.
Parameters
theLeft unscaled x coordinate of the object's upper-left corner when rendered scaled
theTop unscaled y coordinate of the object's upper-left corner when rendered scaled
theRight unscaled x coordinate of the object's lower-right corner when rendered scaled
theBottom unscaled y coordinate of the object's lower-right corner when rendered scaled
shifted true if the image should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
scaledLeft computed x coordinate of the object's upper-left corner when rendered scaled
scaledTop computed y coordinate of the object's upper-left corner when rendered scaled
scaledRight computed x coordinate of the object's lower-right corner when rendered scaled
scaledBottom computed y coordinate of the object's lower-right corner when rendered scaled
Definition at line 775 of file DrawableObject2D.cpp.
References FAIL_CONDITION, getHeight(), getWidth(), getWindowHeight(), getWindowWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kInvalidRectangleError, scaleX_, and scaleY_.
Referenced by render().
 {
     const int renderWinHeight = getWindowHeight();
     const int renderWinWidth = getWindowWidth();
     if (origin != NULL)
     {
         FAIL_CONDITION( (renderWinHeight < 0) || (renderWinWidth < 0),
                         kInvalidRectangleError,
                         "The dimensions of the window must be known in the shifted mode");
         //  if we display at a specified location, then the global (0, 0) corner should be
         //  at the upper left corner of our window.
         scaledLeft = static_cast<int>(floorf(origin->getX()*scaleX_));
         scaledRight = static_cast<int>(floorf((origin->getX() + (theRight - theLeft))*scaleX_));
         scaledTop = renderWinHeight - static_cast<int>(floorf(origin->getY()*scaleY_));
         scaledBottom = renderWinHeight -
                         static_cast<int>(floorf(origin->getY() + (theBottom - theTop)*scaleY_));
     }
     else if (shifted)
     {
         FAIL_CONDITION( (renderWinHeight < 0) || (renderWinWidth < 0),
                         kInvalidRectangleError,
                         "The dimensions of the window must be known in the shifted mode");
         //  if we display shifted, then the global (0, 0) corner should be in
         //  the upper left corner of our window.
         scaledLeft = static_cast<int>(floorf(theLeft*scaleX_));
         scaledRight = static_cast<int>(floorf(theRight*scaleX_));
         scaledTop = renderWinHeight - static_cast<int>(floorf(theTop*scaleY_));
         scaledBottom = renderWinHeight - static_cast<int>(floorf(theBottom*scaleY_));
     }
     else
     {
         //  If we display unshifted, then we need to move to the upper-left
         //  corner of the image, and draw right and down from there.
         scaledLeft = 0;
         scaledRight = static_cast<int>(floorf(getWidth()*scaleX_));
         scaledTop = static_cast<int>(floorf(getHeight()*scaleY_));
         scaledBottom = 0;
     }
 }
virtual void uriVL::DrawableObject2D::computeValidRect_ (ImageRect & rect) const private pure virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
See also
boundingRectIsUpToDate_
boundRect_
Implemented in uriVL::RasterImage, uriVL::VectorField, uriVL::Pattern2D, uriVL::Blob, uriVL::Histogram, uriVL::Contour_I, uriVL::ContourForce, and uriVL::Contour_F.
Referenced by getValidRect().
bool DrawableObject2D::contains (const DrawableObject2D * obj) const virtual
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
Parameters
img the image to test agains this image
Returns
true if theRect is contained within this rectangle, false otherwise
Definition at line 421 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::contains(), FAIL_CONDITION, getBoundRect(), and uriVL::kInvalidParameterError.
Referenced by uriVL::ImageGradient::allocateTempRaster_(), uriVL::GaussianFilter::allocateTempRaster_(), uriVL::ColorGaussianFilter::allocateTempRaster_(), uriVL::ColorImageGradient::allocateTempRasters_(), uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::RasterImage::copyInto_(), uriVL::ImageArithmetics::difference(), uriVL::RasterImage::grab(), uriVL::ImageWarper::setImages(), and uriVL::RasterImage::writeInto().
 {
         try {
                 return boundRect_.contains(theObj->getBoundRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::contains.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::contains");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::contains (const ImageRect * rect) const virtual
Indicates whether this image's bounding rectangle contains the one received as parameter.
Parameters
rect the rectangle to test agains that of this image
Returns
true if theRect is contained within this rectangle, false otherwise
Definition at line 440 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::contains(), FAIL_CONDITION, and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.contains(theRect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::contains.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::contains");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::contains (const ImagePoint * pt, int padding = 0) const virtual
Checks whether the point passed as parameter belongs to the rectangle.
Parameters
pt the point to check
padding the difference between the rectangle and search rectangle
Returns
true if pt is inside this rectangle
Definition at line 459 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::contains(), FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.contains(pt->getX(), pt->getY(), padding);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::contains.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::contains");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::contains (int x, int y, int padding = 0) const virtual
Checks whether the point passed as parameter belongs to the rectangle.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
padding the difference between the rectangle and search rectangle
Returns
true if pt is inside this rectangle
Definition at line 478 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, uriVL::ImageRect::contains(), FAIL_CONDITION, and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.contains(x, y, padding);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::contains.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::contains");
                 //      for compiler
                 return false;
         }
 }
int DrawableObject2D::getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
Returns
y coordinate of the lower-right pixel
Definition at line 557 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getBottom().
Referenced by render(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::VectorField_I::translateShiftedRaster2D_(), and uriVL::VectorField_F::translateShiftedRaster2D_().
 {
     return boundRect_.getBottom( );
 }
const ImageRect * DrawableObject2D::getBoundRect (void) const virtual
Returns the object's bounding rectangle.
Returns a pointer to the object's bounding rectangle.
Reminder: the ImageRect class uses the pixel-as-rectangle convention. Many subclasses will need to override this function (e.g RasterImage & LabelRaster classes, Blob & Pattern2D classes).
Returns
pointer to the object's bounding rectangle
See also
validRect_
boundRect_
getValidRect
Reimplemented in uriVL::Pattern2D, and uriVL::ContourForce.
Definition at line 267 of file DrawableObject2D.cpp.
References boundingRectIsUpToDate_, boundRect_, and computeBoundingRect_().
Referenced by uriVL::BlobTracker2DController::action(), uriVL::MedianFilter_I::applyTo(), uriVL::MedianFilter_F::applyTo(), uriVL::ColorMedianFilter_F::applyTo(), uriVL::ColorMedianFilter_I::applyTo(), uriVL::Blob::Blob(), uriVL::BlobTracker2DController::BlobTracker2DController(), coincidesWith(), uriVL::ContourForce::computeBoundingRect_(), uriVL::Blob::computeCentroid_(), uriVL::VectorField::computeNorm(), uriVL::VectorField::computeNormAndPhase(), uriVL::VectorField::computeNormSquared(), uriVL::VectorField::computeNormSquaredAndPhase(), uriVL::VectorField::computePhase(), uriVL::Blob::computeQuadNbPixels_(), uriVL::Contour_F::computeValidRect_(), uriVL::ContourForce::computeValidRect_(), uriVL::Contour_I::computeValidRect_(), uriVL::Blob::computeValidRect_(), contains(), uriVL::VectorField::copyInto(), uriVL::BlobFinder::findAllBlobsInside(), uriVL::ContourForce::getBoundRect(), glSetupAndRun(), isContainedBy(), loadImage(), myIdle(), overlaps(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternTracker2DController::PatternTracker2DController(), render(), uriVL::PatternTracker2DController::scaleImage(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::ImageWarper::setImages(), uriVL::Pattern2D::setPattern(), uriVL::ZeroCrossingDetector::showSignAsColor(), uriComputerVision::BackgroundRemoverTester::test1_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriComputerVision::BackgroundRemoverTester::test3_(), uriComputerVision::BackgroundRemoverTester::test4_(), translate(), uriVL::Pattern2D::update(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::VectorField_F::VectorField_F(), and uriVL::RasterImage::writeInto().
 {
     if (!boundingRectIsUpToDate_)
         {
                 computeBoundingRect_(boundRect_);
                 boundingRectIsUpToDate_ = true;
         }
         return &boundRect_;
 }
const ImagePoint_F * DrawableObject2D::getCenterOfMass (void) const
Returns the object's center of mass.
Returns
the object center of mass as a float image point
Definition at line 303 of file DrawableObject2D.cpp.
References centerOfMass_, centerOfMassIsUpToDate_, and computeCenterOfMass_().
Referenced by uriVL::ContourForce::computeCenterOfMass_().
{
         if (centerOfMassIsUpToDate_ != true)
         {
                 computeCenterOfMass_(centerOfMass_);
                 centerOfMassIsUpToDate_ = true;
         }
         return &centerOfMass_;
 }
const ImagePoint_F * DrawableObject2D::getCentroid (void) const
Returns the object's centroid.
Returns
the object centroid as a float image point
Definition at line 292 of file DrawableObject2D.cpp.
References centroid_, centroidIsUpToDate_, and computeCentroid_().
Referenced by uriVL::ContourForce::computeCentroid_(), and uriVL::Cluster::distance().
{
         if (centroidIsUpToDate_ != true)
         {
                 computeCentroid_(centroid_);
                 centroidIsUpToDate_ = true;
         }
         return &centroid_;
 }
const float * DrawableObject2D::getColor (void) const
Returns a read-only pointer to the object's color data.
Typically this function should only be called by the child class's render_ function.
Returns
read-only pointer to the object's color data
Definition at line 739 of file DrawableObject2D.cpp.
References color_.
Referenced by uriVL::Blob::Blob(), uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), uriVL::Histogram::render_(), uriVL::Blob::render_(), and uriVL::VectorField::render_().
 {
         return color_;
 }
DrawableInformationType DrawableObject2D::getDrawableInformationType (void) const
Returns the type of information stored in this object.
Returns
type of information stored in this object
Definition at line 1004 of file DrawableObject2D.cpp.
References drawableInfoType_.
Referenced by uriVL::DepthMap::draw(), uriVL::RangeMap::draw(), uriVL::ElevationMap::draw(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), and uriVL::ElevationMap::updateMesh().
 {
     return drawableInfoType_;
 }
int DrawableObject2D::getHeight (void) const virtual
Returns the number of rows for the image.
Returns
number of rows for the image
Definition at line 537 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getHeight().
Referenced by uriVL::DepthMap::allocateDenseMesh_(), uriVL::ElevationMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), uriVL::PatternMatcher2D::allocateRasters_(), uriVL::PatternMatcher2D_corr::allocateRasters_(), uriVL::PatternMatcher2D_scaledDiff::allocateRasters_(), uriVL::PatternMatcher2D_medianDiff::allocateRasters_(), uriVL::HysteresisLabeler::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::HysteresisLabeler::applyTo(), uriVL::NormalFlowCalculator::applyTo(), computeDepth(), computeScaledCorners_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::VectorField::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::PatternMatcher2D_partCorr::covariance_(), uriVL::SegmentDetector::detect(), displayTextualInfo(), uriVL::RangeMap::drawDenseMesh_(), uriVL::ElevationMap::drawDenseMesh_(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::Pattern2D::getNbPixels(), glSetupAndRun(), handleMouseDrag(), uriVL::VectorField_I::initializeRasters_(), uriVL::VectorField_F::initializeRasters_(), initImagesAndWarper(), loadImage(), loadImages(), main(), WXGL_IO_Canvas::MakeFake_ImageBinary(), WXGL_IO_Canvas::MakeFake_ImageGS(), WXGL_IO_Canvas::MakeFake_ImageGSF(), WXGL_IO_Canvas::MakeFake_ImageRGBa(), uriVL::PatternMatcher2D::match(), myDisplay2(), myMenu1(), myMenu2(), uriVL::PatternMatcher2D_partCorr::patternCorrScale_(), uriVL::RasterImage_RGB::RasterImage_RGB(), resetCells(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::VectorField::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::ImageWarper::setImages(), setOrigin(), simpleImageTransform(), uriComputerVision::BackgroundRemoverTester::test1_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriComputerVision::BackgroundRemoverTester::test3_(), uriComputerVision::BackgroundRemoverTester::test4_(), uriVL::ElevationMap::updateMesh(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), updateState(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::DepthMap::~DepthMap(), uriVL::ElevationMap::~ElevationMap(), and uriVL::RangeMap::~RangeMap().
 {
     return boundRect_.getHeight( );
 }
int DrawableObject2D::getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
Returns
x coordinate of the upper-left pixel
Definition at line 562 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getLeft().
Referenced by uriVL::VectorField_I::allocateShiftedRaster2D_(), uriVL::VectorField_F::allocateShiftedRaster2D_(), uriVL::RasterImage_RGB::allocateShiftedRaster2D_(), uriVL::RasterImage_HSV::allocateShiftedRaster2D_(), uriVL::RasterImage_RGBa::allocateShiftedRaster2D_(), uriVL::RasterImage_aRGB16::allocateShiftedRaster2D_(), uriVL::RasterImage_gray::allocateShiftedRaster2D_(), uriVL::RasterImage_gray_F::allocateShiftedRaster2D_(), uriVL::RasterImage_RGBa_F::allocateShiftedRaster2D_(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), uriVL::VectorField::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::VectorField_I::deleteShiftedRaster2D_(), uriVL::VectorField_F::deleteShiftedRaster2D_(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::RasterImage_aRGB16::getShiftedARGB2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_HSV::getShiftedHue2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::RasterImage_RGB::RasterImage_RGB(), render(), uriVL::Contour_I::render_(), uriVL::Blob::render_(), uriVL::VectorField_F::renderNeedles_(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::VectorField::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return boundRect_.getLeft( );
 }
float DrawableObject2D::getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function returns the scale set for the horizontal direction.
Returns
horizontal rendering scale set for this image
Definition at line 764 of file DrawableObject2D.cpp.
References scaleX_.
Referenced by myKeyboard(), uriVL::ContourForce::render_(), uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), uriVL::Blob::render_(), uriVL::VectorField::render_(), uriVL::RasterImage::render_(), and uriVL::Pattern2D::renderBlobPattern_().
 {
     return scaleX_;
 }
float DrawableObject2D::getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function returns the scale set for the vertical direction.
Returns
vertical rendering scale set for this image
Definition at line 769 of file DrawableObject2D.cpp.
References scaleY_.
Referenced by uriVL::ContourForce::render_(), uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), uriVL::Blob::render_(), uriVL::VectorField::render_(), uriVL::RasterImage::render_(), and uriVL::Pattern2D::renderBlobPattern_().
 {
     return scaleY_;
 }
int DrawableObject2D::getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
Returns
x coordinate of the upper-right pixel
Definition at line 567 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getRight().
Referenced by render().
 {
     return boundRect_.getRight( );
 }
int DrawableObject2D::getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
Returns
y coordinate of the upper-left pixel
Definition at line 552 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getTop().
Referenced by uriVL::VectorField_I::allocateShiftedRaster2D_(), uriVL::VectorField_F::allocateShiftedRaster2D_(), uriVL::RasterImage_RGB::allocateShiftedRaster2D_(), uriVL::RasterImage_HSV::allocateShiftedRaster2D_(), uriVL::RasterImage_RGBa::allocateShiftedRaster2D_(), uriVL::RasterImage_aRGB16::allocateShiftedRaster2D_(), uriVL::RasterImage_gray::allocateShiftedRaster2D_(), uriVL::RasterImage_gray_F::allocateShiftedRaster2D_(), uriVL::RasterImage_RGBa_F::allocateShiftedRaster2D_(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), uriVL::VectorField::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::VectorField_I::deleteShiftedRaster2D_(), uriVL::VectorField_F::deleteShiftedRaster2D_(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::RasterImage_aRGB16::getShiftedARGB2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_HSV::getShiftedHue2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_RGB::RasterImage_RGB(), render(), uriVL::Contour_I::render_(), uriVL::Blob::render_(), uriVL::VectorField_F::renderNeedles_(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::VectorField::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::VectorField_I::translateShiftedRaster2D_(), uriVL::VectorField_F::translateShiftedRaster2D_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), uriVL::RasterImage_RGBa_F::writeInto_(), uriVL::RasterImage_aRGB16::~RasterImage_aRGB16(), uriVL::RasterImage_gray::~RasterImage_gray(), uriVL::RasterImage_gray_F::~RasterImage_gray_F(), uriVL::RasterImage_HSV::~RasterImage_HSV(), uriVL::RasterImage_RGB::~RasterImage_RGB(), uriVL::RasterImage_RGBa::~RasterImage_RGBa(), and uriVL::RasterImage_RGBa_F::~RasterImage_RGBa_F().
 {
     return boundRect_.getTop( );
 }
const ImagePoint * DrawableObject2D::getUpperLeft (void) const virtual
returns the coordinates of the upper left corner of the object
Returns
coordinates of the upper left corner
Definition at line 547 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getUpperLeft().
 {
         return boundRect_.getUpperLeft();
 }
const ImageRect * DrawableObject2D::getValidRect (void) const virtual
Returns the object's valid data rectangle.
Returns a pointer to the object's valid data rectangle. Many subclasses will need to override this function (e.g RasterImage & LabelRaster classes, Blob & Pattern2D classes)
Reminder: the ImageRect class uses the pixel-as-rectangle convention.
Returns
pointer to the object's valid data rectangle
See also
validRect_
boundRect_
getBoundRect
Reimplemented in uriVL::Pattern2D, and uriVL::ContourForce.
Definition at line 277 of file DrawableObject2D.cpp.
References boundRect_, computeValidRect_(), validRect_, and validRectIsUpToDate_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::RangeMap::allocateDenseMesh_(), applyAdditiveNoise(), uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::HysteresisLabeler::applyInto(), uriVL::NonMaximumSuppressor::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::ZeroCrossingDetector::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto(), uriVL::ColorThresholdLabeler::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::GrayThresholdLabeler::applyInto(), uriVL::NormalFlowCalculator::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Gaussian_I::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::ZeroCrossingDetector::applyInto_st(), applySaltAndPepperNoise(), uriVL::EdgeDetector_Canny_F::applyTo(), uriVL::NonMaximumSuppressor::applyTo(), uriVL::ColorInverseThresholdLabeler::applyTo(), uriVL::ColorImageGradient_Sobel::applyTo(), uriVL::ColorThresholdLabeler::applyTo(), uriVL::MedianFilter_F::applyTo(), uriVL::MedianFilter_I::applyTo(), uriVL::ColorMedianFilter_F::applyTo(), uriVL::GrayThresholdLabeler::applyTo(), uriVL::ColorMedianFilter_I::applyTo(), uriVL::ImageLaplacian_Gaussian_I::applyTo(), uriVL::ImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_F::applyTo(), uriVL::ZeroCrossingDetector::applyTo(), uriVL::ImageLaplacian_Sobel::applyTo(), uriVL::GaussianFilter_F::applyTo(), uriVL::ColorGaussianFilter_F::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::ColorGaussianFilter_I::applyTo(), uriVL::ColorImageGradient_Gaussian_F::applyTo(), uriVL::ColorImageGradient_Gaussian_I::applyTo(), uriVL::ImageGradient_Gaussian_F::applyTo(), uriVL::NonMaximumSuppressor::applyTo_st(), uriVL::ZeroCrossingDetector::applyTo_st(), uriVL::Blob::Blob(), uriVL::BlobTracker2DController::BlobTracker2DController(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), uriVL::VectorField::computeNorm(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField::computeNormAndPhase(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField::computeNormSquared(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField::computeNormSquaredAndPhase(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField::computePhase(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::RasterImage_HSV::convertFromGray_(), uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::RasterImage_HSV::convertToRGBa_(), uriVL::RasterImage_HSV::convertToSaturatedRGBa_(), uriVL::VectorField::copyInto(), uriVL::VectorField_F::copyInto(), uriVL::VectorField_I::copyInto(), uriVL::RasterImage_aRGB16::copyInto(), uriVL::RasterImage_RGB::copyInto(), uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage_RGBa::copyInto(), uriVL::RasterImage_gray_F::copyInto(), uriVL::RasterImage_RGBa_F::copyInto(), uriVL::RasterImage_binary::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::PatternMatcher2D_partCorr::covariance_(), uriVL::RasterImage::createCopy(), uriVL::DepthMap::DepthMap(), uriVL::ImageArithmetics::difference(), uriVL::ImageArithmetics::difference_(), uriVL::Blob::diskCoverage(), uriVL::DepthMap::drawDenseMesh_(), uriVL::ElevationMap::ElevationMap(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::VectorField_I::getMinMax(), uriVL::VectorField_F::getMinMax(), uriVL::VectorField_I::getMinMaxX(), uriVL::VectorField_F::getMinMaxX(), uriVL::VectorField_I::getMinMaxY(), uriVL::VectorField_F::getMinMaxY(), uriVL::StereoPair::getValidRect(), uriVL::ContourForce::getValidRect(), uriVL::Pattern2D::getValidRect(), uriVL::PatternTracker2D::grabImage_(), uriVL::ImageHistogram::ImageHistogram(), initImagesAndWarper(), loadImage(), uriVL::RasterImage_aRGB16::localRasterARGB16(), uriVL::RasterImage_gray::localRasterGray(), uriVL::RasterImage_HSV::localRasterHSV(), uriVL::RasterImage_RGBa::localRasterRGBa(), uriVL::RectifiedStereoMatcher_JJL::match(), uriVL::PatternMatcher2D::match(), uriVL::PatternTracker2D::mergeBlob_(), uriVL::RasterImage::overlay(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternMatcher2D_partCorr::patternCorrScale_(), uriVL::PatternTracker2DController::PatternTracker2DController(), uriVL::VectorField_I::prepareVectFieldForRendering_(), uriVL::VectorField_F::prepareVectFieldForRendering_(), uriVL::RangeMap::RangeMap(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), render(), uriVL::VectorField_I::renderNeedles_(), uriVL::VectorField_F::renderNeedles_(), uriVL::ImageHistogram::setImage(), uriVL::Pattern2D::setPattern(), uriVL::ZeroCrossingDetector::showSignAsColor(), uriVL::PatternTracker2D::track(), translate(), uriVL::Pattern2D::update(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), uriVL::ElevationMap::updateMesh(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), and uriVL::RasterImage::writeInto().
 {
     if (!validRectIsUpToDate_)
         {
                 computeValidRect_(boundRect_);
                 validRectIsUpToDate_ = true;
         }
     return &validRect_;
 }
int DrawableObject2D::getWidth (void) const virtual
Returns the number of columns for the image.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of columns for the image
Definition at line 542 of file DrawableObject2D.cpp.
References boundRect_, and uriVL::ImageRect::getWidth().
Referenced by uriVL::DepthMap::allocateDenseMesh_(), uriVL::ElevationMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), uriVL::PatternMatcher2D::allocateRasters_(), uriVL::PatternMatcher2D_corr::allocateRasters_(), uriVL::PatternMatcher2D_scaledDiff::allocateRasters_(), uriVL::PatternMatcher2D_medianDiff::allocateRasters_(), uriVL::HysteresisLabeler::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::HysteresisLabeler::applyTo(), uriVL::NormalFlowCalculator::applyTo(), computeDepth(), computeScaledCorners_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::VectorField::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::PatternMatcher2D_partCorr::covariance_(), uriVL::SegmentDetector::detect(), displayTextualInfo(), uriVL::RangeMap::drawDenseMesh_(), uriVL::ElevationMap::drawDenseMesh_(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::Pattern2D::getNbPixels(), glSetupAndRun(), handleMouseDrag(), uriVL::VectorField_I::initializeRasters_(), uriVL::VectorField_F::initializeRasters_(), initImagesAndWarper(), loadImage(), loadImages(), main(), WXGL_IO_Canvas::MakeFake_ImageBinary(), WXGL_IO_Canvas::MakeFake_ImageGS(), WXGL_IO_Canvas::MakeFake_ImageGSF(), WXGL_IO_Canvas::MakeFake_ImageRGBa(), uriVL::PatternMatcher2D::match(), myDisplay2(), myMenu1(), myMenu2(), uriVL::PatternMatcher2D_partCorr::patternCorrScale_(), uriVL::RasterImage_RGB::RasterImage_RGB(), resetCells(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::VectorField::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::ImageWarper::setImages(), setOrigin(), simpleImageTransform(), uriComputerVision::BackgroundRemoverTester::test1_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriComputerVision::BackgroundRemoverTester::test3_(), uriComputerVision::BackgroundRemoverTester::test4_(), uriVL::ElevationMap::updateMesh(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), updateState(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::RasterImage_aRGB16::writeInto_(), and uriVL::RasterImage_RGB::writeInto_().
 {
     return boundRect_.getWidth( );
 }
int DrawableObject2D::getWindowHeight (void) const
Gives the window height for this object.
Returns
the window height for this object
Definition at line 990 of file DrawableObject2D.cpp.
References defaultWindowHeight_, hasIndivWindowDimensions_, and windowHeight_.
Referenced by uriVL::Histogram::computeRenderingParameters_(), and computeScaledCorners_().
 {
     if (hasIndivWindowDimensions_)
                 return windowHeight_;
         else
                 return defaultWindowHeight_;
 }
int DrawableObject2D::getWindowWidth (void) const
Gives the window width for this object.
Returns
the window width for this object
Definition at line 980 of file DrawableObject2D.cpp.
References defaultWindowWidth_, hasIndivWindowDimensions_, windowHeight_, and windowWidth_.
Referenced by uriVL::Histogram::computeRenderingParameters_(), and computeScaledCorners_().
 {
     if (hasIndivWindowDimensions_)
                 return windowWidth_;
         else
                 return defaultWindowWidth_;
     return windowHeight_;
 }
bool DrawableObject2D::hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
Returns
true if this object has individual window dimensions
Definition at line 999 of file DrawableObject2D.cpp.
References hasIndivWindowDimensions_.
 {
         return hasIndivWindowDimensions_;
 }
bool DrawableObject2D::isContainedBy (DrawableObject2D * obj) const virtual
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
Parameters
img the image to test agains this image
Returns
true if this image contains img, false otherwise
Definition at line 499 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, getBoundRect(), uriVL::ImageRect::isContainedBy(), and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.isContainedBy(theObj->getBoundRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::isContainedBy.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::isContainedBy");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::isContainedBy (const ImageRect * rect) const virtual
Indicates whether this image's bounding rectangle is contained by the received as parameter.
Parameters
rect the rectangle to test agains that of this image
Returns
true if this image contains img, false otherwise
Definition at line 518 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, uriVL::ImageRect::isContainedBy(), and uriVL::kInvalidParameterError.
 {
         try {
                 return boundRect_.isContainedBy(theRect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::isContainedBy.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::isContainedBy");
                 //      for compiler
                 return false;
         }
 }
const DrawableObject2D & DrawableObject2D::operator= (const DrawableObject2D & thePt) private
Equal operator.
Created so that gcc will stop complaining.
Parameters
thePt reference to the DrawableObject2D object to copy
Definition at line 230 of file DrawableObject2D.cpp.
References boundRect_, uriVL::ImageRect::coincidesWith(), frameColor_, hasIndivWindowDimensions_, isRenderedScaled_, mustDrawFrame_, mustDrawValidDataFrame_, renderZ_, scaleX_, scaleY_, and validRect_.
 {
         boundRect_ = new ImageRect(theObj.boundRect_);
         if (!theObj.validRect_.coincidesWith(&(theObj.boundRect_))) {
                 validRect_ = new ImageRect(theObj.validRect_);
         }
         else {
                 validRect_ = theObj.boundRect_;
         }
         scaleX_ = theObj.scaleX_;
         scaleY_ = theObj.scaleY_;
         isRenderedScaled_ = theObj.isRenderedScaled_;
         hasIndivWindowDimensions_ = theObj.hasIndivWindowDimensions_;
         //
         renderZ_ = theObj.renderZ_;
         if (frameColor_ != NULL) {
                 frameColor_ = new float[3];
                 for (int i=0; i<3; i++)
                         frameColor_[i] = theObj.frameColor_[i];
         }
         mustDrawFrame_= theObj.mustDrawFrame_;
         mustDrawValidDataFrame_ = theObj.mustDrawValidDataFrame_;
         return *this;
 }
bool DrawableObject2D::overlaps (DrawableObject2D * obj) const virtual
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
Parameters
img the image to test agains this image
Returns
true if the two rectangles overlap, false otherwise
Definition at line 383 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, getBoundRect(), uriVL::kInvalidParameterError, and uriVL::ImageRect::overlaps().
 {
         try {
                 return boundRect_.overlaps(theObj->getBoundRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::overlaps.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::overlaps");
                 //      for compiler
                 return false;
         }
 }
bool DrawableObject2D::overlaps (const ImageRect * rect) const virtual
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
Parameters
rect the rectangle to test agains that of this image
Returns
true if the two rectangles overlap, false otherwise
Definition at line 402 of file DrawableObject2D.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, uriVL::kInvalidParameterError, and uriVL::ImageRect::overlaps().
 {
         try {
                 return boundRect_.overlaps(theRect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by DrawableObject2D::overlaps.");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer passed to a DrawableObjec2D passed to DrawableObject2D::overlaps");
                 //      for compiler
                 return false;
         }
 }
void DrawableObject2D::render (void) const
Renders the object at the default depth and (0, 0) location.
Renders the object, using OpenGL. The rendering is done at the preset "depth".
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
See also
setRenderDepth
Definition at line 828 of file DrawableObject2D.cpp.
References renderZ_.
Referenced by myDisplay(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myMouseMotion(), render(), uriVL::ContourForce::render_(), uriVL::Blob::render_(), uriVL::Pattern2D::render_(), uriVL::Blob::renderContour(), and uriVL::ActiveContourDetector_balloon::renderForces().
 {
     render(renderZ_, false, NULL);
 }
void DrawableObject2D::render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
Renders the "shifted" object, using OpenGL. The rendering is done at the preset "depth".
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
Parameters
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
See also
setRenderDepth
Definition at line 833 of file DrawableObject2D.cpp.
References render(), and renderZ_.
 {
     render(renderZ_, shifted, NULL);
 }
void DrawableObject2D::render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
Renders the RasterImage's base raster, using OpenGL's glDrawPixels function. The rendering is done at depth specified. The latter should be chosen so that the image lies within the frustum and vector graphics can be overlaid
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
Parameters
theZ Depth at which this object is to be rendered.
Definition at line 838 of file DrawableObject2D.cpp.
References render().
 {
     render(theZ, false, NULL);
 }
void DrawableObject2D::render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
Renders the drawable object, using OpenGL at the depth specified.
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
Parameters
theZ Depth at which this object is to be rendered.
shifted true if the image should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
Definition at line 843 of file DrawableObject2D.cpp.
References render().
 {
     render(theZ, shifted, NULL);
 }
void DrawableObject2D::render (const ImagePoint * origin) const
Renders the drawable object at the default depth and at the location specified.
A drawable object can be rendered with its bounding rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
Parameters
origin location of the object's upper-left corner in the rendering
Definition at line 848 of file DrawableObject2D.cpp.
References render(), and renderZ_.
 {
     render(renderZ_, true, origin);
 }
void DrawableObject2D::render (float theZ, bool shifted, const ImagePoint * origin) const
Renders the drawable object at the depth and location specified.
A drawable object can be rendered with its bounding rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
Parameters
theZ Depth at which this object is to be rendered.
shifted true if the image should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
Definition at line 853 of file DrawableObject2D.cpp.
References boundRect_, uriVL::ImageRect::coincidesWith(), computeScaledCorners_(), defaultDimensionsHaveChangedSinceLastRender_, dimensionsHaveChangedSinceLastRender_, frameColor_, getBottom(), getBoundRect(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), getLeft(), getRight(), uriVL::ImageRect::getTop(), getTop(), getValidRect(), uriVL::ImageRect::getWidth(), hasIndivWindowDimensions_, mustDrawFrame_, mustDrawValidDataFrame_, render_(), scaledBottom_, scaledLeft_, scaledRight_, scaledTop_, scaleX_, scaleY_, and validRect_.
 {
         //      If needed, forces a recalculation of the bounding rectangle
         //      From this point until the end of the function, the bounding rect will not change,
         //      so, e.g., trueBoundRect->getLeft(), getLeft(), and getBoundRect()->getLeft() all return
         //      the same value.
         const ImageRect* trueBoundRect = getBoundRect();
     //--------------------------------------------------------------
     //  Part 1: update rendering location if needed
     //--------------------------------------------------------------
         if ((hasIndivWindowDimensions_ && dimensionsHaveChangedSinceLastRender_) ||
                 defaultDimensionsHaveChangedSinceLastRender_)
         {
                 computeScaledCorners_(getLeft(), getTop(), getRight(), getBottom(), shifted, origin,
                                                           scaledLeft_, scaledTop_, scaledRight_, scaledBottom_);
                 dimensionsHaveChangedSinceLastRender_ = false;
         }
     //--------------------------------------------------------------
     //  Part 2: do subclass-specific rendering stuff
     //--------------------------------------------------------------
     render_(scaledLeft_, scaledTop_, scaledRight_, scaledBottom_, theZ, shifted, origin);
     //--------------------------------------------------------------
     //  Part 3: if required, indicate the bounding box by a colored frame
     //--------------------------------------------------------------
     if (mustDrawFrame_)
     {
         float   pRed, pGreen, pBlue;
         if (frameColor_ != NULL)
         {
             pRed = frameColor_[0];
             pGreen = frameColor_[1];
             pBlue = frameColor_[2];
         }
         else
             pRed = pGreen = pBlue = 0.f;
         //  The actual drawing
         glPushMatrix();
         glLoadIdentity();
         glTranslatef(scaledLeft_, scaledTop_, theZ);
         glScalef(scaleX_, -scaleY_, 1.f);
         glColor3f(pRed, pGreen, pBlue);
         glBegin(GL_LINE_LOOP);
             glVertex3f(0, 0, 0);
             glVertex3f(trueBoundRect->getWidth(), 0, 0);
             glVertex3f(trueBoundRect->getWidth(), trueBoundRect->getHeight(), 0);
             glVertex3f(0, trueBoundRect->getHeight(), 0);
         glEnd();
         glPopMatrix();
     }
     //--------------------------------------------------------------
     //  Part 4: if required and necessary (not all data are valid),
     //  indicate the valid data rectangle by a colored frame
     //--------------------------------------------------------------
     if (mustDrawValidDataFrame_ && (!validRect_.coincidesWith(&boundRect_) || !mustDrawFrame_))
     {
         const ImageRect* trueValidRect = getValidRect();
                 int shiftX = trueValidRect->getLeft() - getLeft();
                 int shiftY = trueValidRect->getTop() - getTop();
         float   pRed, pGreen, pBlue;
         if (frameColor_ != NULL)
         {
             pRed = 1.f - frameColor_[0];
             pGreen = 1.f - frameColor_[1];
             pBlue = 1.f - frameColor_[2];
         }
         else
             pRed = pGreen = pBlue = 0.f;
         //  The actual drawing
         glPushMatrix();
                 //      moved to the location of the bounding rect
         glTranslatef(scaledLeft_, scaledTop_, theZ);
                 //      apply the rendering scale
         glScalef(scaleX_, -scaleY_, 1.f);
                 //      then apply relative shift to the origin of the valid rect
         glTranslatef(shiftX, shiftY, 0.f);
         glColor3f(pRed, pGreen, pBlue);
         glBegin(GL_LINE_LOOP);
                         glVertex3f(0, 0, 0);
                         glVertex3f(trueValidRect->getWidth(), 0, 0);
                         glVertex3f(trueValidRect->getWidth(), trueValidRect->getHeight(), 0);
                         glVertex3f(0, trueValidRect->getHeight(), 0);
         glEnd();
         glPopMatrix();
     }
 }
virtual void uriVL::DrawableObject2D::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private pure virtual
Renders the drawable object at the depth and location specified.
A drawable object can be rendered with its valid data rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
            All render functions are declared to be const.  The basic idea behind that is that
            rendering just gives a snapshot of the current state of the object but should not
            really change the object.  According to this view, anything that needs to be
            changed/updated at render time is really mutable.
This function must be overridden by child classes.
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
Implemented in uriVL::RasterImage, uriVL::VectorField, uriVL::Pattern2D, uriVL::Blob, uriVL::Histogram, uriVL::Contour_I, uriVL::Contour_F, and uriVL::ContourForce.
Referenced by render().
virtual void uriVL::DrawableObject2D::rotate (float angle, const ImagePoint * rotCenter = NULL) pure virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implemented in uriVL::RasterImage, uriVL::Pattern2D, uriVL::Histogram, uriVL::VectorField_F, uriVL::VectorField_I, uriVL::ContourForce, uriVL::Blob, uriVL::Contour_I, and uriVL::Contour_F.
void DrawableObject2D::setBoundingRectIsUpToDate_ (bool isUpToDate) const protected
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
Parameters
isUpToDate is bounding rectangle up to date?
Definition at line 324 of file DrawableObject2D.cpp.
References boundingRectIsUpToDate_, and dimensionsHaveChangedSinceLastRender_.
Referenced by uriVL::Blob::addSegment(), uriVL::Blob::applyTransformation(), and uriVL::Contour::pointsHaveMoved().
 {
     boundingRectIsUpToDate_ = isUpToDate;
         if (!isUpToDate)
         {
                 dimensionsHaveChangedSinceLastRender_ = true;
         }
 }
void DrawableObject2D::setBoundRect (const ImageRect * theRect)
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function should be overridden by child classes that have their own raster (eg. HSV, gray_F, etc.)
Parameters
theRect new bounding rectangle for the image
Definition at line 602 of file DrawableObject2D.cpp.
References FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), and uriVL::kNullRectangleError.
Referenced by uriVL::ImageGradient::allocateTempRaster_(), uriVL::GaussianFilter::allocateTempRaster_(), uriVL::ColorGaussianFilter::allocateTempRaster_(), uriVL::ColorImageGradient::allocateTempRasters_(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::VectorField::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::ImageArithmetics::difference(), uriVL::RasterImage::RasterImage(), uriVL::VectorField::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::ImageWarper::setImages(), setOrigin(), and uriVL::RectifiedStereoMatcher_JJL::setStereoPair().
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null rectangle received as parameter in DrawableObject2D::setRect");
     setBoundRect(theRect->getLeft(), theRect->getTop(), theRect->getWidth(), theRect->getHeight());
 }
void DrawableObject2D::setBoundRect (int x, int y, int theWidth, int theHeight) virtual
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function should be overridden by child classes that have their own raster (eg. HSV, gray_F, etc.)
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
theWidth number of columns occupied by the drawable object
theHeight number of rows occupied by the drawable object
Definition at line 612 of file DrawableObject2D.cpp.
References boundRect_, setBoundRect_(), uriVL::ImageRect::setRect(), setValidRect(), and uriVL::UriVL::validDataRectIsSafe().
 {
     //  Call the child class's function for some class-specific settings
     setBoundRect_(x, y, theWidth, theHeight);
         boundRect_.setRect(x, y, theWidth, theHeight);
         //      if we are in "safe mode" then the valid data rect is set to empty
         //      otherwise it is equal to the new boundrect
         if (UriVL::validDataRectIsSafe())
                 setValidRect(x, y, 0, 0);
         else
                 setValidRect(x, y, theWidth, theHeight);
 }
virtual void uriVL::DrawableObject2D::setBoundRect_ (int x, int y, int theWidth, int theHeight) private pure virtual
Sets a new bounding rectangle for the drawable object.
A drawable object occupies a rectangle within the global image space. For example, a drawable object could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function must be overridden by child classes
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
theWidth number of valid columns
theHeight number of valid rows
Implemented in uriVL::RasterImage_RGBa_F, uriVL::RasterImage_binary, uriVL::RasterImage_gray_F, uriVL::VectorField, uriVL::RasterImage_gray, uriVL::RasterImage_RGBa, uriVL::RasterImage_RGB, uriVL::RasterImage_aRGB16, uriVL::Blob, uriVL::Pattern2D, uriVL::Histogram, uriVL::Contour, and uriVL::ContourForce.
Referenced by setBoundRect(), and translate().
void DrawableObject2D::setCenterOfMassIsUpToDate_ (bool isUpToDate) const protected
Allows a child class whose content has been changed to force recomputation of the center of mass.
Parameters
isUpToDate is center of mass up to date?
Definition at line 319 of file DrawableObject2D.cpp.
References centerOfMassIsUpToDate_.
Referenced by uriVL::Blob::addSegment(), uriVL::Blob::applyTransformation(), uriVL::Blob::fillHoles(), and uriVL::Contour::pointsHaveMoved().
 {
     centerOfMassIsUpToDate_ = isUpToDate;
 }
void DrawableObject2D::setCentroidIsUpToDate_ (bool isUpToDate) const protected
Allows a child class whose content has been changed to force recomputation of the centroid.
Parameters
isUpToDate is centroid up to date?
Definition at line 314 of file DrawableObject2D.cpp.
References centroidIsUpToDate_.
Referenced by uriVL::Blob::addSegment(), uriVL::Blob::applyTransformation(), and uriVL::Contour::pointsHaveMoved().
 {
     centroidIsUpToDate_ = isUpToDate;
 }
void DrawableObject2D::setColor (float red, float green, float blue) virtual
Assigns a rendering color to the object (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Reimplemented in uriVL::ContourForce.
Definition at line 706 of file DrawableObject2D.cpp.
References color_.
Referenced by uriVL::Blob::Blob(), CreateImageAndField(), glSetupAndRun(), myDisplay3(), myHistogramColorSubmenu(), myMenu2(), myMenu3(), myMouse3(), myVectFieldSubmenu(), uriVL::ContourForce::setColor(), and uriVL::Blob::setContourColor().
 {
     color_[0] = red;
     color_[1] = green;
     color_[2] = blue;
     color_[3] = 1.f;
 }
void DrawableObject2D::setColor (unsigned char red, unsigned char green, unsigned char blue) virtual
Assigns a rendering color to the object (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Reimplemented in uriVL::ContourForce.
Definition at line 723 of file DrawableObject2D.cpp.
References color_.
 {
     color_[0] = red/255.f;
     color_[1] = green/255.f;
     color_[2] = blue/255.f;
     color_[3] = 1.f;
 }
void DrawableObject2D::setColor (const float theColor[]) virtual
Assigns a rendering color to the object (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Reimplemented in uriVL::ContourForce.
Definition at line 714 of file DrawableObject2D.cpp.
References color_.
 {
     color_[0] = theColor[0];
     color_[1] = theColor[1];
     color_[2] = theColor[2];
     color_[3] = 1.f;
 }
void DrawableObject2D::setColor (const unsigned char theColor[]) virtual
Assigns a rendering color to the object (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Reimplemented in uriVL::ContourForce.
Definition at line 731 of file DrawableObject2D.cpp.
References color_.
 {
     color_[0] = theColor[0]/255.f;
     color_[1] = theColor[1]/255.f;
     color_[2] = theColor[2]/255.f;
     color_[3] = 1.f;
 }
void DrawableObject2D::setDefaultWindowDimensions (int theWidth, int theHeight) static
Informs the class of the dimensions of the default graphic context used for rendering.
An individual VectorField can have its own dimensions assigned by calling setWindowDimensions. These dimensions are only needed if the user wants to display the VectorField "shifted" (boolean true passed to render). If only the 0-based rendering is used (default call to render), then this information is not needed.
Parameters
theWidth width of the window where rendering takes place
theHeight height of the window where rendering takes place
See also
defaultWindowWidth_
defaultWindowHeight_
setWindowDimensions
hasIndivWindowDimensions_
Definition at line 957 of file DrawableObject2D.cpp.
References defaultDimensionsHaveChangedSinceLastRender_, defaultWindowHeight_, defaultWindowWidth_, FAIL_CONDITION, and uriVL::kRasterInvalidDimensions.
 {
     FAIL_CONDITION( (theWidth < 0) || (theHeight < 0),
                     kRasterInvalidDimensions,
                     "Invalid window dimensions specified");
     defaultWindowWidth_ = theWidth;
     defaultWindowHeight_ = theHeight;
         defaultDimensionsHaveChangedSinceLastRender_ = true;
 }
void DrawableObject2D::setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Parameters
type type of information in this object
Definition at line 1009 of file DrawableObject2D.cpp.
References drawableInfoType_.
Referenced by uriVL::RasterImage_aRGB16::copyInto(), uriVL::RasterImage_RGB::copyInto(), uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage_RGBa::copyInto(), uriVL::RasterImage_binary::copyInto(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), and uriVL::RasterImage_gray_F::writeInto_().
 {
     drawableInfoType_ = type;
 }
void DrawableObject2D::setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
An image can be rendered with a colored surrounding frame. This function allows set on or off the drawing of the frame (off by default).
See also
setFrameColor
mustDrawFrame_
Parameters
drawFrame true if a frame should be drawn to indicate the bounding rectangle
Definition at line 700 of file DrawableObject2D.cpp.
References mustDrawFrame_.
Referenced by CreateImageAndField(), myMouse3(), and uriVL::Pattern2D::setDrawContour().
 {
     mustDrawFrame_ = drawFrame;
 }
void DrawableObject2D::setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
An image can be rendered with a colored surrounding frame. This function allows set on or off the drawing of the frame (off by default).
See also
setDrawFrame
mustDrawValidDataFrame_
Parameters
drawFrame true if a frame should be drawn to indicate the valid data rectangle
Definition at line 745 of file DrawableObject2D.cpp.
References mustDrawValidDataFrame_.
Referenced by CreateImageAndField(), handleMouseDrag(), loadImage(), myDisplay2(), myDisplay3(), myMenu2(), myMenu3(), and resetImages().
 {
     mustDrawValidDataFrame_ = drawFrame;
 }
void DrawableObject2D::setFrameColor (float frameRed = 0.f, float frameGreen = 0.f, float frameBlue = 0.f)
Specifies the a color for the frame of this object.
An image can be rendered with a colored surrounding frame (by default there is no such frame). This function allows to specify the color for the frame.
See also
setDrawFrame
Parameters
frameRed red value for the frame
frameGreen green value for the frame
frameBlue blue value for the frame
Definition at line 655 of file DrawableObject2D.cpp.
References frameColor_.
Referenced by CreateImageAndField(), handleMouseDrag(), loadImage(), myDisplay2(), myDisplay3(), myMenu2(), myMenu3(), and uriVL::Pattern2D::setContourColor().
 {
     if (frameColor_ == NULL)
         frameColor_ = new float[4];
     frameColor_[0] = frameRed;
     frameColor_[1] = frameGreen;
     frameColor_[2] = frameBlue;
     frameColor_[3] = 1.f;
 }
void DrawableObject2D::setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 678 of file DrawableObject2D.cpp.
References frameColor_.
 {
     if (frameColor_ == NULL)
         frameColor_ = new float[4];
     frameColor_[0] = red/255.f;
     frameColor_[1] = green/255.f;
     frameColor_[2] = blue/255.f;
     frameColor_[3] = 1.f;
 }
void DrawableObject2D::setFrameColor (const float * theColor)
Assigns a rendering color to the frame (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 666 of file DrawableObject2D.cpp.
References frameColor_.
 {
     if (frameColor_ == NULL)
         frameColor_ = new float[4];
     frameColor_[0] = theColor[0];
     frameColor_[1] = theColor[1];
     frameColor_[2] = theColor[2];
     frameColor_[3] = 1.f;
 }
void DrawableObject2D::setFrameColor (const unsigned char * theColor)
Assigns a rendering color to the frame (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 689 of file DrawableObject2D.cpp.
References frameColor_.
 {
     if (frameColor_ == NULL)
         frameColor_ = new float[4];
     frameColor_[0] = theColor[0]/255.f;
     frameColor_[1] = theColor[1]/255.f;
     frameColor_[2] = theColor[2]/255.f;
     frameColor_[3] = 1.f;
 }
void DrawableObject2D::setOrigin (int x = 0, int y = 0)
Sets a new origin for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation does not result in a reallocation of the image's base raster, but the sifted raster will be reallocated.
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
Definition at line 573 of file DrawableObject2D.cpp.
References getHeight(), getWidth(), and setBoundRect().
Referenced by uriVL::ManualStitcher::initStitch(), uriVL::ImageStitcher::optimizeDirection(), uriVL::ManualStitcher::restoreImages(), uriVL::ImageStitcher::restoreImages(), and uriVL::ImageStitcher::stitch().
 {
     setBoundRect(x, y, getWidth(), getHeight());
 }
void DrawableObject2D::setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
The rendering is done at depth specified. The latter should be chosen so that the image lies within the frustum and vector graphics can be overlaid
Parameters
theZ Depth at which this object is to be rendered.
Definition at line 650 of file DrawableObject2D.cpp.
References renderZ_.
 {
     renderZ_ = theZ;
 }
void DrawableObject2D::setRenderingScale (float scale) const virtual
Sets a uniform scale at which this object should be rendered.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function specifies the same scale for the horizontal and vertical directions (uniform scaling).
Parameters
scale scale for the horizontal and vertical directions
Reimplemented in uriVL::Pattern2D.
Definition at line 750 of file DrawableObject2D.cpp.
References isRenderedScaled_, scaleX_, and scaleY_.
Referenced by initializeApplication(), main(), myDisplay3(), myKeyboard(), and uriVL::Pattern2D::setRenderingScale().
 {
     scaleX_ = scaleY_ = scale;
     isRenderedScaled_ = ((scaleX_ != 1.f) || (scaleY_ != 1.f));
 }
void DrawableObject2D::setRenderingScale (float scaleX, float scaleY) const virtual
Sets horizontal and vertical scales at which this object should be rendered.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function specifies separate scales for the horizontal and vertical directions.
Parameters
scaleX scale for the horizontal direction
scaleY scale for the vertical direction
Reimplemented in uriVL::Pattern2D.
Definition at line 757 of file DrawableObject2D.cpp.
References isRenderedScaled_, scaleX_, and scaleY_.
 {
     scaleX_ = scaleX;
     scaleY_ = scaleY;
     isRenderedScaled_ = ((scaleX_ != 1.f) || (scaleY_ != 1.f));
 }
void DrawableObject2D::setValidRect (const ImageRect * theRect)
Sets a new valid data rectangle for the drawable object.
A raster image or vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the vector field's bounding rectangle
Parameters
theRect new valid data rectangle for the vector field
Definition at line 629 of file DrawableObject2D.cpp.
References uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), and uriVL::ImageRect::getWidth().
Referenced by uriVL::Blob::addSegment(), uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::HysteresisLabeler::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Gaussian_I::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), computeDepth(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField::computeNorm(), uriVL::VectorField::computeNormAndPhase(), uriVL::VectorField::computeNormSquared(), uriVL::VectorField::computeNormSquaredAndPhase(), uriVL::VectorField::computePhase(), uriVL::VectorField::copyInto(), uriVL::RasterImage_RGB::copyInto(), uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage_binary::copyInto(), uriVL::RasterImage::copyInto_(), CreateImageAndField(), uriVL::ImageArithmetics::difference(), uriVL::ImageArithmetics::difference_(), uriVL::SequenceGrabber::getFrame_(), handleMouseDrag(), initializeApplication(), initImagesAndWarper(), loadImages(), WXGL_IO_Canvas::MakeFake_ImageBinary(), WXGL_IO_Canvas::MakeFake_ImageGS(), WXGL_IO_Canvas::MakeFake_ImageGSF(), WXGL_IO_Canvas::MakeFake_ImageRGBa(), uriVL::RectifiedStereoMatcher_corr::match_(), uriVL::PatternTracker2D::mergeBlob_(), myMouse2(), myMouse3(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::PatternTracker2DController::PatternTracker2DController(), uriVL::RasterImage::RasterImage(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), setBoundRect(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::RectifiedStereoMatcher_JJL::setStereoPair(), uriVL::VectorField::setValidRect_(), uriVL::RasterImage_binary::setValidRect_(), translate(), and uriVL::VectorField_F::VectorField_F().
 {
     setValidRect(theRect->getLeft(), theRect->getTop(), theRect->getWidth(), theRect->getHeight());
 }
void DrawableObject2D::setValidRect (int x, int y, int theWidth, int theHeight) virtual
Sets a new valid data rectangle for the drawable object.
A raster image or vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the vector field's bounding rectangle
May be overridden by child classes that don't need to maintain their valid data rectangle at all times (e.g. Blob, Contour)
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Definition at line 634 of file DrawableObject2D.cpp.
References uriVL::ImageRect::setRect(), setValidRect_(), and validRect_.
 {
     //  Call the child class's function for some class-specific settings
     setValidRect_(x, y, theWidth, theHeight);
     validRect_.setRect(x, y, theWidth, theHeight);
 }
virtual void uriVL::DrawableObject2D::setValidRect_ (int x, int y, int theWidth, int theHeight) private pure virtual
Sets a new valid data rectangle for the drawable object.
A raster image or vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the vector field's bounding rectangle
Must be overridden by child classes that don't need to maintain their valid data rectangle at all times (e.g. Blob, Contour)
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implemented in uriVL::RasterImage, uriVL::RasterImage_binary, uriVL::VectorField, uriVL::Blob, uriVL::Pattern2D, uriVL::Histogram, uriVL::Contour, and uriVL::ContourForce.
Referenced by setValidRect().
void DrawableObject2D::setValidRectIsUpToDate_ (bool isUpToDate) const protected
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Parameters
isUpToDate is valid rectangle up to date?
Definition at line 333 of file DrawableObject2D.cpp.
References validRectIsUpToDate_.
Referenced by uriVL::Contour::pointsHaveMoved().
 {
     validRectIsUpToDate_ = isUpToDate;
 }
void DrawableObject2D::setWindowDimensions (int theWidth, int theHeight) virtual
Informs the vector field object of the dimensions of graphic context used for its rendering.
These dimensions override the default settings for the class. These dimensions are only needed if the user wants to display the VectorField "shifted" (boolean true passed to render). If only the 0-based rendering is used (default call to render), then this information is not needed.
Parameters
theWidth width of the window where rendering takes place
theHeight height of the window where rendering takes place
See also
defaultWindowWidth_
defaultWindowHeight_
setWindowDimensions
hasIndivWindowDimensions_
setDefaultWindowDimensions
Reimplemented in uriVL::Histogram.
Definition at line 968 of file DrawableObject2D.cpp.
References dimensionsHaveChangedSinceLastRender_, FAIL_CONDITION, hasIndivWindowDimensions_, uriVL::kRasterInvalidDimensions, windowHeight_, and windowWidth_.
Referenced by uriVL::Histogram::setWindowDimensions().
 {
     FAIL_CONDITION( (theWidth < 0) || (theHeight < 0),
                     kRasterInvalidDimensions,
                     "Invalid window dimensions specified");
     windowWidth_ = theWidth;
     windowHeight_ = theHeight;
     hasIndivWindowDimensions_ = true;
         dimensionsHaveChangedSinceLastRender_ = true;
 }
void DrawableObject2D::translate (int dx = 0, int dy = 0) virtual
Translates the raster image by the specified amount.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation does not result in a reallocation of the image's base raster, but the sifted raster will be reallocated.
Parameters
dx horizontal displacement of the image's origin
dy vertical displacement of the image's origin
Reimplemented in uriVL::Blob, and uriVL::Contour_I.
Definition at line 579 of file DrawableObject2D.cpp.
References boundRect_, getBoundRect(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), getValidRect(), uriVL::ImageRect::getWidth(), setBoundRect_(), setValidRect(), and uriVL::ImageRect::translate().
Referenced by uriVL::ImageTransformation::translate(), uriVL::Blob::translate(), translate(), uriVL::ManualStitcher::translateImage(), and uriVL::ImageTransformation::translateInPlace().
 {
     //  Needed to accomodate the child classes that don't maintain their bounding
         //      rectangle at all times: forces recomputation for bounding rect if needed
     const ImageRect* theRect = getBoundRect();
     setBoundRect_(theRect->getLeft() + dx, theRect->getTop() + dy,
                                  theRect->getWidth(), theRect->getHeight());
         boundRect_.translate(dx, dy);
     //  Same thing with valid rectangle
     theRect = getValidRect();
     setValidRect(theRect->getLeft() + dx, theRect->getTop() + dy,
                                  theRect->getWidth(), theRect->getHeight());
 }
void DrawableObject2D::translate (float dx = 0.f, float dy = 0.f) virtual
Translates the raster image by the specified amount.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation does not result in a reallocation of the image's base raster, but the sifted raster will be reallocated.
Parameters
dx horizontal displacement of the image's origin
dy vertical displacement of the image's origin
Reimplemented in uriVL::Blob, uriVL::Contour_I, and uriVL::Contour_F.
Definition at line 595 of file DrawableObject2D.cpp.
References translate().
 {
         translate(static_cast<int>(dx+0.5f), static_cast<int>(dy+0.5f));
 }
Member Data Documentation
bool uriVL::DrawableObject2D::boundingRectIsUpToDate_ mutable private
Indicates whether the bonding box stored is valid.
This boolean is modified by the calculation of the bounding box (true), the addition of a new segment to the contour force, and some operations that modifes the contour force (e.g. erosion).
Definition at line 822 of file DrawableObject2D.h.
Referenced by getBoundRect(), and setBoundingRectIsUpToDate_().
ImageRect uriVL::DrawableObject2D::boundRect_ mutable private
Bounding rectangle for this drawable object.
This rectangle defines the dimensions of the space actually allocated to store this raster image. The upper left corner of the rectangle is not necessarily at (0,0).
See also
validRect_
getBoundRect
getValidRect
getShiftedRaster2D
Definition at line 785 of file DrawableObject2D.h.
Referenced by uriVL::RasterImage_HSV24::allocateRaster2D_(), boundRectIsEmpty(), coincidesWith(), contains(), uriVL::RasterImage_HSV24::deleteShiftedRaster2D_(), getBottom(), getBoundRect(), getHeight(), getLeft(), getRight(), uriVL::RasterImage_HSV24::getShiftedHue2D(), uriVL::RasterImage_HSV24::getShiftedSat2D(), uriVL::RasterImage_HSV24::getShiftedVal2D(), getTop(), getUpperLeft(), getValidRect(), getWidth(), isContainedBy(), operator=(), overlaps(), uriVL::RasterImage_HSV24::RasterImage_HSV24(), render(), setBoundRect(), and translate().
ImagePoint_F uriVL::DrawableObject2D::centerOfMass_ mutable private
The contour's ccenter of mass.
See also
centerOfMassIsUpToDate
Definition at line 813 of file DrawableObject2D.h.
Referenced by getCenterOfMass().
bool uriVL::DrawableObject2D::centerOfMassIsUpToDate_ mutable private
Indicates whether the centroid coordinates stored are valid.
This boolean is modified by the calculation of the centroid (true), the addition of a new segment to the contour force, or any other operation that modifes the contour force (e.g. fill inner holes).
Definition at line 847 of file DrawableObject2D.h.
Referenced by getCenterOfMass(), and setCenterOfMassIsUpToDate_().
ImagePoint_F uriVL::DrawableObject2D::centroid_ mutable private
The contour's centroid.
See also
centroidIsUpToDate_
Definition at line 808 of file DrawableObject2D.h.
Referenced by getCentroid().
bool uriVL::DrawableObject2D::centroidIsUpToDate_ mutable private
Indicates whether the centroid coordinates stored are valid.
This boolean is modified by the calculation of the centroid (true), the addition of a new segment to the contour force, or any other operation that modifes the contour force (e.g. fill inner holes).
Definition at line 838 of file DrawableObject2D.h.
Referenced by getCentroid(), and setCentroidIsUpToDate_().
float uriVL::DrawableObject2D::color_[4] private
The object's rendering color.
Definition at line 949 of file DrawableObject2D.h.
Referenced by DrawableObject2D(), getColor(), and setColor().
bool DrawableObject2D::defaultDimensionsHaveChangedSinceLastRender_ = true static private
flag used to minimize the number of times the scaledXXX_ variables are recomputed prior to a render
Definition at line 981 of file DrawableObject2D.h.
Referenced by render(), and setDefaultWindowDimensions().
int DrawableObject2D::defaultWindowHeight_ = -1 static private
Default rendering window height for all drowable objects.
Proper rendering (scaled in particular) requires knowledge of the dimensions of the rendering context. It is possible to assigne each DrawableObject2D individual rendering dimensions, otherwise this default height is used.
Definition at line 975 of file DrawableObject2D.h.
Referenced by getWindowHeight(), and setDefaultWindowDimensions().
int DrawableObject2D::defaultWindowWidth_ = -1 static private
Default rendering window height for all drawable objects.
Proper rendering (scaled in particular) requires knowledge of the dimensions of the rendering context. It is possible to assigne each DrawableObject2D individual rendering dimensions, otherwise this default height is used.
Definition at line 968 of file DrawableObject2D.h.
Referenced by getWindowWidth(), and setDefaultWindowDimensions().
bool uriVL::DrawableObject2D::dimensionsHaveChangedSinceLastRender_ mutable private
flag used to minimize the number of times the scaledXXX_ variables are recomputed prior to a render
Definition at line 887 of file DrawableObject2D.h.
Referenced by render(), setBoundingRectIsUpToDate_(), and setWindowDimensions().
DrawableInformationType uriVL::DrawableObject2D::drawableInfoType_ private
Stores the type of information (as opposed to "data type" stored in the drawable object.
See also
DrawableInformationType
Definition at line 894 of file DrawableObject2D.h.
Referenced by getDrawableInformationType(), and setDrawableInformationType().
GLfloat* uriVL::DrawableObject2D::frameColor_ private
Color used for drawing a frame for the image when it is rendered.
This color is only used if mustDrawFrame_ is set to true.
See also
setFrameColor
setDrawFrame
mustDrawFrame_
Definition at line 934 of file DrawableObject2D.h.
Referenced by DrawableObject2D(), operator=(), render(), setFrameColor(), and ~DrawableObject2D().
bool uriVL::DrawableObject2D::hasIndivWindowDimensions_ private
Indicate whether individual rendering dimensions have been defined for this object.
Definition at line 911 of file DrawableObject2D.h.
Referenced by getWindowHeight(), getWindowWidth(), hasIndividualWindowDimensions(), operator=(), render(), and setWindowDimensions().
bool uriVL::DrawableObject2D::isRenderedScaled_ mutable private
True when the image should be rendered at a scale other than 1.
See also
scaleX_
scaleY_
Definition at line 865 of file DrawableObject2D.h.
Referenced by operator=(), and setRenderingScale().
bool uriVL::DrawableObject2D::mustDrawFrame_ private
True when a frame should be drawn around the image when it is rendered.
This frame has the color stored in frameColor_ or black if frameColor_ is null.
See also
frameColor_
mustDrawValidDataFrame_
Definition at line 945 of file DrawableObject2D.h.
Referenced by operator=(), render(), and setDrawFrame().
bool uriVL::DrawableObject2D::mustDrawValidDataFrame_ private
True when a frame should be drawn around the image's valid data rectangle when it is rendered.
This frame has the inverse of the color stored in frameColor_ or white if frameColor_ is null.
See also
frameColor_
Definition at line 960 of file DrawableObject2D.h.
Referenced by operator=(), render(), and setDrawValidDataFrame().
float uriVL::DrawableObject2D::renderZ_ private
Depth at which this object is to be rendered.
Since the image is rendered into a window by use of the OpenGL function glDrawPixels, under orthographic projection, we must set a depth for this rendering. This way, we will be able to overlay vector graphics on the image (e.g. edge information, intensity gradient, contours, etc.)
See also
render
setRenderDepth
Definition at line 924 of file DrawableObject2D.h.
Referenced by operator=(), render(), and setRenderDepth().
int uriVL::DrawableObject2D::scaledBottom_ mutable private
y coordinate of the object's lower-right corner when rendered scaled
Definition at line 882 of file DrawableObject2D.h.
Referenced by render().
int uriVL::DrawableObject2D::scaledLeft_ mutable private
x coordinate of the object's upper-left corner when rendered scaled
Definition at line 869 of file DrawableObject2D.h.
Referenced by render().
int uriVL::DrawableObject2D::scaledRight_ mutable private
x coordinate of the object's lower-right corner when rendered scaled
Definition at line 877 of file DrawableObject2D.h.
Referenced by render().
int uriVL::DrawableObject2D::scaledTop_ mutable private
y coordinate of the object's upper-left corner when rendered scaled
Definition at line 873 of file DrawableObject2D.h.
Referenced by render().
float uriVL::DrawableObject2D::scaleX_ mutable private
Horizontal scale at which this image is to be rendered.
Definition at line 852 of file DrawableObject2D.h.
Referenced by computeScaledCorners_(), getRenderingScaleX(), operator=(), render(), and setRenderingScale().
float uriVL::DrawableObject2D::scaleY_ mutable private
Vertical scale at which this image is to be rendered.
Definition at line 857 of file DrawableObject2D.h.
Referenced by computeScaledCorners_(), getRenderingScaleY(), operator=(), render(), and setRenderingScale().
ImageRect uriVL::DrawableObject2D::validRect_ mutable private
Bounding rectangle of the valid data region for this drawable object.
This rectangle defines the subregion of the bounding rectangle (boundRect_) that contains valid data. For example, when a gaussian filter is applied to a raster image, the processed image's valid data rectangle is smaller than that of the input image (we don't use padding for filtering operations). Rather than reallocating an image at the smaller dimensions, we simply update the validaRect_ rectangle.
See also
boundRect_
getBoundRect
getValidRect
getShiftedRaster2D
Definition at line 802 of file DrawableObject2D.h.
Referenced by getValidRect(), operator=(), render(), and setValidRect().
bool uriVL::DrawableObject2D::validRectIsUpToDate_ mutable private
Indicates whether the bonding box stored is valid.
This boolean is modified by the calculation of the bounding box (true), the addition of a new segment to the contour force, and some operations that modifes the contour force (e.g. erosion).
Definition at line 830 of file DrawableObject2D.h.
Referenced by getValidRect(), and setValidRectIsUpToDate_().
int uriVL::DrawableObject2D::windowHeight_ private
Individual rendering window height for this object.
Proper rendering (scaled in particular) requires knowledge of the dimensions of the rendering context.
Definition at line 906 of file DrawableObject2D.h.
Referenced by getWindowHeight(), getWindowWidth(), and setWindowDimensions().
int uriVL::DrawableObject2D::windowWidth_ private
Individual rendering window width for this object.
Proper rendering (scaled in particular) requires knowledge of the dimensions of the rendering context.
Definition at line 900 of file DrawableObject2D.h.
Referenced by getWindowWidth(), and setWindowDimensions().
The documentation for this class was generated from the following files:
DrawableObject2D.h
DrawableObject2D.cpp