URIVisionLibrary: uriVL::ImageOperator Class Reference
uriVL::ImageOperator Class Reference abstract
Virtual parent class for all image operators (operators that are applied to a raster image and produce a raster image as their output).
#include <ImageOperator.h>
Public Member Functions
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual RasterImage * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a RasterImage.
virtual RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image, returns the result as a RasterImage.
virtual void applyInto (const RasterImage *imgIn, RasterImage *imgOut)=0
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)=0
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
const ImageOperator & operator= (const ImageOperator &obj)
Copy operator: disabled.
Private Attributes
ImageRect * rect_
Image rectangle (with its origina at the image pixel) over which the operator is calculated.
bool isIntegerOperator_
true if the operator is an "integer" operator
ConversionFromFloatMode floatConversionMode_
Indicates how the values calculated are to be converted into unsigned char values.
Detailed Description
Virtual parent class for all image operators (operators that are applied to a raster image and produce a raster image as their output).
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 33 of file ImageOperator.h.
Constructor & Destructor Documentation
ImageOperator::~ImageOperator (void) virtual
Destructor.
Definition at line 75 of file ImageOperator.cpp.
References rect_.
 {
         delete rect_;
 }
ImageOperator::ImageOperator (bool isIntOperator = false, ConversionFromFloatMode mode = kSignedFloat) protected
Constructor.
Except for the conversion mode, this constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
            @param  isIntOperator   true if this operator produces only integer output
Parameters
mode indicates the expected range of values for the output of this operator. This will be the mode assigned by default to all "float" raster images produced by the operator.
Definition at line 28 of file ImageOperator.cpp.
                         :       rect_(NULL),
                                 isIntegerOperator_(isIntOperator),
                                 floatConversionMode_(mode)
 {
 }
ImageOperator::ImageOperator (const ImageRect * theRect, bool isIntOperator = false, ConversionFromFloatMode mode = kSignedFloat) protected
Sets the image rectangle this operator will work on.
Parameters
theRect image rectangle this operator will work on
isIntOperator true if this operator produces only integer output
mode indicates the expected range of values for the output of this operator. This will be the mode assigned by default to all "float" raster images produced by the operator.
Definition at line 36 of file ImageOperator.cpp.
                         :       rect_(new ImageRect(theRect)),
                                 isIntegerOperator_(isIntOperator),
                                 floatConversionMode_(mode)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageOperator constructor");
         throw e;
 }
ImageOperator::ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator = false, ConversionFromFloatMode mode = kSignedFloat) protected
Sets the image rectangle this operator will work on.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
isIntOperator true if this operator produces only integer output
mode indicates the expected range of values for the output of this operator. This will be the mode assigned by default to all "float" raster images produced by the operator.
Definition at line 48 of file ImageOperator.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
                         :       rect_(new ImageRect(theLeft, theTop, theWidth, theHeight)),
                                 isIntegerOperator_(isIntOperator),
                                 floatConversionMode_(mode)
 {
     FAIL_CONDITION( (theLeft > theTop) || (theWidth < 0) || (theHeight < 0),
                     kInvalidParameterError,
                     "Invalid dimensions passed to ImageOperator constructor.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageOperator constructor");
         throw e;
 }
ImageOperator::ImageOperator (const ImageOperator & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 64 of file ImageOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       rect_(NULL),
                                 isIntegerOperator_(true),
                                 floatConversionMode_(theObj.floatConversionMode_)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageOperator copy constructor not implemented.");
 }
Member Function Documentation
virtual void uriVL::ImageOperator::applyInto (const RasterImage * imgIn, RasterImage * imgOut) pure virtual
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
This function will be overloaded by subclasses of ImageOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implemented in uriVL::ColorGaussianFilter_I, uriVL::GaussianFilter_I, uriVL::ColorGaussianFilter_F, uriVL::GaussianFilter_F, uriVL::ImageLaplacian_Sobel, uriVL::ImageLaplacian_Gaussian_I, uriVL::ImageLaplacian_Gaussian_F, uriVL::ColorMedianFilter_I, uriVL::ColorMedianFilter_F, uriVL::MedianFilter_F, uriVL::MedianFilter_I, and uriVL::NonMaximumSuppressor.
virtual void uriVL::ImageOperator::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) pure virtual
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
This function will be overloaded by subclasses of ImageOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implemented in uriVL::ColorGaussianFilter_I, uriVL::GaussianFilter_I, uriVL::ColorGaussianFilter_F, uriVL::GaussianFilter_F, uriVL::ImageLaplacian_Sobel, uriVL::ImageLaplacian_Gaussian_I, uriVL::ImageLaplacian_Gaussian_F, uriVL::ColorMedianFilter_I, uriVL::ColorMedianFilter_F, uriVL::MedianFilter_F, uriVL::MedianFilter_I, and uriVL::NonMaximumSuppressor.
virtual RasterImage* uriVL::ImageOperator::applyTo (const RasterImage * imgIn) pure virtual
Applies this operator to an image, returns the result as a RasterImage.
This function will be overloaded by subclasses of ImageOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implemented in uriVL::ColorGaussianFilter_I, uriVL::GaussianFilter_I, uriVL::ColorGaussianFilter_F, uriVL::GaussianFilter_F, uriVL::ImageLaplacian_Sobel, uriVL::ImageLaplacian_Gaussian_I, uriVL::ImageLaplacian_Gaussian_F, uriVL::ColorMedianFilter_I, uriVL::ColorMedianFilter_F, uriVL::MedianFilter_F, uriVL::MedianFilter_I, and uriVL::NonMaximumSuppressor.
virtual RasterImage* uriVL::ImageOperator::applyTo (const RasterImage * imgIn, const ImageRect * theRect) pure virtual
Applies this operator to an image, returns the result as a RasterImage.
This function will be overloaded by subclasses of ImageOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the RasterImage obtained by applying the operator to imgIn
Implemented in uriVL::ColorGaussianFilter_I, uriVL::GaussianFilter_I, uriVL::ColorGaussianFilter_F, uriVL::GaussianFilter_F, uriVL::ImageLaplacian_Sobel, uriVL::ImageLaplacian_Gaussian_I, uriVL::ImageLaplacian_Gaussian_F, uriVL::ColorMedianFilter_I, uriVL::ColorMedianFilter_F, uriVL::MedianFilter_F, uriVL::MedianFilter_I, and uriVL::NonMaximumSuppressor.
ConversionFromFloatMode ImageOperator::getFloatConversionMode (void) const
Returns the image operator's conversion mode.
Returns
conversion mode for this image operator
See also
setFloatConversionMode
floatConversionMode_
Definition at line 114 of file ImageOperator.cpp.
References floatConversionMode_.
Referenced by uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_F::applyInto(), and uriVL::ColorGaussianFilter_I::applyInto().
 {
     return floatConversionMode_;
 }
int ImageOperator::getHeight (void) const
Returns the height of this operator's operation rectangle.
Returns
height of this operator's operation rectangle
Definition at line 150 of file ImageOperator.cpp.
References uriVL::ImageRect::getHeight(), and rect_.
 {
     return rect_->getHeight();
 }
const ImageRect * ImageOperator::getRect (void) const
Returns a pointer to this operator's operation rectangle.
Returns
a pointer to this operator's operation rectangle
Definition at line 140 of file ImageOperator.cpp.
References rect_.
Referenced by uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ColorGaussianFilter::getHeight(), and uriVL::ColorGaussianFilter::getWidth().
 {
         return rect_;
 }
int ImageOperator::getWidth (void) const
Returns the width of this operator's operation rectangle.
Returns
width of this operator's operation rectangle
Definition at line 145 of file ImageOperator.cpp.
References uriVL::ImageRect::getWidth(), and rect_.
Referenced by uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::GaussianFilter_F::initializeFilter_(), and uriVL::GaussianFilter_I::initializeFilter_().
 {
     return rect_->getWidth();
 }
bool ImageOperator::isFloatOperator (void) const
returns true if the filter is a "float" operator
Returns
true if the filter is a "float" operator
Definition at line 104 of file ImageOperator.cpp.
References isIntegerOperator_.
 {
     return !isIntegerOperator_;
 }
bool ImageOperator::isIntegerOperator (void) const
returns true if the filter is an "integer" operator
Returns
true if the filter is an "integer" operator
Definition at line 99 of file ImageOperator.cpp.
References isIntegerOperator_.
 {
     return isIntegerOperator_;
 }
const ImageOperator & ImageOperator::operator= (const ImageOperator & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 81 of file ImageOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageOperator copy operator not implemented.");
         return *this;
 }
void ImageOperator::setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
Parameters
theMode conversion mode for this image operator
See also
getFloatConversionMode
floatConversionMode_
Definition at line 109 of file ImageOperator.cpp.
References floatConversionMode_.
Referenced by uriVL::ColorGaussianFilter_I::applyInto().
 {
     floatConversionMode_ = theMode;
 }
void ImageOperator::setRect (const ImageRect * theRect) protected
Sets the rectangle on which this operator uh...
operates.
Parameters
theRect image rectangle this operator will work on
Definition at line 133 of file ImageOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by uriVL::ColorGaussianFilter::ColorGaussianFilter(), and uriVL::GaussianFilter::GaussianFilter().
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageOperator copy operator not implemented.");
 }
void ImageOperator::setRect (int theLeft, int theTop, int theWidth, int theHeight) protected
Sets the rectangle on which this operator uh...
operates.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Definition at line 120 of file ImageOperator.cpp.
References FAIL_CONDITION, uriVL::kImageProcessingError, rect_, and uriVL::ImageRect::setRect().
 {
         FAIL_CONDITION( (theWidth < 0) || (theHeight < 0),
                                         kImageProcessingError,
                                         "Error in the computation of MedianFilter_F::applyTo");
         if (rect_ == NULL)
                         rect_ = new ImageRect(theLeft, theTop, theWidth, theHeight);
         else
                 rect_->setRect(theLeft, theTop, theWidth, theHeight);
 }
Member Data Documentation
ConversionFromFloatMode uriVL::ImageOperator::floatConversionMode_ private
Indicates how the values calculated are to be converted into unsigned char values.
This variable is set by the constructor. Default value is kSignedFloat
See also
getFloatConversionMode
setFloatConversionMode
Definition at line 252 of file ImageOperator.h.
Referenced by getFloatConversionMode(), uriVL::ImageLaplacian::ImageLaplacian(), and setFloatConversionMode().
bool uriVL::ImageOperator::isIntegerOperator_ private
true if the operator is an "integer" operator
Definition at line 244 of file ImageOperator.h.
Referenced by uriVL::ImageLaplacian::ImageLaplacian(), uriVL::ImageLaplacian_Gaussian_F::ImageLaplacian_Gaussian_F(), uriVL::ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I(), isFloatOperator(), and isIntegerOperator().
ImageRect* uriVL::ImageOperator::rect_ private
Image rectangle (with its origina at the image pixel) over which the operator is calculated.
Definition at line 239 of file ImageOperator.h.
Referenced by getHeight(), getRect(), getWidth(), uriVL::ImageLaplacian_Gaussian_F::ImageLaplacian_Gaussian_F(), uriVL::ImageLaplacian_Gaussian_I::ImageLaplacian_Gaussian_I(), setRect(), uriVL::ImageLaplacian_Gaussian_F::~ImageLaplacian_Gaussian_F(), and ~ImageOperator().
The documentation for this class was generated from the following files:
ImageOperator.h
ImageOperator.cpp