URIVisionLibrary: uriVL::ImageWarper_GL Class Reference
uriVL::ImageWarper_GL Class Reference
holds the records of 2D matching result
#include <ImageWarper_GL.h>
Public Member Functions
ImageWarper_GL (InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Creates a new OpenGL ImageWarper whose grid points conform to the displacement modes specified.
~ImageWarper_GL (void)
Destructor.
void setImages (const RasterImage *imgIn, RasterImage *imgOut)
Defines an input image and an output image(for multiple warpings).
void setGrid (int gridRows, int gridCols)
Sets the dimensions of the warping grid (should be at least 3x3)
void getImageSuitableDimensions (int imgWidth, int imgHeight, int *lowImgWidth, int *lowImgHeight, int *highImgWidth, int *highImgHeight) const
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
int getEffectivePixelsPerRow (const int nominalWidth) const
Returns the "true" number of pixels on a row of the input image (possibly larger than the nominal width, due to row padding).
Public Member Functions inherited from uriVL::ImageWarper
ImageWarper (ImageWarperType type, const InnerWarpingMode innerMode=INNER_FREE, const BorderWarpingMode outerMode=BORDER_FREE)
Creates a new ImageWarper whose grid points conform to the displacement modes specified.
virtual ~ImageWarper (void)
Destructor.
ImageWarperType getWarperType (void) const
Indicates the type of warping algorithm used by this warper (e.g.
float ***const newWarpingGrid (void) const
Returns a new grid of points allocated at the grid dimensions of this warper and initialized as a regular rectangular grid.
const RasterImage * getInputImage (void) const
Returns the warper's input image.
RasterImage * getOutputImage (void) const
Returns the warper's output image.
virtual bool isValidDisplacement (float ***xy) const
Indicates whether a point grid is consistent with the displacement modes of of this warper.
void warp (float ***xy, const RasterImage *imgIn, RasterImage *imgOut)
Warps the image.
void warp (float ***xy)
warp the image using the new grid point coordinates specified
int getNbGridRows (void) const
Returns the number of rows on this warper's grid.
int getNbGridCols (void) const
Returns the number of columns on this warper's grid.
bool isSetUp (void) const
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
InnerWarpingMode getInnerWarpingMode (void) const
Returns the warper's inner warping mode.
BorderWarpingMode getBorderWarpingMode (void) const
Returns the warper's border warping mode.
Protected Member Functions
void warp_ (float ***xy)
warp the (pre-specified) input image into the (prespecified) output image using the new grid point coordinates specified
ImageWarper_GL (const ImageWarper_GL &obj)
Copy constructor (disabled)
const ImageWarper_GL & operator= (const ImageWarper_GL &obj)
Copy operator: disabled.
Protected Member Functions inherited from uriVL::ImageWarper
bool isValidDisplacement_ (const float ***const xy) const
Checks whether the grid coordinates specified conform to the grid displacement modes set.
void allocateGrids_ (void)
Allocates new grids of points at the (pre-approved) dimensions.
void initializeGrids_ (void)
Initializes the grids once its dimensions and that of the image are known.
void deleteGrids_ (void)
Deletes the pre-allocates grids of points (grid resize or destruction)
ImageWarper (const ImageWarper &obj)
Copy constructor (disabled)
const ImageWarper & operator= (const ImageWarper &obj)
Copy operator: disabled.
Protected Attributes
GLuint textureID_
Stores the OpenGL id for the texture map used for the warping.
GLfloat *** texturePoint_
list of uv points
Protected Attributes inherited from uriVL::ImageWarper
ImageWarperType warperType_
Indicates the type of warping algorithm used by this warper (e.g.
InnerWarpingMode innerMode_
Warping mode if the grid's inner points.
BorderWarpingMode outerMode_
Warping mode if the grid's border points.
bool isSetUp_
Indicates whether the input image, output image, and grids are all correctly set up and mutually compatible.
int imgHeight_
Height of the image to warp.
int imgWidth_
Width of the image to warp.
int effImgWidth_
Effective width of the image to warp (taking into account row padding)
BaseRasterType rasterType_
Type of the input image's raster (only RGBa32 and gray supported so far)
int gridRows_
number of rows of the warping grid
int gridCols_
number of cols of the warping grid
float *** xy_
gridRows_ x gridCols_ array of 2D grid points
float *** xy0_
gridRows_ x gridCols_ array of original 2D grid points
float verticalSpacing_
distance between vertical grid points
float horizontalSpacing_
distance between horizontal grid points
const RasterImage * imgIn_
texture image
RasterImage * imgOut_
output image
const unsigned char * imgIn1D_
1D raster of the texture image
unsigned char * imgOut1D_
1D raster of output image
Detailed Description
holds the records of 2D matching result
Definition at line 28 of file ImageWarper_GL.h.
Constructor & Destructor Documentation
ImageWarper_GL::ImageWarper_GL (InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE)
Creates a new OpenGL ImageWarper whose grid points conform to the displacement modes specified.
If modes other than INNER_FREE and BORDER_FREE are specified, then the warper will verify that the point coordinates specified are conform to its set motion modes prior to applying a warping.
Parameters
gridMode grid warping mode for this warper
Definition at line 30 of file ImageWarper_GL.cpp.
     :   ImageWarper(GL_WARPER, innerMode, outerMode),
                 //
                 textureID_(0),
                 texturePoint_(NULL)
 {
 }
ImageWarper_GL::~ImageWarper_GL (void)
Destructor.
Definition at line 57 of file ImageWarper_GL.cpp.
References uriVL::ImageWarper::gridCols_, uriVL::ImageWarper::gridRows_, textureID_, and texturePoint_.
 {
     if (textureID_ != 0)
     {
         for (int i=0; i<gridRows_; i++)
         {
                 for (int j=0; j<gridCols_; j++)
                         delete []texturePoint_[i][j];
                 delete []texturePoint_[i];
         }
         delete []texturePoint_;
         }
     if (textureID_ > 0)
         glDeleteTextures (1, &textureID_);
 }
ImageWarper_GL::ImageWarper_GL (const ImageWarper_GL & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 40 of file ImageWarper_GL.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
     :   ImageWarper(GL_WARPER),
                 //
                 textureID_(0),
                 texturePoint_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageWarper_GL copy constructor not implemented.");
 }
Member Function Documentation
int ImageWarper_GL::getEffectivePixelsPerRow (const int nominalWidth) const virtual
Returns the "true" number of pixels on a row of the input image (possibly larger than the nominal width, due to row padding).
Parameters
nominalWidth nominal width of the input image
Returns
"true" width of the image stored
Implements uriVL::ImageWarper.
Definition at line 288 of file ImageWarper_GL.cpp.
 {
     int tempDim, loWidth, hiWidth, effLoWidth, effHiWidth;
     //  We find the largest power of two lower than or equal to the input width
     tempDim = nominalWidth;
     effLoWidth = 1;
     tempDim--;
     while (tempDim != 0)
     {
         tempDim /= 2;
         effLoWidth *= 2;
     }
     effHiWidth = 2*effLoWidth;
     #if URIVL_USE_QUICKTIME && URIVL_OS_MACOS
         hiWidth = effHiWidth - 4;
         loWidth = effLoWidth - 4;
     #else
         hiWidth = effHiWidth;
         loWidth = effLoWidth;
     #endif
     if (nominalWidth == loWidth)
         return effLoWidth;
     else if (nominalWidth == hiWidth)
         return effHiWidth;
     else
         return -1;
 }
void ImageWarper_GL::getImageSuitableDimensions (int imgWidth, int imgHeight, int * lowImgWidth, int * lowImgHeight, int * highImgWidth, int * highImgHeight) const virtual
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
Some warpers require specific image dimensions/ratios (e.g. a GL warper only takes 2^n x 2^n images). Furthermore, QuickTime GraphWorld rasters are padded on some platforms. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
If you want to warp an image, it is therefore recommended that you check what are the closest suitable dimensions for the type of warper you are using.
Parameters
imgWidth input image width
imgHeight input image height
lowImgWidth closest lower suitable width
lowImgHeight closest lower suitable height
highImgWidth closest higher suitable width
highImgHeight closest higher suitable height
Implements uriVL::ImageWarper.
Definition at line 179 of file ImageWarper_GL.cpp.
Referenced by initImagesAndWarper().
 {
     int tempDim, lowWidth, lowHeight;
     //  We find the largest power of two lower than or equal to the input width
     tempDim = imgWidth;
     lowWidth = 1;
     tempDim--;
     while (tempDim != 0)
     {
         tempDim /= 2;
         lowWidth *= 2;
     }
     //  We do the same thing for the height
     tempDim = imgHeight,
     lowHeight = 1;
     tempDim--;
     while (tempDim != 0)
     {
         tempDim /= 2;
         lowHeight *= 2;
     }
     //  We determine the low and high height dimensions
     *lowImgHeight = lowHeight;
     if (imgHeight == lowHeight)
         *highImgHeight = lowHeight;
     else
         *highImgHeight = 2*lowHeight;
     //  Now, depending on the platform on which we run, we will have different
     //  lower and upper width
     //
     //  QuickTime gworlds are padded on the Mac side
     #if URIVL_USE_QUICKTIME && URIVL_OS_MACOS
         *lowImgWidth = lowWidth - 4;
         *highImgWidth = 2*lowWidth - 4;
     #else
         *lowImgWidth = lowWidth;
         if (imgHeight == lowWidth)
             *highImgWidth = lowWidth;
         else
             *highImgWidth = 2*lowWidth;
     #endif
 }
const ImageWarper_GL & ImageWarper_GL::operator= (const ImageWarper_GL & obj) protected
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 76 of file ImageWarper_GL.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageWarper_GL copy operator not implemented.");
         return *this;
 }
void ImageWarper_GL::setGrid (int gridRows, int gridCols) virtual
Sets the dimensions of the warping grid (should be at least 3x3)
Parameters
gridRows number of rows of the grid
gridCols number of columns of the grid
Reimplemented from uriVL::ImageWarper.
Definition at line 156 of file ImageWarper_GL.cpp.
References uriVL::ImageWarper::gridCols_, uriVL::ImageWarper::gridRows_, uriVL::ImageWarper::imgHeight_, uriVL::ImageWarper::imgIn1D_, uriVL::ImageWarper::imgWidth_, uriVL::ImageWarper::setGrid(), and texturePoint_.
Referenced by setImages(), and setupWarper().
 {
     ImageWarper::setGrid(gridRows, gridCols);
     float scaleU = 1.f;
     if (imgIn1D_ != NULL)
         scaleU = 1.f * imgWidth_ / imgHeight_;
     texturePoint_ = new GLfloat**[gridRows_];
         for (int i=0; i<gridRows_; i++)
     {
         texturePoint_[i] = new  GLfloat*[gridCols_];
                 for (int j=0; j<gridCols_; j++)
                 {
                         texturePoint_[i][j] = new GLfloat[2];
                     texturePoint_[i][j][0] = scaleU * j / (gridCols_ -  1);
                     texturePoint_[i][j][1] = 1.f * i / (gridRows_ -  1);
         }
         }
 }
void ImageWarper_GL::setImages (const RasterImage * imgIn, RasterImage * imgOut) virtual
Defines an input image and an output image(for multiple warpings).
Note that the dimensions of the image must be in agreement with values produced by imageEffectiveDimensions. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
Parameters
imgIn input image for (multiple) subsequent warpings
Reimplemented from uriVL::ImageWarper.
Definition at line 90 of file ImageWarper_GL.cpp.
References uriVL::ImageWarper::gridCols_, uriVL::ImageWarper::gridRows_, uriVL::ImageWarper::imgHeight_, uriVL::ImageWarper::imgIn1D_, uriVL::kGrayRaster, uriVL::kRGBa32Raster, uriVL::ImageWarper::rasterType_, setGrid(), uriVL::ImageWarper::setImages(), and textureID_.
Referenced by setupWarper().
 {
     ImageWarper::setImages(imgIn, imgOut);
     glEnable(GL_TEXTURE_2D);
     if (textureID_ > 0)
         glDeleteTextures (1, &textureID_);
         glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);     // Clear Screen And Depth Buffer
         //      gets a free identificator for the texture
         glGenTextures(1, &textureID_);
         glBindTexture(GL_TEXTURE_2D, textureID_);
     //int n = 256;
         /*
         imgIn1D_ = new unsigned char [n*n*4];
         long    idx = 0;
         for (short i=0; i<n; i++)
         {
                 idx = 4 * n * i;
                 for (short j=0; j<n; j++)
                 {
                         imgIn1D_[idx++] = (unsigned char) floor((i-n/2.)*(i-n/2.)/120. + 20);
                         imgIn1D_[idx++] = (unsigned char) j/4 + 30;
                         imgIn1D_[idx++] = (unsigned char) floor(127*(cos(0.06*i)*sin(0.1*j)+0.5));
                         imgIn1D_[idx++] = (unsigned char) 255;
                 }
         }
         */
         switch (rasterType_)
         {
                 case kGrayRaster:
                         glTexImage2D(GL_TEXTURE_2D, 0,  GL_LUMINANCE,
                                                                                         imgHeight_,
                                                                                         imgHeight_,
                                                                                         0,
                                                                                         GL_LUMINANCE, GL_UNSIGNED_BYTE,
                                                                                         imgIn1D_);
                         break;
                 case kRGBa32Raster:
                         glTexImage2D(GL_TEXTURE_2D, 0,  GL_RGBA,
                                                                                         imgHeight_,
                                                                                         imgHeight_,
                                                                                         0,
                                                                                         GL_RGBA, GL_UNSIGNED_BYTE,
                                                                                         imgIn1D_);
                         break;
                 default:
                         break;
         }
         glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
         glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
         if ((gridRows_ != 0) && (gridCols_ != 0))
             setGrid(gridRows_, gridCols_);
 }
void ImageWarper_GL::warp_ (float *** xy) protected virtual
warp the (pre-specified) input image into the (prespecified) output image using the new grid point coordinates specified
Parameters
xy new coordinates of the grid points
Implements uriVL::ImageWarper.
Definition at line 236 of file ImageWarper_GL.cpp.
References uriVL::ImageWarper::gridCols_, uriVL::ImageWarper::gridRows_, uriVL::ImageWarper::imgHeight_, uriVL::ImageWarper::imgOut1D_, uriVL::kGrayRaster, uriVL::kRGBa32Raster, uriVL::ImageWarper::rasterType_, textureID_, and texturePoint_.
 {
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);     // Clear Screen And Depth Buffer
         glEnable(GL_TEXTURE_2D);
         glBindTexture(GL_TEXTURE_2D, textureID_);
         glColor4f(1.f, 1.f, 1.f, 1.f);
         //      map the texture to each square
         for (int i=0; i<gridRows_ - 1; i++)
         {
                 for (int j=0; j<gridCols_ - 1; j++)
                 {
                         glBegin(GL_POLYGON);
                                 glTexCoord2fv(texturePoint_[i][j]);
                                 glVertex2fv(xy[i][j]);
                                 glTexCoord2fv(texturePoint_[i+1][j]);
                                 glVertex2fv(xy[i+1][j]);
                                 glTexCoord2fv(texturePoint_[i+1][j+1]);
                                 glVertex2fv(xy[i+1][j+1]);
                                 glTexCoord2fv(texturePoint_[i][j+1]);
                                 glVertex2fv(xy[i][j+1]);
                         glEnd();
                 }
         }
         // read from front buffer
         glReadBuffer(GL_BACK);
         switch (rasterType_)
         {
                 case kGrayRaster:
                         // read pixel data
                         glReadPixels(0, 0, imgHeight_, imgHeight_, GL_LUMINANCE, GL_UNSIGNED_BYTE, imgOut1D_);
                         break;
                 case kRGBa32Raster:
                         // read pixel data
                         glReadPixels(0, 0, imgHeight_, imgHeight_, GL_RGBA, GL_UNSIGNED_BYTE, imgOut1D_);
                         break;
                 default:
                         break;
         }
         glDisable(GL_TEXTURE_2D);
 }
Member Data Documentation
GLuint uriVL::ImageWarper_GL::textureID_ protected
Stores the OpenGL id for the texture map used for the warping.
Definition at line 98 of file ImageWarper_GL.h.
Referenced by setImages(), warp_(), and ~ImageWarper_GL().
GLfloat*** uriVL::ImageWarper_GL::texturePoint_ protected
list of uv points
Definition at line 102 of file ImageWarper_GL.h.
Referenced by setGrid(), warp_(), and ~ImageWarper_GL().
The documentation for this class was generated from the following files:
ImageWarper_GL.h
ImageWarper_GL.cpp