URIVisionLibrary: uriVL::ActiveContourDetector Class Reference
uriVL::ActiveContourDetector Class Reference abstract
Parent class for all implementations of active contour algorithms for seeking closed contours in an image.
#include <ActiveContourDetector.h>
Public Member Functions
ActiveContourDetector (const ImageRect *imgInRect=NULL)
Constructor.
virtual ~ActiveContourDetector (void)
Destructor.
virtual IterationStatus findContour (const RasterImage *imgIn, Contour_F *contour, const ImageRect *searchRect=NULL)=0
Finds one contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
std::list< Contour_F * > * findAllContours (const RasterImage *imgIn, const ImageRect *rect=NULL)
Finds all contours within the specified search rectangle of the input image.
const Contour_F * getContour (void) const
Returns a read-only pointer to the contour being computed (when operating in step-by-step mode).
IterationStatus getStatus (void) const
Returns the current iteration status without computing an iteration step.
virtual void renderForces (void)=0
Renders the different forces applied to the contour's vertices.
void setStepByStep (bool sbs)
Allows the user to change the mode in which the detector operate: "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
void setStepSize (int size)
When in step-by-step mode, sets the number of iterations run at each "step".
IterationStatus iterate (int n)
Aplies n iterations of the algorithm (or fewer if convergence occurs before).
bool gradientsAreLocal (void) const
Reports whether this object "owns" the various gradient rasters and vector fields and should delete them in the destructor.
float getTimeStep (void) const
Returns the value of the "time step" that scales the total force to produce a displacement.
Public Member Functions inherited from uriVL::ContourDetector
ContourDetector (void)
Constructor.
ContourDetector (const ImageRect *rect)
Constructor.
virtual ~ContourDetector (void)
Destructor.
virtual Contour_F * findContour (const RasterImage *imgIn, const ImageRect *rect=NULL)=0
Finds one contour within the specified search rectangle of the input image.
Public Member Functions inherited from uriVL::FeatureDetector
FeatureDetector (void)
Constructor.
FeatureDetector (const ImageRect *rect)
Constructor.
virtual ~FeatureDetector (void)
Destructor.
const ImageRect * getSearchRect (void) const
Returns a pointer to the ImageRect on which this object is operating.
void setSearchRect (const ImageRect *rect)
Assigns a (new) search rectangle to this object.
virtual ImageFeature * findFeatureAbout (const RasterImage *img, const ImagePoint *searchStart, const ImageRect *searchRect=NULL)=0
Find one image feature near the designated point.
virtual FeatureList * findAllFeatures (const RasterImage *img, const ImageRect *searchRect=NULL)=0
Find all image feature within a search rectangle.
Protected Member Functions
void calculateInternalForce_ (void)
Calculates the internal force that preserves the quality of the contour (points regularly spread out on the contour, minimization of curvature)
void setInternalCoeff_ (float internalCoeff)
Called by a subclass to set the coeefficient of the internal force in the computation of the total force.
void setGradientRasters_ (VectorField_F *grad, RasterImage_gray_F *normSqrd)
This function should be called for video-rate applications that must re-use the same rasters for performance optimization purposes.
void setContour_ (Contour_F *contour)
Assigns a contour object, typically, to start an iteration.
Contour_F * getContour_ (ReadWriteStatus rw)
Returns a writable pointer to the contour force's geometric contour (list of points)
ActiveContourDetector (const ActiveContourDetector &obj)
Copy constructor (disabled)
const ActiveContourDetector & operator= (const ActiveContourDetector &obj)
Copy operator: disabled.
virtual IterationStatus oneStep_ (void)=0
Applies one iteration of the contour determination algorithm.
Protected Attributes
VectorField_F * imageGradient_
Stores the gradient of the image being operated on.
RasterImage_gray_F * normSqrdOfGrad_
Stores as a gray-level image the norm squared of gradient of the image being operated on.
ColorImageGradient_Gaussian_F * colorImageGradientProcessor_
Used when processing a color image.
ImageGradient_Gaussian_F * grayImageGradientProcessor_
Used when processing a gray-level image.
Contour_F * contour_
Pointer to the Contour_F object being worked on by this object.
ContourForce * totalForce_
Sum of all forces applied to each vertex of the active contour.
ContourForce * internalForce_
Internal, "goodness" component of the force applied to each vertex of the active contour.
IterationStatus status_
Status of the current iteration.
float internalCoeff_
Coefficient of the internal force in the computation of the total force.
float gaussianGradientScale_
Scale of the gradient of Gaussian.
float alphaFirstDeriv_
Energy contributed by the distance between control points to the internal force.
float betaSecondDeriv_
Energy contributed by the curvature of the snake to the internal force.
float maxInternalForce_
Maximimum magnitude of the internal force.
float timeStep_
Time "step" in the integration of the differential equation.
float tolerance_
Convergence threshold, for whatever convergence criterion is being used.
int nbIterations_
Number of iterations done so far.
bool gradientsAreLocal_
Indicates whether the contour detector allocated its own gradient, norm of gradient, etc.
bool stepByStep_
Indicates whether the contour detector operates in "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
int stepSize_
How many integration steps to apply when in "step-by"step" mode.
bool setupCompleted_
True after the detector has run at least one iteration step, so that the iterate function can be called to iterate one or more steps.
Static Protected Attributes
static const float DEFAULT_GAUSSIAN_FILTER_SCALE = 2.0f
Default scale of the gradient of Gaussian.
static const float DEFAULT_MAX_INTERNAL_FORCE = 5.1f
Default value for the maximimum magnitude of the internal force.
static const float DEFAULT_INTERNAL_COEFF = 1.f
Default value for the internal force coefficient.
static const float DEFAULT_TIME_STEP = 0.15f
Default time step in the iteration equation, arbitrarily set.
static const float DEFAULT_TOLERANCE = (float)1E-5
Default time step in the iteration equation, arbitrarily set.
static const float DEFAULT_ALPHA_1ST_DERIV = 4.f
Default value for the energy contributed by the distance between control points.
static const float DEFAULT_BETA_2ND_DERIV = 0.1f
Default value for the energy contributed by the curvature of the snake.
Detailed Description
Parent class for all implementations of active contour algorithms for seeking closed contours in an image.
In uriVL there is no such thing as an "active contour object." There is a Contour class (a Contour object being made up of a list of ImagePoint objects) and then there is a Hierarchy of ActiveContourDetector classes, each of which implements a specific algorithm for actively adjusting the vertices of a Contour object to fit the contour of a region in an image. All ActiveContourDetector classes proceed by summing up diverse "force" components—implemented as ContourForce objects mapped to the current Contour—such as "edge force," "internal force," etc., to produce the "total force" that is applied to the vertices of the current contour. The fitting of the active contour is therefore modeled as the convergence of a diffusion equation, which requires a "time step" constant, a criterion for convergence (average displacement, maximum displacement, etc.), and a numerical threshold associated to that criterion.
Author
Clifford Manzanillo, Department of Computer Science and Statistics, URI
Chris Allen, 3DG, URI [major revision 2009]
jyh, 3DG, URI [major uriVL overhaul 2013]
Definition at line 54 of file ActiveContourDetector.h.
Constructor & Destructor Documentation
ActiveContourDetector::ActiveContourDetector (const ImageRect * imgInRect = NULL)
Constructor.
If a non-null ImageRect pointer is passed, the ActiveContourDetector will allocate accessory object (RasterImage and VectorField) at the dimensions specified by the ImageRect.
Whether or not to pass a non-null ImageRect pointer to this constructor depends on the way this object will be used:
If it's a one-shot use, then it does not make much difference, except maybe to allow to allocate all accessory objects in advance.
If the ActiveContourDetector will be used multiple times, then
If the accessory objects are computed outside of the ActiveContourDetector, (for example as part of preprocessing), then pass a null pointer to this constructor;
Otherwise, send a pointer to a valid ImageRect
Parameters
imgInRect the rectangle to work within. If a rectangle is specified, then this object will preallocate
Definition at line 46 of file ActiveContourDetector.cpp.
References contour_, INTERNAL_FORCE_DEFAULT_COLOR, internalForce_, uriVL::ContourForce::mapToContour(), uriVL::ContourForce::setNeedleColor(), uriVL::ContourForce::setRenderContour(), TOTAL_FORCE_DEFAULT_COLOR, and totalForce_.
                         :       ContourDetector(imgRect),
                                 //
                                 imageGradient_(NULL),
                                 normSqrdOfGrad_(NULL),
                                 colorImageGradientProcessor_(NULL),
                                 grayImageGradientProcessor_(NULL),
                                 //
                                 contour_(NULL),
                                 totalForce_(NULL),
                                 internalForce_(NULL),
                                 status_(IterationStatus()),
                                 //
                                 internalCoeff_(DEFAULT_INTERNAL_COEFF),
                                 gaussianGradientScale_(DEFAULT_GAUSSIAN_FILTER_SCALE),
                                 alphaFirstDeriv_(DEFAULT_ALPHA_1ST_DERIV),
                                 betaSecondDeriv_(DEFAULT_BETA_2ND_DERIV),
                                 maxInternalForce_(DEFAULT_MAX_INTERNAL_FORCE),
                                 timeStep_(DEFAULT_TIME_STEP),
                                 tolerance_(DEFAULT_TOLERANCE),
                                 //
                                 nbIterations_(0),
                                 gradientsAreLocal_(true),
                                 stepByStep_(false),
                                 stepSize_(1),
                                 setupCompleted_(false)
 {
         totalForce_->setNeedleColor(TOTAL_FORCE_DEFAULT_COLOR);
         internalForce_->setNeedleColor(INTERNAL_FORCE_DEFAULT_COLOR);
         //
         totalForce_->setRenderContour(false);
         internalForce_->setRenderContour(false);
         //
         totalForce_->mapToContour(contour_);
         internalForce_->mapToContour(contour_);
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ActiveContourDetector constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "In ActiveContourDetector constructor");
 }
ActiveContourDetector::~ActiveContourDetector (void) virtual
Destructor.
Note that the destructor does not free the Contour_F object it has a pointer to, as that object was created outside of this class and a pointer to the Contour_F passed as destination for the contour finding computation.
Definition at line 130 of file ActiveContourDetector.cpp.
References colorImageGradientProcessor_, gradientsAreLocal(), grayImageGradientProcessor_, imageGradient_, internalForce_, normSqrdOfGrad_, and totalForce_.
{
         if (colorImageGradientProcessor_)
                 delete colorImageGradientProcessor_;
         if (grayImageGradientProcessor_)
                 delete grayImageGradientProcessor_;
         if (internalForce_)
                 delete internalForce_;
         if (totalForce_)
                 delete totalForce_;
         //      only delete the gradient objects if they are local
         if (gradientsAreLocal()){
                 if (imageGradient_)
                         delete imageGradient_;
                 if (normSqrdOfGrad_)
                         delete normSqrdOfGrad_;
         }
 }
ActiveContourDetector::ActiveContourDetector (const ActiveContourDetector & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 96 of file ActiveContourDetector.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :               ContourDetector(),
                                 //
                                 imageGradient_(NULL),
                                 normSqrdOfGrad_(NULL),
                                 colorImageGradientProcessor_(NULL),
                                 grayImageGradientProcessor_(NULL),
                                 //
                                 contour_(NULL),
                                 totalForce_(NULL),
                                 internalForce_(NULL),
                                 status_(IterationStatus()),
                                 //
                                 internalCoeff_(DEFAULT_INTERNAL_COEFF),
                                 gaussianGradientScale_(DEFAULT_GAUSSIAN_FILTER_SCALE),
                                 alphaFirstDeriv_(DEFAULT_ALPHA_1ST_DERIV),
                                 betaSecondDeriv_(DEFAULT_BETA_2ND_DERIV),
                                 maxInternalForce_(DEFAULT_MAX_INTERNAL_FORCE),
                                 timeStep_(DEFAULT_TIME_STEP),
                                 tolerance_(DEFAULT_TOLERANCE),
                                 //
                                 nbIterations_(0),
                                 gradientsAreLocal_(true),
                                 stepByStep_(false),
                                 stepSize_(1),
                                 setupCompleted_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ActiveContourDetector copy constructor not implemented.");
 }
Member Function Documentation
void ActiveContourDetector::calculateInternalForce_ (void) protected
Calculates the internal force that preserves the quality of the contour (points regularly spread out on the contour, minimization of curvature)
Definition at line 282 of file ActiveContourDetector.cpp.
References DEFAULT_ALPHA_1ST_DERIV, DEFAULT_BETA_2ND_DERIV, DEFAULT_MAX_INTERNAL_FORCE, uriVL::ContourForce::getContour(), uriVL::ContourForce::getForce(), uriVL::Contour_F::getPoints(), internalForce_, and timeStep_.
Referenced by uriVL::ActiveContourDetector_balloon::oneStep_().
 {
         const list<Vector2D_F*> *internalForce = internalForce_->getForce();
         const Contour_F* contour = internalForce_->getContour();
         const list<ImagePoint_F*> *contourPts = contour->getPoints();
         list<ImagePoint_F*>::const_iterator itm2, itm1, itp1, itp2, contourEnd = contourPts->end();
         list<Vector2D_F*>::const_iterator intIter;
         float   w2 = DEFAULT_BETA_2ND_DERIV,
                         w2Times4 = 4.f*w2,
                         w2Times6 = 6.f*w2,
                         w1 = DEFAULT_ALPHA_1ST_DERIV,
                         w1Times2 = 2.f*w1;
         float   a, b, c;
         float   im2X, im1X, ip1X, ip2X, iX;
         float   im2Y, im1Y, ip1Y, ip2Y, iY;
         // begin by setting all the contour pts to the
         // correct positions
         itm2 = contourPts->end();
         itm2--;
         itm1 = itm2;
         itm2--;
         itp2 = contourPts->begin();
         itp2++;
         itp1 = itp2;
         itp2++;
         //
         intIter = internalForce->begin();
         for(list<ImagePoint_F*>::const_iterator iter = contourPts->begin(); iter != contourEnd; iter++, intIter++){
                 /*
                         The following stems from the equations below.
                         We basically loop through each point call them C, and
                         compute the 2nd and 4th derivatives by the difference of points
                         -(W1*Ci')' + (W2*Ci")" = AV
                         -W1*Ci" + W2*Ci"" = AV
                         Ci" = C(i+1) - 2 * Ci + C(i-1)
                         Ci"" = C(i+2) - 4 * C(i+1) + 6 * Ci - 4C(i-1) + C(i-2)s
                 */
                 a = -w2;
                 b = w1 + w2Times4;
                 c = -w1Times2 - w2Times6;
                 im2X = (*itm2)->getX();
                 im1X = (*itm1)->getX();
                 iX   = (*iter)->getX();
                 ip1X = (*itp1)->getX();
                 ip2X = (*itp2)->getX();
                 im2Y = (*itm2)->getY();
                 im1Y = (*itm1)->getY();
                 iY   = (*iter)->getY();
                 ip1Y = (*itp1)->getY();
                 ip2Y = (*itp2)->getY();
                 float  vectX = a * (im2X + ip2X ) + b * (im1X + ip1X ) + c * iX,
                         vectY = a * (im2Y + ip2Y ) + b * (im1Y + ip1Y ) + c * iY,
                         normVect2 = vectX*vectX + vectY*vectY;
                 if (normVect2 > DEFAULT_MAX_INTERNAL_FORCE) {
                         float scale = static_cast<float>(DEFAULT_MAX_INTERNAL_FORCE / sqrt(normVect2));
                         vectX *= scale;
                         vectY *= scale;
                 }
                 (*intIter)->setX(timeStep_ * vectX);
                 (*intIter)->setY(timeStep_ * vectY);
                 itm2 = itm1;
                 itm1 = iter;
                 itp1 = itp2;
                 itp2++;
                 if (itp2 == contourPts->end()){
                         itp2 = contourPts->begin();
                 }
         }
 }
list< Contour_F * > * ActiveContourDetector::findAllContours (const RasterImage * imgIn, const ImageRect * rect = NULL) virtual
Finds all contours within the specified search rectangle of the input image.
To be implemented by subclasses.
Parameters
imgIn the image to process
rect the rectangle within which to look for a contour.
Returns
a list of pointers to the contour objects found in the image
Implements uriVL::ContourDetector.
Definition at line 169 of file ActiveContourDetector.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ActiveContourDetector::findAllContours function not implemented.");
         return NULL;
 }
virtual IterationStatus uriVL::ActiveContourDetector::findContour (const RasterImage * imgIn, Contour_F * contour, const ImageRect * searchRect = NULL) pure virtual
Finds one contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
Parameters
imgIn image in which to look for the contour
contourIn initial contour, and also output contour
const Contour_F * ActiveContourDetector::getContour (void) const
Returns a read-only pointer to the contour being computed (when operating in step-by-step mode).
Returns
read-only pointer to the contour being computed
Definition at line 197 of file ActiveContourDetector.cpp.
References contour_.
 {
         return contour_;
 }
Contour_F * ActiveContourDetector::getContour_ (ReadWriteStatus rw) protected
Returns a writable pointer to the contour force's geometric contour (list of points)
Returns
a writable pointer to the contour force's geometric contour
Definition at line 202 of file ActiveContourDetector.cpp.
References contour_.
Referenced by uriVL::ActiveContourDetector_balloon::findContour_(), and uriVL::ActiveContourDetector_balloon::oneStep_().
 {
         return contour_;
 }
IterationStatus ActiveContourDetector::getStatus (void) const
Returns the current iteration status without computing an iteration step.
Returns
reference to the current iteration status
Definition at line 234 of file ActiveContourDetector.cpp.
References status_.
Referenced by iterate().
 {
         return status_;
 }
float ActiveContourDetector::getTimeStep (void) const
Returns the value of the "time step" that scales the total force to produce a displacement.
See also
timeStep_
Returns
value of the "time step"
Definition at line 239 of file ActiveContourDetector.cpp.
References timeStep_.
Referenced by uriVL::ActiveContourDetector_balloon::calculateEdgeForce_(), and uriVL::ActiveContourDetector_balloon::calculateShrinkForce_().
 {
         return timeStep_;
 }
bool uriVL::ActiveContourDetector::gradientsAreLocal (void) const inline
Reports whether this object "owns" the various gradient rasters and vector fields and should delete them in the destructor.
Returns
true if this object "owns" the various gradient rasters and vector fields
Definition at line 155 of file ActiveContourDetector.h.
Referenced by ~ActiveContourDetector(), and uriVL::ActiveContourDetector_balloon::~ActiveContourDetector_balloon().
{
                                 return gradientsAreLocal_;
                         }
IterationStatus ActiveContourDetector::iterate (int n)
Aplies n iterations of the algorithm (or fewer if convergence occurs before).
Can only be called when the detector operates in "step-by-step" mode and after one step of calculation or more has been performed (by a call to findContour)
Parameters
n number of iteration steps to process
Returns
an iteration status record
See also
setStepByStep
findContour
stepByStep_
setupCompleted_
Definition at line 256 of file ActiveContourDetector.cpp.
References getStatus(), uriVL::IterationStatus::hasConverged(), oneStep_(), and setupCompleted_.
Referenced by uriVL::ActiveContourDetector_balloon::findContour_().
 {
         //      if this balloon detector has been set to operate in "step by step" mode
         //      and has been properly configured (image and input contour sent in),
         //      execute the number of steps specified.
         if (setupCompleted_){
                 bool converged = false;
                 int count = 0;
                 for(int i=0; (i < nbSteps) && !converged ; i++){
                         IterationStatus stepStatus = oneStep_();
                         converged = stepStatus.hasConverged();
                         count++;
                 }
                 if(converged){
                         cout<< count << " iterations (convergence)" << endl;
                 }
         }
         return getStatus();
 }
virtual IterationStatus uriVL::ActiveContourDetector::oneStep_ (void) protected pure virtual
Applies one iteration of the contour determination algorithm.
Returns
contour detection iteration status structure
Implemented in uriVL::ActiveContourDetector_balloon.
Referenced by iterate().
const ActiveContourDetector & ActiveContourDetector::operator= (const ActiveContourDetector & obj) protected
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 152 of file ActiveContourDetector.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ActiveContourDetector copy operator not implemented.");
         return *this;
 }
virtual void uriVL::ActiveContourDetector::renderForces (void) pure virtual
Renders the different forces applied to the contour's vertices.
Implemented in uriVL::ActiveContourDetector_balloon, and uriVL::ActiveContourDetector_GVF.
void ActiveContourDetector::setContour_ (Contour_F * contour) protected
Assigns a contour object, typically, to start an iteration.
This object will now use that contour object for its search and modify it while doing so.
Parameters
contour the initial contour for the search
Definition at line 207 of file ActiveContourDetector.cpp.
References contour_, FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), and uriVL::ActiveContourDetector_balloon::setImageProperties().
 {
         if (contour_ != NULL)
         {
                 FAIL_CONDITION( true,
                                                 kFunctionNotImplemented,
                                                 "Not completely finished.  Unusure yet if contour will ever be local to an instance of the class");
         }
         contour_ = contour;
 }
void ActiveContourDetector::setGradientRasters_ (VectorField_F * grad, RasterImage_gray_F * normSqrd) protected
This function should be called for video-rate applications that must re-use the same rasters for performance optimization purposes.
In that case, the image and vector rasters are not local to the
Parameters
grad image gradient vector field
normSqrd norm of gradient raster
Definition at line 189 of file ActiveContourDetector.cpp.
References grad, gradientsAreLocal_, imageGradient_, and normSqrdOfGrad_.
Referenced by uriVL::ActiveContourDetector_balloon::setImageProperties().
 {
         imageGradient_ = grad;
         normSqrdOfGrad_ = normSqrd;
         gradientsAreLocal_ = false;
 }
void ActiveContourDetector::setInternalCoeff_ (float internalCoeff) protected
Called by a subclass to set the coeefficient of the internal force in the computation of the total force.
Parameters
internalCoeff value to assign to the coefficient of the internal force
Definition at line 184 of file ActiveContourDetector.cpp.
References internalCoeff_.
Referenced by uriVL::ActiveContourDetector_balloon::setCoeffs().
 {
         internalCoeff_ = internalCoeff;
 }
void ActiveContourDetector::setStepByStep (bool sbs)
Allows the user to change the mode in which the detector operate: "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
Parameters
sbs true if step-by-step mode is selected by the user
See also
stepByStep_
Definition at line 224 of file ActiveContourDetector.cpp.
References stepByStep_.
 {
         stepByStep_ = sbs;
 }
void ActiveContourDetector::setStepSize (int size)
When in step-by-step mode, sets the number of iterations run at each "step".
Parameters
size size of a step (number of regular iterations)
Definition at line 228 of file ActiveContourDetector.cpp.
References stepSize_.
 {
         stepSize_ = size;
 }
Member Data Documentation
float uriVL::ActiveContourDetector::alphaFirstDeriv_ protected
Energy contributed by the distance between control points to the internal force.
Definition at line 276 of file ActiveContourDetector.h.
float uriVL::ActiveContourDetector::betaSecondDeriv_ protected
Energy contributed by the curvature of the snake to the internal force.
Larger values of beta cause bends in the snake to have a high cost and lead to smoother snakes.
Definition at line 282 of file ActiveContourDetector.h.
ColorImageGradient_Gaussian_F* uriVL::ActiveContourDetector::colorImageGradientProcessor_ protected
Used when processing a color image.
Definition at line 243 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), and ~ActiveContourDetector().
Contour_F* uriVL::ActiveContourDetector::contour_ protected
Pointer to the Contour_F object being worked on by this object.
The Contour_F object is not "owned" by this object and will not be freed by the destructor.
Definition at line 252 of file ActiveContourDetector.h.
Referenced by ActiveContourDetector(), getContour(), getContour_(), and setContour_().
const float ActiveContourDetector::DEFAULT_ALPHA_1ST_DERIV = 4.f static protected
Default value for the energy contributed by the distance between control points.
Definition at line 192 of file ActiveContourDetector.h.
Referenced by calculateInternalForce_().
const float ActiveContourDetector::DEFAULT_BETA_2ND_DERIV = 0.1f static protected
Default value for the energy contributed by the curvature of the snake.
Definition at line 196 of file ActiveContourDetector.h.
Referenced by calculateInternalForce_().
const float ActiveContourDetector::DEFAULT_GAUSSIAN_FILTER_SCALE = 2.0f static protected
Default scale of the gradient of Gaussian.
In the Xu & Price paper it is 1.5f
Definition at line 172 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour().
const float ActiveContourDetector::DEFAULT_INTERNAL_COEFF = 1.f static protected
Default value for the internal force coefficient.
Definition at line 180 of file ActiveContourDetector.h.
const float ActiveContourDetector::DEFAULT_MAX_INTERNAL_FORCE = 5.1f static protected
Default value for the maximimum magnitude of the internal force.
Definition at line 176 of file ActiveContourDetector.h.
Referenced by calculateInternalForce_().
const float ActiveContourDetector::DEFAULT_TIME_STEP = 0.15f static protected
Default time step in the iteration equation, arbitrarily set.
Definition at line 184 of file ActiveContourDetector.h.
const float ActiveContourDetector::DEFAULT_TOLERANCE = (float)1E-5 static protected
Default time step in the iteration equation, arbitrarily set.
Definition at line 188 of file ActiveContourDetector.h.
float uriVL::ActiveContourDetector::gaussianGradientScale_ protected
Scale of the gradient of Gaussian.
In the Xu & Price paper it is 1.5f
Definition at line 272 of file ActiveContourDetector.h.
bool uriVL::ActiveContourDetector::gradientsAreLocal_ protected
Indicates whether the contour detector allocated its own gradient, norm of gradient, etc.
objects
Definition at line 303 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), and setGradientRasters_().
ImageGradient_Gaussian_F* uriVL::ActiveContourDetector::grayImageGradientProcessor_ protected
Used when processing a gray-level image.
Definition at line 247 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), and ~ActiveContourDetector().
VectorField_F* uriVL::ActiveContourDetector::imageGradient_ protected
Stores the gradient of the image being operated on.
Definition at line 235 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), setGradientRasters_(), and ~ActiveContourDetector().
float uriVL::ActiveContourDetector::internalCoeff_ protected
Coefficient of the internal force in the computation of the total force.
Definition at line 268 of file ActiveContourDetector.h.
Referenced by setInternalCoeff_().
ContourForce* uriVL::ActiveContourDetector::internalForce_ protected
Internal, "goodness" component of the force applied to each vertex of the active contour.
Definition at line 260 of file ActiveContourDetector.h.
Referenced by ActiveContourDetector(), calculateInternalForce_(), uriVL::ActiveContourDetector_balloon::findContour_(), uriVL::ActiveContourDetector_balloon::oneStep_(), uriVL::ActiveContourDetector_balloon::renderForces(), uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_(), uriVL::ActiveContourDetector_balloon::setImageProperties(), and ~ActiveContourDetector().
float uriVL::ActiveContourDetector::maxInternalForce_ protected
Maximimum magnitude of the internal force.
Definition at line 286 of file ActiveContourDetector.h.
int uriVL::ActiveContourDetector::nbIterations_ protected
Number of iterations done so far.
Definition at line 298 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::oneStep_().
RasterImage_gray_F* uriVL::ActiveContourDetector::normSqrdOfGrad_ protected
Stores as a gray-level image the norm squared of gradient of the image being operated on.
Definition at line 239 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), uriVL::ActiveContourDetector_balloon::oneStep_(), setGradientRasters_(), and ~ActiveContourDetector().
bool uriVL::ActiveContourDetector::setupCompleted_ protected
True after the detector has run at least one iteration step, so that the iterate function can be called to iterate one or more steps.
This boolean is set true after one step of calculation or more has been performed (by a call to findContour)
See also
iterate
Definition at line 323 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour_(), and iterate().
IterationStatus uriVL::ActiveContourDetector::status_ protected
Status of the current iteration.
Definition at line 264 of file ActiveContourDetector.h.
Referenced by getStatus().
bool uriVL::ActiveContourDetector::stepByStep_ protected
Indicates whether the contour detector operates in "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
See also
setStepByStep
Definition at line 310 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour_(), and setStepByStep().
int uriVL::ActiveContourDetector::stepSize_ protected
How many integration steps to apply when in "step-by"step" mode.
Definition at line 314 of file ActiveContourDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour_(), and setStepSize().
float uriVL::ActiveContourDetector::timeStep_ protected
Time "step" in the integration of the differential equation.
Definition at line 290 of file ActiveContourDetector.h.
Referenced by calculateInternalForce_(), and getTimeStep().
float uriVL::ActiveContourDetector::tolerance_ protected
Convergence threshold, for whatever convergence criterion is being used.
Definition at line 294 of file ActiveContourDetector.h.
ContourForce* uriVL::ActiveContourDetector::totalForce_ protected
Sum of all forces applied to each vertex of the active contour.
Definition at line 256 of file ActiveContourDetector.h.
Referenced by ActiveContourDetector(), uriVL::ActiveContourDetector_balloon::findContour_(), uriVL::ActiveContourDetector_balloon::oneStep_(), uriVL::ActiveContourDetector_balloon::renderForces(), uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_(), uriVL::ActiveContourDetector_balloon::setImageProperties(), and ~ActiveContourDetector().
The documentation for this class was generated from the following files:
ActiveContourDetector.h
ActiveContourDetector.cpp