URIVisionLibrary: uriVL::Tracker2D_PID Class Reference
uriVL::Tracker2D_PID Class Reference
#include <Tracker2D_PID.h>
Public Member Functions
Tracker2D_PID (FeatureDetector *detector, float metricX, float metricY, TrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a Tracker2D_PID.
~Tracker2D_PID (void)
Destructor.
TrackingStateList getPredRecord (void)
pure virtual function track the state of the target
TrackingStateList getStateRecord (void)
get the real state record of the target
TrackingState * getCurrState (void)
get the current state of the target
Public Member Functions inherited from uriVL::Tracker2D
Tracker2D (void)
Default Constructor Creates a Tracker2D.
Tracker2D (FeatureDetector *detector, float metricX, float metricY, TrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a Tracker2D.
Tracker2D (float metricX, float metricY, TrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a Tracker2D.
virtual ~Tracker2D (void)
Destructor.
Additional Inherited Members
Protected Attributes inherited from uriVL::Tracker2D
float metricX_
(pending...
float metricY_
(pending...
RasterImage * pattern_
pattern as a RasterImage this tracked object
int leftBound_
left bound of the searching area
int rightBound_
right bound of the searching area
int topBound_
top bound of the searching area
int bottomBound_
bottom bound of the searching area
bool savePred_
whether to save prediction state
bool saveState_
whether to save real state
TrackingState * currentState_
current state of the target
TrackingStateList predRecord_
a TrackingStateList of prediction state found in all input images up to now
TrackingStateList stateRecord_
a TrackingStateList of real state found in all input images up to now
int failCounts_
maximum fail times allowed
FeatureDetector * detector_
FeatureDetector.
Detailed Description
Definition at line 27 of file Tracker2D_PID.h.
Constructor & Destructor Documentation
Tracker2D_PID::Tracker2D_PID (FeatureDetector * detector, float metricX, float metricY, TrackingState * initState, bool savePred = false, bool saveState = false)
Constructor Creates a Tracker2D_PID.
Parameters
detector FeatureDetector used for this tracker
metricX metric (such as displacement) on x coordinate used for tracking
metricY metric (such as displacement) on y coordinate used for tracking
initState initial TrackingState
savePred default argument indicating whether to save prediction state
saveState default argument indicating whether to save real state
Definition at line 27 of file Tracker2D_PID.cpp.
         : Tracker2D(detector, metricX, metricY, initState, savePred, saveState)
 {
 }
Tracker2D_PID::~Tracker2D_PID (void)
Destructor.
Definition at line 38 of file Tracker2D_PID.cpp.
 {
 }
Member Function Documentation
TrackingState * Tracker2D_PID::getCurrState (void) virtual
get the current state of the target
Returns
currentState_
Implements uriVL::Tracker2D.
Definition at line 71 of file Tracker2D_PID.cpp.
References uriVL::Tracker2D::getCurrState().
 {
         Tracker2D::getCurrState();
 }
TrackingStateList Tracker2D_PID::getPredRecord (void) virtual
pure virtual function track the state of the target
Parameters
img input RasterImage
Returns
a pointer to TrackingState Object get the prediction state record of the target
predRecord_
Implements uriVL::Tracker2D.
Definition at line 61 of file Tracker2D_PID.cpp.
References uriVL::Tracker2D::getPredRecord().
 {
         Tracker2D::getPredRecord();
 }
TrackingStateList Tracker2D_PID::getStateRecord (void) virtual
get the real state record of the target
Returns
stateRecord_
Implements uriVL::Tracker2D.
Definition at line 66 of file Tracker2D_PID.cpp.
References uriVL::Tracker2D::getStateRecord().
 {
         Tracker2D::getStateRecord();
 }
The documentation for this class was generated from the following files:
Tracker2D_PID.h
Tracker2D_PID.cpp