URIVisionLibrary: uriVL::BlobTracker2D Class Reference
uriVL::BlobTracker2D Class Reference
#include <BlobTracker2D.h>
Public Member Functions
BlobTracker2D (FeatureDetector *detector, float metricX, float metricY, BlobTrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a BlobTracker2D.
~BlobTracker2D (void)
Destructor.
TrackingState * track (BlobList *blobList, LabelRaster *label)
Blob * getCurrentBlob (void)
virtual function track the state of the target
TrackingStateList getPredRecord (void)
get the prediction state record of the target
TrackingStateList getStateRecord (void)
get the real state record of the target
TrackingState * getCurrState (void)
get the current state of the target
Public Member Functions inherited from uriVL::Tracker2D
Tracker2D (void)
Default Constructor Creates a Tracker2D.
Tracker2D (FeatureDetector *detector, float metricX, float metricY, TrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a Tracker2D.
Tracker2D (float metricX, float metricY, TrackingState *initState, bool savePred=false, bool saveState=false)
Constructor Creates a Tracker2D.
virtual ~Tracker2D (void)
Destructor.
Protected Attributes
Blob * blob_
current blob being tracked
int distanceRange_
tolorance range of distance (on both x and y) during tracking
Protected Attributes inherited from uriVL::Tracker2D
float metricX_
(pending...
float metricY_
(pending...
RasterImage * pattern_
pattern as a RasterImage this tracked object
int leftBound_
left bound of the searching area
int rightBound_
right bound of the searching area
int topBound_
top bound of the searching area
int bottomBound_
bottom bound of the searching area
bool savePred_
whether to save prediction state
bool saveState_
whether to save real state
TrackingState * currentState_
current state of the target
TrackingStateList predRecord_
a TrackingStateList of prediction state found in all input images up to now
TrackingStateList stateRecord_
a TrackingStateList of real state found in all input images up to now
int failCounts_
maximum fail times allowed
FeatureDetector * detector_
FeatureDetector.
Friends
class BlobTracker2DController
Detailed Description
Definition at line 33 of file BlobTracker2D.h.
Constructor & Destructor Documentation
BlobTracker2D::BlobTracker2D (FeatureDetector * detector, float metricX, float metricY, BlobTrackingState * initState, bool savePred = false, bool saveState = false)
Constructor Creates a BlobTracker2D.
Parameters
detector FeatureDetector used for this tracker
metricX metric (such as displacement) on x coordinate used for tracking
metricY metric (such as displacement) on y coordinate used for tracking
initState initial BlobTrackingState
savePred default argument indicating whether to save prediction state
saveState default argument indicating whether to save real state
Definition at line 30 of file BlobTracker2D.cpp.
 {
         //thresholder_  = new GrayThresholdLabeler();
         //colorParams_  = new ColorSegParams;
         //remover_              = new BackgroundRemover_Static();
         //backgroundImg_        = bkgdImg;
         //currImg_              = NULL;
         detector_ = detector;
         currentState_ = new BlobTrackingState(initState);
         metricX_ = metricX;
         metricY_ = metricY;
         savePred_ = savePred;
         saveState_ = saveState;
         predRecord_.push_back(currentState_);
         stateRecord_.push_back(currentState_);
         failCounts_     = 0;
         blob_           = NULL;
         distanceRange_ = 10;
         /*
         colorParams_->fillMode  = kOrigColorFill;
         colorParams_->nbModes   = 1;
         colorParams_->colorMode = false;
         colorParams_->colorReg  = NULL;
         colorParams_->grayReg   = new GrayRegion[colorParams_->nbModes];
     colorParams_->grayReg[0].labelStr =  "medium gray";
     colorParams_->grayReg[0].vMin = 5;
     colorParams_->grayReg[0].vMax = 255;
     colorParams_->grayReg[0].fillColor[0] = 0;
     colorParams_->grayReg[0].fillColor[1] = (unsigned char) 255;
     colorParams_->grayReg[0].fillColor[2] = (unsigned char) 0;
     colorParams_->grayReg[0].label = 1;
         //remover_->setBackground(bkgdImg);
         //remover_->setBackground(backgroundImg_);
         */
 }
BlobTracker2D::~BlobTracker2D (void)
Destructor.
Definition at line 75 of file BlobTracker2D.cpp.
 {
         //delete thresholder_;
         //delete colorParams_;
         //delete remover_;
         //delete currImg_;
         delete currentState_;
         TrackingStateList::iterator predIter = predRecord_.begin();
         TrackingStateList::iterator stateIter = stateRecord_.begin();
         for ( ; predIter != predRecord_.end(); predIter++)
                 delete (*predIter);
         for ( ; stateIter != stateRecord_.end(); stateIter++)
                 delete (*stateIter);
         predRecord_.clear();
         stateRecord_.clear();
         delete blob_;
 }
Member Function Documentation
Blob * BlobTracker2D::getCurrentBlob (void)
virtual function track the state of the target
Parameters
img input RasterImage(after background update)
Returns
a pointer to TrackingState Object overloaded function track the state of the target
Parameters
img input RasterImage
Returns
a pointer to TrackingState Object get current blob
predRecord_
Definition at line 254 of file BlobTracker2D.cpp.
 {
         return blob_;
 }
TrackingState * BlobTracker2D::getCurrState (void) virtual
get the current state of the target
Returns
currentState_
Implements uriVL::Tracker2D.
Definition at line 259 of file BlobTracker2D.cpp.
 {
         return Tracker2D::getCurrState();
 }
TrackingStateList BlobTracker2D::getPredRecord (void) virtual
get the prediction state record of the target
Returns
predRecord_
Implements uriVL::Tracker2D.
Definition at line 244 of file BlobTracker2D.cpp.
 {
         return Tracker2D::getPredRecord();
 }
TrackingStateList BlobTracker2D::getStateRecord (void) virtual
get the real state record of the target
Returns
stateRecord_
Implements uriVL::Tracker2D.
Definition at line 249 of file BlobTracker2D.cpp.
 {
         return Tracker2D::getStateRecord();
 }
TrackingState * BlobTracker2D::track (BlobList * blobList, LabelRaster * label)
Definition at line 104 of file BlobTracker2D.cpp.
References uriVL::ImageRect::getBottom(), uriVL::LabelRaster::getBoundRect(), uriVL::ImageRect::getRight(), uriVL::BlobTrackingState::getSize(), uriVL::ImageRect::getTop(), uriVL::TrackingState::setResult(), uriVL::TARGET_FOUND, uriVL::TARGET_MATCH_LIST, uriVL::TARGET_NOT_FOUND, and uriVL::WRONG_TARGET_FOUND.
Referenced by myIdle().
 {
         const ImageRect* theRect = label->getBoundRect();
         float oldX = currentState_->getPos()->getX();
         float oldY = currentState_->getPos()->getY();
         float predX = oldX+metricX_,
                   predY = oldY+metricY_;
         if(predX > theRect->getRight())
                 predX = theRect->getRight();
         else if(predX < theRect->getLeft())
                 predX = theRect->getRight();
         if(predY > theRect->getBottom())
                 predY = theRect->getBottom();
         else if(predY < theRect->getTop())
                 predY = theRect->getTop();
         //----------------------------------------------------------------
         //      prediction
         //----------------------------------------------------------------
         if(savePred_ == true)           //  save to predRecord_
         {
                 BlobTrackingState *predState = new BlobTrackingState(predX, predY,
                                                                                         ((BlobTrackingState *)currentState_)->getSize());
                 predRecord_.push_back(predState);
         }
         ImagePoint* predPos = new ImagePoint((int) predX, (int) predY);
         ImagePoint_F *predPosF = new ImagePoint_F((float) predX, (float) predY);
         //----------------------------------------------------------------
         //      track based on prediction
         //----------------------------------------------------------------
         float   realX, realY, dx, dy;
         bool flag = true;
         //      check the *blobList to see if any matches
         if(!blobList->empty())
         {
                 BlobList::iterator      iter = blobList->begin();
                 for( ; iter!=blobList->end(); iter++)
                 {
                         realX   = (*iter)->getCentroid()->getX(),
                         realY   = (*iter)->getCentroid()->getY(),
                         dx              = realX - predX,
                         dy              = realY - predY;
                         //      Any one matches?
                         //      yes
                         if(dx<50 && dx>-50 && dy<50 && dy>-50)
{
                                 //  update currentState_, metricX_, metricY_, failCounts_
                                 currentState_->setResult(TARGET_MATCH_LIST);
                                 failCounts_                             = 0;                    //      reset failCounts_
                                 currentState_->setPos((*iter)->getCentroid());
                                 metricX_ = realX - oldX;
                                 metricY_ = realY - oldY;
                                 ((BlobTrackingState *) currentState_)->setSize((*iter)->getNbPixels());
                                 if(saveState_ == true)
                                 {                                       //  save to stateRecord_
                                         BlobTrackingState *realState = new BlobTrackingState(currentState_->getPos()->getX(),
                                                                                                                         currentState_->getPos()->getY(),
                                                                                                                         ((BlobTrackingState *)currentState_)->getSize());
                                         stateRecord_.push_back(realState);
                                 }
                                 blob_ = *iter;
                                 flag = false;                                           //      no need to search blob
                                 break;
                         }
                 }
         }
         //      still need to search blob
         if(flag == true)
         {
                 long    sizeRange = 8,
                                 temp = ((BlobTrackingState *)currentState_)->getSize() - sizeRange,
                                 blobMinSize = temp > 0 ? temp : (temp+sizeRange);
                 blob_                           = ((BlobFinder*) detector_)->findBlobAbout(label, predPos,
                                                                                                  (char)1,
                                                                                                  blobMinSize, theRect);
                 //      Found something?
                 //      yes
                 if(blob_ != NULL)
                 {
                         realX   = blob_->getCentroid()->getX(),
                         realY   = blob_->getCentroid()->getY(),
                         dx              = realX - predX,
                         dy              = realY - predY;
                         //      Is the right target?
                         //      yes
                         if(dx<distanceRange_ && dx>-distanceRange_ && dy<distanceRange_ && dy>-distanceRange_)
{
                                 //  update currentState_, metricX_, metricY_, failCounts_
                                 currentState_->setResult(TARGET_FOUND);
                                 failCounts_                             = 0;                    //      reset failCounts_
                                 currentState_->setPos(blob_->getCentroid());
                                 metricX_ = realX - oldX;
                                 metricY_ = realY - oldY;
                                 ((BlobTrackingState *) currentState_)->setSize(blob_->getNbPixels());
                                 if(saveState_ == true)
                                 {                                       //  save to stateRecord_
                                         BlobTrackingState *realState = new BlobTrackingState(currentState_->getPos()->getX(),
                                                                                                                         currentState_->getPos()->getY(),
                                                                                                                         ((BlobTrackingState *)currentState_)->getSize());
                                         stateRecord_.push_back(realState);
                                 }
                         }
                         //      no
                         else
{
                                 currentState_->setResult(WRONG_TARGET_FOUND);
                                 failCounts_++;
                                 currentState_->setPos(predPosF);
                         }
                 }
                 //      no
                 else
                 {
                         currentState_->setResult(TARGET_NOT_FOUND);
                         failCounts_++;
                         currentState_->setPos(predPosF);
                 }
                 //      set targetGone_ if necessary
                 if(failCounts_ >= 5)
                         currentState_->setTargetGone(true);
         }
         delete predPos;
         delete predPosF;
         return currentState_;
 }
Friends And Related Function Documentation
friend class BlobTracker2DController friend
Definition at line 35 of file BlobTracker2D.h.
Member Data Documentation
Blob* uriVL::BlobTracker2D::blob_ protected
current blob being tracked
Definition at line 114 of file BlobTracker2D.h.
int uriVL::BlobTracker2D::distanceRange_ protected
tolorance range of distance (on both x and y) during tracking
Definition at line 119 of file BlobTracker2D.h.
The documentation for this class was generated from the following files:
BlobTracker2D.h
BlobTracker2D.cpp