URIVisionLibrary: uriVL::LinearSolver_QR Class Reference
uriVL::LinearSolver_QR Class Reference
Class that implement the Householder QR factorization algorithm for solving overdetermined SLEs.
#include <LinearSolver_QR.h>
Public Member Functions
LinearSolver_QR (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_QR object.
LinearSolver_QR (Matrix *a, bool preserveMatrix=false)
A LinearSolver_QR is created for a specific matrix.
~LinearSolver_QR (void)
Destructor.
void setMatrix (Matrix *A, bool preserveMatrix=false)
Assigns a new matrix to this LinearSolver.
LinearSolverRecord * solve (Matrix *b)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
LinearSolverRecord * solve (Matrix *b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Public Member Functions inherited from uriVL::LinearSolver
virtual ~LinearSolver (void)
Destructor.
Static Public Member Functions
static LinearSolverRecord * solve (Matrix *A, Matrix *B, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecord * solve (Matrix *A, Matrix *B, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
Private Member Functions
LinearSolver_QR (const LinearSolver_QR &obj)
Copy constructor: disabled.
const LinearSolver_QR & operator= (const LinearSolver_QR &obj)
Copy operator: disabled.
Static Private Member Functions
static LinearSolverRecordStatus factorize_ (int m, int n, double *const *const a, double *const colR, double *const *const v)
Computes the QR factorization of an SLE.
static LinearSolverRecordStatus computeHouseholderV_ (int n, double *const a, double *const v, double *alphaV)
Computes the Householder construction vector for a partial column of the matrix.
static void solve_ (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix)
Solves an SLE for the matrix and right-side term received as parameters.
static void solveBS_ (int nbRows, int nbCols, const double *const *const r, const double *const *const b, double *const *const x)
Solves an SLE for the matrix and right-side term received as parameters.
static void applyQt_ (int nbRows, int nbColsR, int nbColsB, const double *const *const v, double *const *const b)
Applies the Q matrix of a QR factorization (stored under the form of Householder V vectors) to the right side of an SLE.
Private Attributes
Matrix * R_
Matrix in which the QR factorization calculations are done.
double ** v_
2D array that stores the v vectors of the Householder algorithm used to generate the orthogonal matrices of the factorization.
double * colR_
Vector used to store (part of) a column of R_.
Static Private Attributes
static const double ILL_COND_THRESHOLD = 1.E-7
Minimum value for the norm of a partial column before the matrix is considered to be ill-conditioned.
Additional Inherited Members
Protected Member Functions inherited from uriVL::LinearSolver
LinearSolver (void)
Default constructor.
LinearSolver (int nbRows, int nbCols)
Constructor: initializes the dimensions of the linear solver.
LinearSolver (Matrix *a, bool preserveMatrix=false)
Constructor: initializes the dimensions of the linear solver.
void setSingularityStatus_ (LinearSolverRecordStatus singularityStatus)
Sets the singularityStatus_.
LinearSolverRecordStatus getSingularityStatus_ (void)
Get the singularityStatus_.
int getNbRows_ (void)
Reports the number of rows of the solver's matrix.
int getNbCols_ (void)
Reports the number of rows of the solver's matrix.
void setMatrixDimensions_ (int nbRows, int nbCols)
Sets the dimensions of the solver's matrix.
int getNbStorageRows_ (void)
Reports the number of storage rows of the solver's matrix.
int getNbStorageCols_ (void)
Reports the number of storage rows of the solver's matrix.
void setMatrixStorageDimensions_ (int nbRows, int nbCols)
Sets the storage dimensions of the solver's matrix.
bool getMatrixIsLocal_ (void)
Reports whether the solver keeps a local copy of the SLE's matrix.
void setMatrixIsLocal_ (bool matrixIsLocal)
Sets whether the solver keeps a local copy of the SLE's matrix.
Detailed Description
Class that implement the Householder QR factorization algorithm for solving overdetermined SLEs.
Important note about LinearSolver classes: These classes have been built for speed, not for OOP orthodoxy. We try to minimize as much as possible the number of malloc/delete operations. The default behavior of most functions in these classes is to only keep references to the SLE's matrix, not copies of it, and to perform claculations directly in that matrix (destructive behavior). If this behavior is not desirable for your application, then call the function with the parameter preserveMatrix set to true, when available.
Author
jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 41 of file LinearSolver_QR.h.
Constructor & Destructor Documentation
LinearSolver_QR::LinearSolver_QR (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_QR object.
That matrix must have at least as many rows as it has columns otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
nbRows the maximum number of rows in the matrix
nbCols the maximum number of columns in the matrix
Definition at line 36 of file LinearSolver_QR.cpp.
References colR_, FAIL_CONDITION, uriVL::kInvalidParameterError, R_, and v_.
         :   LinearSolver(nbRows, nbCols),
             //
             R_(new Matrix(nbRows, nbCols)),
             v_(new double*[nbCols]),
             colR_ (new double[nbRows])
 {
     if (nbRows < nbCols)
     {
         delete R_;
         delete []v_;
         delete []colR_;
         FAIL_CONDITION( true,
                         kInvalidParameterError,
                         "Underdetermined SLE assigned to a LinearSolver_QR");
     }
     for (int j=0, lv=nbRows; j<nbCols; j++, lv--)
         v_[j] = new double[lv];
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LinearSolver_QR constructor");
         throw e;
 }
LinearSolver_QR::LinearSolver_QR (Matrix * a, bool preserveMatrix = false)
A LinearSolver_QR is created for a specific matrix.
That matrix must have at least as many rows as it has columns otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function.
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 65 of file LinearSolver_QR.cpp.
References colR_, factorize_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, R_, uriVL::R_W_ACCESS, uriVL::LinearSolver::setMatrixDimensions_(), uriVL::LinearSolver::setMatrixIsLocal_(), uriVL::LinearSolver::setMatrixStorageDimensions_(), uriVL::LinearSolver::setSingularityStatus_(), and v_.
            :    LinearSolver(A, preserveMatrix),
                                 //
                                 R_(preserveMatrix ? new Matrix(A) : A),
                                 v_(new double*[A->getNbCols()]),
                                 colR_(new double[A->getNbRows()])
 {
     const int nbRows = A->getNbRows();
     const int nbCols = A->getNbCols();
         if (nbRows < nbCols)
         {
                 delete []v_;
                 delete []colR_;
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Underdetermined SLE assigned to a LinearSolver_QR");
         }
         setMatrixDimensions_(nbRows, nbCols);
     if (preserveMatrix)
     {
                 setMatrixStorageDimensions_(nbRows, nbCols);
     }
     setMatrixIsLocal_(preserveMatrix);
     for (int j=0, lv=nbRows; j<nbCols; j++, lv--)
         v_[j] = new double[lv];
     double* const*const r = R_->getMatrix(R_W_ACCESS);
     setSingularityStatus_(factorize_(nbRows, nbCols, r, colR_, v_));
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by LinearSolver_QR constructor");
         throw e;
 }
 catch (...)
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_QR");
 }
LinearSolver_QR::~LinearSolver_QR (void)
Destructor.
Definition at line 123 of file LinearSolver_QR.cpp.
References colR_, uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::LinearSolver::getNbStorageCols_(), R_, and v_.
 {
     if (getMatrixIsLocal_())
         delete R_;
     for (int j=0; j<getNbStorageCols_(); j++)
         delete []v_[j];
     delete []v_;
     delete []colR_;
 }
LinearSolver_QR::LinearSolver_QR (const LinearSolver_QR & obj) private
Copy constructor: disabled.
Parameters
obj reference to the object to copy
Definition at line 110 of file LinearSolver_QR.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :   LinearSolver(),
             //
             R_(NULL),
             v_(NULL),
             colR_ (NULL)
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_QR copy constructor not inplemented");
 }
Member Function Documentation
void LinearSolver_QR::applyQt_ (int nbRows, int nbColsR, int nbColsB, const double *const *const v, double *const *const b) static private
Applies the Q matrix of a QR factorization (stored under the form of Householder V vectors) to the right side of an SLE.
Parameters
nbRows number of rows of the SLE's matrix
nbColsR number of columns of the SLE's matrix
nbColsB number of columns of the right-side term
v the array of Householder vectors
b (possibly, a copy of) the right-side term of the SLE. At the end of the function, stores Q^T . b
Definition at line 502 of file LinearSolver_QR.cpp.
Referenced by solve(), and solve_().
 {
     //  We apply the Hv matrices (under the form of their v vector) that were computed
         //      for the different columns (left to right) of the SLE's original matrix
     for (int j=0; j<nbColsR; j++)
     {
         //  Vector v is applied to all columns of the right-side term
         for (int l=0; l<nbColsB; l++)
         {
             double  bv = 0.L;
             //  compute the dot product of the (partial) column and v
             for (int i=j, k=0; i<nbRows; i++, k++)
                 bv += b[i][l]*v[j][k];
             //  and subtract 2 v^T a v from a
             bv *= 2.L;
             for (int i=j, k=0; i<nbRows; i++, k++)
                 b[i][l] -= bv * v[j][k];
         }
     }
 }
LinearSolverRecordStatus LinearSolver_QR::computeHouseholderV_ (int n, double *const a, double *const v, double * alphaV) static private
Computes the Householder construction vector for a partial column of the matrix.
Parameters
n dimension of the partial column
a the partial column to operate on
v the construction vector calculated for a
alphaV will store in output the signed Euclidean norm of a
Returns
a matrix singularity status
Definition at line 585 of file LinearSolver_QR.cpp.
References ILL_COND_THRESHOLD, uriVL::ILL_CONDITIONED_MATRIX, uriVL::REGULAR_MATRIX, and uriVL::SINGULAR_MATRIX.
Referenced by factorize_().
 {
     LinearSolverRecordStatus status = REGULAR_MATRIX;
     double  invNormV, normA, normA1 = 0.L;
     for (int i=1; i<n; i++)
     {
         v[i] = a[i];
         normA1 += a[i]*a[i];
     }
     normA = sqrt(normA1 + a[0]*a[0]);
     if (normA == 0.L)
         status = SINGULAR_MATRIX;
     else
     {
         if (normA < ILL_COND_THRESHOLD)
                         status = ILL_CONDITIONED_MATRIX;
         if (a[0] > 0.L)
         {
             v[0] = a[0] + normA;
             *alphaV = -normA;
             invNormV = 1.L / sqrt(normA1 + v[0]*v[0]);
         }
         else
         {
             v[0] = a[0] - normA;
             *alphaV = normA;
             invNormV = 1.L / sqrt(normA1 + v[0]*v[0]);
         }
         //  we normalize v to speedup later calculations
         for (int i=0; i<n; i++)
             v[i] *= invNormV;
     }
     return status;
 }
LinearSolverRecordStatus LinearSolver_QR::factorize_ (int m, int n, double *const *const a, double *const colR, double *const *const v) static private
Computes the QR factorization of an SLE.
Parameters
m number of rows of the SLE
n number of columns of the SLE
a the matrix of the SLE (will store R in output)
colR stores (part of) a column of a for faster calculations
v stores the construction vectors of Q^t (by row)
Returns
a matrix singularity status
v is computed from elements from rows j to m-1 of column j
Definition at line 530 of file LinearSolver_QR.cpp.
References computeHouseholderV_(), uriVL::ILL_CONDITIONED_MATRIX, uriVL::REGULAR_MATRIX, and uriVL::SINGULAR_MATRIX.
Referenced by LinearSolver_QR(), setMatrix(), and solve_().
 {
     LinearSolverRecordStatus status = REGULAR_MATRIX, colStatus;
     //  We proceed column by column, from the left to the right
     for (int j=0, lv=nbRows; j<nbCols; j++, lv--)
     {
         //  Step 0:  Copy the data from column j of the matrix
         for (int i=j; i<nbRows; i++)
             colR[i] = r[i][j];
         //  Step 1:  Determine the v vector that constructs the orthogonal Householder Hv matrix
         //           Hv = I - 2 (v v^T) / (v^T v)
         ///          v is computed from elements from rows j to m-1 of column j
         double alphaV;
         colStatus = computeHouseholderV_(lv, colR+j, v[j], &alphaV);
         if (colStatus == SINGULAR_MATRIX)
             status = SINGULAR_MATRIX;
         else if ((colStatus == ILL_CONDITIONED_MATRIX) && (status != SINGULAR_MATRIX))
             status = ILL_CONDITIONED_MATRIX;
         if (status != SINGULAR_MATRIX)
         {
             //  column j is "compressed"
             r[j][j] = alphaV;
             //  This is not really needed.  I do it so far for aesthetic reasons but as soon
             //  as the code has been thoroughly tested, I will remove this for better
             //  performance.
             for (int i=j+1; i<nbRows; i++)
                 r[i][j] = 0;
             //  Vector v is applied to all other columns right of j.  This only afffects
             //  rows j and below
             for (int l=j+1; l<nbCols; l++)
             {
                 double  av = 0;
                 //  compute the dot product of the (partial) column and v
                 for (int i=j, k=0; i<nbRows; i++, k++)
                     av += r[i][l]*v[j][k];
                 //  and subtract 2 v^T a v from a
                 av *= 2.L;
                 for (int i=j, k=0; i<nbRows; i++, k++)
                     r[i][l] -= av * v[j][k];
             }
         }
     }
     return status;
 }
const LinearSolver_QR & LinearSolver_QR::operator= (const LinearSolver_QR & obj) private
Copy operator: disabled.
Parameters
obj reference to the object to copy
Definition at line 135 of file LinearSolver_QR.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_QR copy opertator not inplemented");
         return *this;
 }
void LinearSolver_QR::setMatrix (Matrix * A, bool preserveMatrix = false) virtual
Assigns a new matrix to this LinearSolver.
This call only makes sense if the new matrix has the same dimensions as the previous one (it then saves a destruction and an allocation of a matrix). Otherwise, just use the static solve function.
Important: If you don't set preserveMatrix true, then the LinearSolver only stores a reference to matrix it receives as a parameter. It will do calculations in this matrix.
You cannot delete it before you call the solve function,
The matrix's elements will be modified (destructive behavior)
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Implements uriVL::LinearSolver.
Definition at line 144 of file LinearSolver_QR.cpp.
References colR_, factorize_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::Matrix::getNbCols(), uriVL::LinearSolver::getNbCols_(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::LinearSolver::getNbStorageCols_(), uriVL::LinearSolver::getNbStorageRows_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, R_, uriVL::R_W_ACCESS, uriVL::LinearSolver::setMatrixDimensions_(), uriVL::LinearSolver::setMatrixIsLocal_(), uriVL::LinearSolver::setMatrixStorageDimensions_(), uriVL::LinearSolver::setSingularityStatus_(), and v_.
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_QR");
     const int nbRows = A->getNbRows();
     const int nbCols = A->getNbCols();
     FAIL_CONDITION( nbRows < nbCols,
                     kInvalidParameterError,
                     "Underdetermined SLE assigned to a LinearSolver_QR");
         int newStorageRows = getNbStorageRows_(),
                 newStorageCols = getNbStorageCols_();
     //  First, take care of v_
     if ((getNbRows_() != nbRows) || (getNbCols_() != nbCols))
     {
                 if (nbCols > getNbStorageCols_())
                 {
                         for (int j=0; j<nbCols; j++)
                                 delete []v_[j];
                         delete []v_;
                         newStorageCols = nbCols;
                         v_ = new double*[nbCols];
                         for (int j=0, lv=max(nbRows, newStorageRows); j<nbCols; j++, lv--)
                                 v_[j] = new double[lv];
                 }
         if (R_->getNbRows() > newStorageRows)
         {
             delete []colR_;
             colR_ = new double[nbRows];
                         newStorageRows = nbRows;
         }
                 setMatrixDimensions_(nbRows, nbCols);
                 setMatrixStorageDimensions_(newStorageRows, newStorageCols);
     }
     //  If we were already storing a local copy of a previous SLE's matrix,
     //  then we may have to do delete/reallocate that local copy
     if (getMatrixIsLocal_())
     {
         if (preserveMatrix)
         {
             //  If the new matrix has different dimensions from the old one, we
             //  must delete & reallocate R_
             if ((R_->getNbRows() < nbRows) || (R_->getNbCols() < nbCols))
             {
                 if (R_ != NULL)
                     delete R_;
                 R_ = new Matrix(A);
             }
             //  if the dimensions did not change we simply copy the data
             else
                 (*R_) = (*A);
         }
         //  If the matrix was local, but should not be anymore, we simply delete the
         //  current matrix and store the reference to the new one
         else
         {
             delete R_;
             R_ = A;
             setMatrixIsLocal_(false);
         }
     }
     else
     {
         if (preserveMatrix)
         {
             R_ = new Matrix(A);
             setMatrixIsLocal_(true);
         }
         else
             R_ = A;
     }
     setMatrixIsLocal_(preserveMatrix);
     double* const*const r = R_->getMatrix(R_W_ACCESS);
     setSingularityStatus_(factorize_(nbRows, nbCols, r, colR_, v_));
 }
LinearSolverRecord * LinearSolver_QR::solve (Matrix * b) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 234 of file LinearSolver_QR.cpp.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), main(), and solve().
 {
     return solve(B, 0);
 }
LinearSolverRecord * LinearSolver_QR::solve (Matrix * b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 239 of file LinearSolver_QR.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_QR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( nbRows != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve(B, record, incrImprov);
     return record;
 }
void LinearSolver_QR::solve (Matrix * b, LinearSolverRecord * record) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 261 of file LinearSolver_QR.cpp.
References solve().
 {
     solve(B, record, 0);
 }
void LinearSolver_QR::solve (Matrix * b, LinearSolverRecord * record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
record stores the solution to the SLe and indication about the matrix's regularity.
Definition at line 266 of file LinearSolver_QR.cpp.
References applyQt_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::Matrix::getNbCols(), uriVL::LinearSolver::getNbCols_(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::LinearSolver::getSingularityStatus_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::kSingularMatrixError, R_, uriVL::R_W_ACCESS, uriVL::SINGULAR_MATRIX, uriVL::LinearSolverRecord::sol, solveBS_(), uriVL::LinearSolverRecord::status, and v_.
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_QR");
     FAIL_CONDITION( record == NULL,
                     kNullParameterError,
                     "Null LinearSolverRecord term sent to a LinearSolver_QR");
     const int nbRowsB = B->getNbRows(),
               nbColsB = B->getNbCols();
     FAIL_CONDITION( nbRowsB != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     //  If the SLE's matrix is singular we bail out
     FAIL_CONDITION( getSingularityStatus_() == SINGULAR_MATRIX,
                     kSingularMatrixError,
                     "The matrix of the SLE is singular");
     Matrix* X = record->sol;
     //  if the solution was not allocated we do it now
     if (X == NULL)
     {
         if (nbColsB == 1)
             X = record->sol = new ColumnVector(getNbCols_());
         else
             X = record->sol = new Matrix(getNbCols_(), nbColsB);
     }
     else
     {
         FAIL_CONDITION( getNbCols_() != X->getNbRows(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the SLE's matrix");
         FAIL_CONDITION( nbColsB != X->getNbCols(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the right-side term");
     }
     Matrix *newB;
     if (getMatrixIsLocal_())
         newB = new Matrix(B);
     else
         newB = B;
     double* const*const b = newB->getMatrix(R_W_ACCESS);
     record->status = getSingularityStatus_();
     applyQt_(getNbRows_(), getNbCols_(), nbColsB, v_, b);
     solveBS_(getNbCols_(), nbColsB, R_->getMatrix(), b, X->getMatrix(R_W_ACCESS));
     if (getMatrixIsLocal_())
         delete newB;
 }
LinearSolverRecord * LinearSolver_QR::solve (Matrix * A, Matrix * B, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 326 of file LinearSolver_QR.cpp.
References solve().
 {
     return solve(A, B, 0, preserveMatrix);
 }
LinearSolverRecord * LinearSolver_QR::solve (Matrix * A, Matrix * B, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 332 of file LinearSolver_QR.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_QR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_QR");
     const int aRows = A->getNbRows();
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_QR");
     FAIL_CONDITION( preserveMatrix && (incrImprov>0),
                     kInvalidParameterError,
                     "Impossible to do incremental improvement w/o preserving the matrix in LinearSolver_QR:solve");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve_(A, B, record, incrImprov, preserveMatrix);
     return record;
 }
void LinearSolver_QR::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 362 of file LinearSolver_QR.cpp.
References solve().
 {
     solve(A, B, record, 0, preserveMatrix);
 }
void LinearSolver_QR::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 369 of file LinearSolver_QR.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_QR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_QR");
     const int aRows = A->getNbRows(); /*,
               aCols = A->getNbCols();*/
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_QR");
     //  was the record properly created?
     if (record->sol != NULL)
     {
         FAIL_CONDITION( (nbRows != record->sol->getNbRows()) ||
                         (nbCols != record->sol->getNbCols()),
                         kInvalidParameterError,
                         "right-side term and solution's dimensions dont match for LinearSolver_QR");
     }
     //  if the solution was not allocated we do it now
     else
     {
         if (nbCols == 1)
             record->sol = new ColumnVector(nbRows);
         else
             record->sol = new Matrix(nbRows, nbCols);
     }
     solve_(A, B, record, incrImprov, preserveMatrix);
 }
void LinearSolver_QR::solve_ (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix) static private
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 411 of file LinearSolver_QR.cpp.
References applyQt_(), factorize_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::R_W_ACCESS, uriVL::LinearSolverRecord::sol, solveBS_(), and uriVL::LinearSolverRecord::status.
Referenced by solve().
 {
     const int nbRowsA = A->getNbRows(),
               nbColsA = A->getNbCols();
     const int nbRowsB = B->getNbRows(),
               nbColsB = B->getNbCols();
     Matrix *QR;
     Matrix *newB;
     if (preserveMatrix)
         {
         QR = new Matrix(A);
         newB = new Matrix(B);
     }
         else
     {
             QR = A;
         newB = B;
     }
     Matrix* X = record->sol;
         if (X == NULL)
     {
         if (nbColsB == 1)
             X = record->sol = new ColumnVector(nbColsA);
         else
             X = record->sol = new Matrix(nbColsA, nbColsB);
     }
     else
     {
         FAIL_CONDITION( nbRowsA != X->getNbRows(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the SLE's matrix");
         FAIL_CONDITION( nbColsB != X->getNbCols(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the right-side term");
     }
     double* const*const qr = QR->getMatrix(R_W_ACCESS);
     double** v = new double*[nbColsA];
     for (int j=0, lv=nbRowsA; j<nbColsA; j++, lv--)
         v[j] = new double[lv];
     double* colR = new double[nbRowsA];
     record->status = factorize_(nbRowsA, nbColsA, qr, colR, v);
     double* const*const b = newB->getMatrix(R_W_ACCESS);
     applyQt_(nbRowsB, nbColsB, nbColsB, v, b);
     solveBS_(nbColsA, nbColsB, qr, b, X->getMatrix(R_W_ACCESS));
     delete []colR;
     for (int j=0; j<nbColsA; j++)
         delete []v[j];
     delete []v;
     if (preserveMatrix)
         {
         delete QR;
                 delete newB;
         }
 }
void LinearSolver_QR::solveBS_ (int nbRows, int nbCols, const double *const *const r, const double *const *const b, double *const *const x) static private
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
nbRows number of rows of the SLE
nbCols number of columns of the SLE
r the upper triangular matrix of the QR factorization
b the right-side term of the SLE (after multiplication by Q^T
x the solution to the SLE
Definition at line 476 of file LinearSolver_QR.cpp.
Referenced by solve(), and solve_().
 {
     //  We want to solve R . X = B
     //  The outer loop deals with the columns of the right-side term
     for (int j=0; j<nbCols; j++)
     {
         if (r[nbRows-1][nbRows-1] != 0)
             x[nbRows-1][j] = b[nbRows-1][j] / r[nbRows-1][nbRows-1];
         else
             x[nbRows-1][j] = 0.L;
         for (int i=nbRows-2; i>=0; i--)
         {
             x[i][j] = b[i][j];
             for (int k=i+1; k<nbRows; k++)
                 x[i][j] -= r[i][k] * x[k][j];
             if (r[i][i] != 0)
                 x[i][j] /= r[i][i];
         }
     }
 }
Member Data Documentation
double* uriVL::LinearSolver_QR::colR_ private
Vector used to store (part of) a column of R_.
Definition at line 218 of file LinearSolver_QR.h.
Referenced by LinearSolver_QR(), setMatrix(), and ~LinearSolver_QR().
const double LinearSolver_QR::ILL_COND_THRESHOLD = 1.E-7 static private
Minimum value for the norm of a partial column before the matrix is considered to be ill-conditioned.
Definition at line 201 of file LinearSolver_QR.h.
Referenced by computeHouseholderV_().
Matrix* uriVL::LinearSolver_QR::R_ private
Matrix in which the QR factorization calculations are done.
Initially, this matrix will be a copy of the input matrix A (if preserveMatrix was set true) or simply a reference to it (preserveMatrix false for "destructive" version)
Definition at line 207 of file LinearSolver_QR.h.
Referenced by LinearSolver_QR(), setMatrix(), solve(), and ~LinearSolver_QR().
double** uriVL::LinearSolver_QR::v_ private
2D array that stores the v vectors of the Householder algorithm used to generate the orthogonal matrices of the factorization.
The vectors are stored on rows of this array. If the SLE'smatrix is mxn, then the first vector v_[0] has m elements and the last vector v_[n-1] has m-n-1 elements.
Definition at line 214 of file LinearSolver_QR.h.
Referenced by LinearSolver_QR(), setMatrix(), solve(), and ~LinearSolver_QR().
The documentation for this class was generated from the following files:
LinearSolver_QR.h
LinearSolver_QR.cpp