URIVisionLibrary: uriVL::LinearSolver_LU Class Reference
uriVL::LinearSolver_LU Class Reference
Class that implement Crout's version of the LU factorization algorithm for solving SLEs.
#include <LinearSolver_LU.h>
Public Member Functions
LinearSolver_LU (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_LU object.
LinearSolver_LU (Matrix *A, bool preserveMatrix=false)
Constructor.
~LinearSolver_LU (void)
Constructor.
void setMatrix (Matrix *A, bool preserveMatrix=false)
Assigns a new matrix to this LinearSolver.
LinearSolverRecord * solve (Matrix *b)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
LinearSolverRecord * solve (Matrix *b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Public Member Functions inherited from uriVL::LinearSolver
virtual ~LinearSolver (void)
Destructor.
Static Public Member Functions
static LinearSolverRecord * solve (Matrix *A, Matrix *B, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecord * solve (Matrix *A, Matrix *B, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
Private Member Functions
LinearSolver_LU (const LinearSolver_LU &obj)
Copy constructor: disabled.
const LinearSolver_LU & operator= (const LinearSolver_LU &obj)
Copy operator: disabled.
Static Private Member Functions
static void solve_ (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecordStatus factorize_ (int n, double *const *const a, int *p, double *v_)
Computes the LU factorization of an SLE.
static void forwardSubstitution_ (int m, int n, double *const *const l, double *const *const b, int *p, double *const *const y)
Solves a unit-diagonal lower-triangular SLE.
static void backSubstitution_ (int m, int n, double *const *const u, double *const *const y, int *p, double *const *const x)
Solves an upper-triangular SLE.
Private Attributes
Matrix * LU_
Matrix that stores the LU factorization of the matrix for which this object was created.
int * p_
Permutation array for this factorization object.
double * v_
Array that stores row information for pivoting.
Static Private Attributes
static const double ILL_COND_PIVOT_THRESHOLD = 1.E-7
Minimum value for a pivot before the matrix is considered to be ill-conditioned.
Additional Inherited Members
Protected Member Functions inherited from uriVL::LinearSolver
LinearSolver (void)
Default constructor.
LinearSolver (int nbRows, int nbCols)
Constructor: initializes the dimensions of the linear solver.
LinearSolver (Matrix *a, bool preserveMatrix=false)
Constructor: initializes the dimensions of the linear solver.
void setSingularityStatus_ (LinearSolverRecordStatus singularityStatus)
Sets the singularityStatus_.
LinearSolverRecordStatus getSingularityStatus_ (void)
Get the singularityStatus_.
int getNbRows_ (void)
Reports the number of rows of the solver's matrix.
int getNbCols_ (void)
Reports the number of rows of the solver's matrix.
void setMatrixDimensions_ (int nbRows, int nbCols)
Sets the dimensions of the solver's matrix.
int getNbStorageRows_ (void)
Reports the number of storage rows of the solver's matrix.
int getNbStorageCols_ (void)
Reports the number of storage rows of the solver's matrix.
void setMatrixStorageDimensions_ (int nbRows, int nbCols)
Sets the storage dimensions of the solver's matrix.
bool getMatrixIsLocal_ (void)
Reports whether the solver keeps a local copy of the SLE's matrix.
void setMatrixIsLocal_ (bool matrixIsLocal)
Sets whether the solver keeps a local copy of the SLE's matrix.
Detailed Description
Class that implement Crout's version of the LU factorization algorithm for solving SLEs.
This implementation was certainly influenced by that found in the Numerical Recipes in C, but it is a complete recoding, not just an adaptation.
Important note about LinearSolver classes: These classes have been built for speed, not for OOP orthodoxy. We try to minimize as much as possible the number of malloc/delete operations. The default behavior of most functions in these classes is to only keep references to the SLE's matrix, not copies of it, and to perform claculations directly in that matrix (destructive behavior). If this behavior is not desirable for your application, then call the function with the parameter preserveMatrix set to true, when available.
Author
jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 42 of file LinearSolver_LU.h.
Constructor & Destructor Documentation
LinearSolver_LU::LinearSolver_LU (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_LU object.
That matrix must have as many rows as it has columns otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
nbRows the maximum number of rows in the matrix
nbCols the maximum number of columns in the matrix
Definition at line 26 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, LU_, p_, uriVL::LinearSolver::setMatrixIsLocal_(), and v_.
         :   LinearSolver(nbRows, nbCols),
             //
             LU_(new Matrix(nbRows, nbCols)),
             p_(new int[nbRows]),
             v_(new double[nbRows])
 {
     if (nbRows != nbCols)
     {
         delete LU_;
         delete []v_;
         delete []p_;
         FAIL_CONDITION( true,
                         kInvalidParameterError,
                         "Nonsquare SLE assigned to a LinearSolver_LU");
     }
         setMatrixIsLocal_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LinearSolver_LU constructor");
         throw e;
 }
LinearSolver_LU::LinearSolver_LU (Matrix * A, bool preserveMatrix = false)
Constructor.
A LinearSolver_LU is created for a specific matrix. That matrix must be square otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 53 of file LinearSolver_LU.cpp.
References factorize_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::LinearSolver::getNbCols_(), uriVL::LinearSolver::getNbRows_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, LU_, p_, uriVL::R_W_ACCESS, uriVL::LinearSolver::setSingularityStatus_(), and v_.
         :   LinearSolver(A, preserveMatrix),
                         //
                         LU_(preserveMatrix ? new Matrix(A) : A),
                         p_(new int[A->getNbRows()]),
                         v_(new double[A->getNbRows()])
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_LU");
         if (getNbRows_() != getNbCols_())
         {
                 delete []v_;
                 delete []p_;
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Nonsquare matrix assigned to a LinearSolver_LU");
         }
     double* const*const lu = LU_->getMatrix(R_W_ACCESS);
     setSingularityStatus_(factorize_(getNbRows_(), lu, p_, v_));
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LinearSolver_LU constructor");
         throw e;
 }
LinearSolver_LU::~LinearSolver_LU (void)
Constructor.
A LinearSolver_LU is created for a specific dimension of the SLE and number of clumns of the right-side term. This is the version of the constructor to use if you are going to always operate in destructive mode and are going to request a couple of steps of incremental improvement of the solution. Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
n dimension of the SLE
nbRighSideCols number of columns of the right-side term (if known in advance.Destructor
Definition at line 95 of file LinearSolver_LU.cpp.
References uriVL::LinearSolver::getMatrixIsLocal_(), LU_, p_, and v_.
 {
     if (getMatrixIsLocal_())
         delete LU_;
     delete[] p_;
     delete[] v_;
 }
LinearSolver_LU::LinearSolver_LU (const LinearSolver_LU & obj) private
Copy constructor: disabled.
Parameters
obj reference to the object to copy
Definition at line 81 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :   LinearSolver(),
             //
             LU_(NULL),
             p_(NULL),
             v_(NULL)
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_LU copy constructor not inplemented");
 }
Member Function Documentation
void LinearSolver_LU::backSubstitution_ (int m, int n, double *const *const u, double *const *const y, int * p, double *const *const x) static private
Solves an upper-triangular SLE.
Parameters
m the dimension of the SLE's matrix
n the number of columns of the right-side term
u the lower-triangular matrix of the SLE
y the SLE's right-side term
p the preallocated index permutation array
x the solution matrix/vector
Definition at line 522 of file LinearSolver_LU.cpp.
Referenced by solve(), and solve_().
 {
     //  We want to solve P(U). X = Y
     //  The row permutations applied to  do not affect X, but must be applied to Y
     //  as well to preserve the equation
     //  The outer loop deals with the columns of the right-side term
     for (int j=0; j<n; j++)
     {
         int ip = p[m-1];
         if (u[ip][m-1] != 0)
             x[m-1][j] = y[m-1][j] / u[ip][m-1];
         else
             x[m-1][j] = 0.L;
         for (int i=m-2; i>=0; i--)
         {
             ip = p[i];
             x[i][j] = y[i][j];
             for (int k=i+1; k<m; k++)
                 x[i][j] -= u[ip][k] * x[k][j];
             if (u[ip][i] != 0)
                 x[i][j] /= u[ip][i];
         }
     }
 }
LinearSolverRecordStatus LinearSolver_LU::factorize_ (int n, double *const *const a, int * p, double * v_) static private
Computes the LU factorization of an SLE.
Parameters
n the dimension of the SLE
a the matrix of the SLE
p the preallocated index permutation array
v a preallocated array for pivoting calculations
Returns
a matrix singularity status
Definition at line 396 of file LinearSolver_LU.cpp.
References ILL_COND_PIVOT_THRESHOLD, uriVL::ILL_CONDITIONED_MATRIX, uriVL::REGULAR_MATRIX, and uriVL::SINGULAR_MATRIX.
Referenced by LinearSolver_LU(), setMatrix(), and solve_().
 {
     //  a, l, u, lu are all aliases of the same array
     double* const*const l = a;
     double* const*const lu = a;
     double* const*const u = a;
     LinearSolverRecordStatus status = REGULAR_MATRIX;
     for (int i=0; i<n; i++)
         p[i] = i;
     //-----------------------------------------------------------
     //  Step 1: Determine largest element of each row
     //-----------------------------------------------------------
     for (int i=0; i<n; i++)
     {
         double val, valMax = a[i][0];
         for (int j=1; j<n; j++)
             if ((val = fabs(a[i][j])) > valMax)
                 valMax = val;
         v[i] = valMax;
     }
     //-----------------------------------------------------------
     //  Step 2: Apply Crout's algorithm with partial pivoting
     //-----------------------------------------------------------
     for (int j=0; j<n; j++)
     {
         //-------------------------------------------
         //  process superdiagonal elements
         //-------------------------------------------
         for (int i=0; i<j; i++)
             //  u[p[i]][j] stores a[p[i]][j]
             for (int k=0; k<i; k++)
                 u[p[i]][j] -= l[p[i]][k] * u[p[k]][j];
         //-------------------------------------------
         //  process diagonal and subdiagonal elements
         //-------------------------------------------
         for (int i=j; i<n; i++)
             //  lu[p[i]][j] stores a[p[i]][j]
             for (int k=0; k<j; k++)
                 lu[p[i]][j] -= l[p[i]][k] * u[p[k]][j];
         //  The last column has no subdiagonal elements
         if (j < n-1)
         {
             //-------------------------------------------
             //  find index of best pivot, rows j to n-1
             //-------------------------------------------
             double maxRatio = v[p[j]] != 0 ? fabs(lu[p[j]][j]) / v[p[j]] : 0.L;
             double ratio;
             int    iBest = j;
             for (int i=j+1; i<n; i++)
             {
                 if ((ratio = fabs(lu[p[i]][j]) / v[p[i]]) > maxRatio)
                 {
                     maxRatio = ratio;
                     iBest = i;
                 }
             }
             //  if j is not the best pivot, swap rows
             if (iBest != j)
             {
                 int temp = p[j];
                 p[j] = p[iBest];
                 p[iBest] = temp;
             }
             //-------------------------------------------
             //  Compute the scale and apply is to all
             //  subdiagonal elements
             //-------------------------------------------
             double s;
             if (fabs(u[p[j]][j]) > ILL_COND_PIVOT_THRESHOLD)
                 s = 1.L / u[p[j]][j];
             else if (u[p[j]][j] == 0.L)
             {
                 status = SINGULAR_MATRIX;
                 s = 0.L;
             }
             else
             {
                 if (status != SINGULAR_MATRIX)
                     status = ILL_CONDITIONED_MATRIX;
                 s = 1.L / u[p[j]][j];
             }
             for (int i=j+1; i<n; i++)
                 l[p[i]][j] *= s;
         }
     }
     return status;
 }
void LinearSolver_LU::forwardSubstitution_ (int m, int n, double *const *const l, double *const *const b, int * p, double *const *const y) static private
Solves a unit-diagonal lower-triangular SLE.
Parameters
m the dimension of the SLE's matrix
n the number of columns of the right-side term
l the lower-triangular matrix of the SLE
b the SLE's right-side term
p the preallocated index permutation array
y the solution matrix/vector
Definition at line 497 of file LinearSolver_LU.cpp.
Referenced by solve(), and solve_().
 {
     //  We want to solve P(L) . Y = B
     //  The row permutations applied to L do not affect Y, but must be applied to B
     //  as well to preserve the equation
     //  The outer loop deals with the columns of the right-side term
     for (int j=0; j<n; j++)
     {
         int ip = p[0];
         y[0][j] = b[ip][j];
         for (int i=1; i<m; i++)
         {
             ip = p[i];
             y[i][j] = b[ip][j];
             for (int k=0; k<i; k++)
                 y[i][j] -= l[ip][k] * y[k][j];
         }
     }
 }
const LinearSolver_LU & LinearSolver_LU::operator= (const LinearSolver_LU & obj) private
Copy operator: disabled.
Parameters
obj reference to the object to copy
Definition at line 107 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_LU copy opertator not inplemented");
         return *this;
 }
void LinearSolver_LU::setMatrix (Matrix * A, bool preserveMatrix = false) virtual
Assigns a new matrix to this LinearSolver.
This call only makes sense if the new matrix has the same dimensions as the previous one (it then saves a destruction and an allocation of a matrix). Otherwise, just use the static solve function.
Important: If you don't set preserveMatrix true, then the LinearSolver only stores a reference to matrix it receives as a parameter. It will do calculations in this matrix.
You cannot delete it before you call the solve function,
The matrix's elements will be modified (destructive behavior)
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Implements uriVL::LinearSolver.
Definition at line 117 of file LinearSolver_LU.cpp.
References factorize_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, LU_, p_, uriVL::R_W_ACCESS, uriVL::LinearSolver::setMatrixDimensions_(), uriVL::LinearSolver::setMatrixIsLocal_(), uriVL::LinearSolver::setMatrixStorageDimensions_(), uriVL::LinearSolver::setSingularityStatus_(), and v_.
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_LU");
     const int nbRows = A->getNbRows(),
               nbCols = A->getNbCols();
     FAIL_CONDITION( nbRows != nbCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_LU");
     //  First, take care of p_ and v_
     if (LU_->getNbRows() != nbRows)
     {
         delete []v_;
         delete []p_;
         v_ = new double[nbRows];
         p_ = new int[nbRows];
     }
     setMatrixDimensions_(nbRows, nbRows);
     //  If we were already storing a local copy of a previous SLE's matrix,
     //  then we may have to do delete/reallocate that local copy
     if (getMatrixIsLocal_())
     {
         if (preserveMatrix)
         {
             //  If the new matrix has different dimensions from the old one, we
             //  must delete & reallocate LU_ and the permutation array
             if ((LU_->getNbRows() != nbRows) || (LU_->getNbCols() != nbCols))
             {
                 if (LU_ != NULL)
                     delete LU_;
                 LU_ = new Matrix(A);
             }
             //  if the dimensions did not change we simply copy the data
             else
                 (*LU_) = (*A);
             setMatrixStorageDimensions_(nbRows, nbRows);
         }
         //  If the matrix was local, but should not be anymore, we simply delete the
         //  current matrix and store the reference to the new one
         else
         {
             delete LU_;
             LU_ = A;
         }
     }
     else
     {
         if (preserveMatrix)
             LU_ = new Matrix(A);
         else
             LU_  =A;
     }
     setMatrixIsLocal_(preserveMatrix);
     double* const*const lu = LU_->getMatrix(R_W_ACCESS);
     setSingularityStatus_(factorize_(nbRows, lu, p_, v_));
 }
LinearSolverRecord * LinearSolver_LU::solve (Matrix * b) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 187 of file LinearSolver_LU.cpp.
Referenced by main(), and solve().
 {
     return solve(B, 0);
 }
LinearSolverRecord * LinearSolver_LU::solve (Matrix * b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 192 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_LU");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( nbRows != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve(B, record, incrImprov);
     return record;
 }
void LinearSolver_LU::solve (Matrix * b, LinearSolverRecord * record) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 214 of file LinearSolver_LU.cpp.
References solve().
 {
     solve(B, record, 0);
 }
void LinearSolver_LU::solve (Matrix * b, LinearSolverRecord * record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
record stores the solution to the SLe and indication about the matrix's regularity.
Definition at line 219 of file LinearSolver_LU.cpp.
References backSubstitution_(), FAIL_CONDITION, forwardSubstitution_(), uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::LinearSolver::getSingularityStatus_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, LU_, p_, uriVL::R_W_ACCESS, uriVL::LinearSolverRecord::sol, and uriVL::LinearSolverRecord::status.
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_LU");
     FAIL_CONDITION( record == NULL,
                     kNullParameterError,
                     "Null LinearSolverRecord term sent to a LinearSolver_LU");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( nbRows != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     Matrix* X = record->sol;
     //  if the solution was not allocated we do it now
     if (X == NULL)
     {
         if (nbCols == 1)
             X = record->sol = new ColumnVector(nbRows);
         else
             X = record->sol = new Matrix(nbRows, nbCols);
     }
     else
     {
         FAIL_CONDITION( nbRows != X->getNbRows(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the SLE");
         FAIL_CONDITION( nbCols != X->getNbCols(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the right-side term");
     }
     double* const*const lu = LU_->getMatrix(R_W_ACCESS);
     double* const*const b = B->getMatrix(R_W_ACCESS);
     double* const*const x = X->getMatrix(R_W_ACCESS);
     forwardSubstitution_(nbRows, nbCols, lu, b, p_, x);
     backSubstitution_(nbRows, nbCols, lu, x, p_, x);
 /*
     //  Incremental improvement (using residual as right-side term for the
     //  corrective term)
     for (int k=0; k< incrImprov; k++)
     {
         Matrix R =
     }
 */
     record->status = getSingularityStatus_();
 }
LinearSolverRecord * LinearSolver_LU::solve (Matrix * A, Matrix * B, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 274 of file LinearSolver_LU.cpp.
References solve().
 {
     return solve(A, B, 0, preserveMatrix);
 }
LinearSolverRecord * LinearSolver_LU::solve (Matrix * A, Matrix * B, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 280 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_LU");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_LU");
     const int aRows = A->getNbRows(),
               aCols = A->getNbCols();
     FAIL_CONDITION( aRows != aCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_LU");
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_LU");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve_(A, B, record, incrImprov, preserveMatrix);
     return record;
 }
void LinearSolver_LU::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 312 of file LinearSolver_LU.cpp.
References solve().
 {
     solve(A, B, record, 0, preserveMatrix);
 }
void LinearSolver_LU::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 319 of file LinearSolver_LU.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_LU");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_LU");
     const int aRows = A->getNbRows(),
               aCols = A->getNbCols();
     FAIL_CONDITION( aRows != aCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_LU");
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_LU");
     //  was the record properly created?
     if (record->sol != NULL)
     {
         FAIL_CONDITION( (nbRows != record->sol->getNbRows()) ||
                         (nbCols != record->sol->getNbCols()),
                         kInvalidParameterError,
                         "right-side term and solution's dimensions dont match for LinearSolver_LU");
     }
     //  if the solution was not allocated we do it now
     else
     {
         if (nbCols == 1)
             record->sol = new ColumnVector(nbRows);
         else
             record->sol = new Matrix(nbRows, nbCols);
     }
     solve_(A, B, record, incrImprov, preserveMatrix);
 }
void LinearSolver_LU::solve_ (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix) static private
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 360 of file LinearSolver_LU.cpp.
References backSubstitution_(), factorize_(), forwardSubstitution_(), uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::R_W_ACCESS, uriVL::LinearSolverRecord::sol, and uriVL::LinearSolverRecord::status.
Referenced by solve().
 {
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     Matrix *X = record->sol;
     int* p = new int[nbRows];
     double* v = new double[nbRows];
     Matrix *LU;
     if (preserveMatrix)
         LU = new Matrix(A);
     else
         LU = A;
     double* const*const lu = LU->getMatrix(R_W_ACCESS);
     double* const*const b = B->getMatrix(R_W_ACCESS);
     double* const*const x = X->getMatrix(R_W_ACCESS);
     record->status = factorize_(nbRows, lu, p, v);
     forwardSubstitution_(nbRows, nbCols, lu, b, p, x);
     backSubstitution_(nbRows, nbCols, lu, x, p, x);
     delete []p;
     delete []v;
     if (preserveMatrix)
         delete LU;
 }
Member Data Documentation
const double LinearSolver_LU::ILL_COND_PIVOT_THRESHOLD = 1.E-7 static private
Minimum value for a pivot before the matrix is considered to be ill-conditioned.
Definition at line 216 of file LinearSolver_LU.h.
Referenced by factorize_().
Matrix* uriVL::LinearSolver_LU::LU_ private
Matrix that stores the LU factorization of the matrix for which this object was created.
Definition at line 221 of file LinearSolver_LU.h.
Referenced by LinearSolver_LU(), setMatrix(), solve(), and ~LinearSolver_LU().
int* uriVL::LinearSolver_LU::p_ private
Permutation array for this factorization object.
Definition at line 225 of file LinearSolver_LU.h.
Referenced by LinearSolver_LU(), setMatrix(), solve(), and ~LinearSolver_LU().
double* uriVL::LinearSolver_LU::v_ private
Array that stores row information for pivoting.
Definition at line 229 of file LinearSolver_LU.h.
Referenced by LinearSolver_LU(), setMatrix(), and ~LinearSolver_LU().
The documentation for this class was generated from the following files:
LinearSolver_LU.h
LinearSolver_LU.cpp