URIVisionLibrary: uriVL::RasterImage_gray_F Class Reference
uriVL::RasterImage_gray_F Class Reference
Floating point gray-level image class.
#include <RasterImage_gray_F.h>
Public Member Functions
RasterImage_gray_F (int nbRows, int nbCols)
Allocates a float gray-level raster image at the specified dimensions.
RasterImage_gray_F (const ImageRect *theRect)
Allocates a float gray-level raster image at the specified dimensions.
RasterImage_gray_F (int nbRows, int nbCols, const unsigned char *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const ImageRect *theRect, const unsigned char *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (int nbRows, int nbCols, const float *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const ImageRect *theRect, const float *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const GraphWorld *gworld)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const RasterImage *img)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const RasterImage *img, const ImageRect *theRect)
Initializes a float raster image at the specified dimensions and values.
~RasterImage_gray_F (void)
Destructor.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
const float * getGrayF (void) const
Returns the float gray-level raster for this image as a read-only 1D array.
float * getGrayF (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 1D array.
const float *const * getGrayF2D (void) const
Returns the float gray-level raster for this image as a read-only 2D array.
float *const * getGrayF2D (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 2D array.
const float *const * getShiftedGrayF2D (void) const
Returns the shifted float gray-level raster for this image as a read-only 2D array.
float *const * getShiftedGrayF2D (ReadWriteStatus rw)
Returns the shifted float gray-level raster for this image as a read-write 2D array.
const unsigned char * getGray (void) const
Returns the 8-bit gray-level base raster as a read-only 1D array.
unsigned char * getGray (ReadWriteStatus rw)
Returns the 8-bit gray-level base raster as a read-write 1D array.
const unsigned char *const * getGray2D (void) const
Returns the 8-bit gray-level base raster as a read-only 2D array.
unsigned char *const * getGray2D (ReadWriteStatus rw)
Returns the 8-bit gray-level base raster as a read-write 2D array.
const unsigned char *const * getShiftedGray2D (void) const
Returns the shifted 8-bit gray-level base raster as a read-only 2D array.
unsigned char *const * getShiftedGray2D (ReadWriteStatus rw)
Returns the shifted 8-bit gray-level base raster as a read-write 2D array.
void setFloatConversionMode (const ConversionFromFloatMode theMode)
Sets an individual conversion mode from float to gray for this image.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image's conversion mode from float to gray.
Public Member Functions inherited from uriVL::RasterImage_gray
RasterImage_gray (int nbRows, int nbCols)
Allocates an 8-bit gray-level raster image at the specified dimensions.
RasterImage_gray (int nbRows, int nbCols, const unsigned char *theGray)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const ImageRect *theRect)
Allocates an 8-bit gray-level raster image at the specified dimensions.
RasterImage_gray (const ImageRect *theRect, const unsigned char *theGray)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const GraphWorld *gworld)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const RasterImage *img)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const RasterImage *img, const ImageRect *theRect)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
virtual ~RasterImage_gray (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void setDefaultFloatConversionMode (const ConversionFromFloatMode theMode)
Sets the default conversion mode from float to gray for this class.
Static Public Member Functions inherited from uriVL::RasterImage_gray
static void convertToBinary (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D binary raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 16-bit argb raster.
static const RasterImage_gray * localRasterGray (const RasterImage *imgIn, bool *localGray)
Allocates a read-only gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static const RasterImage_gray * localRasterGray (const RasterImage *imgIn, const ImageRect *rect, bool *localGray)
Allocates a read-only gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static RasterImage_gray * localRasterGray (RasterImage *imgIn, bool *localGray)
Allocates a writable gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static RasterImage_gray * localRasterGray (RasterImage *imgIn, const ImageRect *rect, bool *localGray)
Allocates a gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
RasterImage_gray_F (void)
Default constructor.
Protected Member Functions inherited from uriVL::RasterImage_gray
RasterImage_gray (void)
Default constructor.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Private Member Functions
RasterImage_gray_F (const RasterImage_gray_F &img)
Creates a new raster image based on the one received as parameter.
const RasterImage_gray_F & operator= (const RasterImage_gray_F &theImg)
Equal operator.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void convertToRGBa_ (const float *theSource, unsigned char *theDestination, long nbPixels, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts this image's base raster into a 1D 32-bit rgba raster.
void convertToRGB_ (const float *theSource, unsigned char *theDestination, long nbPixels, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts this image's base raster into a 1D 24-bit rgb raster.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
void updateRaster_ (void) const
Updates the image's base raster (if it is not the reference).
void calculateFloatConversionParams_ (void) const
Calculates the parameters of a conversion to gray.
Static Private Member Functions
static void convertToGray_ (const float *theSource, unsigned char *theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv=kUndefFloatConv)
Converts this image's base raster into a 1D gray-level raster.
Private Attributes
float * fltGray_
The float gray-level raster of this image.
float ** fltGray2D_
The 0-based 2D float gray-level raster mapped over fltGray_.
float ** shiftedFltGray2D_
The shifted 2D float gray-level raster mapped over fltGray_.
bool hasIndivFloatConvMode_
True if an algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
ConversionFromFloatMode floatConv_
Code for the algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
float valMin_
Minimum value over the raster.
float valMax_
Minimum value over the raster.
float convScale_
Scale factor to apply in a float to gray conversion.
Static Private Attributes
static ConversionFromFloatMode defaultFloatConv_ = kSignedFloat
Code for the default algorithm for conversion from float to gray.
Friends
class RasterImage_gray
Detailed Description
Floating point gray-level image class.
This class is heavily used by the image operator classes.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 32 of file RasterImage_gray_F.h.
Constructor & Destructor Documentation
RasterImage_gray_F::RasterImage_gray_F (int nbRows, int nbCols)
Allocates a float gray-level raster image at the specified dimensions.
Allocates a float gray-level raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Definition at line 51 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::RasterImage::setGraphWorldAsReference_(), and uriVL::RasterImage::setReferenceHasChanged_().
                    :    RasterImage_gray(nbRows, nbCols),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     setGraphWorldAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
RasterImage_gray_F::RasterImage_gray_F (const ImageRect * theRect)
Allocates a float gray-level raster image at the specified dimensions.
Allocates a float gray-level raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 135 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::RasterImage::setGraphWorldAsReference_(), and uriVL::RasterImage::setReferenceHasChanged_().
         :       RasterImage_gray(theRect),
                         //
                         fltGray_(NULL),
                         fltGray2D_(NULL),
                         shiftedFltGray2D_(NULL),
                         hasIndivFloatConvMode_(false),
                         floatConv_(kUndefFloatConv),
                         valMin_(+HUGE_VALF),
                         valMax_(-HUGE_VALF),
                         convScale_(1.f)
 {
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(), theRect->getTop(), theRect->getLeft());
     setGraphWorldAsReference_();
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray constructor");
         throw e;
 }
RasterImage_gray_F::RasterImage_gray_F (int nbRows, int nbCols, const unsigned char * theGray)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes it with the contents of the raster received as parameter.
Parameters
nbRows number of rows of the rgb raster image
nbCols number of columns of the rgb raster image
theGray values to which the image should be initialized
Definition at line 76 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), and allocateShiftedRaster2D_().
                         :   RasterImage_gray(nbRows, nbCols, theGray),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kPositiveFloat),     //  all the values in this raster are positive
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
RasterImage_gray_F::RasterImage_gray_F (const ImageRect * theRect, const unsigned char * theGray)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes it with the contents of the raster received as parameter.
Parameters
theRect ImageRect specifying the image's bounding rectangle
theGray values to which the image should be initialized
Definition at line 159 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), and uriVL::RasterImage::setHasFloatRaster_().
                         :   RasterImage_gray(theRect, theGray),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kPositiveFloat),     //  all the values in this raster are positive
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
 //    const int   iLow = theRect->getTop(),
 //                      iHigh = theRect->getBottom(),
 //                      jLow = theRect->getLeft(),
 //                      jHigh = theRect->getRight();
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
 //      try {
 //              long    lSource = 0;
 //              for (int i=iLow; i<=iHigh; i++)
 //                      for (int j=jLow; j<=jHigh; j++)
 //                              shiftedFltGray2D_[i][j] = theGray[lSource++];
 //      }
 //      catch(...) {
 //              FAIL_CONDITION( theGray == NULL,
 //                                              kNullRasterError,
 //                                              "null raster as parameter in RasterImage_gray_F constructor");
 //              FAIL_CONDITION( true,
 //                                              kMemoryCopyError,
 //                                              "Data copy error in RasterImage_gray_F constructor");
 //      }
     setHasFloatRaster_(true);
 //    setFloatRasterAsReference_();
 //    setReferenceHasChanged_(true);
 //      setValidRect(theRect);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( theRect == NULL,
                                         kNullRectangleError,
                                         "null ImageRect as parameter in RasterImage_gray_F constructor");
 }
RasterImage_gray_F::RasterImage_gray_F (int nbRows, int nbCols, const float * theGray)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes it with the contents of the raster received as parameter.
Parameters
nbRows number of rows of the rgb raster image
nbCols number of columns of the rgb raster image
theGray values to which the image should be initialized
Definition at line 98 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), FAIL_CONDITION, fltGray2D_, uriVL::kNullRasterError, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and uriVL::DrawableObject2D::setValidRect().
                         :   RasterImage_gray(nbRows, nbCols),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 //
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 //
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     FAIL_CONDITION( theGray == NULL,
                     kNullRasterError,
                     "null raster as parameter in RasterImage_gray_F constructor");
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     long    lSource = 0;
     for (int i=0; i<nbRows; i++)
         for (int j=0; j<nbCols; j++)
             fltGray2D_[i][j] = theGray[lSource++];
         setValidRect(0, 0, nbCols, nbRows);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
RasterImage_gray_F::RasterImage_gray_F (const ImageRect * theRect, const float * theGray)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes it with the contents of the raster received as parameter.
Parameters
theRect ImageRect specifying the image's bounding rectangle
theGray values to which the image should be initialized
Definition at line 210 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kNullRasterError, uriVL::kNullRectangleError, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), uriVL::DrawableObject2D::setValidRect(), and shiftedFltGray2D_.
                         :       RasterImage_gray(theRect),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in RasterImage_gray_F constructor");
     FAIL_CONDITION( theGray == NULL,
                     kNullRasterError,
                     "null raster as parameter in RasterImage_gray_F constructor");
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(), theRect->getTop(), theRect->getLeft());
     const int   iLow = theRect->getTop(),
                         iHigh = theRect->getBottom(),
                         jLow = theRect->getLeft(),
                         jHigh = theRect->getRight();
     long    lSource = 0;
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             shiftedFltGray2D_[i][j] = theGray[lSource++];
         setValidRect(theRect);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( theRect == NULL,
                                         kNullRectangleError,
                                         "null ImageRect as parameter in RasterImage_gray_F constructor");
 }
RasterImage_gray_F::RasterImage_gray_F (const GraphWorld * gworld)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter.
Parameters
gworld the GraphWorld to use for dimensions and values
Definition at line 257 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   RasterImage_gray( ),
                         //
                         fltGray_(NULL),
                         fltGray2D_(NULL),
                         shiftedFltGray2D_(NULL),
                         hasIndivFloatConvMode_(false),
                         floatConv_(kUndefFloatConv),
                         valMin_(+HUGE_VALF),
                         valMax_(-HUGE_VALF),
                         convScale_(1.f)
 {
     FAIL_CONDITION( true, kFunctionNotImplemented,
                     "RasterImage_gray GraphWorld clone constructor is not operative yet");
 }
RasterImage_gray_F::RasterImage_gray_F (GraphWorld * gworld, bool keepThisGraphWorld)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter. Possibly keeps the GraphWorld received as parameter rather than making a copy of it.
Parameters
gworld the GraphWorld to use for dimensions and values
keepThisGraphWorld if true, then this new image raster object will simply store a reference to a pre-allocated GWorld instead of allocating its own (beware!)
Definition at line 273 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   RasterImage_gray( ),
                         //
                         fltGray_(NULL),
                         fltGray2D_(NULL),
                         shiftedFltGray2D_(NULL),
                         hasIndivFloatConvMode_(false),
                         floatConv_(kUndefFloatConv),
                         valMin_(+HUGE_VALF),
                         valMax_(-HUGE_VALF),
                         convScale_(1.f)
 {
     FAIL_CONDITION( true, kFunctionNotImplemented,
                     "RasterImage_gray GraphWorld clone constructor is not operative yet");
 }
RasterImage_gray_F::RasterImage_gray_F (const RasterImage * img)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
Definition at line 292 of file RasterImage_gray_F.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::kPositiveFloat, setFloatConversionMode(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setHasFloatRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :   RasterImage_gray(img),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     //  Although technically the float raster does not exist yet,
     //  we do this to force the writing to take place in the float
     //  raster rather than in the GraphWorld.
     setHasFloatRaster_(true);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
         try {
                 img->copyInto(this, img->getValidRect());
         }
         catch(ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_gray_F constructor");
                 throw e;
         }
     //  if img was a float raster image, then in the copyInto function
     //  it already attributed "me" its float to gray conversion mode.
     //  If img does not have a float raster, then all its values
     //  are positive
     if (!img->hasFloatRaster())
         setFloatConversionMode(kPositiveFloat);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( img == NULL,
                                         kNullRectangleError,
                                         "null RasterImage pointer as parameter in RasterImage_gray_F constructor");
 }
RasterImage_gray_F::RasterImage_gray_F (const RasterImage * img, const ImageRect * theRect)
Initializes a float raster image at the specified dimensions and values.
Allocates a float raster at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 341 of file RasterImage_gray_F.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), uriVL::RasterImage::hasFloatRaster(), uriVL::kPositiveFloat, setFloatConversionMode(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setHasFloatRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_gray(img, theRect),
                                 //
                                 fltGray_(NULL),
                                 fltGray2D_(NULL),
                                 shiftedFltGray2D_(NULL),
                                 hasIndivFloatConvMode_(false),
                                 floatConv_(kUndefFloatConv),
                                 valMin_(+HUGE_VALF),
                                 valMax_(-HUGE_VALF),
                                 convScale_(1.f)
 {
     //  Although technically the float raster does not exist yet,
     //  we do this to force the writing to take place in the float
     //  raster rather than in the GraphWorld.
     setHasFloatRaster_(true);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
         try {
                 img->copyInto(this, theRect);
         }
         catch(ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_gray_F constructor");
                 throw e;
         }
     //  if img was a float raster image, then in the copyInto function
     //  it already attributed "me" its float to gray conversion mode.
     //  If img does not have a float raster, then all its values
     //  are positive
     if (!img->hasFloatRaster())
         setFloatConversionMode(kPositiveFloat);
     setHasFloatRaster_(true);
     setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_gray_F constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( img == NULL,
                                         kNullRectangleError,
                                         "null RasterImage pointer as parameter in RasterImage_gray_F constructor");
         FAIL_CONDITION( theRect == NULL,
                                         kNullRectangleError,
                                         "null ImageRect as parameter in RasterImage_gray_F constructor");
 }
RasterImage_gray_F::~RasterImage_gray_F (void)
Destructor.
Definition at line 411 of file RasterImage_gray_F.cpp.
References deleteRaster2D_(), deleteShiftedRaster2D_(), and uriVL::DrawableObject2D::getTop().
 {
     deleteShiftedRaster2D_(getTop());
     deleteRaster2D_();
 }
RasterImage_gray_F::RasterImage_gray_F (void) protected
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
This constructor should only be invoked from subclasses of Raster_image_gray_F
Definition at line 35 of file RasterImage_gray_F.cpp.
         :   RasterImage_gray( ),
                         //
                         fltGray_(NULL),
                         fltGray2D_(NULL),
                         shiftedFltGray2D_(NULL),
                         //
                         hasIndivFloatConvMode_(false),
                         floatConv_(kUndefFloatConv),
                         valMin_(+HUGE_VALF),
                         valMax_(-HUGE_VALF),
                         convScale_(1.f)
 {
 }
RasterImage_gray_F::RasterImage_gray_F (const RasterImage_gray_F & img) private
Creates a new raster image based on the one received as parameter.
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
img pointer to the RasterImage_gray_F object to copy
Definition at line 393 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   RasterImage_gray( ),
                         //
                         fltGray_(NULL),
                         fltGray2D_(NULL),
                         shiftedFltGray2D_(NULL),
                         hasIndivFloatConvMode_(false),
                         floatConv_(kUndefFloatConv),
                         valMin_(+HUGE_VALF),
                         valMax_(-HUGE_VALF),
                         convScale_(1.f)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_gray_F copy constructor not implemented");
 }
Member Function Documentation
void RasterImage_gray_F::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 1046 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, fltGray2D_, fltGray_, uriVL::kRasterAllocationFailure, and uriVL::RasterImage::setHasFloatRaster_().
Referenced by RasterImage_gray_F(), and setBoundRect_().
 {
     fltGray_ = new float[nbRows*nbCols];
     FAIL_CONDITION(fltGray_ == NULL, kRasterAllocationFailure,
                    "Could not allocate fltGray_ array");
     fltGray2D_ = new float*[nbRows];
     FAIL_CONDITION(fltGray2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate fltGray2D_ array");
     fltGray2D_[0] = fltGray_;
     for (int i=1; i<nbRows; i++)
         fltGray2D_[i] = fltGray2D_[i-1] + nbCols;
     setHasFloatRaster_(true);
 }
void RasterImage_gray_F::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Reimplemented from uriVL::RasterImage_gray.
Definition at line 1079 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, getGrayF(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::kRasterAllocationFailure, uriVL::R_W_ACCESS, and shiftedFltGray2D_.
Referenced by RasterImage_gray_F(), and setBoundRect_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
     {
         const int   iHigh = iLow + nbRows - 1;
         shiftedFltGray2D_ = new float*[nbRows];
         FAIL_CONDITION( shiftedFltGray2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D float gray-level  raster allocation failed");
         shiftedFltGray2D_ -= iLow;
         //
         shiftedFltGray2D_[iLow] = getGrayF(R_W_ACCESS) - jLow;
         for (int i = iLow; i < iHigh; i++)
             shiftedFltGray2D_[i+1] = shiftedFltGray2D_[i] + nbCols;
     }
     else
         shiftedFltGray2D_ = NULL;
 }
void RasterImage_gray_F::calculateFloatConversionParams_ (void) const private
Calculates the parameters of a conversion to gray.
Definition at line 921 of file RasterImage_gray_F.cpp.
References convScale_, defaultFloatConv_, floatConv_, fltGray2D_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), hasIndivFloatConvMode_, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kSignedFloat, shiftedFltGray2D_, valMax_, and valMin_.
Referenced by updateRaster_(), and writeInto_().
 {
     const float* const* theGray;
         const ImageRect* validRect = getValidRect();
     int     iLow = validRect->getTop(),
             iHigh = validRect->getBottom(),
             jLow = validRect->getLeft(),
             jHigh = validRect->getRight();
     if ((getTop()==0) && (getLeft()==0))
         theGray = fltGray2D_;
     else
         theGray = shiftedFltGray2D_;
     ConversionFromFloatMode convType;
     if (hasIndivFloatConvMode_)
         convType = floatConv_;
     else
         convType = defaultFloatConv_;
     valMin_ = valMax_ = fltGray2D_[iLow][jLow];
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             if (theGray[i][j] > valMax_)
                 valMax_ = theGray[i][j];
             else if (theGray[i][j] < valMin_)
                 valMin_ = theGray[i][j];
     switch (convType)
     {
             // We don't care about the MIN, simply rescale the MAX to 255
         case kPositiveFloat:
             valMin_ = 0.f;
             convScale_ = 255.0f/valMax_;
             break;
             //  We rescale to 0 255, with 0 at 128
         case kSignedFloat:
             if (valMax_ > -valMin_)
                 valMin_ = -valMax_;
             else
                 valMax_ = -valMin_;
             convScale_ = 127.5f/valMax_;
             break;
         case kRangeFloat:
             convScale_ = 255.f/(valMax_ - valMin_);
             break;
         default:
             break;
     }
 }
void RasterImage_gray_F::convertToGray_ (const float * theSource, unsigned char * theDestination, long nbPixels, float valMin, float convScale, ConversionFromFloatMode myFloatConv = kUndefFloatConv) static private
Converts this image's base raster into a 1D gray-level raster.
Initializes a 1D raster array to store the gray levels corresponding to this image's data. Will be called by convertToGray and copyInto.
The raster returned is not a clone of this image's base raster since it does not contain any padding of the rows.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
valMin min value of the float raster
convScale scaling factor from float to char
myFloatConv the conversion mode from float desired
Definition at line 978 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kSaturatedPositive, uriVL::kSaturatedSigned, and uriVL::kSignedFloat.
Referenced by updateRaster_(), and writeInto_().
 {
     const float     *grayIn = theSource;
     unsigned char   *grayOut = theDestination;
     switch (myFloatConv)
     {
         case kSignedFloat:
         case kPositiveFloat:
         case kRangeFloat:
             for (long l=0; l<nbPixels; l++)
                 *(grayOut++) = static_cast<unsigned char>(convScale*(*(grayIn++)-valMin));
             break;
         case kSaturatedPositive:
             for (long l=0; l<nbPixels; l++)
             {
                 float val = *(grayIn++);
                 if (val >= 0.f)
                     if (val <= 255.f)
                         *(grayOut++) = static_cast<unsigned char>(val);
                     else
                         *(grayOut++) = static_cast<unsigned char>(255);
                 else
                     *(grayOut++) = static_cast<unsigned char>(0);
             }
             break;
         case kSaturatedSigned:
             for (long l=0; l<nbPixels; l++)
             {
                 float val = *(grayIn++);
                 if (val >= -128.f)
                     if (val <= 127.f)
                         *(grayOut++) = static_cast<unsigned char>(val + 128);
                     else
                         *(grayOut++) = static_cast<unsigned char>(255);
                 else
                     *(grayOut++) = static_cast<unsigned char>(0);
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Unknown float to gray conversion mode");
             break;
     }
 }
void uriVL::RasterImage_gray_F::convertToRGB_ (const float * theSource, unsigned char * theDestination, long nbPixels, ConversionFromFloatMode myFloatConv = kUndefFloatConv) private
Converts this image's base raster into a 1D 24-bit rgb raster.
Initializes a 1D raster array to store the gray levels corresponding to this image's data. Will be called by convertToRGB and copyInto.
The raster returned is not a clone of this image's base raster since it does not contain any padding of the rows.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myFloatConv the conversion mode from float desired
void uriVL::RasterImage_gray_F::convertToRGBa_ (const float * theSource, unsigned char * theDestination, long nbPixels, ConversionFromFloatMode myFloatConv = kUndefFloatConv) private
Converts this image's base raster into a 1D 32-bit rgba raster.
Initializes a 1D raster array to store the gray levels corresponding to this image's data. Will be called by convertToRGBa and copyInto.
The raster returned is not a clone of this image's base raster since it does not contain any padding of the rows.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myFloatConv the conversion mode from float desired
void RasterImage_gray_F::copyInto (RasterImage * imgOut) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the type of the destination image, the copy may require some data conversion. If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 676 of file RasterImage_gray_F.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by copyInto(), uriVL::VectorField::getNormAndPhaseAsRasterImages(), uriVL::VectorField::getNormAsRasterImage(), uriVL::VectorField::getNormSquaredAndPhaseAsRasterImages(), uriVL::VectorField::getNormSquaredAsRasterImage(), and uriVL::VectorField::getPhaseAsRasterImage().
 {
     copyInto(imgOut, getValidRect(), NULL);
 }
void RasterImage_gray_F::copyInto (RasterImage * imgOut, const ImageRect * theRect) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the type of the destination image, the copy may require some data conversion. If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Reimplemented from uriVL::RasterImage_gray.
Definition at line 682 of file RasterImage_gray_F.cpp.
References copyInto().
 {
     copyInto(imgOut, theRect, NULL);
 }
void RasterImage_gray_F::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Reimplemented from uriVL::RasterImage_gray.
Definition at line 688 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::RasterImage::floatRasterIsReference(), and writeInto_().
 {
     //  If this image's float raster is not the reference, what we are
     //  trying to copy is just a "normal" gray level image.
     if (!floatRasterIsReference())
         RasterImage_gray::copyInto(imgOut, theRect, origin);
         //      If the float raster is the reference, then we use this class's copy mechanism
     else
     {
         //  All the rectangle testing and resizing is done in the parent class's function
         RasterImage::copyInto_(imgOut, theRect, origin);
         writeInto_(imgOut, theRect, origin);
     }
 }
void RasterImage_gray_F::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Reimplemented from uriVL::RasterImage_gray.
Definition at line 1063 of file RasterImage_gray_F.cpp.
References fltGray2D_, fltGray_, and uriVL::RasterImage::setHasFloatRaster_().
Referenced by setBoundRect_(), and ~RasterImage_gray_F().
 {
     if (fltGray2D_ != NULL)
     {
         delete []fltGray2D_;
         fltGray2D_ = NULL;
     }
     if (fltGray_ != NULL)
     {
         delete []fltGray_;
         fltGray_ = NULL;
     }
     setHasFloatRaster_(false);
 }
void RasterImage_gray_F::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Reimplemented from uriVL::RasterImage_gray.
Definition at line 1105 of file RasterImage_gray_F.cpp.
References shiftedFltGray2D_.
Referenced by setBoundRect_(), and ~RasterImage_gray_F().
 {
     //  delete the shifted float raster
     if (shiftedFltGray2D_ != NULL)
     {
         shiftedFltGray2D_ += iLow;
         delete []shiftedFltGray2D_;
         shiftedFltGray2D_ = NULL;
     }
 }
ConversionFromFloatMode RasterImage_gray_F::getFloatConversionMode (void) const
Returns the image's conversion mode from float to gray.
Returns
conversion mode for this image
See also
setFloatConversionMode
setDefaultFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 912 of file RasterImage_gray_F.cpp.
References defaultFloatConv_, floatConv_, and hasIndivFloatConvMode_.
Referenced by writeInto_().
 {
     if (hasIndivFloatConvMode_)
         return floatConv_;
     else
         return defaultFloatConv_;
 }
const unsigned char * RasterImage_gray_F::getGray (void) const virtual
Returns the 8-bit gray-level base raster as a read-only 1D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 426 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage::getRaster(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     return RasterImage_gray::getRaster();
 }
unsigned char * RasterImage_gray_F::getGray (ReadWriteStatus rw) virtual
Returns the 8-bit gray-level base raster as a read-write 1D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 436 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage::getRaster(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setGraphWorldAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     setGraphWorldAsReference_();
     setReferenceHasChanged_(true);
     return RasterImage_gray::getRaster(R_W_ACCESS);
 }
const unsigned char *const * RasterImage_gray_F::getGray2D (void) const virtual
Returns the 8-bit gray-level base raster as a read-only 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 452 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::getGray2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     return RasterImage_gray::getGray2D();
 }
unsigned char *const * RasterImage_gray_F::getGray2D (ReadWriteStatus rw) virtual
Returns the 8-bit gray-level base raster as a read-write 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 461 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::getGray2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setGraphWorldAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     setGraphWorldAsReference_();
     setReferenceHasChanged_(true);
     return RasterImage_gray::getGray2D(R_W_ACCESS);
 }
const float * RasterImage_gray_F::getGrayF (void) const
Returns the float gray-level raster for this image as a read-only 1D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
1D float raster for this image
Definition at line 503 of file RasterImage_gray_F.cpp.
References fltGray_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
Referenced by allocateShiftedRaster2D_(), and uriVL::ElevationMap::updateMesh().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     return fltGray_;
 }
float * RasterImage_gray_F::getGrayF (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 1D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D float raster for this image
Definition at line 511 of file RasterImage_gray_F.cpp.
References fltGray_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRasterF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return fltGray_;
 }
const float *const * RasterImage_gray_F::getGrayF2D (void) const
Returns the float gray-level raster for this image as a read-only 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
1D float raster for this image
Definition at line 525 of file RasterImage_gray_F.cpp.
References fltGray2D_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     return fltGray2D_;
 }
float *const * RasterImage_gray_F::getGrayF2D (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D float raster for this image
Definition at line 533 of file RasterImage_gray_F.cpp.
References fltGray2D_, uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRasterF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return fltGray2D_;
 }
const unsigned char *const * RasterImage_gray_F::getShiftedGray2D (void) const virtual
Returns the shifted 8-bit gray-level base raster as a read-only 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 476 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     setReferenceHasChanged_(false);
     return RasterImage_gray::getShiftedGray2D();
 }
unsigned char *const * RasterImage_gray_F::getShiftedGray2D (ReadWriteStatus rw) virtual
Returns the shifted 8-bit gray-level base raster as a read-write 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 488 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
 {
     if ( graphWorldIsNull_() ||
             (!graphWorldIsReference() && referenceHasChanged()) )
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the reference is marked as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     return RasterImage_gray::getShiftedGray2D(R_W_ACCESS);
 }
const float *const * RasterImage_gray_F::getShiftedGrayF2D (void) const
Returns the shifted float gray-level raster for this image as a read-only 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
Returns
1D float raster for this image
Definition at line 547 of file RasterImage_gray_F.cpp.
References fltGray2D_, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), shiftedFltGray2D_, and updateRaster_().
Referenced by uriVL::HysteresisLabeler::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::HysteresisLabeler::applyTo(), computeDepth(), uriVL::ImageHistogram::computeFloatHistogram_(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::ImageArithmetics::difference_(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::GaussianFilter::getShiftedTempGrayF2D_(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::RectifiedStereoMatcher_JJL::setStereoPair(), uriVL::ZeroCrossingDetector::showSignAsColor(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), and writeInto_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return fltGray2D_;
     else
         return shiftedFltGray2D_;
 }
float *const * RasterImage_gray_F::getShiftedGrayF2D (ReadWriteStatus rw)
Returns the shifted float gray-level raster for this image as a read-write 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into gray-level data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D float raster for this image
Definition at line 561 of file RasterImage_gray_F.cpp.
References fltGray2D_, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), shiftedFltGray2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_();
     //  A side-effect of calling the read-write version of a getRasterF function is
     //  that the float raster is set to be the reference and is marked
     //  as 'changed'
         setFloatRasterAsReference_();
     setReferenceHasChanged_(true);
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return fltGray2D_;
     else
         return shiftedFltGray2D_;
 }
const RasterImage_gray_F & RasterImage_gray_F::operator= (const RasterImage_gray_F & theImg) private
Equal operator.
Created so that gcc will stop complaining. This RasterImage_gray object will retain its own id and info.
Parameters
theImg reference to the RasterImage_gray_F object to copy
Definition at line 668 of file RasterImage_gray_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
{
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_gray_F copy operator not implemented");
         return *this;
 }
void RasterImage_gray_F::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function may be called or overridden by child classes that have their own raster
Parameters
x horizontal coordinate of upper left corner
y vertical coordinate of upper left corner
theWidth desired width of the image
theHeight desired height of the image
Reimplemented from uriVL::RasterImage_gray.
Definition at line 1126 of file RasterImage_gray_F.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked_, uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_gray::setBoundRect_(), and shiftedFltGray2D_.
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  if width and height have not changed, then the operation is just a translation.
     //  All we need to do is update the "shifted" array (no re-allocation needed)
     //  since the parent class will take care of the rectangle itself
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             //  Since the rasters have the same dimensions, there is no need
             //  to delete and reallocate the shifted rasters.  Just apply a
             //  relative shift to them
             const int   iLow  = getTop(),
                         iHigh = getBottom(),
                         jLow = getLeft(),
                         rowShift = y - iLow,
                         colShift = x - jLow;
             for (int i=iLow; i<=iHigh; i++)
                 shiftedFltGray2D_[i] += colShift;
             shiftedFltGray2D_ += rowShift;
             //  if the image has an integer raster, then we let the parent class do
             //  the rectangle resizing
                         if (!graphWorldIsNull_())
                 RasterImage_gray::setBoundRect(x, y, theWidth, theHeight);
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangles are different, then we must delete
     //  and reallocate the 0-based 2D raster.
     else
     {
         deleteShiftedRaster2D_(getTop());
         deleteRaster2D_();
         //  if the image has an integer raster, then we let the parent class do
         //  the rectangle resizing
         if (!graphWorldIsNull_())
             RasterImage_gray::setBoundRect_(x, y, theWidth, theHeight);
         allocateRaster2D_(theHeight, theWidth);
         allocateShiftedRaster2D_(theHeight, theWidth, y, x);
     }
 }
void RasterImage_gray_F::setDefaultFloatConversionMode (const ConversionFromFloatMode theMode) static
Sets the default conversion mode from float to gray for this class.
Parameters
theMode individual convcersion mode for the class
See also
getFloatConversionMode
setFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 901 of file RasterImage_gray_F.cpp.
References defaultFloatConv_.
 {
     defaultFloatConv_ = theMode;
 }
void RasterImage_gray_F::setFloatConversionMode (const ConversionFromFloatMode theMode)
Sets an individual conversion mode from float to gray for this image.
Parameters
theMode individual convcersion mode for this image
See also
getFloatConversionMode
setDefaultFloatConversionMode
hasIndivFloatConvMode_
defaultFloatConv_
floatConv_
Definition at line 906 of file RasterImage_gray_F.cpp.
References floatConv_, and hasIndivFloatConvMode_.
Referenced by uriVL::NormalFlowCalculator::applyInto_(), computeDepth(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField::computeNorm(), uriVL::VectorField::computeNormSquared(), uriVL::DepthMap::DepthMap(), uriVL::ImageArithmetics::difference_(), RasterImage_gray_F(), and uriComputerVision::BackgroundRemoverTester::test0_().
 {
     floatConv_ = theMode;
     hasIndivFloatConvMode_ = true;
 }
void RasterImage_gray_F::updateRaster_ (void) const private virtual
Updates the image's base raster (if it is not the reference).
Overrides the virtual method of the RasterImage class.
Reimplemented from uriVL::RasterImage_gray.
Definition at line 585 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage_gray::allocateGraphWorld_(), calculateFloatConversionParams_(), convertToGray_(), convScale_, defaultFloatConv_, FAIL_CONDITION, floatConv_, fltGray2D_, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), hasIndivFloatConvMode_, uriVL::kGWorldAllocationError, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kSignedFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), shiftedFltGray2D_, and valMin_.
Referenced by getGray(), getGray2D(), getGrayF(), getGrayF2D(), getShiftedGray2D(), getShiftedGrayF2D(), and uriVL::RasterImage_gray::updateRaster_().
 {
         const ImageRect* validRect = getValidRect();
     const int   iLow = validRect->getTop(),
                 iHigh = validRect->getBottom(),
                 jLow = validRect->getLeft(),
                 jHigh = validRect->getRight();
     float *const* fltGray;
     unsigned char *const* gray;
         //      Before we call functions of the parent class with side effects on the
         //      "reference" flags, we copy their values to know what actually needs
         //      to be updated
         bool isCharToFloatUpdate = graphWorldIsReference();
         //      Not the prettiest solution, but gets the job done to preserve logical constness
         RasterImage_gray_F* updateableThis = const_cast<RasterImage_gray_F*>(this);
     //  if the GWorld has not been allocated (typically
     //  the first time we render a RasterImage_gray_F object) then we must allocate
     //  it at the same dimensions (bounding rectangle) as the float raster
     if (graphWorldIsNull_())
     {
         updateableThis->allocateGraphWorld_(getHeight(), getWidth());
         FAIL_CONDITION( graphWorldIsNull_(),
                         kGWorldAllocationError,
                         "GraphWorld allocation failed in RasterImage_gray_F::updateRaster_");
         updateableThis->RasterImage_gray::allocateRaster2D_(getHeight(), getWidth());
         updateableThis->RasterImage_gray::allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     }
     //  if the bounding rectangle has its origin at (0, 0) then the shifted
     //  raster was never allocated or it is equal to the unshifted raster
     if ((getTop()==0) && (getLeft()==0))
     {
         gray = updateableThis->RasterImage_gray::getGray2D(R_W_ACCESS);
         fltGray = fltGray2D_;
     }
     //  otherwise I use the shifted raster
     else
     {
         gray = updateableThis->RasterImage_gray::getShiftedGray2D(R_W_ACCESS);
         fltGray = shiftedFltGray2D_;
     }
     //  First find out which raster is the reference to update from
     if (isCharToFloatUpdate)
     {
         for (int i=iLow; i<=iHigh; i++)
             for (int j=jLow; j<=jHigh; j++)
                 fltGray[i][j] = gray[i][j];
     }
     else
     {
         ConversionFromFloatMode convMode;
         if (hasIndivFloatConvMode_)
             convMode = floatConv_;
         else
             convMode = defaultFloatConv_;
                 if ((convMode==kSignedFloat) || (convMode==kPositiveFloat) || (convMode==kRangeFloat))
                         calculateFloatConversionParams_( );
         long nbCols = jHigh - jLow + 1;
         for (int i=iLow; i<=iHigh; i++)
             updateableThis->convertToGray_(fltGray[i]+jLow, gray[i]+jLow, nbCols, valMin_, convScale_, convMode);
     }
         if (isCharToFloatUpdate)
                 setGraphWorldAsReference_();
         else
                 setFloatRasterAsReference_();
 }
void RasterImage_gray_F::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const private virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Reimplemented from uriVL::RasterImage_gray.
Definition at line 706 of file RasterImage_gray_F.cpp.
References uriVL::RasterImage::allocateRaster2D_(), uriVL::RasterImage::allocateShiftedRaster2D_(), calculateFloatConversionParams_(), convertToGray_(), convScale_, defaultFloatConv_, FAIL_CONDITION, floatConv_, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), getFloatConversionMode(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), getShiftedGrayF2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::hasFloatRaster(), hasIndivFloatConvMode_, uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kDense, uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kPositiveFloat, uriVL::kRangeFloat, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kSignedFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged(), uriVL::DrawableObject2D::setDrawableInformationType(), uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), uriVL::RasterImage::setOtherRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), valMin_, and uriVL::RasterImage_gray::writeInto_().
Referenced by copyInto().
 {
     //  If the float raster is not the reference then we really should not be here.
     if (graphWorldIsReference() && referenceHasChanged()) {
         RasterImage_gray::writeInto_(imgOut, copyRect, origin);
         }
     //  Converting from the float raster
     else
     {
                 //  The GWorld only works with unshifted rasters so we need to compute
                 //  the "true" copy rectangles first
                 ImageRect*  sourceRect = new ImageRect(copyRect->getLeft() - getLeft(),
                                                                                            copyRect->getTop() - getTop(),
                                                                                            copyRect->getWidth(), copyRect->getHeight());
                 ImageRect*  destRect =  origin == NULL ?
                                                                 new ImageRect(copyRect->getLeft() - imgOut->getLeft(),
                                                                                           copyRect->getTop() - imgOut->getTop(),
                                                                                           copyRect->getWidth(), copyRect->getHeight())
                                                                 :
                                                                 new ImageRect(origin->getX() - imgOut->getLeft(),
                                                                                           origin->getY() - imgOut->getTop(),
                                                                                           copyRect->getWidth(), copyRect->getHeight());
         const float* const* graySource = getShiftedGrayF2D();
         const int   iLowSource = sourceRect->getTop(),
                     iLowDest = destRect->getTop(),
                     iHighSource = sourceRect->getBottom(),
                     jLowSource = sourceRect->getLeft(),
                     jLowDest = destRect->getLeft();
                 const int       nbRows = sourceRect->getHeight(),
                                         nbCols = sourceRect->getWidth();
         //  For the time being, we only handle regular dense rasters
         imgOut->setDrawableInformationType(kDense);
         switch( imgOut->getBaseRasterType() )
         {
             case kBinaryRaster:
                 imgOut->setOtherRasterAsReference_();
                 imgOut->setReferenceHasChanged_(true);
                 FAIL_CONDITION( true,
                                 kFunctionNotImplemented,
                                 "gray_F to binary copies not handled yet by RasterImage_gray_F::writeInto_");
                 break;
             case kGrayRaster:
                 //  if we are dealing with a plain gray raster image
                 if (!imgOut->hasFloatRaster())
                 {
                     unsigned char*const* grayDest = ((RasterImage_gray* )imgOut)->getShiftedGray2D(R_W_ACCESS);
                     ConversionFromFloatMode floatConvMode =  hasIndivFloatConvMode_ ? floatConv_ : defaultFloatConv_;
                                         if ((floatConvMode==kSignedFloat) || (floatConvMode==kPositiveFloat) ||
                                                 (floatConvMode==kRangeFloat))
                                                 calculateFloatConversionParams_( );
                     for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
                         convertToGray_(graySource[i]+jLowSource, grayDest[iDest]+jLowDest,
                                        nbCols, valMin_, convScale_, floatConvMode);
                     imgOut->setGraphWorldAsReference_();
                     imgOut->setReferenceHasChanged_(true);
                 }
                 //
                 //  if imgOut has a float raster, we had better use it
                 else
                 {
                     float* const* fGrayDest = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
                                         //      This call may have been made from within the RasterImage_gray_F constructor of imgOut,
                                         //      in which case grayDest has not been allocated yet
                                         if (fGrayDest == NULL)
{
                                                 imgOut->allocateRaster2D_(nbRows, nbCols);
                                                 imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                                 fGrayDest = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
                                         }
                     int     byteShiftSource = static_cast<int>(sizeof(float)*jLowSource),
                             byteShiftDest = static_cast<int>(sizeof(float)*jLowDest);
                     long    bytesPerRow = static_cast<long>(sizeof(float)*nbCols);
                     for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
                         memcpy(fGrayDest[iDest] + byteShiftDest,
                                graySource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                     imgOut->setGraphWorldAsReference_();
                     imgOut->setReferenceHasChanged_(true);
                     //  assign to imgOut the same float->gray conversion as this image
                     ((RasterImage_gray_F *)imgOut)->setFloatConversionMode(
                         this->getFloatConversionMode());
                     imgOut->setFloatRasterAsReference_();
                     imgOut->setReferenceHasChanged_(true);
                 }
                 break;
             case kRGB24Raster:
                 //  if we are dealing with a plain RGB raster image, just copy the bytes
                 FAIL_CONDITION( true,
                                 kFunctionNotImplemented,
                                 "Gray_F to RGB copies not handled yet");
                 imgOut->setOtherRasterAsReference_();
                 imgOut->setReferenceHasChanged_(true);
                 break;
                         case kaRGB16Raster:
                                         //  if we are dealing with a plain aRGB16 raster image, just copy the bytes
                                         FAIL_CONDITION( true,
                                                                         kFunctionNotImplemented,
                                                                         "Gray_F to aRGB16 copies not handled yet");
                                         imgOut->setGraphWorldAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 break;
                         case kRGBa32Raster:
                                 //  if we are dealing with a plain gray raster image, just copy the bytes
                                 if (!imgOut->hasFloatRaster())
{
                                         /*
                                         unsigned char** rgbaDest = ((RasterImage_RGBa* )imgOut)->getRGBa2D();
                                         for (int i2=0; i2<nbRows; i2++)
                                                 convertToRGBa_(graySource[i2], rgbaDest[i2], nbCols);
                                         */
                                         FAIL_CONDITION( true,
                                                                         kFunctionNotImplemented,
                                                                         "Gray_F to RGBa copies not handled yet");
                                         imgOut->setGraphWorldAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                 }
                                 //
                                 //  if imgOut has a float raster, we had better use it
                                 else
{
                                         float*const* fRedOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                                         float*const* fGreenOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                                         float*const* fBlueOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                         //      This call may have been made from within the RasterImage_gray_F constructor of imgOut,
                                         //      in which case grayDest has not been allocated yet
                                         if ((fRedOut == NULL) || (fGreenOut == NULL)  || (fBlueOut == NULL))
{
                                                 imgOut->allocateRaster2D_(nbRows, nbCols);
                                                 imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                                 fRedOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                                                 fGreenOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                                                 fBlueOut = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                         }
                     int     byteShiftSource = static_cast<int>(sizeof(float)*jLowSource),
                             byteShiftDest = static_cast<int>(sizeof(float)*jLowDest);
                     long    bytesPerRow = static_cast<long>(sizeof(float)*nbCols);
                     for (int i=iLowSource, iDest = iLowDest; i<=iHighSource; i++, iDest++)
{
                         memcpy(fRedOut[iDest] + byteShiftDest,
                                graySource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                         memcpy(fGreenOut[iDest] + byteShiftDest,
                                graySource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                         memcpy(fBlueOut[iDest] + byteShiftDest,
                                graySource[i] + byteShiftSource, static_cast<unsigned long>(bytesPerRow));
                                         }
                                         imgOut->setFloatRasterAsReference_();
                                         imgOut->setReferenceHasChanged_(true);
                                                 //  assign to imgOut the same float conversion as this image
                                                 ((RasterImage_RGBa_F *)imgOut)->setFloatConversionMode(this->getFloatConversionMode());
                                 }
                                 break;
             default:
                 FAIL_CONDITION( true,
                                 kRasterImageError,
                                 "Invalid image type in RasterImage_gray::copyInto");
                 break;
         }
         if (sourceRect != NULL)
             delete sourceRect;
         if (destRect != NULL)
             delete destRect;
     }
 }
Friends And Related Function Documentation
friend class RasterImage_gray friend
Definition at line 649 of file RasterImage_gray_F.h.
Member Data Documentation
float uriVL::RasterImage_gray_F::convScale_ mutable private
Scale factor to apply in a float to gray conversion.
Definition at line 489 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_(), updateRaster_(), and writeInto_().
ConversionFromFloatMode RasterImage_gray_F::defaultFloatConv_ = kSignedFloat static private
Code for the default algorithm for conversion from float to gray.
An image instance can override this default mode by setting its floatConv_ field to an other value.
See also
hasIndivFloatConvMode_
Definition at line 476 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setDefaultFloatConversionMode(), updateRaster_(), and writeInto_().
ConversionFromFloatMode uriVL::RasterImage_gray_F::floatConv_ private
Code for the algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
Only relevant if hasIndivFloatConvMode_ is true.
See also
hasIndivFloatConvMode_
Definition at line 467 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setFloatConversionMode(), updateRaster_(), and writeInto_().
float** uriVL::RasterImage_gray_F::fltGray2D_ mutable private
The 0-based 2D float gray-level raster mapped over fltGray_.
Definition at line 442 of file RasterImage_gray_F.h.
Referenced by allocateRaster2D_(), calculateFloatConversionParams_(), deleteRaster2D_(), getGrayF2D(), getShiftedGrayF2D(), RasterImage_gray_F(), and updateRaster_().
float* uriVL::RasterImage_gray_F::fltGray_ mutable private
The float gray-level raster of this image.
Definition at line 437 of file RasterImage_gray_F.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), and getGrayF().
bool uriVL::RasterImage_gray_F::hasIndivFloatConvMode_ private
True if an algorithm for conversion from float to gray other than the default class-wide algorithm identified in RasterImage::defaultFloatConv_.
See also
floatConv_
Definition at line 456 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_(), getFloatConversionMode(), setFloatConversionMode(), updateRaster_(), and writeInto_().
float** uriVL::RasterImage_gray_F::shiftedFltGray2D_ mutable private
The shifted 2D float gray-level raster mapped over fltGray_.
Definition at line 447 of file RasterImage_gray_F.h.
Referenced by allocateShiftedRaster2D_(), calculateFloatConversionParams_(), deleteShiftedRaster2D_(), getShiftedGrayF2D(), RasterImage_gray_F(), setBoundRect_(), and updateRaster_().
float uriVL::RasterImage_gray_F::valMax_ mutable private
Minimum value over the raster.
Definition at line 485 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_().
float uriVL::RasterImage_gray_F::valMin_ mutable private
Minimum value over the raster.
Definition at line 481 of file RasterImage_gray_F.h.
Referenced by calculateFloatConversionParams_(), updateRaster_(), and writeInto_().
The documentation for this class was generated from the following files:
RasterImage_gray_F.h
RasterImage_gray_F.cpp