URIVisionLibrary: uriVL::NonlinearOptimizer1D_gss Class Reference
uriVL::NonlinearOptimizer1D_gss Class Reference
1-dimensional optimizerimplementing the golden section search.
#include <NonlinearOptimizer1D_gss.h>
Public Member Functions
NonlinearOptimizer1D_gss (void)
Creates a new 1D GSS optimizer.
NonlinearOptimizer1D_gss (const Function1D *f)
Creates a new 1D optimizer for a specific function.
NonlinearOptimizer1D_gss (const Function1D_F *f)
Creates a new 1D optimizer for a specific function.
~NonlinearOptimizer1D_gss (void)
Destructor.
Public Member Functions inherited from uriVL::NonlinearOptimizer1D
NonlinearOptimizer1D (void)
Creates a new 1D optimizer.
NonlinearOptimizer1D (const Function1D *f)
Creates a new 1D optimizer for a specific function.
NonlinearOptimizer1D (const Function1D_F *f)
Creates a new 1D optimizer for a specific function.
virtual ~NonlinearOptimizer1D (void)
Destructor.
void setFunction (const Function1D *f)
Assigns a new double 1D function to this optimizer.
void setFunction (const Function1D_F *f)
Assigns a new float 1D function to this optimizer.
bool isOptimizationFunction (const Function1D *f)
Checks if the function passed as parameter is the one set for this optimization problem.
bool isOptimizationFunction (const Function1D_F *f)
Checks if the function passed as parameter is the one set for this optimization problem.
const OptimizerRecord1D * minimize (const Function1D *f, double startX, double xMin, double xMax, double tol)
Finds and returns a (local) minimum for a double function over a specific range.
const OptimizerRecord1D * minimize (const Function1D_F *f, float startX, float xMin, float xMax, float tol)
Finds and returns a (local) minimum for a float function over a specific range.
void minimize (const Function1D *f, double startX, double xMin, double xMax, double tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a double function over a specific range.
void minimize (const Function1D_F *f, float startX, float xMin, float xMax, float tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a float function over a specific range.
Private Member Functions
void minimize_ (const Function1D_F *f, const float startX, const float xMin, const float xMax, const float tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize_ (const Function1D *f, const double startX, const double xMin, const double xMax, const double tol, OptimizerRecord1D *optRec)
Finds a (local) minimum for a function over a specific range.
Static Private Member Functions
static bool initSearchBracket_ (const Function1D_F *f, float xStart, float xMin, float xMax, float *a, float *b, float *x1, float *x2, float *fA, float *fB, float *fX1, float *fX2, int *nbIters)
Finds a GS search bracket about the starting point.
static bool initSearchBracket_ (const Function1D *f, double xStart, double xMin, double xMax, double *a, double *b, double *x1, double *x2, double *fA, double *fB, double *fX1, double *fX2, int *nbIters)
Finds a GS search bracket about the starting point.
Detailed Description
1-dimensional optimizerimplementing the golden section search.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 32 of file NonlinearOptimizer1D_gss.h.
Constructor & Destructor Documentation
NonlinearOptimizer1D_gss::NonlinearOptimizer1D_gss (void)
Creates a new 1D GSS optimizer.
Definition at line 47 of file NonlinearOptimizer1D_gss.cpp.
                         :   NonlinearOptimizer1D()
 {
 }
NonlinearOptimizer1D_gss::NonlinearOptimizer1D_gss (const Function1D * f)
Creates a new 1D optimizer for a specific function.
This is the version of the constructor to invoke if the same function will be used over and over for optimization.
Parameters
f the function to optimize
Definition at line 53 of file NonlinearOptimizer1D_gss.cpp.
                         :   NonlinearOptimizer1D(f)
 {
 }
 catch(ErrorReport& e)
 {
         e.appendToMessage("called by NonlinearOptimizer1D_gss constructor");
         throw e;
 }
NonlinearOptimizer1D_gss::NonlinearOptimizer1D_gss (const Function1D_F * f)
Creates a new 1D optimizer for a specific function.
This is the version of the constructor to invoke if the same function will be used over and over for optimization.
Parameters
f the function to optimize
Definition at line 64 of file NonlinearOptimizer1D_gss.cpp.
                         :   NonlinearOptimizer1D(f)
 {
 }
 catch(ErrorReport& e)
 {
         e.appendToMessage("called by NonlinearOptimizer1D_gss constructor");
         throw e;
 }
NonlinearOptimizer1D_gss::~NonlinearOptimizer1D_gss (void)
Destructor.
Definition at line 75 of file NonlinearOptimizer1D_gss.cpp.
 {
 }
Member Function Documentation
bool NonlinearOptimizer1D_gss::initSearchBracket_ (const Function1D_F * f, float xStart, float xMin, float xMax, float * a, float * b, float * x1, float * x2, float * fA, float * fB, float * fX1, float * fX2, int * nbIters) static private
Finds a GS search bracket about the starting point.
Parameters
f the function to optimize
xStart starting point for the search
xMin lower bound of the search interval
xMax upper bound of the search interval
a left endpoint of the search bracket found
b right endpoint of the search bracket found
x1 left internal point of the search bracket found
x2 right internal point of the search bracket found
fA value of the function at a
fB value of the function at b
fX1 value of the function at x1
fX2 value of the function at x2
nbIters number of iterations steps required to find the bracket
Returns
true if a search bracket was found
Definition at line 317 of file NonlinearOptimizer1D_gss.cpp.
References uriVL::Function1D_F::func(), HUGE_VALF, INV_TAU_F, MAX_NB_ITERS, SMALL_STEP_FRAC_F, STEP_GAIN_F, TAU1_F, and TAU_F.
Referenced by minimize_().
 {
     float       a, b, c, lastC,
                         fA, fB, fC, lastFC;
     a = xStart;
     fA = f->func(xStart);
     //  I make a small step (arbitrarily, 1/10th to 1/100th of the search interval) on the
     //  right side of a to see which way the function is going down.
     if ((xMin != -HUGE_VALF) && (xMax != HUGE_VALF))
         c = xStart + (xMax - xStart)*SMALL_STEP_FRAC_F;
     else if (xStart == 0)
         c = xStart + SMALL_STEP_FRAC_F;
     else if (xStart > 0)
         c = xStart * (1.0f + SMALL_STEP_FRAC_F);
     else
         c = xStart * (1.0f - SMALL_STEP_FRAC_F);
     fC = f->func(c);
     //  if the function is going down on the right side -> positive steps
     //  if the function is going down on the left side -> negative steps
     const bool  LEFT_TO_RIGHT = (fC < fA);
     if (!LEFT_TO_RIGHT)
     {
         //  swap a and c
         b = a; fB = fA;
         a = c; fA = fC;
         c = b; fC = fB;
     }
     float tempSmallStep, tempBoundC;
     if ((xMin != -HUGE_VALF) && (xMax != HUGE_VALF))
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = (xMax - xStart)*SMALL_STEP_FRAC_F;
             tempBoundC = a + TAU_F*(xMax - a);
         }
         else
         {
             tempSmallStep = (xMin - xStart)*SMALL_STEP_FRAC_F;
             tempBoundC = a + TAU_F * (xMin - a);
         }
     }
     else if (xStart != 0)
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = fabsf(SMALL_STEP_FRAC_F * xStart);
             tempBoundC = HUGE_VALF;
         }
         else
         {
             tempSmallStep = -fabsf(SMALL_STEP_FRAC_F * xStart);
             tempBoundC = -HUGE_VALF;
         }
     }
     else
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = SMALL_STEP_FRAC_F;
             tempBoundC = HUGE_VALF;
         }
         else
         {
             tempSmallStep = -SMALL_STEP_FRAC_F;
             tempBoundC = -HUGE_VALF;
         }
     }
     const float smallStep = tempSmallStep;
     const float boundC = tempBoundC;
     float step = smallStep;
     *nbIters = 0;
     b = a + INV_TAU_F *(c-a);
     fB = f->func(b);
     while ((fC > fB) && ((*nbIters)<=MAX_NB_ITERS))
     {
         lastC = c;
         lastFC = fC;
         c = c + step;
         (*nbIters)++;
         //  if c is beyond the bound, we have not found a bracket.  It is possible/likely
         //  that the function is strictly decreasing over the search interval.  So we
         //  compute one more value at the end of the search interval
         if (LEFT_TO_RIGHT && (c>boundC))
         {
                 *theA = a; *theFA = fA;
                 *theX1 = c; *theFX1 = fC;
                 *theX2 = b; *theFX2 = fB;
                 *theB = xMax - SMALL_STEP_FRAC_F * (xMax-xMin); *theFB = f->func(*theB);
             return false;
         }
         else if (!LEFT_TO_RIGHT && (c<boundC))
         {
                 *theA = a; *theFA = fA;
                 *theX1 = c; *theFX1 = fC;
                 *theX2 = b; *theFX2 = fB;
                 *theB = xMin + SMALL_STEP_FRAC_F * (xMax-xMin); *theFB = f->func(*theB);
             return false;
         }
         fC = f->func(c);
         //  if f(c) is still ower than f(a) then we compute the corresponding b
         //  for the next round of evaluation
         if (fC < fA)
         {
             b = a + INV_TAU_F *(c-a);
             fB = f->func(b);
             step *= STEP_GAIN_F;
         }
         //  if fC > fA, we went too far, but it's good because  now we know that
         //  there is a bracket [a, lastC, c].  We do a sort of GSS until we have our
         //  bracket.  This is not wasted time since this is going to reduce the
         //  time of the actual minimum search by giving us a smaller bracket.
         else
         {
             //  we compute the golden section points for the segment a-c
             float x1, x2,
                    fX1 = HUGE_VALF,
                    fX2 = HUGE_VALF;
             //  if either one of these two points is below f(a), then we have our bracket
             //  otherwise, we need to repeat the operation
             while (((*nbIters)<=MAX_NB_ITERS) && (fX1 > fA) && (fX2 > fA))
             {
                 x1 = a + TAU1_F*(c-a);
                 x2 = a + TAU_F*(c-a);
                 fX1 = f->func(x1);
                 fX2 = f->func(x2);
                 (*nbIters)++;
                 //  if lastC is between a and x1, repeat the operation between
                 //  a and x1
                 if (lastC < x1)
                 {
                     c = x1;
                     fC = fX1;
                 }
                 //  if lastC is between x1 and x2
                 else if (lastC < x2)
                 {
                     a = x1;
                     fA = fX1;
                     c = x2;
                     fC = fX2;
                 }
                 else
                 {
                     a = x2;
                     fA = fX2;
                 }
             }
             if ((*nbIters) > MAX_NB_ITERS)
                 return false;
             else
             {
                 *theA = a;
                 *theFA = fA;
                 *theX1 = x1;
                 *theFX1 = fX1;
                 *theX2 = x2;
                 *theFX2 = fX2;
                 *theB = c;
                 *theFB = fC;
                 return true;
             }
         }
     }
     *theA = a;
     *theFA = fA;
     *theX1 = a + TAU1_F*(b-a);
     *theFX1 = f->func(*theX1);
     *theX2 = c;
     *theFX2 = fC;
     *theB = b;
     *theFB = fB;
     return (*nbIters) <= MAX_NB_ITERS;
 }
bool NonlinearOptimizer1D_gss::initSearchBracket_ (const Function1D * f, double xStart, double xMin, double xMax, double * a, double * b, double * x1, double * x2, double * fA, double * fB, double * fX1, double * fX2, int * nbIters) static private
Finds a GS search bracket about the starting point.
Parameters
f the function to optimize
xStart starting point for the search
xMin lower bound of the search interval
xMax upper bound of the search interval
a left endpoint of the search bracket found
b right endpoint of the search bracket found
x1 left internal point of the search bracket found
x2 right internal point of the search bracket found
fA value of the function at a
fB value of the function at b
fX1 value of the function at x1
fX2 value of the function at x2
nbIters number of iterations steps required to find the bracket
Returns
true if a search bracket was found
Definition at line 515 of file NonlinearOptimizer1D_gss.cpp.
References uriVL::Function1D::func(), HUGE_VALF, INV_TAU, MAX_NB_ITERS, SMALL_STEP_FRAC, STEP_GAIN, TAU, and TAU1.
 {
     double   a, b, c, lastC,
              fA, fB, fC, lastFC;
     a = xStart;
     fA = f->func(xStart);
     //  I make a small step (arbitrarily, 1/100th of the search interval) on the right side
     //  of a to see which way the function is going down.
     if ((xMin != -HUGE_VALF) && (xMax != HUGE_VALF))
         c = xStart + (xMax - xMin)*SMALL_STEP_FRAC;
     else if (xStart == 0)
         c = xStart + SMALL_STEP_FRAC;
     else if (xStart > 0)
         c = xStart * (1.0f + SMALL_STEP_FRAC);
     else
         c = xStart * (1.0f - SMALL_STEP_FRAC);
     fC = f->func(c);
     //  if the function is going down on the right side -> positive steps
     //  if the function is going down on the left side -> negative steps
     const bool  LEFT_TO_RIGHT = (fC < fA);
     if (!LEFT_TO_RIGHT)
     {
         //  swap a and c
         b = a; fB = fA;
         a = c; fA = fC;
         c = b; fC = fB;
     }
     double   tempSmallStep, tempBoundC;
     if ((xMin != -HUGE_VALF) && (xMax != HUGE_VALF))
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = (xMax - xMin)*SMALL_STEP_FRAC;
             tempBoundC = a + TAU*(xMax - a);
         }
         else
         {
             tempSmallStep = (xMin - xMax)*SMALL_STEP_FRAC;
             tempBoundC = a + TAU * (xMin - a);
         }
     }
     else if (xStart != 0)
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = fabs(SMALL_STEP_FRAC * xStart);
             tempBoundC = HUGE_VALF;
         }
         else
         {
             tempSmallStep = -fabs(SMALL_STEP_FRAC * xStart);
             tempBoundC = -HUGE_VALF;
         }
     }
     else
     {
         if (LEFT_TO_RIGHT)
         {
             tempSmallStep = SMALL_STEP_FRAC;
             tempBoundC = HUGE_VALF;
         }
         else
         {
             tempSmallStep = -SMALL_STEP_FRAC;
             tempBoundC = -HUGE_VALF;
         }
     }
     const double smallStep = tempSmallStep;
     const double boundC = tempBoundC;
     double  step = smallStep;
     *nbIters = 0;
     b = a + INV_TAU *(c-a);
     fB = f->func(b);
     while ((fC > fB) && ((*nbIters)<=MAX_NB_ITERS))
     {
         lastC = c;
         lastFC = fC;
         c = c + step;
         (*nbIters)++;
         //  if c is beyond the bound, we have not found a bracket.  It is possible/likely
         //  that the function is strictly decreasing over the search interval.  So we
         //  compute one more value at the end of the search interval
         if (LEFT_TO_RIGHT && (c>boundC))
         {
                 *theA = a; *theFA = fA;
                 *theX1 = c; *theFX1 = fC;
                 *theX2 = b; *theFX2 = fB;
                 *theB = xMax - SMALL_STEP_FRAC * (xMax-xMin); *theFB = f->func(*theB);
             return false;
         }
         else if (LEFT_TO_RIGHT && (c>boundC))
         {
                 *theA = a; *theFA = fA;
                 *theX1 = c; *theFX1 = fC;
                 *theX2 = b; *theFX2 = fB;
                 *theB = xMin + SMALL_STEP_FRAC * (xMax-xMin); *theFB = f->func(*theB);
             return false;
         }
         fC = f->func(c);
         //  if f(c) is still ower than f(a) then we compute the corresponding b
         //  for the next round of evaluation
         if (fC < fA)
         {
             b = a + INV_TAU *(c-a);
             fB = f->func(b);
             step *= STEP_GAIN;
         }
         //  if fC > fA, we went too far, but it's good because  now we know that
         //  there is a bracket [a, lastC, c].  We do a sort of GSS until we have our
         //  bracket.  This is not wasted time since this is going to reduce the
         //  time of the actual minimum search by giving us a smaller bracket.
         else
         {
             //  we compute the golden section points for the segment a-c
             double  x1, x2,
                     fX1 = HUGE_VALF,
                     fX2 = HUGE_VALF;
             //  if either one of these two points is below f(a), then we have our bracket
             //  otherwise, we need to repeat the operation
             while (((*nbIters)<=MAX_NB_ITERS) && (fX1 > fA) && (fX2 > fA))
             {
                 x1 = a + TAU1*(c-a);
                 x2 = a + TAU*(c-a);
                 fX1 = f->func(x1);
                 fX2 = f->func(x2);
                 (*nbIters)++;
                 //  if lastC is between a and x1, repeat the operation between
                 //  a and x1
                 if (lastC < x1)
                 {
                     c = x1;
                     fC = fX1;
                 }
                 //  if lastC is between x1 and x2
                 else if (lastC < x2)
                 {
                     a = x1;
                     fA = fX1;
                     c = x2;
                     fC = fX2;
                 }
                 else
                 {
                     a = x2;
                     fA = fX2;
                 }
             }
             if ((*nbIters) > MAX_NB_ITERS)
                 return false;
             else
             {
                 *theA = a;
                 *theFA = fA;
                 *theX1 = x1;
                 *theFX1 = fX1;
                 *theX2 = x2;
                 *theFX2 = fX2;
                 *theB = c;
                 *theFB = fC;
                 return true;
             }
         }
     }
     if ((*nbIters) > MAX_NB_ITERS)
         return false;
     else
     {
         *theA = a;
         *theFA = fA;
         *theX1 = a + TAU1*(b-a);
         *theFX1 = f->func(*theX1);
         *theX2 = c;
         *theFX2 = fC;
         *theB = b;
         *theFB = fB;
         return true;
     }
 }
void NonlinearOptimizer1D_gss::minimize_ (const Function1D_F * f, const float startX, const float xMin, const float xMax, const float tol, OptimizerRecord1D * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Implements uriVL::NonlinearOptimizer1D.
Definition at line 87 of file NonlinearOptimizer1D_gss.cpp.
References uriVL::Function1D_F::func(), uriVL::Function1D_F::getLowerBound(), uriVL::Function1D_F::getUpperBound(), initSearchBracket_(), uriVL::OptimizerRecord1D::isSuccess, MAX_NB_ITERS, uriVL::OptimizerRecord1D::nbIters, uriVL::OptimizerRecord1D::optVal, uriVL::OptimizerRecord1D::optX, TAU1_F, and TAU_F.
 {
     //  work on the intersection of the domain of definition and of the search interval
     //  specified by the user
     float  funcXMin = f->getLowerBound(),
            funcXMax = f->getUpperBound();
     if (xMin > funcXMin)
        funcXMin = xMin;
     if (xMax < funcXMax)
         funcXMax = xMax;
     //  determine an initial search bracket
     float   a, b, x1, x2,
             fA, fB, fX1, fX2,
             tolX;
     int     nbIters = 0;
 /*
 const int NB_TEST_PTS = 100;
 float   testX[NB_TEST_PTS], testFunc[NB_TEST_PTS];
 if ((xMin != -HUGE_VALF) && (xMax !=HUGE_VALF))
 {
     cout << "{";
     for (int k=0; k<NB_TEST_PTS; k++)
     {
         testX[k] = xMin + k*(xMax-xMin) / 99.f;
         testFunc[k] = f->func(testX[k]);
         cout << "{" << testX[k] << "," << testFunc[k] << "}";
         if (k <NB_TEST_PTS-1)
             cout << ",";
     }
     cout << "}" << endl;
 }
 */
     bool foundBracket = initSearchBracket_(f, xStart, funcXMin, funcXMax, &a, &b, &x1, &x2,
                                             &fA, &fB, &fX1, &fX2, &nbIters);
     if (foundBracket)
     {
         tolX = 0.5f*tol*(fabs(x1) + fabs(x2));
         //  if the search bracket we get has a > b (this will happens if the function's slope is
         //  positive at the starting point we got), then we must invert the interval
         if (a > b)
         {
             float  t = a,
                    fT = fA;
             a = b;
             fA = fB;
             b = t;
             fB = fT;
             t = x1;
             fT = fX1;
             x1 = x2;
             fX1 = fX2;
             x2 = t;
             fX2 = fT;
         }
         while ((fabs(b-a) > tolX) && (nbIters<=MAX_NB_ITERS))
         {
             if (fX1 > fX2)
             {
                 a = x1;
                 fA = fX1;
                 x1 = x2;
                 fX1 = fX2;
                 x2 = a + TAU_F*(b-a);
                 fX2 = f->func(x2);
             }
             else
             {
                 b = x2;
                 fB = fX2;
                 x2 = x1;
                 fX2 = fX1;
                 x1 = a + TAU1_F*(b-a);
                 fX1 = f->func(x1);
             }
             tolX = 0.5f*tol*(fabsf(x1) + fabsf(x2));
             nbIters++;
         }
         if (fX1 > fX2)
         {
             optRec->optX = x2;
             optRec->optVal = fX2;
         }
         else
         {
             optRec->optX = x1;
             optRec->optVal = fX1;
         }
         optRec->isSuccess = (nbIters<=MAX_NB_ITERS);
         optRec->nbIters = nbIters;
     }
     //  if we did not find a bracket, then we must report our abject failure
     else
     {
         //  still return the "best" among a, b, x1, x2
         double  x, fX;
         if (fA < fB) {
             x = a; fX = fA;
         }
         else {
             x = b; fX = fB;
         }
         if (fX1 < fX) {
             x = x1; fX = fX1;
         }
         if (fX2 < fX) {
             x = x2; fX = fX2;
         }
         optRec->optX = x;
         optRec->optVal = fX;
         optRec->isSuccess = false;
         optRec->nbIters = nbIters;
     }
 }
void NonlinearOptimizer1D_gss::minimize_ (const Function1D * f, const double startX, const double xMin, const double xMax, const double tol, OptimizerRecord1D * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin lower bound of the search interval
xMax upper bound of the search interval
tol tolerance of the search
optRec result of the optimization
Implements uriVL::NonlinearOptimizer1D.
Definition at line 210 of file NonlinearOptimizer1D_gss.cpp.
References uriVL::Function1D::func(), uriVL::Function1D::getLowerBound(), uriVL::Function1D::getUpperBound(), initSearchBracket_(), uriVL::OptimizerRecord1D::isSuccess, MAX_NB_ITERS, uriVL::OptimizerRecord1D::nbIters, uriVL::OptimizerRecord1D::optVal, uriVL::OptimizerRecord1D::optX, TAU, and TAU1.
 {
     //  work on the intersection of the domain of definition and of the search interval
     //  specified by the user
     double funcXMin = f->getLowerBound(),
            funcXMax = f->getUpperBound();
     if (xMin > funcXMin)
        funcXMin = xMin;
     if (xMax < funcXMax)
         funcXMax = xMax;
     //  determine an initial search bracket
     double  a, b, x1, x2,
             fA, fB, fX1, fX2,
             tolX;
     int     nbIters = 0;
     bool foundBracket = initSearchBracket_(f, xStart, funcXMin, funcXMax, &a, &b, &x1, &x2, &fA,
                                             &fB, &fX1, &fX2, &nbIters);
     if (foundBracket)
     {
         tolX = 0.5f*tol*(fabs(x1) + fabs(x2));
         //  if the search bracket we get has a > b (this will happens if the function's slope is
         //  positive at the starting point we got), then we must invert the interval
         if (a > b)
         {
             double  t = a,
                     fT = fA;
             a = b;
             fA = fB;
             b = t;
             fB = fT;
             t = x1;
             fT = fX1;
             x1 = x2;
             fX1 = fX2;
             x2 = t;
             fX2 = fT;
         }
         while ((fabs(b-a) > tolX) && (nbIters<=MAX_NB_ITERS))
         {
             if (fX1 > fX2)
             {
                 a = x1;
                 fA = fX1;
                 x1 = x2;
                 fX1 = fX2;
                 x2 = a + TAU*(b-a);
                 fX2 = f->func(x2);
             }
             else
             {
                 b = x2;
                 fB = fX2;
                 x2 = x1;
                 fX2 = fX1;
                 x1 = a + TAU1*(b-a);
                 fX1 = f->func(x1);
             }
             tolX = 0.5*tol*(fabs(x1) + fabs(x2));
             nbIters++;
         }
         if (fX1 > fX2)
         {
             optRec->optX = x2;
             optRec->optVal = fX2;
         }
         else
         {
             optRec->optX = x1;
             optRec->optVal = fX1;
         }
         optRec->isSuccess = (nbIters<=MAX_NB_ITERS);
         optRec->nbIters = nbIters;
     }
     //  if we did not find a bracket, then we must report our abject failure
     else
     {
         //  still return the "best" among a, b, x1, x2
         double  x, fX;
         if (fA < fB) {
             x = a; fX = fA;
         }
         else {
             x = b; fX = fB;
         }
         if (fX1 < fX) {
             x = x1; fX = fX1;
         }
         if (fX2 < fX) {
             x = x2; fX = fX2;
         }
         optRec->optX = x;
         optRec->optVal = fX;
         optRec->isSuccess = false;
         optRec->nbIters = nbIters;
     }
 }
The documentation for this class was generated from the following files:
NonlinearOptimizer1D_gss.h
NonlinearOptimizer1D_gss.cpp