URIVisionLibrary: uriVL::NonlinearOptimizerND Class Reference
uriVL::NonlinearOptimizerND Class Reference abstract
Pure virtual parent class for all n-dimensional optimizers.
#include <NonlinearOptimizerND.h>
Public Member Functions
NonlinearOptimizerND (void)
Creates a new nD optimizer.
NonlinearOptimizerND (int n)
Creates a new n-dimensional nD optimizer.
NonlinearOptimizerND (const FunctionND *f)
Creates a new n-dimensional nD optimizer for a specific function.
NonlinearOptimizerND (const FunctionND_F *f)
Creates a new n-dimensional nD optimizer for a specific function.
virtual ~NonlinearOptimizerND (void)
Destructor.
void setFunction (const FunctionND *f)
Assigns a new nD function to this optimizer.
void setFunction (const FunctionND_F *f)
Assigns a new nD function to this optimizer.
bool isOptimizationFunction (const FunctionND *f)
Checks if the function passed as parameter is the one set for this optimization problem.
bool isOptimizationFunction (const FunctionND_F *f)
Checks if the function passed as parameter is the one set for this optimization problem.
int getDimension (void) const
Gives the dimension of this optimizer (if one has been set)
const OptimizerRecordND * minimize (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
void minimize (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
Private Member Functions
NonlinearOptimizerND (const NonlinearOptimizerND &obj)
Disabled copy constructor.
const NonlinearOptimizerND & operator= (const NonlinearOptimizerND &obj)
Disabled copy operator.
virtual void setFunction_ (const FunctionND *f)
Called by this class's public function prior to changing the value of the instance variable.
virtual void setFunction_ (const FunctionND_F *f)
Called by this class's public function prior to changing the value of the instance variable.
virtual void minimize_ (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol, OptimizerRecordND *optRec)=0
Finds a (local) minimum for a double function over a specific range.
virtual void minimize_ (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol, OptimizerRecordND *optRec)=0
Finds a (local) minimum for a float function over a specific range.
virtual void minimize_ (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol, OptimizerRecordND *optRec)=0
Finds a (local) minimum for a double function over a specific range.
virtual void minimize_ (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol, OptimizerRecordND *optRec)=0
Finds a (local) minimum for a float function over a specific range.
Private Attributes
int nDim_
Stores the dimension of the minimization problem (if it has been defined)
const FunctionND * fND_
Stores a pointer to the nD function of the minimization problem (if it has been defined)
const FunctionND_F * fNF_
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Detailed Description
Pure virtual parent class for all n-dimensional optimizers.
Subclasses of NonlinearOptimizerND will actually implement an optimization algorithm, i.e. Powells conjugate gradients.
I have flip-flopped for a while on a couple of questions regarding optimizers:
Inheritance: Is there any point at all to using inheritance for these classes, and wouldn't it be simpler to simple propose a flat list of implementations with no common parent class? All the more so since most of the functions in these classes could very well be static. I opted for a class hierarchy because this allows me in the future to define a "processing pipeline" with a generic nd optimizer, and then pick the particular optimizer subclass to use w/o having to redefine the pipeline.
Should an optimizer store a reference to the nd function of the optimization problem, since all my minimize_ functions take the nd function asone of their parameters? The answer is yes, because setting the function (and dimension) allows to preallocate matrices and setup 1D "line" optimizers (if needed). Now, if the user wants to change the nd funtion each time they solve a minimization problem, this is their problem.
What about a set of "maximize" functions? No time, and not convinced that it's worth it. Since the user has to define & implement the function to optimize, nothing prevents implenting -f or bigNumber - f and run through minimization to get the maximum of +f.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 59 of file NonlinearOptimizerND.h.
Constructor & Destructor Documentation
NonlinearOptimizerND::NonlinearOptimizerND (void)
Creates a new nD optimizer.
Definition at line 38 of file NonlinearOptimizerND.cpp.
                         :       nDim_(0),
                                 fND_(NULL),
                                 fNF_(NULL)
 {
 }
NonlinearOptimizerND::NonlinearOptimizerND (int n)
Creates a new n-dimensional nD optimizer.
Parameters
n dimension of the optimization problem
Definition at line 46 of file NonlinearOptimizerND.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
                         :       nDim_(n),
                                 fND_(NULL),
                                 fNF_(NULL)
 {
         FAIL_CONDITION( n < 0,
                                         kInvalidParameterError,
                                         "Negative dimension passed to NonlinearOptimizerND constructor");
 }
NonlinearOptimizerND::NonlinearOptimizerND (const FunctionND * f)
Creates a new n-dimensional nD optimizer for a specific function.
Parameters
f the function of the optimization problem
Definition at line 56 of file NonlinearOptimizerND.cpp.
                         :       nDim_(f->getDimension()),
                                 fND_(f),
                                 fNF_(NULL)
 {
 }
 catch(...)
 {
         FAIL_CONDITION( f == NULL,
                                         kNullFunctionError,
                                         "Null function pointer passed to NonlinearOptimizerND constructor");
         FAIL_CONDITION( true,
                                         kNumericalError,
                                         "Unexpected error in NonlinearOptimizerND constructor");
 }
NonlinearOptimizerND::NonlinearOptimizerND (const FunctionND_F * f)
Creates a new n-dimensional nD optimizer for a specific function.
Parameters
f the function of the optimization problem
Definition at line 74 of file NonlinearOptimizerND.cpp.
                         :       nDim_(f->getDimension()),
                                 fND_(NULL),
                                 fNF_(f)
 {
 }
 catch(...)
 {
         FAIL_CONDITION( f == NULL,
                                         kNullFunctionError,
                                         "Null function pointer passed to NonlinearOptimizerND constructor");
         FAIL_CONDITION( true,
                                         kNumericalError,
                                         "Unexpected error in NonlinearOptimizerND constructor");
 }
NonlinearOptimizerND::~NonlinearOptimizerND (void) virtual
Destructor.
Definition at line 94 of file NonlinearOptimizerND.cpp.
 {
 }
uriVL::NonlinearOptimizerND::NonlinearOptimizerND (const NonlinearOptimizerND & obj) private
Disabled copy constructor.
Member Function Documentation
int NonlinearOptimizerND::getDimension (void) const
Gives the dimension of this optimizer (if one has been set)
Returns
dimension of this optimizer
Definition at line 153 of file NonlinearOptimizerND.cpp.
References nDim_.
Referenced by uriVL::NonlinearOptimizerND_conjDir::minimize_(), uriVL::NonlinearOptimizerND_conjDir::updateConjugateDirections_(), and uriVL::NonlinearOptimizerND_conjDir::~NonlinearOptimizerND_conjDir().
 {
         return nDim_;
 }
bool NonlinearOptimizerND::isOptimizationFunction (const FunctionND * f)
Checks if the function passed as parameter is the one set for this optimization problem.
Why this function: Because the library (still) admits double and float versions of the Function1D class, we can't have a getFunction function, and I don't like the idea of using protected variables much.
Returns
true if f is the function of this optimizaton problem
Definition at line 142 of file NonlinearOptimizerND.cpp.
References fND_.
Referenced by uriVL::NonlinearOptimizerND_conjDir::minimize_().
 {
         return (fND_ == f);
 }
bool NonlinearOptimizerND::isOptimizationFunction (const FunctionND_F * f)
Checks if the function passed as parameter is the one set for this optimization problem.
Why this function: Because the library (still) admits double and float versions of the Function1D class, we can't have a getFunction function, and I don't like the idea of using protected variables much.
Returns
true if f is the function of this optimizaton problem
Definition at line 147 of file NonlinearOptimizerND.cpp.
References fNF_.
 {
         return (fNF_ == f);
 }
const OptimizerRecordND * NonlinearOptimizerND::minimize (const FunctionND * f, const double * startX, const double * xMin, const double * xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
Returns
result of the minimization in an OptimizerRecordND
Definition at line 531 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), checkIfSearchStartPointIsValid_(), FAIL_CONDITION, uriVL::FunctionND::getDimension(), uriVL::kNullFunctionError, uriVL::kNullParameterError, uriVL::kNumericalError, and minimize_().
Referenced by main().
 {
         //----------------------------------------------------
         //      First test for null parameters
         //----------------------------------------------------
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( startX == NULL,
                     kNullParameterError,
                     "null start point as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMin == NULL,
                     kNullParameterError,
                     "null min range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMax == NULL,
                     kNullParameterError,
                     "null max range as parameter in NonlinearOptimizerND::minimize");
         //----------------------------------------------------------------------------------
         //      Check if the start point belongs to the search domain and domain of definition
         //----------------------------------------------------------------------------------
         try
         {
                 checkIfSearchStartPointIsValid_(f, xMin, xMax, startX);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
         //----------------------------------------------------------------------------------
         //      Finally, perform the minimization
         //----------------------------------------------------------------------------------
         OptimizerRecordND* optRec = NULL;
         try
         {
                 optRec = new OptimizerRecordND(f->getDimension());
                 minimize_(f, startX, xMin, xMax, tol, optRec);
         }
         catch (ErrorReport& e)
         {
                 if (optRec != NULL)
                 {
                         delete optRec;
                         optRec = NULL;
                 }
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
     return optRec;
 }
const OptimizerRecordND * NonlinearOptimizerND::minimize (const FunctionND_F * f, const float * startX, const float * xMin, const float * xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
Returns
result of the minimization in an OptimizerRecordND
Definition at line 166 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), checkIfSearchStartPointIsValid_(), FAIL_CONDITION, uriVL::FunctionND_F::getDimension(), uriVL::kNullFunctionError, uriVL::kNullParameterError, uriVL::kNumericalError, and minimize_().
 {
         //----------------------------------------------------
         //      First test for null parameters
         //----------------------------------------------------
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( startX == NULL,
                     kNullParameterError,
                     "null start point as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMin == NULL,
                     kNullParameterError,
                     "null min range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMax == NULL,
                     kNullParameterError,
                     "null max range as parameter in NonlinearOptimizerND::minimize");
         //----------------------------------------------------------------------------------
         //      Check if the start point belongs to the search domain and domain of definition
         //----------------------------------------------------------------------------------
         try
         {
                 checkIfSearchStartPointIsValid_(f, xMin, xMax, startX);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
         //----------------------------------------------------------------------------------
         //      Finally, perform the minimization
         //----------------------------------------------------------------------------------
         OptimizerRecordND* optRec = NULL;
         try
         {
                 optRec = new OptimizerRecordND(f->getDimension());
                 minimize_(f, startX, xMin, xMax, tol, optRec);
         }
         catch (ErrorReport& e)
         {
                 if (optRec != NULL)
                 {
                         delete optRec;
                         optRec = NULL;
                 }
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
     return optRec;
 }
const OptimizerRecordND* uriVL::NonlinearOptimizerND::minimize (const FunctionND * f, const std::vector< double > & startX, const std::vector< double > & xMin, const std::vector< double > & xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
Returns
result of the minimization in an OptimizerRecordND
const OptimizerRecordND* uriVL::NonlinearOptimizerND::minimize (const FunctionND_F * f, const std::vector< float > & startX, const std::vector< float > & xMin, const std::vector< float > & xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
Returns
result of the minimization in an OptimizerRecordND
void NonlinearOptimizerND::minimize (const FunctionND * f, const double * startX, const double * xMin, const double * xMax, double tol, OptimizerRecordND * optRec)
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Definition at line 605 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), checkIfSearchStartPointIsValid_(), FAIL_CONDITION, uriVL::FunctionND::getDimension(), uriVL::kInvalidParameterError, uriVL::kNullFunctionError, uriVL::kNullParameterError, uriVL::kNumericalError, minimize_(), and uriVL::OptimizerRecordND::nDim.
 {
         //----------------------------------------------------
         //      First test for null parameters
         //----------------------------------------------------
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( startX == NULL,
                     kNullParameterError,
                     "null start point as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMin == NULL,
                     kNullParameterError,
                     "null min range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMax == NULL,
                     kNullParameterError,
                     "null max range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( optRec == NULL,
                     kNullParameterError,
                     "null optimizer record as parameter in NonlinearOptimizerND::minimize");
         //----------------------------------------------------------------------------------
         //      Check if dimensions match
         //----------------------------------------------------------------------------------
         int fDim = -1, recDim = -2;
         try
         {
                 fDim = f->getDimension();
                 recDim = optRec->nDim;
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid Parameter error in NonlinearOptimizerND::minimize");
         }
     FAIL_CONDITION( fDim != recDim,
                     kInvalidParameterError,
                     "function's and optimizer's dimensions don't match");
         //----------------------------------------------------------------------------------
         //      Check if the start point belongs to the search domain and domain of definition
         //----------------------------------------------------------------------------------
         try
         {
                 checkIfSearchStartPointIsValid_(f, xMin, xMax, startX);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
         //----------------------------------------------------------------------------------
         //      Finally, perform the minimization
         //----------------------------------------------------------------------------------
         try
         {
                 minimize_(f, startX, xMin, xMax, tol, optRec);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
 }
void NonlinearOptimizerND::minimize (const FunctionND_F * f, const float * startX, const float * xMin, const float * xMax, float tol, OptimizerRecordND * optRec)
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Definition at line 347 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), checkIfSearchStartPointIsValid_(), FAIL_CONDITION, uriVL::FunctionND_F::getDimension(), uriVL::kInvalidParameterError, uriVL::kNullFunctionError, uriVL::kNullParameterError, uriVL::kNumericalError, minimize_(), and uriVL::OptimizerRecordND::nDim.
 {
         //----------------------------------------------------
         //      First test for null parameters
         //----------------------------------------------------
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( startX == NULL,
                     kNullParameterError,
                     "null start point as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMin == NULL,
                     kNullParameterError,
                     "null min range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( xMax == NULL,
                     kNullParameterError,
                     "null max range as parameter in NonlinearOptimizerND::minimize");
     FAIL_CONDITION( optRec == NULL,
                     kNullParameterError,
                     "null optimizer record as parameter in NonlinearOptimizerND::minimize");
         //----------------------------------------------------------------------------------
         //      Check if dimensions match
         //----------------------------------------------------------------------------------
         int fDim = -1, recDim = -2;
         try
         {
                 fDim = f->getDimension();
                 recDim = optRec->nDim;
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid Parameter error in NonlinearOptimizerND::minimize");
         }
     FAIL_CONDITION( fDim != recDim,
                     kInvalidParameterError,
                     "function's and optimizer's dimensions don't match");
         //----------------------------------------------------------------------------------
         //      Check if the start point belongs to the search domain and domain of definition
         //----------------------------------------------------------------------------------
         try
         {
                 checkIfSearchStartPointIsValid_(f, xMin, xMax, startX);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
         //----------------------------------------------------------------------------------
         //      Finally, perform the minimization
         //----------------------------------------------------------------------------------
         try
         {
                 minimize_(f, startX, xMin, xMax, tol, optRec);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by NonlinearOptimizerND::minimize");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in NonlinearOptimizerND::minimize");
         }
 }
void uriVL::NonlinearOptimizerND::minimize (const FunctionND * f, const std::vector< double > & startX, const std::vector< double > & xMin, const std::vector< double > & xMax, double tol, OptimizerRecordND * optRec)
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
void uriVL::NonlinearOptimizerND::minimize (const FunctionND_F * f, const std::vector< float > & startX, const std::vector< float > & xMin, const std::vector< float > & xMax, float tol, OptimizerRecordND * optRec)
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
virtual void uriVL::NonlinearOptimizerND::minimize_ (const FunctionND * f, const double * startX, const double * xMin, const double * xMax, double tol, OptimizerRecordND * optRec) private pure virtual
Finds a (local) minimum for a double function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizerND_conjDir.
Referenced by minimize().
virtual void uriVL::NonlinearOptimizerND::minimize_ (const FunctionND_F * f, const float * startX, const float * xMin, const float * xMax, float tol, OptimizerRecordND * optRec) private pure virtual
Finds a (local) minimum for a float function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizerND_conjDir.
virtual void uriVL::NonlinearOptimizerND::minimize_ (const FunctionND * f, const std::vector< double > & startX, const std::vector< double > & xMin, const std::vector< double > & xMax, double tol, OptimizerRecordND * optRec) private pure virtual
Finds a (local) minimum for a double function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizerND_conjDir.
virtual void uriVL::NonlinearOptimizerND::minimize_ (const FunctionND_F * f, const std::vector< float > & startX, const std::vector< float > & xMin, const std::vector< float > & xMax, float tol, OptimizerRecordND * optRec) private pure virtual
Finds a (local) minimum for a float function over a specific range.
Should be implemented by subclasses.
Parameters
f the function to optimize
startX starting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implemented in uriVL::NonlinearOptimizerND_conjDir.
const NonlinearOptimizerND& uriVL::NonlinearOptimizerND::operator= (const NonlinearOptimizerND & obj) private
Disabled copy operator.
void NonlinearOptimizerND::setFunction (const FunctionND * f)
Assigns a new nD function to this optimizer.
Note that an optimizer cannot have a double and float function assigned to it. The last function assigned simply replaces the previous one, regardless of type.
Parameters
f the function of the optimization problem
Definition at line 105 of file NonlinearOptimizerND.cpp.
References FAIL_CONDITION, fND_, fNF_, uriVL::kNullFunctionError, and setFunction_().
Referenced by uriVL::NonlinearOptimizerND_conjDir::minimize_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND constructor");
         //      don't waste time
         if (f != fND_)
         {
                 //      call the private setting function (possibly overriden by child class)
                 setFunction_(f);
                 //      sets the variables
                 fNF_ = NULL;
                 fND_ = f;
         }
 }
void NonlinearOptimizerND::setFunction (const FunctionND_F * f)
Assigns a new nD function to this optimizer.
Note that an optimizer cannot have a double and float function assigned to it. The last function assigned simply replaces the previous one, regardless of type.
Parameters
f the function of the optimization problem
Definition at line 123 of file NonlinearOptimizerND.cpp.
References FAIL_CONDITION, fND_, fNF_, uriVL::kNullFunctionError, and setFunction_().
 {
     FAIL_CONDITION( f == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND constructor");
         //      don't waste time
         if (f != fNF_)
         {
                 //      call the private setting function (possibly overriden by child class)
                 setFunction_(f);
                 //      sets the variables
                 fND_ = NULL;
                 fNF_ = f;
         }
 }
virtual void uriVL::NonlinearOptimizerND::setFunction_ (const FunctionND * f) inline private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Reimplemented in uriVL::NonlinearOptimizerND_conjDir.
Definition at line 260 of file NonlinearOptimizerND.h.
Referenced by setFunction().
{
                                 //      nothing.  Override if needed
                         }
virtual void uriVL::NonlinearOptimizerND::setFunction_ (const FunctionND_F * f) inline private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Reimplemented in uriVL::NonlinearOptimizerND_conjDir.
Definition at line 270 of file NonlinearOptimizerND.h.
{
                                 //      nothing.  Override if needed
                         }
Member Data Documentation
const FunctionND* uriVL::NonlinearOptimizerND::fND_ private
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Definition at line 240 of file NonlinearOptimizerND.h.
Referenced by isOptimizationFunction(), and setFunction().
const FunctionND_F* uriVL::NonlinearOptimizerND::fNF_ private
Stores a pointer to the nD function of the minimization problem (if it has been defined)
Definition at line 244 of file NonlinearOptimizerND.h.
Referenced by isOptimizationFunction(), and setFunction().
int uriVL::NonlinearOptimizerND::nDim_ private
Stores the dimension of the minimization problem (if it has been defined)
Definition at line 236 of file NonlinearOptimizerND.h.
Referenced by getDimension().
The documentation for this class was generated from the following files:
NonlinearOptimizerND.h
NonlinearOptimizerND.cpp