URIVisionLibrary: uriVL::Contour Class Reference
uriVL::Contour Class Reference abstract
Set of ImagePoint objects which form a closed curve.
#include <Contour.h>
Public Member Functions
virtual ~Contour (void)
Destructor.
virtual bool hasSubpixelPrecision (void) const =0
Indicates whether the image points defining this contour have subpixel precision coordinates.
void initialize (int nbPts, ContourInitializer contourType, const ImageRect *rect, int padding=0)
Initializes the contour about a rectangular box.
void initialize (int nbPts, ContourInitializer contourType, const ImagePoint &center, float width, float height, float angle=0.f)
Initializes the contour along the edges of a rectangular box.
virtual void copyInto (Contour *contourOut) const =0
Copies this contour into the one received as parameter.
virtual int getNbPoints (void) const =0
Gives the number of points along the contour.
const std::list< float > * getInterPointDistances (void) const
Computes the distances between image points and returns it as a list of float numbers.
void setVertexColor (float red, float green, float blue)
Assigns a rendering color to the contour's vertices (alpha is set to 1)
void setVertexColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour (alpha is set to 1)
void setVertexColor (const float theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setVertexColor (const unsigned char theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setDrawPoints (bool drawPointCircle)
Sets whether to draw points at each vertex.
virtual bool contains (const ImagePoint *pt) const =0
Checks whether the point passed as parameter is inside the contour.
virtual bool contains (const ImagePoint_F *pt) const =0
Checks whether the point passed as parameter is inside the contour.
virtual bool contains (int x, int y) const =0
Checks whether the point passed as parameter is inside the contour.
virtual bool contains (float x, float y) const =0
Checks whether the point passed as parameter is inside the contour.
virtual bool isInside (const Contour_I *pt) const =0
Checks whether this contour is completely inside the one passed as parameter.
virtual bool isInside (const Contour_F *pt) const =0
Checks whether this contour is completely inside the one passed as parameter.
virtual void setPoint (int index, float x, float y)=0
Checks whether this contour completely contains the one passed as parameter.
void pointsHaveMoved (void)
To be called by a user who has modified the list of points or the points themselves.
Public Member Functions inherited from uriVL::ImageFeature
ImageFeature (void)
Default constructor.
ImageFeature (const ImageFeature &obj)
Copy constructor.
virtual ~ImageFeature (void)
Destructor.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void applyTransformation (const Transformation2D *theTransf)=0
Applies a Transformation2D to this object.
virtual void rotate (float angle, const ImagePoint *rotCenter=NULL)=0
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Protected Member Functions
Contour (bool isFloatingPoint=false)
Constructor.
Contour (const Contour &ct)
Copy Constructor.
void setInterPointDistancesAreUpToDate_ (void) const
Allows a child class whose content has been changed to force recomputation of the inter-point distances.
void setEdgeVectorsAreUpToDate_ (void) const
Allows a child class whose content has been changed to force recomputation of the edge vectors.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Static Protected Attributes
static float VERTEX_DOT_RADIUS = 4.f
Radius of the circular dot used to render a vertex.
Private Member Functions
const Contour & operator= (const Contour &obj)
Copy operator: disabled.
virtual void initializeBox_ (const ImageRect &rect, int padding=0)=0
Initializes the contour along the edges of a rectangular box.
virtual void initializeBox_ (int nbPts, const ImagePoint &upperLeft, const ImagePoint &upperRight, const ImagePoint &lowerLeft, const ImagePoint &lowerRight)=0
Initializes the contour about a rectangular box.
virtual void initializeOval_ (int nbPts, const ImagePoint &center, float width, float height, float angle=0.f)=0
Initializes the contour along the edges of a oval.
virtual void computeInterPointDistances_ (void) const =0
Computes the distances between image points.
virtual void computeEdgeVectorList_ (void) const =0
Computes the edges along the closed contour and returns it as a list of image points.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the drawable object.
void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the contour.
Private Attributes
std::list< float > ptDistance_
The list of inter-point distances along the contour.
float color_ [4]
The contour's rendering color.
float vertexColor_ [4]
The rendering color for the contour's points.
bool isFloatingPointContour_
Indicates whether the points on this contour have floating point coordinates.
bool interPointDistancesAreUpToDate_
Indicates whether the inter-point distance list is up to date.
bool edgeVectorsAreUpToDate_
Indicates whether the edge list is up to date.
bool drawPoints_
Indicates whether individual points are drawn.
Friends
class Contour_F
class Contour_I
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Detailed Description
Set of ImagePoint objects which form a closed curve.
See also
Blob
Contour_I
Contour_F
Author
Clifford Manzanillo, jyh Department of Computer Science and Statistics, University of Rhode Island
Definition at line 53 of file Contour.h.
Constructor & Destructor Documentation
Contour::~Contour (void) virtual
Destructor.
Definition at line 74 of file Contour.cpp.
References ptDistance_.
 {
         ptDistance_.clear();
 }
Contour::Contour (bool isFloatingPoint = false) protected
Constructor.
Parameters
isFloatingPoint true if the points on this contour have floating point coordinates
Definition at line 61 of file Contour.cpp.
References vertexColor_.
         :   ImageFeature(),
                         //
                         ptDistance_(list<float>(0)),
                         isFloatingPointContour_(isFloatingPoint),
                         interPointDistancesAreUpToDate_(false),
                         edgeVectorsAreUpToDate_(false),
                         drawPoints_(false)
 {
     vertexColor_[0] = vertexColor_[1] = vertexColor_[2] = 0.f;
     vertexColor_[3] = 1.0f;
 }
Contour::Contour (const Contour & ct) protected
Copy Constructor.
Parameters
ct the object to copy
Definition at line 35 of file Contour.cpp.
References vertexColor_.
                         :   ImageFeature(ct),
                                 //
                                 ptDistance_(ct.ptDistance_),
                                 isFloatingPointContour_(ct.isFloatingPointContour_),
                                 interPointDistancesAreUpToDate_(ct.interPointDistancesAreUpToDate_),
                                 edgeVectorsAreUpToDate_(ct.edgeVectorsAreUpToDate_),
                                 drawPoints_(ct.drawPoints_)
 {
     vertexColor_[0] = vertexColor_[1] = vertexColor_[2] = 0.f;
     vertexColor_[3] = 1.0f;
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by Contour constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid Contour reference parameter passed to Contour constructor");
 }
Member Function Documentation
virtual void uriVL::Contour::computeEdgeVectorList_ (void) const private pure virtual
Computes the edges along the closed contour and returns it as a list of image points.
Admittedly, it is not pretty to use an ImagePoint object to store a vector. This will have to be changed in the not-too-distant future;
This function returns private data of the contour object. Do not modify it.
See also
getEdgeList
edgeList_
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual void uriVL::Contour::computeInterPointDistances_ (void) const private pure virtual
Computes the distances between image points.
See also
getInterPointDistances
ptDistance_
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
Referenced by getInterPointDistances().
virtual bool uriVL::Contour::contains (const ImagePoint * pt) const pure virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
pt the point to check
Returns
true if pt is inside this contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::contains (const ImagePoint_F * pt) const pure virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
pt the point to check
Returns
true if pt is inside this contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::contains (int x, int y) const pure virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
Returns
true if pt is inside this contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::contains (float x, float y) const pure virtual
Checks whether the point passed as parameter is inside the contour.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
Returns
true if pt is inside this contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual void uriVL::Contour::copyInto (Contour * contourOut) const pure virtual
Copies this contour into the one received as parameter.
Parameters
contourOut The contour to copy this one into
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
const list< float > * Contour::getInterPointDistances (void) const
Computes the distances between image points and returns it as a list of float numbers.
Note that this function returns private data of the contour object. Do not modify it.
See also
calculateInterPointDistances
ptDistance_
Definition at line 172 of file Contour.cpp.
References computeInterPointDistances_(), interPointDistancesAreUpToDate_, and ptDistance_.
Referenced by uriVL::ActiveContourDetector_balloon::calculateShrinkForce_().
 {
     if (!interPointDistancesAreUpToDate_)
         computeInterPointDistances_();
     return &ptDistance_;
 }
virtual int uriVL::Contour::getNbPoints (void) const pure virtual
Gives the number of points along the contour.
Returns
number of points along the contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::hasSubpixelPrecision (void) const pure virtual
Indicates whether the image points defining this contour have subpixel precision coordinates.
Returns
true if this contour's points have subpixel precision
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
void Contour::initialize (int nbPts, ContourInitializer contourType, const ImageRect * rect, int padding = 0)
Initializes the contour about a rectangular box.
Parameters
nbPts number of points to create along the contour
contourType the type of contour to initialize this one to
rect rectangular box
padding signed distance away from the box at which to initialize the contour (negative distance creates the contour inside the box)
Definition at line 96 of file Contour.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "This contour intializer is not implemented yet.");
 }
void Contour::initialize (int nbPts, ContourInitializer contourType, const ImagePoint & center, float width, float height, float angle = 0.f)
Initializes the contour along the edges of a rectangular box.
Parameters
nbPts number of points to create along the contour
contourType the type of contour to initialize this one to
center coordinates of the contour's center
width width of the box or ellipse
height height of the box or ellipse
angle orientation of the contour
Definition at line 105 of file Contour.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "This contour intializer is not implemented yet.");
 }
virtual void uriVL::Contour::initializeBox_ (const ImageRect & rect, int padding = 0) private pure virtual
Initializes the contour along the edges of a rectangular box.
Parameters
rect rectangular box
padding distance away from the box at which to initialize the contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual void uriVL::Contour::initializeBox_ (int nbPts, const ImagePoint & upperLeft, const ImagePoint & upperRight, const ImagePoint & lowerLeft, const ImagePoint & lowerRight) private pure virtual
Initializes the contour about a rectangular box.
Parameters
nbPts number of points to create along the contour
contourType the type of contour to initialize this one to
rect rectangular box
padding signed distance away from the box at which to initialize the contour (negative distance creates the contour inside the box)
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual void uriVL::Contour::initializeOval_ (int nbPts, const ImagePoint & center, float width, float height, float angle = 0.f) private pure virtual
Initializes the contour along the edges of a oval.
Parameters
nbPts number of points to create along the contour
contourType the type of contour to initialize this one to
center coordinates of the contour's center
width width of the box or ellipse
height height of the box or ellipse
angle orientation of the contour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::isInside (const Contour_I * pt) const pure virtual
Checks whether this contour is completely inside the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour is inside theContour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
virtual bool uriVL::Contour::isInside (const Contour_F * pt) const pure virtual
Checks whether this contour is completely inside the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour is inside theContour
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
const Contour & Contour::operator= (const Contour & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 79 of file Contour.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Contour copy operator not implemented.");
         return *this;
 }
void Contour::pointsHaveMoved (void)
To be called by a user who has modified the list of points or the points themselves.
This forces recomputation of some of the summary data.
Definition at line 187 of file Contour.cpp.
References edgeVectorsAreUpToDate_, interPointDistancesAreUpToDate_, uriVL::DrawableObject2D::setBoundingRectIsUpToDate_(), uriVL::DrawableObject2D::setCenterOfMassIsUpToDate_(), uriVL::DrawableObject2D::setCentroidIsUpToDate_(), and uriVL::DrawableObject2D::setValidRectIsUpToDate_().
Referenced by uriVL::ContourForce::applyForceToContour(), uriVL::Contour_F::applyTransformation(), uriVL::Contour_I::applyTransformation(), uriVL::Contour_F::rotate(), uriVL::Contour_I::rotate(), and uriVL::Contour_F::translate().
 {
     interPointDistancesAreUpToDate_ = false;
     edgeVectorsAreUpToDate_ = false;
         setCentroidIsUpToDate_(false);
         setCenterOfMassIsUpToDate_(false);
         setBoundingRectIsUpToDate_(false);
         setValidRectIsUpToDate_(false);
 }
void Contour::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the drawable object.
A drawable object occupies a rectangle within the global image space. For example, a drawable object could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function should be overridden by child classes that have their own raster (eg. HSV, gray_F, etc.)
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
theWidth desired width of the object
theHeight desired height of the object
Implements uriVL::DrawableObject2D.
Definition at line 218 of file Contour.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     //  this function should clip the contour to the new dimensions of the bounding box.
     //  See Folley van-Damm for algorithm
 }
void Contour::setDrawPoints (bool drawPointCircle)
Sets whether to draw points at each vertex.
Parameters
drawPointCircle
Definition at line 158 of file Contour.cpp.
References drawPoints_.
Referenced by uriVL::ContourForce::setDrawPoints().
 {
         drawPoints_ = drawPointCircle;
 }
void Contour::setEdgeVectorsAreUpToDate_ (void) const protected
Allows a child class whose content has been changed to force recomputation of the edge vectors.
Parameters
isUpToDate are edge vectors up to date?
Definition at line 202 of file Contour.cpp.
References edgeVectorsAreUpToDate_.
 {
     edgeVectorsAreUpToDate_ = true;
 }
void Contour::setInterPointDistancesAreUpToDate_ (void) const protected
Allows a child class whose content has been changed to force recomputation of the inter-point distances.
Parameters
isUpToDate are inter-point distances up to date?
Definition at line 197 of file Contour.cpp.
References interPointDistancesAreUpToDate_.
 {
     interPointDistancesAreUpToDate_ = true;
 }
virtual void uriVL::Contour::setPoint (int index, float x, float y) pure virtual
Checks whether this contour completely contains the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour contains theContourChecks whether this contour completely contains the one passed as parameter.
Parameters
contour the contour to check against
Returns
true if this contour contains theContourSet the coordinates of the contour's vertex whose index is provided. Fails if the index is larger that the number of vertices of the contour.
Parameters
index index of the vertex to modify
x new x coordinate of the vertex
y new y coordinate of the vertex
Implemented in uriVL::Contour_I, and uriVL::Contour_F.
void Contour::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the contour.
Not sure yet what this function should do
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Definition at line 228 of file Contour.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void Contour::setVertexColor (float red, float green, float blue)
Assigns a rendering color to the contour's vertices (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 122 of file Contour.cpp.
References vertexColor_.
 {
     vertexColor_[0] = red;
     vertexColor_[1] = green;
     vertexColor_[2] = blue;
     vertexColor_[3] = 1.f;
 }
void Contour::setVertexColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 142 of file Contour.cpp.
References vertexColor_.
 {
     vertexColor_[0] = red/255.f;
     vertexColor_[1] = green/255.f;
     vertexColor_[2] = blue/255.f;
     vertexColor_[3] = 1.f;
 }
void Contour::setVertexColor (const float theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 130 of file Contour.cpp.
References vertexColor_.
 {
     vertexColor_[0] = theColor[0];
     vertexColor_[1] = theColor[1];
     vertexColor_[2] = theColor[2];
     vertexColor_[3] = 1.f;
 }
void Contour::setVertexColor (const unsigned char theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 150 of file Contour.cpp.
References vertexColor_.
 {
     vertexColor_[0] = theColor[0]/255.f;
     vertexColor_[1] = theColor[1]/255.f;
     vertexColor_[2] = theColor[2]/255.f;
     vertexColor_[3] = 1.f;
 }
Friends And Related Function Documentation
friend class Contour_F friend
Definition at line 378 of file Contour.h.
friend class Contour_I friend
Definition at line 379 of file Contour.h.
Member Data Documentation
float uriVL::Contour::color_[4] private
The contour's rendering color.
Definition at line 257 of file Contour.h.
bool uriVL::Contour::drawPoints_ private
Indicates whether individual points are drawn.
Definition at line 279 of file Contour.h.
Referenced by uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), and setDrawPoints().
bool uriVL::Contour::edgeVectorsAreUpToDate_ mutable private
Indicates whether the edge list is up to date.
Definition at line 275 of file Contour.h.
Referenced by uriVL::Contour_F::computeEdgeVectorList_(), uriVL::Contour_I::computeEdgeVectorList_(), uriVL::Contour_F::computeInterPointDistances_(), uriVL::Contour_I::computeInterPointDistances_(), uriVL::Contour_F::getEdgeList(), uriVL::Contour_I::getEdgeList(), pointsHaveMoved(), and setEdgeVectorsAreUpToDate_().
bool uriVL::Contour::interPointDistancesAreUpToDate_ mutable private
Indicates whether the inter-point distance list is up to date.
Definition at line 270 of file Contour.h.
Referenced by uriVL::Contour_F::computeInterPointDistances_(), uriVL::Contour_I::computeInterPointDistances_(), getInterPointDistances(), pointsHaveMoved(), and setInterPointDistancesAreUpToDate_().
bool uriVL::Contour::isFloatingPointContour_ mutable private
Indicates whether the points on this contour have floating point coordinates.
Definition at line 266 of file Contour.h.
std::list<float> uriVL::Contour::ptDistance_ mutable private
The list of inter-point distances along the contour.
distance [i] = || p[i] p[i+1] ||
Definition at line 253 of file Contour.h.
Referenced by uriVL::Contour_F::computeInterPointDistances_(), uriVL::Contour_I::computeInterPointDistances_(), uriVL::Contour_I::Contour_I(), getInterPointDistances(), and ~Contour().
float Contour::VERTEX_DOT_RADIUS = 4.f static protected
Radius of the circular dot used to render a vertex.
Definition at line 222 of file Contour.h.
Referenced by uriVL::Contour_F::render_(), and uriVL::Contour_I::render_().
float uriVL::Contour::vertexColor_[4] private
The rendering color for the contour's points.
Definition at line 261 of file Contour.h.
Referenced by Contour(), uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), and setVertexColor().
The documentation for this class was generated from the following files:
Contour.h
Contour.cpp