URIVisionLibrary: uriVL::ImageGradient_Gaussian_F Class Reference
uriVL::ImageGradient_Gaussian_F Class Reference
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
#include <ImageGradient_Gaussian_F.h>
Public Member Functions
ImageGradient_Gaussian_F (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
ImageGradient_Gaussian_F (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
ImageGradient_Gaussian_F (double theScale, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
ImageGradient_Gaussian_F (int theWidth, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified width.
~ImageGradient_Gaussian_F (void)
Destructor.
float getScale (void) const
Returns the scale of the operator.
VectorField * applyTo (const RasterImage *imgIn)
Applies this operator to a gray-level version of the input image and returns the result as a VectorField_F.
VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to a gray-level version of the input image within the rectangle specified as second parameter and returns the result as a VectorField_F.
void applyInto (const RasterImage *imgIn, VectorField *vectOut)
Applies this operator to a gray-level version of the input image and writes the result into a VectorField_F received as second parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)
Applies this operator to a gray-level version of the input image within the rectangle specified as second parameter and writes the result into a VectorField_F received as third parameter.
Public Member Functions inherited from uriVL::ImageGradient
virtual ~ImageGradient (void)
Destructor.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
ImageGradient_Gaussian_F (const ImageGradient_Gaussian_F &obj)
Copy constructor (disabled)
const ImageGradient_Gaussian_F & operator= (const ImageGradient_Gaussian_F &obj)
Copy operator: disabled.
void applyInto_3x3_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of a 3x3 gradient filter.
void applyInto_3x3_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the x component of a 3x3 gradient filter.
void applyInto_5x5_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of a 5x5 gradient filter.
void applyInto_5x5_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the y component of a 5x5 gradient filter.
void applyInto_7x7_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of a 7x7 gradient filter.
void applyInto_7x7_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the y component of a 7x7 gradient filter.
void applyInto_9x9_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of a 9x9 gradient filter.
void applyInto_9x9_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the y component of a 9x9 gradient filter.
void applyInto_11x11_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of an 11x11 gradient filter.
void applyInto_11x11_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the y component of an 11x11 gradient filter.
void applyInto_13x13_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Hard-coded function that computes the x component of a 13x13 gradient filter.
void applyInto_13x13_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Hard-coded function that computes the y component of a 13x13 gradient filter.
void applyInto_X_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvx)
Function that computes the x component of a generic (width greater than 13) gradient filter.
void applyInto_Y_ (const RasterImage_gray *imgIn, const ImageRect *theRect, float *const *fvy)
Function that computes the y component of a generic (width greater than 13) gradient filter.
void initializeFilter_ (void)
Initializes the coefficients' array.
Private Attributes
double scale_
Scale parameter (sigma) of the filter.
float * fg_
Stores into a 1D array the filter coefficients for the Gaussian.
float * fgD_
Stores into a 1D array the filter coefficients for the Gaussian's derivative.
Additional Inherited Members
Protected Member Functions inherited from uriVL::ImageGradient
ImageGradient (int theWidth, bool isIntOperator)
Creates an ImageGradient operator with the specified width.
ImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates an ImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ImageGradient (const ImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempGrayF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D gray temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
Objects of this class only operate on gray-level images. If a color image is sent as parameter, it gets converted to a gray-level image first. For operation on color images, see ColorImageGradient subclasses.
    Note that in the current implementation of this class the same scale is
    applied along the x and y directions.  Implementing a more general form
    is a low-priority item at this point.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file ImageGradient_Gaussian_F.h.
Constructor & Destructor Documentation
ImageGradient_Gaussian_F::ImageGradient_Gaussian_F (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
Parameters
scale scale sigma of the Gaussian filter
Definition at line 35 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ImageGradient(2*(((int ) (5*theScale))/2) + 1, false),
                                 //
                                 scale_(theScale),
                                 fg_(NULL),
                                 fgD_(NULL)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a Gaussian Gradient operator is 0.8");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
         throw e;
 }
ImageGradient_Gaussian_F::ImageGradient_Gaussian_F (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Gaussian filter
Definition at line 90 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ImageGradient(theWidth, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 fg_(NULL),
                                 fgD_(NULL)
 {
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
         throw e;
 }
ImageGradient_Gaussian_F::ImageGradient_Gaussian_F (double theScale, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 55 of file ImageGradient_Gaussian_F.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, uriVL::kInvalidParameterError, and uriVL::kNullParameterError.
                         :       ImageGradient(2*(((int ) (5*theScale))/2) + 1, false),
                                 //
                                 scale_(theScale),
                                 fg_(NULL),
                                 fgD_(NULL)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a G Gradient filter is 0.8");
         try {
 //              theRect->getWidth()*theRect->getHeight();
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
                 throw e;
         }
         catch (...) {
                 FAIL_CONDITION( theRect == NULL,
                                                 kNullParameterError,
                                                 "Null pointer passed to ImageGradient_Gaussian_F constructor");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid parameter passed to ImageGradient_Gaussian_F constructor");
         }
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
         throw e;
 }
ImageGradient_Gaussian_F::ImageGradient_Gaussian_F (int theWidth, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 110 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ImageGradient(theWidth, theRect, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 fg_(NULL),
                                 fgD_(NULL)
 {
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G Gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
         throw e;
 }
ImageGradient_Gaussian_F::~ImageGradient_Gaussian_F (void)
Destructor.
Definition at line 146 of file ImageGradient_Gaussian_F.cpp.
References fg_, and fgD_.
 {
     delete []fg_;
     delete []fgD_;
 }
ImageGradient_Gaussian_F::ImageGradient_Gaussian_F (const ImageGradient_Gaussian_F & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 129 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(theObj),
                                 //
                                 scale_(theObj.scale_),
                                 fg_(NULL),
                                 fgD_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_F copy constructor not implemented.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_F constructor");
         throw e;
 }
Member Function Documentation
void ImageGradient_Gaussian_F::applyInto (const RasterImage * imgIn, VectorField * vectOut) virtual
Applies this operator to a gray-level version of the input image and writes the result into a VectorField_F received as second parameter.
Parameters
imgIn the RasterImage to which the operator is applied
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 220 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kNullVectorFieldError.
Referenced by uriVL::EdgeDetector_Canny_F::applyInto(), applyTo(), uriVL::ActiveContourDetector_balloon::findContour(), myIdle(), myMenu2(), and myMenu3().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage passed as input to ImageGradient_Gaussian_F::applyInto");
     FAIL_CONDITION( vectOut == NULL,
                     kNullVectorFieldError,
                     "null VectorField passed as destination to ImageGradient_Gaussian_F::applyInto");
     applyInto(imgIn, imgIn->getValidRect(), vectOut);
 }
void ImageGradient_Gaussian_F::applyInto (const RasterImage * imgIn, const ImageRect * theRect, VectorField * vectOut) virtual
Applies this operator to a gray-level version of the input image within the rectangle specified as second parameter and writes the result into a VectorField_F received as third parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 233 of file ImageGradient_Gaussian_F.cpp.
References uriVL::ImageGradient::allocateTempRaster_(), applyInto_11x11_X_(), applyInto_11x11_Y_(), applyInto_13x13_X_(), applyInto_13x13_Y_(), applyInto_3x3_X_(), applyInto_3x3_Y_(), applyInto_5x5_X_(), applyInto_5x5_Y_(), applyInto_7x7_X_(), applyInto_7x7_Y_(), applyInto_9x9_X_(), applyInto_9x9_Y_(), applyInto_X_(), applyInto_Y_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::forceRasterUpdate(), uriVL::ImageGradient::freeTempRaster_(), uriVL::DrawableObject2D::getValidRect(), uriVL::VectorOperator::getWidth(), grayImg, uriVL::VectorField::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kNullVectorFieldError, uriVL::RasterImage_gray::localRasterGray(), uriVL::DrawableObject2D::setBoundRect(), uriVL::VectorField::setRasterAsReference(), and uriVL::DrawableObject2D::setValidRect().
 {
         //----------------------------------------------------------------
         //      STEP 0:         Test for null or invalid type parameters
         //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageGradient_Gaussian_F::applyInto");
     FAIL_CONDITION( vectOut == NULL,
                     kNullVectorFieldError,
                     "null VectorField passed as destination to ImageGradient_Gaussian_F::applyInto");
     //  so far I only accept a floating point vector field as output
         FAIL_CONDITION( !vectOut->hasFloatRaster(),
                         kInvalidRasterType,
                         "ImageGradient_Gaussian_F::applyInto only accepts float vector fields as destination");
         //----------------------------------------------------------------
         //      STEP 1:         Test for rectangle intersection
         //----------------------------------------------------------------
         //  determine the output rectangle that the input image can produce.
         //              Here, because we apply a filter of width&height (2m+1), we
         //              "lose m all around".
         ImageRect*      usableRect = new ImageRect(imgIn->getValidRect());
         const int       m = getWidth() / 2;
         usableRect->removeAllAround(m);
         //      ... and determine its intersection with the user-specified output rectangle
         ImageRect*      destRect = ImageRect::intersection(usableRect, theRect);
         delete usableRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output field does not contain the destination rect, it must be resized.
     if (!vectOut->contains(destRect))
         vectOut->setBoundRect(destRect);
         //----------------------------------------------------------------
         //      STEP 2:         Operate only on a gray-level image
         //----------------------------------------------------------------
     bool localGray = false;
         const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
         //----------------------------------------------------------------
         //      STEP 3:         Perform the calculations
         //----------------------------------------------------------------
     //  allocate a 2D raster for intermediate calculations if needed
     bool newTempRaster = allocateTempRaster_(imgIn->getValidRect());
     float*const* fvx = (float*const*) (((VectorField_F *) vectOut)->getShiftedRasterX2D());
     float*const* fvy = (float*const*) (((VectorField_F *) vectOut)->getShiftedRasterY2D());
     switch (getWidth())
     {
         case 3:
             applyInto_3x3_X_(grayImg, destRect, fvx);
             applyInto_3x3_Y_(grayImg, destRect, fvy);
             break;
         case 5:
             applyInto_5x5_X_(grayImg, destRect, fvx);
             applyInto_5x5_Y_(grayImg, destRect, fvy);
             break;
         case 7:
             applyInto_7x7_X_(grayImg, destRect, fvx);
             applyInto_7x7_Y_(grayImg, destRect, fvy);
             break;
         case 9:
             applyInto_9x9_X_(grayImg, destRect, fvx);
             applyInto_9x9_Y_(grayImg, destRect, fvy);
             break;
         case 11:
             applyInto_11x11_X_(grayImg, destRect, fvx);
             applyInto_11x11_Y_(grayImg, destRect, fvy);
             break;
         case 13:
             applyInto_13x13_X_(grayImg, destRect, fvx);
             applyInto_13x13_Y_(grayImg, destRect, fvy);
             break;
         default:
             applyInto_X_(grayImg, destRect, fvx);
             applyInto_Y_(grayImg, destRect, fvy);
             break;
     }
         //----------------------------------------------------------------
         //      STEP 4:         Set rectangle
         //----------------------------------------------------------------
         //      Very important:  At the end of the computation, don't forget to set the
         //      output's valid data rectangle.  In "safe" mode, the library has no way to guess
         //      what the valid data rectangle should be and sets it to its minimum value... empty
     vectOut->setValidRect(destRect);
         vectOut->setRasterAsReference();
     vectOut->forceRasterUpdate();
         //----------------------------------------------------------------
         //      STEP 5:         Free temporary storage (if needed)
         //----------------------------------------------------------------
         if (localGray)
             delete grayImg;
         delete destRect;
     if (newTempRaster)
                 freeTempRaster_();
 }
void ImageGradient_Gaussian_F::applyInto_11x11_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of an 11x11 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 1312 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM5 = iLow - 5, iHighP5 = iHigh + 5;
     int         j, jm1, jm2, jm3, jm4, jm5, jp1, jp2, jp3, jp4, jp5;
     int         i, im1, im2, im3, im4, im5, ip1, ip2, ip3, ip4, ip5;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM5; i<=iHighP5; i++)
                                 fTemp[i][j] =   fgD_[5]*(iGray[i][jm5] - iGray[i][jp5]) +
                                                                 fgD_[4]*(iGray[i][jm4] - iGray[i][jp4]) +
                                                                 fgD_[3]*(iGray[i][jm3] - iGray[i][jp3]) +
                                                                 fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM5; i<=iHighP5; i++)
                                 fTemp[i][j] =   fgD_[5]*(fGray[i][jm5] - fGray[i][jp5]) +
                                                                 fgD_[4]*(fGray[i][jm4] - fGray[i][jp4]) +
                                                                 fgD_[3]*(fGray[i][jm3] - fGray[i][jp3]) +
                                                                 fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_11x11_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the y component of an 11x11 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 1467 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM5 = iLow - 5, iHighP5 = iHigh + 5;
     int         j, jm1, jm2, jm3, jm4, jm5, jp1, jp2, jp3, jp4, jp5;
     int         i, im1, im2, im3, im4, im5, ip1, ip2, ip3, ip4, ip5;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM5; i<=iHighP5; i++)
                                 fTemp[i][j] =   fg_[5]*(iGray[i][jm5] + iGray[i][jp5]) +
                                                                 fg_[4]*(iGray[i][jm4] + iGray[i][jp4]) +
                                                                 fg_[3]*(iGray[i][jm3] + iGray[i][jp3]) +
                                                                 fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM5; i<=iHighP5; i++)
                                 fTemp[i][j] =   fg_[5]*(fGray[i][jm5] + fGray[i][jp5]) +
                                                                 fg_[4]*(fGray[i][jm4] + fGray[i][jp4]) +
                                                                 fg_[3]*(fGray[i][jm3] + fGray[i][jp3]) +
                                                                 fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_13x13_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of a 13x13 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 1622 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
      const int  iLowM6 = iLow - 6, iHighP6 = iHigh + 6;
     int         j, jm1, jm2, jm3, jm4, jm5, jm6, jp1, jp2, jp3, jp4, jp5, jp6;
     int         i, im1, im2, im3, im4, im5, im6, ip1, ip2, ip3, ip4, ip5, ip6;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM6; i<=iHighP6; i++)
                                 fTemp[i][j] =   fgD_[6]*(iGray[i][jm6] - iGray[i][jp6]) +
                                                                 fgD_[5]*(iGray[i][jm5] - iGray[i][jp5]) +
                                                                 fgD_[4]*(iGray[i][jm4] - iGray[i][jp4]) +
                                                                 fgD_[3]*(iGray[i][jm3] - iGray[i][jp3]) +
                                                                 fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
             {
                                 fvx[i][j] =     fg_[6]*(fTemp[im6][j] + fTemp[ip6][j]) +
                                                                 fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
             }
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM6; i<=iHighP6; i++)
                                 fTemp[i][j] =   fgD_[6]*(fGray[i][jm6] - fGray[i][jp6]) +
                                                                 fgD_[5]*(fGray[i][jm5] - fGray[i][jp5]) +
                                                                 fgD_[4]*(fGray[i][jm4] - fGray[i][jp4]) +
                                                                 fgD_[3]*(fGray[i][jm3] - fGray[i][jp3]) +
                                                                 fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[6]*(fTemp[im6][j] + fTemp[ip6][j]) +
                                                                 fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_13x13_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the y component of a 13x13 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 1792 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM6 = iLow - 6, iHighP6 = iHigh + 6;
     int         j, jm1, jm2, jm3, jm4, jm5, jm6, jp1, jp2, jp3, jp4, jp5, jp6;
     int         i, im1, im2, im3, im4, im5, im6, ip1, ip2, ip3, ip4, ip5, ip6;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM6; i<=iHighP6; i++)
                                 fTemp[i][j] =   fg_[6]*(iGray[i][jm6] + iGray[i][jp6]) +
                                                                 fg_[5]*(iGray[i][jm5] + iGray[i][jp5]) +
                                                                 fg_[4]*(iGray[i][jm4] + iGray[i][jp4]) +
                                                                 fg_[3]*(iGray[i][jm3] + iGray[i][jp3]) +
                                                                 fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[6]*(fTemp[im6][j] - fTemp[ip6][j]) +
                                                                 fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM6; i<=iHighP6; i++)
                                 fTemp[i][j] =   fg_[6]*(fGray[i][jm6] + fGray[i][jp6]) +
                                                                 fg_[5]*(fGray[i][jm5] + fGray[i][jp5]) +
                                                                 fg_[4]*(fGray[i][jm4] + fGray[i][jp4]) +
                                                                 fg_[3]*(fGray[i][jm3] + fGray[i][jp3]) +
                                                                 fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[6]*(fTemp[im6][j] - fTemp[ip6][j]) +
                                                                 fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_3x3_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of a 3x3 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 358 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     int         iLowM1 = iLow - 1, iHighP1 = iHigh+1;
     int         j, jm1, jp1;
     int         i, im1, ip1;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM1; i<=iHighP1; i++)
                                 fTemp[i][j] =   fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1;
                 ip1 = iLow+1;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im1 = i;
                         ip1++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM1; i<=iHighP1; i++)
                                 fTemp[i][j] =   fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1;
                 ip1 = iLow+1;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im1 = i;
                         ip1++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_3x3_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the x component of a 3x3 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 457 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM1 = iLow - 1, iHighP1 = iHigh + 1;
     int         j, jm1, jp1;
     int         i, im1, ip1;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM1; i<=iHighP1; i++)
                                 fTemp[i][j] =   fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1;
                 ip1 = iLow+1;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im1 = i;
                         ip1++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM1; i<=iHighP1; i++)
                                 fTemp[i][j] =   fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1;
                 ip1 = iLow+1;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im1 = i;
                         ip1++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_5x5_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of a 5x5 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 556 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     int     iLow = theRect->getTop(),
             iHigh = theRect->getBottom(),
             jLow = theRect->getLeft(),
             jHigh = theRect->getRight();
     int         iLowM2 = iLow - 2, iHighP2 = iHigh + 2;
     int         i, im1, im2, ip1, ip2;
     int         j, jm1, jm2, jp1, jp2;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2;
         jp1 = jLow+1; jp2 = jLow+2;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM2; i<=iHighP2; i++)
                                 fTemp[i][j] =   fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2;
                 ip1 = iLow+1; ip2 = iLow+2;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2;
         jp1 = jLow+1; jp2 = jLow+2;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM2; i<=iHighP2; i++)
                                 fTemp[i][j] =   fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2;
                 ip1 = iLow+1; ip2 = iLow+2;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_5x5_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the y component of a 5x5 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 667 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     int             iLowM2 = iLow - 2, iHighP2 = iHigh + 2;
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     int         i, im1, im2, ip1, ip2;
     int         j, jm1, jm2, jp1, jp2;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2;
         jp1 = jLow+1; jp2 = jLow+2;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM2; i<=iHighP2; i++)
                                 fTemp[i][j] =   fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2;
                 ip1 = iLow+1; ip2 = iLow+2;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2;
         jp1 = jLow+1; jp2 = jLow+2;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM2; i<=iHighP2; i++)
                                 fTemp[i][j] =   fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2;
                 ip1 = iLow+1; ip2 = iLow+2;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_7x7_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of a 7x7 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 778 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM3 = iLow - 3, iHighP3 = iHigh + 3;
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     int         i, im1, im2, im3, ip1, ip2, ip3;
     int         j, jm1, jm2, jm3, jp1, jp2, jp3;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM3; i<=iHighP3; i++)
                                 fTemp[i][j] =   fgD_[3]*(iGray[i][jm3] - iGray[i][jp3]) +
                                                                 fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM3; i<=iHighP3; i++)
                                 fTemp[i][j] =   fgD_[3]*(fGray[i][jm3] - fGray[i][jp3]) +
                                                                 fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_7x7_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the y component of a 7x7 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 902 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM3 = iLow - 3, iHighP3 = iHigh + 3;
     int         i, im1, im2, im3, ip1, ip2, ip3;
     int         j, jm1, jm2, jm3, jp1, jp2, jp3;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM3; i<=iHighP3; i++)
                                 fTemp[i][j] =   fg_[3]*(iGray[i][jm3] + iGray[i][jp3]) +
                                                                 fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM3; i<=iHighP3; i++)
                                 fTemp[i][j] =   fg_[3]*(fGray[i][jm3] + fGray[i][jp3]) +
                                                                 fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_9x9_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Hard-coded function that computes the x component of a 9x9 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 1026 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM4 = iLow - 4, iHighP4 = iHigh + 4;
     int         j, jm1, jm2, jm3, jm4, jp1, jp2, jp3, jp4;
     int         i, im1, im2, im3, im4, ip1, ip2, ip3, ip4;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM4; i<=iHighP4; i++)
                                 fTemp[i][j] =   fgD_[4]*(iGray[i][jm4] - iGray[i][jp4]) +
                                                                 fgD_[3]*(iGray[i][jm3] - iGray[i][jp3]) +
                                                                 fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM4; i<=iHighP4; i++)
                                 fTemp[i][j] =   fgD_[4]*(fGray[i][jm4] - fGray[i][jp4]) +
                                                                 fgD_[3]*(fGray[i][jm3] - fGray[i][jp3]) +
                                                                 fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvx[i][j] =     fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_9x9_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Hard-coded function that computes the y component of a 9x9 gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 1169 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowM4 = iLow - 4, iHighP4 = iHigh + 4;
     int         j, jm1, jm2, jm3, jm4, jp1, jp2, jp3, jp4;
     int         i, im1, im2, im3, im4, ip1, ip2, ip3, ip4;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM4; i<=iHighP4; i++)
                                 fTemp[i][j] =   fg_[4]*(iGray[i][jm4] + iGray[i][jp4]) +
                                                                 fg_[3]*(iGray[i][jm3] + iGray[i][jp3]) +
                                                                 fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowM4; i<=iHighP4; i++)
                                 fTemp[i][j] =   fg_[4]*(fGray[i][jm4] + fGray[i][jp4]) +
                                                                 fg_[3]*(fGray[i][jm3] + fGray[i][jp3]) +
                                                                 fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
                                 fvy[i][j] =     fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_X_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvx) private
Function that computes the x component of a generic (width greater than 13) gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvx x component of the output field
Definition at line 1959 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::VectorOperator::getWidth(), uriVL::RasterImage::hasFloatRaster(), kMaxHardCodedWidth, and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int    m = getWidth()/2;
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowMm = iLow - m, iHighPm = iHigh + m;
     int         j, jm1, jm2, jm3, jm4, jm5, jm6, jp1, jp2, jp3, jp4, jp5, jp6;
     int         i, im1, im2, im3, im4, im5, im6, ip1, ip2, ip3, ip4, ip5, ip6;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
         const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowMm; i<=iHighPm; i++)
             {
                                 fTemp[i][j] =   fgD_[6]*(iGray[i][jm6] - iGray[i][jp6]) +
                                                                 fgD_[5]*(iGray[i][jm5] - iGray[i][jp5]) +
                                                                 fgD_[4]*(iGray[i][jm4] - iGray[i][jp4]) +
                                                                 fgD_[3]*(iGray[i][jm3] - iGray[i][jp3]) +
                                                                 fgD_[2]*(iGray[i][jm2] - iGray[i][jp2]) +
                                                                 fgD_[1]*(iGray[i][jm1] - iGray[i][jp1]);
                                 for (int  l= kMaxHardCodedWidth+1; l<=m; l++)
                                         fTemp[i][j] += fgD_[l] * (iGray[i][j-l] - iGray[i][j+l] );
                         }
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
             {
                                 fvx[i][j] =     fg_[6]*(fTemp[im6][j] + fTemp[ip6][j]) +
                                                                 fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                                 for (int  k= kMaxHardCodedWidth+1; k<=m; k++)
                                                 fvx[i][j] += fg_[k] * (fTemp[i-k][j] + fTemp[i+k][j] );
                         }
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowMm; i<=iHighPm; i++)
             {
                                 fTemp[i][j] =   fgD_[6]*(fGray[i][jm6] - fGray[i][jp6]) +
                                                                 fgD_[5]*(fGray[i][jm5] - fGray[i][jp5]) +
                                                                 fgD_[4]*(fGray[i][jm4] - fGray[i][jp4]) +
                                                                 fgD_[3]*(fGray[i][jm3] - fGray[i][jp3]) +
                                                                 fgD_[2]*(fGray[i][jm2] - fGray[i][jp2]) +
                                                                 fgD_[1]*(fGray[i][jm1] - fGray[i][jp1]);
                                 for (int  l= kMaxHardCodedWidth+1; l<=m; l++)
                                                 fTemp[i][j] += fgD_[l] * (fGray[i][j-l] - fGray[i][j+l] );
                         }
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
             {
                                 fvx[i][j] =     fg_[6]*(fTemp[im6][j] + fTemp[ip6][j]) +
                                                                 fg_[5]*(fTemp[im5][j] + fTemp[ip5][j]) +
                                                                 fg_[4]*(fTemp[im4][j] + fTemp[ip4][j]) +
                                                                 fg_[3]*(fTemp[im3][j] + fTemp[ip3][j]) +
                                                                 fg_[2]*(fTemp[im2][j] + fTemp[ip2][j]) +
                                                                 fg_[1]*(fTemp[im1][j] + fTemp[ip1][j]) +
                                                                 fg_[0]* fTemp[i][j];
                                 for (int  k= kMaxHardCodedWidth+1; k<=m; k++)
                                                 fvx[i][j] += fg_[k] * (fTemp[i-k][j] + fTemp[i+k][j] );
             }
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
 }
void ImageGradient_Gaussian_F::applyInto_Y_ (const RasterImage_gray * imgIn, const ImageRect * theRect, float *const * fvy) private
Function that computes the y component of a generic (width greater than 13) gradient filter.
Parameters
imgIn the input image
theRect the rectangle over which the filter must be applied
fvy y component of the output field
Definition at line 2151 of file ImageGradient_Gaussian_F.cpp.
References fg_, fgD_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageGradient::getShiftedTempGrayF2D_(), uriVL::ImageRect::getTop(), uriVL::VectorOperator::getWidth(), uriVL::RasterImage::hasFloatRaster(), kMaxHardCodedWidth, and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     //  This private function is called after all data validity tests have been performed
     //  We know that the images are valid and that the rectangle fits both the input and
     //  the output images.
     float* const* fTemp = getShiftedTempGrayF2D_(R_W_ACCESS);
     const int   m = getWidth()/2;
     const int   iLow = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     const int   iLowMm = iLow - m, iHighPm = iHigh + m;
     int         j, jm1, jm2, jm3, jm4, jm5, jm6, jp1, jp2, jp3, jp4, jp5, jp6;
     int         i, im1, im2, im3, im4, im5, im6, ip1, ip2, ip3, ip4, ip5, ip6;
     //  case of an "integer" gray level image
     if (!imgIn->hasFloatRaster())
     {
        const unsigned char* const* iGray = imgIn->getShiftedRaster2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowMm; i<=iHighPm; i++)
             {
                                 fTemp[i][j] =   fg_[6]*(iGray[i][jm6] + iGray[i][jp6]) +
                                                                 fg_[5]*(iGray[i][jm5] + iGray[i][jp5]) +
                                                                 fg_[4]*(iGray[i][jm4] + iGray[i][jp4]) +
                                                                 fg_[3]*(iGray[i][jm3] + iGray[i][jp3]) +
                                                                 fg_[2]*(iGray[i][jm2] + iGray[i][jp2]) +
                                                                 fg_[1]*(iGray[i][jm1] + iGray[i][jp1]) +
                                                                 fg_[0]* iGray[i][j];
                                 for (int  l= kMaxHardCodedWidth+1; l<=m; l++)
                                         fTemp[i][j] += fg_[l] * (iGray[i][j-l] + iGray[i][j+l] );
                         }
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
             {
                                 fvy[i][j] =     fgD_[6]*(fTemp[im6][j] - fTemp[ip6][j]) +
                                                                 fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                                 for (int  k= kMaxHardCodedWidth+1; k<=m; k++)
                                                 fvy[i][j] += fgD_[k] * (fTemp[i-k][j] + fTemp[i+k][j] );
                         }
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
     //  float
     else
     {
         const float* const* fGray = ((RasterImage_gray_F *) imgIn)->getShiftedGrayF2D();
                 //-------------------------------------------------------
                 //      first apply the 1D filter along the x direction
                 //-------------------------------------------------------
                 //      Note that we have to apply this filter out of the destination rect since
                 //      some of these elements will be needed we we apply a filter along the
                 //      other direction.
         jm1 = jLow-1; jm2 = jLow-2; jm3 = jLow-3;
         jm4 = jLow-4; jm5 = jLow-5; jm6 = jLow-6;
         jp1 = jLow+1; jp2 = jLow+2; jp3 = jLow+3;
         jp4 = jLow+4; jp5 = jLow+5; jp6 = jLow+6;
         for (j=jLow; j<=jHigh; j++)
         {
             for (i=iLowMm; i<=iHighPm; i++)
             {
                                 fTemp[i][j] =   fg_[6]*(fGray[i][jm6] + fGray[i][jp6]) +
                                                                 fg_[5]*(fGray[i][jm5] + fGray[i][jp5]) +
                                                                 fg_[4]*(fGray[i][jm4] + fGray[i][jp4]) +
                                                                 fg_[3]*(fGray[i][jm3] + fGray[i][jp3]) +
                                                                 fg_[2]*(fGray[i][jm2] + fGray[i][jp2]) +
                                                                 fg_[1]*(fGray[i][jm1] + fGray[i][jp1]) +
                                                                 fg_[0]* fGray[i][j];
                                 for (int  l= kMaxHardCodedWidth+1; l<=m; l++)
                                                 fTemp[i][j] += fg_[l] * (fGray[i][j-l] + fGray[i][j+l] );
                         }
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm6 = jm5;
             jm5 = jm4;
             jm4 = jm3;
             jm3 = jm2;
             jm2 = jm1;
             jm1 = j;
             jp1 = jp2;
             jp2 = jp3;
             jp3 = jp4;
             jp4 = jp5;
             jp5 = jp6;
             jp6++;
                 }
                 //-------------------------------------------------------
                 //      then apply the 1D filter along the y direction
                 //-------------------------------------------------------
         im1 = iLow-1; im2 = iLow-2; im3 = iLow-3;
                 im4 = iLow-4; im5 = iLow-5; im6 = iLow-6;
                 ip1 = iLow+1; ip2 = iLow+2; ip3 = iLow+3;
                 ip4 = iLow+4; ip5 = iLow+5; ip6 = iLow+6;
         for (i=iLow; i<=iHigh; i++)
         {
             for (j=jLow; j<=jHigh; j++)
             {
                                 fvy[i][j] =     fgD_[6]*(fTemp[im6][j] - fTemp[ip6][j]) +
                                                                 fgD_[5]*(fTemp[im5][j] - fTemp[ip5][j]) +
                                                                 fgD_[4]*(fTemp[im4][j] - fTemp[ip4][j]) +
                                                                 fgD_[3]*(fTemp[im3][j] - fTemp[ip3][j]) +
                                                                 fgD_[2]*(fTemp[im2][j] - fTemp[ip2][j]) +
                                                                 fgD_[1]*(fTemp[im1][j] - fTemp[ip1][j]);
                                 for (int  k= kMaxHardCodedWidth+1; k<=m; k++)
                                                 fvy[i][j] += fgD_[k] * (fTemp[i-k][j] - fTemp[i+k][j] );
             }
                         //  shift the i indexes (i itself is taken care of in the loop
                         //  statement)
                         im6 = im5;
                         im5 = im4;
                         im4 = im3;
                         im3 = im2;
                         im2 = im1;
                         im1 = i;
                         ip1 = ip2;
                         ip2 = ip3;
                         ip3 = ip4;
                         ip4 = ip5;
                         ip5 = ip6;
                         ip6++;
                 }
     }
 }
VectorField * ImageGradient_Gaussian_F::applyTo (const RasterImage * imgIn) virtual
Applies this operator to a gray-level version of the input image and returns the result as a VectorField_F.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 184 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by uriVL::NormalFlowCalculator::applyInto().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage passed as input to ImageGradient_Gaussian_F::applyInto");
         return applyTo(imgIn, imgIn->getValidRect());
 }
VectorField * ImageGradient_Gaussian_F::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to a gray-level version of the input image within the rectangle specified as second parameter and returns the result as a VectorField_F.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 194 of file ImageGradient_Gaussian_F.cpp.
References applyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::VectorOperator::getWidth(), uriVL::ImageRect::intersection(), uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage passed as input to ImageGradient_Gaussian_F::applyInto");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageGradient_Gaussian_F::applyInto");
         ImageRect       *usableRect = new ImageRect(imgIn->getValidRect());
         const int       m = getWidth() / 2;
         usableRect->removeAllAround(m);
         ImageRect* destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
         VectorField     *vectOut = new VectorField_F(destRect);
         applyInto(imgIn, theRect, vectOut);
         delete destRect;
         delete usableRect;
         return vectOut;
 }
float ImageGradient_Gaussian_F::getScale (void) const virtual
Returns the scale of the operator.
Returns
scale of the operator
Implements uriVL::ImageGradient.
Definition at line 170 of file ImageGradient_Gaussian_F.cpp.
References scale_.
 {
     return static_cast<float>(scale_);
 }
void ImageGradient_Gaussian_F::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
fg_
fgD_
Definition at line 2352 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, fg_, fgD_, uriVL::VectorOperator::getWidth(), uriVL::kFilterAllocationError, PI, and scale_.
Referenced by ImageGradient_Gaussian_F().
 {
     const int  m = getWidth()/2;
     const double        sigma2Scale = 1.L / (2.L * scale_ * scale_),
                                         piSigma = 1.L / (sqrt(2*PI) * scale_),
                                         piSigma2 = piSigma/scale_;
     fg_ = new float [m+1];
     FAIL_CONDITION( fg_ == NULL,
                     kFilterAllocationError,
                     "filter allocation failed in ImageGradient_Gaussian_F::initializeFilter_");
     fgD_ = new float [m+1];
     FAIL_CONDITION( fgD_ == NULL,
                     kFilterAllocationError,
                     "filter allocation failed in ImageGradient_Gaussian_F::initializeFilter_");
     for (int  r=0; r<=m; r++)
     {
         //      fg_ is a regular 1D Gaussian
         fg_[r] = (float) (piSigma * exp(-r*r*sigma2Scale));
         //      fg1Dx_ is a first derivative of a 1D Gaussian
         fgD_[r] = (float) (-r * piSigma2 * exp(-r*r*sigma2Scale));
         }
 }
const ImageGradient_Gaussian_F & ImageGradient_Gaussian_F::operator= (const ImageGradient_Gaussian_F & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 153 of file ImageGradient_Gaussian_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_F copy operator not implemented.");
         return *this;
 }
Member Data Documentation
float* uriVL::ImageGradient_Gaussian_F::fg_ private
Stores into a 1D array the filter coefficients for the Gaussian.
Definition at line 159 of file ImageGradient_Gaussian_F.h.
Referenced by applyInto_11x11_X_(), applyInto_11x11_Y_(), applyInto_13x13_X_(), applyInto_13x13_Y_(), applyInto_3x3_X_(), applyInto_3x3_Y_(), applyInto_5x5_X_(), applyInto_5x5_Y_(), applyInto_7x7_X_(), applyInto_7x7_Y_(), applyInto_9x9_X_(), applyInto_9x9_Y_(), applyInto_X_(), applyInto_Y_(), initializeFilter_(), and ~ImageGradient_Gaussian_F().
float* uriVL::ImageGradient_Gaussian_F::fgD_ private
Stores into a 1D array the filter coefficients for the Gaussian's derivative.
Definition at line 163 of file ImageGradient_Gaussian_F.h.
Referenced by applyInto_11x11_X_(), applyInto_11x11_Y_(), applyInto_13x13_X_(), applyInto_13x13_Y_(), applyInto_3x3_X_(), applyInto_3x3_Y_(), applyInto_5x5_X_(), applyInto_5x5_Y_(), applyInto_7x7_X_(), applyInto_7x7_Y_(), applyInto_9x9_X_(), applyInto_9x9_Y_(), applyInto_X_(), applyInto_Y_(), initializeFilter_(), and ~ImageGradient_Gaussian_F().
double uriVL::ImageGradient_Gaussian_F::scale_ private
Scale parameter (sigma) of the filter.
Definition at line 155 of file ImageGradient_Gaussian_F.h.
Referenced by getScale(), and initializeFilter_().
The documentation for this class was generated from the following files:
ImageGradient_Gaussian_F.h
ImageGradient_Gaussian_F.cpp