URIVisionLibrary: uriVL::RigidTransformation2D Class Reference
uriVL::RigidTransformation2D Class Reference
Class for all 2D transformation composed of a translation and a rotation.
#include <RigidTransformation2D.h>
Public Member Functions
RigidTransformation2D (void)
Constructor.
RigidTransformation2D (const float theMat[][3])
Constructor.
RigidTransformation2D (const RigidTransformation2D *theTransf)
Clone constructor.
RigidTransformation2D (Rotation2D *theRot, Translation2D *theTrans)
Constructor.
virtual ~RigidTransformation2D (void)
Destructor.
void setMatrix (const float theMat[][3])
Assign a new matrix to this transformation.
float getTransX (void) const
Returns the x component of the translation.
float getTransY (void) const
Returns the y component of the translation.
float getAngle (void) const
Returns the rotation's angle.
void setAngle (float theAngle)
Sets the rotation's angle (in radians)
void setTranslation (float tx, float ty)
Sets the translation component of this transformation.
void setTranslation (const float trans[])
Sets the translation component of this transformation.
Public Member Functions inherited from uriVL::Transformation2D
Transformation2D (bool isRigid=false)
Constructor.
Transformation2D (const float theMat[][3])
Constructor.
Transformation2D (const float *const *theMat)
Constructor.
Transformation2D (const Transformation2D *theTransf)
Copy constructor.
Transformation2D (const Transformation2D &theTransf)
Copy constructor.
virtual ~Transformation2D (void)
Destructor.
const Transformation2D & operator= (const Transformation2D &theTransf)
Equal operator.
virtual void setMatrix (const float *const *theMat)
Assign a new matrix to this transformation.
const float *const *const getMatrix (void) const
Returns a read-only pointer to the transformation's matrix data.
float *const *const getMatrix (ReadWriteStatus rwa)
Returns a pointer to the transformation's's matrix data that allows to set new values to the matrix's elements.
ImagePoint_F * applyTo (const ImagePoint *pt)
Applies this transformation to the image point received as parameter.
ImagePoint_F * applyInto (const ImagePoint *pt, const ImagePoint *transfPt)
Applies this transformation to the image point received as parameter.
bool isRigidTransformation (void) const
Indicates whether this transftormation is rigid (rotation + translation)
Private Member Functions
void setMatrixAsReference_ (void)
Indicates that the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
void updateMatrix_ (void)
Updates the transformation matrix if it was not the reference, and if it is the reference, then re-orthogonalizes it.
virtual void orthogonalizeMatrix_ (void)
Ensures that the transformation matrix is still orthogonal.
Private Attributes
float angle_
Angle of the rotation component.
bool angleIsReference_
Indicates whether the angle is the reference.
Additional Inherited Members
Protected Member Functions inherited from uriVL::Transformation2D
bool checkOrthogonality_ (void) const
Check whether the matrix is orthogonal.
Detailed Description
Class for all 2D transformation composed of a translation and a rotation.
The translation component of the transformation is always stored in the object's matrix. The rotation component can be sotred either in the matrix or as an angle. The variables matrixIsReference_ and angleIsReference_ indicate which stores the "correct" reference value.
See also
matrixIsReference_
angleIsReference_
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file RigidTransformation2D.h.
Constructor & Destructor Documentation
RigidTransformation2D::RigidTransformation2D (void)
Constructor.
Creates an identity transformation.
Definition at line 24 of file RigidTransformation2D.cpp.
         :   Transformation2D(true),
                         //
                         angle_(0.f),
                         angleIsReference_(false)
 {
 }
RigidTransformation2D::RigidTransformation2D (const float theMat[][3])
Constructor.
Creates a 2D transformation based on the transformation matrix received as parameter
Parameters
theMat 3 by 3 transformation matrix
Definition at line 32 of file RigidTransformation2D.cpp.
References angleIsReference_, FAIL_CONDITION, uriVL::Transformation2D::isRigidTransformation(), and uriVL::kInvalidParameterError.
         :   Transformation2D(theMat),
                         //
                         angle_(0.f),
                         angleIsReference_(false)
 {
         FAIL_CONDITION( !isRigidTransformation(),
                                         kInvalidParameterError,
                                         "The matrix passed to RigidTransformation2D is not that of a rigid transformation");
     angleIsReference_ = false;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RigidTransformation2D constructor.");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid parameter passed to RigidTransformation2D constructor.");
 }
RigidTransformation2D::RigidTransformation2D (const RigidTransformation2D * theTransf)
Clone constructor.
Creates a 2D transformation identical to the one received as parameter
Parameters
theTransf transformation to clone
Definition at line 56 of file RigidTransformation2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   Transformation2D(true),
                         //
                         angle_(0.f),
                         angleIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Copy constructor not open for business yet");
 }
RigidTransformation2D::RigidTransformation2D (Rotation2D * theRot, Translation2D * theTrans)
Constructor.
Creates a 2D transformation based on the rotation and translation received as parameters
Parameters
theRot the rotation transformation
theTrans the translation transformation
Definition at line 67 of file RigidTransformation2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   Transformation2D(true),
                         //
                         angle_(0.f),
                         angleIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor not fully open for business yet");
 }
RigidTransformation2D::~RigidTransformation2D (void) virtual
Destructor.
Definition at line 78 of file RigidTransformation2D.cpp.
 {
 }
Member Function Documentation
float RigidTransformation2D::getAngle (void) const
Returns the rotation's angle.
If the matrix is the reference, this call may require a re-orthogonalization of the matrix.
Returns
the rotation's angle
Definition at line 145 of file RigidTransformation2D.cpp.
References angle_.
Referenced by uriVL::Contour_F::applyTransformation(), uriVL::Contour_I::applyTransformation(), uriVL::Blob::applyTransformation(), and uriVL::Registration2D_ICP::registerPoints_lin_().
 {
         return angle_;
 }
float RigidTransformation2D::getTransX (void) const
Returns the x component of the translation.
Returns
x component of the translation
Definition at line 133 of file RigidTransformation2D.cpp.
References uriVL::Transformation2D::getMatrix().
Referenced by uriVL::Contour_F::applyTransformation(), uriVL::Contour_I::applyTransformation(), uriVL::Blob::applyTransformation(), and uriVL::Registration2D_ICP::registerPoints_lin_().
 {
         const float *const* mat = getMatrix();
     return mat[0][2];
 }
float RigidTransformation2D::getTransY (void) const
Returns the y component of the translation.
Returns
y component of the translation
Definition at line 139 of file RigidTransformation2D.cpp.
References uriVL::Transformation2D::getMatrix().
Referenced by uriVL::Contour_F::applyTransformation(), uriVL::Contour_I::applyTransformation(), uriVL::Blob::applyTransformation(), and uriVL::Registration2D_ICP::registerPoints_lin_().
 {
         const float *const* mat = getMatrix();
     return mat[1][2];
 }
void RigidTransformation2D::orthogonalizeMatrix_ (void) private virtual
Ensures that the transformation matrix is still orthogonal.
Definition at line 95 of file RigidTransformation2D.cpp.
References angle_, FAIL_CONDITION, uriVL::Transformation2D::getMatrix(), uriVL::kMatrixCalculationError, and uriVL::R_W_ACCESS.
 {
         float *const* mat = getMatrix(R_W_ACCESS);
     FAIL_CONDITION( mat[2][2] == 0.f,
                     kMatrixCalculationError,
                     "Cannot orthogonalize a matrix when scale element is 0");
     if (mat[2][2] != 1.f)
     {
         for (int i=0; i<2; i++)
             for (int j=0; j<3; j++)
                 mat[i][j] /= mat[2][2];
     }
     //  force the bottom row to be {0, 0, 1}
     mat[2][0] = mat[2][1] = 0.f; mat[2][2] = 1.f;
     //  If the determinant is  negative this is not a rigid transformation matrix
     FAIL_CONDITION( (mat[0][0]*mat[1][1] - mat[1][0] * mat[0][1]) <= 0,
                     kMatrixCalculationError,
                     "Matrix determinant <= 0: it cannot be a rigid transformation");
     //  Now I compute the 2x2 orthogonal matrix closest to the current matrix
     //  We expect the matrix to be very close to orthogonal, so basically we can
     //  look for the angle theta s.t. the upper-left part 2x2 submatrix looks like
     //  {{cos(theta), -sin(theta)}, {sin(theta), cos(theta)}}
     const float v0 = mat[0][0] + mat[1][1];
     const float v1 = mat[1][0] - mat[0][1];
     const float nv = sqrtf(v0*v0+v1*v1);
     const float cTheta = v0/nv;
     const float sTheta = v1/nv;
     mat[0][0] = mat[1][1] = cTheta;
     mat[0][1] = - (mat[1][0] = sTheta);
         angle_ = atan2f(sTheta, cTheta);
 }
void RigidTransformation2D::setAngle (float theAngle)
Sets the rotation's angle (in radians)
Parameters
theAngle the rotation's new angle
Definition at line 151 of file RigidTransformation2D.cpp.
References angle_, uriVL::Transformation2D::getMatrix(), and uriVL::R_W_ACCESS.
Referenced by uriVL::Registration2D_ICP::registerPoints_lin_().
 {
     angle_ = angle;
         float *const* mat = getMatrix(R_W_ACCESS);
     mat[2][0] = mat[2][1] = 0.f; mat[2][2] = 1.f;
         const float ct = cosf(angle_),
                                 st = sinf(angle_);
         mat[0][0] = mat[1][1] = ct;
         mat[0][1] = -st;
         mat[1][0] = st;
 }
void RigidTransformation2D::setMatrix (const float theMat[][3]) virtual
Assign a new matrix to this transformation.
The new matrix is now the reference for this transformation.
Parameters
theMat 3x3 transformation matrix
Reimplemented from uriVL::Transformation2D.
Definition at line 82 of file RigidTransformation2D.cpp.
References angle_, uriVL::Transformation2D::checkOrthogonality_(), FAIL_CONDITION, uriVL::kInvalidParameterError, and uriVL::Transformation2D::setMatrix().
 {
         Transformation2D::setMatrix(theMat);
     FAIL_CONDITION( !checkOrthogonality_(),
                     kInvalidParameterError,
                     "input matrix is not orthogonal in RigidTransformation2D::setMatrix");
         angle_ = atan2f(theMat[1][0], theMat[0][0]);
 }
void uriVL::RigidTransformation2D::setMatrixAsReference_ (void) private
Indicates that the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
Whenever redundant storage is used in this library, as with the transformation matrix and the Rotation2D and Translation2D objects of a RigidTransformation2D, a boolean variable us used to indicate which is the current "true" value.
void RigidTransformation2D::setTranslation (float tx, float ty)
Sets the translation component of this transformation.
Parameters
tx x translation component
ty x translation component
Definition at line 164 of file RigidTransformation2D.cpp.
References uriVL::Transformation2D::getMatrix(), and uriVL::R_W_ACCESS.
Referenced by uriVL::Registration2D_ICP::registerPoints_lin_(), and uriVL::Translation2D::Translation2D().
 {
         float *const* mat = getMatrix(R_W_ACCESS);
     mat[0][2] = tx;
         mat[1][2] = ty;
 }
void RigidTransformation2D::setTranslation (const float trans[])
Sets the translation component of this transformation.
Parameters
trans translation component
Definition at line 172 of file RigidTransformation2D.cpp.
References FAIL_CONDITION, uriVL::Transformation2D::getMatrix(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, and uriVL::R_W_ACCESS.
 {
         float *const* mat = getMatrix(R_W_ACCESS);
         try {
                 mat[0][2] = trans[0];
                 mat[1][2] = trans[1];
         }
         catch (...)
         {
                 FAIL_CONDITION( trans == NULL,
                                                 kNullParameterError,
                                                 "null array passed to RigidTransformation2D::setTranslation.");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid pointer passed to IRigidTransformation2D::setTranslation.");
         }
 }
void uriVL::RigidTransformation2D::updateMatrix_ (void) private
Updates the transformation matrix if it was not the reference, and if it is the reference, then re-orthogonalizes it.
Member Data Documentation
float uriVL::RigidTransformation2D::angle_ mutable private
Angle of the rotation component.
Definition at line 126 of file RigidTransformation2D.h.
Referenced by getAngle(), orthogonalizeMatrix_(), setAngle(), and setMatrix().
bool uriVL::RigidTransformation2D::angleIsReference_ private
Indicates whether the angle is the reference.
Definition at line 131 of file RigidTransformation2D.h.
Referenced by RigidTransformation2D().
The documentation for this class was generated from the following files:
RigidTransformation2D.h
RigidTransformation2D.cpp