URIVisionLibrary: uriVL::WarpMatchScoreFunctionND Class Reference
uriVL::WarpMatchScoreFunctionND Class Reference
Warping Matching Score Function nD.
#include <WarpMatchScoreFunctionND.h>
Public Member Functions
WarpMatchScoreFunctionND (BasePatternMatcher2DType matcherType, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Creates a new warping-based matching score function.
WarpMatchScoreFunctionND (PatternMatcher2D *matcher, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Creates a new warping-based matching score function.
WarpMatchScoreFunctionND (BasePatternMatcher2DType matcherType, ImageWarper *warper)
Creates a new warping-based matching score function.
WarpMatchScoreFunctionND (PatternMatcher2D *matcher, ImageWarper *warper)
Creates a new warping-based matching score function.
~WarpMatchScoreFunctionND (void)
destructor
void setPattern (const Pattern2D *newPattern)
Called to define the pattern used for subsequent matching score calculations.
void setPattern (const RasterImage *patImg, const Blob *patBlob=NULL)
Called to define the pattern used for subsequent matching score calculations.
void setImage (const RasterImage *img, const ImagePoint *matchPoint)
Called to define the image used for subsequent covariance calculations.
float ***const newWarpingGrid (void) const
Returns a new grid of points allocated at the grid dimensions of this object's warper and initialized as a regular rectangular grid.
float ***const getWarpingGrid (void) const
Returns a this object's private grid of warping points.
ImageWarper * getWarper (void) const
Returns a pointer to this object's warper.
RasterImage * getWarpedImage (void) const
Returns a pointer to the output image of the warper.
float * newVarArray (void) const
Returns a new 1D array of float properly sized to serve as an argument for this nD function.
void newVarArray (float *x) const
void getImageSuitableDimensions (int imgWidth, int imgHeight, int *lowImgWidth, int *lowImgHeight, int *highImgWidth, int *highImgHeight) const
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
float func (const float *x)
Evaluates the function at the nD point specified.
float func (const vector< float > &x)
Evaluates the function at the nD point specified.
Public Member Functions inherited from uriVL::FunctionND
FunctionND (int n)
Creates a new n-dimensional function defined over ]-infinity, +infinity[^n.
FunctionND (int n, const double *xMin, const double *xMax)
Creates a new n-dimensional function defined over the range specified.
virtual ~FunctionND (void)
Destructor.
virtual double func (const double *x) const =0
Evaluates the function at the nD point specified.
virtual double func (const std::vector< double > &x) const
Evaluates the function at the nD point specified.
virtual double func (const ColumnVector *x) const
Evaluates the function at the nD point specified.
virtual void gradient (const double *x, double *gradVect) const
Evaluates the gradient of the function at the point specified.
virtual void gradient (const ColumnVector *x, ColumnVector *gradVect) const
Evaluates the gradient of the function at the point specified.
const ColumnVector * gradient (const ColumnVector *x) const
Evaluates the gradient of the function at the point specified.
virtual void hessian (const double *x, double *const *hessianMat) const
Evaluates the Hessian matrix of the function at the point specified.
virtual void hessian (const ColumnVector *x, Matrix *hess) const
Evaluates the gradient of the function at the point specified.
const Matrix * hessian (const ColumnVector *x) const
Evaluates the gradient of the function at the point specified.
virtual bool gradientIsImplemented (void) const =0
Indicates whether the function implements its own gradient function.
virtual bool hessianIsImplemented (void) const =0
Indicates whether the function implements its own Hessian function.
bool isDefinedAt (const double *x) const
Indicates whther a point is within the domain of definition of this function.
bool isDefinedAt (const std::vector< double > &x) const
Indicates whther a point is within the domain of definition of this function.
bool isDefinedAt (const ColumnVector *x) const
Indicates whther a point is within the domain of definition of this function.
const double * getLowerBound (void) const
Returns the lower bounds of this function's domain of definition.
const double * getUpperBound (void) const
Returns the upper bounds of this function's domain of definition.
int getDimension (void) const
Returns the dimension of this function's domain.
Protected Member Functions
void deleteGrid_ (void)
Deletes the grid of warping points stored by this object.
Static Protected Member Functions
static int functionDim_ (int gridRows, int gridCols, InnerWarpingMode innerMode=INNER_FREE, BorderWarpingMode outerMode=BORDER_FREE)
Computes the number of active grid point coordinates for the warping mode and grid dimensions chosen.
Protected Attributes
PatternMatcher2D * matcher_
Pattern matcher (of one of the basic types) used by this warping-based matcher.
bool matcherIsLocal_
Indicates whether _matcher is "owned" by this object or was passed to the constructor.
ImageWarper * warper_
warper
bool warperIsLocal_
Indicates whether _warper is "owned" by this object or was passed to the constructor.
float *** grid_
Grid point coordinates used to pass warping commands to the warper.
InnerWarpingMode innerMode_
The warper's inner warping mode (stored for speedier func call)
BorderWarpingMode outerMode_
The warper's border warping mode (stored for speedier func call)
int gridRows_
number of rows of the grid (stored for speedier func call)
int gridCols_
number of cols of the grid (stored for speedier func call)
const RasterImage * imgIn_
input image (for warping)
RasterImage * imgOut_
output image (for correlation)
Pattern2D * pat_
pattern for correlation with img_
BaseRasterType patRasterType_
Base raster type of the pattern.
Pattern2DMatchRecord * matchRecord_
Match record used for the results of the matcher.
float * patScale1D_
stores a 1D array of "pattern scaling factor" data needed by some pattern matchers
float * imgScale1D_
stores a 1D array of "image scaling factor" data needed by some pattern matchers
float ** patScale2D_
stores a 2D array of "pattern scaling factor" data needed by some pattern matchers
float ** imgScale2D_
stores a 2D array of "image scaling factor" data needed by some pattern matchers
float * imgScore1D_
stores a 1D array of "image score" data needed by some pattern matchers
float ** imgScore2D_
stores a 2D array of "image score" data needed by some pattern matchers
int matchPointX_
x coordinate of match point
int matchPointY_
y coordinate of match point
Protected Attributes inherited from uriVL::FunctionND
int nDim_
Dimension of the source space of this function.
bool isBounded_
Is set true when bounds xMin_ and xMax_ were set for the domain of definition of the function.
double * xMin_
nDim-sized array of lower bounds of the domain of definition.
double * xMax_
nDim-sized array of upper bounds of the domain of definition.
double * xLocal_
Array that stores a copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function)
double * xLocal2_
Array that stores another copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function and derivative)
Detailed Description
Warping Matching Score Function nD.
This class exists for doing deformable (warping-based) pattern matching. It allows the user to define a reference pattern (image + blob) and a search image, and then compute the matching score for a given warping configuration (nD array of warping point coordinates)
Definition at line 44 of file WarpMatchScoreFunctionND.h.
Constructor & Destructor Documentation
WarpMatchScoreFunctionND::WarpMatchScoreFunctionND (BasePatternMatcher2DType matcherType, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE)
Creates a new warping-based matching score function.
'
Parameters
matcherType type of basic matcher this one is based on
warperType type of image warper used by this object
gridRows number of rows of the warping grid
gridCols number of columns of the warping grid
innerMode grid inner warping mode for this warper
outerMode grid outer warping mode for this warper
Definition at line 26 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, grid_, gridCols_, gridRows_, imgIn_, imgOut_, imgScale1D_, imgScale2D_, imgScore1D_, imgScore2D_, innerMode_, uriVL::kInvalidParameterError, matcher_, matcherIsLocal_, matchRecord_, outerMode_, pat_, patScale1D_, patScale2D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_PART_CORR, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, uriVL::ImageWarper::setGrid(), warper_, and warperIsLocal_.
             : FunctionND(functionDim_(gridRows, gridCols, innerMode, outerMode))
 {
     switch(matcherType)
     {
         case PATTERN_MATCHER_2D_CORR:
             matcher_ = new PatternMatcher2D_corr();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_PART_CORR:
             matcher_ = new PatternMatcher2D_partCorr();
             matchRecord_ = new Pattern2DMatchRecord_part();
             patScale1D_ = NULL;
             imgScale1D_ = NULL;
             imgScore1D_ = NULL;
             patScale2D_ = new float*[3];
             imgScale2D_ = new float*[3];
             imgScore2D_ = new float*[3];
             for (int i=0; i<3; i++)
             {
                 patScale2D_[i] = new float[5];
                 imgScale2D_[i] = new float[5];
                 imgScore2D_[i] = new float[5];
             }
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             matcher_ = new PatternMatcher2D_scaledDiff();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             matcher_ = new PatternMatcher2D_medianDiff();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     matcherIsLocal_ = true;
     warper_ = new ImageWarper_GL(innerMode, outerMode);
     warper_->setGrid(gridRows, gridCols);
     outerMode_ = outerMode;
     innerMode_ = innerMode;
     gridRows_ = gridRows;
     gridCols_ = gridCols;
     grid_ = NULL;
     warperIsLocal_ = true;
     //  the input image and pattern are not defined yet
     imgIn_ = imgOut_ = NULL;
     pat_ = NULL;
 }
WarpMatchScoreFunctionND::WarpMatchScoreFunctionND (PatternMatcher2D * matcher, ImageWarperType warperType, int gridRows, int gridCols, InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE)
Creates a new warping-based matching score function.
'
Parameters
predefined basic pattern matcher (e.g. correlation) to use
warperType type of image warper used by this object
gridRows number of rows of the warping grid
gridCols number of columns of the warping grid
innerMode grid inner warping mode for this warper
outerMode grid outer warping mode for this warper
Definition at line 191 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, uriVL::PatternMatcher2D::getBaseMatcherType(), grid_, gridCols_, gridRows_, imgIn_, imgOut_, imgScale1D_, imgScale2D_, imgScore1D_, imgScore2D_, innerMode_, uriVL::kInvalidParameterError, matcher_, matcherIsLocal_, matchRecord_, outerMode_, pat_, patScale1D_, patScale2D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_PART_CORR, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, uriVL::ImageWarper::setGrid(), warper_, and warperIsLocal_.
             : FunctionND(functionDim_(gridRows, gridCols, innerMode, outerMode))
 {
     matcher_ = matcher;
     switch(matcher->getBaseMatcherType())
     {
         case PATTERN_MATCHER_2D_CORR:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_PART_CORR:
             matchRecord_ = new Pattern2DMatchRecord_part();
             patScale1D_ = NULL;
             imgScale1D_ = NULL;
             imgScore1D_ = NULL;
             patScale2D_ = new float*[3];
             imgScale2D_ = new float*[3];
             imgScore2D_ = new float*[3];
             for (int i=0; i<3; i++)
             {
                 patScale2D_[i] = new float[5];
                 imgScale2D_[i] = new float[5];
                 imgScore2D_[i] = new float[5];
             }
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     matcherIsLocal_ = false;
     warper_ = new ImageWarper_GL(innerMode, outerMode);
     warper_->setGrid(gridRows, gridCols);
     outerMode_ = outerMode;
     innerMode_ = innerMode;
     gridRows_ = gridRows;
     gridCols_ = gridCols;
     warperIsLocal_ = true;
     grid_ = NULL;
     //  the input image and pattern are not defined yet
     imgIn_ = imgOut_ = NULL;
     pat_ = NULL;
 }
WarpMatchScoreFunctionND::WarpMatchScoreFunctionND (BasePatternMatcher2DType matcherType, ImageWarper * warper)
Creates a new warping-based matching score function.
'
Parameters
matcherType type of basic matcher this one is based on
predefined image warper (e.g. GL-based) to use
Definition at line 110 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, uriVL::ImageWarper::getBorderWarpingMode(), uriVL::ImageWarper::getInnerWarpingMode(), uriVL::ImageWarper::getNbGridCols(), uriVL::ImageWarper::getNbGridRows(), grid_, gridCols_, gridRows_, imgIn_, imgOut_, imgScale1D_, imgScale2D_, imgScore1D_, imgScore2D_, innerMode_, uriVL::kInvalidParameterError, matcher_, matcherIsLocal_, matchRecord_, outerMode_, pat_, patScale1D_, patScale2D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_PART_CORR, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, warper_, and warperIsLocal_.
             : FunctionND(functionDim_(warper->getNbGridRows(), warper->getNbGridCols(),
                                       warper->getInnerWarpingMode(),
                                       warper->getBorderWarpingMode()))
 {
     switch(matcherType)
     {
         case PATTERN_MATCHER_2D_CORR:
             matcher_ = new PatternMatcher2D_corr();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_PART_CORR:
             matcher_ = new PatternMatcher2D_partCorr();
             matchRecord_ = new Pattern2DMatchRecord_part();
             patScale1D_ = NULL;
             imgScale1D_ = NULL;
             imgScore1D_ = NULL;
             patScale2D_ = new float*[3];
             imgScale2D_ = new float*[3];
             imgScore2D_ = new float*[3];
             for (int i=0; i<3; i++)
             {
                 patScale2D_[i] = new float[5];
                 imgScale2D_[i] = new float[5];
                 imgScore2D_[i] = new float[5];
             }
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             matcher_ = new PatternMatcher2D_scaledDiff();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             matcher_ = new PatternMatcher2D_medianDiff();
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     matcherIsLocal_ = true;
     warper_ = warper;
     innerMode_ = warper->getInnerWarpingMode();
     outerMode_ = warper->getBorderWarpingMode();
     gridRows_ = warper->getNbGridRows();
     gridCols_ = warper->getNbGridCols();
     grid_ = NULL;
     warperIsLocal_ = false;
     //  the input image and pattern are not defined yet
     imgIn_ = imgOut_ = NULL;
     pat_ = NULL;
 }
WarpMatchScoreFunctionND::WarpMatchScoreFunctionND (PatternMatcher2D * matcher, ImageWarper * warper)
Creates a new warping-based matching score function.
Parameters
predefined basic pattern matcher (e.g. correlation) to use
predefined image warper (e.g. GL-based) to use
Definition at line 271 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, uriVL::PatternMatcher2D::getBaseMatcherType(), uriVL::ImageWarper::getBorderWarpingMode(), uriVL::ImageWarper::getInnerWarpingMode(), uriVL::ImageWarper::getNbGridCols(), uriVL::ImageWarper::getNbGridRows(), grid_, gridCols_, gridRows_, imgIn_, imgOut_, imgScale1D_, imgScale2D_, imgScore1D_, imgScore2D_, innerMode_, uriVL::kInvalidParameterError, matcher_, matcherIsLocal_, matchRecord_, outerMode_, pat_, patScale1D_, patScale2D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_PART_CORR, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, warper_, and warperIsLocal_.
             : FunctionND(functionDim_(warper->getNbGridRows(), warper->getNbGridCols(),
                                      warper->getInnerWarpingMode(),
                                      warper->getBorderWarpingMode()))
 {
     matcher_ = matcher;
     switch(matcher->getBaseMatcherType())
     {
         case PATTERN_MATCHER_2D_CORR:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_PART_CORR:
             matchRecord_ = new Pattern2DMatchRecord_part();
             patScale1D_ = NULL;
             imgScale1D_ = NULL;
             imgScore1D_ = NULL;
             patScale2D_ = new float*[3];
             imgScale2D_ = new float*[3];
             imgScore2D_ = new float*[3];
             for (int i=0; i<3; i++)
             {
                 patScale2D_[i] = new float[5];
                 imgScale2D_[i] = new float[5];
                 imgScore2D_[i] = new float[5];
             }
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             matchRecord_ = new Pattern2DMatchRecord();
             patScale1D_ = new float[3];
             imgScale1D_ = new float[3];
             imgScore1D_ = new float[3];
             patScale2D_ = NULL;
             imgScale2D_ = NULL;
             imgScore2D_ = NULL;
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     matcherIsLocal_ = false;
     warper_ = warper;
     innerMode_ = warper->getInnerWarpingMode();
     outerMode_ = warper->getBorderWarpingMode();
     gridRows_ = warper->getNbGridRows();
     gridCols_ = warper->getNbGridCols();
     warperIsLocal_ = false;
     grid_ = NULL;
     //  the input image and pattern are not defined yet
     imgIn_ = imgOut_ = NULL;
     pat_ = NULL;
 }
WarpMatchScoreFunctionND::~WarpMatchScoreFunctionND (void)
destructor
Definition at line 349 of file WarpMatchScoreFunctionND.cpp.
References deleteGrid_(), grid_, imgScale1D_, imgScale2D_, imgScore1D_, imgScore2D_, matcher_, matcherIsLocal_, pat_, patScale1D_, patScale2D_, warper_, and warperIsLocal_.
 {
     if (warperIsLocal_)
         delete warper_;
     if (matcherIsLocal_)
         delete matcher_;
     if (grid_ != NULL)
         deleteGrid_();
     if (pat_ != NULL)
         delete pat_;
     if (patScale1D_ != NULL)
         delete []patScale1D_;
     if (imgScale1D_ != NULL)
         delete []patScale1D_;
     if (imgScore1D_ != NULL)
         delete []patScale1D_;
     if (patScale2D_ != NULL)
     {
         for (int i=0; i<3; i++)
             delete []patScale2D_[i];
         delete []patScale2D_;
     }
     if (imgScale2D_ != NULL)
     {
         for (int i=0; i<3; i++)
             delete []imgScale2D_[i];
         delete []imgScale2D_;
     }
     if (imgScore2D_ != NULL)
     {
         for (int i=0; i<3; i++)
             delete []imgScore2D_[i];
         delete []imgScore2D_;
     }
 }
Member Function Documentation
void WarpMatchScoreFunctionND::deleteGrid_ (void) protected
Deletes the grid of warping points stored by this object.
Definition at line 918 of file WarpMatchScoreFunctionND.cpp.
References grid_, and gridRows_.
Referenced by setImage(), and ~WarpMatchScoreFunctionND().
 {
     for (int i=0; i<gridRows_; i++)
         delete []grid_[i];
     delete []grid_;
     grid_ = NULL;
 }
float WarpMatchScoreFunctionND::func (const float * x)
Evaluates the function at the nD point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Definition at line 642 of file WarpMatchScoreFunctionND.cpp.
References uriVL::BORDER_FIXED, uriVL::BORDER_FREE, uriVL::BORDER_INWARD, uriVL::BORDER_SLIDE, FAIL_CONDITION, uriVL::PatternMatcher2D::getBaseMatcherType(), grid_, gridCols_, gridRows_, imgOut_, imgScale1D_, imgScore1D_, uriVL::kGrayRaster, uriVL::kInvalidParameterError, matcher_, matchPointX_, matchPointY_, outerMode_, patRasterType_, patScale1D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_PART_CORR, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, uriVL::ImageWarper::warp(), and warper_.
 {
     int k = 0;
     //  copy data from x to grid_
     switch(outerMode_)
     {
         case BORDER_FREE:
         case BORDER_INWARD:
             for (int i=0; i<gridRows_; i++)
                 for (int j=0; j<gridCols_; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
             break;
         case BORDER_SLIDE:
             //   on top row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 grid_[0][j][0] = x[k++];
             for (int i=1; i<gridRows_-1; i++)
             {
                 //  points on the left border can only slide in y direction
                 grid_[i][0][1] = x[k++];
                 //  inner points can move freely
                 for (int j=0; j<gridCols_; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
                 //  points on the right border can only slide in y direction
                 grid_[i][gridCols_-1][1] = x[k++];
             }
             //   on bottom row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 grid_[gridRows_-1][j][0] = x[k++];
             break;
         case BORDER_FIXED:
             for (int i=1; i<gridRows_-1; i++)
                 for (int j=1; j<gridCols_-1; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     warper_->warp(grid_);
     //  Finally calculate the matching score
     float score = 0.f;
     switch(matcher_->getBaseMatcherType())
     {
         case PATTERN_MATCHER_2D_CORR:
                 if (patRasterType_ == kGrayRaster)
             {
                     ((PatternMatcher2D_corr *)matcher_)->covariance((RasterImage_gray* )imgOut_,
                                                                                                                 matchPointX_,
                                                                                                                 matchPointY_,
                                                                                                                 imgScore1D_,
                                                                     imgScale1D_);
                 score = -imgScore1D_[0] * imgScale1D_[0] * patScale1D_[0];
                 }
                 else
             {
                 ((PatternMatcher2D_corr *)matcher_)->covariance((RasterImage_RGBa* )imgOut_,
                                                                                                                 matchPointX_,
                                                                                                                 matchPointY_,
                                                                                                                 imgScore1D_,
                                                                 imgScale1D_);
                     score = -1.f / 3.f * (imgScore1D_[0] * imgScale1D_[0] * patScale1D_[0]
                                                         + imgScore1D_[1] * imgScale1D_[1] * patScale1D_[1]
                                                         + imgScore1D_[2] * imgScale1D_[2] * patScale1D_[2]);
             }
             break;
         case PATTERN_MATCHER_2D_PART_CORR:  //  not ready yet
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
     }
     return score;
 }
float WarpMatchScoreFunctionND::func (const vector< float > & x)
Evaluates the function at the nD point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Definition at line 760 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
 {
     FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "Not implemented yet");
     float score = 0.f;
 /*
     int k = 0;
     //  copy data from x to grid_
     switch(outerMode_)
     {
         case BORDER_FREE:
         case BORDER_INWARD:
             for (int i=0; i<gridRows_; i++)
                 for (int j=0; j<gridCols_; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
             break;
         case BORDER_SLIDE:
             //   on top row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 grid_[0][j][0] = x[k++];
             for (int i=1; i<gridRows_-1; i++)
             {
                 //  points on the left border can only slide in y direction
                 grid_[i][0][1] = x[k++];
                 //  inner points can move freely
                 for (int j=0; j<gridCols_; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
                 //  points on the right border can only slide in y direction
                 grid_[i][gridCols_-1][1] = x[k++];
             }
             //   on bottom row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 grid_[gridRows_-1][j][0] = x[k++];
             break;
         case BORDER_FIXED:
             for (int i=1; i<gridRows_-1; i++)
                 for (int j=1; j<gridCols_-1; j++)
                 {
                     grid_[i][j][0] = x[k++];
                     grid_[i][j][1] = x[k++];
                 }
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
     warper_->warp(grid_);
     //  Finally calculate the matching score
     float score = 0.f;
     switch(matcher_->getBaseMatcherType())
     {
         case PATTERN_MATCHER_2D_CORR:
                 if (patRasterType_ == kGrayRaster)
             {
                     ((PatternMatcher2D_corr *)matcher_)->covariance((RasterImage_gray* )imgOut_,
                                                                                                                 matchPointX_,
                                                                                                                 matchPointY_,
                                                                                                                 imgScore1D_,
                                                                     imgScale1D_);
                 score = -imgScore1D_[0] * imgScale1D_[0] * patScale1D_[0];
                 }
                 else
             {
                 ((PatternMatcher2D_corr *)matcher_)->covariance((RasterImage_RGBa* )imgOut_,
                                                                                                                 matchPointX_,
                                                                                                                 matchPointY_,
                                                                                                                 imgScore1D_,
                                                                 imgScale1D_);
                     score = -1.f / 3.f * (imgScore1D_[0] * imgScale1D_[0] * patScale1D_[0]
                                                         + imgScore1D_[1] * imgScale1D_[1] * patScale1D_[1]
                                                         + imgScore1D_[2] * imgScale1D_[2] * patScale1D_[2]);
             }
             break;
         case PATTERN_MATCHER_2D_PART_CORR:  //  not ready yet
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         case PATTERN_MATCHER_2D_MEDIAN:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Not implemented yet");
             break;
     }
 */
     return score;
 }
int WarpMatchScoreFunctionND::functionDim_ (int gridRows, int gridCols, InnerWarpingMode innerMode = INNER_FREE, BorderWarpingMode outerMode = BORDER_FREE) static protected
Computes the number of active grid point coordinates for the warping mode and grid dimensions chosen.
Definition at line 889 of file WarpMatchScoreFunctionND.cpp.
References uriVL::BORDER_FIXED, uriVL::BORDER_FREE, uriVL::BORDER_INWARD, uriVL::BORDER_SLIDE, FAIL_CONDITION, and uriVL::kNoCode.
 {
     int n = 2 * gridRows * gridCols;
     switch(outerMode)
     {
         case BORDER_SLIDE:
             //  the 4 corners are fixed and the other border points can only
             //  change 1 coordinate
             n -= 4*2 + 2*(gridRows-2) + 2*(gridCols-2);
             break;
         case BORDER_FIXED:
             //  the 4 corners and all other border points are fixed
             n -= 4*2 + 4*(gridRows-2) + 4*(gridCols-2);
             break;
         case BORDER_FREE:
         case BORDER_INWARD:
             FAIL_CONDITION( true,
                                                         kNoCode,
                                                         "Unhandled case in a switch statement");
     }
     return n;
 }
void WarpMatchScoreFunctionND::getImageSuitableDimensions (int imgWidth, int imgHeight, int * lowImgWidth, int * lowImgHeight, int * highImgWidth, int * highImgHeight) const
Computes the image dimensions that the warper can afford that are closest to the ones sent by the user.
Some warpers require specific image dimensions/ratios (e.g. a GL warper only takes 2^n x 2^n images). Furthermore, QuickTime GraphWorld rasters are padded on some platforms. The user should therefore first call imageEffectiveDimensions with desired image dimensions, and then create the image at the corresponding "effective" dimensions specified by that function.
If you want to warp an image, it is therefore recommended that you check what are the closest suitable dimensions for the type of warper you are using.
Parameters
imgWidth input image width
imgHeight input image height
lowImgWidth closest lower suitable width
lowImgHeight closest lower suitable height
highImgWidth closest higher suitable width
highImgHeight closest higher suitable height
Definition at line 615 of file WarpMatchScoreFunctionND.cpp.
References uriVL::ImageWarper::getImageSuitableDimensions(), and warper_.
Referenced by uriVL::PatternMatcher2D_warp::getImageSuitableDimensions().
 {
     warper_->getImageSuitableDimensions(imgWidth, imgHeight, lowImgWidth, lowImgHeight,
                                         highImgWidth, highImgHeight);
 }
RasterImage * WarpMatchScoreFunctionND::getWarpedImage (void) const
Returns a pointer to the output image of the warper.
Definition at line 631 of file WarpMatchScoreFunctionND.cpp.
References imgOut_.
Referenced by uriVL::PatternMatcher2D_warp::getWarpedImage().
 {
     return imgOut_;
 }
ImageWarper * WarpMatchScoreFunctionND::getWarper (void) const
Returns a pointer to this object's warper.
Returns
a pointer to this object's warper
Definition at line 626 of file WarpMatchScoreFunctionND.cpp.
References warper_.
 {
         return warper_;
 }
float ***const WarpMatchScoreFunctionND::getWarpingGrid (void) const
Returns a this object's private grid of warping points.
This function should only be used for debugging purposes, to visualize the allocated at the grid dimensions of this warper and initialized as a regular rectangular grid. This function can only be called after the grid dimensions and input image have been set. The user is responsible for deleting this grid when it is not needed anymore.
Returns
a new warping grid to be used with this warper
Definition at line 468 of file WarpMatchScoreFunctionND.cpp.
References grid_.
Referenced by uriVL::PatternMatcher2D_warp::match().
 {
     return grid_;
 }
float * WarpMatchScoreFunctionND::newVarArray (void) const
Returns a new 1D array of float properly sized to serve as an argument for this nD function.
It is the user's responsibility to delete this array when it is not needed anymore.
Returns
a new array of float to pass as parameter to func
Definition at line 458 of file WarpMatchScoreFunctionND.cpp.
References uriVL::FunctionND::getDimension().
Referenced by uriVL::PatternMatcher2D_warp::PatternMatcher2D_warp().
 {
     float* x = new float[this->getDimension()];
     newVarArray(x);
     return x;
 }
void WarpMatchScoreFunctionND::newVarArray (float * x) const
Definition at line 399 of file WarpMatchScoreFunctionND.cpp.
References uriVL::BORDER_FIXED, uriVL::BORDER_FREE, uriVL::BORDER_INWARD, uriVL::BORDER_SLIDE, FAIL_CONDITION, grid_, gridCols_, gridRows_, uriVL::kInvalidParameterError, and outerMode_.
 {
     int k = 0;
     //  copy data from x to grid_
     switch(outerMode_)
     {
         case BORDER_FREE:
         case BORDER_INWARD:
             for (int i=0; i<gridRows_; i++)
                 for (int j=0; j<gridCols_; j++)
                 {
                     x[k++] = grid_[i][j][0];
                     x[k++] = grid_[i][j][1];
                 }
             break;
         case BORDER_SLIDE:
             //   on top row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 x[k++] = grid_[0][j][0];
             for (int i=1; i<gridRows_-1; i++)
             {
                 //  points on the left border can only slide in y direction
                 x[k++] = grid_[i][0][1];
                 //  inner points can move freely
                 for (int j=0; j<gridCols_; j++)
                 {
                     x[k++] = grid_[i][j][0];
                     x[k++] = grid_[i][j][1];
                 }
                 //  points on the right border can only slide in y direction
                 x[k++] = grid_[i][gridCols_-1][1];
             }
             //   on bottom row only x coordinates change (slide)
             for (int j=1; j<gridCols_-1; j++)
                 x[k++] = grid_[gridRows_-1][j][0];
             break;
         case BORDER_FIXED:
             for (int i=1; i<gridRows_-1; i++)
                 for (int j=1; j<gridCols_-1; j++)
                 {
                     x[k++] = grid_[i][j][0];
                     x[k++] = grid_[i][j][1];
                 }
             break;
         default:
             FAIL_CONDITION( true,
                             kInvalidParameterError,
                             "Unknown base pattern matcher type");
             break;
     }
 }
float ***const WarpMatchScoreFunctionND::newWarpingGrid (void) const
Returns a new grid of points allocated at the grid dimensions of this object's warper and initialized as a regular rectangular grid.
This function can only be called after the grid dimensions and input image have been set. The user is responsible for deleting this grid when it is not needed anymore.
Returns
a new warping grid to be used with this warper
Definition at line 474 of file WarpMatchScoreFunctionND.cpp.
References uriVL::ImageWarper::newWarpingGrid(), and warper_.
Referenced by uriVL::PatternMatcher2D_warp::computeGridBounds_().
 {
     return warper_->newWarpingGrid();
 }
void WarpMatchScoreFunctionND::setImage (const RasterImage * img, const ImagePoint * matchPoint)
Called to define the image used for subsequent covariance calculations.
Currently, the image's base raster type should match that of the pattern (which implies that the pattern should have been set before this function is called)
Parameters
img the image in which we seek a best match for the pattern
matchPoint origin of the search
See also
setPattern
Definition at line 546 of file WarpMatchScoreFunctionND.cpp.
References deleteGrid_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageWarper::getImageSuitableDimensions(), uriVL::DrawableObject2D::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), grid_, imgIn_, imgOut_, uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kNoninitializedObjectError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, matchPointX_, matchPointY_, uriVL::ImageWarper::newWarpingGrid(), pat_, patRasterType_, uriVL::ImageWarper::setImages(), uriVL::DrawableObject2D::setValidRect(), and warper_.
Referenced by uriVL::PatternMatcher2D_warp::setImage().
 {
     FAIL_CONDITION( pat_ == NULL,
                     kNoninitializedObjectError,
                     "A pattern must be set before the input image");
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "null search image assigned to WarpMatchScoreFunctionND");
     //  we find out which image dimensions are recommended by the warper (closest
     //  to the input image's dimensions)
     int imgHeight = img->getHeight(),
         imgWidth = img->getWidth();
     int loWidth, hiWidth, loHeight, hiHeight;
     warper_->getImageSuitableDimensions(imgWidth, imgHeight, &loWidth, &loHeight,
                                         &hiWidth, &hiHeight);
     //  if the dimensions of the image are not equal to the low or high fits, we
     //  just bail out
     FAIL_CONDITION( ((imgWidth != loWidth) && (imgWidth != hiWidth)) ||
                     ((imgHeight != loHeight) && (imgHeight != hiHeight)),
                     kInvalidParameterError,
                     "Image not properly sized for the warper");
     imgIn_ = img;
     bool createNewImage = false;
     //  if imgOut_ was null we allocate it
     if (imgOut_ == NULL)
         createNewImage = true;
     //  if imgOut_ had a different type, or different dimensions than img, we must delete it first
     //
     else if ((img->getBaseRasterType() != imgOut_->getBaseRasterType()) ||
              (imgWidth != imgOut_->getWidth()) ||
              (imgHeight != imgOut_->getHeight()))
     {
         delete imgOut_;
         createNewImage = true;
     }
     if (createNewImage)
     {
         switch (patRasterType_)
         {
             case kGrayRaster:
                 imgOut_ = new RasterImage_gray(imgHeight, imgWidth);
                 break;
             case kRGBa32Raster:
                 imgOut_ = new RasterImage_RGBa(imgHeight, imgWidth);
                 break;
             default:
                 break;
         }
         imgOut_->setValidRect(0, 0, imgWidth, imgHeight);
     }
     //  finally we assing the input and output images to the warper
     warper_->setImages(imgIn_, imgOut_);
     //  we need an array of grid point coordinates to pass warping commands
     if (grid_ != NULL)
         deleteGrid_();
     grid_ = warper_->newWarpingGrid();
     matchPointX_ = matchPoint->getX();
     matchPointY_ = matchPoint->getY();
 }
void WarpMatchScoreFunctionND::setPattern (const Pattern2D * newPattern)
Called to define the pattern used for subsequent matching score calculations.
Parameters
newPattern new pattern
Definition at line 485 of file WarpMatchScoreFunctionND.cpp.
References FAIL_CONDITION, uriVL::Pattern2D::getBlob(), uriVL::Pattern2D::getPattern(), and uriVL::kNullParameterError.
Referenced by uriVL::PatternMatcher2D_warp::setPattern().
 {
     FAIL_CONDITION(     pat == NULL,
                     kNullParameterError,
                     "NULL pattern sent to PatternMatcher2D_corr::setPattern");
     setPattern(pat->getPattern(), pat->getBlob());
 }
void WarpMatchScoreFunctionND::setPattern (const RasterImage * patImg, const Blob * patBlob = NULL)
Called to define the pattern used for subsequent matching score calculations.
Parameters
patImg the rectangular pattern we are seaking
patBlob the blob that defines the actual geometry of the pattern
Definition at line 493 of file WarpMatchScoreFunctionND.cpp.
References uriVL::Pattern2D::assignPattern(), FAIL_CONDITION, uriVL::PatternMatcher2D::getBaseMatcherType(), uriVL::RasterImage::getBaseRasterType(), imgIn_, uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, matcher_, pat_, patRasterType_, patScale1D_, uriVL::PATTERN_MATCHER_2D_CORR, uriVL::PATTERN_MATCHER_2D_MEDIAN, uriVL::PATTERN_MATCHER_2D_SCALED_DIFF, and uriVL::PatternMatcher2D::setPattern().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL image sent as parameter to PatternMatcher2D_corr::setPattern");
     BaseRasterType patRasterType = patImg->getBaseRasterType();
     FAIL_CONDITION(     (patRasterType != kGrayRaster) && (patRasterType != kRGBa32Raster),
                     kInvalidParameterError,
                     "WarpMatchScoreFunctionND::setPattern only takes gray and RGBa images");
     FAIL_CONDITION( (imgIn_ != NULL) &&  (imgIn_->getBaseRasterType() != patRasterType),
                     kInvalidParameterError,
                     "Pattern and image base raster types don't match");
         patRasterType_ = patRasterType;
     matcher_->setPattern(patImg, patBlob);
     if (pat_ == NULL)
         pat_ = new Pattern2D();
     pat_->assignPattern(patImg, patBlob);
     switch (matcher_->getBaseMatcherType())
     {
         case PATTERN_MATCHER_2D_CORR:
                 if (patRasterType_ == kGrayRaster)
                     ((PatternMatcher2D_corr *)matcher_)->patternCorrScale((RasterImage_gray* )patImg, patBlob, patScale1D_);
                 else
                     ((PatternMatcher2D_corr *)matcher_)->patternCorrScale((RasterImage_RGBa* )patImg, patBlob, patScale1D_);
             break;
 /*
         case PATTERN_MATCHER_2D_PART_CORR:
                 if (patRasterType_ == kGrayRaster)
                     ((PatternMatcher2D_partCorr *)matcher_)->patternCorrScale((RasterImage_gray* )patImg, patBlob, patScale2D_);
                 else
                     ((PatternMatcher2D_partCorr *)matcher_)->patternCorrScale((RasterImage_RGBa* )patImg, patBlob, patScale1D_);
             break;
 */
         case PATTERN_MATCHER_2D_MEDIAN:
             break;
         case PATTERN_MATCHER_2D_SCALED_DIFF:
             break;
         default:
             break;
     }
 }
Member Data Documentation
float*** uriVL::WarpMatchScoreFunctionND::grid_ protected
Grid point coordinates used to pass warping commands to the warper.
Definition at line 225 of file WarpMatchScoreFunctionND.h.
Referenced by deleteGrid_(), func(), getWarpingGrid(), newVarArray(), setImage(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
int uriVL::WarpMatchScoreFunctionND::gridCols_ protected
number of cols of the grid (stored for speedier func call)
Definition at line 242 of file WarpMatchScoreFunctionND.h.
Referenced by func(), newVarArray(), and WarpMatchScoreFunctionND().
int uriVL::WarpMatchScoreFunctionND::gridRows_ protected
number of rows of the grid (stored for speedier func call)
Definition at line 238 of file WarpMatchScoreFunctionND.h.
Referenced by deleteGrid_(), func(), newVarArray(), and WarpMatchScoreFunctionND().
const RasterImage* uriVL::WarpMatchScoreFunctionND::imgIn_ protected
input image (for warping)
Definition at line 247 of file WarpMatchScoreFunctionND.h.
Referenced by setImage(), setPattern(), and WarpMatchScoreFunctionND().
RasterImage* uriVL::WarpMatchScoreFunctionND::imgOut_ protected
output image (for correlation)
Definition at line 251 of file WarpMatchScoreFunctionND.h.
Referenced by func(), getWarpedImage(), setImage(), and WarpMatchScoreFunctionND().
float* uriVL::WarpMatchScoreFunctionND::imgScale1D_ protected
stores a 1D array of "image scaling factor" data needed by some pattern matchers
Definition at line 274 of file WarpMatchScoreFunctionND.h.
Referenced by func(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
float** uriVL::WarpMatchScoreFunctionND::imgScale2D_ protected
stores a 2D array of "image scaling factor" data needed by some pattern matchers
Definition at line 284 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
float* uriVL::WarpMatchScoreFunctionND::imgScore1D_ protected
stores a 1D array of "image score" data needed by some pattern matchers
Definition at line 289 of file WarpMatchScoreFunctionND.h.
Referenced by func(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
float** uriVL::WarpMatchScoreFunctionND::imgScore2D_ protected
stores a 2D array of "image score" data needed by some pattern matchers
Definition at line 294 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
InnerWarpingMode uriVL::WarpMatchScoreFunctionND::innerMode_ protected
The warper's inner warping mode (stored for speedier func call)
Definition at line 229 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND().
PatternMatcher2D* uriVL::WarpMatchScoreFunctionND::matcher_ protected
Pattern matcher (of one of the basic types) used by this warping-based matcher.
See also
BasePatternMatcher2DType
Definition at line 206 of file WarpMatchScoreFunctionND.h.
Referenced by func(), setPattern(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
bool uriVL::WarpMatchScoreFunctionND::matcherIsLocal_ protected
Indicates whether _matcher is "owned" by this object or was passed to the constructor.
Definition at line 211 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
int uriVL::WarpMatchScoreFunctionND::matchPointX_ protected
x coordinate of match point
Definition at line 298 of file WarpMatchScoreFunctionND.h.
Referenced by func(), and setImage().
int uriVL::WarpMatchScoreFunctionND::matchPointY_ protected
y coordinate of match point
Definition at line 302 of file WarpMatchScoreFunctionND.h.
Referenced by func(), and setImage().
Pattern2DMatchRecord* uriVL::WarpMatchScoreFunctionND::matchRecord_ protected
Match record used for the results of the matcher.
Definition at line 264 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND().
BorderWarpingMode uriVL::WarpMatchScoreFunctionND::outerMode_ protected
The warper's border warping mode (stored for speedier func call)
Definition at line 233 of file WarpMatchScoreFunctionND.h.
Referenced by func(), newVarArray(), and WarpMatchScoreFunctionND().
Pattern2D* uriVL::WarpMatchScoreFunctionND::pat_ protected
pattern for correlation with img_
Definition at line 255 of file WarpMatchScoreFunctionND.h.
Referenced by setImage(), setPattern(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
BaseRasterType uriVL::WarpMatchScoreFunctionND::patRasterType_ protected
Base raster type of the pattern.
Definition at line 259 of file WarpMatchScoreFunctionND.h.
Referenced by func(), setImage(), and setPattern().
float* uriVL::WarpMatchScoreFunctionND::patScale1D_ protected
stores a 1D array of "pattern scaling factor" data needed by some pattern matchers
Definition at line 269 of file WarpMatchScoreFunctionND.h.
Referenced by func(), setPattern(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
float** uriVL::WarpMatchScoreFunctionND::patScale2D_ protected
stores a 2D array of "pattern scaling factor" data needed by some pattern matchers
Definition at line 279 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
ImageWarper* uriVL::WarpMatchScoreFunctionND::warper_ protected
warper
Definition at line 215 of file WarpMatchScoreFunctionND.h.
Referenced by func(), getImageSuitableDimensions(), getWarper(), newWarpingGrid(), setImage(), WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
bool uriVL::WarpMatchScoreFunctionND::warperIsLocal_ protected
Indicates whether _warper is "owned" by this object or was passed to the constructor.
Definition at line 220 of file WarpMatchScoreFunctionND.h.
Referenced by WarpMatchScoreFunctionND(), and ~WarpMatchScoreFunctionND().
The documentation for this class was generated from the following files:
WarpMatchScoreFunctionND.h
WarpMatchScoreFunctionND.cpp