URIVisionLibrary: uriVL::LinearSolver Class Reference
uriVL::LinearSolver Class Reference abstract
Parent class to all classes that implement an algorithm for solving a system of linear equations.
#include <LinearSolver.h>
Public Member Functions
virtual ~LinearSolver (void)
Destructor.
virtual void setMatrix (Matrix *a, bool preserveMatrix=false)=0
Assigns a new matrix to this LinearSolver.
virtual LinearSolverRecord * solve (Matrix *b)=0
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
virtual void solve (Matrix *b, LinearSolverRecord *record)=0
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Protected Member Functions
LinearSolver (void)
Default constructor.
LinearSolver (int nbRows, int nbCols)
Constructor: initializes the dimensions of the linear solver.
LinearSolver (Matrix *a, bool preserveMatrix=false)
Constructor: initializes the dimensions of the linear solver.
void setSingularityStatus_ (LinearSolverRecordStatus singularityStatus)
Sets the singularityStatus_.
LinearSolverRecordStatus getSingularityStatus_ (void)
Get the singularityStatus_.
int getNbRows_ (void)
Reports the number of rows of the solver's matrix.
int getNbCols_ (void)
Reports the number of rows of the solver's matrix.
void setMatrixDimensions_ (int nbRows, int nbCols)
Sets the dimensions of the solver's matrix.
int getNbStorageRows_ (void)
Reports the number of storage rows of the solver's matrix.
int getNbStorageCols_ (void)
Reports the number of storage rows of the solver's matrix.
void setMatrixStorageDimensions_ (int nbRows, int nbCols)
Sets the storage dimensions of the solver's matrix.
bool getMatrixIsLocal_ (void)
Reports whether the solver keeps a local copy of the SLE's matrix.
void setMatrixIsLocal_ (bool matrixIsLocal)
Sets whether the solver keeps a local copy of the SLE's matrix.
Private Attributes
int nbRows_
Effective number of rows of the matrix.
int nbCols_
Effective number of columns of the matrix.
int nbStorageRows_
Number of storage rows of the matrix, in case the matrix is stored locally.
int nbStorageCols_
Number of storage columns of the matrix, in case the matrix is stored locally.
bool matrixIsLocal_
Indicates whether this object stores a local copy of the SLE's matrix or just a reference to that matrix.
LinearSolverRecordStatus singularityStatus_
Set by factorization functions.
Detailed Description
Parent class to all classes that implement an algorithm for solving a system of linear equations.
Important note about LinearSolver classes: These classes have been built for speed, not for OOP orthodoxy. We try to minimize as much as possible the number of malloc/delete operations. The default behavior of most functions in these classes is to only keep references to the SLE's matrix, not copies of it, and to perform claculations directly in that matrix (destructive behavior). If this behavior is not desirable for your application, then call the function with the parameter preserveMatrix set to true, when available.
Author
jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 45 of file LinearSolver.h.
Constructor & Destructor Documentation
LinearSolver::~LinearSolver (void) virtual
Destructor.
Definition at line 68 of file LinearSolver.cpp.
 {
 }
LinearSolver::LinearSolver (void) protected
Default constructor.
Definition at line 19 of file LinearSolver.cpp.
                 :       nbRows_(0),
                         nbCols_(0),
                         nbStorageRows_(0),
                         nbStorageCols_(0),
                         matrixIsLocal_(true),
                         //
                         singularityStatus_(UNKNOWN_STATUS)
 {
 }
LinearSolver::LinearSolver (int nbRows, int nbCols) protected
Constructor: initializes the dimensions of the linear solver.
Parameters
nbRows the maximum number of rows in the matrix
nbCols the maximum number of columns in the matrix
Definition at line 30 of file LinearSolver.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
                 :       nbRows_(nbRows),
                         nbCols_(nbCols),
                         nbStorageRows_(nbRows),
                         nbStorageCols_(nbCols),
                         matrixIsLocal_(true),
                         //
                         singularityStatus_(UNKNOWN_STATUS)
 {
         FAIL_CONDITION( (nbRows < 1) || (nbCols < 1),
                         kInvalidParameterError,
                         "Invalid dimension SLE assigned to a LinearSolver constructor");
 }
LinearSolver::LinearSolver (Matrix * a, bool preserveMatrix = false) protected
Constructor: initializes the dimensions of the linear solver.
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 47 of file LinearSolver.cpp.
                 :       nbRows_(A->getNbRows()),
                         nbCols_(A->getNbCols()),
                         nbStorageRows_(A->getNbRows()),
                         nbStorageCols_(A->getNbCols()),
                         matrixIsLocal_(preserveMatrix),
                         //
                         singularityStatus_(UNKNOWN_STATUS)
 {
 }
 catch (...) {
         FAIL_CONDITION( A == NULL,
                                         kNullParameterError,
                                         "Null pointer to Matrix passed to LinearSolver constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid pointer to Matrix passed to LinearSolver constructor");
 }
Member Function Documentation
bool LinearSolver::getMatrixIsLocal_ (void) protected
Reports whether the solver keeps a local copy of the SLE's matrix.
Returns
true if the solver keeps a local copy of the SLE's matrix
Definition at line 116 of file LinearSolver.cpp.
References matrixIsLocal_.
Referenced by uriVL::LinearSolver_SVD::LinearSolver_SVD(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), uriVL::LinearSolver_LU::setMatrix(), uriVL::LinearSolver_SVD::setMatrix(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_Jacobi::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_GaussSeidel::~LinearSolver_GaussSeidel(), uriVL::LinearSolver_Jacobi::~LinearSolver_Jacobi(), uriVL::LinearSolver_LU::~LinearSolver_LU(), uriVL::LinearSolver_QR::~LinearSolver_QR(), uriVL::LinearSolver_SOR::~LinearSolver_SOR(), and uriVL::LinearSolver_SVD::~LinearSolver_SVD().
 {
         return matrixIsLocal_;
 }
int LinearSolver::getNbCols_ (void) protected
Reports the number of rows of the solver's matrix.
Returns
number of rows of the solver's matrix
Definition at line 89 of file LinearSolver.cpp.
References nbCols_.
Referenced by uriVL::LinearSolver_LU::LinearSolver_LU(), uriVL::LinearSolver_QR::setMatrix(), and uriVL::LinearSolver_QR::solve().
 {
         return nbCols_;
 }
int LinearSolver::getNbRows_ (void) protected
Reports the number of rows of the solver's matrix.
Returns
number of rows of the solver's matrix
Definition at line 84 of file LinearSolver.cpp.
References nbRows_.
Referenced by uriVL::LinearSolver_LU::LinearSolver_LU(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_Jacobi::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_LU::solve(), and uriVL::LinearSolver_SVD::solve().
 {
         return nbRows_;
 }
int LinearSolver::getNbStorageCols_ (void) protected
Reports the number of storage rows of the solver's matrix.
Returns
number of storage rows of the solver's matrix
Definition at line 105 of file LinearSolver.cpp.
References nbStorageCols_.
Referenced by uriVL::LinearSolver_QR::setMatrix(), and uriVL::LinearSolver_QR::~LinearSolver_QR().
 {
         return nbStorageCols_;
 }
int LinearSolver::getNbStorageRows_ (void) protected
Reports the number of storage rows of the solver's matrix.
Returns
number of storage rows of the solver's matrix
Definition at line 100 of file LinearSolver.cpp.
References nbStorageRows_.
Referenced by uriVL::LinearSolver_QR::setMatrix().
 {
         return nbStorageRows_;
 }
LinearSolverRecordStatus LinearSolver::getSingularityStatus_ (void) protected
Get the singularityStatus_.
See also
singularityStatus_
Returns
value of singularityStatus_
Definition at line 79 of file LinearSolver.cpp.
References singularityStatus_.
Referenced by uriVL::LinearSolver_Cholesky::solve(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_LU::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_Jacobi::solve(), and uriVL::LinearSolver_SVD::solve().
 {
         return singularityStatus_;
 }
virtual void uriVL::LinearSolver::setMatrix (Matrix * a, bool preserveMatrix = false) pure virtual
Assigns a new matrix to this LinearSolver.
This call only makes sense if the new matrix has the same dimensions as the previous one (it then saves a destruction and an allocation of a matrix). Otherwise, just use the static solve function.
Important: If you don't set preserveMatrix true, then the LinearSolver only stores a reference to matrix it receives as a parameter. It will do calculations in this matrix.
You cannot delete it before you call the solve function,
The matrix's elements will be modified (destructive behavior)
Parameters
a the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Implemented in uriVL::LinearSolver_SVD, uriVL::LinearSolver_LU, uriVL::LinearSolver_GaussSeidel, uriVL::LinearSolver_Jacobi, uriVL::LinearSolver_SOR, uriVL::LinearSolver_QR, and uriVL::LinearSolver_Cholesky.
void LinearSolver::setMatrixDimensions_ (int nbRows, int nbCols) protected
Sets the dimensions of the solver's matrix.
Parameters
nbRows new number of rows
nbCols new number of columns
Definition at line 94 of file LinearSolver.cpp.
References nbCols_, and nbRows_.
Referenced by uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), and uriVL::LinearSolver_LU::setMatrix().
 {
         nbRows_ = nbRows;
         nbCols_ = nbCols;
 }
void LinearSolver::setMatrixIsLocal_ (bool matrixIsLocal) protected
Sets whether the solver keeps a local copy of the SLE's matrix.
Parameters
matrixIsLocal indicates whether the solver keeps a local copy of the SLE's matrix
Definition at line 122 of file LinearSolver.cpp.
References matrixIsLocal_.
Referenced by uriVL::LinearSolver_GaussSeidel::LinearSolver_GaussSeidel(), uriVL::LinearSolver_Jacobi::LinearSolver_Jacobi(), uriVL::LinearSolver_LU::LinearSolver_LU(), uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_SOR::LinearSolver_SOR(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), and uriVL::LinearSolver_LU::setMatrix().
 {
         matrixIsLocal_ = matrixIsLocal;
 }
void LinearSolver::setMatrixStorageDimensions_ (int nbRows, int nbCols) protected
Sets the storage dimensions of the solver's matrix.
To facilitate the reuse of a matrix object in video processing applications, the matrix's data array may be allocated at a larger size (the "storage" dimensions) than the matrix's nominal dimensions.
Parameters
nbRows new number of storage rows
nbCols new number of storage columns
Definition at line 110 of file LinearSolver.cpp.
References nbStorageCols_, and nbStorageRows_.
Referenced by uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), and uriVL::LinearSolver_LU::setMatrix().
 {
         nbStorageRows_ = nbRows;
         nbStorageCols_ = nbCols;
 }
void LinearSolver::setSingularityStatus_ (LinearSolverRecordStatus singularityStatus) protected
Sets the singularityStatus_.
The conditions for singularity are solver-dependent. The child class solver makes its own singularity test and sets the value of singularityStatus_
See also
singularityStatus_
Parameters
singularityStatus new value for singularityStatus_
Definition at line 73 of file LinearSolver.cpp.
References singularityStatus_.
Referenced by uriVL::LinearSolver_GaussSeidel::LinearSolver_GaussSeidel(), uriVL::LinearSolver_Jacobi::LinearSolver_Jacobi(), uriVL::LinearSolver_LU::LinearSolver_LU(), uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_SOR::LinearSolver_SOR(), uriVL::LinearSolver_SVD::LinearSolver_SVD(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), uriVL::LinearSolver_LU::setMatrix(), and uriVL::LinearSolver_SVD::setMatrix().
 {
         singularityStatus_ = singularityStatus;
 }
virtual LinearSolverRecord* uriVL::LinearSolver::solve (Matrix * b) pure virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the right-side term of the SLE to solve
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Implemented in uriVL::LinearSolver_SVD, uriVL::LinearSolver_LU, uriVL::LinearSolver_GaussSeidel, uriVL::LinearSolver_Jacobi, uriVL::LinearSolver_SOR, uriVL::LinearSolver_QR, and uriVL::LinearSolver_Cholesky.
virtual void uriVL::LinearSolver::solve (Matrix * b, LinearSolverRecord * record) pure virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
Implemented in uriVL::LinearSolver_SVD, uriVL::LinearSolver_GaussSeidel, uriVL::LinearSolver_Jacobi, uriVL::LinearSolver_LU, uriVL::LinearSolver_SOR, uriVL::LinearSolver_QR, and uriVL::LinearSolver_Cholesky.
Member Data Documentation
bool uriVL::LinearSolver::matrixIsLocal_ private
Indicates whether this object stores a local copy of the SLE's matrix or just a reference to that matrix.
Definition at line 191 of file LinearSolver.h.
Referenced by getMatrixIsLocal_(), and setMatrixIsLocal_().
int uriVL::LinearSolver::nbCols_ private
Effective number of columns of the matrix.
Definition at line 173 of file LinearSolver.h.
Referenced by getNbCols_(), and setMatrixDimensions_().
int uriVL::LinearSolver::nbRows_ private
Effective number of rows of the matrix.
Definition at line 169 of file LinearSolver.h.
Referenced by getNbRows_(), and setMatrixDimensions_().
int uriVL::LinearSolver::nbStorageCols_ private
Number of storage columns of the matrix, in case the matrix is stored locally.
To facilitate the reuse of a matrix object in video processing applications, the matrix's data array may be allocated at a larger size (the "storage" dimensions) than the matrix's nominal dimensions
Definition at line 187 of file LinearSolver.h.
Referenced by getNbStorageCols_(), and setMatrixStorageDimensions_().
int uriVL::LinearSolver::nbStorageRows_ private
Number of storage rows of the matrix, in case the matrix is stored locally.
To facilitate the reuse of a matrix object in video processing applications, the matrix's data array may be allocated at a larger size (the "storage" dimensions) than the matrix's nominal dimensions
Definition at line 180 of file LinearSolver.h.
Referenced by getNbStorageRows_(), and setMatrixStorageDimensions_().
LinearSolverRecordStatus uriVL::LinearSolver::singularityStatus_ private
Set by factorization functions.
Definition at line 195 of file LinearSolver.h.
Referenced by getSingularityStatus_(), and setSingularityStatus_().
The documentation for this class was generated from the following files:
LinearSolver.h
LinearSolver.cpp