URIVisionLibrary: uriVL::FunctionND_F Class Reference
uriVL::FunctionND_F Class Reference abstract
Pure virtual parent class for all n-dimensional functions.
#include <FunctionND_F.h>
Public Member Functions
FunctionND_F (int n)
Creates a new n-dimensional function defined over ]-infinity, +infinity[^n.
FunctionND_F (int n, const float *xMin, const float *xMax)
Creates a new n-dimensional function defined over the range specified.
virtual ~FunctionND_F (void)
Destructor.
virtual float func (const float *x) const =0
Evaluates the function at the nD point specified.
virtual float func (const std::vector< float > &x) const
Evaluates the function at the nD point specified.
virtual void gradient (const float *x, float *gradVect) const
Evaluates the gradient of the function at the point specified.
virtual void hessian (const float *x, float **hessianMat) const
Evaluates the Hessian matrix of the function at the point specified.
virtual bool gradientIsImplemented (void) const =0
Indicates whether the function implements its own gradient function.
virtual bool hessianIsImplemented (void) const =0
Indicates whether the function implements its own Hessian function.
bool isDefinedAt (const float *x) const
Indicates whther a point is within the domain of definition of this function.
bool isDefinedAt (const std::vector< float > &x) const
Indicates whther a point is within the domain of definition of this function.
const float * getLowerBound (void) const
Returns the lower bounds of this function's domain of definition.
const float * getUpperBound (void) const
Returns the upper bounds of this function's domain of definition.
int getDimension (void) const
Returns the dimension of this function's domain.
Protected Attributes
int nDim_
Dimension of the source space of this function.
bool isBounded_
Is set true when bounds xMin_ and xMax_ were set for the domain of definition of the function.
float * xMin_
nDim-sized array of lower bounds of the domain of definition.
float * xMax_
nDim-sized array of upper bounds of the domain of definition.
float * xLocal_
Array that stores a copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function)
float * xLocal2_
Array that stores another copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function and derivative)
Private Member Functions
FunctionND_F (const FunctionND_F &obj)
Copy constructor.
const FunctionND_F & operator= (const FunctionND_F &obj)
Copy operator.
Detailed Description
Pure virtual parent class for all n-dimensional functions.
The function's actual implementation will be done in the child class and it will always be hard-coded.
Note that, contrary to a mathematical function, a Function is always defined on an interval that could be -∞ to +∞, but cannot have "holes" in it.
    I have finally decided to remove all versions of func, gradient, and hessian that
    take (pointers to) ColumnVector and Matrix objects as parameters:  Since all classes
    in the linear algebra package only use double, it was a form of perversity to go
    back and form between double and float.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 43 of file FunctionND_F.h.
Constructor & Destructor Documentation
FunctionND_F::FunctionND_F (int n)
Creates a new n-dimensional function defined over ]-infinity, +infinity[^n.
Definition at line 31 of file FunctionND_F.cpp.
References HUGE_VALF, xMax_, and xMin_.
                         :       nDim_(n),
                                 isBounded_(false),
                                 xMin_(new float[n]),
                                 xMax_(new float[n]),
                                 xLocal_(new float[n]),
                                 xLocal2_(new float[n])
 {
     for (int i=0; i<n; i++)
     {
         xMin_[i] = static_cast<float>(-HUGE_VALF);
         xMax_[i] = static_cast<float>(HUGE_VALF);
     }
 }
 catch (...)
 {
         FAIL_CONDITION( n <= 0,
                                         kInvalidParameterError,
                                         "Invalid dimension passed to FunctionND_F constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter passed to FunctionND_F constructor");
 }
FunctionND_F::FunctionND_F (int n, const float * xMin, const float * xMax)
Creates a new n-dimensional function defined over the range specified.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
Definition at line 56 of file FunctionND_F.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, xMax_, and xMin_.
                         :       nDim_(n),
                                 isBounded_(true),
                                 xMin_(new float[n]),
                                 xMax_(new float[n]),
                                 xLocal_(new float[n]),
                                 xLocal2_(new float[n])
 {
         try
         {
                 for (int i=0; i<n; i++)
                 {
                         xMin_[i] = xMin[i];
                         xMax_[i] = xMax[i];
                 }
         }
         catch(...)
         {
                 FAIL_CONDITION( (xMin == NULL) || (xMax == NULL),
                                                 kNullParameterError,
                                                 "Null bound vector passed to FunctionND_F constructor");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid bound vector passed to FunctionND_F constructor");
         }
 }
 catch (...)
 {
         FAIL_CONDITION( n <= 0,
                                         kInvalidParameterError,
                                         "Invalid dimension passed to FunctionND_F constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter passed to FunctionND_F constructor");
 }
FunctionND_F::~FunctionND_F (void) virtual
Destructor.
Definition at line 107 of file FunctionND_F.cpp.
References xLocal2_, xLocal_, xMax_, and xMin_.
 {
     delete []xMin_;
     delete []xMax_;
         delete [] xLocal_;
         delete [] xLocal2_;
 }
FunctionND_F::FunctionND_F (const FunctionND_F & obj) private
Copy constructor.
Parameters
obj object to copy
Definition at line 93 of file FunctionND_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       nDim_(0),
                                 isBounded_(false),
                                 xMin_(NULL),
                                 xMax_(NULL),
                                 xLocal_(NULL),
                                 xLocal2_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "FunctionND_F copy constructor not implemented");
 }
Member Function Documentation
virtual float uriVL::FunctionND_F::func (const float * x) const pure virtual
Evaluates the function at the nD point specified.
This is the only version of func that must be implemented in the child class.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Referenced by uriVL::FunctionNDSection1D_F::func(), func(), and gradient().
float FunctionND_F::func (const std::vector< float > & x) const virtual
Evaluates the function at the nD point specified.
If you are going to use this function a lot you should override it in your custom child class because this implementation is (by necessity) very inefficient: It copies all the data into an array before calling the array version of func.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Definition at line 131 of file FunctionND_F.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, uriVL::kNumericalError, and xLocal_.
 {
         //-----------------------------------------------------
         //      First check that the function is defined at x
         //-----------------------------------------------------
         if (isBounded_)
         {
                 bool isDefined = false;
                 try
                 {
                         isDefined = isDefinedAt(x);
                 }
                 catch (ErrorReport& e)
                 {
                         e.appendToMessage("called by FunctionND::func");
                         throw e;
                 }
                 catch(...)
                 {
                         FAIL_CONDITION( true,
                                                         kNumericalError,
                                                         "Unexpected error in FunctionND::func");
                 }
                 FAIL_CONDITION( !isDefined,
                                                 kDataRangeError,
                                                 "x not within domain of definition in FunctionND::func");
         }
         //-----------------------------------------------------
         //      Make local copy of x
         //-----------------------------------------------------
         try
         {
                 for (unsigned int k=0; k<x.size(); k++)
                         xLocal_[k] = x[k];
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND_F::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error while copying input data in in FunctionND_F::func");
         }
         //-----------------------------------------------------
         //      Finally evaluate the function at x
         //-----------------------------------------------------
         float val = 0;
         try
         {
                 val  = func(xLocal_);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND_F::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND_F::func");
         }
         return val;
 }
int FunctionND_F::getDimension (void) const
Returns the dimension of this function's domain.
Definition at line 329 of file FunctionND_F.cpp.
References nDim_.
Referenced by checkIfSearchStartPointIsValid_(), uriVL::NonlinearOptimizerND::minimize(), uriVL::NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir(), and uriVL::NonlinearOptimizerND_conjDir::setFunction_().
 {
     return nDim_;
 }
const float * FunctionND_F::getLowerBound (void) const
Returns the lower bounds of this function's domain of definition.
Definition at line 378 of file FunctionND_F.cpp.
References xMin_.
Referenced by uriVL::FunctionNDSection1D_F::getLowerBound(), and uriVL::FunctionNDSection1D_F::getUpperBound().
 {
     return xMin_;
 }
const float * FunctionND_F::getUpperBound (void) const
Returns the upper bounds of this function's domain of definition.
Definition at line 384 of file FunctionND_F.cpp.
References xMax_.
Referenced by uriVL::FunctionNDSection1D_F::getLowerBound(), and uriVL::FunctionNDSection1D_F::getUpperBound().
 {
     return xMax_;
 }
void FunctionND_F::gradient (const float * x, float * gradVect) const virtual
Evaluates the gradient of the function at the point specified.
If the subclass does not implement its own gradient function, then this function will be called instead, which implements the second-order central difference approximation for all directions.
Parameters
x where the function should be evaluated
gradVect the gradient of the function at x
Definition at line 220 of file FunctionND_F.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, uriVL::kNumericalError, LARGE_RELATIVE_TOLERANCE_F, nDim_, xLocal2_, and xLocal_.
 {
         //-----------------------------------------------------
         //      First check that the function is defined at x
         //-----------------------------------------------------
         if (isBounded_)
         {
                 bool isDefined = false;
                 try
                 {
                         isDefined = isDefinedAt(x);
                 }
                 catch (ErrorReport& e)
                 {
                         e.appendToMessage("called by FunctionND_F::gradient");
                         throw e;
                 }
                 catch(...)
                 {
                         FAIL_CONDITION( true,
                                                         kNumericalError,
                                                         "Unexpected error in FunctionND_F::gradient");
                 }
                 FAIL_CONDITION( !isDefined,
                                                 kDataRangeError,
                                                 "x not within domain of definition in FunctionND_F::gradient");
         }
         //-----------------------------------------------------
         //      Make local copies of x
         //-----------------------------------------------------
         float* xPlus = xLocal_;
         float* xMinus = xLocal2_;
         try
         {
                 //      for each variable of x --> derivative
                 for (int k=0; k<nDim_; k++)
                 {
                         //      compute a small discrete displacement along kth direction
                         const float DX = fabsf(x[k]) > LARGE_RELATIVE_TOLERANCE_F ?
                                                                 fabsf(x[k])*LARGE_RELATIVE_TOLERANCE_F
                                                                 :
                                                                 LARGE_RELATIVE_TOLERANCE_F;
                         const float TWO_OVER_DX = 2.f / DX;
                         //      initialize the "plus" and "minus" arrays
                         for (int i=0; i<nDim_; i++)
{
                                 if (i!= k)
{
                                         xPlus[k] = xMinus[k] = x[k];
                                 }
                                 else
{
                                         xPlus[k] = x[k] + DX;
                                         xMinus[k] = x[k] - DX;
                                 }
                         }
                         gradVect[k] = TWO_OVER_DX * (func(xPlus) - func(xMinus));
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::gradient");
         }
 }
virtual bool uriVL::FunctionND_F::gradientIsImplemented (void) const pure virtual
Indicates whether the function implements its own gradient function.
Returns
true if the function implements its own gradient function
void FunctionND_F::hessian (const float * x, float ** hessianMat) const virtual
Evaluates the Hessian matrix of the function at the point specified.
If the subclass does not implement its own gradient function, then this function will be called instead, which implements the second-order difference approximation for all directions.
Parameters
x where the function should be evaluated
hessianMat the Hessian matrix of the function at x
Definition at line 312 of file FunctionND_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
virtual bool uriVL::FunctionND_F::hessianIsImplemented (void) const pure virtual
Indicates whether the function implements its own Hessian function.
Returns
true if the function implements its own Hessian function
bool FunctionND_F::isDefinedAt (const float * x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
Definition at line 334 of file FunctionND_F.cpp.
References FAIL_CONDITION, uriVL::kNumericalError, nDim_, xMax_, and xMin_.
Referenced by checkIfSearchStartPointIsValid_(), func(), gradient(), and uriVL::FunctionNDSection1D_F::isDefinedAt().
 {
         bool isDefined = true;
         try
         {
                 for (int i=0; (i<nDim_) && isDefined; i++)
                         if ((x[i] < xMin_[i]) || (x[i] > xMax_[i]))
                                 isDefined = false;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error encountered in FunctionND_F::isDefinedAt");
         }
     return isDefined;
 }
bool uriVL::FunctionND_F::isDefinedAt (const std::vector< float > & x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
const FunctionND_F & FunctionND_F::operator= (const FunctionND_F & obj) private
Copy operator.
Parameters
obj object to copy
Definition at line 115 of file FunctionND_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "FunctionND_F copy operator not implemented");
         return *this;
 }
Member Data Documentation
bool uriVL::FunctionND_F::isBounded_ protected
Is set true when bounds xMin_ and xMax_ were set for the domain of definition of the function.
Definition at line 150 of file FunctionND_F.h.
Referenced by func(), and gradient().
int uriVL::FunctionND_F::nDim_ protected
Dimension of the source space of this function.
Definition at line 145 of file FunctionND_F.h.
Referenced by getDimension(), gradient(), and isDefinedAt().
float* uriVL::FunctionND_F::xLocal2_ mutable protected
Array that stores another copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function and derivative)
Definition at line 174 of file FunctionND_F.h.
Referenced by gradient(), and ~FunctionND_F().
float* uriVL::FunctionND_F::xLocal_ mutable protected
Array that stores a copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function)
Definition at line 169 of file FunctionND_F.h.
Referenced by func(), gradient(), and ~FunctionND_F().
float* uriVL::FunctionND_F::xMax_ protected
nDim-sized array of upper bounds of the domain of definition.
Admitedly, this is a somewhat naive/restrictive form of domain of definition, but let's not forget that our underlying space is based on rectangular images.
Definition at line 164 of file FunctionND_F.h.
Referenced by FunctionND_F(), getUpperBound(), isDefinedAt(), and ~FunctionND_F().
float* uriVL::FunctionND_F::xMin_ protected
nDim-sized array of lower bounds of the domain of definition.
Admitedly, this is a somewhat naive/restrictive form of domain of definition, but let's not forget that our underlying space is based on rectangular images.
Definition at line 157 of file FunctionND_F.h.
Referenced by FunctionND_F(), getLowerBound(), isDefinedAt(), and ~FunctionND_F().
The documentation for this class was generated from the following files:
FunctionND_F.h
FunctionND_F.cpp