URIVisionLibrary: uriVL::Matrix Class Reference
uriVL::Matrix Class Reference
Implements the Matrix class of Linear Algebra matrices.
#include <Matrix.h>
Public Member Functions
Matrix (int nbRows, int nbCols)
Creates a nbRows x nbCols matrix whose elements have not been initialized.
Matrix (int nbRows, int nbCols, double v)
"v-valued" constructor of Matrix class.
Matrix (const Matrix *b)
Copy constructor.
Matrix (const Matrix &b)
Copy constructor.
Matrix (int nbRows, int nbCols, double **m, bool safe=true, const MatrixIndicators *matrixIndic=NULL)
"array" constructor of Matrix class.
virtual ~Matrix (void)
Destructor.
int getNbRows (void) const
This function returns a int corresponding to the number of rows in this
int getNbCols (void) const
This function returns a int corresponding to the number of columns in this
const double *const * getMatrix (void) const
Returns a read-only pointer to the matrix data.
double *const * getMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
TriState isSymmetric (void)
Check whether the matrix is symmetric.
TriState isAntisymmetric (void)
Check whether the matrix is antisymmetric.
TriState isOrthogonal (void)
Check whether the matrix is orthogonal.
TriState isDiagonal (void)
Check whether the matrix is diagonal.
TriState isIdentity (void)
Check whether the matrix is an identity matrix.
TriState isUpperTriangular (void)
Check whether the matrix is upper-triangular.
TriState isLowerTriangular (void)
Check whether the matrix is lower-triangular.
double checkSymmetryStatus (void)
Check whether the matrix is symmetric.
double checkAntisymmetryStatus (void)
Check whether the matrix is antisymmetric.
double checkOrthogonalityStatus (void)
Check whether the matrix is orthogonal.
double checkDiagonalityStatus (void)
Check whether the matrix is diagonal.
double checkIdentityStatus (void)
Check whether the matrix is an identity matrix.
double checkUpperTriangularityStatus (void)
Check whether the matrix is upper-triangular.
double checkLowerTriangularityStatus (void)
Check whether the matrix is lower-triangular.
double checkNormalization1Status (void)
Check whether the matrix is normalized according to Norm 1.
double checkNormalization2Status (void)
Check whether the matrix is normalized according to Norm 2.
double checkNormalizationInfStatus (void)
Check whether the matrix is normalized according to Norm 1.
void enforceSymmetry (void)
Forces a matrix that passes the test for symmetry of checkIsSymmetric_ to be exactly symmetric.
void enforcesAntisymmetry (void)
Forces a matrix that passes the test for antisymmetry of checkIsAntisymmetric_ to be exactly antisymmetric.
void enforceOthogonality (void)
Forces a matrix that passes the test for orthogonality of checkIsSymmetric_ to be exactly orthogonality.
void enforceDiagonality (void)
Forces a matrix that passes the test for diagonality of checkIsDiagonal_ to be exactly diagonal.
void enforceIdentity (void)
Forces a matrix that passes the test for identity of checkIsIdentity_ to be exactly identity.
void enforceUpperTriangularity (void)
Forces a matrix that passes the test for upper-triangularity of checkIsUpperTriangular_ to be exactly upper-triangular.
void enforceLowerTriangularity (void)
Forces a matrix that passes the test for lower-triangularity of checkIsLowerTriangular_ to be exactly lower-triangular.
void operator+= (const Matrix &b)
This function adds the parameter Matrix b to this thereby modifying this.
virtual void operator-= (const Matrix &b)
This function subtracts the parameter Matrix from this thereby modifying this.
virtual void operator*= (const double s)
This function multiplies every element of this by the scalar parameter thereby modifying this.
virtual void operator*= (const Matrix &b)
This function premultiplies the parameter Matrix b by this thereby modifying this.
virtual void preMultiplyBy (const Matrix *b)
This function premultiplies this by the parameter Matrix b thereby modifying this
virtual void postMultiplyBy (const Matrix *b)
This function postmultiplies this by the parameter Matrix b thereby modifying this
const Matrix & operator= (const Matrix &b)
Assigns to this matrix the matrix received as parameter (resizes it if necessary.
TriState operator== (const Matrix &b) const
This function does an element-wise comparison to the parameter Matrix b with this.
double operator() (int theRow, int theCol) const
This function returns the element of the Matrix at row theRow and column theCol.
void rowSwap (int r1, int r2)
This function swaps rows of the Matrix (rather, of mat_)
void colSwap (int c1, int c2)
This function swaps columns of the Matrix (rather, of mat_)
double norm1 (void) const
This function returns a double corresponding to the "1" norm of the Matrix this.
double normInf (void) const
This function returns a double corresponding to the "Infinity" norm of the Matrix this.
double determinant (void) const
This function returns a double corresponding to the determinant of the Matrix this.
virtual Matrix * transposition (void) const
This function returns a reference to a new Matrix object, the transposition of this matrix.
virtual void transpose (void)
This function transposes this, thereby altering this.
virtual Matrix * inverse (void) const
This function creates a new Matrix corresponding to the inverse of this (if nonsingular).
virtual void invert (void)
This function inverts this (if nonsingular), thereby modifying this.
string toString (void) const
This function returns a string corresponding to the matrix using the static delimiting strings for the Matrix class.
string toString (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) const
This function returns a string corresponding to the matrix using the parameters as delimiting strings.
Static Public Member Functions
static Matrix * copyMatrix (int nbRows, int nbCols, const double *const *m)
Creates a new nbRows x nbCols matrix and copies into it the elements of the 2D array referenced by m.
static Matrix * nullMatrix (int nbRows, int nbCols)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements to zero.
static Matrix * diagonalMatrix (int nbRows, int nbCols, double v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * diagonalMatrix (int nbRows, int nbCols, const double *v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * identityMatrix (int n)
Produces a new identity matrix at the dimensions specified.
static Matrix * randomMatrix (int nbRows, int nbCols, double lowerBound, double upperBound)
produces a new matrix filled with random values between lowerBound (inclusive) and upperBound (exclusive)
static void setToStringFormat (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor)
This function resets the delimiting strings used when generating a string representation for a given matrix.
Private Member Functions
void killMat_ ()
Deletes and nullifies the 2D array, mat_.
void allocateMatrix_ (void)
Allocates mat_ at the storage dimensions.
Static Private Member Functions
static void sum_ (const double *const *a, const double *const *b, double *const *c, int m, int n)
Computes the sum of two matrices.
static void difference_ (const double *const *a, const double *const *b, double *const *c, int m, int n)
Computes the difference of two matrices.
static void product_ (const double *const *a, const double *const *b, double *const *c, int m, int n, int p)
Computes the product of two matrices.
Private Attributes
int nbRows_
Number of rows of the matrix.
int nbCols_
int nbStorageRows_
Number of storage rows of the matrix.
int nbStorageCols_
Number of storage columns of the matrix.
double ** mat_
The data for the Matrix.
bool storageIsLocal_
Indicates whether the array mat_ was allocated by the matrix or is simply a reference to an array created outside of the class.
TriState isDiagonal_
Indicates whether the matrix is known to be diagonal.
TriState isIdentity_
Indicates whether the matrix is known to be an identity matrix.
TriState isUpperTriangular_
Indicates whether the matrix is known to be upper-triangular.
TriState isLowerTriangular_
Indicates whether the matrix is known to be lower-triangular.
TriState isFullRank_
Indicates whether the matrix is known to be a full rank matrix (which includes nonsingular for a square matrix)
TriState isSymmetric_
Indicates whether the matrix is known to be symmetric.
TriState isAntisymmetric_
Indicates whether the matrix is known to be antisymmetric.
TriState isOrthogonal_
Indicates whether the matrix is known to be orthogonal.
TriState isNormalized1_
Is this matrix normalized with respect to N1 norm?
TriState isNormalized2_
Is this matrix normalized with respect to N2 (Euclidean) norm?
TriState isNormalizedInf_
Is this matrix normalized with respect to N_infinity norm?
Static Private Attributes
static string beginArrayStr_ = "["
Beginning of row or col array for output as a string.
static string endArrayStr_ = "]"
End of row or col array for output as a string.
static string elmtSepStr_ = ", "
Separation between elements for output as a string.
static bool eolAtEor_ = true
Does the output format require an end of line character at the end of the string?
static const double MATRIX_PROP_ABS_TOL = 1.E-7
Absolute tolerance for all properties of the matrix class.
static const double MATRIX_PROP_REL_TOL = 1.E-7
Relative tolerance for all properties of the matrix class.
Friends
class ColumnVector
class RowVector
class HomogeneousMatrix
const Matrix operator* (const Matrix &a, const Matrix &b)
This operator creates a new Matrix equal to the sum of the two terms.
const Matrix operator* (const double s, const Matrix &a)
This operator creates a new Matrix equal to the multiplication of a matrix by a scalar term.
const Matrix operator* (const Matrix &a, const double s)
This operator creates a new Matrix equal to the multiplication of a matrix by a scalar term.
Detailed Description
Implements the Matrix class of Linear Algebra matrices.
Note: Being somewhat inconsistant, I added flags to store information about the matrix such as whether it is symmetric, orthogonal, upper-triangular, etc. On the one hand, it might be nice to keep track of that because it allows to be "smarter" when we need to solve an SLE (e.g. it's good to know if the matrix is orthogonal or triangular) or compute the determinant (e.g. if the matrix is triangular). On the other hand, it is a bit of a hassle to keep track of this, and this could be claimed to be the user's job to do so. At this point, the flags are declared but not accessible, and their computation/update is not fully implemented.
Author
Joshua Sawyer and jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 63 of file Matrix.h.
Constructor & Destructor Documentation
Matrix::Matrix (int nbRows, int nbCols)
Creates a nbRows x nbCols matrix whose elements have not been initialized.
This is the fastest way to get a new matrix if you are going to assign values directly by yourself.
Parameters
nbRows the number of rows in the matrix
nbCols the number of columns in the matrix
Definition at line 44 of file Matrix.cpp.
References allocateMatrix_(), FAIL_CONDITION, uriVL::IS_FALSE, uriVL::IS_TRUE, isAntisymmetric_, isOrthogonal_, and uriVL::kInvalidParameterError.
Referenced by copyMatrix(), diagonalMatrix(), randomMatrix(), and transposition().
         :       nbRows_(nbRows),
                 nbCols_(nbCols),
                 nbStorageRows_(nbRows),
                 nbStorageCols_(nbCols),
                 mat_(NULL),
                 storageIsLocal_(false),
                 //
                 isDiagonal_(IS_TRUE),
                 isIdentity_(IS_FALSE),
                 isUpperTriangular_(IS_TRUE),
                 isLowerTriangular_(IS_TRUE),
                 isFullRank_(IS_FALSE),
                 isSymmetric_(IS_TRUE),
                 isAntisymmetric_(IS_TRUE),
                 isOrthogonal_(IS_FALSE),
                 isNormalized1_(IS_FALSE),
                 isNormalized2_(IS_FALSE),
                 isNormalizedInf_(IS_FALSE)
 {
     FAIL_CONDITION( (nbRows < 1) || (nbCols<1),
                     kInvalidParameterError,
                     "Wrong dimensions in Matrix constructor");
     allocateMatrix_();
     if (nbRows == nbCols)
         isAntisymmetric_ = IS_TRUE;
     else
         isAntisymmetric_ = IS_FALSE;
     isOrthogonal_ = IS_FALSE;
 }
Matrix::Matrix (int nbRows, int nbCols, double v)
"v-valued" constructor of Matrix class.
Creates a nbRows x nbCols matrix where all elements are v.
Parameters
nbRows the number of rows in the matrix
nbCols the number of columns in the matrix
v the value with which to fill the matrix
Definition at line 78 of file Matrix.cpp.
References allocateMatrix_(), FAIL_CONDITION, uriVL::kInvalidParameterError, mat_, nbCols_, and nbRows_.
         :       nbRows_(nbRows),
                 nbCols_(nbCols),
                 nbStorageRows_(nbRows),
                 nbStorageCols_(nbCols),
                 mat_(NULL),
                 storageIsLocal_(false),
                 //
                 isDiagonal_(IS_TRUE),
                 isIdentity_((nbRows_ == nbCols_) && (v== 1.L) ? IS_TRUE : IS_FALSE),
         isUpperTriangular_(v==0.L ? IS_TRUE : IS_FALSE),
         isLowerTriangular_(v==0.L ? IS_TRUE : IS_FALSE),
                 isFullRank_((nbRows_ >= nbCols_) && (v!= 0.L) ? IS_TRUE : IS_FALSE),
                 isSymmetric_(nbRows_ == nbCols_ ? IS_TRUE : IS_FALSE),
                 isAntisymmetric_((nbRows_ == nbCols_) && (v== 0.L) ? IS_TRUE : IS_FALSE),
                 isOrthogonal_((nbRows_ >= nbCols_) && (v*v != 1.L) ? IS_TRUE : IS_FALSE),
                 isNormalized1_((fabs(fabs(nbRows*v) - 1) < 1E-6) ? IS_TRUE : IS_FALSE),
                 isNormalized2_((nbRows_ == nbCols_) && (fabs(fabs(v)*nbRows - 1.0) < 1E-6) ? IS_TRUE : IS_FALSE),
                 isNormalizedInf_((fabs(fabs(nbCols*v) - 1.0) < 1E-6) ? IS_TRUE : IS_FALSE)
 {
     FAIL_CONDITION( (nbRows < 1) || (nbCols<1),
                     kInvalidParameterError,
                     "Wrong dimensions in Matrix constructor");
     allocateMatrix_();
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] = v;
 }
Matrix::Matrix (const Matrix * b)
Copy constructor.
Parameters
b a pointer to the Matrix to copy
Definition at line 175 of file Matrix.cpp.
References allocateMatrix_(), mat_, nbCols_, and nbRows_.
                 :               nbRows_(b->nbRows_),
                                 nbCols_(b->nbCols_),
                                 nbStorageRows_(b->nbRows_),
                                 nbStorageCols_(b->nbCols_),
                                 mat_(NULL),
                                 storageIsLocal_(false),
                                 //
                                 isDiagonal_(b->isDiagonal_),
                                 isIdentity_(b->isIdentity_),
                                 isUpperTriangular_(b->isUpperTriangular_),
                                 isLowerTriangular_(b->isLowerTriangular_),
                                 isFullRank_(b->isFullRank_),
                                 isSymmetric_(b->isSymmetric_),
                                 isAntisymmetric_(b->isAntisymmetric_),
                                 isOrthogonal_(b->isOrthogonal_),
                                 isNormalized1_(b->isNormalized1_),
                                 isNormalized2_(b->isNormalized2_),
                                 isNormalizedInf_(b->isNormalizedInf_)
 {
     allocateMatrix_();
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] = b->mat_[i][j];
 }
 catch (...)
 {
     FAIL_CONDITION( b == NULL,
                     kNullParameterError,
                     "Null parameter in Matrix copy constructor");
 }
Matrix::Matrix (const Matrix & b)
Copy constructor.
Parameters
b a reference to the Matrix to copy
Definition at line 210 of file Matrix.cpp.
References allocateMatrix_(), mat_, nbCols_, and nbRows_.
                 :               nbRows_(b.nbRows_),
                                 nbCols_(b.nbCols_),
                                 nbStorageRows_(b.nbRows_),
                                 nbStorageCols_(b.nbCols_),
                                 mat_(NULL),
                                 storageIsLocal_(false),
                                 //
                                 isDiagonal_(b.isDiagonal_),
                                 isIdentity_(b.isIdentity_),
                                 isUpperTriangular_(b.isUpperTriangular_),
                                 isLowerTriangular_(b.isLowerTriangular_),
                                 isFullRank_(b.isFullRank_),
                                 isSymmetric_(b.isSymmetric_),
                                 isAntisymmetric_(b.isAntisymmetric_),
                                 isOrthogonal_(b.isOrthogonal_),
                                 isNormalized1_(b.isNormalized1_),
                                 isNormalized2_(b.isNormalized2_),
                                 isNormalizedInf_(b.isNormalizedInf_)
 {
     allocateMatrix_();
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] = b.mat_[i][j];
 }
 catch (...)
 {
     FAIL_CONDITION( true,
                     kInvalidReferenceError,
                     "Invalid reference in Matrix copy constructor");
 }
Matrix::Matrix (int nbRows, int nbCols, double ** m, bool safe = true, const MatrixIndicators * matrixIndic = NULL)
"array" constructor of Matrix class.
Creates a nbRows x nbCols matrix where the elements are the elements of the 2D array referenced by m. This function does not allocate a new area; instead it uses m as its own data array.
Parameters
nbRows the number of rows in the matrix
nbCols the number of columns in the matrix
m a pointer to a 2D array
safe when true, a copy of the matrix array m will be created and stored
matrixIndic struct describing all that is known about the new matrix
Definition at line 110 of file Matrix.cpp.
References allocateMatrix_(), uriVL::MatrixIndicators::antisymmetryStatus, uriVL::MatrixIndicators::diagonalityStatus, FAIL_CONDITION, uriVL::MatrixIndicators::fullRankStatus, uriVL::MatrixIndicators::identityStatus, uriVL::IS_FALSE, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isNormalized1_, isNormalized2_, isNormalizedInf_, isOrthogonal_, isSymmetric_, isUpperTriangular_, uriVL::kInvalidParameterError, uriVL::MatrixIndicators::lowerTriangularityStatus, mat_, nbCols_, nbRows_, uriVL::MatrixIndicators::normalized1Status, uriVL::MatrixIndicators::normalized2Status, uriVL::MatrixIndicators::normalizedInfStatus, uriVL::MatrixIndicators::orthogonalityStatus, storageIsLocal_, uriVL::MatrixIndicators::symmetryStatus, and uriVL::MatrixIndicators::upperTriangularityStatus.
         :       nbRows_(nbRows),
                 nbCols_(nbCols),
                 nbStorageRows_(nbRows),
                 nbStorageCols_(nbCols),
                 mat_(NULL),
                 storageIsLocal_(safe),
                 //
                 //
                 isDiagonal_(IS_UNKNOWN),
                 isIdentity_(IS_UNKNOWN),
                 isUpperTriangular_(IS_UNKNOWN),
                 isLowerTriangular_(IS_UNKNOWN),
                 isFullRank_(IS_UNKNOWN),
                 isSymmetric_(IS_UNKNOWN),
                 isAntisymmetric_(IS_UNKNOWN),
                 isOrthogonal_(IS_UNKNOWN),
                 isNormalized1_(IS_UNKNOWN),
                 isNormalized2_(IS_UNKNOWN),
                 isNormalizedInf_(IS_UNKNOWN)
 {
     FAIL_CONDITION( (nbRows < 1) || (nbCols<1),
                     kInvalidParameterError,
                     "Wrong dimensions in Matrix constructor");
     if (storageIsLocal_)
     {
         allocateMatrix_();
         for (int i=0; i<nbRows_; i++)
             for (int j=0; j<nbCols_; j++)
                 mat_[i][j] = m[i][j];
     }
     else
         mat_ = m;
     if (matrixIndic != NULL)
     {
         isSymmetric_ = matrixIndic->symmetryStatus;
         isAntisymmetric_ = matrixIndic->antisymmetryStatus;
         isDiagonal_ = matrixIndic->diagonalityStatus;
         isIdentity_ = matrixIndic->identityStatus;
         isOrthogonal_ = matrixIndic->orthogonalityStatus;
         isUpperTriangular_ = matrixIndic->upperTriangularityStatus;
         isLowerTriangular_ = matrixIndic->lowerTriangularityStatus;
         isFullRank_ = matrixIndic->fullRankStatus;
                 isNormalized1_ = matrixIndic->normalized1Status;
                 isNormalized2_ = matrixIndic->normalized2Status;
                 isNormalizedInf_ = matrixIndic->normalizedInfStatus;
     }
     else
     {
         //  only a square matrix can be identity, symmetric, or antisymmetric
         if (nbRows != nbCols)
         {
             isIdentity_ = IS_FALSE;
             isSymmetric_ = IS_FALSE;
             isAntisymmetric_ = IS_FALSE;
         }
     }
 }
Matrix::~Matrix (void) virtual
Destructor.
Definition at line 245 of file Matrix.cpp.
References mat_, and nbRows_.
 {
     if (mat_ != NULL)
     {
         for (int i=0; i<nbRows_; i++)
                 delete []mat_[i];
         delete []mat_;
     }
 }
Member Function Documentation
void Matrix::allocateMatrix_ (void) private
Allocates mat_ at the storage dimensions.
Definition at line 1493 of file Matrix.cpp.
References mat_, nbStorageCols_, nbStorageRows_, and storageIsLocal_.
Referenced by Matrix().
 {
     mat_ = new double*[nbStorageRows_];
     for (int i=0; i < nbStorageRows_; i++)
         mat_[i] = new double[nbStorageCols_];
     storageIsLocal_ = true;
 }
double uriVL::Matrix::checkAntisymmetryStatus (void)
Check whether the matrix is antisymmetric.
A "real-world" matrix is never exactly antisymmetric unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" antisymmetry by calling enforceAntiSymmetry_(). This function updates isAntisymmmetric_ indicator.
See also
isAntisymmmetric_;
enforceAntiSymmetry
Returns
maximum deviation from antisymmetry in the matrix
double uriVL::Matrix::checkDiagonalityStatus (void)
Check whether the matrix is diagonal.
A "real-world" matrix is never exactly diagonal unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" diagonality by calling enforceDiagonality_(). This function updates isDiagonal_ indicator.
See also
isDiagonal_;
enforceDiagonality
Returns
maximum deviation from diagonality in the matrix
double uriVL::Matrix::checkIdentityStatus (void)
Check whether the matrix is an identity matrix.
A "real-world" matrix is never exactly identity unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" indentity by calling enforceIdentitity_(). This function updates isUnity_ indicator.
See also
isDiagonal_;
enforceIdentity_
Returns
maximum deviation from identity in the matrix
double uriVL::Matrix::checkLowerTriangularityStatus (void)
Check whether the matrix is lower-triangular.
A "real-world" matrix is never exactly lower-triangular unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" lower-triangularity by calling enforceUpperTriangularity_(). This function updates isLowerTriangular_ indicator.
See also
isLowerTriangular_;
enforceSymmetry_
Returns
maximum deviation from lower-triangularity in the matrix
double uriVL::Matrix::checkNormalization1Status (void)
Check whether the matrix is normalized according to Norm 1.
A "real-world" matrix is never exactly normalized unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" normalization by calling normalize1(). This function updates isNormalized1_ indicator.
See also
isNormalized1_;
normalize1
Returns
maximum deviation from norm1 normality in the matrix
double uriVL::Matrix::checkNormalization2Status (void)
Check whether the matrix is normalized according to Norm 2.
A "real-world" matrix is never exactly normalized unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" normalization by calling normalize2(). This function updates isNormalized2_ indicator.
See also
isNormalized2_;
normalize2
Returns
maximum deviation from norm2 normality in the matrix
double uriVL::Matrix::checkNormalizationInfStatus (void)
Check whether the matrix is normalized according to Norm 1.
A "real-world" matrix is never exactly normalized unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" normalization by calling normalize1(). This function updates isNormalizedInf_ indicator.
See also
isNormalizedInf_;
normalizeInf
Returns
maximum deviation from norm Inf normality in the matrix
double uriVL::Matrix::checkOrthogonalityStatus (void)
Check whether the matrix is orthogonal.
A "real-world" matrix is never exactly orthogonal unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" orthogonality by calling enforceOthogonality_(). This function updates isOrthogonal_ indicator.
See also
isOrthogonal_;
enforceOthogonality
Returns
maximum deviation from orthogonality in the matrix
double uriVL::Matrix::checkSymmetryStatus (void)
Check whether the matrix is symmetric.
A "real-world" matrix is never exactly symmetric unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" symmetry by calling enforceSymmetry_(). This function updates the isSymmmetric_ indicator.
See also
isSymmmetric_
enforceSymmetry
Returns
maximum deviation from symmetry in the matrix
double uriVL::Matrix::checkUpperTriangularityStatus (void)
Check whether the matrix is upper-triangular.
A "real-world" matrix is never exactly upper-triangular unless it was explicitly created that way. This function checks the property within a fixed relative tolerance and returns the largest deviation encountered. The user can decide to "enforce" upper-triangularity by calling enforceUpperTriangularity_(). This function updates isUpperTriangular_ indicator.
See also
isUpperTriangular_;
enforceUpperTriangularity_
Returns
maximum deviation from upper-triangularity in the matrix
void Matrix::colSwap (int c1, int c2)
This function swaps columns of the Matrix (rather, of mat_)
Parameters
c1 the first column to swap
c2 the second column to swap
Definition at line 792 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_UNKNOWN, isAntisymmetric_, isDiagonal_, isFullRank_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, uriVL::kInvalidParameterError, mat_, nbCols_, and nbRows_.
 {
   FAIL_CONDITION ( (c1 < 0) || (c2 < 0) || (c1 >= nbCols_) || (c2 >= nbCols_),
                  kInvalidParameterError,
                  "Invalid column choices in Matrix::rowSwap");
     if (c1 != c2)
     {
         for (int i = 0; i < nbRows_; i++)
         {
             double temp = mat_[i][c1];
             mat_[i][c1] = mat_[i][c2];
             mat_[i][c2] = temp;
         }
         //  column swap pretty much breaks all properties
         isDiagonal_ = IS_UNKNOWN;
         isUpperTriangular_ = IS_UNKNOWN;
         isLowerTriangular_ = IS_UNKNOWN;
         isFullRank_ = IS_UNKNOWN;
         isSymmetric_ = IS_UNKNOWN;
         isAntisymmetric_ = IS_UNKNOWN;
         isOrthogonal_ = IS_UNKNOWN;
     }
 }
Matrix * Matrix::copyMatrix (int nbRows, int nbCols, const double *const * m) static
Creates a new nbRows x nbCols matrix and copies into it the elements of the 2D array referenced by m.
Parameters
nbRows the number of rows in the matrix
nbCols the number of columns in the matrix
m a pointer to a 2D array
Definition at line 262 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_FALSE, uriVL::IS_UNKNOWN, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, uriVL::kInvalidParameterError, mat_, Matrix(), nbCols_, and nbRows_.
 {
     FAIL_CONDITION( (nbRows < 1) || (nbCols<1),
                     kInvalidParameterError,
                     "Wrong dimensions in Matrix::copyMatrix");
     Matrix *m = new Matrix(nbRows, nbCols);
     m->nbRows_ = nbRows;
     m->nbCols_ = nbCols;
     for (int i=0; i<nbRows; i++)
         for (int j=0; j<nbCols; j++)
             m->mat_[i][j] = a[i][j];
     m->isDiagonal_ = IS_UNKNOWN;
     m->isUpperTriangular_ = IS_UNKNOWN;
     m->isLowerTriangular_ = IS_UNKNOWN;
     m->isFullRank_ = IS_FALSE;
     m->isOrthogonal_ = IS_UNKNOWN;
     //  only a square matrix can be identity, symmetric, or antisymmetric
     if (nbRows == nbCols)
     {
         m->isIdentity_ = IS_UNKNOWN;
         m->isSymmetric_ = IS_UNKNOWN;
         m->isAntisymmetric_ = IS_UNKNOWN;
     }
     else
     {
         m->isIdentity_ = IS_FALSE;
         m->isSymmetric_ = IS_FALSE;
         m->isAntisymmetric_ = IS_FALSE;
     }
     return m;
 }
double Matrix::determinant (void) const
This function returns a double corresponding to the determinant of the Matrix this.
Returns
the determinant of this
Definition at line 1338 of file Matrix.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by inverse().
 {
 /*
   FAIL_CONDITION( nbRows_ != nbCols_,
                   kNumericalError,
                   "Not a square matrix in Matrix::determinant()");
   Factorization_LU* myLU = new Factorization_LU(this);
   int* p = myLU->getP();
   Matrix* LU = myLU->getLU();
   double det = 1;
   for (int i = 0; i < nbRows_; i++)
     det *= (*LU)(p[i],i);
   delete[] p;
   delete LU;
   delete myLU;
   return det;
 */
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
     return 0.L;
 }
Matrix * Matrix::diagonalMatrix (int nbRows, int nbCols, double v) static
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
Parameters
nbRows number of rows of the new matrix
nbCols number of columnss of the new matrix
v value to assign to all diagonal elements
Returns
a new nbRows x nbCols diagonal matrix
Definition at line 306 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, mat_, and Matrix().
Referenced by identityMatrix(), and inverse().
 {
     Matrix  *diag = new Matrix(nbRows, nbCols);
     int smallerDim = (nbRows < nbCols) ? nbRows : nbCols;
     for (int i = 0; i < smallerDim; i++)
         diag->mat_[i][i] = v;
     diag->isDiagonal_ = IS_TRUE;
     diag->isUpperTriangular_ = IS_TRUE;
     diag->isLowerTriangular_ = IS_TRUE;
     if (v != 0.L)
         {
         diag->isFullRank_ = IS_TRUE;
         }
     else
         {
         diag->isFullRank_ = IS_FALSE;
         }
     //  only a square matrix can be identity, symmetric, or antisymmetric
     if (nbRows == nbCols)
     {
         if (v == 1.L)
         {
             diag->isIdentity_ = IS_TRUE;
             diag->isOrthogonal_ = IS_TRUE;
         }
         else if (v == -1.L)
         {
             diag->isIdentity_ = IS_FALSE;
             diag->isOrthogonal_ = IS_TRUE;
         }
         else
         {
             diag->isIdentity_ = IS_FALSE;
             diag->isOrthogonal_ = IS_FALSE;
         }
         diag->isSymmetric_ = IS_TRUE;
         diag->isAntisymmetric_ = IS_TRUE;
     }
     else
     {
         diag->isIdentity_ = IS_FALSE;
         diag->isSymmetric_ = IS_FALSE;
         diag->isAntisymmetric_ = IS_FALSE;
         diag->isOrthogonal_ = IS_FALSE;
     }
     return diag;
 }
Matrix * Matrix::diagonalMatrix (int nbRows, int nbCols, const double * v) static
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
Parameters
nbRows number of rows of the new matrix
nbCols number of columnss of the new matrix
v value to assign to all diagonal elements
Returns
a new nbRows x nbCols diagonal matrix
Definition at line 360 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_FALSE, uriVL::IS_TRUE, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, uriVL::kNullParameterError, mat_, and Matrix().
 {
     FAIL_CONDITION( v == NULL,
                     kNullParameterError,
                     "Null array passed as parameter to Matrix::diagonalMatrix");
     Matrix  *diag = new Matrix(nbRows, nbCols);
     //  true no matter what v looks like
     diag->isDiagonal_ = IS_TRUE;
     diag->isUpperTriangular_ = IS_TRUE;
     diag->isLowerTriangular_ = IS_TRUE;
     //  subject to change
     diag->isFullRank_ = IS_TRUE;
     diag->isIdentity_ = IS_TRUE;
     if (nbRows != nbCols)
     {
         diag->isSymmetric_ = IS_FALSE;
         diag->isAntisymmetric_ = IS_FALSE;
         diag->isOrthogonal_ = IS_FALSE;
     }
     else
     {
         diag->isSymmetric_ = IS_TRUE;
         diag->isAntisymmetric_ = IS_TRUE;
         diag->isOrthogonal_ = IS_TRUE;
     }
     int smallerDim = (nbRows < nbCols) ? nbRows : nbCols;
     for (int i = 0; i < smallerDim; i++)
     {
         const double  vi = v[i];
         if (vi != 1.L)
             diag->isIdentity_ = IS_FALSE;
         else if (vi != -1.L)
             diag->isOrthogonal_ = IS_FALSE;
         else if (vi == 0.L)
         {
             diag->isFullRank_ = IS_FALSE;
         }
         diag->mat_[i][i] = vi;
     }
     return diag;
 }
void Matrix::difference_ (const double *const * a, const double *const * b, double *const * c, int m, int n) static private
Computes the difference of two matrices.
All dimension and allocation checkup is assumed to have been made prior to calling this function
Parameters
a left term of the matrix difference, dimensions m x n
b right term of the matrix difference, dimensions m x n
c result of the matrix sum, dimensions m x n
m number of rows of a, b, and of the difference matrix c
n number of columns of a, b, and of the difference matrix c
Definition at line 1386 of file Matrix.cpp.
 {
         for (int i=0; i<m; i++)
         {
                 for (int j=0; j<n; j++)
                 {
                         c[i][j] = a[i][j] - b[i][j];
                 }
     }
 }
void Matrix::enforceDiagonality (void)
Forces a matrix that passes the test for diagonality of checkIsDiagonal_ to be exactly diagonal.
Does so by setting to 0 all non-diagonal elements.
See also
isDiagonal_;
checkIsDiagonal
Definition at line 1135 of file Matrix.cpp.
References uriVL::IS_TRUE, isDiagonal_, mat_, nbCols_, and nbRows_.
 {
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             if (i!=j)
                 mat_[i][j] = 0.L;
     isDiagonal_ = IS_TRUE;
 }
void uriVL::Matrix::enforceIdentity (void)
Forces a matrix that passes the test for identity of checkIsIdentity_ to be exactly identity.
Does so by setting to 0 all non-diagonal elements and to 1 all diagonal elements.
See also
isIdentity_;
checkIsIddentity
void Matrix::enforceLowerTriangularity (void)
Forces a matrix that passes the test for lower-triangularity of checkIsLowerTriangular_ to be exactly lower-triangular.
Does so by setting to 0 all subdiagonal elements.
See also
isLowerTriangular_;
checkIsLowerTriangular
Definition at line 1157 of file Matrix.cpp.
References uriVL::IS_TRUE, isLowerTriangular_, mat_, nbCols_, and nbRows_.
 {
     const int iMax = nbRows_ > nbCols_ ? nbCols_ : nbRows_;
     //  set all superdiagonal elements to zero
     for (int i=0; i<iMax; i++)
         for (int j=i+1; j<nbCols_; j++)
             mat_[i][j] = 0.L;
     isLowerTriangular_ = IS_TRUE;
 }
void Matrix::enforceOthogonality (void)
Forces a matrix that passes the test for orthogonality of checkIsSymmetric_ to be exactly orthogonality.
Does so by applying an orthogonalization algorithm.
See also
isOrthogonal_;
checkIsOrthogonal
Definition at line 1128 of file Matrix.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "method not open for business yet");
 }
void Matrix::enforcesAntisymmetry (void)
Forces a matrix that passes the test for antisymmetry of checkIsAntisymmetric_ to be exactly antisymmetric.
Does so by replacing all element mat_[i][j] and mat_[i][j] by +/- 0.5*(mat_[i][j] - mat_[i][j]).
See also
isAntisymmmetric_;
checkIsAntisymmetric
Definition at line 1107 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_TRUE, isAntisymmetric_, uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
     FAIL_CONDITION(     nbRows_ != nbCols_,
                                 kMatrixIncorrectDimensionsError,
                                 "only square matrices can be forced to be symmetric");
     for (int i=0; i<nbRows_; i++)
     {
         for (int j=0; j<i; j++)
         {
             double midPt = 0.5L*(mat_[i][j] - mat_[j][i]);
             mat_[i][j] = midPt;
             mat_[j][i] = -midPt;
         }
         mat_[i][i] = 0.L;
     }
     isAntisymmetric_ = IS_TRUE;
 }
void Matrix::enforceSymmetry (void)
Forces a matrix that passes the test for symmetry of checkIsSymmetric_ to be exactly symmetric.
Does so by replacing all element mat_[i][j] and mat_[i][j] by 0.5*(mat_[i][j] + mat_[i][j]).
See also
isSymmmetric_
checkIsSymmetric
Definition at line 1091 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_TRUE, isSymmetric_, uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
     FAIL_CONDITION(     nbRows_ != nbCols_,
                                 kMatrixIncorrectDimensionsError,
                                 "only square matrices can be forced to be symmetric");
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<i; j++)
         {
             double midPt = 0.5L*(mat_[i][j] + mat_[j][i]);
             mat_[i][j] = mat_[j][i] = midPt;
         }
     isSymmetric_ = IS_TRUE;
 }
void Matrix::enforceUpperTriangularity (void)
Forces a matrix that passes the test for upper-triangularity of checkIsUpperTriangular_ to be exactly upper-triangular.
Does so by setting to 0 all superdiagonal elements.
See also
isUpperTriangular_;
checkIsUpperTriangular
Definition at line 1145 of file Matrix.cpp.
References uriVL::IS_TRUE, isUpperTriangular_, mat_, nbCols_, and nbRows_.
 {
     const int jMax = nbRows_ > nbCols_ ? nbCols_ : nbRows_;
     //  set all subdiagonal elements to zero
     for (int j=0; j<jMax; j++)
         for (int i=j+1; i<nbRows_; i++)
             mat_[i][j] = 0.L;
     isUpperTriangular_ = IS_TRUE;
 }
const double *const * Matrix::getMatrix (void) const
Returns a read-only pointer to the matrix data.
If you want to have full read-write access to the data, call instead getMatrixRW.
Returns
the matrice's private read-only 2D array of data
Definition at line 461 of file Matrix.cpp.
References mat_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::LinearSolver_GaussSeidel::checkMatrixStatus_(), uriVL::LinearSolver_SOR::checkMatrixStatus_(), uriVL::LinearSolver_Jacobi::checkMatrixStatus_(), uriVL::LinearSolver_SVD::factorize_(), uriVL::FunctionND::func(), uriVL::FunctionND::gradient(), uriVL::FunctionND::hessian(), uriVL::FunctionND::isDefinedAt(), uriVL::LinearSolver_LU::LinearSolver_LU(), uriVL::LinearSolver_QR::LinearSolver_QR(), main(), uriVL::RigidTransformation3D::postComposeTransformation(), uriVL::RigidTransformation3D::RigidTransformation3D(), uriVL::Rotation3D::Rotation3D(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_LU::setMatrix(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_LU::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_Jacobi::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_LU::solve_(), uriVL::LinearSolver_QR::solve_(), uriVL::LinearSolver_SOR::solve_(), uriVL::LinearSolver_Jacobi::solve_(), uriVL::LinearSolver_GaussSeidel::solve_(), uriVL::LinearSolver_SVD::solve_(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), and uriVL::RigidTransformation3D::updateMatrix_().
 {
     return mat_;
 }
double *const * Matrix::getMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
As a side effect, this function sets to IS_UNKNOWN all the matrix's indicators.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the matrix's private read-write 2D array of data
Definition at line 447 of file Matrix.cpp.
References uriVL::IS_UNKNOWN, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, and mat_.
 {
     isDiagonal_ = IS_UNKNOWN;
     isIdentity_ = IS_UNKNOWN;
     isUpperTriangular_ = IS_UNKNOWN;
     isLowerTriangular_ = IS_UNKNOWN;
     isFullRank_ = IS_UNKNOWN;
     isSymmetric_ = IS_UNKNOWN;
     isAntisymmetric_ = IS_UNKNOWN;
     isOrthogonal_ = IS_UNKNOWN;
     return mat_;
 }
int Matrix::getNbCols (void) const
This function returns a int corresponding to the number of columns in this
Returns
the number of columns in this matrix
Definition at line 442 of file Matrix.cpp.
References nbCols_.
Referenced by uriVL::LinearSolver_SVD::factorize_(), uriVL::LinearSolver_GaussSeidel::LinearSolver_GaussSeidel(), uriVL::LinearSolver_Jacobi::LinearSolver_Jacobi(), uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_SOR::LinearSolver_SOR(), uriVL::LinearSolver_SVD::LinearSolver_SVD(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_LU::setMatrix(), uriVL::LinearSolver_SVD::setMatrix(), uriVL::LinearSolver_Cholesky::solve(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_Jacobi::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_LU::solve(), uriVL::LinearSolver_SVD::solve(), uriVL::LinearSolver_LU::solve_(), uriVL::LinearSolver_QR::solve_(), uriVL::LinearSolver_SOR::solve_(), uriVL::LinearSolver_Jacobi::solve_(), uriVL::LinearSolver_GaussSeidel::solve_(), and uriVL::LinearSolver_SVD::solve_().
 {
     return nbCols_;
 }
int Matrix::getNbRows (void) const
This function returns a int corresponding to the number of rows in this
Returns
the number of rows in this matrix
Definition at line 437 of file Matrix.cpp.
References nbRows_.
Referenced by uriVL::LinearSolver_GaussSeidel::checkMatrixStatus_(), uriVL::LinearSolver_Jacobi::checkMatrixStatus_(), uriVL::LinearSolver_SOR::checkMatrixStatus_(), uriVL::LinearSolver_SVD::factorize_(), uriVL::LinearSolver_GaussSeidel::LinearSolver_GaussSeidel(), uriVL::LinearSolver_Jacobi::LinearSolver_Jacobi(), uriVL::LinearSolver_QR::LinearSolver_QR(), uriVL::LinearSolver_SOR::LinearSolver_SOR(), uriVL::LinearSolver_SVD::LinearSolver_SVD(), uriVL::LinearSolver_QR::setMatrix(), uriVL::LinearSolver_SOR::setMatrix(), uriVL::LinearSolver_Jacobi::setMatrix(), uriVL::LinearSolver_GaussSeidel::setMatrix(), uriVL::LinearSolver_LU::setMatrix(), uriVL::LinearSolver_SVD::setMatrix(), uriVL::LinearSolver_Cholesky::solve(), uriVL::LinearSolver_QR::solve(), uriVL::LinearSolver_GaussSeidel::solve(), uriVL::LinearSolver_Jacobi::solve(), uriVL::LinearSolver_SOR::solve(), uriVL::LinearSolver_LU::solve(), uriVL::LinearSolver_SVD::solve(), uriVL::LinearSolver_LU::solve_(), uriVL::LinearSolver_QR::solve_(), uriVL::LinearSolver_Jacobi::solve_(), uriVL::LinearSolver_GaussSeidel::solve_(), uriVL::LinearSolver_SOR::solve_(), and uriVL::LinearSolver_SVD::solve_().
 {
     return nbRows_;
 }
Matrix * Matrix::identityMatrix (int n) static
Produces a new identity matrix at the dimensions specified.
To produce a non-square matrix with a unit diagonal, use diagonalMatrix instead.
Parameters
n size of the new matrix
Returns
a new n x n identity matrix
Definition at line 300 of file Matrix.cpp.
References diagonalMatrix().
Referenced by inverse(), and uriVL::Rotation3D::Rotation3D().
 {
     return diagonalMatrix(n, n, 1.L);
 }
Matrix * Matrix::inverse (void) const virtual
This function creates a new Matrix corresponding to the inverse of this (if nonsingular).
It then returns a reference to that inverse.
Returns
a reference to the inverse of this
Definition at line 1246 of file Matrix.cpp.
References determinant(), diagonalMatrix(), FAIL_CONDITION, identityMatrix(), uriVL::IS_TRUE, isDiagonal_, isIdentity_, isOrthogonal_, uriVL::kNumericalError, mat_, nbCols_, nbRows_, and transposition().
Referenced by invert().
 {
     FAIL_CONDITION( nbRows_ != nbCols_,
                     kNumericalError,
                     "Not a square matrix in Matrix::inverse()");
     //------------------------------------------------------------
     //  Special cases: exact properties
     //------------------------------------------------------------
     if (isIdentity_ == IS_TRUE)
         return Matrix::identityMatrix(nbRows_);
     //
     else if (isDiagonal_ == IS_TRUE)
     {
         double  *v = new double[nbRows_];
         for (int i=0; i<nbRows_; i++)
         {
             FAIL_CONDITION( mat_[i][i] == 0.L,
                             kNumericalError,
                             "Attempt to invert a singular diagonal matrix");
             v[i] = 1.L / mat_[i][i];
         }
         Matrix *x = Matrix::diagonalMatrix(nbRows_, nbRows_, v);
         delete []v;
         return x;
     }
     //
     else if (isOrthogonal_ == IS_TRUE)
     {
         return transposition();
     }
 //  This is completely absurd:  The LU factorization is done twice!!
     double det = this->determinant();
     FAIL_CONDITION( det == 0,
     kNumericalError,
     "Not a nonsingular matrix in Matrix::inverse()");
 /*
     Matrix* i = Matrix::identityMatrix(nbRows_);
   LinearSolver_LU* myLU = new LinearSolver_LU();
     Matrix* x = myLU->solve(this,i);
     delete i;
     delete myLU;
     x->isDiagonal_ = isDiagonal_;
     x->isIdentity_ = isIdentity_;
     if (isUpperTriangular_ == IS_TRUE)
         x->isUpperTriangular_ = IS_APPROX_TRUE;
     else
         x->isUpperTriangular_ = isUpperTriangular_;
     if (isLowerTriangular_ == IS_TRUE)
         x->isLowerTriangular_ = IS_APPROX_TRUE;
     else
         x->isLowerTriangular_ = isLowerTriangular_;
     x->isFullRank_ = IS_TRUE;
     x->isSymmetric_ = isSymmetric_;
     x->isAntisymmetric_ = isAntisymmetric_;
     x->isOrthogonal_ = isOrthogonal_;
     return x;
 */
 return NULL;
 }
void Matrix::invert (void) virtual
This function inverts this (if nonsingular), thereby modifying this.
Definition at line 1315 of file Matrix.cpp.
References inverse(), isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, mat_, nbCols_, and nbRows_.
 {
     Matrix* x = inverse();
     double** xMat = x->mat_;
     for (int i = 0; i < nbRows_; i++)
         for (int j = 0; j < nbCols_; j++)
             mat_[i][j] = xMat[i][j];
     isDiagonal_ = x->isDiagonal_;
     isIdentity_ = x->isIdentity_;
     isUpperTriangular_ = x->isUpperTriangular_;
     isLowerTriangular_ = x->isLowerTriangular_;
     isFullRank_ = x->isFullRank_;
     isSymmetric_ = x->isSymmetric_;
     isAntisymmetric_ = x->isAntisymmetric_;
     isOrthogonal_ = x->isOrthogonal_;
     delete x;
 }
TriState Matrix::isAntisymmetric (void)
Check whether the matrix is antisymmetric.
A "real-world" matrix is never exactly antisymmetric unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost antisymmetric" status can call checkAntisymmetryStatus() and then decide whether or not to "enforce" symmetry by calling enforceAntisymmetry(). This function updates the isAntisymmmetric_ indicator.
See also
isAntisymmmetric_;
checkAntisymmetryStatus
enforceAntisymmetry
Returns
antisymmetry test result as IS_TRUE or IS_FALSE
Definition at line 912 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isAntisymmetric_, mat_, MATRIX_PROP_ABS_TOL, MATRIX_PROP_REL_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
 {
     double  maxDev = 0.L, dev;
     if (nbRows_ == nbCols_)
     {
         for (int i=0; i<nbRows_; i++)
         {
             //  Check nondiagonal elements
             for (int j=0; j<i; j++)
             {
                 if (mat_[i][j] != 0.L)
                 {
                     dev = fabs(mat_[i][j] + mat_[j][i]);
                     if (dev > MATRIX_PROP_REL_TOL*fabs(mat_[i][j]))
                         return (isAntisymmetric_ = IS_FALSE);
                     if (dev > maxDev)
                         maxDev = dev;
                 }
                 else
                 {
                     dev = fabs(mat_[j][i]);
                     if (dev > MATRIX_PROP_ABS_TOL)
                         return (isAntisymmetric_ = IS_FALSE);
                     if (dev > maxDev)
                         maxDev = dev;
                 }
             }
             //  Now check the diagonal element for this row
             dev = fabs(mat_[i][i]);
             if (dev > MATRIX_PROP_ABS_TOL)
                 return (isAntisymmetric_ = IS_FALSE);
             if (dev > maxDev)
                 maxDev = dev;
         }
         //   if we made it all the way here, then the matrix is antisymmetric
         if (maxDev < STD_RELATIVE_TOLERANCE)
             return (isAntisymmetric_ = IS_TRUE);
         else
             return (isAntisymmetric_ = IS_FALSE);
     }
     else
         return (isAntisymmetric_ = IS_FALSE);
 }
TriState Matrix::isDiagonal (void)
Check whether the matrix is diagonal.
A "real-world" matrix is never exactly diagonal unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost diagonal" status can call checkDiagonalityStatus() and then decide whether or not to "enforce" diagonality by calling enforceDiagonality(). This function updates the isDiagonal_ indicator.
See also
isDiagonal_;
checkDiagonalityStatus
enforceDiagonality
Returns
diagonality test result as IS_TRUE or IS_FALSE
Definition at line 975 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isDiagonal_, isLowerTriangular(), and isUpperTriangular().
Referenced by isIdentity().
 {
     //  The matrix is diagonal iff it is both upper-diagonal and lower_diagonal
     if (isUpperTriangular() == IS_TRUE)
     {
         isLowerTriangular();
         if (isLowerTriangular() == IS_TRUE)
             return  (isDiagonal_ = IS_TRUE);
         else
             return (isDiagonal_ = IS_FALSE);
     }
     else
         return (isDiagonal_ = IS_FALSE);
 }
TriState Matrix::isIdentity (void)
Check whether the matrix is an identity matrix.
A "real-world" matrix is never exactly identity unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost identity" status can call checkIdentityStatus() and then decide whether or not to "enforce" symmetry by calling enforceIdentity(). This function updates the isIdentity_ indicator.
See also
isIdentity_;
checkIdentityStatus
enforceIdentity
Returns
identity test result as IS_TRUE or IS_FALSE
Definition at line 993 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isDiagonal(), isIdentity_, mat_, MATRIX_PROP_REL_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
 {
     if (nbRows_ == nbCols_)
     {
         if (isDiagonal() == IS_TRUE)
         {
             double maxDev = 0.L;
             for (int i=0; i<nbRows_; i++)
             {
                 double dev = fabs(mat_[i][i] - 1.L);
                 if (dev > MATRIX_PROP_REL_TOL)
                     return (isIdentity_ = IS_FALSE);
                 if (dev > maxDev)
                     maxDev = dev;
             }
             //   if we made it all the way here, then the matrix is indetity
             if (maxDev < STD_RELATIVE_TOLERANCE)
                 return (isIdentity_ = IS_TRUE);
             else
                 return (isIdentity_ = IS_FALSE);
         }
         else
             return (isIdentity_ = IS_FALSE);
     }
     else
         return (isIdentity_ = IS_FALSE);
 }
TriState Matrix::isLowerTriangular (void)
Check whether the matrix is lower-triangular.
A "real-world" matrix is never exactly lower-triangular unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost lower-triangular" status can call checkLowerTriangularityStatus() and then decide whether or not to "enforce" symmetry by calling enforceLowerTriangularity_(). This function updates isLowerTriangular_ indicator.
See also
isLowerTriangular_;
checkLowerTriangularityStatus
enforceLowerTriangularity
Returns
lower-triangularity test result as IS_TRUE or IS_FALSE
Definition at line 1055 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isLowerTriangular_, mat_, MATRIX_PROP_ABS_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
Referenced by isDiagonal().
 {
     const int iMax = nbRows_ > nbCols_ ? nbCols_ : nbRows_;
     double  maxDev = 0.L, dev;
     //  check that all superdiagonal elements are nearly equal to zero
     for (int i=0; i<iMax; i++)
     {
         for (int j=i+1; j<nbCols_; j++)
         {
             dev = fabs(mat_[i][j]);
             if (dev > MATRIX_PROP_ABS_TOL)
                 return (isLowerTriangular_ = IS_FALSE);
             if (dev > maxDev)
                 maxDev = dev;
         }
     }
     //   if we made it all the way here, then the matrix is lower-triangular
     if (maxDev < STD_RELATIVE_TOLERANCE)
         return (isLowerTriangular_ = IS_TRUE);
     else
         return (isLowerTriangular_ = IS_FALSE);
 }
TriState Matrix::isOrthogonal (void)
Check whether the matrix is orthogonal.
A "real-world" matrix is never exactly orthogonal unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost orthogonal" status can call checkOrthogonalityStatus() and then decide whether or not to "enforce" symmetry by calling enforceAntisymmetry(). The user can decide to "enforce" orthogonality by calling enforceOthogonality(). This function updates the isOrthogonal_ indicator.
See also
isOrthogonal_;
checkOrthogonalityStatus
enforceOthogonality
Returns
orthogonality test result as IS_TRUE or IS_FALSE
Definition at line 966 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_UNKNOWN, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "method not open for business yet");
     return IS_UNKNOWN;
 }
TriState Matrix::isSymmetric (void)
Check whether the matrix is symmetric.
A "real-world" matrix is never exactly symmetric unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost symmetric" status can call checkSymmetryStatus() and then decide whether or not to "enforce" symmetry by calling enforceSymmetry(). This function updates the isSymmmetric_ indicator.
See also
isSymmmetric_
checkSymmetryStatus
enforceSymmetry
Returns
symmetry test result as IS_TRUE or IS_FALSE
Definition at line 869 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isSymmetric_, mat_, MATRIX_PROP_ABS_TOL, MATRIX_PROP_REL_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
 {
     double  maxDev = 0.L;
     if (nbRows_ == nbCols_)
     {
         for (int i=0; i<nbRows_; i++)
         {
             for (int j=0; j<i; j++)
             {
                 if (mat_[i][j] != 0.L)
                 {
                     double dev = fabs(mat_[i][j] - mat_[j][i]);
                     if (dev > MATRIX_PROP_REL_TOL*fabs(mat_[i][j]))
                         return (isSymmetric_ = IS_FALSE);
                     if (dev > maxDev)
                         maxDev = dev;
                 }
                 else
                 {
                     double dev = fabs(mat_[j][i]);
                     if (dev > MATRIX_PROP_ABS_TOL)
                     if (dev > maxDev)
                         maxDev = dev;
                 }
             }
         }
         //   if we made it all the way here, then the matrix is symmetric
         if (maxDev < STD_RELATIVE_TOLERANCE)
             return (isSymmetric_ = IS_TRUE);
         else
             return IS_FALSE;
     }
     else
         return (isSymmetric_ = IS_FALSE);
 }
TriState Matrix::isUpperTriangular (void)
Check whether the matrix is upper-triangular.
A "real-world" matrix is never exactly upper-triangular unless it was explicitly created that way. This function checks the property within a fixed relative tolerance. The user wishing a finer control of "almost upper-triangular" status can call checkUpperTriangularityStatus() and then decide whether or not to "enforce" symmetry by calling enforceUpperTriangularity_(). This function updates isUpperTriangular_ indicator.
See also
isUpperTriangular_;
checkUpperTriangularityStatus
enforceUpperTriangularity
Returns
upper-triangularity test result as IS_TRUE or IS_FALSE
Definition at line 1027 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, isUpperTriangular_, mat_, MATRIX_PROP_ABS_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
Referenced by isDiagonal().
 {
     double  maxDev = 0.L, dev;
     const int jMax = nbRows_ > nbCols_ ? nbCols_ : nbRows_;
     //  check that all subdiagonal elements are nearly equal to zero
     for (int j=0; j<jMax; j++)
     {
         for (int i=j+1; i<nbRows_; i++)
         {
             dev = fabs(mat_[i][j]);
             if (dev > MATRIX_PROP_ABS_TOL)
                 return (isUpperTriangular_ = IS_FALSE);
             if (dev > maxDev)
                 maxDev = dev;
         }
     }
     //   if we made it all the way here, then the matrix is upper-triangular
     if (maxDev < STD_RELATIVE_TOLERANCE)
         return (isUpperTriangular_ = IS_TRUE);
     else
         return (isUpperTriangular_ = IS_FALSE);
 }
void Matrix::killMat_ (void) private
Deletes and nullifies the 2D array, mat_.
Definition at line 1502 of file Matrix.cpp.
References mat_, nbStorageRows_, and storageIsLocal_.
Referenced by operator*=(), operator=(), preMultiplyBy(), and transpose().
 {
     if (storageIsLocal_)
     {
         for (int i = 0; i < nbStorageRows_; i++)
             delete[] mat_[i];
         delete[] mat_;
     }
     mat_ = NULL;
 }
double Matrix::norm1 (void) const
This function returns a double corresponding to the "1" norm of the Matrix this.
Returns
the "1" norm of this
Definition at line 843 of file Matrix.cpp.
References mat_, nbCols_, and nbRows_.
Referenced by uriVL::RowVector::normalize1(), and uriVL::ColumnVector::normalize1().
 {
     double  maxVal = 0.L, colSum;
     for (int j=1; j<nbCols_; j++)
     {
         colSum = 0.f;
         for (int i=0; i<nbRows_; i++)
             colSum += fabs(mat_[i][j]);
         if (colSum > maxVal)
             maxVal = colSum;
     }
   return maxVal;
 }
double Matrix::normInf (void) const
This function returns a double corresponding to the "Infinity" norm of the Matrix this.
Returns
the "Infinity" norm of this
Definition at line 824 of file Matrix.cpp.
References mat_, nbCols_, and nbRows_.
Referenced by uriVL::RowVector::normalizeInf(), and uriVL::ColumnVector::normalizeInf().
 {
     double  maxVal = 0.L, rowSum;
     for (int i=0; i<nbRows_; i++)
     {
         rowSum = 0.L;
         for (int j=0; j<nbCols_; j++)
             rowSum += fabs(mat_[i][j]);
         if (rowSum  > maxVal)
             maxVal = rowSum;
     }
   return maxVal;
 }
static Matrix* uriVL::Matrix::nullMatrix (int nbRows, int nbCols) static
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements to zero.
Parameters
nbRows number of rows of the new matrix
nbCols number of columnss of the new matrix
Returns
a new nbRows x nbCols null matrix
double Matrix::operator() (int theRow, int theCol) const
This function returns the element of the Matrix at row theRow and column theCol.
When accessing an element of the matrix, the indices are directly related to the structure of the 2D-array storing them, not the row and column containing it.
Parameters
theRow the row of the element to return
theCol the column of the element to return
Returns
the element at theRow,theCol
Definition at line 467 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
   FAIL_CONDITION( (theRow < 0) || (theCol < 0) || (theRow >= nbRows_) || (theCol >= nbCols_),
                   kMatrixIncorrectDimensionsError,
                   "dimension error in Matrix::()");
   return mat_[theRow][theCol];
 }
void Matrix::operator*= (const double s) virtual
This function multiplies every element of this by the scalar parameter thereby modifying this.
Parameters
s the scalar by which to multiply each element of this
Definition at line 596 of file Matrix.cpp.
References mat_, nbCols_, and nbRows_.
 {
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] *= s;
 }
void Matrix::operator*= (const Matrix & b) virtual
This function premultiplies the parameter Matrix b by this thereby modifying this.
Parameters
b the matrix that is premultiplied by this
Definition at line 632 of file Matrix.cpp.
References FAIL_CONDITION, killMat_(), uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
         FAIL_CONDITION( b.nbRows_ != nbCols_,
                       kMatrixIncorrectDimensionsError,
                       "parameter has incorrect dimensions in Matrix::*=");
         double** c = new double*[nbRows_];
         for (int i=0; i<nbRows_; i++)
                 c[i] = new double[b.nbCols_];
         for (int i=0; i<nbRows_; i++)
                 for (int j=0; j<b.nbCols_; j++)
                 {
                         c[i][j] = 0.L;
                         for (int k=0; k<nbCols_; k++)
                                 c[i][j] += mat_[i][k] * b.mat_[k][j];
                 }
         killMat_();
         mat_ = c;
         nbCols_ = b.nbCols_;
 }
void Matrix::operator+= (const Matrix & b)
This function adds the parameter Matrix b to this thereby modifying this.
Parameters
b the Matrix to add to this
Definition at line 537 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
     FAIL_CONDITION( (b.nbRows_ != nbRows_) || (b.nbCols_ != nbCols_),
                     kMatrixIncorrectDimensionsError,
                     "parameter has incorrect dimensions in Matrix::operator +=");
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] += b.mat_[i][j];
 }
void Matrix::operator-= (const Matrix & b) virtual
This function subtracts the parameter Matrix from this thereby modifying this.
Parameters
b the Matrix to subtract from this
Definition at line 551 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, mat_, nbCols_, and nbRows_.
 {
     FAIL_CONDITION( (b.nbRows_ != nbRows_) || (b.nbCols_ != nbCols_),
                     kMatrixIncorrectDimensionsError,
                     "parameter has incorrect dimensions in Matrix::subtractFrom");
     for (int i=0; i<nbRows_; i++)
         for (int j=0; j<nbCols_; j++)
             mat_[i][j] -= b.mat_[i][j];
 }
const Matrix & Matrix::operator= (const Matrix & b)
Assigns to this matrix the matrix received as parameter (resizes it if necessary.
Parameters
b the matrix to set this object equal to
Definition at line 701 of file Matrix.cpp.
References killMat_(), mat_, nbCols_, and nbRows_.
 {
     //  if the dimensions don't match, delete this matrix an reallocate it.
     if ((nbRows_ != b.nbRows_) || (nbCols_ != b.nbCols_))
     {
         killMat_();
         nbRows_ = b.nbRows_;
         nbCols_= b.nbCols_;
         mat_ = new double*[nbRows_];
         for (int i=0; i<nbRows_; i++)
         {
             mat_[i] = new double[nbCols_];
             for (int j=0; j<nbCols_; j++)
                 mat_[i][j] = b.mat_[i][j];
         }
     }
     else
     {
         for (int i=0; i<nbRows_; i++)
             for (int j=0; j<nbCols_; j++)
                 mat_[i][j] = b.mat_[i][j];
     }
     return *this;
 }
TriState Matrix::operator== (const Matrix & b) const
This function does an element-wise comparison to the parameter Matrix b with this.
Matrix b == this iff:
i. the dimensions are same AND ii. all elements are the same
Parameters
b the matrix to compare this one to
Returns
a quadstate indicate if the matrics are equal, nearly equal, or different
Definition at line 730 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, mat_, MATRIX_PROP_REL_TOL, nbCols_, nbRows_, and STD_RELATIVE_TOLERANCE.
 {
     if ((b.nbRows_ == nbRows_) && (b.nbCols_ == nbCols_))
     {
         double maxDev = 0.L;
         for (int i = 0; i < nbRows_; i++)
             for (int j = 0; j < nbCols_; j++)
             {
                 double dev = fabs(mat_[i][j] - b.mat_[i][j]);
                 if (dev > MATRIX_PROP_REL_TOL*fabs(mat_[i][j]))
                     return IS_FALSE;
                 if (dev > maxDev)
                     maxDev = dev;
             }
         //   if we made it all the way here, then the matrix is symmetric
         if (maxDev < STD_RELATIVE_TOLERANCE)
             return IS_TRUE;
         else
             return IS_FALSE;
     }
     else
         return IS_FALSE;
 }
void Matrix::postMultiplyBy (const Matrix * b) virtual
This function postmultiplies this by the parameter Matrix b thereby modifying this
Parameters
b the matrix that is postmultiplying this
Definition at line 685 of file Matrix.cpp.
References FAIL_CONDITION, and uriVL::kNullParameterError.
 {
     FAIL_CONDITION( b == NULL,
                     kNullParameterError,
                     "Null parameter in Matrix::postMultiplyBy");
     (*this) *= (*b);
 }
void Matrix::preMultiplyBy (const Matrix * b) virtual
This function premultiplies this by the parameter Matrix b thereby modifying this
Parameters
b the matrix that is premultiplying this
Definition at line 657 of file Matrix.cpp.
References FAIL_CONDITION, killMat_(), uriVL::kMatrixIncorrectDimensionsError, uriVL::kNullParameterError, mat_, nbCols_, and nbRows_.
 {
     FAIL_CONDITION( b == NULL,
                     kNullParameterError,
                     "Null parameter in Matrix::postMultiplyBy");
         FAIL_CONDITION( b->nbCols_ != nbRows_,
                       kMatrixIncorrectDimensionsError,
                       "parameter has incorrect dimensions in Matrix::postMultiplyBy");
     const int   newRows = b->nbRows_;
         double** c = new double*[newRows];
         for (int i=0; i<newRows; i++)
                 c[i] = new double[nbCols_];
         for (int i=0; i<newRows; i++)
                 for (int j=0; j<nbCols_; j++)
                 {
                         c[i][j] = 0.L;
                         for (int k=0; k<nbRows_; k++)
                                 c[i][j] += b->mat_[i][k]*mat_[k][j];
                 }
         killMat_();
         mat_ = c;
         nbRows_ = newRows;
 }
void Matrix::product_ (const double *const * a, const double *const * b, double *const * c, int m, int n, int p) static private
Computes the product of two matrices.
All dimension and allocation checkup is assumed to have been made prior to calling this function
Parameters
a left term of the matrix product, dimensions m x n
b right term of the matrix product, dimensions n x p
c result of the matrix product, dimensions m x p
m number of rows of a and of the product matrix c
n number of columns of a and of rows of b
m number of columns of b and of the product matrix c
Definition at line 1397 of file Matrix.cpp.
 {
         for (int i=0; i<m; i++)
         {
                 for (int j=0; j<p; j++)
                 {
                         c[i][j] = 0.L;
                         for (int k=0; k<n; k++)
                                 c[i][j] += a[i][k] * b[k][j];
                 }
     }
 }
Matrix * Matrix::randomMatrix (int nbRows, int nbCols, double lowerBound, double upperBound) static
produces a new matrix filled with random values between lowerBound (inclusive) and upperBound (exclusive)
Parameters
nbRows the number of rows in the matrix
nbCols the number of columns in the matrix
lowerBound lower bound for the range of random values
upperBound upper bound for the range of random values
Returns
a new nbRows x nbCols random matrix
Definition at line 408 of file Matrix.cpp.
References uriVL::IS_FALSE, uriVL::IS_UNKNOWN, isAntisymmetric_, isDiagonal_, isFullRank_, isIdentity_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, mat_, Matrix(), and uriVL::RandomGenerator_C::nextDouble_st().
 {
     Matrix *m = new Matrix(nbRows, nbCols);
     for (int i = 0; i < nbRows; i++)
         for (int j = 0; j < nbCols; j++)
             m->mat_[i][j] = RandomGenerator_C::nextDouble_st(upperBound, lowerBound);
     m->isDiagonal_ = IS_FALSE;
     m->isIdentity_ = IS_FALSE;
     m->isUpperTriangular_ = IS_FALSE;
     m->isLowerTriangular_ = IS_FALSE;
     m->isFullRank_ = IS_UNKNOWN;
     m->isSymmetric_ = IS_FALSE;
     m->isAntisymmetric_ = IS_FALSE;
     m->isOrthogonal_ = IS_FALSE;
     return m;
 }
void Matrix::rowSwap (int r1, int r2)
This function swaps rows of the Matrix (rather, of mat_)
Parameters
r1 the first row to swap
r2 the second row to swap
Definition at line 769 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::IS_UNKNOWN, isAntisymmetric_, isDiagonal_, isFullRank_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, uriVL::kInvalidParameterError, mat_, and nbRows_.
 {
     FAIL_CONDITION ( (r1 < 0) || (r2 < 0) || (r1 >= nbRows_) || (r2 >= nbRows_),
                      kInvalidParameterError,
                      "Invalid row choices in Matrix::rowSwap");
     if (r1 != r2)
     {
         double* temp = mat_[r1];
         mat_[r1] = mat_[r2];
         mat_[r2] = temp;
         //  row swap pretty much breaks all properties
         isDiagonal_ = IS_UNKNOWN;
         isUpperTriangular_ = IS_UNKNOWN;
         isLowerTriangular_ = IS_UNKNOWN;
         isFullRank_ = IS_UNKNOWN;
         isSymmetric_ = IS_UNKNOWN;
         isAntisymmetric_ = IS_UNKNOWN;
         isOrthogonal_ = IS_UNKNOWN;
     }
 }
void Matrix::setToStringFormat (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) static
This function resets the delimiting strings used when generating a string representation for a given matrix.
Parameters
theBeginArrayStr the string used to denote the beginning of the array
theEndArrayStr the string used to denote the end of the array
theElmtSepStr the string used to denote the seperation of elements
theEolAtEor a bool describing whether per-row end of lines should be used
Definition at line 1471 of file Matrix.cpp.
References beginArrayStr_, elmtSepStr_, endArrayStr_, eolAtEor_, FAIL_CONDITION, and uriVL::kInvalidParameterError.
 {
   FAIL_CONDITION ( (theBeginArrayStr.length()==0) || (theEndArrayStr.length()==0) || (theElmtSepStr.length()==0),
                    kInvalidParameterError,
                    "Null seperator string");
   beginArrayStr_ = theBeginArrayStr;
   endArrayStr_ = theEndArrayStr;
   elmtSepStr_ = theElmtSepStr;
   eolAtEor_ = theEolAtEor;
 }
void Matrix::sum_ (const double *const * a, const double *const * b, double *const * c, int m, int n) static private
Computes the sum of two matrices.
All dimension and allocation checkup is assumed to have been made prior to calling this function
Parameters
a left term of the matrix sum, dimensions m x n
b right term of the matrix sum, dimensions m x n
c result of the matrix sum, dimensions m x n
m number of rows of a, b, and of the sum matrix c
n number of columns of a, b, and of the sum matrix c
Definition at line 1375 of file Matrix.cpp.
 {
         for (int i=0; i<m; i++)
         {
                 for (int j=0; j<n; j++)
                 {
                         c[i][j] = a[i][j] + b[i][j];
                 }
     }
 }
string Matrix::toString (void) const
This function returns a string corresponding to the matrix using the static delimiting strings for the Matrix class.
Definition at line 1420 of file Matrix.cpp.
References beginArrayStr_, elmtSepStr_, endArrayStr_, and eolAtEor_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), and main().
 {
   return toString(beginArrayStr_, endArrayStr_, elmtSepStr_, eolAtEor_);
 }
string Matrix::toString (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) const
This function returns a string corresponding to the matrix using the parameters as delimiting strings.
Parameters
theBeginArrayStr the string used to denote the beginning of the array
theEndArrayStr the string used to denote the end of the array
theElmtSepStr the string used to denote the seperation of elements
theEolAtEor a bool describing whether per-row end of lines should be used
Definition at line 1426 of file Matrix.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, mat_, nbCols_, and nbRows_.
 {
   FAIL_CONDITION ( (theBeginArrayStr.length()==0) || (theEndArrayStr.length()==0) || (theElmtSepStr.length()==0),
                    kInvalidParameterError,
                    "Null seperator string");
   string  outStr, myEndRow;
   if (theEolAtEor)
     myEndRow = "\n";
   else
     myEndRow = "";
   outStr = theBeginArrayStr;    //  beginning of the array, say "{"
   for (int i=0; i<nbRows_; i++)
   {
     outStr.append(theBeginArrayStr);
     std::ostringstream o;
     o << mat_[i][0];
     outStr.append(o.str());
     for (int j=1; j<nbCols_; j++)
     {
       outStr.append(theElmtSepStr);
       std::ostringstream m;
       m << mat_[i][j];
       outStr.append(m.str());
     }
     outStr.append(theEndArrayStr);
     if (i!=nbRows_-1)
     {
       outStr.append(theElmtSepStr);
       outStr.append(myEndRow);
     }
     else
       outStr.append(theEndArrayStr);
   }
   return outStr;
 }
void Matrix::transpose (void) virtual
This function transposes this, thereby altering this.
Definition at line 1202 of file Matrix.cpp.
References isLowerTriangular_, isUpperTriangular_, killMat_(), mat_, nbCols_, and nbRows_.
 {
     //  if the matrix is not sqaure, we need to allocate a new array
     if (nbRows_ != nbCols_)
     {
         double** mat2_ = new double*[nbCols_];
         for (int i=0; i < nbCols_; i++)
             mat2_[i] = new double[nbRows_];
         for (int i=0; i<nbCols_; i++)
             for (int j=0; j<nbRows_; j++)
                 mat2_[i][j] = mat_[j][i];
         killMat_();
         mat_ = mat2_;
     }
     //  otherwise we transpose within the array
     else
     {
         for (int i=0; i<nbRows_; i++)
             for (int j=0; j<i; j++)
             {
                 double temp = mat_[i][j];
                 mat_[i][j] = mat_[j][i];
                 mat_[i][j] = temp;
             }
     }
     //  update properties of the matrix
     TriState tempProp = isUpperTriangular_;
     isUpperTriangular_ = isLowerTriangular_;
     isLowerTriangular_ = tempProp;
 }
Matrix * Matrix::transposition (void) const virtual
This function returns a reference to a new Matrix object, the transposition of this matrix.
Returns
a reference to the transposition of this matrix
Reimplemented in uriVL::ColumnVector, and uriVL::RowVector.
Definition at line 1180 of file Matrix.cpp.
References isAntisymmetric_, isDiagonal_, isFullRank_, isLowerTriangular_, isOrthogonal_, isSymmetric_, isUpperTriangular_, mat_, Matrix(), nbCols_, and nbRows_.
Referenced by inverse(), and main().
 {
     Matrix  *b = new Matrix(nbCols_, nbRows_);
     double** bMat = b->mat_;
     //  This can be optimized based on the matrix's properties
     for (int i=0; i<nbCols_; i++)
         for (int j=0; j<nbRows_; j++)
             bMat[i][j] = mat_[j][i];
     //  update properties of matrix b
     b->isDiagonal_ = isDiagonal_;
     b->isUpperTriangular_ = isLowerTriangular_;
     b->isLowerTriangular_ = isUpperTriangular_;
     b->isFullRank_ = isFullRank_;
     b->isSymmetric_ = isSymmetric_;
     b->isAntisymmetric_ = isAntisymmetric_;
     b->isOrthogonal_ = isOrthogonal_;
     return b;
 }
Friends And Related Function Documentation
friend class ColumnVector friend
Definition at line 65 of file Matrix.h.
friend class HomogeneousMatrix friend
Definition at line 67 of file Matrix.h.
const Matrix operator* (const Matrix & a, const Matrix & b) friend
This operator creates a new Matrix equal to the sum of the two terms.
Throws an exception if the matrices' dimensions do not match.
Parameters
a left term in the addition
b right term in the addition
Returns
a reference to a + b This operator creates a new Matrix equal to the difference of the two terms. Throws an exception if the matrices' dimensions do not match.
Parameters
a left term in the difference
b right term in the difference
Returns
a reference to a - b This operator creates a new Matrix equal to the product of the two terms. Throws an exception if the matrices' dimensions do not match (number of columns of the left term should be equal to the number of rows of the right term)
Parameters
a left term in the product
b right term in the product
Returns
a reference to a * b
const Matrix operator* (const double s, const Matrix & a) friend
This operator creates a new Matrix equal to the multiplication of a matrix by a scalar term.
Parameters
a matrix to apply the scalar multiplication to
s scalar term to apply to the matrix
Returns
a reference to s * a
const Matrix operator* (const Matrix & a, const double s) friend
This operator creates a new Matrix equal to the multiplication of a matrix by a scalar term.
Parameters
a matrix to apply the scalar multiplication to
s scalar term to apply to the matrix
Returns
a reference to s * a
friend class RowVector friend
Definition at line 66 of file Matrix.h.
Member Data Documentation
string Matrix::beginArrayStr_ = "[" static private
Beginning of row or col array for output as a string.
Definition at line 794 of file Matrix.h.
Referenced by setToStringFormat(), and toString().
string Matrix::elmtSepStr_ = ", " static private
Separation between elements for output as a string.
Definition at line 802 of file Matrix.h.
Referenced by setToStringFormat(), and toString().
string Matrix::endArrayStr_ = "]" static private
End of row or col array for output as a string.
Definition at line 798 of file Matrix.h.
Referenced by setToStringFormat(), and toString().
bool Matrix::eolAtEor_ = true static private
Does the output format require an end of line character at the end of the string?
Definition at line 806 of file Matrix.h.
Referenced by setToStringFormat(), and toString().
TriState uriVL::Matrix::isAntisymmetric_ private
Indicates whether the matrix is known to be antisymmetric.
Definition at line 774 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), enforcesAntisymmetry(), getMatrix(), invert(), isAntisymmetric(), Matrix(), randomMatrix(), rowSwap(), and transposition().
TriState uriVL::Matrix::isDiagonal_ private
Indicates whether the matrix is known to be diagonal.
Definition at line 749 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), enforceDiagonality(), getMatrix(), inverse(), invert(), isDiagonal(), Matrix(), randomMatrix(), rowSwap(), and transposition().
TriState uriVL::Matrix::isFullRank_ private
Indicates whether the matrix is known to be a full rank matrix (which includes nonsingular for a square matrix)
Definition at line 766 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), getMatrix(), invert(), Matrix(), randomMatrix(), rowSwap(), and transposition().
TriState uriVL::Matrix::isIdentity_ private
Indicates whether the matrix is known to be an identity matrix.
Definition at line 753 of file Matrix.h.
Referenced by copyMatrix(), diagonalMatrix(), getMatrix(), inverse(), invert(), isIdentity(), Matrix(), and randomMatrix().
TriState uriVL::Matrix::isLowerTriangular_ private
Indicates whether the matrix is known to be lower-triangular.
Definition at line 761 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), enforceLowerTriangularity(), getMatrix(), invert(), isLowerTriangular(), Matrix(), randomMatrix(), rowSwap(), transpose(), and transposition().
TriState uriVL::Matrix::isNormalized1_ private
Is this matrix normalized with respect to N1 norm?
Definition at line 782 of file Matrix.h.
Referenced by Matrix(), uriVL::ColumnVector::normalize1(), uriVL::ColumnVector::normalize2(), and uriVL::RowVector::RowVector().
TriState uriVL::Matrix::isNormalized2_ private
Is this matrix normalized with respect to N2 (Euclidean) norm?
Definition at line 786 of file Matrix.h.
Referenced by Matrix(), uriVL::ColumnVector::normalize2(), and uriVL::RowVector::RowVector().
TriState uriVL::Matrix::isNormalizedInf_ private
Is this matrix normalized with respect to N_infinity norm?
Definition at line 790 of file Matrix.h.
Referenced by Matrix(), uriVL::ColumnVector::normalize2(), uriVL::ColumnVector::normalizeInf(), and uriVL::RowVector::RowVector().
TriState uriVL::Matrix::isOrthogonal_ private
Indicates whether the matrix is known to be orthogonal.
Definition at line 778 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), getMatrix(), inverse(), invert(), Matrix(), randomMatrix(), rowSwap(), and transposition().
TriState uriVL::Matrix::isSymmetric_ private
Indicates whether the matrix is known to be symmetric.
Definition at line 770 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), enforceSymmetry(), getMatrix(), invert(), isSymmetric(), Matrix(), randomMatrix(), rowSwap(), and transposition().
TriState uriVL::Matrix::isUpperTriangular_ private
Indicates whether the matrix is known to be upper-triangular.
Definition at line 757 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), diagonalMatrix(), enforceUpperTriangularity(), getMatrix(), invert(), isUpperTriangular(), Matrix(), randomMatrix(), rowSwap(), transpose(), and transposition().
double** uriVL::Matrix::mat_ private
The data for the Matrix.
The data is stored in the following fashion: mat_ is a 1D-array of double pointers. Each of these points to a double array.
Definition at line 740 of file Matrix.h.
Referenced by allocateMatrix_(), colSwap(), uriVL::ColumnVector::ColumnVector(), copyMatrix(), diagonalMatrix(), uriVL::ColumnVector::dotProd(), enforceDiagonality(), enforceLowerTriangularity(), enforcesAntisymmetry(), enforceSymmetry(), enforceUpperTriangularity(), uriVL::HomogeneousMatrix::getGLMatrix(), getMatrix(), uriVL::HomogeneousMatrix::HomogeneousMatrix(), inverse(), invert(), isAntisymmetric(), isIdentity(), isLowerTriangular(), isSymmetric(), isUpperTriangular(), killMat_(), Matrix(), norm1(), uriVL::RowVector::norm2(), uriVL::ColumnVector::norm2(), uriVL::RowVector::normalize1(), uriVL::ColumnVector::normalize1(), uriVL::RowVector::normalize2(), uriVL::ColumnVector::normalize2(), uriVL::RowVector::normalizeInf(), uriVL::ColumnVector::normalizeInf(), normInf(), operator()(), operator*=(), uriVL::ColumnVector::operator+=(), operator+=(), uriVL::ColumnVector::operator-=(), operator-=(), operator=(), operator==(), preMultiplyBy(), randomMatrix(), rowSwap(), uriVL::RowVector::RowVector(), toString(), transpose(), uriVL::RowVector::transposition(), uriVL::ColumnVector::transposition(), transposition(), and ~Matrix().
const double Matrix::MATRIX_PROP_ABS_TOL = 1.E-7 static private
Absolute tolerance for all properties of the matrix class.
Definition at line 810 of file Matrix.h.
Referenced by isAntisymmetric(), isLowerTriangular(), isSymmetric(), and isUpperTriangular().
const double Matrix::MATRIX_PROP_REL_TOL = 1.E-7 static private
Relative tolerance for all properties of the matrix class.
Definition at line 814 of file Matrix.h.
Referenced by isAntisymmetric(), isIdentity(), isSymmetric(), and operator==().
int uriVL::Matrix::nbCols_ private
Definition at line 722 of file Matrix.h.
Referenced by colSwap(), copyMatrix(), enforceDiagonality(), enforceLowerTriangularity(), enforcesAntisymmetry(), enforceSymmetry(), enforceUpperTriangularity(), getNbCols(), inverse(), invert(), isAntisymmetric(), isIdentity(), isLowerTriangular(), isSymmetric(), isUpperTriangular(), Matrix(), norm1(), uriVL::RowVector::norm2(), uriVL::RowVector::normalize1(), uriVL::RowVector::normalize2(), uriVL::RowVector::normalizeInf(), normInf(), operator()(), operator*=(), operator+=(), operator-=(), operator=(), operator==(), preMultiplyBy(), uriVL::RowVector::RowVector(), toString(), transpose(), uriVL::RowVector::transposition(), and transposition().
int uriVL::Matrix::nbRows_ private
Number of rows of the matrix.
Definition at line 717 of file Matrix.h.
Referenced by colSwap(), uriVL::ColumnVector::ColumnVector(), copyMatrix(), uriVL::ColumnVector::dotProd(), enforceDiagonality(), enforceLowerTriangularity(), enforcesAntisymmetry(), enforceSymmetry(), enforceUpperTriangularity(), getNbRows(), inverse(), invert(), isAntisymmetric(), isIdentity(), isLowerTriangular(), isSymmetric(), isUpperTriangular(), Matrix(), norm1(), uriVL::ColumnVector::norm2(), uriVL::ColumnVector::normalize1(), uriVL::ColumnVector::normalize2(), uriVL::ColumnVector::normalizeInf(), normInf(), operator()(), operator*=(), uriVL::ColumnVector::operator+=(), operator+=(), uriVL::ColumnVector::operator-=(), operator-=(), operator=(), operator==(), preMultiplyBy(), rowSwap(), toString(), transpose(), uriVL::ColumnVector::transposition(), transposition(), and ~Matrix().
int uriVL::Matrix::nbStorageCols_ private
Number of storage columns of the matrix.
To facilitate the reuse of a matrix object in video processing applications, the matrix's data array may be allocated at a larger size (the "storage" dimensions) than the matrix's nominal dimensions
Definition at line 734 of file Matrix.h.
Referenced by allocateMatrix_().
int uriVL::Matrix::nbStorageRows_ private
Number of storage rows of the matrix.
To facilitate the reuse of a matrix object in video processing applications, the matrix's data array may be allocated at a larger size (the "storage" dimensions) than the matrix's nominal dimensions
Definition at line 728 of file Matrix.h.
Referenced by allocateMatrix_(), and killMat_().
bool uriVL::Matrix::storageIsLocal_ private
Indicates whether the array mat_ was allocated by the matrix or is simply a reference to an array created outside of the class.
Definition at line 745 of file Matrix.h.
Referenced by allocateMatrix_(), killMat_(), and Matrix().
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp