URIVisionLibrary: uriVL::NormalFlowCalculator Class Reference
uriVL::NormalFlowCalculator Class Reference
#include <NormalFlowCalculator.h>
Public Member Functions
NormalFlowCalculator (const ImageRect *rect, const float gradScale, const float gradThreshold)
Creates a NormalFlowCalculator.
NormalFlowCalculator (const float gradScale, const float gradThreshold)
Creates a NormalFlowCalculator.
virtual ~NormalFlowCalculator ()
Destructor.
RasterImage_gray_F * applyTo (const RasterImage *currImg, const RasterImage *prevImg)
Call applyInto() Compute the normal flow.
RasterImage_gray_F * applyTo (const RasterImage *currImg, const RasterImage *prevImg, const ImageRect *theRect)
Call applyInto() Compute the normal flow within the rectangle specified.
RasterImage_gray_F * applyTo (const RasterImage *currImg, const RasterImage *prevImg, const VectorField_F *grad)
Call applyInto() Compute the normal flow.
RasterImage_gray_F * applyTo (const RasterImage *currImg, const RasterImage *prevImg, const VectorField_F *grad, const ImageRect *theRect)
Call applyInto() Compute the normal flow within the rectangle specified.
void applyInto (const RasterImage *currImg, const RasterImage *prevImg, RasterImage_gray_F *normalFlow)
Call applyInto() Compute the normal flow.
void applyInto (const RasterImage *currImg, const RasterImage *prevImg, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Call applyInto() Compute the normal flow within the rectangle specified.
void applyInto (const RasterImage *currImg, const RasterImage *prevImg, const VectorField_F *grad, RasterImage_gray_F *normalFlow)
Call applyInto() Compute the normal flow.
void applyInto (const RasterImage *currImg, const RasterImage *prevImg, const VectorField_F *grad, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Call applyInto_() Compute the normal flow within the rectangle specified.
Protected Member Functions
NormalFlowCalculator (const NormalFlowCalculator &theObj)
Copy Constructor.
const NormalFlowCalculator & operator= (const NormalFlowCalculator &theObj)
Copy operator.
void applyInto_ (const RasterImage_gray *currImg, const RasterImage_gray *prevImg, const VectorField_F *grad, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Called by all public functions Compute the normal flow.
void applyInto_ (const RasterImage_gray_F *currImg, const RasterImage_gray_F *prevImg, const VectorField_F *grad, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Called by all public functions Compute the normal flow.
void applyInto_ (const RasterImage_RGBa *currImg, const RasterImage_RGBa *prevImg, const VectorField_F *grad, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Called by all public functions Compute the normal flow.
void applyInto_ (const RasterImage_RGB *currImg, const RasterImage_RGB *prevImg, const VectorField_F *grad, const ImageRect *theRect, RasterImage_gray_F *normalFlow)
Called by all public functions Compute the normal flow.
Protected Attributes
float threshold_
Threshold used to compute normal flow.
ImageGradient_Gaussian_F * gaussGrad_
Gradient calculator.
Detailed Description
Definition at line 47 of file NormalFlowCalculator.h.
Constructor & Destructor Documentation
NormalFlowCalculator::NormalFlowCalculator (const ImageRect * rect, const float gradScale, const float gradThreshold)
Creates a NormalFlowCalculator.
Parameters
rect image's bound rect
gradScale gradient scale
gradThreshold gradient threshold
Definition at line 42 of file NormalFlowCalculator.cpp.
                 :       threshold_(gradThreshold),
                         gaussGrad_(new ImageGradient_Gaussian_F(gradScale, theRect))
 {
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by NormalFlowCalculator constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Unexpected error encountered in NormalFlowCalculator constructor.");
 }
NormalFlowCalculator::NormalFlowCalculator (const float gradScale, const float gradThreshold)
Creates a NormalFlowCalculator.
Parameters
gradScale gradient scale
gradThreshold gradient threshold
Definition at line 25 of file NormalFlowCalculator.cpp.
                 :       threshold_(gradThreshold),
                         gaussGrad_(new ImageGradient_Gaussian_F(gradScale))
 {
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by NormalFlowCalculator constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Unexpected error encountered in NormalFlowCalculator constructor.");
 }
NormalFlowCalculator::~NormalFlowCalculator (void) virtual
Destructor.
Definition at line 69 of file NormalFlowCalculator.cpp.
References gaussGrad_.
 {
         if (gaussGrad_ != NULL)
                 delete gaussGrad_;
 }
NormalFlowCalculator::NormalFlowCalculator (const NormalFlowCalculator & theObj) protected
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 59 of file NormalFlowCalculator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       threshold_(0.f),
                         gaussGrad_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "NormalFlowCalculator copy constructor not implemented");
 }
Member Function Documentation
void NormalFlowCalculator::applyInto (const RasterImage * currImg, const RasterImage * prevImg, RasterImage_gray_F * normalFlow)
Call applyInto() Compute the normal flow.
Parameters
currImg current image
prevImg previous image
normalFlow normal flow as a RasterImage_gray_F
Definition at line 154 of file NormalFlowCalculator.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by applyInto(), applyTo(), and myIdle().
 {
         applyInto(currImg, prevImg, currImg->getValidRect(), normalFlow);
 }
void NormalFlowCalculator::applyInto (const RasterImage * currImg, const RasterImage * prevImg, const ImageRect * theRect, RasterImage_gray_F * normalFlow)
Call applyInto() Compute the normal flow within the rectangle specified.
Parameters
currImg current image
prevImg previous image
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
Definition at line 163 of file NormalFlowCalculator.cpp.
References applyInto(), uriVL::ImageGradient_Gaussian_F::applyTo(), FAIL_CONDITION, gaussGrad_, grad, and uriVL::kNullRasterImageError.
 {
         //  compute gradient
         const VectorField_F* grad = (const VectorField_F *) (gaussGrad_->applyTo(prevImg));
     FAIL_CONDITION( grad == NULL,
                     kNullRasterImageError,
                     "null VectorField in NormalFlowCalculator::applyInto");
         applyInto(currImg, prevImg, grad, theRect, normalFlow);
     //  clean up local allocations
         delete grad;
 }
void NormalFlowCalculator::applyInto (const RasterImage * currImg, const RasterImage * prevImg, const VectorField_F * grad, RasterImage_gray_F * normalFlow)
Call applyInto() Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
normalFlow normal flow as a RasterImage_gray_F
Definition at line 182 of file NormalFlowCalculator.cpp.
References applyInto(), and uriVL::DrawableObject2D::getValidRect().
 {
         applyInto(currImg, prevImg, grad, currImg->getValidRect(), normalFlow);
 }
void NormalFlowCalculator::applyInto (const RasterImage * currImg, const RasterImage * prevImg, const VectorField_F * grad, const ImageRect * theRect, RasterImage_gray_F * normalFlow)
Call applyInto_() Compute the normal flow within the rectangle specified.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
Definition at line 192 of file NormalFlowCalculator.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::RasterImage::floatRasterIsReference(), uriVL::RasterImage::getBaseRasterType(), uriVL::RasterImage::hasFloatRaster(), uriVL::kGrayRaster, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRasterImageError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION( currImg == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in NormalFlowCalculator::applyInto");
     FAIL_CONDITION( prevImg == NULL,
                     kNullParameterError,
                     "null RasterImage as parameter in NormalFlowCalculator::applyInto");
     FAIL_CONDITION( grad == NULL,
                     kNullRasterImageError,
                     "null VectorField in NormalFlowCalculator::applyInto");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in NormalFlowCalculator::applyInto");
     FAIL_CONDITION( normalFlow == NULL,
                     kNullRasterImageError,
                     "null RasterImage_gray_F in NormalFlowCalculator::applyInto");
     //  get type information
     const int type1 = currImg->getBaseRasterType(),
                           type2 = prevImg->getBaseRasterType();
     const bool  inFloat1 = currImg->hasFloatRaster(),
                                 inFloatRef1 = currImg->floatRasterIsReference(),
                                 inFloat2 = prevImg->hasFloatRaster(),
                                 inFloatRef2 = prevImg->floatRasterIsReference();
     //  if currImg and prevImg have the same base raster type
     if (type1 == type2)
     {
         switch (type1)
         {
                 case kGrayRaster:
                 if(inFloat1 && inFloatRef1)
                         if(inFloat2 && inFloatRef2)
                                 applyInto_((RasterImage_gray_F*)currImg, (RasterImage_gray_F*)prevImg, grad, theRect, normalFlow);
                         else
                                 applyInto_((RasterImage_gray* )prevImg, (RasterImage_gray_F *)currImg, grad, theRect, normalFlow);
                 else{
                         if(inFloat2 && inFloatRef2)
                                 applyInto_((RasterImage_gray* )currImg, (RasterImage_gray_F *)prevImg, grad, theRect, normalFlow);
                         else
                                 applyInto_((RasterImage_gray* )currImg, (RasterImage_gray* )prevImg, grad, theRect, normalFlow);
                         }
                         break;
                 case kRGB24Raster:
                         applyInto_((RasterImage_RGB* )currImg, (RasterImage_RGB* )prevImg, grad, theRect, normalFlow);
                     break;
             case kRGBa32Raster:
                 applyInto_((RasterImage_RGBa* )currImg, (RasterImage_RGBa* )prevImg, grad, theRect, normalFlow);
                 break;
             default:
                 FAIL_CONDITION( true,
                                 kRasterImageError,
                                 "Invalid image type in NormalFlowCalculator::applyInto");
                 break;
         }
     }
     //  if type different, convert them to be the same
     else
     {
         //      if one is a RasterImage_gray, convert the other to RasterImage_gray
         if (type1 == kGrayRaster)
         {
             RasterImage_gray* gray2 = new RasterImage_gray(prevImg);
             if(inFloat1 && inFloatRef1)
                 applyInto_(gray2, (RasterImage_gray_F *)currImg, grad, theRect, normalFlow);
             else
                 applyInto_((RasterImage_gray* )currImg, gray2, grad, theRect, normalFlow);
             delete gray2;
         }
         else if (type2 == kGrayRaster)
         {
             RasterImage_gray    *gray1 = new RasterImage_gray(currImg);
             if(inFloat2 && inFloatRef2)
                 applyInto_(gray1, (RasterImage_gray_F *)prevImg, grad, theRect, normalFlow);
             else
                 applyInto_((RasterImage_gray* )prevImg, gray1, grad, theRect, normalFlow);
             delete gray1;
         }
         //      else if one is RGB and the other RGBa, convert the former to RGBa
         else if (type1 == kRGBa32Raster)
         {
             RasterImage_RGBa* rgba2 = new RasterImage_RGBa(prevImg);
             applyInto_((RasterImage_RGBa* )currImg, rgba2, grad, theRect, normalFlow);
             delete rgba2;
         }
         else if (type2 == kRGBa32Raster)
         {
             RasterImage_RGBa* rgba1 = new RasterImage_RGBa(currImg);
             applyInto_(rgba1, (RasterImage_RGBa* )prevImg, grad, theRect, normalFlow);
             delete rgba1;
         }
         else    //      this should not happen
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in NormalFlowCalculator::applyInto");
     }
 }
void NormalFlowCalculator::applyInto_ (const RasterImage_gray * currImg, const RasterImage_gray * prevImg, const VectorField_F * grad, const ImageRect * theRect, RasterImage_gray_F * normalFlow) protected
Called by all public functions Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
Definition at line 315 of file NormalFlowCalculator.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::getNormAsRasterImage(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, uriVL::kPositiveFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::DrawableObject2D::setValidRect(), and threshold_.
Referenced by applyInto().
 {
     const unsigned char*const*  im1     = (const unsigned char* const*) currImg->getShiftedRaster2D();
     const unsigned char*const*  im2     = (const unsigned char* const*) prevImg->getShiftedRaster2D();
         const float*const*      ng      = grad->getNormAsRasterImage()->getShiftedGrayF2D();
         float* const*   mv      = normalFlow->getShiftedGrayF2D(R_W_ACCESS);
         /*      get display rectangle   */
         ImageRect* rect1                = ImageRect::intersection(currImg->getValidRect(), prevImg->getValidRect());
         ImageRect* rect2                = ImageRect::intersection(rect1, grad->getValidRect());
         ImageRect* destRect     = ImageRect::intersection(rect2, theRect);
         FAIL_CONDITION( destRect == NULL,
                         kNullRectangleError,
                         "Computation rectangle specified does not contain valid data");
     //  if normalFlow does not contain the destRect, resize it
     if (!normalFlow->contains(destRect))
         normalFlow->setBoundRect(destRect);
     /*  end of get display rectangle    */
     const int iLow      = destRect->getTop(),
               iHigh     = destRect->getBottom(),
                           jLow  = destRect->getLeft(),
               jHigh     = destRect->getRight();
         for(int i=iLow; i<=iHigh; i++)
                 for(int j=jLow; j<=jHigh; j++)
                 {
                         if(ng[i][j] > threshold_)
{
                                 float temp = (im1[i][j] - im2[i][j])/ng[i][j];
                                 mv[i][j] = (temp > 0 ? temp:-temp);
                         }
                         else
                                 mv[i][j] = 0;
                 }
         normalFlow->requestRasterUpdate();
         normalFlow->setValidRect(destRect);
         normalFlow->setFloatConversionMode(kPositiveFloat);
     //  clean up local allocations
         delete rect1;
         delete rect2;
         delete destRect;
 }
void NormalFlowCalculator::applyInto_ (const RasterImage_gray_F * currImg, const RasterImage_gray_F * prevImg, const VectorField_F * grad, const ImageRect * theRect, RasterImage_gray_F * normalFlow) protected
Called by all public functions Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
the RasterImage_gray & RasterImage_gray_F case */
Definition at line 434 of file NormalFlowCalculator.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::getNormAsRasterImage(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, uriVL::kPositiveFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::DrawableObject2D::setValidRect(), and threshold_.
 {
     const float *const* im1     = currImg->getShiftedGrayF2D();
     const float *const* im2     = prevImg->getShiftedGrayF2D();
         const float     *const* ng      = grad->getNormAsRasterImage()->getShiftedGrayF2D();
         float* const* mv        = normalFlow->getShiftedGrayF2D(R_W_ACCESS);
         /*      get display rectangle   */
         ImageRect   *rect1, *rect2, *destRect;
         rect1           = ImageRect::intersection(currImg->getValidRect(), prevImg->getValidRect());
         rect2           = ImageRect::intersection(rect1, grad->getValidRect());
         destRect        = ImageRect::intersection(rect2, theRect);
         FAIL_CONDITION( destRect == NULL,
                         kNullRectangleError,
                         "Computation rectangle specified does not contain valid data");
     //  if normalFlow does not contain the destRect, resize it
     if (!normalFlow->contains(destRect))
         normalFlow->setBoundRect(destRect);
     /*  end of get display rectangle    */
     int   iLow  = destRect->getTop(),
             iHigh       = destRect->getBottom(),
             jLow        = destRect->getLeft(),
             jHigh       = destRect->getRight();
         for(int i=iLow; i<=iHigh; i++)
                 for(int j=jLow; j<=jHigh; j++)
                 {
                         if(ng[i][j] > threshold_)
{
                                 float temp = (im1[i][j] - im2[i][j])/ng[i][j];
                                 mv[i][j] = (temp > 0 ? temp:-temp);
                         }
                         else
                                 mv[i][j] = 0;
                 }
         normalFlow->requestRasterUpdate();
         normalFlow->setValidRect(destRect);
         normalFlow->setFloatConversionMode(kPositiveFloat);
     //  clean up local allocations
         delete rect1;
         delete rect2;
         delete destRect;
 }
void NormalFlowCalculator::applyInto_ (const RasterImage_RGBa * currImg, const RasterImage_RGBa * prevImg, const VectorField_F * grad, const ImageRect * theRect, RasterImage_gray_F * normalFlow) protected
Called by all public functions Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F Called by all public functions Compute the normal flow
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
Definition at line 491 of file NormalFlowCalculator.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::getNormAsRasterImage(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, uriVL::kPositiveFloat, uriVL::R_W_ACCESS, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::DrawableObject2D::setValidRect(), and threshold_.
 {
     const unsigned char* const* im1     = currImg->getShiftedRaster2D(),
                                                 *const* im2     = prevImg->getShiftedRaster2D();
         const float* const* ng  = grad->getNormAsRasterImage()->getShiftedGrayF2D();
         float* const* mv        = normalFlow->getShiftedGrayF2D(R_W_ACCESS);
         /*      get display rectangle   */
         ImageRect   *rect1, *rect2, *destRect;
         rect1           = ImageRect::intersection(currImg->getValidRect(), prevImg->getValidRect());
         rect2           = ImageRect::intersection(rect1, grad->getValidRect());
         destRect        = ImageRect::intersection(rect2, theRect);
         FAIL_CONDITION( destRect == NULL,
                         kNullRectangleError,
                         "Computation rectangle specified does not contain valid data");
     //  if normalFlow does not contain the destRect, resize it
     if (!normalFlow->contains(destRect))
         normalFlow->setBoundRect(destRect);
     /*  end of get display rectangle    */
     const int   iLow    = destRect->getTop(),
                 iHigh   = destRect->getBottom(),
                 jLow    = destRect->getLeft(),
                 jHigh   = destRect->getRight();
     //  use AVERAGE_DIFFERENCE as the default algorithm
         //      get the average value of R,G,B,a for each pixel
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
                         if(ng[i][j] > threshold_)
{
                     int avg = 0;
                     for(int k=0; k<4; k++)
{
                                 int temp1 = im1[i][4*j+k] - im2[i][4*j+k];
                                 temp1 = temp1>0 ? temp1 : -temp1;               // normalize
                                 avg += temp1;
                         }
                         mv[i][j] = static_cast<unsigned char>(avg/(4*ng[i][j]));
                 }
                         else
                                 mv[i][j] = 0;
         }
         normalFlow->requestRasterUpdate();
         normalFlow->setValidRect(destRect);
         normalFlow->setFloatConversionMode(kPositiveFloat);
     //  clean up local allocations
         delete rect1;
         delete rect2;
         delete destRect;
 }
void NormalFlowCalculator::applyInto_ (const RasterImage_RGB * currImg, const RasterImage_RGB * prevImg, const VectorField_F * grad, const ImageRect * theRect, RasterImage_gray_F * normalFlow) protected
Called by all public functions Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
normalFlow normal flow as a RasterImage_gray_F
Definition at line 556 of file NormalFlowCalculator.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::getNormAsRasterImage(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, uriVL::kPositiveFloat, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::DrawableObject2D::setValidRect(), and threshold_.
 {
     unsigned char       **im1   = (unsigned char** ) currImg->getShiftedRaster2D(),
                         **im2   = (unsigned char** ) prevImg->getShiftedRaster2D();
         float                   **ng    = (float** ) grad->getNormAsRasterImage()->getShiftedGrayF2D(),
                                         **mv    = (float** ) normalFlow->getShiftedGrayF2D();
         /*      get display rectangle   */
         ImageRect   *rect1, *rect2, *destRect;
         rect1           = ImageRect::intersection(currImg->getValidRect(), prevImg->getValidRect());
         rect2           = ImageRect::intersection(rect1, grad->getValidRect());
         destRect        = ImageRect::intersection(rect2, theRect);
         FAIL_CONDITION( destRect == NULL,
                         kNullRectangleError,
                         "Computation rectangle specified does not contain valid data");
     //  if normalFlow does not contain the destRect, resize it
     if (!normalFlow->contains(destRect))
         normalFlow->setBoundRect(destRect);
     /*  end of get display rectangle    */
     int   iLow  = destRect->getTop(),
             iHigh       = destRect->getBottom(),
             jLow        = destRect->getLeft(),
             jHigh       = destRect->getRight();
     //  use AVERAGE_DIFFERENCE as the default algorithm
         //      get the average value of R,G,B for each pixel
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
         {
                         if(ng[i][j] > threshold_)
{
                     unsigned char avg = 0;
                     for(int k=0; k<3; k++)
{
                                 int temp1 = im1[i][3*j+k] - im2[i][3*j+k];
                                 temp1 = temp1>0 ? temp1 : -temp1;               // normalize
                                 avg += temp1;
                         }
                         mv[i][j] = static_cast<unsigned char>(avg/(3*ng[i][j]));
                 }
                         else
                                 mv[i][j] = 0;
         }
         normalFlow->requestRasterUpdate();
         normalFlow->setValidRect(destRect);
         normalFlow->setFloatConversionMode(kPositiveFloat);
     //  clean up local allocations
         delete rect1;
         delete rect2;
         delete destRect;
 }
RasterImage_gray_F * NormalFlowCalculator::applyTo (const RasterImage * currImg, const RasterImage * prevImg)
Call applyInto() Compute the normal flow.
Parameters
currImg current image
prevImg previous image
Returns
computed normal flow as a RasterImage_gray_F
Definition at line 98 of file NormalFlowCalculator.cpp.
References applyInto(), uriVL::DrawableObject2D::getHeight(), and uriVL::DrawableObject2D::getWidth().
 {
         RasterImage_gray_F* normalFlow = new RasterImage_gray_F(currImg->getHeight(), currImg->getWidth());
         applyInto(currImg, prevImg, normalFlow);
         return normalFlow;
 }
RasterImage_gray_F * NormalFlowCalculator::applyTo (const RasterImage * currImg, const RasterImage * prevImg, const ImageRect * theRect)
Call applyInto() Compute the normal flow within the rectangle specified.
Parameters
currImg current image
prevImg previous image
theRect rectangle within which to calculate the normal flow
Returns
computed normal flow as a RasterImage_gray_F
Definition at line 109 of file NormalFlowCalculator.cpp.
References applyInto(), FAIL_CONDITION, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in NormalFlowCalculator::applyTo");
         RasterImage_gray_F* normalFlow = new RasterImage_gray_F(theRect);
         applyInto(currImg, prevImg, theRect, normalFlow);
         return normalFlow;
 }
RasterImage_gray_F * NormalFlowCalculator::applyTo (const RasterImage * currImg, const RasterImage * prevImg, const VectorField_F * grad)
Call applyInto() Compute the normal flow.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
Returns
computed normal flow as a RasterImage_gray_F
Definition at line 125 of file NormalFlowCalculator.cpp.
References applyInto(), uriVL::DrawableObject2D::getHeight(), and uriVL::DrawableObject2D::getWidth().
 {
         RasterImage_gray_F* normalFlow = new RasterImage_gray_F(currImg->getHeight(), currImg->getWidth());
         applyInto(currImg, prevImg, grad, normalFlow);
         return normalFlow;
 }
RasterImage_gray_F * NormalFlowCalculator::applyTo (const RasterImage * currImg, const RasterImage * prevImg, const VectorField_F * grad, const ImageRect * theRect)
Call applyInto() Compute the normal flow within the rectangle specified.
Parameters
currImg current image
prevImg previous image
grad gradient as a VectorField_F
theRect rectangle within which to calculate the normal flow
Returns
computed normal flow as a RasterImage_gray_F
Definition at line 137 of file NormalFlowCalculator.cpp.
References applyInto(), FAIL_CONDITION, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in NormalFlowCalculator::applyTo");
         RasterImage_gray_F* normalFlow = new RasterImage_gray_F(theRect);
         applyInto(currImg, prevImg, grad, theRect, normalFlow);
         return normalFlow;
 }
const NormalFlowCalculator & NormalFlowCalculator::operator= (const NormalFlowCalculator & theObj) protected
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 77 of file NormalFlowCalculator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "NormalFlowCalculator copy operator not implemented");
         return *this;
 }
Member Data Documentation
ImageGradient_Gaussian_F* uriVL::NormalFlowCalculator::gaussGrad_ protected
Gradient calculator.
Definition at line 193 of file NormalFlowCalculator.h.
Referenced by applyInto(), and ~NormalFlowCalculator().
float uriVL::NormalFlowCalculator::threshold_ protected
Threshold used to compute normal flow.
Definition at line 187 of file NormalFlowCalculator.h.
Referenced by applyInto_().
The documentation for this class was generated from the following files:
NormalFlowCalculator.h
NormalFlowCalculator.cpp