URIVisionLibrary: uriVL::ImageHistogram Class Reference
uriVL::ImageHistogram Class Reference
Implements the ImageHistogram class.
#include <ImageHistogram.h>
Public Member Functions
ImageHistogram (RasterImage *img, const ImageRect *rect=NULL)
Constructor taking in a RasterImage and possibly an ImageRect over which to compute the histogram.
ImageHistogram (RasterImage_gray *img, const ImageRect *rect=NULL, int nbVals=HIST_DEFAULT_NB_VALS, unsigned char rangeMin=HIST_DEFAULT_RANGE_MIN_UC, unsigned char rangeMax=HIST_DEFAULT_RANGE_MAX_UC)
Constructor taking in a RasterImage_gray, range values, and possibly an ImageRect over which to compute the histogram.
ImageHistogram (RasterImage_gray_F *img, const ImageRect *rect=NULL, int nbVals=HIST_DEFAULT_NB_VALS, float rangeMin=HIST_DEFAULT_RANGE_MIN, float rangeMax=HIST_DEFAULT_RANGE_MAX)
Constructor taking in a RasterImage_gray_F, range values, and possibly an ImageRect over which to compute the histogram.
~ImageHistogram (void)
Destructor.
long * getHistogram (void) const
returns the histogram values cast to a pointer to char.
void setRenderMode (HistogramRenderMode mode)
Defines the rendering mode for the image histogram.
void setImage (RasterImage *img, const ImageRect *rect=NULL)
Assigns a new RasterImage and possibly an ImageRect over which to compute the histogram.
void setImage (RasterImage_gray *img, const ImageRect *rect=NULL, int nbVals=HIST_DEFAULT_NB_VALS, unsigned char rangeMin=HIST_DEFAULT_RANGE_MIN_UC, unsigned char rangeMax=HIST_DEFAULT_RANGE_MAX_UC)
Assigns a new RasterImage_gray and possibly an ImageRect, and range values over which to compute the histogram.
void setImage (RasterImage_gray_F *img, const ImageRect *rect=NULL, int nbVals=HIST_DEFAULT_NB_VALS, float rangeMin=HIST_DEFAULT_RANGE_MIN, float rangeMax=HIST_DEFAULT_RANGE_MAX)
Assigns a new RasterImage_gray and possibly an ImageRect, and range values over which to compute the histogram.
Public Member Functions inherited from uriVL::Histogram
Histogram (const float *x, int n, int nbVals=HIST_DEFAULT_NB_VALS, float rangeMin=HIST_DEFAULT_RANGE_MIN, float rangeMax=HIST_DEFAULT_RANGE_MAX)
Creates an histogram for a float data set.
Histogram (const int *x, const int n, int nbVals=HIST_DEFAULT_NB_VALS, int rangeMin=HIST_DEFAULT_RANGE_MIN, int rangeMax=HIST_DEFAULT_RANGE_MAX)
Creates an histogram for a data set.
Histogram (const unsigned char *x, const int n, int nbVals=HIST_DEFAULT_NB_VALS, unsigned char rangeMin=HIST_DEFAULT_RANGE_MIN_UC, unsigned char rangeMax=HIST_DEFAULT_RANGE_MAX_UC)
Creates an histogram for a data set.
Histogram (const unsigned char *x, int n)
Creates an histogram for a data set.
virtual ~Histogram (void)
Creates an histogram for a data set.
const long * getHistogram (void) const
returns the histogram values
void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
void setBackgroundColor (float theRed, float theGreen, float theBlue)
Specifies the a color for the background of the histogram, when rendered.
void setAxesColor (float theRed, float theGreen, float theBlue)
Specifies the a color for the histogram's axes, when rendered.
void setTitleColor (float theRed, float theGreen, float theBlue)
Specifies the a color for the title of the histogram, when rendered.
void setDrawAxes (bool drawAxes)
Called to tell whether or not to draw axes when rendering the histogram.
void setDrawTitle (bool drawTitle)
Called to tell whether or not to draw a title when rendering the histogram.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Protected Member Functions
ImageHistogram (void)
Default constructor.
void computeFastHistogram_ (RasterImage_gray *img, const ImageRect *rect)
The function that does all the work for a regular (unsigned char) gray-level image, using the default histogram parameters (no scaling)
void computeHistogram_ (RasterImage_gray *img, const ImageRect *rect)
The function that does all the work for a regular (unsigned char) gray-level image, using custom histogram parameters (involving scaling and shifting)
void computeFloatHistogram_ (RasterImage_gray_F *img, const ImageRect *rect)
The function that does all the work for a float gray-level image, using custom histogram parameters (involving scaling and shifting)
Protected Member Functions inherited from uriVL::Histogram
Histogram (void)
Default constructor.
void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Empty implementation mandated by pure virtual parent class DrawableObject2D.
void setValidRect_ (int x, int y, int theWidth, int theHeight)
Empty implementation mandated by pure virtual parent class DrawableObject2D.
virtual void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders the histogram at the depth specified and using the colors specified.
void computeRenderingParameters_ (void) const
Computes the translation and scaling parameters for the rendering mode set by setRenderMode.
void computeHistogram_ (void)
The function that does all the work.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Attributes inherited from uriVL::Histogram
bool drawAxes_
true if histogram labels should be drawn (false by default)
bool drawTitle_
true if the histogram's title should be drawn (false by default)
float * axesColor_
color for the axes (black by default)
float * backgroundColor_
background color to render the histogram (white by default)
float * titleColor_
color for the title (black by default)
char * title_
stores a title for the histogram.
HistogramDataType dataType_
Data type of this histogram.
unsigned char ucRangeMin_
stores the lower bound of an unsigned char histogram's range.
unsigned char ucRangeMax_
stores the upper bound of an unsigned char histogram's range.
int iRangeMin_
stores the lower bound of an int histogram's range.
int iRangeMax_
stores the upper bound of an int histogram's range.
float flRangeMin_
stores the lower bound of a float histogram's range.
float flRangeMax_
stores the upper bound of a float histogram's range.
int histVals_
stores the number of discrete values for which the frequency is calculated.
long * hist_
Stores the histogram values.
long nbPts_
number of measurements that make up the histogram.
HistogramRenderMode renderMode_
Rendering mode for this histogram.
bool isRenderReady_
true when all the scaling parameters have been set for the rendering of the histogram in the selected rendering mode
int vertPad_
Vertical shift for rendering (from left edge)
int horPad_
Horizontal shift for rendering (from left edge)
float vertScale_
Vertical rendering scale.
float horScale_
Horizontal rendering scale.
int renderWidth_
Actual width of the rendered histogram (in pixel)
int renderHeight_
Actual height of the rendered histogram (in pixel)
Detailed Description
Implements the ImageHistogram class.
This class computes, stores, and returns a 1D array of long storing the histogram of a given raster image. It can also render this histogram in a window. You should use this class if you want to display an image's histogram (for verification purposes) or want to do your own calculations with the histogram array. Otherwise, the ImageHistogramCalculator class provides a number of functions. such as median computation and the generation of gray thresholding regions
So far the class does not provide any means to set the values of the various range parameters because I haven't quite decided yet what the API for this should be. So, for the time being the class only really works with RasterImage_gray objects (converts to that format any other type of image) and uses the 256 values in the range 0-255 to calculate the histogram.
Version history
2007/03/16 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 51 of file ImageHistogram.h.
Constructor & Destructor Documentation
ImageHistogram::ImageHistogram (RasterImage * img, const ImageRect * rect = NULL)
Constructor taking in a RasterImage and possibly an ImageRect over which to compute the histogram.
Determines whether a floating point or unsigned char histogram should be used, and possibly allocates a local gray raster if theimage sent in was a color image. Uses default values for the range [0, 256[ and the number of values of the histogram.
Users who know what they are doing should instead one of the next two constructors.
Parameters
img The image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
Definition at line 34 of file ImageHistogram.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
     :   Histogram()
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor not open for business yet");
 }
ImageHistogram::ImageHistogram (RasterImage_gray * img, const ImageRect * rect = NULL, int nbVals = HIST_DEFAULT_NB_VALS, unsigned char rangeMin = HIST_DEFAULT_RANGE_MIN_UC, unsigned char rangeMax = HIST_DEFAULT_RANGE_MAX_UC)
Constructor taking in a RasterImage_gray, range values, and possibly an ImageRect over which to compute the histogram.
Parameters
img The gray-level image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
nbVals The number of values/slots in the histogram
rangeMin The lower bound of values over the image
rangeMax The upper bound of values over the image
Definition at line 43 of file ImageHistogram.cpp.
References computeFastHistogram_(), uriVL::Histogram::computeHistogram_(), uriVL::Histogram::dataType_, FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::Histogram::hist_, HIST_DEFAULT_NB_VALS, HIST_DEFAULT_RANGE_MAX_UC, HIST_DEFAULT_RANGE_MIN_UC, uriVL::Histogram::histVals_, uriVL::ImageRect::intersection(), uriVL::kNullParameterError, uriVL::kNullRectangleError, uriVL::UCHAR_HIST, uriVL::Histogram::ucRangeMax_, and uriVL::Histogram::ucRangeMin_.
     :   Histogram()
 {
     FAIL_CONDITION( img==NULL,
                     kNullParameterError,
                     "Null rast image passed to ImageHistogram constructor");
     //  determine the rectangle over which to perform the calculations
     const ImageRect   *theRect;
     bool        localRect = false;
     if (rect !=NULL)
     {
         theRect = ImageRect::intersection(rect, img->getValidRect());
         FAIL_CONDITION( theRect==NULL,
                         kNullRectangleError,
                         "Computation rectangle not within image valid data bounds in ImageHistogram constructor");
         localRect = true;
     }
     else
         theRect = img->getValidRect();
     //  Allocate the histogram and store its parameters
     dataType_ = UCHAR_HIST;
     hist_ = new long[nbVals];
     histVals_ = nbVals;
     ucRangeMin_ = rangeMin;
     ucRangeMax_ = rangeMax;
     //  We have two forms of the function: the "fast" form uses the default 256 values over the
     //  interval [0, 256[, that is no scaling nor shifting.  The "regular" function does the
     //  scaling and shifting calculations
     if ((nbVals==HIST_DEFAULT_NB_VALS) && (rangeMin==HIST_DEFAULT_RANGE_MIN_UC) &&
         (rangeMax==HIST_DEFAULT_RANGE_MAX_UC))
         computeFastHistogram_(img, theRect);
     else
         computeHistogram_(img, theRect);
     if (localRect)
         delete theRect;
 }
ImageHistogram::ImageHistogram (RasterImage_gray_F * img, const ImageRect * rect = NULL, int nbVals = HIST_DEFAULT_NB_VALS, float rangeMin = HIST_DEFAULT_RANGE_MIN, float rangeMax = HIST_DEFAULT_RANGE_MAX)
Constructor taking in a RasterImage_gray_F, range values, and possibly an ImageRect over which to compute the histogram.
Parameters
img The gray-level image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
nbVals The number of values/slots in the histogram
rangeMin The lower bound of values over the image
rangeMax The upper bound of values over the image
Definition at line 86 of file ImageHistogram.cpp.
References computeFloatHistogram_(), uriVL::Histogram::dataType_, FAIL_CONDITION, uriVL::FLOAT_HIST, uriVL::Histogram::flRangeMax_, uriVL::Histogram::flRangeMin_, uriVL::DrawableObject2D::getValidRect(), uriVL::Histogram::hist_, uriVL::Histogram::histVals_, uriVL::ImageRect::intersection(), uriVL::kNullParameterError, and uriVL::kNullRectangleError.
     :   Histogram()
 {
     FAIL_CONDITION( img==NULL,
                     kNullParameterError,
                     "Null rast image passed to ImageHistogram constructor");
     //  determine the rectangle over which to perform the calculations
     const ImageRect   *theRect;
     bool        localRect = false;
     if (rect !=NULL)
     {
         theRect = ImageRect::intersection(rect, img->getValidRect());
         FAIL_CONDITION( theRect==NULL,
                         kNullRectangleError,
                         "Computation rectangle not within image valid data bounds in ImageHistogram constructor");
         localRect = true;
     }
     else
         theRect = img->getValidRect();
     //  Allocate the histogram and store its parameters
     dataType_ = FLOAT_HIST;
     hist_ = new long[nbVals];
     histVals_ = nbVals;
     flRangeMin_ = rangeMin;
     flRangeMax_ = rangeMax;
     //  There is no point having two forms of the computation function since there will be scaling,
     //  shifting, and rounding no matter what we do.
     computeFloatHistogram_(img, theRect);
     if (localRect)
         delete theRect;
 }
ImageHistogram::~ImageHistogram (void)
Destructor.
Definition at line 125 of file ImageHistogram.cpp.
 {
 }
ImageHistogram::ImageHistogram (void) protected
Default constructor.
Definition at line 26 of file ImageHistogram.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
     :   Histogram()
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor not open for business yet");
 }
Member Function Documentation
void ImageHistogram::computeFastHistogram_ (RasterImage_gray * img, const ImageRect * rect) protected
The function that does all the work for a regular (unsigned char) gray-level image, using the default histogram parameters (no scaling)
Definition at line 238 of file ImageHistogram.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), uriVL::Histogram::hist_, and uriVL::Histogram::histVals_.
Referenced by ImageHistogram(), and setImage().
 {
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     const unsigned char* const* grayIn = img->getShiftedGray2D();
     //  clear the histogram
     for (int k=0; k<histVals_; k++)
         hist_[k] = 0L;
     //  and do the counting
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             hist_[grayIn[i][j]]++;
 }
void ImageHistogram::computeFloatHistogram_ (RasterImage_gray_F * img, const ImageRect * rect) protected
The function that does all the work for a float gray-level image, using custom histogram parameters (involving scaling and shifting)
Definition at line 296 of file ImageHistogram.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::ImageRect::getTop(), uriVL::Histogram::hist_, uriVL::Histogram::histVals_, uriVL::Histogram::ucRangeMax_, and uriVL::Histogram::ucRangeMin_.
Referenced by ImageHistogram(), and setImage().
 {
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     const float scale = (1.f * histVals_) / (ucRangeMax_ - ucRangeMin_);
     const float shift = -scale*ucRangeMin_;
     const float* const* grayIn = img->getShiftedGrayF2D();
     //  clear the histogram
     for (int k=0; k<histVals_; k++)
         hist_[k] = 0;
     //  and do the counting
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
             hist_[static_cast<int>(shift + scale*grayIn[i][j])]++;
 }
void ImageHistogram::computeHistogram_ (RasterImage_gray * img, const ImageRect * rect) protected
The function that does all the work for a regular (unsigned char) gray-level image, using custom histogram parameters (involving scaling and shifting)
Definition at line 257 of file ImageHistogram.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), uriVL::Histogram::hist_, uriVL::Histogram::histVals_, uriVL::Histogram::ucRangeMax_, and uriVL::Histogram::ucRangeMin_.
 {
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     const float scale = (1.f * histVals_) / (ucRangeMax_ - ucRangeMin_);
     const float shift = -scale*ucRangeMin_;
     const unsigned char* const* grayIn = img->getShiftedGray2D();
     //  clear the histogram
     for (int k=0; k<histVals_; k++)
         hist_[k] = 0L;
     //  If we have to compte a histogram for a large number of pixels (I arbitrarily put the bar
     //  at 4 times 256), then we are better  off precomputing a lookup table
     const long nbPixels = (iHigh-iLow+1)*(jHigh-jLow+1);
     if (nbPixels > 1024)
     {
         int   lut[256];
         for (int l=0; l<256; l++)
             lut[l] = static_cast<int>(shift + scale*l);
         //  and do the counting
         for (int i=iLow; i<=iHigh; i++)
             for (int j=jLow; j<=jHigh; j++)
                 hist_[lut[grayIn[i][j]]]++;
     }
     //  for the histogram of a small region, we perform the conversion for each pixel
     else
     {
         //  and do the counting
         for (int i=iLow; i<=iHigh; i++)
             for (int j=jLow; j<=jHigh; j++)
                 hist_[static_cast<int>(shift + scale*grayIn[i][j])]++;
      }
 }
long* uriVL::ImageHistogram::getHistogram (void) const
returns the histogram values cast to a pointer to char.
The histogram can be a single array of long (gray image) or a 3 1D arrays of long. The user should call getType() befefore using this function. You are probably better off calling getGrayHistogram or getColorHistogram;
Returns
histogram values
void ImageHistogram::setImage (RasterImage * img, const ImageRect * rect = NULL)
Assigns a new RasterImage and possibly an ImageRect over which to compute the histogram.
Determines whether a floating point or unsigned char histogram should be used, and possibly allocates a local gray raster if theimage sent in was a color image. Uses default values for the range [0, 256[ and the number of values of the histogram.
Users who know what they are doing should instead one of the next two constructors.
Parameters
img The image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
Definition at line 134 of file ImageHistogram.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by myMouse().
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor not open for business yet");
 }
void ImageHistogram::setImage (RasterImage_gray * img, const ImageRect * rect = NULL, int nbVals = HIST_DEFAULT_NB_VALS, unsigned char rangeMin = HIST_DEFAULT_RANGE_MIN_UC, unsigned char rangeMax = HIST_DEFAULT_RANGE_MAX_UC)
Assigns a new RasterImage_gray and possibly an ImageRect, and range values over which to compute the histogram.
Parameters
img The gray-level image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
nbVals The number of values/slots in the histogram
rangeMin The lower bound of values over the image
rangeMax The upper bound of values over the image
Definition at line 142 of file ImageHistogram.cpp.
References computeFastHistogram_(), uriVL::Histogram::computeHistogram_(), uriVL::Histogram::dataType_, FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::Histogram::hist_, HIST_DEFAULT_NB_VALS, HIST_DEFAULT_RANGE_MAX_UC, HIST_DEFAULT_RANGE_MIN_UC, uriVL::Histogram::histVals_, uriVL::ImageRect::intersection(), uriVL::Histogram::isRenderReady_, uriVL::kNullParameterError, uriVL::kNullRectangleError, uriVL::UCHAR_HIST, uriVL::Histogram::ucRangeMax_, and uriVL::Histogram::ucRangeMin_.
 {
     FAIL_CONDITION( img==NULL,
                     kNullParameterError,
                     "Null rast image passed to ImageHistogram constructor");
     //  determine the rectangle over which to perform the calculations
     const ImageRect   *theRect;
     bool        localRect = false;
     if (rect !=NULL)
     {
         theRect = ImageRect::intersection(rect, img->getValidRect());
         FAIL_CONDITION( theRect==NULL,
                         kNullRectangleError,
                         "Computation rectangle not within image valid data bounds in ImageHistogram constructor");
         localRect = true;
     }
     else
         theRect = img->getValidRect();
     dataType_ = UCHAR_HIST;
     //  If needed re-allocate the histogram and store its parameters
     if (nbVals != histVals_)
     {
         delete []hist_;
         hist_ = new long[nbVals];
         histVals_ = nbVals;
     }
     ucRangeMin_ = rangeMin;
     ucRangeMax_ = rangeMax;
     isRenderReady_ = false;
     //  We have two forms of the function: the "fast" form uses the default 256 values over the
     //  interval [0, 256[, that is no scaling nor shifting.  The "regular" function does the
     //  scaling and shifting calculations
     if ((nbVals==HIST_DEFAULT_NB_VALS) && (rangeMin==HIST_DEFAULT_RANGE_MIN_UC) &&
         (rangeMax==HIST_DEFAULT_RANGE_MAX_UC))
         computeFastHistogram_(img, theRect);
     else
         computeHistogram_(img, theRect);
     if (localRect)
         delete theRect;
 }
void ImageHistogram::setImage (RasterImage_gray_F * img, const ImageRect * rect = NULL, int nbVals = HIST_DEFAULT_NB_VALS, float rangeMin = HIST_DEFAULT_RANGE_MIN, float rangeMax = HIST_DEFAULT_RANGE_MAX)
Assigns a new RasterImage_gray and possibly an ImageRect, and range values over which to compute the histogram.
Parameters
img The gray-level image of which to calculate the histogram
rect Partial rectangle over which to compute the histogram. When NULL, the image's entire validRect is used
nbVals The number of values/slots in the histogram
rangeMin The lower bound of values over the image
rangeMax The upper bound of values over the image
Definition at line 190 of file ImageHistogram.cpp.
References computeFloatHistogram_(), uriVL::Histogram::dataType_, FAIL_CONDITION, uriVL::FLOAT_HIST, uriVL::Histogram::flRangeMax_, uriVL::Histogram::flRangeMin_, uriVL::DrawableObject2D::getValidRect(), uriVL::Histogram::hist_, uriVL::Histogram::histVals_, uriVL::ImageRect::intersection(), uriVL::Histogram::isRenderReady_, uriVL::kNullParameterError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( img==NULL,
                     kNullParameterError,
                     "Null rast image passed to ImageHistogram constructor");
     //  determine the rectangle over which to perform the calculations
     const ImageRect   *theRect;
     bool        localRect = false;
     if (rect !=NULL)
     {
         theRect = ImageRect::intersection(rect, img->getValidRect());
         FAIL_CONDITION( theRect==NULL,
                         kNullRectangleError,
                         "Computation rectangle not within image valid data bounds in ImageHistogram constructor");
         localRect = true;
     }
     else
         theRect = img->getValidRect();
     dataType_ = FLOAT_HIST;
     //  If needed re-allocate the histogram and store its parameters
     if (nbVals != histVals_)
     {
         delete []hist_;
         hist_ = new long[nbVals];
         histVals_ = nbVals;
     }
     flRangeMin_ = rangeMin;
     flRangeMax_ = rangeMax;
     isRenderReady_ = false;
     //  There is no point having two forms of the computation function since there will be scaling,
     //  shifting, and rounding no matter what we do.
     computeFloatHistogram_(img, theRect);
     if (localRect)
         delete theRect;
 }
void ImageHistogram::setRenderMode (HistogramRenderMode mode) virtual
Defines the rendering mode for the image histogram.
In my opinion a polar rendering makes no sense for a gray-level image, so we only accept LIN_LIN and LIN_LOG modes. Other mode selections are simply ignored.
Parameters
renderMode rendering mode
See also
renderMode_
Reimplemented from uriVL::Histogram.
Definition at line 318 of file ImageHistogram.cpp.
References uriVL::LIN_LIN, uriVL::LIN_LOG, and uriVL::Histogram::setRenderMode().
Referenced by myHistogramRenderModeSubmenu().
 {
     //  only accept LIN_LIN or LIN_LOG mode
     if ((mode==LIN_LIN) || (mode==LIN_LOG))
         Histogram::setRenderMode(mode);
 }
The documentation for this class was generated from the following files:
ImageHistogram.h
ImageHistogram.cpp