URIVisionLibrary: uriVL::StereoMatcher Class Reference
uriVL::StereoMatcher Class Reference abstract
Pure virtual parent class for all classes that implement a stereo matching algorithm.
#include <StereoMatcher.h>
Public Member Functions
StereoMatcher (const StereoPair *stereoPair)
Creates a new stereo matcher and set the stereo pair on which to operate.
~StereoMatcher (void)
Destructor.
virtual void setStereoPair (const StereoPair *stereoPair)
Assigns the stereo pair and processing rectangle for this matcher object.
StereoMatchRecord * match (const StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated.
StereoMatchRecord * match (ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
void match (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated.
void match (ImagePoint *pt, StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
StereoDisparity * disparity (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated.
StereoDisparity * disparity (ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
void disparity (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, StereoDisparity *disp, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated.
void disparity (ImagePoint *pt, StereoImageID l_or_r, StereoDisparity *disp, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
bool isSubpixelMatcher (void)
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
Protected Member Functions
StereoMatcher (void)
Default Constructor.
StereoMatcher (const StereoPair &theObj)
Copy Constructor.
const StereoMatcher & operator= (const StereoMatcher &theObj)
Copy operator.
virtual void computeSearchRect_ (ImagePoint *pt, const ImageRect *imgRect, const StereoImageID l_or_r, ImageRect *rect=NULL)=0
Computes a search rectangle for the target point.
virtual void match_ (StereoPair *stereoPair, ImagePoint *pt, const StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)=0
Function implemented by subclasses that computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Protected Attributes
PatternMatcher2D * matcher_
a stereo match
StereoPair * stereoPair_
StereoPair for this matcher to operate on (if one was set)
ImageRect * searchRect_
Search rectangle stored during a call to match.
StereoMatchRecord * matchRecord_
StereoMatchRecord record used to call private match function.
bool isSubpixelMatcher_
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
Detailed Description
Pure virtual parent class for all classes that implement a stereo matching algorithm.
Definition at line 36 of file StereoMatcher.h.
Constructor & Destructor Documentation
StereoMatcher::StereoMatcher (const StereoPair * stereoPair)
Creates a new stereo matcher and set the stereo pair on which to operate.
Parameters
pair reference to the image pair to process
Definition at line 28 of file StereoMatcher.cpp.
                 :       matcher_(NULL),
                         stereoPair_(stereoPair_),
                         searchRect_(new ImageRect(0, 0, 0, 0)),
                         matchRecord_(new StereoMatchRecord()),
                         isSubpixelMatcher_(false)
 {
 }
StereoMatcher::~StereoMatcher (void)
Destructor.
Definition at line 49 of file StereoMatcher.cpp.
References matchRecord_, and searchRect_.
 {
     delete matchRecord_;
     delete searchRect_;
 }
StereoMatcher::StereoMatcher (void) protected
Default Constructor.
Creates a new stereo matcher.
Definition at line 19 of file StereoMatcher.cpp.
                 :       matcher_(NULL),
                         stereoPair_(NULL),
                         searchRect_(new ImageRect(0, 0, 0, 0)),
                         matchRecord_(new StereoMatchRecord()),
                         isSubpixelMatcher_(false)
 {
 }
StereoMatcher::StereoMatcher (const StereoPair & theObj) protected
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 37 of file StereoMatcher.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       matcher_(NULL),
                         stereoPair_(NULL),
                         searchRect_(NULL),
                         matchRecord_(NULL),
                         isSubpixelMatcher_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoPair copy constructor not implemented");
 }
Member Function Documentation
virtual void uriVL::StereoMatcher::computeSearchRect_ (ImagePoint * pt, const ImageRect * imgRect, const StereoImageID l_or_r, ImageRect * rect = NULL) protected pure virtual
Computes a search rectangle for the target point.
Parameters
pt image point to find a match for
imgRect valid data rect (or computation rectangle) of the image. Defaults to the entire image
l_or_r is pt defined in the left or right image?
rect search rectangle for the point to match
Referenced by match().
StereoDisparity * StereoMatcher::disparity (StereoPair * stereoPair, ImagePoint * pt, StereoImageID l_or_r, const ImageRect * searchRect = NULL)
Computes the stereo disparity at the point indicated.
Parameters
stereoPair the stereo pair on which to operate
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
searchRect bounds for the search of a matching point in the other image
Returns
the disparity (and score) for the point indicated
Definition at line 148 of file StereoMatcher.cpp.
References uriVL::StereoMatchRecord::getBestMatch(), uriVL::StereoMatchRecord::getScore(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), match(), and matchRecord_.
 {
         match(stereoPair, pt, l_or_r, matchRecord_, searchRect);
         ImagePoint  *bestMatch = matchRecord_->getBestMatch();
         return new StereoDisparity( bestMatch->getX() - pt->getX(),
                                     bestMatch->getY() - pt->getY(),
                                     matchRecord_->getScore(),
                                     l_or_r);
 }
StereoDisparity * StereoMatcher::disparity (ImagePoint * pt, StereoImageID l_or_r, const ImageRect * searchRect = NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Parameters
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
searchRect bounds for the search of a matching point in the other image
Returns
the disparity (and score) for the point indicated
Definition at line 159 of file StereoMatcher.cpp.
References uriVL::StereoMatchRecord::getBestMatch(), uriVL::StereoMatchRecord::getScore(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), match(), matchRecord_, and stereoPair_.
 {
         match(stereoPair_, pt, l_or_r, matchRecord_, searchRect);
         ImagePoint  *bestMatch = matchRecord_->getBestMatch();
         return new StereoDisparity( bestMatch->getX() - pt->getX(),
                                     bestMatch->getY() - pt->getY(),
                                     matchRecord_->getScore(),
                                     l_or_r);
 }
void StereoMatcher::disparity (StereoPair * stereoPair, ImagePoint * pt, StereoImageID l_or_r, StereoDisparity * disp, const ImageRect * searchRect = NULL)
Computes the stereo disparity at the point indicated.
Parameters
stereoPair the stereo pair on which to operate
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
disp the disparity (and score) for the point indicated
searchRect bounds for the search of a matching point in the other image
Definition at line 186 of file StereoMatcher.cpp.
References FAIL_CONDITION, uriVL::StereoMatchRecord::getBestMatch(), uriVL::StereoMatchRecord::getScore(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kNullImagePointError, match(), matchRecord_, uriVL::Disparity::setDisparity(), and uriVL::Disparity::setScore().
 {
         FAIL_CONDITION( disp == NULL,
                     kNullImagePointError,
                     "NULL ImagePoint passed as parameter to StereoMatcher::match");
         match(stereoPair, pt, l_or_r, matchRecord_, searchRect);
         ImagePoint  *bestMatch = matchRecord_->getBestMatch();
     disp->setDisparity(bestMatch->getX() - pt->getX(),
                            bestMatch->getY() - pt->getY());
         disp->setScore(matchRecord_->getScore());
         disp->setIsSubpixelDisparity(false);
 }
void StereoMatcher::disparity (ImagePoint * pt, StereoImageID l_or_r, StereoDisparity * disp, const ImageRect * searchRect = NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Parameters
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
disp the disparity (and score) for the point indicated
searchRect bounds for the search of a matching point in the other image
Definition at line 170 of file StereoMatcher.cpp.
References FAIL_CONDITION, uriVL::StereoMatchRecord::getBestMatch(), uriVL::StereoMatchRecord::getScore(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kNullImagePointError, match(), matchRecord_, uriVL::Disparity::setDisparity(), uriVL::Disparity::setScore(), and stereoPair_.
 {
         FAIL_CONDITION( disp == NULL,
                     kNullImagePointError,
                     "NULL ImagePoint passed as parameter to StereoMatcher::match");
         match(stereoPair_, pt, l_or_r, matchRecord_, searchRect);
         ImagePoint  *bestMatch = matchRecord_->getBestMatch();
     disp->setDisparity(bestMatch->getX() - pt->getX(),
                            bestMatch->getY() - pt->getY());
         disp->setScore(matchRecord_->getScore());
         disp->setIsSubpixelDisparity(false);
 }
bool StereoMatcher::isSubpixelMatcher (void)
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
Returns
true if this matcher computes a subpixel disparity
Definition at line 78 of file StereoMatcher.cpp.
References isSubpixelMatcher_.
 {
         return isSubpixelMatcher_;
 }
StereoMatchRecord* uriVL::StereoMatcher::match (const StereoPair * stereoPair, ImagePoint * pt, StereoImageID l_or_r, const ImageRect * searchRect = NULL)
Computes the stereo match for the point indicated.
Parameters
stereoPair the stereo pair on which to operate
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
searchRect bounds for the search of a matching point in the other image
Returns
the best match (and score) for the point indicated
Referenced by disparity(), and match().
StereoMatchRecord * StereoMatcher::match (ImagePoint * pt, StereoImageID l_or_r, const ImageRect * searchRect = NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Parameters
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
searchRect bounds for the search of a matching point in the other image
Returns
the best match (and score) for the point indicated
Definition at line 97 of file StereoMatcher.cpp.
References match(), matchRecord_, and stereoPair_.
 {
         match(stereoPair_, pt, l_or_r, matchRecord_, searchRect);
         return new StereoMatchRecord(matchRecord_);
 }
void StereoMatcher::match (StereoPair * stereoPair, ImagePoint * pt, StereoImageID l_or_r, StereoMatchRecord * matchRec, const ImageRect * searchRect = NULL)
Computes the stereo match for the point indicated.
Parameters
stereoPair the stereo pair on which to operate
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
matchRec the best match (and score) for the point indicated
searchRect bounds for the search of a matching point in the other image
Definition at line 112 of file StereoMatcher.cpp.
References computeSearchRect_(), FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::StereoPair::getValidRect(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kNullImagePointError, uriVL::kNullParameterError, match_(), uriVL::StereoMatchRecord::setBestMatch(), and uriVL::StereoMatchRecord::setScore().
 {
         FAIL_CONDITION( stereoPair == NULL,
                     kNullParameterError,
                     "NULL stereo pair passed as parameter to StereoMatcher::match");
         FAIL_CONDITION( pt == NULL,
                     kNullImagePointError,
                     "NULL ImagePoint passed as parameter to StereoMatcher::match");
         FAIL_CONDITION( matchRec == NULL,
                     kNullParameterError,
                     "NULL StereoMatchRecord passed as parameter to StereoMatcher::match");
     ImageRect   *theRect;
     if (searchRect == NULL)
         theRect = new ImageRect(stereoPair->getValidRect(l_or_r));
     else
         theRect=  new ImageRect(searchRect);
         computeSearchRect_(pt, stereoPair->getValidRect(l_or_r), l_or_r, theRect);
         if ((theRect->getWidth()>0) && (theRect->getHeight()>0))
         match_(stereoPair, pt, l_or_r, matchRec, theRect);
         //  if the search rect is empty (the point is outside of the matchable area for
         //  the algorithm used) we simply set confidence to 0
     else
     {
         matchRec->setBestMatch(pt->getX(), pt->getY());
         matchRec->setScore(0);
     }
     delete theRect;
 }
void StereoMatcher::match (ImagePoint * pt, StereoImageID l_or_r, StereoMatchRecord * matchRec, const ImageRect * searchRect = NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Parameters
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
matchRec the best match (and score) for the point indicated
searchRect bounds for the search of a matching point in the other image
Definition at line 104 of file StereoMatcher.cpp.
References match(), and stereoPair_.
 {
         match(stereoPair_, pt, l_or_r, matchRec, searchRect);
 }
virtual void uriVL::StereoMatcher::match_ (StereoPair * stereoPair, ImagePoint * pt, const StereoImageID l_or_r, StereoMatchRecord * matchRec, const ImageRect * searchRect = NULL) protected pure virtual
Function implemented by subclasses that computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Parameters
pt the point for which to compute the disparity
l_or_r are we working left to right or right to left
matchRec the best match (and score) for the point indicated
searchRect bounds for the search of a matching point in the other image.
Referenced by match().
const StereoMatcher & StereoMatcher::operator= (const StereoMatcher & theObj) protected
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 56 of file StereoMatcher.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoMatcher copy operator not implemented");
         return *this;
 }
void StereoMatcher::setStereoPair (const StereoPair * stereoPair) virtual
Assigns the stereo pair and processing rectangle for this matcher object.
Parameters
stereoPair reference to the image pair to process
Definition at line 69 of file StereoMatcher.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, and stereoPair_.
 {
         FAIL_CONDITION( stereoPair == NULL,
                     kNullParameterError,
                     "NULL stereo pair passed as parameter to StereoMatcher::setStereoPair");
         stereoPair_ = stereoPair;
 }
Member Data Documentation
bool uriVL::StereoMatcher::isSubpixelMatcher_ protected
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
SShould be initialized by subclasses implementing an algorithm.
Definition at line 194 of file StereoMatcher.h.
Referenced by isSubpixelMatcher(), and uriVL::RectifiedStereoMatcher_corr::RectifiedStereoMatcher_corr().
PatternMatcher2D* uriVL::StereoMatcher::matcher_ protected
a stereo match
Definition at line 175 of file StereoMatcher.h.
Referenced by uriVL::RectifiedStereoMatcher_corr::match_(), uriVL::RectifiedStereoMatcher_corr::RectifiedStereoMatcher_corr(), and uriVL::RectifiedStereoMatcher_corr::~RectifiedStereoMatcher_corr().
StereoMatchRecord* uriVL::StereoMatcher::matchRecord_ protected
StereoMatchRecord record used to call private match function.
This object is reused rather than being created at each call of the public match functions.
Definition at line 187 of file StereoMatcher.h.
Referenced by disparity(), match(), and ~StereoMatcher().
ImageRect* uriVL::StereoMatcher::searchRect_ protected
Search rectangle stored during a call to match.
Definition at line 183 of file StereoMatcher.h.
Referenced by ~StereoMatcher().
StereoPair* uriVL::StereoMatcher::stereoPair_ protected
StereoPair for this matcher to operate on (if one was set)
Definition at line 179 of file StereoMatcher.h.
Referenced by disparity(), match(), setStereoPair(), and uriVL::RectifiedStereoMatcher::setStereoPair().
The documentation for this class was generated from the following files:
StereoMatcher.h
StereoMatcher.cpp