URIVisionLibrary: uriVL::ImagePoint_F Class Reference
uriVL::ImagePoint_F Class Reference
Implements the ImagePoint_F class.
#include <ImagePoint_F.h>
Public Member Functions
ImagePoint_F (void)
Default Constructor.
ImagePoint_F (float theX, float theY)
Constructor.
ImagePoint_F (const float theXY[])
Constructor.
ImagePoint_F (const ImagePoint_F *thePt)
Copy constructor.
ImagePoint_F (const ImagePoint *thePt)
Copy constructor.
ImagePoint_F (const ImagePoint_F &thePt)
Copy constructor.
~ImagePoint_F (void)
Destructor.
const ImagePoint_F & operator= (const ImagePoint_F &thePt)
Equal operator.
bool hasSubpixelPrecision (void) const
Indicates that the image point has subpixel precision coordinates.
float getXF (void) const
Returns the pixel's x coordinate.
float getYF (void) const
Returns the pixel's y coordinate.
void setX (int val)
Assigns new x coordinate to the pixel.
void setX (float val)
Assigns new x coordinate to the pixel.
void setY (int val)
Assigns new y coordinate to the pixel.
void setY (float val)
Assigns new y coordinate to the pixel.
void setCoordinates (int valX, int valY)
Assigns new coordinates to the pixel.
void setCoordinates (const int *xy)
Assigns new coordinates to the pixel.
void setCoordinates (float valX, float valY)
Assigns new coordinates to the pixel.
void setCoordinates (const float *xy)
Assigns new coordinates to the pixel.
void setCoordinates (const ImagePoint *thePt)
Assigns new coordinates to the pixel.
void setCoordinates (const ImagePoint &thePt)
Assigns new coordinates to the pixel.
void translate (int dx, int dy)
Shifts the existing x and y coordinates by the amount specified.
void translate (float dx, float dy)
Shifts the existing x and y coordinate by the amount specified.
void shiftX (int dx)
Shifts the existing x coordinate by the amount specified.
void shiftX (float dx)
Shifts the existing x coordinate by the amount specified.
void shiftY (float dy)
Shifts the existing y coordinate by the amount specified.
void shiftY (int dy)
Shifts the existing y coordinate by the amount specified.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Public Member Functions inherited from uriVL::ImagePoint
ImagePoint (bool hasSubpixelPrecision=false)
Default Constructor.
ImagePoint (int x, int y, bool hasSubpixelPrecision=false)
Constructor.
ImagePoint (const int xy[], bool hasSubpixelPrecision=false)
Constructor.
ImagePoint (const ImagePoint *thePt)
Copy constructor.
ImagePoint (const ImagePoint &thePt)
Copy constructor.
virtual ~ImagePoint (void)
Destructor.
const ImagePoint & operator= (const ImagePoint &thePt)
Equal operator.
int getX (void) const
Returns the point's x coordinate.
int getY (void) const
Returns the point's y coordinate.
int getID (void) const
Returns the point's id.
virtual void setCoordinates (const int xy[])
Assigns new coordinates to the pixel.
float distanceTo (const ImagePoint *pt)
Computes the distance between this point and the one passed as parameter.
Private Attributes
float xf_
The pixel's x coordinate.
float yf_
The pixel's y coordinate.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::ImagePoint
static float distance (const ImagePoint *pt1, const ImagePoint *pt2)
Computes the distance between two points.
Detailed Description
Implements the ImagePoint_F class.
An ImagePoint_F object represents a dimensionless mathematical point. This class should be used for all applications requiring subpixel precision.
Version history
2004/11/20 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 37 of file ImagePoint_F.h.
Constructor & Destructor Documentation
ImagePoint_F::ImagePoint_F (void)
Default Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Definition at line 29 of file ImagePoint_F.cpp.
         :       ImagePoint(true),
                 //
                 xf_(0.f),
                 yf_(0.f)
 {
 }
ImagePoint_F::ImagePoint_F (float theX, float theY)
Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Parameters
theX x coordinate of the pixel
theY y coordinate of the pixel
Definition at line 38 of file ImagePoint_F.cpp.
         :       ImagePoint(static_cast<int>(theX), static_cast<int>(theY), true),
                 //
                 xf_(theX),
                 yf_(theY)
 {
 }
uriVL::ImagePoint_F::ImagePoint_F (const float theXY[])
Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Parameters
theXY coordinate array of the pixel
ImagePoint_F::ImagePoint_F (const ImagePoint_F * thePt)
Copy constructor.
Creates a clone of the ImagePoint object passed as parameter.
Parameters
thePt pointer to the ImagePoint_F object to clone
Definition at line 63 of file ImagePoint_F.cpp.
                 :       ImagePoint(thePt),
                         //
                         xf_(thePt->xf_),
                         yf_(thePt->yf_)
 {
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by ImagePoint_F constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint pointer passed to ImagePoint_F constructor.");
 }
ImagePoint_F::ImagePoint_F (const ImagePoint * thePt)
Copy constructor.
Creates a clone of the ImagePoint object passed as parameter.
Parameters
thePt pointer to the ImagePoint object to clone
Definition at line 81 of file ImagePoint_F.cpp.
                 :       ImagePoint(thePt),
                         //
                         xf_(thePt->hasSubpixelPrecision() ? static_cast<const ImagePoint_F*>(thePt)->getXF() : thePt->getX()),
                         yf_(thePt->hasSubpixelPrecision() ? static_cast<const ImagePoint_F*>(thePt)->getYF() : thePt->getY())
 {
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by ImagePoint_F constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint pointer passed to ImagePoint_F constructor.");
 }
ImagePoint_F::ImagePoint_F (const ImagePoint_F & thePt)
Copy constructor.
Creates a clone of the ImagePoint object passed as parameter.
Parameters
thePt reference to the ImagePoint object to copy
Definition at line 99 of file ImagePoint_F.cpp.
                 :       ImagePoint(thePt),
                         //
                         xf_(thePt.xf_),
                         yf_(thePt.yf_)
 {
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by ImagePoint_F constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint reference passed to ImagePoint_F constructor.");
 }
ImagePoint_F::~ImagePoint_F (void)
Destructor.
Definition at line 116 of file ImagePoint_F.cpp.
 {
 }
Member Function Documentation
void ImagePoint_F::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Reimplemented from uriVL::ImagePoint.
Definition at line 371 of file ImagePoint_F.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
float ImagePoint_F::getXF (void) const
Returns the pixel's x coordinate.
Returns
x coordinate of the pixel
Definition at line 252 of file ImagePoint_F.cpp.
References xf_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::Contour_F::contains(), uriVL::ImagePoint::distance(), uriVL::ImagePoint::rotate(), and uriVL::Vector2D_F::setCoordinates().
 {
     return xf_;
 }
float ImagePoint_F::getYF (void) const
Returns the pixel's y coordinate.
Returns
y coordinate of the pixel
Definition at line 257 of file ImagePoint_F.cpp.
References yf_.
Referenced by uriVL::Calibration3D_Kim::calibrate_linear_(), uriVL::Contour_F::contains(), uriVL::ImagePoint::distance(), and uriVL::ImagePoint::rotate().
 {
     return yf_;
 }
bool uriVL::ImagePoint_F::hasSubpixelPrecision (void) const inline virtual
Indicates that the image point has subpixel precision coordinates.
Returns
true if image point has subpixel precision
Reimplemented from uriVL::ImagePoint.
Definition at line 99 of file ImagePoint_F.h.
{
                                 return true;
                         }
const ImagePoint_F& uriVL::ImagePoint_F::operator= (const ImagePoint_F & thePt)
Equal operator.
Created so that gcc will stop complaining.
Parameters
thePt reference to the ImagePoint object to copy
void ImagePoint_F::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Reimplemented from uriVL::ImagePoint.
Definition at line 334 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     const float cT = cosf(angle),
                 sT = sinf(angle);
     //  if the rotation center is null we rotate around the origin
     if (rotCenter == NULL)
     {
         const float x = cT*xf_ - sT*yf_;
         yf_ = sT*xf_ + cT*yf_;
         xf_ = x;
     }
     else
     {
                 float xcf, ycf;
         if (typeid(*rotCenter) == typeid(uriVL::ImagePoint_F))
         {
                 const ImagePoint_F      *rotCenterF = (ImagePoint_F*) rotCenter;
                 xcf = rotCenterF->xf_;
                 ycf = rotCenterF->yf_;
         }
         else
         {
                 xcf = rotCenter->getX();
                 ycf = rotCenter->getY();
         }
                 const float dx = x_ - xcf;
                 const float dy = y_ - ycf;
                 xf_ = xcf + cT*dx - sT*dy;
                 yf_ = ycf + sT*dx + cT*dy;
     }
     x_ = static_cast<int>(round(xf_));
     y_ = static_cast<int>(round(yf_));
 }
void ImagePoint_F::setCoordinates (int valX, int valY) virtual
Assigns new coordinates to the pixel.
Parameters
valY new x coordinate for the pixel
valY new y coordinate for the pixel
Reimplemented from uriVL::ImagePoint.
Definition at line 158 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
Referenced by uriVL::Contour_F::computeCenterOfMass_(), uriVL::ContourForce::computeCenterOfMass_(), uriVL::Contour_I::computeCenterOfMass_(), uriVL::Histogram::computeCenterOfMass_(), uriVL::Blob::computeCenterOfMass_(), uriVL::Contour_F::computeCentroid_(), uriVL::ContourForce::computeCentroid_(), uriVL::Contour_I::computeCentroid_(), uriVL::Histogram::computeCentroid_(), uriVL::Blob::computeCentroid_(), uriVL::Camera::getImagePoint(), and uriVL::TrackingState::setPos().
 {
     x_ = valX;
     y_ = valY;
     xf_ = valX;
     yf_ = valY;
 }
void ImagePoint_F::setCoordinates (const int * xy)
Assigns new coordinates to the pixel.
Parameters
theXY coordinate array of the pixel
Definition at line 166 of file ImagePoint_F.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to ImagePoint::setCoordinates");
         try {
                 x_ = xy[0];
                 y_ = xy[1];
                 xf_ = xy[0];
                 yf_ = xy[1];
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
 }
void ImagePoint_F::setCoordinates (float valX, float valY)
Assigns new coordinates to the pixel.
Parameters
valY new x coordinate for the pixel
valY new y coordinate for the pixel
Definition at line 149 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     xf_ = valX;
     yf_ = valY;
     x_=static_cast<int>(round(xf_));
     y_=static_cast<int>(round(yf_));
 }
void ImagePoint_F::setCoordinates (const float * xy)
Assigns new coordinates to the pixel.
Parameters
theXY coordinate array of the pixel
Definition at line 128 of file ImagePoint_F.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to ImagePoint::setCoordinates");
         try {
                 xf_ = xy[0];
                 yf_ = xy[1];
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
     x_ = static_cast<int>(round(xf_));
     y_ = static_cast<int>(round(yf_));
 }
void ImagePoint_F::setCoordinates (const ImagePoint * thePt) virtual
Assigns new coordinates to the pixel.
Parameters
thePt pointer to the ImagePoint object to copy
Reimplemented from uriVL::ImagePoint.
Definition at line 185 of file ImagePoint_F.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::ImagePoint::setX(), uriVL::ImagePoint::setY(), xf_, uriVL::ImagePoint::y_, and yf_.
 {
     FAIL_CONDITION( thePt == NULL,
                     kNullParameterError,
                     "null ImagePoint passed to ImagePoint::setCoordinates");
         try {
                 if (typeid(*thePt) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F      *thePtF = (ImagePoint_F*) thePt;
                         xf_ = thePtF->xf_;
                         yf_ = thePtF->yf_;
                         ImagePoint::setX(thePt->getX());
                         ImagePoint::setY(y_ = thePt->getY());
                 }
                 else
                 {
                         int x = thePt->getX(),
                                 y = thePt->getY();
                         ImagePoint::setX(x);
                         ImagePoint::setY(y);
                         xf_ = x;
                         yf_ = y;
                 }
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
 }
void ImagePoint_F::setCoordinates (const ImagePoint & thePt) virtual
Assigns new coordinates to the pixel.
Parameters
thePt reference to the ImagePoint object to copy
Reimplemented from uriVL::ImagePoint.
Definition at line 217 of file ImagePoint_F.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kInvalidParameterError, uriVL::ImagePoint::setX(), uriVL::ImagePoint::setY(), xf_, uriVL::ImagePoint::y_, and yf_.
 {
         try {
                 if (typeid(thePt) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F      *thePtF = (ImagePoint_F*) &thePt;
                         xf_ = thePtF->xf_;
                         yf_ = thePtF->yf_;
                         ImagePoint::setX(thePt.getX());
                         ImagePoint::setY(y_ = thePt.getY());
                 }
                 else
                 {
                         int x = thePt.getX(),
                                 y = thePt.getY();
                         ImagePoint::setX(x);
                         ImagePoint::setY(y);
                         xf_ = x;
                         yf_ = y;
                 }
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
 }
void ImagePoint_F::setX (int val) virtual
Assigns new x coordinate to the pixel.
Parameters
val new x coordinate for the pixel
Reimplemented from uriVL::ImagePoint.
Definition at line 268 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, and xf_.
 {
     xf_ = theX;
         x_ = theX;
 }
void ImagePoint_F::setX (float val)
Assigns new x coordinate to the pixel.
Parameters
val new x coordinate for the pixel
Definition at line 262 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, and xf_.
 {
     x_ = static_cast<int>(round(theX));
     xf_ = theX;
 }
void ImagePoint_F::setY (int val) virtual
Assigns new y coordinate to the pixel.
Parameters
val new y coordinate for the pixel
Reimplemented from uriVL::ImagePoint.
Definition at line 274 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::y_, and yf_.
 {
     y_ = theY;
     yf_ = theY;
 }
void ImagePoint_F::setY (float val)
Assigns new y coordinate to the pixel.
Parameters
val new y coordinate for the pixel
Definition at line 280 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::y_, and yf_.
 {
     y_ = static_cast<int>(round(theY));
     yf_ = theY;
 }
void ImagePoint_F::shiftX (int dx) virtual
Shifts the existing x coordinate by the amount specified.
Parameters
dx a positive or negative x displacement
Reimplemented from uriVL::ImagePoint.
Definition at line 293 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, and xf_.
 {
     x_ += dx;
     xf_ += dx;
 }
void ImagePoint_F::shiftX (float dx)
Shifts the existing x coordinate by the amount specified.
Parameters
dx a positive or negative x displacement
Definition at line 299 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, and xf_.
 {
     xf_ += dx;
     x_=static_cast<int>(round(xf_));
 }
void ImagePoint_F::shiftY (float dy)
Shifts the existing y coordinate by the amount specified.
Parameters
dy a positive or negative y displacement
Definition at line 305 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::y_, and yf_.
 {
     yf_ += dy;
     y_=static_cast<int>(round(yf_));
 }
void ImagePoint_F::shiftY (int dy) virtual
Shifts the existing y coordinate by the amount specified.
Parameters
dy a positive or negative y displacement
Reimplemented from uriVL::ImagePoint.
Definition at line 311 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::y_, and yf_.
 {
     y_ += dy;
     yf_ += dy;
 }
void ImagePoint_F::translate (int dx, int dy) virtual
Shifts the existing x and y coordinates by the amount specified.
Parameters
dx a positive or negative x displacement
dy a positive or negative y displacement
Reimplemented from uriVL::ImagePoint.
Definition at line 317 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     x_ += dx;
     y_ += dy;
     xf_ += dx;
     yf_ += dy;
 }
void ImagePoint_F::translate (float dx, float dy)
Shifts the existing x and y coordinate by the amount specified.
Parameters
dx a positive or negative x displacement
dy a positive or negative y displacement
Definition at line 325 of file ImagePoint_F.cpp.
References uriVL::ImagePoint::x_, xf_, uriVL::ImagePoint::y_, and yf_.
 {
     xf_ += dx;
     yf_ += dy;
     x_ = static_cast<int>(round(xf_));
     y_ = static_cast<int>(round(yf_));
 }
Member Data Documentation
float uriVL::ImagePoint_F::xf_ private
The pixel's x coordinate.
Definition at line 236 of file ImagePoint_F.h.
Referenced by getXF(), rotate(), setCoordinates(), setX(), shiftX(), and translate().
float uriVL::ImagePoint_F::yf_ private
The pixel's y coordinate.
Definition at line 241 of file ImagePoint_F.h.
Referenced by getYF(), rotate(), setCoordinates(), setY(), shiftY(), and translate().
The documentation for this class was generated from the following files:
ImagePoint_F.h
ImagePoint_F.cpp