URIVisionLibrary: uriVL::Pattern2DMatchRecord Class Reference
uriVL::Pattern2DMatchRecord Class Reference
Holds the records of a 2D matching result.
#include <Pattern2DMatchRecord.h>
Public Member Functions
Pattern2DMatchRecord (void)
Default constructor.
Pattern2DMatchRecord (const ImagePoint *bestMatch, float score)
Creates a new match record with the best matching point and score specified.
Pattern2DMatchRecord (int x, int y, float score)
Creates a new match record with the best matching point and score specified.
~Pattern2DMatchRecord (void)
Destructor.
float getScore (void)
Returns the score of the best match found.
ImagePoint * getBestMatch (void)
Returns the location of the best match.
void setScore (float score)
Sets the score.
void setBestMatch (int x, int y)
Sets the coordinates of the best match.
void setBestMatch (const ImagePoint *bestMatch)
Sets the coordinates of the best match.
const std::string getRecordType (void) const
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Protected Attributes
ImagePoint * bestMatch_
best matching point
float score_
confidence score
bool isSubpixelMatch_
Indicates whether the match was calculated with subpixel accuracy (false by default)
std::string recordType_
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Friends
class PatternMatcher2D
Detailed Description
Holds the records of a 2D matching result.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file Pattern2DMatchRecord.h.
Constructor & Destructor Documentation
Pattern2DMatchRecord::Pattern2DMatchRecord (void)
Default constructor.
Definition at line 21 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::Pattern2DMatchRecord_part::Pattern2DMatchRecord_part().
 {
         bestMatch_ = new ImagePoint(0, 0);
         score_ = 0.f;
         recordType_ = "generic record ";
 }
Pattern2DMatchRecord::Pattern2DMatchRecord (const ImagePoint * bestMatch, float score)
Creates a new match record with the best matching point and score specified.
Parameters
bestMatch location of the best match found
score score of the best match
Definition at line 28 of file Pattern2DMatchRecord.cpp.
 {
         bestMatch_ = new ImagePoint(bestMatch);
         score_ = score;
         recordType_ = "generic record ";
 }
Pattern2DMatchRecord::Pattern2DMatchRecord (int x, int y, float score)
Creates a new match record with the best matching point and score specified.
Parameters
x x coordinate for this record's best match point
y y coordinate for this record's best match point
score score of the best match
Definition at line 35 of file Pattern2DMatchRecord.cpp.
 {
         bestMatch_ = new ImagePoint(x, y);
         score_ = score;
         recordType_ = "generic record ";
 }
Pattern2DMatchRecord::~Pattern2DMatchRecord (void)
Destructor.
Definition at line 43 of file Pattern2DMatchRecord.cpp.
 {
         delete bestMatch_;
 }
Member Function Documentation
ImagePoint * Pattern2DMatchRecord::getBestMatch (void)
Returns the location of the best match.
Definition at line 61 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::Pattern2DMatchRecord_part::getBestMatch(), uriVL::RectifiedStereoMatcher_corr::match_(), and performMatching().
 {
     return bestMatch_;
 }
const string Pattern2DMatchRecord::getRecordType (void) const
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Definition at line 95 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::PatternMatcher2D_warp::isProperMatchRecordType_(), and uriVL::PatternMatcher2D_partCorr::isProperMatchRecordType_().
 {
     return recordType_;
 }
float Pattern2DMatchRecord::getScore (void)
Returns the score of the best match found.
Definition at line 55 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::Pattern2DMatchRecord_part::getScore(), uriVL::RectifiedStereoMatcher_corr::match_(), performMatching(), and uriVL::PatternTracker2D::track().
 {
     return score_;
 }
void Pattern2DMatchRecord::setBestMatch (int x, int y)
Sets the coordinates of the best match.
Parameters
x new x coordinate for this record's best match point
y new y coordinate for this record's best match point
Definition at line 72 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), and uriVL::Pattern2DMatchRecord_part::setBestMatch().
 {
     if (bestMatch_ == NULL)
         bestMatch_ = new ImagePoint(x, y);
     else
         bestMatch_->setCoordinates(x, y);
 }
void Pattern2DMatchRecord::setBestMatch (const ImagePoint * bestMatch)
Sets the coordinates of the best match.
Parameters
bestMatch new best match point for this record
Definition at line 81 of file Pattern2DMatchRecord.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and uriVL::kNullImagePointError.
 {
     FAIL_CONDITION( bestMatch == NULL,
                     kNullImagePointError,
                     "null ImagePoint passed to Pattern2DMatchRecord::setBestMatch");
     if (bestMatch_ == NULL)
         bestMatch_ = new ImagePoint(bestMatch);
     else
         bestMatch_->setCoordinates(bestMatch->getX(), bestMatch->getY());
 }
void Pattern2DMatchRecord::setScore (float score)
Sets the score.
Parameters
score the new score for this record
Definition at line 66 of file Pattern2DMatchRecord.cpp.
Referenced by uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), uriVL::PatternMatcher2D_warp::match_(), and uriVL::Pattern2DMatchRecord_part::setScore().
 {
     score_ = score;
 }
Friends And Related Function Documentation
friend class PatternMatcher2D friend
Definition at line 41 of file Pattern2DMatchRecord.h.
Member Data Documentation
ImagePoint* uriVL::Pattern2DMatchRecord::bestMatch_ protected
best matching point
Definition at line 103 of file Pattern2DMatchRecord.h.
bool uriVL::Pattern2DMatchRecord::isSubpixelMatch_ protected
Indicates whether the match was calculated with subpixel accuracy (false by default)
Definition at line 112 of file Pattern2DMatchRecord.h.
Referenced by uriVL::Pattern2DMatchRecord_warp::Pattern2DMatchRecord_warp().
std::string uriVL::Pattern2DMatchRecord::recordType_ protected
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Definition at line 117 of file Pattern2DMatchRecord.h.
Referenced by uriVL::Pattern2DMatchRecord_part::Pattern2DMatchRecord_part().
float uriVL::Pattern2DMatchRecord::score_ protected
confidence score
Definition at line 107 of file Pattern2DMatchRecord.h.
The documentation for this class was generated from the following files:
Pattern2DMatchRecord.h
Pattern2DMatchRecord.cpp