URIVisionLibrary: uriVL::RasterImage_HSV Class Reference
uriVL::RasterImage_HSV Class Reference
A RasterImage_HSV is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel.
#include <RasterImage_HSV.h>
Public Member Functions
RasterImage_HSV (int theRows, int theCols)
Creates a RasterImage_HSV object at the specified dimensions.
RasterImage_HSV (const ImageRect *theRect)
Allocates an HSV raster image at the specified dimensions.
RasterImage_HSV (int theRows, int theCols, const unsigned int *hue, const unsigned char *sat, const unsigned char *val)
Creates and initializes a raster image using the specified dimensions and values.
RasterImage_HSV (const RasterImage *img)
Cloner constructor.
RasterImage_HSV (const RasterImage *img, const ImageRect *theRect)
Initializes an HSV raster image at the specified dimensions and values.
RasterImage_HSV (const RasterImage_HSV &obj)
Copy constructor.
virtual ~RasterImage_HSV (void)
Destructor.
const RasterImage_HSV & operator= (const RasterImage_HSV &obj)
Copy operator.
const int * getHue (void) const
Returns the hue as a read-only 1D raster.
int * getHue (ReadWriteStatus rw)
Returns the hue as a read-write 1D raster.
const int *const * getHue2D (void) const
Returns the hue as a read-only 2D raster.
int *const * getHue2D (ReadWriteStatus rw)
Returns the hue as a read-write 2D raster.
const int *const * getShiftedHue2D (void) const
Returns the hue as a read-only shifted 2D raster.
int *const * getShiftedHue2D (ReadWriteStatus rw)
Returns the hue as a read-write shifted 2D raster.
const unsigned char * getSat (void) const
Returns the saturation as a read-only 1D raster.
unsigned char * getSat (ReadWriteStatus rw)
Returns the saturation as a read-write 1D raster.
const unsigned char *const * getSat2D (void) const
Returns the saturation as a read-only 2D raster.
unsigned char *const * getSat2D (ReadWriteStatus rw)
Returns the saturation as a read-write 2D raster.
const unsigned char *const * getShiftedSat2D (void) const
Returns the saturation as a read-only shifted 2D raster.
unsigned char *const * getShiftedSat2D (ReadWriteStatus rw)
Returns the saturation as a read-write shifted 2D raster.
const unsigned char * getVal (void) const
Returns the value as a read-only 1D raster.
unsigned char * getVal (ReadWriteStatus rw)
Returns the value as a read-write 1D raster.
const unsigned char *const * getVal2D (void) const
Returns the value as a read-only 2D raster.
unsigned char *const * getVal2D (ReadWriteStatus rw)
Returns the value as a read-write 2D raster.
const unsigned char *const * getShiftedVal2D (void) const
Returns the value as a read-only shifted 2D raster.
unsigned char *const * getShiftedVal2D (ReadWriteStatus rw)
Returns the value as a read-write shifted 2D raster.
const unsigned char * getRGBa (void) const
Returns the 32-bit rgba base raster as a read-only 1D array.
unsigned char * getRGBa (ReadWriteStatus rw)
Returns the 32-bit rgba base raster as a read-write 1D array.
const unsigned char *const * getRGBa2D (void) const
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
unsigned char *const * getRGBa2D (ReadWriteStatus rw)
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
const unsigned char *const * getShiftedRGBa2D (void) const
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
unsigned char *const * getShiftedRGBa2D (ReadWriteStatus rw)
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
virtual void setHsvAsReference (void)
Sets this image's HSV rasters as the reference.
void forceConversionToSaturatedRGBa (void)
Forces a conversion of the image's gworld rasters into a saturated image based on curent hue raster.
Public Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
RasterImage_RGBa (const ImageRect *theRect)
Allocates a 32-bit RGBa color raster image at the specified dimensions.
RasterImage_RGBa (int nbRows, int nbCols, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const ImageRect *theRect, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (GraphWorld *gworld, bool keepThisGraphWorld=false)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img)
Initializes an rgba raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img, const ImageRect *theRect)
Initializes an rgba raster image at the specified dimensions and values.
virtual ~RasterImage_RGBa (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void rgb2HSV (unsigned char r, unsigned char g, unsigned char b, int *hue, unsigned char *sat, unsigned char *val)
Converts an rgb value to hue, saturation, and value.
static void rgb2HSV (const unsigned char rgb[], int *hue, unsigned char *sat, unsigned char *val)
Converts an rgb value to hue, saturation, and value.
static const RasterImage_HSV * localRasterHSV (const RasterImage *imgIn, bool *localHSV)
Allocates a read-only HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
static const RasterImage_HSV * localRasterHSV (const RasterImage *imgIn, const ImageRect *rect, bool *localHSV)
Allocates a read-only HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
static RasterImage_HSV * localRasterHSV (RasterImage *imgIn, bool *localHSV)
Allocates a writable HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
static RasterImage_HSV * localRasterHSV (RasterImage *imgIn, const ImageRect *rect, bool *localHSV)
Allocates a writable HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
Static Public Member Functions inherited from uriVL::RasterImage_RGBa
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Copies a 1D RGBa32 raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 16-bit aRGB16 raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, bool *localRGBa)
Allocates a read-only RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Private Member Functions
RasterImage_HSV (void)
Creates an undimensioned RGBa float color raster image.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
void deleteHSV_ (void)
Deletes the raster image's private hue, saturation and value rasters.
void convertToRGBa_ (void)
Updates the RGBa raster of this raster image to match the HSV rasters.
void convertToRGBa_ (const ImageRect *theRect)
Updates the RGBa raster of this raster image to match the HSV rasters on the image rectangle specified.
void convertToSaturatedRGBa_ (void)
Updates the RGBa raster of this raster image to match a saturated version the HSV rasters (where a value of 100 has been used for the saturation)
void convertToSaturatedRGBa_ (const ImageRect *theRect)
Updates the RGBa raster of this raster image to match a saturated version the HSV rasters (where a value of 100 has been used for the saturation) on the image rectangle specified.
void convertFromGray_ (const RasterImage_gray *imgIn)
Calculates HSV values for the input gray-level image received as parameter.
void convertFromGray_ (const RasterImage_gray *imgIn, const ImageRect *theRect)
Calculates HSV values for the input gray-level image received as parameter.
void convertFromRGBa_ (const RasterImage_RGBa *imgIn)
Calculates HSV values for the input RGBa image received as parameter.
void convertFromRGBa_ (const RasterImage_RGBa *imgIn, const ImageRect *theRect)
Calculates HSV values for the input RGBa image received as parameter.
void convertFromARGB16_ (const RasterImage_aRGB16 *imgIn)
Calculates HSV values for the input aRGB16 image received as parameter.
void convertFromARGB16_ (const RasterImage_aRGB16 *imgIn, const ImageRect *theRect)
Calculates HSV values for the input aRGB16 image received as parameter.
void convertFromRGB_ (const RasterImage_RGB *imgIn)
Calculates HSV values for the input RGB image received as parameter.
void convertFromRGB_ (const RasterImage_RGB *imgIn, const ImageRect *theRect)
Calculates HSV values for the input RGB image received as parameter.
void updateRaster_ (void) const
Forces an update of the base rgb raster if it is not the reference raster.
Private Attributes
int * hue_
1D raster storing the hue of this image (range [0, 359])
unsigned char * sat_
1D raster storing the saturation of this image (range [0, 100])
unsigned char * val_
1D raster storing the value of this image (range [0, 255])
int ** hue2D_
unshifted 2D raster storing the hue of this image (range [0, 359])
unsigned char ** sat2D_
unshifted 2D raster storing the saturation of this image (range [0, 100])
unsigned char ** val2D_
unshifted 2D raster storing the value of this image (range [0, 255])
int ** shiftedHue2D_
shifted 2D raster storing the hue of this image (range [0, 359])
unsigned char ** shiftedSat2D_
shifted 2D raster storing the saturation of this image (range [0, 100])
unsigned char ** shiftedVal2D_
shifted 2D raster storing the value of this image (range [0, 255])
bool hsvIsReference_
true when the HSV rasters define the reference for this image
Friends
class RasterImage_RGBa
Additional Inherited Members
Protected Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (void)
Protected default constructor.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Detailed Description
A RasterImage_HSV is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file RasterImage_HSV.h.
Constructor & Destructor Documentation
RasterImage_HSV::RasterImage_HSV (int theRows, int theCols)
Creates a RasterImage_HSV object at the specified dimensions.
Parameters
nbRows number of rows of the hsv raster image
nbCols number of columns of the hsv raster image
Definition at line 96 of file RasterImage_HSV.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::RasterImage::setHasOtherRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(nbRows, nbCols),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
         //
         setHasOtherRaster_(true);
 //    setHsvAsReference();
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::RasterImage_HSV (const ImageRect * theRect)
Allocates an HSV raster image at the specified dimensions.
Allocates an HSV color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 124 of file RasterImage_HSV.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::RasterImage::setHasOtherRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(theRect),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
 //      allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
         //
         setHasOtherRaster_(true);
 //    setHsvAsReference();
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::RasterImage_HSV (int theRows, int theCols, const unsigned int * hue, const unsigned char * sat, const unsigned char * val)
Creates and initializes a raster image using the specified dimensions and values.
Parameters
nbRows number of rows of the hsv raster image
nbCols number of columns of the hsv raster image
hue 1D raster storing hue values in the range [0, 359]
sat 1D raster storing saturation values in the range [0, 100]
val 1D raster storing the value in the range [0, 255]
Definition at line 153 of file RasterImage_HSV.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), FAIL_CONDITION, hue_, uriVL::kNullRasterError, sat_, uriVL::RasterImage::setHasOtherRaster_(), setHsvAsReference(), uriVL::RasterImage::setReferenceHasChanged_(), uriVL::DrawableObject2D::setValidRect(), and val_.
                         :       RasterImage_RGBa(nbRows, nbCols),
                         //
                         hue_(NULL),
                         sat_(NULL),
                         val_(NULL),
                         hue2D_(NULL),
                         sat2D_(NULL),
                         val2D_(NULL),
                         shiftedHue2D_(NULL),
                         shiftedSat2D_(NULL),
                         shiftedVal2D_(NULL),
                         //
                         hsvIsReference_(false)
 {
     FAIL_CONDITION(     (hue==NULL) || (sat==NULL) || (val==NULL),
                     kNullRasterError,
                     "NULL array passed to RasterImage_HSV constructor");
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
         //
     const long  nbPixels = nbRows * nbCols;
     //  There is no padding for the H, S, & V arrays, so global memcpy calls are possible
     memcpy((char* ) hue_, (char* ) hue, static_cast<unsigned long>(sizeof(int)*nbPixels));
     memcpy((char* ) val_, (char* ) val, static_cast<unsigned long>(nbPixels));
     memcpy((char* ) sat_, (char* ) sat, static_cast<unsigned long>(nbPixels));
         setValidRect(0, 0, nbCols, nbRows);
     setHsvAsReference();
         setHasOtherRaster_(true);
     setReferenceHasChanged_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::RasterImage_HSV (const RasterImage * img)
Cloner constructor.
Parameters
img the image to clone
Definition at line 193 of file RasterImage_HSV.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), convertFromGray_(), convertFromRGB_(), convertFromRGBa_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::getWidth(), uriVL::kGrayRaster, uriVL::kNullRectangleError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::RasterImage::setHasOtherRaster_(), setHsvAsReference(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(img),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
     const ImageRect* inRect = img->getValidRect();
     FAIL_CONDITION( inRect == NULL,
                     kNullRectangleError,
                     "Attempt to clone a RasterImage with null valid data rect in RasterImage_HSV constructor");
     allocateRaster2D_(inRect->getHeight(), inRect->getWidth());
     allocateShiftedRaster2D_(inRect->getHeight(), inRect->getWidth(),
                                                          inRect->getTop(), inRect->getLeft());
     switch( img->getBaseRasterType() )
     {
         case kGrayRaster:
             convertFromGray_((RasterImage_gray* ) img, inRect);
             break;
         case kRGB24Raster:
             convertFromRGB_((RasterImage_RGB* ) img, inRect);
             break;
         case kRGBa32Raster:
             convertFromRGBa_((RasterImage_RGBa* ) img, inRect);
             break;
         default:
             break;
     }
     setHsvAsReference();
         setHasOtherRaster_(true);
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::RasterImage_HSV (const RasterImage * img, const ImageRect * theRect)
Initializes an HSV raster image at the specified dimensions and values.
Allocates an 8-bit gray-level GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 247 of file RasterImage_HSV.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), convertFromGray_(), convertFromRGB_(), convertFromRGBa_(), uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kGrayRaster, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::RasterImage::setHasOtherRaster_(), setHsvAsReference(), and uriVL::RasterImage::setReferenceHasChanged_().
                         :       RasterImage_RGBa(img, theRect),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(),
                                                          theRect->getTop(), theRect->getLeft());
     switch( img->getBaseRasterType() )
     {
         case kGrayRaster:
             convertFromGray_((RasterImage_gray* ) img, theRect);
             break;
         case kRGB24Raster:
             convertFromRGB_((RasterImage_RGB* ) img, theRect);
             break;
         case kRGBa32Raster:
             convertFromRGBa_((RasterImage_RGBa* ) img, theRect);
             break;
         default:
             break;
     }
     setHsvAsReference();
         setHasOtherRaster_(true);
     setReferenceHasChanged_(false);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::RasterImage_HSV (const RasterImage_HSV & obj)
Copy constructor.
Not implemented
Parameters
obj the object to copy
Definition at line 297 of file RasterImage_HSV.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       RasterImage_RGBa(),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_HSV copy constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_HSV constructor");
         throw e;
 }
RasterImage_HSV::~RasterImage_HSV (void) virtual
Destructor.
Definition at line 322 of file RasterImage_HSV.cpp.
References deleteHSV_(), deleteRaster2D_(), deleteShiftedRaster2D_(), and uriVL::DrawableObject2D::getTop().
 {
     deleteHSV_( );
     deleteRaster2D_();
     deleteShiftedRaster2D_(getTop());
 }
RasterImage_HSV::RasterImage_HSV (void) private
Creates an undimensioned RGBa float color raster image.
Definition at line 75 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::setHasOtherRaster_(), and uriVL::RasterImage::setReferenceHasChanged_().
Referenced by localRasterHSV().
                         :       RasterImage_RGBa( ),
                                 //
                                 hue_(NULL),
                                 sat_(NULL),
                                 val_(NULL),
                                 hue2D_(NULL),
                                 sat2D_(NULL),
                                 val2D_(NULL),
                                 shiftedHue2D_(NULL),
                                 shiftedSat2D_(NULL),
                                 shiftedVal2D_(NULL),
                                 //
                                 hsvIsReference_(false)
 {
         setHasOtherRaster_(true);
 //    setHsvAsReference();
     setReferenceHasChanged_(false);
 }
Member Function Documentation
void RasterImage_HSV::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Implements uriVL::RasterImage.
Definition at line 1279 of file RasterImage_HSV.cpp.
References FAIL_CONDITION, hue2D_, hue_, uriVL::kRasterAllocationFailure, sat2D_, sat_, val2D_, and val_.
Referenced by RasterImage_HSV().
 {
     const long  nbPixels = nbRows*nbCols;
     if (hue_ == NULL)
     {
         hue_ = new int[nbPixels];
         FAIL_CONDITION( hue_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate hue_ in RasterImage allocateRaster2D_");
         hue2D_ = new int*[nbRows];
         FAIL_CONDITION( hue2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate hue2D_ in RasterImage allocateRaster2D_");
         hue2D_[0] = hue_;
         for (int i=1; i<nbRows; i++)
             hue2D_[i] = hue2D_[i-1] + nbCols;
     }
     if (sat_ == NULL)
     {
         sat_ = new unsigned char[nbPixels];
         FAIL_CONDITION( sat_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate sat_ in RasterImage allocateRaster2D_");
         sat2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( sat2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate sat2D_ in RasterImage allocateRaster2D_");
         sat2D_[0] = sat_;
         for (int i=1; i<nbRows; i++)
             sat2D_[i] = sat2D_[i-1] + nbCols;
     }
     if (val_ == NULL)
     {
         val_ = new unsigned char[nbPixels];
         FAIL_CONDITION( val_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate value in RasterImage allocateRaster2D_");
         val2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( val2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate val2D_ in RasterImage allocateRaster2D_");
         val2D_[0] = val_;
         for (int i=1; i<nbRows; i++)
             val2D_[i] = val2D_[i-1] + nbCols;
     }
 }
void RasterImage_HSV::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implements uriVL::RasterImage.
Definition at line 1368 of file RasterImage_HSV.cpp.
References deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), hue_, uriVL::kRasterAllocationFailure, sat_, shiftedHue2D_, shiftedSat2D_, shiftedVal2D_, and val_.
Referenced by RasterImage_HSV().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()!=0) || (getLeft()!=0))
     {
         const int iHigh = iLow + nbRows - 1;
         deleteShiftedRaster2D_(iLow);
         shiftedHue2D_ = new int*[nbRows];
         FAIL_CONDITION( shiftedHue2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedHue2D_ in RasterImage_HSV::allocateRaster2D_");
         shiftedHue2D_ -= iLow;
         shiftedHue2D_[iLow] = hue_ - jLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedHue2D_[i+1] = shiftedHue2D_[i] + nbCols;
         shiftedSat2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedSat2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedHue2D_ in RasterImage_HSV::allocateRaster2D_");
         shiftedSat2D_ -= iLow;
         shiftedSat2D_[iLow] = sat_ - jLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedSat2D_[i+1] = shiftedSat2D_[i] + nbCols;
         shiftedVal2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedVal2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedVal2D_ in RasterImage_HSV::allocateRaster2D_");
         shiftedVal2D_ -= iLow;
         shiftedVal2D_[iLow] = val_ - jLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedVal2D_[i+1] = shiftedVal2D_[i] + nbCols;
     }
     else
     {
         shiftedHue2D_ = NULL;
         shiftedSat2D_ = NULL;
         shiftedVal2D_ = NULL;
     }
 }
void uriVL::RasterImage_HSV::convertFromARGB16_ (const RasterImage_aRGB16 * imgIn) private
Calculates HSV values for the input aRGB16 image received as parameter.
Parameters
img RGBa image to base the HSV values on
void uriVL::RasterImage_HSV::convertFromARGB16_ (const RasterImage_aRGB16 * imgIn, const ImageRect * theRect) private
Calculates HSV values for the input aRGB16 image received as parameter.
Parameters
img RGBa image to base the HSV values on
theRect image rectangle on which to do the conversion
void RasterImage_HSV::convertFromGray_ (const RasterImage_gray * imgIn) private
Calculates HSV values for the input gray-level image received as parameter.
This function is rather trivial. It arbitrarily set the hue to 0. The saturation is unambiguously set to 0 and the val to the gray level.
Parameters
img gray-level image to base the HSV values on
Definition at line 709 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by RasterImage_HSV().
 {
     convertFromGray_(imgIn, imgIn->getValidRect());
 }
void RasterImage_HSV::convertFromGray_ (const RasterImage_gray * imgIn, const ImageRect * theRect) private
Calculates HSV values for the input gray-level image received as parameter.
This function is rather trivial. It arbitrarily set the hue to 0. The saturation is unambiguously set to 0 and the val to the gray level.
Parameters
img gray-level image to base the HSV values on
theRect image rectangle on which to do the conversion
Definition at line 714 of file RasterImage_HSV.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), getShiftedHue2D(), getShiftedSat2D(), getShiftedVal2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
 {
     const unsigned char *const* gray = imgIn->getShiftedGray2D();
     unsigned char* const* sat = getShiftedSat2D(R_W_ACCESS),
                   *const* val = getShiftedVal2D(R_W_ACCESS);
     int           *const* hue = getShiftedHue2D(R_W_ACCESS);
     const int     iLow = theRect->getTop( ),
                   iHigh = theRect->getBottom( ),
                   jLow = theRect->getLeft( ),
                   jHigh = theRect->getRight( );
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             sat[i][j] = 0;
             val[i][j] = gray[i][j];
             hue[i][j] = 0;
         }
     }
 }
void RasterImage_HSV::convertFromRGB_ (const RasterImage_RGB * imgIn) private
Calculates HSV values for the input RGB image received as parameter.
Parameters
img RGB image to base the HSV values on
Definition at line 816 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by RasterImage_HSV().
 {
     convertFromRGB_(imgIn, imgIn->getValidRect());
 }
void RasterImage_HSV::convertFromRGB_ (const RasterImage_RGB * imgIn, const ImageRect * theRect) private
Calculates HSV values for the input RGB image received as parameter.
Parameters
img RGB image to base the HSV values on
theRect image rectangle on which to do the conversion
Definition at line 821 of file RasterImage_HSV.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedHue2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), getShiftedSat2D(), getShiftedVal2D(), uriVL::ImageRect::getTop(), MAX, MIN, and uriVL::R_W_ACCESS.
 {
     const unsigned char* const* rgb = imgIn->getShiftedRGB2D();
     unsigned char* const* sat = getShiftedSat2D(R_W_ACCESS),
                   *const* val = getShiftedVal2D(R_W_ACCESS);
     int           *const* hue = getShiftedHue2D(R_W_ACCESS);
     const int   iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
         #if URIVL_LUT_RGB_TO_HSV
                 for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow, rgbIndex=3*jLow; j<=jHigh; j++, rgbIndex+=3)
{
                                 int lutIndex =  (rgb[i][rgbIndex] << 16) |
                                                                 (rgb[i][rgbIndex+1] << 8) |
                                                                 (rgb[i][rgbIndex+2]);
                                 hue[i][j] = hueFromRGB_[lutIndex];
                                 sat[i][j] = satFromRGB_[lutIndex];
                                 val[i][j] = valFromRGB_[lutIndex];
                         }
                 }
         #else
                 unsigned char   maxVal, minVal, valRange,
                                                 pRed, pGreen, pBlue;
                 for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow, rgbIndex=3*jLow; j<=jHigh; j++)
{
                                 pRed = rgb[i][rgbIndex++];
                                 pGreen = rgb[i][rgbIndex++];
                                 pBlue = rgb[i][rgbIndex++];
                                 maxVal = MAX(MAX(pRed, pGreen), pBlue);
                                 minVal = MIN(MIN(pRed, pGreen), pBlue);
                                 valRange = static_cast<unsigned char>(maxVal - minVal);
                                 /*      HueSaturationV  */
                                 val[i][j] = maxVal;
                                 if (valRange != 0)
{
                                         sat[i][j] = static_cast<unsigned char>((valRange*100)/maxVal);
                                         if ( pRed == maxVal )
                                                 hue[i][j] = (pGreen-pBlue)*60/valRange;
                                         else if ( pGreen == maxVal )
                                                 hue[i][j] = 120 + (pBlue-pRed)*60/valRange;
                                         else
                                                 hue[i][j] = 240 + (pRed-pGreen)*60/valRange;
                                         //      we want the hue_ in the range [0, 360).
                                         if ( hue[i][j] < 0)
                                                 hue[i][j] += 360;
                                 }
                                 else
{
                                         sat[i][j] = 0;
                                         hue[i][j] = 0;
                                 }
                         }
                 }
         #endif
 }
void RasterImage_HSV::convertFromRGBa_ (const RasterImage_RGBa * imgIn) private
Calculates HSV values for the input RGBa image received as parameter.
Parameters
img RGBa image to base the HSV values on
Definition at line 738 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by RasterImage_HSV(), and updateRaster_().
 {
     convertFromRGBa_(imgIn, imgIn->getValidRect());
 }
void RasterImage_HSV::convertFromRGBa_ (const RasterImage_RGBa * imgIn, const ImageRect * theRect) private
Calculates HSV values for the input RGBa image received as parameter.
Parameters
img RGBa image to base the HSV values on
theRect image rectangle on which to do the conversion
Definition at line 743 of file RasterImage_HSV.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedHue2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), getShiftedSat2D(), getShiftedVal2D(), uriVL::ImageRect::getTop(), MAX, MIN, and uriVL::R_W_ACCESS.
 {
     const unsigned char* const* rgba = imgIn->getShiftedRGBa2D();
     unsigned char* const* sat = getShiftedSat2D(R_W_ACCESS),
                   *const* val = getShiftedVal2D(R_W_ACCESS);
     int           *const* hue = getShiftedHue2D(R_W_ACCESS);
     const int   iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
         #if URIVL_LUT_RGB_TO_HSV
                 for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow, rgbaIndex=4*jLow; j<=jHigh; j++, rgbaIndex+=4)
{
                                 int lutIndex =  (rgba[i][rgbaIndex] << 16) |
                                                                 (rgba[i][rgbaIndex+1] << 8) |
                                                                 (rgba[i][rgbaIndex+2]);
                                 hue[i][j] = hueFromRGB_[lutIndex];
                                 sat[i][j] = satFromRGB_[lutIndex];
                                 val[i][j] = valFromRGB_[lutIndex];
                         }
                 }
         #else
                 unsigned char   maxVal, minVal, valRange,
                                                 pRed, pGreen, pBlue;
                 for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow, rgbaIndex=4*jLow; j<=jHigh; j++, rgbaIndex++)
{
                                 pRed = rgba[i][rgbaIndex++];
                                 pGreen = rgba[i][rgbaIndex++];
                                 pBlue = rgba[i][rgbaIndex++];
                                 maxVal = MAX(MAX(pRed, pGreen), pBlue);
                                 minVal = MIN(MIN(pRed, pGreen), pBlue);
                                 valRange = static_cast<unsigned char>(maxVal - minVal);
                                 /*      HueSaturationV  */
                                 val[i][j] = maxVal;
                                 if (valRange != 0)
{
                                         sat[i][j] = static_cast<unsigned char>((valRange*100)/maxVal);
                                         if ( pRed == maxVal )
                                                 hue[i][j] = (pGreen-pBlue)*60/valRange;
                                         else if ( pGreen == maxVal )
                                                 hue[i][j] = 120 + (pBlue-pRed)*60/valRange;
                                         else
                                                 hue[i][j] = 240 + (pRed-pGreen)*60/valRange;
                                         //      we want the hue_ in the range [0, 360).
                                         if ( hue[i][j] < 0)
                                                 hue[i][j] += 360;
                                 }
                                 else
{
                                         sat[i][j] = 0;
                                         hue[i][j] = 0;
                                 }
                         }
                 }
         #endif
 }
void RasterImage_HSV::convertToRGBa_ (void) private
Updates the RGBa raster of this raster image to match the HSV rasters.
Definition at line 1022 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by convertToSaturatedRGBa_(), and updateRaster_().
 {
     convertToRGBa_(getValidRect());
 }
void RasterImage_HSV::convertToRGBa_ (const ImageRect * theRect) private
Updates the RGBa raster of this raster image to match the HSV rasters on the image rectangle specified.
Parameters
theRect the image rectangle on which to do the conversion
Definition at line 1027 of file RasterImage_HSV.cpp.
References FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedHue2D(), getShiftedRGBa2D(), getShiftedSat2D(), getShiftedVal2D(), uriVL::ImageRect::getTop(), uriVL::kImageProcessingError, and uriVL::R_W_ACCESS.
 {
     const unsigned char* const* sat = getShiftedSat2D();
     const unsigned char* const* val = getShiftedVal2D();
     const int* const* hue = getShiftedHue2D();
     unsigned char       maxVal, minVal, rangeVal,
                     *const* rgba = getShiftedRGBa2D(R_W_ACCESS);
     const int   iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow, rgbaIndex=4*jLow; j<=jHigh; j++)
         {
             //  get minimum and maximum values converted to range 0-255
             maxVal = val[i][j];
             minVal = static_cast<unsigned char>(maxVal - ((maxVal * sat[i][j]) / 100));
             rangeVal = static_cast<unsigned char>(maxVal - minVal);
             //  determine which region for the HSV cone we are in
             int hueRegion = hue[i][j]/60;
             switch (hueRegion)
             {
                     //  hue in [0, 60] -- red-green, dominant red
                 case 0:
                     rgba[i][rgbaIndex++] = maxVal;                              //  red is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  green is
                                             (hue[i][j] *rangeVal)/ 60);         //      calculated
                     rgba[i][rgbaIndex++] = minVal;                              //  blue is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                     //  hue in [60, 120] -- red-green, dominant green
                 case 1:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  red is
                                             ((120-hue[i][j]) *rangeVal)/ 60);   //      calculated
                     rgba[i][rgbaIndex++] = maxVal;                              //  green is max
                     rgba[i][rgbaIndex++] = minVal;                              //  blue is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                     //  hue in [120, 180] -- green-blue, dominant green
                 case 2:
                     rgba[i][rgbaIndex++] = minVal;                              //  red is min
                     rgba[i][rgbaIndex++] = maxVal;                              //  green is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  blue is
                                             ((hue[i][j]-120) *rangeVal)/ 60);   //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                     //  hue in [180, 240] -- green-blue, dominant blue
                 case 3:
                     rgba[i][rgbaIndex++] = minVal;                              //  red is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  green is
                                             ((240-hue[i][j]) *rangeVal)/ 60);   //      calculated
                     rgba[i][rgbaIndex++] = maxVal;                              //  blue is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                     //  hue in [240, 300] -- blue-red, dominant blue
                 case 4:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  red is
                                             ((hue[i][j]-240) *rangeVal)/ 60);   //  calculated
                     rgba[i][rgbaIndex++] = minVal;                              //  green is min
                     rgba[i][rgbaIndex++] = maxVal;                              //  blue is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                     //  hue in [300, 360] -- blue-red, dominant red
                 case 5:
                     rgba[i][rgbaIndex++] = maxVal;                              //  red is max
                     rgba[i][rgbaIndex++] = minVal;                              //  green is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(minVal +  //  blue is
                                             ((360-hue[i][j]) *rangeVal)/ 60);   //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255);                 //  alpha
                     break;
                 default:
                     FAIL_CONDITION( true,
                                     kImageProcessingError,
                                     "Invalid hue data in RasterImage_HSV::convertToRGBa_");
                     break;
             }
         }
     }
 }
void RasterImage_HSV::convertToSaturatedRGBa_ (void) private
Updates the RGBa raster of this raster image to match a saturated version the HSV rasters (where a value of 100 has been used for the saturation)
Definition at line 1118 of file RasterImage_HSV.cpp.
References convertToRGBa_(), and uriVL::DrawableObject2D::getValidRect().
Referenced by forceConversionToSaturatedRGBa().
 {
     convertToRGBa_(getValidRect());
 }
void RasterImage_HSV::convertToSaturatedRGBa_ (const ImageRect * theRect) private
Updates the RGBa raster of this raster image to match a saturated version the HSV rasters (where a value of 100 has been used for the saturation) on the image rectangle specified.
Parameters
theRect the image rectangle on which to do the conversion
Definition at line 1123 of file RasterImage_HSV.cpp.
References FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), getShiftedHue2D(), getShiftedRGBa2D(), uriVL::ImageRect::getTop(), uriVL::kImageProcessingError, and uriVL::R_W_ACCESS.
 {
     //  In this version we simply force the minVal to zero (saturation = 100)
     //  and rescale the max value to 255.
     //  and re-use otherwise the code of the function convertToRGBa_
     //  (we could optimize but this is a low-priority item at this point).
     unsigned char* const* rgba = getShiftedRGBa2D(R_W_ACCESS);
     const int* const* hue = getShiftedHue2D();
     const int   iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow, rgbaIndex=4*jLow; j<=jHigh; j++)
         {
         //  determine which region for the HSV cone we are in
 //      #if URIVL_LUT_RGB_TO_HSV
             int hueRegion = hue[i][j]/60;
 //      #else
 //      #endif
             switch (hueRegion)
             {
                     //  hue in [0, 60] -- red-green, dominant red
                 case 0:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  red is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  green is
                                            ((hue[i][j]*255)/ 60);           //      calculated
                     rgba[i][rgbaIndex++] = 0;                               //  blue is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                     //  hue in [60, 120] -- red-green, dominant green
                 case 1:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  red is
                                            (((120-hue[i][j])*255)/ 60);     //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  green is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(0);   //  blue is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                     //  hue in [120, 180] -- green-blue, dominant green
                 case 2:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(0);   //  red is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  green is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  blue is
                                            (((hue[i][j]-120)*255)/ 60);     //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                     //  hue in [180, 240] -- green-blue, dominant blue
                 case 3:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(0);   //  red is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  green is
                                            (((240-hue[i][j])*255)/ 60);     //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  blue is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                     //  hue in [240, 300] -- blue-red, dominant blue
                 case 4:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  red is
                                            (((hue[i][j]-240)*255)/ 60);     //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(0);   //  green is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  blue is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                     //  hue in [300, 360] -- blue-red, dominant red
                 case 5:
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  red is max
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(0);   //  green is min
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>       //  blue is
                                            (((360-hue[i][j])*255)/ 60);     //      calculated
                     rgba[i][rgbaIndex++] = static_cast<unsigned char>(255); //  alpha
                     break;
                 default:
                     FAIL_CONDITION( true,
                                     kImageProcessingError,
                                     "Invalid hue data in RasterImage_HSV::convertToRGBa_");
                     break;
             }
         }
     }
 }
void RasterImage_HSV::deleteHSV_ (void) private
Deletes the raster image's private hue, saturation and value rasters.
Definition at line 1330 of file RasterImage_HSV.cpp.
References hue_, sat_, and val_.
Referenced by ~RasterImage_HSV().
 {
     if (hue_ != NULL)
     {
         delete hue_;
         hue_ = NULL;
     }
     if (sat_ != NULL)
     {
         delete sat_;
         sat_ = NULL;
     }
     if (val_ != NULL)
     {
         delete val_;
         val_ = NULL;
     }
 }
void RasterImage_HSV::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Implements uriVL::RasterImage.
Definition at line 1349 of file RasterImage_HSV.cpp.
References hue2D_, sat2D_, and val2D_.
Referenced by ~RasterImage_HSV().
 {
     if (hue2D_ != NULL)
     {
         delete hue2D_;
         hue2D_ = NULL;
     }
     if (sat2D_ != NULL)
     {
         delete sat2D_;
         sat2D_ = NULL;
     }
     if (val2D_ != NULL)
     {
         delete val2D_;
         val2D_ = NULL;
     }
 }
void RasterImage_HSV::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Implements uriVL::RasterImage.
Definition at line 1415 of file RasterImage_HSV.cpp.
References shiftedHue2D_, shiftedSat2D_, and shiftedVal2D_.
Referenced by allocateShiftedRaster2D_(), and ~RasterImage_HSV().
 {
     if (shiftedHue2D_ != NULL)
     {
         shiftedHue2D_ += iLow;
         delete []shiftedHue2D_;
         shiftedHue2D_ = NULL;
     }
     if (shiftedSat2D_ != NULL)
     {
         shiftedSat2D_ += iLow;
         delete []shiftedSat2D_;
         shiftedSat2D_ = NULL;
     }
     if (shiftedVal2D_ != NULL)
     {
         shiftedVal2D_ += iLow;
         delete []shiftedVal2D_;
         shiftedVal2D_ = NULL;
     }
 }
void RasterImage_HSV::forceConversionToSaturatedRGBa (void)
Forces a conversion of the image's gworld rasters into a saturated image based on curent hue raster.
Definition at line 893 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::allocateGraphWorld_(), uriVL::RasterImage_RGBa::allocateRaster2D_(), uriVL::RasterImage_RGBa::allocateShiftedRaster2D_(), convertToSaturatedRGBa_(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::referenceHasChanged_, and uriVL::RasterImage::setGraphWorldAsReference_().
Referenced by myIdle().
 {
     //  if the GWorld has not been allocated then we must allocate
     //  it at the same dimensions (bounding rectangle) as the float raster
     if (graphWorldIsNull_())
     {
         allocateGraphWorld_(getHeight(), getWidth());
         RasterImage_RGBa::allocateRaster2D_(getHeight(), getWidth());
         RasterImage_RGBa::allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     }
     //  And then we convert from HSV to RGBa
     convertToSaturatedRGBa_(getValidRect());
     setGraphWorldAsReference_();
     referenceHasChanged_ = true;
 }
const int * RasterImage_HSV::getHue (void) const
Returns the hue as a read-only 1D raster.
Returns
hue as a 1D raster
Definition at line 338 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), hue_, uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return hue_;
 }
int * RasterImage_HSV::getHue (ReadWriteStatus rw)
Returns the hue as a read-write 1D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
hue as a 1D raster
Definition at line 346 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), hue_, uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return hue_;
 }
const int *const * RasterImage_HSV::getHue2D (void) const
Returns the hue as a read-only 2D raster.
Returns
hue as a 2D raster
Definition at line 401 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), hue2D_, uriVL::RasterImage::referenceHasChanged(), and updateRaster_().
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return hue2D_;
 }
int *const * RasterImage_HSV::getHue2D (ReadWriteStatus rw)
Returns the hue as a read-write 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
hue as a 2D raster
Definition at line 409 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), hue2D_, uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return hue2D_;
 }
const unsigned char * RasterImage_HSV::getRGBa (void) const virtual
Returns the 32-bit rgba base raster as a read-only 1D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 576 of file RasterImage_HSV.cpp.
References uriVL::GraphWorld::getRaster(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged()) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return gworld_->getRaster();
 }
unsigned char * RasterImage_HSV::getRGBa (ReadWriteStatus rw) virtual
Returns the 32-bit rgba base raster as a read-write 1D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 590 of file RasterImage_HSV.cpp.
References uriVL::GraphWorld::getRaster(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return gworld_->getRaster();
 }
const unsigned char *const * RasterImage_HSV::getRGBa2D (void) const virtual
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 610 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return RasterImage_RGBa::getRGBa2D();
 }
unsigned char *const * RasterImage_HSV::getRGBa2D (ReadWriteStatus rw) virtual
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 623 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworldIsReference_, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return RasterImage_RGBa::getRGBa2D(R_W_ACCESS);
 }
const unsigned char * RasterImage_HSV::getSat (void) const
Returns the saturation as a read-only 1D raster.
Returns
saturation as a 1D raster
Definition at line 359 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return sat_;
 }
unsigned char * RasterImage_HSV::getSat (ReadWriteStatus rw)
Returns the saturation as a read-write 1D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Returns
saturation as a 1D raster
Definition at line 367 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat_, setHsvAsReference(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return sat_;
 }
const unsigned char *const * RasterImage_HSV::getSat2D (void) const
Returns the saturation as a read-only 2D raster.
Returns
saturation as a 2D raster
Definition at line 422 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return sat2D_;
 }
unsigned char *const * RasterImage_HSV::getSat2D (ReadWriteStatus rw)
Returns the saturation as a read-write 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
saturation as a 2D raster
Definition at line 430 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat2D_, setHsvAsReference(), and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return sat2D_;
 }
const int *const * RasterImage_HSV::getShiftedHue2D (void) const
Returns the hue as a read-only shifted 2D raster.
Returns
hue as a shifted 2D raster
Definition at line 464 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), hue2D_, uriVL::RasterImage::referenceHasChanged(), shiftedHue2D_, and updateRaster_().
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), convertFromGray_(), convertFromRGB_(), convertFromRGBa_(), convertToRGBa_(), convertToSaturatedRGBa_(), and uriVL::ImageArithmetics::difference_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return hue2D_;
     else
         return shiftedHue2D_;
 }
int *const * RasterImage_HSV::getShiftedHue2D (ReadWriteStatus rw)
Returns the hue as a read-write shifted 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
hue as a shifted 2D raster
Definition at line 479 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), hue2D_, uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), shiftedHue2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return hue2D_;
     else
         return shiftedHue2D_;
 }
const unsigned char *const * RasterImage_HSV::getShiftedRGBa2D (void) const virtual
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
Overrides the method of the parent class RasterImage_RGBa.
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 642 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
Referenced by convertToRGBa_(), and convertToSaturatedRGBa_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     return RasterImage_RGBa::getShiftedRGBa2D();
 }
unsigned char *const * RasterImage_HSV::getShiftedRGBa2D (ReadWriteStatus rw) virtual
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
Overrides the method of the parent class RasterImage_RGBa.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 655 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::gworldIsReference_, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
 {
     if ( (graphWorldIsNull_()) ||
             (!graphWorldIsReference() && referenceHasChanged_) )
     {
         //  force an update
         referenceHasChanged_ = true;
         updateRaster_();
     }
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return RasterImage_RGBa::getShiftedRGBa2D(R_W_ACCESS);
 }
const unsigned char *const * RasterImage_HSV::getShiftedSat2D (void) const
Returns the saturation as a read-only shifted 2D raster.
Returns
saturation as a shifted 2D raster
Definition at line 499 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat2D_, shiftedSat2D_, and updateRaster_().
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), convertFromGray_(), convertFromRGB_(), convertFromRGBa_(), convertToRGBa_(), and uriVL::ImageArithmetics::difference_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return sat2D_;
     else
         return shiftedSat2D_;
 }
unsigned char *const * RasterImage_HSV::getShiftedSat2D (ReadWriteStatus rw)
Returns the saturation as a read-write shifted 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
saturation as a shifted 2D raster
Definition at line 514 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), sat2D_, setHsvAsReference(), shiftedSat2D_, and updateRaster_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return sat2D_;
     else
         return shiftedSat2D_;
 }
const unsigned char *const * RasterImage_HSV::getShiftedVal2D (void) const
Returns the value as a read-only shifted 2D raster.
Returns
the value a shifted 2D raster
Definition at line 534 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), shiftedVal2D_, updateRaster_(), and val2D_.
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), convertFromGray_(), convertFromRGB_(), convertFromRGBa_(), and convertToRGBa_().
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return val2D_;
     else
         return shiftedVal2D_;
 }
unsigned char *const * RasterImage_HSV::getShiftedVal2D (ReadWriteStatus rw)
Returns the value as a read-write shifted 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the value a shifted 2D raster
Definition at line 549 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), shiftedVal2D_, updateRaster_(), and val2D_.
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return val2D_;
     else
         return shiftedVal2D_;
 }
const unsigned char * RasterImage_HSV::getVal (void) const
Returns the value as a read-only 1D raster.
Returns
the value a 1D raster
Definition at line 380 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), updateRaster_(), and val_.
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return val_;
 }
unsigned char * RasterImage_HSV::getVal (ReadWriteStatus rw)
Returns the value as a read-write 1D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the value a 1D raster
Definition at line 388 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), updateRaster_(), and val_.
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return val_;
 }
const unsigned char *const * RasterImage_HSV::getVal2D (void) const
Returns the value as a read-only 2D raster.
Returns
the value a 2D raster
Definition at line 443 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), updateRaster_(), and val2D_.
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     return val2D_;
 }
unsigned char *const * RasterImage_HSV::getVal2D (ReadWriteStatus rw)
Returns the value as a read-write 2D raster.
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the value a 2D raster
Definition at line 451 of file RasterImage_HSV.cpp.
References uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), setHsvAsReference(), updateRaster_(), and val2D_.
 {
     if (graphWorldIsReference() && referenceHasChanged())
         updateRaster_( );
     //  A side-effect of calling the read-write version of a getH-S-V function is
     //  that the base (GraphWorld) raster is set not to be the reference and that the
     //  reference is marked as 'changed'
     setHsvAsReference();
     return val2D_;
 }
const RasterImage_HSV * RasterImage_HSV::localRasterHSV (const RasterImage * imgIn, bool * localHSV) static
Allocates a read-only HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
This function should be used as follows: = bool localHSV;
const RasterImage_HSV* imgHSV = RasterImage_HSV::localRasterHSV_(imgIn, &localHSV);
... lots of high-quality, efficient code ...
if (localHSV)
delete imgHSV;
Parameters
img the image of which to make a local gray copy
localGray will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to read-only HSV image
Definition at line 1221 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), and localRasterHSV().
 {
     return localRasterHSV(imgIn, imgIn->getValidRect(), localHSV);
 }
const RasterImage_HSV * RasterImage_HSV::localRasterHSV (const RasterImage * imgIn, const ImageRect * rect, bool * localHSV) static
Allocates a read-only HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
This function should be used as follows: = bool localHSV;
const RasterImage_HSV* imgHSV = RasterImage_HSV::localRasterHSV(imgIn, &localHSV);
... lots of high-quality, efficient code ...
if (localHSV)
delete imgHSV;
Parameters
img the image of which to make a local gray copy
rect the rectangle over which we want a gray-level image
localGray will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to read-only HSV image
Definition at line 1226 of file RasterImage_HSV.cpp.
References RasterImage_HSV().
 {
     const RasterImage_HSV* hsvImg = NULL;
     //  we want hue, sat, val to store HSV values corresponding to
     //  whatever is store in imgIn
     //
     //  case 1, imgIn is alread a ReasterImage_HSV --> then just use its rasters
     if (typeid(*imgIn) == typeid(uriVL::RasterImage_HSV))
     {
         hsvImg = static_cast<const RasterImage_HSV*>(imgIn);
         *localHSV = false;
     }
     //  if imgIn was not a RasterImage_HSV, we need to create a local HSV
     //  image that is converted from imgIn
     else
     {
         hsvImg = new RasterImage_HSV(imgIn);
         *localHSV = true;
     }
     return hsvImg;
 }
RasterImage_HSV * RasterImage_HSV::localRasterHSV (RasterImage * imgIn, bool * localHSV) static
Allocates a writable HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
This function should be used as follows: = bool localHSV;
RasterImage_HSV *imgHSV = RasterImage_HSV::localRasterHSV_(imgIn, &localHSV);
... lots of high-quality, efficient code ...
if (localHSV)
delete imgHSV;
Parameters
img the image of which to make a local gray copy
localGray will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to writable HSV image
Definition at line 1251 of file RasterImage_HSV.cpp.
References uriVL::DrawableObject2D::getValidRect(), and localRasterHSV().
 {
     return const_cast<RasterImage_HSV*>(localRasterHSV(static_cast<const RasterImage* >(imgIn),
                                                                                  imgIn->getValidRect(), localHSV));
 }
RasterImage_HSV * RasterImage_HSV::localRasterHSV (RasterImage * imgIn, const ImageRect * rect, bool * localHSV) static
Allocates a writable HSV copy of the image received as parameter if that image is not already some forn of HSV raster.
This function should be used as follows: = bool localHSV;
RasterImage_HSV *imgHSV = RasterImage_HSV::localRasterHSV(imgIn, &localHSV);
... lots of high-quality, efficient code ...
if (localHSV)
delete imgHSV;
Parameters
img the image of which to make a local gray copy
rect the rectangle over which we want a gray-level image
localGray will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to writable HSV image
Definition at line 1258 of file RasterImage_HSV.cpp.
References localRasterHSV().
 {
     return const_cast<RasterImage_HSV*>(localRasterHSV(static_cast<const RasterImage* >(imgIn),
                                                                                  rect, localHSV));
 }
const RasterImage_HSV & RasterImage_HSV::operator= (const RasterImage_HSV & obj)
Copy operator.
Not implemented
Parameters
obj the object to copy
Definition at line 684 of file RasterImage_HSV.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_HSV copy operator not implemented");
         return *this;
 }
void RasterImage_HSV::rgb2HSV (unsigned char r, unsigned char g, unsigned char b, int * hue, unsigned char * sat, unsigned char * val) static
Converts an rgb value to hue, saturation, and value.
Parameters
r red component of the color to convert
g green component of the color to convert
b blue component of the color to convert
hue corresponding hue in the range [0, 359]
sat corresponding saturation in the range [0, 100]
val corresponding value in the range [0, 255]
Definition at line 956 of file RasterImage_HSV.cpp.
References MAX, and MIN.
 {
     unsigned char       maxVal = MAX(MAX(r, g), b),
                     minVal = MIN(MIN(r, g), b);
     /*  HueSaturationV  */
     *val = maxVal;
     int valRange = maxVal - minVal;
     if (valRange !=0)
     {
         *sat = static_cast<unsigned char>((valRange*100)/maxVal);
         if ( r == maxVal )
             *hue = (g-b)*60/valRange;
         else if ( g == maxVal )
             *hue = 120 + (b-r)*60/valRange;
         else
             *hue = 240 + (r-g)*60/valRange;
         //      we want the hue in the range [0, 360).
         if ( *hue < 0)
             *hue += 360;
     }
     else
     {
         *sat = static_cast<unsigned char>(0);
         *hue = 0;
     }
 }
void RasterImage_HSV::rgb2HSV (const unsigned char rgb[], int * hue, unsigned char * sat, unsigned char * val) static
Converts an rgb value to hue, saturation, and value.
Parameters
rgb the color to convert
hue corresponding hue in the range [0, 359]
sat corresponding saturation in the range [0, 100]
val corresponding value in the range [0, 255]
Definition at line 989 of file RasterImage_HSV.cpp.
References MAX, and MIN.
 {
     unsigned char       maxVal = MAX(MAX(rgb[0], rgb[1]), rgb[2]),
                     minVal = MIN(MIN(rgb[0], rgb[1]), rgb[2]);
     /*  HueSaturationV  */
     *val = maxVal;
     int valRange = maxVal - minVal;
     if (valRange !=0)
     {
         *sat = static_cast<unsigned char>((valRange*100)/maxVal);
         if ( rgb[0] == maxVal )
             *hue = (rgb[1]-rgb[2])*60/valRange;
         else if ( rgb[1] == maxVal )
             *hue = 120 + (rgb[2]-rgb[0])*60/valRange;
         else
             *hue = 240 + (rgb[0]-rgb[1])*60/valRange;
         //      we want the hue in the range [0, 360).
         if ( *hue < 0)
             *hue += 360;
     }
     else
     {
         *sat = static_cast<unsigned char>(0);
         *hue = 0;
     }
 }
void RasterImage_HSV::setHsvAsReference (void) virtual
Sets this image's HSV rasters as the reference.
See also
setGraphWorldAsReference
Definition at line 694 of file RasterImage_HSV.cpp.
References hsvIsReference_, and uriVL::RasterImage::setOtherRasterAsReference_().
Referenced by getHue(), getHue2D(), getSat(), getSat2D(), getShiftedHue2D(), getShiftedSat2D(), getShiftedVal2D(), getVal(), getVal2D(), and RasterImage_HSV().
 {
     setOtherRasterAsReference_();
     hsvIsReference_ = true;
 }
void RasterImage_HSV::updateRaster_ (void) const private virtual
Forces an update of the base rgb raster if it is not the reference raster.
Reimplemented from uriVL::RasterImage_RGBa.
Definition at line 911 of file RasterImage_HSV.cpp.
References uriVL::RasterImage_RGBa::allocateGraphWorld_(), convertFromRGBa_(), convertToRGBa_(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::graphWorldIsReference(), uriVL::RasterImage::referenceHasChanged(), and uriVL::RasterImage::setReferenceHasChanged_().
Referenced by getHue(), getHue2D(), getRGBa(), getRGBa2D(), getSat(), getSat2D(), getShiftedHue2D(), getShiftedRGBa2D(), getShiftedSat2D(), getShiftedVal2D(), getVal(), getVal2D(), and uriVL::RasterImage_RGBa::updateRaster_().
 {
     //  only need to update rasters if the reference (whatever it is) has changed
     if (referenceHasChanged() || (graphWorldIsNull_()))
     {
         //  do this now to avoid infinite loops later
         setReferenceHasChanged_(false);
                 //      Not the prettiest solution, but allows to respect logical constness
                 RasterImage_HSV* updateableThis = const_cast<RasterImage_HSV*>(this);
         //      First find out which raster is the reference to update from
         //
         //  If the graphworld is the reference we need to to an RGBa --> HSV
         //  convertion over the valid data rect
         if (graphWorldIsReference())
         {
             updateableThis->convertFromRGBa_(this, getValidRect());
         }
         //
         //  If the HSV rasters form the reference...
         else
         {
             //  if the GWorld is not the reference and has not been allocated (typically
             //  the first time we render a RasterImage_HSV object) then we must allocate
             //  it at the same dimensions (bounding rectangle) as the float raster
             if (graphWorldIsNull_())
             {
                                 updateableThis->allocateGraphWorld_(getHeight(), getWidth());
                                 updateableThis->RasterImage_RGBa::allocateRaster2D_(getHeight(), getWidth());
                                 updateableThis->RasterImage_RGBa::allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
             }
             //  And then we convert from HSV to RGBa
             updateableThis->convertToRGBa_(getValidRect());
         }
     }
 }
Friends And Related Function Documentation
friend class RasterImage_RGBa friend
Definition at line 597 of file RasterImage_HSV.h.
Member Data Documentation
bool uriVL::RasterImage_HSV::hsvIsReference_ private
true when the HSV rasters define the reference for this image
Definition at line 462 of file RasterImage_HSV.h.
Referenced by setHsvAsReference().
int** uriVL::RasterImage_HSV::hue2D_ private
unshifted 2D raster storing the hue of this image (range [0, 359])
See also
getHue2D
Definition at line 433 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getHue2D(), and getShiftedHue2D().
int* uriVL::RasterImage_HSV::hue_ private
1D raster storing the hue of this image (range [0, 359])
See also
getHue
Definition at line 418 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getHue(), and RasterImage_HSV().
unsigned char** uriVL::RasterImage_HSV::sat2D_ private
unshifted 2D raster storing the saturation of this image (range [0, 100])
See also
getSat
Definition at line 438 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getSat2D(), and getShiftedSat2D().
unsigned char* uriVL::RasterImage_HSV::sat_ private
1D raster storing the saturation of this image (range [0, 100])
See also
getSat
Definition at line 423 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getSat(), and RasterImage_HSV().
int** uriVL::RasterImage_HSV::shiftedHue2D_ private
shifted 2D raster storing the hue of this image (range [0, 359])
See also
getHue2D
Definition at line 448 of file RasterImage_HSV.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), and getShiftedHue2D().
unsigned char** uriVL::RasterImage_HSV::shiftedSat2D_ private
shifted 2D raster storing the saturation of this image (range [0, 100])
See also
getSat
Definition at line 453 of file RasterImage_HSV.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), and getShiftedSat2D().
unsigned char** uriVL::RasterImage_HSV::shiftedVal2D_ private
shifted 2D raster storing the value of this image (range [0, 255])
See also
getVal
Definition at line 458 of file RasterImage_HSV.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), and getShiftedVal2D().
unsigned char** uriVL::RasterImage_HSV::val2D_ private
unshifted 2D raster storing the value of this image (range [0, 255])
See also
getVal
Definition at line 443 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getShiftedVal2D(), and getVal2D().
unsigned char* uriVL::RasterImage_HSV::val_ private
1D raster storing the value of this image (range [0, 255])
See also
getVal
Definition at line 428 of file RasterImage_HSV.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getVal(), and RasterImage_HSV().
The documentation for this class was generated from the following files:
RasterImage_HSV.h
RasterImage_HSV.cpp