URIVisionLibrary: uriVL::LinearSolver_Cholesky Class Reference
uriVL::LinearSolver_Cholesky Class Reference abstract
#include <LinearSolver_Cholesky.h>
Public Member Functions
LinearSolver_Cholesky (Matrix *a, bool preserveMatrix=false)
Constructor.
~LinearSolver_Cholesky (void)
Destructor.
virtual void setMatrix (Matrix *a, bool preserveMatrix=false)=0
Assigns a new matrix to this LinearSolver.
LinearSolverRecord * solve (Matrix *b)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
LinearSolverRecord * solve (Matrix *b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Public Member Functions inherited from uriVL::LinearSolver
virtual ~LinearSolver (void)
Destructor.
Static Public Member Functions
static LinearSolverRecord * solve (Matrix *A, Matrix *B, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecord * solve (Matrix *A, Matrix *B, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
Static Private Member Functions
static void solve_ (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix)
Solves an SLE for the matrix and right-side term received as parameters.
Additional Inherited Members
Protected Member Functions inherited from uriVL::LinearSolver
LinearSolver (void)
Default constructor.
LinearSolver (int nbRows, int nbCols)
Constructor: initializes the dimensions of the linear solver.
LinearSolver (Matrix *a, bool preserveMatrix=false)
Constructor: initializes the dimensions of the linear solver.
void setSingularityStatus_ (LinearSolverRecordStatus singularityStatus)
Sets the singularityStatus_.
LinearSolverRecordStatus getSingularityStatus_ (void)
Get the singularityStatus_.
int getNbRows_ (void)
Reports the number of rows of the solver's matrix.
int getNbCols_ (void)
Reports the number of rows of the solver's matrix.
void setMatrixDimensions_ (int nbRows, int nbCols)
Sets the dimensions of the solver's matrix.
int getNbStorageRows_ (void)
Reports the number of storage rows of the solver's matrix.
int getNbStorageCols_ (void)
Reports the number of storage rows of the solver's matrix.
void setMatrixStorageDimensions_ (int nbRows, int nbCols)
Sets the storage dimensions of the solver's matrix.
bool getMatrixIsLocal_ (void)
Reports whether the solver keeps a local copy of the SLE's matrix.
void setMatrixIsLocal_ (bool matrixIsLocal)
Sets whether the solver keeps a local copy of the SLE's matrix.
Detailed Description
Definition at line 29 of file LinearSolver_Cholesky.h.
Constructor & Destructor Documentation
LinearSolver_Cholesky::LinearSolver_Cholesky (Matrix * a, bool preserveMatrix = false)
Constructor.
A LinearSolver_Cholesky is created for a specific matrix. That matrix must be square, positive definite, symmetric, otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 20 of file LinearSolver_Cholesky.cpp.
         :   LinearSolver()
 {
 }
LinearSolver_Cholesky::~LinearSolver_Cholesky (void)
Destructor.
Definition at line 25 of file LinearSolver_Cholesky.cpp.
 {
 }
Member Function Documentation
void LinearSolver_Cholesky::setMatrix (Matrix * a, bool preserveMatrix = false) pure virtual
Assigns a new matrix to this LinearSolver.
This call only makes sense if the new matrix has the same dimensions as the previous one (it then saves a destruction and an allocation of a matrix). Otherwise, just use the static solve function.
Important: If you don't set preserveMatrix true, then the LinearSolver only stores a reference to matrix it receives as a parameter. It will do calculations in this matrix.
You cannot delete it before you call the solve function,
The matrix's elements will be modified (destructive behavior)
Parameters
a the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Implements uriVL::LinearSolver.
Definition at line 29 of file LinearSolver_Cholesky.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
LinearSolverRecord * LinearSolver_Cholesky::solve (Matrix * b) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 40 of file LinearSolver_Cholesky.cpp.
Referenced by solve().
 {
     return solve(B, 0);
 }
LinearSolverRecord * LinearSolver_Cholesky::solve (Matrix * b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 45 of file LinearSolver_Cholesky.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_Cholesky");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
 //    FAIL_CONDITION( nbRows != LU_->getNbRows(),
 //                    kInvalidParameterError,
 //                    "Right-side term's dimensions don't match that of the matrix");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve(B, record, incrImprov);
     return record;
 }
void LinearSolver_Cholesky::solve (Matrix * b, LinearSolverRecord * record) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 67 of file LinearSolver_Cholesky.cpp.
References solve().
 {
     solve(B, record, 0);
 }
void LinearSolver_Cholesky::solve (Matrix * b, LinearSolverRecord * record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
record stores the solution to the SLe and indication about the matrix's regularity.
Definition at line 72 of file LinearSolver_Cholesky.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getSingularityStatus_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and uriVL::LinearSolverRecord::status.
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_Cholesky");
     FAIL_CONDITION( record == NULL,
                     kNullParameterError,
                     "Null LinearSolverRecord term sent to a LinearSolver_Cholesky");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
 //    FAIL_CONDITION( nbRows != LU_->getNbRows(),
 //                    kInvalidParameterError,
 //                    "Right-side term's dimensions don't match that of the matrix");
     Matrix* X = record->sol;
     //  if the solution was not allocated we do it now
     if (X == NULL)
     {
         if (nbCols == 1)
             record->sol = new ColumnVector(nbRows);
         else
             record->sol = new Matrix(nbRows, nbCols);
     }
     else
     {
         FAIL_CONDITION( nbRows != X->getNbRows(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the SLE");
         FAIL_CONDITION( nbCols != X->getNbCols(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the right-side term");
     }
     //  do something
     record->status = getSingularityStatus_();
 }
LinearSolverRecord * LinearSolver_Cholesky::solve (Matrix * A, Matrix * B, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 116 of file LinearSolver_Cholesky.cpp.
References solve().
 {
     return solve(A, B, 0, preserveMatrix);
 }
LinearSolverRecord * LinearSolver_Cholesky::solve (Matrix * A, Matrix * B, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 122 of file LinearSolver_Cholesky.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_Cholesky");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_Cholesky");
     const int aRows = A->getNbRows(),
               aCols = A->getNbCols();
     FAIL_CONDITION( aRows != aCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_Cholesky");
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_Cholesky");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve_(A, B, record, preserveMatrix, incrImprov);
     return record;
 }
void LinearSolver_Cholesky::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 154 of file LinearSolver_Cholesky.cpp.
References solve().
 {
     solve(A, B, record, 0, preserveMatrix);
 }
void LinearSolver_Cholesky::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 161 of file LinearSolver_Cholesky.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve_().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_Cholesky");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_Cholesky");
     const int aRows = A->getNbRows(); /*,
               aCols = A->getNbCols();*/
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_Cholesky");
     //  was the record properly created?
     if (record->sol != NULL)
     {
         FAIL_CONDITION( (nbRows != record->sol->getNbRows()) ||
                         (nbCols != record->sol->getNbCols()),
                         kInvalidParameterError,
                         "right-side term and solution's dimensions dont match for LinearSolver_Cholesky");
     }
     //  if the solution was not allocated we do it now
     else
     {
         if (nbCols == 1)
             record->sol = new ColumnVector(nbRows);
         else
             record->sol = new Matrix(nbRows, nbCols);
     }
     solve_(A, B, record, preserveMatrix, incrImprov);
 }
void LinearSolver_Cholesky::solve_ (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix) static private
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 199 of file LinearSolver_Cholesky.cpp.
Referenced by solve().
 {
 }
The documentation for this class was generated from the following files:
LinearSolver_Cholesky.h
LinearSolver_Cholesky.cpp