URIVisionLibrary: imageDifference_main.cpp File Reference
imageDifference_main.cpp File Reference
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include <string>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "ImageArithmetics.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void computeImageDifferences (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const string filePath0 = color_dir + "car1.tga"
const string filePath1 = color_dir + "car2.tga"
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
RasterImage ** gMyImage = NULL
RasterImage * gDiffImgHue = NULL
RasterImage * gDiffImgAvg = NULL
RasterImage * gDiffImgMax = NULL
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int QUIT_MENU = 0
const int SEPARATOR = -1
const int AVERAGE_DIFF_MENU = 10
const int MAX_DIFF_MENU = 11
const int HUE_DIFF_MENU = 12
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 87 of file imageDifference_main.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 88 of file imageDifference_main.cpp.
#define kDefaultWidth 256
Definition at line 89 of file imageDifference_main.cpp.
#define kMaxWindowHeight 640
Definition at line 91 of file imageDifference_main.cpp.
#define kMaxWindowWidth 900
Definition at line 90 of file imageDifference_main.cpp.
#define kNbBckgndCols 5
Definition at line 158 of file imageDifference_main.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 83 of file imageDifference_main.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 85 of file imageDifference_main.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 82 of file imageDifference_main.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 84 of file imageDifference_main.cpp.
Referenced by main(), and myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 203 of file imageDifference_main.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void computeImageDifferences (void)
Definition at line 250 of file imageDifference_main.cpp.
References uriVL::AVERAGE_DIFFERENCE, uriVL::HUE_DIFFERENCE, uriVL::MAX_DIFFERENCE, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     //  Difference between images was implemented in the BackgroundRemover class
     //  hierarchy, more specifically in the BackgroundRemover_static class.
     //  We view background removal as a "computer vision" operation, mostly because
     //  we are more interested in dynamic, adaptive background removal techniques,
     //  which is why basic image difference ended up in the uriComputerVision namespace.
     // difference of "current" and "background" images using HUE_DIFFERENCE
     gDiffImgHue = ImageArithmetics::difference(gMyImage[UPPER_LEFT],
                                                 gMyImage[UPPER_RIGHT],
                                                 HUE_DIFFERENCE);
     //  Difference of "current" and "background" images using AVERAGE_DIFFERENCE
     gDiffImgAvg = ImageArithmetics::difference(gMyImage[UPPER_LEFT], gMyImage[UPPER_RIGHT],
                                                AVERAGE_DIFFERENCE);
     //  Difference of "current" and "background" images using MAX_DIFFERENCE
     //  First, I can keep reusing the same background with new images.
     //  Here I show that we can also use a pre-allocated output image and
     //  pass it for the difference function to write into.
     gDiffImgMax = new RasterImage_gray( gMyImage[UPPER_LEFT]->getHeight(),
                                         gMyImage[UPPER_LEFT]->getWidth());
     ImageArithmetics::difference(gMyImage[UPPER_LEFT],  gMyImage[UPPER_RIGHT],
                                  (RasterImage_gray *) gDiffImgMax,
                                  MAX_DIFFERENCE);
 }
void initializeQTEnvironment (void)
Definition at line 179 of file imageDifference_main.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 218 of file imageDifference_main.cpp.
References cleanupAndQuit(), filePath0, filePath1, uriVL::ImageReader::getFrame(), kNbImages, LOWER_LEFT, LOWER_RIGHT, myReader, uriVL::ImageReader::setSource(), UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     gMyImage = new RasterImage*[kNbImages];
     //-------------------------------------------------------------
     //  We read Image 0 from a file
     //-------------------------------------------------------------
     ImageReader         *myReader = new ImageReader(const_cast<char*>(filePath0.c_str()));
     gMyImage[UPPER_LEFT] = myReader->getFrame(true);
     if (gMyImage[UPPER_LEFT] == NULL)
     {
         cout << "Error encountered while reading image file " << filePath0 << endl;
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  We read Image 1 from a file
     //-------------------------------------------------------------
     myReader->setSource(const_cast<char*>(filePath1.c_str()));
     gMyImage[UPPER_RIGHT] = myReader->getFrame(true);
     if (gMyImage[UPPER_RIGHT] == NULL)
     {
         cout << "Error encountered while reading image file " << filePath1 << endl;
         cleanupAndQuit(-1);
     }
         gMyImage[LOWER_LEFT] = gMyImage[LOWER_RIGHT] = NULL;
 }
int main (int argc, char ** argv)
Definition at line 606 of file imageDifference_main.cpp.
References cleanupAndQuit(), computeImageDifferences(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), myReshape(), setupCamera(), and UPPER_LEFT.
 {
    try
    {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
         initializeQTEnvironment();
         //      I load my images and compute differences
         loadImage();
         computeImageDifferences();
         int     imgHeight = gMyImage[UPPER_LEFT]->getHeight(),
             imgWidth = gMyImage[UPPER_LEFT]->getWidth();
         //      I inform all drawable objects of the dimensions of their subwindow
         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
         //      I initialize my window's dimensions
         gWinHeight = kNbRowsSubwindows * (imgHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows * (imgWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Background Remover Demo");
         GLfloat *backColor;
         void    (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                                         myDisplay2, myDisplay3};
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
         int winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(imgWidth + kBorder) + kBorder,
                                                         i*(imgHeight + kBorder) + kBorder,
                                                         imgWidth, imgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                         glutKeyboardFunc(myKeyboard);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(imgWidth, imgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         glutSetWindow(gMainWindow);
         glClearColor(0.f, 1.f, 1.f, 1.f);
         glutPostRedisplay();
         glutMainLoop();
         cleanupAndQuit(0);
     }
     catch (uriVL::ErrorReport & e)
         {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
         return 0;
 }
void myColorSubmenu (int value)
Definition at line 519 of file imageDifference_main.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 304 of file imageDifference_main.cpp.
References gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_LEFT] != NULL)
                 gMyImage[UPPER_LEFT]->render();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 320 of file imageDifference_main.cpp.
References gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_RIGHT] != NULL)
         gMyImage[UPPER_RIGHT]->render();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay2 (void)
Definition at line 336 of file imageDifference_main.cpp.
References gMainWindow, gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[LOWER_LEFT] != NULL)
                 gMyImage[LOWER_LEFT]->render();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 353 of file imageDifference_main.cpp.
References gMainWindow, gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[LOWER_RIGHT] != NULL)
                 gMyImage[LOWER_RIGHT]->render();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 289 of file imageDifference_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 595 of file imageDifference_main.cpp.
References gInitDone, and gMainWindow.
Referenced by main().
 {
         if (gInitDone)
         {
                 glutSetWindow(gMainWindow);
             glutPostRedisplay();
         }
 }
void myInit (void)
Definition at line 536 of file imageDifference_main.cpp.
References AVERAGE_DIFF_MENU, gInitDone, gMainWindow, gSubwindow, HUE_DIFF_MENU, kBckgndColStr, kNbBckgndCols, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, MAX_DIFF_MENU, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), QUIT_MENU, SEPARATOR, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[0] = glutCreateMenu(myMenu0);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("Reset Images", 1);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[1] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     menu[2] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Average difference", AVERAGE_DIFF_MENU);
     glutAddMenuEntry("Max difference", MAX_DIFF_MENU);
     glutAddMenuEntry("Hue difference", HUE_DIFF_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[3] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Average difference", AVERAGE_DIFF_MENU);
     glutAddMenuEntry("Max difference", MAX_DIFF_MENU);
     glutAddMenuEntry("Hue difference", HUE_DIFF_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 401 of file imageDifference_main.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 431 of file imageDifference_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 446 of file imageDifference_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 461 of file imageDifference_main.cpp.
References AVERAGE_DIFF_MENU, cleanupAndQuit(), gDiffImgAvg, gDiffImgHue, gDiffImgMax, HUE_DIFF_MENU, LOWER_LEFT, MAX_DIFF_MENU, and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case AVERAGE_DIFF_MENU:
             gMyImage[LOWER_LEFT] =gDiffImgAvg ;
             break;
         case MAX_DIFF_MENU:
             gMyImage[LOWER_LEFT] = gDiffImgMax;
             break;
         case HUE_DIFF_MENU:
             gMyImage[LOWER_LEFT] = gDiffImgHue;
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
     glutPostRedisplay();
 }
void myMenu3 (int value)
Definition at line 490 of file imageDifference_main.cpp.
References AVERAGE_DIFF_MENU, cleanupAndQuit(), gDiffImgAvg, gDiffImgHue, gDiffImgMax, HUE_DIFF_MENU, LOWER_RIGHT, MAX_DIFF_MENU, and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case AVERAGE_DIFF_MENU:
             gMyImage[LOWER_RIGHT] = gDiffImgAvg ;
             break;
         case MAX_DIFF_MENU:
             gMyImage[LOWER_RIGHT] = gDiffImgMax;
             break;
         case HUE_DIFF_MENU:
             gMyImage[LOWER_RIGHT] = gDiffImgHue;
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
     glutPostRedisplay();
 }
void myMenuMain (int value)
Definition at line 416 of file imageDifference_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 352 of file main_imageHistogram.cpp.
References applyWarp(), cleanupQT(), gCurrentImg, gDragWin, gGridCols, gGridPoint, gGridRows, gMouseDown, gMyImage, gScaleIndex, gSelectedPtCol, gSelectedPtRow, gStartDragX, gStartDragY, uriVL::ImageWarper::isValidDisplacement(), kMinSearchDim, kNbImages, MAX, MIN, myDisplayMain(), myIdle(), uriVL::ImageHistogram::setImage(), stepByStep, withinBounds(), X_PAD, and Y_PAD.
Referenced by glSetupAndRun(), main(), and myInit().
 {
     if (button == GLUT_LEFT_BUTTON)
     {
         if (buttonState == GLUT_DOWN)
         {
             //  If the mouse button was not already pressed down, we start recording
             if (!gMouseDown)
             {
                 gMouseDown = true;
                 gStartDragX = ix;
                 gStartDragY = iy;
             }
         }
         else    //      buttonState == GLUT_UP
         {
             //  check that the mouse had been dragged from within the same subwindow and
             //  defines a suffficiently large search region.
             if (gMouseDown && withinBounds(ix, iy))
             {
                 int theLeft = MIN(ix, gStartDragX),
                     theTop = MIN(iy, gStartDragY),
                     theWidth = MAX(ix, gStartDragX) - theLeft + 1,
                     theHeight = MAX(iy, gStartDragY) - theTop + 1;
                 if ((theWidth >= kMinSearchDim) && (theHeight >= kMinSearchDim))
                 {
                     ImageRect myRect(theLeft, theTop, theWidth, theHeight);
                     gGrayHist->setImage(gGrayImage, &myRect);
                 }
             }
             gMouseDown = false;
             gDragWin = -1;
             myDisplayMain();
         }
     }
 }
void myReshape (int w, int h)
Definition at line 370 of file imageDifference_main.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 389 of file imageDifference_main.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const int AVERAGE_DIFF_MENU = 10
Definition at line 154 of file imageDifference_main.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
const string color_dir = COLOR_DIR_PATH
Definition at line 73 of file imageDifference_main.cpp.
const string filePath0 = color_dir + "car1.tga"
Definition at line 76 of file imageDifference_main.cpp.
Referenced by loadImage().
const string filePath1 = color_dir + "car2.tga"
Definition at line 77 of file imageDifference_main.cpp.
Referenced by loadImage().
RasterImage* gDiffImgAvg = NULL
Definition at line 140 of file imageDifference_main.cpp.
Referenced by myMenu2(), and myMenu3().
RasterImage* gDiffImgHue = NULL
Definition at line 139 of file imageDifference_main.cpp.
Referenced by myMenu2(), and myMenu3().
RasterImage* gDiffImgMax = NULL
Definition at line 141 of file imageDifference_main.cpp.
Referenced by myMenu2(), and myMenu3().
int gImageHeight = kDefaultHeight
Definition at line 130 of file imageDifference_main.cpp.
int gImageWidth = kDefaultWidth
Definition at line 129 of file imageDifference_main.cpp.
bool gInitDone = false
Definition at line 135 of file imageDifference_main.cpp.
Referenced by myIdle(), and myInit().
int gMainWindow
Definition at line 132 of file imageDifference_main.cpp.
Referenced by main(), myColorSubmenu(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), and myInit().
RasterImage** gMyImage = NULL
Definition at line 137 of file imageDifference_main.cpp.
const string gray_dir = GRAY_DIR_PATH
Definition at line 74 of file imageDifference_main.cpp.
int gSubwindow[kNbSubwindows]
Definition at line 132 of file imageDifference_main.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
int gWinHeight
Definition at line 127 of file imageDifference_main.cpp.
Referenced by main().
int gWinWidth
Definition at line 127 of file imageDifference_main.cpp.
Referenced by main().
const int HUE_DIFF_MENU = 12
Definition at line 156 of file imageDifference_main.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 160 of file imageDifference_main.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
}
Definition at line 166 of file imageDifference_main.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 149 of file imageDifference_main.cpp.
Referenced by loadImage(), myDisplay2(), myInit(), and myMenu2().
const int LOWER_RIGHT = 3
Definition at line 150 of file imageDifference_main.cpp.
Referenced by loadImage(), myDisplay3(), myInit(), and myMenu3().
const int MAX_DIFF_MENU = 11
Definition at line 155 of file imageDifference_main.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
const int QUIT_MENU = 0
Definition at line 152 of file imageDifference_main.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int SEPARATOR = -1
Definition at line 153 of file imageDifference_main.cpp.
Referenced by myInit().
const int UPPER_LEFT = 0
Definition at line 147 of file imageDifference_main.cpp.
Referenced by computeImageDifferences(), loadImage(), main(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 148 of file imageDifference_main.cpp.
Referenced by computeImageDifferences(), loadImage(), myDisplay1(), and myInit().