URIVisionLibrary: main_movieFilling.cpp File Reference
main_movieFilling.cpp File Reference
#include <fstream>
#include <iostream>
#include <list>
#include <cstdlib>
#include <cmath>
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "BlobFinder.h"
#include "ColorThresholdLabeler.h"
#include "MoviePlayer.h"
#include "Demos/dataFolderPath.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define DISPLAY_FONT GLUT_BITMAP_HELVETICA_12
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void initThresholds (void)
void detectAllBlobs (void)
void myIdle (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void displayTextualInfo (void)
void myKeyboard (unsigned char c, int x, int y)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void initializeApplication (void)
int main (int argc, char **argv)
Variables
const string movie_dir = MOVIE_DIR_PATH
const int IMG_WIDTH = 640
const int IMG_HEIGHT = 480
const int MIN_BLOB_SIZE = 50
const int MAX_BLOB_SIZE = 300
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const float RENDER_SCALE = 1.0
int gWinWidth
int gWinHeight
int gImageWidth = static_cast<int>(RENDER_SCALE*IMG_WIDTH)
int gImageHeight = static_cast<int>(RENDER_SCALE*IMG_HEIGHT)
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
FillingMode gModeWin [kNbSubwindows]
long gFrameIndex = 0
ImageRect * gMyRect = NULL
MoviePlayer * gMyPlayer = NULL
RasterImage_RGBa * gInputImage = NULL
RasterImage * gThresholdedImage = NULL
LabelRaster * gLabel = NULL
BlobList * gBlobList = NULL
ColorThresholdLabeler * gThresholder = NULL
ColorSegParams * gColorParams = NULL
BlobFinder * gBlobFinder = new BlobFinder()
char * gTarget
long gBlobMinSize = 220
const int FONT_HEIGHT = 12
const int TEXT_PADDING = 2
const float kTextColor [3] = {1.f, 1.f, 1.f}
const float kTextBackgroundColor [3] = {0.0f, 0.2f, 0.0f}
Macro Definition Documentation
#define DISPLAY_FONT GLUT_BITMAP_HELVETICA_12
Definition at line 176 of file main_movieFilling.cpp.
Referenced by displayTextualInfo().
#define kBorder 8
Definition at line 97 of file main_movieFilling.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 98 of file main_movieFilling.cpp.
#define kDefaultWidth 256
Definition at line 99 of file main_movieFilling.cpp.
#define kMaxWindowHeight 640
Definition at line 101 of file main_movieFilling.cpp.
#define kMaxWindowWidth 900
Definition at line 100 of file main_movieFilling.cpp.
#define kNbColsSubwindows 2
Definition at line 93 of file main_movieFilling.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 95 of file main_movieFilling.cpp.
#define kNbRowsSubwindows 2
Definition at line 92 of file main_movieFilling.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 94 of file main_movieFilling.cpp.
Referenced by main().
#define READ_IN_RGB_IMAGE 0
Definition at line 64 of file main_movieFilling.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 63 of file main_movieFilling.cpp.
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 210 of file main_movieFilling.cpp.
Referenced by main(), and myKeyboard().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void detectAllBlobs (void)
Definition at line 275 of file main_movieFilling.cpp.
References uriVL::ColorThresholdLabeler::applyInto(), uriVL::ColorSegParams::colorReg, uriVL::BlobFinder::findAllBlobs(), uriVL::ColorSegParams::nbModes, and RENDER_SCALE.
Referenced by myIdle().
 {
     gThresholder->applyInto(gInputImage, gColorParams, gLabel);
     //  clear the lists of blobs for each target color
     for (int k=0; k<gColorParams->nbModes; k++)
     {
         if (!gBlobList[k].empty())
                 {
                         BlobList::iterator      iter;
                         for (iter=gBlobList[k].begin(); iter!=gBlobList[k].end(); iter++)
                                 //      delete the blob allocated
                                 delete (*iter);
                         gBlobList[k].clear();
                 }
     }
     gBlobList = gBlobFinder->findAllBlobs(gLabel, gColorParams->nbModes,
                                                   gTarget, gBlobMinSize, false);
     for (int k=0; k<gColorParams->nbModes ; k++)
         {
         if (!gBlobList[k].empty())
         {
             BlobList::iterator iter, endList = gBlobList[k].end();
             for (iter = gBlobList[k].begin(); iter != endList; iter++)
             {
                 (*iter)->setColor((gColorParams->colorReg[k]).fillColor);
                 (*iter)->setContourColor(1.f, 1.f, 1.f);
                                 (*iter)->setRenderingScale(RENDER_SCALE);
             }
         }
         }
 }
void displayTextualInfo (void)
Definition at line 455 of file main_movieFilling.cpp.
References DISPLAY_FONT, FONT_HEIGHT, gImageHeight, gImageWidth, kTextBackgroundColor, and TEXT_PADDING.
Referenced by myDisplay3().
 {
     //-----------------------------------------------
     //  0.  get current material properties
     //-----------------------------------------------
     float oldAmb[4], oldDif[4], oldSpec[4], oldShiny;
     glGetMaterialfv(GL_FRONT, GL_AMBIENT, oldAmb);
     glGetMaterialfv(GL_FRONT, GL_DIFFUSE, oldDif);
     glGetMaterialfv(GL_FRONT, GL_SPECULAR, oldSpec);
     glGetMaterialfv(GL_FRONT, GL_SHININESS, &oldShiny);
     glPushMatrix();
     //-----------------------------------------------
     //  1.  Build the string to display
     //-----------------------------------------------
         char infoStr[256];
         sprintf(infoStr, "Blob threshold: %d ", gBlobMinSize);
     int infoLn = strlen(infoStr);
     //-----------------------------------------------
     //  2.  Determine the string's length (in pixels)
     //-----------------------------------------------
     int textWidth = 0;
     for (int k=0; k<infoLn; k++)
         textWidth += glutBitmapWidth(DISPLAY_FONT, infoStr[k]);
     //  add a few pixels of padding
     textWidth += 2*TEXT_PADDING;
     //-----------------------------------------------
     //  3.  Clear background rectangle
     //-----------------------------------------------
 //    setMaterial(kTextBackgroundColor[0], kTextBackgroundColor[1], kTextBackgroundColor[2]);
         glColor3f(kTextBackgroundColor[0], kTextBackgroundColor[1], kTextBackgroundColor[2]);
     glBegin(GL_POLYGON);
         glVertex2i(0, gImageHeight);
         glVertex2i(gImageWidth, gImageHeight);
         glVertex2i(gImageWidth, gImageHeight - FONT_HEIGHT - 4);
         glVertex2i(0, gImageHeight - FONT_HEIGHT - 4);
     glEnd();
         glTranslatef(0.f, 0.f, 1.f);
     //-----------------------------------------------
     //  4.  Draw the string
     //-----------------------------------------------
 //    setMaterial(kTextColor[0], kTextColor[1], kTextColor[2]);
     glColor3f(kTextColor[0], kTextColor[1], kTextColor[2]);
     int xPos = TEXT_PADDING,
         yPos = gImageHeight - FONT_HEIGHT;
     for (int k=0, i=0; k<infoLn; k++)
     {
         glRasterPos2i(xPos, yPos);
         glutBitmapCharacter(DISPLAY_FONT, infoStr[k]);
         xPos += glutBitmapWidth(DISPLAY_FONT, infoStr[k]);
     }
     //-----------------------------------------------
     //  5.  Restore old material properties
     //-----------------------------------------------
         glMaterialfv(GL_FRONT, GL_AMBIENT, oldAmb);
         glMaterialfv(GL_FRONT, GL_DIFFUSE, oldDif);
         glMaterialfv(GL_FRONT, GL_SPECULAR, oldSpec);
         glMaterialf(GL_FRONT, GL_SHININESS, oldShiny);
     //-----------------------------------------------
     //  6.  Restore reference frame
     //-----------------------------------------------
     glPopMatrix();
 }
void initializeApplication (void)
Definition at line 588 of file main_movieFilling.cpp.
References uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), initThresholds(), RENDER_SCALE, uriVL::DrawableObject2D::setRenderingScale(), and uriVL::DrawableObject2D::setValidRect().
Referenced by main().
 {
         gMyPlayer = new MoviePlayer();
         gMyPlayer->setSource();
     const ImageRect *myRect = gMyPlayer->getRect();
     int nbRows = myRect->getHeight();
     int nbCols = myRect->getWidth();
         ImageRect imgRect(0, 0, nbCols-1, nbRows-1);
         #if READ_IN_RGBA_IMAGE
                 gInputImage = new RasterImage_RGBa(&imgRect);
         #elif READ_IN_RGB_IMAGE
                 gInputImage = new RasterImage_RGB(&imgRect);
         #endif
         gThresholdedImage = new RasterImage_RGBa(&imgRect);
         gInputImage->setRenderingScale(RENDER_SCALE);
         gThresholdedImage->setRenderingScale(RENDER_SCALE);
         gLabel = new LabelRaster(&imgRect);
         gInputImage->setValidRect(&imgRect);
         initThresholds();
 }
void initializeQTEnvironment (void)
Definition at line 186 of file main_movieFilling.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void initThresholds (void)
Definition at line 231 of file main_movieFilling.cpp.
References uriVL::ColorSegParams::colorMode, uriVL::ColorSegParams::colorReg, uriVL::ColorRegion::deltaHue, uriVL::ColorRegion::fillColor, uriVL::ColorSegParams::fillMode, uriVL::ColorSegParams::grayReg, uriVL::ColorRegion::hueRef, uriVL::kOrigGrayFill, uriVL::ColorRegion::label, uriVL::ColorRegion::labelStr, uriVL::ColorSegParams::nbModes, uriVL::ColorRegion::satMax, uriVL::ColorRegion::satMin, uriVL::ColorRegion::valMax, and uriVL::ColorRegion::valMin.
Referenced by initializeApplication().
 {
     gThresholder = new ColorThresholdLabeler();
     gColorParams = new ColorSegParams;
     gColorParams->fillMode = kOrigGrayFill;
     gColorParams->nbModes = 2;
     gColorParams->colorMode = true;
     gColorParams->grayReg = NULL;
     gColorParams->colorReg = new ColorRegion[gColorParams->nbModes];
         gColorParams->colorReg[0].labelStr =  "magentaish";
     gColorParams->colorReg[0].hueRef = 320;
     gColorParams->colorReg[0].deltaHue = 40;
     gColorParams->colorReg[0].satMin = 40;
     gColorParams->colorReg[0].satMax = 100;
     gColorParams->colorReg[0].valMin = 40;
     gColorParams->colorReg[0].valMax = 255;
     gColorParams->colorReg[0].fillColor[0] = static_cast<unsigned char>(255);
     gColorParams->colorReg[0].fillColor[1] = static_cast<unsigned char>(0);
     gColorParams->colorReg[0].fillColor[2] = static_cast<unsigned char>(255);
     gColorParams->colorReg[0].label = static_cast<char>(1);
     gColorParams->colorReg[1].labelStr = "cianish";
     gColorParams->colorReg[1].hueRef = 200;
     gColorParams->colorReg[1].deltaHue = 25;
     gColorParams->colorReg[1].satMin = 60;
     gColorParams->colorReg[1].satMax = 100;
     gColorParams->colorReg[1].valMin = 40;
     gColorParams->colorReg[1].valMax = 255;
     gColorParams->colorReg[1].fillColor[0] = static_cast<unsigned char>(0);
     gColorParams->colorReg[1].fillColor[1] = static_cast<unsigned char>(255);
     gColorParams->colorReg[1].fillColor[2] = static_cast<unsigned char>(255);
     gColorParams->colorReg[1].label = static_cast<char>(2);
         gTarget = new char[gColorParams->nbModes];
         for (int i=0; i<gColorParams->nbModes; i++)
                 gTarget[i] = gColorParams->colorReg[i].label;
     gBlobList = new BlobList[gColorParams->nbModes];
 }
int main (int argc, char ** argv)
Definition at line 616 of file main_movieFilling.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), gImageHeight, gImageWidth, gWinHeight, gWinWidth, initializeApplication(), initializeQTEnvironment(), kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myKeyboard(), myReshape(), and setupCamera().
 {
     int         winID;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                      myDisplay2, myDisplay3};
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         //      I initialize my window's dimensions at the default values
         gWinHeight = kNbRowsSubwindows*(gImageHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows*(gImageWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Blob Filling Demo");
                 glutIdleFunc(myIdle);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glutKeyboardFunc(myKeyboard);
         winID = 0;
         glutSetWindow(gMainWindow);
                 glClearColor(0.1, 0.1, 0.1, 1.);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(
                                         gMainWindow,
                                         j*(gImageWidth + kBorder) + kBorder,
                                         i*(gImageHeight + kBorder) + kBorder,
                                         gImageWidth,
                                         gImageHeight);
                                 glClearColor(0.0, 0.0, 0.0, 1.0);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(gImageWidth, gImageHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         //  Inform drawable objects of the dimensions of my rendering windows
         DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
                 initializeApplication();
                 gInitDone = true;
         glutMainLoop();
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myDisplay0 (void)
Definition at line 363 of file main_movieFilling.cpp.
References uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
         if (gInitDone)
         {
                 if (gInputImage!= NULL)
                 {
                         gInputImage->render();
                 }
         }
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 381 of file main_movieFilling.cpp.
References uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
         if (gInitDone)
         {
                 if (gThresholdedImage != NULL)
                 {
                         gThresholdedImage->render();
                 }
         }
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 400 of file main_movieFilling.cpp.
References LOWER_LEFT, uriVL::ColorSegParams::nbModes, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
         if (gInitDone)
         {
                 if (gInputImage!= NULL)
                         gInputImage->render();
                 for (int k=0; k<gColorParams->nbModes ; k++)
                 {
                         if (!gBlobList[k].empty())
{
                                 BlobList::iterator iter;
                                 for (iter = gBlobList[k].begin(); iter != gBlobList[k].end(); iter++)
                                         (*iter)->render(true);
                         }
                 }
         }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 428 of file main_movieFilling.cpp.
References displayTextualInfo(), LOWER_RIGHT, and uriVL::ColorSegParams::nbModes.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
         if (gInitDone)
         {
                 for (int k=0; k<gColorParams->nbModes ; k++)
                 {
                         if (!gBlobList[k].empty())
{
                                 BlobList::iterator iter;
                                 for (iter = gBlobList[k].begin(); iter != gBlobList[k].end(); iter++)
                                         (*iter)->render(true);
                         }
                 }
         }
         displayTextualInfo();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 346 of file main_movieFilling.cpp.
References myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
     glutSetWindow(gMainWindow);
 }
void myIdle (void)
Definition at line 326 of file main_movieFilling.cpp.
References uriVL::ColorThresholdLabeler::applyInto(), detectAllBlobs(), uriVL::ColorSegParams::fillMode, and uriVL::kOrigGrayFill.
Referenced by main().
 {
         if (gInitDone) {
                 if (!gMyPlayer->isFinished())
                 {
                         gMyPlayer->getFrame(gInputImage);
                 }
                 gFrameIndex++;
                 gColorParams->fillMode = kOrigGrayFill;
                 gThresholder->applyInto(gInputImage, (char *) gColorParams, gThresholdedImage);
                 detectAllBlobs();
         }
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 559 of file main_movieFilling.cpp.
References cleanupAndQuit(), MAX_BLOB_SIZE, and MIN_BLOB_SIZE.
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
                 case ',':
                         gBlobMinSize -= 5;
                         if (gBlobMinSize < MIN_BLOB_SIZE)
                                 gBlobMinSize = MIN_BLOB_SIZE;
                         break;
                 case '.':
                         gBlobMinSize += 5;
                         if (gBlobMinSize > MAX_BLOB_SIZE)
                                 gBlobMinSize = MAX_BLOB_SIZE;
                         break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 529 of file main_movieFilling.cpp.
Referenced by main().
 {
     if (gInputImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 548 of file main_movieFilling.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const int FONT_HEIGHT = 12
Definition at line 177 of file main_movieFilling.cpp.
Referenced by displayTextualInfo().
BlobFinder* gBlobFinder = new BlobFinder()
Definition at line 172 of file main_movieFilling.cpp.
BlobList* gBlobList = NULL
Definition at line 169 of file main_movieFilling.cpp.
long gBlobMinSize = 220
Definition at line 174 of file main_movieFilling.cpp.
ColorSegParams* gColorParams = NULL
Definition at line 171 of file main_movieFilling.cpp.
long gFrameIndex = 0
Definition at line 152 of file main_movieFilling.cpp.
int gImageHeight = static_cast<int>(RENDER_SCALE*IMG_HEIGHT)
Definition at line 142 of file main_movieFilling.cpp.
Referenced by displayTextualInfo(), and main().
int gImageWidth = static_cast<int>(RENDER_SCALE*IMG_WIDTH)
Definition at line 141 of file main_movieFilling.cpp.
Referenced by displayTextualInfo(), and main().
bool gInitDone = false
Definition at line 147 of file main_movieFilling.cpp.
RasterImage_RGBa* gInputImage = NULL
Definition at line 157 of file main_movieFilling.cpp.
LabelRaster* gLabel = NULL
Definition at line 168 of file main_movieFilling.cpp.
int gMainWindow
Definition at line 144 of file main_movieFilling.cpp.
FillingMode gModeWin[kNbSubwindows]
Initial value:
= {kIdentityFill, kBlackFill, kWhiteFill,
                                                                                kOrigGrayFill}
Definition at line 149 of file main_movieFilling.cpp.
MoviePlayer* gMyPlayer = NULL
Definition at line 154 of file main_movieFilling.cpp.
ImageRect* gMyRect = NULL
Definition at line 153 of file main_movieFilling.cpp.
int gSubwindow[kNbSubwindows]
Definition at line 144 of file main_movieFilling.cpp.
char* gTarget
Definition at line 173 of file main_movieFilling.cpp.
RasterImage* gThresholdedImage = NULL
Definition at line 167 of file main_movieFilling.cpp.
ColorThresholdLabeler* gThresholder = NULL
Definition at line 170 of file main_movieFilling.cpp.
int gWinHeight
Definition at line 139 of file main_movieFilling.cpp.
Referenced by main().
int gWinWidth
Definition at line 139 of file main_movieFilling.cpp.
Referenced by main().
const int IMG_HEIGHT = 480
Definition at line 87 of file main_movieFilling.cpp.
const int IMG_WIDTH = 640
Definition at line 86 of file main_movieFilling.cpp.
const float kTextBackgroundColor[3] = {0.0f, 0.2f, 0.0f}
Definition at line 180 of file main_movieFilling.cpp.
Referenced by displayTextualInfo().
const float kTextColor[3] = {1.f, 1.f, 1.f}
Definition at line 179 of file main_movieFilling.cpp.
const int LOWER_LEFT = 2
Definition at line 105 of file main_movieFilling.cpp.
Referenced by myDisplay2().
const int LOWER_RIGHT = 3
Definition at line 106 of file main_movieFilling.cpp.
Referenced by myDisplay3().
const int MAX_BLOB_SIZE = 300
Definition at line 90 of file main_movieFilling.cpp.
Referenced by myKeyboard().
const int MIN_BLOB_SIZE = 50
Definition at line 89 of file main_movieFilling.cpp.
Referenced by myKeyboard().
const string movie_dir = MOVIE_DIR_PATH
Definition at line 76 of file main_movieFilling.cpp.
const float RENDER_SCALE = 1.0
Definition at line 107 of file main_movieFilling.cpp.
Referenced by detectAllBlobs(), and initializeApplication().
const int TEXT_PADDING = 2
Definition at line 178 of file main_movieFilling.cpp.
Referenced by displayTextualInfo().
const int UPPER_LEFT = 0
Definition at line 103 of file main_movieFilling.cpp.
Referenced by myDisplay0().
const int UPPER_RIGHT = 1
Definition at line 104 of file main_movieFilling.cpp.
Referenced by myDisplay1().