URIVisionLibrary: main_stereo.cpp File Reference
main_stereo.cpp File Reference
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage_gray.h"
#include "DepthMap.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages 3
#define kBorder 8
#define kDefaultHeight 120
#define kDefaultWidth 120
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define PI 3.14159265
#define RAD_TO_DEG 57.29577951308232
#define DEG_TO_RAD 0.017453292519943
#define kNbBckgndCols 6
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImages (void)
void computeDepth (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplayDepth (void)
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
void myReshape (int w, int h)
void setupOrthoCam (int w, int h)
void setupProjCam (int w, int h)
void myMenu0 (int value)
void myMenu1 (int value)
void myDepthMenu (int value)
void myColorSubmenu (int value)
void myUpperRightSubmenu (int value)
void myRenderSubmenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myDepthMouse (int button, int state, int ix, int iy)
void myDepthMotion (int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
int myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string stereo_dir = STEREO_DIR_PATH
const string leftImagePath = stereo_dir + "pentagon_L.tga"
const string righttImagePath = stereo_dir + "pentagon_R.tga"
const string disparityImagePath = stereo_dir + "pentagon_d.tga"
const float FOV_Y = 40
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gDepthWinWidth
int gDepthWinHeight
ResolutionLevel gMeshResolution = kMediumResolution
const float gNearZ = 1
const float gFarZ = 120.0
const float MAX_DEPTH = 80.f
int gMainWindow
int gSubwindow [2]
int gDepthWindow
int gStartx
int gStarty
bool gInitDone = false
bool gDisplayDisparity = false
bool gFilledFaceNormals = true
bool gFilledVertexNormals = false
bool gMoving = false
float gCurrentQuat [4]
float gLastQuat [4]
GLfloat gTx = 0.f
GLfloat gTy = 0.f
GLfloat gTz = -70.0f
GLfloat gAngle = 20
GLfloat gAngle2 = 30
RasterImage * gMyLeftImage = NULL
RasterImage * gMyRightImage = NULL
RasterImage_gray * gMyDisparity = NULL
RasterImage_gray_F * gMyDepth = NULL
RasterImage * gUpperRightDisplay = NULL
DepthMap * gMyDenseMap = NULL
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int QUIT_MENU = 0
const int WIREFRAME_MENU = 100
const int FILLED_FACES_MENU = 101
const int FILLED_VERTEX_MENU = 102
const int COARSER_RESOLUTION_MENU = 104
const int FINER_RESOLUTION_MENU = 105
const int RED_COLOR_MENU = 106
const int GREEN_COLOR_MENU = 107
const int YELLOW_COLOR_MENU = 108
const int RIGHT_IMAGE_MENU = 200
const int DISPARITY_MAP_MENU = 201
const int DEPTH_MAP_MENU = 202
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define DEG_TO_RAD 0.017453292519943
Definition at line 73 of file main_stereo.cpp.
Referenced by computeDepth().
#define kBorder 8
Definition at line 61 of file main_stereo.cpp.
Referenced by main().
#define kDefaultHeight 120
Definition at line 62 of file main_stereo.cpp.
#define kDefaultWidth 120
Definition at line 63 of file main_stereo.cpp.
#define kMaxWindowHeight 640
Definition at line 65 of file main_stereo.cpp.
#define kMaxWindowWidth 900
Definition at line 64 of file main_stereo.cpp.
#define kNbBckgndCols 6
Definition at line 190 of file main_stereo.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 57 of file main_stereo.cpp.
#define kNbImages 3
Definition at line 59 of file main_stereo.cpp.
#define kNbRowsSubwindows 2
Definition at line 56 of file main_stereo.cpp.
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 58 of file main_stereo.cpp.
#define PI 3.14159265
Definition at line 69 of file main_stereo.cpp.
#define RAD_TO_DEG 57.29577951308232
Definition at line 72 of file main_stereo.cpp.
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 237 of file main_stereo.cpp.
Referenced by main(), myDepthMenu(), myKeyboard(), myMenu0(), and myMenu1().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void computeDepth (void)
Definition at line 286 of file main_stereo.cpp.
References DEG_TO_RAD, FOV_Y, uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::DrawableObject2D::getWidth(), gMeshResolution, uriVL::kRangeFloat, MAX_DEPTH, uriVL::R_W_ACCESS, uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::GraphicComponent3D::setMaterial(), uriVL::DepthMap::setResolution(), uriVL::DrawableObject2D::setValidRect(), and uriVL::DepthMap::setWireframe().
Referenced by myInit().
 {
     //------------------
     //  Step 1: create the IntrinsicParameters object
     //------------------
     //  I know next to nothing about the cameras that took these images, so
     //  I made up all the data.  I create an ideal pinhole camera
     int nbRows = gMyDisparity->getHeight(),
                    nbCols = gMyDisparity->getWidth();
     IntrinsicParameters_pinhole *camParams;
     //  Since this is a "pinhole" camera we are dealing with here, not a real one, I need
     //  to compute my focal length in "pixel" units
     float   focPix = 0.5f * gMyLeftImage->getHeight() / tan(DEG_TO_RAD*FOV_Y/2);
     camParams = new IntrinsicParameters_pinhole(nbCols, nbRows, focPix, focPix);
     //------------------
     //  Step 2: compute depth at each pixel
     //------------------
     //  I don't know the geometry of the stereo pair either, only that they are supposed
     //  to form a parallel pair.  So I make up a baseline.
     //float     baseline = 1.f;
     //  Here we break the process into a series of baby steps.  I create first a
     //  "depth" raster image that will store the depth computed from the disparity
     //  Note that my calculation of "depth" uses completely made up coefficients
     gMyDepth = new RasterImage_gray_F(nbRows, nbCols);
     ImageRect *validRect = new ImageRect(0, 0, nbCols, nbRows);
     float *const* depth = gMyDepth->getShiftedGrayF2D(R_W_ACCESS);
     const unsigned char *const* disp = gMyDisparity->getShiftedGray2D();
     for (int i=0; i<nbRows; i++)
         for (int j=0; j<nbCols; j++)
         {
             depth[i][j] = 75.f * (1.f + 1.f / (2.f + disp[i][j]));
             if (depth[i][j] > MAX_DEPTH)
                 depth[i][j] = MAX_DEPTH;
         }
     gMyDepth->setValidRect(validRect);
     gMyDepth->setFloatConversionMode(kRangeFloat);
     //------------------
     //  Step 3: create the dense DepthMap object
     //------------------
     gMyDenseMap = new DepthMap(gMyDepth, camParams, 1.f);
     gMyDenseMap->setFloatConversionMode(kRangeFloat);
     gMyDenseMap->setResolution(gMeshResolution);
     gMyDenseMap->setWireframe(true);
     gMyDenseMap->setMaterial(0.8f, 0.1f, 0.1f, .5f, .5f, .5f, 0.3f, .3f, .3f, .5f);
 }
void initializeQTEnvironment (void)
Definition at line 213 of file main_stereo.cpp.
Referenced by main(), and myInit().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImages (void)
Definition at line 256 of file main_stereo.cpp.
References disparityImagePath, uriVL::ImageReader::getFrame(), gMyRightImage, leftImagePath, myReader, righttImagePath, and uriVL::ImageReader::setSource().
Referenced by main().
 {
     ImageReader         myReader;
     //-------------------------------------------------------------
     //  We read the left image, right image, and disparity map
     //-------------------------------------------------------------
     myReader.setSource(const_cast<char*>(leftImagePath.c_str()));
     gMyLeftImage = myReader.getFrame(false);    //      left image
     myReader.setSource(const_cast<char*>(righttImagePath.c_str()));
     gMyRightImage = myReader.getFrame(false);   //      right image
     //  Normally, I should be able to read the disparity map directly into my
     //  DepthMap's raster.  Then I could render the map as a gray-level image
     //  in one subwindow and draw it as a mesh in an other.  However, at this
     //  point, the "readInto" component of the ImageReader class has not been
     //  implemented, so I had to separate the two operations.
     myReader.setSource(const_cast<char*>(disparityImagePath.c_str()));
     gMyDisparity = static_cast<RasterImage_gray*>(myReader.getFrame(false));    //      disparity map
     //  initially we display the right image in the upper-right subwindow
     gUpperRightDisplay = gMyRightImage;
 }
int main (int argc, char ** argv)
Definition at line 796 of file main_stereo.cpp.
References cleanupAndQuit(), gDepthWindow, gDepthWinHeight, gDepthWinWidth, uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, loadImages(), myDepthMotion(), myDepthMouse(), myDisplay0(), myDisplay1(), myDisplayDepth(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), myMouse(), myReshape(), setupOrthoCam(), setupProjCam(), UPPER_LEFT, and UPPER_RIGHT.
 {
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
         initializeQTEnvironment();
         //      I load my images
         loadImages();
         int     imgWidth = gMyLeftImage->getHeight(),
             imgHeight = gMyLeftImage->getWidth();
         //  and I inform drawable object of these dimensions (in case they want to get rendered
         //  "shifted")
         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
         //      I initialize my window's dimensions
         gWinHeight = 5 * imgHeight / 2 + 3 * kBorder;
         gWinWidth = 2 * imgWidth + 3 * kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Depth Map Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glutIdleFunc(myIdle);
         glutMouseFunc(myMouse);
         glClearColor(0.0, 0.0, 0.0, 1.0);
         glutSetWindow(gMainWindow);
         GLfloat *backColor;
         //--------------
         //      Upper-left subwindow will display the left image
         //--------------
         gSubwindow[UPPER_LEFT] = glutCreateSubWindow(gMainWindow, kBorder, kBorder,
                                             imgWidth, imgHeight);
         //      I don't need to do this.  I just set a different "clear" color for
         //      each subwindow.
         backColor = kBackgroundColor[0];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         //      This *has* to be defined:  a "display" callback function for each subwindow
         glutDisplayFunc(myDisplay0);
         glutKeyboardFunc(myKeyboard);
         setupOrthoCam(imgWidth, imgHeight);
         glutSetWindow(gMainWindow);
         //--------------
         //      Upper-right subwindow will display the right image or the disparity map
         //--------------
         gSubwindow[UPPER_RIGHT] = glutCreateSubWindow(gMainWindow, imgWidth + 2*kBorder, kBorder,
                                             imgWidth, imgHeight);
         //      I don't need to do this.  I just set a different "clear" color for
         //      each subwindow.
         backColor = kBackgroundColor[1];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         //      This *has* to be defined:  a "display" callback function for each subwindow
         glutDisplayFunc(myDisplay1);
         glutKeyboardFunc(myKeyboard);
         setupOrthoCam(imgWidth, imgHeight);
         glutSetWindow(gMainWindow);
         //--------------
         //      The depth subwindow will diplay the depth map, interactively.
         //--------------
         gDepthWinWidth = 2*imgWidth + kBorder;
         gDepthWinHeight = 3*imgHeight/2;
         gDepthWindow = glutCreateSubWindow(gMainWindow, kBorder, imgHeight + 2*kBorder,
                                            gDepthWinWidth, gDepthWinHeight);
         //      I don't need to do this.  I just set a different "clear" color for
         //      each subwindow.
         backColor = kBackgroundColor[2];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         //      This *has* to be defined:  a "display" callback function for each subwindow
         glutDisplayFunc(myDisplayDepth);
         //      handle mouse events and "active" mouse motion events in this subwindow.
         glutMouseFunc(myDepthMouse);
         glutMotionFunc(myDepthMotion);
         glutKeyboardFunc(myKeyboard);
         //
         setupProjCam(gDepthWinWidth, gDepthWinHeight);
         glutSetWindow(gMainWindow);
         myInit();
         glutMainLoop();
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myColorSubmenu (int value)
Definition at line 646 of file main_stereo.cpp.
References gMainWindow, kBackgroundColor, kNbBckgndCols, and myDisplay0().
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         myDisplay0();
         glutPostRedisplay();
     }
 }
void myDepthMenu (int value)
Definition at line 551 of file main_stereo.cpp.
References cleanupAndQuit(), COARSER_RESOLUTION_MENU, FINER_RESOLUTION_MENU, gMeshResolution, GREEN_COLOR_MENU, uriVL::kCoarseResolution, uriVL::kFineResolution, uriVL::kMediumResolution, uriVL::kVeryHighResolution, uriVL::kVeryLowResolution, QUIT_MENU, RED_COLOR_MENU, uriVL::GraphicComponent3D::setMaterial(), uriVL::DepthMap::setResolution(), and YELLOW_COLOR_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case FINER_RESOLUTION_MENU:
             switch (gMeshResolution)
             {
                 case kVeryHighResolution:
                 case kFineResolution:
                     gMeshResolution = kVeryHighResolution;
                     break;
                 case kMediumResolution:
                     gMeshResolution = kFineResolution;
                     break;
                 case kCoarseResolution:
                     gMeshResolution = kMediumResolution;
                     break;
                 case kVeryLowResolution:
                     gMeshResolution = kCoarseResolution;
                     break;
             }
             gMyDenseMap->setResolution(gMeshResolution);
             break;
         case COARSER_RESOLUTION_MENU:
             switch (gMeshResolution)
             {
                 case kVeryHighResolution:
                     gMeshResolution = kFineResolution;
                     break;
                 case kFineResolution:
                     gMeshResolution = kMediumResolution;
                     break;
                 case kMediumResolution:
                     gMeshResolution = kCoarseResolution;
                     break;
                 case kCoarseResolution:
                 case kVeryLowResolution:
                     gMeshResolution = kVeryLowResolution;
                     break;
             }
             gMyDenseMap->setResolution(gMeshResolution);
             break;
         case RED_COLOR_MENU:
             gMyDenseMap->setMaterial(0.8f, 0.1f, 0.1f, .5f, .2f, .2f, 0.3f, 0.f, 0.f, .5f);
             break;
         case GREEN_COLOR_MENU:
             gMyDenseMap->setMaterial(0.1f, 0.7f, 0.1f, .2f, .5f, .2f, 0.f, .3f, 0.f, .5f);
             break;
         case YELLOW_COLOR_MENU:
             gMyDenseMap->setMaterial(0.8f, 0.8f, 0.1f, .5f, .5f, .2f, .3f, .3f, 0.f, .5f);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myDepthMotion (int ix, int iy)
Definition at line 508 of file main_stereo.cpp.
References gAngle, gAngle2, gMoving, gStartx, and gStarty.
Referenced by main().
 {
     if (gMoving)
     {
         gAngle += (ix - gStartx);
         gAngle2 += (iy - gStarty);
         gStartx = ix;
         gStarty = iy;
         glutPostRedisplay();
     }
 }
void myDepthMouse (int button, int state, int ix, int iy)
Definition at line 495 of file main_stereo.cpp.
References gMoving, gStartx, and gStarty.
Referenced by main().
 {
     if (button == GLUT_LEFT_BUTTON && state == GLUT_DOWN)
     {
         gMoving = true;
         gStartx = ix;
         gStarty = iy;
     }
     if (button == GLUT_LEFT_BUTTON && state == GLUT_UP)
         gMoving = false;
 }
void myDisplay0 (void)
Definition at line 358 of file main_stereo.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), myColorSubmenu(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyLeftImage->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 376 of file main_stereo.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
         gUpperRightDisplay->render();
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayDepth (void)
Definition at line 392 of file main_stereo.cpp.
References uriVL::DepthMap::draw(), gAngle, gAngle2, gDepthWindow, gMainWindow, gTx, gTy, and gTz.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gDepthWindow);
     glClear(GL_COLOR_BUFFER_BIT);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     if (gMyDenseMap != NULL)
     {
         glPushMatrix();
         glTranslatef(gTx, gTy, gTz);
         glRotatef(gAngle2, 1.0, 0.0, 0.0);
         glRotatef(gAngle, 0.0, 1.0, 0.0);
                 glScalef(1.f, 1.f, 2.f);
         gMyDenseMap->draw();
         glPopMatrix();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 343 of file main_stereo.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), and myDisplayDepth().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     myDisplay0();
     myDisplay1();
     myDisplayDepth();
     glutSwapBuffers();
 }
void myIdle (void)
Definition at line 427 of file main_stereo.cpp.
Referenced by main().
 {
     glutPostRedisplay();
 }
int myInit (void)
Definition at line 736 of file main_stereo.cpp.
References COARSER_RESOLUTION_MENU, computeDepth(), DEPTH_MAP_MENU, DISPARITY_MAP_MENU, FILLED_FACES_MENU, FILLED_VERTEX_MENU, FINER_RESOLUTION_MENU, gDepthWindow, gInitDone, gMainWindow, GREEN_COLOR_MENU, gSubwindow, initializeQTEnvironment(), kBckgndColStr, kNbBckgndCols, myColorSubmenu(), myDepthMenu(), myMenu0(), myMenu1(), myRenderSubmenu(), myUpperRightSubmenu(), QUIT_MENU, RED_COLOR_MENU, RIGHT_IMAGE_MENU, UPPER_LEFT, UPPER_RIGHT, WIREFRAME_MENU, and YELLOW_COLOR_MENU.
Referenced by main().
 {
     initializeQTEnvironment();
     // Create Menus
     int menu[3], colorSubmenu, renderSubmenu,
     upperRightSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[0] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     upperRightSubmenu = glutCreateMenu(myUpperRightSubmenu);
     glutAddMenuEntry("Right Image", RIGHT_IMAGE_MENU);
     glutAddMenuEntry("Disparity Map", DISPARITY_MAP_MENU);
     glutAddMenuEntry("Depth Map", DEPTH_MAP_MENU);
     menu[1] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Display Selection", upperRightSubmenu);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gDepthWindow);
     renderSubmenu = glutCreateMenu(myRenderSubmenu);
     glutAddMenuEntry("Wireframe", WIREFRAME_MENU);
     glutAddMenuEntry("Filled, face normals", FILLED_FACES_MENU);
     glutAddMenuEntry("Filled, vertex normals", FILLED_VERTEX_MENU);
     menu[2] = glutCreateMenu(myDepthMenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddSubMenu("Rendering", renderSubmenu);
     glutAddMenuEntry("Coarser resolution", COARSER_RESOLUTION_MENU);
     glutAddMenuEntry("Finer resolution", FINER_RESOLUTION_MENU);
     glutAddMenuEntry("Color: red", RED_COLOR_MENU);
     glutAddMenuEntry("Color: green", GREEN_COLOR_MENU);
     glutAddMenuEntry("Color: yellow", YELLOW_COLOR_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     computeDepth();
     gInitDone = true;
     return false;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 432 of file main_stereo.cpp.
References cleanupAndQuit(), gMeshResolution, uriVL::kCoarseResolution, uriVL::kFineResolution, uriVL::kMediumResolution, uriVL::kVeryHighResolution, uriVL::kVeryLowResolution, and uriVL::DepthMap::setResolution().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
             //  , and . (below < and >) change the mesh's resolution
         case '.':
             switch (gMeshResolution)
             {
                 case kVeryHighResolution:
                 case kFineResolution:
                     gMeshResolution = kVeryHighResolution;
                     break;
                 case kMediumResolution:
                     gMeshResolution = kFineResolution;
                     break;
                 case kCoarseResolution:
                     gMeshResolution = kMediumResolution;
                     break;
                 case kVeryLowResolution:
                     gMeshResolution = kCoarseResolution;
                     break;
             }
             gMyDenseMap->setResolution(gMeshResolution);
             break;
         case ',':
             switch (gMeshResolution)
             {
                 case kVeryHighResolution:
                     gMeshResolution = kFineResolution;
                     break;
                 case kFineResolution:
                     gMeshResolution = kMediumResolution;
                     break;
                 case kMediumResolution:
                     gMeshResolution = kCoarseResolution;
                     break;
                 case kCoarseResolution:
                 case kVeryLowResolution:
                     gMeshResolution = kVeryLowResolution;
                     break;
             }
             gMyDenseMap->setResolution(gMeshResolution);
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myMenu0 (int value)
Definition at line 521 of file main_stereo.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 536 of file main_stereo.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 490 of file main_stereo.cpp.
Referenced by main().
 {}
void myRenderSubmenu (int value)
Definition at line 617 of file main_stereo.cpp.
References FILLED_FACES_MENU, FILLED_VERTEX_MENU, gFilledFaceNormals, uriVL::DepthMap::setWireframe(), and WIREFRAME_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case WIREFRAME_MENU:
             if (gMyDenseMap!=NULL)
                 gMyDenseMap->setWireframe(true);
             break;
         case FILLED_FACES_MENU:
         case FILLED_VERTEX_MENU:
                         gFilledFaceNormals = !gFilledFaceNormals;
             if (gMyDenseMap!=NULL)
                 gMyDenseMap->setWireframe(false);
 /*
                         gFilledVertexNormals = !gFilledVertexNormals;
                         if (gCurrentDepthMap!=NULL)
                                 gCurrentDepthMap->setVertexNormals(gFilledVertexNormals);
 */
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myReshape (int w, int h)
Definition at line 697 of file main_stereo.cpp.
Referenced by main().
 {}
void myUpperRightSubmenu (int value)
Definition at line 665 of file main_stereo.cpp.
References DEPTH_MAP_MENU, DISPARITY_MAP_MENU, gMyDenseMap, gMyDisparity, gMyRightImage, and RIGHT_IMAGE_MENU.
Referenced by myInit().
 {
     switch (urDisplayIndex)
     {
         case RIGHT_IMAGE_MENU:
             gUpperRightDisplay = gMyRightImage;
             break;
         case DISPARITY_MAP_MENU:
             gUpperRightDisplay = gMyDisparity;
             break;
         case DEPTH_MAP_MENU:
             gUpperRightDisplay = gMyDenseMap;
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
void setupOrthoCam (int w, int h)
Definition at line 706 of file main_stereo.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupProjCam (int w, int h)
Definition at line 722 of file main_stereo.cpp.
References FOV_Y, gDepthWinHeight, gDepthWinWidth, gFarZ, and gNearZ.
Referenced by main().
 {
     glMatrixMode( GL_PROJECTION );
     glLoadIdentity();
     float   fov_xy = (1.0f * gDepthWinWidth) / gDepthWinHeight;
     gluPerspective(FOV_Y, fov_xy, gNearZ, gFarZ);
     glMatrixMode( GL_MODELVIEW );
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const int COARSER_RESOLUTION_MENU = 104
Definition at line 177 of file main_stereo.cpp.
Referenced by myDepthMenu(), and myInit().
const int DEPTH_MAP_MENU = 202
Definition at line 185 of file main_stereo.cpp.
Referenced by myInit(), and myUpperRightSubmenu().
const int DISPARITY_MAP_MENU = 201
Definition at line 184 of file main_stereo.cpp.
Referenced by myInit(), and myUpperRightSubmenu().
const string disparityImagePath = stereo_dir + "pentagon_d.tga"
Definition at line 49 of file main_stereo.cpp.
Referenced by loadImages().
const int FILLED_FACES_MENU = 101
Definition at line 174 of file main_stereo.cpp.
Referenced by myInit(), and myRenderSubmenu().
const int FILLED_VERTEX_MENU = 102
Definition at line 175 of file main_stereo.cpp.
Referenced by myInit(), and myRenderSubmenu().
const int FINER_RESOLUTION_MENU = 105
Definition at line 178 of file main_stereo.cpp.
Referenced by myDepthMenu(), and myInit().
const float FOV_Y = 40
Definition at line 83 of file main_stereo.cpp.
Referenced by computeDepth(), and setupProjCam().
GLfloat gAngle = 20
Definition at line 158 of file main_stereo.cpp.
Referenced by myDepthMotion(), and myDisplayDepth().
GLfloat gAngle2 = 30
Definition at line 159 of file main_stereo.cpp.
Referenced by myDepthMotion(), and myDisplayDepth().
float gCurrentQuat[4]
Definition at line 152 of file main_stereo.cpp.
int gDepthWindow
Definition at line 139 of file main_stereo.cpp.
Referenced by main(), myDisplayDepth(), and myInit().
int gDepthWinHeight
Definition at line 128 of file main_stereo.cpp.
Referenced by main(), and setupProjCam().
int gDepthWinWidth
Definition at line 128 of file main_stereo.cpp.
Referenced by main(), and setupProjCam().
bool gDisplayDisparity = false
Definition at line 147 of file main_stereo.cpp.
const float gFarZ = 120.0
Definition at line 135 of file main_stereo.cpp.
Referenced by setupProjCam().
bool gFilledFaceNormals = true
Definition at line 148 of file main_stereo.cpp.
Referenced by myRenderSubmenu().
bool gFilledVertexNormals = false
Definition at line 149 of file main_stereo.cpp.
int gImageHeight = kDefaultHeight
Definition at line 128 of file main_stereo.cpp.
int gImageWidth = kDefaultWidth
Definition at line 127 of file main_stereo.cpp.
bool gInitDone = false
Definition at line 146 of file main_stereo.cpp.
Referenced by myDisplay0(), myDisplay1(), and myInit().
float gLastQuat[4]
Definition at line 152 of file main_stereo.cpp.
int gMainWindow
Definition at line 139 of file main_stereo.cpp.
Referenced by main(), myColorSubmenu(), myDisplay0(), myDisplay1(), myDisplayDepth(), myDisplayMain(), and myInit().
ResolutionLevel gMeshResolution = kMediumResolution
Definition at line 132 of file main_stereo.cpp.
Referenced by computeDepth(), myDepthMenu(), and myKeyboard().
bool gMoving = false
Definition at line 150 of file main_stereo.cpp.
Referenced by myDepthMotion(), and myDepthMouse().
DepthMap* gMyDenseMap = NULL
Definition at line 166 of file main_stereo.cpp.
Referenced by myUpperRightSubmenu().
RasterImage_gray_F* gMyDepth = NULL
Definition at line 164 of file main_stereo.cpp.
RasterImage_gray* gMyDisparity = NULL
Definition at line 163 of file main_stereo.cpp.
Referenced by myUpperRightSubmenu().
RasterImage* gMyLeftImage = NULL
Definition at line 161 of file main_stereo.cpp.
RasterImage* gMyRightImage = NULL
Definition at line 162 of file main_stereo.cpp.
Referenced by loadImages(), and myUpperRightSubmenu().
const float gNearZ = 1
Definition at line 134 of file main_stereo.cpp.
Referenced by setupProjCam().
const int GREEN_COLOR_MENU = 107
Definition at line 180 of file main_stereo.cpp.
Referenced by myDepthMenu(), and myInit().
int gStartx
Definition at line 143 of file main_stereo.cpp.
Referenced by myDepthMotion(), and myDepthMouse().
int gStarty
Definition at line 143 of file main_stereo.cpp.
Referenced by myDepthMotion(), and myDepthMouse().
int gSubwindow[2]
Definition at line 139 of file main_stereo.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), and myInit().
GLfloat gTx = 0.f
Definition at line 155 of file main_stereo.cpp.
Referenced by myDisplayDepth().
GLfloat gTy = 0.f
Definition at line 156 of file main_stereo.cpp.
Referenced by myDisplayDepth().
GLfloat gTz = -70.0f
Definition at line 157 of file main_stereo.cpp.
Referenced by myDisplayDepth().
RasterImage* gUpperRightDisplay = NULL
Definition at line 165 of file main_stereo.cpp.
int gWinHeight
Definition at line 125 of file main_stereo.cpp.
Referenced by main().
int gWinWidth
Definition at line 125 of file main_stereo.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {.2f, .2f, .3f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                                                                         }
Definition at line 192 of file main_stereo.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Gray",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 199 of file main_stereo.cpp.
Referenced by myInit().
const string leftImagePath = stereo_dir + "pentagon_L.tga"
Definition at line 47 of file main_stereo.cpp.
Referenced by loadImages().
const float MAX_DEPTH = 80.f
Definition at line 137 of file main_stereo.cpp.
Referenced by computeDepth().
const int QUIT_MENU = 0
Definition at line 171 of file main_stereo.cpp.
Referenced by myDepthMenu(), myInit(), myMenu0(), and myMenu1().
const int RED_COLOR_MENU = 106
Definition at line 179 of file main_stereo.cpp.
Referenced by myDepthMenu(), and myInit().
const int RIGHT_IMAGE_MENU = 200
Definition at line 183 of file main_stereo.cpp.
Referenced by myInit(), and myUpperRightSubmenu().
const string righttImagePath = stereo_dir + "pentagon_R.tga"
Definition at line 48 of file main_stereo.cpp.
Referenced by loadImages().
const string stereo_dir = STEREO_DIR_PATH
Definition at line 45 of file main_stereo.cpp.
const int UPPER_LEFT = 0
Definition at line 168 of file main_stereo.cpp.
Referenced by main(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 169 of file main_stereo.cpp.
Referenced by main(), myDisplay1(), and myInit().
const int WIREFRAME_MENU = 100
Definition at line 173 of file main_stereo.cpp.
Referenced by myInit(), and myRenderSubmenu().
const int YELLOW_COLOR_MENU = 108
Definition at line 181 of file main_stereo.cpp.
Referenced by myDepthMenu(), and myInit().