URIVisionLibrary: main_imageHistogram.cpp File Reference
main_imageHistogram.cpp File Reference
#include <iostream>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "ImageHistogram.h"
#include "HistogramCalculator.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 1
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbColorChoices 5
#define kNbRenderModes 2
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myReshape (int w, int h)
void settupCamera (int w, int h)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myMouseMotion (int ix, int iy)
bool withinBounds (int ix, int iy)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myFrameColorSubmenu (int value)
void myHistogramColorSubmenu (int value)
void myHistogramAxesColorSubmenu (int value)
void myHistogramTitleColorSubmenu (int value)
void myHistogramBackgroundColorSubmenu (int value)
void myHistogramRenderModeSubmenu (int value)
void myInit (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const string output_dir = OUTPUT_DIR_PATH
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbRowsSubwindows *kNbColsSubwindows]
bool gInitDone = false
bool gDisplayAxes = false
bool gDisplayLabels = false
RasterImage * gMyImage = NULL
RasterImage_gray * gGrayImage = NULL
ImageHistogram * gGrayHist = NULL
const int kMinSearchDim = 20
bool gMouseDown = false
int gDragWin
int gStartDragX
int gStartDragY
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int QUIT_MENU = 0
const int SEPARATOR = 1000
const int RESET_MENU = 1
const int TOGGLE_DISPLAY_AXES_MENU = 2
const int TOGGLE_DISPLAY_TITLE_MENU = 3
GLfloat kColorChoice [kNbColorChoices][4]
string kColStr []
HistogramRenderMode kRenderMode [kNbRenderModes]
char * kRenderModeStr [kNbRenderModes]
Macro Definition Documentation
#define kBorder 8
Definition at line 70 of file main_imageHistogram.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 71 of file main_imageHistogram.cpp.
#define kDefaultWidth 256
Definition at line 72 of file main_imageHistogram.cpp.
#define kMaxWindowHeight 640
Definition at line 74 of file main_imageHistogram.cpp.
#define kMaxWindowWidth 900
Definition at line 73 of file main_imageHistogram.cpp.
#define kNbColorChoices 5
Definition at line 148 of file main_imageHistogram.cpp.
Referenced by myFrameColorSubmenu(), myHistogramAxesColorSubmenu(), myHistogramBackgroundColorSubmenu(), myHistogramColorSubmenu(), myHistogramTitleColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 66 of file main_imageHistogram.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 68 of file main_imageHistogram.cpp.
#define kNbRenderModes 2
Definition at line 165 of file main_imageHistogram.cpp.
Referenced by myHistogramRenderModeSubmenu(), and myInit().
#define kNbRowsSubwindows 1
Definition at line 65 of file main_imageHistogram.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 67 of file main_imageHistogram.cpp.
Referenced by main(), and myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 206 of file main_imageHistogram.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 182 of file main_imageHistogram.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 221 of file main_imageHistogram.cpp.
References cleanupAndQuit(), uriVL::ImageReader::getFrame(), gGrayImage, gray_dir, and myReader.
Referenced by main().
 {
     const string grayFilePath = gray_dir + "Lena_256x256.tga";
     //-------------------------------------------------------------
     //  We read the image from a file
     //-------------------------------------------------------------
     ImageReader myReader(const_cast<char*>(grayFilePath.c_str()));
     gGrayImage = static_cast<RasterImage_gray*>(myReader.getFrame(true));
     if (gGrayImage ==NULL)
     {
         cout << "Error encountered while reading image file " << grayFilePath << endl;
                 cleanupAndQuit(-1);
     }
     gMyImage = gGrayImage;
     gGrayHist = new ImageHistogram(gGrayImage);
 }
int main (int argc, char ** argv)
Definition at line 656 of file main_imageHistogram.cpp.
References cleanupAndQuit(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gImageHeight, gImageWidth, gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBorder, kColorChoice, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplayMain(), myInit(), myKeyboard(), myMouse(), myReshape(), and settupCamera().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1};
         try
         {
         //      initialization code.  You will always need this
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         //      I load my image
         loadImage();
         int     imgHeight = gMyImage->getHeight(),
             imgWidth = gMyImage->getWidth();
         //      I initialize my window's dimensions
         gWinHeight = kNbRowsSubwindows * imgHeight + (kNbRowsSubwindows + 1) * kBorder;
         gWinWidth = kNbColsSubwindows * imgWidth + (kNbColsSubwindows + 1) * kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Image Histogram Demo");
         glClearColor(0.0, 0.0, 0.0, 1.0);
         //  and I inform drawable object of these dimensions (in case they want to get rendered
         //  "shifted")
         DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
         //      in all applications with a GUI you will need to define some
         //      of these callback functions
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glutMouseFunc(myMouse);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(imgWidth + kBorder) + kBorder,
                                                         i*(imgHeight + kBorder) + kBorder,
                                                         imgWidth, imgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kColorChoice[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 settupCamera(imgWidth, imgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
                 //  Enter infinite glut loop
                 glutMainLoop();
                 //  Normally this call should never be placed since the only way to leave the
                 //  glut loop is to quit
                 cleanupAndQuit(0);
         }
         catch (uriVL::ErrorReport & e)
         {
                 cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
                 return 1;
         }
         return 0;
 }
void myDisplay0 (void)
Definition at line 263 of file main_imageHistogram.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 280 of file main_imageHistogram.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gGrayHist->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 250 of file main_imageHistogram.cpp.
References gMainWindow, myDisplay0(), and myDisplay1().
Referenced by main(), and myMouse().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
 }
void myFrameColorSubmenu (int value)
Definition at line 488 of file main_imageHistogram.cpp.
References gMainWindow, kColorChoice, and kNbColorChoices.
Referenced by myInit().
 {
     if ((colorIndex >= 0) && (colorIndex < kNbColorChoices))
     {
         GLfloat         *backColor;
         glutSetWindow(gMainWindow);
         backColor = kColorChoice[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myHistogramAxesColorSubmenu (int value)
Definition at line 516 of file main_imageHistogram.cpp.
References gMainWindow, kColorChoice, kNbColorChoices, and uriVL::Histogram::setAxesColor().
Referenced by myInit().
 {
     if ((colorIndex >= 0) && (colorIndex < kNbColorChoices))
     {
         GLfloat         *histColor = kColorChoice[colorIndex];
         gGrayHist->setAxesColor(histColor[0], histColor[1], histColor[2]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myHistogramBackgroundColorSubmenu (int value)
Definition at line 540 of file main_imageHistogram.cpp.
References gMainWindow, kColorChoice, kNbColorChoices, and uriVL::Histogram::setBackgroundColor().
Referenced by myInit().
 {
     if ((colorIndex >= 0) && (colorIndex < kNbColorChoices))
     {
         GLfloat         *histColor = kColorChoice[colorIndex];
         gGrayHist->setBackgroundColor(histColor[0], histColor[1], histColor[2]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myHistogramColorSubmenu (int value)
Definition at line 504 of file main_imageHistogram.cpp.
References gMainWindow, kColorChoice, kNbColorChoices, and uriVL::DrawableObject2D::setColor().
Referenced by myInit().
 {
     if ((colorIndex >= 0) && (colorIndex < kNbColorChoices))
     {
         GLfloat         *histColor = kColorChoice[colorIndex];
         gGrayHist->setColor(histColor[0], histColor[1], histColor[2]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myHistogramRenderModeSubmenu (int value)
Definition at line 552 of file main_imageHistogram.cpp.
References gMainWindow, kNbRenderModes, kRenderMode, and uriVL::ImageHistogram::setRenderMode().
Referenced by myInit().
 {
     if ((modeIndex >= 0) && (modeIndex < kNbRenderModes))
     {
         gGrayHist->setRenderMode(kRenderMode[modeIndex]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myHistogramTitleColorSubmenu (int value)
Definition at line 528 of file main_imageHistogram.cpp.
References gMainWindow, kColorChoice, kNbColorChoices, and uriVL::Histogram::setTitleColor().
Referenced by myInit().
 {
     if ((colorIndex >= 0) && (colorIndex < kNbColorChoices))
     {
         GLfloat         *histColor = kColorChoice[colorIndex];
         gGrayHist->setTitleColor(histColor[0], histColor[1], histColor[2]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myInit (void)
Definition at line 569 of file main_imageHistogram.cpp.
References gInitDone, gMainWindow, gSubwindow, kColStr, kNbColorChoices, kNbRenderModes, kNbSubwindows, kRenderModeStr, myFrameColorSubmenu(), myHistogramAxesColorSubmenu(), myHistogramBackgroundColorSubmenu(), myHistogramColorSubmenu(), myHistogramRenderModeSubmenu(), myHistogramTitleColorSubmenu(), myMenu0(), myMenu1(), myMenuMain(), myMouse(), myMouseMotion(), QUIT_MENU, SEPARATOR, TOGGLE_DISPLAY_AXES_MENU, TOGGLE_DISPLAY_TITLE_MENU, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], frameColorSubmenu, histColorSubmenu,
         histRenderModeSubmenu, histAxesColorSubmenu, histBackgroundColorSubmenu,
         histTitleColorSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     //  Submenu for background color selection choices
     frameColorSubmenu = glutCreateMenu(myFrameColorSubmenu);
     for (int i=0; i<kNbColorChoices; i++)
         glutAddMenuEntry(kColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------------------------------------------------
     //  Left subwindow: select gray-color, frame color, quit
     //------------------------------------------------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glutMotionFunc(myMouseMotion);
     glutMouseFunc(myMouse);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", frameColorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------------------------------------------------
     //  right subwindow: select histogram display modes & color, frame color, quit
     //------------------------------------------------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     //
     //  Submenu for histogram color selection choices
     histColorSubmenu = glutCreateMenu(myHistogramColorSubmenu);
     for (int i=0; i<kNbColorChoices; i++)
         glutAddMenuEntry(kColStr[i].c_str(), i);
     //
     //  Submenu for histogram axes color selection choices
     histAxesColorSubmenu = glutCreateMenu(myHistogramAxesColorSubmenu);
     for (int i=0; i<kNbColorChoices; i++)
         glutAddMenuEntry(kColStr[i].c_str(), i);
     //
     //  Submenu for histogram background color selection choices
     histBackgroundColorSubmenu = glutCreateMenu(myHistogramBackgroundColorSubmenu);
     for (int i=0; i<kNbColorChoices; i++)
         glutAddMenuEntry(kColStr[i].c_str(), i);
     //
     //  Submenu for histogram title color selection choices
     histTitleColorSubmenu = glutCreateMenu(myHistogramTitleColorSubmenu);
     for (int i=0; i<kNbColorChoices; i++)
         glutAddMenuEntry(kColStr[i].c_str(), i);
     //
     //  Submenu for histogram render mode selection
     histRenderModeSubmenu = glutCreateMenu(myHistogramRenderModeSubmenu);
     for (int i=0; i<kNbRenderModes; i++)
         glutAddMenuEntry(kRenderModeStr[i], i);
     //
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     //
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Toggle display axes", TOGGLE_DISPLAY_AXES_MENU);
     glutAddMenuEntry("Toggle display title", TOGGLE_DISPLAY_TITLE_MENU);
     glutAddSubMenu("Histogram render mode", histRenderModeSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Histogram color", histColorSubmenu);
     glutAddSubMenu("Histogram background color", histBackgroundColorSubmenu);
     glutAddSubMenu("Histogram axes color", histAxesColorSubmenu);
     glutAddSubMenu("Histogram title color", histTitleColorSubmenu);
     glutAddSubMenu("Histogram rendering mode", histRenderModeSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", frameColorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 337 of file main_imageHistogram.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 443 of file main_imageHistogram.cpp.
References cleanupAndQuit(), QUIT_MENU, and RESET_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case RESET_MENU:
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 461 of file main_imageHistogram.cpp.
References cleanupAndQuit(), gDisplayAxes, gDisplayLabels, QUIT_MENU, uriVL::Histogram::setDrawAxes(), uriVL::Histogram::setDrawTitle(), TOGGLE_DISPLAY_AXES_MENU, and TOGGLE_DISPLAY_TITLE_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case TOGGLE_DISPLAY_AXES_MENU:
             gDisplayAxes = !gDisplayAxes;
             gGrayHist->setDrawAxes(gDisplayAxes);
             glutPostRedisplay();
             break;
         case TOGGLE_DISPLAY_TITLE_MENU:
             gDisplayLabels = !gDisplayLabels;
             gGrayHist->setDrawTitle(gDisplayAxes);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 428 of file main_imageHistogram.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 352 of file main_imageHistogram.cpp.
Referenced by main(), and myInit().
 {
     if (button == GLUT_LEFT_BUTTON)
     {
         if (buttonState == GLUT_DOWN)
         {
             //  If the mouse button was not already pressed down, we start recording
             if (!gMouseDown)
             {
                 gMouseDown = true;
                 gStartDragX = ix;
                 gStartDragY = iy;
             }
         }
         else    //      buttonState == GLUT_UP
         {
             //  check that the mouse had been dragged from within the same subwindow and
             //  defines a suffficiently large search region.
             if (gMouseDown && withinBounds(ix, iy))
             {
                 int theLeft = MIN(ix, gStartDragX),
                     theTop = MIN(iy, gStartDragY),
                     theWidth = MAX(ix, gStartDragX) - theLeft + 1,
                     theHeight = MAX(iy, gStartDragY) - theTop + 1;
                 if ((theWidth >= kMinSearchDim) && (theHeight >= kMinSearchDim))
                 {
                     ImageRect myRect(theLeft, theTop, theWidth, theHeight);
                     gGrayHist->setImage(gGrayImage, &myRect);
                 }
             }
             gMouseDown = false;
             gDragWin = -1;
             myDisplayMain();
         }
     }
 }
void myMouseMotion (int ix, int iy)
Definition at line 392 of file main_imageHistogram.cpp.
References gImageHeight, gMouseDown, gStartDragX, gStartDragY, gSubwindow, uriVL::DrawableObject2D::render(), UPPER_LEFT, and withinBounds().
Referenced by myInit().
 {
     if (gMouseDown)
     {
         glutSetWindow(gSubwindow[UPPER_LEFT]);
         glClear(GL_COLOR_BUFFER_BIT);
         if (gMyImage!= NULL)
             gMyImage->render();
         if (withinBounds(ix, iy))
         {
             glColor3f(1.0f, 1.0f, 1.0f);
             glBegin(GL_LINE_LOOP);
             glVertex2i(gStartDragX, gImageHeight - 1 -gStartDragY);
             glVertex2i(gStartDragX, gImageHeight - iy - 1);
             glVertex2i(ix, gImageHeight - iy - 1);
             glVertex2i(ix, gImageHeight - 1 - gStartDragY);
             glEnd();
         }
         glutSwapBuffers();
     }
 }
void myReshape (int w, int h)
Definition at line 302 of file main_imageHistogram.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void settupCamera (int w, int h)
Definition at line 321 of file main_imageHistogram.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
bool withinBounds (int ix, int iy)
Definition at line 418 of file main_imageHistogram.cpp.
Referenced by myMouse(), and myMouseMotion().
 {
     return ((ix>=0) && (ix<gMyImage->getWidth()) &&
             (iy>=0) && (iy<gMyImage->getHeight()));
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 57 of file main_imageHistogram.cpp.
bool gDisplayAxes = false
Definition at line 121 of file main_imageHistogram.cpp.
Referenced by myMenu1().
bool gDisplayLabels = false
Definition at line 122 of file main_imageHistogram.cpp.
Referenced by myMenu1().
int gDragWin
Definition at line 130 of file main_imageHistogram.cpp.
Referenced by myMouse().
ImageHistogram* gGrayHist = NULL
Definition at line 126 of file main_imageHistogram.cpp.
RasterImage_gray* gGrayImage = NULL
Definition at line 125 of file main_imageHistogram.cpp.
Referenced by loadImage().
int gImageHeight = kDefaultHeight
Definition at line 115 of file main_imageHistogram.cpp.
Referenced by main(), and myMouseMotion().
int gImageWidth = kDefaultWidth
Definition at line 114 of file main_imageHistogram.cpp.
Referenced by main().
bool gInitDone = false
Definition at line 120 of file main_imageHistogram.cpp.
Referenced by myDisplay0(), myDisplay1(), and myInit().
int gMainWindow
Definition at line 117 of file main_imageHistogram.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplayMain(), myFrameColorSubmenu(), myHistogramAxesColorSubmenu(), myHistogramBackgroundColorSubmenu(), myHistogramColorSubmenu(), myHistogramRenderModeSubmenu(), myHistogramTitleColorSubmenu(), and myInit().
bool gMouseDown = false
Definition at line 129 of file main_imageHistogram.cpp.
Referenced by myMouse(), and myMouseMotion().
RasterImage* gMyImage = NULL
Definition at line 124 of file main_imageHistogram.cpp.
const string gray_dir = GRAY_DIR_PATH
Definition at line 58 of file main_imageHistogram.cpp.
Referenced by loadImage().
int gStartDragX
Definition at line 131 of file main_imageHistogram.cpp.
Referenced by myMouse(), and myMouseMotion().
int gStartDragY
Definition at line 131 of file main_imageHistogram.cpp.
Referenced by myMouse(), and myMouseMotion().
int gSubwindow[kNbRowsSubwindows *kNbColsSubwindows]
Definition at line 117 of file main_imageHistogram.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myInit(), and myMouseMotion().
int gWinHeight
Definition at line 112 of file main_imageHistogram.cpp.
Referenced by main().
int gWinWidth
Definition at line 112 of file main_imageHistogram.cpp.
Referenced by main().
GLfloat kColorChoice[kNbColorChoices][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                                                                         }
Definition at line 150 of file main_imageHistogram.cpp.
Referenced by main(), myFrameColorSubmenu(), myHistogramAxesColorSubmenu(), myHistogramBackgroundColorSubmenu(), myHistogramColorSubmenu(), and myHistogramTitleColorSubmenu().
string kColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 156 of file main_imageHistogram.cpp.
Referenced by myInit().
const int kMinSearchDim = 20
Definition at line 128 of file main_imageHistogram.cpp.
Referenced by myMouse().
HistogramRenderMode kRenderMode[kNbRenderModes]
Initial value:
= {
                                                    LIN_LIN,
                                                    LIN_LOG
                                                  }
Definition at line 167 of file main_imageHistogram.cpp.
Referenced by myHistogramRenderModeSubmenu().
char* kRenderModeStr[kNbRenderModes]
Initial value:
= {
                                            "LIN_LIN",
                                            "LIN_LOG"
                                          }
Definition at line 172 of file main_imageHistogram.cpp.
Referenced by myInit().
const string output_dir = OUTPUT_DIR_PATH
Definition at line 59 of file main_imageHistogram.cpp.
const int QUIT_MENU = 0
Definition at line 137 of file main_imageHistogram.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), and myMenuMain().
const int RESET_MENU = 1
Definition at line 139 of file main_imageHistogram.cpp.
Referenced by myMenu0().
const int SEPARATOR = 1000
Definition at line 138 of file main_imageHistogram.cpp.
Referenced by myInit().
const int TOGGLE_DISPLAY_AXES_MENU = 2
Definition at line 140 of file main_imageHistogram.cpp.
Referenced by myInit(), and myMenu1().
const int TOGGLE_DISPLAY_TITLE_MENU = 3
Definition at line 141 of file main_imageHistogram.cpp.
Referenced by myInit(), and myMenu1().
const int UPPER_LEFT = 0
Definition at line 134 of file main_imageHistogram.cpp.
Referenced by myDisplay0(), myInit(), and myMouseMotion().
const int UPPER_RIGHT = 1
Definition at line 135 of file main_imageHistogram.cpp.
Referenced by myDisplay1(), and myInit().