URIVisionLibrary: main_filling.cpp File Reference
main_filling.cpp File Reference
#include <fstream>
#include <iostream>
#include <list>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "BlobFinder.h"
#include "ColorThresholdLabeler.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void initThresholds (void)
void detectAllBlobs (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myLabelSubmenu (int value)
void myColorSubmenu (int value)
void myMouse3 (int button, int buttonState, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string filePath = color_dir + "mandrill_256x256.tga"
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int MENU_SEPARATOR = -1
const int QUIT_MENU = 0
const int INCREASE_THRESH_MENU = 2
const int DECREASE_THRESH_MENU = 3
const int TOGGLE_SHOW_BCKGND_IMAGE_MENU = 4
const int TOGGLE_SHOW_BLOBS_MENU = 5
const int TOGGLE_SHOW_BLOB_CONTOURS_MENU = 6
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
FillingMode gModeWin [kNbSubwindows]
RasterImage ** gMyImage = NULL
LabelRaster * gLabel2
LabelRaster * gLabel3
BlobList * gBlobList2
BlobList gBlobList3
ColorThresholdLabeler * gThresholder
ColorSegParams * gColorParams
BlobFinder * gBlobFinder = new BlobFinder()
char gTargetIndex = (char) -1
long gBlobMinSize = 20
bool gShowBackgndImage = true
bool gShowBlobs = true
bool gShowBlobContours = false
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 81 of file main_filling.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 82 of file main_filling.cpp.
#define kDefaultWidth 256
Definition at line 83 of file main_filling.cpp.
#define kMaxWindowHeight 640
Definition at line 85 of file main_filling.cpp.
#define kMaxWindowWidth 900
Definition at line 84 of file main_filling.cpp.
#define kNbBckgndCols 5
Definition at line 167 of file main_filling.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 77 of file main_filling.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 79 of file main_filling.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 76 of file main_filling.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 78 of file main_filling.cpp.
Referenced by main(), and myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 212 of file main_filling.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void detectAllBlobs (void)
Definition at line 350 of file main_filling.cpp.
References uriVL::ColorThresholdLabeler::applyInto(), uriVL::ColorSegParams::colorReg, uriVL::BlobFinder::findAllBlobs(), gBlobList2, gBlobMinSize, uriVL::ColorRegion::label, uriVL::ColorSegParams::nbModes, and UPPER_LEFT.
Referenced by loadImage(), and myMenu2().
 {
     //  clear the lists of blobs for each target color
     for (int k=0; k<gColorParams->nbModes; k++)
     {
         BlobList::iterator      iter;
         for (iter=gBlobList2[k].begin(); iter!=gBlobList2[k].end(); iter++)
             //  delete the blob allocated
             delete (*iter);
         gBlobList2[k].clear();
     }
         delete []gBlobList2;
     //  apply color thresholding
     gThresholder->applyInto(gMyImage[UPPER_LEFT], gColorParams, gLabel2);
     //gThresholder->applyInto(gMyImage[UPPER_LEFT], gColorParams, gLabel2, true);
     char        *target = new char[gColorParams->nbModes];
     for (int m=0; m<gColorParams->nbModes; m++)
         target[m] = gColorParams->colorReg[m].label;
     //  Detect the blobs and assign to each one of them a filling color to render them
     //gBlobFinder->findAllBlobs(gLabel2, gColorParams->nbModes, target, gBlobMinSize, gBlobList2);
 //    gBlobFinder->findAllBlobs(gLabel2, gColorParams->nbModes,
 //                                                target, gBlobMinSize, gBlobList2, true);
     gBlobList2 = gBlobFinder->findAllBlobs(gLabel2, gColorParams->nbModes,
                                                   target, gBlobMinSize, true);
 //                                                target, gBlobMinSize, false);
     for (int m1=0; m1<gColorParams->nbModes ; m1++)
         if (!gBlobList2[m1].empty())
         {
             BlobList::iterator iter, endList = gBlobList2[m1].end();
             for (iter = gBlobList2[m1].begin(); iter != endList; iter++)
             {
                 (*iter)->setColor((gColorParams->colorReg[m1]).fillColor);
                 (*iter)->setContourColor(1.f, 1.f, 1.f);
             }
         }
     delete []target;
 }
void initializeQTEnvironment (void)
Definition at line 188 of file main_filling.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void initThresholds (void)
Definition at line 268 of file main_filling.cpp.
References uriVL::ColorSegParams::colorMode, uriVL::ColorSegParams::colorReg, uriVL::ColorRegion::deltaHue, uriVL::ColorRegion::fillColor, uriVL::ColorSegParams::grayReg, uriVL::ColorRegion::hueRef, uriVL::ColorRegion::label, uriVL::ColorRegion::labelStr, uriVL::ColorSegParams::nbModes, uriVL::ColorRegion::satMax, uriVL::ColorRegion::satMin, uriVL::ColorRegion::valMax, and uriVL::ColorRegion::valMin.
Referenced by main().
 {
     gColorParams = new ColorSegParams;
     gColorParams->nbModes = 6;
     gColorParams->colorMode = true;
     gColorParams->grayReg = NULL;
     gColorParams->colorReg = new ColorRegion[gColorParams->nbModes];
     gColorParams->colorReg[0].labelStr =  "magentaish";
     gColorParams->colorReg[0].hueRef = 300;
     gColorParams->colorReg[0].deltaHue = 30;
     gColorParams->colorReg[0].satMin = 20;
     gColorParams->colorReg[0].satMax = 100;
     gColorParams->colorReg[0].valMin = 0;
     gColorParams->colorReg[0].valMax = 255;
     gColorParams->colorReg[0].fillColor[0] = (unsigned char) 255;
     gColorParams->colorReg[0].fillColor[1] = 0;
     gColorParams->colorReg[0].fillColor[2] = (unsigned char) 255;
     gColorParams->colorReg[0].label = (char) 1;
     gColorParams->colorReg[1].labelStr = "red";
     gColorParams->colorReg[1].hueRef = 0;
     gColorParams->colorReg[1].deltaHue = 15;
     gColorParams->colorReg[1].satMin = 20;
     gColorParams->colorReg[1].satMax = 100;
     gColorParams->colorReg[1].valMin = 0;
     gColorParams->colorReg[1].valMax = 255;
     gColorParams->colorReg[1].fillColor[0] = (unsigned char) 255;
     gColorParams->colorReg[1].fillColor[1] = 0;
     gColorParams->colorReg[1].fillColor[2] = 0;
     gColorParams->colorReg[1].label = (char) 2;
     gColorParams->colorReg[2].labelStr = "greenish";
     gColorParams->colorReg[2].hueRef = 110;
     gColorParams->colorReg[2].deltaHue = 15;
     gColorParams->colorReg[2].satMin = 40;
     gColorParams->colorReg[2].satMax = 100;
     gColorParams->colorReg[2].valMin = 0;
     gColorParams->colorReg[2].valMax = 255;
     gColorParams->colorReg[2].fillColor[0] = 0;
     gColorParams->colorReg[2].fillColor[1] = (unsigned char) 255;
     gColorParams->colorReg[2].fillColor[2] = 0;
     gColorParams->colorReg[2].label = (char) 3;
     gColorParams->colorReg[3].labelStr = "yellowish";
     gColorParams->colorReg[3].hueRef = 55;
     gColorParams->colorReg[3].deltaHue = 20;
     gColorParams->colorReg[3].satMin = 20;
     gColorParams->colorReg[3].satMax = 100;
     gColorParams->colorReg[3].valMin = 0;
     gColorParams->colorReg[3].valMax = 255;
     gColorParams->colorReg[3].fillColor[0] = (unsigned char) 255;
     gColorParams->colorReg[3].fillColor[1] = (unsigned char) 255;
     gColorParams->colorReg[3].fillColor[2] = 0;
     gColorParams->colorReg[3].label = (char) 4;
     gColorParams->colorReg[4].labelStr = "blueish";
     gColorParams->colorReg[4].hueRef = 240;
     gColorParams->colorReg[4].deltaHue = 20;
     gColorParams->colorReg[4].satMin = 20;
     gColorParams->colorReg[4].satMax = 100;
     gColorParams->colorReg[4].valMin = 0;
     gColorParams->colorReg[4].valMax = 255;
     gColorParams->colorReg[4].fillColor[0] = 0;
     gColorParams->colorReg[4].fillColor[1] = 0;
     gColorParams->colorReg[4].fillColor[2] = (unsigned char) 255;
     gColorParams->colorReg[4].label = (char) 5;
     gColorParams->colorReg[5].labelStr = "cianish";
     gColorParams->colorReg[5].hueRef = 185;
     gColorParams->colorReg[5].deltaHue = 25;
     gColorParams->colorReg[5].satMin = 20;
     gColorParams->colorReg[5].satMax = 100;
     gColorParams->colorReg[5].valMin = 0;
     gColorParams->colorReg[5].valMax = 255;
     gColorParams->colorReg[5].fillColor[0] = 0;
     gColorParams->colorReg[5].fillColor[1] = (unsigned char) 255;
     gColorParams->colorReg[5].fillColor[2] = (unsigned char) 255;
     gColorParams->colorReg[5].label = (char) 6;
 }
void loadImage (void)
Definition at line 232 of file main_filling.cpp.
References uriVL::ColorThresholdLabeler::applyInto(), uriVL::ColorThresholdLabeler::applyTo(), cleanupAndQuit(), detectAllBlobs(), filePath, uriVL::ColorSegParams::fillMode, gBlobList2, uriVL::ImageReader::getFrame(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gImageHeight, gImageWidth, kNbImages, uriVL::kOrigGrayFill, LOWER_LEFT, myReader, uriVL::ColorSegParams::nbModes, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     ImageReader myReader(const_cast<char*>(filePath.c_str()));
     gMyImage = new RasterImage *[kNbImages];
     //-------------------------------------------------------------
     //  We read the input image from a file
     //-------------------------------------------------------------
     gMyImage[UPPER_LEFT] = myReader.getFrame(true);
     if (gMyImage[UPPER_LEFT] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath << endl;
         cleanupAndQuit(-1);
     }
     gImageWidth = gMyImage[UPPER_LEFT]->getWidth();
     gImageHeight = gMyImage[UPPER_LEFT]->getHeight();
     gThresholder = new ColorThresholdLabeler();
     //  select a black background
     gColorParams->fillMode = kOrigGrayFill;
     gMyImage[UPPER_RIGHT] = new RasterImage_RGBa(gImageHeight, gImageWidth);
     gThresholder->applyInto(gMyImage[UPPER_LEFT], (char *) gColorParams, gMyImage[UPPER_RIGHT]);
     gMyImage[LOWER_LEFT] = new RasterImage_gray(gMyImage[UPPER_LEFT]);
     gLabel2 = gThresholder->applyTo(gMyImage[UPPER_LEFT], gColorParams);
     //gLabel2 = gThresholder->applyTo(gMyImage[UPPER_LEFT], gColorParams, true);
     gBlobList2 = new BlobList[gColorParams->nbModes];
     detectAllBlobs();
     gLabel3 = gThresholder->applyTo(gMyImage[UPPER_LEFT], gColorParams);
 }
int main (int argc, char ** argv)
Definition at line 826 of file main_filling.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), gImageHeight, gImageWidth, gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), initThresholds(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), myReshape(), and setupCamera().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                      myDisplay2, myDisplay3};
     try
         {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         initThresholds();
         loadImage();
         //      I initialize my window's dimensions at the default values
         gWinHeight = kNbRowsSubwindows*(gImageHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows*(gImageWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Blob Filling Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
         glClearColor(0.2f, 0.2f, 0.2f, 1.f);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(
                                         gMainWindow,
                                         j*(gImageWidth + kBorder) + kBorder,
                                         i*(gImageHeight + kBorder) + kBorder,
                                         gImageWidth,
                                         gImageHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(gImageWidth, gImageHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         //  Inform drawable objects of the dimensions of my rendering windows
         DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
         myInit();
         glutMainLoop();
         cleanupAndQuit(0);
     }
     catch (uriVL::ErrorReport & e)
         {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
         return 0;
 }
void myColorSubmenu (int value)
Definition at line 698 of file main_filling.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 418 of file main_filling.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_LEFT]!= NULL)
     {
         gMyImage[UPPER_LEFT]->render();
     }
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 434 of file main_filling.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_RIGHT]!= NULL)
     {
         gMyImage[UPPER_RIGHT]->render();
     }
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 450 of file main_filling.cpp.
References gBlobList2, gMainWindow, gShowBackgndImage, gShowBlobs, gSubwindow, LOWER_LEFT, uriVL::ColorSegParams::nbModes, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gShowBackgndImage && (gMyImage[LOWER_LEFT]!= NULL))
         gMyImage[LOWER_LEFT]->render();
     for (int k=0; k<gColorParams->nbModes ; k++)
         if (!gBlobList2[k].empty())
         {
             BlobList::iterator iter;
             for (iter = gBlobList2[k].begin(); iter != gBlobList2[k].end(); iter++)
                 if (gShowBlobs)
                     (*iter)->render(true);
         }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 475 of file main_filling.cpp.
References gBlobList3, gMainWindow, gSubwindow, LOWER_RIGHT, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gMyImage[UPPER_LEFT]!= NULL)
         gMyImage[UPPER_LEFT]->render();
     if (!gBlobList3.empty())
     {
         BlobList::iterator iter;
         for (iter = gBlobList3.begin(); iter != gBlobList3.end(); iter++)
             (*iter)->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 401 of file main_filling.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main(), myMenu2(), and myMouse3().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
     glutSetWindow(gMainWindow);
 }
void myIdle (void)
Definition at line 816 of file main_filling.cpp.
References gInitDone, and gMainWindow.
Referenced by main().
 {
         if (gInitDone)
         {
                 glutSetWindow(gMainWindow);
             glutPostRedisplay();
         }
 }
void myInit (void)
Definition at line 715 of file main_filling.cpp.
References uriVL::ColorSegParams::colorReg, DECREASE_THRESH_MENU, gInitDone, gMainWindow, gSubwindow, INCREASE_THRESH_MENU, kBckgndColStr, kNbBckgndCols, kNbSubwindows, uriVL::ColorRegion::labelStr, LOWER_LEFT, LOWER_RIGHT, MENU_SEPARATOR, myColorSubmenu(), myLabelSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), myMouse3(), uriVL::ColorSegParams::nbModes, QUIT_MENU, TOGGLE_SHOW_BCKGND_IMAGE_MENU, TOGGLE_SHOW_BLOB_CONTOURS_MENU, TOGGLE_SHOW_BLOBS_MENU, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     int i;
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu, labelSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.f, 0.f, 0.f, 1.f);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     //------------------------------------
     // Main menu for the window
     //------------------------------------
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddMenuEntry("Raise blob size threshold", INCREASE_THRESH_MENU);
     glutAddMenuEntry("Lower blob size threshold", DECREASE_THRESH_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddMenuEntry("Toggle show background image", TOGGLE_SHOW_BCKGND_IMAGE_MENU);
     glutAddMenuEntry("Toggle show blobs", TOGGLE_SHOW_BLOBS_MENU);
     glutAddMenuEntry("Toggle show blob contours", TOGGLE_SHOW_BLOB_CONTOURS_MENU);
     //
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-right quadrant
     //------------------------------------
     //  Submenu for target color selection choices
     labelSubmenu = glutCreateMenu(myLabelSubmenu);
     for (i=0; i<gColorParams->nbModes; i++)
     {
         string  menuStr = " target color = " + gColorParams->colorReg[i].labelStr;
         const   char *labelStr = menuStr.c_str();
         glutAddMenuEntry(labelStr, i);
     }
     //
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddSubMenu("Target", labelSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutMouseFunc(myMouse3);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 530 of file main_filling.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myLabelSubmenu (int value)
Definition at line 693 of file main_filling.cpp.
References gTargetIndex.
Referenced by myInit().
 {
     gTargetIndex = targetIndex;
 }
void myMenu0 (int value)
Definition at line 596 of file main_filling.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 611 of file main_filling.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 626 of file main_filling.cpp.
References cleanupAndQuit(), DECREASE_THRESH_MENU, detectAllBlobs(), gBlobList2, gBlobMinSize, gShowBackgndImage, gShowBlobContours, gShowBlobs, INCREASE_THRESH_MENU, myDisplayMain(), uriVL::ColorSegParams::nbModes, QUIT_MENU, TOGGLE_SHOW_BCKGND_IMAGE_MENU, TOGGLE_SHOW_BLOB_CONTOURS_MENU, and TOGGLE_SHOW_BLOBS_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case INCREASE_THRESH_MENU:
             gBlobMinSize += 5;
             detectAllBlobs();
             myDisplayMain();
             break;
         case DECREASE_THRESH_MENU:
             if (gBlobMinSize >= 10)
             {
                 gBlobMinSize -= 5;
                 detectAllBlobs();
                 myDisplayMain();
             }
             break;
         case TOGGLE_SHOW_BCKGND_IMAGE_MENU:
             gShowBackgndImage = !gShowBackgndImage;
             myDisplayMain();
             break;
         case TOGGLE_SHOW_BLOBS_MENU:
             gShowBlobs = !gShowBlobs;
             myDisplayMain();
             break;
         case TOGGLE_SHOW_BLOB_CONTOURS_MENU:
             gShowBlobContours = !gShowBlobContours;
             for (int k=0; k<gColorParams->nbModes ; k++)
                 if (!gBlobList2[k].empty())
                 {
                     BlobList::iterator iter;
                     for (iter = gBlobList2[k].begin(); iter != gBlobList2[k].end(); iter++)
                                         (*iter)->setDrawContour(gShowBlobContours);
                 }
             myDisplayMain();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 679 of file main_filling.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 581 of file main_filling.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse3 (int button, int buttonState, int ix, int iy)
Definition at line 547 of file main_filling.cpp.
References uriVL::ColorSegParams::colorReg, uriVL::ColorRegion::fillColor, uriVL::BlobFinder::findBlobAbout(), gBlobList3, gBlobMinSize, gTargetIndex, uriVL::ColorRegion::label, myDisplayMain(), uriVL::DrawableObject2D::setColor(), and uriVL::DrawableObject2D::setDrawFrame().
Referenced by myInit().
 {
     if (gMyImage[0] != NULL)
     {
         if(buttonState == GLUT_UP && button == GLUT_LEFT_BUTTON)
         {
             if (gTargetIndex >= 0)
             {
                 ImagePoint      *pos = new ImagePoint(ix, iy);
                 ImageRect       *theRect = new ImageRect(ix-5, iy-5, 11, 11);
                 Blob    *myBlob = gBlobFinder->findBlobAbout(gLabel3, pos,
                                gColorParams->colorReg[gTargetIndex].label,
                                gBlobMinSize, theRect);
                 if (myBlob != NULL)
                 {
                     //  add the block to the list
                     gBlobList3.push_back(myBlob);
                     //  I want to display a frame around my new blob
                     myBlob->setDrawFrame(true);
                     //  I want my blob drawn in the saturated color of my color seg params
                     myBlob->setColor(gColorParams->colorReg[gTargetIndex].fillColor);
                 }
                 delete pos;
                 delete theRect;
                 myDisplayMain();
             }
         }
     }
 }
void myReshape (int w, int h)
Definition at line 499 of file main_filling.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 518 of file main_filling.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 66 of file main_filling.cpp.
const int DECREASE_THRESH_MENU = 3
Definition at line 96 of file main_filling.cpp.
Referenced by myInit(), and myMenu2().
const string filePath = color_dir + "mandrill_256x256.tga"
Definition at line 68 of file main_filling.cpp.
Referenced by loadImage().
BlobFinder* gBlobFinder = new BlobFinder()
Definition at line 157 of file main_filling.cpp.
BlobList* gBlobList2
Definition at line 154 of file main_filling.cpp.
Referenced by detectAllBlobs(), loadImage(), myDisplay2(), and myMenu2().
BlobList gBlobList3
Definition at line 154 of file main_filling.cpp.
Referenced by myDisplay3(), and myMouse3().
long gBlobMinSize = 20
Definition at line 159 of file main_filling.cpp.
Referenced by detectAllBlobs(), myMenu2(), and myMouse3().
ColorSegParams* gColorParams
Definition at line 156 of file main_filling.cpp.
int gImageHeight = kDefaultHeight
Definition at line 142 of file main_filling.cpp.
Referenced by loadImage(), and main().
int gImageWidth = kDefaultWidth
Definition at line 141 of file main_filling.cpp.
Referenced by loadImage(), and main().
bool gInitDone = false
Definition at line 147 of file main_filling.cpp.
Referenced by myIdle(), and myInit().
LabelRaster* gLabel2
Definition at line 153 of file main_filling.cpp.
LabelRaster * gLabel3
Definition at line 153 of file main_filling.cpp.
int gMainWindow
Definition at line 144 of file main_filling.cpp.
Referenced by main(), myColorSubmenu(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), and myInit().
FillingMode gModeWin[kNbSubwindows]
Initial value:
= {kIdentityFill, kBlackFill, kWhiteFill,
                                                    kOrigGrayFill}
Definition at line 149 of file main_filling.cpp.
RasterImage** gMyImage = NULL
Definition at line 152 of file main_filling.cpp.
bool gShowBackgndImage = true
Definition at line 160 of file main_filling.cpp.
Referenced by myDisplay2(), and myMenu2().
bool gShowBlobContours = false
Definition at line 162 of file main_filling.cpp.
Referenced by myMenu2().
bool gShowBlobs = true
Definition at line 161 of file main_filling.cpp.
Referenced by myDisplay2(), and myMenu2().
int gSubwindow[kNbSubwindows]
Definition at line 144 of file main_filling.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
char gTargetIndex = (char) -1
Definition at line 158 of file main_filling.cpp.
Referenced by myLabelSubmenu(), and myMouse3().
ColorThresholdLabeler* gThresholder
Definition at line 155 of file main_filling.cpp.
int gWinHeight
Definition at line 139 of file main_filling.cpp.
Referenced by main().
int gWinWidth
Definition at line 139 of file main_filling.cpp.
Referenced by main().
const int INCREASE_THRESH_MENU = 2
Definition at line 95 of file main_filling.cpp.
Referenced by myInit(), and myMenu2().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                                 }
Definition at line 169 of file main_filling.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Red",
                                "Green" ,
                                "Black",
                                "Yellow",
                                "Cyan"
                            }
Definition at line 175 of file main_filling.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 89 of file main_filling.cpp.
Referenced by loadImage(), myDisplay2(), and myInit().
const int LOWER_RIGHT = 3
Definition at line 90 of file main_filling.cpp.
Referenced by myDisplay3(), and myInit().
const int MENU_SEPARATOR = -1
Definition at line 92 of file main_filling.cpp.
Referenced by myInit().
const int QUIT_MENU = 0
Definition at line 93 of file main_filling.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int TOGGLE_SHOW_BCKGND_IMAGE_MENU = 4
Definition at line 98 of file main_filling.cpp.
Referenced by myInit(), and myMenu2().
const int TOGGLE_SHOW_BLOB_CONTOURS_MENU = 6
Definition at line 100 of file main_filling.cpp.
Referenced by myInit(), and myMenu2().
const int TOGGLE_SHOW_BLOBS_MENU = 5
Definition at line 99 of file main_filling.cpp.
Referenced by myInit(), and myMenu2().
const int UPPER_LEFT = 0
Definition at line 87 of file main_filling.cpp.
Referenced by detectAllBlobs(), loadImage(), myDisplay0(), myDisplay3(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 88 of file main_filling.cpp.
Referenced by loadImage(), myDisplay1(), and myInit().