URIVisionLibrary: NonlinearOptimizer1D_gss.cpp File Reference
NonlinearOptimizer1D_gss.cpp File Reference
#include <iostream>
#include <cmath>
#include "NonlinearOptimizer1D_gss.h"
Variables
const double TAU = 0.618033988749895L
const double TAU1 = 1.L - TAU
const double INV_TAU = 1.L / TAU
const float TAU_F = static_cast<float>(TAU)
const float TAU1_F = static_cast<float>(TAU1)
const float INV_TAU_F = static_cast<float>(INV_TAU)
const double SMALL_STEP_FRAC = 0.01L
const double STEP_GAIN = 1.1L
const float SMALL_STEP_FRAC_F = static_cast<float>(SMALL_STEP_FRAC)
const float STEP_GAIN_F = static_cast<float>(STEP_GAIN)
const int MAX_NB_ITERS = 1000
Variable Documentation
const double INV_TAU = 1.L / TAU
Definition at line 26 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const float INV_TAU_F = static_cast<float>(INV_TAU)
Definition at line 29 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const int MAX_NB_ITERS = 1000
Definition at line 37 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
const double SMALL_STEP_FRAC = 0.01L
Definition at line 31 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const float SMALL_STEP_FRAC_F = static_cast<float>(SMALL_STEP_FRAC)
Definition at line 34 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const double STEP_GAIN = 1.1L
Definition at line 32 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const float STEP_GAIN_F = static_cast<float>(STEP_GAIN)
Definition at line 35 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_().
const double TAU = 0.618033988749895L
Definition at line 23 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
const double TAU1 = 1.L - TAU
Definition at line 25 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
const float TAU1_F = static_cast<float>(TAU1)
Definition at line 28 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
const float TAU_F = static_cast<float>(TAU)
Definition at line 27 of file NonlinearOptimizer1D_gss.cpp.
Referenced by uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().