URIVisionLibrary: patternMatching_main.cpp File Reference
patternMatching_main.cpp File Reference
#include <iostream>
#include <string>
#include <typeinfo>
#include <list>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "PatternMatcher2D_corr.h"
#include "PatternMatcher2D_partCorr.h"
#include "PatternMatcher2D_scaledDiff.h"
#include "PatternMatcher2D_medianDiff.h"
#include "Pattern2DMatchRecord_part.h"
#include "Pattern2D.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void applySaltAndPepperNoise (void)
void applyAdditiveNoise (void)
void performMatching (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myMouse0 (int button, int buttonState, int ix, int iy)
void myMouse1 (int button, int buttonState, int ix, int iy)
void myMouse2 (int button, int buttonState, int ix, int iy)
void myMouse3 (int button, int buttonState, int ix, int iy)
void handleMouseDrag (int buttonState, int ix, int iy, int winIndex)
void handleMiddleDrag (int buttonState, int ix, int iy, int winIndex)
void myMouseMotion (int ix, int iy)
bool withinBounds (int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
int main (int argc, char **argv)
Variables
const string filePath = color_dir + "mandrill_256x256.tga"
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int MENU_SEPARATOR = -1
const int QUIT_MENU = 0
const int COLOR_INPUT_MENU = 100
const int GRAY_INPUT_MENU = 110
const int GAUSSIAN_NOISE_MENU = 10
const int SALT_AND_PEPPER_NOISE_MENU = 20
const int RESET_IMAGE_MENU = 30
const int MATCHER_BASE = 50
const int CORRELATION_MATCHER = 50
const int SCALED_DIFF_MATCHER = 51
const int MEDIAN_DIFF_MATCHER = 52
const int PARTIAL_CORR_MATCHER = 53
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
RasterImage * gGrayImage = NULL
RasterImage * gColorImage = NULL
RasterImage * gInputImage = NULL
RasterImage * gSearchImage = NULL
RasterImage ** gDisplayImage = NULL
ImageRect * gSearchRect = new ImageRect(0, 0, 0, 0)
Pattern2D * gSelectedPat = NULL
ImagePoint * gSelectedOrig = new ImagePoint(0, 0)
ImagePoint * gBestMatch
bool gMatchDone = false
const int kMinSearchDim = 11
bool gMouseDown = false
int gDragWin
int gStartDragX
int gStartDragY
int gMatchingMode = CORRELATION_MATCHER
GLfloat kBackgroundColor [kNbBckgndCols][4]
char * kBckgndColStr []
const float ADDITIVE_NOISE_RANGE = 20.f
const float S_N_P_NOISE_RANGE = 255.f
const int NB_S_N_P_PIXELS = 300
const float ADDITIVE_NOISE_SCALE = (2*ADDITIVE_NOISE_RANGE)/(RAND_MAX + 1.f)
const float S_N_P_NOISE_SCALE = S_N_P_NOISE_RANGE/(RAND_MAX + 1.f)
const float UNIT_SCALE = 1.f/(RAND_MAX + 1.f)
Macro Definition Documentation
#define kBorder 8
Definition at line 98 of file patternMatching_main.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 99 of file patternMatching_main.cpp.
#define kDefaultWidth 256
Definition at line 100 of file patternMatching_main.cpp.
#define kMaxWindowHeight 640
Definition at line 102 of file patternMatching_main.cpp.
#define kMaxWindowWidth 900
Definition at line 101 of file patternMatching_main.cpp.
#define kNbBckgndCols 5
Definition at line 199 of file patternMatching_main.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 94 of file patternMatching_main.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 96 of file patternMatching_main.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 93 of file patternMatching_main.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 95 of file patternMatching_main.cpp.
Referenced by main(), and myInit().
Function Documentation
void applyAdditiveNoise (void)
Definition at line 314 of file patternMatching_main.cpp.
References ADDITIVE_NOISE_SCALE, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kRGBa32Raster, and uriVL::R_W_ACCESS.
Referenced by myMenu2().
 {
     const ImageRect *rect = gSearchImage->getValidRect();
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     switch (gSearchImage->getBaseRasterType())
     {
         case kGrayRaster:
             {
                 unsigned char *const* gray = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                 for (int i=iLow; i<=iHigh; i++)
                    for (int j=jLow; j<=jHigh; j++)
                    {
                       float   v = gray[i][j] + (rand() - 0.5f)*ADDITIVE_NOISE_SCALE;
                       if (v >=0)
                             if (v <256)
                                gray[i][j] = static_cast<unsigned char>(v);
                             else
                                gray[i][j] = static_cast<unsigned char>(255);
                       else
                             gray[i][j] = static_cast<unsigned char>(0);
                    }
                }
             break;
         case kRGBa32Raster:
             {
                 unsigned char *const* rgba = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                 for (int i=iLow; i<=iHigh; i++)
                    for (int j=jLow; j<=jHigh; j++)
                       for (int k=0; k<3; k++)
                       {
                             float   v = rgba[i][4*j+k] + (rand() - 0.5f)*ADDITIVE_NOISE_SCALE;
                             if (v >=0)
                                if (v <256)
                                   rgba[i][4*j+k] = static_cast<unsigned char>(v);
                                else
                                   rgba[i][4*j+k] = static_cast<unsigned char>(255);
                             else
                                rgba[i][4*j+k] = static_cast<unsigned char>(0);
                       }
             }
             break;
         default:
             break;
     }
 }
void applySaltAndPepperNoise (void)
Definition at line 370 of file patternMatching_main.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kRGBa32Raster, NB_S_N_P_PIXELS, uriVL::R_W_ACCESS, and UNIT_SCALE.
Referenced by myMenu2().
 {
     const ImageRect *rect = gSearchImage->getValidRect();
     const int   iLow = rect->getTop(),
                 iHigh = rect->getBottom(),
                 jLow = rect->getLeft(),
                 jHigh = rect->getRight();
     switch (gSearchImage->getBaseRasterType())
     {
         case kGrayRaster:
             {
                 unsigned char *const* gray = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                 for (int l=0; l<NB_S_N_P_PIXELS; l++)
                 {
                    int i = (int) (iLow + (iHigh-iLow)*rand()*UNIT_SCALE);
                    int j = (int) (jLow + (jHigh-jLow)*rand()*UNIT_SCALE);
                    gray[i][j] = static_cast<unsigned char>(S_N_P_NOISE_SCALE * rand());
                 }
             }
             break;
         case kRGBa32Raster:
             {
                 unsigned char *const* rgba = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                 for (int l=0; l<NB_S_N_P_PIXELS; l++)
                 {
                    int i = static_cast<int>(iLow + (iHigh-iLow)*rand()*UNIT_SCALE);
                    int j = static_cast<int>(jLow + (jHigh-jLow)*rand()*UNIT_SCALE);
                    for (int k=0; k<3; k++)
                       rgba[i][4*j+k] = static_cast<unsigned char>(S_N_P_NOISE_SCALE * rand());
                 }
             }
             break;
         default:
             break;
     }
 }
void cleanupAndQuit (int exitCode)
Definition at line 250 of file patternMatching_main.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), and myMenu3().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
         #if __profile__
                 ProfilerDump("\pProfilerData");
                 ProfilerTerm();
         #endif
     #endif
     std::exit(exitCode);
 }
void handleMiddleDrag (int buttonState, int ix, int iy, int winIndex)
Definition at line 692 of file patternMatching_main.cpp.
References gDragWin, uriVL::RasterImage::getBaseRasterType(), uriVL::RasterImage::getShiftedRaster2D(), gMouseDown, gStartDragX, gStartDragY, uriVL::kGrayRaster, uriVL::kRGBa32Raster, MAX, MIN, myDisplayMain(), uriVL::R_W_ACCESS, and withinBounds().
Referenced by myMouse2().
 {
     if (buttonState == GLUT_DOWN)
     {
         //  If the mouse button was not already pressed down, we start recording
         if (!gMouseDown)
         {
             gMouseDown = true;
             gDragWin = winIndex;
             gStartDragX = ix;
             gStartDragY = iy;
         }
     }
     else        //      buttonState == GLUT_UP
     {
         //      check that the mouse had been dragged from within the same subwindow and
         //      defines a suffficiently large search region.
         if (gMouseDown && withinBounds(ix, iy))
         {
             const int   iLow = MIN(iy, gStartDragY),
                         iHigh = MAX(iy, gStartDragY),
                         jLow = MIN(ix, gStartDragX),
                         jHigh = MAX(ix, gStartDragX);
             //  fill in the selected region with random noise
             switch (gSearchImage->getBaseRasterType())
             {
                 case kGrayRaster:
                     {
                         unsigned char *const* gray = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                         for (int i=iLow; i<=iHigh; i++)
                               for (int j=jLow; j<=jHigh; j++)
                                  gray[i][j] = static_cast<unsigned char>(
                                      S_N_P_NOISE_SCALE * rand());
                     }
                     break;
                 case kRGBa32Raster:
                     {
                         unsigned char *const* rgba = gSearchImage->getShiftedRaster2D(R_W_ACCESS);
                         for (int i=iLow; i<=iHigh; i++)
                               for (int j=jLow; j<=jHigh; j++)
                                  for (int k=0; k<3; k++)
                                     rgba[i][4*j+k] = static_cast<unsigned char>(
                                         S_N_P_NOISE_SCALE * rand());
                     }
                     break;
                 default:
                     break;
             }
         }
         gMouseDown = false;
         gDragWin = -1;
         myDisplayMain();
     }
 }
void handleMouseDrag (int buttonState, int ix, int iy, int winIndex)
Definition at line 633 of file patternMatching_main.cpp.
References gDragWin, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gMouseDown, gSelectedPat, gStartDragX, gStartDragY, kMinSearchDim, LOWER_LEFT, MAX, MIN, myDisplayMain(), performMatching(), uriVL::ImagePoint::setCoordinates(), uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), uriVL::ImageRect::setRect(), UPPER_LEFT, and withinBounds().
Referenced by myMouse0(), and myMouse2().
 {
     if (buttonState == GLUT_DOWN)
     {
         //  If the mouse button was not already pressed down, we start recording
         if (!gMouseDown)
         {
             gMouseDown = true;
             gDragWin = winIndex;
             gStartDragX = ix;
             gStartDragY = iy;
         }
     }
     else        //      buttonState == GLUT_UP
     {
         //      check that the mouse had been dragged from within the same subwindow and
         //      defines a suffficiently large search region.
         if (gMouseDown && withinBounds(ix, iy))
         {
             int theLeft = MIN(ix, gStartDragX),
                 theTop = MIN(iy, gStartDragY),
                 theWidth = MAX(ix, gStartDragX) - theLeft + 1,
                 theHeight = MAX(iy, gStartDragY) - theTop + 1;
             if ((theWidth >= kMinSearchDim) && (theHeight >= kMinSearchDim))
             {
                 //  If the selection was done in the upper-left quadrant, we now have a
                 //  pattern 2D to look for and match
                 if (winIndex == UPPER_LEFT)
                 {
                     ImageRect *patRect = new ImageRect(theLeft, theTop, theWidth, theHeight);
                     gSelectedOrig->setCoordinates(theLeft, theTop);
                     if (gSelectedPat != NULL)
                         delete gSelectedPat;
                     gSelectedPat = new Pattern2D(patRect, gInputImage);
                     gSelectedPat->setFrameColor(0.f, 0.f, 1.f);
                     gSelectedPat->setDrawValidDataFrame(true);
                     delete patRect;
                 }
                 //  If the selection was donw in the lower-left quadrant, then the user has
                 //  selected a search region and we should try to do a match.
                 //  The selected region must be larger than the pattern, though...
                 if ((winIndex == LOWER_LEFT) && (gSelectedPat != NULL) &&
                     (theWidth>gSelectedPat->getWidth()) && (theHeight>gSelectedPat->getHeight()))
                 {
                     gSearchRect->setRect(theLeft, theTop, theWidth - gSelectedPat->getWidth(),
                                          theHeight - gSelectedPat->getHeight());
                     performMatching();
                 }
             }
         }
         gMouseDown = false;
         gDragWin = -1;
         myDisplayMain();
     }
 }
void initializeQTEnvironment (void)
Definition at line 228 of file patternMatching_main.cpp.
Referenced by main().
 {
     #if URIVL_OS_WIN32
         OSErr   anErr = noErr;
         anErr = InitializeQTML(kQTMLNoIdleEvents);
         if (anErr != noErr)
         {
             cerr <<"\pQuickTime is not installed on this computer";
             ExitToShell();
         }
         anErr = EnterMovies();
         if(anErr != noErr)
         {
             cerr <<"\pProblems with EnterMovies, returning errors (exit)";
             ExitToShell();
         }
     #endif
 }
void loadImage (void)
Definition at line 274 of file patternMatching_main.cpp.
References cleanupAndQuit(), color_dir, gColorImage, uriVL::ImageReader::getFrame(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gImageHeight, gImageWidth, gInputImage, gSearchImage, kNbImages, LOWER_LEFT, LOWER_RIGHT, myReader, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     const string colorFilePath = color_dir + "mandrill_256x256.tga";
     ImageReader myReader(const_cast<char*>(colorFilePath.c_str()));
     //-------------------------------------------------------------
     //  We read the color input images from a file
     //-------------------------------------------------------------
     gColorImage = myReader.getFrame(true);
     if (gColorImage ==NULL)
     {
         cout << "Error encountered while reading image file " << colorFilePath << endl;
         cleanupAndQuit(-1);
     }
     gImageWidth = gColorImage->getWidth();
     gImageHeight = gColorImage->getHeight();
     //
     //  The gray image is a gray-level copy of the color image
     gGrayImage = new RasterImage_gray(gColorImage);
     //-------------------------------------------------------------
     //  Initially the search image is a copy of the input image
     //-------------------------------------------------------------
     gInputImage = gColorImage;
     gSearchImage = new RasterImage_RGBa(gColorImage);
     //-------------------------------------------------------------
     //  We allocate the array of display images
     //-------------------------------------------------------------
     gDisplayImage = new RasterImage*[kNbImages];
     gDisplayImage[UPPER_LEFT] = gInputImage;
     gDisplayImage[UPPER_RIGHT] = NULL;
     gDisplayImage[LOWER_LEFT] = gSearchImage;
     gDisplayImage[LOWER_RIGHT] = gSearchImage;
     gBestMatch = new ImagePoint();
 }
int main (int argc, char ** argv)
Definition at line 1097 of file patternMatching_main.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), gImageHeight, gImageWidth, gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myInit(), myKeyboard(), myReshape(), and setupCamera().
 {
         #if __profile__
                 OSErr                                           errProfiler = noErr;
                 ProfilerCollectionMethod        method = collectDetailed;
                 ProfilerTimeBase                        timeBase = bestTimeBase;
                 short                                           numFunctions = 300,
                                                                         stackDepth = 150;
         #endif
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                      myDisplay2, myDisplay3};
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         loadImage();
         //      I initialize my window's dimensions at the default values
         gWinHeight = kNbRowsSubwindows*(gImageHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows*(gImageWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Pattern Matching Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glClearColor(0.0, 1.0, 1.0, 1.0);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(
                                         gMainWindow,
                                         j*(gImageWidth + kBorder) + kBorder,
                                         i*(gImageHeight + kBorder) + kBorder,
                                         gImageWidth,
                                         gImageHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(gImageWidth, gImageHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         //  Inform drawable objects of the dimensions of my rendering windows
         DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
         #if __profile__
                 ProfilerInit(method, timeBase, numFunctions, stackDepth);
                 if (errProfiler != noErr)
                         return 1;
                 ProfilerSetStatus(false);
         #endif
         myInit();
 RasterImage_RGBa *testImg = new RasterImage_RGBa(100, 100);
 RasterImage *testImg2 = testImg;
 string  s1 = typeid(*testImg).name();
 string  s2 = typeid(*testImg2).name();
 cout << "With images: true type is --> " << s1 << endl;
 cout << "             polymorphism type is still --> " << s2 << endl;
 Pattern2DMatchRecord_part *partCorrMatchRec = new Pattern2DMatchRecord_part();
 Pattern2DMatchRecord *partCorrMatchRec2 = partCorrMatchRec;
 string  s3 = typeid(*partCorrMatchRec).name();
 string  s4 = typeid(*partCorrMatchRec2).name();
 cout << "With Pattern2DMatchRecord_part: true type is --> " << s3 << endl;
 cout << "                                polymorphism type is now --> " << s4 << endl;
         glutMainLoop();
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myColorSubmenu (int value)
Definition at line 990 of file patternMatching_main.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 438 of file patternMatching_main.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[0]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[UPPER_LEFT]!= NULL)
     {
         gDisplayImage[UPPER_LEFT]->render(true);
     }
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 454 of file patternMatching_main.cpp.
References gSubwindow, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[1]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gSelectedPat!= NULL)
     {
         gSelectedPat->render(gSelectedOrig);
     }
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 470 of file patternMatching_main.cpp.
References gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[2]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[LOWER_LEFT]!= NULL)
     {
         gDisplayImage[LOWER_LEFT]->render(false);
     }
     glutSwapBuffers();
 }
void myDisplay3 (void)
Definition at line 487 of file patternMatching_main.cpp.
References gMainWindow, gMatchDone, gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[LOWER_RIGHT]!= NULL)
         gDisplayImage[LOWER_RIGHT]->render();
     if (gMatchDone)
         gSelectedPat->render(gBestMatch);
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 421 of file patternMatching_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by handleMiddleDrag(), handleMouseDrag(), main(), myMenu0(), and myMenu2().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
     glutSetWindow(gMainWindow);
 }
void myInit (void)
Definition at line 1007 of file patternMatching_main.cpp.
References COLOR_INPUT_MENU, CORRELATION_MATCHER, GAUSSIAN_NOISE_MENU, gInitDone, gMainWindow, GRAY_INPUT_MENU, gSubwindow, kBckgndColStr, kNbBckgndCols, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, MEDIAN_DIFF_MATCHER, MENU_SEPARATOR, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMouse0(), myMouse2(), myMouseMotion(), PARTIAL_CORR_MATCHER, QUIT_MENU, RESET_IMAGE_MENU, SALT_AND_PEPPER_NOISE_MENU, SCALED_DIFF_MATCHER, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menu[kNbSubwindows], colorSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i], i);
     //------------------------------------
     //  menus for upper-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddMenuEntry("Color input image", COLOR_INPUT_MENU);
     glutAddMenuEntry("Gray-level input image", GRAY_INPUT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutMouseFunc(myMouse0);
     glutMotionFunc(myMouseMotion);
     //------------------------------------
     //  menus for upper-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddMenuEntry("Additive noise", GAUSSIAN_NOISE_MENU);
     glutAddMenuEntry("Salt and pepper noise", SALT_AND_PEPPER_NOISE_MENU);
     glutAddMenuEntry("reset image", RESET_IMAGE_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddMenuEntry("Correlation matcher", CORRELATION_MATCHER);
     glutAddMenuEntry("Scaled centered difference matcher", SCALED_DIFF_MATCHER);
     glutAddMenuEntry("Scaled median difference matcher", MEDIAN_DIFF_MATCHER);
     glutAddMenuEntry("Partial correlation matcher", PARTIAL_CORR_MATCHER);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutMouseFunc(myMouse2);
     glutMotionFunc(myMouseMotion);
     //------------------------------------
     //  menus for lower-right quadrant
     //------------------------------------
     //
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     //
     glutAddMenuEntry("-", MENU_SEPARATOR);
     //
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 545 of file patternMatching_main.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myMenu0 (int value)
Definition at line 884 of file patternMatching_main.cpp.
References cleanupAndQuit(), COLOR_INPUT_MENU, gColorImage, gGrayImage, gMatchDone, GRAY_INPUT_MENU, gSearchImage, gSelectedPat, myDisplayMain(), QUIT_MENU, and UPPER_LEFT.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case COLOR_INPUT_MENU:
             delete gSelectedPat;
             gSelectedPat = NULL;
             gMatchDone = false;
             gDisplayImage[UPPER_LEFT] = gInputImage = gColorImage;
             delete gSearchImage;
             gSearchImage = new RasterImage_RGBa(gInputImage);
             break;
         case GRAY_INPUT_MENU:
             delete gSelectedPat;
             gSelectedPat = NULL;
             gMatchDone = false;
             gDisplayImage[UPPER_LEFT] = gInputImage = gGrayImage;
             delete gSearchImage;
             gSearchImage = new RasterImage_gray(gInputImage);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
     myDisplayMain();
 }
void myMenu1 (int value)
Definition at line 920 of file patternMatching_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 935 of file patternMatching_main.cpp.
References applyAdditiveNoise(), applySaltAndPepperNoise(), cleanupAndQuit(), uriVL::RasterImage::copyInto(), CORRELATION_MATCHER, GAUSSIAN_NOISE_MENU, gMatchDone, gMatchingMode, MEDIAN_DIFF_MATCHER, myDisplayMain(), PARTIAL_CORR_MATCHER, performMatching(), QUIT_MENU, RESET_IMAGE_MENU, SALT_AND_PEPPER_NOISE_MENU, and SCALED_DIFF_MATCHER.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case GAUSSIAN_NOISE_MENU:
             applyAdditiveNoise();
             myDisplayMain();
             break;
         case SALT_AND_PEPPER_NOISE_MENU:
             applySaltAndPepperNoise();
             myDisplayMain();
             break;
         case RESET_IMAGE_MENU:
             gInputImage->copyInto(gSearchImage);
             gMatchDone = false;
             myDisplayMain();
             break;
         case CORRELATION_MATCHER:
         case SCALED_DIFF_MATCHER:
         case MEDIAN_DIFF_MATCHER:
         case PARTIAL_CORR_MATCHER:
             gMatchingMode = value;
             if (gMatchDone)
                 performMatching();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 975 of file patternMatching_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse0 (int button, int buttonState, int ix, int iy)
Definition at line 561 of file patternMatching_main.cpp.
References gSubwindow, handleMouseDrag(), and UPPER_LEFT.
Referenced by myInit().
 {
     if (gDisplayImage[UPPER_LEFT] != NULL)
     {
         glutSetWindow(gSubwindow[UPPER_LEFT]);
         if (button == GLUT_LEFT_BUTTON)
             handleMouseDrag(buttonState, ix, iy, UPPER_LEFT);
     }
 }
void myMouse1 (int button, int buttonState, int ix, int iy)
Definition at line 573 of file patternMatching_main.cpp.
 {
 }
void myMouse2 (int button, int buttonState, int ix, int iy)
Definition at line 578 of file patternMatching_main.cpp.
References gSubwindow, handleMiddleDrag(), handleMouseDrag(), and LOWER_LEFT.
Referenced by myInit().
 {
     if (gDisplayImage[LOWER_LEFT] != NULL)
     {
         glutSetWindow(gSubwindow[LOWER_LEFT]);
         if (button == GLUT_LEFT_BUTTON)
             handleMouseDrag(buttonState, ix, iy, LOWER_LEFT);
         if (button == GLUT_MIDDLE_BUTTON)
             handleMiddleDrag(buttonState, ix, iy, LOWER_LEFT);
     }
 }
void myMouse3 (int button, int buttonState, int ix, int iy)
Definition at line 593 of file patternMatching_main.cpp.
 {
 }
void myMouseMotion (int ix, int iy)
Definition at line 604 of file patternMatching_main.cpp.
References gDragWin, gImageHeight, gMouseDown, gStartDragX, gStartDragY, gSubwindow, uriVL::DrawableObject2D::render(), and withinBounds().
Referenced by myInit().
 {
     if (gMouseDown)
     {
         glutSetWindow(gSubwindow[gDragWin]);
         glClear(GL_COLOR_BUFFER_BIT);
         if (gDisplayImage[gDragWin]!= NULL)
         {
             gDisplayImage[gDragWin]->render();
         }
         if (withinBounds(ix, iy))
         {
             glColor3f(1.0f, 1.0f, 1.0f);
             glBegin(GL_LINE_LOOP);
             glVertex2i(gStartDragX, gImageHeight - 1 -gStartDragY);
             glVertex2i(gStartDragX, gImageHeight - iy - 1);
             glVertex2i(ix, gImageHeight - iy - 1);
             glVertex2i(ix, gImageHeight - 1 - gStartDragY);
             glEnd();
         }
         glutSwapBuffers();
     }
 }
void myReshape (int w, int h)
Definition at line 509 of file patternMatching_main.cpp.
Referenced by main().
 {
     if (gDisplayImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void performMatching (void)
Definition at line 758 of file patternMatching_main.cpp.
References CORRELATION_MATCHER, uriVL::Pattern2DMatchRecord::getBestMatch(), uriVL::Pattern2DMatchRecord_part::getMatchRecord(), uriVL::Pattern2DMatchRecord::getScore(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), gMatchDone, gMatchingMode, uriVL::LOWER_LEFT_QUAD, uriVL::LOWER_RIGHT_QUAD, uriVL::PatternMatcher2D::match(), MEDIAN_DIFF_MATCHER, PARTIAL_CORR_MATCHER, SCALED_DIFF_MATCHER, uriVL::ImagePoint::setCoordinates(), uriVL::UPPER_LEFT_QUAD, and uriVL::UPPER_RIGHT_QUAD.
Referenced by handleMouseDrag(), and myMenu2().
 {
     ImagePoint              *matchPt;
         #if __profile__
                 ProfilerSetStatus(true);
         #endif
     switch(gMatchingMode)
     {
         case CORRELATION_MATCHER:
             {
                 PatternMatcher2D_corr   *corrMatcher = new PatternMatcher2D_corr();
                 Pattern2DMatchRecord    *corrMatchRec = new Pattern2DMatchRecord();
 #if __profile__
 for(int i=0; i<10; i++)
 #endif
                 corrMatcher->match(gSelectedPat, gSearchRect, gSearchImage, corrMatchRec);
                 matchPt = corrMatchRec->getBestMatch();
                 gBestMatch->setCoordinates(matchPt->getX(), matchPt->getY());
                 cout << "Correlation matcher:" << endl << "====================" << endl ;
                 cout << "\tBest match:\t\t<" << matchPt->getX() << ", " << matchPt->getY() <<
                       ">, score = " << corrMatchRec->getScore() << endl << endl;
                 gMatchDone = true;
                 delete corrMatcher;
                 delete corrMatchRec;
             }
             break;
         case SCALED_DIFF_MATCHER:
             {
                 PatternMatcher2D_scaledDiff *scaledDiffMatcher = new PatternMatcher2D_scaledDiff();
                 Pattern2DMatchRecord        *scaledDiffMatchRec = new Pattern2DMatchRecord();
 #if __profile__
 for(int i=0; i<10; i++)
 #endif
                 scaledDiffMatcher->match(gSelectedPat, gSearchRect, gSearchImage,
                     scaledDiffMatchRec);
                 matchPt = scaledDiffMatchRec->getBestMatch();
                 gBestMatch->setCoordinates(matchPt->getX(), matchPt->getY());
                 cout << "Scaled difference matcher:" << endl
                      << "==========================" << endl ;
                 cout << "\tBest match:\t\t<" << matchPt->getX() << ", " << matchPt->getY() <<
                      ">, score = " << scaledDiffMatchRec->getScore() << endl << endl;
                 gMatchDone = true;
                 delete scaledDiffMatcher;
                 delete scaledDiffMatchRec;
             }
             break;
         case MEDIAN_DIFF_MATCHER:
             {
                 PatternMatcher2D_medianDiff *medianDiffMatcher = new PatternMatcher2D_medianDiff();
                 Pattern2DMatchRecord        *medianDiffMatchRec = new Pattern2DMatchRecord();
 #if __profile__
 for(int i=0; i<10; i++)
 #endif
                 medianDiffMatcher->match(gSelectedPat, gSearchRect, gSearchImage,
                     medianDiffMatchRec);
                 matchPt = medianDiffMatchRec->getBestMatch();
                 gBestMatch->setCoordinates(matchPt->getX(), matchPt->getY());
                 cout << "Median difference matcher:" << endl
                       << "==========================" << endl ;
                 cout << "\tBest match:\t\t<" << matchPt->getX() << ", " << matchPt->getY() <<
                          ">, score = " << medianDiffMatchRec->getScore() << endl << endl;
                 gMatchDone = true;
                 delete medianDiffMatcher;
                 delete medianDiffMatchRec;
             }
             break;
         case PARTIAL_CORR_MATCHER:
             {
                 PatternMatcher2D_partCorr *partCorrMatcher = new PatternMatcher2D_partCorr();
                 Pattern2DMatchRecord_part *partCorrMatchRec = new Pattern2DMatchRecord_part();
 #if __profile__
 for(int i=0; i<10; i++)
 #endif
                 partCorrMatcher->match(gSelectedPat, gSearchRect, gSearchImage, partCorrMatchRec);
                 matchPt = static_cast<Pattern2DMatchRecord*>(partCorrMatchRec)->getBestMatch();
                 gBestMatch->setCoordinates(matchPt->getX(), matchPt->getY());
                 cout << "Partial correlation matcher:" << endl
                    << "============================" << endl ;
                 cout << "\tGlobal match:\t<" << matchPt->getX() << ", " << matchPt->getY() <<
                       ">, score = "
                    << static_cast<Pattern2DMatchRecord*>(partCorrMatchRec)->getScore() << endl;
                 //
                 Pattern2DMatchRecord  *quadMatch;
                 quadMatch = partCorrMatchRec->getMatchRecord(UPPER_LEFT_QUAD);
                 cout << "\tUpper-left:\t\t<" << quadMatch->getBestMatch()->getX() <<
                       ", " << quadMatch->getBestMatch()->getY() <<
                       ">, score = " << quadMatch->getScore() << endl;
                 quadMatch = partCorrMatchRec->getMatchRecord(UPPER_RIGHT_QUAD);
                 cout << "\tUpper-right:\t\t<" << quadMatch->getBestMatch()->getX() <<
                       ", " << quadMatch->getBestMatch()->getY() <<
                       ">, score = " << quadMatch->getScore() << endl;
                 quadMatch = partCorrMatchRec->getMatchRecord(LOWER_LEFT_QUAD);
                 cout << "\tLower-left:\t\t<" << quadMatch->getBestMatch()->getX() <<
                       ", " << quadMatch->getBestMatch()->getY() <<
                       ">, score = " << quadMatch->getScore() << endl;
                 quadMatch = partCorrMatchRec->getMatchRecord(LOWER_RIGHT_QUAD);
                 cout << "\tLower-right:\t\t<" << quadMatch->getBestMatch()->getX() <<
                       ", " << quadMatch->getBestMatch()->getY() <<
                       ">, score = " << quadMatch->getScore() << endl << endl;
                 gMatchDone = true;
                 delete partCorrMatcher;
                 delete partCorrMatchRec;
             }
             break;
         default:
             //  do nothing
             break;
      }
         #if __profile__
                 ProfilerSetStatus(false);
         #endif
 }
void setupCamera (int w, int h)
Definition at line 528 of file patternMatching_main.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
bool withinBounds (int ix, int iy)
Definition at line 598 of file patternMatching_main.cpp.
References gImageHeight, and gImageWidth.
Referenced by handleMiddleDrag(), handleMouseDrag(), and myMouseMotion().
 {
     return ((ix>=0) && (ix<gImageWidth) &&
             (iy>=0) && (iy<gImageHeight));
 }
Variable Documentation
const float ADDITIVE_NOISE_RANGE = 20.f
Definition at line 215 of file patternMatching_main.cpp.
const float ADDITIVE_NOISE_SCALE = (2*ADDITIVE_NOISE_RANGE)/(RAND_MAX + 1.f)
Definition at line 219 of file patternMatching_main.cpp.
Referenced by applyAdditiveNoise().
const int COLOR_INPUT_MENU = 100
Definition at line 112 of file patternMatching_main.cpp.
Referenced by myInit(), and myMenu0().
const int CORRELATION_MATCHER = 50
Definition at line 120 of file patternMatching_main.cpp.
Referenced by myInit(), myMenu2(), and performMatching().
const string filePath = color_dir + "mandrill_256x256.tga"
Definition at line 87 of file patternMatching_main.cpp.
const int GAUSSIAN_NOISE_MENU = 10
Definition at line 115 of file patternMatching_main.cpp.
Referenced by myInit(), and myMenu2().
ImagePoint* gBestMatch
Definition at line 186 of file patternMatching_main.cpp.
RasterImage* gColorImage = NULL
Definition at line 179 of file patternMatching_main.cpp.
Referenced by loadImage(), and myMenu0().
RasterImage** gDisplayImage = NULL
Definition at line 182 of file patternMatching_main.cpp.
int gDragWin
Definition at line 192 of file patternMatching_main.cpp.
Referenced by handleMiddleDrag(), handleMouseDrag(), and myMouseMotion().
RasterImage* gGrayImage = NULL
Definition at line 178 of file patternMatching_main.cpp.
Referenced by myMenu0().
int gImageHeight = kDefaultHeight
Definition at line 171 of file patternMatching_main.cpp.
Referenced by loadImage(), main(), myMouseMotion(), and withinBounds().
int gImageWidth = kDefaultWidth
Definition at line 170 of file patternMatching_main.cpp.
Referenced by loadImage(), main(), and withinBounds().
bool gInitDone = false
Definition at line 176 of file patternMatching_main.cpp.
Referenced by myInit().
RasterImage* gInputImage = NULL
Definition at line 180 of file patternMatching_main.cpp.
Referenced by loadImage().
int gMainWindow
Definition at line 173 of file patternMatching_main.cpp.
Referenced by main(), myColorSubmenu(), myDisplay3(), myDisplayMain(), and myInit().
bool gMatchDone = false
Definition at line 187 of file patternMatching_main.cpp.
Referenced by myDisplay3(), myMenu0(), myMenu2(), and performMatching().
int gMatchingMode = CORRELATION_MATCHER
Definition at line 195 of file patternMatching_main.cpp.
Referenced by myMenu2(), and performMatching().
bool gMouseDown = false
Definition at line 191 of file patternMatching_main.cpp.
Referenced by handleMiddleDrag(), handleMouseDrag(), and myMouseMotion().
const int GRAY_INPUT_MENU = 110
Definition at line 113 of file patternMatching_main.cpp.
Referenced by myInit(), and myMenu0().
RasterImage* gSearchImage = NULL
Definition at line 181 of file patternMatching_main.cpp.
Referenced by loadImage(), and myMenu0().
ImageRect* gSearchRect = new ImageRect(0, 0, 0, 0)
Definition at line 183 of file patternMatching_main.cpp.
ImagePoint* gSelectedOrig = new ImagePoint(0, 0)
Definition at line 185 of file patternMatching_main.cpp.
Pattern2D* gSelectedPat = NULL
Definition at line 184 of file patternMatching_main.cpp.
Referenced by handleMouseDrag(), and myMenu0().
int gStartDragX
Definition at line 193 of file patternMatching_main.cpp.
Referenced by handleMiddleDrag(), handleMouseDrag(), and myMouseMotion().
int gStartDragY
Definition at line 193 of file patternMatching_main.cpp.
Referenced by handleMiddleDrag(), handleMouseDrag(), and myMouseMotion().
int gSubwindow[kNbSubwindows]
Definition at line 173 of file patternMatching_main.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myInit(), myMouse0(), myMouse2(), and myMouseMotion().
int gWinHeight
Definition at line 168 of file patternMatching_main.cpp.
Referenced by main().
int gWinWidth
Definition at line 168 of file patternMatching_main.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                                 }
Definition at line 201 of file patternMatching_main.cpp.
Referenced by main(), and myColorSubmenu().
char* kBckgndColStr[]
Initial value:
=       {
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Black",
                                "Cyan"
                            }
Definition at line 207 of file patternMatching_main.cpp.
Referenced by myInit().
const int kMinSearchDim = 11
Definition at line 189 of file patternMatching_main.cpp.
Referenced by handleMouseDrag().
const int LOWER_LEFT = 2
Definition at line 106 of file patternMatching_main.cpp.
Referenced by handleMouseDrag(), loadImage(), myDisplay2(), myInit(), and myMouse2().
const int LOWER_RIGHT = 3
Definition at line 107 of file patternMatching_main.cpp.
Referenced by loadImage(), myDisplay3(), and myInit().
const int MATCHER_BASE = 50
Definition at line 119 of file patternMatching_main.cpp.
const int MEDIAN_DIFF_MATCHER = 52
Definition at line 122 of file patternMatching_main.cpp.
Referenced by myInit(), myMenu2(), and performMatching().
const int MENU_SEPARATOR = -1
Definition at line 109 of file patternMatching_main.cpp.
Referenced by myInit().
const int NB_S_N_P_PIXELS = 300
Definition at line 217 of file patternMatching_main.cpp.
Referenced by applySaltAndPepperNoise().
const int PARTIAL_CORR_MATCHER = 53
Definition at line 123 of file patternMatching_main.cpp.
Referenced by myInit(), myMenu2(), and performMatching().
const int QUIT_MENU = 0
Definition at line 110 of file patternMatching_main.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), and myMenu3().
const int RESET_IMAGE_MENU = 30
Definition at line 117 of file patternMatching_main.cpp.
Referenced by myInit(), and myMenu2().
const float S_N_P_NOISE_RANGE = 255.f
Definition at line 216 of file patternMatching_main.cpp.
const float S_N_P_NOISE_SCALE = S_N_P_NOISE_RANGE/(RAND_MAX + 1.f)
Definition at line 220 of file patternMatching_main.cpp.
const int SALT_AND_PEPPER_NOISE_MENU = 20
Definition at line 116 of file patternMatching_main.cpp.
Referenced by myInit(), and myMenu2().
const int SCALED_DIFF_MATCHER = 51
Definition at line 121 of file patternMatching_main.cpp.
Referenced by myInit(), myMenu2(), and performMatching().
const float UNIT_SCALE = 1.f/(RAND_MAX + 1.f)
Definition at line 221 of file patternMatching_main.cpp.
Referenced by applySaltAndPepperNoise().
const int UPPER_LEFT = 0
Definition at line 104 of file patternMatching_main.cpp.
Referenced by handleMouseDrag(), loadImage(), myDisplay0(), myInit(), myMenu0(), and myMouse0().
const int UPPER_RIGHT = 1
Definition at line 105 of file patternMatching_main.cpp.
Referenced by loadImage(), and myInit().