URIVisionLibrary: videoGrabbing_main.cpp File Reference
videoGrabbing_main.cpp File Reference
#include <string>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ErrorReport.h"
#include "RasterImage.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray.h"
#include "FrameGrabber.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define READ_IN_GRAY_IMAGE 0
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void myDisplay (void)
void setupOrthoCam (int w, int h)
void myIdle (void)
void myReshape (int w, int h)
void myKeyboard (unsigned char c, int x, int y)
void initializeApplication (void)
void initGlut (void)
int main (int argc, char **argv)
Variables
const int IMG_WIDTH = 640
const int IMG_HEIGHT = 480
long gFrameIndex = 0
ImageRect * gMyRect = NULL
FrameGrabber * gMyGrabber = NULL
bool gInitDone = false
RasterImage_RGBa * gInputImage = NULL
Macro Definition Documentation
#define READ_IN_GRAY_IMAGE 0
Definition at line 57 of file videoGrabbing_main.cpp.
#define READ_IN_RGB_IMAGE 0
Definition at line 56 of file videoGrabbing_main.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 55 of file videoGrabbing_main.cpp.
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 154 of file videoGrabbing_main.cpp.
Referenced by main(), and myKeyboard().
 {
         #if URIVL_USE_QUICKTIME
             // terminate the QuickTime Media Layer
             ExitMovies();
             #if URIVL_OS_WIN32
                 TerminateQTML();
             #endif
         #endif
     std::exit(exitCode);
 }
void initGlut (void)
Definition at line 303 of file videoGrabbing_main.cpp.
References IMG_HEIGHT, IMG_WIDTH, myDisplay(), myIdle(), myKeyboard(), myReshape(), and setupOrthoCam().
Referenced by main().
 {
                 glClearColor(0.f, 0.f, 0.f, 1.f);
                 glutDisplayFunc(myDisplay);
                 setupOrthoCam(IMG_WIDTH, IMG_HEIGHT);
                 glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
                 glutKeyboardFunc(myKeyboard);
 }
void initializeApplication (void)
Definition at line 284 of file videoGrabbing_main.cpp.
References gMyGrabber, IMG_HEIGHT, IMG_WIDTH, and uriVL::DrawableObject2D::setValidRect().
Referenced by main().
 {
         ImageRect imgRect(0, 0, IMG_WIDTH, IMG_HEIGHT);
         #if READ_IN_RGBA_IMAGE
                 gInputImage = new RasterImage_RGBa(&imgRect);
         #elif READ_IN_RGB_IMAGE
                 gInputImage = new RasterImage_RGB(&imgRect);
         #else READ_IN_GRAY_IMAGE
                 gInputImage = new RasterImage_gray(&imgRect);
         #endif
         gInputImage->setValidRect(&imgRect);
         gMyGrabber = new FrameGrabber(&imgRect);
         gMyGrabber->setSource();
 }
void initializeQTEnvironment (void)
Definition at line 125 of file videoGrabbing_main.cpp.
References FAIL_CONDITION, uriVL::kEnterMoviesError, and uriVL::kQuickTimeNotInstalled.
Referenced by main().
 {
         #if URIVL_USE_QUICKTIME
                 printf("using quicktime\n");
             OSErr       myErr = noErr;
             #if URIVL_OS_WIN32
                 myErr = InitializeQTML(kQTMLNoIdleEvents);
             #else
                 #if URIVL_OS_MACOS
                     long        myAttrs;
                     myErr = Gestalt(gestaltQuickTime, &myAttrs);
                 #endif
             #endif
             FAIL_CONDITION(     myErr != noErr,
                             kQuickTimeNotInstalled,
                             "QuickTime is not installed on this computer");
             myErr = EnterMovies();
             FAIL_CONDITION(     myErr != noErr,
                             kEnterMoviesError,
                             "Problems with EnterMovies, returning errors (exit)");
          #else
                 //do nothing?
          #endif
 }
int main (int argc, char ** argv)
Definition at line 317 of file videoGrabbing_main.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), gMyGrabber, IMG_HEIGHT, IMG_WIDTH, initGlut(), initializeApplication(), and initializeQTEnvironment().
 {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH);
     try {
                 initializeQTEnvironment();
                 glutInitWindowSize(IMG_WIDTH, IMG_HEIGHT);
                 glutCreateWindow("Video Capture Demo");
                 initGlut();
                 initializeApplication();
                 gMyGrabber->start();
                 glutMainLoop();
                 cleanupAndQuit(0);
                 return 0;
         }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myDisplay (void)
Definition at line 199 of file videoGrabbing_main.cpp.
References gFrameIndex, and uriVL::DrawableObject2D::render().
Referenced by initGlut().
 {
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     if (gFrameIndex>0)
     {
         gInputImage->render( );
     }
     glutSwapBuffers();
 }
void myIdle (void)
Definition at line 182 of file videoGrabbing_main.cpp.
References gFrameIndex, and gMyGrabber.
Referenced by initGlut().
 {
     gMyGrabber->getFrame(gInputImage);
         gFrameIndex++;
 cout << "frame " << gFrameIndex << endl;
         //  do something cool
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 260 of file videoGrabbing_main.cpp.
References cleanupAndQuit().
Referenced by initGlut().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
     }
     //    glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 240 of file videoGrabbing_main.cpp.
References IMG_HEIGHT, IMG_WIDTH, and setupOrthoCam().
Referenced by initGlut().
 {
         if ((w != IMG_WIDTH) || (h != IMG_HEIGHT))
                 glutReshapeWindow(IMG_WIDTH, IMG_HEIGHT);
         setupOrthoCam(w, h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
     DrawableObject2D::setDefaultWindowDimensions(w, h);
 }
void setupOrthoCam (int w, int h)
Definition at line 224 of file videoGrabbing_main.cpp.
Referenced by initGlut(), and myReshape().
 {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glViewport(0, 0, w, h);
 }
Variable Documentation
long gFrameIndex = 0
Definition at line 102 of file videoGrabbing_main.cpp.
Referenced by myDisplay(), and myIdle().
bool gInitDone = false
Definition at line 105 of file videoGrabbing_main.cpp.
RasterImage_RGBa* gInputImage = NULL
Definition at line 108 of file videoGrabbing_main.cpp.
FrameGrabber* gMyGrabber = NULL
Definition at line 104 of file videoGrabbing_main.cpp.
Referenced by initializeApplication(), main(), and myIdle().
ImageRect* gMyRect = NULL
Definition at line 103 of file videoGrabbing_main.cpp.
const int IMG_HEIGHT = 480
Definition at line 77 of file videoGrabbing_main.cpp.
Referenced by initGlut(), initializeApplication(), main(), and myReshape().
const int IMG_WIDTH = 640
Definition at line 76 of file videoGrabbing_main.cpp.
Referenced by initGlut(), initializeApplication(), main(), and myReshape().