URIVisionLibrary: warping_main.cpp File Reference
warping_main.cpp File Reference
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_RGBa_F.h"
#include "ImageWarper_GL.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 1
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 900
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void initImagesAndWarper (void)
void setupWarper (void)
void applyWarp (void)
void resetGrid (void)
void deleteGrids (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void precalcCircle (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myColorSubmenu (int value)
void myGridSizeMenu (int value)
void myMouse (int button, int buttonState, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int QUIT_MENU = 0
const int RESET_MENU = 1
const int SEPARATOR = 1000
const int FOUR_BY_FOUR_GRID = 404
const int FOUR_BY_SIX_GRID = 406
const int FIVE_BY_FIVE_GRID = 505
const int SIX_BY_FOUR_GRID = 604
const int SIX_BY_SIX_GRID = 606
GLfloat kBackgroundColor [kNbBckgndCols][4]
char * kBckgndColStr []
RasterImage * gImgIn = NULL
RasterImage * gImgOut = NULL
int gImgWidth
int gImgHeight
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
GLfloat ** gCirclePt
const int gNbCirclePts = 12
const GLfloat gGridPtColor [4] = {0.f, 0.f, 1.f, 1.f}
const GLfloat gActivePtColor [4] = {1.f, 0.f, 0.f, 1.f}
int gSelectedPtRow = -1
int gSelectedPtCol = -1
ImageWarper_GL * gWarper = NULL
InnerWarpingMode gInnerMode = INNER_FREE
BorderWarpingMode gBorderMode = BORDER_FIXED
int gGridRows = 5
int gGridCols = 5
float *** gGridPoint = NULL
float *** gInitGridPoint = NULL
Macro Definition Documentation
#define kBorder 8
Definition at line 72 of file warping_main.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 73 of file warping_main.cpp.
Referenced by main().
#define kDefaultWidth 256
Definition at line 74 of file warping_main.cpp.
Referenced by main().
#define kMaxWindowHeight 900
Definition at line 76 of file warping_main.cpp.
#define kMaxWindowWidth 900
Definition at line 75 of file warping_main.cpp.
#define kNbBckgndCols 5
Definition at line 128 of file warping_main.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 68 of file warping_main.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 70 of file warping_main.cpp.
#define kNbRowsSubwindows 1
Definition at line 67 of file warping_main.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 69 of file warping_main.cpp.
Referenced by main(), and myInit().
Function Documentation
void applyWarp (void)
Definition at line 286 of file warping_main.cpp.
References gGridPoint, gSubwindow, UPPER_RIGHT, and uriVL::ImageWarper::warp().
Referenced by main(), myMouse(), and resetGrid().
 {
 //    glutSetWindow(gSubwindow[UPPER_LEFT]);
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
         gWarper->warp(gGridPoint);
 }
void cleanupAndQuit (int exitCode)
Definition at line 195 of file warping_main.cpp.
Referenced by initImagesAndWarper(), main(), myKeyboard(), myMenu0(), myMenu1(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void deleteGrids (void)
Definition at line 306 of file warping_main.cpp.
References gGridCols, gGridPoint, gGridRows, and gInitGridPoint.
Referenced by myGridSizeMenu().
 {
     //  if we already previously set a grid, we need to delete it
     if (gGridPoint != NULL)
     {
         for (int i=0; i<gGridRows; i++)
         {
             for (int j=0; j<gGridCols; j++)
             {
                 delete []gGridPoint[i][j];
                 delete []gInitGridPoint[i][j];
             }
             delete []gGridPoint[i];
             delete []gInitGridPoint[i];
         }
         delete []gGridPoint;
         delete []gInitGridPoint;
     }
     gGridPoint = gInitGridPoint = NULL;
 }
void initializeQTEnvironment (void)
Definition at line 171 of file warping_main.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void initImagesAndWarper (void)
Definition at line 210 of file warping_main.cpp.
References uriVL::BORDER_FIXED, cleanupAndQuit(), color_dir, filePath, gBorderMode, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageReader::getFrame(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageWarper_GL::getImageSuitableDimensions(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), gImgOut, gInnerMode, uriVL::INNER_FREE, uriVL::kRGBa32Raster, myReader, uriVL::DrawableObject2D::setValidRect(), and uriVL::RasterImage::writeInto().
Referenced by main().
 {
     //-------------------------------------------------------------
     //  We read an image from a file
     //-------------------------------------------------------------
     const string filePath = color_dir + "bottles_256x256.tga";
 //    const string filePath = color_dir + "mandrill_256x256.tga";
 //    const string filePath = color_dir + "warpedMandrill_256x256.tga";
     ImageReader myReader(const_cast<char *>(filePath.c_str()));
     RasterImage *tempImage = myReader.getFrame(true);
     if (tempImage ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath << endl;
         cleanupAndQuit(-1);
     }
     const BaseRasterType imgType = tempImage->getBaseRasterType();
     if (imgType != kRGBa32Raster)
     {
         cout << "This demo only takes RGBA32 color images" << endl;
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Create the warper
     //-------------------------------------------------------------
     //  Initially the warper has fixed border nodes and free-moving
     //  inner nodes
     gInnerMode = INNER_FREE;
     gBorderMode = BORDER_FIXED;
     gWarper = new ImageWarper_GL(gInnerMode, gBorderMode);
     //  we find out which image dimensions are recommended by the warper (closest
     //  to the input image's dimensions)
     int imgHeight = tempImage->getHeight(),
         imgWidth = tempImage->getWidth();
     int loWidth, hiWidth, loHeight, hiHeight;
     gWarper->getImageSuitableDimensions(imgWidth, imgHeight, &loWidth, &loHeight,
                                         &hiWidth, &hiHeight);
     //  for this demo I don't mind chopping a few pixels off the right and bottom
     //  edges of my image, so if the "low" values are at least 90% of the input
     //  I keep them
     if (10*loWidth >= 9*imgWidth)
         imgWidth = loWidth;
     else
         imgWidth = hiWidth;
     if (10*loHeight >= 9*imgHeight)
         imgHeight = loHeight;
     else
         imgHeight = loHeight;
         //  Now we can copy (part of) the temporary image into the input image
         ImageRect myRect(0, 0, imgWidth, imgHeight),
                   *trueRect = ImageRect::intersection(&myRect, tempImage->getValidRect());
         gImgIn = new RasterImage_RGBa(imgHeight, imgWidth);
         gImgOut = new RasterImage_RGBa(imgHeight, imgWidth);
         gImgIn->setValidRect(&myRect);
         gImgOut->setValidRect(&myRect);
         tempImage->writeInto(gImgIn, trueRect);
         delete trueRect;
 }
int main (int argc, char ** argv)
Definition at line 766 of file warping_main.cpp.
References applyWarp(), cleanupAndQuit(), uriVL::RasterImage::getBytesPerRow(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), gImgHeight, gImgWidth, gMainWindow, gSubwindow, initializeQTEnvironment(), initImagesAndWarper(), kBackgroundColor, kBorder, kDefaultHeight, kDefaultWidth, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, myDisplay0(), myDisplay1(), myDisplayMain(), myInit(), myKeyboard(), myReshape(), precalcCircle(), setupCamera(), and setupWarper().
 {
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1};
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH);
         initializeQTEnvironment();
         //  It's a bit of a hack.  Right now I use the window's back buffer for my warper so I need
         //  to have a window already created when I activate the warper.  I resize the window
         //  later when I know the image's dimensions
         glutInitWindowSize(kDefaultWidth, kDefaultHeight);
         gMainWindow = glutCreateWindow("Background Remover Demo");
         //      I load my image and initialize my warper
         initImagesAndWarper();
         gImgHeight = gImgIn->getHeight();
         gImgWidth = (gImgIn->getBytesPerRow())/4;
         //      I inform all drawable objects of the dimensions of their subwindow
         DrawableObject2D::setDefaultWindowDimensions(gImgWidth, gImgHeight);
         //      I initialize my window's dimensions
         int winHeight = kNbRowsSubwindows * (gImgHeight + kBorder) + kBorder;
         int winWidth = kNbColsSubwindows * (gImgWidth + kBorder) + kBorder;
         glutSetWindow(gMainWindow);
         glutReshapeWindow(winWidth, winHeight);
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glClearColor(0.f, 0.f, 0.f, 1.f);
         int     winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(gImgWidth + kBorder) + kBorder,
                                                         i*(gImgHeight + kBorder) + kBorder,
                                                         gImgWidth, gImgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(gImgWidth, gImgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         precalcCircle();
         //  set up the warper
         setupWarper();
         //  apply a first warping into the output image
         applyWarp();
         myDisplayMain();
         glutMainLoop();
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myColorSubmenu (int value)
Definition at line 640 of file warping_main.cpp.
References gMainWindow, kBackgroundColor, kNbBckgndCols, and myDisplay0().
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         myDisplay0();
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 353 of file warping_main.cpp.
References gActivePtColor, gCirclePt, gGridCols, gGridPtColor, gGridRows, gImgHeight, gInitDone, gInitGridPoint, gMainWindow, gNbCirclePts, gSelectedPtCol, gSelectedPtRow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), myColorSubmenu(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gImgIn->render();
         //  then overlay the warping grid
         glColor4f(0.f, 0.f, 0.f, 1.f);
         for (int i=0; i<gGridRows; i++)
         {
             glBegin(GL_LINE_STRIP);
                 for (int j=0; j<gGridCols; j++)
                     glVertex2f(gInitGridPoint[i][j][0], gImgHeight - gInitGridPoint[i][j][1]);
             glEnd();
          }
         for (int j=0; j<gGridCols; j++)
         {
             glBegin(GL_LINE_STRIP);
                 for (int i=0; i<gGridRows; i++)
                     glVertex2f(gInitGridPoint[i][j][0], gImgHeight - gInitGridPoint[i][j][1]);
             glEnd();
         }
         //  and the grid points as circles
         for (int i=0; i<gGridRows; i++)
         {
             for (int j=0; j<gGridCols; j++)
             {
                 glPushMatrix();
                 glTranslatef(gInitGridPoint[i][j][0], gImgHeight - gInitGridPoint[i][j][1], 0.f);
                 if ((i!=gSelectedPtRow) || (j!=gSelectedPtCol))
                     glColor4f(gGridPtColor[0], gGridPtColor[1], gGridPtColor[2], gGridPtColor[3]);
                 else
                     glColor4f(gActivePtColor[0], gActivePtColor[1], gActivePtColor[2], gActivePtColor[3]);
                 glScalef(4.f, 4.f, 1.f);
                 glBegin(GL_POLYGON);
                     for (int k=0; k<gNbCirclePts; k++)
                         glVertex2fv(gCirclePt[k]);
                 glEnd();
                 glPopMatrix();
             }
         }
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 408 of file warping_main.cpp.
References gActivePtColor, gCirclePt, gGridCols, gGridPoint, gGridPtColor, gGridRows, gImgHeight, gImgOut, gInitDone, gMainWindow, gNbCirclePts, gSelectedPtCol, gSelectedPtRow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         //  render the warped image
         gImgOut->render();
         //  then overlay the warping grid
         glColor4f(0.f, 0.f, 0.f, 1.f);
         for (int i=0; i<gGridRows; i++)
         {
             glBegin(GL_LINE_STRIP);
                 for (int j=0; j<gGridCols; j++)
                     glVertex2f(gGridPoint[i][j][0], gImgHeight - gGridPoint[i][j][1]);
             glEnd();
          }
         for (int j=0; j<gGridCols; j++)
         {
             glBegin(GL_LINE_STRIP);
                 for (int i=0; i<gGridRows; i++)
                     glVertex2f(gGridPoint[i][j][0], gImgHeight - gGridPoint[i][j][1]);
             glEnd();
         }
         //  and the grid points as circles
         for (int i=0; i<gGridRows; i++)
         {
             for (int j=0; j<gGridCols; j++)
             {
                 glPushMatrix();
                 glTranslatef(gGridPoint[i][j][0], gImgHeight - gGridPoint[i][j][1], 0.f);
                 if ((i!=gSelectedPtRow) || (j!=gSelectedPtCol))
                     glColor4f(gGridPtColor[0], gGridPtColor[1], gGridPtColor[2], gGridPtColor[3]);
                 else
                     glColor4f(gActivePtColor[0], gActivePtColor[1], gActivePtColor[2], gActivePtColor[3]);
                 glScalef(4.f, 4.f, 1.f);
                 glBegin(GL_POLYGON);
                     for (int k=0; k<gNbCirclePts; k++)
                         glVertex2fv(gCirclePt[k]);
                 glEnd();
                 glPopMatrix();
             }
         }
 //        glColor4f(1.f, 1.f, 1.f, 1.f);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 339 of file warping_main.cpp.
References gMainWindow, myDisplay0(), and myDisplay1().
Referenced by main(), myMouse(), and resetGrid().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClearColor(0, 0, 0, 1);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
 }
void myGridSizeMenu (int value)
Definition at line 657 of file warping_main.cpp.
References deleteGrids(), FIVE_BY_FIVE_GRID, FOUR_BY_FOUR_GRID, FOUR_BY_SIX_GRID, gGridCols, gGridRows, setupWarper(), SIX_BY_FOUR_GRID, and SIX_BY_SIX_GRID.
Referenced by myInit().
 {
     switch (value)
     {
         case FOUR_BY_FOUR_GRID:
             if ((gGridRows != 4) || (gGridCols != 4))
                 deleteGrids();
             gGridRows = 4;
             gGridCols = 4;
             setupWarper();
             break;
         case FOUR_BY_SIX_GRID:
             if ((gGridRows != 4) || (gGridCols != 6))
                 deleteGrids();
             gGridRows = 4;
             gGridCols = 6;
             setupWarper();
             break;
         case FIVE_BY_FIVE_GRID:
             if ((gGridRows != 5) || (gGridCols != 5))
                 deleteGrids();
             gGridRows = 5;
             gGridCols = 5;
             setupWarper();
             break;
         case SIX_BY_FOUR_GRID:
             if ((gGridRows != 6) || (gGridCols != 4))
                 deleteGrids();
             gGridRows = 6;
             gGridCols = 4;
             setupWarper();
             break;
         case SIX_BY_SIX_GRID:
             if ((gGridRows != 6) || (gGridCols != 6))
                 deleteGrids();
             gGridRows = 6;
             gGridCols = 6;
             setupWarper();
             break;
         default:
             break;
     }
 }
void myInit (void)
Definition at line 706 of file warping_main.cpp.
References FOUR_BY_FOUR_GRID, FOUR_BY_SIX_GRID, gInitDone, gMainWindow, gSubwindow, kBckgndColStr, kNbBckgndCols, kNbSubwindows, myColorSubmenu(), myGridSizeMenu(), myMenu0(), myMenu1(), myMenuMain(), myMouse(), QUIT_MENU, RESET_MENU, SEPARATOR, SIX_BY_FOUR_GRID, SIX_BY_SIX_GRID, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu,
         gridSizeMenu /*, innerGridMoveMenu, borderGridMoveMenu*/;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.f, 0.f, 0.f, 1.f);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i], i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //---------------------------------------
     //  Left subwindow
     //---------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     gridSizeMenu = glutCreateMenu(myGridSizeMenu);
     glutAddMenuEntry("4x4", FOUR_BY_FOUR_GRID);
     glutAddMenuEntry("4x6", FOUR_BY_SIX_GRID);
     glutAddMenuEntry("5x5", FOUR_BY_FOUR_GRID);
     glutAddMenuEntry("6x4", SIX_BY_FOUR_GRID);
     glutAddMenuEntry("6x6", SIX_BY_SIX_GRID);
     //
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Reset Images", RESET_MENU);
     glutAddSubMenu("Grid dimensions", gridSizeMenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //---------------------------------------
     //  Right subwindow
     //---------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glutMouseFunc(myMouse);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 576 of file warping_main.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 606 of file warping_main.cpp.
References cleanupAndQuit(), QUIT_MENU, RESET_MENU, and resetGrid().
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case RESET_MENU:
             resetGrid();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 625 of file warping_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 591 of file warping_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse (int button, int buttonState, int ix, int iy)
Definition at line 517 of file warping_main.cpp.
References applyWarp(), gGridCols, gGridPoint, gGridRows, gSelectedPtCol, gSelectedPtRow, uriVL::ImageWarper::isValidDisplacement(), and myDisplayMain().
Referenced by myInit().
 {
     if ((button == GLUT_LEFT_BUTTON) && (buttonState == GLUT_UP))
     {
         //  if no point was previously selected, this mouse click is used to
         //  select a new point
         if ((gSelectedPtRow == -1) && (gSelectedPtCol == -1))
         {
             //  did the user click on one of the active points?
             bool  pointClicked = false;
             gSelectedPtRow = gSelectedPtCol = -1;
             for (int i=1; (i<gGridRows-1) && !pointClicked; i++)
             {
                 for (int j=1; (j<gGridCols-1) && !pointClicked; j++)
                 {
                     float   dx = ix - gGridPoint[i][j][0],
                             dy = iy - gGridPoint[i][j][1],
                             dist2 = dx*dx + dy*dy;
                     if (dist2 < 25)
                     {
                         pointClicked = true;
                         gSelectedPtRow = i;
                         gSelectedPtCol = j;
                     }
                 }
             }
         }
         //  otherwise, the location of the mouse click gives the new coordinates of
         //  the grid point
         else
         {
             float   tempX = gGridPoint[gSelectedPtRow][gSelectedPtCol][0],
                     tempY = gGridPoint[gSelectedPtRow][gSelectedPtCol][1];
             gGridPoint[gSelectedPtRow][gSelectedPtCol][0] = ix;
             gGridPoint[gSelectedPtRow][gSelectedPtCol][1] = iy;
             //  if this is a valid displacement, proceed
             if (gWarper->isValidDisplacement(gGridPoint))
             {
                 //  Note that the warper performs again the above validity test.  We only do it
                 //  it so that we can restore the grid to a correct state if the displacement
                 //  was not valid
                 applyWarp();
             }
             //  otherwise restore grid point values and ignore
             else
             {
                 gGridPoint[gSelectedPtRow][gSelectedPtCol][0] = tempX;
                 gGridPoint[gSelectedPtRow][gSelectedPtCol][1] = tempY;
             }
             //  in any case, deselect the point
             gSelectedPtRow = gSelectedPtCol = -1;
         }
     }
     myDisplayMain();
 }
void myReshape (int w, int h)
Definition at line 485 of file warping_main.cpp.
References gInitDone.
Referenced by main().
 {
     if (gInitDone)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void precalcCircle (void)
Definition at line 468 of file warping_main.cpp.
References gCirclePt, gNbCirclePts, and PI_F.
Referenced by main().
 {
     gCirclePt = new GLfloat*[gNbCirclePts];
     for (int k=0; k<gNbCirclePts; k++)
     {
         gCirclePt[k] = new GLfloat[2];
         float theta = 2*PI_F*k/gNbCirclePts;
         gCirclePt[k][0] = cosf(theta);
         gCirclePt[k][1] = sinf(theta);
     }
 }
void resetGrid (void)
Definition at line 293 of file warping_main.cpp.
References applyWarp(), gGridCols, gGridPoint, gGridRows, gInitGridPoint, and myDisplayMain().
Referenced by myMenu0().
 {
     for (int i=0; i<gGridRows; i++)
         for (int j=0; j<gGridCols; j++)
         {
             gGridPoint[i][j][0] = gInitGridPoint[i][j][0];
             gGridPoint[i][j][1] = gInitGridPoint[i][j][1];
         }
     applyWarp();
     myDisplayMain();
 }
void setupCamera (int w, int h)
Definition at line 504 of file warping_main.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupWarper (void)
Definition at line 273 of file warping_main.cpp.
References gGridCols, gGridPoint, gGridRows, gImgOut, gInitGridPoint, gSubwindow, uriVL::ImageWarper::newWarpingGrid(), uriVL::ImageWarper_GL::setGrid(), uriVL::ImageWarper_GL::setImages(), and UPPER_RIGHT.
Referenced by main(), and myGridSizeMenu().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     gWarper->setImages(gImgIn, gImgOut);
     gWarper->setGrid(gGridRows, gGridCols);
     //  ask the warper for a grid of points to work with
     //  We only need gGridPoint to perform the warp, but we also get a copy to store
     //  the initial configuration, to use for our display.
     gGridPoint = gWarper->newWarpingGrid();
     gInitGridPoint = gWarper->newWarpingGrid();
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 61 of file warping_main.cpp.
Referenced by initImagesAndWarper().
const int FIVE_BY_FIVE_GRID = 505
Definition at line 124 of file warping_main.cpp.
Referenced by myGridSizeMenu().
const int FOUR_BY_FOUR_GRID = 404
Definition at line 122 of file warping_main.cpp.
Referenced by myGridSizeMenu(), and myInit().
const int FOUR_BY_SIX_GRID = 406
Definition at line 123 of file warping_main.cpp.
Referenced by myGridSizeMenu(), and myInit().
const GLfloat gActivePtColor[4] = {1.f, 0.f, 0.f, 1.f}
Definition at line 155 of file warping_main.cpp.
Referenced by myDisplay0(), and myDisplay1().
BorderWarpingMode gBorderMode = BORDER_FIXED
Definition at line 161 of file warping_main.cpp.
Referenced by initImagesAndWarper().
GLfloat** gCirclePt
Definition at line 152 of file warping_main.cpp.
Referenced by myDisplay0(), myDisplay1(), and precalcCircle().
int gGridCols = 5
Definition at line 163 of file warping_main.cpp.
Referenced by deleteGrids(), myDisplay0(), myDisplay1(), myGridSizeMenu(), myMouse(), resetGrid(), and setupWarper().
float*** gGridPoint = NULL
Definition at line 164 of file warping_main.cpp.
Referenced by applyWarp(), deleteGrids(), myDisplay1(), myMouse(), resetGrid(), and setupWarper().
const GLfloat gGridPtColor[4] = {0.f, 0.f, 1.f, 1.f}
Definition at line 154 of file warping_main.cpp.
Referenced by myDisplay0(), and myDisplay1().
int gGridRows = 5
Definition at line 162 of file warping_main.cpp.
Referenced by deleteGrids(), myDisplay0(), myDisplay1(), myGridSizeMenu(), myMouse(), resetGrid(), and setupWarper().
int gImgHeight
Definition at line 147 of file warping_main.cpp.
Referenced by main(), myDisplay0(), and myDisplay1().
RasterImage* gImgIn = NULL
Definition at line 145 of file warping_main.cpp.
RasterImage * gImgOut = NULL
Definition at line 146 of file warping_main.cpp.
Referenced by initImagesAndWarper(), myDisplay1(), and setupWarper().
int gImgWidth
Definition at line 147 of file warping_main.cpp.
Referenced by main().
bool gInitDone = false
Definition at line 151 of file warping_main.cpp.
Referenced by myDisplay0(), myDisplay1(), myInit(), and myReshape().
float *** gInitGridPoint = NULL
Definition at line 165 of file warping_main.cpp.
Referenced by deleteGrids(), myDisplay0(), resetGrid(), and setupWarper().
InnerWarpingMode gInnerMode = INNER_FREE
Definition at line 160 of file warping_main.cpp.
Referenced by initImagesAndWarper().
int gMainWindow
Definition at line 149 of file warping_main.cpp.
Referenced by main(), myColorSubmenu(), myDisplay0(), myDisplay1(), myDisplayMain(), and myInit().
const int gNbCirclePts = 12
Definition at line 153 of file warping_main.cpp.
Referenced by myDisplay0(), myDisplay1(), and precalcCircle().
const string gray_dir = GRAY_DIR_PATH
Definition at line 62 of file warping_main.cpp.
int gSelectedPtCol = -1
Definition at line 157 of file warping_main.cpp.
Referenced by myDisplay0(), myDisplay1(), and myMouse().
int gSelectedPtRow = -1
Definition at line 156 of file warping_main.cpp.
Referenced by myDisplay0(), myDisplay1(), and myMouse().
int gSubwindow[kNbSubwindows]
Definition at line 149 of file warping_main.cpp.
Referenced by applyWarp(), main(), myDisplay0(), myDisplay1(), myInit(), and setupWarper().
ImageWarper_GL* gWarper = NULL
Definition at line 159 of file warping_main.cpp.
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 130 of file warping_main.cpp.
Referenced by main(), and myColorSubmenu().
char* kBckgndColStr[]
Initial value:
=       {
                                                        "Black",
                                                        "Red",
                                                        "Green" ,
                                                        "Yellow",
                                                        "Cyan"
                                                }
Definition at line 136 of file warping_main.cpp.
Referenced by myInit().
const int QUIT_MENU = 0
Definition at line 118 of file warping_main.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), and myMenuMain().
const int RESET_MENU = 1
Definition at line 119 of file warping_main.cpp.
Referenced by myInit(), and myMenu0().
const int SEPARATOR = 1000
Definition at line 120 of file warping_main.cpp.
Referenced by myInit().
const int SIX_BY_FOUR_GRID = 604
Definition at line 125 of file warping_main.cpp.
Referenced by myGridSizeMenu(), and myInit().
const int SIX_BY_SIX_GRID = 606
Definition at line 126 of file warping_main.cpp.
Referenced by myGridSizeMenu(), and myInit().
const int UPPER_LEFT = 0
Definition at line 115 of file warping_main.cpp.
Referenced by myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 116 of file warping_main.cpp.
Referenced by applyWarp(), myDisplay1(), myInit(), and setupWarper().