URIVisionLibrary: uriVL::ColorGaussianFilter Class Reference
uriVL::ColorGaussianFilter Class Reference
Pure Virtual parent class for the Gaussian filter classes _F and _I.
#include <ColorGaussianFilter.h>
Public Member Functions
int getWidth (void) const
Returns the width of the filter.
int getHeight (void) const
Returns the height of the filter.
float getScale (void) const
Returns the scale of the filter.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual RasterImage * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a RasterImage.
virtual RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image, returns the result as a RasterImage.
virtual void applyInto (const RasterImage *imgIn, RasterImage *imgOut)=0
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)=0
Applies this operator to a RasterImage and writes the resukt into a second RasterImage received as parameter.
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ColorGaussianFilter (double theScale, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
ColorGaussianFilter (int theWidth, bool isIntOperator)
Creates a Gaussian filter with the specified width.
ColorGaussianFilter (double theScale, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
ColorGaussianFilter (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified width.
ColorGaussianFilter (const ColorGaussianFilter &obj)
Copy constructor (disabled)
~ColorGaussianFilter (void)
Destructor.
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D red temp raster.
float *const * getShiftedTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D green temp raster.
float *const * getShiftedTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D blue temp raster.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
const ColorGaussianFilter & operator= (const ColorGaussianFilter &obj)
Copy operator: disabled.
Private Attributes
ImageRect * boundRect_
Bounding rectangle for pre-allocated temporary raster.
RasterImage_RGBa_F * tempRaster_
Temporary raster.
double scale_
the scale sigma of this filter
Detailed Description
Pure Virtual parent class for the Gaussian filter classes _F and _I.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 33 of file ColorGaussianFilter.h.
Constructor & Destructor Documentation
ColorGaussianFilter::ColorGaussianFilter (double theScale, bool isIntOperator) protected
Creates a Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
Parameters
scale scale sigma of the Gaussian filter
isIntOperator true if this operator produces only integer output
Definition at line 28 of file ColorGaussianFilter.cpp.
References FAIL_CONDITION, uriVL::kFilterAllocationError, and uriVL::ImageOperator::setRect().
                         :       ImageOperator(isIntOperator, kSaturatedPositive),
                                 //
                                 boundRect_(NULL),
                                 tempRaster_(NULL),
                                 scale_(theScale)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a color Gaussian filter is 0.8");
     const int   m = ((int) (5*theScale))/2;
     const int width = 2*m+1;
     setRect(-m, -m, width, width);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter constructor");
         throw e;
 }
ColorGaussianFilter::ColorGaussianFilter (int theWidth, bool isIntOperator) protected
Creates a Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
isIntOperator true if this operator produces only integer output
theWidth desired width of the Gaussian filter
Definition at line 50 of file ColorGaussianFilter.cpp.
References FAIL_CONDITION, and uriVL::kFilterAllocationError.
                         :       ImageOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1, isIntOperator,
                                                           kSaturatedPositive),
                                 boundRect_(NULL),
                                 tempRaster_(NULL),
                                 scale_(0.2L*(2*(theWidth/2) + 1))
 {
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest theWidth admissible for a color Gaussian filter is 3");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter constructor");
         throw e;
 }
ColorGaussianFilter::ColorGaussianFilter (double theScale, const ImageRect * theRect, bool isIntOperator) protected
Creates a Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
isIntOperator true if this operator produces only integer output
Definition at line 68 of file ColorGaussianFilter.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, uriVL::kFilterAllocationError, uriVL::ImageOperator::setRect(), and tempRaster_.
                         :       ImageOperator(isIntOperator, kSaturatedPositive),
                                 //
                                 boundRect_(new ImageRect(theRect)),
                                 tempRaster_(new RasterImage_RGBa_F(theRect)),
                                 scale_(theScale)
 {
     if (theScale < 0.8f)
         {
                 delete boundRect_;
                 delete tempRaster_;
                 FAIL_CONDITION( true,
                                                 kFilterAllocationError,
                                                 "The smallest theWidth admissible for a color Gaussian filter is 3");
         }
     int m = ((int) (5*theScale))/2;
     int width = 2*m+1;
         try {
                 setRect(-m, -m, width, width);
     }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by ColorGaussianFilter constructor");
                 throw e;
         }
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter constructor");
         throw e;
 }
ColorGaussianFilter::ColorGaussianFilter (int theWidth, const ImageRect * theRect, bool isIntOperator) protected
Creates a Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
isIntOperator true if this operator produces only integer output
Definition at line 102 of file ColorGaussianFilter.cpp.
                         :       ImageOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1),
                                 boundRect_(new ImageRect(theRect)),
                                 tempRaster_(new RasterImage_RGBa_F(theRect)),
                                 scale_(0.2L*(2*(theWidth/2) + 1))
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter constructor");
         throw e;
 }
ColorGaussianFilter::ColorGaussianFilter (const ColorGaussianFilter & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 117 of file ColorGaussianFilter.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ImageOperator(theObj),
                                 //
                                 boundRect_(NULL),
                                 tempRaster_(NULL),
                                 scale_(0)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorGaussianFilter copy constructor not implemented.");
 }
ColorGaussianFilter::~ColorGaussianFilter (void) protected
Destructor.
Definition at line 131 of file ColorGaussianFilter.cpp.
References boundRect_, and tempRaster_.
 {
     if (boundRect_ != NULL)
         delete boundRect_;
     if (tempRaster_ != NULL)
         delete tempRaster_;
 }
Member Function Documentation
bool ColorGaussianFilter::allocateTempRaster_ (const ImageRect * rect) protected
Allocates the temporary raster associated with this object.
If the raster was already allocated, the function only reallocates it if it was smaller than the new rect.
Parameters
rect dimensions of the temp rect to allocate
Returns
true if a new raster was allocated or the old one was resized
Definition at line 178 of file ColorGaussianFilter.cpp.
References uriVL::DrawableObject2D::contains(), uriVL::DrawableObject2D::setBoundRect(), and tempRaster_.
Referenced by uriVL::ColorGaussianFilter_F::applyInto(), and uriVL::ColorGaussianFilter_I::applyInto().
 {
         bool newTempRaster = (tempRaster_ == NULL);
     if (newTempRaster) {
         tempRaster_ = new RasterImage_RGBa_F(theRect);
         }
         //      Check if the user is a bonehead
     else if (!tempRaster_->contains(theRect)) {
                 tempRaster_->setBoundRect(theRect);
                 newTempRaster = true;
         }
         return newTempRaster;
 }
void ColorGaussianFilter::freeTempRaster_ (void) protected
Frees the temporary raster associated with this object.
Definition at line 193 of file ColorGaussianFilter.cpp.
References tempRaster_.
Referenced by uriVL::ColorGaussianFilter_F::applyInto(), and uriVL::ColorGaussianFilter_I::applyInto().
 {
         if (tempRaster_ != NULL) {
                 delete tempRaster_;
                 tempRaster_ = NULL;
         }
 }
int ColorGaussianFilter::getHeight (void) const
Returns the height of the filter.
Returns
height of the filter
Definition at line 161 of file ColorGaussianFilter.cpp.
References uriVL::ImageRect::getHeight(), and uriVL::ImageOperator::getRect().
 {
     return getRect()->getHeight();
 }
float ColorGaussianFilter::getScale (void) const
Returns the scale of the filter.
Returns
scale of the filter
Definition at line 166 of file ColorGaussianFilter.cpp.
References scale_.
Referenced by uriVL::ColorGaussianFilter_F::initializeFilter_(), and uriVL::ColorGaussianFilter_I::initializeFilter_().
 {
     return static_cast<float>(scale_);
 }
float *const * ColorGaussianFilter::getShiftedTempBlueF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D blue temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D blue temp raster
Definition at line 213 of file ColorGaussianFilter.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), and uriVL::ColorGaussianFilter_F::applyInto_9x9_().
 {
         return tempRaster_->getShiftedBlueF2D(R_W_ACCESS);
 }
float *const * ColorGaussianFilter::getShiftedTempGreenF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D green temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D green temp raster
Definition at line 207 of file ColorGaussianFilter.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), and uriVL::ColorGaussianFilter_F::applyInto_9x9_().
 {
         return tempRaster_->getShiftedGreenF2D(R_W_ACCESS);
 }
float *const * ColorGaussianFilter::getShiftedTempRedF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D red temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D red temp raster
Definition at line 201 of file ColorGaussianFilter.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), and uriVL::ColorGaussianFilter_F::applyInto_9x9_().
 {
         return tempRaster_->getShiftedRedF2D(R_W_ACCESS);
 }
int ColorGaussianFilter::getWidth (void) const
Returns the width of the filter.
Returns
width of the filter
Definition at line 156 of file ColorGaussianFilter.cpp.
References uriVL::ImageOperator::getRect(), and uriVL::ImageRect::getWidth().
Referenced by uriVL::ColorGaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyTo(), uriVL::ColorGaussianFilter_I::applyTo(), uriVL::ColorGaussianFilter_F::initializeFilter_(), and uriVL::ColorGaussianFilter_I::initializeFilter_().
 {
     return getRect()->getWidth();
 }
const ColorGaussianFilter & ColorGaussianFilter::operator= (const ColorGaussianFilter & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 140 of file ColorGaussianFilter.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorGaussianFilter copy operator not implemented.");
         return *this;
 }
Member Data Documentation
ImageRect* uriVL::ColorGaussianFilter::boundRect_ private
Bounding rectangle for pre-allocated temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 175 of file ColorGaussianFilter.h.
Referenced by ColorGaussianFilter(), and ~ColorGaussianFilter().
double uriVL::ColorGaussianFilter::scale_ private
the scale sigma of this filter
Definition at line 187 of file ColorGaussianFilter.h.
Referenced by getScale().
RasterImage_RGBa_F* uriVL::ColorGaussianFilter::tempRaster_ private
Temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 183 of file ColorGaussianFilter.h.
Referenced by allocateTempRaster_(), ColorGaussianFilter(), freeTempRaster_(), getShiftedTempBlueF2D_(), getShiftedTempGreenF2D_(), getShiftedTempRedF2D_(), and ~ColorGaussianFilter().
The documentation for this class was generated from the following files:
ColorGaussianFilter.h
ColorGaussianFilter.cpp