URIVisionLibrary: uriVL::GaussianFilter_I Class Reference
uriVL::GaussianFilter_I Class Reference
GaussianFilter_I class.
#include <GaussianFilter_I.h>
Public Member Functions
GaussianFilter_I (double theScale)
Defines a Gaussian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
GaussianFilter_I (int theWidth)
Defines a Gaussian Filter with a specified "radius".
GaussianFilter_I (double theScale, const ImageRect *theRect)
Creates a Gaussian filter with the specified scale.
GaussianFilter_I (int theWidth, const ImageRect *theRect)
Creates a Gaussian filter with the specified width.
~GaussianFilter_I (void)
Destructor.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::GaussianFilter
float getScale (void) const
Returns the scale of the filter.
~GaussianFilter (void)
Destructor.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
GaussianFilter_I (const GaussianFilter_I &obj)
Copy constructor (disabled)
const GaussianFilter_I & operator= (const GaussianFilter_I &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
void applyInto_3x3_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 3x3 Gaussian filter.
void applyInto_5x5_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 5x5 Gaussian filter.
void applyInto_7x7_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 7x7 Gaussian filter.
void applyInto_9x9_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 9x9 Gaussian filter.
void applyInto_11x11_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 11x11 Gaussian filter.
void applyInto_13x13_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 13x13 Gaussian filter.
void applyInto_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Function that implements a generic (width greater than 13) Gaussian filter.
Private Attributes
int * ig_
Stores into a 1D array (radial distances squared) the filter's coefficients.
int iDenum_
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Additional Inherited Members
Protected Member Functions inherited from uriVL::GaussianFilter
GaussianFilter (double theScale, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
GaussianFilter (int theWidth, bool isIntOperator)
Creates a Gaussian filter with the specified width.
GaussianFilter (double theScale, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
GaussianFilter (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified width.
GaussianFilter (const GaussianFilter &obj)
Copy constructor (disabled)
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempGrayF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D gray temp raster.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
GaussianFilter_I class.
Implements the application of a Gaussian filter using only integer weights. Note that in the current implementation of this class the same scale is applied along the x and y directions. Implementing a more general form is a low-priority item at this point.
Definition at line 32 of file GaussianFilter_I.h.
Constructor & Destructor Documentation
GaussianFilter_I::GaussianFilter_I (double theScale)
Defines a Gaussian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
Parameters
theScale scale parameter sigma of the 2D Gaussian filter
Definition at line 32 of file GaussianFilter_I.cpp.
References initializeFilter_().
                         :       GaussianFilter(theScale, true),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GaussianFilter_I constructor");
         throw e;
 }
GaussianFilter_I::GaussianFilter_I (int theWidth)
Defines a Gaussian Filter with a specified "radius".
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Gaussian filter
Definition at line 46 of file GaussianFilter_I.cpp.
References initializeFilter_().
                         :       GaussianFilter(theWidth, true),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GaussianFilter_I constructor");
         throw e;
 }
GaussianFilter_I::GaussianFilter_I (double theScale, const ImageRect * theRect)
Creates a Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 60 of file GaussianFilter_I.cpp.
References initializeFilter_().
                         :       GaussianFilter(theScale, theRect, true),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GaussianFilter_I constructor");
         throw e;
 }
GaussianFilter_I::GaussianFilter_I (int theWidth, const ImageRect * theRect)
Creates a Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 74 of file GaussianFilter_I.cpp.
References initializeFilter_().
                         :       GaussianFilter(theWidth, theRect, true),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by GaussianFilter_I constructor");
         throw e;
 }
GaussianFilter_I::~GaussianFilter_I (void)
Destructor.
Definition at line 101 of file GaussianFilter_I.cpp.
References ig_.
 {
         delete []ig_;
 }
GaussianFilter_I::GaussianFilter_I (const GaussianFilter_I & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 88 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       GaussianFilter(theObj),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "GaussianFilter_I copy constructor not implemented.");
 }
Member Function Documentation
void GaussianFilter_I::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 206 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void GaussianFilter_I::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 214 of file GaussianFilter_I.cpp.
References applyInto_(), applyInto_11x11_(), applyInto_13x13_(), applyInto_3x3_(), applyInto_5x5_(), applyInto_7x7_(), applyInto_9x9_(), uriVL::ImageRect::contains(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageOperator::getWidth(), uriVL::ImageRect::getWidth(), uriVL::ImageRect::intersection(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::RasterImage::requestRasterUpdate(), uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
         //----------------------------------------------------------------
         //      STEP 0:         Test for null or invalid type parameters
         //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in GaussianFilter_I::applyInto");
     FAIL_CONDITION(     imgOut == NULL,
                                 kNullRasterImageError,
                                 "NULL output raster image passed as parameter");
     //  so far I only accept a RasterImage_gray or RasterImage_gray_F as a source
         FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                         kInvalidRasterType,
                         "GaussianFilter_F::applyInto only accepts RasterImage_gray images as destination");
     //  so far I only accept a RasterImage_gray or RasterImage_gray_F as a destination
         FAIL_CONDITION( imgOut->getBaseRasterType() != kGrayRaster,
                         kInvalidRasterType,
                         "GaussianFilter_F::applyInto only accepts RasterImage_gray images as destination");
         //----------------------------------------------------------------
         //      STEP 1:         Test for rectangle intersection
         //----------------------------------------------------------------
         //  determine the output rectangle that the input image can produce.
         //              Here, because we apply a filter of width&height (2m+1), we
         //              "lose m all around".
         const int       m = getWidth() / 2;
         const ImageRect* inRect = imgIn->getValidRect();
     ImageRect* outRect = new ImageRect(inRect->getLeft() + m, inRect->getTop() + m,
                                                                                 inRect->getWidth() - 2*m,
                                                                                 inRect->getHeight() - 2*m);
         //      ... and determine its intersection with the user-specified output rectangle
         ImageRect* destRect = ImageRect::intersection(theRect, outRect);
         delete outRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!outRect->contains(destRect))
         imgOut->setBoundRect(destRect);
         //----------------------------------------------------------------
         //      STEP 2:         Perform the calculations
         //----------------------------------------------------------------
     switch (getWidth())
     {
         case 3:
             applyInto_3x3_(imgIn, destRect, imgOut);
             break;
         case 5:
             applyInto_5x5_(imgIn, destRect, imgOut);
             break;
         case 7:
             applyInto_7x7_(imgIn, destRect, imgOut);
             break;
         case 9:
             applyInto_9x9_(imgIn, destRect, imgOut);
             break;
         case 11:
             applyInto_11x11_(imgIn, destRect, imgOut);
             break;
         case 13:
             applyInto_13x13_(imgIn, destRect, imgOut);
             break;
         default:
             applyInto_(imgIn, destRect, imgOut);
             break;
     }
         //      Very important:  At the end of the computation, don't forget to set the
         //      output's valid data rectangle.  In "safe" mode, the library has no way to guess
         //      what the valid data rectangle should be and sets it to its minimum value... empty
         imgOut->setValidRect(destRect);
         imgOut->requestRasterUpdate();
         //      imgOut->setFloatRasterAsReference();
         delete destRect;
 }
void GaussianFilter_I::applyInto_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Function that implements a generic (width greater than 13) Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 367 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_11x11_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 11x11 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 348 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_13x13_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 13x13 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 357 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_3x3_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 3x3 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 312 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_5x5_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 5x5 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 321 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_7x7_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 7x7 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 330 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void GaussianFilter_I::applyInto_9x9_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 9x9 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 339 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
RasterImage * GaussianFilter_I::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 126 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to GaussianFilter_I::applyTo");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * GaussianFilter_I::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 135 of file GaussianFilter_I.cpp.
References applyInto(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageOperator::getWidth(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to GaussianFilter_I::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in GaussianFilter_I::applyTo");
         ImageRect       *usableRect = new ImageRect(imgIn->getValidRect());
         const int       m = getWidth() / 2;
         usableRect->removeAllAround(m);
         ImageRect       *destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
         RasterImage* imgOut = NULL;
         if (imgIn->hasFloatRaster())
         {
             switch (imgIn->getBaseRasterType())
             {
                 case kGrayRaster:
                     imgOut = new RasterImage_gray_F(destRect);
                     break;
                 case kRGBa32Raster:
                     imgOut = new RasterImage_RGBa_F(destRect);
                     break;
                 default:
                     FAIL_CONDITION(     true,
                                                 kFunctionNotImplemented,
                                                 "image type not suported by Gaussian filter yet");
                     break;
             }
     }
     else
         {
             switch (imgIn->getBaseRasterType())
             {
                 case kGrayRaster:
                     imgOut = new RasterImage_gray(destRect);
                     break;
                 case kRGB24Raster:
                     imgOut = new RasterImage_RGB(destRect);
                     break;
                 case kRGBa32Raster:
                     imgOut = new RasterImage_RGBa(destRect);
                     break;
                 default:
                     FAIL_CONDITION(     true,
                                                 kFunctionNotImplemented,
                                                 "image type not suported by Gaussian filter yet");
                     break;
             }
     }
     applyInto(imgIn, theRect, imgOut);
         delete destRect;
         delete usableRect;
         return imgOut;
 }
void GaussianFilter_I::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
ig_
Definition at line 381 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::GaussianFilter::getScale(), uriVL::ImageOperator::getWidth(), iDenum_, ig_, uriVL::kFilterAllocationError, and PI.
Referenced by GaussianFilter_I().
 {
     const int   m = getWidth()/2;
         const double scale = getScale();
     const double sigma2Scale = 1.L / (2.L * scale * scale);
     ig_ = new int[m+1];
     FAIL_CONDITION( ig_ == NULL,
                     kFilterAllocationError,
                     "filter allocation failed");
     //  the scaling denominator is the inverse of the smallest value of the
     //  "floating point filter"
     iDenum_ = static_cast<int>((sqrt(2*PI)*scale) / exp(-m*m*sigma2Scale));
     for (int r=0; r<=m; r++)
         ig_[r] = static_cast<int>(exp((m*m - -r*r)*sigma2Scale));
 }
const GaussianFilter_I & GaussianFilter_I::operator= (const GaussianFilter_I & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 107 of file GaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "GaussianFilter_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
int uriVL::GaussianFilter_I::iDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Definition at line 148 of file GaussianFilter_I.h.
Referenced by initializeFilter_().
int* uriVL::GaussianFilter_I::ig_ private
Stores into a 1D array (radial distances squared) the filter's coefficients.
Definition at line 143 of file GaussianFilter_I.h.
Referenced by initializeFilter_(), and ~GaussianFilter_I().
The documentation for this class was generated from the following files:
GaussianFilter_I.h
GaussianFilter_I.cpp