URIVisionLibrary: uriVL::ImageLaplacian_Sobel Class Reference
uriVL::ImageLaplacian_Sobel Class Reference
ImageLaplacian_Sobel class.
#include <ColorImageLaplacian_Sobel.h>
Public Member Functions
ImageLaplacian_Sobel (LaplacianSobelForm form)
Default constructor.
~ImageLaplacian_Sobel (void)
Destructor.
RasterImage * applyTo (RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
ImageLaplacian_Sobel (LaplacianSobelForm form)
Default constructor.
~ImageLaplacian_Sobel (void)
Destructor.
float getScale (void) const
Implements the pure virtual function defined in the parent class to return the value 0.6f (or width/5 = 3/5.f) even though this is not really the "scale" of anything, just an analogy to the Gaussian version.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::ImageLaplacian
~ImageLaplacian (void)
Destructor.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
void applyInto_form1_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 1" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
void applyInto_form2_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 2" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
void applyInto_form3_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 3" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Protected Member Functions inherited from uriVL::ImageLaplacian
ImageLaplacian (int theWidth, int theHeight, bool isIntOperator)
Constructor.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
void applyInto_form1_ (RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 1" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
void applyInto_form2_ (RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 2" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
void applyInto_form3_ (RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies the "form 3" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Private Attributes
LaplacianSobelForm form_
Mask form of this operator.
Detailed Description
ImageLaplacian_Sobel class.
There are (so far) 3 possible implementations of the ImageLaplacian_Sobel class. I know that by calling them so I abuse the name "Sobel" but I just call a "Sobel" operator any linear operator that corresponds to a 3x3 covariance mask.
See also
LaplacianSobelForm
Definition at line 63 of file ColorImageLaplacian_Sobel.h.
Constructor & Destructor Documentation
ImageLaplacian_Sobel::ImageLaplacian_Sobel (LaplacianSobelForm form)
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
Definition at line 23 of file ColorImageLaplacian_Sobel.cpp.
References form_.
         :       ImageLaplacian( )
 {
     form_ = form;
     width_ = 3;
 }
ImageLaplacian_Sobel::~ImageLaplacian_Sobel (void)
Destructor.
Definition at line 30 of file ColorImageLaplacian_Sobel.cpp.
 {}
uriVL::ImageLaplacian_Sobel::ImageLaplacian_Sobel (LaplacianSobelForm form)
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
uriVL::ImageLaplacian_Sobel::~ImageLaplacian_Sobel (void)
Destructor.
Member Function Documentation
void ImageLaplacian_Sobel::applyInto (RasterImage * imgIn, RasterImage * imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
That destination image must be of type RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Definition at line 70 of file ColorImageLaplacian_Sobel.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyInto(), applyTo(), and myMenu2().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void ImageLaplacian_Sobel::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
That destination image must be of type RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 91 of file ImageLaplacian_Sobel.cpp.
References applyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void uriVL::ImageLaplacian_Sobel::applyInto (RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
That destination image must be of type RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
void ImageLaplacian_Sobel::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
That destination image must be of type RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 101 of file ImageLaplacian_Sobel.cpp.
References applyInto_form1_(), applyInto_form2_(), applyInto_form3_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, form_, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageOperator::getFloatConversionMode(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kGrayRaster, uriVL::kImageProcessingError, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::LAPLACIAN_SOBEL_FORM_1, uriVL::LAPLACIAN_SOBEL_FORM_2, uriVL::LAPLACIAN_SOBEL_FORM_3, uriVL::RasterImage_gray::localRasterGray(), uriVL::ImageRect::removeAllAround(), uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
     //----------------------------------------------------------------
     //  STEP 0:         Test for null or invalid type parameters
     //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageLaplacian_Sobel::applyInto");
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter");
     //  so far I only accept a RasterImage_gray_F as a destination
     FAIL_CONDITION( (imgOut->getBaseRasterType() != kGrayRaster)  ||
                     !(imgOut->hasFloatRaster()),
                     kInvalidRasterType,
                     "ImageLaplacian_Sobel::applyInto only accepts RasterImage_gray_F images as destination");
     //----------------------------------------------------------------
     //  STEP 1:         Test for rectangle intersection
     //----------------------------------------------------------------
     //  determine the output rectangle that the input image can produce.
     //          Here, because we apply a filter of width&height 3, we
     //          "lose m all around".
     ImageRect* usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     //  ... and determine its intersection with the user-specified output rectangle
     ImageRect* destRect = ImageRect::intersection(theRect, usableRect);
     delete usableRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!imgOut->contains(destRect))
         imgOut->setBoundRect(destRect);
     //----------------------------------------------------------------
     //  STEP 2:         Operate only on a gray-level image
     //----------------------------------------------------------------
     bool localGray;
     const RasterImage_gray* grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
     //----------------------------------------------------------------
     //  STEP 3:         Perform the calculations
     //----------------------------------------------------------------
     switch (form_)
     {
         case LAPLACIAN_SOBEL_FORM_1:
             applyInto_form1_(grayImg, destRect, imgOut);
             break;
         case LAPLACIAN_SOBEL_FORM_2:
             applyInto_form2_(grayImg, destRect, imgOut);
             break;
         case LAPLACIAN_SOBEL_FORM_3:
             applyInto_form3_(grayImg, destRect, imgOut);
             break;
         default:
             FAIL_CONDITION(     true,
                             kImageProcessingError,
                             "invalid Laplacian Sobel form");
             break;
     }
     //----------------------------------------------------------------
     //  STEP 4:         Set rectangle
     //----------------------------------------------------------------
     //  Very important:  At the end of the computation, don't forget to set the
     //  output's valid data rectangle.  In "safe" mode, the library has no way to guess
     //  what the valid data rectangle should be and sets it to its minimum value... empty
     imgOut->setValidRect(destRect);
     ((RasterImage_gray_F *) imgOut)->setFloatConversionMode(getFloatConversionMode());
     //----------------------------------------------------------------
     //  STEP 5:         Free temporary storage (if needed)
     //----------------------------------------------------------------
     if (localGray)
         delete grayImg;
     delete destRect;
 }
void uriVL::ImageLaplacian_Sobel::applyInto_form1_ (RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Applies the "form 1" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Referenced by applyInto().
void ImageLaplacian_Sobel::applyInto_form1_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Applies the "form 1" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
2 cases
Definition at line 197 of file ImageLaplacian_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
 {
     const int   iLow  = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     /// 2 cases
     if (imgIn->hasFloatRaster())
     {
         const float* const* inGray = (static_cast<const RasterImage_gray_F*>(imgIn))->getShiftedGrayF2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = inGray[i][jp1] + inGray[i][jm1] +
                                 inGray[im1][j] + inGray[ip1][j] -
                                 4.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
     else
     {
         const unsigned char* const* inGray = imgIn->getShiftedRaster2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = inGray[i][jp1] + inGray[i][jm1] +
                                 inGray[im1][j] + inGray[ip1][j] -
                                 4.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
 }
void uriVL::ImageLaplacian_Sobel::applyInto_form2_ (RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Applies the "form 2" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Referenced by applyInto().
void ImageLaplacian_Sobel::applyInto_form2_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Applies the "form 2" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
2 cases
Definition at line 267 of file ImageLaplacian_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
 {
     const int   iLow  = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     /// 2 cases
     if (imgIn->hasFloatRaster())
     {
         const float* const* inGray = (static_cast<const RasterImage_gray_F*>(imgIn))->getShiftedGrayF2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = inGray[im1][jp1] + inGray[ip1][jm1] +
                                 inGray[im1][jm1] + inGray[ip1][jp1] -
                                 4.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
     else
     {
         const unsigned char* const* inGray = imgIn->getShiftedRaster2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = inGray[im1][jp1] + inGray[ip1][jm1] +
                                 inGray[im1][jm1] + inGray[ip1][jp1] -
                                 4.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
 }
void uriVL::ImageLaplacian_Sobel::applyInto_form3_ (RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Applies the "form 3" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Referenced by applyInto().
void ImageLaplacian_Sobel::applyInto_form3_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) protected
Applies the "form 3" Laplacian to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
2 cases
Definition at line 336 of file ImageLaplacian_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::RasterImage::hasFloatRaster(), and uriVL::R_W_ACCESS.
 {
     const int   iLow  = theRect->getTop(),
                 iHigh = theRect->getBottom(),
                 jLow = theRect->getLeft(),
                 jHigh = theRect->getRight();
     /// 2 cases
     if (imgIn->hasFloatRaster())
     {
         const float* const* inGray = (static_cast<const RasterImage_gray_F*>(imgIn))->getShiftedGrayF2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = (inGray[im1][jm1] + inGray[im1][jp1] +
                                  inGray[ip1][jm1] + inGray[ip1][jp1]) +
                                 4.f*(inGray[im1][j] + inGray[i][jm1] +
                                      inGray[i][jp1] + inGray[ip1][j]) -
                                 20.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
     else
     {
         const unsigned char* const* inGray = imgIn->getShiftedRaster2D();
         float* const* outGray = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
         //  compute convolution over the processing rectangle
         int   im1 = iLow-1, ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; i++)
         {
             int jm1 = jLow-1, jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; j++)
             {
                 outGray[i][j] = (inGray[im1][jm1] + inGray[im1][jp1] +
                                  inGray[ip1][jm1] + inGray[ip1][jp1]) +
                                 4.f*(inGray[im1][j] + inGray[i][jm1] +
                                      inGray[i][jp1] + inGray[ip1][j]) -
                                 20.f*inGray[i][j];
                 //  shift the j indexes (j itself is taken care of in the loop
                 //  statement)
                 jm1 = j;
                 jp1++;
             }
             //  shift the i indexes (i itself is taken care of in the loop
             //  statement)
             im1 = i;
             ip1++;
         }
     }
 }
RasterImage * ImageLaplacian_Sobel::applyTo (RasterImage * imgIn)
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is always of type RasterImage_Gray_F
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Definition at line 38 of file ColorImageLaplacian_Sobel.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * ImageLaplacian_Sobel::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is always of type RasterImage_Gray_F
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 59 of file ImageLaplacian_Sobel.cpp.
References applyTo(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage* uriVL::ImageLaplacian_Sobel::applyTo (RasterImage * imgIn, const ImageRect * theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is always of type RasterImage_Gray_F
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
RasterImage * ImageLaplacian_Sobel::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is always of type RasterImage_Gray_F
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 68 of file ImageLaplacian_Sobel.cpp.
References applyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     ImageRect   *usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     ImageRect   *destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     RasterImage *imgOut = new RasterImage_gray_F(destRect);
     applyInto(imgIn, theRect, imgOut);
     delete destRect;
     delete usableRect;
     return imgOut;
 }
float ImageLaplacian_Sobel::getScale (void) const virtual
Implements the pure virtual function defined in the parent class to return the value 0.6f (or width/5 = 3/5.f) even though this is not really the "scale" of anything, just an analogy to the Gaussian version.
Returns
0.6f
Implements uriVL::ImageLaplacian.
Definition at line 46 of file ImageLaplacian_Sobel.cpp.
 {
     return 0.6f;
 }
Member Data Documentation
LaplacianSobelForm uriVL::ImageLaplacian_Sobel::form_ private
Mask form of this operator.
Definition at line 127 of file ColorImageLaplacian_Sobel.h.
Referenced by applyInto(), and ImageLaplacian_Sobel().
The documentation for this class was generated from the following files:
ColorImageLaplacian_Sobel.h
ImageLaplacian_Sobel.h
ColorImageLaplacian_Sobel.cpp
ImageLaplacian_Sobel.cpp