URIVisionLibrary: uriVL::RasterImage Class Reference
uriVL::RasterImage Class Reference abstract
Virtual base image class.
#include <RasterImage.h>
Public Member Functions
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
virtual void copyInto (RasterImage *imgOut) const =0
Copies this image into the one received as parameter.
virtual void copyInto (RasterImage *imgOut, const ImageRect *theRect) const =0
Copies this image into the one received as parameter.
virtual void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const =0
Copies this image into the one received as parameter.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
virtual BaseRasterType getBaseRasterType (void) const =0
Returns the image's base raster type.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
virtual void allocateGraphWorld_ (int nbRows, int nbCols)=0
Alocates the GraphWorld for this object at the set dimensions.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Private Member Functions
RasterImage (void)
Default constructor.
RasterImage (int nbRows, int nbCols)
Allocates a raster image at the specified dimensions.
RasterImage (const ImageRect *theRect)
Allocates a raster image at the specified dimensions.
RasterImage (const ImageRect &theRect)
Allocates a raster image at the specified dimensions.
RasterImage (const GraphWorld *gworld)
Creates a new raster image based on the GraphWorld received as parameter.
RasterImage (GraphWorld *gworld, bool keepThisGWorld)
Creates a new raster image based on the GraphWorld received as parameter.
RasterImage (const RasterImage *img)
Creates a new raster image based on the one received as parameter.
RasterImage (const RasterImage &img)
Creates a new raster image based on the one received as parameter.
const RasterImage & operator= (const RasterImage &img)
Copy operator: disabled.
virtual void copyInto_ (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const =0
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the raster image.
virtual void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders the RasterImage's base raster at the depth and location specified.
virtual void updateRaster_ (void) const =0
Updates the image's base raster (if it is not the reference).
virtual void allocateRaster2D_ (int nbRows, int nbCols)=0
Allocates the 2D base raster.
virtual void deleteRaster2D_ (void)=0
Deletes the 0-based 2D base raster.
virtual void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)=0
Allocates the 2D shifted base raster.
virtual void deleteShiftedRaster2D_ (int iLow)=0
Deletes the 2D shifted base raster.
virtual void computeBoundingRect_ (ImageRect &rect) const
Calculates the object's bounding rect.
virtual void computeValidRect_ (ImageRect &rect) const
Calculates the object's valid box.
virtual void computeCentroid_ (ImagePoint_F &cent) const
Computes the contour's centroid.
virtual void computeCenterOfMass_ (ImagePoint_F &cent) const
Computes the object's center of mass by calculating the average point.
Private Attributes
unsigned int id_
Unique index of this RasterImage object.
GraphWorld * gworld_
Stores the base raster for this image.
bool gworldIsReference_
True when the base raster stored in the GraphWorld object is the reference raster for this image.
bool hasFloatRaster_
True when the RasterImage stores a float raster.
bool hasOtherRaster_
True when the RasterImage stores another raster (other than a float raster), e.g.
bool floatRasterIsReference_
True when the RasterImage stores a float raster and that raster is the reference.
bool referenceHasChanged_
True when the base raster stored in the GraphWorld object the reference raster for this image.
long timeStamp_
Time stamp for this image.
bool propertiesAreLocked_
True when the image's dimensions and pixel depth are locked.
bool pixmapIsLocked_
True when the image's pixel map is locked.
void * propertiesKey_
Key for the image's dimensions and pixel depth.
void * pixmapKey_
Key for the image's pixel map.
Static Private Attributes
static unsigned int imgCount_ = 0
Counter for RasterImage objects created by the application.
static ConversionToGrayMode defaultGrayConv_ = kAverageConversion
Code for the default algorithm for conversion to gray.
static float defaultConvWeight_ [3] = {1.f/3.f, 1.f/3.f, 1.f/3.f}
Weights used for the red, green, and blue channels if the default conversion algorithm for this image is kWeightedAverageConversion.
Friends
class DrawableObject2D
class RasterImage_binary
class RasterImage_gray
class RasterImage_gray_F
class RasterImage_RGB
class RasterImage_RGBa
class RasterImage_RGBa_F
class RasterImage_HSV
class RasterImage_aRGB16
class Pattern2D
class VideoSource
class _FrameGrabber_libvidcap
Detailed Description
Virtual base image class.
RasterImage is the base class for all image types. This class is build around a QuickTime GWorld buffer, which is itself wrapped into a GraphWorld object.
Each RasterImage object has a base raster type (8 bit gray, 16 bit argb color, 24 bit rgb color, and 32 bit rgba color). The GraphWorld object corresponding to this base type is not always allocated. It only needs to be so when the raster must be displayed.
The RasterImage class contains a number of virtual methods that must be implemented by the subclasses.
The base subclasses of RasterImage correspond to the base raster types. They are:
RasterImage_gray for 8-bit gray level images
RasterImage_rgb16 for 16-bit [1 alpha, 5 red, 5 green, 5 blue] color images
RasterImage_RGB for 24-bit [8 red, 8 green, 8 blue] color images
RasterImage_RGBa for 32-bit [8 alpha, 8 red, 8 green, 8 blue] color images These base subclasses can be instanciated and are the ones most commonly used for image processing and computer vision purposes.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 100 of file RasterImage.h.
Constructor & Destructor Documentation
RasterImage::~RasterImage (void) virtual
Destructor.
Definition at line 271 of file RasterImage.cpp.
References gworld_.
 {
     if (gworld_ != NULL)
         delete gworld_;
 }
RasterImage::RasterImage (void) private
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Definition at line 44 of file RasterImage.cpp.
         :   DrawableObject2D(),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
 }
RasterImage::RasterImage (int nbRows, int nbCols) private
Allocates a raster image at the specified dimensions.
Initializes some instance variables (in particular the ImageRect).
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Definition at line 63 of file RasterImage.cpp.
         :   DrawableObject2D(nbRows, nbCols),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
 }
RasterImage::RasterImage (const ImageRect * theRect) private
Allocates a raster image at the specified dimensions.
Initializes some instance variables (in particular the ImageRect).
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
theRect image rectangle indicating the desired dimensions
Definition at line 82 of file RasterImage.cpp.
                 :   DrawableObject2D(*theRect),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by RasterImage constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ImageRect parameter error in RasterImage constructor");
 }
RasterImage::RasterImage (const ImageRect & theRect) private
Allocates a raster image at the specified dimensions.
Initializes some instance variables (in particular the ImageRect).
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
Parameters
theRect image rectangle indicating the desired dimensions
Definition at line 112 of file RasterImage.cpp.
                 :   DrawableObject2D(theRect),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by RasterImage constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ImageRect parameter error in RasterImage constructor");
 }
RasterImage::RasterImage (const GraphWorld * gworld) private
Creates a new raster image based on the GraphWorld received as parameter.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
The GraphWorld received as parameter is cloned into the new image and gworldIsReference_ is set to true (can be overridden by a subclass).
See also
gworldIsReference_
Parameters
gworld pointer to the GraphWorld to clone
Definition at line 142 of file RasterImage.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   DrawableObject2D(kDense),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor is not operative yet");
 }
RasterImage::RasterImage (GraphWorld * gworld, bool keepThisGWorld) private
Creates a new raster image based on the GraphWorld received as parameter.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
The GraphWorld received as parameter is kept rather than being cloned if the boolean parameter is true. gworldIsReference_ is set to true (can be overridden by a subclass).
See also
gworldIsReference_
Parameters
gworld pointer to the GraphWorld to clone or keep
keepThisGWorld true if the GraphWorld should be kept rather than cloned
Definition at line 166 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getEffectiveNbCols(), uriVL::GraphWorld::getNbRows(), gworld_, uriVL::kFunctionNotImplemented, uriVL::kGWorldIsNullError, uriVL::kNullParameterError, uriVL::DrawableObject2D::setBoundRect(), uriVL::DrawableObject2D::setValidRect(), and uriVL::UriVL::validDataRectIsSafe().
         :   DrawableObject2D(kDense),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(true),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Constructor is not operative yet");
     FAIL_CONDITION(theGworld == NULL, kGWorldIsNullError,
                    "NULL GraphWorld in RasterImage constructor");
     if (keepThisGWorld)
         gworld_ = theGworld;
     else
         gworld_ = new GraphWorld(theGworld);
         try {
                 setBoundRect(0, 0, theGworld->getNbRows(), theGworld->getEffectiveNbCols());
         }
         catch (...) {
                 FAIL_CONDITION( theGworld == NULL,
                                                 kNullParameterError,
                                                 "Null pointer passed to RasterImage constructor.");
         }
     if (UriVL::validDataRectIsSafe())
     {
         setValidRect(0, 0, 0, 0);
     }
     else
         setValidRect(0, 0, theGworld->getNbRows(), theGworld->getEffectiveNbCols());
 }
RasterImage::RasterImage (const RasterImage * img) private
Creates a new raster image based on the one received as parameter.
This constructor should only be invoked from one of the base raster subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa)
if that image did not not have its GraphWorld allocated or if the GraphWorld was not the reference, then only copy image bounds info
if that image had a valid GraphWorld as its reference, then clone that GraphWorld for the new image
Note that it is not possible w/o massive recoding and headaches to offer a version of this constructor that gharantees the constness of the parameter. If the actual types of the two images do not match, then a conversion must take place, and either we have to code all possible combinations of such conversions or we do it through the GWorld, in which case the GWorld of the source may have to be updated, hence non-constness. Making the GWorld mutable has a cascading effect (after all, this is the central data structure for this class), which amounts to making "const" meaningless.
Parameters
img pointer to the RasterImage object to copy
Definition at line 214 of file RasterImage.cpp.
References pixmapIsLocked_, propertiesAreLocked_, and timeStamp_.
         :   DrawableObject2D(*img),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(false),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
     timeStamp_ = 0;
     propertiesAreLocked_ = pixmapIsLocked_ = false;
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by RasterImage constructor");
         throw e;
 }
 catch (...)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in RasterImage constructor");
 }
RasterImage::RasterImage (const RasterImage & img) private
Creates a new raster image based on the one received as parameter.
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
img the RasterImage object to copy
Definition at line 249 of file RasterImage.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   DrawableObject2D(),
                         //
                         id_(imgCount_++),
                         gworld_ (NULL),
                         gworldIsReference_(true),
                         hasFloatRaster_(false),
                         hasOtherRaster_(false),
                         floatRasterIsReference_(false),
                         referenceHasChanged_(false),
                         timeStamp_(0),
                         propertiesAreLocked_(false),
                         pixmapIsLocked_(false),
                         propertiesKey_(NULL),
                         pixmapKey_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage copy constructor not implemented.");
 }
Member Function Documentation
virtual void uriVL::RasterImage::allocateGraphWorld_ (int nbRows, int nbCols) protected pure virtual
Alocates the GraphWorld for this object at the set dimensions.
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_aRGB16, uriVL::RasterImage_gray, uriVL::RasterImage_RGBa, and uriVL::RasterImage_RGB.
virtual void uriVL::RasterImage::allocateRaster2D_ (int nbRows, int nbCols) private pure virtual
Allocates the 2D base raster.
This pure virtual function must be implemented by child classes.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_gray, uriVL::RasterImage_aRGB16, uriVL::RasterImage_RGBa, uriVL::RasterImage_HSV, uriVL::RasterImage_RGB, uriVL::RasterImage_HSV24, and uriVL::RasterImage_Lab.
Referenced by copyInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
virtual void uriVL::RasterImage::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private pure virtual
Allocates the 2D shifted base raster.
This pure virtual function must be implemented by child classes.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_gray, uriVL::RasterImage_aRGB16, uriVL::RasterImage_RGBa, uriVL::RasterImage_HSV, uriVL::RasterImage_RGB, uriVL::RasterImage_HSV24, and uriVL::RasterImage_Lab.
Referenced by copyInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
void RasterImage::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implements uriVL::DrawableObject2D.
Definition at line 998 of file RasterImage.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void RasterImage::computeBoundingRect_ (ImageRect & rect) const private virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 1296 of file RasterImage.cpp.
 {
         //      nothing to do
 }
void RasterImage::computeCenterOfMass_ (ImagePoint_F & cent) const private virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implements uriVL::DrawableObject2D.
Definition at line 1311 of file RasterImage.cpp.
 {
         //      nothing to do
 }
void RasterImage::computeCentroid_ (ImagePoint_F & cent) const private virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implements uriVL::DrawableObject2D.
Definition at line 1306 of file RasterImage.cpp.
 {
         //      nothing to do
 }
void RasterImage::computeValidRect_ (ImageRect & rect) const private virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 1301 of file RasterImage.cpp.
 {
         //      nothing to do
 }
virtual void uriVL::RasterImage::copyInto (RasterImage * imgOut) const pure virtual
Copies this image into the one received as parameter.
Copies (rather than cloning) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated. This function must be overridden (and called by the overriding function) by subclasses of RasterImage.
Parameters
imgOut pointer to the destination image
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_RGB, and uriVL::RasterImage_aRGB16.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), applyOverlays(), uriVL::BackgroundRemover::assignBackground_(), grab(), myMenu2(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), and resetImages().
virtual void uriVL::RasterImage::copyInto (RasterImage * imgOut, const ImageRect * theRect) const pure virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated. This function must be overridden (and called by the overriding function) by subclasses of RasterImage.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_RGB, and uriVL::RasterImage_aRGB16.
virtual void uriVL::RasterImage::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const pure virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated. This function must be overridden (and called by the overriding function) by subclasses of RasterImage.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_RGB, and uriVL::RasterImage_aRGB16.
void RasterImage::copyInto_ (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const private virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated. This function must be overridden (and called by the overriding function) by subclasses of VectorField.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner
Definition at line 471 of file RasterImage.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::DrawableObject2D::boundRectIsEmpty(), uriVL::DrawableObject2D::contains(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, getBaseRasterType(), uriVL::ImageRect::getHeight(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::getWidth(), uriVL::DrawableObject2D::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), graphWorldIsReference(), gworld_, hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kInvalidRectangleError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
Referenced by uriVL::RasterImage_aRGB16::copyInto(), uriVL::RasterImage_RGB::copyInto(), uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage_RGBa::copyInto(), uriVL::RasterImage_gray_F::copyInto(), uriVL::RasterImage_RGBa_F::copyInto(), and uriVL::RasterImage_binary::copyInto().
 {
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage::copyInto_");
     //  We only copy from the valid data rect, so we need to calculate its intersection
     //  with theRect.
 //      Here I am not sure:  Should we fail or simply do nothing????
     ImageRect* copyRect = ImageRect::intersection(getValidRect(), theRect);
     FAIL_CONDITION( copyRect == NULL,
                     kInvalidRectangleError,
                     "the copy rectangle specified is not within valid data in RasterImage::copyInto_");
     //  the destination rectangle has the same width and height as the copy rectangle,
     //  but with its upper-left corner at the location specified by origin
         //      If the origin has not been set (NULL pointer), then use the copyRect
     ImageRect* destRect;
     if (origin != NULL) {
                 int x, y;
                 try {
                         x = origin->getX();
                         y = origin->getY();
                 }
                 catch (...) {
                         FAIL_CONDITION( true,
                                                         kInvalidParameterError,
                                                         "Invalid ImagePoint pointer in RasterImage::copyInto_");
                 }
                 int w, h;
                 try {
                         w = copyRect->getWidth();
                         h = copyRect->getHeight();
                 }
                 catch (...) {
                         FAIL_CONDITION( true,
                                                         kInvalidParameterError,
                                                         "Invalid ImageRect pointer in RasterImage::copyInto_");
                 }
         destRect = new ImageRect(x, y, w, h);
     }
         else
         destRect = copyRect;
     bool        needToAllocateNewGWorld = false;
     bool        needToAllocateFloatRaster = false;
         try {
                 //      If the destination image did not already have a raster allocated, we allocate
                 //      one now, and the bound rect and valid rect coincide
                 if ((imgOut->gworld_ == NULL) || (imgOut->boundRectIsEmpty()))
                 {
                         if (imgOut->hasFloatRaster())
                                 needToAllocateFloatRaster = true;
                         else
                                 needToAllocateNewGWorld = true;
                         imgOut->setBoundRect(destRect);
                         imgOut->setBoundRect(destRect);
                         //      since imgOut did not have any raster allocated, we must allocate one
                         if (imgOut->graphWorldIsReference())
                                 needToAllocateNewGWorld = true;
                         if (imgOut->hasFloatRaster())
                                 needToAllocateFloatRaster = true;
                 }
                 //      if the bounding rectangle of the destination field does not contain copyRect
                 //      we need to resize it
                 else if (!(imgOut->contains(destRect)))
                 {
                         imgOut->deleteShiftedRaster2D_(imgOut->getTop());
                         imgOut->deleteRaster2D_( );
                         //      The bound rect and valid rect coincide.
                         imgOut->setBoundRect(destRect);
                         imgOut->setBoundRect(destRect);
                         //      if imgOut was GraphWorld-based, we must reallocate the GraphWorld
                         if (imgOut->graphWorldIsReference())
{
                                 delete imgOut->gworld_;
                                 needToAllocateNewGWorld = true;
                         }
                         if (imgOut->hasFloatRaster())
                                 needToAllocateFloatRaster = true;
                 }
         }
         catch (ErrorReport& e) {
                 delete copyRect;
                 if (origin != NULL)
                         delete destRect;
                 e.appendToMessage("called from RasterImage::copyInto_");
                 throw e;
         }
         catch (...) {
                 delete copyRect;
                 if (origin != NULL)
                         delete destRect;
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid output image pointer in RasterImage::copyInto_");
         }
     //  If either the output image's did not have a GraphWorld allocated or we just
     //  deleted it because its dimensions did not match those of the input image, we
     //  allocate a new GraphWorld now.
     if (needToAllocateNewGWorld)
     {
         switch (imgOut->getBaseRasterType())
         {
             case kBinaryRaster:
                 imgOut->gworld_ = new GraphWorld(1, destRect);
                 break;
             case kGrayRaster:
                 imgOut->gworld_ = new GraphWorld(8, destRect);
                 break;
             case kRGB24Raster:
                 imgOut->gworld_ = new GraphWorld(24, destRect);
                 break;
             case kRGBa32Raster:
                 imgOut->gworld_ = new GraphWorld(32, destRect);
                 break;
             default:
                 FAIL_CONDITION( true,
                                 kRasterImageError,
                                 "Invalid image type in RasterImage::copyInto_");
                 break;
         }
     }
     if (needToAllocateNewGWorld || needToAllocateFloatRaster)
     {
         imgOut->allocateRaster2D_(imgOut->getHeight(), imgOut->getWidth());
         imgOut->allocateShiftedRaster2D_(imgOut->getHeight(), imgOut->getWidth(),
                                                                                  imgOut->getTop(), imgOut->getLeft());
     }
         //      the destRect defines the new valid rect of the destination image
         imgOut->setValidRect(destRect);
     delete copyRect;
     if (origin != NULL)
         delete destRect;
 }
RasterImage * RasterImage::createCopy (void) const
Creates a new raster image that is a copy of this image.
Note that this function only copies the valid data of this image. This function is just a simplified version of the grab function, which it calls.
Returns
a copy of this image
See also
grab
Definition at line 859 of file RasterImage.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), grab(), and uriVL::kUnknownError.
Referenced by uriVL::ImageTransformation::translate().
 {
         RasterImage* imgOut = NULL;
         try
         {
                 imgOut = grab(this, this->getValidRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by RasterImage::createCopy");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kUnknownError,
                                                 "Unexpected error in RasterImage::createCopy");
         }
         return imgOut;
 }
RasterImage * RasterImage::createCopy (const RasterImage * imgIn) static
Creates a new raster image that is a copy of the image received as parameter.
Note that this function only copies the valid data of the input image. This function is just a simplified version of the grab function, which it calls.
Parameters
imgIn the image to copy
Returns
a pointer to a new copy of img
See also
grab
Definition at line 881 of file RasterImage.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), grab(), uriVL::kInvalidParameterError, and uriVL::kNullParameterError.
 {
         RasterImage* imgOut = NULL;
         try
         {
                 imgOut = grab(imgIn, imgIn->getValidRect());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by RasterImage::createCopy");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( imgIn == NULL,
                                                 kNullParameterError,
                                                 "Null RasterImage pointer passed to RasterImage::createCopy");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid RasterImage pointer passed to RasterImage::createCopy");
         }
         return imgOut;
 }
virtual void uriVL::RasterImage::deleteRaster2D_ (void) private pure virtual
Deletes the 0-based 2D base raster.
This virtual function must be implemented by child classes.
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_aRGB16, uriVL::RasterImage_HSV, uriVL::RasterImage_RGB, uriVL::RasterImage_HSV24, and uriVL::RasterImage_Lab.
Referenced by copyInto_().
virtual void uriVL::RasterImage::deleteShiftedRaster2D_ (int iLow) private pure virtual
Deletes the 2D shifted base raster.
Parameters
iLow Y coordinate of the image's origin This pure virtual function must be implemented by child classes.
Implemented in uriVL::RasterImage_binary, uriVL::RasterImage_RGBa_F, uriVL::RasterImage_gray_F, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_aRGB16, uriVL::RasterImage_HSV, uriVL::RasterImage_RGB, uriVL::RasterImage_HSV24, and uriVL::RasterImage_Lab.
Referenced by copyInto_().
bool RasterImage::floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
Returns
true if the float raster stores the reference values
See also
hasFloatRaster
Definition at line 1074 of file RasterImage.cpp.
References floatRasterIsReference_, and hasFloatRaster_.
Referenced by uriVL::ColorMedianFilter_F::applyInto(), uriVL::NormalFlowCalculator::applyInto(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_I::applyTo(), uriVL::BackgroundRemover::assignBackground_(), uriVL::RasterImage_gray_F::copyInto(), uriVL::RasterImage_RGBa_F::copyInto(), uriVL::ImageArithmetics::difference(), uriVL::BackgroundRemover_dynamic_MW::setBackground(), and uriVL::BackgroundRemover_dynamic_MW::updateBackground().
 {
     return (hasFloatRaster_ && floatRasterIsReference_);
 }
virtual BaseRasterType uriVL::RasterImage::getBaseRasterType (void) const pure virtual
Returns the image's base raster type.
Returns one of the following values:
- kGrayRaster, for any image based on the 8-bit gray level format
- kaRGB16Raster, for any image based on the 16-bit argb color format
- kRGB24Raster, for any image based on the 24-bit rgb color format
- kaRGB32Raster, for any image based on the 32-bit argb color format
- kRGBa32Raster, for any image based on the 32-bit rgba color format
This method is virtual and should be implemented by the base raster subclasses
Returns
the image's base raster type
Implemented in uriVL::RasterImage_gray, uriVL::RasterImage_RGB, uriVL::RasterImage_binary, uriVL::RasterImage_RGBa, and uriVL::RasterImage_aRGB16.
Referenced by uriVL::PatternMatcher2D::allocateRasters_(), uriVL::PatternMatcher2D_corr::allocateRasters_(), uriVL::PatternMatcher2D_scaledDiff::allocateRasters_(), uriVL::PatternMatcher2D_medianDiff::allocateRasters_(), applyAdditiveNoise(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ZeroCrossingDetector::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::NormalFlowCalculator::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto(), uriVL::ColorThresholdLabeler::applyInto(), uriVL::GrayThresholdLabeler::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ZeroCrossingDetector::applyInto_st(), applySaltAndPepperNoise(), uriVL::MedianFilter_F::applyTo(), uriVL::MedianFilter_I::applyTo(), uriVL::ColorMedianFilter_F::applyTo(), uriVL::ColorMedianFilter_I::applyTo(), uriVL::ColorGaussianFilter_F::applyTo(), uriVL::GaussianFilter_F::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::ColorGaussianFilter_I::applyTo(), uriVL::NonMaximumSuppressor::applyTo_st(), uriVL::BackgroundRemover::assignBackground_(), copyInto_(), uriVL::ImageArithmetics::difference(), uriVL::ActiveContourDetector_balloon::findContour(), getRaster(), getRaster2D(), getShiftedRaster2D(), grab(), handleMiddleDrag(), initImagesAndWarper(), uriVL::RasterImage_aRGB16::localRasterARGB16(), uriVL::RasterImage_gray::localRasterGray(), uriVL::RasterImage_RGBa::localRasterRGBa(), WXGL_IO_Canvas::MakeFake_ImageGS(), WXGL_IO_Canvas::MakeFake_ImageGSF(), WXGL_IO_Canvas::MakeFake_ImageRGBa(), uriVL::PatternMatcher2D::match(), uriVL::PatternMatcher2D_warp::match(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::PatternTracker2DController::PatternTracker2DController(), uriVL::RasterImage_HSV::RasterImage_HSV(), render_(), uriVL::Pattern2D::renderBlobPattern_(), uriVL::Blob::renderInto(), uriVL::ImageTransformation::rotate(), uriVL::BackgroundRemover_dynamic_MW::setBackground(), uriVL::PatternMatcher2D::setImage(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::PatternMatcher2D_warp::setImage(), uriVL::ImageWarper::setImages(), uriVL::PatternMatcher2D_scaledDiff::setPattern(), uriVL::PatternMatcher2D_medianDiff::setPattern(), uriVL::PatternMatcher2D_corr::setPattern(), uriVL::PatternMatcher2D::setPattern(), uriVL::PatternMatcher2D_warp::setPattern(), uriVL::WarpMatchScoreFunctionND::setPattern(), uriVL::BackgroundRemover_dynamic_MW::updateBackground(), uriVL::VideoSource::updateImageRasterStatus_(), uriVL::Pattern2D::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
int RasterImage::getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of bytes on a row of the image
Definition at line 1019 of file RasterImage.cpp.
References uriVL::GraphWorld::getBytesPerRow(), and gworld_.
Referenced by uriVL::RasterImage_RGB::allocateShiftedRaster2D_(), uriVL::RasterImage_RGBa::allocateShiftedRaster2D_(), uriVL::RasterImage_aRGB16::allocateShiftedRaster2D_(), uriVL::RasterImage_gray::allocateShiftedRaster2D_(), and main().
 {
     if (gworld_ != NULL)
         return gworld_->getBytesPerRow( );
     else
         return 0;
 }
const float * RasterImage::getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
For some unknown reason (must have made sense at the time) the conversion coefficients as instance variables for a particular image are gone (along with companion access functions). I Still implement this finction as instance in case these members make it back
Returns
array of coefficients of the conversion to gray
Definition at line 1266 of file RasterImage.cpp.
References defaultConvWeight_.
 {
         //      if (hasIndividualConversionWeights_)
         //              return indivConvWeight_
         //      else
         return defaultConvWeight_;
 }
const float * RasterImage::getDefaultConversionWeights (void) static
Returns the default to-gray conversion coefficients for this image.
Returns
array of default coefficients of the conversion to gray
Definition at line 1274 of file RasterImage.cpp.
References defaultConvWeight_.
Referenced by uriVL::RasterImage_RGBa_F::convertToGray_().
 {
         return defaultConvWeight_;
 }
unsigned int RasterImage::getID (void)
Gives this image's unique id this image's id.
Definition at line 1014 of file RasterImage.cpp.
References id_.
 {
         return id_;
 }
int RasterImage::getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
Returns
pixel depth
Definition at line 1027 of file RasterImage.cpp.
References uriVL::GraphWorld::getPixelDepth(), and gworld_.
Referenced by uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), and uriVL::ColorThresholdLabeler::applyInto_().
 {
     if (gworld_ != NULL)
         return gworld_->getPixelDepth( );
     else
         return 0;
 }
const unsigned char * RasterImage::getRaster (void) const virtual
Returns the base raster as a read-only 1D array.
This method is implemented by the base subclasses of RasterImage, and should be overridden by these classes' own subclasses. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
1D base raster for this image
Reimplemented in uriVL::RasterImage_binary, and uriVL::RasterImage_Lab.
Definition at line 293 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by uriVL::RasterImage_binary::getBw(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_binary::getRaster(), and uriVL::ImageWarper::setImages().
 {
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             return ((RasterImage_gray* ) this)->getGray();
             break;
         case kRGB24Raster:
             return ((RasterImage_RGB* ) this)->getRGB();
             break;
         case kRGBa32Raster:
             return ((RasterImage_RGBa* ) this)->getRGBa();
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getRaster");
             return NULL;
             break;
     }
 }
unsigned char * RasterImage::getRaster (ReadWriteStatus rw) virtual
Returns the base raster as a read-write 1D array.
This method is implemented by the base subclasses of RasterImage, and should be overridden by these classes' own subclasses. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Reimplemented in uriVL::RasterImage_binary.
Definition at line 318 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and uriVL::R_W_ACCESS.
 {
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             return ((RasterImage_gray* ) this)->getGray(R_W_ACCESS);
             break;
         case kRGB24Raster:
             return ((RasterImage_RGB* ) this)->getRGB(R_W_ACCESS);
             break;
         case kRGBa32Raster:
             return ((RasterImage_RGBa* ) this)->getRGBa(R_W_ACCESS);
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getRaster");
             return NULL;
             break;
     }
 }
const unsigned char *const * RasterImage::getRaster2D (void) const virtual
Returns the base raster as a read-only 2D array.
This method is implemented by the base subclasses of RasterImage, and should be overridden by these classes' own subclasses. The 2D base raster array is an array of rows that point to parts of the base 1D raster. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
2D base raster for this image
Reimplemented in uriVL::RasterImage_binary.
Definition at line 344 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by uriVL::SegmentDetector::detect(), uriVL::RasterImage_binary::getBw2D(), uriVL::RasterImage_binary::getRaster2D(), loadImages(), WXGL_IO_Canvas::MakeFake_ImageGS(), WXGL_IO_Canvas::MakeFake_ImageRGBa(), myMenu1(), myMenu2(), uriVL::Pattern2D::renderBlobPattern_(), simpleImageTransform(), and updateState().
 {
     const unsigned char *const* raster = NULL;
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             raster = (static_cast< const RasterImage_gray*>(this))->getGray2D();
             break;
         case kRGB24Raster:
             raster = (static_cast<const RasterImage_RGB*>(this))->getRGB2D();
             break;
         case kRGBa32Raster:
             raster = (static_cast<const RasterImage_RGBa*>(this))->getRGBa2D();
             break;
 //        case kaRGB16Raster:
 //            raster = (static_cast<const RasterImage_aRGB16*>(this))->getARGB2D();
 //            break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getRaster2D");
             break;
     }
     return raster;
 }
unsigned char *const * RasterImage::getRaster2D (ReadWriteStatus rw) virtual
Returns the base raster as a read-write 2D array.
This method is implemented by the base subclasses of RasterImage, and should be overridden by these classes' own subclasses. The 2D base raster array is an array of rows that point to parts of the base 1D raster. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Reimplemented in uriVL::RasterImage_binary.
Definition at line 376 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and uriVL::R_W_ACCESS.
 {
     unsigned char       *const* raster = NULL;
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             raster = (static_cast<RasterImage_gray*>(this))->getGray2D(R_W_ACCESS);
             break;
         case kRGB24Raster:
             raster = (static_cast<RasterImage_RGB*>(this))->getRGB2D(R_W_ACCESS);
             break;
         case kRGBa32Raster:
             raster = (static_cast<RasterImage_RGBa*>(this))->getRGBa2D(R_W_ACCESS);
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getRaster2D");
             break;
     }
     return raster;
 }
const unsigned char *const * RasterImage::getShiftedRaster2D (void) const virtual
Returns the shifted base raster as a read-only 2D array.
The shifted raster has index bounds defined by the image's rectangle. This method simply calls getShiftedRGB2D().
Returns
shifted 2D base raster for this image
Reimplemented in uriVL::RasterImage_binary.
Definition at line 405 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by applyAdditiveNoise(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), applySaltAndPepperNoise(), CreateImageAndField(), uriVL::ImageArithmetics::difference_(), uriVL::RasterImage_binary::getShiftedBw2D(), uriVL::RasterImage_binary::getShiftedRaster2D(), handleMiddleDrag(), loadImage(), uriVL::PatternTracker2D::mergeBlob_(), uriVL::PatternTracker2DController::scaleImage(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::ZeroCrossingDetector::showSignAsColor(), uriComputerVision::BackgroundRemoverTester::test0_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::RasterImage_binary::updateRaster_(), and uriVL::RasterImage_gray::writeInto_().
 {
     const unsigned char *const* raster = NULL;
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             raster = (static_cast<const RasterImage_gray*>(this))->getShiftedGray2D();
             break;
         case kRGB24Raster:
             raster = (static_cast<const RasterImage_RGB*>(this))->getShiftedRGB2D();
             break;
         case kRGBa32Raster:
             raster = (static_cast<const RasterImage_RGBa*>(this))->getShiftedRGBa2D();
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getShiftedRaster2D");
             break;
     }
     return raster;
 }
unsigned char *const * RasterImage::getShiftedRaster2D (ReadWriteStatus rw) virtual
Returns the shifted base raster as a read-write 2D array.
The shifted raster has index bounds defined by the image's rectangle. This method simply calls getShiftedRGB2D().
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Reimplemented in uriVL::RasterImage_binary.
Definition at line 433 of file RasterImage.cpp.
References FAIL_CONDITION, getBaseRasterType(), uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and uriVL::R_W_ACCESS.
 {
     unsigned char* const* raster = NULL;
     switch (getBaseRasterType())
     {
         case kGrayRaster:
             raster = (static_cast<RasterImage_gray*>(this))->getShiftedGray2D(R_W_ACCESS);
             break;
         case kRGB24Raster:
             raster = (static_cast<RasterImage_RGB*>(this))->getShiftedRGB2D(R_W_ACCESS);
             break;
         case kRGBa32Raster:
             raster = (static_cast<RasterImage_RGBa*>(this))->getShiftedRGBa2D(R_W_ACCESS);
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage::getShiftedRaster2D");
             break;
     }
     return raster;
 }
long RasterImage::getTimeStamp (void) const
Get the time stamp of this image.
The time stamp only really makes sense when the image is coming from a movie file or frame grabber.
Returns
the time stamp of this image
See also
setTimeStamp
Definition at line 972 of file RasterImage.cpp.
References timeStamp_.
 {
     return timeStamp_;
 }
long RasterImage::getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of bytes in the image
Definition at line 1035 of file RasterImage.cpp.
References uriVL::GraphWorld::getTotalByteCount(), and gworld_.
Referenced by uriVL::Blob::renderInto().
 {
     if (gworld_ != NULL)
         return gworld_->getTotalByteCount( );
     else
         return 0;
 }
RasterImage * RasterImage::grab (const ImageRect * rect) const
Writes into a new raster image the part of this image specified by a rectangle.
Returns NULL if the destination rectangle is not contained by the source image.
Parameters
rect specifies the part of the source to grab from
Returns
the part of this image specified by rect
Definition at line 787 of file RasterImage.cpp.
Referenced by createCopy(), grab(), uriVL::PatternTracker2D::grabImage_(), loadImages(), uriVL::Pattern2D::Pattern2D(), and uriVL::Pattern2D::setPattern().
 {
     return grab(this, rect, NULL);
 }
RasterImage * RasterImage::grab (const ImageRect * rect, const ImagePoint * origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
Returns NULL if the destination rectangle is not contained by the source image. If the origin point is NULL, just uses the origin of the grabbing rectangle.
Parameters
rect specifies the part of the source to grab from
origin the point to use as origin for the new image's valid data rectangle's upper-left corner.
Returns
the part of this image specified by rect
Definition at line 792 of file RasterImage.cpp.
References grab().
 {
     return grab(this, rect, origin);
 }
RasterImage * RasterImage::grab (const RasterImage * imgIn, const ImageRect * rect) static
Writes into a new raster image the part of the input image specified by a rectangle.
Returns null if the destination rectangle is not contained by the source image.
Parameters
imgIn the image to grab from
rect specifies the part of the source to write into the destination
Returns
the part of the input image specified by rect
Definition at line 798 of file RasterImage.cpp.
References grab().
 {
     return grab(imgIn, theRect, NULL);
 }
RasterImage * RasterImage::grab (const RasterImage * imgIn, const ImageRect * rect, const ImagePoint * origin) static
Writes into a new raster image the part of the input image specified by a rectangle.
Returns null if the destination rectangle is not contained by the source image.
Parameters
imgIn the image to grab from
rect specifies the part of the source to write into the destination
origin the point to use as origin for the new image's valid data rectangle's upper-left corner.
Returns
the part of the input image specified by rect
Definition at line 803 of file RasterImage.cpp.
References uriVL::DrawableObject2D::contains(), copyInto(), FAIL_CONDITION, getBaseRasterType(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, RasterImage_binary, RasterImage_gray, RasterImage_RGB, and RasterImage_RGBa.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter in RI::grab");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage::grab");
     RasterImage* grabImg = NULL;
     if (imgIn->contains(theRect))
     {
         const ImageRect* grabRect;
         if (origin == NULL)
             grabRect = theRect;
         else
             grabRect = new ImageRect(origin->getX(), origin->getY(),
                                      theRect->getWidth(), theRect->getHeight());
         switch (imgIn->getBaseRasterType())
         {
             case kBinaryRaster:
                 grabImg = new RasterImage_binary(grabRect);
                 break;
             case kGrayRaster:
                 grabImg = new RasterImage_gray(grabRect);
                 break;
             case kRGB24Raster:
                 grabImg = new RasterImage_RGB(grabRect);
                 break;
             case kRGBa32Raster:
                 grabImg = new RasterImage_RGBa(grabRect);
                 break;
             default:
                 FAIL_CONDITION( true,
                                 kRasterImageError,
                                 "Invalid image type in RasterImage::grab");
                 break;
         }
         imgIn->copyInto(grabImg, theRect, origin);
         if (origin != NULL)
             delete grabRect;
     }
     return grabImg;
 }
bool RasterImage::graphWorldIsNull_ (void) const protected
Indicates whether the GraphWorld was allocated for this object.
Returns
true if the GraphWorld for this object is null
Definition at line 1121 of file RasterImage.cpp.
References gworld_.
Referenced by uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_gray_F::getGray2D(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_HSV::getRGBa2D(), uriVL::RasterImage_gray_F::getShiftedGray2D(), uriVL::RasterImage_HSV::getShiftedRGBa2D(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_RGBa_F::setBoundRect_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), and uriVL::RasterImage_RGBa_F::updateRaster_().
 {
         return (gworld_ == NULL);
 }
bool RasterImage::graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
Could be false for a raster image that stores its own raster outside of the GraphWorld, eg RasterImage_HSV or RasterImage_gray_F
Returns
true if the raster stored in the GraphWorld stores the reference
See also
floatRasterIsReference
Definition at line 1058 of file RasterImage.cpp.
References gworldIsReference_.
Referenced by copyInto_(), uriVL::RasterImage_RGBa_F::getBlueF(), uriVL::RasterImage_RGBa_F::getBlueF2D(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_gray_F::getGray2D(), uriVL::RasterImage_gray_F::getGrayF(), uriVL::RasterImage_gray_F::getGrayF2D(), uriVL::RasterImage_RGBa_F::getGreenF(), uriVL::RasterImage_RGBa_F::getGreenF2D(), uriVL::RasterImage_HSV::getHue(), uriVL::RasterImage_HSV::getHue2D(), uriVL::RasterImage_RGBa_F::getRedF(), uriVL::RasterImage_RGBa_F::getRedF2D(), uriVL::RasterImage_RGBa_F::getRGBa(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa2D(), uriVL::RasterImage_HSV::getRGBa2D(), uriVL::RasterImage_HSV::getSat(), uriVL::RasterImage_HSV::getSat2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray_F::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_HSV::getShiftedHue2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_RGBa_F::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::RasterImage_HSV::getVal(), uriVL::RasterImage_HSV::getVal2D(), uriVL::Pattern2D::renderBlobPattern_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::RasterImage_gray_F::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return gworldIsReference_;
 }
bool RasterImage::hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
Returns
true if the raster images stores a float raster
See also
floatRasterIsReference
Definition at line 1043 of file RasterImage.cpp.
References hasFloatRaster_.
Referenced by uriVL::MedianFilter_F::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::MedianFilter_I::applyTo(), uriVL::ColorMedianFilter_I::applyTo(), uriVL::ColorImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_I::applyTo(), uriVL::ImageGradient_Sobel::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::BackgroundRemover::assignBackground_(), copyInto_(), uriVL::ImageArithmetics::difference(), WXGL_IO_Canvas::MakeFake_ImageGSF(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::BackgroundRemover_dynamic_MW::setBackground(), uriVL::BackgroundRemover_dynamic_MW::updateBackground(), uriVL::VideoSource::updateImageRasterStatus_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return hasFloatRaster_;
 }
void RasterImage::lockPixels (void * key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
The object that calls this function is meant to pass its own adress as parameter so that it can unlock the image later.
Parameters
key address/key that must be passed later to unlock the image
Definition at line 944 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::kInvalidLockAccess, pixmapIsLocked_, and pixmapKey_.
 {
     FAIL_CONDITION( pixmapIsLocked_,
                     kInvalidLockAccess,
                     "Attempt to lock pixels of an already-locked RasterImage");
     pixmapKey_ = key;
     pixmapIsLocked_ = true;
 }
void RasterImage::lockProperties (void * key)
Locks the geometry and pixel depth of the image.
The object that calls this function is meant to pass its own adress as parameter so that it can unlock the image later.
Parameters
key address/key that must be passed later to unlock the image
Definition at line 917 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::kInvalidLockAccess, propertiesAreLocked_, and propertiesKey_.
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kInvalidLockAccess,
                     "Attempt to lock properties of an already-locked RasterImage");
     propertiesKey_ = key;
     propertiesAreLocked_ = true;
 }
const RasterImage & RasterImage::operator= (const RasterImage & img) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
img pointer to the RasterImage object to copy
Definition at line 278 of file RasterImage.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
{
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage copy operator not implemented");
         return *this;
 }
void RasterImage::overlay (const RasterImage * imgIn)
Writes another image over part of this image.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the images' valid data rectangles.
Parameters
imgIn the image to write over (part of) this image
Definition at line 640 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and writeInto().
Referenced by applyOverlays().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL source raster image passed as parameter in RI::overlay");
     imgIn->writeInto(this, imgIn->getValidRect(), NULL);
 }
void RasterImage::overlay (const RasterImage * imgIn, const ImagePoint * origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgIn the image to write into
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Definition at line 649 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and writeInto().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL source raster image passed as parameter in RI::overlay");
     imgIn->writeInto(this, imgIn->getValidRect(), origin);
 }
void RasterImage::overlay (const RasterImage * imgIn, const ImageRect * rect)
Writes over this image the part of another image specified by a rectangle.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgIn the image to write into
rect specifies the part of the source to write into the destination
Definition at line 658 of file RasterImage.cpp.
References writeInto().
 {
     imgIn->writeInto(this, theRect, NULL);
 }
void RasterImage::overlay (const RasterImage * imgIn, const ImageRect * rect, const ImagePoint * origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgIn the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Definition at line 663 of file RasterImage.cpp.
References writeInto().
 {
     imgIn->writeInto(this, theRect, origin);
 }
bool RasterImage::pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
Returns
true if the RasterImage object's pixmap is locked
Definition at line 965 of file RasterImage.cpp.
References pixmapIsLocked_.
 {
         return pixmapIsLocked_;
 }
bool RasterImage::propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
Returns
true if the RasterImage object's properties are locked
Definition at line 938 of file RasterImage.cpp.
References propertiesAreLocked_.
Referenced by uriVL::RasterImage_RGBa_F::setBoundRect_().
 {
         return propertiesAreLocked_;
 }
bool RasterImage::referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
When the reference raster is modified, other rasters stored by the image object my have to be modified. For example, for a RasterImage_HSV image, if the HSV rasters are the reference and are modified, the RGBa raster would have to be updated prior to rendering the image.
Returns
true if the reference raster has changed.
See also
referenceHasChanged_
Definition at line 1063 of file RasterImage.cpp.
References referenceHasChanged_.
Referenced by uriVL::VectorField::computeNormAndPhase(), uriVL::VectorField::computeNormSquared(), uriVL::VectorField::computeNormSquaredAndPhase(), uriVL::VectorField::computePhase(), uriVL::RasterImage_RGBa_F::getBlueF(), uriVL::RasterImage_RGBa_F::getBlueF2D(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_gray_F::getGray2D(), uriVL::RasterImage_gray_F::getGrayF(), uriVL::RasterImage_gray_F::getGrayF2D(), uriVL::RasterImage_RGBa_F::getGreenF(), uriVL::RasterImage_RGBa_F::getGreenF2D(), uriVL::RasterImage_HSV::getHue(), uriVL::RasterImage_HSV::getHue2D(), uriVL::RasterImage_RGBa_F::getRedF(), uriVL::RasterImage_RGBa_F::getRedF2D(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_HSV::getSat(), uriVL::RasterImage_HSV::getSat2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray_F::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_HSV::getShiftedHue2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::RasterImage_HSV::getVal(), uriVL::RasterImage_HSV::getVal2D(), uriVL::Pattern2D::renderBlobPattern_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_gray_F::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return referenceHasChanged_;
 }
void RasterImage::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private virtual
Renders the RasterImage's base raster at the depth and location specified.
Renders the RasterImage's base raster, using OpenGL's glDrawPixels function. The rendering is done at depth specified. The latter should be chosen so that the image lies within the frustum and vector graphics can be overlaid. The rendering is done at the location specified. This means that the image's bounding rectangle's upper left corner will appear at the location specified by the point received as parameter.
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the image should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
the gray raster (re-binarize it).
Implements uriVL::DrawableObject2D.
Definition at line 1144 of file RasterImage.cpp.
References uriVL::GraphWorld::draw(), getBaseRasterType(), uriVL::DrawableObject2D::getRenderingScaleX(), uriVL::DrawableObject2D::getRenderingScaleY(), gworld_, gworldIsReference_, uriVL::kBinaryRaster, referenceHasChanged_, and updateRaster_().
 {
     //--------------------------------------------------------------
     //  Part 1: make sure that what we draw is up to date
     //--------------------------------------------------------------
     //  Binary images are a special case.  OpenGL cannot draw QD binary
     //  raster, so we need to use the gray raster instead.
     bool    binaryRaster = (getBaseRasterType() == kBinaryRaster);
     if (binaryRaster)
     {
         //  if the gworld is the reference and has been modified, or
         //  the gray raster has been modified, update
         /// the gray raster (re-binarize it).
         if (gworldIsReference_ || referenceHasChanged_)
             updateRaster_( );
     }
     else
         //  For other image types, the base raster is the one to draw, so if it
         //  does not already exist, create it.  If it is not up-to-date, update it.
         if ( (gworld_ == NULL) || (!gworldIsReference_ && referenceHasChanged_) )
             updateRaster_( );
     //--------------------------------------------------------------
     //  Part 2: render the raster
     //--------------------------------------------------------------
     //  I apply a -1 scaling vertical scaling to my image so that it gets displayed
     //  with the right side up.
     glPushMatrix();
     glLoadIdentity();
     //subtracting .1f to make work with unix systems
     //otherwise the image starts 'off the screen' and
     //will not render at all
         #if URIVL_OS_UNIX
                 glRasterPos3f(scaledLeft, scaledTop - 0.1f, theZ);
     #else
                 glRasterPos3f(scaledLeft, scaledTop, theZ);
         #endif
         glPixelZoom(getRenderingScaleX(), -getRenderingScaleY());
     //  for binary images, really render the gray raster
     if (binaryRaster)
     {
         GraphWorld  *grayWorld = ((static_cast<const RasterImage_binary*>(this))->getGrayRasterImage())->gworld_;
         (grayWorld)->draw();
     }
     else
         gworld_->draw();
     glPopMatrix();
 }
void RasterImage::requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
A RasterImage object can be store more than one raster. For example, a RasterImage_HSV will store hue, saturation, and value rasters, and possibly an RGBa raster as well. One of the rasters (HSV or RGBa) must be designated as the reference raster. It is possible that one of the image's rasters be modified by some image processing operation. Whenever the user requests a pointer to a non-reference raster, we must verify if this raster must be updated according to the values of the reference raster.
Definition at line 1079 of file RasterImage.cpp.
References referenceHasChanged_.
Referenced by uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::VectorField::computeNorm(), and uriVL::Pattern2D::renderBlobPattern_().
 {
     referenceHasChanged_ = true;
 }
void RasterImage::restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
Parameters
bufferRec buffer record to add information to Restores the previous "current GraphWorld".
QuickDraw (and therefore QuickTime) draws into whatever was defined as the "current GWorld." This class function resores the "current GWorld" to its previous value".
See also
setAsCurrentGraphWorld
setAsMovieGraphWorld
Definition at line 1241 of file RasterImage.cpp.
References gworld_, gworldIsReference_, referenceHasChanged_, uriVL::GraphWorld::restoreGraphWorld(), and updateRaster_().
 {
     if ( (gworld_ == NULL) || (!gworldIsReference_ && referenceHasChanged_) )
         updateRaster_( );
     gworld_->restoreGraphWorld( );
 }
void RasterImage::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implements uriVL::DrawableObject2D.
Definition at line 990 of file RasterImage.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void RasterImage::setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
QuickDraw (and therefore QuickTime) draws into whatever was defined as the "current GWorld". This member function defines its RasterImage's base raster as the destination for such operations.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
See also
restoreGraphWorld
Definition at line 1207 of file RasterImage.cpp.
References gworld_, gworldIsReference_, referenceHasChanged_, uriVL::GraphWorld::setGraphWorld(), and updateRaster_().
 {
     if ( (gworld_ == NULL) || (!gworldIsReference_ && referenceHasChanged_) )
         updateRaster_( );
     gworld_->setGraphWorld(gworld_);
 }
void RasterImage::setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
When a movie is played or live video is grabbed, a GWorld must be set as the destination for the video stream. This member function allows to define the RasterImage's base raster as the destination for the video stream, so as to avoid unnecessary blitting between buffers.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
Parameters
grabber the FrameGrabber that will play into this object
Returns
error code (0 if all OK)
See also
restoreGraphWorld Sets this RasterImage as destination for a graphic importer.
When data is read from an image file, a GWorld must be set as the destination for the graphic importer. This member function allows to define the RasterImage's base raster as the destination for the importer, so as to avoid unnecessary blitting between buffers.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
Parameters
importer the graphic importer that will draw into this object
See also
restoreGraphWorld
Definition at line 1233 of file RasterImage.cpp.
References gworld_, gworldIsReference_, referenceHasChanged_, uriVL::GraphWorld::setAsImporterGraphWorld(), and updateRaster_().
 {
     if ( (gworld_ == NULL) || (!gworldIsReference_ && referenceHasChanged_) )
         updateRaster_( );
     gworld_->setAsImporterGraphWorld(theImporter);
 }
void RasterImage::setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
When a movie is played or live video is grabbed, a GWorld must be set as the destination for the video stream. This member function allows to define the RasterImage's base raster as the destination for the video stream, so as to avoid unnecessary blitting between buffers.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
Parameters
theMovie the movie that will play into this object
See also
restoreGraphWorld
Definition at line 1215 of file RasterImage.cpp.
References gworld_, gworldIsReference_, referenceHasChanged_, uriVL::GraphWorld::setAsMovieGraphWorld(), and updateRaster_().
 {
     if ( (gworld_ == NULL) || (!gworldIsReference_ && referenceHasChanged_) )
         updateRaster_( );
     gworld_->setAsMovieGraphWorld(theMovie);
 }
void RasterImage::setDefaultConversionWeights (const float redW, const float greenW, const float blueW) static
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
The function uses the relative values of these weights and sets normalized [0..1] weights.
Parameters
redW weight of the red component
greenW weight of the green component
blueW weight of the blue component
Definition at line 1285 of file RasterImage.cpp.
References defaultConvWeight_.
 {
     //  we can't trust the user to provide normalized weights, so we have to do it here
     float   sumW = redW + greenW + blueW;
     defaultConvWeight_[0] = redW / sumW;
     defaultConvWeight_[1] = greenW / sumW;
     defaultConvWeight_[2] = blueW / sumW;
 }
void RasterImage::setDefaultGrayConversionMode (const ConversionToGrayMode theMode) static
Sets the default mode for color to gray conversion for the entire RasterImage class.
Parameters
theMode new default conversion mode for the class
Definition at line 1280 of file RasterImage.cpp.
References defaultGrayConv_.
 {
     defaultGrayConv_ = theMode;
 }
void RasterImage::setFloatRasterAsReference_ (void) const protected
Sets this image's float raster as the reference (fails if it was NULL)
Definition at line 1100 of file RasterImage.cpp.
References FAIL_CONDITION, floatRasterIsReference_, gworldIsReference_, hasFloatRaster_, uriVL::kNullRasterError, and referenceHasChanged_.
Referenced by uriVL::RasterImage_RGBa_F::getBlueF(), uriVL::RasterImage_RGBa_F::getBlueF2D(), uriVL::RasterImage_gray_F::getGrayF(), uriVL::RasterImage_gray_F::getGrayF2D(), uriVL::RasterImage_RGBa_F::getGreenF(), uriVL::RasterImage_RGBa_F::getGreenF2D(), uriVL::RasterImage_RGBa_F::getRedF(), uriVL::RasterImage_RGBa_F::getRedF2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray_F::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::VideoSource::updateImageRasterStatus_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     FAIL_CONDITION( !hasFloatRaster_,
                     kNullRasterError,
                     "RasterImage object lacks a float raster to set as reference");
         if (!floatRasterIsReference_)
                 referenceHasChanged_ = true;
     gworldIsReference_ = false;
     floatRasterIsReference_ = true;
 }
void RasterImage::setGraphWorldAsReference_ (void) const protected
Sets this image's gworld as the reference (and allocates if it was NULL)
Should be overridden by subclasses that allocate and maintain their own raster(s), e.g. RasterImage_HSV
See also
graphWorldIsReference
Definition at line 1084 of file RasterImage.cpp.
References floatRasterIsReference_, gworld_, gworldIsReference_, and referenceHasChanged_.
Referenced by uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_gray_F::getGray2D(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::VideoSource::updateImageRasterStatus_(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     //  this should never happen.  I am considering making a FAIL_CONDITION
     if (gworld_ == NULL)
     {
 //              if (isRef
 //        updateRaster_( );
     }
         if (!gworldIsReference_)
                 referenceHasChanged_ = true;
         gworldIsReference_ = true;
         floatRasterIsReference_ = false;
 }
void RasterImage::setHasFloatRaster_ (bool hasRaster) protected
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
Parameters
hasRaster true if this RasterImage has a float raster
Definition at line 1048 of file RasterImage.cpp.
References hasFloatRaster_.
Referenced by uriVL::RasterImage_gray_F::allocateRaster2D_(), uriVL::RasterImage_RGBa_F::allocateRaster2D_(), uriVL::RasterImage_gray_F::deleteRaster2D_(), uriVL::RasterImage_RGBa_F::deleteRaster2D_(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), and uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F().
 {
     hasFloatRaster_ = hasRaster;
 }
void RasterImage::setHasOtherRaster_ (bool hasRaster) protected
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
binary or HSV (false by default)
Parameters
hasRaster true if this RasterImage has another raster
Definition at line 1053 of file RasterImage.cpp.
References hasOtherRaster_.
Referenced by uriVL::RasterImage_binary::RasterImage_binary(), and uriVL::RasterImage_HSV::RasterImage_HSV().
 {
     hasOtherRaster_ = hasRaster;
 }
void RasterImage::setOtherRasterAsReference_ (void) const protected
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
Definition at line 1113 of file RasterImage.cpp.
References floatRasterIsReference_, gworldIsReference_, and referenceHasChanged_.
Referenced by uriVL::RasterImage_binary::getBw(), uriVL::RasterImage_binary::getBw2D(), uriVL::RasterImage_binary::getGrayRasterImage(), uriVL::RasterImage_binary::getRaster(), uriVL::RasterImage_binary::getRaster2D(), uriVL::RasterImage_binary::getShiftedBw2D(), uriVL::RasterImage_binary::getShiftedRaster2D(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_HSV::setHsvAsReference(), uriVL::RasterImage_gray_F::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
         referenceHasChanged_ = true;
     gworldIsReference_ = false;
     floatRasterIsReference_ = false;
 }
void RasterImage::setReferenceHasChanged_ (bool hasChanged) const protected
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
Parameters
hasChanged new value to assign to referenceHasChanged_
Definition at line 1068 of file RasterImage.cpp.
References referenceHasChanged_.
Referenced by uriVL::RasterImage_RGBa_F::getBlueF(), uriVL::RasterImage_RGBa_F::getBlueF2D(), uriVL::RasterImage_gray_F::getGray(), uriVL::RasterImage_gray_F::getGray2D(), uriVL::RasterImage_gray_F::getGrayF(), uriVL::RasterImage_gray_F::getGrayF2D(), uriVL::RasterImage_binary::getGrayRasterImage(), uriVL::RasterImage_RGBa_F::getGreenF(), uriVL::RasterImage_RGBa_F::getGreenF2D(), uriVL::RasterImage_RGBa_F::getRedF(), uriVL::RasterImage_RGBa_F::getRedF2D(), uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::RasterImage_gray_F::getShiftedGray2D(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::VideoSource::updateImageRasterStatus_(), uriVL::RasterImage_HSV::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     referenceHasChanged_ = hasChanged;
 }
void RasterImage::setTimeStamp (long timeStamp)
Sets the time stamp of this image.
The time stamp only really makes sense when the image is coming from a movie file or frame grabber.
Parameters
timeStamp the new time stamp of this image
See also
getTimeStamp
Definition at line 977 of file RasterImage.cpp.
References timeStamp_.
 {
     timeStamp_ = timeStamp;
 }
void RasterImage::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a raster image could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the vector field's bounding rectangle
May be overridden by child classes that have other rasters than their base raster.
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Reimplemented in uriVL::RasterImage_binary.
Definition at line 1136 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::kAccessToLockedData, and propertiesAreLocked_.
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
 }
void RasterImage::unlockPixels (void * key)
Unlocks the pixel map of the image.
Only the address/key that was used to lock the image can unlock it.
Parameters
key address/key that earlier locked the image
Definition at line 953 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::kInvalidLockAccess, pixmapIsLocked_, and pixmapKey_.
 {
     FAIL_CONDITION( !pixmapIsLocked_,
                     kInvalidLockAccess,
                     "Attempt to unlock pixels on an already unlocked image");
     FAIL_CONDITION( pixmapIsLocked_ && (key != pixmapKey_),
                     kInvalidLockAccess,
                     "Attempt to unlock pixels with incorrect key");
     pixmapIsLocked_ = false;
 }
void RasterImage::unlockProperties (void * key)
Unlocks the geometry and pixel depth of the image.
Only the address/key that was used to lock the image can unlock it.
Parameters
key address/key that earlier locked the image
Definition at line 926 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::kInvalidLockAccess, propertiesAreLocked_, and propertiesKey_.
 {
     FAIL_CONDITION( !propertiesAreLocked_,
                     kInvalidLockAccess,
                     "Attempt to unlock pixels on an already unlocked image");
     FAIL_CONDITION( propertiesAreLocked_ && (key != propertiesKey_),
                     kInvalidLockAccess,
                     "Attempt to unlock pixels with incorrect key");
     propertiesAreLocked_ = false;
 }
virtual void uriVL::RasterImage::updateRaster_ (void) const private pure virtual
Updates the image's base raster (if it is not the reference).
This method is virtual and is implemented by the base subclasses (RasterImage_gray, RasterImage_rgb16, RasterImage_RGB, RasterImage_RGBa). Updates the image's base raster stored in the GraphWorld of this RasterImage object, if the base raster was not the reference raster. If the base raster had not been allocated it will be allocated and initialized.
Implemented in uriVL::RasterImage_RGBa_F, uriVL::RasterImage_binary, uriVL::RasterImage_gray_F, uriVL::RasterImage_HSV, uriVL::RasterImage_RGBa, uriVL::RasterImage_gray, uriVL::RasterImage_RGB, and uriVL::RasterImage_aRGB16.
Referenced by render_(), restoreGraphWorld(), setAsCurrentGraphWorld(), setAsImporterGraphWorld(), and setAsMovieGraphWorld().
void RasterImage::writeInto (RasterImage * imgOut) const
Writes this image into another image.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the images' valid data rectangles.
Parameters
imgOut the image to write into
Definition at line 673 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyOverlays(), initImagesAndWarper(), overlay(), uriVL::Pattern2D::writeInto(), and writeInto().
 {
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter in RI::writeInto");
     writeInto(imgOut, getValidRect(), NULL);
 }
void RasterImage::writeInto (RasterImage * imgOut, const ImageRect * rect) const
Writes into another image the part of this image specified by a rectangle.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
Definition at line 682 of file RasterImage.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and writeInto_().
 {
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter in RI::writeInto");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage::writeInto");
     //  the copy rectangle must be entirely contained within this image's valid
     //  data rectangle
     FAIL_CONDITION( !this->contains(theRect),
                     kInvalidRectangleError,
                     "the copy rectangle is not containerd by the source image in RI::writeInto");
     //  We only write in the intersection of theREct and of the destination's valid
     //  data rectangle.
     ImageRect* writeRect = ImageRect::intersection(imgOut->getValidRect(), theRect);
     //  if writeRect is empty, no need to do anything (and no error)
     if (writeRect != NULL)
     {
         writeInto_(imgOut, writeRect, NULL);
         delete writeRect;
     }
 }
void RasterImage::writeInto (RasterImage * imgOut, const ImagePoint * origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the images' valid data rectangles.
Parameters
imgOut the image to write into
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Definition at line 710 of file RasterImage.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and writeInto().
 {
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter in RI::writeInto");
     writeInto(imgOut, getValidRect(), origin);
 }
void RasterImage::writeInto (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Definition at line 719 of file RasterImage.cpp.
References uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::ImageRect::translate(), and writeInto_().
 {
     FAIL_CONDITION(     imgOut == NULL,
                     kNullRasterImageError,
                     "NULL output raster image passed as parameter in RI::writeInto");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage::writeInto");
     //  the copy rectangle must be entirely contained within this image's valid
     //  data rectangle
     FAIL_CONDITION( !this->contains(theRect),
                     kInvalidRectangleError,
                     "the copy rectangle is not containerd by the source image in RI::writeInto");
     //  We only write in the intersection of theRect and of the destination's valid
     //  data rectangle.
     ImageRect* destRect = NULL;
         ImageRect* writeRect = NULL;
     ImagePoint* trueOrigin = NULL;
     //  If no origin was specified, then we only have to make sure that we will copy
     //  the data into a rectangle that is within the destination's valid data rectangle
     if (origin == NULL)
         writeRect = ImageRect::intersection(imgOut->getValidRect(), theRect);
     //  If an origin was specified, then we may not have to copy the entire rectangle
     else
     {
         //  first determine the actual destination rectangle, that is, the one that
         //  will be written into
         destRect = new ImageRect(origin->getX(), origin->getY(),
                                  theRect->getWidth(), theRect->getHeight());
         writeRect = ImageRect::intersection(imgOut->getBoundRect(), destRect);
         if (writeRect != NULL)
         {
             //  the upper-left corner of that rectangle is the "true" origin.  It is a point
             //  on the border of the destination image's valid data rectangle
             trueOrigin = new ImagePoint(writeRect->getLeft(), writeRect->getTop());
             //  the rectangle to grab data from in this image has the same dimensions as
             //  writeRect.  Its UL corner is obtained by translating the UL corner of
             //  theRect by (trueOrigin - origin)
             writeRect->translate(theRect->getLeft() - origin->getX(),
                                        theRect->getTop() - origin->getY());
         }
     }
     //  if writeRect is empty, no need to do anything (and no error)
     if (writeRect != NULL)
     {
         writeInto_(imgOut, writeRect, trueOrigin);
         delete writeRect;
     }
     if (destRect != NULL)
         delete destRect;
     if (trueOrigin != NULL)
         delete trueOrigin;
 }
virtual void uriVL::RasterImage::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const private pure virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner
Implemented in uriVL::RasterImage_RGBa_F, uriVL::RasterImage_binary, uriVL::RasterImage_gray_F, uriVL::RasterImage_gray, uriVL::RasterImage_RGBa, uriVL::RasterImage_RGB, and uriVL::RasterImage_aRGB16.
Referenced by writeInto().
Friends And Related Function Documentation
friend class _FrameGrabber_libvidcap friend
Definition at line 1164 of file RasterImage.h.
friend class DrawableObject2D friend
Definition at line 1146 of file RasterImage.h.
friend class Pattern2D friend
Definition at line 1157 of file RasterImage.h.
friend class RasterImage_aRGB16 friend
Definition at line 1155 of file RasterImage.h.
friend class RasterImage_binary friend
Definition at line 1148 of file RasterImage.h.
Referenced by grab().
friend class RasterImage_gray friend
Definition at line 1149 of file RasterImage.h.
Referenced by uriVL::RasterImage_binary::getGrayRasterImage(), grab(), uriVL::RasterImage_binary::RasterImage_binary(), and uriVL::RasterImage_binary::updateRaster_().
friend class RasterImage_gray_F friend
Definition at line 1150 of file RasterImage.h.
friend class RasterImage_HSV friend
Definition at line 1154 of file RasterImage.h.
friend class RasterImage_RGB friend
Definition at line 1151 of file RasterImage.h.
Referenced by grab().
friend class RasterImage_RGBa friend
Definition at line 1152 of file RasterImage.h.
Referenced by grab().
friend class RasterImage_RGBa_F friend
Definition at line 1153 of file RasterImage.h.
friend class VideoSource friend
Definition at line 1159 of file RasterImage.h.
Member Data Documentation
float RasterImage::defaultConvWeight_ = {1.f/3.f, 1.f/3.f, 1.f/3.f} static private
Weights used for the red, green, and blue channels if the default conversion algorithm for this image is kWeightedAverageConversion.
See also
defaultGrayConv_
Definition at line 868 of file RasterImage.h.
Referenced by uriVL::RasterImage_aRGB16::convertToGray(), uriVL::RasterImage_RGB::convertToGray(), uriVL::RasterImage_RGBa::convertToGray(), getConversionWeights(), getDefaultConversionWeights(), and setDefaultConversionWeights().
ConversionToGrayMode RasterImage::defaultGrayConv_ = kAverageConversion static private
Code for the default algorithm for conversion to gray.
An image instance can override this default mode by setting its grayConv_ field to an other value.
See also
hasIndivGrayConvMode_
Definition at line 860 of file RasterImage.h.
Referenced by setDefaultGrayConversionMode(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
bool uriVL::RasterImage::floatRasterIsReference_ mutable private
True when the RasterImage stores a float raster and that raster is the reference.
Definition at line 811 of file RasterImage.h.
Referenced by floatRasterIsReference(), setFloatRasterAsReference_(), setGraphWorldAsReference_(), setOtherRasterAsReference_(), uriVL::RasterImage_gray::updateRaster_(), and uriVL::RasterImage_RGBa::updateRaster_().
GraphWorld* uriVL::RasterImage::gworld_ private
Stores the base raster for this image.
Not necessarily allocated.
Definition at line 786 of file RasterImage.h.
Referenced by uriVL::RasterImage_RGB::allocateGraphWorld_(), uriVL::RasterImage_RGBa::allocateGraphWorld_(), uriVL::RasterImage_gray::allocateGraphWorld_(), uriVL::RasterImage_aRGB16::allocateGraphWorld_(), uriVL::RasterImage_binary::allocateGraphWorld_(), uriVL::RasterImage_RGB::allocateRaster2D_(), uriVL::RasterImage_RGBa::allocateRaster2D_(), uriVL::RasterImage_aRGB16::allocateRaster2D_(), uriVL::RasterImage_gray::allocateRaster2D_(), uriVL::RasterImage_gray::allocateShiftedRaster2D_(), copyInto_(), uriVL::RasterImage_aRGB16::getARGB(), uriVL::RasterImage_aRGB16::getARGB2D(), getBytesPerRow(), uriVL::RasterImage_gray::getGray(), uriVL::RasterImage_gray::getGray2D(), getPixelDepth(), uriVL::RasterImage_RGB::getRGB(), uriVL::RasterImage_RGB::getRGB2D(), uriVL::RasterImage_RGBa::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa2D(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage_aRGB16::getShiftedARGB2D(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), uriVL::RasterImage_RGBa_F::getShiftedRGBa2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), getTotalByteCount(), graphWorldIsNull_(), RasterImage(), uriVL::RasterImage_HSV24::RasterImage_HSV24(), render_(), restoreGraphWorld(), setAsCurrentGraphWorld(), setAsImporterGraphWorld(), setAsMovieGraphWorld(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), setGraphWorldAsReference_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and ~RasterImage().
bool uriVL::RasterImage::gworldIsReference_ mutable private
True when the base raster stored in the GraphWorld object is the reference raster for this image.
This is not always the case. For example, color image processing may affect the HSV fields of a RasterImage_HSV, and these changes will only be applied to the base RGBa raster if requestRasterUpdate is called.
Definition at line 795 of file RasterImage.h.
Referenced by uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_aRGB16::getARGB(), uriVL::RasterImage_aRGB16::getARGB2D(), uriVL::RasterImage_gray::getGray(), uriVL::RasterImage_gray::getGray2D(), uriVL::RasterImage_binary::getGrayRasterImage(), uriVL::RasterImage_HSV24::getHue(), uriVL::RasterImage_HSV24::getHue2D(), uriVL::RasterImage_RGB::getRGB(), uriVL::RasterImage_RGB::getRGB2D(), uriVL::RasterImage_RGBa::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage_RGBa_F::getRGBa2D(), uriVL::RasterImage_HSV::getRGBa2D(), uriVL::RasterImage_HSV24::getSat(), uriVL::RasterImage_HSV24::getSat2D(), uriVL::RasterImage_aRGB16::getShiftedARGB2D(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_HSV24::getShiftedHue2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), uriVL::RasterImage_RGBa_F::getShiftedRGBa2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedRGBa2D(), uriVL::RasterImage_HSV24::getShiftedSat2D(), uriVL::RasterImage_HSV24::getShiftedVal2D(), uriVL::RasterImage_HSV24::getVal(), uriVL::RasterImage_HSV24::getVal2D(), graphWorldIsReference(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_HSV24::RasterImage_HSV24(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), render_(), restoreGraphWorld(), setAsCurrentGraphWorld(), setAsImporterGraphWorld(), setAsMovieGraphWorld(), setFloatRasterAsReference_(), setGraphWorldAsReference_(), setOtherRasterAsReference_(), uriVL::RasterImage_RGBa::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), and uriVL::RasterImage_binary::writeInto_().
bool uriVL::RasterImage::hasFloatRaster_ private
True when the RasterImage stores a float raster.
Definition at line 800 of file RasterImage.h.
Referenced by floatRasterIsReference(), hasFloatRaster(), setFloatRasterAsReference_(), setHasFloatRaster_(), uriVL::RasterImage_gray::updateRaster_(), and uriVL::RasterImage_RGBa::updateRaster_().
bool uriVL::RasterImage::hasOtherRaster_ private
True when the RasterImage stores another raster (other than a float raster), e.g.
HSV raster or binary raster
Definition at line 806 of file RasterImage.h.
Referenced by setHasOtherRaster_(), and uriVL::RasterImage_RGBa::updateRaster_().
unsigned int uriVL::RasterImage::id_ private
Unique index of this RasterImage object.
Definition at line 781 of file RasterImage.h.
Referenced by getID().
unsigned int RasterImage::imgCount_ = 0 static private
Counter for RasterImage objects created by the application.
Definition at line 850 of file RasterImage.h.
bool uriVL::RasterImage::pixmapIsLocked_ private
True when the image's pixel map is locked.
Definition at line 837 of file RasterImage.h.
Referenced by lockPixels(), pixelsAreLocked(), RasterImage(), and unlockPixels().
void* uriVL::RasterImage::pixmapKey_ private
Key for the image's pixel map.
Definition at line 845 of file RasterImage.h.
Referenced by lockPixels(), and unlockPixels().
bool uriVL::RasterImage::propertiesAreLocked_ private
True when the image's dimensions and pixel depth are locked.
Definition at line 833 of file RasterImage.h.
Referenced by lockProperties(), propertiesAreLocked(), RasterImage(), uriVL::RasterImage_aRGB16::setBoundRect_(), uriVL::RasterImage_RGB::setBoundRect_(), uriVL::RasterImage_RGBa::setBoundRect_(), uriVL::RasterImage_gray::setBoundRect_(), uriVL::RasterImage_gray_F::setBoundRect_(), uriVL::RasterImage_binary::setBoundRect_(), uriVL::RasterImage_binary::setValidRect_(), setValidRect_(), and unlockProperties().
void* uriVL::RasterImage::propertiesKey_ private
Key for the image's dimensions and pixel depth.
Definition at line 841 of file RasterImage.h.
Referenced by lockProperties(), and unlockProperties().
bool uriVL::RasterImage::referenceHasChanged_ mutable private
True when the base raster stored in the GraphWorld object the reference raster for this image.
This is not always the case. For example, color image processing may affect the HSV fields of a RasterImage_HSV, and these changes will only be applied to the base RGBa raster if requestRasterUpdate is called.a frame should be drawn around the images, when it is rendered. This frame has the color stored in frameColor_ or black if frameColor_ is null.
Definition at line 822 of file RasterImage.h.
Referenced by uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), uriVL::RasterImage_aRGB16::getARGB(), uriVL::RasterImage_aRGB16::getARGB2D(), uriVL::RasterImage_gray::getGray(), uriVL::RasterImage_gray::getGray2D(), uriVL::RasterImage_binary::getGrayRasterImage(), uriVL::RasterImage_HSV24::getHue(), uriVL::RasterImage_HSV24::getHue2D(), uriVL::RasterImage_RGB::getRGB(), uriVL::RasterImage_RGB::getRGB2D(), uriVL::RasterImage_RGBa_F::getRGBa(), uriVL::RasterImage_RGBa::getRGBa(), uriVL::RasterImage_HSV::getRGBa(), uriVL::RasterImage_RGBa_F::getRGBa2D(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::RasterImage_HSV::getRGBa2D(), uriVL::RasterImage_HSV24::getSat(), uriVL::RasterImage_HSV24::getSat2D(), uriVL::RasterImage_aRGB16::getShiftedARGB2D(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::RasterImage_HSV24::getShiftedHue2D(), uriVL::RasterImage_RGB::getShiftedRGB2D(), uriVL::RasterImage_RGBa_F::getShiftedRGBa2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedRGBa2D(), uriVL::RasterImage_HSV24::getShiftedSat2D(), uriVL::RasterImage_HSV24::getShiftedVal2D(), uriVL::RasterImage_HSV24::getVal(), uriVL::RasterImage_HSV24::getVal2D(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_HSV24::RasterImage_HSV24(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), referenceHasChanged(), render_(), requestRasterUpdate(), restoreGraphWorld(), setAsCurrentGraphWorld(), setAsImporterGraphWorld(), setAsMovieGraphWorld(), setFloatRasterAsReference_(), setGraphWorldAsReference_(), setOtherRasterAsReference_(), setReferenceHasChanged_(), uriVL::RasterImage_aRGB16::updateRaster_(), uriVL::RasterImage_RGB::updateRaster_(), uriVL::RasterImage_gray::updateRaster_(), uriVL::RasterImage_RGBa::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), and uriVL::RasterImage_binary::writeInto_().
long uriVL::RasterImage::timeStamp_ private
Time stamp for this image.
The time stamp only really makes sense when the image is coming from a movie file or frame grabber.
See also
setTimeStamp
getTimeStamp
Definition at line 829 of file RasterImage.h.
Referenced by getTimeStamp(), RasterImage(), and setTimeStamp().
The documentation for this class was generated from the following files:
RasterImage.h
RasterImage.cpp