URIVisionLibrary: uriVL::ColorImageGradient_Gaussian_I Class Reference
uriVL::ColorImageGradient_Gaussian_I Class Reference
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
#include <ColorImageGradient_Gaussian_I.h>
Public Member Functions
ColorImageGradient_Gaussian_I (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
ColorImageGradient_Gaussian_I (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
ColorImageGradient_Gaussian_I (double theScale, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
ColorImageGradient_Gaussian_I (int theWidth, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified width.
~ColorImageGradient_Gaussian_I (void)
Destructor.
float getScale (void) const
Returns the scale of the operator.
VectorField * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a VectorField.
VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
void applyInto (const RasterImage *imgIn, VectorField *vectOut)
Applies this operator to a RasterImage and writes the result into a VectorField received as second parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
Public Member Functions inherited from uriVL::ColorImageGradient
virtual ~ColorImageGradient (void)
Destructor.
int getWidth (void) const
Returns the width of the filter.
int getHeight (void) const
Returns the height of the filter.
void setColorGradientMode (ColorGradientMode colorGradientMode)
Sets the Computation mode for the color gradient.
ColorGradientMode getColorGradientMode (void) const
Returns the Computation mode for the color gradient.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
ColorImageGradient_Gaussian_I (const ColorImageGradient_Gaussian_I &obj)
Copy constructor (disabled)
const ColorImageGradient_Gaussian_I & operator= (const ColorImageGradient_Gaussian_I &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
Private Attributes
double scale_
Scale parameter (sigma) of the filter.
float * ig_
Stores into a 1D array (radial distances squared) the filter's coefficients.
float * igD_
Stores into a 1D array (radial distances squared) the filter's coefficients.
int iDenum_
denumerator by which to divide the weighted summation computed using the coefficients of ig_
int iDevDenum_
denumerator by which to divide the weighted summation computed using the coefficients of igD_
Additional Inherited Members
Protected Member Functions inherited from uriVL::ColorImageGradient
ColorImageGradient (int theWidth, bool isIntOperator, ColorGradientMode theMode=GRAD_AVE_OF_COLOR_COMPONENTS)
Creates a ColorImageGradient operator with the specified width.
ColorImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator, ColorGradientMode theMode=GRAD_AVE_OF_COLOR_COMPONENTS)
Creates a ColorImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ColorImageGradient (const ColorImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRasters_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRasters_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D red temp raster.
float *const * getShiftedTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D green temp raster.
float *const * getShiftedTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D blue temp raster.
float *const * getShiftedAltTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate red temp raster.
float *const * getShiftedAltTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate green temp raster.
float *const * getShiftedAltTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate blue temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
This class has not been implemented yet
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file ColorImageGradient_Gaussian_I.h.
Constructor & Destructor Documentation
ColorImageGradient_Gaussian_I::ColorImageGradient_Gaussian_I (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
Parameters
scale scale sigma of the Gaussian filter
Definition at line 30 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ColorImageGradient(2*(((int ) (5*theScale))/2) + 1, false),
                                 //
                                 scale_(theScale),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a G Gradient filter is 0.8");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient_Gaussian_I constructor");
         throw e;
 }
ColorImageGradient_Gaussian_I::ColorImageGradient_Gaussian_I (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Gaussian filter
Definition at line 77 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ColorImageGradient(theWidth, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient_Gaussian_I constructor");
         throw e;
 }
ColorImageGradient_Gaussian_I::ColorImageGradient_Gaussian_I (double theScale, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 51 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ColorImageGradient(2*(((int ) (5*theScale))/2) + 1, false),
                                 //
                                 scale_(theScale),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a G Gradient filter is 0.8");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient_Gaussian_I constructor");
         throw e;
 }
ColorImageGradient_Gaussian_I::ColorImageGradient_Gaussian_I (int theWidth, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 103 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ColorImageGradient(theWidth, theRect, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G Gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient_Gaussian_I constructor");
         throw e;
 }
ColorImageGradient_Gaussian_I::~ColorImageGradient_Gaussian_I (void)
Destructor.
Definition at line 147 of file ColorImageGradient_Gaussian_I.cpp.
References ig_, and igD_.
 {
     delete []ig_;
     delete []igD_;
 }
ColorImageGradient_Gaussian_I::ColorImageGradient_Gaussian_I (const ColorImageGradient_Gaussian_I & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 128 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ColorImageGradient(theObj),
                                 //
                                 scale_(theObj.scale_),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient_Gaussian_I copy constructor not implemented.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient_Gaussian_I constructor");
         throw e;
 }
Member Function Documentation
void ColorImageGradient_Gaussian_I::applyInto (const RasterImage * imgIn, VectorField * vectOut) virtual
Applies this operator to a RasterImage and writes the result into a VectorField received as second parameter.
Parameters
imgIn the RasterImage to which the operator is applied
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 212 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     applyInto(imgIn, imgIn->getValidRect(), vectOut);
 }
void ColorImageGradient_Gaussian_I::applyInto (const RasterImage * imgIn, const ImageRect * theRect, VectorField * vectOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 220 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::VectorField::forceRasterUpdate(), uriVL::kFunctionNotImplemented, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kNullVectorFieldError, uriVL::VectorField::setRasterAsReference(), and uriVL::DrawableObject2D::setValidRect().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     FAIL_CONDITION(     vectOut == NULL,
                                 kNullVectorFieldError,
                                 "NULL output vector field passed as parameter");
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
     vectOut->setValidRect(destRect);
         vectOut->setRasterAsReference();
         vectOut->forceRasterUpdate();
 }
VectorField * ColorImageGradient_Gaussian_I::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a VectorField.
Since the operator is an "integer" operator, then the VectorField returned should have the type matching that of the input image
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 185 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
         return applyTo(imgIn, imgIn->getValidRect());
 }
VectorField * ColorImageGradient_Gaussian_I::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 193 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, uriVL::kFunctionNotImplemented, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
         VectorField     *vectOut = NULL;
         return vectOut;
 }
float ColorImageGradient_Gaussian_I::getScale (void) const virtual
Returns the scale of the operator.
Returns
scale of the operator
Implements uriVL::ColorImageGradient.
Definition at line 172 of file ColorImageGradient_Gaussian_I.cpp.
References scale_.
 {
     return static_cast<float>(scale_);
 }
void ColorImageGradient_Gaussian_I::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
fg_
fgD_
Definition at line 252 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by ColorImageGradient_Gaussian_I().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 //    const int  m = getWidth()/2;
 //    const double      sigma2Scale = 1.L / (2.L * scale_ * scale_),
 //                                      piSigma = 1.L / (sqrt(2*PI) * scale_),
 //                                      piSigma2 = piSigma/scale_;
 //
 //    ig_ = new int [m+1];
 //    FAIL_CONDITION( ig_ == NULL,
 //                    kFilterAllocationError,
 //                    "filter allocation failed in ColorImageGradient_Gaussian_I::initializeFilter_");
 //    igD_ = new int [m+1];
 //    FAIL_CONDITION( igD_ == NULL,
 //                    kFilterAllocationError,
 //                    "filter allocation failed in ColorImageGradient_Gaussian_I::initializeFilter_");
 //
 }
const ColorImageGradient_Gaussian_I & ColorImageGradient_Gaussian_I::operator= (const ColorImageGradient_Gaussian_I & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 155 of file ColorImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient_Gaussian_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
int uriVL::ColorImageGradient_Gaussian_I::iDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Definition at line 167 of file ColorImageGradient_Gaussian_I.h.
int uriVL::ColorImageGradient_Gaussian_I::iDevDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of igD_
Definition at line 172 of file ColorImageGradient_Gaussian_I.h.
float* uriVL::ColorImageGradient_Gaussian_I::ig_ private
Stores into a 1D array (radial distances squared) the filter's coefficients.
Definition at line 157 of file ColorImageGradient_Gaussian_I.h.
Referenced by ~ColorImageGradient_Gaussian_I().
float* uriVL::ColorImageGradient_Gaussian_I::igD_ private
Stores into a 1D array (radial distances squared) the filter's coefficients.
Definition at line 161 of file ColorImageGradient_Gaussian_I.h.
Referenced by ~ColorImageGradient_Gaussian_I().
double uriVL::ColorImageGradient_Gaussian_I::scale_ private
Scale parameter (sigma) of the filter.
Definition at line 153 of file ColorImageGradient_Gaussian_I.h.
Referenced by getScale().
The documentation for this class was generated from the following files:
ColorImageGradient_Gaussian_I.h
ColorImageGradient_Gaussian_I.cpp