URIVisionLibrary: uriVL::RasterImage_binary Class Reference
uriVL::RasterImage_binary Class Reference
Base binary image class.
#include <RasterImage_binary.h>
Public Member Functions
RasterImage_binary (int nbRows, int nbCols)
Allocates a binary raster image at the specified dimensions.
RasterImage_binary (const ImageRect *theRect)
Allocates an 8-bit binary raster image at the specified dimensions.
RasterImage_binary (int nbRows, int nbCols, const bool *theBw)
Initializes an 8-bit binary raster image at the specified dimensions and values.
RasterImage_binary (const GraphWorld *gworld)
Initializes an 8-bit binary raster image at the specified dimensions and values.
RasterImage_binary (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes an 8-bit binary raster image at the specified dimensions and values.
RasterImage_binary (const RasterImage *img)
Initializes an 8-bit binary raster image at the specified dimensions and values.
RasterImage_binary (const RasterImage *img, const ImageRect *theRect)
Initializes an 8-bit binary raster image at the specified dimensions and values.
~RasterImage_binary (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
const unsigned char * getBw (void) const
Returns the 1-bit binary base raster as a read-only 1D array.
unsigned char * getBw (ReadWriteStatus rw)
Returns the 1-bit binary base raster as a read-write 1D array.
const unsigned char *const * getBw2D (void) const
Returns the 1-bit binary "unpacked" base raster as a read-only 2D array.
unsigned char *const * getBw2D (ReadWriteStatus rw)
Returns the 1-bit binary "unpacked" base raster as a read-write 2D array.
const unsigned char *const * getShiftedBw2D (void) const
Returns the shifted 1-bit binary "unpacked" base raster as a read-only 2D array.
unsigned char *const * getShiftedBw2D (ReadWriteStatus rw)
Returns the shifted 1-bit binary "unpacked" base raster as a read-write 2D array.
RasterImage_gray * getGrayRasterImage (void) const
Returns the gray-level form of this image.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
bool unpackedRasterIsReference (void)
Indicates whether the "unpacked" raster (rather than the "packed" binary raster) is the reference.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts (copies) a 1D gray-level raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 16-bit argb raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
void setUnpackedRasterAsReference (void) const
Sets the "unpacked" raster (rather than the "packed" binary raster) tpo be the reference.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Private Member Functions
RasterImage_binary (void)
Default constructor.
RasterImage_binary (const RasterImage_binary &img)
Creates a new raster image based on the one received as parameter.
const RasterImage_binary & operator= (const RasterImage_binary &thePt)
Equal operator.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the raster image.
void updateRaster_ (void) const
Forces an update of the base gray raster if it is not the reference raster.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
Private Attributes
RasterImage_gray * grayForm_
"Unpacked" gray-level version of this object.
bool unpackedRasterIsReference_
2D array mapped on the GraphWorld's 1D raster.
Friends
class _GraphWorld_gen
Detailed Description
Base binary image class.
RasterImage_binary objects are used in image processing as the input and output of a number of operators such as edge detection or morphological operators.
RasterImage_binary implements or overrides a number of methods of the base RasterImageClass, and in particular the mostly useless convertTo<Gray,RGB,RGBa> methods.
This class is special in the sense that it must maintain two copies of its raster: the "packed binary" base raster (8 pixels per byte) that is used to display the image, and the 1-byte-per pixel raster that is used to manipulate pixels. The latter is stored as a RasterImage_gray object. Any nonzero value in this raster will be coded as a 1 in the binary for on the image.
At this point, I don't see any reason why anyone would want to subclass RasterImage_binary, so I won't waste time thinking/writing about what should and what should not be overridden.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 50 of file RasterImage_binary.h.
Constructor & Destructor Documentation
RasterImage_binary::RasterImage_binary (int nbRows, int nbCols)
Allocates a binary raster image at the specified dimensions.
Allocates a binary GraphWorld at the specified dimensions and initializes this raster to zero values (black).
Parameters
nbRows number of rows of the binary raster image
nbCols number of columns of the binary raster image
Definition at line 43 of file RasterImage_binary.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), grayForm_, uriVL::RasterImage::RasterImage_gray, and uriVL::RasterImage::setHasOtherRaster_().
         :       RasterImage(nbRows, nbCols),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
         allocateGraphWorld_(nbRows, nbCols);
         allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
         //
     grayForm_ = new RasterImage_gray(nbRows, nbCols);
         setHasOtherRaster_(true);
 }
RasterImage_binary::RasterImage_binary (const ImageRect * theRect)
Allocates an 8-bit binary raster image at the specified dimensions.
Allocates an 8-bit binary raster image at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageREct specifying the image's bounding rectangle
Definition at line 58 of file RasterImage_binary.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), and uriVL::RasterImage::setHasOtherRaster_().
         :       RasterImage(theRect),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
         allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(), theRect->getTop(), theRect->getLeft());
         //
         setHasOtherRaster_(true);
 }
RasterImage_binary::RasterImage_binary (int nbRows, int nbCols, const bool * theBw)
Initializes an 8-bit binary raster image at the specified dimensions and values.
Allocates an 8-bit binary GraphWorld at the specified dimensions and initializes this raster to zero values (black).
Parameters
nbRows number of rows of the binary raster image
nbCols number of columns of the binary raster image
theBW values to which the image should be initialized
Definition at line 72 of file RasterImage_binary.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::RasterImage_gray::getGray2D(), grayForm_, uriVL::R_W_ACCESS, uriVL::RasterImage::RasterImage_gray, uriVL::RasterImage::setHasOtherRaster_(), and uriVL::RasterImage::setOtherRasterAsReference_().
         :       RasterImage(nbRows, nbCols),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(true)
 {
         allocateGraphWorld_(nbRows, nbCols);
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     //
     grayForm_ = new RasterImage_gray(nbRows, nbCols);
     unsigned char* const* gray2D = grayForm_->getGray2D(R_W_ACCESS);
     long    l = 0;
     for (int i=0; i<nbRows; i++)
     {
         for (int j=0; j<nbCols; j++)
         {
             if (theBw[l++])
                 gray2D[i][j] = static_cast<unsigned char>(255);
             else
                 gray2D[i][j] = static_cast<unsigned char>(0);
         }
     }
         setHasOtherRaster_(true);
     setOtherRasterAsReference_();
 }
RasterImage_binary::RasterImage_binary (const GraphWorld * gworld)
Initializes an 8-bit binary raster image at the specified dimensions and values.
Allocates an 8-bit binary GraphWorld at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter.
Parameters
gworld the GraphWorld to use for dimensions and values
Definition at line 101 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       RasterImage(theGworld),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
RasterImage_binary::RasterImage_binary (GraphWorld * gworld, bool keepThisGraphWorld)
Initializes an 8-bit binary raster image at the specified dimensions and values.
Allocates an 8-bit binary GraphWorld at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter. Possibly keeps the GraphWorld received as parameter rather than making a copy of it.
Parameters
gworld the GraphWorld to use for dimensions and values
keepThisGraphWorld if true, then this new image raster object will simply store a reference to a pre-allocated GWorld instead of allocating its own (beware!)
Definition at line 114 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       RasterImage(theGworld, keepThisGraphWorld),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
RasterImage_binary::RasterImage_binary (const RasterImage * img)
Initializes an 8-bit binary raster image at the specified dimensions and values.
Allocates an 8-bit binary GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
Definition at line 126 of file RasterImage_binary.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), deleteRaster2D_(), deleteShiftedRaster2D_(), uriVL::DrawableObject2D::getTop(), and uriVL::DrawableObject2D::getValidRect().
         :       RasterImage(img),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
         try {
                 img->copyInto(this, img->getValidRect());
         }
         catch(ErrorReport& e) {
                 if (img != NULL)
                 {
                         deleteShiftedRaster2D_(img->getTop());
                         deleteRaster2D_();
                 }
                 e.appendToMessage("called by RasterImage_binary constructor");
                 throw e;
         }
 }
RasterImage_binary::RasterImage_binary (const RasterImage * img, const ImageRect * theRect)
Initializes an 8-bit binary raster image at the specified dimensions and values.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 147 of file RasterImage_binary.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::RasterImage::gworldIsReference_, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::RasterImage::referenceHasChanged_.
                 :       RasterImage( ),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_binary constructor");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage_binary constructor");
         try {
                 img->copyInto(this, theRect);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_binary constructor");
                 throw e;
         }
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_binary constructor");
         throw e;
 }
RasterImage_binary::~RasterImage_binary (void)
Class destructor.
Standard destructor (nothing fancy).
Definition at line 203 of file RasterImage_binary.cpp.
References grayForm_.
 {
     if (grayForm_ != NULL)
         delete grayForm_;
 }
RasterImage_binary::RasterImage_binary (void) private
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
This constructor should only be invoked from subclasses
Definition at line 33 of file RasterImage_binary.cpp.
References uriVL::RasterImage::setHasOtherRaster_().
         :       RasterImage(),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
         setHasOtherRaster_(true);
 }
RasterImage_binary::RasterImage_binary (const RasterImage_binary & img) private
Creates a new raster image based on the one received as parameter.
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
img pointer to the RasterImage_binary object to copy
Definition at line 180 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       RasterImage( ),
                         //
                         grayForm_(NULL),
                         unpackedRasterIsReference_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_binary copy constructor not implemented");
 }
Member Function Documentation
void RasterImage_binary::allocateGraphWorld_ (int nbRows, int nbCols) protected virtual
Alocates the GraphWorld for this object at the set dimensions.
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Implements uriVL::RasterImage.
Definition at line 774 of file RasterImage_binary.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, and uriVL::kGWorldAllocationError.
Referenced by RasterImage_binary(), and setBoundRect_().
 {
     gworld_ = new GraphWorld(1, nbRows, nbCols);
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldAllocationError,
                     "GraphWorld allocation failed in RasterImage_binary constructor");
 }
void RasterImage_binary::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Implements uriVL::RasterImage.
Definition at line 786 of file RasterImage_binary.cpp.
Referenced by RasterImage_binary().
 {
 }
void RasterImage_binary::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implements uriVL::RasterImage.
Definition at line 794 of file RasterImage_binary.cpp.
Referenced by RasterImage_binary().
 {
 }
void RasterImage_binary::convertToARGB16 (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D gray-level raster into a 1D 16-bit argb raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 690 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
void RasterImage_binary::convertToGray (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts (copies) a 1D gray-level raster into a 1D gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
Definition at line 610 of file RasterImage_binary.cpp.
Referenced by uriVL::_GraphWorld_gen::copyBinaryInto_().
 {
     const long  nbBytes = (nbPixels+7)/8;
     const int   remainder = static_cast<int>(nbPixels % 8);
     const unsigned char* source = theSource;
     unsigned char* dest = theDestination;
     const unsigned char BIN_0 = static_cast<unsigned char>(0),
                         BIN_255 = static_cast<unsigned char>(255);
     //  do the conversion for the full bytes
     for (long l=0; l<nbBytes-1; l++)
     {
         unsigned char   c = *(source++);
         for (int k=7; k>=0; k--)
             *(dest++) = (c & (1 << k)) ? BIN_255 : BIN_0;
     }
     //  do the conversion for the remainder bits (incomplete byte)
     unsigned char   c = *(source++);
     for (int k=7; k>7-remainder; k--)
         *(dest++) = (c & (1 << k)) ? BIN_255 : BIN_0;
 }
void RasterImage_binary::convertToGray (const unsigned char * theSource, float * theDestination, long nbPixels) static
Converts a 1D gray-level raster into a 1D float gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myGrayConv the gray conversion mode desired
Definition at line 639 of file RasterImage_binary.cpp.
 {
     const long  nbBytes = (nbPixels+7)/8;
     const int   remainder = static_cast<int>(nbPixels % 8);
     const unsigned char* source = theSource;
     float* dest = theDestination;
     const unsigned char BIN_0 = static_cast<unsigned char>(0),
                         BIN_255 = static_cast<unsigned char>(255);
     //  do the conversion for the full bytes
     for (long l=0; l<nbBytes-1; l++)
     {
         unsigned char   c = *(source++);
         for (int k=7; k>=0; k--)
             *(dest++) = (c & (1 << k)) ? BIN_255 : BIN_0;
     }
     //  do the conversion for the remainder bits (incomplete byte)
     unsigned char   c = *(source++);
     for (int k=7; k>7-remainder; k--)
         *(dest++) = (c & (1 << k)) ? BIN_255 : BIN_0;
 }
void RasterImage_binary::convertToRGB (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D gray-level raster into a 1D 24-bit rgb raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 680 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
void RasterImage_binary::convertToRGBa (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D gray-level raster into a 1D 32-bit rgba raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 668 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
void RasterImage_binary::copyInto (RasterImage * imgOut) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
Implements uriVL::RasterImage.
Definition at line 411 of file RasterImage_binary.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by copyInto(), and updateRaster_().
 {
     copyInto(imgOut, getValidRect(), NULL);
 }
void RasterImage_binary::copyInto (RasterImage * imgOut, const ImageRect * theRect) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab).
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Implements uriVL::RasterImage.
Definition at line 417 of file RasterImage_binary.cpp.
References copyInto().
 {
     copyInto(imgOut, theRect, NULL);
 }
void RasterImage_binary::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Definition at line 423 of file RasterImage_binary.cpp.
References uriVL::RasterImage::copyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kDense, uriVL::kUriBaseError, uriVL::DrawableObject2D::setDrawableInformationType(), uriVL::DrawableObject2D::setValidRect(), and writeInto_().
 {
     //  All the rectangle testing and resizing is done in the parent class' function
     RasterImage::copyInto_(imgOut, theRect, origin);
     //  We only copy from the validRect_, so we need to calculate its intersection
     //  with theRect.
     ImageRect* copyRect = ImageRect::intersection(getValidRect(), theRect);
     FAIL_CONDITION( copyRect == NULL,
                     kUriBaseError,
                     "the copy rectangle specified is not within valid data");
     //  For the time being, we only handle regular dense rasters
     imgOut->setDrawableInformationType(kDense);
     writeInto_(imgOut, copyRect, origin);
         imgOut->setValidRect(copyRect);
     delete copyRect;
 }
void RasterImage_binary::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Implements uriVL::RasterImage.
Definition at line 790 of file RasterImage_binary.cpp.
Referenced by RasterImage_binary(), and setBoundRect_().
 {
 }
void RasterImage_binary::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Implements uriVL::RasterImage.
Definition at line 798 of file RasterImage_binary.cpp.
Referenced by RasterImage_binary(), and setBoundRect_().
 {
 }
BaseRasterType RasterImage_binary::getBaseRasterType (void) const virtual
Returns the image's base raster type.
Returns the following value:
- kGrayRaster, since this image is based on the 8-bit gray level format
Returns
the image's base raster type
Implements uriVL::RasterImage.
Definition at line 217 of file RasterImage_binary.cpp.
References uriVL::kBinaryRaster.
 {
     return kBinaryRaster;
 }
const unsigned char * RasterImage_binary::getBw (void) const
Returns the 1-bit binary base raster as a read-only 1D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
1D base raster for this image
See also
getRaster
Definition at line 275 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getRaster().
 {
     return getGrayRasterImage()->getRaster();
 }
unsigned char * RasterImage_binary::getBw (ReadWriteStatus rw)
Returns the 1-bit binary base raster as a read-write 1D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
See also
getRaster
Definition at line 281 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getRaster(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getRaster(rw);
 }
const unsigned char *const * RasterImage_binary::getBw2D (void) const
Returns the 1-bit binary "unpacked" base raster as a read-only 2D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
2D base raster for this image
See also
getRaster2D
Definition at line 293 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getRaster2D().
 {
     return getGrayRasterImage()->getRaster2D();
 }
unsigned char *const * RasterImage_binary::getBw2D (ReadWriteStatus rw)
Returns the 1-bit binary "unpacked" base raster as a read-write 2D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
See also
getRaster2D
Definition at line 299 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getRaster2D(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getRaster2D(rw);
 }
RasterImage_gray * RasterImage_binary::getGrayRasterImage (void) const
Returns the gray-level form of this image.
Returns
private gray-level RasterImage form
Definition at line 373 of file RasterImage_binary.cpp.
References grayForm_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::RasterImage_gray, uriVL::RasterImage::referenceHasChanged_, uriVL::RasterImage::setOtherRasterAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and unpackedRasterIsReference_.
Referenced by getBw(), getBw2D(), getRaster(), getRaster2D(), getShiftedBw2D(), and getShiftedRaster2D().
 {
     //  if the gworld is the reference
     if (gworldIsReference_)
     {
         //  If we have never allocated the gray raster, now would be a good time
         //  to do so.
         if (grayForm_ == NULL)
             grayForm_ = new RasterImage_gray(const_cast<RasterImage_binary*>(this));
         //  otherwise, udpdate the gray raster only if the binary raster has changed
         else if (referenceHasChanged_)
         {
             //  sets the flag to false to avoid loop repeats
             setReferenceHasChanged_(false);
             //  Copy the binary raster into the gray one
                         //      I cast away this object's constness because the changes that may occur
                         //      are only of type update.  The "true" content is not changed
             (const_cast<RasterImage_binary*>(this))->copyInto(grayForm_);
         }
     }
     //  the gray raster is now the reference
     setOtherRasterAsReference_();
         unpackedRasterIsReference_ = true;
     return  grayForm_;
 }
const unsigned char * RasterImage_binary::getRaster (void) const virtual
Returns the base raster as a read-only 1D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
1D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 223 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getRaster().
 {
     return getGrayRasterImage()->getRaster();
 }
unsigned char * RasterImage_binary::getRaster (ReadWriteStatus rw) virtual
Returns the base raster as a read-write 1D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 229 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getRaster(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getRaster(rw);
 }
const unsigned char *const * RasterImage_binary::getRaster2D (void) const virtual
Returns the base raster as a read-only 2D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
2D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 241 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getRaster2D().
 {
     return getGrayRasterImage()->getRaster2D();
 }
unsigned char *const * RasterImage_binary::getRaster2D (ReadWriteStatus rw) virtual
Returns the base raster as a read-write 2D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 247 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getRaster2D(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getRaster2D(rw);
 }
const unsigned char *const * RasterImage_binary::getShiftedBw2D (void) const
Returns the shifted 1-bit binary "unpacked" base raster as a read-only 2D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
shifted 2D base raster for this image
See also
getShiftedRaster2D
Definition at line 311 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getShiftedRaster2D().
 {
     return getGrayRasterImage()->getShiftedRaster2D();
 }
unsigned char *const * RasterImage_binary::getShiftedBw2D (ReadWriteStatus rw)
Returns the shifted 1-bit binary "unpacked" base raster as a read-write 2D array.
You must be aware of the following when you use this function:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
See also
getShiftedRaster2D
Definition at line 317 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getShiftedRaster2D(rw);
 }
const unsigned char *const * RasterImage_binary::getShiftedRaster2D (void) const virtual
Returns the shifted base raster as a read-only 2D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Returns
shifted 2D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 259 of file RasterImage_binary.cpp.
References getGrayRasterImage(), and uriVL::RasterImage::getShiftedRaster2D().
Referenced by writeInto_().
 {
     return getGrayRasterImage()->getShiftedRaster2D();
 }
unsigned char *const * RasterImage_binary::getShiftedRaster2D (ReadWriteStatus rw) virtual
Returns the shifted base raster as a read-write 2D array.
The implementation of this function for the "binary" image class differs from that for the "gray" and various "color classes in two important aspects:
First, it does not really return the image's graphworld's private raster, which is a "packed" binary raster (8 pixels per byte) but an "unpacked" copy of that raster (1 byte per pixel).
The raster that is returned is now assumed to be the reference raster for the image. In other words, gworldIsReference_ is set to false and referenceHasChanged_ is set to true. This will results in a slight performance penalty when rendering the image (if the "unpacked" raster was in fact not modified). It is possible to avoid that performance hit by setting the graphworld back as the reference: setGraphWorldAsReference
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
See also
setGraphWorldAsReference
Reimplemented from uriVL::RasterImage.
Definition at line 264 of file RasterImage_binary.cpp.
References getGrayRasterImage(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::RasterImage::setOtherRasterAsReference_(), and unpackedRasterIsReference_.
 {
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the private gray raster is set to be the reference and is marked
     //  as 'changed'
     setOtherRasterAsReference_();
     unpackedRasterIsReference_= true;
     return getGrayRasterImage()->getShiftedRaster2D(rw);
 }
const RasterImage_binary & RasterImage_binary::operator= (const RasterImage_binary & thePt) private
Equal operator.
Created so that gcc will stop complaining. This RasterImage_binary object will retain its own id.
Parameters
thePt reference to the RasterImage_binary object to copy
Definition at line 193 of file RasterImage_binary.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_binary copy operator not implemented");
         return *this;
 }
void RasterImage_binary::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
Parameters
x horizontal coordinate of upper left corner
y vertical coordinate of upper left corner
theWidth desired width of the image
theHeight desired height of the image
(no re-allocation needed)
Implements uriVL::DrawableObject2D.
Definition at line 709 of file RasterImage_binary.cpp.
References allocateGraphWorld_(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), grayForm_, uriVL::RasterImage::gworld_, uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked_, uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  if width and height have not changed, then the operation is just a translation.
     //  All we need to do is update the ImageRect member and update the "shifted" array
     /// (no re-allocation needed)
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             setBoundRect(x, y, theWidth, theHeight);
             setValidRect(x, y, theWidth, theHeight);
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangles are different, then we must delete
     //  and reallocate the GraphWorld as well as the 0-based 2D raster.
     else
     {
         //      I am not sure if this is the right thing to do: should subclasses completely
         //      reimplement this or call this function?  This is opting for the latter.
         if (gworld_ != NULL)
         {
             delete gworld_;
             deleteShiftedRaster2D_(getTop());
             deleteRaster2D_();
             allocateGraphWorld_(theHeight, theWidth);
             setBoundRect(x, y, theWidth, theHeight);
             setValidRect(x, y, theWidth, theHeight);
         }
     }
     //  The resizing also affects the gray form raster
     if (grayForm_ != NULL)
         grayForm_->setBoundRect(x, y, theWidth, theHeight);
 }
void uriVL::RasterImage_binary::setUnpackedRasterAsReference (void) const protected
Sets the "unpacked" raster (rather than the "packed" binary raster) tpo be the reference.
void RasterImage_binary::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a raster image could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter).
This function is called by the public function setValidRect of the root parent class <code.DrawableObject2D. All data validity tests were performed there. This protected function only has to take care of class-specific issues such as the handling of non-base rasters.
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Reimplemented from uriVL::RasterImage.
Definition at line 753 of file RasterImage_binary.cpp.
References FAIL_CONDITION, grayForm_, uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked_, and uriVL::DrawableObject2D::setValidRect().
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  The root parent class already took care of this image's valid rect.
     //  All what remains to do is set the gray form's valid rect
     if (grayForm_ != NULL)
         grayForm_->setValidRect(x, y, theWidth, theHeight);
 }
bool uriVL::RasterImage_binary::unpackedRasterIsReference (void)
Indicates whether the "unpacked" raster (rather than the "packed" binary raster) is the reference.
Returns
true if the "unpacked" raster (rather than the "packed" binary raster) is the reference
void RasterImage_binary::updateRaster_ (void) const private virtual
Forces an update of the base gray raster if it is not the reference raster.
This virtual function should be overridden by all subclasses of RasterImage_gray.
Implements uriVL::RasterImage.
Definition at line 332 of file RasterImage_binary.cpp.
References uriVL::RasterImage_gray::copyInto(), copyInto(), uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getBoundRect(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), grayForm_, uriVL::RasterImage::gworldIsReference_, uriVL::R_W_ACCESS, uriVL::RasterImage::RasterImage_gray, uriVL::RasterImage::referenceHasChanged_, and uriVL::RasterImage::setReferenceHasChanged_().
Referenced by writeInto_().
 {
     if (referenceHasChanged_)
     {
         //  Change this flag now to avoid an infinite loop in copyInto
         setReferenceHasChanged_(false);
         if (gworldIsReference_)
         {
             //  If we have never allocated the gray raster, now would be a good time
             //  to do so.
             if (grayForm_ == NULL)
                 grayForm_ = new RasterImage_gray(getBoundRect());
             //  Copy the binary raster into the gray one
             copyInto(grayForm_);
         }
         else
         {
             //  To copy the gray raster into the binary one, we first need to
             //  "saturate the gray raster
                         const ImageRect* validRect = getValidRect();
             const int   iLow = validRect->getTop(),
                         iHigh = validRect->getBottom(),
                         jLow = validRect->getLeft(),
                         jHigh = validRect->getRight();
             unsigned char   *const* gray = grayForm_->getShiftedRaster2D(R_W_ACCESS);
             for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                     if (gray[i][j] != 0)
                         gray[i][j] = static_cast<unsigned char>(255);
             //  then we do the CopyBits
                         //      OK, the const_cast is ugly, but this is really the only way to preserve
                         //      logical constness
             grayForm_->copyInto(const_cast<RasterImage_binary*>(this));
         }
     }
 }
void RasterImage_binary::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const private virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Definition at line 446 of file RasterImage_binary.cpp.
References uriVL::RasterImage::allocateRaster2D_(), uriVL::RasterImage::allocateShiftedRaster2D_(), uriVL::GraphWorld::copyInto(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::hasFloatRaster(), uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kSaturatedPositive, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, uriVL::RasterImage::setFloatRasterAsReference_(), uriVL::RasterImage::setGraphWorldAsReference_(), uriVL::RasterImage::setReferenceHasChanged_(), and updateRaster_().
Referenced by copyInto().
 {
     const unsigned char* const* graySource = NULL;
         //  The GWorld only works with unshifted rasters so we need to compute
         //  the "true" copy rectangles first
     ImageRect*  sourceRect = new ImageRect(copyRect->getLeft() - getLeft(),
                                                                                    copyRect->getTop() - getTop(),
                                                                                    copyRect->getWidth(), copyRect->getHeight());
         ImageRect*  destRect =  origin == NULL ?
                                                         new ImageRect(copyRect->getLeft() - imgOut->getLeft(),
                                           copyRect->getTop() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight())
                                                         :
                                                         new ImageRect(origin->getX() - imgOut->getLeft(),
                                           origin->getY() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight());
         const int   //iLowSource = sourceRect->getTop(),
                                 iLowDest = destRect->getTop(),
                                 //iHighSource = sourceRect->getBottom(),
                                 //jLowSource = sourceRect->getLeft(),
                                 jLowDest = destRect->getLeft();
         const int       nbRows = sourceRect->getHeight(),
                                 nbCols = sourceRect->getWidth();
     //  Subclasses should override this function, but in case they don't, we need to
     //  do the conversion through the base gray-level raster.
     if (!gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     switch( imgOut->getBaseRasterType() )
     {
         case kBinaryRaster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
             imgOut->setGraphWorldAsReference_();
             imgOut->setReferenceHasChanged_(true);
             break;
         case kGrayRaster:
             //  if we are dealing with a plain gray raster image, just copy the bytes
             if (!imgOut->hasFloatRaster()) {
                 //  At this point we are ready to perform the copy/conversion and we use
                 //  the CopyBits function of QuickDraw/QuickTime
                 gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
                                 imgOut->setGraphWorldAsReference_();
                 imgOut->setReferenceHasChanged_(true);
             }
             //
             //  if imgOut has a float, use this image's gray raster to do the copy.
             else
             {
                 //  temporary
                 const int   iLow = copyRect->getTop(),
                             iHigh = copyRect->getBottom(),
                             jLow = copyRect->getLeft(),
                             jHigh = copyRect->getRight();
                 //
                 graySource = getShiftedRaster2D();
                 float* const* fGrayDest = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
                                 //      This call may have been made from within the RasterImage_gray_F constructor of imgOut,
                                 //      in which case grayDest has not been allocated yet
                                 if (fGrayDest == NULL)
{
                                         imgOut->allocateRaster2D_(nbRows, nbCols);
                                         imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                         fGrayDest = (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
                                 }
                 for (int i=iLow; i<=iHigh; i++)
                     for (int j=jLow; j<=jHigh; j++)
                         fGrayDest[i][j] = graySource[i][j];
                 imgOut->setFloatRasterAsReference_();
                 imgOut->setReferenceHasChanged_(true);
                 (static_cast<RasterImage_gray_F*>(imgOut))->setFloatConversionMode(kSaturatedPositive);
             }
             break;
         case kRGB24Raster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
             imgOut->setGraphWorldAsReference_();
             imgOut->setReferenceHasChanged_(true);
             break;
         case kaRGB16Raster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
             imgOut->setGraphWorldAsReference_();
             imgOut->setReferenceHasChanged_(true);
             break;
         case kRGBa32Raster:
             //  if we are dealing with a plain gray raster image, just copy the bytes
             if (!imgOut->hasFloatRaster())
             {
                 //  At this point we are ready to perform the copy/conversion and we use
                 //  the CopyBits function of QuickDraw/QuickTime
                 gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
                                 imgOut->setGraphWorldAsReference_();
                                 imgOut->setReferenceHasChanged_(true);
             }
             //
             //  if imgOut has a float raster, we had better use it
             else
             {
                 //  temporary
                 const int   iLow = copyRect->getTop(),
                             iHigh = copyRect->getBottom(),
                             jLow = copyRect->getLeft(),
                             jHigh = copyRect->getRight();
                 //
                 graySource = getShiftedRaster2D();
                 float* const* fRedDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                 float* const* fGreenDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                 float* const* fBlueDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                 for (int i=iLow; i<=iHigh; i++)
                     for (int j=jLow; j<=jHigh; j++)
                         fRedDest[i][j] = fGreenDest[i][j] = fBlueDest[i][j] = graySource[i][j];
                 imgOut->setFloatRasterAsReference_();
                 imgOut->setReferenceHasChanged_(true);
                 (static_cast<RasterImage_RGBa_F*>(imgOut))->setFloatConversionMode(kSaturatedPositive);
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage_gray::writeInto_");
             break;
     }
     if (sourceRect != NULL)
         delete sourceRect;
     if (destRect != NULL)
         delete destRect;
 }
Friends And Related Function Documentation
friend class _GraphWorld_gen friend
Definition at line 701 of file RasterImage_binary.h.
Member Data Documentation
RasterImage_gray* uriVL::RasterImage_binary::grayForm_ mutable private
"Unpacked" gray-level version of this object.
This member is mutable because we can "change" it by allocating the object w/o really changing this binary image.
Definition at line 563 of file RasterImage_binary.h.
Referenced by getGrayRasterImage(), RasterImage_binary(), setBoundRect_(), setValidRect_(), updateRaster_(), and ~RasterImage_binary().
bool uriVL::RasterImage_binary::unpackedRasterIsReference_ mutable private
2D array mapped on the GraphWorld's 1D raster.
"shifted" 2D array mapped on the GraphWorld's 1D raster.Indicates whether the "unpacked" raster (rather than the "packed" binary raster) is the reference
Definition at line 578 of file RasterImage_binary.h.
Referenced by getBw(), getBw2D(), getGrayRasterImage(), getRaster(), getRaster2D(), getShiftedBw2D(), and getShiftedRaster2D().
The documentation for this class was generated from the following files:
RasterImage_binary.h
RasterImage_binary.cpp