URIVisionLibrary: uriVL::BackgroundRemover_static Class Reference
uriVL::BackgroundRemover_static Class Reference
Image operator that computes differences between images.
#include <BackgroundRemover_static.h>
Public Member Functions
BackgroundRemover_static (void)
Default constructor.
virtual ~BackgroundRemover_static (void)
Destructor.
void setBackground (RasterImage *img)
Overided virtual func.
Public Member Functions inherited from uriVL::BackgroundRemover
BackgroundRemover (void)
Default constructor.
virtual ~BackgroundRemover (void)
Destructor.
RasterImage_gray * removeBackground (RasterImage *imgIn)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images)
RasterImage_gray * removeBackground (RasterImage *imgIn, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images) into a gray-level raster image received as parameter.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background into a gray-level raster image received as parameter.
void setColorDifferenceMode (ColorDifferenceMode mode)
Sets the default color difference mode for this object.
RasterImage * getBackground (void)
get background_;
ColorDifferenceMode getColorDifferenceMode (void)
Reports what is the color difference mode for this object.
Additional Inherited Members
Protected Member Functions inherited from uriVL::BackgroundRemover
void assignBackground_ (RasterImage *img)
Detailed Description
Image operator that computes differences between images.
The BackgroundRemover_static class operates either in static mode (compute the difference between to raster images) or in "instance" mode" (compute the difference between an image and a "background" image stored by the BackgroundRemover_static object.
Note that image differences are always positive unsigned char
The basic rules for image differences are as follows
The output image is a RasterImage_gray (possibly a RasterImage_gray_F);
If one of the two images has a "<code>float</code>" raster as reference, then that raster will be use to compute the difference;
If the difference function must return an image (i.e. the output image is not passed as a parameter), then if the difference function calculates a "<code>float</code>" difference, the raster returned will be of type RasterImage_gray_F;
If one of the two input images is a gray raster, the other image will be converted to gray before computing the difference;
If one image is RGB and the other RGBa, then the former will be converted to RGBA before computing the difference.
Very Important Note Regarding "Float" Images"
If an image has a float raster as reference, then that raster will be used to calculate the image difference. This can pose problems for float images that are not using the range 0-255. There are two workarounds for that problem:
rescale the raster's values to the desired range using RasterImage::scaleValues(minVal, maxVal)
call in sequence
unsigned char** gray2D = myFloatImage->getGray2D() (forces float to char conversion)
unsigned char** gray2D = myFloatImage->setGWorldAsReference(true)
Using the first solution, a float difference will be calculated while the second solution will give an "integer" difference.
@author         jyh and Fang Han
@version        1.1
(Abstract)Base class: BackgroundRemover
Definition at line 74 of file BackgroundRemover_static.h.
Constructor & Destructor Documentation
BackgroundRemover_static::BackgroundRemover_static (void)
Default constructor.
Definition at line 25 of file BackgroundRemover_static.cpp.
References uriVL::AVERAGE_DIFFERENCE, and uriVL::BackgroundRemover::setColorDifferenceMode().
         :   BackgroundRemover()
 {
     setColorDifferenceMode(AVERAGE_DIFFERENCE);
 }
BackgroundRemover_static::~BackgroundRemover_static (void) virtual
Destructor.
Definition at line 31 of file BackgroundRemover_static.cpp.
 {
 }
Member Function Documentation
void BackgroundRemover_static::setBackground (RasterImage * img) virtual
Overided virtual func.
Stores a copy of img to use as background for future image difference computations
Parameters
img raster image to store as background image
Implements uriVL::BackgroundRemover.
Definition at line 37 of file BackgroundRemover_static.cpp.
References uriVL::ErrorReport::appendToMessage(), and uriVL::BackgroundRemover::assignBackground_().
 {
     try {
         assignBackground_(img);
     }
     catch (ErrorReport& e) {
         e.appendToMessage("called by BackgroundRemover_static::setBackground.");
         throw e;
     }
 }
The documentation for this class was generated from the following files:
BackgroundRemover_static.h
BackgroundRemover_static.cpp