URIVisionLibrary: uriVL::Pattern2D Class Reference
uriVL::Pattern2D Class Reference
A Pattern2D is defined as a connected set of pixels.
#include <Pattern2D.h>
Public Member Functions
Pattern2D (void)
A new empty Pattern2D.
Pattern2D (const Blob *blob, const ImageRect *rect, const RasterImage *img, bool safe=false)
A new Pattern2D is defined by a Blob (connected set of pixels), an ImageRect and a RasterImage to get pixel data from.
Pattern2D (const Blob *blob, const RasterImage *img, bool safe=false)
A new Pattern2D is defined by a Blob (connected set of pixels) and a RasterImage to get pixel data from.
Pattern2D (const ImageRect *rect, const RasterImage *img)
A new Pattern2D is defined by an image rectangle and a RasterImage to get pixel data from.
Pattern2D (BaseRasterType rasterType, int nbRows, int nbCols)
A new rectangular Pattern2D is defined by its dimensions.
virtual ~Pattern2D (void)
Destructor.
void setPattern (const Pattern2D *newPattern)
sets new raster and blob info for this pattern.
void setPattern (const RasterImage *patImg, const Blob *patBlob)
sets new raster and blob info for this pattern.
void assignPattern (const RasterImage *patImg, const Blob *patBlob)
Assigns new raster and blob info for this pattern.
const RasterImage * getPattern (void) const
Returns a reference to the pattern's pixel data.
const Blob * getBlob (void) const
Returns a reference to the pattern's blob data.
const ImageRect * getBoundRect () const
Returns the pattern's bounding rectangle.
const ImageRect * getValidRect () const
Returns the pattern's valid data rectangle.
long getNbPixels () const
Returns the total number of pixels in the pattern.
void writeInto (RasterImage *imgOut, const ImagePoint *origin)
Writes this pattern into a raster image using the point specified as origin for this pattern's valid rectangle's upper-left corner.
void update (const Pattern2D *newPattern, bool updateBlob=false)
Update the state of this pattern using the new measurement received as parameter, using the selected pattern update mode.
void update (const RasterImage *newImg, const Blob *newBlob, bool updateBlob)
Update the state of this pattern using the new measurement received as parameter, using the selected pattern update mode.
void setUpdateMode (Pattern2DUpdateMode updateMode)
Sets a new Individual update mode for this pattern (hasIndivUpdateMode_ is now true).
bool contains (const ImagePoint *pt)
Checks whether the point passed as parameter belongs to the pattern.
bool contains (int x, int y)
Checks whether the point passed as parameter is inside the pattern.
void setDrawContour (bool drawContour)
Tells the blob whether its contour should be drawn when the pattern is rendered.
void setContourColor (float red, float green, float blue)
Assigns a rendering color to the contour (alpha is set to 1)
void setContourColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour (alpha is set to 1)
void setContourColor (const float theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setContourColor (const unsigned char theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
void setBlob (const Blob *blob, const ImagePoint *point)
Assigns a reference to the pattern's blob data.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
void setRenderingScale (float scale) const
Sets a uniform scale at which this image should be rendered.
void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this image should be rendered.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void setDefaultUpdateMode (Pattern2DUpdateMode defaultUpdateMode)
Sets a new default pattern update mode for this class.
static void grabInto (RasterImage *img, const ImageRect *rect, Pattern2D *pattern)
Grabs a rectangular pattern in the input image and assign this value to the pattern object received as parameter.
static Pattern2D * grab (RasterImage *imIng, const ImageRect *rect)
Grabs a rectangular pattern in the input image and returns it as a new pattern object.
static void grabInto (RasterImage *imgIn, Blob *blob, Pattern2D *pattern)
Grabs a 2D pattern in the input image at the location specified by the blob received as parameter and assign this value to the pattern object received as parameter.
static Pattern2D * grab (RasterImage *imgIn, Blob *blob)
Grabs a 2D pattern in the input image at the location specified by the blob returns it as a new pattern object.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Private Member Functions
Pattern2D (const Pattern2D &obj)
Copy constructor (disabled)
const Pattern2D & operator= (const Pattern2D &obj)
Copy operator: disabled.
void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the pattern.
void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the pattern.
void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders the pattern at the depth and location specified.
void renderBlobPattern_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders a blob pattern.
void computeBoundingRect_ (ImageRect &rect) const
Calculates the object's bounding rect.
void computeValidRect_ (ImageRect &rect) const
Calculates the object's valid box.
void computeCentroid_ (ImagePoint_F &cent) const
Computes the contour's centroid.
void computeCenterOfMass_ (ImagePoint_F &cent) const
Computes the object's center of mass by calculating the average point.
Private Attributes
const Blob * blob_
Reference to the blob that lists the pixels making up the pattern.
const RasterImage * pattern_
The pixel value of the pattern over the blob's bounding rectangle.
bool hasIndivUpdateMode_
True if this pattern has an "individual" (non-default) update mode.
Pattern2DUpdateMode updateMode_
Individual update mode for this pattern (if hasIndivUpdateMode_ is true).
bool drawContour_
When rendering the pattern, draw its contour.
bool patImgIsLocal_
True when the pattern image is local to the object.
bool patBlobIsLocal_
True when the pattern's blob is local to the object.
Static Private Attributes
static Pattern2DUpdateMode defaultUpdateMode_ = REPLACE_PATTERN
Default pattern update mode for this class.
Additional Inherited Members
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Detailed Description
A Pattern2D is defined as a connected set of pixels.
A Pattern2D can be stored either as a Blob or as a rectangular region. In either case, image information is stored for each pixel of the Pattern. The indices of the pixels of the blob and of the image stored have been shifted so that the pattern's upper-left corner is at (0, 0).
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 53 of file Pattern2D.h.
Constructor & Destructor Documentation
Pattern2D::Pattern2D (void)
A new empty Pattern2D.
Definition at line 36 of file Pattern2D.cpp.
Referenced by grab().
                 :   DrawableObject2D(),
                         //
                         blob_(NULL),
                         pattern_(NULL),
                         hasIndivUpdateMode_(false),
                         updateMode_(REPLACE_PATTERN),
                         drawContour_(false),
                         patImgIsLocal_(false),
                         patBlobIsLocal_(false)
 {
 }
Pattern2D::Pattern2D (const Blob * blob, const ImageRect * rect, const RasterImage * img, bool safe = false)
A new Pattern2D is defined by a Blob (connected set of pixels), an ImageRect and a RasterImage to get pixel data from.
(blob and rect must have the same upperleft) (blob's rect and rect must have the same upperleft and rect cover larger area).
If you you decide to use the "fast", usafe mode, then you cannot delete the object blob refers to before this Pattern2D object has been deleted.
Parameters
blob list of connected pixels that define the pattern's geometry
img RasterImage where to get pixel data from
safe when true, a copy of the blob will be created and stored
Definition at line 49 of file Pattern2D.cpp.
References blob_, drawContour_, FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::grab(), hasIndivUpdateMode_, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, patBlobIsLocal_, patImgIsLocal_, and pattern_.
                 :   DrawableObject2D(*blob),
                         //
                         blob_(NULL),
                         pattern_(NULL),
                         hasIndivUpdateMode_(false),
                         updateMode_(REPLACE_PATTERN),
                         drawContour_(false),
                         patImgIsLocal_(false),
                         patBlobIsLocal_(false)
 {
     FAIL_CONDITION(     rect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect passed as parameter to Pattern2D constructor");
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL raster image passed as parameter to Pattern2D constructor");
     FAIL_CONDITION(     blob == NULL,
                     kNullParameterError,
                     "NULL blob passed as parameter to Pattern2D constructor");
         const ImageRect* blobRect = blob->getValidRect();
     FAIL_CONDITION(     (blobRect->getLeft() != rect->getLeft())  ||
                     (blobRect->getTop() != rect->getTop())    ||
                             (blobRect->getRight() > rect->getRight()) ||
                     (blobRect->getBottom() > rect->getBottom()),
                     kNullParameterError,
                     "blob and rect must have the same upperLeft and rect must cover larger area in Pattern2D constructor");
         if (safe)
         {
         ImagePoint  origin(0, 0);
         pattern_ = img->grab(rect, &origin);
         blob_ = new Blob(blob, &origin);
         patImgIsLocal_ = patBlobIsLocal_ = true;
     }
     else
     {
         pattern_ = img;
         blob_ = blob;
         patImgIsLocal_ = patBlobIsLocal_ = false;
     }
     drawContour_ = false;
     hasIndivUpdateMode_ = false;
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by Pattern2D constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( blob,
                                         kNullParameterError,
                                         "Null pointer passed to Pattern2D constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid  parameter passed to Pattern2D constructor.");
 }
Pattern2D::Pattern2D (const Blob * blob, const RasterImage * img, bool safe = false)
A new Pattern2D is defined by a Blob (connected set of pixels) and a RasterImage to get pixel data from.
If you you decide to use the "fast", usafe mode, then you cannot delete the object blob refers to before this Pattern2D object has been deleted.
Parameters
blob list of connected pixels that define the pattern's geometry
img RasterImage where to get pixel data from
safe when true, a copy of the blob will be created and stored
Definition at line 113 of file Pattern2D.cpp.
References blob_, drawContour_, FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::grab(), hasIndivUpdateMode_, uriVL::kNullRasterImageError, patBlobIsLocal_, patImgIsLocal_, and pattern_.
                 :   DrawableObject2D(*blob),
                         //
                         blob_(NULL),
                         pattern_(NULL),
                         hasIndivUpdateMode_(false),
                         updateMode_(REPLACE_PATTERN),
                         drawContour_(false),
                         patImgIsLocal_(false),
                         patBlobIsLocal_(false)
 {
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL raster image passed as parameter to Pattern2D constructor");
     const ImageRect* rect;
     //  if we have a blob we use its valid rect.
     if (blob != NULL)
         rect = blob->getBoundRect();
     //  otherwise that of the image will do
     else
         rect = img->getValidRect();
         if (safe)
         {
         ImagePoint  origin(0, 0);
         pattern_ = img->grab(rect, &origin);
         blob_ = new Blob(blob, &origin);
         patImgIsLocal_ = patBlobIsLocal_ = true;
     }
     else
     {
 //temp
         ImagePoint  origin(0, 0);
         pattern_ = img->grab(rect, &origin);
         blob_ = new Blob(blob, &origin);
         patImgIsLocal_ = patBlobIsLocal_ = false;
     }
 /*
     ImagePoint  origin(0, 0);
 //jyh
     pattern_ = img->grab(rect, &origin);
 //jyh
     if (blob != NULL)
         blob_ = new Blob(blob, &origin);
     else
         blob_ = NULL;
 */
         patImgIsLocal_ = patBlobIsLocal_ = true;
     drawContour_ = false;
     hasIndivUpdateMode_ = false;
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by Pattern2D constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( blob,
                                         kNullParameterError,
                                         "Null pointer passed to Pattern2D constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid  parameter passed to Pattern2D constructor.");
 }
Pattern2D::Pattern2D (const ImageRect * rect, const RasterImage * img)
A new Pattern2D is defined by an image rectangle and a RasterImage to get pixel data from.
Parameters
rect image rectangle that define the pattern's geometry
img RasterImage where to get pixel data from
Definition at line 182 of file Pattern2D.cpp.
References blob_, drawContour_, FAIL_CONDITION, uriVL::RasterImage::grab(), hasIndivUpdateMode_, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, patBlobIsLocal_, patImgIsLocal_, and pattern_.
                         :   DrawableObject2D(rect),
                                 //
                         //
                         blob_(NULL),
                         pattern_(NULL),
                         hasIndivUpdateMode_(false),
                         updateMode_(REPLACE_PATTERN),
                         drawContour_(false),
                         patImgIsLocal_(false),
                         patBlobIsLocal_(false)
 {
     FAIL_CONDITION(     img == NULL,
                     kNullRasterImageError,
                     "NULL raster image passed as parameter to Pattern2D constructor");
     FAIL_CONDITION(     rect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect passed as parameter to Pattern2D constructor");
     ImagePoint  origin(0, 0);
     pattern_ = img->grab(rect, &origin);
     blob_ = NULL;
         patImgIsLocal_ = true;
         patBlobIsLocal_ = false;
     drawContour_ = false;
     hasIndivUpdateMode_ = false;
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by Pattern2D constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint pointer passed to Pattern2D constructor.");
 }
Pattern2D::Pattern2D (BaseRasterType rasterType, int nbRows, int nbCols)
A new rectangular Pattern2D is defined by its dimensions.
Parameters
rasterType what kind of image raster the pattern stores
nbRows number of rows of the pattern
nbCols number of columns of the pattern
Definition at line 223 of file Pattern2D.cpp.
References blob_, drawContour_, FAIL_CONDITION, hasIndivUpdateMode_, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kRasterImageError, uriVL::kRGBa32Raster, patBlobIsLocal_, patImgIsLocal_, and pattern_.
                         :   DrawableObject2D(nbRows, nbCols),
                                 //
                                 blob_(NULL),
                                 pattern_(NULL),
                                 hasIndivUpdateMode_(false),
                                 updateMode_(REPLACE_PATTERN),
                                 drawContour_(false),
                                 patImgIsLocal_(false),
                                 patBlobIsLocal_(false)
 {
     FAIL_CONDITION(     nbRows < 2,
                     kInvalidParameterError,
                     "A Pattern2D must be at least 2x2");
     FAIL_CONDITION(     nbCols < 2,
                     kInvalidParameterError,
                     "A Pattern2D must be at least 2x2");
     switch (rasterType)
     {
         case kBinaryRaster:
             pattern_ = new RasterImage_binary(nbRows, nbCols);
             break;
         case kGrayRaster:
             pattern_ = new RasterImage_gray(nbRows, nbCols);
             break;
         case kRGBa32Raster:
             pattern_ = new RasterImage_RGBa(nbRows, nbCols);
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in Pattern2D constructor");
             break;
     }
     blob_ = NULL;
         patImgIsLocal_ = true;
         patBlobIsLocal_ = false;
     drawContour_ = false;
     hasIndivUpdateMode_ = false;
 }
 catch(ErrorReport& e) {
         e.appendToMessage("called by Pattern2D constructor.");
         throw e;
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint pointer passed to Pattern2D constructor.");
 }
Pattern2D::~Pattern2D (void) virtual
Destructor.
Definition at line 299 of file Pattern2D.cpp.
References blob_, patBlobIsLocal_, patImgIsLocal_, and pattern_.
 {
     if (patBlobIsLocal_ && (blob_ != NULL))
         delete blob_;
     if (patImgIsLocal_ && (pattern_ != NULL))
         delete pattern_;
 }
Pattern2D::Pattern2D (const Pattern2D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 281 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :   DrawableObject2D(),
                         //
                         blob_(NULL),
                         pattern_(NULL),
                         hasIndivUpdateMode_(false),
                         updateMode_(REPLACE_PATTERN),
                         drawContour_(false),
                         patImgIsLocal_(false),
                         patBlobIsLocal_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Pattern2D copy constructor not implemented");
 }
Member Function Documentation
void Pattern2D::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implements uriVL::DrawableObject2D.
Definition at line 717 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void Pattern2D::assignPattern (const RasterImage * patImg, const Blob * patBlob)
Assigns new raster and blob info for this pattern.
This function does not copy the data, just references to the original objects. This is equivalent to the "unsafe" mode of the constructor
See also
patImgIsLocal_
patBlobIsLocal_
Definition at line 368 of file Pattern2D.cpp.
References blob_, FAIL_CONDITION, uriVL::kNullRasterImageError, patBlobIsLocal_, patImgIsLocal_, and pattern_.
Referenced by uriVL::WarpMatchScoreFunctionND::setPattern().
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL raster image passed as parameter to Pattern2D::assignPattern");
     if (patImgIsLocal_ && (pattern_ != NULL))
         delete pattern_;
     pattern_ = patImg;
         patImgIsLocal_ = false;
     if (patBlobIsLocal_ && (blob_ != NULL))
             delete blob_;
     blob_ = patBlob;
         patBlobIsLocal_ = false;
 }
void Pattern2D::computeBoundingRect_ (ImageRect & rect) const private virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 924 of file Pattern2D.cpp.
 {
 }
void Pattern2D::computeCenterOfMass_ (ImagePoint_F & cent) const private virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implements uriVL::DrawableObject2D.
Definition at line 939 of file Pattern2D.cpp.
 {
 }
void Pattern2D::computeCentroid_ (ImagePoint_F & cent) const private virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implements uriVL::DrawableObject2D.
Definition at line 934 of file Pattern2D.cpp.
 {
 }
void Pattern2D::computeValidRect_ (ImageRect & rect) const private virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 929 of file Pattern2D.cpp.
 {
 }
bool Pattern2D::contains (const ImagePoint * pt)
Checks whether the point passed as parameter belongs to the pattern.
Parameters
pt the point to check
Returns
true if pt is inside this pattern's contour
Definition at line 686 of file Pattern2D.cpp.
References FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and uriVL::kNullParameterError.
 {
     FAIL_CONDITION( q == NULL,
                     kNullParameterError,
                     "Null ImagePoint passed to Blob::isInside");
     return contains(q->getX(), q->getY());
 }
bool Pattern2D::contains (int x, int y)
Checks whether the point passed as parameter is inside the pattern.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
Returns
true if pt is inside this pattern
Definition at line 695 of file Pattern2D.cpp.
References blob_, uriVL::Blob::contains(), uriVL::ImageRect::contains(), and getBoundRect().
 {
     if (blob_ == NULL)
         return getBoundRect()->contains(x, y);
     else
         return blob_->contains(x, y);
 }
const Blob * Pattern2D::getBlob (void) const
Returns a reference to the pattern's blob data.
Returns
a reference to the pattern's blob data
Definition at line 393 of file Pattern2D.cpp.
References blob_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::PatternTracker2D::grabImage_(), uriVL::PatternMatcher2D::match(), uriVL::PatternMatcher2D_warp::match(), uriVL::PatternTracker2D::PatternTracker2D(), printBlobs(), uriVL::PatternMatcher2D_warp::reverseWarp_(), uriVL::PatternMatcher2D_medianDiff::setPattern(), uriVL::PatternMatcher2D_scaledDiff::setPattern(), uriVL::PatternMatcher2D_corr::setPattern(), uriVL::PatternMatcher2D::setPattern(), uriVL::WarpMatchScoreFunctionND::setPattern(), setPattern(), uriVL::PatternMatcher2D_warp::setPattern(), uriVL::PatternTracker2D::track(), and update().
 {
     return blob_;
 }
const ImageRect * Pattern2D::getBoundRect (void) const virtual
Returns the pattern's bounding rectangle.
Returns a pointer to the pattern's bounding rectangle, which is either the of the blob or (if the blob is NULL) that of the RasterImage pattern. Note that this rectangle always has its upper-left corner at (0,0).
Returns
pointer to the pattern's bounding rectangle
See also
validRect_
boundRect_
getValidRect
Reimplemented from uriVL::DrawableObject2D.
Definition at line 398 of file Pattern2D.cpp.
References getValidRect().
Referenced by contains(), and uriVL::PatternTracker2D::PatternTracker2D().
 {
     return getValidRect();
 }
long Pattern2D::getNbPixels (void) const
Returns the total number of pixels in the pattern.
Returns
total number of pixels in the pattern
Definition at line 427 of file Pattern2D.cpp.
References blob_, uriVL::DrawableObject2D::getHeight(), uriVL::Blob::getNbPixels(), uriVL::DrawableObject2D::getWidth(), and pattern_.
Referenced by uriVL::PatternTracker2D::track().
 {
     if (blob_ == NULL)
         return pattern_->getWidth() * pattern_->getHeight();
     else
         return blob_->getNbPixels();
 }
const RasterImage * Pattern2D::getPattern (void) const
Returns a reference to the pattern's pixel data.
Returns
a reference to the pattern's pixel data
Definition at line 387 of file Pattern2D.cpp.
References pattern_.
Referenced by uriVL::PatternMatcher2D::match(), uriVL::PatternMatcher2D_warp::match(), uriVL::RectifiedStereoMatcher_corr::match_(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::PatternMatcher2D_medianDiff::setPattern(), uriVL::PatternMatcher2D_scaledDiff::setPattern(), uriVL::PatternMatcher2D_corr::setPattern(), uriVL::PatternMatcher2D::setPattern(), uriVL::WarpMatchScoreFunctionND::setPattern(), setPattern(), uriVL::PatternMatcher2D_warp::setPattern(), and update().
 {
     return pattern_;
 }
const ImageRect * Pattern2D::getValidRect (void) const virtual
Returns the pattern's valid data rectangle.
Returns a pointer to the pattern's valid data rectangle, which is either the of the blob or (if the blob is NULL) that of the RasterImage pattern. Note that this rectangle always has its upper-left corner at (0,0).
Returns
pointer to the pattern's valid data rectangle
See also
validRect_
boundRect_
getBoundRect
Reimplemented from uriVL::DrawableObject2D.
Definition at line 403 of file Pattern2D.cpp.
References blob_, uriVL::DrawableObject2D::getValidRect(), and pattern_.
Referenced by getBoundRect(), and writeInto().
 {
     if (blob_ != NULL)
         return blob_->getValidRect();
     else
         return pattern_->getValidRect();
 }
Pattern2D * Pattern2D::grab (RasterImage * imIng, const ImageRect * rect) static
Grabs a rectangular pattern in the input image and returns it as a new pattern object.
Parameters
imgIn the image to grab the pattern into
rect the rectangle within within to grab the pattern
Returns
a new rectangular Pattern2D object
Definition at line 665 of file Pattern2D.cpp.
References Pattern2D().
 {
     return new Pattern2D(rect, imgIn);
 }
Pattern2D * Pattern2D::grab (RasterImage * imgIn, Blob * blob) static
Grabs a 2D pattern in the input image at the location specified by the blob returns it as a new pattern object.
Parameters
imgIn the image to grab the pattern into
blob the blob template within within to grab the pattern
Returns
a new Pattern2D object
Definition at line 679 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void Pattern2D::grabInto (RasterImage * img, const ImageRect * rect, Pattern2D * pattern) static
Grabs a rectangular pattern in the input image and assign this value to the pattern object received as parameter.
Parameters
imgIn the image to grab the pattern into
rect the rectangle within within to grab the pattern
pattern the rectangular Pattern2D object in which to store the data grabbed
Definition at line 657 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void Pattern2D::grabInto (RasterImage * imgIn, Blob * blob, Pattern2D * pattern) static
Grabs a 2D pattern in the input image at the location specified by the blob received as parameter and assign this value to the pattern object received as parameter.
Parameters
imgIn the image to grab the pattern into
blob the blob template within within to grab the pattern
pattern the Pattern2D object in which to store the data grabbed
Definition at line 671 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
const Pattern2D & Pattern2D::operator= (const Pattern2D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 309 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Pattern2D copy operator not implemented");
         return *this;
 }
void Pattern2D::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private virtual
Renders the pattern at the depth and location specified.
A drawable object can be rendered with its valid data rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
Implements uriVL::DrawableObject2D.
Definition at line 820 of file Pattern2D.cpp.
References blob_, pattern_, uriVL::DrawableObject2D::render(), and renderBlobPattern_().
 {
     if (blob_ == NULL)
         pattern_->render(theZ, shifted, origin);
     else
         renderBlobPattern_(scaledLeft, scaledTop, scaledRight, scaledBottom, theZ, shifted, origin);
 }
void Pattern2D::renderBlobPattern_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private
Renders a blob pattern.
Renders a blob pattern at the depth and location specified by drawing the value of the image at the pixels that belong to the blob.
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
the gray raster (re-binarize it).
Definition at line 830 of file Pattern2D.cpp.
References blob_, drawContour_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::RasterImage::getRaster2D(), uriVL::DrawableObject2D::getRenderingScaleX(), uriVL::DrawableObject2D::getRenderingScaleY(), uriVL::Blob::getSegDeque(), uriVL::RasterImage::graphWorldIsReference(), uriVL::kaRGB16Raster, uriVL::kaRGB32Raster, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kLongGrayRaster, uriVL::kNoCode, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kUndefRasterType, uriVL::HorizontalSegment::leftX, pattern_, uriVL::RasterImage::referenceHasChanged(), uriVL::Blob::renderContour(), uriVL::RasterImage::requestRasterUpdate(), uriVL::HorizontalSegment::rightX, and uriVL::HorizontalSegment::y.
Referenced by render_().
 {
     //--------------------------------------------------------------
     //  Part 1: make sure that what we draw is up to date
     //--------------------------------------------------------------
     //  Binary images are a special case.  OpenGL cannot draw QD binary
     //  raster, so we need to use the gray raster instead.
     bool    binaryRaster = (pattern_->getBaseRasterType() == kBinaryRaster);
     if (binaryRaster)
     {
         //  if the gworld is the reference and has been modified, or
         //  the gray raster has been modified, update
         /// the gray raster (re-binarize it).
         if (pattern_->graphWorldIsReference() || pattern_->referenceHasChanged())
             pattern_->requestRasterUpdate( );
     }
     else
         //  For other image types, the base raster is the one to draw, so if it
         //  is not up-to-date, update it.
         if ( !pattern_->graphWorldIsReference() && pattern_->referenceHasChanged() )
             pattern_->requestRasterUpdate( );
     //--------------------------------------------------------------
     //  Part 2: render the blob pattern
     //--------------------------------------------------------------
     //  I apply a -1 scaling vertical scaling to my image so that it gets displayed
     //  with the right side up.
     GLenum  rasterType;
     int     pixelDepth;
     switch (pattern_->getBaseRasterType())
     {
         case kBinaryRaster:
         case kGrayRaster:
             rasterType = GL_LUMINANCE;
             pixelDepth = 1;
             break;
         case kRGB24Raster:
             rasterType = GL_RGB;
             pixelDepth = 3;
             break;
         case kRGBa32Raster:
             rasterType = GL_RGBA;
             pixelDepth = 4;
             break;
         case kUndefRasterType:
         case kLongGrayRaster:
         case kaRGB16Raster:
         case kaRGB32Raster:
             FAIL_CONDITION(true, kNoCode, "Unhandled case in a switch statement");
     }
     const unsigned char* const* raster = pattern_->getRaster2D();
         const float SCALE_X = getRenderingScaleX(),
                                 SCALE_Y = getRenderingScaleY();
     glPushMatrix();
     glLoadIdentity();
     glPixelZoom(SCALE_X, -SCALE_Y);
     const LineSegDeque segDeque = blob_->getSegDeque();
     LineSegDeque::const_iterator lastLine = segDeque.end();
     for (LineSegDeque::const_iterator lineIter = segDeque.begin(); lineIter != lastLine; lineIter++)
     {
         list<HorizontalSegment*>::iterator lastSeg = (*lineIter)->end();
         for (list<HorizontalSegment*>::iterator segIter = (*lineIter)->begin(); segIter != lastSeg; segIter++)
         {
             HorizontalSegment   *theSeg;
             theSeg = (*segIter);
             glRasterPos3f(scaledLeft + SCALE_X*theSeg->leftX,
                                         scaledTop - SCALE_Y*theSeg->y, theZ);
             glDrawPixels(theSeg->rightX - theSeg->leftX + 1, 1,
                          rasterType, GL_UNSIGNED_BYTE,
                          raster[theSeg->y] + pixelDepth*theSeg->leftX);
         }
     }
     glPopMatrix();
     //--------------------------------------------------------------
     //  Part 3: if needed, draw the blob's contour
     //--------------------------------------------------------------
     if (drawContour_)
         blob_->renderContour(theZ,  shifted, origin);
 }
void Pattern2D::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implements uriVL::DrawableObject2D.
Definition at line 709 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void Pattern2D::setBlob (const Blob * blob, const ImagePoint * point)
Assigns a reference to the pattern's blob data.
Parameters
blob a reference to a blob
point a reference to an ImagePoint
Definition at line 730 of file Pattern2D.cpp.
References blob_.
 {
     blob_ = new Blob(blob, point);
 }
void Pattern2D::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the pattern.
At this point I am not quite sure what this function should do. It has to be implemented because a Pattern2D is a DrawableObject2D.
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Definition at line 412 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void Pattern2D::setContourColor (float red, float green, float blue)
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 735 of file Pattern2D.cpp.
References blob_, uriVL::Blob::setContourColor(), and uriVL::DrawableObject2D::setFrameColor().
Referenced by myDisplay2().
 {
     if (blob_ != NULL)
         blob_->setContourColor(red, green, blue);
     //  if this is a rectangular pattern we interpret the call as meaning "draw frame"
     else
         setFrameColor(red, green, blue);
 }
void Pattern2D::setContourColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 758 of file Pattern2D.cpp.
References blob_, uriVL::Blob::setContourColor(), and uriVL::DrawableObject2D::setFrameColor().
 {
     if (blob_ != NULL)
         blob_->setContourColor(red, green, blue);
     //  if this is a rectangular pattern we interpret the call as meaning "draw frame"
     else
         setFrameColor(red, green, blue);
 }
void Pattern2D::setContourColor (const float theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 746 of file Pattern2D.cpp.
References blob_, uriVL::Blob::setContourColor(), and uriVL::DrawableObject2D::setFrameColor().
 {
     if (blob_ != NULL)
         blob_->setContourColor(theColor);
     //  if this is a rectangular pattern we interpret the call as meaning "draw frame"
     else
         setFrameColor(theColor);
 }
void Pattern2D::setContourColor (const unsigned char theColor[])
Assigns a rendering color to the contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 769 of file Pattern2D.cpp.
References blob_, uriVL::Blob::setContourColor(), and uriVL::DrawableObject2D::setFrameColor().
 {
     if (blob_ != NULL)
         blob_->setContourColor(theColor);
     //  if this is a rectangular pattern we interpret the call as meaning "draw frame"
     else
         setFrameColor(theColor);
 }
void Pattern2D::setDefaultUpdateMode (Pattern2DUpdateMode defaultUpdateMode) static
Sets a new default pattern update mode for this class.
See also
Pattern2DUpdateMode
defaultUpdateMode_
hasIndivUpdateMode_
Definition at line 642 of file Pattern2D.cpp.
References defaultUpdateMode_.
 {
     defaultUpdateMode_ = defaultUpdateMode;
 }
void Pattern2D::setDrawContour (bool drawContour)
Tells the blob whether its contour should be drawn when the pattern is rendered.
Parameters
drawContour true if the blob's contour is to be drawn
Definition at line 780 of file Pattern2D.cpp.
References blob_, drawContour_, uriVL::Blob::getContour(), and uriVL::DrawableObject2D::setDrawFrame().
Referenced by myDisplay2().
 {
     if (blob_ != NULL)
     {
         drawContour_ = drawContour;
         if (drawContour_) {
             //  force contour calculation
 // JYH:TOCHECK
 // I don't know if getContour() has a side effect, so I'm leaving the call
 // there.  But the variable 'rect' was going unused thus generating a compiler
 // warning. -CJC
 //             Contour *contour = blob_->getContour();
             blob_->getContour();
         }
     }
     //  if this is a rectangular pattern we interpret the call as meaning "draw frame"
     else
         setDrawFrame(drawContour);
 }
void Pattern2D::setPattern (const Pattern2D * newPattern)
sets new raster and blob info for this pattern.
This function actually copies the data. This is equivalent to the "safe" mode of the constructor.
Definition at line 327 of file Pattern2D.cpp.
References getBlob(), and getPattern().
 {
     setPattern(newPattern->getPattern(), newPattern->getBlob());
 }
void Pattern2D::setPattern (const RasterImage * patImg, const Blob * patBlob)
sets new raster and blob info for this pattern.
This function actually copies the data. This is equivalent to the "safe" mode of the constructor
Definition at line 332 of file Pattern2D.cpp.
References blob_, FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::grab(), uriVL::kNullRasterImageError, patBlobIsLocal_, patImgIsLocal_, and pattern_.
 {
     FAIL_CONDITION(     patImg == NULL,
                     kNullRasterImageError,
                     "NULL raster image passed as parameter to Pattern2D::setPattern");
     const ImageRect* rect;
     //  if we have a blob we use its valid rect.
     if (patBlob != NULL)
         rect = patBlob->getBoundRect();
     //  otherwise that of the image will do
     else
         rect = patImg->getValidRect();
         if (patImgIsLocal_ && (pattern_ != NULL))
                 delete pattern_;
         if (patBlobIsLocal_ && (blob_ != NULL))
                 delete blob_;
         ImagePoint  origin(0, 0);
         pattern_ = patImg->grab(rect, &origin);
         if (patBlob != NULL)
         {
                 blob_ = new Blob(patBlob, &origin);
                 patBlobIsLocal_ = true;
         }
         else
         {
                 blob_ = NULL;
                 patBlobIsLocal_ = false;
         }
 }
void Pattern2D::setRenderingScale (float scale) const virtual
Sets a uniform scale at which this image should be rendered.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function specifies the same scale for the horizontal and vertical directions (uniform scaling).
Parameters
scale scale for the horizontal and vertical directions
Reimplemented from uriVL::DrawableObject2D.
Definition at line 802 of file Pattern2D.cpp.
References blob_, pattern_, and uriVL::DrawableObject2D::setRenderingScale().
Referenced by myDisplay2().
 {
     pattern_->setRenderingScale(scale, scale);
     blob_->setRenderingScale(scale, scale);
 }
void Pattern2D::setRenderingScale (float scaleX, float scaleY) const virtual
Sets horizontal and vertical scales at which this image should be rendered.
An image can be rendered at different scales (smaller if the scale is less than 1, larger is the scale is greater than 1). This function specifies separate scales for the horizontal and vertical directions.
Parameters
scaleX scale for the horizontal direction
scaleY scale for the vertical direction
Reimplemented from uriVL::DrawableObject2D.
Definition at line 809 of file Pattern2D.cpp.
References blob_, pattern_, and uriVL::DrawableObject2D::setRenderingScale().
 {
     pattern_->setRenderingScale(scaleX, scaleY);
     blob_->setRenderingScale(scaleX, scaleY);
 }
void Pattern2D::setUpdateMode (Pattern2DUpdateMode updateMode)
Sets a new Individual update mode for this pattern (hasIndivUpdateMode_ is now true).
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
defaultUpdateMode_
hasIndivUpdateMode_
Definition at line 647 of file Pattern2D.cpp.
References hasIndivUpdateMode_, and updateMode_.
 {
     updateMode_ = updateMode;
     hasIndivUpdateMode_ = true;
 }
void Pattern2D::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the pattern.
At this point I am not quite sure what this function should do. It has to be implemented because a Pattern2D is a DrawableObject2D.
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Definition at line 420 of file Pattern2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void Pattern2D::update (const Pattern2D * newPattern, bool updateBlob = false)
Update the state of this pattern using the new measurement received as parameter, using the selected pattern update mode.
Parameters
newPattern the new measurement with which to update the state of this pattern
updateBlob whether update blob inside the pattern2D
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
Definition at line 571 of file Pattern2D.cpp.
References FAIL_CONDITION, getBlob(), getPattern(), and uriVL::kNullParameterError.
Referenced by uriVL::PatternTracker2D::track().
 {
     FAIL_CONDITION(     newPattern == NULL,
                     kNullParameterError,
                     "NULL pattern passed as parameter to Pattern2::update");
     update(newPattern->getPattern(), newPattern->getBlob(), updateBlob);
 }
void Pattern2D::update (const RasterImage * newImg, const Blob * newBlob, bool updateBlob)
Update the state of this pattern using the new measurement received as parameter, using the selected pattern update mode.
Parameters
newImage raster image of the new measurement with which to update the state of this pattern
newBlob blob info of the new measurement with which to update the state of this pattern
updateBlob whether update blob inside the pattern2D
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
Definition at line 580 of file Pattern2D.cpp.
References uriVL::AVERAGE_PATTERNS, defaultUpdateMode_, FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), hasIndivUpdateMode_, uriVL::INTERSECT_BLOBS_AVG_IMG, uriVL::INTERSECT_BLOBS_REPLACE_IMG, uriVL::kNullRasterImageError, uriVL::REPLACE_PATTERN, uriVL::UNION_BLOBS_AVG_IMG, uriVL::UNION_BLOBS_REPLACE_IMG, and updateMode_.
 {
     FAIL_CONDITION(     newImg == NULL,
                     kNullRasterImageError,
                     "NULL image passed as parameter to Pattern2::update");
     Pattern2DUpdateMode theMode;
     if (hasIndivUpdateMode_)
         theMode = updateMode_;
     else
         theMode = defaultUpdateMode_;
     ImagePoint  origin(0, 0);
     const ImageRect* rect;
     //  if we have a blob we use its valid rect.
     if (newBlob != NULL)
         rect = newBlob->getBoundRect();
     //  otherwise that of the image will do
     else
         rect = newImg->getValidRect();
     switch (theMode)
     {
         case REPLACE_PATTERN:
                 //      at this point:  Incomptible with setPattern/assignPattern distinction
 //              newImg->copyInto(pattern_, rect, &origin);
 //
 //              //      update blob_
 //              if (updateBlob)
 //              {
 //                      if (blob_ != NULL)
 //                      delete blob_;
 //
 //                  if (newBlob != NULL)
 //                          blob_ = new Blob(newBlob, &origin);
 //                      else
 //                          blob_ = NULL;
 //              }
             break;
         case UNION_BLOBS_REPLACE_IMG:
             break;
         case UNION_BLOBS_AVG_IMG:
             break;
         case INTERSECT_BLOBS_REPLACE_IMG:
             break;
         case INTERSECT_BLOBS_AVG_IMG:
             break;
         case AVERAGE_PATTERNS:
             break;
         default:
             break;
     }
 }
void Pattern2D::writeInto (RasterImage * imgOut, const ImagePoint * origin)
Writes this pattern into a raster image using the point specified as origin for this pattern's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the images' valid data rectangles.
Parameters
imgOut the image to write into
origin the point to use as origin for this pattern's valid data rectangle's upper-left corner.
Definition at line 440 of file Pattern2D.cpp.
References blob_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::Blob::getSegDeque(), getValidRect(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kNoCode, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, uriVL::HorizontalSegment::leftX, pattern_, uriVL::R_W_ACCESS, uriVL::HorizontalSegment::rightX, uriVL::RasterImage::writeInto(), and uriVL::HorizontalSegment::y.
Referenced by uriVL::PatternTracker2DController::action().
 {
         FAIL_CONDITION( imgOut == NULL,
                                         kNullRasterImageError,
                                         "Null rater image as parameter in Pattern2D::writeInto");
     if (blob_ == NULL)
         pattern_->writeInto(imgOut, origin);
     else
     {
 // JYH:TOCHECK
 // I don't know if getValidRect() has a side effect, so I'm leaving the call
 // there.  But the variable 'rect' was going unused thus generating a compiler
 // warning. -CJC
 //      ImageRect* rect = getValidRect();
         getValidRect();
         BaseRasterType  rasterType = pattern_->getBaseRasterType();
         if (rasterType == kGrayRaster)
         {
                         FAIL_CONDITION( true,
                                                         kFunctionNotImplemented,
                                                         "gray blob pattern wrinteInto not implemented yet");
         }
         else if (rasterType == kRGBa32Raster)
         {
                 const unsigned char* const* rgbaPat =
                                         (static_cast<const RasterImage_RGBa*>(pattern_))->getShiftedRGBa2D();
                 unsigned char* const* rgbaImg =
                             (static_cast<RasterImage_RGBa*>(imgOut))->getShiftedRGBa2D(R_W_ACCESS);
                 if (origin == NULL)
                 {
                                 FAIL_CONDITION( true,
                                                                 kFunctionNotImplemented,
                                                                 "gray blob pattern wrinteInto not implemented yet");
                 }
                 else
                 {
                 const LineSegDeque segDeque = blob_->getSegDeque();
                 LineSegDeque::const_iterator lastLine = segDeque.end();
                 int iI = origin->getY();
                 for (LineSegDeque::const_iterator lineIter = segDeque.begin(); lineIter != lastLine; lineIter++, iI++)
                 {
                     list<HorizontalSegment*>::iterator  segIter, lastSeg = (*lineIter)->end();
                     for (segIter = (*lineIter)->begin(); segIter != lastSeg; segIter++)
                     {
                         HorizontalSegment *theSeg = (*segIter);
                         int iP = theSeg->y;
                         for (int jP = theSeg->leftX, fourJP = 4*jP, jI = jP + origin->getX(), fourJI=4*jI;
                                                     jP<=theSeg->rightX; jP++, jI++, fourJP++, fourJI++)
{
 /*
                             rgbaImg[iI][fourJI++] = rgbaPat[iP][fourJP++];
                             rgbaImg[iI][fourJI++] = rgbaPat[iP][fourJP++];
                             rgbaImg[iI][fourJI++] = rgbaPat[iP][fourJP++];
 */
 //
                             unsigned char x, y, z;
                             x = rgbaPat[iP][fourJP++];
                             y = rgbaPat[iP][fourJP++];
                             z = rgbaPat[iP][fourJP++];
 //
                             rgbaImg[iI][fourJI++] = x;
                             rgbaImg[iI][fourJI++] = y;
                             rgbaImg[iI][fourJI++] = z;
                         }
                     }
                 }
                 }
         }
                 else
                         FAIL_CONDITION( true,
                                                         kNoCode,
                                                         "invalid raster type in Pattern2D::writeInto");
     }
 }
Member Data Documentation
const Blob* uriVL::Pattern2D::blob_ private
Reference to the blob that lists the pixels making up the pattern.
Definition at line 354 of file Pattern2D.h.
Referenced by assignPattern(), contains(), getBlob(), getNbPixels(), getValidRect(), Pattern2D(), render_(), renderBlobPattern_(), setBlob(), setContourColor(), setDrawContour(), setPattern(), setRenderingScale(), writeInto(), and ~Pattern2D().
Pattern2DUpdateMode Pattern2D::defaultUpdateMode_ = REPLACE_PATTERN static private
Default pattern update mode for this class.
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
hasIndivUpdateMode_
updateMode_
Definition at line 397 of file Pattern2D.h.
Referenced by setDefaultUpdateMode(), and update().
bool uriVL::Pattern2D::drawContour_ private
When rendering the pattern, draw its contour.
Definition at line 380 of file Pattern2D.h.
Referenced by Pattern2D(), renderBlobPattern_(), and setDrawContour().
bool uriVL::Pattern2D::hasIndivUpdateMode_ private
True if this pattern has an "individual" (non-default) update mode.
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
defaultUpdateMode_
updateMode_
Definition at line 367 of file Pattern2D.h.
Referenced by Pattern2D(), setUpdateMode(), and update().
bool uriVL::Pattern2D::patBlobIsLocal_ private
True when the pattern's blob is local to the object.
Definition at line 388 of file Pattern2D.h.
Referenced by assignPattern(), Pattern2D(), setPattern(), and ~Pattern2D().
bool uriVL::Pattern2D::patImgIsLocal_ private
True when the pattern image is local to the object.
Definition at line 384 of file Pattern2D.h.
Referenced by assignPattern(), Pattern2D(), setPattern(), and ~Pattern2D().
const RasterImage* uriVL::Pattern2D::pattern_ private
The pixel value of the pattern over the blob's bounding rectangle.
Definition at line 358 of file Pattern2D.h.
Referenced by uriVL::PatternTracker2DController::action(), assignPattern(), getNbPixels(), getPattern(), getValidRect(), Pattern2D(), render_(), renderBlobPattern_(), setPattern(), setRenderingScale(), writeInto(), and ~Pattern2D().
Pattern2DUpdateMode uriVL::Pattern2D::updateMode_ private
Individual update mode for this pattern (if hasIndivUpdateMode_ is true).
See also
Pattern2DUpdateMode
setDefaultUpdateMode
setUpdateMode
defaultUpdateMode_
hasIndivUpdateMode_
Definition at line 376 of file Pattern2D.h.
Referenced by setUpdateMode(), and update().
The documentation for this class was generated from the following files:
Pattern2D.h
Pattern2D.cpp