URIVisionLibrary: uriVL::GraphicComponent3D Class Reference
uriVL::GraphicComponent3D Class Reference abstract
This is the parent class for all basic 3D shapes (boxes, cylinders, quad and triangle meshes, generic polyhedra.
#include <GraphicComponent3D.h>
Public Member Functions
virtual ~GraphicComponent3D (void)
Destructor.
virtual void draw (void)
Draw the object in the current graphic context.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
virtual void setResolution (ResolutionLevel res)=0
Assigns a new drawing resolution to the object.
Static Public Member Functions
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
This is the parent class for all basic 3D shapes (boxes, cylinders, quad and triangle meshes, generic polyhedra.
Virtual objects are made up of one or more GraphicComponent3D objects. Important: A GraphicComponent3D is not a 3D object in the sense that it does not have a ReferenceFrame3D. A GraphicComponent3D is simply something that will be attached (has-a) to an Entity3D that need to be rendered.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 132 of file GraphicComponent3D.h.
Constructor & Destructor Documentation
GraphicComponent3D::~GraphicComponent3D (void) virtual
Destructor.
Definition at line 44 of file GraphicComponent3D.cpp.
 {
 }
GraphicComponent3D::GraphicComponent3D (void) protected
Default constructor.
Definition at line 32 of file GraphicComponent3D.cpp.
         :       shiny_(0.f)
 {
 }
Member Function Documentation
void GraphicComponent3D::commonNormalVector (GLfloat * e1, GLfloat * e2, GLfloat * nv) static
Definition at line 232 of file GraphicComponent3D.cpp.
References normalizeVector().
Referenced by uriVL::Cone3D::Cone3D(), uriVL::Cylinder3D::Cylinder3D(), faceAverageNormal(), faceExactNormal(), uriVL::HalfCone3D::HalfCone3D(), uriVL::HalfCylinder3D::HalfCylinder3D(), uriVL::Box3D::init_(), uriVL::HalfCylinder3D::init_(), uriVL::Cylinder3D::init_(), uriVL::Cone3D::init_(), uriVL::HalfCone3D::init_(), uriVL::TubularSection3D::TubularSection3D(), and vertexAverageNormal().
 {
         nv[0] = e1[1]*e2[2]-e1[2]*e2[1];
         nv[1] = e1[2]*e2[0]-e1[0]*e2[2];
         nv[2] = e1[0]*e2[1]-e1[1]*e2[0];
         normalizeVector(nv);
 }
void GraphicComponent3D::crossProduct (GLfloat * e1, GLfloat * e2, GLfloat * nv) static
Definition at line 210 of file GraphicComponent3D.cpp.
Referenced by uriVL::HalfCylinder3D::init_(), uriVL::Cylinder3D::init_(), uriVL::Cone3D::init_(), uriVL::TubularSection3D::init_(), and uriVL::HalfCone3D::init_().
 {
         nv[0] = e1[1]*e2[2]-e1[2]*e2[1];
         nv[1] = e1[2]*e2[0]-e1[0]*e2[2];
         nv[2] = e1[0]*e2[1]-e1[1]*e2[0];
 }
GLfloat GraphicComponent3D::dotProduct (GLfloat * e1, GLfloat * e2) static
Definition at line 191 of file GraphicComponent3D.cpp.
Referenced by faceAverageNormal().
 {
         return e1[0]*e2[0] + e1[1]*e2[1] + e1[2]*e2[2];
 }
void GraphicComponent3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented in uriVL::ElevationMap, uriVL::RangeMap, uriVL::DepthMap, uriVL::HalfCone3D, uriVL::TubularSection3D, uriVL::Cone3D, uriVL::Cylinder3D, uriVL::HalfCylinder3D, uriVL::Prism3D, uriVL::PolyMesh3D, and uriVL::Box3D.
Definition at line 126 of file GraphicComponent3D.cpp.
References setReflectionParameters_().
Referenced by uriVL::Box3D::draw(), uriVL::PolyMesh3D::draw(), uriVL::Prism3D::draw(), uriVL::Cylinder3D::draw(), uriVL::Cone3D::draw(), uriVL::TubularSection3D::draw(), and uriVL::HalfCone3D::draw().
 {
         setReflectionParameters_();
 }
void GraphicComponent3D::faceAverageNormal (GLuint n, GLfloat ** v, GLfloat * nVect) static
Definition at line 287 of file GraphicComponent3D.cpp.
References commonNormalVector(), dotProduct(), and normalizeVector().
Referenced by faceAverageNormal(), uriVL::Prism3D::init_(), and uriVL::PolyMesh3D::init_().
 {
         GLfloat nv[3],
                         e1[3], e2[3],
                         theta,
                         totalAngle;
         int     i, i1, i2, k;
         //      The difficulty in computing the average normal vector of a polygonal
         //      patch is that we can't just take any 3-tuple of vertices and compute a
         //      cross product because we don't know which way the computed normal vector
         //      will be pointing (i.o.w., do the 3 vertices form a convex or concave corner
         //      of the polygon?).  Here I am using the fact that going around the polygon
         //      counterclockwise really corresponds to doing a +2pi rotation around the
         //      normal vector.  So here is how I proceed.  Start from the first 3 points,
         //      compute the cross product, normalize.  This is +/- the desired normal vector
         //      (+ some error), but I don't know which.
         //      For all v_i, v_i+1 v_i+2 3-tuples of vertices, compute the cross product,
         //      if it points in the same direction as the first one, increment the angle,
         //      else decrement it.  In any case, add up +/- computed normal vector for the
         //      average.  In the end, if the sum of angles is 2pi, we have the right normal
         //      vector, otherwise we have its opposite.
         //-------------------------------------------------------------------------
         //      Initialize the computation with the first 3 vertices
         //-------------------------------------------------------------------------
         //      1. Compute the edge vectors and normalize them
         for (k=0; k<3; k++)
         {
                 e1[k] = v[1][k] - v[0][k];
                 e2[k] = v[2][k] - v[0][k];
         }
         normalizeVector(e1);
         normalizeVector(e2);
         //      2. Compute the cross product.  Store its normalized version as the
         //              first normal vector.  Compute the dot product and store its arcCos
         //              as the angle of the rotation.
         commonNormalVector(e1, e2, nVect);
         totalAngle = acosf(dotProduct(e1, e2));
         //-------------------------------------------------------------------------
         //      Go through the polygon, counterclockwise, and repeat the following
         //      step for all 3-tuples of consecutive vertices.
         //-------------------------------------------------------------------------
         for (i=1; i< static_cast<int>(n); i++)
         {
                 i1 = (i+1)%n;
                 i2 = (i+2)%n;
                 //      1. Compute the edge vectors and normalize them
                 for (k=0; k<3; k++)
                 {
                         e1[k] = v[i1][k] - v[i][k];
                         e2[k] = v[i2][k] - v[i][k];
                 }
                 normalizeVector(e1);
                 normalizeVector(e2);
                 //      2. compute the cross product and the angle of the rotation
                 commonNormalVector(e1, e2, nv);
                 theta = acosf(dotProduct(e1, e2));
                 //      3. If nv points in the same direction as the initial normal vector
                 //              everything is added up.
                 if (dotProduct(nv, nVect) > 0)
                 {
                         for (k=0; k<3; k++)
                                 nVect[k] += nv[k];
                         totalAngle += theta;
                 }
                 //      if the vectors point in opposite directions, we substract.
                 else
                 {
                         for (k=0; k<3; k++)
                                 nVect[k] -= nv[k];
                         totalAngle -= theta;
                 }
         }
         //-------------------------------------------------------------------------
         //      Once we have gone through all vertices, we check the sign of the total
         //      rotation we computed.  If it is > 0 (should be 2Pi), then we just have
         //      to normalize the normal vector.  If it is negative (should be -2Pi),
         //      then we must invert the normal vector before we return it.
         //-------------------------------------------------------------------------
         if (totalAngle < 0.f)
                 for (k=0; k<3; k++)
                         nVect[k] *= -1.f;
         normalizeVector(nVect);
 }
void GraphicComponent3D::faceAverageNormal (GLuint * index, GLfloat ** v, GLfloat * nVect) static
Definition at line 398 of file GraphicComponent3D.cpp.
References faceAverageNormal().
 {
         GLfloat         **vArray;
         unsigned int            i;
         vArray  = new GLfloat*[index[0]];
         for (i=0; i<index[0]; i++)
                 vArray[i] = v[index[i+1]];
         faceAverageNormal(index[0], vArray, nVect);
         delete [] vArray;
 }
void GraphicComponent3D::faceAverageNormal (GLfloat * v0, GLfloat * v1, GLfloat * v2, GLfloat * v3, GLfloat * nVect) static
Definition at line 428 of file GraphicComponent3D.cpp.
References normalizeVector().
 {
         //      computes the norm at the vertex as the average of the norm of the three
         //      triangles that this vertex participates to: v0-v1-v2, v0-v1-v3, v0-v2-v3
         nVect[0] = 2.f * (v3[1]*v0[2] - v1[1]*v0[2] + v0[1]*v1[2] - v0[1]*v3[2]) - v2[1]*v1[2] -
                                 v3[1]*v1[2] + v1[1]*v2[2] - v3[1]*v2[2] + v1[1]*v3[2] + v2[1]*v3[2];
         nVect[1] = 2.f * (v1[0]*v0[2] - v3[0]*v0[2] - v0[0]*v1[2] + v0[0]*v3[2]) + v2[0]*v1[2] +
                                         v3[0]*v1[2] - v1[0]*v2[2] + v3[0]*v2[2] - v1[0]*v3[2] - v2[0]*v3[2];
     nVect[2] = 2.f * (v3[0]*v0[1] - v1[0]*v0[1] + v0[0]*v1[1] - v0[0]*v3[1]) - v2[0]*v1[1] -
                                 v3[0]*v1[1] + v1[0]*v2[1] - v3[0]*v2[1] + v1[0]*v3[1] + v2[0]*v3[1];
         normalizeVector(nVect);
 }
void GraphicComponent3D::faceExactNormal (GLfloat * v0, GLfloat * v1, GLfloat * v2, GLfloat * nVect) static
Definition at line 257 of file GraphicComponent3D.cpp.
References commonNormalVector().
Referenced by uriVL::PolyMesh3D::init_().
 {
         GLfloat e1[3] = {v1[0]-v0[0], v1[1]-v0[1], v1[2]-v0[2]},
                         e2[3] = {v2[0]-v0[0], v2[1]-v0[1], v2[2]-v0[2]};
         commonNormalVector(e1, e2, nVect);
 }
GLfloat GraphicComponent3D::norm (GLfloat * V) static
Definition at line 151 of file GraphicComponent3D.cpp.
Referenced by normalizeVector().
 {
         return sqrtf(V[0]*V[0] + V[1]*V[1] + V[2]*V[2]);
 }
void GraphicComponent3D::normalizeVector (GLfloat * V) static
Definition at line 169 of file GraphicComponent3D.cpp.
References norm().
Referenced by commonNormalVector(), faceAverageNormal(), uriVL::Cylinder3D::init_(), uriVL::PolyMesh3D::init_(), uriVL::Cone3D::init_(), uriVL::TubularSection3D::init_(), and uriVL::HalfCone3D::init_().
 {
         GLfloat normScale = 1.0f / norm(V);
         V[0] *= normScale;
         V[1] *= normScale;
         V[2] *= normScale;
 }
void GraphicComponent3D::setMaterial (float params[])
Definition at line 67 of file GraphicComponent3D.cpp.
References ambientMat_, diffuseMat_, shiny_, and specularMat_.
Referenced by computeDepth(), and myDepthMenu().
 {
         ambientMat_[0] = params[0];
         ambientMat_[1] = params[1];
         ambientMat_[2] = params[2];
         //
         diffuseMat_[0] = params[3];
         diffuseMat_[1] = params[4];
         diffuseMat_[2] = params[5];
         //
         specularMat_[0] = params[6];
         specularMat_[1] = params[7];
         specularMat_[2] = params[8];
         //
         shiny_ = params[9];
 }
void GraphicComponent3D::setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Definition at line 84 of file GraphicComponent3D.cpp.
References ambientMat_, diffuseMat_, shiny_, and specularMat_.
 {
         ambientMat_[0] = ambRed;
         ambientMat_[1] = ambGreen;
         ambientMat_[2] = ambBlue;
         //
         diffuseMat_[0] = difRed;
         diffuseMat_[1] = difGreen;
         diffuseMat_[2] = difBlue;
         //
         specularMat_[0] = specRed;
         specularMat_[1] = specGreen;
         specularMat_[2] = specBlue;
         //
         shiny_ = shine;
 }
void GraphicComponent3D::setReflectionParameters_ (void) protected
Definition at line 117 of file GraphicComponent3D.cpp.
References ambientMat_, diffuseMat_, shiny_, and specularMat_.
Referenced by draw(), uriVL::DepthMap::drawDenseMesh_(), uriVL::RangeMap::drawDenseMesh_(), and uriVL::ElevationMap::drawDenseMesh_().
 {
         glMaterialfv(GL_FRONT, GL_AMBIENT, ambientMat_);
         glMaterialfv(GL_FRONT, GL_DIFFUSE, diffuseMat_);
         glMaterialfv(GL_FRONT, GL_SPECULAR, specularMat_);
         glMaterialf(GL_FRONT, GL_SHININESS, shiny_);
 }
virtual void uriVL::GraphicComponent3D::setResolution (ResolutionLevel res) pure virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implemented in uriVL::ElevationMap, uriVL::RangeMap, uriVL::DepthMap, uriVL::HalfCone3D, uriVL::TubularSection3D, uriVL::Cone3D, uriVL::Cylinder3D, uriVL::Prism3D, uriVL::PolyMesh3D, and uriVL::Box3D.
void GraphicComponent3D::vertexAverageNormal (GLfloat * v0, GLfloat * v1, GLfloat * v2, GLfloat * d, GLfloat * nVect) static
Definition at line 465 of file GraphicComponent3D.cpp.
References commonNormalVector().
Referenced by uriVL::Prism3D::init_().
 {
         GLfloat         e[3] = {vR[0]-vL[0], vR[1]-vL[1], vR[2]-vL[2]};
         //      n (unscaled) = (v0 - vL) x d  +  (vR - v0) x d  =  (vR - vL) x d.
         commonNormalVector(e, d, nVect);
 }
Member Data Documentation
GLfloat uriVL::GraphicComponent3D::ambientMat_[3] protected
stores "ambient" light material property for this object
Definition at line 170 of file GraphicComponent3D.h.
Referenced by uriVL::DepthMap::drawDenseMesh_(), uriVL::RangeMap::drawDenseMesh_(), uriVL::ElevationMap::drawDenseMesh_(), setMaterial(), and setReflectionParameters_().
GLfloat uriVL::GraphicComponent3D::diffuseMat_[3] protected
stores "diffuse" light material property for this object
Definition at line 174 of file GraphicComponent3D.h.
Referenced by setMaterial(), and setReflectionParameters_().
GLfloat uriVL::GraphicComponent3D::shiny_ protected
stores "shininess" light material property for this object
Definition at line 182 of file GraphicComponent3D.h.
Referenced by setMaterial(), and setReflectionParameters_().
GLfloat uriVL::GraphicComponent3D::specularMat_[3] protected
stores "specular" light material property for this object
Definition at line 178 of file GraphicComponent3D.h.
Referenced by setMaterial(), and setReflectionParameters_().
The documentation for this class was generated from the following files:
GraphicComponent3D.h
GraphicComponent3D.cpp