URIVisionLibrary: uriVL::VectorField Class Reference
uriVL::VectorField Class Reference abstract
VectorField class.
#include <VectorField.h>
Public Member Functions
virtual ~VectorField (void)
Destructor.
void copyInto (VectorField *out) const
Copies this vector field into the one received as parameter.
virtual void copyInto (VectorField *vectOut, const ImageRect *theRect) const
Copies this vector field into the one received as parameter using the specified copy rectangle.
virtual const void * getRasterX (void) const =0
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
virtual void * getRasterX (ReadWriteStatus rw)=0
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
virtual const void * getRasterY (void) const =0
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
virtual void * getRasterY (ReadWriteStatus rw)=0
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
virtual const void * getRasterX2D (void) const =0
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
virtual void * getRasterX2D (ReadWriteStatus rw)=0
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
virtual const void * getRasterY2D (void) const =0
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
virtual void * getRasterY2D (ReadWriteStatus rw)=0
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
virtual const void * getShiftedRasterX2D (void) const =0
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
virtual void * getShiftedRasterX2D (ReadWriteStatus rw)=0
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
virtual const void * getShiftedRasterY2D (void) const =0
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
virtual void * getShiftedRasterY2D (ReadWriteStatus rw)=0
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
virtual const RasterImage_gray_F * getNormAsRasterImage (void) const
Returns the vector field's norm as gray-level raster image.
virtual RasterImage_gray_F * getNormAsRasterImage (ReadWriteStatus rw)
Returns the vector field's norm as gray-level raster image.
virtual const RasterImage_gray_F * getNormSquaredAsRasterImage (void) const
Returns the vector field's norm squared as gray-level raster image.
virtual RasterImage_gray_F * getNormSquaredAsRasterImage (ReadWriteStatus rw)
Returns the vector field's norm squared as gray-level raster image.
virtual const RasterImage_gray_F * getPhaseAsRasterImage (void) const
Returns the vector field's phase as gray-level raster image.
virtual RasterImage_gray_F * getPhaseAsRasterImage (ReadWriteStatus rw)
Returns the vector field's phase as gray-level raster image.
virtual void getNormAsRasterImage (RasterImage_gray *normOut)
Returns the vector field's norm as gray-level raster image.
virtual void getNormSquaredAsRasterImage (RasterImage_gray *norm2Out)
Returns the vector field's norm squared as gray-level raster image.
virtual void getPhaseAsRasterImage (RasterImage_gray *phaseOut)
Returns the vector field's phase as gray-level raster image.
virtual void getNormAndPhaseAsRasterImages (RasterImage_gray *normOut, RasterImage_gray *phaseOut)
Returns the vector field's norm and phase as gray-level raster images.
virtual void getNormSquaredAndPhaseAsRasterImages (RasterImage_gray *norm2Out, RasterImage_gray *phaseOut)
Returns the vector field's squared norm and phase as gray-level raster images.
void computeNorm (void) const
Computes vector field's norm as a gray-level raster image and stores it as an instance variable.
void computeNormSquared (void) const
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
void computePhase (void) const
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
void computeNormAndPhase (void) const
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
void computeNormSquaredAndPhase (void)
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
void setVectResolution (int nPts)
Sets the resolution of the vector field's rendering (distance between needles in pixel)
bool hasFloatRaster (void) const
true if the vector field has a float raster
void forceRasterUpdate (void)
Forces an update of the raster (for rendering)
void setRasterAsReference (void)
Sets this vector field's base raster as the reference.
void setNormAndPhaseAsReference (void)
Sets this vector field's norm and phase as the reference (fails either one was NULL)
void setNormSquaredAndPhaseAsReference (void)
Sets this vector field's norm squared and phase as the reference (fails either one was NULL)
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this vector field has been modified.
void setReferenceHasChanged (void) const
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void applyTransformation (const Transformation2D *theTransf)=0
Applies a Transformation2D to this object.
virtual void rotate (float angle, const ImagePoint *rotCenter=NULL)=0
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Protected Member Functions
VectorField (int theNbRows, int theNbCols, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions and values.
VectorField (const ImageRect *theRect, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions.
VectorField (const ImageRect &theRect, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Initializes a vector field at the specified dimensions.
VectorField (const VectorField *theField, bool hasFloatRast, DrawableInformationType drawableInfoType=kDense)
Copy Constructor.
VectorField (const VectorField &theField)
Copy Constructor.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Static Protected Attributes
static float NEEDLE_DOT_RADIUS = 2.f
Radius of the circular dot used to render a vertex.
Private Member Functions
const VectorField & operator= (const VectorField &theField)
Copy operator.
virtual void computeNorm_ (RasterImage_gray_F *norm) const =0
Computes vector field's norm as a gray-level raster image.
virtual void computeNormSquared_ (RasterImage_gray_F *normSq) const =0
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
virtual void computePhase_ (RasterImage_gray_F *phase) const =0
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
virtual void computeNormAndPhase_ (RasterImage_gray_F *norm, RasterImage_gray_F *phase) const =0
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
virtual void computeNormSquaredAndPhase_ (RasterImage_gray_F *normSq, RasterImage_gray_F *phase) const =0
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the vector field.
virtual void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the vector field.
virtual void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Render the vector field as a subsampled array of arrows at the depth and location specified.
virtual void renderNeedles_ (int nVectRes, float scaleVect) const =0
Render the vector field as a regularly sampled array of needles.
virtual void prepareVectFieldForRendering_ (int nVectRes, float &scaleVect, float &normMax) const =0
Computes the shifting and scaling factors to properly render the vectors as needles the next time render_ is called.
virtual void allocateRaster2D_ (int nbRows, int nbCols)=0
Allocates the 2D base rasters.
virtual void deleteRaster2D_ (void)=0
Deletes the 0-based 2D base rasters.
virtual void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)=0
Allocates the 2D shifted rasters.
virtual void translateShiftedRaster2D_ (int rowShoft, int colShift)=0
Translates the 2D shifted base rasters by the specified amount.
virtual void deleteShiftedRaster2D_ (void)=0
Deletes the 2D shifted base raster.
void computeBoundingRect_ (ImageRect &rect) const
Calculates the object's bounding rect.
void computeValidRect_ (ImageRect &rect) const
Calculates the object's valid box.
void computeCentroid_ (ImagePoint_F &cent) const
Computes the contour's centroid.
void computeCenterOfMass_ (ImagePoint_F &cent) const
Computes the object's center of mass by calculating the average point.
Private Attributes
int nVectRes_
resolution of vector field's rendering
float scaleVect_
Scale factor for vectors' needles.
float normMax_
Stores the maximum value of the norm over the entire valid portion of the vector field.
bool referenceHasChanged_
True if the reference raster has been modified since the last rendering.
bool normNeedsUpdate_
True if the vector field has been modified since the last time the norm was calculated.
bool normSquaredNeedsUpdate_
True if the vector field has been modified since the last time the norm squared was calculated.
bool phaseNeedsUpdate_
True if the vector field has been modified since the last time the phase was calculated.
bool hasFloatRaster_
True if the VectorField is of a "float" subclass.
bool baseRasterIsReference_
True if the VectorField's base raster is the reference.
bool normAndPhaseIsReference_
True if the VectorField's norm and phase rasters are the reference.
bool normSquaredAndPhaseIsReference_
True if the VectorField's norm squared and phase rasters are the reference.
RasterImage_gray_F * norm_
Stores a local copy of the vector field's norm.
RasterImage_gray_F * normSquared_
Stores a local copy of the vector field's norm squared.
RasterImage_gray_F * phase_
Stores a local copy of the vector field's phase.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Detailed Description
VectorField class.
A VectorField object stores a vector field defined over a 2d array. I haven't quite made up my mind on the opacity of this class. For the moment, the getRaster method returns the data's master pointer. In the future I may decide to clone the data and return the clone's master pointer. In any case, this would not change the class's API.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 49 of file VectorField.h.
Constructor & Destructor Documentation
VectorField::~VectorField (void) virtual
Destructor.
Definition at line 229 of file VectorField.cpp.
References norm_, normSquared_, and phase_.
 {
         if (norm_ != NULL)
                 delete norm_;
         if (normSquared_ != NULL)
                 delete normSquared_;
         if (phase_ != NULL)
                 delete phase_;
 }
VectorField::VectorField (int theNbRows, int theNbCols, bool hasFloatRast, DrawableInformationType drawableInfoType = kDense) protected
Initializes a vector field at the specified dimensions and values.
Parameters
nbRows number of rows of the vector field
nbCols number of columns of vector field
hasFloatRast true if this object has a float raster
drawableInfoType by default we assume that we have a dense vector field
Definition at line 40 of file VectorField.cpp.
                 :   DrawableObject2D(theNbRows, theNbCols, drawableInfoType),
                         //
                         //by default, I set the vectorial rendering resolution to 1 every 30 pixels
                         //      and the color to red
                         nVectRes_(30),
                         scaleVect_(1.f),
                         normMax_(0.f),
                         //
                         referenceHasChanged_(true),
                         normNeedsUpdate_(false),
                         normSquaredNeedsUpdate_(false),
                         phaseNeedsUpdate_(false),
                         hasFloatRaster_(hasFloatRast),
                         baseRasterIsReference_(true),
                         normAndPhaseIsReference_(false),
                         normSquaredAndPhaseIsReference_(false),
                         norm_(NULL),
                         normSquared_(NULL),
                         phase_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid dimension parameter error in VectorField constructor");
 }
VectorField::VectorField (const ImageRect * theRect, bool hasFloatRast, DrawableInformationType drawableInfoType = kDense) protected
Initializes a vector field at the specified dimensions.
Parameters
theRect rectangle at which to allocate the vector field
drawableInfoType by default we assume that we have a dense vector field
Definition at line 78 of file VectorField.cpp.
                 :       DrawableObject2D(theRect, drawableInfoType),
                         //
                         //by default, I set the vectorial rendering resolution to 1 every 30 pixels
                         //      and the color to red
                         nVectRes_(30),
                         scaleVect_(1.f),
                         normMax_(0.f),
                         //
                         referenceHasChanged_(true),
                         normNeedsUpdate_(false),
                         normSquaredNeedsUpdate_(false),
                         phaseNeedsUpdate_(false),
                         hasFloatRaster_(hasFloatRast),
                         baseRasterIsReference_(true),
                         normAndPhaseIsReference_(false),
                         normSquaredAndPhaseIsReference_(false),
                         norm_(NULL),
                         normSquared_(NULL),
                         phase_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ImageRect parameter error in VectorField constructor");
 }
VectorField::VectorField (const ImageRect & theRect, bool hasFloatRast, DrawableInformationType drawableInfoType = kDense) protected
Initializes a vector field at the specified dimensions.
Parameters
theRect rectangle at which to allocate the vector field
hasFloatRast true if this object has a float raster
drawableInfoType by default we assume that we have a dense vector field
Definition at line 115 of file VectorField.cpp.
                 :       DrawableObject2D(theRect, drawableInfoType),
                         //
                         //by default, I set the vectorial rendering resolution to 1 every 30 pixels
                         //      and the color to red
                         nVectRes_(30),
                         scaleVect_(1.f),
                         normMax_(0.f),
                         //
                         referenceHasChanged_(true),
                         normNeedsUpdate_(false),
                         normSquaredNeedsUpdate_(false),
                         phaseNeedsUpdate_(false),
                         hasFloatRaster_(hasFloatRast),
                         baseRasterIsReference_(true),
                         normAndPhaseIsReference_(false),
                         normSquaredAndPhaseIsReference_(false),
                         norm_(NULL),
                         normSquared_(NULL),
                         phase_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ImageRect parameter error in VectorField constructor");
 }
VectorField::VectorField (const VectorField * theField, bool hasFloatRast, DrawableInformationType drawableInfoType = kDense) protected
Copy Constructor.
Initializes a vector field at the dimensions and values of the VectorField received as parameter.
Parameters
theField pointer to the VectorField object to copy
hasFloatRast true if this object has a float raster
drawableInfoType by default we assume that we have a dense vector field
Definition at line 153 of file VectorField.cpp.
                 :   DrawableObject2D(*theField),
                         //
                         //by default, I set the vectorial rendering resolution to 1 every 30 pixels
                         //      and the color to red
                         nVectRes_(30),
                         scaleVect_(1.f),
                         normMax_(0.f),
                         //
                         referenceHasChanged_(true),
                         normNeedsUpdate_(false),
                         normSquaredNeedsUpdate_(false),
                         phaseNeedsUpdate_(false),
                         hasFloatRaster_(hasFloatRast),
                         baseRasterIsReference_(true),
                         normAndPhaseIsReference_(false),
                         normSquaredAndPhaseIsReference_(false),
                         norm_(NULL),
                         normSquared_(NULL),
                         phase_(NULL)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( theField == NULL,
                                         kInvalidParameterError,
                                         "null pointer error in VectorField copy constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField copy constructor");
 }
VectorField::VectorField (const VectorField & theField) protected
Copy Constructor.
Disabled
Parameters
theField reference to the VectorField object to copy
Definition at line 191 of file VectorField.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :   DrawableObject2D(theField),
                         //
                         //by default, I set the vectorial rendering resolution to 1 every 30 pixels
                         //      and the color to red
                         nVectRes_(30),
                         scaleVect_(1.f),
                         normMax_(0.f),
                         //
                         referenceHasChanged_(true),
                         normNeedsUpdate_(false),
                         normSquaredNeedsUpdate_(false),
                         phaseNeedsUpdate_(false),
                         hasFloatRaster_(false),
                         baseRasterIsReference_(true),
                         normAndPhaseIsReference_(false),
                         normSquaredAndPhaseIsReference_(false),
                         norm_(NULL),
                         normSquared_(NULL),
                         phase_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "VectorField copy constructor not implemented");
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by VectorField constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter error in VectorField copy constructor");
 }
Member Function Documentation
virtual void uriVL::VectorField::allocateRaster2D_ (int nbRows, int nbCols) private pure virtual
Allocates the 2D base rasters.
Parameters
nbRows number of rows of the field
nbCols number of columns of the field
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by copyInto(), and setBoundRect_().
virtual void uriVL::VectorField::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private pure virtual
Allocates the 2D shifted rasters.
Parameters
jLow X coordinate of the image's origin
iLow Y coordinate of the image's origin
nbRows number of rows of the field
nbCols number of columns of the field
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by copyInto(), and setBoundRect_().
void VectorField::computeBoundingRect_ (ImageRect & rect) const private virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 750 of file VectorField.cpp.
 {
         //      nothing to do
 }
void VectorField::computeCenterOfMass_ (ImagePoint_F & cent) const private virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implements uriVL::DrawableObject2D.
Definition at line 765 of file VectorField.cpp.
 {
         //      nothing to do
 }
void VectorField::computeCentroid_ (ImagePoint_F & cent) const private virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implements uriVL::DrawableObject2D.
Definition at line 760 of file VectorField.cpp.
 {
         //      nothing to do
 }
void VectorField::computeNorm (void) const
Computes vector field's norm as a gray-level raster image and stores it as an instance variable.
Definition at line 381 of file VectorField.cpp.
References computeNorm_(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), uriVL::kPositiveFloat, norm_, normNeedsUpdate_, uriVL::RasterImage::requestRasterUpdate(), uriVL::RasterImage_gray_F::setFloatConversionMode(), and uriVL::DrawableObject2D::setValidRect().
Referenced by getNormAsRasterImage().
 {
     bool mustComputeNorm = false;
     //  If the norm has never been allocated do so now
     if (norm_ == NULL)
     {
         norm_ = new RasterImage_gray_F(getBoundRect());
         mustComputeNorm = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputeNorm = normNeedsUpdate_;
     //  update the rasters that need it
     if (mustComputeNorm)
     {
         computeNorm_(norm_);
         norm_->requestRasterUpdate();
     }
     normNeedsUpdate_ = false;
     norm_->setValidRect(this->getValidRect());
     norm_->setFloatConversionMode(kPositiveFloat);
 }
virtual void uriVL::VectorField::computeNorm_ (RasterImage_gray_F * norm) const private pure virtual
Computes vector field's norm as a gray-level raster image.
Parameters
norm pointer to the vector field's private norm variable
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by computeNorm(), and computeNormAndPhase().
void VectorField::computeNormAndPhase (void) const
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
Definition at line 459 of file VectorField.cpp.
References computeNorm_(), computeNormAndPhase_(), computePhase_(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), norm_, normNeedsUpdate_, phase_, phaseNeedsUpdate_, uriVL::RasterImage::referenceHasChanged(), and uriVL::DrawableObject2D::setValidRect().
Referenced by uriVL::NonMaximumSuppressor::applyInto_vectF_(), and getNormAndPhaseAsRasterImages().
 {
     bool    mustComputePhase = false,
                                mustComputeNorm = false;
     //  If the norm has never been allocated do so now
     if (norm_ == NULL)
     {
         norm_ = new RasterImage_gray_F(getBoundRect());
         mustComputeNorm = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputeNorm = normNeedsUpdate_;
     //  If the phase has never been allocated do so now
     if (phase_ == NULL)
     {
         phase_ = new RasterImage_gray_F(getBoundRect());
         mustComputePhase = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputePhase = phaseNeedsUpdate_;
     //  update the rasters that need it
     if (mustComputeNorm)
         if (mustComputePhase)
         {
             computeNormAndPhase_(norm_, phase_);
             norm_->referenceHasChanged();
             phase_->referenceHasChanged();
         }
         else
         {
             computeNorm_(norm_);
             norm_->referenceHasChanged();
         }
     else if (mustComputePhase)
     {
         computePhase_(phase_);
         phase_->referenceHasChanged();
     }
     normNeedsUpdate_ = false;
     phaseNeedsUpdate_ = false;
     norm_->setValidRect(getValidRect());
     phase_->setValidRect(getValidRect());
 }
virtual void uriVL::VectorField::computeNormAndPhase_ (RasterImage_gray_F * norm, RasterImage_gray_F * phase) const private pure virtual
Computes vector field's norm and phase as gray-level raster images and stores them as instance variables.
Parameters
norm pointer to the vector field's private norm variable
phase pointer to the vector field's private phase variable
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by computeNormAndPhase().
void VectorField::computeNormSquared (void) const
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
Definition at line 407 of file VectorField.cpp.
References computeNormSquared_(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), uriVL::kPositiveFloat, normSquared_, normSquaredNeedsUpdate_, uriVL::RasterImage::referenceHasChanged(), uriVL::RasterImage_gray_F::setFloatConversionMode(), and uriVL::DrawableObject2D::setValidRect().
Referenced by getNormSquaredAsRasterImage().
 {
     bool    mustComputeNorm2 = false;
     //  If the norm has never been allocated do so now
     if (normSquared_ == NULL)
     {
         normSquared_ = new RasterImage_gray_F(getBoundRect());
         mustComputeNorm2 = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputeNorm2 = normSquaredNeedsUpdate_;
     //  update the rasters that need it
     if (mustComputeNorm2)
     {
         computeNormSquared_(normSquared_);
         normSquared_->referenceHasChanged();
     }
     normSquaredNeedsUpdate_ = false;
     normSquared_->setValidRect(this->getValidRect());
     normSquared_->setFloatConversionMode(kPositiveFloat);
 }
virtual void uriVL::VectorField::computeNormSquared_ (RasterImage_gray_F * normSq) const private pure virtual
Returns the vector field's squared norm as a gray-level raster image and stores it as an instance variable.
Parameters
normSq pointer to the vector field's private norm squared variable
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by computeNormSquared(), and computeNormSquaredAndPhase().
void VectorField::computeNormSquaredAndPhase (void)
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
Definition at line 509 of file VectorField.cpp.
References computeNormSquared_(), computeNormSquaredAndPhase_(), computePhase_(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), normSquared_, normSquaredNeedsUpdate_, phase_, phaseNeedsUpdate_, uriVL::RasterImage::referenceHasChanged(), and uriVL::DrawableObject2D::setValidRect().
Referenced by getNormSquaredAndPhaseAsRasterImages().
 {
     bool    mustComputePhase = false,
                                mustComputeNorm2 = false;
     //  If the norm has never been allocated do so now
     if (normSquared_ == NULL)
     {
         normSquared_ = new RasterImage_gray_F(getBoundRect());
         mustComputeNorm2 = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputeNorm2 = normSquaredNeedsUpdate_;
     //  If the phase has never been allocated do so now
     if (phase_ == NULL)
     {
         phase_ = new RasterImage_gray_F(getBoundRect());
         mustComputePhase = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputePhase = phaseNeedsUpdate_;
     //  update the rasters that need it
     if (mustComputeNorm2)
         if (mustComputePhase)
         {
             computeNormSquaredAndPhase_(normSquared_, phase_);
             normSquared_->referenceHasChanged();
             phase_->referenceHasChanged();
         }
         else
         {
             computeNormSquared_(normSquared_);
             normSquared_->referenceHasChanged();
         }
     else if (mustComputePhase)
     {
         computePhase_(phase_);
         phase_->referenceHasChanged();
     }
     normSquaredNeedsUpdate_ = false;
     phaseNeedsUpdate_ = false;
     normSquared_->setValidRect(this->getValidRect());
     phase_->setValidRect(this->getValidRect());
 }
virtual void uriVL::VectorField::computeNormSquaredAndPhase_ (RasterImage_gray_F * normSq, RasterImage_gray_F * phase) const private pure virtual
Computes vector field's norm squared and phase as gray-level raster images and stores them as instance variables.
Parameters
normSq pointer to the vector field's private norm squared variable
phase pointer to the vector field's private phase variable
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by computeNormSquaredAndPhase().
void VectorField::computePhase (void) const
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
Definition at line 434 of file VectorField.cpp.
References computePhase_(), uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getValidRect(), phase_, phaseNeedsUpdate_, uriVL::RasterImage::referenceHasChanged(), and uriVL::DrawableObject2D::setValidRect().
Referenced by getPhaseAsRasterImage().
 {
     bool    mustComputePhase = false;
     //  If the phase has never been allocated do so now
     if (phase_ == NULL)
     {
         phase_ = new RasterImage_gray_F(getBoundRect());
         mustComputePhase = true;
     }
     //  otherwise check if the vector field has changed since last use
     else
         mustComputePhase = phaseNeedsUpdate_;
     //  update the rasters that need it
     if (mustComputePhase)
     {
         computePhase_(phase_);
         phase_->referenceHasChanged();
     }
     phaseNeedsUpdate_ = false;
     phase_->setValidRect(getValidRect());
 }
virtual void uriVL::VectorField::computePhase_ (RasterImage_gray_F * phase) const private pure virtual
Computes vector field's phase as gray-level raster image and stores it as an instance variable.
Parameters
phase pointer to the vector field's private phase variable
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by computeNormAndPhase(), computeNormSquaredAndPhase(), and computePhase().
void VectorField::computeValidRect_ (ImageRect & rect) const private virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 755 of file VectorField.cpp.
 {
         //      nothing to do
 }
void VectorField::copyInto (VectorField * out) const
Copies this vector field into the one received as parameter.
If the destination vector field does not have the same dimensions as this vector field (source), its rasters are reallocated. Only the data within the validRect_ rectangle need to be be copied. The bounding rectangle and valid data rectangle of the destination are equal to that of the source.
Parameters
vectOut destination vector field
Definition at line 601 of file VectorField.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), uriVL::VectorField_F::VectorField_F(), and uriVL::VectorField_I::VectorField_I().
 {
     copyInto(vectOut, getValidRect());
 }
void VectorField::copyInto (VectorField * vectOut, const ImageRect * theRect) const virtual
Copies this vector field into the one received as parameter using the specified copy rectangle.
The call fails if the rectangle specified is not contained within the source. This function must be overridden (and called by the overriding function) by subclasses of VectorField.
Parameters
vectOut destination vector field
theRect region of the vector field to copy
Reimplemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Definition at line 607 of file VectorField.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ImageRect::coincidesWith(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::DrawableObject2D::getWidth(), uriVL::ImageRect::intersection(), uriVL::kNullRectangleError, uriVL::kNullVectorFieldError, uriVL::kUriBaseError, uriVL::DrawableObject2D::setBoundRect(), and uriVL::DrawableObject2D::setValidRect().
 {
     FAIL_CONDITION(     vectOut == NULL,
                     kNullVectorFieldError,
                     "null vector field passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     //  We only copy from the validRect_, so we need to calculate its intersection
     //  with theRect.
     ImageRect   *copyRect = ImageRect::intersection(getValidRect(), theRect);
     FAIL_CONDITION( copyRect == NULL,
                     kUriBaseError,
                     "the copy rectangle specified is not within valid data");
     //  if theRect was not already the bounding rectangle of the destination field,
     //  we make it so.
     if (!theRect->coincidesWith(vectOut->getBoundRect()))
     {
         vectOut->deleteShiftedRaster2D_();
         vectOut->deleteRaster2D_( );
         vectOut->setValidRect(getBoundRect());
         vectOut->setBoundRect(getBoundRect());
         vectOut->allocateRaster2D_(getHeight(), getWidth());
         vectOut->allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     }
     //  set the destination field's new valid data rect.
     vectOut->setValidRect(copyRect);
         delete copyRect;
 }
virtual void uriVL::VectorField::deleteRaster2D_ (void) private pure virtual
Deletes the 0-based 2D base rasters.
This virtual function must be implemented by child classes.
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by copyInto(), and setBoundRect_().
virtual void uriVL::VectorField::deleteShiftedRaster2D_ (void) private pure virtual
Deletes the 2D shifted base raster.
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by copyInto(), and setBoundRect_().
void VectorField::forceRasterUpdate (void)
Forces an update of the raster (for rendering)
Should be called by users of the class who modify directly the raster (by accessing it through calls to getRaster or getShiftedRaster functions)
Definition at line 256 of file VectorField.cpp.
References baseRasterIsReference_, normNeedsUpdate_, normSquaredNeedsUpdate_, phaseNeedsUpdate_, and referenceHasChanged_.
Referenced by uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ColorImageGradient_Gaussian_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NonMaximumSuppressor::applyInto_st(), CreateImageAndField(), myMenu2(), and myMenu3().
 {
     referenceHasChanged_ = true;
     if (baseRasterIsReference_)
     {
         normNeedsUpdate_ = normSquaredNeedsUpdate_ = phaseNeedsUpdate_ = true;
     }
 }
void VectorField::getNormAndPhaseAsRasterImages (RasterImage_gray * normOut, RasterImage_gray * phaseOut) virtual
Returns the vector field's norm and phase as gray-level raster images.
Parameters
normOut destination raster image for the norm of this vector field
phaseOut destination raster image for the phase of this vector field
Definition at line 339 of file VectorField.cpp.
References computeNormAndPhase(), uriVL::RasterImage_gray_F::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, norm_, and phase_.
 {
     FAIL_CONDITION( normOut == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getNormAsRasterImage");
     FAIL_CONDITION( phaseOut == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getPhaseAsRasterImage");
     computeNormAndPhase();
     //  copy the local rasters into the destination images provided
     norm_->copyInto(normOut);
     phase_->copyInto(phaseOut);
 }
const RasterImage_gray_F * VectorField::getNormAsRasterImage (void) const virtual
Returns the vector field's norm as gray-level raster image.
Important: What is returned here is a a pointer to the vector field's private data. Do not delete it. If you plan to modify this data, you are better off passing a RasterImage_gray_F to getNormAsRasterImage to fill in.
Returns
vector field's norm as a gray-level raster image
See also
computeNormAndPhase
Definition at line 273 of file VectorField.cpp.
References computeNorm(), and norm_.
Referenced by uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), myIdle(), myMenu2(), and myMenu3().
 {
     computeNorm();
     return norm_;
 }
RasterImage_gray_F * VectorField::getNormAsRasterImage (ReadWriteStatus rw) virtual
Returns the vector field's norm as gray-level raster image.
Important: What is returned here is a a pointer to the vector field's private data. Do not delete it. If you plan to modify this data, you are better off passing a RasterImage_gray_F to getNormAsRasterImage to fill in.
Returns
vector field's norm as a gray-level raster image
See also
computeNormAndPhase
Definition at line 279 of file VectorField.cpp.
References computeNorm(), and norm_.
 {
     computeNorm();
     return norm_;
 }
void VectorField::getNormAsRasterImage (RasterImage_gray * normOut) virtual
Returns the vector field's norm as gray-level raster image.
Parameters
normOut destination raster image for the norm of this vector field
See also
getNormAndPhaseAsRasterImages
Definition at line 285 of file VectorField.cpp.
References computeNorm(), uriVL::RasterImage_gray_F::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, and norm_.
 {
     FAIL_CONDITION( normOut == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getNormAsRasterImage");
     computeNorm();
     norm_->copyInto(normOut);
 }
void VectorField::getNormSquaredAndPhaseAsRasterImages (RasterImage_gray * norm2Out, RasterImage_gray * phaseOut) virtual
Returns the vector field's squared norm and phase as gray-level raster images.
Parameters
norm2Out destination raster image for the squared norm of this vector field
phaseOut destination raster image for the phase of this vector field
Definition at line 356 of file VectorField.cpp.
References computeNormSquaredAndPhase(), uriVL::RasterImage_gray_F::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, normSquared_, and phase_.
 {
     FAIL_CONDITION( norm2Out == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getNormAsRasterImage");
     FAIL_CONDITION( phaseOut == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getPhaseAsRasterImage");
     computeNormSquaredAndPhase();
     //  copy the local rasters into the destination images provided
     normSquared_->copyInto(norm2Out);
     phase_->copyInto(phaseOut);
 }
const RasterImage_gray_F * VectorField::getNormSquaredAsRasterImage (void) const virtual
Returns the vector field's norm squared as gray-level raster image.
Important: What is returned here is a a pointer to the vector field's private data. Do not delete it. If you plan to modify this data, you are better off passing a RasterImage_gray_F to getNormSquaredAsRasterImage to fill in.
Returns
vector field's norm squared as a gray-level raster image
See also
computeNormSquaredAndPhase
Definition at line 295 of file VectorField.cpp.
References computeNormSquared(), and normSquared_.
Referenced by uriVL::HysteresisLabeler::applyInto(), uriVL::HysteresisLabeler::applyTo(), and uriVL::ActiveContourDetector_balloon::findContour().
 {
     computeNormSquared();
     return normSquared_;
 }
RasterImage_gray_F * VectorField::getNormSquaredAsRasterImage (ReadWriteStatus rw) virtual
Returns the vector field's norm squared as gray-level raster image.
Important: What is returned here is a a pointer to the vector field's private data. Do not delete it. If you plan to modify this data, you are better off passing a RasterImage_gray_F to getNormSquaredAsRasterImage to fill in.
Returns
vector field's norm squared as a gray-level raster image
See also
computeNormSquaredAndPhase
Definition at line 301 of file VectorField.cpp.
References computeNormSquared(), and normSquared_.
 {
     computeNormSquared();
     return normSquared_;
 }
void VectorField::getNormSquaredAsRasterImage (RasterImage_gray * norm2Out) virtual
Returns the vector field's norm squared as gray-level raster image.
Parameters
norm2Out destination raster image for the square of the norm of this vector field
See also
getNormSquaredAndPhaseAsRasterImages
Definition at line 307 of file VectorField.cpp.
References computeNormSquared(), uriVL::RasterImage_gray_F::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, and normSquared_.
 {
     FAIL_CONDITION( norm2Out == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::computeNormSquaredAsRasterImage");
     computeNormSquared();
     normSquared_->copyInto(norm2Out);
 }
const RasterImage_gray_F * VectorField::getPhaseAsRasterImage (void) const virtual
Returns the vector field's phase as gray-level raster image.
Returns
vector field's norm as a gray-level raster image
If you plan to use this function in combination with getNormAsRasterImage (resp. getNormSquaredAsRasterImage) then you might get better performance by calling computeNormAndPhase (resp. computeNormSquaredAndPhase)first. That way, if the norm (resp. norm squared) and/or phase either have not been allocated or have not been updated, they will be both computed in one pass.
See also
computeNormAndPhase
computeNormSquaredAndPhase
Definition at line 317 of file VectorField.cpp.
References computePhase(), and phase_.
Referenced by uriVL::NonMaximumSuppressor::applyInto_vectF_().
 {
     computePhase();
     return phase_;
 }
RasterImage_gray_F * VectorField::getPhaseAsRasterImage (ReadWriteStatus rw) virtual
Returns the vector field's phase as gray-level raster image.
Returns
vector field's norm as a gray-level raster image
If you plan to use this function in combination with getNormAsRasterImage (resp. getNormSquaredAsRasterImage) then you might get better performance by calling computeNormAndPhase (resp. computeNormSquaredAndPhase)first. That way, if the norm (resp. norm squared) and/or phase either have not been allocated or have not been updated, they will be both computed in one pass.
See also
computeNormAndPhase
computeNormSquaredAndPhase
Definition at line 323 of file VectorField.cpp.
References computePhase(), and phase_.
 {
     computePhase();
     return phase_;
 }
void VectorField::getPhaseAsRasterImage (RasterImage_gray * phaseOut) virtual
Returns the vector field's phase as gray-level raster image.
If you plan to use this function in combination with getNormAsRasterImage (resp. getNormSquaredAsRasterImage) then you might get better performance by calling computeNormAndPhase (resp. computeNormSquaredAndPhase)first. That way, if the norm (resp. norm squared) and/or phase either have not been allocated or have not been updated, they will be both computed in one pass.
Parameters
phaseOut destination raster image for the phase of this vector field
Definition at line 329 of file VectorField.cpp.
References computePhase(), uriVL::RasterImage_gray_F::copyInto(), FAIL_CONDITION, uriVL::kNullRasterImageError, and phase_.
 {
     FAIL_CONDITION( phaseOut == NULL,
                     kNullRasterImageError,
                     "null raster image destination in VectorField::getPhaseAsRasterImage");
     computePhase();
     phase_->copyInto(phaseOut);
 }
virtual const void* uriVL::VectorField::getRasterX (void) const pure virtual
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
Returns
the vector field's X component's 1D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual void* uriVL::VectorField::getRasterX (ReadWriteStatus rw) pure virtual
Returns the vector field's X component's 1D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 1D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual const void* uriVL::VectorField::getRasterX2D (void) const pure virtual
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
Returns
the vector field's X component's 2D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual void* uriVL::VectorField::getRasterX2D (ReadWriteStatus rw) pure virtual
Returns the vector field's X component's 2D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 2D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual const void* uriVL::VectorField::getRasterY (void) const pure virtual
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
Returns
the vector field's Y component's 1D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual void* uriVL::VectorField::getRasterY (ReadWriteStatus rw) pure virtual
Returns the vector field's Y component's 1D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 1D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual const void* uriVL::VectorField::getRasterY2D (void) const pure virtual
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
Returns
the vector field's Y component's 2D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual void* uriVL::VectorField::getRasterY2D (ReadWriteStatus rw) pure virtual
Returns the vector field's Y component's 2D base raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 2D base raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual const void* uriVL::VectorField::getShiftedRasterX2D (void) const pure virtual
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
Returns
the vector field's X component's 2D "shifted" raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by uriVL::HysteresisLabeler::applyInto(), and uriVL::HysteresisLabeler::applyTo().
virtual void* uriVL::VectorField::getShiftedRasterX2D (ReadWriteStatus rw) pure virtual
Returns the vector field's X component's 2D "shifted" raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's X component's 2D "shifted" raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
virtual const void* uriVL::VectorField::getShiftedRasterY2D (void) const pure virtual
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
Returns
the vector field's Y component's 2D "shifted" raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by uriVL::HysteresisLabeler::applyInto(), and uriVL::HysteresisLabeler::applyTo().
virtual void* uriVL::VectorField::getShiftedRasterY2D (ReadWriteStatus rw) pure virtual
Returns the vector field's Y component's 2D "shifted" raster Must be overridden by child classes.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
the vector field's Y component's 2D "shifted" raster
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
bool VectorField::hasFloatRaster (void) const
true if the vector field has a float raster
Returns
true if the vector field has a float raster
Definition at line 251 of file VectorField.cpp.
References hasFloatRaster_.
Referenced by uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::NonMaximumSuppressor::applyTo_st(), uriVL::VectorField_I::copyInto(), and uriVL::VectorField_F::copyInto().
 {
     return hasFloatRaster_;
 }
const VectorField & VectorField::operator= (const VectorField & theField) private
Copy operator.
Disabled
Parameters
theField reference to the VectorField object to copy
Definition at line 239 of file VectorField.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "VectorField copy operator not implemented");
         return *this;
 }
virtual void uriVL::VectorField::prepareVectFieldForRendering_ (int nVectRes, float & scaleVect, float & normMax) const private pure virtual
Computes the shifting and scaling factors to properly render the vectors as needles the next time render_ is called.
Parameters
nVectRes resolution of vector field's rendering
scaleVect scale factor for vectors' needles (gets updated)
normMax max value of the vector field's norm (gets updated)
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by render_(), and setVectResolution().
bool VectorField::referenceHasChanged (void) const
Indicates whether or not the reference raster for this vector field has been modified.
When the reference raster is modified, other rasters stored by the vector field object my have to be modified.
Returns
true if the reference raster has changed.
See also
referenceHasChanged_
Definition at line 581 of file VectorField.cpp.
References referenceHasChanged_.
 {
     return referenceHasChanged_;
 }
void VectorField::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private virtual
Render the vector field as a subsampled array of arrows at the depth and location specified.
Parameters
scaledLeft x coordinate of the vector field's upper-left corner when rendered scaled
scaledTop y coordinate of the vector field's upper-left corner when rendered scaled
scaledRight x coordinate of the vector field's lower-right corner when rendered scaled
scaledBottom y coordinate of the vector field's lower-right corner when rendered scaled
theZ Depth at which this vector field is to be rendered.
shifted true if the vector field should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the vector field's upper-left corner in the rendering
Implements uriVL::DrawableObject2D.
Definition at line 706 of file VectorField.cpp.
References uriVL::DrawableObject2D::getColor(), uriVL::DrawableObject2D::getRenderingScaleX(), uriVL::DrawableObject2D::getRenderingScaleY(), normMax_, nVectRes_, prepareVectFieldForRendering_(), referenceHasChanged_, renderNeedles_(), and scaleVect_.
 {
     //--------------------------------------------------------------
     //  Part 1: make sure that what we draw is up to date
     //--------------------------------------------------------------
     if (referenceHasChanged_)
         {
         prepareVectFieldForRendering_(nVectRes_, scaleVect_, normMax_);
                 referenceHasChanged_ = false;
         }
     //--------------------------------------------------------------
     //  Part 2: render the vector field
     //--------------------------------------------------------------
     glLoadIdentity();
     glPushMatrix();
     glTranslatef(scaledLeft, scaledTop, theZ);
     glColor4fv(getColor());
     glScalef(getRenderingScaleX(), -getRenderingScaleY(), 1.f);
     //  now let the child class take over
     renderNeedles_(nVectRes_, scaleVect_);
     glPopMatrix();
 }
virtual void uriVL::VectorField::renderNeedles_ (int nVectRes, float scaleVect) const private pure virtual
Render the vector field as a regularly sampled array of needles.
Parameters
nVectRes resolution of vector field's rendering
scaleVect scale factor for vectors' needles
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by render_().
void VectorField::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new bounding rectangle for the vector field.
A vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. This operation may require a reallocation of the vector field.
If the norm, norm squared, or phase have been allocated then their valid data rect must be modified too.
Parameters
x X coordinate of the vector field's origin
y Y coordinate of the vector field's origin
theWidth desired width of the vector field
theHeight desired height of the vector field
Implements uriVL::DrawableObject2D.
Definition at line 645 of file VectorField.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), deleteShiftedRaster2D_(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), norm_, normSquared_, phase_, uriVL::DrawableObject2D::setBoundRect(), and translateShiftedRaster2D_().
 {
         //  The ImageRect member will be updated in DrawableObject2D::setBoundRect, so we only need
         //      to update the "shifted" array (no re-allocation needed)
     //  if width and height have not changed, then all we need to do is update the
     //  ImageRect member and translate the "shifted" array.
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             translateShiftedRaster2D_(y - getTop(), x - getLeft());
         }
     }
     //  if the dimensions of the rectangle are different, then we must delete
     //  and reallocate the 0-based and "shifted" 2D rasters.
     else
     {
         //      I am not sure if this is the right thing to do: should subclasses completely
         //      reimplement this or call this function if they have to override it?
         //      This is opting for the latter.
         deleteShiftedRaster2D_();
         deleteRaster2D_();
         allocateRaster2D_(theHeight, theWidth);
         allocateShiftedRaster2D_(theHeight, theWidth, y, x);
     }
     //  If the norm, norm squared, or phase have been allocated then their bounding
     //  data rect must be modified too.
     if (norm_ != NULL)
         norm_->setBoundRect(x, y, theWidth, theHeight);
     if (normSquared_ != NULL)
         normSquared_->setBoundRect(x, y, theWidth, theHeight);
     if (phase_ != NULL)
         phase_->setBoundRect(x, y, theWidth, theHeight);
 }
void VectorField::setNormAndPhaseAsReference (void)
Sets this vector field's norm and phase as the reference (fails either one was NULL)
Definition at line 569 of file VectorField.cpp.
References baseRasterIsReference_, normAndPhaseIsReference_, and normSquaredAndPhaseIsReference_.
 {
     normAndPhaseIsReference_ = true;
     baseRasterIsReference_ = normSquaredAndPhaseIsReference_ = false;
 }
void VectorField::setNormSquaredAndPhaseAsReference (void)
Sets this vector field's norm squared and phase as the reference (fails either one was NULL)
Definition at line 575 of file VectorField.cpp.
References baseRasterIsReference_, normAndPhaseIsReference_, and normSquaredAndPhaseIsReference_.
 {
     normSquaredAndPhaseIsReference_ = true;
     baseRasterIsReference_ = normAndPhaseIsReference_ = false;
 }
void VectorField::setRasterAsReference (void)
Sets this vector field's base raster as the reference.
Definition at line 563 of file VectorField.cpp.
References baseRasterIsReference_, normAndPhaseIsReference_, and normSquaredAndPhaseIsReference_.
Referenced by uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ColorImageGradient_Gaussian_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::VectorField_I::getRasterX(), uriVL::VectorField_F::getRasterX(), uriVL::VectorField_I::getRasterX2D(), uriVL::VectorField_F::getRasterX2D(), uriVL::VectorField_I::getRasterY(), uriVL::VectorField_F::getRasterY(), uriVL::VectorField_I::getRasterY2D(), uriVL::VectorField_F::getRasterY2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), and uriVL::VectorField_F::getShiftedRasterY2D().
 {
     baseRasterIsReference_ = true;
     normAndPhaseIsReference_ = normSquaredAndPhaseIsReference_ = false;
 }
void VectorField::setReferenceHasChanged (void) const
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Definition at line 591 of file VectorField.cpp.
References referenceHasChanged_.
Referenced by uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), uriVL::VectorField_I::getRasterX(), uriVL::VectorField_F::getRasterX(), uriVL::VectorField_I::getRasterX2D(), uriVL::VectorField_F::getRasterX2D(), uriVL::VectorField_I::getRasterY(), uriVL::VectorField_F::getRasterY(), uriVL::VectorField_I::getRasterY2D(), uriVL::VectorField_F::getRasterY2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), and uriVL::VectorField_F::getShiftedRasterY2D().
 {
     referenceHasChanged_ = true;
 }
void VectorField::setReferenceHasChanged_ (bool hasChanged) const protected
To be called by a child class that has modified the raster or one of the secondary rasters, or updated a secondary raster.
Parameters
hasChanged new value to assign to referenceHasChanged_
Definition at line 586 of file VectorField.cpp.
References referenceHasChanged_.
 {
     referenceHasChanged_ = hasChanged;
 }
void VectorField::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the vector field.
If the norm, norm squared, or phase have been allocated then their valid data rect must be modified too.
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Definition at line 684 of file VectorField.cpp.
References norm_, normSquared_, phase_, and uriVL::DrawableObject2D::setValidRect().
 {
     //  If the norm, norm squared, or phase have been allocated then their valid
     //  data rect must be modified too.
     if (norm_ != NULL)
         norm_->setValidRect(x, y, theWidth, theHeight);
     if (normSquared_ != NULL)
         normSquared_->setValidRect(x, y, theWidth, theHeight);
     if (phase_ != NULL)
         phase_->setValidRect(x, y, theWidth, theHeight);
 }
void VectorField::setVectResolution (int nPts)
Sets the resolution of the vector field's rendering (distance between needles in pixel)
Definition at line 734 of file VectorField.cpp.
References normMax_, nVectRes_, prepareVectFieldForRendering_(), and scaleVect_.
Referenced by glSetupAndRun(), loadImage(), myMenu2(), myMenu3(), and myVectFieldSubmenu().
 {
     nVectRes_ = nPts;
     prepareVectFieldForRendering_(nVectRes_, scaleVect_, normMax_);
 }
virtual void uriVL::VectorField::translateShiftedRaster2D_ (int rowShoft, int colShift) private pure virtual
Translates the 2D shifted base rasters by the specified amount.
This virtual function must be implemented by child classes.
Parameters
rowShift displacement of the row index
colShift displacement of the column index
Implemented in uriVL::VectorField_F, and uriVL::VectorField_I.
Referenced by setBoundRect_().
Member Data Documentation
bool uriVL::VectorField::baseRasterIsReference_ private
True if the VectorField's base raster is the reference.
Definition at line 452 of file VectorField.h.
Referenced by forceRasterUpdate(), setNormAndPhaseAsReference(), setNormSquaredAndPhaseAsReference(), and setRasterAsReference().
bool uriVL::VectorField::hasFloatRaster_ private
True if the VectorField is of a "float" subclass.
Definition at line 448 of file VectorField.h.
Referenced by hasFloatRaster().
float VectorField::NEEDLE_DOT_RADIUS = 2.f static protected
Radius of the circular dot used to render a vertex.
Definition at line 351 of file VectorField.h.
Referenced by uriVL::VectorField_I::renderNeedles_(), and uriVL::VectorField_F::renderNeedles_().
RasterImage_gray_F* uriVL::VectorField::norm_ mutable private
Stores a local copy of the vector field's norm.
This object is allocated and initialized by a call to computeNormAsRasterImage
See also
computeNormAsRasterImage
Definition at line 467 of file VectorField.h.
Referenced by computeNorm(), computeNormAndPhase(), getNormAndPhaseAsRasterImages(), getNormAsRasterImage(), setBoundRect_(), setValidRect_(), and ~VectorField().
bool uriVL::VectorField::normAndPhaseIsReference_ private
True if the VectorField's norm and phase rasters are the reference.
Definition at line 456 of file VectorField.h.
Referenced by setNormAndPhaseAsReference(), setNormSquaredAndPhaseAsReference(), and setRasterAsReference().
float uriVL::VectorField::normMax_ mutable private
Stores the maximum value of the norm over the entire valid portion of the vector field.
Definition at line 424 of file VectorField.h.
Referenced by render_(), and setVectResolution().
bool uriVL::VectorField::normNeedsUpdate_ mutable private
True if the vector field has been modified since the last time the norm was calculated.
Definition at line 434 of file VectorField.h.
Referenced by computeNorm(), computeNormAndPhase(), and forceRasterUpdate().
RasterImage_gray_F* uriVL::VectorField::normSquared_ mutable private
Stores a local copy of the vector field's norm squared.
This object is allocated and initialized by a call to computeNormSquaredAsRasterImage
See also
computeNormSquaredAsRasterImage
Definition at line 473 of file VectorField.h.
Referenced by computeNormSquared(), computeNormSquaredAndPhase(), getNormSquaredAndPhaseAsRasterImages(), getNormSquaredAsRasterImage(), setBoundRect_(), setValidRect_(), and ~VectorField().
bool uriVL::VectorField::normSquaredAndPhaseIsReference_ private
True if the VectorField's norm squared and phase rasters are the reference.
Definition at line 460 of file VectorField.h.
Referenced by setNormAndPhaseAsReference(), setNormSquaredAndPhaseAsReference(), and setRasterAsReference().
bool uriVL::VectorField::normSquaredNeedsUpdate_ mutable private
True if the vector field has been modified since the last time the norm squared was calculated.
Definition at line 439 of file VectorField.h.
Referenced by computeNormSquared(), computeNormSquaredAndPhase(), and forceRasterUpdate().
int uriVL::VectorField::nVectRes_ mutable private
resolution of vector field's rendering
Definition at line 415 of file VectorField.h.
Referenced by render_(), and setVectResolution().
RasterImage_gray_F* uriVL::VectorField::phase_ mutable private
Stores a local copy of the vector field's phase.
This object is allocated and initialized by a call to computePhaseAsRasterImage
See also
computePhaseAsRasterImage
Definition at line 479 of file VectorField.h.
Referenced by computeNormAndPhase(), computeNormSquaredAndPhase(), computePhase(), getNormAndPhaseAsRasterImages(), getNormSquaredAndPhaseAsRasterImages(), getPhaseAsRasterImage(), setBoundRect_(), setValidRect_(), and ~VectorField().
bool uriVL::VectorField::phaseNeedsUpdate_ mutable private
True if the vector field has been modified since the last time the phase was calculated.
Definition at line 444 of file VectorField.h.
Referenced by computeNormAndPhase(), computeNormSquaredAndPhase(), computePhase(), and forceRasterUpdate().
bool uriVL::VectorField::referenceHasChanged_ mutable private
True if the reference raster has been modified since the last rendering.
Definition at line 429 of file VectorField.h.
Referenced by forceRasterUpdate(), referenceHasChanged(), render_(), setReferenceHasChanged(), and setReferenceHasChanged_().
float uriVL::VectorField::scaleVect_ mutable private
Scale factor for vectors' needles.
Definition at line 419 of file VectorField.h.
Referenced by render_(), and setVectResolution().
The documentation for this class was generated from the following files:
VectorField.h
VectorField.cpp