URIVisionLibrary: uriVL::ImageGradient Class Reference
uriVL::ImageGradient Class Reference abstract
Pure virtual parent class for an operator that computes the gradient of a raster image.
#include <ImageGradient.h>
Public Member Functions
virtual ~ImageGradient (void)
Destructor.
virtual float getScale (void) const =0
Returns the scale of the operator.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual VectorField * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a VectorField.
virtual VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
virtual void applyInto (const RasterImage *imgIn, VectorField *vectOut)=0
Applies this operator to a RasterImage and writes the result into a VectorField received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)=0
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ImageGradient (int theWidth, bool isIntOperator)
Creates an ImageGradient operator with the specified width.
ImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates an ImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ImageGradient (const ImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempGrayF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D gray temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
const ImageGradient & operator= (const ImageGradient &obj)
Copy operator: disabled.
Private Attributes
ImageRect * boundRect_
Bounding rectangle for pre-allocated temporary raster.
RasterImage_gray_F * tempRaster_
Temporary raster.
Detailed Description
Pure virtual parent class for an operator that computes the gradient of a raster image.
Author
jean-yves herve', 3D Group, URI
Definition at line 29 of file ImageGradient.h.
Constructor & Destructor Documentation
ImageGradient::~ImageGradient (void) virtual
Destructor.
Does nothing
Definition at line 66 of file ImageGradient.cpp.
References boundRect_, and tempRaster_.
 {
    if (boundRect_ != NULL)
         delete boundRect_;
     if (tempRaster_ != NULL)
         delete tempRaster_;
 }
ImageGradient::ImageGradient (int theWidth, bool isIntOperator) protected
Creates an ImageGradient operator with the specified width.
Parameters
theWidth desired width of the Gaussian filter
isIntOperator true if this operator produces only integer output
Definition at line 27 of file ImageGradient.cpp.
                         :       VectorOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1, isIntOperator),
                                 boundRect_(NULL),
                                 tempRaster_(NULL)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient constructor");
         throw e;
 }
ImageGradient::ImageGradient (int theWidth, const ImageRect * theRect, bool isIntOperator) protected
Creates an ImageGradient operator with the specified width and a temporary raster at the specified dimensions.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the ImageGradient
theRect bounding rectangle for the temporary raster
isIntOperator true if this operator produces only integer output
Definition at line 41 of file ImageGradient.cpp.
                         :       VectorOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1, isIntOperator),
                                 boundRect_(new ImageRect(theRect)),
                                 tempRaster_(new RasterImage_gray_F(theRect))
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient constructor");
         throw e;
 }
ImageGradient::ImageGradient (const ImageGradient & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 54 of file ImageGradient.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       VectorOperator(theObj),
                                 //
                                 boundRect_(NULL),
                                 tempRaster_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient copy constructor not implemented.");
 }
Member Function Documentation
bool ImageGradient::allocateTempRaster_ (const ImageRect * rect) protected
Allocates the temporary raster associated with this object.
If the raster was already allocated, the function only reallocates it if it was smaller than the new rect.
Parameters
rect dimensions of the temp rect to allocate
Returns
true if a new raster was allocated or the old one was resized
Definition at line 91 of file ImageGradient.cpp.
References uriVL::DrawableObject2D::contains(), uriVL::DrawableObject2D::setBoundRect(), and tempRaster_.
Referenced by uriVL::ImageGradient_Gaussian_F::applyInto().
 {
         bool newTempRaster = (tempRaster_ == NULL);
     if (newTempRaster) {
         tempRaster_ = new RasterImage_gray_F(theRect);
         }
         //      Check if the user is a bonehead
     else if (!tempRaster_->contains(theRect)) {
                 tempRaster_->setBoundRect(theRect);
                 newTempRaster = true;
         }
         return newTempRaster;
 }
void ImageGradient::freeTempRaster_ (void) protected
Frees the temporary raster associated with this object.
Definition at line 106 of file ImageGradient.cpp.
References tempRaster_.
Referenced by uriVL::ImageGradient_Gaussian_F::applyInto().
 {
         if (tempRaster_ != NULL) {
                 delete tempRaster_;
                 tempRaster_ = NULL;
         }
 }
virtual float uriVL::ImageGradient::getScale (void) const pure virtual
Returns the scale of the operator.
Returns
scale of the operator
Implemented in uriVL::ImageGradient_Gaussian_I, uriVL::ImageGradient_Gaussian_F, and uriVL::ImageGradient_Sobel.
float *const * ImageGradient::getShiftedTempGrayF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D gray temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 114 of file ImageGradient.cpp.
References uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), and uriVL::ImageGradient_Gaussian_F::applyInto_Y_().
 {
         return tempRaster_->getShiftedGrayF2D(R_W_ACCESS);
 }
const ImageGradient & ImageGradient::operator= (const ImageGradient & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 74 of file ImageGradient.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient copy operator not implemented.");
         return *this;
 }
Member Data Documentation
ImageRect* uriVL::ImageGradient::boundRect_ private
Bounding rectangle for pre-allocated temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 104 of file ImageGradient.h.
Referenced by ~ImageGradient().
RasterImage_gray_F* uriVL::ImageGradient::tempRaster_ private
Temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 113 of file ImageGradient.h.
Referenced by allocateTempRaster_(), freeTempRaster_(), getShiftedTempGrayF2D_(), and ~ImageGradient().
The documentation for this class was generated from the following files:
ImageGradient.h
ImageGradient.cpp