URIVisionLibrary: uriVL::ImageWriter Class Reference
uriVL::ImageWriter Class Reference
A simple/lame class that writes image objects to files.
#include <ImageWriter.h>
Public Member Functions
ImageWriter (void)
Default constructor.
ImageWriter (const char *filePath)
Creates a new ImageWriter with a destination already assigned.
~ImageWriter (void)
Destructor.
void setDestination (void)
Use the GUI to assign a new destination to the writer.
void setDestination (const char *filePath)
Assign as a new destination to the writer the file designated by the path.
void outputFrame (const RasterImage *theImage, bool writeUpsideDown=false)
Write the image to the currently assigned destination.
void writeImage (const RasterImage *theImage, bool writeUpsideDown=false)
Write the image to the currently assigned destination.
Public Member Functions inherited from uriVL::VideoDestination
VideoDestination (void)
Default constructor.
virtual ~VideoDestination (void)
Destructor.
Static Public Member Functions
static void writeImage (const RasterImage *theImage, const char *filePath, bool writeUpsideDown=false)
Write the image to the currently assigned destination.
static int extensionIndex (const char *ext)
Identifies the type of an image file from its file extension (as long as it is ppm, pgm, pbm, or tga)
Private Member Functions
ImageWriter (const ImageWriter &obj)
Copy constructor.
const ImageWriter & operator= (const ImageWriter &obj)
Copy operator.
Static Private Attributes
static const char * kWriteExtensions_ [4]
List of file extensions supported by this class.
Detailed Description
A simple/lame class that writes image objects to files.
Currently handles only the following image formats
PPM [both ASCII and binary]
PGM [both ASCII and binary]
tga (Targa) [Both 24 and 8 bit formats]
I haven't bothered adding support for GIF or JPEG because I don't want to mess with compression. If I had to handle these image formats, I would probably use QuickTime's export libraries.
Origins of this code: The PPM code is mine. The TGA code is not. I lifted it from my student Claude Duchesne's augmented reality project [GRPR, EPM, 1999-2002]. I have seen minor variations of that code in many programs that I have downloaded, but I do not know who was the original author.
Versions:
01/10/2003 basic code for reading PPM/tga files
02/10/2003 cleanup and bug fixes
05/07/2004 derived from VideoDestination
05/29/2013 revised to match VideoSource update
Definition at line 67 of file ImageWriter.h.
Constructor & Destructor Documentation
ImageWriter::ImageWriter (void)
Default constructor.
Definition at line 42 of file ImageWriter.cpp.
     :   VideoDestination( ),
                 //
                 #if URIVL_USE_QUICKTIME
                         writer_(new _ImageWriter_QT( ))
                 #elif URIVL_USE_FREEIMAGE
                         writer_(new _ImageWriter_FreeImage( ))
                 #elif URIVL_USE_HACK_RW
                         writer_(new _ImageWriter_hack( ))
                 #else
                           #error no writer defined
                 #endif
 {
 }
ImageWriter::ImageWriter (const char * filePath)
Creates a new ImageWriter with a destination already assigned.
Parameters
filePath path to the file assigned as destination to this writer
Definition at line 58 of file ImageWriter.cpp.
     :   VideoDestination( ),
                 //
                 #if URIVL_USE_QUICKTIME
                         writer_(new _ImageWriter_QT(theFilePath))
                 #elif URIVL_USE_FREEIMAGE
                         writer_(new _ImageWriter_FreeImage(theFilePath))
                 #elif URIVL_USE_HACK_RW
                         writer_(new _ImageWriter_hack(theFilePath))
                 #else
                         #error no writer defined
     #endif
 {
 }
ImageWriter::~ImageWriter (void)
Destructor.
Definition at line 89 of file ImageWriter.cpp.
 {
         if (writer_ != NULL)
         {
                 delete writer_;
         }
 }
uriVL::ImageWriter::ImageWriter (const ImageWriter & obj) private
Copy constructor.
Parameters
obj the object to copy
Member Function Documentation
static int uriVL::ImageWriter::extensionIndex (const char * ext) static
Identifies the type of an image file from its file extension (as long as it is ppm, pgm, pbm, or tga)
Parameters
ext the file's extension
Returns
the type of the image
const ImageWriter& uriVL::ImageWriter::operator= (const ImageWriter & obj) private
Copy operator.
Parameters
obj the object to copy
void ImageWriter::outputFrame (const RasterImage * theImage, bool writeUpsideDown = false) virtual
Write the image to the currently assigned destination.
Parameters
the image to write
writeUpsideDown true if the image should be written upside down (temp. setting for some tga files)
Implements uriVL::VideoDestination.
Definition at line 124 of file ImageWriter.cpp.
Referenced by WXGL_IO_Canvas::CreateTestImage().
 {
     writer_->outputFrame_(theImage, writeUpsideDown);
 }
void ImageWriter::setDestination (void) virtual
Use the GUI to assign a new destination to the writer.
Implements uriVL::VideoDestination.
Definition at line 102 of file ImageWriter.cpp.
 {
     writer_->setDestination_( );
 }
void ImageWriter::setDestination (const char * filePath)
Assign as a new destination to the writer the file designated by the path.
Parameters
filePath path to the new destination file
Definition at line 107 of file ImageWriter.cpp.
 {
     writer_->setDestination_(filePath);
 }
void ImageWriter::writeImage (const RasterImage * theImage, bool writeUpsideDown = false)
Write the image to the currently assigned destination.
Parameters
the image to write
writeUpsideDown true if the image should be written upside down (temp. setting for some tga files)
Definition at line 130 of file ImageWriter.cpp.
 {
     writer_->outputFrame_(theImage, writeUpsideDown);
 }
void ImageWriter::writeImage (const RasterImage * theImage, const char * filePath, bool writeUpsideDown = false) static
Write the image to the currently assigned destination.
Parameters
the image to write
filePath path to the new destination file
writeUpsideDown true if the image should be written upside down (temp. setting for some tga files)
Definition at line 135 of file ImageWriter.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::kFileIOError, and uriVL::_ImageWriter_FreeImage::writeImage_().
 {
         try
         {
                 #if URIVL_USE_QUICKTIME
                         _ImageWriter_QT::writeImage_(theImage, filePath, writeUpsideDown);
                 #elif URIVL_USE_FREEIMAGE
                         _ImageWriter_FreeImage::writeImage_(theImage, filePath, writeUpsideDown);
                 #elif  URIVL_USE_HACK_RW
                         _ImageWriter_hack::writeImage_(theImage, filePath, writeUpsideDown);
                 #else
                         //      we should not make it there
                         #error No writer defined in ImageWriter::writeImage
                 #endif
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by ImageWriter::writeImage");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kFileIOError,
                                                 "Unexpected error encountered in ImageWriter::writeImage");
         }
 }
Member Data Documentation
const char * ImageWriter::kWriteExtensions_ static private
Initial value:
= {
                                                                                                        "tga",
                                                                                                        "ppm",
                                                                                                        "pgm",
                                                                                                        "bmp"
                                                                                                }
List of file extensions supported by this class.
Not sure why I should still need that stuff when the QT file importer is supposed to handle all that
Definition at line 145 of file ImageWriter.h.
The documentation for this class was generated from the following files:
ImageWriter.h
ImageWriter.cpp