URIVisionLibrary: uriVL::_GraphWorld_gen Class Reference
uriVL::_GraphWorld_gen Class Reference
Implements the _GraphWorld_gen class.
#include <_GraphWorld_gen.h>
Private Member Functions
_GraphWorld_gen (int pixelDepth, const ImageRect *boundsRect)
Constructor.
_GraphWorld_gen (int pixelDepth, int nbRows, int nbCols)
Constructor.
_GraphWorld_gen (const _GraphWorld_gen *theGWorld)
Copy constructor.
_GraphWorld_gen (const _GraphWorld_gen &theGWorld)
Copy constructor.
~_GraphWorld_gen (void)
Destructor.
const _GraphWorld_gen & operator= (const _GraphWorld_gen &theGWorld)
= operator.
int getBaseRasterType_ (void) const
Returns the index of the base raster type for this GWorld.
int getPixelDepth_ (void) const
Returns the number of bits per pixel (pixel depth)
int getBytesPerPixel_ (void) const
Returns the number of bytes per pixel.
int getNbRows_ (void) const
Returns the height (number of rows) of the raster.
int getBytesPerRow_ (void) const
Returns the number of bytes on each row of the _GraphWorld_gen.
int getEffectiveNbCols_ (void) const
Returns the effectivenumber of columns in the GraphWorld.
void copyInto_ (_GraphWorld_gen *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray)
void copyBinaryInto_ (_GraphWorld_gen *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray)
void copyGrayInto_ (_GraphWorld_gen *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray)
void copyRGB24Into_ (_GraphWorld_gen *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray)
void copyRGBa32Into_ (_GraphWorld_gen *destination, const ImageRect *sourceRect, const ImageRect *destRect, bool inverseGray)
void draw_ (void)
Renders the raster, using the OpenGL drawPixel function.
unsigned char * getRaster_ (void)
Returns the base address of the Graphworld's raster (QuickDraw PixMap)
void setAsMovieGraphWorld_ (Movie theMovie)
Sets this _GraphWorld_gen object as the destination of a movie.
void setAsImporterGraphWorld_ (GraphicsImportComponent importer)
Sets this _GraphWorld_QT object as destination for a graphic importer.
void setGraphWorld_ (const _GraphWorld_gen *theGWorld)
Sets this GraphWorld as destination for a video capture.
void setGraphWorld_ (const _GraphWorld_gen *theGWorld, GDHandle theDevice)
Sets this object as the current GWorld for the QuickDraw engine, preserves the previous GWorld and graphic device in objects defined by the caller.
void restoreGraphWorld_ (void)
Restores previous current _GraphWorld_gen and graphic device settings.
void setGraphWorld_ (void)
Sets this GWorld as the current graphic port (QuickDraw call) The current device is set to NULL.
void setGraphWorld_ (GDHandle theDevice)
Sets this GWorld as the current graphic port (QuickDraw call).
void lock_ (void)
Locks this GraphWorld's PixMap.
void unlock_ (void)
Unlocks this GraphWorld's PixMap.
Private Attributes
BaseRasterType baseType_
Index for the base raster type.
int nbRows_
Number of rows of the raster.
int nbCols_
Number of columns of the raster.
int rowBytes_
Effective number of bytes per row (taking into account row padding)
int pixelDepth_
Stores the pixel depth (number of bits per pixel)
unsigned char * raster_
Reference to the 1D raster storing the image.
Friends
class GraphWorld
class FrameGrabber
Detailed Description
Implements the _GraphWorld_gen class.
Graphworld_gen is an implementation of the GraphWorld class that only uses "generic" C++ code.
The base subclasses of RasterImage correspond to the base raster types. They are:
RasterImage_gray for 8-bit gray level images
RasterImage_rgb16 for 16-bit [1 alpha, 5 red, 5 green, 5 blue] color images
RasterImage_RGB for 24-bit [8 red, 8 green, 8 blue] color images
RasterImage_RGBa for 32-bit [8 alpha, 8 red, 8 green, 8 blue] color images These base subclasses can be instanciated and are the ones most commonly used for image processing and computer vision purposes.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 46 of file _GraphWorld_gen.h.
Constructor & Destructor Documentation
_GraphWorld_gen::_GraphWorld_gen (int pixelDepth, const ImageRect * boundsRect) private
Constructor.
Creates a new _GraphWorld_gen at the dimensions and pixel depth specified.
Parameters
pixelDepth number of bits per pixel (8, 16, 24, 32)
boundsRect bounding rectangle for this raster
Definition at line 39 of file _GraphWorld_gen.cpp.
References baseType_, FAIL_CONDITION, uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kGWorldAllocationError, uriVL::kGWorldInvalidPixelDepth, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, nbCols_, nbRows_, pixelDepth_, raster_, and rowBytes_.
                 :       baseType_(kUndefRasterType),
                         nbRows_(boundsRect->getHeight()),
                         nbCols_(boundsRect->getWidth()),
                         rowBytes_(0),
                         pixelDepth_(pixelDepth),
                         raster_(NULL)
 {
     long nbBytes;
     raster_ = NULL;
     switch (pixelDepth)
     {
         //  binary raster
         case 1:
             baseType_ = kBinaryRaster;
             nbBytes = (nbCols_+7)/8;
             rowBytes_ = (nbCols_+7)/8;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  gray-level raster
         case 8:
             baseType_ = kGrayRaster;
             rowBytes_ = ((nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  16-bit color raster
         case 16:
             baseType_ = kaRGB16Raster;
             rowBytes_ = ((2*nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  RGB raster
         case 24:
             baseType_ = kRGB24Raster;
             rowBytes_ = ((3*nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  ARGB raster
         case 32:
             baseType_ = kRGBa32Raster;
             rowBytes_ = 4*nbCols_;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         default:
             FAIL_CONDITION( true, kGWorldInvalidPixelDepth,
                             "_GraphWorld_gen pixel depth must be 1, 8, 16, 24, or 32");
             break;
     }
     FAIL_CONDITION( raster_==NULL,
                     kGWorldAllocationError,
                     "GWorld allocation failed in _GraphWorld_gen constructor");
     pixelDepth_ = pixelDepth;
 }
 catch(...) {
         FAIL_CONDITION( boundsRect == NULL,
                                         kNullParameterError,
                                         "null ImageRect pointer passed to _GraphWorld_QT constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid ImageRect pointer passed to _GraphWorld_QT constructor.");
 }
_GraphWorld_gen::_GraphWorld_gen (int pixelDepth, int nbRows, int nbCols) private
Constructor.
Creates a new _GraphWorld_gen at the dimensions and pixel depth specified.
Parameters
pixelDepth number of bits per pixel (8, 16, 24, 32)
nbRows number of rows of the raster
nbCols number of columns of the raster
Definition at line 116 of file _GraphWorld_gen.cpp.
References baseType_, FAIL_CONDITION, uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kGWorldAllocationError, uriVL::kGWorldInvalidPixelDepth, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, nbCols_, nbRows_, raster_, and rowBytes_.
                 :       baseType_(kUndefRasterType),
                         nbRows_(nbRows),
                         nbCols_(nbCols),
                         rowBytes_(0),
                         pixelDepth_(pixelDepth),
                         raster_(NULL)
 {
     long nbBytes;
     raster_ = NULL;
     switch (pixelDepth)
     {
         //  binary raster
         case 1:
             baseType_ = kBinaryRaster;
             nbBytes = (nbCols_+7)/8;
             rowBytes_ = (nbCols_+7)/8;
             nbBytes = nbRows_*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  gray-level raster
         case 8:
             baseType_ = kGrayRaster;
             rowBytes_ = ((nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  16-bit color raster
         case 16:
             baseType_ = kaRGB16Raster;
             rowBytes_ = ((2*nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  RGB raster
         case 24:
             baseType_ = kRGB24Raster;
             rowBytes_ = ((3*nbCols_ + 3)/4)*4;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         //  ARGB raster
         case 32:
             baseType_ = kRGBa32Raster;
             rowBytes_ = 4*nbCols_;
             nbBytes = (1L*nbRows_)*rowBytes_;
             raster_ = new unsigned char[nbBytes];
             break;
         default:
             FAIL_CONDITION( true, kGWorldInvalidPixelDepth,
                             "_GraphWorld_gen pixel depth must be 1, 8, 16, 24, or 32");
             break;
     }
     FAIL_CONDITION( raster_==NULL,
                     kGWorldAllocationError,
                     "GWorld allocation failed in _GraphWorld_gen constructor");
 }
_GraphWorld_gen::_GraphWorld_gen (const _GraphWorld_gen * theGWorld) private
Copy constructor.
Parameters
theGWorld the _GraphWorld_gen to clone
Definition at line 184 of file _GraphWorld_gen.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       baseType_(kUndefRasterType),
                         nbRows_(0),
                         nbCols_(0),
                         rowBytes_(0),
                         pixelDepth_(0),
                         raster_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "_GraphWorld_gen clone constructor is not operative yet");
 }
_GraphWorld_gen::_GraphWorld_gen (const _GraphWorld_gen & theGWorld) private
Copy constructor.
Currently not implemented.
Parameters
theGWorld the _GraphWorld_gen to clone
Definition at line 197 of file _GraphWorld_gen.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       baseType_(kUndefRasterType),
                         nbRows_(0),
                         nbCols_(0),
                         rowBytes_(0),
                         pixelDepth_(0),
                         raster_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "_GraphWorld_gen clone constructor is not operative yet");
 }
_GraphWorld_gen::~_GraphWorld_gen (void) private
Destructor.
Definition at line 211 of file _GraphWorld_gen.cpp.
References raster_.
 {
     delete []raster_;
 }
Member Function Documentation
void _GraphWorld_gen::copyBinaryInto_ (_GraphWorld_gen * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) private
Definition at line 320 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::RasterImage_binary::convertToGray(), FAIL_CONDITION, getBytesPerPixel_(), getBytesPerRow_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), getRaster_(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kBinaryRaster, uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by copyInto_().
 {
     const int   rowBytesIn = getBytesPerRow_(),
                 rowBytesOut = destination->getBytesPerRow_(),
                 pixelBytesIn = getBytesPerPixel_(),
                 pixelBytesOut = destination->getBytesPerPixel_(),
                 nbRows = sourceRect->getHeight(),
                 nbCols = sourceRect->getWidth();
     unsigned char  *imgIn = getRaster_() + rowBytesIn*sourceRect->getTop()
                                          + pixelBytesIn*sourceRect->getLeft(),
                    *imgOut = destination->getRaster_() + rowBytesOut*destRect->getTop()
                                          + pixelBytesOut*destRect->getLeft();
     switch (destination->baseType_)
     {
         case kBinaryRaster: {
                 const int nbBytes = (nbCols+7)/8;
                 for (int i=0; i<nbRows; i++)
                 {
                     memcpy(imgOut, imgIn, nbBytes);
                     imgIn += rowBytesIn;
                     imgOut += rowBytesOut;
                 }
             }
             break;
         case kGrayRaster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_binary::convertToGray(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGB24Raster:
             FAIL_CONDITION( true,
                             kFunctionNotImplemented,
                             "_GraphWorld_gen::copyBinaryInto_ --> RGB is not operative yet");
             break;
         case kRGBa32Raster:
             FAIL_CONDITION( true,
                             kFunctionNotImplemented,
                             "_GraphWorld_gen::copyBinaryInto_ --> RGB is not operative yet");
             break;
         default:
             break;
     }
 }
void _GraphWorld_gen::copyGrayInto_ (_GraphWorld_gen * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) private
Definition at line 379 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::RasterImage_gray::convertToBinary(), uriVL::RasterImage_gray::convertToRGB(), uriVL::RasterImage_gray::convertToRGBa(), getBytesPerPixel_(), getBytesPerRow_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), getRaster_(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by copyInto_().
 {
     const int   rowBytesIn = getBytesPerRow_(),
                 rowBytesOut = destination->getBytesPerRow_();
     const int   pixelBytesIn = getBytesPerPixel_(),
                 pixelBytesOut = destination->getBytesPerPixel_(),
                 nbRows = sourceRect->getHeight(),
                 nbCols = sourceRect->getWidth();
     unsigned char  *imgIn = getRaster_() + rowBytesIn*sourceRect->getTop()
                                          + pixelBytesIn*sourceRect->getLeft(),
                    *imgOut = destination->getRaster_() + rowBytesOut*destRect->getTop()
                                          + pixelBytesOut*destRect->getLeft();
     switch (destination->baseType_)
     {
         case kBinaryRaster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_gray::convertToBinary(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kGrayRaster:
             for (int i=0; i<nbRows; i++)
             {
                 memcpy(imgOut, imgIn, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGB24Raster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_gray::convertToRGB(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGBa32Raster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_gray::convertToRGBa(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         default:
             break;
     }
 }
void _GraphWorld_gen::copyInto_ (_GraphWorld_gen * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) private
Definition at line 285 of file _GraphWorld_gen.cpp.
References baseType_, copyBinaryInto_(), copyGrayInto_(), copyRGB24Into_(), copyRGBa32Into_(), FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kInvalidParameterError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by uriVL::GraphWorld::copyInto().
 {
     //  At this point copyInto does not do any kind of scaling.
     FAIL_CONDITION( (sourceRect->getWidth() != destRect->getWidth()) ||
                     (sourceRect->getHeight() != destRect->getHeight()),
                     kInvalidParameterError,
                     "Generic copyInto does not do any kind of scaling");
     switch (baseType_)
     {
         case kBinaryRaster:
             copyBinaryInto_(destination, sourceRect, destRect, inverseGray);
             break;
         case kGrayRaster:
             copyGrayInto_(destination, sourceRect, destRect, inverseGray);
             break;
         case kRGB24Raster:
             copyRGB24Into_(destination, sourceRect, destRect, inverseGray);
             break;
         case kRGBa32Raster:
             copyRGBa32Into_(destination, sourceRect, destRect, inverseGray);
             break;
         default:
             break;
     }
 }
void _GraphWorld_gen::copyRGB24Into_ (_GraphWorld_gen * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) private
Definition at line 441 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::RasterImage_RGB::convertToGray(), uriVL::RasterImage_RGB::convertToRGBa(), FAIL_CONDITION, getBytesPerPixel_(), getBytesPerRow_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), getRaster_(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kAverageConversion, uriVL::kBinaryRaster, uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by copyInto_().
 {
     const int   rowBytesIn = getBytesPerRow_(),
                 rowBytesOut = destination->getBytesPerRow_();
         const int   pixelBytesIn = getBytesPerPixel_(),
                 pixelBytesOut = destination->getBytesPerPixel_(),
                 nbRows = sourceRect->getHeight(),
                 nbCols = sourceRect->getWidth();
     unsigned char  *imgIn = getRaster_() + rowBytesIn*sourceRect->getTop()
                                          + pixelBytesIn*sourceRect->getLeft(),
                    *imgOut = destination->getRaster_() + rowBytesOut*destRect->getTop()
                                          + pixelBytesOut*destRect->getLeft();
     switch (destination->baseType_)
     {
         case kBinaryRaster:
             FAIL_CONDITION( true,
                             kFunctionNotImplemented,
                             "_GraphWorld_gen::copyInto --> binary is not operative yet");
             break;
         case kGrayRaster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_RGB::convertToGray(imgIn, imgOut, nbCols, kAverageConversion);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGB24Raster:
             {
                 const int nbBytes = 3*nbCols;
                 for (int i=0; i<nbRows; i++)
                 {
                     memcpy(imgOut, imgIn, nbBytes);
                     imgIn += rowBytesIn;
                     imgOut += rowBytesOut;
                 }
             }
             break;
         case kRGBa32Raster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_RGB::convertToRGBa(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         default:
             break;
     }
 }
void _GraphWorld_gen::copyRGBa32Into_ (_GraphWorld_gen * destination, const ImageRect * sourceRect, const ImageRect * destRect, bool inverseGray) private
Definition at line 504 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::RasterImage_RGBa::convertToGray(), uriVL::RasterImage_RGBa::convertToRGB(), FAIL_CONDITION, getBytesPerPixel_(), getBytesPerRow_(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), getRaster_(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::kAverageConversion, uriVL::kBinaryRaster, uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by copyInto_().
 {
     const int   rowBytesIn = getBytesPerRow_(),
                 rowBytesOut = destination->getBytesPerRow_(),
                 pixelBytesIn = getBytesPerPixel_(),
                 pixelBytesOut = destination->getBytesPerPixel_(),
                 nbRows = sourceRect->getHeight(),
                 nbCols = sourceRect->getWidth();
     unsigned char  *imgIn = getRaster_() + rowBytesIn*sourceRect->getTop()
                                          + pixelBytesIn*sourceRect->getLeft(),
                    *imgOut = destination->getRaster_() + rowBytesOut*destRect->getTop()
                                          + pixelBytesOut*destRect->getLeft();
     switch (destination->baseType_)
     {
         case kBinaryRaster:
             FAIL_CONDITION( true,
                             kFunctionNotImplemented,
                             "_GraphWorld_gen::copyInto --> binary is not operative yet");
             break;
         case kGrayRaster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_RGBa::convertToGray(imgIn, imgOut, nbCols, kAverageConversion);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGB24Raster:
             for (int i=0; i<nbRows; i++)
             {
                 RasterImage_RGBa::convertToRGB(imgIn, imgOut, nbCols);
                 imgIn += rowBytesIn;
                 imgOut += rowBytesOut;
             }
             break;
         case kRGBa32Raster:
             {
                 const int nbBytes = 4*nbCols;
                 for (int i=0; i<nbRows; i++)
                 {
                     memcpy(imgOut, imgIn, nbBytes);
                     imgIn += rowBytesIn;
                     imgOut += rowBytesOut;
                 }
             }
             break;
         default:
             break;
     }
 }
void _GraphWorld_gen::draw_ (void) private
Renders the raster, using the OpenGL drawPixel function.
Definition at line 568 of file _GraphWorld_gen.cpp.
References baseType_, getEffectiveNbCols_(), getRaster_(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and nbRows_.
Referenced by uriVL::GraphWorld::draw().
 {
     switch (baseType_)
     {
         case kBinaryRaster:
             glDrawPixels( getEffectiveNbCols_(), nbRows_,
                           GL_LUMINANCE,
                           GL_UNSIGNED_BYTE,
                           getRaster_());
             break;
         case kGrayRaster:
             glDrawPixels( getEffectiveNbCols_(), nbRows_,
                           GL_LUMINANCE,
                           GL_UNSIGNED_BYTE,
                           getRaster_());
             break;
         case kRGB24Raster:
             glDrawPixels( getEffectiveNbCols_(), nbRows_,
                           GL_RGB,
                           GL_UNSIGNED_BYTE,
                           getRaster_());
             break;
         case kRGBa32Raster:
             glDrawPixels( getEffectiveNbCols_(), nbRows_,
                           GL_RGBA,
                           GL_UNSIGNED_BYTE,
                           getRaster_());
             break;
         default:
             break;
     }
 }
int _GraphWorld_gen::getBaseRasterType_ (void) const private
Returns the index of the base raster type for this GWorld.
The base raster type is one of those defined by the BaseRasterType enum type.
Returns
index of the base raster type for this GWorld
See also
BaseRasterType
Definition at line 233 of file _GraphWorld_gen.cpp.
References baseType_.
Referenced by uriVL::GraphWorld::getBaseRasterType().
 {
     return baseType_;
 }
int _GraphWorld_gen::getBytesPerPixel_ (void) const private
Returns the number of bytes per pixel.
Returns
number of bytes per pixel
Definition at line 265 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::kBinaryRaster, and pixelDepth_.
Referenced by copyBinaryInto_(), copyGrayInto_(), copyRGB24Into_(), and copyRGBa32Into_().
 {
     if (baseType_ == kBinaryRaster)
         return 0;
     else
         return pixelDepth_/8;
 }
int _GraphWorld_gen::getBytesPerRow_ (void) const private
Returns the number of bytes on each row of the _GraphWorld_gen.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of bytes on a row of the _GraphWorld_gen
Definition at line 239 of file _GraphWorld_gen.cpp.
References rowBytes_.
Referenced by copyBinaryInto_(), copyGrayInto_(), copyRGB24Into_(), copyRGBa32Into_(), and uriVL::GraphWorld::getBytesPerRow().
 {
     return rowBytes_;
 }
int _GraphWorld_gen::getEffectiveNbCols_ (void) const private
Returns the effectivenumber of columns in the GraphWorld.
Base rasters have padded rows. This function returns the number of bytes per row divided by the pixel depth.
Returns
effectivenumber of columns in the GraphWorld
Definition at line 251 of file _GraphWorld_gen.cpp.
References baseType_, uriVL::kBinaryRaster, pixelDepth_, and rowBytes_.
Referenced by draw_(), and uriVL::GraphWorld::getEffectiveNbCols().
 {
     if (baseType_ == kBinaryRaster)
         return rowBytes_*8;
     else
         return rowBytes_ / (pixelDepth_/8);
 }
int _GraphWorld_gen::getNbRows_ (void) const private
Returns the height (number of rows) of the raster.
Returns
height of the raster
Definition at line 245 of file _GraphWorld_gen.cpp.
References nbRows_.
Referenced by uriVL::GraphWorld::getNbRows(), and uriVL::GraphWorld::getTotalByteCount().
 {
     return nbRows_;
 }
int _GraphWorld_gen::getPixelDepth_ (void) const private
Returns the number of bits per pixel (pixel depth)
Returns
pixel depth
See also
pixelDepth_
Definition at line 260 of file _GraphWorld_gen.cpp.
References pixelDepth_.
Referenced by uriVL::GraphWorld::getPixelDepth().
 {
     return pixelDepth_;
 }
unsigned char * _GraphWorld_gen::getRaster_ (void) private
Returns the base address of the Graphworld's raster (QuickDraw PixMap)
Returns
base address of the Graphworld's raster
Definition at line 606 of file _GraphWorld_gen.cpp.
References raster_.
Referenced by copyBinaryInto_(), copyGrayInto_(), copyRGB24Into_(), copyRGBa32Into_(), draw_(), and uriVL::GraphWorld::getRaster().
 {
     return raster_;
 }
void uriVL::_GraphWorld_gen::lock_ (void) private
Locks this GraphWorld's PixMap.
const _GraphWorld_gen & _GraphWorld_gen::operator= (const _GraphWorld_gen & theGWorld) private
= operator.
Currently not implemented.
Parameters
theGWorld the _GraphWorld_gen to copy
Definition at line 216 of file _GraphWorld_gen.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "_GraphWorld_gen = operator is not operative yet");
         return *this;
 }
void _GraphWorld_gen::restoreGraphWorld_ (void) private
Restores previous current _GraphWorld_gen and graphic device settings.
Definition at line 644 of file _GraphWorld_gen.cpp.
Referenced by uriVL::GraphWorld::restoreGraphWorld().
 {
 }
void _GraphWorld_gen::setAsImporterGraphWorld_ (GraphicsImportComponent importer) private
Sets this _GraphWorld_QT object as destination for a graphic importer.
When data is read from an image file, a GWorld must be set as the destination for the graphic importer. This member function allows to define this GraphWorld as the destination for the importer, so as to avoid unnecessary blitting between buffers.
Parameters
importer the graphic importer that will draw into this object
See also
restoreGraphWorld
Definition at line 623 of file _GraphWorld_gen.cpp.
Referenced by uriVL::GraphWorld::setAsImporterGraphWorld().
 {
 }
void _GraphWorld_gen::setAsMovieGraphWorld_ (Movie theMovie) private
Sets this _GraphWorld_gen object as the destination of a movie.
The movie will play (render) into this object
Parameters
theMovie the movie that will play into this object
Definition at line 619 of file _GraphWorld_gen.cpp.
Referenced by uriVL::GraphWorld::setAsMovieGraphWorld().
 {
 }
void _GraphWorld_gen::setGraphWorld_ (const _GraphWorld_gen * theGWorld) private
Sets this GraphWorld as destination for a video capture.
When a movie is played or live video is grabbed, a GWorld must be set as the destination for the video stream. This member function allows to define the RasterImage's base raster as the destination for the video stream, so as to avoid unnecessary blitting between buffers.
This function keeps a copy of the previous GraphWorld, so that it can restore it later on.
Parameters
grabber the FrameGrabber that will play into this object
Returns
error code (0 if all OK)
See also
restoreGraphWorldSets this object as the current GWorld for the QuickDraw engine, preserves the previous GWorld in a _GraphWorld_gen object defined by the caller. The Graphic Device is set to NULL.
Parameters
theGWorld reference to _GraphWorld_gen where to store previous settings Stores copies of these references to restore them later.
Definition at line 635 of file _GraphWorld_gen.cpp.
Referenced by uriVL::GraphWorld::setGraphWorld().
 {
 }
void _GraphWorld_gen::setGraphWorld_ (const _GraphWorld_gen * theGWorld, GDHandle theDevice) private
Sets this object as the current GWorld for the QuickDraw engine, preserves the previous GWorld and graphic device in objects defined by the caller.
Stores copies of these references to restore them later.
Parameters
theGWorld reference to _GraphWorld_gen where to store previous settings
theDevice handle to graphic device where to store previous settings
Definition at line 639 of file _GraphWorld_gen.cpp.
 {
 }
void _GraphWorld_gen::setGraphWorld_ (void) private
Sets this GWorld as the current graphic port (QuickDraw call) The current device is set to NULL.
Definition at line 627 of file _GraphWorld_gen.cpp.
 {
 }
void _GraphWorld_gen::setGraphWorld_ (GDHandle theDevice) private
Sets this GWorld as the current graphic port (QuickDraw call).
Parameters
theDevice new current device
Definition at line 631 of file _GraphWorld_gen.cpp.
 {
 }
void uriVL::_GraphWorld_gen::unlock_ (void) private
Unlocks this GraphWorld's PixMap.
Friends And Related Function Documentation
friend class FrameGrabber friend
Definition at line 327 of file _GraphWorld_gen.h.
friend class GraphWorld friend
Definition at line 326 of file _GraphWorld_gen.h.
Member Data Documentation
BaseRasterType uriVL::_GraphWorld_gen::baseType_ private
Index for the base raster type.
Any RasterImage object is derived from one of the five base types; binary, gray, RGB, RGBa, aRGB16.
Definition at line 52 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen(), copyBinaryInto_(), copyGrayInto_(), copyInto_(), copyRGB24Into_(), copyRGBa32Into_(), draw_(), getBaseRasterType_(), getBytesPerPixel_(), and getEffectiveNbCols_().
int uriVL::_GraphWorld_gen::nbCols_ private
Number of columns of the raster.
Definition at line 60 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen().
int uriVL::_GraphWorld_gen::nbRows_ private
Number of rows of the raster.
Definition at line 56 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen(), draw_(), and getNbRows_().
int uriVL::_GraphWorld_gen::pixelDepth_ private
Stores the pixel depth (number of bits per pixel)
Definition at line 69 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen(), getBytesPerPixel_(), getEffectiveNbCols_(), and getPixelDepth_().
unsigned char* uriVL::_GraphWorld_gen::raster_ private
Reference to the 1D raster storing the image.
Definition at line 74 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen(), getRaster_(), and ~_GraphWorld_gen().
int uriVL::_GraphWorld_gen::rowBytes_ private
Effective number of bytes per row (taking into account row padding)
Definition at line 64 of file _GraphWorld_gen.h.
Referenced by _GraphWorld_gen(), getBytesPerRow_(), and getEffectiveNbCols_().
The documentation for this class was generated from the following files:
_GraphWorld_gen.h
_GraphWorld_gen.cpp