URIVisionLibrary: uriVL::ImageRect Class Reference
uriVL::ImageRect Class Reference
Implements the ImageRect class.
#include <ImageRect.h>
Public Member Functions
ImageRect (void)
Default Constructor.
ImageRect (int theLeft, int theTop, int theWidth, int theHeight)
Constructor.
ImageRect (const ImagePoint *theUpperLeft, const ImagePoint *theLowerRight)
Constructor.
ImageRect (const ImagePoint *theUpperLeft, int theWidth, int theHeight)
Constructor.
ImageRect (const ImageRect *theRect)
Copy constructor.
ImageRect (const ImageRect &theRect)
Copy constructor.
ImageRect (const URIVL_Rect qtRect)
Cross-convention constructor.
~ImageRect (void)
Destructor.
const ImageRect & operator= (const ImageRect &theRect)
Equal operator.
int getWidth (void) const
Returns the width of the rectangle.
int getHeight (void) const
Returns the height of the rectangle.
int getLeft (void) const
Returns the minimum x coordinate of the rectangle.
int getRight (void) const
Returns the maximum x coordinate of the rectangle.
int getTop (void) const
Returns the minimum y coordinate of the rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the rectangle.
const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
long getArea (void) const
Returns the area of the rectangle.
void setOrigin (int x, int y)
Sets the origin of the rectangle.
void setCenter (int cX, int cY)
Sets the center of the rectangle.
void translate (int dx, int dy)
Sets the origin of the rectangle.
void setRect (const ImageRect *theRect)
Sets the origin and size of the rectangle.
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the origin and size of the rectangle.
void setRect (const ImagePoint *topLeft, const ImagePoint *bottomRight)
Sets the origin and size of the rectangle.
void setRect (const ImagePoint *topLeft, int theWidth, int theHeight)
Sets the origin and size of the rectangle.
bool overlaps (const ImageRect *theRect) const
Indicates whether this rectangle and the one received as parameter overlap.
bool overlaps (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle and the one received as parameter overlap.
bool coincidesWith (const ImageRect *theRect) const
Indicates whether this rectangle and the one received as parameter coincide.
bool coincidesWith (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle and the one received as parameter coincide.
bool contains (const ImageRect *theRect, int padding=0) const
Indicates whether this rectangle contains the one received as parameter.
bool contains (int theLeft, int theTop, int theWidth, int theHeight, int padding=0) const
Indicates whether this rectangle contains the one received as parameter.
bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
bool isContainedBy (const ImageRect *theRect) const
Indicates whether this rectangle is contained by the one received as parameter.
bool isContainedBy (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle is contained by the one received as parameter.
bool upperLeftIsAtOrigin (void) const
Indicates whether this rectangle has its upper left corner at (0, 0)
void addAllAround (int n)
Adds n elements all around the rectangle.
void removeAllAround (int n)
Removes n elements all around the rectangle.
Static Public Member Functions
static ImageRect * intersection (const ImageRect *rect1, const ImageRect *rect2)
Returns the intersection of the two rectangles received as parameters.
Private Member Functions
const URIVL_Rect * getRectQT_ (void) const
Returns a reference to the private QuickTime rectangle structure of this ImageRect objet.
Private Attributes
URIVL_Rect rect_
QuickTime rectangle.
ImagePoint upperLeft_
Upper-left point of the rectangle.
ImagePoint lowerRight_
Lower-right point of the rectangle.
Friends
class GraphWorld
class _GraphWorld_gen
Detailed Description
Implements the ImageRect class.
Wrapper class for an image rectangle structure.
Beware! The ImageRect class and the Rect structure of QuickTime (and QuickDraw) are based on different notions of a pixel.
QuickTime sees a pixel as a little square that hangs between the points (xLeft, yTop) and (xLeft+1, yTop+1). This pixel occuppies the QuickTime Rect {xLeft, yTop, xLeft+1, yTop+1}. So the width and height of a QuickTime Rect are simply the differences between xBottom - xLeft and yBottom - yTop.
An ImageRect rectangle is based on the notion of a pixel as a point. In this model, the rectangle {xLeft, yTop, xLeft+1, yTop+1} contains 4 points, not one! This makes more sense for image processing, but one should be very careful when going from Rect to ImageRect and back.
Important: The PixMap stored by the GWorld pads the rows of the raster to round their length in bytes to a multiple of 32. Make sure not to confuse the nominal and effective bounding rectangles of the GraphWorld.
Version history
2007/04/14 [jyh] minor revision (added a bunch of const modifiers).
2004/04/27 [jyh] fixed the pixel-as-point vs. pixel-as-rectangle issue.
2004/02/20 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 84 of file ImageRect.h.
Constructor & Destructor Documentation
ImageRect::ImageRect (void)
Default Constructor.
Creates an image rectangle with its upper-left corner at (0, 0) and a width and height of 0 pixel
Definition at line 26 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, rect_, uriVL::URIVL_Rect::right, and uriVL::URIVL_Rect::top.
Referenced by intersection().
                 :       rect_(URIVL_Rect()),
                         upperLeft_(0, 0),
                         lowerRight_(-1, -1)
 {
         rect_.left = rect_.top = rect_.right = rect_.bottom = static_cast<short>(0);
 }
ImageRect::ImageRect (int theLeft, int theTop, int theWidth, int theHeight)
Constructor.
Creates an image rectangle using the pixel-as-point convention.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Definition at line 35 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, rect_, uriVL::URIVL_Rect::right, and uriVL::URIVL_Rect::top.
                 :       rect_(URIVL_Rect()),
                         upperLeft_(ImagePoint(theLeft, theTop)),
                         lowerRight_(ImagePoint(theLeft + theWidth - 1, theTop + theHeight - 1))
 {
         rect_.left = static_cast<short>(theLeft);
         rect_.top = static_cast<short>(theTop);
         rect_.right = static_cast<short>(rect_.left + theWidth);
         rect_.bottom = static_cast<short>(rect_.top + theHeight);
 }
ImageRect::ImageRect (const ImagePoint * theUpperLeft, const ImagePoint * theLowerRight)
Constructor.
Creates an image rectangle using the pixel-as-point convention.
Parameters
theUpperLeft pointer to the upper-left pixel
theLowerRight pointer to the lower-right pixel (inclusive)
Definition at line 47 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kInvalidParameterError, uriVL::URIVL_Rect::left, rect_, uriVL::URIVL_Rect::right, and uriVL::URIVL_Rect::top.
                 :       rect_(),
                         upperLeft_(ImagePoint(theUpperLeft)),
                         lowerRight_(ImagePoint(theLowerRight))
 {
         try {
                 rect_.left = static_cast<short>(theUpperLeft->getX());
                 rect_.top = static_cast<short>(theUpperLeft->getY());
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid UL ImagePoint pointer passed to ImageRect constructor.");
         }
     try {
                 rect_.right = static_cast<short>(theLowerRight->getX() + 1);
                 rect_.bottom = static_cast<short>(theLowerRight->getY() + 1);
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid LR ImagePoint pointer passed to ImageRect constructor.");
         }
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageRect constructor.");
         throw e;
 }
ImageRect::ImageRect (const ImagePoint * theUpperLeft, int theWidth, int theHeight)
Constructor.
Creates an image rectangle using the pixel-as-point convention.
Parameters
theUpperLeft pointer to the upper-left pixel
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Definition at line 77 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::kInvalidParameterError, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::URIVL_Rect::top, and uriVL::ImagePoint::translate().
                 :       rect_(),
                         upperLeft_(ImagePoint(theUpperLeft)),
                         lowerRight_(ImagePoint(theUpperLeft))
 {
         try {
                 rect_.left = static_cast<short>(theUpperLeft->getX());
                 rect_.top = static_cast<short>(theUpperLeft->getY());
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid UL ImagePoint pointer passed to ImageRect constructor.");
         }
     rect_.right = static_cast<short>(rect_.left + theWidth);
     rect_.bottom = static_cast<short>(rect_.top + theHeight);
     lowerRight_.translate(theWidth-1, theHeight-1);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageRect constructor.");
         throw e;
 }
ImageRect::ImageRect (const ImageRect * theRect)
Copy constructor.
Creates an image rectangle using the pixel-as-point convention.
Parameters
theRect pointer to ImageRect to copy
Definition at line 103 of file ImageRect.cpp.
                 :       rect_(theRect->rect_),
                         upperLeft_(theRect->upperLeft_),
                         lowerRight_(theRect->lowerRight_)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageRect constructor.");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( theRect == NULL,
                                         kNullParameterError,
                                         "null ImageRect pointer passed to ImageRect constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid ImageRect pointer passed to ImageRect constructor.");
 }
ImageRect::ImageRect (const ImageRect & theRect)
Copy constructor.
Creates an image rectangle using the pixel-as-point convention.
Parameters
theRect reference to ImageRect object to copy
Definition at line 124 of file ImageRect.cpp.
                 :       rect_(theRect.rect_),
                         upperLeft_(theRect.upperLeft_),
                         lowerRight_(theRect.lowerRight_)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageRect constructor.");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid ImageRect reference passed to ImageRect constructor.");
 }
ImageRect::ImageRect (const URIVL_Rect qtRect)
Cross-convention constructor.
Creates a pixel-as-point image rectangle using a pixel-as-rectangle rectangle (QuickTime rectangle).
Parameters
theRect pointer to a QuickTime rectangle
Definition at line 144 of file ImageRect.cpp.
                 :       rect_(qtRect),
                         upperLeft_(new ImagePoint(qtRect.left, qtRect.top)),
                         lowerRight_(new ImagePoint(qtRect.right - 1, qtRect.bottom - 1))
 {
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid ImageRect pointer passed to ImageRect constructor.");
 }
ImageRect::~ImageRect (void)
Destructor.
Definition at line 158 of file ImageRect.cpp.
 {
 }
Member Function Documentation
void ImageRect::addAllAround (int n)
Adds n elements all around the rectangle.
After this operation, the rowHigh and colHigh have been incremented by n while the rowLow and colLow have been decremented by n.
Parameters
n amount to add all around
Definition at line 431 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
 {
     rect_.left -= n;
     rect_.top -= n;
     rect_.right += n;
     rect_.bottom += n;
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
bool ImageRect::coincidesWith (const ImageRect * theRect) const
Indicates whether this rectangle and the one received as parameter coincide.
Parameters
theRect the rectangle to test agains this rectangle
Returns
true if the two rectangles coincide, false otherwise
Definition at line 318 of file ImageRect.cpp.
References FAIL_CONDITION, getBottom(), getLeft(), getRight(), getTop(), and uriVL::kNullRectangleError.
Referenced by uriVL::LabelRaster::coincidesWith(), uriVL::DrawableObject2D::coincidesWith(), uriVL::VectorField::copyInto(), uriVL::DrawableObject2D::operator=(), and uriVL::DrawableObject2D::render().
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::coincidesWith");
     return  (theRect->getTop() == getTop()) &&
             (theRect->getLeft() == getLeft()) &&
             (theRect->getBottom() == getBottom()) &&
             (theRect->getRight() == getRight());
 }
bool ImageRect::coincidesWith (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle and the one received as parameter coincide.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Returns
true if the two rectangles coincide, false otherwise
Definition at line 330 of file ImageRect.cpp.
References getBottom(), getLeft(), getRight(), and getTop().
 {
     return  (theTop == getTop()) &&
             (theLeft == getLeft()) &&
             (theTop + theHeight == getBottom()) &&
             (theLeft + theWidth == getRight());
 }
bool ImageRect::contains (const ImageRect * theRect, int padding = 0) const
Indicates whether this rectangle contains the one received as parameter.
Parameters
theRect the rectangle to test agains this rectangle
padding the difference between the rectangle and search rectangle
Returns
true if theRect is contained within this rectangle, false otherwise
Definition at line 362 of file ImageRect.cpp.
References FAIL_CONDITION, getBottom(), getLeft(), getRight(), getTop(), and uriVL::kNullRectangleError.
Referenced by uriVL::MedianFilter_F::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::LabelRaster::contains(), uriVL::DrawableObject2D::contains(), uriVL::Pattern2D::contains(), contains(), uriVL::BlobFinder::findAllBlobsInside(), uriVL::BlobFinder::findBlobAbout(), and uriVL::RectifiedStereoMatcher_JJL::setStereoPair().
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::contains");
     return  (theRect->getTop() >= (getTop()+padding)) &&
             (theRect->getLeft() >= (getLeft()+padding)) &&
             (theRect->getBottom() <= (getBottom()-padding)) &&
             (theRect->getRight() <= (getRight()-padding));
 }
bool ImageRect::contains (int theLeft, int theTop, int theWidth, int theHeight, int padding = 0) const
Indicates whether this rectangle contains the one received as parameter.
Parameters
theRect the rectangle to test agains this rectangle
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
padding the difference between the rectangle and search rectangle
Returns
true if theRect is contained within this rectangle, false otherwise
Definition at line 374 of file ImageRect.cpp.
References getBottom(), getLeft(), getRight(), and getTop().
 {
     return  (theTop >= (getTop()+padding)) &&
             (theLeft >= (getLeft()+padding)) &&
             (theTop + theHeight <= (getBottom()-padding)) &&
             (theLeft + theWidth <= (getRight()-padding));
 }
bool ImageRect::contains (const ImagePoint * pt, int padding = 0) const
Checks whether the point passed as parameter belongs to the rectangle.
Parameters
pt the point to check
padding the difference between the rectangle and search rectangle
Returns
true if pt is inside this rectangle
Definition at line 403 of file ImageRect.cpp.
References contains(), FAIL_CONDITION, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), and uriVL::kNullParameterError.
 {
     FAIL_CONDITION( q == NULL,
                     kNullParameterError,
                     "Null ImagePoint passed to ImageRect::isInside");
     return contains(q->getX(), q->getY(), padding);
 }
bool ImageRect::contains (int x, int y, int padding = 0) const
Checks whether the point passed as parameter belongs to the rectangle.
Parameters
x x coordinate of the point to check
y y coordinate of the point to check
padding the difference between the rectangle and search rectangle
Returns
true if pt is inside this rectangle
Definition at line 412 of file ImageRect.cpp.
References getBottom(), getLeft(), getRight(), and getTop().
 {
 //    return (x>=getLeft()) && (x<=getRight()) && (y>=getTop()) && (y<=getBottom());
     return (x>=(getLeft()+padding)) && (x<=(getRight()-padding))
                  && (y>=(getTop()+padding)) && (y<=(getBottom()-padding));
 }
long uriVL::ImageRect::getArea (void) const
Returns the area of the rectangle.
Returns
area (number of pixels) of the rectangle
int ImageRect::getBottom (void) const
Returns the maximum y coordinate of the rectangle.
Returns
y coordinate of the lower-right pixel
Definition at line 300 of file ImageRect.cpp.
References uriVL::ImagePoint::getY(), and lowerRight_.
Referenced by uriVL::RangeMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), uriVL::LabelRaster::allocateShiftedRaster2D_(), applyAdditiveNoise(), uriVL::HysteresisLabeler::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), applySaltAndPepperNoise(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), coincidesWith(), uriVL::Contour_I::computeCentroid_(), uriVL::Blob::computeCentroid_(), uriVL::ImageHistogram::computeFastHistogram_(), uriVL::ImageHistogram::computeFloatHistogram_(), uriVL::ImageHistogram::computeHistogram_(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::Blob::computeQuadNbPixels_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::ColorInverseThresholdLabeler::connectNeighbor_(), uriVL::ColorThresholdLabeler::connectNeighbors_(), uriVL::GrayThresholdLabeler::connectNeighbors_(), contains(), uriVL::RasterImage_HSV::convertFromGray_(), uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::RasterImage_HSV::convertToRGBa_(), uriVL::RasterImage_HSV::convertToSaturatedRGBa_(), uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), CreateImageAndField(), uriVL::RasterImage_HSV24::deleteShiftedRaster2D_(), uriVL::DepthMap::DepthMap(), uriVL::ImageArithmetics::difference_(), uriVL::DepthMap::drawDenseMesh_(), uriVL::ElevationMap::ElevationMap(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findAllBlobs(), uriVL::DrawableObject2D::getBottom(), uriVL::VectorField_I::getMinMax(), uriVL::VectorField_F::getMinMax(), uriVL::VectorField_I::getMinMaxX(), uriVL::VectorField_F::getMinMaxX(), uriVL::VectorField_I::getMinMaxY(), uriVL::VectorField_F::getMinMaxY(), intersection(), isContainedBy(), loadImage(), uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), overlaps(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::VectorField_I::prepareVectFieldForRendering_(), uriVL::VectorField_F::prepareVectFieldForRendering_(), uriVL::RangeMap::RangeMap(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), uriVL::VectorField_I::renderNeedles_(), uriVL::VectorField_F::renderNeedles_(), uriVL::PatternTracker2DController::scaleImage(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::LabelRaster::setValidRect(), uriVL::BlobFinder::spiralSearch_(), uriComputerVision::BackgroundRemoverTester::test1_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriComputerVision::BackgroundRemoverTester::test3_(), uriComputerVision::BackgroundRemoverTester::test4_(), uriVL::BlobTracker2D::track(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::PatternTracker2D::verticalExtend_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return lowerRight_.getY( );
 }
int ImageRect::getHeight (void) const
Returns the height of the rectangle.
Returns
height of the rectangle (pixels per column)
Definition at line 280 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, rect_, and uriVL::URIVL_Rect::top.
Referenced by uriVL::RangeMap::allocateDenseMesh_(), uriVL::LabelRaster::allocateRasters_(), uriVL::GaussianFilter_I::applyInto(), uriVL::Blob::Blob(), uriVL::DrawableObject2D::boundRectIsEmpty(), uriVL::_GraphWorld_gen::copyBinaryInto_(), uriVL::_GraphWorld_gen::copyGrayInto_(), uriVL::_GraphWorld_gen::copyInto_(), uriVL::RasterImage::copyInto_(), uriVL::_GraphWorld_gen::copyRGB24Into_(), uriVL::_GraphWorld_gen::copyRGBa32Into_(), uriVL::PatternMatcher2D_partCorr::covariance_(), createRasterImageObj(), uriVL::ColorGaussianFilter::getHeight(), uriVL::ColorImageGradient::getHeight(), uriVL::SequenceGrabber::getHeight(), uriVL::VectorOperator::getHeight(), uriVL::LabelRaster::getHeight(), uriVL::ImageOperator::getHeight(), uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage::grab(), uriVL::PatternTracker2D::grabImage_(), initializeApplication(), main(), uriVL::StereoMatcher::match(), uriVL::PatternMatcher2D::match(), uriVL::MedianFilter_F::MedianFilter_F(), uriVL::PatternMatcher2D_partCorr::patternCorrScale_(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), removeAllAround(), uriVL::DrawableObject2D::render(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::DrawableObject2D::setBoundRect(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), uriVL::DrawableObject2D::setValidRect(), uriVL::DrawableObject2D::translate(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return  rect_.bottom - rect_.top;
 }
int ImageRect::getLeft (void) const
Returns the minimum x coordinate of the rectangle.
Returns
x coordinate of the upper-left pixel
Definition at line 285 of file ImageRect.cpp.
References uriVL::ImagePoint::getX(), and upperLeft_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::RangeMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), uriVL::LabelRaster::allocateShiftedRaster2D_(), applyAdditiveNoise(), uriVL::HysteresisLabeler::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), applySaltAndPepperNoise(), uriVL::Blob::Blob(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), coincidesWith(), uriVL::Contour_I::computeCentroid_(), uriVL::Blob::computeCentroid_(), uriVL::ImageHistogram::computeFastHistogram_(), uriVL::ImageHistogram::computeFloatHistogram_(), uriVL::ImageHistogram::computeHistogram_(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::Blob::computeQuadNbPixels_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::ColorInverseThresholdLabeler::connectNeighbor_(), uriVL::ColorThresholdLabeler::connectNeighbors_(), uriVL::GrayThresholdLabeler::connectNeighbors_(), contains(), uriVL::RasterImage_HSV::convertFromGray_(), uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::RasterImage_HSV::convertToRGBa_(), uriVL::RasterImage_HSV::convertToSaturatedRGBa_(), uriVL::_GraphWorld_gen::copyBinaryInto_(), uriVL::_GraphWorld_gen::copyGrayInto_(), uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), uriVL::_GraphWorld_gen::copyRGB24Into_(), uriVL::_GraphWorld_gen::copyRGBa32Into_(), CreateImageAndField(), uriVL::DepthMap::DepthMap(), detectAllBlobs(), uriVL::ImageArithmetics::difference_(), uriVL::Blob::diskCoverage(), uriVL::DepthMap::drawDenseMesh_(), uriVL::ElevationMap::ElevationMap(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findAllBlobs(), uriVL::DrawableObject2D::getLeft(), uriVL::VectorField_I::getMinMax(), uriVL::VectorField_F::getMinMax(), uriVL::VectorField_I::getMinMaxX(), uriVL::VectorField_F::getMinMaxX(), uriVL::VectorField_I::getMinMaxY(), uriVL::VectorField_F::getMinMaxY(), intersection(), isContainedBy(), uriVL::LabelRaster::LabelRaster(), loadImage(), uriVL::PatternMatcher2D::match(), uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), overlaps(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::VectorField_I::prepareVectFieldForRendering_(), uriVL::VectorField_F::prepareVectFieldForRendering_(), uriVL::RangeMap::RangeMap(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), uriVL::DrawableObject2D::render(), uriVL::VectorField_I::renderNeedles_(), uriVL::VectorField_F::renderNeedles_(), uriVL::PatternTracker2DController::scaleImage(), uriVL::DrawableObject2D::setBoundRect(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), uriVL::DrawableObject2D::setValidRect(), uriVL::BlobFinder::spiralSearch_(), uriVL::PatternTracker2D::track(), uriVL::DrawableObject2D::translate(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), uriVL::ElevationMap::updateMesh(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), upperLeftIsAtOrigin(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::PatternTracker2D::verticalExtend_(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), uriVL::RasterImage_RGBa_F::writeInto_(), and uriVL::RectifiedStereoMatcher_JJL::~RectifiedStereoMatcher_JJL().
 {
     return upperLeft_.getX( );
 }
const URIVL_Rect * ImageRect::getRectQT_ (void) const private
Returns a reference to the private QuickTime rectangle structure of this ImageRect objet.
This function is private, with GraphWorld as sole friend class, because I can't see any reason why anyone should want to access this data except for a CopyBits.
Returns
reference to private Rect structure
Definition at line 271 of file ImageRect.cpp.
References rect_.
 {
     return &rect_;
 }
int ImageRect::getRight (void) const
Returns the maximum x coordinate of the rectangle.
Returns
x coordinate of the upper-right pixel
Definition at line 290 of file ImageRect.cpp.
References uriVL::ImagePoint::getX(), and lowerRight_.
Referenced by uriVL::RangeMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), applyAdditiveNoise(), uriVL::HysteresisLabeler::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), applySaltAndPepperNoise(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), coincidesWith(), uriVL::Contour_I::computeCentroid_(), uriVL::Blob::computeCentroid_(), uriVL::ImageHistogram::computeFastHistogram_(), uriVL::ImageHistogram::computeFloatHistogram_(), uriVL::ImageHistogram::computeHistogram_(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::Blob::computeQuadNbPixels_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::ColorInverseThresholdLabeler::connectNeighbor_(), uriVL::ColorThresholdLabeler::connectNeighbors_(), uriVL::GrayThresholdLabeler::connectNeighbors_(), contains(), uriVL::RasterImage_HSV::convertFromGray_(), uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::RasterImage_HSV::convertToRGBa_(), uriVL::RasterImage_HSV::convertToSaturatedRGBa_(), uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), CreateImageAndField(), uriVL::DepthMap::DepthMap(), uriVL::ImageArithmetics::difference_(), uriVL::Blob::diskCoverage(), uriVL::DepthMap::drawDenseMesh_(), uriVL::ElevationMap::ElevationMap(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findAllBlobs(), uriVL::VectorField_I::getMinMax(), uriVL::VectorField_F::getMinMax(), uriVL::VectorField_I::getMinMaxX(), uriVL::VectorField_F::getMinMaxX(), uriVL::VectorField_I::getMinMaxY(), uriVL::VectorField_F::getMinMaxY(), uriVL::DrawableObject2D::getRight(), intersection(), isContainedBy(), loadImage(), uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), overlaps(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::VectorField_I::prepareVectFieldForRendering_(), uriVL::VectorField_F::prepareVectFieldForRendering_(), uriVL::RangeMap::RangeMap(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::VectorField_I::renderNeedles_(), uriVL::VectorField_F::renderNeedles_(), uriVL::PatternTracker2DController::scaleImage(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), uriVL::BlobFinder::spiralSearch_(), uriComputerVision::BackgroundRemoverTester::test1_(), uriComputerVision::BackgroundRemoverTester::test21_(), uriComputerVision::BackgroundRemoverTester::test22_(), uriComputerVision::BackgroundRemoverTester::test3_(), uriComputerVision::BackgroundRemoverTester::test4_(), uriVL::BlobTracker2D::track(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), uriVL::PatternTracker2D::verticalExtend_(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), and uriVL::RasterImage_binary::writeInto_().
 {
     return lowerRight_.getX( );
 }
int ImageRect::getTop (void) const
Returns the minimum y coordinate of the rectangle.
Returns
y coordinate of the upper-left pixel
Definition at line 295 of file ImageRect.cpp.
References uriVL::ImagePoint::getY(), and upperLeft_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::RangeMap::allocateDenseMesh_(), uriVL::RasterImage_HSV24::allocateRaster2D_(), uriVL::LabelRaster::allocateShiftedRaster2D_(), applyAdditiveNoise(), uriVL::HysteresisLabeler::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto_(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ColorGaussianFilter_F::applyInto_(), uriVL::GaussianFilter_F::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_11x11_(), uriVL::ColorGaussianFilter_F::applyInto_11x11_(), uriVL::GaussianFilter_F::applyInto_11x11_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_13x13_(), uriVL::ColorGaussianFilter_F::applyInto_13x13_(), uriVL::GaussianFilter_F::applyInto_13x13_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorGaussianFilter_F::applyInto_3x3_(), uriVL::GaussianFilter_F::applyInto_3x3_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_5x5_(), uriVL::ColorGaussianFilter_F::applyInto_5x5_(), uriVL::GaussianFilter_F::applyInto_5x5_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_7x7_(), uriVL::ColorGaussianFilter_F::applyInto_7x7_(), uriVL::GaussianFilter_F::applyInto_7x7_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ImageLaplacian_Gaussian_F::applyInto_9x9_(), uriVL::ColorGaussianFilter_F::applyInto_9x9_(), uriVL::GaussianFilter_F::applyInto_9x9_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ImageLaplacian_Sobel::applyInto_form1_(), uriVL::ImageLaplacian_Sobel::applyInto_form2_(), uriVL::ImageLaplacian_Sobel::applyInto_form3_(), uriVL::NonMaximumSuppressor::applyInto_vectF_(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), uriVL::ImageGradient_Sobel::applyIntoF_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoI_(), uriVL::ImageGradient_Sobel::applyIntoI_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), applySaltAndPepperNoise(), uriVL::Blob::Blob(), uriVL::RasterImage_gray_F::calculateFloatConversionParams_(), uriVL::RasterImage_RGBa_F::calculateFloatConversionParams_(), coincidesWith(), uriVL::Contour_I::computeCentroid_(), uriVL::Blob::computeCentroid_(), uriVL::ImageHistogram::computeFastHistogram_(), uriVL::ImageHistogram::computeFloatHistogram_(), uriVL::ImageHistogram::computeHistogram_(), uriVL::RectifiedStereoMatcher_JJL::computeIntegralImage_(), uriVL::VectorField_I::computeNorm_(), uriVL::VectorField_F::computeNorm_(), uriVL::VectorField_I::computeNormAndPhase_(), uriVL::VectorField_F::computeNormAndPhase_(), uriVL::VectorField_I::computeNormSquared_(), uriVL::VectorField_F::computeNormSquared_(), uriVL::VectorField_I::computeNormSquaredAndPhase_(), uriVL::VectorField_F::computeNormSquaredAndPhase_(), uriVL::VectorField_I::computePhase_(), uriVL::VectorField_F::computePhase_(), uriVL::Blob::computeQuadNbPixels_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::ColorInverseThresholdLabeler::connectNeighbor_(), uriVL::ColorThresholdLabeler::connectNeighbors_(), uriVL::GrayThresholdLabeler::connectNeighbors_(), contains(), uriVL::RasterImage_HSV::convertFromGray_(), uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::RasterImage_HSV::convertToRGBa_(), uriVL::RasterImage_HSV::convertToSaturatedRGBa_(), uriVL::_GraphWorld_gen::copyBinaryInto_(), uriVL::_GraphWorld_gen::copyGrayInto_(), uriVL::VectorField_I::copyInto(), uriVL::VectorField_F::copyInto(), uriVL::_GraphWorld_gen::copyRGB24Into_(), uriVL::_GraphWorld_gen::copyRGBa32Into_(), CreateImageAndField(), uriVL::RasterImage_HSV24::deleteShiftedRaster2D_(), uriVL::DepthMap::DepthMap(), detectAllBlobs(), uriVL::ImageArithmetics::difference_(), uriVL::DepthMap::drawDenseMesh_(), uriVL::ElevationMap::ElevationMap(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findAllBlobs(), uriVL::VectorField_I::getMinMax(), uriVL::VectorField_F::getMinMax(), uriVL::VectorField_I::getMinMaxX(), uriVL::VectorField_F::getMinMaxX(), uriVL::VectorField_I::getMinMaxY(), uriVL::VectorField_F::getMinMaxY(), uriVL::DrawableObject2D::getTop(), intersection(), isContainedBy(), uriVL::LabelRaster::LabelRaster(), loadImage(), uriVL::PatternMatcher2D::match(), uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_partCorr::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), overlaps(), uriVL::Pattern2D::Pattern2D(), uriVL::PatternTracker2D::PatternTracker2D(), uriVL::VectorField_I::prepareVectFieldForRendering_(), uriVL::VectorField_F::prepareVectFieldForRendering_(), uriVL::RangeMap::RangeMap(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), uriVL::DrawableObject2D::render(), uriVL::VectorField_I::renderNeedles_(), uriVL::VectorField_F::renderNeedles_(), uriVL::PatternTracker2DController::scaleImage(), uriVL::DrawableObject2D::setBoundRect(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), uriVL::DrawableObject2D::setValidRect(), uriVL::BlobFinder::spiralSearch_(), uriVL::BlobTracker2D::track(), uriVL::PatternTracker2D::track(), uriVL::DrawableObject2D::translate(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), uriVL::DepthMap::updateMesh(), uriVL::RangeMap::updateMesh(), uriVL::ElevationMap::updateMesh(), uriVL::RasterImage_gray_F::updateRaster_(), uriVL::RasterImage_binary::updateRaster_(), uriVL::RasterImage_RGBa_F::updateRaster_(), upperLeftIsAtOrigin(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::PatternTracker2D::verticalExtend_(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), uriVL::RasterImage_RGBa_F::writeInto_(), and uriVL::RectifiedStereoMatcher_JJL::~RectifiedStereoMatcher_JJL().
 {
     return upperLeft_.getY( );
 }
const ImagePoint * ImageRect::getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
Returns
coordinates of the upper left corner
Definition at line 305 of file ImageRect.cpp.
References upperLeft_.
Referenced by uriVL::DrawableObject2D::getUpperLeft().
 {
         return &upperLeft_;
 }
int ImageRect::getWidth (void) const
Returns the width of the rectangle.
Returns
width of the rectangle (pixels per row)
Definition at line 276 of file ImageRect.cpp.
References uriVL::URIVL_Rect::left, rect_, and uriVL::URIVL_Rect::right.
Referenced by uriVL::RangeMap::allocateDenseMesh_(), uriVL::LabelRaster::allocateRasters_(), uriVL::GaussianFilter_I::applyInto(), uriVL::DrawableObject2D::boundRectIsEmpty(), uriVL::_GraphWorld_gen::copyBinaryInto_(), uriVL::_GraphWorld_gen::copyGrayInto_(), uriVL::_GraphWorld_gen::copyInto_(), uriVL::RasterImage::copyInto_(), uriVL::_GraphWorld_gen::copyRGB24Into_(), uriVL::_GraphWorld_gen::copyRGBa32Into_(), uriVL::PatternMatcher2D_partCorr::covariance_(), createRasterImageObj(), uriVL::ColorGaussianFilter::getWidth(), uriVL::ColorImageGradient::getWidth(), uriVL::SequenceGrabber::getWidth(), uriVL::VectorOperator::getWidth(), uriVL::ImageOperator::getWidth(), uriVL::LabelRaster::getWidth(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::grab(), uriVL::PatternTracker2D::grabImage_(), initializeApplication(), main(), uriVL::StereoMatcher::match(), uriVL::PatternMatcher2D::match(), uriVL::MedianFilter_F::MedianFilter_F(), uriVL::PatternMatcher2D_partCorr::patternCorrScale_(), uriVL::RasterImage_aRGB16::RasterImage_aRGB16(), uriVL::RasterImage_binary::RasterImage_binary(), uriVL::RasterImage_gray::RasterImage_gray(), uriVL::RasterImage_gray_F::RasterImage_gray_F(), uriVL::RasterImage_HSV::RasterImage_HSV(), uriVL::RasterImage_RGB::RasterImage_RGB(), uriVL::RasterImage_RGBa::RasterImage_RGBa(), uriVL::RasterImage_RGBa_F::RasterImage_RGBa_F(), uriVL::RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL(), removeAllAround(), uriVL::DrawableObject2D::render(), uriVL::BackgroundRemover_dynamic_MW::setBackground_(), uriVL::DrawableObject2D::setBoundRect(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), uriVL::DrawableObject2D::setValidRect(), uriVL::DrawableObject2D::translate(), uriVL::VectorField_F::VectorField_F(), uriVL::VectorField_I::VectorField_I(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return rect_.right - rect_.left;
 }
ImageRect * ImageRect::intersection (const ImageRect * rect1, const ImageRect * rect2) static
Returns the intersection of the two rectangles received as parameters.
Parameters
rect1 first input rectangle
rect2 second input rectangle
Returns
new rectangle = intersection of rect1 and rect2
Definition at line 458 of file ImageRect.cpp.
References FAIL_CONDITION, getBottom(), getLeft(), getRight(), getTop(), ImageRect(), uriVL::kNullRectangleError, and overlaps().
Referenced by uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::MedianFilter_F::applyInto(), uriVL::MedianFilter_I::applyInto(), uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::GaussianFilter_I::applyInto(), uriVL::ColorGaussianFilter_I::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::NormalFlowCalculator::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::EdgeDetector_Canny_F::applyTo(), uriVL::ColorImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_F::applyTo(), uriVL::ImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_I::applyTo(), uriVL::ImageLaplacian_Sobel::applyTo(), uriVL::GaussianFilter_F::applyTo(), uriVL::ColorGaussianFilter_F::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::ColorGaussianFilter_I::applyTo(), uriVL::ColorImageGradient_Gaussian_F::applyTo(), uriVL::ImageGradient_Gaussian_F::applyTo(), uriVL::NonMaximumSuppressor::applyTo_st(), uriVL::VectorField::copyInto(), uriVL::RasterImage_aRGB16::copyInto(), uriVL::RasterImage_RGB::copyInto(), uriVL::RasterImage_gray::copyInto(), uriVL::RasterImage_RGBa::copyInto(), uriVL::RasterImage_binary::copyInto(), uriVL::RasterImage::copyInto_(), uriVL::ImageArithmetics::difference(), uriVL::BlobFinder::findAllBlobs(), uriVL::BlobFinder::findBlobAbout(), uriVL::ImageHistogram::ImageHistogram(), uriVL::ImageHistogram::setImage(), uriVL::ZeroCrossingDetector::showSignAsColor(), and uriVL::RasterImage::writeInto().
 {
     FAIL_CONDITION( rect1 == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::intersection");
     FAIL_CONDITION( rect2 == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::intersection");
     ImageRect* inter = NULL;
     //  if the rectangles don't overlap, we return NULL
     if (rect1->overlaps(rect2))
     {
         const int       xMin1 = rect1->getLeft(),
                                         xMax1 = rect1->getRight(),
                                         yMin1 = rect1->getTop(),
                                         yMax1 = rect1->getBottom();
         const int       xMin2 = rect2->getLeft(),
                                         xMax2 = rect2->getRight(),
                                         yMin2 = rect2->getTop(),
                                         yMax2 = rect2->getBottom();
                 const int xMin = xMin1 > xMin2 ? xMin1 : xMin2;
                 const int yMin = yMin1 > yMin2 ? yMin1 : yMin2;
                 const int w = xMax1 > xMax2 ? xMax2 - xMin + 1: xMax1 - xMin + 1;
                 const int h = yMax1 > yMax2 ? yMax2 - yMin + 1: yMax1 - yMin +1;
         inter = new ImageRect(xMin, yMin, w, h);
     }
     return inter;
 }
bool ImageRect::isContainedBy (const ImageRect * theRect) const
Indicates whether this rectangle is contained by the one received as parameter.
Parameters
theRect the rectangle to test agains this rectangle
Returns
true if theRect contains this rectangle, false otherwise
Definition at line 383 of file ImageRect.cpp.
References FAIL_CONDITION, getBottom(), getLeft(), getRight(), getTop(), and uriVL::kNullRectangleError.
Referenced by uriVL::LabelRaster::isContainedBy(), and uriVL::DrawableObject2D::isContainedBy().
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::isContainedBy");
     return  (theRect->getTop() <= getTop()) &&
             (theRect->getLeft() <= getLeft()) &&
             (theRect->getBottom() >= getBottom()) &&
             (theRect->getRight() >= getRight());
 }
bool ImageRect::isContainedBy (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle is contained by the one received as parameter.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Returns
true if theRect contains this rectangle, false otherwise
Definition at line 395 of file ImageRect.cpp.
References getBottom(), getLeft(), getRight(), and getTop().
 {
     return  (theTop <= getTop()) &&
             (theLeft <= getLeft()) &&
             (theTop + theHeight >= getBottom()) &&
             (theLeft + theWidth >= getRight());
 }
const ImageRect & ImageRect::operator= (const ImageRect & theRect)
Equal operator.
Mostly defined so that gcc will stop bugging me about it.
Parameters
theRect reference to ImageRect object to copy
Definition at line 171 of file ImageRect.cpp.
References lowerRight_, rect_, uriVL::ImagePoint::setCoordinates(), and upperLeft_.
 {
         rect_ = theRect.rect_;
         upperLeft_.setCoordinates(theRect.upperLeft_);
         lowerRight_.setCoordinates(theRect.lowerRight_);
         return *this;
 }
bool ImageRect::overlaps (const ImageRect * theRect) const
Indicates whether this rectangle and the one received as parameter overlap.
Parameters
theRect the rectangle to test agains this rectangle
Returns
true if the two rectangles overlap, false otherwise
Definition at line 338 of file ImageRect.cpp.
References FAIL_CONDITION, getBottom(), getLeft(), getRight(), getTop(), and uriVL::kNullRectangleError.
Referenced by intersection(), uriVL::DrawableObject2D::overlaps(), and uriVL::LabelRaster::overlaps().
 {
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageRect::overlaps");
     return !(
                (theRect->getBottom() < getTop())   ||    //  completely above
                (theRect->getTop() > getBottom())   ||    //  completely below
                (theRect->getRight() < getLeft())   ||    //  completely to the left
                (theRect->getLeft() > getRight())         //  completely to the right
            );
 }
bool ImageRect::overlaps (int theLeft, int theTop, int theWidth, int theHeight) const
Indicates whether this rectangle and the one received as parameter overlap.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Returns
true if the two rectangles overlap, false otherwise
Definition at line 352 of file ImageRect.cpp.
References getBottom(), getLeft(), getRight(), and getTop().
 {
     return !(
                (theTop + theHeight < getTop())   ||    //  completely above
                (theTop > getBottom())   ||    //  completely below
                (theLeft + theWidth < getLeft())   ||    //  completely to the left
                (theLeft > getRight())         //  completely to the right
            );
 }
void ImageRect::removeAllAround (int n)
Removes n elements all around the rectangle.
After this operation, the rowHigh and colHigh have been decremented by n while the rowLow and colLow have been incremented by n. The operation fails (throws an exception) if either dimension of the resized rectangle is negative.
Parameters
n amount to add all around
Definition at line 442 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, FAIL_CONDITION, getHeight(), getWidth(), uriVL::kInvalidRectangleError, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
Referenced by uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageGradient_Sobel::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), uriVL::GaussianFilter_F::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::NonMaximumSuppressor::applyInto_st(), uriVL::ColorImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_F::applyTo(), uriVL::ImageGradient_Sobel::applyTo(), uriVL::ImageLaplacian_Gaussian_I::applyTo(), uriVL::ImageLaplacian_Sobel::applyTo(), uriVL::GaussianFilter_F::applyTo(), uriVL::ColorGaussianFilter_F::applyTo(), uriVL::ColorGaussianFilter_I::applyTo(), uriVL::GaussianFilter_I::applyTo(), uriVL::ColorImageGradient_Gaussian_F::applyTo(), and uriVL::ImageGradient_Gaussian_F::applyTo().
 {
     FAIL_CONDITION( (getWidth() <= 2*n) || (getHeight() <= 2*n),
                     kInvalidRectangleError,
                     "attempt to remove too much from an ImageRect");
     rect_.left += n;
     rect_.top += n;
     rect_.right -= n;
     rect_.bottom -= n;
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
void ImageRect::setCenter (int cX, int cY)
Sets the center of the rectangle.
The rectangle's width and height are preserved but it is translated so that its center is at the coordinates indicated. The rectangle's upper-left corner is moved to (cx - width/2, cy - height/2)
Parameters
cX new x coordinate of the rectangle's center
cY new y coordinate of the rectangle's center
Definition at line 193 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setX(), uriVL::ImagePoint::setY(), uriVL::URIVL_Rect::top, and upperLeft_.
 {
         const int myWidth = rect_.right - rect_.left;
         const int myHeight = rect_.bottom - rect_.top;
     rect_.left = static_cast<short>(cX - myWidth/2);
     rect_.right = static_cast<short>(rect_.left + myWidth);
     rect_.top = static_cast<short>(cY - myHeight/2);
     rect_.bottom += static_cast<short>(rect_.top + myHeight);
     upperLeft_.setX(rect_.left);
     upperLeft_.setY(rect_.top);
     lowerRight_.setX(rect_.right - 1);
     lowerRight_.setY(rect_.bottom - 1);
 }
void ImageRect::setOrigin (int x, int y)
Sets the origin of the rectangle.
A move-to operation.
Parameters
x new x coordinate asigned to the upper-left pixel
y new y coordinate asigned to the upper-left pixel
Definition at line 181 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
Referenced by uriVL::RectifiedStereoMatcher_corr::match_(), and uriVL::LabelRaster::setOrigin().
 {
     rect_.right += static_cast<short>(x - rect_.left);
     rect_.left = static_cast<short>(x);
     rect_.bottom += static_cast<short>(y - rect_.top);
     rect_.top = static_cast<short>(y);
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
void ImageRect::setRect (const ImageRect * theRect)
Sets the origin and size of the rectangle.
Parameters
theRect ImageRect object to copy the information from
Definition at line 223 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
Referenced by uriVL::Contour_F::computeBoundingRect_(), uriVL::ContourForce::computeBoundingRect_(), uriVL::Contour_I::computeBoundingRect_(), uriVL::Histogram::computeBoundingRect_(), uriVL::Blob::computeBoundingRect_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::Contour_F::computeValidRect_(), uriVL::ContourForce::computeValidRect_(), uriVL::Contour_I::computeValidRect_(), uriVL::Histogram::computeValidRect_(), uriVL::Blob::computeValidRect_(), CreateImageAndField(), uriVL::PatternTracker2D::grabImage_(), handleMouseDrag(), loadImages(), uriVL::DrawableObject2D::setBoundRect(), uriVL::VectorOperator::setRect(), uriVL::ImageOperator::setRect(), uriVL::LabelRaster::setRect(), uriVL::LabelRaster::setValidRect(), and uriVL::DrawableObject2D::setValidRect().
 {
     rect_.left = theRect->rect_.left;
     rect_.top = theRect->rect_.top;
     rect_.right = theRect->rect_.right;
     rect_.bottom = theRect->rect_.bottom;
 //    upperLeft_ = new ImagePoint(theRect->upperLeft_);
 //    lowerRight_ = new ImagePoint(theRect->lowerRight_);
         upperLeft_.setCoordinates(rect_.left, rect_.top);
         lowerRight_.setCoordinates(rect_.right-1, rect_.bottom - 1);
 }
void ImageRect::setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the origin and size of the rectangle.
Parameters
left new x coordinate asigned to the upper-left pixel
top new y coordinate asigned to the upper-left pixel
width new width asigned to the rectangular
height new height asigned to the rectangular
Definition at line 236 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
 {
     rect_.left = static_cast<short>(theLeft);
     rect_.top = static_cast<short>(theTop);
 //    upperLeft_ = new ImagePoint(rect_.left, rect_.top);
     rect_.right = static_cast<short>(rect_.left + theWidth);
     rect_.bottom = static_cast<short>(rect_.top + theHeight);
 //    lowerRight_ = new ImagePoint(rect_.right - 1, rect_.bottom - 1);
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
void ImageRect::setRect (const ImagePoint * topLeft, const ImagePoint * bottomRight)
Sets the origin and size of the rectangle.
Parameters
topLeft new ImagePoint asigned to the upper-left pixel
bottomRight new ImagePoint asigned to the bottom-right pixel
Definition at line 252 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
 {
     rect_.left = static_cast<short>(topLeft->getX());
     rect_.top = static_cast<short>(topLeft->getY());
     rect_.right = static_cast<short>(bottomRight->getX());
     rect_.bottom = static_cast<short>(bottomRight->getY());
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
void uriVL::ImageRect::setRect (const ImagePoint * topLeft, int theWidth, int theHeight)
Sets the origin and size of the rectangle.
Parameters
topLeft new ImagePoint asigned to the upper-left pixel
width new width asigned to the rectangular
height new height asigned to the rectangular
void ImageRect::translate (int dx, int dy)
Sets the origin of the rectangle.
A move-by operation.
Parameters
dx x displacement asigned to the upper-left pixel
dy y displacement asigned to the upper-left pixel
Definition at line 211 of file ImageRect.cpp.
References uriVL::URIVL_Rect::bottom, uriVL::URIVL_Rect::left, lowerRight_, rect_, uriVL::URIVL_Rect::right, uriVL::ImagePoint::setCoordinates(), uriVL::URIVL_Rect::top, and upperLeft_.
Referenced by uriVL::LabelRaster::setRect(), uriVL::LabelRaster::translate(), uriVL::DrawableObject2D::translate(), and uriVL::RasterImage::writeInto().
 {
     rect_.right += dx;
     rect_.left += dx;
     rect_.bottom += dy;
     rect_.top += dy;
     upperLeft_.setCoordinates(rect_.left, rect_.top);
     lowerRight_.setCoordinates(rect_.right - 1, rect_.bottom - 1);
 }
bool ImageRect::upperLeftIsAtOrigin (void) const
Indicates whether this rectangle has its upper left corner at (0, 0)
Returns
true if this rectangle has its upper left corner at (0, 0)
Definition at line 419 of file ImageRect.cpp.
References getLeft(), and getTop().
Referenced by uriVL::LabelRaster::allocateShiftedRaster2D_(), uriVL::RasterImage_HSV24::getShiftedHue2D(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::RasterImage_HSV24::getShiftedSat2D(), and uriVL::RasterImage_HSV24::getShiftedVal2D().
 {
     return (getTop() == 0) && (getLeft() == 0);
 }
Friends And Related Function Documentation
friend class _GraphWorld_gen friend
Definition at line 422 of file ImageRect.h.
friend class GraphWorld friend
Definition at line 418 of file ImageRect.h.
Member Data Documentation
ImagePoint uriVL::ImageRect::lowerRight_ private
Lower-right point of the rectangle.
Redundant information, using the pixel-as-point convention.
Definition at line 406 of file ImageRect.h.
Referenced by addAllAround(), getBottom(), getRight(), ImageRect(), operator=(), removeAllAround(), setCenter(), setOrigin(), setRect(), and translate().
URIVL_Rect uriVL::ImageRect::rect_ private
QuickTime rectangle.
Underlying QuickTime rectangle, using the pixel-as-rectangle convention.
Definition at line 393 of file ImageRect.h.
Referenced by addAllAround(), getHeight(), getRectQT_(), getWidth(), ImageRect(), operator=(), removeAllAround(), setCenter(), setOrigin(), setRect(), and translate().
ImagePoint uriVL::ImageRect::upperLeft_ private
Upper-left point of the rectangle.
Redundant information, using the pixel-as-point convention.
Definition at line 399 of file ImageRect.h.
Referenced by addAllAround(), getLeft(), getTop(), getUpperLeft(), operator=(), removeAllAround(), setCenter(), setOrigin(), setRect(), and translate().
The documentation for this class was generated from the following files:
ImageRect.h
ImageRect.cpp