URIVisionLibrary: uriVL::ActiveContourDetector_balloon Class Reference
uriVL::ActiveContourDetector_balloon Class Reference
A Function Class which searches for a closed contour in a given image by applying the "balloon" active contour algorithm of L.
#include <ActiveContourDetector_balloon.h>
Public Member Functions
ActiveContourDetector_balloon (BalloonType type, const ImageRect *imgRect, ConvergenceCriterion crit, float tol, float internalCoeff, float edgeCoeff, float shrinkCoeff, float timeStep=DEFAULT_TIME_STEP)
Constructor.
~ActiveContourDetector_balloon (void)
Destructor.
void setCoeffs (float internalCoeff, float edgeCoeff, float shrinkCoeff)
Sets the coefficients of the detector's various force components.
void setImageProperties (VectorField_F *grad, RasterImage_gray_F *normSqrd, VectorField_F *gradNormSqrd, Contour_F *contourOut)
This function should be called for video-rate applications that must re-use the same rasters for performance optimization purposes.
IterationStatus findContour (const RasterImage *imgIn, Contour_F *contour)
Finds a contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
IterationStatus findContour (VectorField_F *grad, RasterImage_gray_F *normSqrd, VectorField_F *gradNormSqrd, Contour_F *contour)
Finds a contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
void renderForces (void)
Renders the different forces that compose the balloon total force.
Public Member Functions inherited from uriVL::ActiveContourDetector
ActiveContourDetector (const ImageRect *imgInRect=NULL)
Constructor.
virtual ~ActiveContourDetector (void)
Destructor.
virtual IterationStatus findContour (const RasterImage *imgIn, Contour_F *contour, const ImageRect *searchRect=NULL)=0
Finds one contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
std::list< Contour_F * > * findAllContours (const RasterImage *imgIn, const ImageRect *rect=NULL)
Finds all contours within the specified search rectangle of the input image.
const Contour_F * getContour (void) const
Returns a read-only pointer to the contour being computed (when operating in step-by-step mode).
IterationStatus getStatus (void) const
Returns the current iteration status without computing an iteration step.
void setStepByStep (bool sbs)
Allows the user to change the mode in which the detector operate: "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
void setStepSize (int size)
When in step-by-step mode, sets the number of iterations run at each "step".
IterationStatus iterate (int n)
Aplies n iterations of the algorithm (or fewer if convergence occurs before).
bool gradientsAreLocal (void) const
Reports whether this object "owns" the various gradient rasters and vector fields and should delete them in the destructor.
float getTimeStep (void) const
Returns the value of the "time step" that scales the total force to produce a displacement.
Public Member Functions inherited from uriVL::ContourDetector
ContourDetector (void)
Constructor.
ContourDetector (const ImageRect *rect)
Constructor.
virtual ~ContourDetector (void)
Destructor.
virtual Contour_F * findContour (const RasterImage *imgIn, const ImageRect *rect=NULL)=0
Finds one contour within the specified search rectangle of the input image.
Public Member Functions inherited from uriVL::FeatureDetector
FeatureDetector (void)
Constructor.
FeatureDetector (const ImageRect *rect)
Constructor.
virtual ~FeatureDetector (void)
Destructor.
const ImageRect * getSearchRect (void) const
Returns a pointer to the ImageRect on which this object is operating.
void setSearchRect (const ImageRect *rect)
Assigns a (new) search rectangle to this object.
virtual ImageFeature * findFeatureAbout (const RasterImage *img, const ImagePoint *searchStart, const ImageRect *searchRect=NULL)=0
Find one image feature near the designated point.
virtual FeatureList * findAllFeatures (const RasterImage *img, const ImageRect *searchRect=NULL)=0
Find all image feature within a search rectangle.
Private Member Functions
ActiveContourDetector_balloon (const ActiveContourDetector_balloon &obj)
Copy constructor (disabled)
const ActiveContourDetector_balloon & operator= (const ActiveContourDetector_balloon &obj)
Copy operator: disabled.
const IterationStatus findContour_ (void)
Depending on the value of step.
void searchAndInsertPoints_ (Contour_F *contour, const RasterImage_gray_F *normSqrdOfGrad)
Uses bresenham's alg to calculate all the points in between each contour pt and inserts a new point if an edge is found beyond a certain threshold.
void calculateEdgeForce_ (Contour_F *contour, const VectorField_F *gradNorm2, ContourForce *edge)
Calculate the edge force for each pt on the contour.
void calculateShrinkForce_ (Contour_F *contourIn, ContourForce *shrink)
Calculate the shrink force for each pt on the contour.
void initializeContour_ (Contour_F *contour)
Set up the contour equaly spacing them around the image.
IterationStatus oneStep_ (void)
Applies one iteration of the balloon algorithm.
void transToBresenhamSpace_ (int &dx, int &dy, int x[], int y[], int &octant, bool &swapped0F)
Attempts to find an edge by going a fixed distance from a a particular point.
void transFromBresenhamSpace_ (int &xVal, int &yVal, int octant)
This is a private helper method designed to facilitate using our modified Bresenham's Algorithm to transform the computed point from the space of the Bresenham's Algorithm to its appropriate reflection about the various axes.
void swapXY_ (int x[], int y[])
Swaps the values of X-pairs and Y-pairs (x0,x1)->(y0,y1)
void swapXY_ (int &x, int &y)
Swaps the values of X and Y.
void swap0F_ (int x[], int y[])
Inverts the Y-pair vaules (y0,y1)->(-y0,-y1)
Private Attributes
ContourForce * edgeForce_
Force that attracts the contour to the closest/strongest edge.
ContourForce * shrinkForce_
Force that makes the balloon contract/expand.
VectorField_F * gradOfNormSqrdOfGrad_
Stores the gradient of norm squared of gradient of the image being operated on.
float edgeCoeff_
Coefficient of the "edge force" in the total force computation.
float shrinkCoeff_
Coefficient of the "expand/contract force" in the total force computation.
Additional Inherited Members
Protected Member Functions inherited from uriVL::ActiveContourDetector
void calculateInternalForce_ (void)
Calculates the internal force that preserves the quality of the contour (points regularly spread out on the contour, minimization of curvature)
void setInternalCoeff_ (float internalCoeff)
Called by a subclass to set the coeefficient of the internal force in the computation of the total force.
void setGradientRasters_ (VectorField_F *grad, RasterImage_gray_F *normSqrd)
This function should be called for video-rate applications that must re-use the same rasters for performance optimization purposes.
void setContour_ (Contour_F *contour)
Assigns a contour object, typically, to start an iteration.
Contour_F * getContour_ (ReadWriteStatus rw)
Returns a writable pointer to the contour force's geometric contour (list of points)
ActiveContourDetector (const ActiveContourDetector &obj)
Copy constructor (disabled)
const ActiveContourDetector & operator= (const ActiveContourDetector &obj)
Copy operator: disabled.
Protected Attributes inherited from uriVL::ActiveContourDetector
VectorField_F * imageGradient_
Stores the gradient of the image being operated on.
RasterImage_gray_F * normSqrdOfGrad_
Stores as a gray-level image the norm squared of gradient of the image being operated on.
ColorImageGradient_Gaussian_F * colorImageGradientProcessor_
Used when processing a color image.
ImageGradient_Gaussian_F * grayImageGradientProcessor_
Used when processing a gray-level image.
Contour_F * contour_
Pointer to the Contour_F object being worked on by this object.
ContourForce * totalForce_
Sum of all forces applied to each vertex of the active contour.
ContourForce * internalForce_
Internal, "goodness" component of the force applied to each vertex of the active contour.
IterationStatus status_
Status of the current iteration.
float internalCoeff_
Coefficient of the internal force in the computation of the total force.
float gaussianGradientScale_
Scale of the gradient of Gaussian.
float alphaFirstDeriv_
Energy contributed by the distance between control points to the internal force.
float betaSecondDeriv_
Energy contributed by the curvature of the snake to the internal force.
float maxInternalForce_
Maximimum magnitude of the internal force.
float timeStep_
Time "step" in the integration of the differential equation.
float tolerance_
Convergence threshold, for whatever convergence criterion is being used.
int nbIterations_
Number of iterations done so far.
bool gradientsAreLocal_
Indicates whether the contour detector allocated its own gradient, norm of gradient, etc.
bool stepByStep_
Indicates whether the contour detector operates in "discrete" mode (n steps at a time) or "full" mode (runs to convergence or max number iterations).
int stepSize_
How many integration steps to apply when in "step-by"step" mode.
bool setupCompleted_
True after the detector has run at least one iteration step, so that the iterate function can be called to iterate one or more steps.
Static Protected Attributes inherited from uriVL::ActiveContourDetector
static const float DEFAULT_GAUSSIAN_FILTER_SCALE = 2.0f
Default scale of the gradient of Gaussian.
static const float DEFAULT_MAX_INTERNAL_FORCE = 5.1f
Default value for the maximimum magnitude of the internal force.
static const float DEFAULT_INTERNAL_COEFF = 1.f
Default value for the internal force coefficient.
static const float DEFAULT_TIME_STEP = 0.15f
Default time step in the iteration equation, arbitrarily set.
static const float DEFAULT_TOLERANCE = (float)1E-5
Default time step in the iteration equation, arbitrarily set.
static const float DEFAULT_ALPHA_1ST_DERIV = 4.f
Default value for the energy contributed by the distance between control points.
static const float DEFAULT_BETA_2ND_DERIV = 0.1f
Default value for the energy contributed by the curvature of the snake.
Detailed Description
A Function Class which searches for a closed contour in a given image by applying the "balloon" active contour algorithm of L.
Cohen. The balloon's vertices are connected by linear splines.
Author
Clifford Manzanillo, Department of Computer Science and Statistics, URI
Chris Allen, 3DG, URI [major revision 2009]
jyh, 3DG, URI [major uriVL overhaul 2013]
Definition at line 57 of file ActiveContourDetector_balloon.h.
Constructor & Destructor Documentation
ActiveContourDetector_balloon::ActiveContourDetector_balloon (BalloonType type, const ImageRect * imgRect, ConvergenceCriterion crit, float tol, float internalCoeff, float edgeCoeff, float shrinkCoeff, float timeStep = DEFAULT_TIME_STEP)
Constructor.
Parameters
nbContourPts initial number of points on a new contour
imgRect the rectangle to work within
edgeCoeff coefficient of the edge force in total force calculation
shrinkCoeff coefficient of the shrink/inflate force in total force calculation
tol tolerance of the search
timeStep the "time step" of the active contour searchConstructor.
type does the balloon expand or contract?
imgRect the rectangle to work within
crit what convergence criterion
tol tolerance of the search
edgeCoeff coefficient of the edge force in total force calculation
shrinkCoeff coefficient of the shrink/inflate force in total force calculation
timeStep the "time step" of the active contour search
Definition at line 38 of file ActiveContourDetector_balloon.cpp.
References EDGE_FORCE_DEFAULT_COLOR, edgeForce_, uriVL::ContourForce::setNeedleColor(), SHRINK_FORCE_DEFAULT_COLOR, and shrinkForce_.
                                         :       ActiveContourDetector(imgRect),
                                                 //
                                                 edgeForce_(new ContourForce()),
                                                 shrinkForce_(new ContourForce()),
                                                 gradOfNormSqrdOfGrad_(NULL),
                                                 //
                                                 edgeCoeff_(edgeCoeff),
                                                 shrinkCoeff_(shrinkCoeff)
 {
         shrinkForce_->setNeedleColor(SHRINK_FORCE_DEFAULT_COLOR);
         edgeForce_->setNeedleColor(EDGE_FORCE_DEFAULT_COLOR);
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ActiveContourDetector_balloon constructor.");
         throw e;
 }
 catch(...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid parameters sent to ActiveContourDetector_balloon constructor.");
 }
ActiveContourDetector_balloon::~ActiveContourDetector_balloon (void)
Destructor.
Definition at line 82 of file ActiveContourDetector_balloon.cpp.
References edgeForce_, uriVL::ActiveContourDetector::gradientsAreLocal(), gradOfNormSqrdOfGrad_, and shrinkForce_.
{
         delete edgeForce_;
         delete shrinkForce_;
         //      only delete the gradient objects if they are local
         if (gradientsAreLocal())
         {
                 if (gradOfNormSqrdOfGrad_)
                         delete gradOfNormSqrdOfGrad_;
         }
 }
ActiveContourDetector_balloon::ActiveContourDetector_balloon (const ActiveContourDetector_balloon & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 66 of file ActiveContourDetector_balloon.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ActiveContourDetector(),
                                 //
                                 edgeForce_(NULL),
                                 shrinkForce_(NULL),
                                 gradOfNormSqrdOfGrad_(NULL),
                                 //
                                 edgeCoeff_(0.f),
                                 shrinkCoeff_(0.f)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ActiveContourDetector_balloon copy constructor not implemented.");
 }
Member Function Documentation
void ActiveContourDetector_balloon::calculateEdgeForce_ (Contour_F * contour, const VectorField_F * gradNorm2, ContourForce * edge) private
Calculate the edge force for each pt on the contour.
Parameters
vectorfield which is the normSquaredOfTheGrad
contour
contourforce
Definition at line 399 of file ActiveContourDetector_balloon.cpp.
References edgeCoeff_, uriVL::ContourForce::getForce(), uriVL::Contour_F::getPoints(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::ActiveContourDetector::getTimeStep(), MIN_DIST_BTWN_PTS, and uriVL::R_W_ACCESS.
Referenced by oneStep_().
 {
         const float TIMESTEP_MULT_EDGE_COEFF = edgeCoeff_ * getTimeStep();
         const float NORM_SQRD_TOL = 250.f;
         //gradient of image gradient magnitude at integer and non-integer position
         const float *const* dPx = (const float *const*) gradNorm2->getShiftedRasterX2D();
         const float *const* dPy = (const float *const*) gradNorm2->getShiftedRasterY2D();
         list <ImagePoint_F*>* contourList = contourIn->getPoints(R_W_ACCESS);
         const list <Vector2D_F*>* edgeForceList = edgeForce->getForce();
         list<Vector2D_F*>::const_iterator       iterE = edgeForceList->begin(),
                                                                                 iterE2 = edgeForceList->begin();
         list<ImagePoint_F*>::iterator   iter2 = contourList->begin(),
                                                                         iterTemp = contourList->begin();
         list<ImagePoint_F*>::const_iterator     endContourList = contourList->end();
         for(list<ImagePoint_F*>::iterator iter = contourList->begin(); iter != endContourList; iter++, iterE++)
         {
                 //rename x and y to IroundedDown, JroundedDown
                 int     j = int((*iter)->getX()),
                         i = int((*iter)->getY()),
                         iPlus1 = i + 1,
                         jPlus1 = j + 1;
                 float   a = (*iter)->getX() - j,
                                 b = (*iter)->getY() - i;
                 //if points are at the non-filtered positions,edge force is zero
                 //bilinear interpolation
                 float   tempAlpha = dPx[i][j],
                                 tempBeta = dPx[iPlus1][j],
                                 tempGamma = dPx[i][jPlus1],
                                 tempDelta = dPx[iPlus1][jPlus1],
                                 tempBetaMinusAlpha = tempBeta - tempAlpha;
                 float fx = tempAlpha + ((tempGamma - tempAlpha) * a) + (tempBetaMinusAlpha * b)
                                                          + ((tempDelta - tempGamma - tempBetaMinusAlpha) * a * b);
                 tempAlpha = dPy[i][j];
                 tempBeta = dPy[iPlus1][j];
                 tempGamma = dPy[i][jPlus1];
                 tempDelta = dPy[iPlus1][jPlus1];
                 tempBetaMinusAlpha = tempBeta - tempAlpha;
                 float fy = tempAlpha + ((tempGamma - tempAlpha) * a) + (tempBetaMinusAlpha * b)
                                                          + ((tempDelta - tempGamma - tempBetaMinusAlpha) * a * b);
                 //if edge force is greater than smallest float value, get it
                 //otherwise, set it to zero
                 float normSquared = fx*fx + fy*fy;
                 if(normSquared > NORM_SQRD_TOL)
                 {
                         float norm = sqrtf(normSquared);
                         (*iterE)->setX((fx/norm) * TIMESTEP_MULT_EDGE_COEFF);
                         (*iterE)->setY((fy/norm) * TIMESTEP_MULT_EDGE_COEFF);
                 }
                 else
                 {
                         (*iterE)->setX(0.f);
                         (*iterE)->setY(0.f);
                 }
                 iter2 = iter;
                 iter2++;
                 bool done = false;
 //              bool swapped = false;
                 while (!done)
                 {
                         if (iter2 == endContourList)
{
                                 iter2 = contourList->begin();
                         //      swapped = true;
                         }
                         if (iter2 == iter)
{
                                 done = true;
                                 break;
                         }
 //                      int iter2_x = (*iter2)->getX(),
 //                              iter2_y = (*iter2)->getY();
                         float   deltaX = (*iter2)->getX() - (*iter)->getX(),
                                         deltaY = (*iter2)->getY() - (*iter)->getY();
                         float diff = sqrtf(deltaX*deltaX + deltaY*deltaY);
                         if (diff < MIN_DIST_BTWN_PTS)
{
                                 contourList->erase(iter2++);
                         }
                         else
{
                                 //if (diff < MIN_DIST_BTWN_PTS*2)
 //                              {
 //                                      int swap = 0;
 //                                      for (iterTemp = iter; iterTemp != iter2; iterTemp++)
 //                                      {
 //                                              swap++;
 //                                      }
 //
 //                                      if (swap >= contourList->size()/2)
 //                                      {
 //                                              swapped = true;
 //                                      }
 //
 //                                      if (!swapped)
 //                                      {
 //
 //                                              iterTemp = iter;
 //                                              iterTemp++;
 //                                              while (iterTemp != iter2)
 //                                              {
 //                                                      contourList->erase(iterTemp++);
 //                                              }
 ////                                            iterTemp++;
 ////                                            contourList->erase(iterTemp,iter2++);
 //                                      } else {
 //                                              iterTemp = iter2;
 //                                              iterTemp++;
 //                                              while(iterTemp != iter)
 //                                              {
 //                                                      contourList->erase(iterTemp++);
 //                                              }
 //////                                          iter2++;
 ////////                                                iterTemp--;
 ////////                                                contourList->erase(iter2++,iterTemp);
 //                                      }
 //                              }
                                 iter2++;
                         }
                 }
         }
 }
void ActiveContourDetector_balloon::calculateShrinkForce_ (Contour_F * contourIn, ContourForce * shrink) private
Calculate the shrink force for each pt on the contour.
Parameters
contour
contourforce
Definition at line 304 of file ActiveContourDetector_balloon.cpp.
References edgeCoeff_, uriVL::Contour_F::getEdgeList(), uriVL::ContourForce::getForce(), uriVL::Contour::getInterPointDistances(), uriVL::Contour_F::getPoints(), uriVL::ActiveContourDetector::getTimeStep(), and uriVL::R_W_ACCESS.
Referenced by oneStep_().
{
         const float TIMESTEP_MULT_EDGE_COEFF = edgeCoeff_ * getTimeStep();
         //const float NORM_SQRD_TOL = 250.f;
         float   shrinkTolerance = .001f,
                         magnitude = 0.f,
                         tVecYTimestVecX = 0.f,
                         tVecXTimestVecY = 0.f,
                         difference = 0.f,
                         normedVecX, normedVecXp1, normedVecY, normedVecYp1;
         const list<float>*      ptDistance = contourIn->getInterPointDistances();
         const list<ImagePoint_F*>*      tangentVec = contourIn->getEdgeList();
         list<Vector2D_F*>*      shrinkVec = shrink->getForce(R_W_ACCESS);
         const list<ImagePoint_F*>*      contour = contourIn->getPoints();
         list<Vector2D_F*>::const_iterator       iterS = shrinkVec->begin(),
                                                                                 iterSip1 = shrinkVec->begin();
         list<ImagePoint_F*>::const_iterator iterTanVec = tangentVec->begin(),
                                                                                 iterTanVecIp1 = tangentVec->begin(),
                                                                                 iter_0 = contour->begin(),
                                                                                 iter_1 = contour->begin();
         iter_0 = contour->begin();
         for(list<float>::const_iterator iterPtDist = ptDistance->begin(), iterPtDistIp1 = ptDistance->begin();
                                     iterPtDist != ptDistance->end(); iterPtDist++)
{
                 // increment all teh points accordingly
                 iterSip1++;
                 iterPtDistIp1++;
                 iterTanVecIp1++;
                 if(iterSip1 == shrinkVec->end()){
                         iterSip1 = shrinkVec->begin();
                         iterPtDistIp1 = ptDistance->begin();
                         iterTanVecIp1 = tangentVec->begin();
                 }
                 float   shrinkVecXiP1 = (*iterSip1)->getX();
                 float   shrinkVecYiP1 = (*iterSip1)->getY();
                 //  normalize edge vectors --> should not have to calculate the values for
                 //  i, just get those from ip1 [from last iteration]
 //jyh --> unused
 //              float   tempVecX = (*iterTanVec)->getX();
 //              float   tempVecY = (*iterTanVec)->getY();
 //              float   tempDist = *iterPtDist;
 //              float   tempVecXp1 = (*iterTanVecIp1)->getX();
 //              float   tempVecYp1 = (*iterTanVecIp1)->getY();
 //              float   tempDistP1 = *iterPtDistIp1;
                 normedVecX = (*iterTanVec)->getX()/(*iterPtDist);
                 normedVecY = (*iterTanVec)->getY()/(*iterPtDist);
                 normedVecXp1 = (*iterTanVecIp1)->getX()/(*iterPtDistIp1);
                 normedVecYp1 = (*iterTanVecIp1)->getY()/(*iterPtDistIp1);
                 tVecYTimestVecX = normedVecYp1 * normedVecX;
                 tVecXTimestVecY = normedVecXp1 * normedVecY;
                 difference = tVecXTimestVecY - tVecYTimestVecX;
                 //if contour is a straight line at Vi+1
                 if(difference*difference < shrinkTolerance){
                         shrinkVecXiP1 = -normedVecYp1;
                         shrinkVecYiP1 =  normedVecXp1;
                         magnitude = 1.0f;   //  edge vectors have been normalized
                 }else if(difference < 0){//if contour is convex at Vi+1
                         shrinkVecXiP1 = normedVecXp1 - normedVecX;
                         shrinkVecYiP1 = normedVecYp1 - normedVecY;
                         //      shrinking force is normalized
                         magnitude = sqrtf(shrinkVecXiP1 * shrinkVecXiP1 + shrinkVecYiP1 * shrinkVecYiP1);
                 }else{//contour is concave at Vi+1
                         shrinkVecXiP1 = normedVecX - normedVecXp1;
                         shrinkVecYiP1 = normedVecY - normedVecYp1;
                         //  hack
                         magnitude = sqrtf(shrinkVecXiP1 * shrinkVecXiP1 +
                         shrinkVecYiP1 * shrinkVecYiP1);
                 }
                 //      shrinking force is normalized
                 if(magnitude != 0.f){
                         shrinkVecXiP1 /= magnitude;
                         shrinkVecYiP1 /= magnitude;
                 }
                 (*iterSip1)->setX(shrinkVecXiP1 * TIMESTEP_MULT_EDGE_COEFF);
                 (*iterSip1)->setY(shrinkVecYiP1 * TIMESTEP_MULT_EDGE_COEFF);
                 iterS++;
                 iterTanVec++;
         }
 }
IterationStatus ActiveContourDetector_balloon::findContour (const RasterImage * imgIn, Contour_F * contour)
Finds a contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
Parameters
imgIn image in which to look for the contour
contour initial contour, and also output contour
Returns
status of the search
Definition at line 154 of file ActiveContourDetector_balloon.cpp.
References uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::ActiveContourDetector::colorImageGradientProcessor_, uriVL::ActiveContourDetector::DEFAULT_GAUSSIAN_FILTER_SCALE, FAIL_CONDITION, findContour_(), uriVL::RasterImage::getBaseRasterType(), uriVL::VectorField::getNormSquaredAsRasterImage(), uriVL::FeatureDetector::getSearchRect(), uriVL::GRAD_LARGEST_COLOR_COMPONENT, uriVL::ActiveContourDetector::gradientsAreLocal_, gradOfNormSqrdOfGrad_, uriVL::ActiveContourDetector::grayImageGradientProcessor_, uriVL::ActiveContourDetector::imageGradient_, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kRGBa32Raster, uriVL::ActiveContourDetector::normSqrdOfGrad_, uriVL::ColorImageGradient::setColorGradientMode(), and uriVL::ActiveContourDetector::setContour_().
 {
         FAIL_CONDITION( imgIn == NULL,
                                         kNullRasterImageError,
                                         "null RasterImage passed as input to ActiveContourDetector_balloon");
         FAIL_CONDITION( contour == NULL,
                                         kNullParameterError,
                                         "null Contour passed as input to ActiveContourDetector_balloon");
         const ImageRect* procRect = getSearchRect();
     imageGradient_      = new VectorField_F(procRect);
     normSqrdOfGrad_ = new RasterImage_gray_F(procRect);
     gradOfNormSqrdOfGrad_ = new VectorField_F(procRect);
         //  we only need a color gradient if the input image is a color image
         if(imgIn->getBaseRasterType() == kRGBa32Raster){
                 colorImageGradientProcessor_ = new ColorImageGradient_Gaussian_F(DEFAULT_GAUSSIAN_FILTER_SCALE);
                 colorImageGradientProcessor_->setColorGradientMode(GRAD_LARGEST_COLOR_COMPONENT);
                 colorImageGradientProcessor_->applyInto(imgIn, imageGradient_);
         }
         else{
                 grayImageGradientProcessor_ = new ImageGradient_Gaussian_F(DEFAULT_GAUSSIAN_FILTER_SCALE);
                 grayImageGradientProcessor_->applyInto(imgIn, imageGradient_);
         }
         imageGradient_->getNormSquaredAsRasterImage(normSqrdOfGrad_);
         grayImageGradientProcessor_->applyInto(normSqrdOfGrad_, gradOfNormSqrdOfGrad_);
         //
         gradientsAreLocal_ = true;
         //      All the computation will be done inside balloonContour_, which is an alias of contourOut
         //      and whose points are initialized as that of contourIn.
         setContour_(contour);
         return findContour_( );
 }
IterationStatus ActiveContourDetector_balloon::findContour (VectorField_F * grad, RasterImage_gray_F * normSqrd, VectorField_F * gradNormSqrd, Contour_F * contour)
Finds a contour in the input image, starting with the initial contour specified, which will be modified and provide the output of the function.
Parameters
imgIn image in which to look for the contour
contour initial contour, and also output contour
Returns
status of the search
Definition at line 192 of file ActiveContourDetector_balloon.cpp.
References FAIL_CONDITION, findContour_(), grad, uriVL::ActiveContourDetector::gradientsAreLocal_, gradOfNormSqrdOfGrad_, uriVL::ActiveContourDetector::imageGradient_, uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kNullVectorFieldError, uriVL::ActiveContourDetector::normSqrdOfGrad_, and uriVL::ActiveContourDetector::setContour_().
 {
         FAIL_CONDITION( grad == NULL,
                                         kNullVectorFieldError,
                                         "null gradient passed as input to ActiveContourDetector_balloon");
         FAIL_CONDITION( normSqrd == NULL,
                                         kNullRasterImageError,
                                         "null  gradient norm image passed as input to ActiveContourDetector_balloon");
         FAIL_CONDITION( gradNormSqrd == NULL,
                                         kNullVectorFieldError,
                                         "null grad-of-norm2 passed as input to ActiveContourDetector_balloon");
         FAIL_CONDITION( contour == NULL,
                                         kNullParameterError,
                                         "null Contour passed as input to ActiveContourDetector_balloon");
         //      We don't need to allocate new gradient objects.  We just keep references to the ones
         //      computed by the caller.
         imageGradient_ = grad;
         normSqrdOfGrad_ = normSqrd;
         gradOfNormSqrdOfGrad_ = gradNormSqrd;
         gradientsAreLocal_ = false;
         //      All the computation will be done inside balloonContour_, which is an alias of contourOut
         //      and whose points are initialized as that of contourIn.
         setContour_(contour);
         return findContour_();
 }
const IterationStatus ActiveContourDetector_balloon::findContour_ (void) private
Depending on the value of step.
Definition at line 231 of file ActiveContourDetector_balloon.cpp.
References edgeForce_, uriVL::ActiveContourDetector::getContour_(), uriVL::IterationStatus::hasConverged(), uriVL::ActiveContourDetector::internalForce_, uriVL::ActiveContourDetector::iterate(), uriVL::ContourForce::mapToContour(), MAX_BALLOON_ITERATIONS, oneStep_(), uriVL::R_W_ACCESS, uriVL::ActiveContourDetector::setupCompleted_, shrinkForce_, uriVL::ActiveContourDetector::stepByStep_, uriVL::ActiveContourDetector::stepSize_, and uriVL::ActiveContourDetector::totalForce_.
Referenced by findContour().
 {
         Contour_F* contour = getContour_(R_W_ACCESS);
         edgeForce_->mapToContour(contour);
         shrinkForce_->mapToContour(contour);
         internalForce_->mapToContour(contour);
         totalForce_->mapToContour(contour);
         //      at this point the setup is complete.  We could proceed either step by step if the user
         //      asked us to do so.
         setupCompleted_ = true;
         IterationStatus iterationStatus;
         if (stepByStep_)
         {
                 for(int i=0; (i < stepSize_) && !iterationStatus.hasConverged(); i++)
                 {
                         iterationStatus = oneStep_();
                 }
         }
         else
         {
                 iterationStatus = iterate(MAX_BALLOON_ITERATIONS);
         }
         return iterationStatus;
 }
void uriVL::ActiveContourDetector_balloon::initializeContour_ (Contour_F * contour) private
Set up the contour equaly spacing them around the image.
Parameters
contour
IterationStatus ActiveContourDetector_balloon::oneStep_ (void) private virtual
Applies one iteration of the balloon algorithm.
Returns
contour detection iteration status structure
Implements uriVL::ActiveContourDetector.
Definition at line 261 of file ActiveContourDetector_balloon.cpp.
References uriVL::ContourForce::addForce(), uriVL::ContourForce::applyForceToContour(), calculateEdgeForce_(), uriVL::ActiveContourDetector::calculateInternalForce_(), calculateShrinkForce_(), edgeForce_, uriVL::ActiveContourDetector::getContour_(), gradOfNormSqrdOfGrad_, uriVL::ActiveContourDetector::internalForce_, uriVL::ActiveContourDetector::nbIterations_, uriVL::ActiveContourDetector::normSqrdOfGrad_, uriVL::R_W_ACCESS, searchAndInsertPoints_(), uriVL::IterationStatus::setConverged(), uriVL::ContourForce::setForcesToZero(), shrinkForce_, and uriVL::ActiveContourDetector::totalForce_.
Referenced by findContour_().
{
         /*      here i calc all the forces then add them to the total force
                 then i apply the total force to the contour
                 after this i set it back to zero for the next iteration.
                 these forces stem from the equation
                 Eint + Eimage = 0
                 where
                         Eint = Internal Force
                         Eimage = Balloon Force -> (-k1(vectorNormal2Curve) + k2(grad/normOfGrad))
          */
         IterationStatus status;
         Contour_F* contour = getContour_(R_W_ACCESS);
         // pretty smooth.. just calc the forces on each point
         calculateInternalForce_();
         calculateEdgeForce_(contour, gradOfNormSqrdOfGrad_, edgeForce_);
         calculateShrinkForce_(contour, shrinkForce_);
         // add them up to be one total force
         totalForce_->setForcesToZero();
         totalForce_->addForce(internalForce_);
         totalForce_->addForce(edgeForce_);
         totalForce_->addForce(shrinkForce_);
         // apply the force and if it has converged then don't insert pts
         bool contourHasConverged = totalForce_->applyForceToContour();
         if (contourHasConverged)
         {
                 status.setConverged();
         }
         else
         {
                 // check to see if after the move we need to insert a point
                 searchAndInsertPoints_(contour, normSqrdOfGrad_);
         }
         nbIterations_++;
         return status;
 }
const ActiveContourDetector_balloon & ActiveContourDetector_balloon::operator= (const ActiveContourDetector_balloon & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 97 of file ActiveContourDetector_balloon.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ActiveContourDetector_balloon copy operator not implemented.");
         return *this;
 }
void ActiveContourDetector_balloon::renderForces (void) virtual
Renders the different forces that compose the balloon total force.
Implements uriVL::ActiveContourDetector.
Definition at line 873 of file ActiveContourDetector_balloon.cpp.
References edgeForce_, uriVL::ActiveContourDetector::internalForce_, uriVL::DrawableObject2D::render(), shrinkForce_, and uriVL::ActiveContourDetector::totalForce_.
{
         glPushMatrix();
                 shrinkForce_->render();
                 internalForce_->render();
                 edgeForce_->render();
                 totalForce_->render();
         glPopMatrix();
 }
void ActiveContourDetector_balloon::searchAndInsertPoints_ (Contour_F * contour, const RasterImage_gray_F * normSqrdOfGrad) private
Uses bresenham's alg to calculate all the points in between each contour pt and inserts a new point if an edge is found beyond a certain threshold.
Definition at line 543 of file ActiveContourDetector_balloon.cpp.
References BRESENHAM_STEP_SIZE, edgeForce_, uriVL::Contour_F::getPoints(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), GRAD_THRESHOLD, uriVL::ContourForce::insertIntoForceVector(), uriVL::Contour_F::insertPoint(), uriVL::ActiveContourDetector::internalForce_, MIN_DIST_BTWN_PTS, shrinkForce_, uriVL::ActiveContourDetector::totalForce_, transFromBresenhamSpace_(), and transToBresenhamSpace_().
Referenced by oneStep_().
 {
         //get the array representing the norm squared of the gradient.
         const float *const*             normRaster = normSquaredOfGrad->getShiftedGrayF2D();
         //coordinate-related integer variables
         int     x[2] = {0,0},
                 y[2] = {0,0};
         int     x0 = 0, y0 = 0,
                 startX = 0, startY = 0,
                 endX = 0, endY = 0,
                 dx = 0, dy = 0, //difference in x and y
                 currIndex = 0;
         int lastCx = 0,
                 lastCy = 0,
                 lastInsert = 0;
         //      iter_0 starts at the end of the list of contour points while iter_1
         //      starts at the beginning of the list.  This is so that the during the
         //      first iteration, the edge E[n]->E[0] is handled first.  During this first
         //      iteration the value of the current index (the index representing iter_1)
         //      is not modified; however, every subsequent loop that points are inserted
         //      onto the contour edge, the value of current index must be incremented
         //      accordingly.
         const list<ImagePoint_F *>*     contourList = contour->getPoints();             //a list of the ImagePoint_Fs representing the contour
         list<ImagePoint_F *>::const_iterator    iter_0 = contourList->end(),    //iterator representing element C_(i-1) of the contour list
                                                                                         iter_1 = contourList->begin(),  //iterator representing element C_(i) of the contour list
                                                                                         endList = contourList->end(),
                                                                                         debug_0 = contourList->begin(),
                                                                                         debug_1 = contourList->begin();
         iter_0--;
         while (iter_1 != endList)
         {
                 bool    swapped0F = false,
                                 edgeSection = false;
                 // get this iterations initial and final values for each point
                 x[0] = (*iter_0)->getX();
                 x[1] = (*iter_1)->getX();
                 y[0] = (*iter_0)->getY();
                 y[1] = (*iter_1)->getY();
                 //      if the two endpoints coincide
                 if ((x[0] == x[1]) && (y[0] == y[1]))
                 {
                         //      and iter_1 is not the end of the list
                         if ( iter_1 != endList )
{
                                 iter_0 = iter_1;
                                 iter_1++;
                                 currIndex++;
                                 x[0] = (*iter_0)->getX();
                                 y[0] = (*iter_0)->getY();
                                 x[1] = (*iter_1)->getX();
                                 y[1] = (*iter_1)->getY();
                         }
                         // else do what???
                 }
                 //next we need to keep track of these initial and final values since
                 //the x and y arrays will be modified by the transToBresenhamSpace
                 //method
                 startX = x[0];
                 startY = y[0];
                 endX = x[1];
                 endY = y[1];
                 dx = x[1] - x[0];       //dx represents the difference in x values
                 dy = y[1] - y[0];       //dy represents the difference in y values
                 //rather than adapt Bresenham's Algorithm to handle all cases we exploit
                 //the symmetry inherent in our coordinate system to transform the given
                 //points into a space that will work with the unadapted Bresenham's
                 //algorithm
                 int     octant = 0;     //octant represents the Octant that the current point lies in
                 transToBresenhamSpace_(dx, dy, x, y, octant, swapped0F);
                 int     sumX = x[0],
                         sumY = y[0],
                         ptCount = 1;
                 //      Bressenham decision variable
                 int bres_d = 2*dy - dx; //initialize bres_d to be 2dy - dx, per the Bresenham Algorithm
                 y0 = y[0];              //initialize y0 to be the initial point transformed to Bresenham Space
                 lastCx = x[0];
                 lastCy = y[0];
                 lastInsert = currIndex;
                 for (x0 = x[0]; x0 < x[1]; x0 += BRESENHAM_STEP_SIZE )
                 {
                         int     xn = x0,
                                 yn = y0;
                         transFromBresenhamSpace_(xn, yn, octant);
                         const float gradAtPoint = normRaster[yn][xn];
                         if (gradAtPoint > GRAD_THRESHOLD)
{
                                 if (edgeSection)
{
                                         sumX += xn;
                                         sumY += yn;
                                         ptCount++;
                                 } else {
                                         edgeSection = true;
                                         sumX = xn;
                                         sumY = yn;
                                         ptCount = 1;
                                 }
                         } else {
                                 if (edgeSection)
{
                                         edgeSection = false;
                                         float   Cx = sumX/ptCount,
                                                         Cy = sumY/ptCount;
                                         float   distToEnd = sqrtf((Cx - endX)*(Cx - endX) + (Cy - endY)*(Cy - endY)),
                                                         distToLast = sqrtf((Cx - lastCx)*(Cx - lastCx) + (Cy - lastCy)*(Cy - lastCy)),
                                                         distToStart = sqrtf((Cx - startX)*(Cx - startX) + (Cy - startY)*(Cy - startY));
                                         if (distToEnd > MIN_DIST_BTWN_PTS && distToLast > MIN_DIST_BTWN_PTS && distToStart > MIN_DIST_BTWN_PTS)
{
                                                 if (!swapped0F)
{
                                                         lastCx = static_cast<int>(roundf(Cx));
                                                         lastCy = static_cast<int>(roundf(Cy));
                                                         contour->insertPoint(currIndex,Cx,Cy);
                                                         edgeForce_->insertIntoForceVector(currIndex, 0.f, 0.f);
                                                         internalForce_->insertIntoForceVector(currIndex, 0.f, 0.f);
                                                         shrinkForce_->insertIntoForceVector(currIndex, 0.f, 0.f);
                                                         totalForce_->insertIntoForceVector(currIndex, 0.f, 0.f);
                                                         if (iter_1 != contourList->begin() || currIndex != 0)
{
                                                                 currIndex++;
                                                                 lastInsert = currIndex;
                                                         }
                                                 } else {
                                                         lastCx = static_cast<int>(roundf(Cx));
                                                         lastCy = static_cast<int>(roundf(Cy));
                                                         contour->insertPoint(currIndex,Cx,Cy);
                                                         edgeForce_->insertIntoForceVector(lastInsert, 0.f, 0.f);
                                                         internalForce_->insertIntoForceVector(lastInsert, 0.f, 0.f);
                                                         shrinkForce_->insertIntoForceVector(lastInsert, 0.f, 0.f);
                                                         totalForce_->insertIntoForceVector(lastInsert, 0.f, 0.f);
                                                         if (iter_1 != contourList->begin() || currIndex != 0)
{
                                                                 currIndex++;
                                                                 if (lastInsert != 0)
{
                                                                         lastInsert--;
                                                                 } else {
                                                                         lastInsert = 0;
                                                                 }
                                                         }
                                                 }
                                         }
                                 }
                         }
                         bres_d += dy;
                         if ( (bres_d << 1) >= dx )
{
                                 y0 += BRESENHAM_STEP_SIZE;
                                 bres_d -= dx;
                         }
                 }
                 iter_0 = iter_1;
                 iter_1++;
                 currIndex++;
         }// ;   //keep looping until we've visited all the contour points
 }
void ActiveContourDetector_balloon::setCoeffs (float internalCoeff, float edgeCoeff, float shrinkCoeff)
Sets the coefficients of the detector's various force components.
Thie coefficients received are normalized by the function (so that their sum is 1).
Parameters
internalCoeff coefficient of the internal, "goodness" force in total force calculation
edgeCoeff coefficient of the edge force in total force calculation
shrinkCoeff coefficient of the shrink/inflate force in total force calculation
Definition at line 115 of file ActiveContourDetector_balloon.cpp.
References edgeCoeff_, uriVL::ActiveContourDetector::setInternalCoeff_(), and shrinkCoeff_.
 {
         //      Normalize coefficients sent by the user, just in case.
         const float coeffScale = 1.f / (internalCoeff + edgeCoeff + shrinkCoeff);
         ActiveContourDetector::setInternalCoeff_(coeffScale * internalCoeff);
         edgeCoeff_ = edgeCoeff * coeffScale;
         shrinkCoeff_ = shrinkCoeff * coeffScale;
 }
void ActiveContourDetector_balloon::setImageProperties (VectorField_F * grad, RasterImage_gray_F * normSqrd, VectorField_F * gradNormSqrd, Contour_F * contourOut)
This function should be called for video-rate applications that must re-use the same rasters for performance optimization purposes.
In that case, the image and vector rasters are not local to the
Parameters
grad image gradient vector field
normSqrd norm of gradient raster
gradNormSqrd gradient of norm of gradient squared raster
contourOut the contour object into which to compute the results
Definition at line 126 of file ActiveContourDetector_balloon.cpp.
References edgeForce_, gradOfNormSqrdOfGrad_, uriVL::ActiveContourDetector::internalForce_, uriVL::ContourForce::mapToContour(), uriVL::ActiveContourDetector::setContour_(), uriVL::ActiveContourDetector::setGradientRasters_(), shrinkForce_, and uriVL::ActiveContourDetector::totalForce_.
 {
         //      We don't need to allocate new gradient objects.  We just keep references to the ones
         //      computed by the caller.
         //      The parent class's function also sets gradientsAreLocal_ to 'false'
         setGradientRasters_(grad, normSqrd);
         gradOfNormSqrdOfGrad_ = gradNormSqrd;
         //      All the computation will be done inside balloonContour_, which is an alias of contourOut
         //      and whose points are initialized as that of contourIn.
         setContour_(contourOut);
         edgeForce_->mapToContour(contourOut);
         shrinkForce_->mapToContour(contourOut);
         internalForce_->mapToContour(contourOut);
         totalForce_->mapToContour(contourOut);
 }
void ActiveContourDetector_balloon::swap0F_ (int x[], int y[]) inline private
Inverts the Y-pair vaules (y0,y1)->(-y0,-y1)
Parameters
Y a pointer to the array representing the pair of y values.Inverts the Y value y -> -y
Y a reference to the Y value.Swaps the initial point's values with the final point's values
@param      x       an array representing the pair of x-values
@param      y       an array representing the pair of y-values
Definition at line 854 of file ActiveContourDetector_balloon.cpp.
Referenced by transToBresenhamSpace_().
 {
         int temp = x[0];
         x[0] = x[1];
         x[1] = temp;
         temp = y[0];
         y[0] = y[1];
         y[1] = temp;
 }
void ActiveContourDetector_balloon::swapXY_ (int x[], int y[]) inline private
Swaps the values of X-pairs and Y-pairs (x0,x1)->(y0,y1)
Parameters
X a pointer to the array representing the pair of x values.
Y a pointer to the array representing the pair of y values.
Definition at line 836 of file ActiveContourDetector_balloon.cpp.
Referenced by transFromBresenhamSpace_(), and transToBresenhamSpace_().
 {
         int temp = x[0];
         x[0] = y[0];
         y[0] = temp;
         temp = x[1];
         x[1] = y[1];
         y[1] = temp;
 }
void ActiveContourDetector_balloon::swapXY_ (int & x, int & y) inline private
Swaps the values of X and Y.
Parameters
X a reference to the X value.
Y a reference to the Y value.
Definition at line 847 of file ActiveContourDetector_balloon.cpp.
 {
         int temp = x;
         x = y;
         y = temp;
 }
void ActiveContourDetector_balloon::transFromBresenhamSpace_ (int & xVal, int & yVal, int octant) private
This is a private helper method designed to facilitate using our modified Bresenham's Algorithm to transform the computed point from the space of the Bresenham's Algorithm to its appropriate reflection about the various axes.
Parameters
xVal the computed x-value
yVal the computed y-value
octant the octant that the point is supposed to be in
Definition at line 802 of file ActiveContourDetector_balloon.cpp.
References swapXY_().
Referenced by searchAndInsertPoints_().
 {
         switch(octant)
         {
                 case 1:
                         break;
                 case 2:
                         swapXY_(x,y);
                         break;
                 case 3:
                         y = -y;
                         swapXY_(x,y);
                         break;
                 case 4:
                         y = -y;
                         break;
                 case 5:
                         break;
                 case 6:
                         swapXY_(x,y);
                         break;
                 case 7:
                         swapXY_(x,y);
                         y = -y;
                         break;
                 case 8:
                         y = -y;
                         break;
                 default:
                         break;
         }
 }
void ActiveContourDetector_balloon::transToBresenhamSpace_ (int & dx, int & dy, int x[], int y[], int & octant, bool & swapped0F) private
Attempts to find an edge by going a fixed distance from a a particular point.
Parameters
start an ImagePoint_F that represents the starting point
maxDist a float representing the maximum distance from the starting point that should be searched
dx the displacement in the x
dy the displacement in the y
normSquaredOfGrad a RasterImage_gray_F representing the norm squared of the gradient of the points in the VectorField.
Returns
true if an edge is detectedPrivate helper method designed to facilitate using our modified Bresenham's Algorithm in searchAndInsertPoints() method
Parameters
dx the initially calculated change in the x-values
dy the initially calculated change in the y-values
x an array of size two representing the pair of x-values (x_0, x_f)
y an array of size two representing the pair of y-values (y_0, y_f)
octant an interger value representing what octant the pair of points lies in.
swapped0F a boolean value used in conjunction with octant to determine the order that points are inserted onto the contour.
Definition at line 736 of file ActiveContourDetector_balloon.cpp.
References swap0F_(), and swapXY_().
Referenced by searchAndInsertPoints_().
 {
         if (x[1] > x[0] && abs(dx) >= abs(dy) && y[1] >= y[0])
         {
                 octant = 1;
                 swapped0F = false;
         }
         else if (x[1] >= x[0] && abs(dx) < abs(dy) && y[1] > y[0])
         {
                 octant = 2;
                 swapXY_(x,y);
                 swapped0F = false;
         }
         else if (x[1] < x[0] && abs(dx) < abs(dy) && y[1] > y[0])
         {
                 octant = 3;
                 swapXY_(x,y);
                 *y = -(*y);
                 swapped0F = false;
         }
         else if (x[1] < x[0] && abs(dx) >= abs(dy) && y[1] > y[0])
         {
                 octant = 4;
                 *y = -(*y);
                 swap0F_(x,y);
                 swapped0F = true;
         }
         else if (x[1] < x[0] && abs(dx) >= abs(dy) && y[1] <= y[0])
         {
                 octant = 5;
                 swap0F_(x,y);
                 swapped0F = true;
         }
         else if (x[1] < x[0] && abs(dx) < abs(dy) && y[1] < y[0])
         {
                 octant = 6;
                 swap0F_(x,y);
                 swapXY_(x,y);
                 swapped0F = true;
         }
         else if (x[1] >= x[0] && abs(dx) < abs(dy) && y[1] < y[0])
         {
                 octant = 7;
                 *y = -(*y);
                 swapXY_(x,y);
                 swapped0F = false;
         }
         else if (x[1] > x[0] && abs(dx) >= abs(dy) && y[1] < y[0])
         {
                 octant = 8;
                 *y = -(*y);
                 swapped0F = false;
         }
         else
         {
                 cout << "There is an error in the logic of transforming the point to Bresenham Algorithm's space." << endl;
                 cout << "dx: " << dx << "\tdy: " << dy << endl;
                 cout << "x0: " << x[0] << "\tx1: " << x[1] << endl;
                 cout << "y0: " << y[0] << "\ty1: " << y[1] << endl;
         }
         //recalculate the dx and dy
         dx = x[1] - x[0];       //dx represents the difference in x values
         dy = y[1] - y[0];       //dy represents the difference in y values
 }
Member Data Documentation
float uriVL::ActiveContourDetector_balloon::edgeCoeff_ private
Coefficient of the "edge force" in the total force computation.
Definition at line 150 of file ActiveContourDetector_balloon.h.
Referenced by calculateEdgeForce_(), calculateShrinkForce_(), and setCoeffs().
ContourForce* uriVL::ActiveContourDetector_balloon::edgeForce_ private
Force that attracts the contour to the closest/strongest edge.
Definition at line 138 of file ActiveContourDetector_balloon.h.
Referenced by ActiveContourDetector_balloon(), findContour_(), oneStep_(), renderForces(), searchAndInsertPoints_(), setImageProperties(), and ~ActiveContourDetector_balloon().
VectorField_F* uriVL::ActiveContourDetector_balloon::gradOfNormSqrdOfGrad_ private
Stores the gradient of norm squared of gradient of the image being operated on.
Definition at line 146 of file ActiveContourDetector_balloon.h.
Referenced by findContour(), oneStep_(), setImageProperties(), and ~ActiveContourDetector_balloon().
float uriVL::ActiveContourDetector_balloon::shrinkCoeff_ private
Coefficient of the "expand/contract force" in the total force computation.
Definition at line 154 of file ActiveContourDetector_balloon.h.
Referenced by setCoeffs().
ContourForce* uriVL::ActiveContourDetector_balloon::shrinkForce_ private
Force that makes the balloon contract/expand.
Definition at line 142 of file ActiveContourDetector_balloon.h.
Referenced by ActiveContourDetector_balloon(), findContour_(), oneStep_(), renderForces(), searchAndInsertPoints_(), setImageProperties(), and ~ActiveContourDetector_balloon().
The documentation for this class was generated from the following files:
ActiveContourDetector_balloon.h
ActiveContourDetector_balloon.cpp