URIVisionLibrary: WXGL_IO_Frame Class Reference
WXGL_IO_Frame Class Reference
#include <WXGL_IO_frame.h>
Public Member Functions
WXGL_IO_Frame (wxFrame *frame, const wxString &title, const wxPoint &pos, const wxSize &size)
virtual ~WXGL_IO_Frame ()
class wxGLCanvas * GetCanvas ()
void InitCanvas ()
void OnCloseWindow (wxCloseEvent &event)
void CreateMenus ()
void FileOpen (wxCommandEvent &event)
void FileSave (wxCommandEvent &event)
void FileSaveAs (wxCommandEvent &event)
void FileRead (wxCommandEvent &event)
void FileWrite (wxCommandEvent &event)
void FileExit (wxCommandEvent &event)
void ParamSize (wxCommandEvent &event)
void TypeExtension (wxCommandEvent &event)
void RasterType (wxCommandEvent &event)
void HelpAbout (wxCommandEvent &event)
void HelpHelp (wxCommandEvent &event)
Private Types
enum MenuCommands {
MENU_ID_FILE_OPEN = 10,
MENU_ID_FILE_SAVE,
MENU_ID_FILE_SAVEAS,
MENU_ID_FILE_READ,
MENU_ID_FILE_WRITE,
MENU_ID_PARAM_ROWS,
MENU_ID_PARAM_COLS,
MENU_ID_EXT_BMP = 100,
MENU_ID_EXT_JPG,
MENU_ID_EXT_PNG,
MENU_ID_EXT_TIF,
MENU_ID_IMAGE_BINARY,
MENU_ID_IMAGE_GRAY,
MENU_ID_IMAGE_GRAY_F,
MENU_ID_IMAGE_RGBA,
MENU_ID_HELP_HELP
}
Private Attributes
WXGL_IO_Canvas * mp_Canvas
wxMenuBar * mp_menuBar
Detailed Description
Definition at line 26 of file WXGL_IO_frame.h.
Member Enumeration Documentation
enum WXGL_IO_Frame::MenuCommands private
Enumerator
MENU_ID_FILE_OPEN
MENU_ID_FILE_SAVE
MENU_ID_FILE_SAVEAS
MENU_ID_FILE_READ
MENU_ID_FILE_WRITE
MENU_ID_PARAM_ROWS
MENU_ID_PARAM_COLS
MENU_ID_EXT_BMP
MENU_ID_EXT_JPG
MENU_ID_EXT_PNG
MENU_ID_EXT_TIF
MENU_ID_IMAGE_BINARY
MENU_ID_IMAGE_GRAY
MENU_ID_IMAGE_GRAY_F
MENU_ID_IMAGE_RGBA
MENU_ID_HELP_HELP
Definition at line 93 of file WXGL_IO_frame.h.
{
                   // menu file params
         MENU_ID_FILE_OPEN = 10,
         MENU_ID_FILE_SAVE,
         MENU_ID_FILE_SAVEAS,
         MENU_ID_FILE_READ,
         MENU_ID_FILE_WRITE,
                   // MENU_ID_FILE_EXIT MUST USE wxID_EXIT so it is #defined above
                   // parameter setting IDs
                   MENU_ID_PARAM_ROWS,
                   MENU_ID_PARAM_COLS,
                          // file extension types
                         MENU_ID_EXT_BMP = 100, // copies are made in canvas so these have to match
                         MENU_ID_EXT_JPG,
                         MENU_ID_EXT_PNG,
                         MENU_ID_EXT_TIF,
                          // raster types
                         MENU_ID_IMAGE_BINARY,
                         MENU_ID_IMAGE_GRAY,
                         MENU_ID_IMAGE_GRAY_F,
                         MENU_ID_IMAGE_RGBA,
                         MENU_ID_HELP_HELP
                         // MENU_ID_HELP_ABOUT MUST USE wxID_ABOUT so it is #defined above
     };
Constructor & Destructor Documentation
WXGL_IO_Frame::WXGL_IO_Frame (wxFrame * frame, const wxString & title, const wxPoint & pos, const wxSize & size)
Definition at line 79 of file WXGL_IO_frame.cpp.
                                                                                                          :
     wxFrame(frame, wxID_ANY, title, pos, size)
 {
 #ifdef __WXMAC__
     wxApp::s_macAboutMenuItemId = wxID_ABOUT ;
 #endif
     // set the icon
 #ifdef __WXMSW__
     SetIcon(wxIcon(_T("UtilityIcon.ico")));
 #else
 #ifdef GTK_TBD
     SetIcon(wxIcon(Cards_bits, Cards_width, Cards_height));
 #endif
 #endif
         // call member function to init all the memus
         CreateMenus();
         // Create new drawing canvas
         mp_Canvas = new WXGL_IO_Canvas(this, -1 , wxDefaultPosition, size, 0, "GLKansas");
 #if wxUSE_STATUSBAR
     CreateStatusBar();
 #endif // wxUSE_STATUSBAR
 }
WXGL_IO_Frame::~WXGL_IO_Frame () virtual
Definition at line 106 of file WXGL_IO_frame.cpp.
 {
         // do not need to delete frame or canvas here
         // they get done automatically in WX base classes somewhere
 }
Member Function Documentation
void WXGL_IO_Frame::CreateMenus ()
Definition at line 70 of file WXGL_IO_menus.cpp.
References MENU_ID_EXT_BMP, MENU_ID_EXT_JPG, MENU_ID_EXT_PNG, MENU_ID_EXT_TIF, MENU_ID_FILE_EXIT, MENU_ID_FILE_OPEN, MENU_ID_FILE_READ, MENU_ID_FILE_SAVE, MENU_ID_FILE_SAVEAS, MENU_ID_FILE_WRITE, MENU_ID_HELP_ABOUT, MENU_ID_HELP_HELP, MENU_ID_IMAGE_BINARY, MENU_ID_IMAGE_GRAY, MENU_ID_IMAGE_GRAY_F, MENU_ID_IMAGE_RGBA, MENU_ID_PARAM_COLS, MENU_ID_PARAM_ROWS, MENU_TXT_FILE_EXIT, and mp_menuBar.
 {
          // Make the FILE MENU
     wxMenu* fileMenu = new wxMenu;
     fileMenu->Append(MENU_ID_FILE_OPEN,
                  _T("&Open"),
                  _T("Open a configuration file for this utility")
                  );
     fileMenu->Append(MENU_ID_FILE_SAVE,
                  _T("&Save"),
                  _T("Save current configuration for this utility")
                  );
     fileMenu->Append(MENU_ID_FILE_SAVEAS,
                  _T("Save &As"),
                  _T("Save current configuration for this utility")
                  );
          fileMenu->AppendSeparator();
          fileMenu->Append(MENU_ID_FILE_READ,
                  _T("&Read"),
                  _T("Read current values from the controller")
                  );
     fileMenu->Append(MENU_ID_FILE_WRITE,
                  _T("&Write"),
                  _T("Write current values to the controller")
                  );
          fileMenu->AppendSeparator();
     fileMenu->Append(MENU_ID_FILE_EXIT,
                  MENU_TXT_FILE_EXIT,
                  _T("Exits the utility")
                  );
          // make the PARAMETER MENU
     wxMenu* paramMenu = new wxMenu;
     paramMenu->Append(MENU_ID_PARAM_ROWS,
                 _T("&Rows"),
                 _T("Sets the number of rows the test image")
                 );
     paramMenu->Append(MENU_ID_PARAM_COLS,
                 _T("&Cols"),
                 _T("Sets the number of columns the test image")
                 );
          // make the TYPE MENU
     wxMenu* typeMenu = new wxMenu;
     typeMenu->Append(MENU_ID_EXT_BMP,
                 _T("&BMP"),
                 _T("Sets the test image type to .BMP")
                 );
     typeMenu->Append(MENU_ID_EXT_JPG,
                 _T("&JPG"),
                 _T("Sets the test image type to .JPG")
                 );
     typeMenu->Append(MENU_ID_EXT_PNG,
                 _T("&PNG"),
                 _T("Sets the test image type to .PNG")
                 );
     typeMenu->Append(MENU_ID_EXT_TIF,
                 _T("&TIF"),
                 _T("Sets the test image type to .TIF")
                 );
          // make the IMAGE MENU
     wxMenu* imageMenu = new wxMenu;
     imageMenu->Append(MENU_ID_IMAGE_BINARY,
                 _T("&Binary"),
                 _T("Sets the test image raster to Binary")
                 );
     imageMenu->Append(MENU_ID_IMAGE_GRAY_F,
                 _T("&FloatGray"),
                 _T("Sets the test image raster to Floating Grayscale")
                 );
     imageMenu->Append(MENU_ID_IMAGE_GRAY,
                 _T("&Gray"),
                 _T("Sets the test image raster to Grayscale")
                 );
     imageMenu->Append(MENU_ID_IMAGE_RGBA,
                 _T("&RGBa"),
                 _T("Sets the test image raster to RGBa")
                 );
          // make the HELP MENU
     wxMenu* helpMenu = new wxMenu;
              helpMenu->Append(MENU_ID_HELP_HELP,
                 _T("&Help Contents"),
                 _T("Displays information about running this utility")
                 );
     helpMenu->Append(MENU_ID_HELP_ABOUT,
                 _T("&About..."),
                 _T("Displays information about the Alignment and Linearization utility")
                 );
          // make the menu bar
     mp_menuBar = new wxMenuBar;
     mp_menuBar->Append(fileMenu,   _T("&File"));
     mp_menuBar->Append(paramMenu,  _T("&Params"));
     mp_menuBar->Append(typeMenu,   _T("&Type"));
     mp_menuBar->Append(imageMenu,  _T("&Image"));
     mp_menuBar->Append(helpMenu,   _T("&Help"));
     SetMenuBar(mp_menuBar);
 }
void WXGL_IO_Frame::FileExit (wxCommandEvent & event)
Definition at line 248 of file WXGL_IO_menus.cpp.
 {
     Close(true);
 }
void WXGL_IO_Frame::FileOpen (wxCommandEvent & event)
Definition at line 183 of file WXGL_IO_menus.cpp.
 {
 #if DISPLAY_CALLBACK_MSGBOX
         wxMessageBox(
                 _T("FileOpen command reached\n"),_T("DEBUG"),
       wxOK|wxICON_INFORMATION,
                 this
    );
 #endif // DISPLAY_CALLBACK_MSGBOX
 }
void WXGL_IO_Frame::FileRead (wxCommandEvent & event)
Definition at line 222 of file WXGL_IO_menus.cpp.
 {
 #if DISPLAY_CALLBACK_MSGBOX
         wxMessageBox(
                 _T("FileRead command reached\n"),_T("DEBUG"),
       wxOK|wxICON_INFORMATION,
                 this
    );
 #endif // DISPLAY_CALLBACK_MSGBOX
 }
void WXGL_IO_Frame::FileSave (wxCommandEvent & event)
Definition at line 196 of file WXGL_IO_menus.cpp.
 {
 #if DISPLAY_CALLBACK_MSGBOX
         wxMessageBox(
                 _T("FileSave command reached\n"),_T("DEBUG"),
       wxOK|wxICON_INFORMATION,
                 this
    );
 #endif // DISPLAY_CALLBACK_MSGBOX
 }
void WXGL_IO_Frame::FileSaveAs (wxCommandEvent & event)
Definition at line 209 of file WXGL_IO_menus.cpp.
 {
 #if DISPLAY_CALLBACK_MSGBOX
         wxMessageBox(
                 _T("FileSaveAs command reached\n"),_T("DEBUG"),
       wxOK|wxICON_INFORMATION,
                 this
    );
 #endif // DISPLAY_CALLBACK_MSGBOX
 }
void WXGL_IO_Frame::FileWrite (wxCommandEvent & event)
Definition at line 235 of file WXGL_IO_menus.cpp.
 {
  #if DISPLAY_CALLBACK_MSGBOX
         wxMessageBox(
                 _T("FileWrite command reached\n"),_T("DEBUG"),
       wxOK|wxICON_INFORMATION,
                 this
    );
 #endif // DISPLAY_CALLBACK_MSGBOX
 }
wxGLCanvas * WXGL_IO_Frame::GetCanvas ()
Definition at line 113 of file WXGL_IO_frame.cpp.
References mp_Canvas.
 {
         return mp_Canvas;
 }
void WXGL_IO_Frame::HelpAbout (wxCommandEvent & event)
Definition at line 374 of file WXGL_IO_menus.cpp.
 {
 #if USE_SVNINFO
         char full_rev[128];
         memset(full_rev,NULL,sizeof(full_rev));
         int result=GetSvinfo_FullRev(full_rev,sizeof(full_rev));
 #else
         char *full_rev = "1.0.0"; // manually set the version number if SVN info is not used
 #endif
         wxString contents=
                                 _T("URI Vision Library\n\n")
                                 _T("Demonstration wxWidget and OpenGL Code\n\n Version: ");
         contents+=      full_rev;
         contents+=      _T("\n\n")
                                 _T("Author: Lewis Collier\n")
                                 _T("email:  wlcollier@cs.uri.edu\n")
                                 _T("(c) 2012  URI 3D Group for Interactive Visualization");
         wxMessageBox(   contents,
                                         _T("ABOUT"),
                                         wxOK|wxICON_INFORMATION,
                                         this
                                 );
 }
void WXGL_IO_Frame::HelpHelp (wxCommandEvent & event)
Definition at line 346 of file WXGL_IO_menus.cpp.
 {
 #if 0 & wxUSE_HTML
     if (wxFileExists(wxGetApp().GetHelpFile()))
     {
         Linear25AboutDialog dialog(this, wxID_ANY, wxT("Demonstration wxWidget and OpenGL Code"));
         if (dialog.ShowModal() == wxID_OK)
         {
         }
     }
     else
 #endif
     {
         wxMessageBox(
             _T("URI Vision Library\n\n")
             _T("Demonstration wxWidget and OpenGL Code\n\n")
             _T("Author: Lewis Collier\n")
                                 _T("email:  wlcollier@cs.uri.edu\n\n")
                                 _T("(c) 2012 URI 3D Group for Interactive Visualization\n\n")
                                 _T("HELP COMING IN FUTURE VERSION\n"),
                                 _T("HELP"),
             wxOK|wxICON_INFORMATION,
                                 this
             );
     }
 }
void WXGL_IO_Frame::InitCanvas ()
Definition at line 120 of file WXGL_IO_frame.cpp.
References mp_Canvas, and WXGL_IO_Canvas::SetUpCamera().
Referenced by WXGL_IO_App::OnInit().
 {
         // make canvas current for GL calls
         mp_Canvas->SetCurrent();
         // sey up the camera co-ords
         mp_Canvas->SetUpCamera();
 }
void WXGL_IO_Frame::OnCloseWindow (wxCloseEvent & event)
Definition at line 56 of file WXGL_IO_menus.cpp.
References mp_Canvas, and WXGL_IO_Canvas::OnCloseCanvas().
 {
     if (mp_Canvas->OnCloseCanvas() )
     {
         this->Destroy();
     }
     else
         myEvent.Veto();
 }
void WXGL_IO_Frame::ParamSize (wxCommandEvent & event)
Definition at line 258 of file WXGL_IO_menus.cpp.
References WXGL_IO_Canvas::CreateTestImage(), WXGL_IO_Canvas::GetTestImageCols(), WXGL_IO_Canvas::GetTestImageRows(), MENU_ID_PARAM_COLS, MENU_ID_PARAM_ROWS, mp_Canvas, WXGL_IO_Canvas::SetTestImageCols(), WXGL_IO_Canvas::SetTestImageRows(), and WXGL_IO_Canvas::UpdateCanvas().
 {
         // set up default items for the dialog box
         wxString strMessage("defMessage");
         wxString strDefaultValue;
         wxPoint  pointLoc(242,242);
         char abValue[32];
         // check event to see if this is looking for rows or columns
         // set caption string accordingly
         char *pszMessage = 0;
         char *pszCaption = "Enter Test Image Size Parameter";
         if (myEvent.GetId() == MENU_ID_PARAM_COLS)
         {
                 pszMessage = "Enter # of COLUMNS in test image";
                 sprintf(abValue,"%d",mp_Canvas->GetTestImageCols());
         }
         else
         {
                 pszMessage = "Enter # of ROWS in test image";
                 sprintf(abValue,"%d",mp_Canvas->GetTestImageRows());
         }
         strDefaultValue = abValue;
         wxTextEntryDialog *ptDialog = new wxTextEntryDialog(this,wxString(pszMessage),wxString(pszCaption),strDefaultValue,wxOK|wxCANCEL|wxCENTRE, pointLoc);
         if (ptDialog != 0)
         {
                 int nStatus = ptDialog->ShowModal();
                 if (nStatus==wxID_OK)
                 {
                         wxString strAnswer = ptDialog->GetValue();
                         if(strAnswer.IsNumber())
{
                                 unsigned long ulAnswer;
                                 strAnswer.ToULong(&ulAnswer);
                                 if (myEvent.GetId() == MENU_ID_PARAM_COLS)
{
                                         mp_Canvas->SetTestImageCols(ulAnswer);
                                 }
                                 else if (myEvent.GetId() == MENU_ID_PARAM_ROWS)
{
                                         mp_Canvas->SetTestImageRows(ulAnswer);
                                 }
                                 mp_Canvas->CreateTestImage();
                                 mp_Canvas->UpdateCanvas();
                         }
                         else
{
                                 wxMessageBox(
                                                                         _T("Invalid Data Entry\n")+strAnswer,
                                                                         _T("ERROR"),
                                                                         wxOK|wxICON_INFORMATION,
                                                                         this
                                                                  );
                         }
                 }
         }
         else
         {
                         wxMessageBox(
                                                                 _T("Error creating text dialog box\n"),
                                                                 _T("ERROR"),
                                                                 wxOK|wxICON_INFORMATION,
                                                                 this
                                                          );
         }
 }
void WXGL_IO_Frame::RasterType (wxCommandEvent & event)
Definition at line 337 of file WXGL_IO_menus.cpp.
References WXGL_IO_Canvas::CreateTestImage(), mp_Canvas, WXGL_IO_Canvas::SetRasterType(), and WXGL_IO_Canvas::UpdateCanvas().
 {
         mp_Canvas->SetRasterType(myEvent.GetId());
         mp_Canvas->CreateTestImage();
         mp_Canvas->UpdateCanvas();
 }
void WXGL_IO_Frame::TypeExtension (wxCommandEvent & event)
Definition at line 329 of file WXGL_IO_menus.cpp.
References WXGL_IO_Canvas::CreateTestImage(), mp_Canvas, WXGL_IO_Canvas::SetFileType(), and WXGL_IO_Canvas::UpdateCanvas().
 {
         mp_Canvas->SetFileType(myEvent.GetId());
         mp_Canvas->CreateTestImage();
         mp_Canvas->UpdateCanvas();
 }
Member Data Documentation
WXGL_IO_Canvas* WXGL_IO_Frame::mp_Canvas private
Definition at line 81 of file WXGL_IO_frame.h.
Referenced by GetCanvas(), InitCanvas(), OnCloseWindow(), ParamSize(), RasterType(), and TypeExtension().
wxMenuBar* WXGL_IO_Frame::mp_menuBar private
Definition at line 82 of file WXGL_IO_frame.h.
Referenced by CreateMenus().
The documentation for this class was generated from the following files:
WXGL_IO_frame.h
WXGL_IO_frame.cpp
WXGL_IO_menus.cpp