URIVisionLibrary: uriVL::RandomGenerator_C Class Reference
uriVL::RandomGenerator_C Class Reference
Pseudorandom number generator wrapper class for the awful standard C function.
#include <RandomGenerator_C.h>
Public Member Functions
~RandomGenerator_C (void)
Destructor.
unsigned long nextULong (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
double nextDouble (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
double nextDouble (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
void setSeed (long theSeed)
Sets a new seed for this generator.
Public Member Functions inherited from uriVL::RandomGenerator
virtual ~RandomGenerator (void)
Destructor.
virtual unsigned int nextUInt (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
virtual int nextInt (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
virtual long nextLong (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
virtual float nextFloat (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
virtual float nextFloat (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
virtual double nextGaussian (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Static Public Member Functions
static unsigned int nextUInt_st (void)
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
static int nextInt_st (int lowVal, int highVal)
Returns a new uniformly-distributed int pseudo-random number in the range specified.
static unsigned long nextULong_st (void)
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
static long nextLong_st (long lowVal, long highVal)
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
static float nextFloat_st (void)
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
static float nextFloat_st (float lowVal, float highVal)
Returns a new uniformly-distributed float pseudo-random number in the range specified.
static double nextDouble_st (void)
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
static double nextDouble_st (double lowVal, double highVal)
Returns a new uniformly distributed double pseudo-random number in the range specified.
static double nextGaussian_st (double sigma=1.L)
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
static void setSeed_st (long theSeed)
Sets a new seed for this generator.
Static Public Attributes
static const int FULL_IN_ULONG = ((8*sizeof(unsigned long)) / MAX_BITS_IN_RAND)
number of full outputs of the C generator fitting in a long
static const int RES_TO_ULONG
number of residual bits of a output of the C generator to dd to make a long
static const int FULL_IN_UINT = ((8*sizeof(unsigned int)) / MAX_BITS_IN_RAND)
number of full outputs of the C generator fitting in an int
static const int RES_TO_UINT
number of residual bits of a output of the C generator to dd to make an int
Private Member Functions
RandomGenerator_C (void)
Creates a new RandomGenerator object and uses the current time stamp to generate a seed.
Private Attributes
unsigned int seed_
the generator's seed
Static Private Attributes
static RandomGenerator_C * rg_ = new RandomGenerator_C()
The unique object of this class, stored as a static member.
Additional Inherited Members
Protected Member Functions inherited from uriVL::RandomGenerator
RandomGenerator (void)
Creates a new RandomGenerator object.
Static Protected Attributes inherited from uriVL::RandomGenerator
static const bool INT_IS_LONG = (sizeof(int) == sizeof(long))
Indicates whether an int has the same length as a long (should be true non most platforms.
Detailed Description
Pseudorandom number generator wrapper class for the awful standard C function.
Needless to say, nobody should be using that one, I just coded it for debugging purposes (and to have a lower bound, quality-wise, to compare the other generators against).
There can only be one object of this class, therefore the class stores that object as a priveate member and only allows static calls to the generation functions.
Note that if you want to use the seed as a way to get repeatable pseudorandom sequences, it is important that you don't call directly the rand or srand functions. Make all calls through this class.
Author
jean-yves herve', 3D Group for Interactive Visualization, Dept. of Computer Science and Statistics, University of Rhode Island.
Definition at line 40 of file RandomGenerator_C.h.
Constructor & Destructor Documentation
RandomGenerator_C::~RandomGenerator_C (void)
Destructor.
Definition at line 51 of file RandomGenerator_C.cpp.
 {
 }
RandomGenerator_C::RandomGenerator_C (void) private
Creates a new RandomGenerator object and uses the current time stamp to generate a seed.
Definition at line 42 of file RandomGenerator_C.cpp.
References setSeed().
     :   RandomGenerator(),
                 //
                 seed_(0)
 {
     setSeed(time(NULL));
 }
Member Function Documentation
double RandomGenerator_C::nextDouble (double lowVal, double highVal) virtual
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Implements uriVL::RandomGenerator.
Definition at line 84 of file RandomGenerator_C.cpp.
References INV_MAX_ULONG, and nextULong().
Referenced by nextDouble_st().
 {
     return INV_MAX_ULONG * nextULong() * (highVal - lowVal) + lowVal;
 }
double RandomGenerator_C::nextDouble (void) virtual
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Implements uriVL::RandomGenerator.
Definition at line 90 of file RandomGenerator_C.cpp.
References INV_MAX_ULONG, and nextULong().
 {
     return INV_MAX_ULONG * nextULong();
 }
double RandomGenerator_C::nextDouble_st (void) static
Returns a new uniformly-distributed double pseudo-random number in the range [0, 1[.
Returns
new double pseudo-random value in the range [0, 1[
Definition at line 134 of file RandomGenerator_C.cpp.
References nextDouble(), and rg_.
Referenced by uriVL::Matrix::randomMatrix(), uriVL::RowVector::randomVector(), and uriVL::ColumnVector::randomVector().
 {
     return rg_->nextDouble();
 }
double RandomGenerator_C::nextDouble_st (double lowVal, double highVal) static
Returns a new uniformly distributed double pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new double pseudo-random value in the range [lowVal, highVal[
Definition at line 139 of file RandomGenerator_C.cpp.
References nextDouble(), and rg_.
 {
     return rg_->nextDouble(lowVal, highVal);
 }
float RandomGenerator_C::nextFloat_st (void) static
Returns a new uniformly-distributed float pseudo-random number in the range [0, 1[.
Returns
new float pseudo-random value in the range [0, 1[
Definition at line 124 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat();
 }
float RandomGenerator_C::nextFloat_st (float lowVal, float highVal) static
Returns a new uniformly-distributed float pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (exclusive) of the generated value range
Returns
new float pseudo-random value in thhe range [lowVal, highVal[
Definition at line 129 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextFloat(), and rg_.
 {
     return rg_->nextFloat(lowVal, highVal);
 }
double RandomGenerator_C::nextGaussian_st (double sigma = 1.L) static
Returns a new double pseudo-random number in the range [0, 1[ "normally" distributed (mean 0.0 and standard deviation sigma).
Parameters
sigma standard deviation of the distribution
Returns
new normally-distributed double pseudo-random value in the range [0, 1[
Definition at line 144 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextGaussian(), and rg_.
 {
     return rg_->nextGaussian(sigma);
 }
int RandomGenerator_C::nextInt_st (int lowVal, int highVal) static
Returns a new uniformly-distributed int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 109 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextInt(), and rg_.
 {
     return rg_->nextInt(lowVal, highVal);
 }
long RandomGenerator_C::nextLong_st (long lowVal, long highVal) static
Returns a new uniformly-distributed long int pseudo-random number in the range specified.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new int pseudo-random value in the range [lowVal, highVal]
Definition at line 119 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextLong(), and rg_.
 {
     return rg_->nextLong(lowVal, highVal);
 }
unsigned int RandomGenerator_C::nextUInt_st (void) static
Returns a new uniformly-distributed unsigned int pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned int pseudo-random value
Definition at line 104 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::nextUInt(), and rg_.
 {
     return rg_->nextUInt();
 }
unsigned long RandomGenerator_C::nextULong (void) virtual
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Implements uriVL::RandomGenerator.
Definition at line 68 of file RandomGenerator_C.cpp.
References FULL_IN_ULONG, and RES_TO_ULONG.
Referenced by nextDouble(), and nextULong_st().
 {
     unsigned long rl = rand();
     for (int i=1; i<FULL_IN_ULONG; i++)
         rl = (rl << MAX_BITS_IN_RAND) | rand();
     if (RES_TO_ULONG)
     {
         unsigned long lsb = static_cast<unsigned long>(rand()) >>
                                        (MAX_BITS_IN_RAND - RES_TO_ULONG);
         rl = (rl << RES_TO_ULONG) | lsb;
     }
     return rl;
 }
unsigned long RandomGenerator_C::nextULong_st (void) static
Returns a new uniformly-distributed unsigned long pseudo-random number in the full range of the data type.
Parameters
lowVal lower bound of the generated value range
highVal upper bound (inclusive) of the generated value range
Returns
new unsigned long pseudo-random value
Definition at line 114 of file RandomGenerator_C.cpp.
References nextULong(), and rg_.
 {
     return rg_->nextULong();
 }
void RandomGenerator_C::setSeed (long theSeed) virtual
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Implements uriVL::RandomGenerator.
Definition at line 55 of file RandomGenerator_C.cpp.
References uriVL::RandomGenerator::INT_IS_LONG, and seed_.
Referenced by RandomGenerator_C(), and setSeed_st().
 {
     if (INT_IS_LONG)
         seed_ = static_cast<unsigned int>(theSeed);
     else
     {
         //  keep the most significant bits of the time stamp to be the seed
         seed_ = static_cast<unsigned int>(theSeed >> (sizeof(long)-sizeof(int)));
     }
     srand(seed_);
 }
void RandomGenerator_C::setSeed_st (long theSeed) static
Sets a new seed for this generator.
Parameters
seed new seed value for this generator
Definition at line 99 of file RandomGenerator_C.cpp.
References rg_, and setSeed().
 {
     rg_->setSeed(theSeed);
 }
Member Data Documentation
const int RandomGenerator_C::FULL_IN_UINT = ((8*sizeof(unsigned int)) / MAX_BITS_IN_RAND) static
number of full outputs of the C generator fitting in an int
Definition at line 54 of file RandomGenerator_C.h.
const int RandomGenerator_C::FULL_IN_ULONG = ((8*sizeof(unsigned long)) / MAX_BITS_IN_RAND) static
number of full outputs of the C generator fitting in a long
Definition at line 46 of file RandomGenerator_C.h.
Referenced by nextULong().
const int RandomGenerator_C::RES_TO_UINT static
Initial value:
= ((8*sizeof(unsigned int)) -
                                            FULL_IN_UINT*MAX_BITS_IN_RAND)
number of residual bits of a output of the C generator to dd to make an int
Definition at line 58 of file RandomGenerator_C.h.
const int RandomGenerator_C::RES_TO_ULONG static
Initial value:
= ((8*sizeof(unsigned long)) -
                                             FULL_IN_ULONG*MAX_BITS_IN_RAND)
number of residual bits of a output of the C generator to dd to make a long
Definition at line 50 of file RandomGenerator_C.h.
Referenced by nextULong().
RandomGenerator_C * RandomGenerator_C::rg_ = new RandomGenerator_C() static private
The unique object of this class, stored as a static member.
Definition at line 162 of file RandomGenerator_C.h.
Referenced by nextDouble_st(), nextFloat_st(), nextGaussian_st(), nextInt_st(), nextLong_st(), nextUInt_st(), nextULong_st(), and setSeed_st().
unsigned int uriVL::RandomGenerator_C::seed_ private
the generator's seed
Definition at line 166 of file RandomGenerator_C.h.
Referenced by setSeed().
The documentation for this class was generated from the following files:
RandomGenerator_C.h
RandomGenerator_C.cpp