URIVisionLibrary: uriVL::FeatureDetector Class Reference
uriVL::FeatureDetector Class Reference abstract
FeatureDetector class.
#include <FeatureDetector.h>
Public Member Functions
FeatureDetector (void)
Constructor.
FeatureDetector (const ImageRect *rect)
Constructor.
virtual ~FeatureDetector (void)
Destructor.
const ImageRect * getSearchRect (void) const
Returns a pointer to the ImageRect on which this object is operating.
void setSearchRect (const ImageRect *rect)
Assigns a (new) search rectangle to this object.
virtual ImageFeature * findFeatureAbout (const RasterImage *img, const ImagePoint *searchStart, const ImageRect *searchRect=NULL)=0
Find one image feature near the designated point.
virtual FeatureList * findAllFeatures (const RasterImage *img, const ImageRect *searchRect=NULL)=0
Find all image feature within a search rectangle.
Private Member Functions
FeatureDetector (const FeatureDetector &obj)
Copy constructor (disabled)
const FeatureDetector & operator= (const FeatureDetector &obj)
Copy operator: disabled.
Private Attributes
const ImageRect * searchRect_
Search rectangle on which this object operates.
Detailed Description
FeatureDetector class.
Definition at line 38 of file FeatureDetector.h.
Constructor & Destructor Documentation
FeatureDetector::FeatureDetector (void)
Constructor.
Initializes the instance variables
Definition at line 29 of file FeatureDetector.cpp.
         :       searchRect_(NULL)
 {
 }
FeatureDetector::FeatureDetector (const ImageRect * rect)
Constructor.
Defines the sesrch rectangle. This version of the constructor may be needed for Initializes the instance variables
Parameters
rect defines the dimensions of the search
Definition at line 35 of file FeatureDetector.cpp.
References uriVL::ErrorReport::appendToMessage(), and setSearchRect().
         :       searchRect_(NULL)
 {
         try
         {
                 setSearchRect(rect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FeatureDetector constructor");
                 throw e;
         }
 }
FeatureDetector::~FeatureDetector (void) virtual
Destructor.
Definition at line 50 of file FeatureDetector.cpp.
References searchRect_.
 {
         if (searchRect_)
                 delete searchRect_;
 }
uriVL::FeatureDetector::FeatureDetector (const FeatureDetector & obj) private
Copy constructor (disabled)
This constructor is disabled.
Parameters
obj reference of the object to copy
Member Function Documentation
virtual FeatureList* uriVL::FeatureDetector::findAllFeatures (const RasterImage * img, const ImageRect * searchRect = NULL) pure virtual
Find all image feature within a search rectangle.
Parameters
img the image in which to search for features
searchStart start point for the search
searchRect the search rectangle. If NULL, the image's entire valid rect is used
Returns
pointer to the image feature found (NULL if none)
Implemented in uriVL::BlobFinder.
virtual ImageFeature* uriVL::FeatureDetector::findFeatureAbout (const RasterImage * img, const ImagePoint * searchStart, const ImageRect * searchRect = NULL) pure virtual
Find one image feature near the designated point.
Parameters
img the image in which to search for features
searchStart start point for the search
searchRect the search rectangle. If NULL, the image's entire valid rect is used
Returns
pointer to the image feature found (NULL if none)
Implemented in uriVL::BlobFinder.
const ImageRect* uriVL::FeatureDetector::getSearchRect (void) const inline
Returns a pointer to the ImageRect on which this object is operating.
Returns
a pointer to the ImageRect on which this object is operating
Definition at line 63 of file FeatureDetector.h.
Referenced by uriVL::ActiveContourDetector_balloon::findContour().
{
                                 return searchRect_;
                         }
const FeatureDetector& uriVL::FeatureDetector::operator= (const FeatureDetector & obj) private
Copy operator: disabled.
This operator is disabled..
Parameters
obj reference of the object to copy
void FeatureDetector::setSearchRect (const ImageRect * rect)
Assigns a (new) search rectangle to this object.
Parameters
rect new search rectangle for this object
Definition at line 67 of file FeatureDetector.cpp.
References uriVL::ErrorReport::appendToMessage(), and searchRect_.
Referenced by FeatureDetector().
 {
         try
         {
                 searchRect_ = new ImageRect(rect);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FeatureDetector::setSearchRect");
                 throw e;
         }
 }
Member Data Documentation
const ImageRect* uriVL::FeatureDetector::searchRect_ private
Search rectangle on which this object operates.
Definition at line 96 of file FeatureDetector.h.
Referenced by setSearchRect(), and ~FeatureDetector().
The documentation for this class was generated from the following files:
FeatureDetector.h
FeatureDetector.cpp