URIVisionLibrary: uriVL::LinearSolver_SOR Class Reference
uriVL::LinearSolver_SOR Class Reference
Class that implement the Successive Over-relaxation (SOR) iterative algorithm for solving SLEs.
#include <LinearSolver_SOR.h>
Public Member Functions
LinearSolver_SOR (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_SOR object.
LinearSolver_SOR (Matrix *A, bool preserveMatrix=false)
Constructor.
~LinearSolver_SOR (void)
Constructor.
void setMatrix (Matrix *A, bool preserveMatrix=false)
Assigns a new matrix to this LinearSolver.
LinearSolverRecord * solve (Matrix *b)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
LinearSolverRecord * solve (Matrix *b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
void solve (Matrix *b, LinearSolverRecord *record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Public Member Functions inherited from uriVL::LinearSolver
virtual ~LinearSolver (void)
Destructor.
Static Public Member Functions
static LinearSolverRecord * solve (Matrix *A, Matrix *B, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecord * solve (Matrix *A, Matrix *B, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
static void solve (Matrix *A, Matrix *B, LinearSolverRecord *record, int incrImprov, bool preserveMatrix=false)
Solves an SLE for the matrix and right-side term received as parameters.
Private Member Functions
LinearSolver_SOR (const LinearSolver_SOR &obj)
Copy constructor: disabled.
const LinearSolver_SOR & operator= (const LinearSolver_SOR &obj)
Copy operator: disabled.
Static Private Member Functions
static void solve_ (Matrix *A, Matrix *B, LinearSolverRecord *record, Matrix *currentX, Matrix *previousX, double *invDiag, int incrImprov, bool preserveMatrix)
Solves an SLE for the matrix and right-side term received as parameters.
static LinearSolverRecordStatus checkMatrixStatus_ (Matrix *A, double *invDiag)
Private Attributes
Matrix * A_
Matrix of the SLE.
Matrix * currentX_
Work matrix for the iterated solution.
Matrix * previousX_
Second work matrix for the iterated solution.
double * invDiag_
Array storing the inverses of diagonal elements of the system's matrix.
Static Private Attributes
static const double STOP_ITERATION_THRESHOLD = 1.E-5
Minimum value for a pivot before the matrix is considered to be ill-conditioned.
Additional Inherited Members
Protected Member Functions inherited from uriVL::LinearSolver
LinearSolver (void)
Default constructor.
LinearSolver (int nbRows, int nbCols)
Constructor: initializes the dimensions of the linear solver.
LinearSolver (Matrix *a, bool preserveMatrix=false)
Constructor: initializes the dimensions of the linear solver.
void setSingularityStatus_ (LinearSolverRecordStatus singularityStatus)
Sets the singularityStatus_.
LinearSolverRecordStatus getSingularityStatus_ (void)
Get the singularityStatus_.
int getNbRows_ (void)
Reports the number of rows of the solver's matrix.
int getNbCols_ (void)
Reports the number of rows of the solver's matrix.
void setMatrixDimensions_ (int nbRows, int nbCols)
Sets the dimensions of the solver's matrix.
int getNbStorageRows_ (void)
Reports the number of storage rows of the solver's matrix.
int getNbStorageCols_ (void)
Reports the number of storage rows of the solver's matrix.
void setMatrixStorageDimensions_ (int nbRows, int nbCols)
Sets the storage dimensions of the solver's matrix.
bool getMatrixIsLocal_ (void)
Reports whether the solver keeps a local copy of the SLE's matrix.
void setMatrixIsLocal_ (bool matrixIsLocal)
Sets whether the solver keeps a local copy of the SLE's matrix.
Detailed Description
Class that implement the Successive Over-relaxation (SOR) iterative algorithm for solving SLEs.
Important note about LinearSolver classes: These classes have been built for speed, not for OOP orthodoxy. We try to minimize as much as possible the number of malloc/delete operations. The default behavior of most functions in these classes is to only keep references to the SLE's matrix, not copies of it, and to perform claculations directly in that matrix (destructive behavior). If this behavior is not desirable for your application, then call the function with the parameter preserveMatrix set to true, when available.
Author
jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 40 of file LinearSolver_SOR.h.
Constructor & Destructor Documentation
LinearSolver_SOR::LinearSolver_SOR (int nbRows, int nbCols)
Space is allocated for a new LinearSolver_SOR object.
That matrix must have as many rows as it has columns otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
nbRows the maximum number of rows in the matrix
nbCols the maximum number of columns in the matrix
Definition at line 34 of file LinearSolver_SOR.cpp.
References A_, FAIL_CONDITION, uriVL::kInvalidParameterError, and uriVL::LinearSolver::setMatrixIsLocal_().
         :   LinearSolver(nbRows, nbCols),
                         //
                         A_(new Matrix(nbRows, nbCols)),
                         currentX_(NULL),
                         previousX_(NULL),
                         invDiag_(NULL)
 {
     if (nbRows != nbCols)
     {
                 delete A_;
         FAIL_CONDITION( true,
                         kInvalidParameterError,
                         "Nonsquare SLE assigned to a LinearSolver_SOR");
     }
         setMatrixIsLocal_(true);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LinearSolver_SOR constructor");
         throw e;
 }
LinearSolver_SOR::LinearSolver_SOR (Matrix * A, bool preserveMatrix = false)
Constructor.
A LinearSolver_SOR is created for a specific matrix. That matrix must be square otherwise the call will fail (throw an exception or make an assert call depending on the application settings). Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Definition at line 58 of file LinearSolver_SOR.cpp.
References A_, checkMatrixStatus_(), FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), invDiag_, uriVL::kInvalidParameterError, uriVL::kNullParameterError, and uriVL::LinearSolver::setSingularityStatus_().
         :   LinearSolver(A, preserveMatrix),
                         //
                         A_(preserveMatrix ? new Matrix(A) : A),
                         currentX_(NULL),
                         previousX_(NULL),
                         invDiag_(NULL)
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_SOR");
         int nbRows = A->getNbRows();
         int nbCols = A->getNbCols();
         if (nbRows != nbCols)
         {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Nonsquare matrix assigned to a LinearSolver_SOR");
         }
         invDiag_ = new double[nbRows];
         setSingularityStatus_(checkMatrixStatus_(A_, invDiag_));
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LinearSolver_SOR constructor");
         throw e;
 }
LinearSolver_SOR::~LinearSolver_SOR (void)
Constructor.
A LinearSolver_LU is created for a specific dimension of the SLE and number of columns of the right-side term. This is the version of the constructor to use if you are going to always operate in destructive mode and are going to request a couple of steps of incremental improvement of the solution. Only create a LinearSolver if you are going to reuse the same matrix for different right-side terms, or at least matrices with the same dimensions. Otherwise, just use the static solve function
Parameters
n dimension of the SLE
nbRighSideCols number of columns of the right-side term (if known in advance.Destructor
Definition at line 102 of file LinearSolver_SOR.cpp.
References A_, currentX_, uriVL::LinearSolver::getMatrixIsLocal_(), invDiag_, and previousX_.
 {
         if (getMatrixIsLocal_() && (A_ != NULL))
                 delete A_;
         if (currentX_ != NULL)
                 delete currentX_;
         if (previousX_ != NULL)
                 delete previousX_;
         if (invDiag_ != NULL)
                 delete []invDiag_;
 }
LinearSolver_SOR::LinearSolver_SOR (const LinearSolver_SOR & obj) private
Copy constructor: disabled.
Parameters
obj reference to the object to copy
Definition at line 87 of file LinearSolver_SOR.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :   LinearSolver(),
                         //
                         A_(NULL),
                         currentX_(NULL),
                         previousX_(NULL),
                         invDiag_(NULL)
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_SOR copy constructor not inplemented");
 }
Member Function Documentation
LinearSolverRecordStatus LinearSolver_SOR::checkMatrixStatus_ (Matrix * A, double * invDiag) static private
Definition at line 518 of file LinearSolver_SOR.cpp.
References uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbRows(), uriVL::REGULAR_MATRIX, and uriVL::SINGULAR_MATRIX.
Referenced by LinearSolver_SOR(), setMatrix(), and solve().
 {
         const double* const* a = A->getMatrix();
     const int nbRows = A->getNbRows();
         bool isSingular = false;
         for (int i=0; (i<nbRows) && !isSingular; i++)
                 if (a[i][i] != 0.L)
                         invDiag[i] = 1.0L / a[i][i];
                 else
                         isSingular = true;
         if (isSingular)
                 return SINGULAR_MATRIX;
         else
                 return REGULAR_MATRIX;
 }
const LinearSolver_SOR & LinearSolver_SOR::operator= (const LinearSolver_SOR & obj) private
Copy operator: disabled.
Parameters
obj reference to the object to copy
Definition at line 118 of file LinearSolver_SOR.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION (true,
                                         kFunctionNotImplemented,
                                         "LinearSolver_SOR copy opertator not inplemented");
         return *this;
 }
void LinearSolver_SOR::setMatrix (Matrix * A, bool preserveMatrix = false) virtual
Assigns a new matrix to this LinearSolver.
This call only makes sense if the new matrix has the same dimensions as the previous one (it then saves a destruction and an allocation of a matrix). Otherwise, just use the static solve function.
Important: If you don't set preserveMatrix true, then the LinearSolver only stores a reference to matrix it receives as a parameter. It will do calculations in this matrix.
You cannot delete it before you call the solve function,
The matrix's elements will be modified (destructive behavior)
Parameters
A the matrix of SLEs to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
Implements uriVL::LinearSolver.
Definition at line 128 of file LinearSolver_SOR.cpp.
References A_, checkMatrixStatus_(), FAIL_CONDITION, uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), invDiag_, uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolver::setMatrixDimensions_(), uriVL::LinearSolver::setMatrixIsLocal_(), uriVL::LinearSolver::setMatrixStorageDimensions_(), and uriVL::LinearSolver::setSingularityStatus_().
 {
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_SOR");
     const int nbRows = A->getNbRows(),
               nbCols = A->getNbCols();
     FAIL_CONDITION( nbRows != nbCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_SOR");
         if (invDiag_ != NULL)
                 if (A_->getNbRows() != nbRows) {
                         delete []invDiag_;
                         invDiag_ = new double[nbRows];
                 }
     setMatrixDimensions_(nbRows, nbRows);
     //  If we were already storing a local copy of a previous SLE's matrix,
     //  then we may have to do delete/reallocate that local copy
     if (getMatrixIsLocal_())
     {
         if (preserveMatrix)
         {
             //  If the new matrix has different dimensions from the old one, we
             //  must delete & reallocate LU_ and the permutation array
             if ((A_->getNbRows() != nbRows) || (A_->getNbCols() != nbCols))
             {
                 if (A_ != NULL)
                     delete A_;
                 A_ = new Matrix(A);
             }
             //  if the dimensions did not change we simply copy the data
             else
                 (*A_) = (*A);
             setMatrixStorageDimensions_(nbRows, nbRows);
         }
         //  If the matrix was local, but should not be anymore, we simply delete the
         //  current matrix and store the reference to the new one
         else
         {
             delete A_;
             A_ = A;
         }
     }
     else
     {
         if (preserveMatrix)
             A_ = new Matrix(A);
         else
             A_  =A;
     }
     setMatrixIsLocal_(preserveMatrix);
         invDiag_ = new double[nbRows];
         setSingularityStatus_(checkMatrixStatus_(A_, invDiag_));
 }
LinearSolverRecord * LinearSolver_SOR::solve (Matrix * b) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 195 of file LinearSolver_SOR.cpp.
Referenced by solve().
 {
     return solve(B, 0);
 }
LinearSolverRecord * LinearSolver_SOR::solve (Matrix * b, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 200 of file LinearSolver_SOR.cpp.
References FAIL_CONDITION, uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::LinearSolverRecord::sol, and solve().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_SOR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( nbRows != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
     solve(B, record, incrImprov);
     return record;
 }
void LinearSolver_SOR::solve (Matrix * b, LinearSolverRecord * record) virtual
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Note that this version of the function uses the solution matrix stored by the LinearSolverRecord received as parameter as an initial state for the iteration.
Parameters
b the reigh-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
Implements uriVL::LinearSolver.
Definition at line 222 of file LinearSolver_SOR.cpp.
References solve().
 {
     solve(B, record, 0);
 }
void LinearSolver_SOR::solve (Matrix * b, LinearSolverRecord * record, int incrImprov)
Solves the SLE for the matrix assigned through the constructor or through a call to setMatrix and the matrix right-side term received as parameter.
Note that this version of the function uses the solution matrix stored by the LinearSolverRecord received as parameter as an initial state for the iteration.
Parameters
b the reigh-side term of the SLE to solve
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
record stores the solution to the SLe and indication about the matrix's regularity.
Definition at line 227 of file LinearSolver_SOR.cpp.
References A_, FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::LinearSolver::getMatrixIsLocal_(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LinearSolver::getNbRows_(), uriVL::LinearSolver::getSingularityStatus_(), uriVL::ILL_CONDITIONED_MATRIX, invDiag_, uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::R_W_ACCESS, uriVL::SINGULAR_MATRIX, uriVL::LinearSolverRecord::sol, solve_(), and uriVL::LinearSolverRecord::status.
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term sent to a LinearSolver_SOR");
     FAIL_CONDITION( record == NULL,
                     kNullParameterError,
                     "Null LinearSolverRecord term sent to a LinearSolver_SOR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( nbRows != getNbRows_(),
                     kInvalidParameterError,
                     "Right-side term's dimensions don't match that of the matrix");
     Matrix* X = record->sol;
     //  if the solution was not allocated we do it now
     if (X == NULL)
     {
         if (nbCols == 1)
             X = record->sol = new ColumnVector(nbRows);
         else
             X = record->sol = new Matrix(nbRows, nbCols);
                 double* const* x = X->getMatrix(R_W_ACCESS);
                 for (int i=0; i<nbRows; i++)
                         for (int j=0; j<nbCols; j++)
                                 x[i][j] = 0.L;
     }
     else
     {
         FAIL_CONDITION( nbRows != X->getNbRows(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the SLE");
         FAIL_CONDITION( nbCols != X->getNbCols(),
                         kInvalidParameterError,
                         "Solution's dimensions don't match that of the right-side term");
     }
         record->status = getSingularityStatus_();
     if ((record->status != SINGULAR_MATRIX) && (record->status != ILL_CONDITIONED_MATRIX))
         {
                 Matrix* currentX = NULL;
                 Matrix* previousX = NULL;
         if (nbCols == 1)
                 {
                         currentX = new ColumnVector(nbRows);
                         previousX = new ColumnVector(nbRows);
                 }
         else
                 {
                         currentX = new Matrix(nbRows, nbCols);
                         previousX = new Matrix(nbRows, nbCols);
                 }
                 solve_(A_, B, record, currentX, previousX, invDiag_, getMatrixIsLocal_(), incrImprov);
                 delete currentX;
                 delete previousX;
         }
 }
LinearSolverRecord * LinearSolver_SOR::solve (Matrix * A, Matrix * B, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 294 of file LinearSolver_SOR.cpp.
References solve().
 {
     return solve(A, B, 0, preserveMatrix);
 }
LinearSolverRecord * LinearSolver_SOR::solve (Matrix * A, Matrix * B, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Returns
a LinearSolverRecord object that stores the solution to the SLE and indication about the matrix's regularity.
Definition at line 300 of file LinearSolver_SOR.cpp.
References FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::R_W_ACCESS, uriVL::LinearSolverRecord::sol, and solve().
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_SOR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_SOR");
     const int aRows = A->getNbRows(),
               aCols = A->getNbCols();
     FAIL_CONDITION( aRows != aCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_SOR");
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_SOR");
     LinearSolverRecord *record = new LinearSolverRecord();
     if (nbCols == 1)
         record->sol = new ColumnVector(nbRows);
     else
         record->sol = new Matrix(nbRows, nbCols);
         double* const* x = record->sol->getMatrix(R_W_ACCESS);
         for (int i=0; i<nbRows; i++)
                 for (int j=0; j<nbCols; j++)
                         x[i][j] = 0.L;
     solve(A, B, record, preserveMatrix, incrImprov);
     return record;
 }
void LinearSolver_SOR::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Note that this version of the function uses the solution matrix stored by the LinearSolverRecord received as parameter as an initial state for the iteration.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 336 of file LinearSolver_SOR.cpp.
References solve().
 {
     solve(A, B, record, 0, preserveMatrix);
 }
void LinearSolver_SOR::solve (Matrix * A, Matrix * B, LinearSolverRecord * record, int incrImprov, bool preserveMatrix = false) static
Solves an SLE for the matrix and right-side term received as parameters.
Note that this version of the function uses the solution matrix stored by the LinearSolverRecord received as parameter as an initial state for the iteration.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity.
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode).
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough.
Definition at line 343 of file LinearSolver_SOR.cpp.
References checkMatrixStatus_(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::ILL_CONDITIONED_MATRIX, uriVL::kInvalidParameterError, uriVL::kNullParameterError, uriVL::R_W_ACCESS, uriVL::SINGULAR_MATRIX, uriVL::LinearSolverRecord::sol, solve_(), and uriVL::LinearSolverRecord::status.
 {
     FAIL_CONDITION( B == NULL,
                     kNullParameterError,
                     "Null right-side term assigned to a LinearSolver_SOR");
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
     FAIL_CONDITION( A == NULL,
                     kNullParameterError,
                     "Null matrix assigned to a LinearSolver_SOR");
     const int aRows = A->getNbRows(),
               aCols = A->getNbCols();
     FAIL_CONDITION( aRows != aCols,
                     kInvalidParameterError,
                     "Nonsquare matrix assigned to a LinearSolver_SOR");
     FAIL_CONDITION( aRows != nbRows,
                     kInvalidParameterError,
                     "Matrix and right-side term dimensions dont match for LinearSolver_SOR");
     //  was the record properly created?
     if (record->sol != NULL)
     {
         FAIL_CONDITION( (nbRows != record->sol->getNbRows()) ||
                         (nbCols != record->sol->getNbCols()),
                         kInvalidParameterError,
                         "right-side term and solution's dimensions dont match for LinearSolver_SOR");
     }
     //  if the solution was not allocated we do it now.  In any case, we need to alocate
         //      the "current" and "provious" iterated solutions
     else
     {
         if (nbCols == 1)
                 {
             record->sol = new ColumnVector(nbRows);
                 }
         else
                 {
             record->sol = new Matrix(nbRows, nbCols);
                 }
                 double* const* x = record->sol->getMatrix(R_W_ACCESS);
                 for (int i=0; i<nbRows; i++)
                         for (int j=0; j<nbCols; j++)
                                 x[i][j] = 0.L;
    }
         Matrix* currentX = NULL;
         Matrix* previousX = NULL;
         if (nbCols == 1)
         {
                 currentX = new ColumnVector(nbRows);
                 previousX = new ColumnVector(nbRows);
         }
         else
         {
                 currentX = new Matrix(nbRows, nbCols);
                 previousX = new Matrix(nbRows, nbCols);
         }
         double* invDiag = new double[nbRows];
         record->status = checkMatrixStatus_(A, invDiag);
     if ((record->status != SINGULAR_MATRIX) && (record->status != ILL_CONDITIONED_MATRIX))
         {
                 solve_(A, B, record, currentX, previousX, invDiag, preserveMatrix, incrImprov);
         }
         delete currentX;
         delete previousX;
         delete []invDiag;
 }
void LinearSolver_SOR::solve_ (Matrix * A, Matrix * B, LinearSolverRecord * record, Matrix * currentX, Matrix * previousX, double * invDiag, int incrImprov, bool preserveMatrix) static private
Solves an SLE for the matrix and right-side term received as parameters.
Parameters
A the matrix of the SLE to solve
B the right-side term of the SLE to solve
record stores the solution to the SLe and indication about the matrix's regularity
currentX one of two matrices used to compute the iterative solution
proviousX one of two matrices used to compute the iterative solution
invDiag 1D array storing the inverses of the matrix's diagonal elements
incrImprov the number of steps of incremental improvement of the solution (by solving for corrective term with residual as right-side term). It is highly recommended tp apply at least 1 such step. 2-3 should be plenty enough
preserveMatrix when true, the LinearSolver will keep and work on a copy of the matrix (non-destructive mode)
Definition at line 423 of file LinearSolver_SOR.cpp.
References uriVL::Matrix::getMatrix(), uriVL::Matrix::getNbCols(), uriVL::Matrix::getNbRows(), uriVL::LINEAR_SOLVER_FAILED, uriVL::LINEAR_SOLVER_SUCCEDED, uriVL::R_W_ACCESS, uriVL::LinearSolverRecord::sol, uriVL::LinearSolverRecord::status, and STOP_ITERATION_THRESHOLD.
Referenced by solve().
 {
     const int nbRows = B->getNbRows(),
               nbCols = B->getNbCols();
         //      if one of the diagonal elements is 0 we can't solve the SLE
         const double* const* a = A->getMatrix();
         double*const* x = record->sol->getMatrix(R_W_ACCESS);
         double*const* xk = currentX->getMatrix(R_W_ACCESS);
         double*const* xkp1 = previousX->getMatrix(R_W_ACCESS);
         const double*const* b = B->getMatrix(R_W_ACCESS);
         //      The initial state is the one provided by the record passed as parameter
         for (int i=0; i<nbRows; i++)
                 for (int j=0; j<nbCols; j++)
                         xkp1[i][j] = x[i][j];
         int nbIterIncrDist = 0;
         double prevDist = 1.0E10;
         bool notConverged = true;
         bool notDiverged = true;
         do
         {
                 //      swap the "current" and "previous" states
                 {
                         double* const* temp = xk;
                         xk = xkp1;
                         xkp1 = temp;
                 }
                 for (int i=0; i<nbRows; i++)
                 {
                         for (int j=0; j<nbCols; j++)
{
                                 xkp1[i][j] = b[i][j];
                                 for (int l=0; l<nbRows; l++)
                                         if (l != i)
                                                 xkp1[i][j] -= a[i][l]*xk[l][j];
                                 xkp1[i][j] *= invDiag[i];
                         }
                 }
                 //      compute the change between initial and previous state
                 //      We use infinity norm: the distance for all terms must be
                 //      less than the threshold
                 double dist = 0.L;
                 for (int i=0; i<nbRows; i++)
                 {
                         for (int j=0; j<nbCols; j++)
{
                                 double dx = fabs(xkp1[i][j] - xk[i][j]);
                                 if (dx > dist)
                                         dist = dx;
                         }
                 }
                 if (dist < STOP_ITERATION_THRESHOLD)
                         notConverged = false;
                 else if (dist > prevDist)
                 {
                         nbIterIncrDist++;
                         if (nbIterIncrDist > 6)
                                 notDiverged = false;
                 }
                 else
                 {
                         nbIterIncrDist = 0;
                 }
         }
         while (notConverged && notDiverged);
         if (notDiverged)
         {
                 record->status = LINEAR_SOLVER_SUCCEDED;
                 //      after we leave the loop, copy the last computed state into the record to return
                 for (int i=0; i<nbRows; i++)
                         for (int j=0; j<nbCols; j++)
                                 x[i][j] = xkp1[i][j];
         }
         else
         {
                 record->status = LINEAR_SOLVER_FAILED;
         }
 }
Member Data Documentation
Matrix* uriVL::LinearSolver_SOR::A_ private
Matrix of the SLE.
Only an alias if preserveMatrix was false.
Definition at line 226 of file LinearSolver_SOR.h.
Referenced by LinearSolver_SOR(), setMatrix(), solve(), and ~LinearSolver_SOR().
Matrix* uriVL::LinearSolver_SOR::currentX_ private
Work matrix for the iterated solution.
Definition at line 230 of file LinearSolver_SOR.h.
Referenced by ~LinearSolver_SOR().
double* uriVL::LinearSolver_SOR::invDiag_ private
Array storing the inverses of diagonal elements of the system's matrix.
Definition at line 238 of file LinearSolver_SOR.h.
Referenced by LinearSolver_SOR(), setMatrix(), solve(), and ~LinearSolver_SOR().
Matrix* uriVL::LinearSolver_SOR::previousX_ private
Second work matrix for the iterated solution.
Definition at line 234 of file LinearSolver_SOR.h.
Referenced by ~LinearSolver_SOR().
const double LinearSolver_SOR::STOP_ITERATION_THRESHOLD = 1.E-5 static private
Minimum value for a pivot before the matrix is considered to be ill-conditioned.
Definition at line 222 of file LinearSolver_SOR.h.
Referenced by solve_().
The documentation for this class was generated from the following files:
LinearSolver_SOR.h
LinearSolver_SOR.cpp