URIVisionLibrary: uriVL::PolynomialFunction1D Class Reference
uriVL::PolynomialFunction1D Class Reference
Class that implements 1-dimensional polynomial functions and their derivatives.
#include <PolynomialFunction1D.h>
Public Member Functions
PolynomialFunction1D (int n, const double *a)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
PolynomialFunction1D (int n, const double *a, const double xMin, const double xMax)
Creates a new function defined over the interval ]xMin, xMax[.
~PolynomialFunction1D (void)
Destructor.
double func (double x) const
Evaluates the function at the point specified.
double dfunc (double x) const
Evaluates the first derivative of the function at the point specified.
double d2func (double x) const
Evaluates the second derivative of the function at the point specified.
double dnfunc (double x, int n) const
Evaluates the nth derivative of the function at the point specified.
bool firstDerivativeIsImplemented (void) const
Indicates that the function implements its own first derivative function.
bool secondDerivativeIsImplemented (void) const
Indicates whether the function implements its own second derivative function.
Public Member Functions inherited from uriVL::Function1D
Function1D (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Function1D (double xMin, double xMax)
Creates a new function defined over the interval ]xMin, xMax[.
virtual ~Function1D (void)
Destructor.
double dfunc (double x, int n) const
Evaluates the first derivative of the function at the point specified.
double getLowerBound (void) const
returns the lower bound of this function's domain of definition
double getUpperBound (void) const
returns the upper bound of this function's domain of definition
bool isDefinedAt (double x) const
Indicates whther a point is within the domain of definition of this function.
Private Member Functions
void initCoeffArray_ (int n, const double *a)
Initializes the array of coefficients of the polynomial and of its derivatives.
Private Attributes
int n_
degree of the polynomial
double ** a_
array of coefficients of the polynomial and of all of its derivatives
Detailed Description
Class that implements 1-dimensional polynomial functions and their derivatives.
I guess we could store the arrays of coefficients for the first and second derivatives of the function. Right now this is not really needed, so... pass.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file PolynomialFunction1D.h.
Constructor & Destructor Documentation
PolynomialFunction1D::PolynomialFunction1D (int n, const double * a)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Parameters
n degree of the polynomial function
a array of n+1 coefficients of the polynomial function (array index corresponds to power of the monomial)
Definition at line 19 of file PolynomialFunction1D.cpp.
References initCoeffArray_().
     :   Function1D()
 {
     initCoeffArray_(n, a);
 }
PolynomialFunction1D::PolynomialFunction1D (int n, const double * a, const double xMin, const double xMax)
Creates a new function defined over the interval ]xMin, xMax[.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
n degree of the polynomial function
a array of n+1 coefficients of the polynomial function (array index corresponds to power of the monomial)
Definition at line 26 of file PolynomialFunction1D.cpp.
References initCoeffArray_().
     :   Function1D(xMin, xMax)
 {
     initCoeffArray_(n, a);
 }
PolynomialFunction1D::~PolynomialFunction1D (void)
Destructor.
Definition at line 32 of file PolynomialFunction1D.cpp.
 {
 }
Member Function Documentation
double PolynomialFunction1D::d2func (double x) const virtual
Evaluates the second derivative of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the second derivative of the function at x
Reimplemented from uriVL::Function1D.
Definition at line 66 of file PolynomialFunction1D.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D::dfunc2");
         int mdeg = n_ - 2;
         double val = a_[2][mdeg];
         for (int i=mdeg-1; i>=0; i--)
                 val = val*x + a_[2][i];
         return val;
 }
double PolynomialFunction1D::dfunc (double x) const virtual
Evaluates the first derivative of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the first derivative of the function at x
Reimplemented from uriVL::Function1D.
Definition at line 52 of file PolynomialFunction1D.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D::dfunc");
         int mdeg = n_ - 1;
         double val = a_[1][mdeg];
         for (int i=mdeg-1; i>=0; i--)
                 val = val*x + a_[1][i];
         return val;
 }
double PolynomialFunction1D::dnfunc (double x, int n) const
Evaluates the nth derivative of the function at the point specified.
Parameters
x where the function should be evaluated
n the order of the derivative
Returns
the nth derivative of the function at x
Definition at line 80 of file PolynomialFunction1D.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, uriVL::kInvalidParameterError, and n_.
Referenced by main().
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D::dfuncn");
     FAIL_CONDITION( m < 0,
                     kInvalidParameterError,
                     "Negative derivative order passed to PolynomialFunction1D::dfuncn");
         double val = 0.L;
     if (m <= n_)
     {
         int mdeg = n_ - m;
         val = a_[m][mdeg];
         for (int i=mdeg-1; i>=0; i--)
             val = val*x + a_[m][i];
     }
         return val;
 }
bool uriVL::PolynomialFunction1D::firstDerivativeIsImplemented (void) const inline virtual
Indicates that the function implements its own first derivative function.
Returns
true
Implements uriVL::Function1D.
Definition at line 91 of file PolynomialFunction1D.h.
{
                                 return true;
                         }
double PolynomialFunction1D::func (double x) const virtual
Evaluates the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implements uriVL::Function1D.
Definition at line 40 of file PolynomialFunction1D.cpp.
References a_, FAIL_CONDITION, uriVL::Function1D::isDefinedAt(), uriVL::kDataRangeError, and n_.
 {
     FAIL_CONDITION( !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in PolynomialFunction1D::dfunc");
     double val = a_[0][n_];
     for (int i=n_-1; i>=0; i--)
         val = val*x + a_[0][i];
     return val;
 }
void PolynomialFunction1D::initCoeffArray_ (int n, const double * a) private
Initializes the array of coefficients of the polynomial and of its derivatives.
Definition at line 107 of file PolynomialFunction1D.cpp.
References a_, FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, and n_.
Referenced by PolynomialFunction1D().
 {
     FAIL_CONDITION( a == NULL,
                     kNullParameterError,
                     "Null coefficient array passed to PolynomialFunction1D constructor");
     FAIL_CONDITION( n < 0,
                     kInvalidParameterError,
                     "Negative degree passed to PolynomialFunction1D constructor");
     n_ = n;
     a_ = new double*[n+1];
     for (int i=0; i<=n; i++)
     {
          if (i==0)
                 {
                         a_[0] = new double[n + 1];
             for (int j=0; j<=n; j++)
                 a_[0][j] = a[j];
         }
                 else
         {
                         int nd = n - i + 1;
                         a_[i] = new double[nd];
                     for (int j=0; j<nd; j++)
                 a_[i][j] = (j+1)*a_[i-1][j+1];
         }
     }
 }
bool uriVL::PolynomialFunction1D::secondDerivativeIsImplemented (void) const inline virtual
Indicates whether the function implements its own second derivative function.
Returns
true
Implements uriVL::Function1D.
Definition at line 99 of file PolynomialFunction1D.h.
{
                                 return true;
                         }
Member Data Documentation
double** uriVL::PolynomialFunction1D::a_ private
array of coefficients of the polynomial and of all of its derivatives
Definition at line 112 of file PolynomialFunction1D.h.
Referenced by d2func(), dfunc(), dnfunc(), func(), and initCoeffArray_().
int uriVL::PolynomialFunction1D::n_ private
degree of the polynomial
Definition at line 108 of file PolynomialFunction1D.h.
Referenced by d2func(), dfunc(), dnfunc(), func(), and initCoeffArray_().
The documentation for this class was generated from the following files:
PolynomialFunction1D.h
PolynomialFunction1D.cpp