URIVisionLibrary: uriVL::ZeroCrossingDetector Class Reference
uriVL::ZeroCrossingDetector Class Reference
ZeroCrossingDetector class.
#include <ZeroCrossingDetector.h>
Public Member Functions
ZeroCrossingDetector (void)
Default constructor.
~ZeroCrossingDetector (void)
Destructor.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params, const ImageRect *theRect)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const char *params, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, const char *params, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Public Member Functions inherited from uriVL::Labeler
virtual ~Labeler (void)
Destructor.
virtual LabelRaster * applyTo (const RasterImage *imgIn, const char *params, bool connectNeighbor)=0
Applies this operator to an image, returns the result as a LabelRaster.
virtual LabelRaster * applyTo (const RasterImage *imgIn, const char *params, const ImageRect *theRect, bool connectNeighbor)=0
Applies this operator to an image, returns the result as a LabelRaster.
virtual void applyInto (const RasterImage *imgIn, const char *params, LabelRaster *labelOut, bool connectNeighbor)=0
Applies this operator to an image, writes the result into a LabelRaster provided as parameter.
virtual void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor)=0
Applies this operator to an image, writes the result into a LabelRaster provided as parameter.
Static Public Member Functions
static LabelRaster * applyTo_st (const RasterImage *imgIn)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
static LabelRaster * applyTo_st (const RasterImage *imgIn, const ImageRect *theRect)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
static void applyInto_st (const RasterImage *imgIn, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
static void applyInto_st (const RasterImage *imgIn, const ImageRect *theRect, LabelRaster *labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
static void applyInto_st (const RasterImage *imgIn, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
static void applyInto_st (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
static void showSignAsColor (const RasterImage_gray_F *imgIn, RasterImage_RGBa *imgOut, const unsigned char colorChoice[][3])
Displays the sign of the data in the input image under the form of a color raster image (RGBa).
Static Private Member Functions
static void applyInto_ (const RasterImage_gray *imgIn, const ImageRect *theRect, LabelRaster *labelOut)
This is the function that actually does the job, trusting the caller functions to have done all the data type and validity checking.
static void applyInto_ (const RasterImage_gray *imgIn, const ImageRect *theRect, RasterImage *imgOut)
This is the function that actually does the job, trusting the caller functions to have done all the data type and validity checking.
Additional Inherited Members
Protected Member Functions inherited from uriVL::Labeler
Labeler (void)
default constructor
Labeler (int theWidth, int theHeight)
constructor
Protected Attributes inherited from uriVL::Labeler
LabelRaster * tempLabel_
Detailed Description
ZeroCrossingDetector class.
This class is implemented as an instantiable static class. It is instantiable because it may be useful at some point to typecast a ZeroCrossingDetector object as a labeler.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file ZeroCrossingDetector.h.
Constructor & Destructor Documentation
ZeroCrossingDetector::ZeroCrossingDetector (void)
Default constructor.
Definition at line 26 of file ZeroCrossingDetector.cpp.
 {}
ZeroCrossingDetector::~ZeroCrossingDetector (void)
Destructor.
Definition at line 30 of file ZeroCrossingDetector.cpp.
 {}
Member Function Documentation
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const char * params, LabelRaster * labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 126 of file ZeroCrossingDetector.cpp.
 {
     applyInto(imgIn, labelOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, LabelRaster * labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 141 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ZeroCrossingDetector::applyTo");
     applyInto((RasterImage_gray* ) imgIn, imgIn->getValidRect(), labelOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, LabelRaster * labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 133 of file ZeroCrossingDetector.cpp.
References applyInto().
Referenced by applyInto().
 {
     applyInto(imgIn, theRect, labelOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const ImageRect * theRect, LabelRaster * labelOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 157 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, labelOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const char * params, RasterImage * imgOut) virtual
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 177 of file ZeroCrossingDetector.cpp.
 {
     applyInto(imgIn, imgOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, RasterImage * imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Definition at line 190 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, imgIn->getValidRect(), imgOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, RasterImage * imgOut) virtual
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
theRect the rectangle within which to apply the labeler
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 184 of file ZeroCrossingDetector.cpp.
 {
     applyInto(imgIn, theRect, imgOut);
 }
void ZeroCrossingDetector::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut)
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Definition at line 205 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null RasterImage as destination in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, imgOut);
 }
void ZeroCrossingDetector::applyInto_ (const RasterImage_gray * imgIn, const ImageRect * theRect, LabelRaster * labelOut) static private
This is the function that actually does the job, trusting the caller functions to have done all the data type and validity checking.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 309 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::floatRasterIsReference(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::R_W_ACCESS, uriVL::ImageRect::removeAllAround(), and uriVL::LabelRaster::setValidRect().
 {
     ImageRect* usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     ImageRect* destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid data rect and output rectangles must overlap");
 //     unsigned char    **gray = imgIn->getShiftedGray2D(); // unused var. -CJC
     char        **label = labelOut->getShiftedLabel2D(R_W_ACCESS);
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     int im1, ip1, jm1, jp1;
     if (imgIn->hasFloatRaster() && imgIn->floatRasterIsReference())
     {
         const float* const* frIn = (static_cast<const RasterImage_gray_F*>(imgIn))->getShiftedGrayF2D();
         im1 = iLow-1;
         ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; )
         {
             jm1 = jLow-1;
             jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; )
             {
                 if ( (frIn[im1][jm1]*frIn[ip1][jp1] < 0.f) ||
                         (frIn[im1][jp1]*frIn[ip1][jm1] < 0.f) ||
                         (frIn[i][jm1]*frIn[i][jp1] < 0.f)     ||
                         (frIn[im1][j]*frIn[ip1][j] < 0.f) )
                     label[i][j] = (char) 1;
                 else
                     label[i][j] = (char) 0;
                 jm1 = j;
                 j = jp1;
                 jp1++;
             }
             im1 = i;
             i=ip1;
             ip1++;
         }
     }
     else
     {
         const unsigned char* const* irIn = imgIn->getShiftedRaster2D();
         im1 = iLow-1;
         ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; )
         {
             jm1 = jLow-1;
             jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; )
             {
                 if ( (irIn[im1][jm1]*irIn[ip1][jp1] < 0) ||
                         (irIn[im1][jp1]*irIn[ip1][jm1] < 0) ||
                         (irIn[i][jm1]*irIn[i][jp1] < 0)     ||
                         (irIn[im1][j]*irIn[ip1][j] < 0) )
                     label[i][j] = (char) 1;
                 else
                     label[i][j] = (char) 0;
                 jm1 = j;
                 j = jp1;
                 jp1++;
             }
             im1 = i;
             i=ip1;
             ip1++;
         }
     }
     labelOut->setValidRect(destRect);
     delete usableRect;
     delete destRect;
 }
void ZeroCrossingDetector::applyInto_ (const RasterImage_gray * imgIn, const ImageRect * theRect, RasterImage * imgOut) static private
This is the function that actually does the job, trusting the caller functions to have done all the data type and validity checking.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Definition at line 395 of file ZeroCrossingDetector.cpp.
References uriVL::RasterImage_gray::copyInto(), FAIL_CONDITION, uriVL::RasterImage::floatRasterIsReference(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::RasterImage_gray::localRasterGray(), uriVL::R_W_ACCESS, uriVL::ImageRect::removeAllAround(), and uriVL::DrawableObject2D::setValidRect().
 {
     bool localGray;
     RasterImage_gray* grayOut = RasterImage_gray::localRasterGray(imgOut, &localGray);
     ImageRect* usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     ImageRect* destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid date rect and output rectangles must overlap");
     unsigned char* const* rasterOut = grayOut->getShiftedRaster2D(R_W_ACCESS);
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     int im1, ip1, jm1, jp1;
     if (imgIn->hasFloatRaster() && imgIn->floatRasterIsReference())
     {
         const float* const* frIn = (static_cast<const RasterImage_gray_F*>(imgIn))->getShiftedGrayF2D();
         im1 = iLow-1;
         ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; )
         {
             jm1 = jLow-1;
             jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; )
             {
                 if ( (frIn[im1][jm1]*frIn[ip1][jp1] < 0.f) ||
                         (frIn[im1][jp1]*frIn[ip1][jm1] < 0.f) ||
                         (frIn[i][jm1]*frIn[i][jp1] < 0.f)     ||
                         (frIn[im1][j]*frIn[ip1][j] < 0.f) )
                     rasterOut[i][j] = (unsigned char) 255;
                 else
                     rasterOut[i][j] = (unsigned char) 0;
                 jm1 = j;
                 j = jp1;
                 jp1++;
             }
             im1 = i;
             i=ip1;
             ip1++;
         }
     }
     else
     {
         const unsigned char* const* irIn = imgIn->getShiftedRaster2D();
         im1 = iLow-1;
         ip1 = iLow+1;
         for (int i=iLow; i<=iHigh; )
         {
             jm1 = jLow-1;
             jp1 = jLow+1;
             for (int j=jLow; j<=jHigh; )
             {
                 if ( (irIn[im1][jm1]*irIn[ip1][jp1] < 0) ||
                         (irIn[im1][jp1]*irIn[ip1][jm1] < 0) ||
                         (irIn[i][jm1]*irIn[i][jp1] < 0)     ||
                         (irIn[im1][j]*irIn[ip1][j] < 0) )
                     rasterOut[i][j] = (unsigned char) 255;
                 else
                     rasterOut[i][j] = (unsigned char) 0;
                 jm1 = j;
                 j = jp1;
                 jp1++;
             }
             im1 = i;
             i=ip1;
             ip1++;
         }
     }
     grayOut->setValidRect(theRect);
     if (localGray)
     {
         grayOut->copyInto(imgOut);
         delete grayOut;
     }
     delete usableRect;
     delete destRect;
 }
void ZeroCrossingDetector::applyInto_st (const RasterImage * imgIn, LabelRaster * labelOut) static
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 229 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ZeroCrossingDetector::applyTo");
     applyInto_st((RasterImage_gray* ) imgIn, imgIn->getValidRect(), labelOut);
 }
void ZeroCrossingDetector::applyInto_st (const RasterImage * imgIn, const ImageRect * theRect, LabelRaster * labelOut) static
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
This function will be overloaded by subclasses of Labeler
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
Definition at line 245 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, labelOut);
 }
void ZeroCrossingDetector::applyInto_st (const RasterImage * imgIn, RasterImage * imgOut) static
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Definition at line 265 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, imgIn->getValidRect(), imgOut);
 }
void ZeroCrossingDetector::applyInto_st (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) static
Detects the zero crossings in the input image, writes the result into the LabelRaster provided as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the labeler
imgOut a RasterImage version of the label raster obtained by applying the operator to imgIn
Definition at line 280 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kGrayRaster, uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgIn->getBaseRasterType() != kGrayRaster,
                     kInvalidRasterType,
                     "input raster in ZeroCrossingDetector::applyTo should be gray level");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null RasterImage as destination in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, imgOut);
 }
LabelRaster * ZeroCrossingDetector::applyTo (const RasterImage * imgIn, const char * params)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 43 of file ZeroCrossingDetector.cpp.
 {
     return applyTo_st(imgIn);
 }
LabelRaster * ZeroCrossingDetector::applyTo (const RasterImage * imgIn)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 48 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kRasterAllocationFailure.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION(     labelOut == NULL,
                     kRasterAllocationFailure,
                     "output LabelRaster allocation failed in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, imgIn->getValidRect(), labelOut);
     return labelOut;
 }
LabelRaster * ZeroCrossingDetector::applyTo (const RasterImage * imgIn, const char * params, const ImageRect * theRect)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
theRect the rectangle within which to apply the labeler
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 62 of file ZeroCrossingDetector.cpp.
 {
     return applyTo_st(imgIn, theRect);
 }
LabelRaster * ZeroCrossingDetector::applyTo (const RasterImage * imgIn, const ImageRect * theRect)
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
theRect the rectangle within which to apply the labeler
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 68 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, labelOut);
     return labelOut;
 }
LabelRaster * ZeroCrossingDetector::applyTo_st (const RasterImage * imgIn) static
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 90 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kRasterAllocationFailure.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION(     labelOut == NULL,
                     kRasterAllocationFailure,
                     "output LabelRaster allocation failed in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, imgIn->getValidRect(), labelOut);
     return labelOut;
 }
LabelRaster * ZeroCrossingDetector::applyTo_st (const RasterImage * imgIn, const ImageRect * theRect) static
Detects the zero crossings in the input image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params ignored by this function
theRect the rectangle within which to apply the labeler
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 104 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ZeroCrossingDetector::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster in ZeroCrossingDetector::applyTo");
     applyInto_((RasterImage_gray* ) imgIn, theRect, labelOut);
     return labelOut;
 }
void ZeroCrossingDetector::showSignAsColor (const RasterImage_gray_F * imgIn, RasterImage_RGBa * imgOut, const unsigned char colorChoice[][3]) static
Displays the sign of the data in the input image under the form of a color raster image (RGBa).
This is mostly a debugging function, to be applied to the entire image. It is very specific in the type of its parameters. The output image is colored
blue where imgIn is positive
green where imgIn is negative
red where imgIn is zero
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the color RasterImage indicating the sign of imgIn
colorChoice color attributions for positive, negative, zero
Definition at line 488 of file ZeroCrossingDetector.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getBoundRect(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kInvalidRectangleError, uriVL::kNullRasterImageError, and uriVL::R_W_ACCESS.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ZeroCrossingDetector::applyTo");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in ZeroCrossingDetector::applyTo");
     ImageRect* inRect = new ImageRect(imgIn->getValidRect());
     ImageRect* destRect = ImageRect::intersection(inRect, imgOut->getBoundRect());
     FAIL_CONDITION(     destRect == NULL,
                     kInvalidRectangleError,
                     "input image valid date rect and output rectangles must overlap");
     unsigned char* const* rgba = imgOut->getShiftedRaster2D(R_W_ACCESS);
     const float* const* fGray = imgIn->getShiftedGrayF2D();
     const int   iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             if (fGray[i][j] > 0.f)
             {
                 rgba[i][4*j] = colorChoice[0][0];
                 rgba[i][4*j+1] = colorChoice[0][1];
                 rgba[i][4*j+2] = colorChoice[0][2];
                 rgba[i][4*j+3] = (unsigned char) 255;
             }
             else if (fGray[i][j] < 0.f)
             {
                 rgba[i][4*j] = colorChoice[1][0];
                 rgba[i][4*j+1] = colorChoice[1][1];
                 rgba[i][4*j+2] = colorChoice[1][2];
                 rgba[i][4*j+3] = (unsigned char) 255;
             }
             else
             {
                 rgba[i][4*j] = colorChoice[2][0];
                 rgba[i][4*j+1] = colorChoice[2][1];
                 rgba[i][4*j+2] = colorChoice[2][2];
                 rgba[i][4*j+3] = (unsigned char) 255;
             }
         }
     }
     delete destRect;
 }
The documentation for this class was generated from the following files:
ZeroCrossingDetector.h
ZeroCrossingDetector.cpp