URIVisionLibrary: uriVL::VirtualPart3D Class Reference
uriVL::VirtualPart3D Class Reference
Implements the VirtualPart3D class.
#include <VirtualPart3D.h>
Public Member Functions
VirtualPart3D (VirtualObject3D *obj)
Contructor.
virtual ~VirtualPart3D (void)
Non-operative destructor.
std::vector< VirtualPoint3D * > * getVertices (void)
Returns the vector of virtual point3D vertices related to the virtual part.
void addVertex (VirtualPoint3D *thePoint)
Adds a vertex to the part.
void addNormalVector (NormalVector *norm)
Adds a normal vector to the part.
void addFace (VirtualFace3D *theFace)
Adds a face to the part.
void addFaceVertexInfo (int faceIndex, int vertIndex, int uvIndex, int normalIndex)
void render (int camIndex)
drawing a face to be a polygon
void setNbCameras (int n)
set number of cameras
void setDrawReferenceFrame (bool drawFrame)
void setDrawVertices (bool drawVertices)
Public Member Functions inherited from uriVL::Entity3D
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Static Public Member Functions
static void setRenderMode (VirtualRenderMode mode)
Private Member Functions
VirtualPart3D (const VirtualPart3D &obj)
Copy constructor.
const VirtualPart3D & operator= (const VirtualPart3D &obj)
Copy operator.
void drawReferenceFrame_ (void)
void setMaterial_ (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Attributes
std::vector< VirtualPoint3D * > vertices_
std::vector< VirtualFace3D * > faces_
std::vector< NormalVector * > normals_
VirtualObject3D * object_
Reference to the object this part belongs to.
bool drawFrame_
bool drawVertices_
Static Private Attributes
static VirtualRenderMode renderMode_ = INTERPOSE
Additional Inherited Members
Protected Member Functions inherited from uriVL::Entity3D
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Detailed Description
Implements the VirtualPart3D class.
A VirtualPart3D object stores reference frame of 3D object
Author
Fang Han, 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file VirtualPart3D.h.
Constructor & Destructor Documentation
VirtualPart3D::VirtualPart3D (VirtualObject3D * obj)
Contructor.
Parameters
obj the VirtualObject3D this is a part of
Definition at line 35 of file VirtualPart3D.cpp.
         :   Entity3D(),
             //
             vertices_(),
             faces_(),
             normals_(),
             object_(obj),
             //
             drawFrame_(false),
             drawVertices_(true)
 {
         //  setup the reference frames (look at VirtualPoint3D constructor)
 }
VirtualPart3D::~VirtualPart3D (void) virtual
Non-operative destructor.
The class destructor has nothing to do.
Definition at line 75 of file VirtualPart3D.cpp.
 {
 }
VirtualPart3D::VirtualPart3D (const VirtualPart3D & obj) private
Copy constructor.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 49 of file VirtualPart3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   Entity3D(),
             //
             vertices_(),
             faces_(),
             normals_(),
             object_(NULL),
             //
             drawFrame_(false),
             drawVertices_(true)
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "VirtualPart3D copy constructor not implemented");
 }
Member Function Documentation
void VirtualPart3D::addFace (VirtualFace3D * theFace)
Adds a face to the part.
If the vertices that are passed as parameters do not alrteady belong to the frame, they are added to it (this means that their part reference is set to refer to this object.
Parameters
theFace the face to add, stored as a vector of faces
Definition at line 96 of file VirtualPart3D.cpp.
References faces_.
Referenced by uriVL::VirtualObjectLoader::loadObject().
 {
  /* vector<VirtualPoint3D*>    *tempList = new vector<VirtualPoint3D*>;
     vector<VirtualPoint3D*>::iterator  iter, endList = theFace.end();
     for (iter = theFace.begin(); iter != endList; iter++)
     {
         addVertex(*iter);
         tempList->push_back(*iter);
         faces_.push_back(tempList);
     }
 */
 /*
         vector<VirtualFace3D*>::iterator  iter, endList = faces_.end();
     for (iter = faces_.begin(); iter != endList; iter++)
     {
         theFace->addNeighbor(*iter);
     }
 */
         faces_.push_back(theFace);
 }
void VirtualPart3D::addFaceVertexInfo (int faceIndex, int vertIndex, int uvIndex, int normalIndex)
Definition at line 119 of file VirtualPart3D.cpp.
References faces_, and vertices_.
Referenced by uriVL::VirtualObjectLoader::loadObject().
 {
         vector<VirtualFace3D*>::iterator face = faces_.begin();
         face[faceIndex]->addVertex(vertIndex);
         vector<VirtualPoint3D*>::iterator vertex = vertices_.begin();
         vertex[vertIndex]->addFaceInfo(faceIndex, uvIndex, normalIndex);
 }
void VirtualPart3D::addNormalVector (NormalVector * norm)
Adds a normal vector to the part.
Parameters
norm reference to the normal vector to add
Definition at line 91 of file VirtualPart3D.cpp.
References normals_.
Referenced by uriVL::VirtualObjectLoader::loadObject().
 {
         normals_.push_back(norm);
 }
void VirtualPart3D::addVertex (VirtualPoint3D * thePoint)
Adds a vertex to the part.
Parameters
thePoint reference to the vertex to add
Definition at line 84 of file VirtualPart3D.cpp.
References uriVL::Entity3D::getReferenceFrame(), uriVL::VirtualPoint3D::part_, uriVL::Entity3D::setReferenceFrame(), and vertices_.
Referenced by uriVL::VirtualPoint3D::VirtualPoint3D().
 {
         vertices_.push_back(thePoint);
     thePoint->part_ = this;
     thePoint->setReferenceFrame(getReferenceFrame());
 }
void VirtualPart3D::drawReferenceFrame_ (void) private
Definition at line 244 of file VirtualPart3D.cpp.
Referenced by render().
 {
         glBegin(GL_LINES);
                 //      Z --> red.
                 glColor3f(1.f, 0.f, 0.f);
 //              setMaterial_(1.0, 0., 0., 0., 0., 0., 0., 0., 0., 0.);
                 glVertex3f(0.f, 0.f, -0.1f);
                 glVertex3f(0.f, 0.f, 0.5f);
                 //      X --> Green
                 glColor3f(0.f, 1.f, 0.f);
 //              setMaterial_(0., 1.0, 0., 0., 0., 0., 0., 0., 0., 0.);
                 glVertex3f(-0.1f, 0.f, 0.f);
                 glVertex3f(0.5f, 0.f, 0.f);
                 //      Y --> Blue
                 glColor3f(0.f, 0.f, 1.f);
 //              setMaterial_(0., 0., 1.0, 0., 0., 0., 0., 0., 0., 0.);
                 glVertex3f(0.f, -0.1f, 0.f);
                 glVertex3f(0.f, 0.5f, 0.f);
         glEnd();
 }
vector< VirtualPoint3D * > * VirtualPart3D::getVertices (void)
Returns the vector of virtual point3D vertices related to the virtual part.
Definition at line 79 of file VirtualPart3D.cpp.
References vertices_.
Referenced by uriVL::VirtualObjectLoader::loadObject().
 {
     return &vertices_;
 }
const VirtualPart3D & VirtualPart3D::operator= (const VirtualPart3D & obj) private
Copy operator.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 66 of file VirtualPart3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "VirtualPart3D copy operator not implemented");
     return *this;
 }
void VirtualPart3D::render (int camIndex)
drawing a face to be a polygon
Parameters
camIndex the number of cameras
Definition at line 130 of file VirtualPart3D.cpp.
References uriVL::VisibilityStatus::code, uriVL::CONTACT, drawFrame_, drawReferenceFrame_(), drawVertices_, faces_, uriVL::VirtualPoint3D::getVisibility(), uriVL::VirtualPoint3D::getXYZ(), uriVL::INTERPOSE, uriVL::INVISIBLE, uriVL::VirtualPoint3D::normalIndex_, normals_, uriVL::NormalVector::nx, uriVL::NormalVector::ny, uriVL::NormalVector::nz, renderMode_, uriVL::VirtualFace3D::vertexIndex_, vertices_, and uriVL::VISIBLE.
 {
     //  ask each of the part's points to render themselves
         vector<VirtualFace3D*>::iterator        faceIter = faces_.begin();
         vector<VirtualPoint3D*>::iterator       vertIter = vertices_.begin();
         vector<NormalVector*>::iterator normIter = normals_.begin();
         int nFaces = faces_.size();
         if (renderMode_ == INTERPOSE)
         {
                 //  for each face in the part
                 for (int i=0; i<nFaces; i++)
                 {
                     VirtualFace3D *face = faceIter[i];
                         glBegin(GL_POLYGON);
                     vector<int>::iterator faceVertIter = (face->vertexIndex_).begin();
                     int  nbFaceVerts = face->vertexIndex_.size();
                     for (int j=0; j<nbFaceVerts; j++)
                     {
                         int vertIndex = faceVertIter[j];
                         VirtualPoint3D *vert = vertIter[vertIndex];
                         vector<int>::iterator faceVertNormIter = vert->normalIndex_.begin();
                         NormalVector *norm = normIter[faceVertNormIter[i]];
                         glNormal3d(norm->nx, norm->ny, norm->nz);
                                 if (vert->getVisibility(camIndex)->code == VISIBLE)
                                         glColor4f(.0f, .8f, 0.f, 1.f);
                                 else if (vert->getVisibility(camIndex)->code == INVISIBLE)
                                         glColor4f(0.f, 0.f, 1.f, 0.f);
                                 else if (vert->getVisibility(camIndex)->code == CONTACT)
                                         glColor4f(1.f, 0.f, 0.f, 0.f);
                                 else //  if (vert->getVisibility(camIndex)->code == UNKNOWN)
                                         glColor4f(0.f, 1.f, 1.f, 0.f);
                                 glVertex3dv(vert->getXYZ());
                     }
                         glEnd();
                 }
                 if (drawFrame_)
                         drawReferenceFrame_();
                 if (drawVertices_)
                 {
             //  virtual points are shaded
                 glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
                 glDepthMask (GL_TRUE);
                 glDisable (GL_BLEND);
                 vector<VirtualPoint3D *>::iterator ptIter, endVertices = vertices_.end();
                 for (ptIter = vertices_.begin(); ptIter != endVertices; ptIter++)
                     (*ptIter)->render_(camIndex);
             }
         }
     //  Rendering mode = GEOMETRY_TEST
         else
         {
             //  face edges in wireframe
                 glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
                 //  for each face in the part
                 for (int i=0; i<nFaces; i++)
                 {
                     VirtualFace3D *face = faceIter[i];
                 glColor4f(0.f, .8f, 0.f, 1.f);
                         glBegin(GL_POLYGON);
                     vector<int>::iterator faceVertIter = (face->vertexIndex_).begin();
                     int  nbFaceVerts = face->vertexIndex_.size();
                     for (int j=0; j<nbFaceVerts; j++)
                     {
                         int vertIndex = faceVertIter[j];
                         VirtualPoint3D *vert = vertIter[vertIndex];
                                 glVertex3dv(vert->getXYZ());
                     }
                         glEnd();
                 }
                 if (drawFrame_)
                         drawReferenceFrame_();
         //  virtual points are shaded
                 glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
         glDepthMask (GL_TRUE);
         glDisable (GL_BLEND);
         vector<VirtualPoint3D *>::iterator ptIter, endVertices = vertices_.end();
         for (ptIter = vertices_.begin(); ptIter != endVertices; ptIter++)
             (*ptIter)->render_(camIndex);
         }
 }
void VirtualPart3D::setDrawReferenceFrame (bool drawFrame)
Definition at line 233 of file VirtualPart3D.cpp.
References drawFrame_.
 {
         drawFrame_ = drawFrame;
 }
void VirtualPart3D::setDrawVertices (bool drawVertices)
Definition at line 238 of file VirtualPart3D.cpp.
References drawVertices_.
 {
     drawVertices_ = drawVertices;
 }
void VirtualPart3D::setMaterial_ (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine) private
Definition at line 267 of file VirtualPart3D.cpp.
 {
   float mat[4];
         mat[0] = ambRed;
         mat[1] = ambGreen;
         mat[2] = ambBlue;
         mat[3] = 1.0f;
         glMaterialfv(GL_FRONT, GL_AMBIENT, mat);
         mat[0] = difRed;
         mat[1] = difGreen;
         mat[2] = difBlue;
         glMaterialfv(GL_FRONT, GL_DIFFUSE, mat);
         mat[0] = specRed;
         mat[1] = specGreen;
         mat[2] = specBlue;
         glMaterialfv(GL_FRONT, GL_SPECULAR, mat);
         glMaterialf(GL_FRONT, GL_SHININESS, shine * 128.0f);
 }
void VirtualPart3D::setNbCameras (int n)
set number of cameras
Parameters
n the number of camera
Definition at line 224 of file VirtualPart3D.cpp.
References vertices_.
 {
     vector<VirtualPoint3D *>::iterator ptIter, endVertices = vertices_.end();
     for (ptIter = vertices_.begin(); ptIter != endVertices; ptIter++)
         (*ptIter)->setNbCameras_(n);
 }
void VirtualPart3D::setRenderMode (VirtualRenderMode mode) static
Definition at line 290 of file VirtualPart3D.cpp.
References renderMode_.
Referenced by uriVL::VirtualObject3D::setRenderMode().
 {
         renderMode_ = mode;
 }
Member Data Documentation
bool uriVL::VirtualPart3D::drawFrame_ private
Definition at line 118 of file VirtualPart3D.h.
Referenced by render(), and setDrawReferenceFrame().
bool uriVL::VirtualPart3D::drawVertices_ private
Definition at line 120 of file VirtualPart3D.h.
Referenced by render(), and setDrawVertices().
std::vector<VirtualFace3D *> uriVL::VirtualPart3D::faces_ private
Definition at line 106 of file VirtualPart3D.h.
Referenced by addFace(), addFaceVertexInfo(), and render().
std::vector<NormalVector *> uriVL::VirtualPart3D::normals_ private
Definition at line 108 of file VirtualPart3D.h.
Referenced by addNormalVector(), and render().
VirtualObject3D* uriVL::VirtualPart3D::object_ private
Reference to the object this part belongs to.
Definition at line 116 of file VirtualPart3D.h.
VirtualRenderMode VirtualPart3D::renderMode_ = INTERPOSE static private
Definition at line 122 of file VirtualPart3D.h.
Referenced by render(), and setRenderMode().
std::vector<VirtualPoint3D *> uriVL::VirtualPart3D::vertices_ private
Definition at line 104 of file VirtualPart3D.h.
Referenced by addFaceVertexInfo(), addVertex(), getVertices(), render(), and setNbCameras().
The documentation for this class was generated from the following files:
VirtualPart3D.h
VirtualPart3D.cpp