URIVisionLibrary: uriVL::ColorInverseThresholdLabeler Class Reference
uriVL::ColorInverseThresholdLabeler Class Reference
A ColorInverseThresholdLabeler segments an image into regions based on a set of predefined color threshold-based modes.
#include <ColorInverseThresholdLabeler.h>
Public Member Functions
ColorInverseThresholdLabeler (void)
ColorInverseThresholdLabeler (int theWidth, int theHeight)
constructor
~ColorInverseThresholdLabeler (void)
Destructor.
LabelRaster * applyTo (const RasterImage *imgIn, const ColorSegParams *params, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
LabelRaster * applyTo (const RasterImage *imgIn, const char *params, const ImageRect *theRect, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const char *params, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, returns the result as a LabelRaster.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor=false)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const ColorSegParams *params, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const char *params, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
void applyInto (const RasterImage *imgIn, const char *params, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Public Member Functions inherited from uriVL::Labeler
virtual ~Labeler (void)
Destructor.
Private Member Functions
void applyInto_ (const RasterImage *imgIn, const ColorSegParams *colorParams, const ImageRect *theRect, LabelRaster *labelOut, bool connectNeighbor)
Private function that applies this operator to an image, writes the result into a LabelRaster.
void applyInto_ (const RasterImage *imgIn, const ColorSegParams *Params, const ImageRect *theRect, RasterImage_RGBa *imgOut)
Private function that applies this operator to an image, writes the result into an RGBA raster image.
void connectNeighbor_ (const ImageRect *destRect, int nbRegions, LabelRaster *label, LabelRaster *tempLabel, char noMatchVal)
connect neighbor pixels based on each pixel's 8 label values
bool goodColor_ (int hue, unsigned char sat, unsigned char val, const ColorRegion *theColor)
Additional Inherited Members
Protected Member Functions inherited from uriVL::Labeler
Labeler (void)
default constructor
Labeler (int theWidth, int theHeight)
constructor
Protected Attributes inherited from uriVL::Labeler
LabelRaster * tempLabel_
Detailed Description
A ColorInverseThresholdLabeler segments an image into regions based on a set of predefined color threshold-based modes.
Note: So far this class does not do much in the way of data validation. For example, if the user defines gray level or color domains I simply assume that these domains do not overlap, without checking for it.
Author
jean-yves herve' and Fang Han, 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file ColorInverseThresholdLabeler.h.
Constructor & Destructor Documentation
ColorInverseThresholdLabeler::ColorInverseThresholdLabeler (void)
Definition at line 28 of file ColorInverseThresholdLabeler.cpp.
 {}
ColorInverseThresholdLabeler::ColorInverseThresholdLabeler (int theWidth, int theHeight)
constructor
Parameters
theWidth number of columns
theHeight number of rows
Definition at line 31 of file ColorInverseThresholdLabeler.cpp.
                                                 : Labeler(theWidth, theHeight)
 {
 }
ColorInverseThresholdLabeler::~ColorInverseThresholdLabeler (void)
Destructor.
Definition at line 40 of file ColorInverseThresholdLabeler.cpp.
 {}
Member Function Documentation
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, LabelRaster * labelOut, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 113 of file ColorInverseThresholdLabeler.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, and uriVL::kNullRasterImageError.
Referenced by applyInto().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     applyInto(imgIn, params, imgIn->getValidRect(), labelOut, connectNeighbor);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 129 of file ColorInverseThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "null LabelRaster as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ColorInverseThresholdLabeler::applyTo");
     applyInto_(imgIn, params, theRect, labelOut, connectNeighbor);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, LabelRaster * labelOut, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 150 of file ColorInverseThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, labelOut, connectNeighbor);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor = false) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 157 of file ColorInverseThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, theRect, labelOut, connectNeighbor);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, RasterImage * imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
ingOut the RasterImage obtained by applying the operator to imgIn
Definition at line 165 of file ColorInverseThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kRasterImageError, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut->getBaseRasterType() != kRGBa32Raster,
                     kRasterImageError,
                     "only RGBa images accepted in ColorInverseThresholdLabeler::applyInto so far");
     applyInto_(imgIn, params, imgIn->getValidRect(), (RasterImage_RGBa* ) imgOut);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, RasterImage * imgOut)
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
Definition at line 185 of file ColorInverseThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRasterImageError, and uriVL::kRGBa32Raster.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut == NULL,
                     kNullRasterImageError,
                     "null output RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( imgOut->getBaseRasterType() != kRGBa32Raster,
                     kRasterImageError,
                     "only RGBa images accepted in ColorInverseThresholdLabeler::applyInto so far");
     applyInto_(imgIn, params, theRect, (RasterImage_RGBa* ) imgOut);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, RasterImage * imgOut) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
ingOut the RasterImage obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 208 of file ColorInverseThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, imgOut);
 }
void ColorInverseThresholdLabeler::applyInto (const RasterImage * imgIn, const char * params, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to an image, writes the result into a RasterImage.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
theRect the rectangle within which to apply the labeler
ingOut the RasterImage obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 215 of file ColorInverseThresholdLabeler.cpp.
References applyInto().
 {
     applyInto(imgIn, (const ColorSegParams *) params, theRect, imgOut);
 }
void ColorInverseThresholdLabeler::applyInto_ (const RasterImage * imgIn, const ColorSegParams * colorParams, const ImageRect * theRect, LabelRaster * labelOut, bool connectNeighbor) private
Private function that applies this operator to an image, writes the result into a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 230 of file ColorInverseThresholdLabeler.cpp.
References uriVL::ColorSegParams::colorReg, connectNeighbor_(), FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_HSV::getShiftedHue2D(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getWidth(), goodColor_(), uriVL::kRasterDimensionsDontMatch, uriVL::RasterImage_HSV::localRasterHSV(), uriVL::ColorSegParams::nbModes, uriVL::ColorSegParams::noMatchVal, uriVL::R_W_ACCESS, uriVL::LabelRaster::setValidRect(), and uriVL::Labeler::tempLabel_.
Referenced by applyInto(), and applyTo().
 {
     bool                        localHSV;
     const RasterImage_HSV* hsvImg = RasterImage_HSV::localRasterHSV(imgIn, &localHSV);
     ColorRegion         *colorSought = params->colorReg;
     const unsigned char* const* sat2D = hsvImg->getShiftedSat2D(),
                              *const* val2D = hsvImg->getShiftedVal2D();
     char                        **label = labelOut->getShiftedLabel2D(R_W_ACCESS);
     int                         nbColors = params->nbModes;
     const int           *const* hue2D = hsvImg->getShiftedHue2D();
     int                 nbRows = hsvImg->getHeight(),
                 nbCols = hsvImg->getWidth(),
                 iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
         char            noMatchVal = params->noMatchVal;
     bool                        matchFound;
     FAIL_CONDITION( (iLow < 0) || (iHigh > nbRows) || (jLow < 0) || (jHigh > nbCols),
                     kRasterDimensionsDontMatch,
                     "Invalid rectangle dimensions for RGB to HSV conversion");
     for (int i=iLow; i<=iHigh; i++)
     {
         for (int j=jLow; j<=jHigh; j++)
         {
             matchFound = false;
             for (int k=0; (k<nbColors) && !matchFound; k++)
                 if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
                 {
                     label[i][j] = noMatchVal;
                     matchFound = true;
                 }
             if (!matchFound)
             {
                 label[i][j] = 1;
             }
         }
     }
     //  do connect-neighbor operation
     if (connectNeighbor)
     {
         bool tempLabelIsLocal = false;
         if (tempLabel_ == NULL)
         {
                 tempLabel_ = new LabelRaster(theRect);
                 tempLabelIsLocal = true;
         }
         connectNeighbor_(theRect, nbColors, labelOut, tempLabel_, noMatchVal);
         if (tempLabelIsLocal)
         {
                 delete tempLabel_;
                 tempLabel_ = NULL;
         }
     }
     //  cleanup if needed
     //  if the HSV rasters were a local copy, delete the image
     if (localHSV)
         delete hsvImg;
     labelOut->setValidRect(theRect);
 }
void ColorInverseThresholdLabeler::applyInto_ (const RasterImage * imgIn, const ColorSegParams * Params, const ImageRect * theRect, RasterImage_RGBa * imgOut) private
Private function that applies this operator to an image, writes the result into an RGBA raster image.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
labelOut the LabelRaster obtained by applying the operator to imgIn
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Definition at line 304 of file ColorInverseThresholdLabeler.cpp.
References uriVL::ColorSegParams::colorReg, uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::ColorRegion::fillColor, uriVL::ColorSegParams::fillMode, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage_HSV::getHue2D(), uriVL::ImageRect::getLeft(), uriVL::RasterImage::getPixelDepth(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::RasterImage_RGBa::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedSat2D(), uriVL::RasterImage_HSV::getShiftedVal2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getWidth(), goodColor_(), uriVL::kBlackFill, uriVL::kGrayRaster, uriVL::kIdentityFill, uriVL::kMediumGrayFill, uriVL::kOrigColorFill, uriVL::kOrigGrayFill, uriVL::kRasterDimensionsDontMatch, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kWhiteFill, uriVL::RasterImage_HSV::localRasterHSV(), uriVL::ColorSegParams::nbModes, uriVL::R_W_ACCESS, and uriVL::DrawableObject2D::setValidRect().
 {
     bool                        localHSV;
     const RasterImage_HSV* hsvImg = RasterImage_HSV::localRasterHSV(imgIn, &localHSV);
     ColorRegion* colorSought = params->colorReg;
     const unsigned char* const* sat2D = hsvImg->getShiftedSat2D(),
                                                 *const* val2D = hsvImg->getShiftedVal2D();
     unsigned char       *const* rgbaOut = imgOut->getShiftedRGBa2D(R_W_ACCESS);
     const unsigned char *const* rasterIn = imgIn->getShiftedRaster2D();
     const BaseRasterType inType = imgIn->getBaseRasterType();
     const int   inDepth = imgIn->getPixelDepth()/8;
     int                 nbColors = params->nbModes;
     const int   *const* hue2D = hsvImg->getHue2D();
     const int   nbRows = hsvImg->getHeight(),
                 nbCols = hsvImg->getWidth(),
                 iLow = theRect->getTop( ),
                 iHigh = theRect->getBottom( ),
                 jLow = theRect->getLeft( ),
                 jHigh = theRect->getRight( );
     bool                matchFound;
     int         i, j, k, l, m;
     FillingMode fillMode = params->fillMode;
     FAIL_CONDITION( (iLow < 0) || (iHigh > nbRows) || (jLow < 0) || (jHigh > nbCols),
                     kRasterDimensionsDontMatch,
                     "Invalid rectangle dimensions for RGB to HSV conversion");
     switch (fillMode)
     {
         //      The output is an unmodified copy of the input
         case kIdentityFill:
             //jyh   fix later
             //imgIn->copyInto(imgOut, imgIn->getType());
             imgIn->copyInto(imgOut);
             break;
             //  Simply overlay thresholded regions on the original image
         case kOrigColorFill:
             for (i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byte index in the input image
                 for (j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (k=0; (k<nbColors) && !matchFound; k++)
                         if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
{
                             rgbaOut[i][l++] = colorSought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = colorSought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = colorSought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             m+=inDepth;
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         switch (inType)
{
                             case kGrayRaster:
                                 // I reworked this because it generates GCC
                                 // compiler warnings, for good reasons:
                                 // http://c-faq.com/expr/evalorder1.html
 //                                 rgbaOut[i][l++] = rgbaOut[i][l++] =
 //                                                       rgbaOut[i][l++] = rasterIn[i][m++];
 //                                 rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
{
                                     unsigned char c = rasterIn[i][m++];
                                     rgbaOut[i][l++] = c;
                                     rgbaOut[i][l++] = c;
                                     rgbaOut[i][l++] = c;
                                 }
                                 break;
                             case kRGB24Raster:
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                                 break;
                             case kRGBa32Raster:
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 rgbaOut[i][l++] = rasterIn[i][m++];
                                 break;
                             default:
                                 break;
                         }
                     }
                 }
             }
             break;
             //  Display the thresholded regions over a black background
         case kBlackFill:
             for (i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 for (j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (k=0; (k<nbColors) && !matchFound; k++)
                         if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
{
                             rgbaOut[i][l++] = colorSought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = colorSought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = colorSought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = 0;
                         rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                     }
                 }
             }
             break;
             //  Display the thresholded regions over a white background
         case kWhiteFill:
             for (i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 for (j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (k=1; (k<nbColors) && !matchFound; k++)
                         if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
{
                             rgbaOut[i][l++] = colorSought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = colorSought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = colorSought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 0;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
             //  Display the thresholded regions over a medium gray background
         case kMediumGrayFill:
             for (i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 for (j=jLow, l=4*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (k=0; (k<nbColors) && !matchFound; k++)
                         if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
{
                             rgbaOut[i][l++] = colorSought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = colorSought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = colorSought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 127;
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
             //  Display the thresholded regions over the original gray-level image
         case kOrigGrayFill:
             for (i=iLow; i<=iHigh; i++)
             {
                 //  j is the pixel index in the hsv rasters
                 //  l is the byte index in the output image
                 //  m is the byet index in the input image
                 for (j=jLow, l=4*jLow, m=inDepth*jLow; j<=jHigh; j++)
                 {
                     matchFound = false;
                     for (k=0; (k<nbColors) && !matchFound; k++)
                         if (goodColor_(hue2D[i][j], sat2D[i][j], val2D[i][j], colorSought+k))
{
                             rgbaOut[i][l++] = colorSought[k].fillColor[0];  //  red
                             rgbaOut[i][l++] = colorSought[k].fillColor[1];  //  green
                             rgbaOut[i][l++] = colorSought[k].fillColor[2];  //  blue
                             rgbaOut[i][l++] = (unsigned char) 255;  //  alpha
                             matchFound = true;
                         }
                     if (!matchFound)
                     {
                         rgbaOut[i][l++] = val2D[i][j];
                         rgbaOut[i][l++] = val2D[i][j];
                         rgbaOut[i][l++] = val2D[i][j];
                         rgbaOut[i][l++] = (unsigned char) 255;
                     }
                 }
             }
             break;
         default:
             break;
     }
     //  cleanup if needed
     //  if the HSV rasters were a local copy, delete the image
     if (localHSV)
         delete hsvImg;
     imgOut->setValidRect(theRect);
 }
LabelRaster * ColorInverseThresholdLabeler::applyTo (const RasterImage * imgIn, const ColorSegParams * params, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 65 of file ColorInverseThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, and uriVL::kNullRasterImageError.
Referenced by applyTo().
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "output LabelRaster  allocation failed in ColorInverseThresholdLabeler::applyTo");
     applyInto_(imgIn, params, imgIn->getValidRect(), labelOut, connectNeighbor);
     return labelOut;
 }
LabelRaster * ColorInverseThresholdLabeler::applyTo (const RasterImage * imgIn, const ColorSegParams * params, const ImageRect * theRect, bool connectNeighbor = false)
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation
theRect the rectangle within which to apply the labeler
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Definition at line 85 of file ColorInverseThresholdLabeler.cpp.
References applyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullParameterError, uriVL::kNullRasterImageError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( imgIn == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( params == NULL,
                     kNullParameterError,
                     "null ColorSegParams as parameter in ColorInverseThresholdLabeler::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "null ImageRect as parameter in ColorInverseThresholdLabeler::applyTo");
     LabelRaster         *labelOut = new LabelRaster(imgIn->getValidRect());
     FAIL_CONDITION( labelOut == NULL,
                     kNullRasterImageError,
                     "output LabelRaster  allocation failed in GrayThresholdLabeler::applyTo");
     applyInto_(imgIn, params, theRect, labelOut, connectNeighbor);
     return labelOut;
 }
LabelRaster * ColorInverseThresholdLabeler::applyTo (const RasterImage * imgIn, const char * params, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to char)
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Returns
the LabelRaster obtained by applying the operator to imgIn
Implements uriVL::Labeler.
Definition at line 53 of file ColorInverseThresholdLabeler.cpp.
References applyTo().
 {
     return applyTo(imgIn, (const ColorSegParams *) params, connectNeighbor);
 }
LabelRaster * ColorInverseThresholdLabeler::applyTo (const RasterImage * imgIn, const char * params, const ImageRect * theRect, bool connectNeighbor = false) virtual
Applies this operator to an image, returns the result as a LabelRaster.
Parameters
imgIn the RasterImage to which the operator is applied
params parameters for the labeling operation (cast as a pointer to void)
theRect the rectangle within which to apply the labeler
Returns
the LabelRaster obtained by applying the operator to imgIn
Parameters
connectNeighbor when true, indicates that an 8-neighbor connection process should be applied to the results of the thresholding to eliminate isolated pixels.
Implements uriVL::Labeler.
Definition at line 59 of file ColorInverseThresholdLabeler.cpp.
References applyTo().
 {
     return applyTo(imgIn, (const ColorSegParams *) params, theRect, connectNeighbor);
 }
void ColorInverseThresholdLabeler::connectNeighbor_ (const ImageRect * destRect, int nbRegions, LabelRaster * label, LabelRaster * tempLabel, char noMatchVal) private
connect neighbor pixels based on each pixel's 8 label values
Parameters
destRect destination bounding rectangle
nbRegions number of regions
label original LabelRaster
tempLabel temporary LabelRaster for storing label values
Definition at line 593 of file ColorInverseThresholdLabeler.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::LabelRaster::getShiftedLabel2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
Referenced by applyInto_().
 {
         const int       iLow = destRect->getTop( ),
                 iHigh = destRect->getBottom( ),
                 jLow = destRect->getLeft( ),
                 jHigh = destRect->getRight( );
         const int       hT = 5,                                 // high threshold on number of neighbors
                         lT = 3;                                 // low threshold on number of neighbors
         char    **label2D = label->getShiftedLabel2D(R_W_ACCESS),
                         **tempLabel2D = tempLabel->getShiftedLabel2D(R_W_ACCESS);
         // array of label values
         char    *labelArray = new char[nbRegions];
         int             *vote = new int[nbRegions];             // number of each pixel's same neighbor
         int             maxIndex = 0;                                   // index of vote that has max votes
         for (int i=0; i<nbRegions; i++)
         {
                 labelArray[i] = static_cast<char>(i+1);                         // label values begins from 1
                 vote[i] = 0;
         }
         // peripheral points are not processed in this operation, so these values
         // are kept same between label2D and tempLabel2D
         for (int j=jLow; j<=jHigh; j++)
         {
                 tempLabel2D[iLow][j] = label2D[iLow][j];
                 tempLabel2D[iHigh][j] = label2D[iHigh][j];
         }
         for (int i=iLow; i<=iHigh; i++)
         {
                 tempLabel2D[i][jLow] = label2D[i][jLow];
                 tempLabel2D[i][jHigh] = label2D[i][jHigh];
         }
         // process internal points
         for (int i=iLow+1; i<iHigh; i++)
                 for (int j=jLow+1; j<jHigh; j++)
                 {
                         for (int k=0; k<nbRegions; k++)
{
                                 if (labelArray[k] == label2D[i-1][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i-1][j])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i-1][j+1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i][j+1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j-1])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j])
                                         vote[k]++;
                                 if (labelArray[k] == label2D[i+1][j+1])
                                         vote[k]++;
                                 if (vote[k]>vote[maxIndex])
                                         maxIndex = k;
                         }
                         // decide the pixel value based upon vote value
                         if (vote[maxIndex] >= hT)
                                 tempLabel2D[i][j] = labelArray[maxIndex];       // adapt it to majority
                         else if (vote[maxIndex] >= lT)
                                 tempLabel2D[i][j] = label2D[i][j];                      // keep its value
                         else
                                 tempLabel2D[i][j] = noMatchVal;                                         // set to -1
                         // initialize vote back to 0 for next loop
                         for (int k=0; k<nbRegions; k++)
                                 vote[k] = 0;
                 }
         // copy tempLabel2D into label2D
         for (int i=iLow; i<=iHigh; i++)
                 for (int j=jLow; j<=jHigh; j++)
                 {
                         label2D[i][j] = tempLabel2D[i][j];
                 }
 }
bool ColorInverseThresholdLabeler::goodColor_ (int hue, unsigned char sat, unsigned char val, const ColorRegion * theColor) private
Definition at line 554 of file ColorInverseThresholdLabeler.cpp.
References uriVL::ColorRegion::deltaHue, uriVL::ColorRegion::hueRef, uriVL::ColorRegion::satMax, and uriVL::ColorRegion::valMax.
Referenced by applyInto_().
 {
     int hueDiff = hue - theColor->hueRef;
     //--------------------------------
     //  first check the hue
     //--------------------------------
     //  If we get a large positive difference, it might be due to a modulus problem
     if ( hueDiff > theColor->deltaHue )
     {
         //      we are out of the hue wedge sought
         if ( (360 - hueDiff) > theColor->deltaHue )
             return false;
     }
     else if (hueDiff < -theColor->deltaHue )
     {
         //      we are out of the hue wedge sought
         if ( (360 + hueDiff) > theColor->deltaHue )
             return false;
     }
     //--------------------------------
     //  We passed the the hue test, now we check the saturation
     //--------------------------------
     if ( (sat < theColor->satMin) || (sat > theColor->satMax) )
         return false;
     //--------------------------------
     //  Finally we check the value
     //--------------------------------
     if ( (val < theColor->valMin) || (val > theColor->valMax) )
         return false;
     //  We passed all the tests
     return true;
 }
The documentation for this class was generated from the following files:
ColorInverseThresholdLabeler.h
ColorInverseThresholdLabeler.cpp