URIVisionLibrary: uriVL::RangeMap Class Reference
uriVL::RangeMap Class Reference
RangeMap class A range map stores information relative to a surface of the form Z(X, Y), where X, Y, Z, are the coordinates of 3D points.
#include <RangeMap.h>
Public Member Functions
RangeMap (RangeMap *theMap)
Cloner constructor.
RangeMap (RasterImage_gray *rangeMap, float topLatitude, float bottomLatitude, float leftLongitude, float rightLongitude, float scaleRange)
Transforms a range raster into a range map.
RangeMap (ImageRect *theRect, float scaleLongitude, float scaleLatitude, float scaleRange, const float *range)
transforms a range raster into a dense range map object.
RangeMap (int theNbRows, int theNbCols, float startElevation, float elevationStep, float startAzimuth, float AzimuthStep)
Set up dimension for the range map.
RangeMap (int nbPts, const float **thePt)
RangeMap (int nbPts, const Point3D **thePoint)
~RangeMap (void)
Destructor.
void updateMesh (void)
Recalculate the coordinates of the mesh points following an update of the base raster or of the reference 3D points.
void draw (void)
Renders the range map as a meshed surface.
void setResolution (ResolutionLevel res)
Sets the resolution for the rendering of the mesh.
void setWireframe (bool wfState)
Indicates whether or not the range map should be rendered in wireframe.
Public Member Functions inherited from uriVL::RasterImage_gray_F
RasterImage_gray_F (int nbRows, int nbCols)
Allocates a float gray-level raster image at the specified dimensions.
RasterImage_gray_F (const ImageRect *theRect)
Allocates a float gray-level raster image at the specified dimensions.
RasterImage_gray_F (int nbRows, int nbCols, const unsigned char *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const ImageRect *theRect, const unsigned char *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (int nbRows, int nbCols, const float *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const ImageRect *theRect, const float *theGray)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const GraphWorld *gworld)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const RasterImage *img)
Initializes a float raster image at the specified dimensions and values.
RasterImage_gray_F (const RasterImage *img, const ImageRect *theRect)
Initializes a float raster image at the specified dimensions and values.
~RasterImage_gray_F (void)
Destructor.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
const float * getGrayF (void) const
Returns the float gray-level raster for this image as a read-only 1D array.
float * getGrayF (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 1D array.
const float *const * getGrayF2D (void) const
Returns the float gray-level raster for this image as a read-only 2D array.
float *const * getGrayF2D (ReadWriteStatus rw)
Returns the float gray-level raster for this image as a read-write 2D array.
const float *const * getShiftedGrayF2D (void) const
Returns the shifted float gray-level raster for this image as a read-only 2D array.
float *const * getShiftedGrayF2D (ReadWriteStatus rw)
Returns the shifted float gray-level raster for this image as a read-write 2D array.
const unsigned char * getGray (void) const
Returns the 8-bit gray-level base raster as a read-only 1D array.
unsigned char * getGray (ReadWriteStatus rw)
Returns the 8-bit gray-level base raster as a read-write 1D array.
const unsigned char *const * getGray2D (void) const
Returns the 8-bit gray-level base raster as a read-only 2D array.
unsigned char *const * getGray2D (ReadWriteStatus rw)
Returns the 8-bit gray-level base raster as a read-write 2D array.
const unsigned char *const * getShiftedGray2D (void) const
Returns the shifted 8-bit gray-level base raster as a read-only 2D array.
unsigned char *const * getShiftedGray2D (ReadWriteStatus rw)
Returns the shifted 8-bit gray-level base raster as a read-write 2D array.
void setFloatConversionMode (const ConversionFromFloatMode theMode)
Sets an individual conversion mode from float to gray for this image.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image's conversion mode from float to gray.
Public Member Functions inherited from uriVL::RasterImage_gray
RasterImage_gray (int nbRows, int nbCols)
Allocates an 8-bit gray-level raster image at the specified dimensions.
RasterImage_gray (int nbRows, int nbCols, const unsigned char *theGray)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const ImageRect *theRect)
Allocates an 8-bit gray-level raster image at the specified dimensions.
RasterImage_gray (const ImageRect *theRect, const unsigned char *theGray)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const GraphWorld *gworld)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const RasterImage *img)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
RasterImage_gray (const RasterImage *img, const ImageRect *theRect)
Initializes an 8-bit gray-level raster image at the specified dimensions and values.
virtual ~RasterImage_gray (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Protected Member Functions
RangeMap (const RangeMap &theObj)
Copy Constructor.
Protected Member Functions inherited from uriVL::RasterImage_gray_F
RasterImage_gray_F (void)
Default constructor.
Protected Member Functions inherited from uriVL::RasterImage_gray
RasterImage_gray (void)
Default constructor.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Private Member Functions
const RangeMap & operator= (const RangeMap &theObj)
Copy operator.
void allocateDenseMesh_ (void)
Allocates the coordinate array of the dense trimesh.
void drawDenseMesh_ (void)
Draws the triangular mesh of a dense map.
void drawDenseMeshSmooth_ (void)
Draws the smoothed triangular mesh of a dense map.
void drawSparseMesh_ (void)
Draws the mesh of a sparse map.
void drawSparseMeshSmooth_ (void)
Draws the smoothed mesh of a sparse map.
Private Attributes
int ** meshGraph_
Stores the graph of a sparse map.
float *** triMesh_
Triangular mesh of a dense map.
int nRes_
Rendering resolution for a dense range map.
int nbPts_
Number of points of a sparse range map.
bool isWireframe_
Should the range map be rendered in wireframe.
float startLongitude_
longitude at left of range map [in radians]
float stepLongitude_
angle step for the longitude [in radians]
float startLatitude_
latitude at top of range map [in radians]
float stepLatitude_
angle step for the latitude [in radians]
float scaleRange_
Scale to transform raster values into a range [in m].
float * cosLong_
Store the value of cosine of longitude.
float * sinLong_
Store the value of sine of longitude.
float * cosLat_
Store the value of cosine of latitude.
float * sinLat_
Store the value of sine of latitude.
bool useVertexNormals_
Indicates whether or not the elevation map should be rendered using vertex normals for a "smooth" result.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::RasterImage_gray_F
static void setDefaultFloatConversionMode (const ConversionFromFloatMode theMode)
Sets the default conversion mode from float to gray for this class.
Static Public Member Functions inherited from uriVL::RasterImage_gray
static void convertToBinary (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D binary raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D gray-level raster into a 1D 16-bit argb raster.
static const RasterImage_gray * localRasterGray (const RasterImage *imgIn, bool *localGray)
Allocates a read-only gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static const RasterImage_gray * localRasterGray (const RasterImage *imgIn, const ImageRect *rect, bool *localGray)
Allocates a read-only gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static RasterImage_gray * localRasterGray (RasterImage *imgIn, bool *localGray)
Allocates a writable gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
static RasterImage_gray * localRasterGray (RasterImage *imgIn, const ImageRect *rect, bool *localGray)
Allocates a gray-level copy of the image received as parameter if that image is not already some form of gray-level raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
RangeMap class A range map stores information relative to a surface of the form Z(X, Y), where X, Y, Z, are the coordinates of 3D points.
An ElevationMap object can be rendered as a raster image object or drawn as a 3D mesh.
A RangeMap object stores a range map:
for a dense range map, as a 2D raster r[theta, phi] (the row index of the raster corresponds to the longitude theta, the column corresponds to the latitude phi);
for a sparse range map, it is assumed that the 3D points form a valid range surface (i.e. no two points are aligned with the origin)
A range map is what is produced by range finders such as scan lasers or radar. To be properly defined, the range map requires scaling parameters for the longitude, latitude, and range to transform raster indices into coordinates (the r scaling parameter could in theory be dispensed with, since the elevation is normally stored in the float raster, but it is there for the sake of symmetry)
So far the only way to create a DepthMap, RangeMap, or ElevationMap object is to send it either a raster or a list of points to initialize it with. In other words, there is no "create now and allocate/initialize later" constructor.
v. 1.0 12/17/2004 [jyh]
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 60 of file RangeMap.h.
Constructor & Destructor Documentation
RangeMap::RangeMap (RangeMap * theMap)
Cloner constructor.
Parameters
theMap range map to clone
Definition at line 31 of file RangeMap.cpp.
References allocateDenseMesh_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), and triMesh_.
                         :       RasterImage_gray_F(theMap),
                                 //
                                 meshGraph_(NULL),
                                 triMesh_(NULL),
                                 nRes_(1),
                                 nbPts_(0),
                                 isWireframe_(true),
                                 startLongitude_((theMap->startLongitude_)*DEGREE_TO_RADIAN),
                                 stepLongitude_((theMap->stepLongitude_)*DEGREE_TO_RADIAN),
                                 startLatitude_((theMap->startLatitude_)*DEGREE_TO_RADIAN),
                                 stepLatitude_((theMap->stepLatitude_)*DEGREE_TO_RADIAN),
                                 scaleRange_(theMap->scaleRange_),
                                 cosLong_(new float[theMap->getWidth()]),
                                 sinLong_(new float[theMap->getWidth()]),
                                 cosLat_(new float[theMap->getHeight()]),
                                 sinLat_(new float[theMap->getHeight()]),
                                 useVertexNormals_(false)
 {
         //      I want to copy data from the map to clone
         const ImageRect* vRect = getValidRect();
     const int iLow  = vRect->getTop(),
               iHigh = vRect->getBottom(),
               jLow = vRect->getLeft(),
               jHigh = vRect->getRight();
         //      first, I allocate my 2D array of vertices --> a trimesh
         allocateDenseMesh_();
     for (int i=iLow; i<=iHigh; i++)
         for (int j=jLow; j<=jHigh; j++)
                         for (int k=0; k<3; k++)
                                 triMesh_[i][j][k] = theMap->triMesh_[i][j][k];
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RangeMap constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "invalid RangeMap passed as parameter to RangeMap constructor");
 }
RangeMap::RangeMap (RasterImage_gray * rangeMap, float topLatitude, float bottomLatitude, float leftLongitude, float rightLongitude, float scaleRange)
Transforms a range raster into a range map.
Parameters
rangeMap range raster image (gives depth map dimensions)
topLatitude latitude at top of range map [in degrees]
bottomLatitude latitude at bottom of range map [in degrees]
leftLongitude longitude at left of range map [in degrees]
rightLongitude longitude at right of range map [in degrees]
scaleRange scale to apply to range value stored in raster
Definition at line 76 of file RangeMap.cpp.
References allocateDenseMesh_(), and updateMesh().
                    :    RasterImage_gray_F(rangeMap),
                                 //
                                 meshGraph_(NULL),
                                 triMesh_(NULL),
                                 nRes_(1),
                                 nbPts_(0),
                                 isWireframe_(true),
                                 startLongitude_(leftLongitude*DEGREE_TO_RADIAN),
                                 stepLongitude_(DEGREE_TO_RADIAN*(rightLongitude - leftLongitude) / (rangeMap->getWidth() - 1)),
                                 startLatitude_(topLatitude*DEGREE_TO_RADIAN),
                                 stepLatitude_(DEGREE_TO_RADIAN*(bottomLatitude - topLatitude) / (rangeMap->getHeight() - 1)),
                                 scaleRange_(1.f),
                                 cosLong_(new float[rangeMap->getWidth()]),
                                 sinLong_(new float[rangeMap->getWidth()]),
                                 cosLat_(new float[rangeMap->getHeight()]),
                                 sinLat_(new float[rangeMap->getHeight()]),
                                 useVertexNormals_(false)
 {
         //      first, I allocate my 2D array of vertices --> a trimesh
         allocateDenseMesh_();
         updateMesh();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RangeMap constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "invalid RasterImage passed as parameter to RangeMap constructor");
 }
RangeMap::RangeMap (ImageRect * theRect, float scaleLongitude, float scaleLatitude, float scaleRange, const float * range)
transforms a range raster into a dense range map object.
The input rectangle defines the origin and dimensions of the map
Parameters
theRect bounding rectangle of the map
scaleLongitude angle step for the longitude [in degrees]
scaleLatitude angle step for the latitude [in degrees]
scaleRange scale to apply to range value stored in raster
range 1D range raster
Definition at line 113 of file RangeMap.cpp.
References allocateDenseMesh_().
                    :    RasterImage_gray_F(theRect, range),
                                 //
                                 meshGraph_(NULL),
                                 triMesh_(NULL),
                                 nRes_(1),
                                 nbPts_(0),
                                 isWireframe_(true),
                                 startLongitude_(0*DEGREE_TO_RADIAN),
                                 stepLongitude_(scaleLongitude*DEGREE_TO_RADIAN),
                                 startLatitude_(0*DEGREE_TO_RADIAN),
                                 stepLatitude_(scaleLatitude*DEGREE_TO_RADIAN),
                                 scaleRange_(scaleRange),
                                 cosLong_(NULL),
                                 sinLong_(NULL),
                                 cosLat_(NULL),
                                 sinLat_(NULL),
                                 useVertexNormals_(false)
 {
         //      first, I allocate my 2D array of vertices --> a trimesh
         allocateDenseMesh_();
         //      we have no values to push yet
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RangeMap constructor");
         throw e;
 }
RangeMap::RangeMap (int theNbRows, int theNbCols, float startElevation, float elevationStep, float startAzimuth, float AzimuthStep)
Set up dimension for the range map.
Parameters
theNbRows height of the range map
theNbCols width of the range map
startElevation the start Elevation angle [in degrees]
elevationStep the increament of Elevation angle for each steps [in degrees]
startAzimuth the start Azimuth angle [in degrees]
AzimuthStep the increament of Azimuth angle for each steps [in degrees]
Definition at line 146 of file RangeMap.cpp.
References allocateDenseMesh_().
                    :    meshGraph_(NULL),
                                 triMesh_(NULL),
                                 nRes_(1),
                                 nbPts_(0),
                                 isWireframe_(true),
                                 startLongitude_(startElevation*DEGREE_TO_RADIAN),
                                 stepLongitude_(azimuthStep*DEGREE_TO_RADIAN),
                                 startLatitude_(startAzimuth*DEGREE_TO_RADIAN),
                                 stepLatitude_(elevationStep*DEGREE_TO_RADIAN),
                                 scaleRange_(1.f),
                                 cosLong_(NULL),
                                 sinLong_(NULL),
                                 cosLat_(NULL),
                                 sinLat_(NULL),
                                 useVertexNormals_(false)
 {
         //      I allocate my 2D array of vertices --> a trimesh
         allocateDenseMesh_();
         //      we have no values to push yet
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RangeMap constructor");
         throw e;
 }
RangeMap::RangeMap (int nbPts, const float ** thePt)
Definition at line 180 of file RangeMap.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage_gray_F(),
                         //
                         meshGraph_(NULL),
                         triMesh_(NULL),
                         nRes_(1),
                         nbPts_(0),
                         isWireframe_(true),
                         startLongitude_(0*DEGREE_TO_RADIAN),
                         stepLongitude_(0*DEGREE_TO_RADIAN),
                         startLatitude_(0*DEGREE_TO_RADIAN),
                         stepLatitude_(0*DEGREE_TO_RADIAN),
                         scaleRange_(1.f),
                         cosLong_(NULL),
                         sinLong_(NULL),
                         cosLat_(NULL),
                         sinLat_(NULL),
                         useVertexNormals_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "sparse RangeMap constructor not implemented yet");
 }
RangeMap::RangeMap (int nbPts, const Point3D ** thePoint)
Definition at line 208 of file RangeMap.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage_gray_F(),
                         //
                         meshGraph_(NULL),
                         triMesh_(NULL),
                         nRes_(1),
                         nbPts_(0),
                         isWireframe_(true),
                         startLongitude_(1*DEGREE_TO_RADIAN),
                         stepLongitude_(1*DEGREE_TO_RADIAN),
                         startLatitude_(1*DEGREE_TO_RADIAN),
                         stepLatitude_(1*DEGREE_TO_RADIAN),
                         scaleRange_(1),
                         cosLong_(NULL),
                         sinLong_(NULL),
                         cosLat_(NULL),
                         sinLat_(NULL),
                         useVertexNormals_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "sparse RangeMap constructor not implemented yet");
 }
RangeMap::~RangeMap (void)
Destructor.
Definition at line 258 of file RangeMap.cpp.
References cosLat_, cosLong_, uriVL::DrawableObject2D::getHeight(), sinLat_, sinLong_, and triMesh_.
 {
         int     nbRows = getHeight();
 //                      nbCols = getWidth();   // unused var. -CJC
         for (int i=0; i<nbRows; i++)
                 delete []triMesh_[i];
     delete []triMesh_;
         delete []cosLong_;
         delete []sinLong_;
         delete []cosLat_;
         delete []sinLat_;
 }
RangeMap::RangeMap (const RangeMap & theObj) protected
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 233 of file RangeMap.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage_gray_F(),
                         //
                         meshGraph_(NULL),
                         triMesh_(NULL),
                         nRes_(1),
                         nbPts_(0),
                         isWireframe_(true),
                         startLongitude_(0),
                         stepLongitude_(0),
                         startLatitude_(0),
                         stepLatitude_(0),
                         scaleRange_(0),
                         cosLong_(NULL),
                         sinLong_(NULL),
                         cosLat_(NULL),
                         sinLat_(NULL),
                         useVertexNormals_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "RangeMap copy constructor not implemented");
 }
Member Function Documentation
void RangeMap::allocateDenseMesh_ (void) private
Allocates the coordinate array of the dense trimesh.
Definition at line 335 of file RangeMap.cpp.
References cosLat_, cosLong_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::getWidth(), sinLat_, sinLong_, startLatitude_, startLongitude_, stepLatitude_, stepLongitude_, and triMesh_.
Referenced by RangeMap().
 {
         const ImageRect* vRect = getValidRect();
     const int   nbRows = vRect->getHeight(),
                                 nbCols = vRect->getWidth();
     const int   iLow  = vRect->getTop(),
                                 iHigh = vRect->getBottom(),
                                 jLow = vRect->getLeft(),
                                 jHigh = vRect->getRight();
         triMesh_ = new float**[nbRows];
         for (int i=0; i<nbRows; i++)
         {
                 triMesh_[i] = new float*[nbCols];
                 for (int j=0; j<nbCols; j++)
                         triMesh_[i][j] = new float[3];
         }
         float longit = startLongitude_;
         for (int j=jLow; j<=jHigh; j++, longit += stepLongitude_)
         {
                 cosLong_[j] = cosf(longit);
                 sinLong_[j] = sinf(longit);
         }
         float lat = startLatitude_;
         for (int i=iLow; i<=iHigh; i++, lat += stepLatitude_)
         {
                 cosLat_[i] = cosf(lat);
                 sinLat_[i] = sinf(lat);
         }
 }
void RangeMap::draw (void) virtual
Renders the range map as a meshed surface.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 377 of file RangeMap.cpp.
References drawDenseMesh_(), drawDenseMeshSmooth_(), drawSparseMesh_(), drawSparseMeshSmooth_(), uriVL::DrawableObject2D::getDrawableInformationType(), isWireframe_, uriVL::kDense, uriVL::kSparse, and useVertexNormals_.
 {
         switch(getDrawableInformationType())
         {
                 case kDense:
                         if (isWireframe_ || !useVertexNormals_)
                                 drawDenseMesh_();
                         else
                                 drawDenseMeshSmooth_();
                         break;
                 case kSparse:
                         if (isWireframe_ || !useVertexNormals_)
                                 drawSparseMesh_();
                         else
                                 drawSparseMeshSmooth_();
                         break;
                 default:
                         break;
         }
 }
void RangeMap::drawDenseMesh_ (void) private
Draws the triangular mesh of a dense map.
Definition at line 401 of file RangeMap.cpp.
References uriVL::GraphicComponent3D::ambientMat_, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), isWireframe_, uriVL::GraphicComponent3D::setReflectionParameters_(), and triMesh_.
Referenced by draw().
 {
         const int       nbRows = getHeight(),
                             nbCols = getWidth();
         if (isWireframe_)
         {
                 glPolygonMode(GL_FRONT_AND_BACK, GL_LINE);
         glColor3f(ambientMat_[0], ambientMat_[1], ambientMat_[2]);
         }
         else
         {
                 glPolygonMode(GL_FRONT_AND_BACK, GL_FILL);
         setReflectionParameters_( );
     }
         for (int i=0; i<nbRows-1; i++)
         {
                 glBegin(GL_TRIANGLE_STRIP);
                 for (int j=0; j<nbCols; j++)
                 {
                         glVertex3fv(triMesh_[i+1][j]);
                         glVertex3fv(triMesh_[i][j]);
                 }
                 glEnd();
         }
 }
void RangeMap::drawDenseMeshSmooth_ (void) private
Draws the smoothed triangular mesh of a dense map.
Definition at line 430 of file RangeMap.cpp.
Referenced by draw().
 {
         glBegin(GL_TRIANGLE_STRIP);
         glEnd();
 }
void RangeMap::drawSparseMesh_ (void) private
Draws the mesh of a sparse map.
Definition at line 438 of file RangeMap.cpp.
Referenced by draw().
 {
 }
void RangeMap::drawSparseMeshSmooth_ (void) private
Draws the smoothed mesh of a sparse map.
Definition at line 442 of file RangeMap.cpp.
Referenced by draw().
 {
 }
const RangeMap & RangeMap::operator= (const RangeMap & theObj) private
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 273 of file RangeMap.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "RangeMap copy operator not implemented");
         return *this;
 }
void RangeMap::setResolution (ResolutionLevel res) virtual
Sets the resolution for the rendering of the mesh.
Calling this function only makes sense for a dense (raster) map.
Parameters
res resolution level for rendering the mesh
Implements uriVL::GraphicComponent3D.
Definition at line 456 of file RangeMap.cpp.
References uriVL::kCoarseResolution, uriVL::kFineResolution, uriVL::kMediumResolution, uriVL::kVeryHighResolution, uriVL::kVeryLowResolution, and nRes_.
 {
     switch (res)
     {
         case kVeryHighResolution:
             nRes_ = 1;
             break;
         case kFineResolution:
             nRes_ = 4;
             break;
         case kMediumResolution:
             nRes_ = 10;
             break;
         case kCoarseResolution:
             nRes_ = 25;
             break;
         case kVeryLowResolution:
             nRes_ = 50;
             break;
     }
 }
void RangeMap::setWireframe (bool wfState)
Indicates whether or not the range map should be rendered in wireframe.
Parameters
wfState true if the range map should be rendered in wireframe
See also
isWireframe_
Definition at line 479 of file RangeMap.cpp.
References isWireframe_.
 {
         isWireframe_ = wfState;
 }
void RangeMap::updateMesh (void)
Recalculate the coordinates of the mesh points following an update of the base raster or of the reference 3D points.
Definition at line 289 of file RangeMap.cpp.
References cosLat_, cosLong_, FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getDrawableInformationType(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getValidRect(), uriVL::kDense, uriVL::kDenseUncertain, uriVL::kFunctionNotImplemented, scaleRange_, sinLat_, sinLong_, and triMesh_.
Referenced by RangeMap().
 {
         //      If the range raster is the reference we recalculate the mesh
         DrawableInformationType dType = getDrawableInformationType();
         if ((dType == kDense) || (dType == kDenseUncertain))
         {
                 const ImageRect* vRect = getValidRect();
                 const int iLow  = vRect->getTop(),
                                   iHigh = vRect->getBottom(),
                                   jLow = vRect->getLeft(),
                                   jHigh = vRect->getRight();
         const float     *const* range = getShiftedGrayF2D();
                 for (int i=iLow; i<=iHigh; i++)
                 {
                         for (int j=jLow; j<=jHigh; j++)
{
                                 float   r = scaleRange_*range[i][j];
                                 //      X
                                 triMesh_[i][j][0] = r * cosLong_[j] * cosLat_[i];
                                 //      Y
                                 triMesh_[i][j][1] = r * sinLat_[i];
                                 //      Z (z is in the horizontal direction)
                                 triMesh_[i][j][2] = -r * sinLong_[j] * cosLat_[i];
 //dynamic array
 //cout << "(" << i << ", " << j << "), r = " << r << " --> { " << cosLat_[i] << ", " << sinLat_[i] << ", " <<
 //              cosLong_[j] << ", " << sinLong_[j] << "} --> [" << triMesh_[i][j][0]
 //                              << ", " << triMesh_[i][j][1] << ", " << triMesh_[i][j][2] << "]" << endl;
                         }
                 }
         }
         //      else I don't know yet what to do
         else
         {
                 FAIL_CONDITION( true,
                                                 kFunctionNotImplemented,
                                                 "Not implemented yet");
         }
 }
Member Data Documentation
float* uriVL::RangeMap::cosLat_ private
Store the value of cosine of latitude.
Definition at line 223 of file RangeMap.h.
Referenced by allocateDenseMesh_(), updateMesh(), and ~RangeMap().
float* uriVL::RangeMap::cosLong_ private
Store the value of cosine of longitude.
Definition at line 215 of file RangeMap.h.
Referenced by allocateDenseMesh_(), updateMesh(), and ~RangeMap().
bool uriVL::RangeMap::isWireframe_ private
Should the range map be rendered in wireframe.
See also
setWireframe
Definition at line 191 of file RangeMap.h.
Referenced by draw(), drawDenseMesh_(), and setWireframe().
int** uriVL::RangeMap::meshGraph_ private
Stores the graph of a sparse map.
Definition at line 171 of file RangeMap.h.
int uriVL::RangeMap::nbPts_ private
Number of points of a sparse range map.
Definition at line 185 of file RangeMap.h.
int uriVL::RangeMap::nRes_ private
Rendering resolution for a dense range map.
See also
setResolution
Definition at line 181 of file RangeMap.h.
Referenced by setResolution().
float uriVL::RangeMap::scaleRange_ private
Scale to transform raster values into a range [in m].
Definition at line 211 of file RangeMap.h.
Referenced by updateMesh().
float* uriVL::RangeMap::sinLat_ private
Store the value of sine of latitude.
Definition at line 227 of file RangeMap.h.
Referenced by allocateDenseMesh_(), updateMesh(), and ~RangeMap().
float* uriVL::RangeMap::sinLong_ private
Store the value of sine of longitude.
Definition at line 219 of file RangeMap.h.
Referenced by allocateDenseMesh_(), updateMesh(), and ~RangeMap().
float uriVL::RangeMap::startLatitude_ private
latitude at top of range map [in radians]
Definition at line 203 of file RangeMap.h.
Referenced by allocateDenseMesh_().
float uriVL::RangeMap::startLongitude_ private
longitude at left of range map [in radians]
Definition at line 195 of file RangeMap.h.
Referenced by allocateDenseMesh_().
float uriVL::RangeMap::stepLatitude_ private
angle step for the latitude [in radians]
Definition at line 207 of file RangeMap.h.
Referenced by allocateDenseMesh_().
float uriVL::RangeMap::stepLongitude_ private
angle step for the longitude [in radians]
Definition at line 199 of file RangeMap.h.
Referenced by allocateDenseMesh_().
float*** uriVL::RangeMap::triMesh_ private
Triangular mesh of a dense map.
Definition at line 175 of file RangeMap.h.
Referenced by allocateDenseMesh_(), drawDenseMesh_(), RangeMap(), updateMesh(), and ~RangeMap().
bool uriVL::RangeMap::useVertexNormals_ private
Indicates whether or not the elevation map should be rendered using vertex normals for a "smooth" result.
Default is false.
See also
setUseVertexNormals
Definition at line 234 of file RangeMap.h.
Referenced by draw().
The documentation for this class was generated from the following files:
RangeMap.h
RangeMap.cpp