URIVisionLibrary: uriVL::Registration2D_ICP Class Reference
uriVL::Registration2D_ICP Class Reference
Class for objects that register two sets of image points using the Iterated Closest Point (ICP) algorithm of Besl and McKay.
#include <Registration2D_ICP.h>
Public Member Functions
Registration2D_ICP (void)
Constructor.
~Registration2D_ICP (void)
Destructor.
Transformation2D * registerPoints (const Contour *refPts, const Contour *dataPts, const Transformation2D *guessTransf=NULL)
Registers two image contours.
Transformation2D * registerPoints (const std::vector< const ImagePoint * > *refPtList, const std::vector< const ImagePoint * > *ptList, const Transformation2D *guessTransf=NULL)
Registers two sets of 2D image points.
Public Member Functions inherited from uriVL::Registration2D
Registration2D (void)
Constructor.
virtual ~Registration2D (void)
Destructor.
void setRegistrationType (Registration2DType regType)
Sets the type of registration calculations to perform.
void setPointSelectionMode (Point2DSelectionMode ptSelectMode)
Sets the criterion for point selection.
void setMatchingMetric (Point2DMatchingMetric matchingMetric)
Sets the matching metric.
void setPairRejectionMode (Point2DPairRejectMode pairRejectionMode)
Sets the criterion for rejecting matching pairs.
void setPairWeightingMode (MatchPairWeightingMode pairWeightingMode)
Sets the weigthing scheme for combining the scores of matching pairs.
void setNoMatchThreshold (float noMatchThreshold)
Sets the distance beyond which we consider that a data point finds no match in the reference set.
void setNoMatchPenalty (float noMatchPenalty)
Sets the penalty for a "no match" in the global cost function.
Protected Member Functions
Transformation2D * registerPoints_lin_ (int nbRefPts, const double *const refPtX, const double *refPtY, double *transfRefX, double *transfRefY, int nbPts, const double *ptX, const double *ptY, bool *match, double *matchX, double *matchY)
Performs rigid linear registration of two sets of 2D image points.
Transformation2D * registerPoints_nonlin_ (int nbRefPts, const double *refPtX, const double *refPtY, double *transfRefX, double *transfRefY, int nbPts, const double *ptX, const double *ptY, bool *match, double *matchX, double *matchY)
Performs rigid nonlinear registration of two sets of 2D image points.
Transformation2D * registerPoints_aff_ (int nbRefPts, const double *refPtX, const double *refPtY, double *transfRefX, double *transfRefY, int nbPts, const double *ptX, const double *ptY, bool *match, double *matchX, double *matchY)
Performs affine registration of two sets of 2D image points.
void findBestMatch_ (int nbRefPts, const double *refPtX, const double *refPtY, double *transfRefX, double *transfRefY, int nbPts, const double *ptX, const double *ptY, Transformation2D *transf, bool *match, double *matchX, double *matchY)
Determines for each data point which transformed reference point it is closest to.
void findBestMatch_Vertex_ (Contour *refPts, double *transfRefX, double *transfRefY, Contour *dataPts, Transformation2D *transf, bool *match, double *matchX, double *matchY)
Determines for each contour data point which transformed reference point it is closest to.
void findBestMatch_VertexNormal_ (Contour *refPts, double *transfRefX, double *transfRefY, Contour *dataPts, Transformation2D *transf, bool *match, double *matchX, double *matchY)
Determines for each contour data point which transformed reference point it is closest to.
void findBestMatch_Edge_ (Contour *refPts, double *transfRefX, double *transfRefY, Contour *dataPts, Transformation2D *transf, bool *match, double *matchX, double *matchY)
Determines for each contour data point which point on a transformed reference edge (not The distance used in this calculation is simply the Euclidean distance between the data point and the closest point on the closest transformed edge.
void findBestMatch_EdgeNormal_ (Contour *refPts, double *transfRefX, double *transfRefY, Contour *dataPts, Transformation2D *transf, bool *match, double *matchX, double *matchY)
Determines for each contour data point which point on a transformed reference edge (not necessarily a vertex) it is closest to.
double llsSolutionTransformation (int nbPts, const double *ptX, const double *ptY, const bool *match, const double *refPtX, const double *refPtY, Transformation2D *transf)
Computes the least-squares transformation for a list of matched points.
float costFunc_SSD_ (int nbPts, const double *ptX, const double *ptY, const bool *match, const double *refPtX, const double *refPtY, Transformation2D *transf)
Evaluates the "weighted closest point" Sum of Squared Differences cost function between the data points pt and the model refPt to which has been applied the transformation.
float costFunc_SAD_ (int nbPts, const double *ptX, const double *ptY, const bool *match, const double *refPtX, const double *refPtY, Transformation2D *transf)
Evaluates the "weighted closest point" Sum of Absolute Differences cost function between the data points pt and the model refPt to which has been applied the transformation.
Additional Inherited Members
Protected Attributes inherited from uriVL::Registration2D
LinearSolver * solver_
Linear solver used to compute the best-fit parameters.
Registration2DType regType_
what kind of registration to perform
Point2DSelectionMode ptSelectMode_
How data points to match are selected.
Point2DMatchingMetric matchingMetric_
The metric used to evaluate quality of match.
Point2DPairRejectMode pairRejectionMode_
Criterion used to reject matching pairs.
MatchPairWeightingMode pairWeightingMode_
weighting scheme used to combine pairs' matching scores
float noMatchThreshold_
threshold for "no match distance" with THRESHOLD_BASED_REJECT
float noMatchPenalty_
Penalty for a no-match (match rejected)
Static Protected Attributes inherited from uriVL::Registration2D
static const float DEFAULT_NO_MATCH_THRESHOLD = 5
Default threshold for "no match distance".
static const float DEFAULT_NO_MATCH_PENALTY = 10
Default penalty for a no-match.
static const float DEFAULT_PAIR_REJECT_PERCENT
Default percentage of pairs to reject.
static const float DEFAULT_STANDARD_DEV_REJECT_MULT
Default standard deviation multiplier for STANDARD_DEV_REJECT mode.
static const int DEFAULT_NUMBER_NEIGHBOR_COMP
Default number of "neighbor" pairs to compare to in NEIGHBOR_INCONSISTENCY_REJECT mode.
static const int DEFAULT_MIN_NUMBER_FAIL_NEIGHBOR
Default number of neighbors that must fail the test to reject the pair in NEIGHBOR_INCONSISTENCY_REJECT mode.
static const float DEFAULT_FAIL_NEIGHBOR_SCALE
Default scaling factor to reject the pair in NEIGHBOR_INCONSISTENCY_REJECT mode.
Detailed Description
Class for objects that register two sets of image points using the Iterated Closest Point (ICP) algorithm of Besl and McKay.
Author
jean-yves herve', 3D Group for Interactive Visualization, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 33 of file Registration2D_ICP.h.
Constructor & Destructor Documentation
Registration2D_ICP::Registration2D_ICP (void)
Constructor.
Definition at line 26 of file Registration2D_ICP.cpp.
 {
 /*
 //    const int NB_REF_PTS = 14;
     double refPtX[NB_REF_PTS] = {2, 4, 0, 3, 4, 0, 2, 5, 3, 4, 0, 2, 1, 4},
            refPtY[NB_REF_PTS] = {7, 7, 6, 6, 6, 4, 4, 4, 3, 3, 1, 1, 0, 0},
            transfRefX[NB_REF_PTS],
            transfRefY[NB_REF_PTS];
     //  My data points are points {10, 11, 12, 1, 7, 8, 4, 9, 0, 2, 5, 3, 6, 13} rotated by pi/2, with point 1 at 10, 10
 //  all pts, no rot
 //    const int NB_PTS = 14;
 //    double ptX[NB_PTS] = {5, 7, 6, 9, 10, 8, 9, 9, 7, 5},//, 5, 8, 7, 9},
 //           ptY[NB_PTS] = {3, 3, 2, 9,  6, 5, 8, 5, 9, 8};//, 6, 8, 6, 2},
 // all pts, rot 90
 //    const int NB_PTS = 14;
 //    double ptX[NB_PTS] = {15, 15, 16,  9, 12, 13, 10, 13, 9, 10, 12, 10, 12, 16},
 //           ptY[NB_PTS] = { 6,  8,  7, 10, 11,  9, 10, 10, 8,  6,  6,  9,  8, 10};
 //  top pts, rot 90
     const int NB_PTS = 7;
     double ptX[NB_PTS] = {12, 10, 9, 10,  9, 10, 12},
            ptY[NB_PTS] = { 6,  6, 8,  9, 10, 10, 11};
     double matchX[NB_PTS],
            matchY[NB_PTS];
         bool match[NB_PTS];
     registerPoints_lin_(NB_REF_PTS, refPtX, refPtY, transfRefX, transfRefY,
                         NB_PTS, ptX, ptY, match, matchX, matchY);
 */
 }
Registration2D_ICP::~Registration2D_ICP (void)
Destructor.
Definition at line 64 of file Registration2D_ICP.cpp.
 {
 }
Member Function Documentation
float Registration2D_ICP::costFunc_SAD_ (int nbPts, const double * ptX, const double * ptY, const bool * match, const double * refPtX, const double * refPtY, Transformation2D * transf) protected
Evaluates the "weighted closest point" Sum of Absolute Differences cost function between the data points pt and the model refPt to which has been applied the transformation.
Parameters
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
refPtX the array of x coordinates of the "best match" reference image points
refPtY the array of y coordinates of the "best match" reference image points
transf the 2D transformation for which to calculate the cost
Returns
the cost value for the reference and data points and input transformation
Definition at line 542 of file Registration2D_ICP.cpp.
References uriVL::Transformation2D::getMatrix(), and uriVL::Transformation2D::isRigidTransformation().
 {
     const float*const*const mat = transf->getMatrix();
     double costSum = 0.;
     if (transf->isRigidTransformation())
     {
         for (int i=0; i<nbPts; i++)
         {
             //  did we find a match for pt[i]?
             if ( match[i])
             {
                 const double refX = refPtX[i],
                              refY = refPtY[i];
                 //  compute displacement between the data point and the transformed reference point
                 costSum += fabs(ptX[i] - (mat[0][0]*refX + mat[0][1]*refY + mat[0][2])) +
                            fabs(ptY[i] - (mat[1][0]*refX + mat[1][1]*refY + mat[1][2]));
             }
             else
                 costSum += noMatchPenalty_;
         }
     }
     else
     {
         for (int i=0; i<nbPts; i++)
         {
             //  did we find a match for pt[i]?
             if ( match[i])
             {
                 const double refX = refPtX[i],
                              refY = refPtY[i];
                 //  compute scaling term
                 const double s = mat[2][0]*refX + mat[2][1]*refY + mat[2][2];
                 //  compute displacement between the data point and the transformed reference point
                 costSum += fabs(ptX[i] - (mat[0][0]*refX + mat[0][1]*refY + mat[0][2])/s) +
                            fabs(ptY[i] - (mat[1][0]*refX + mat[1][1]*refY + mat[1][2])/s);
             }
             else
                 costSum += noMatchPenalty_;
         }
     }
     return static_cast<float>(costSum / nbPts);
 }
float Registration2D_ICP::costFunc_SSD_ (int nbPts, const double * ptX, const double * ptY, const bool * match, const double * refPtX, const double * refPtY, Transformation2D * transf) protected
Evaluates the "weighted closest point" Sum of Squared Differences cost function between the data points pt and the model refPt to which has been applied the transformation.
Parameters
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
refPtX the array of x coordinates of the "best match" reference image points
refPtY the array of y coordinates of the "best match" reference image points
transf the 2D transformation for which to calculate the cost
Returns
the cost value for the reference and data points and input transformation
Definition at line 485 of file Registration2D_ICP.cpp.
References uriVL::Transformation2D::getMatrix(), and uriVL::Transformation2D::isRigidTransformation().
 {
     const float*const*const mat = transf->getMatrix();
     double costSum = 0.L;
     if (transf->isRigidTransformation())
     {
         for (int i=0; i<nbPts; i++)
         {
             //  did we find a match for pt[i]?
             if ( match[i])
             {
                 const double refX = refPtX[i],
                              refY = refPtY[i];
                 //  compute displacement between the data point and the transformed reference point
                 const double dx = ptX[i] - (mat[0][0]*refX + mat[0][1]*refY + mat[0][2]);
                 const double dy = ptY[i] - (mat[1][0]*refX + mat[1][1]*refY + mat[1][2]);
                 costSum += dx*dx + dy*dy;
             }
             else
                 costSum += noMatchPenalty_;
         }
     }
     else
     {
         for (int i=0; i<nbPts; i++)
         {
             //  did we find a match for pt[i]?
             if ( match[i])
             {
                 const double refX = refPtX[i],
                              refY = refPtY[i];
                 //  compute scaling term
                 const double s = mat[2][0]*refX + mat[2][1]*refY + mat[2][2];
                 //  compute displacement between the data point and the transformed reference point
                 const double dx = ptX[i] - (mat[0][0]*refX + mat[0][1]*refY + mat[0][2])/s;
                 const double dy = ptY[i] - (mat[1][0]*refX + mat[1][1]*refY + mat[1][2])/s;
                 costSum += dx*dx + dy*dy;
             }
             else
                 costSum += noMatchPenalty_;
         }
     }
     return static_cast<float>(costSum / nbPts);
 }
void Registration2D_ICP::findBestMatch_ (int nbRefPts, const double * refPtX, const double * refPtY, double * transfRefX, double * transfRefY, int nbPts, const double * ptX, const double * ptY, Transformation2D * transf, bool * match, double * matchX, double * matchY) protected
Determines for each data point which transformed reference point it is closest to.
Parameters
nbRefPts the number of of reference image points
refPtX the array of x coordinates of the reference image points
refPtY the array of y coordinates of the reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
transf the 2D transformation for which to calculate the cost
match output: array indicating for each data point whether it has a match in the reference set
matchX output: array of x coordinates of the "best match" point (in reference set) for each data point
matchY output: array of y coordinates of the "best match" point (in reference set) for each data point
Definition at line 295 of file Registration2D_ICP.cpp.
References uriVL::Transformation2D::getMatrix(), and uriVL::Transformation2D::isRigidTransformation().
 {
 //int bestMatch[NB_REF_PTS];
     const float*const*const mat = transf->getMatrix();
     //--------------------------------------------------------------------------
     //  1.  Apply the transformation to each point of the reference set
     //--------------------------------------------------------------------------
     if (transf->isRigidTransformation())
     {
         for (int i=0; i<nbRefPts; i++)
         {
             transfRefX[i] = mat[0][0]*refPtX[i] + mat[0][1]*refPtY[i] + mat[0][2];
             transfRefY[i] = mat[1][0]*refPtX[i] + mat[1][1]*refPtY[i] + mat[1][2];
         }
     }
     else
     {
         for (int i=0; i<nbRefPts; i++)
         {
             //  compute scaling term
             double s = mat[2][0]*refPtX[i] + mat[2][1]*refPtY[i] + mat[2][2];
             //  compute displacement between the data point and the transformed reference point
             transfRefX[i] = (mat[0][0]*refPtX[i] + mat[0][1]*refPtY[i] + mat[0][2])/s;
             transfRefX[i] = (mat[1][0]*refPtX[i] + mat[1][1]*refPtY[i] + mat[1][2])/s;
         }
     }
     //--------------------------------------------------------------------------
     //  2.  Iterate over data points and find closest transformed point
     //--------------------------------------------------------------------------
     for (int k=0; k<nbPts; k++)
     {
         double  smallestDist2 = 1000000000000000.L;    //  out of workspace
         for (int i=0; i<nbRefPts; i++)
         {
             double  dx = ptX[k] - transfRefX[i],
                     dy = ptY[k] - transfRefY[i];
             double  d2 = dx*dx + dy*dy;
             if (d2 < smallestDist2)
             {
                 smallestDist2 = d2;
                 matchX[k] = refPtX[i];
                 matchY[k] = refPtY[i];
 //bestMatch[k] = i;
             }
         }
         if (smallestDist2 > noMatchThreshold_*noMatchThreshold_)
 //{
             match[k] = false;
 //bestMatch[k] = -1;
 //}
         else
             match[k] = true;
     }
 //cout << "\tmatch: ";
 //for (int k=0; k<nbPts; k++)
 //    cout << "(" << k << " : " << bestMatch[k] << ")  ";
 //cout << flush;
 }
void Registration2D_ICP::findBestMatch_Edge_ (Contour * refPts, double * transfRefX, double * transfRefY, Contour * dataPts, Transformation2D * transf, bool * match, double * matchX, double * matchY) protected
Determines for each contour data point which point on a transformed reference edge (not The distance used in this calculation is simply the Euclidean distance between the data point and the closest point on the closest transformed edge.
necessarily a vertex) it is closest to.
Parameters
refPtList the set of reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
ptList the set of points to register to the reference
transf the 2D transformation for which to calculate the cost
match output: array indicating for each data point whether it has a match in the reference set
matchX output: array of x coordinates of the "best match" point (in reference set) for each data point
matchY output: array of y coordinates of the "best match" point (in reference set) for each data point
Definition at line 380 of file Registration2D_ICP.cpp.
 {
 }
void Registration2D_ICP::findBestMatch_EdgeNormal_ (Contour * refPts, double * transfRefX, double * transfRefY, Contour * dataPts, Transformation2D * transf, bool * match, double * matchX, double * matchY) protected
Determines for each contour data point which point on a transformed reference edge (not necessarily a vertex) it is closest to.
The distance used in this calculation is the Euclidean distance along the normal to the data point to the closest transformed edge.
Parameters
refPtList the set of reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
ptList the set of points to register to the reference
transf the 2D transformation for which to calculate the cost
match output: array indicating for each data point whether it has a match in the reference set
matchX output: array of x coordinates of the "best match" point (in reference set) for each data point
matchY output: array of y coordinates of the "best match" point (in reference set) for each data point
Definition at line 386 of file Registration2D_ICP.cpp.
 {
 }
void Registration2D_ICP::findBestMatch_Vertex_ (Contour * refPts, double * transfRefX, double * transfRefY, Contour * dataPts, Transformation2D * transf, bool * match, double * matchX, double * matchY) protected
Determines for each contour data point which transformed reference point it is closest to.
The distance used in this calculation is simply the Euclidean distance between two points.
Parameters
refPtList the set of reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
ptList the set of points to register to the reference
transf the 2D transformation for which to calculate the cost
match output: array indicating for each data point whether it has a match in the reference set
matchX output: array of x coordinates of the "best match" point (in reference set) for each data point
matchY output: array of y coordinates of the "best match" point (in reference set) for each data point
Definition at line 368 of file Registration2D_ICP.cpp.
 {
 }
void Registration2D_ICP::findBestMatch_VertexNormal_ (Contour * refPts, double * transfRefX, double * transfRefY, Contour * dataPts, Transformation2D * transf, bool * match, double * matchX, double * matchY) protected
Determines for each contour data point which transformed reference point it is closest to.
The distance used in this calculation is measured along the normal vector at the data point.
Parameters
refPtList the set of reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
ptList the set of points to register to the reference
transf the 2D transformation for which to calculate the cost
match output: array indicating for each data point whether it has a match in the reference set
matchX output: array of x coordinates of the "best match" point (in reference set) for each data point
matchY output: array of y coordinates of the "best match" point (in reference set) for each data point
Definition at line 374 of file Registration2D_ICP.cpp.
 {
 }
double Registration2D_ICP::llsSolutionTransformation (int nbPts, const double * ptX, const double * ptY, const bool * match, const double * refPtX, const double * refPtY, Transformation2D * transf) protected
Computes the least-squares transformation for a list of matched points.
Parameters
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
refPtX the array of x coordinates of the "best match" reference image points
refPtY the array of y coordinates of the "best match" reference image points
transf output: the corresponding least squares 2D transformation
Returns
the squared norm of the residual
Definition at line 398 of file Registration2D_ICP.cpp.
References uriVL::Transformation2D::getMatrix(), and uriVL::R_W_ACCESS.
 {
     //------------------------------------------------------------------------
     //  Do the basic summations of x & y coordinates of the reference and data
     //  points, dot products, and determinants
     //------------------------------------------------------------------------
         int     matchCount = 0;
         double  sumPtX = 0, sumPtY = 0,
                         sumRefX = 0, sumRefY = 0,
                         sumDet = 0, sumDotProd = 0;
         for (int i=0; i<nbPts; i++)
         {
                 if (match[i])
                 {
                         sumPtX += ptX[i];
                         sumPtY += ptY[i];
                         sumRefX += refPtX[i];
                         sumRefY += refPtY[i];
                         sumDet += ptX[i]*refPtY[i] - ptY[i]*refPtX[i];
                         sumDotProd += ptX[i]*refPtX[i] + ptY[i]*refPtY[i];
                         //
                         matchCount++;
                 }
         }
     //------------------------------------------------------------------------
     //  Compute the angle and translation of the rigid transformation
     //------------------------------------------------------------------------
         const double meanPtX = sumPtX / matchCount,
                                  meanPtY = sumPtY / matchCount,
                                  meanRefX = sumRefX / matchCount,
                                  meanRefY = sumRefY / matchCount,
                                  meanDet = sumDet / matchCount,
                                  meanDotProd = sumDotProd / matchCount;
         const double dotProdMean = meanPtX*meanRefX + meanPtY*meanRefY,
                                  detMean = meanPtX*meanRefY - meanPtY*meanRefX;
         const double A = detMean - meanDet,
                                  B = dotProdMean - meanDotProd,
                                  normAB = sqrt(A*A + B*B);
         const double cosTheta = -B / normAB,
                                  sinTheta = A / normAB;
         const double tx = meanPtX - cosTheta*meanRefX + sinTheta*meanRefY,
                                  ty = meanPtY - sinTheta*meanRefX - cosTheta*meanRefY;
     //------------------------------------------------------------------------
     //  Update the transformation's matrix
     //------------------------------------------------------------------------
         float* const* const mat = transf->getMatrix(R_W_ACCESS);
         mat[0][0] = mat[1][1] =  static_cast<float>(cosTheta);
         mat[0][1] = - (mat[1][0] = static_cast<float>(sinTheta));
         //
         mat[0][2] = static_cast<float>(tx);
         mat[1][2] = static_cast<float>(ty);
         //
         mat[2][0] = mat[2][1] = 0.f;
         mat[2][2] = 1.f;
     //------------------------------------------------------------------------
     //  And finally compute the squared norm of the residual
     //------------------------------------------------------------------------
         double  normSqRes = 0.L;
     for (int i=0; i<nbPts; i++)
         {
                 if (match[i])
                 {
             const double dx = ptX[i] - (cosTheta*refPtX[i] - sinTheta*refPtY[i] + tx),
                          dy = ptY[i] - (sinTheta*refPtX[i] + cosTheta*refPtY[i] + ty);
                         normSqRes += dx*dx + dy*dy;
                 }
         }
     return normSqRes;
 }
Transformation2D * Registration2D_ICP::registerPoints (const Contour * refPts, const Contour * dataPts, const Transformation2D * guessTransf = NULL) virtual
Registers two image contours.
The contours are expected to be listed in counterclockwise order.
Parameters
refPtList the set of reference image points
ptList the set of points to register to the reference
guessTransf optional approximation to the solution
Returns
the transformation to apply to ptList to best fit refPtList
Implements uriVL::Registration2D.
Definition at line 74 of file Registration2D_ICP.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Registration not implemented");
     Transformation2D    *transf = NULL;
     return transf;
 }
Transformation2D* uriVL::Registration2D_ICP::registerPoints (const std::vector< const ImagePoint * > * refPtList, const std::vector< const ImagePoint * > * ptList, const Transformation2D * guessTransf = NULL) virtual
Registers two sets of 2D image points.
Parameters
refPtList the set of reference image points
ptList the set of points to register to the reference
guessTransf optional approximation to the solution
Returns
the transformation to apply to ptList to best fit refPtList
Implements uriVL::Registration2D.
Transformation2D * Registration2D_ICP::registerPoints_aff_ (int nbRefPts, const double * refPtX, const double * refPtY, double * transfRefX, double * transfRefY, int nbPts, const double * ptX, const double * ptY, bool * match, double * matchX, double * matchY) protected
Performs affine registration of two sets of 2D image points.
Parameters
nbRefPts the number of of reference image points
refPtX the array of x coordinates of the reference image points
refPtY the array of y coordinates of the reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
matchX array of x coordinates of the "best match" point (in reference set) for each data point
matchY array of y coordinates of the "best match" point (in reference set) for each data point
Returns
the transformation to apply to the reference to best fit the data
Definition at line 275 of file Registration2D_ICP.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Registration not implemented");
     Transformation2D    *transf = NULL;
     return transf;
 }
Transformation2D * Registration2D_ICP::registerPoints_lin_ (int nbRefPts, const double *const refPtX, const double * refPtY, double * transfRefX, double * transfRefY, int nbPts, const double * ptX, const double * ptY, bool * match, double * matchX, double * matchY) protected
Performs rigid linear registration of two sets of 2D image points.
Parameters
nbRefPts the number of of reference image points
refPtX the array of x coordinates of the reference image points
refPtY the array of y coordinates of the reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
matchX array of x coordinates of the "best match" point (in reference set) for each data point
matchY array of y coordinates of the "best match" point (in reference set) for each data point
Returns
the transformation to apply to the reference to best fit the data
Definition at line 174 of file Registration2D_ICP.cpp.
References uriVL::RigidTransformation2D::getAngle(), uriVL::RigidTransformation2D::getTransX(), uriVL::RigidTransformation2D::getTransY(), PI_F, uriVL::RigidTransformation2D::setAngle(), and uriVL::RigidTransformation2D::setTranslation().
 {
     RigidTransformation2D *transf = new RigidTransformation2D();
         //----------------------------------------------------------------------------
         //      1.      Try to put the registration on the right track (we hope)
         //----------------------------------------------------------------------------
         //      1.1     We set the translation to bring the centroids to coincidence
         double  sumRefX = 0.L,
                         sumRefY = 0.L;
         for (int i=0; i<nbRefPts; i++)
         {
                 sumRefX += refPtX[i];
                 sumRefY += refPtY[i];
         }
         double  sumPtX = 0.L,
                         sumPtY = 0.L;
         for (int i=0; i<nbPts; i++)
         {
                 sumPtX += ptX[i];
                 sumPtY += ptY[i];
         }
 double cx = sumPtX/nbPts,
        cRefX = sumRefX/nbRefPts,
        cy = sumPtY/nbPts,
        cRefY = sumRefY/nbRefPts,
        tx, ty;
     transf->setTranslation(     static_cast<float>(sumPtX/nbPts - sumRefX/nbRefPts),
                                                         static_cast<float>(sumPtY/nbPts - sumRefY/nbRefPts));
     float angle = 0.f;
     float bestAngle = 0.f, lowestCost = 10000000.f;
         const float angleIncr = static_cast<float> (2*PI_F/12);
         //
     do
     {
         tx = cx - cRefX*cosf(angle) + cRefY*sinf(angle);
         ty = cy - cRefY*cosf(angle) - cRefX*sinf(angle);
         transf->setAngle(angle);
         transf->setTranslation(tx, ty);
 cout << endl << "angle = " << angle << endl;
         findBestMatch_(nbRefPts, refPtX, refPtY, transfRefX, transfRefY, nbPts, ptX, ptY,
                        transf, match, matchX, matchY);
         double cost = llsSolutionTransformation(nbPts, ptX, ptY, match, matchX, matchY, transf);
 cout << endl << "\t--> transf = (" << transf->getTransX() << ", " << transf->getTransY() << " | " <<
                           transf->getAngle() << ")" << endl;
 cout << "\tcost = " << cost << endl;
         if (cost < lowestCost)
         {
             lowestCost = cost;
             bestAngle = transf->getAngle();
         }
         angle += angleIncr;
     }
     while (angle < 2*PI_F);
     transf->setAngle(static_cast<float>(bestAngle));
     tx = cx - cRefX*cosf(bestAngle) + cRefY*sinf(bestAngle);
     ty = cy - cRefY*cosf(bestAngle) - cRefX*sinf(bestAngle);
     transf->setTranslation(static_cast<float>(tx), static_cast<float>(ty));
     const int NB_RUNS = 20;
     int k = 0;
     do
     {
 cout << "Iteration " << k << endl << "------------" << endl;
         findBestMatch_(nbRefPts, refPtX, refPtY, transfRefX, transfRefY, nbPts, ptX, ptY,
                        transf, match, matchX, matchY);
         double cost = llsSolutionTransformation(nbPts, ptX, ptY, match, matchX, matchY, transf);
 cout << "\ttransf = (" << transf->getTransX() << ", " << transf->getTransY() << " | " <<
                           transf->getAngle() << ")" << endl;
 cout << "\tcost = " << cost << endl;
         k++;
     } while (k <NB_RUNS);
     return transf;
 }
Transformation2D * Registration2D_ICP::registerPoints_nonlin_ (int nbRefPts, const double * refPtX, const double * refPtY, double * transfRefX, double * transfRefY, int nbPts, const double * ptX, const double * ptY, bool * match, double * matchX, double * matchY) protected
Performs rigid nonlinear registration of two sets of 2D image points.
Parameters
nbRefPts the number of of reference image points
refPtX the array of x coordinates of the reference image points
refPtY the array of y coordinates of the reference image points
transfRefX work array for x coordinates of the transformed reference image points
transfRefY work array for y coordinates of the transformed reference image points
nbPts the number of of data image points
ptX the array of x coordinates of the data image points
ptY the array of y coordinates of the data image points
match array indicating for each data point whether it has a match in the reference set
matchX array of x coordinates of the "best match" point (in reference set) for each data point
matchY array of y coordinates of the "best match" point (in reference set) for each data point
Returns
the transformation to apply to the reference to best fit the data
Definition at line 260 of file Registration2D_ICP.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Registration not implemented");
     Transformation2D    *transf = NULL;
     return transf;
 }
The documentation for this class was generated from the following files:
Registration2D_ICP.h
Registration2D_ICP.cpp