URIVisionLibrary: uriVL::HalfCone3D Class Reference
uriVL::HalfCone3D Class Reference
HalfCone3D class.
#include <HalfCone3D.h>
Public Member Functions
HalfCone3D (GLfloat *origin, GLfloat **axes, bool lengthIsClosed, bool sidesClosed)
Constructor.
HalfCone3D (GLfloat *origin, GLfloat **botAxes, GLfloat *dirAxis, GLfloat **topAxes, bool lengthIsClosed, bool sidesAreClosed)
Constructor.
HalfCone3D (GLfloat *origin, GLfloat *dirAxis, GLfloat bottomRadius, GLfloat topRadius, bool lengthIsClosed, bool sidesAreClosed)
Constructor.
~HalfCone3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
HalfCone3D (const HalfCone3D &obj)
Copy constructor (disabled)
const HalfCone3D & operator= (const HalfCone3D &obj)
Copy operator: disabled.
void init_ (GLfloat *origin, GLfloat **axes)
Initialize the cone.
void init_ (GLfloat *origin, GLfloat **botAxes, GLfloat *dirAxis, GLfloat **topAxes)
Initialize the cone.
void deleteArrays_ (void)
Delete all allocated arrays.
Static Private Member Functions
static void initStatic_ (void)
Initializes the classe's static variables.
Private Attributes
GLfloat *** vertex_
0-based list of vertices
GLfloat ** normal_
0-based list of normals
GLfloat normalTop_ [3]
Normal to the top face.
GLfloat normalBottom_ [3]
Normal to the bottom face.
GLfloat normalLength_ [3]
Normal to the length-side face.
int circStep_
Display resolution along a circular/elliptic face.
int slabStep_
Display resolution along a slab (main axis)
bool closedBottom_
Is the bottom face drawn?
bool closedTop_
Is the top face drawn?
bool closedLength_
Is the length-side face drawn?
Static Private Attributes
static bool initCtSt_ = false
Have the static variables been initialized?
static GLfloat ct_ [kVeryHighDefCircPts]
Precomputed array of cosine values.
static GLfloat st_ [kVeryHighDefCircPts]
Precomputed array of sine values.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
HalfCone3D class.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 48 of file HalfCone3D.h.
Constructor & Destructor Documentation
HalfCone3D::HalfCone3D (GLfloat * origin, GLfloat ** axes, bool lengthIsClosed, bool sidesClosed)
Constructor.
Creates a pointed half-cone from the location of its origin, the directions of the 2 axes of its elliptic bottom face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
lengthIsClosed true if the cone's length face should be drawn
sideClosed true if the cone's bottom face should be drawn
Definition at line 46 of file HalfCone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), init_(), initCtSt_, and initStatic_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPtsHalf, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(sideIsClosed),
                         closedTop_(false),
                         closedLength_(sideIsClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         try {
                 init_(origin, axes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from HalfCone3D constructor.");
                 throw e;
         }
 }
HalfCone3D::HalfCone3D (GLfloat * origin, GLfloat ** botAxes, GLfloat * dirAxis, GLfloat ** topAxes, bool lengthIsClosed, bool sidesAreClosed)
Constructor.
Creates a truncated half-cone from the location of its origin, the directions of the 2 axes of its elliptic bottom face, that of its elliptic top face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
botAxes the 2 axes of the cone bottom face
dirAxis the direction of the cones main axis
topAxes the 2 axes of the cone top face
lengthIsClosed true if the cone's length face should be drawn
sidesAreClosed true if the cone's top and bottom faces should be drawn
Definition at line 87 of file HalfCone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), init_(), initCtSt_, and initStatic_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPtsHalf, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(sidesAreClosed),
                         closedTop_(false),
                         closedLength_(lengthIsClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         try {
                 init_(origin, botAxes, dirAxis, topAxes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from HalfCone3D constructor.");
                 throw e;
         }
 }
HalfCone3D::HalfCone3D (GLfloat * origin, GLfloat * dirAxis, GLfloat bottomRadius, GLfloat topRadius, bool lengthIsClosed, bool sidesAreClosed)
Constructor.
Creates a truncated circular half-cone from the loation of its origin, direction of main axis, and radii of top and bottom faces.
Parameters
origin coordinates of the box's origin (at one corner of the box)
dirAxis the direction of the cones main axis
bottomRadius the radius of the cone's circular bottom face
topRadius the radius of the cone's circular top face
lengthIsClosed true if the cone's length face should be drawn
sidesAreClosed true if the cone's top and bottom faces should be drawn
Definition at line 128 of file HalfCone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::GraphicComponent3D::commonNormalVector(), deleteArrays_(), FAIL_CONDITION, uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), init_(), initCtSt_, initStatic_(), and uriVL::kInvalidParameterError.
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(sidesAreClosed),
                         closedTop_(sidesAreClosed),
                         closedLength_(lengthIsClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         GLfloat         **botAxes, **topAxes, w[3];
         botAxes = GlUtils::glfMatrix(0, 2, 0, 2);
         topAxes = GlUtils::glfMatrix(0, 2, 0, 2);
         try {
                 //      For the major axis, we need to build a vector orthogonal to dirAxis.
                 if ((dirAxis[0]!= 0.f) || (dirAxis[2]!= 0.f))   //      this is not the local Y axis
                 {
                         w[0] = 0.f; w[1] = 1.f; w[2] = 0.f;
                         commonNormalVector(w, dirAxis, botAxes[0]);                             //      "X" = "Y" x "Z"
                         commonNormalVector(dirAxis, botAxes[0], botAxes[1]);    //      "Y" = "Z" x "X"
                         //
                         //      and now we can multiply by the radius
                         for (int i=0; i<3; i++)
{
                                 topAxes[0][i] = botAxes[0][i]*topRad;
                                 topAxes[1][i] = botAxes[1][i]*topRad;
                                 //
                                 botAxes[0][i] *= bottomRad;
                                 botAxes[1][i] *= bottomRad;
                         }
                 }
                 //      if dirAxis was the local Y axis, then I can take Z and X as major and minor
                 else
                 {
                         topAxes[0][0] = topAxes[0][1] = topAxes[1][1] = topAxes[1][2] = 0.f;
                         botAxes[0][0] = botAxes[0][1] = botAxes[1][1] = botAxes[1][2] = 0.f;
                         topAxes[0][2] = topAxes[1][0] = topRad;
                         botAxes[0][2] = botAxes[1][0] = bottomRad;
                 }
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
                 GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to Cone constructor");
         }
         try {
                 init_(origin, botAxes, dirAxis, topAxes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
                 GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
                 e.appendToMessage("called from Cone constructor.");
                 throw e;
         }
         GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
         GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
 }
HalfCone3D::~HalfCone3D (void)
Destructor.
Definition at line 225 of file HalfCone3D.cpp.
References deleteArrays_().
 {
         deleteArrays_();
 }
HalfCone3D::HalfCone3D (const HalfCone3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 201 of file HalfCone3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         circStep_(kCoarseResolution),
                         slabStep_(kCoarseResolution),
                         closedBottom_(false),
                         closedTop_(false),
                         closedLength_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "HalfCone3D copy constructor not implemented.");
 }
Member Function Documentation
void HalfCone3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 567 of file HalfCone3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), kVeryHighDefCircPtsHalf, kVeryHighDefSlabs, normal_, and vertex_.
Referenced by HalfCone3D(), and ~HalfCone3D().
 {
         if (vertex_!=NULL)
         {
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         GlUtils::free_glfMatrix(vertex_[i], 0,  kVeryHighDefCircPtsHalf, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (normal_!=NULL)
         {
                 GlUtils::free_glfMatrix(normal_, 0,  kVeryHighDefCircPtsHalf, 0, 2);
                 normal_ = NULL;
         }
 }
void HalfCone3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 351 of file HalfCone3D.cpp.
References circStep_, closedBottom_, closedLength_, closedTop_, uriVL::GraphicComponent3D::draw(), kVeryHighDefCircPtsHalf, kVeryHighDefSlabs, normal_, normalBottom_, normalLength_, normalTop_, slabStep_, and vertex_.
 {
         GraphicComponent3D::draw();
         for (int i=0; i<=kVeryHighDefSlabs-slabStep_; i+=slabStep_)
         {
                 glBegin(GL_TRIANGLE_STRIP);
                         for (int j=0; j<=kVeryHighDefCircPtsHalf; j+=circStep_)
{
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i+slabStep_][j]);
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i][j]);
                         }
                 glEnd();
         }
         if (closedTop_)
         {
                 glNormal3fv(normalTop_);
                 glBegin(GL_POLYGON);
                         for (int j=0; j<=kVeryHighDefCircPtsHalf; j+=circStep_)
                                 glVertex3fv(vertex_[kVeryHighDefSlabs][j]);
                 glEnd();
         }
         if (closedBottom_)
         {
                 glNormal3fv(normalBottom_);
                 glBegin(GL_POLYGON);
                         for (int j=kVeryHighDefCircPtsHalf; j>=0; j-=circStep_)
                                 glVertex3fv(vertex_[0][j]);
                 glEnd();
         }
         if (closedLength_)
         {
                 glNormal3fv(normalLength_);
                 glBegin(GL_QUADS);
                         glVertex3fv(vertex_[0][0]);
                         glVertex3fv(vertex_[kVeryHighDefSlabs][0]);
                         glVertex3fv(vertex_[kVeryHighDefSlabs][kVeryHighDefCircPtsHalf]);
                         glVertex3fv(vertex_[0][kVeryHighDefCircPtsHalf]);
                 glEnd();
         }
 }
void HalfCone3D::init_ (GLfloat * origin, GLfloat ** axes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
Definition at line 425 of file HalfCone3D.cpp.
References closedBottom_, closedLength_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), ct_, kVeryHighDefCircPtsHalf, kVeryHighDefSlabs, normal_, normalBottom_, uriVL::GraphicComponent3D::normalizeVector(), normalLength_, st_, and vertex_.
Referenced by HalfCone3D().
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         d[3],
                         //      The summit of the cone is = origin + axes[2]
                         summit[3] = {   origin[0] + a[2][0],
                                                         origin[1] + a[2][1],
                                                         origin[2] + a[2][2]},
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radial_j[3],
                         majCross[3], minCross[3];
         //      majCross = a[0] x a[2] (major axis x direction)
         crossProduct(a[0], a[2], majCross);
         //      minCross = a[1] x a[2] (minor axis x direction)
         crossProduct(a[1], a[2], minCross);
         for (int j=0; j<=kVeryHighDefCircPtsHalf; j++)
         {
                 for (int k=0; k<3; k++)
                 {
                         //      coordinates of the radial vector for that angle
                         radial_j[k] = ct_[j]*a[0][k] + st_[j]*a[1][k];
                         //      coordinates of the bottom point for that angle
                         vertex_[0][j][k] = origin[k] + radial_j[k];
                         //      the "top vertex" is at the summit of the cone
                         vertex_[kVeryHighDefSlabs][j][k] = summit[k];
                         //      coordinates of the "step displacement towards the summit.
                         d[k] = dirStep*(a[2][k] - radial_j[k]);
                         //      coordinates of the normal vector for that angle
                         normal_[j][k] = ct_[j]*minCross[k] - st_[j]*majCross[k];
                 }
                 normalizeVector(normal_[j]);
                 for (int i=1; i<kVeryHighDefSlabs; i++)
                 {
                         vertex_[i][j][0] = vertex_[i-1][j][0] + d[0];
                         vertex_[i][j][1] = vertex_[i-1][j][1] + d[1];
                         vertex_[i][j][2] = vertex_[i-1][j][2] + d[2];
                 }
         }
         //      if this is a closed cone, then we must also compute the normal
         //      vector for the bottom face.
         //      normalBottom = -major x minor / ||major x minor||
         //
         if (closedBottom_)
                 commonNormalVector(a[1], a[0], normalBottom_);
         //      Same thing for the length side
         if (closedLength_)
                 //      normalLength_ = major x direction / ||major x direction||
                 commonNormalVector(a[0], a[2], normalLength_);
 }
void HalfCone3D::init_ (GLfloat * origin, GLfloat ** botAxes, GLfloat * dirAxis, GLfloat ** topAxes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
botAxes the 2 axes of the cone bottom face
dirAxis the direction of the cones main axis
topAxes the 2 axes of the cone top face
Definition at line 505 of file HalfCone3D.cpp.
References closedBottom_, closedLength_, closedTop_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), ct_, uriVL::GlUtils::glfMatrix(), kVeryHighDefCircPts, kVeryHighDefCircPtsHalf, kVeryHighDefSlabs, normal_, normalBottom_, uriVL::GraphicComponent3D::normalizeVector(), normalLength_, normalTop_, st_, and vertex_.
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radialTop_j[3], radialBot_j[3],
                         d[3],
                         majCross[3], minCross[3];
         GLfloat origTop[3] = {  origin[0] + dirAxis[0],
                                                         origin[1] + dirAxis[1],
                                                         origin[2] + dirAxis[2]};
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2);
         for (int j=0; j<=kVeryHighDefCircPtsHalf; j++)
         {
                 for (int k=0; k<3; k++)
                 {
                         radialTop_j[k] = ct_[j]*topAxes[0][k] + st_[j]*topAxes[1][k];
                         radialBot_j[k] = ct_[j]*botAxes[0][k] + st_[j]*botAxes[1][k];
                         vertex_[0][j][k] = origin[k] + radialBot_j[k];
                         vertex_[kVeryHighDefSlabs][j][k] = origTop[k] + radialTop_j[k];
                         d[k] = dirStep*(vertex_[kVeryHighDefSlabs][j][k] - vertex_[0][j][k]);
                 }
                 //      Ready to compute the coordinates of the cones "inner" vertices
                 for (int i=1; i<kVeryHighDefSlabs; i++)
                 {
                         vertex_[i][j][0] = vertex_[i-1][j][0] + d[0];
                         vertex_[i][j][1] = vertex_[i-1][j][1] + d[1];
                         vertex_[i][j][2] = vertex_[i-1][j][2] + d[2];
                 }
                 //       We can also compute the normal vector for each angular section of the cone
                 crossProduct(botAxes[0], d, majCross);
                 crossProduct(botAxes[1], d, minCross);
                 for (int k=0; k<3; k++)
                         normal_[j][k] = ct_[j]*minCross[k] - st_[j]*majCross[k];
                 //
                 normalizeVector(normal_[j]);
         }
         //      if this is a closed cone, then we must also compute the normal
         //      vector for the top and bottom faces.
         if (closedTop_)
                 //      normalTop = major x minor / ||major x minor||
                 commonNormalVector(topAxes[0], topAxes[1], normalTop_);
         //
         if (closedBottom_)
                 //      normalBottom = -major x minor / ||major x minor||
                 commonNormalVector(botAxes[1], botAxes[0], normalBottom_);
         //      Same thing for the length side
         if (closedLength_)
                 //      normalLength = major x direction / ||major x direction||
                 commonNormalVector(botAxes[0], dirAxis, normalLength_);
 }
void HalfCone3D::initStatic_ (void) static private
Initializes the classe's static variables.
Definition at line 595 of file HalfCone3D.cpp.
References ct_, initCtSt_, kVeryHighDefCircPts, PI, and st_.
Referenced by HalfCone3D().
 {
         GLfloat dTheta = static_cast<GLfloat>(2.f*PI/kVeryHighDefCircPts);
         for (int j=0; j<kVeryHighDefCircPts; j++)
         {
                 ct_[j] = cosf(j*dTheta);
                 st_[j] = sinf(j*dTheta);
         }
         initCtSt_ = true;
 }
const HalfCone3D & HalfCone3D::operator= (const HalfCone3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 231 of file HalfCone3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "HalfCone3D copy operator not implemented.");
         return *this;
 }
void HalfCone3D::setResolution (ResolutionLevel res) virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 261 of file HalfCone3D.cpp.
 {
         setResolution(res, res);
 }
void HalfCone3D::setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
Parameters
circRes resolution to assign along a circular/elliptic face
slabRes resolution to assign along the main axis
Definition at line 281 of file HalfCone3D.cpp.
References circStep_, kCoarseDefCircScale, kCoarseDefSlabScale, uriVL::kCoarseResolution, kFineDefCircScale, kFineDefSlabScale, uriVL::kFineResolution, kMediumDefCircScale, kMediumDefSlabScale, uriVL::kMediumResolution, uriVL::kVeryHighResolution, kVeryLowDefCircScale, kVeryLowDefSlabScale, uriVL::kVeryLowResolution, and slabStep_.
 {
         switch (circRes)
         {
                 case kVeryHighResolution:
                         circStep_ = 1;
                         break;
                 case kFineResolution:
                         circStep_ = kFineDefCircScale;
                         break;
                 case kMediumResolution:
                         circStep_ = kMediumDefCircScale;
                         break;
                 case kCoarseResolution:
                         circStep_ = kCoarseDefCircScale;
                         break;
                 case kVeryLowResolution:
                         circStep_ = kVeryLowDefCircScale;
                         break;
                 default:
                         circStep_ = kMediumDefCircScale;
                         break;
         }
         switch (slabRes)
         {
                 case kVeryHighResolution:
                         slabStep_ = 1;
                         break;
                 case kFineResolution:
                         slabStep_ = kFineDefSlabScale;
                         break;
                 case kMediumResolution:
                         slabStep_ = kMediumDefSlabScale;
                         break;
                 case kCoarseResolution:
                         slabStep_ = kCoarseDefSlabScale;
                         break;
                 case kVeryLowResolution:
                         slabStep_ = kVeryLowDefSlabScale;
                         break;
                 default:
                         slabStep_ = kMediumDefSlabScale;
                         break;
         }
 }
Member Data Documentation
int uriVL::HalfCone3D::circStep_ private
Display resolution along a circular/elliptic face.
Definition at line 131 of file HalfCone3D.h.
Referenced by draw(), and setResolution().
bool uriVL::HalfCone3D::closedBottom_ private
Is the bottom face drawn?
Definition at line 139 of file HalfCone3D.h.
Referenced by draw(), and init_().
bool uriVL::HalfCone3D::closedLength_ private
Is the length-side face drawn?
Definition at line 147 of file HalfCone3D.h.
Referenced by draw(), and init_().
bool uriVL::HalfCone3D::closedTop_ private
Is the top face drawn?
Definition at line 143 of file HalfCone3D.h.
Referenced by draw(), and init_().
GLfloat HalfCone3D::ct_ static private
Precomputed array of cosine values.
Definition at line 155 of file HalfCone3D.h.
Referenced by init_(), and initStatic_().
bool HalfCone3D::initCtSt_ = false static private
Have the static variables been initialized?
Definition at line 151 of file HalfCone3D.h.
Referenced by HalfCone3D(), and initStatic_().
GLfloat** uriVL::HalfCone3D::normal_ private
0-based list of normals
Definition at line 115 of file HalfCone3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::HalfCone3D::normalBottom_[3] private
Normal to the bottom face.
Definition at line 123 of file HalfCone3D.h.
Referenced by draw(), and init_().
GLfloat uriVL::HalfCone3D::normalLength_[3] private
Normal to the length-side face.
Definition at line 127 of file HalfCone3D.h.
Referenced by draw(), and init_().
GLfloat uriVL::HalfCone3D::normalTop_[3] private
Normal to the top face.
Definition at line 119 of file HalfCone3D.h.
Referenced by draw(), and init_().
int uriVL::HalfCone3D::slabStep_ private
Display resolution along a slab (main axis)
Definition at line 135 of file HalfCone3D.h.
Referenced by draw(), and setResolution().
GLfloat HalfCone3D::st_ static private
Precomputed array of sine values.
Definition at line 159 of file HalfCone3D.h.
Referenced by init_(), and initStatic_().
GLfloat*** uriVL::HalfCone3D::vertex_ private
0-based list of vertices
Definition at line 111 of file HalfCone3D.h.
Referenced by deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
HalfCone3D.h
HalfCone3D.cpp