URIVisionLibrary: uriVL::ColumnVector Class Reference
uriVL::ColumnVector Class Reference
ColumnVector implements the ColumnVector class of Linear Algebra column vectors.
#include <ColumnVector.h>
Public Member Functions
ColumnVector (const int nbRows)
This operator creates a new Matrix equal to the sum of the two terms.
ColumnVector (const int nbRows, const double v)
Creates a new constant column vector at the dimensions specified.
ColumnVector (const int nbRows, const double *v)
Creates a new column vector at the dimensions specified and initializes it with the values of a 1D array.
ColumnVector (const ColumnVector &b)
Copy constructor.
~ColumnVector (void)
Destructor.
void operator+= (const ColumnVector &b)
This function adds the parameter ColumnVector b to this thereby modifying this.
virtual void operator-= (const ColumnVector &b)
This function subtracts the parameter Matrix from this thereby modifying this.
double norm2 () const
Returns the Euclidean norm of this vector.
double dotProd (const ColumnVector *b) const
Computes the dot product of this vector and of the column vector received as parameter.
Matrix * transposition (void) const
Computes the transpose of this vector, which is a row vector.
void normalize1 (void)
Normalize the vector according to norm N1.
void normalize2 (void)
Normalize the vector according to norm N2.
void normalizeInf (void)
Normalize the vector according to norm Ninf.
Public Member Functions inherited from uriVL::Matrix
Matrix (int nbRows, int nbCols)
Creates a nbRows x nbCols matrix whose elements have not been initialized.
Matrix (int nbRows, int nbCols, double v)
"v-valued" constructor of Matrix class.
Matrix (const Matrix *b)
Copy constructor.
Matrix (const Matrix &b)
Copy constructor.
Matrix (int nbRows, int nbCols, double **m, bool safe=true, const MatrixIndicators *matrixIndic=NULL)
"array" constructor of Matrix class.
virtual ~Matrix (void)
Destructor.
int getNbRows (void) const
This function returns a int corresponding to the number of rows in this
int getNbCols (void) const
This function returns a int corresponding to the number of columns in this
const double *const * getMatrix (void) const
Returns a read-only pointer to the matrix data.
double *const * getMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
TriState isSymmetric (void)
Check whether the matrix is symmetric.
TriState isAntisymmetric (void)
Check whether the matrix is antisymmetric.
TriState isOrthogonal (void)
Check whether the matrix is orthogonal.
TriState isDiagonal (void)
Check whether the matrix is diagonal.
TriState isIdentity (void)
Check whether the matrix is an identity matrix.
TriState isUpperTriangular (void)
Check whether the matrix is upper-triangular.
TriState isLowerTriangular (void)
Check whether the matrix is lower-triangular.
double checkSymmetryStatus (void)
Check whether the matrix is symmetric.
double checkAntisymmetryStatus (void)
Check whether the matrix is antisymmetric.
double checkOrthogonalityStatus (void)
Check whether the matrix is orthogonal.
double checkDiagonalityStatus (void)
Check whether the matrix is diagonal.
double checkIdentityStatus (void)
Check whether the matrix is an identity matrix.
double checkUpperTriangularityStatus (void)
Check whether the matrix is upper-triangular.
double checkLowerTriangularityStatus (void)
Check whether the matrix is lower-triangular.
double checkNormalization1Status (void)
Check whether the matrix is normalized according to Norm 1.
double checkNormalization2Status (void)
Check whether the matrix is normalized according to Norm 2.
double checkNormalizationInfStatus (void)
Check whether the matrix is normalized according to Norm 1.
void enforceSymmetry (void)
Forces a matrix that passes the test for symmetry of checkIsSymmetric_ to be exactly symmetric.
void enforcesAntisymmetry (void)
Forces a matrix that passes the test for antisymmetry of checkIsAntisymmetric_ to be exactly antisymmetric.
void enforceOthogonality (void)
Forces a matrix that passes the test for orthogonality of checkIsSymmetric_ to be exactly orthogonality.
void enforceDiagonality (void)
Forces a matrix that passes the test for diagonality of checkIsDiagonal_ to be exactly diagonal.
void enforceIdentity (void)
Forces a matrix that passes the test for identity of checkIsIdentity_ to be exactly identity.
void enforceUpperTriangularity (void)
Forces a matrix that passes the test for upper-triangularity of checkIsUpperTriangular_ to be exactly upper-triangular.
void enforceLowerTriangularity (void)
Forces a matrix that passes the test for lower-triangularity of checkIsLowerTriangular_ to be exactly lower-triangular.
void operator+= (const Matrix &b)
This function adds the parameter Matrix b to this thereby modifying this.
virtual void operator-= (const Matrix &b)
This function subtracts the parameter Matrix from this thereby modifying this.
virtual void operator*= (const double s)
This function multiplies every element of this by the scalar parameter thereby modifying this.
virtual void operator*= (const Matrix &b)
This function premultiplies the parameter Matrix b by this thereby modifying this.
virtual void preMultiplyBy (const Matrix *b)
This function premultiplies this by the parameter Matrix b thereby modifying this
virtual void postMultiplyBy (const Matrix *b)
This function postmultiplies this by the parameter Matrix b thereby modifying this
const Matrix & operator= (const Matrix &b)
Assigns to this matrix the matrix received as parameter (resizes it if necessary.
TriState operator== (const Matrix &b) const
This function does an element-wise comparison to the parameter Matrix b with this.
double operator() (int theRow, int theCol) const
This function returns the element of the Matrix at row theRow and column theCol.
void rowSwap (int r1, int r2)
This function swaps rows of the Matrix (rather, of mat_)
void colSwap (int c1, int c2)
This function swaps columns of the Matrix (rather, of mat_)
double norm1 (void) const
This function returns a double corresponding to the "1" norm of the Matrix this.
double normInf (void) const
This function returns a double corresponding to the "Infinity" norm of the Matrix this.
double determinant (void) const
This function returns a double corresponding to the determinant of the Matrix this.
virtual void transpose (void)
This function transposes this, thereby altering this.
virtual Matrix * inverse (void) const
This function creates a new Matrix corresponding to the inverse of this (if nonsingular).
virtual void invert (void)
This function inverts this (if nonsingular), thereby modifying this.
string toString (void) const
This function returns a string corresponding to the matrix using the static delimiting strings for the Matrix class.
string toString (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) const
This function returns a string corresponding to the matrix using the parameters as delimiting strings.
Static Public Member Functions
static ColumnVector * randomVector (const int nbRows, const double lowerBound, const double upperBound)
produces a new vector filled with random values between lowerBound (inclusive) and upperBound (exclusive)
Static Public Member Functions inherited from uriVL::Matrix
static Matrix * copyMatrix (int nbRows, int nbCols, const double *const *m)
Creates a new nbRows x nbCols matrix and copies into it the elements of the 2D array referenced by m.
static Matrix * nullMatrix (int nbRows, int nbCols)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements to zero.
static Matrix * diagonalMatrix (int nbRows, int nbCols, double v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * diagonalMatrix (int nbRows, int nbCols, const double *v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * identityMatrix (int n)
Produces a new identity matrix at the dimensions specified.
static Matrix * randomMatrix (int nbRows, int nbCols, double lowerBound, double upperBound)
produces a new matrix filled with random values between lowerBound (inclusive) and upperBound (exclusive)
static void setToStringFormat (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor)
This function resets the delimiting strings used when generating a string representation for a given matrix.
Friends
class RowVector
To increase the efficiency of the transpose function, friending the RowVector becomes necessary.
Detailed Description
ColumnVector implements the ColumnVector class of Linear Algebra column vectors.
Definition at line 30 of file ColumnVector.h.
Constructor & Destructor Documentation
ColumnVector::ColumnVector (const int nbRows)
This operator creates a new Matrix equal to the sum of the two terms.
Throws an exception if the matrices' dimensions do not match.
Parameters
a left term in the addition
b right term in the addition
Returns
a reference to a + b This operator creates a new Matrix equal to the difference of the two terms. Throws an exception if the matrices' dimensions do not match.
Parameters
a left term in the difference
b right term in the difference
Returns
a reference to a - bCreates a new zero row vector at the dimensions specified
Parameters
nbRows number of rows of the new column vector
Definition at line 21 of file ColumnVector.cpp.
Referenced by randomVector().
                         :   Matrix(nbRows, 1)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ColumnVector constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid dimensions in ColumnVector constructor");
 }
ColumnVector::ColumnVector (const int nbRows, const double v)
Creates a new constant column vector at the dimensions specified.
Parameters
nbRows number of rows of the new column vector
v the value at which to initialize all elements of the vector
Definition at line 38 of file ColumnVector.cpp.
References uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
                         :   Matrix(nbRows, 1)
 {
     for (int i = 0; i < nbRows_; i++)
         {
         mat_[i][0] = v;
         }
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ColumnVector constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid dimensions in ColumnVector constructor");
 }
ColumnVector::ColumnVector (const int nbRows, const double * v)
Creates a new column vector at the dimensions specified and initializes it with the values of a 1D array.
Parameters
nbRows number of rows of the new column vector
v the array of values at which to initialize the elements of the vector
Definition at line 59 of file ColumnVector.cpp.
References uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
                         :   Matrix(nbRows, 1)
 {
     for (int i = 0; i < nbRows_; i++)
         {
         mat_[i][0] = v[i];
         }
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ColumnVector constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid dimensions in ColumnVector constructor");
 }
ColumnVector::ColumnVector (const ColumnVector & b)
Copy constructor.
Parameters
b the ColumnVector to copy
Definition at line 80 of file ColumnVector.cpp.
                         :   Matrix(b)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by ColumnVector constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid ColumnVector parameter error in ColumnVector constructor");
 }
ColumnVector::~ColumnVector (void)
Destructor.
Definition at line 98 of file ColumnVector.cpp.
 {
 }
Member Function Documentation
double ColumnVector::dotProd (const ColumnVector * b) const
Computes the dot product of this vector and of the column vector received as parameter.
Returns
the dot product of the two vectors
Definition at line 217 of file ColumnVector.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
 {
     FAIL_CONDITION(     nbRows_ != b->nbRows_,
                                 kMatrixIncorrectDimensionsError,
                                 "Vector dimensions don't match in ColumnVector::dotProd");
     double sum = 0.L;
     for (int i=0; i<nbRows_; i++)
         sum += mat_[i][0] * b->mat_[i][0];
     return sum;
 }
double ColumnVector::norm2 (void) const
Returns the Euclidean norm of this vector.
Returns
the Euclidean norm of this vector
Definition at line 206 of file ColumnVector.cpp.
References uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
Referenced by normalize2().
 {
     double sum = 0.L;
     for (int i = 0; i < nbRows_; i++)
         sum += mat_[i][0] * mat_[i][0];
     return sqrt(sum);
 }
void ColumnVector::normalize1 (void)
Normalize the vector according to norm N1.
Definition at line 242 of file ColumnVector.cpp.
References uriVL::IS_TRUE, uriVL::Matrix::isNormalized1_, uriVL::Matrix::mat_, uriVL::Matrix::nbRows_, and uriVL::Matrix::norm1().
 {
         if (isNormalized1_ != IS_TRUE)
         {
                 double  normVal = norm1();
                 if (normVal != 0)
                 {
                         double  normScale = 1.L / normVal;
                         for (int i=0; i<nbRows_; i++)
                                 mat_[i][0] *= normScale;
                 }
                 isNormalized1_ = IS_TRUE;
         }
 }
void ColumnVector::normalize2 (void)
Normalize the vector according to norm N2.
Definition at line 260 of file ColumnVector.cpp.
References uriVL::IS_FALSE, uriVL::IS_TRUE, uriVL::Matrix::isNormalized1_, uriVL::Matrix::isNormalized2_, uriVL::Matrix::isNormalizedInf_, uriVL::Matrix::mat_, uriVL::Matrix::nbRows_, norm2(), and STD_RELATIVE_TOLERANCE.
 {
         if (isNormalized2_ != IS_TRUE)
         {
                 double  normVal = norm2();
                 if (normVal != 0)
                 {
                         double  normScale = 1.L / normVal;
                         for (int i=0; i<nbRows_; i++)
                                 mat_[i][0] *= normScale;
                 }
                 if ((isNormalized1_ == IS_TRUE) && (fabs(normVal - 1.0) > STD_RELATIVE_TOLERANCE))
                         isNormalized1_ = IS_FALSE;
                 if ((isNormalizedInf_ == IS_TRUE) && (fabs(normVal - 1.0) > STD_RELATIVE_TOLERANCE))
                         isNormalizedInf_ = IS_FALSE;
                 isNormalized2_ = IS_TRUE;
         }
 }
void ColumnVector::normalizeInf (void)
Normalize the vector according to norm Ninf.
Definition at line 281 of file ColumnVector.cpp.
References uriVL::IS_TRUE, uriVL::Matrix::isNormalizedInf_, uriVL::Matrix::mat_, uriVL::Matrix::nbRows_, and uriVL::Matrix::normInf().
 {
         if (isNormalizedInf_ != IS_TRUE)
         {
                 double  normVal = normInf();
                 if (normVal != 0)
                 {
                         double  normScale = 1.L / normVal;
                         for (int i=0; i<nbRows_; i++)
                                 mat_[i][0] *= normScale;
                 }
                 isNormalizedInf_ = IS_TRUE;
         }
 }
void ColumnVector::operator+= (const ColumnVector & b)
This function adds the parameter ColumnVector b to this thereby modifying this.
Parameters
b the ColumnVector to add to this
Definition at line 176 of file ColumnVector.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
 {
     FAIL_CONDITION( b.nbRows_ != nbRows_,
                     kMatrixIncorrectDimensionsError,
                     "parameter has incorrect dimensions in ColumnVector::operator +=");
     for (int i=0; i<nbRows_; i++)
         mat_[i][0] += b.mat_[i][0];
 }
void ColumnVector::operator-= (const ColumnVector & b) virtual
This function subtracts the parameter Matrix from this thereby modifying this.
Parameters
b the Matrix to subtract from this
Definition at line 189 of file ColumnVector.cpp.
References FAIL_CONDITION, uriVL::kMatrixIncorrectDimensionsError, uriVL::Matrix::mat_, and uriVL::Matrix::nbRows_.
 {
     FAIL_CONDITION( b.nbRows_ != nbRows_,
                     kMatrixIncorrectDimensionsError,
                     "parameter has incorrect dimensions in ColumnVector::subtractFrom");
     for (int i=0; i<nbRows_; i++)
         mat_[i][0] -= b.mat_[i][0];
 }
ColumnVector * ColumnVector::randomVector (const int nbRows, const double lowerBound, const double upperBound) static
produces a new vector filled with random values between lowerBound (inclusive) and upperBound (exclusive)
Parameters
nbRows the number of rows in the vector
lowerBound lower bound for the range of random values
upperBound upper bound for the range of random values
Returns
a new nbRows x nbCols random matrix
Definition at line 103 of file ColumnVector.cpp.
References ColumnVector(), and uriVL::RandomGenerator_C::nextDouble_st().
 {
     ColumnVector* v = new ColumnVector(nbRows);
     for (int i = 0; i < nbRows; i++)
         v->mat_[i][0] = RandomGenerator_C::nextDouble_st(upperBound, lowerBound);
     return v;
 }
Matrix * ColumnVector::transposition (void) const virtual
Computes the transpose of this vector, which is a row vector.
Returns
the transpose of this column vector: a row vector
Reimplemented from uriVL::Matrix.
Definition at line 231 of file ColumnVector.cpp.
References uriVL::Matrix::mat_, uriVL::Matrix::nbRows_, and RowVector.
Referenced by main().
 {
     RowVector *rowVect = new RowVector(nbRows_);
     for (int i=0; i<nbRows_; i++)
         rowVect->mat_[0][i] = mat_[i][0];
     return rowVect;
 }
Friends And Related Function Documentation
friend class RowVector friend
To increase the efficiency of the transpose function, friending the RowVector becomes necessary.
Definition at line 35 of file ColumnVector.h.
Referenced by transposition().
The documentation for this class was generated from the following files:
ColumnVector.h
ColumnVector.cpp