URIVisionLibrary: uriVL::Disparity Class Reference
uriVL::Disparity Class Reference
Generic class for all sort of disparities (stereo, motion in particular).
#include <Disparity.h>
Public Member Functions
Disparity (bool isSubpixelDisparity=false)
Default Constructor.
Disparity (const Disparity *disp)
Copy constructor.
Disparity (const Disparity &disp)
Copy constructor.
Disparity (const Vector2D *disp, float score)
Constructor.
Disparity (int dx, int dy, float score)
Constructor.
Disparity (float dx, float dy, float score, bool isSubpixelDisp=true)
Constructor.
~Disparity (void)
Destructor.
const Disparity & operator= (const Disparity &theObj)
Copy operator.
bool isSubpixelDisparity (void) const
Indicates whether the disparity computed uses integers of floating point (subpixel) numbers.
const Vector2D_F * getDisparity (void) const
Returns the disparity.
Vector2D_F * getDisparity (ReadWriteStatus rw)
Returns the disparity.
float getScore (void)
Returns the confidence.
virtual void setScore (float score)
Assigns new confidence.
void setDisparity (const Vector2D *disp)
Assigns new disparity.
void setDisparity (const Vector2D_F *disp)
Assigns new disparity.
void setDisparity (int x, int y)
Assigns new disparity.
void setDisparity (float x, float y, bool isSubpixelDisp)
Assigns new subpixel disparity.
Private Attributes
Vector2D_F * disparity_
Stores displacement between the left and right matching points.
bool isSubpixelDisparity_
Indicates whether the disparity is calculated with subpixel accuracy.
float score_
Matching confidence, in [0, 1].
Detailed Description
Generic class for all sort of disparities (stereo, motion in particular).
The disparity information proper is held by a Vector2D_F object storing a 2D displacement, a boolean that indicates whether or not that displacement has subpixel precision, and a "confidence" in the disparity value.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 36 of file Disparity.h.
Constructor & Destructor Documentation
Disparity::Disparity (bool isSubpixelDisparity = false)
Default Constructor.
Creates a zero-disparity zero-confidence object
Parameters
isSubpixelDisparity = true if the disparity has subpixel precision
Definition at line 30 of file Disparity.cpp.
                 :       disparity_(new Vector2D_F(0.f, 0.f)),
                         isSubpixelDisparity_(isSubpixelDisp),
                         score_(0.f)
 {
 }
Disparity::Disparity (const Disparity * disp)
Copy constructor.
Parameters
disp disparity object to copy
Definition at line 37 of file Disparity.cpp.
References FAIL_CONDITION, and uriVL::kNullImagePointError.
                 :       disparity_(new Vector2D_F(disp->disparity_)),
                         isSubpixelDisparity_(disp->isSubpixelDisparity_),
                         score_(disp->score_)
 {
         FAIL_CONDITION( disp == NULL,
                     kNullImagePointError,
                     "NULL ImagePoint passed as parameter to Disparity constructor");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by Disparity constructor");
         throw e;
 }
Disparity::Disparity (const Disparity & disp)
Copy constructor.
Parameters
disp disparity object to copy
Definition at line 53 of file Disparity.cpp.
                 :       disparity_(new Vector2D_F(disp.disparity_)),
                         isSubpixelDisparity_(disp.isSubpixelDisparity_),
                         score_(disp.score_)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by Disparity constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "invalid ImagePoint passed as parameter to Disparity constructor");
 }
Disparity::Disparity (const Vector2D * disp, float score)
Constructor.
Allocates a disparity with a confidence.
Parameters
disp disparity
score confidence [0, 1]
Definition at line 70 of file Disparity.cpp.
                 :       disparity_(new Vector2D_F(disp)),
                         isSubpixelDisparity_(false),
                         score_(score)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by Disparity constructor");
         throw e;
 }
 catch (...) {
         FAIL_CONDITION( disp == NULL,
                     kNullImagePointError,
                     "NULL ImagePoint passed as parameter to Disparity constructor");
         FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "invalid ImagePoint passed as parameter to Disparity constructor");
 }
Disparity::Disparity (int dx, int dy, float score)
Constructor.
Allocates a disparity with a confidence.
Parameters
dx horizontal component of disparity
dy vertical coordinate of disparity
score confidence [0, 1]
Definition at line 90 of file Disparity.cpp.
                 :       disparity_(new Vector2D_F(dx, dy)),
                         isSubpixelDisparity_(false),
                         score_(score)
 {
 }
Disparity::Disparity (float dx, float dy, float score, bool isSubpixelDisp = true)
Constructor.
Allocates a disparity with a confidence.
Parameters
dx horizontal component of disparity
dy vertical coordinate of disparity
score confidence [0, 1]
isSubpixelDisp true if this object is trully a float disparity
Definition at line 98 of file Disparity.cpp.
                 :       disparity_(new Vector2D_F(dx, dy)),
                         isSubpixelDisparity_(isSubpixelDisp),
                         score_(score)
 {
 }
Disparity::~Disparity (void)
Destructor.
Definition at line 106 of file Disparity.cpp.
References disparity_.
 {
     if (disparity_ != NULL)
         delete disparity_;
 }
Member Function Documentation
const Vector2D_F * Disparity::getDisparity (void) const
Returns the disparity.
Returns
disparity
Definition at line 129 of file Disparity.cpp.
References disparity_.
 {
         return disparity_;
 }
Vector2D_F * Disparity::getDisparity (ReadWriteStatus rw)
Returns the disparity.
Returns
disparity
Definition at line 134 of file Disparity.cpp.
References disparity_.
 {
         return disparity_;
 }
float Disparity::getScore (void)
Returns the confidence.
Returns
confidence
Definition at line 194 of file Disparity.cpp.
References score_.
 {
         return score_;
 }
bool Disparity::isSubpixelDisparity (void) const
Indicates whether the disparity computed uses integers of floating point (subpixel) numbers.
Returns
true if this disparity can return a floating point, subpixel disparity value
Definition at line 204 of file Disparity.cpp.
References isSubpixelDisparity_.
 {
     return isSubpixelDisparity_;
 }
const Disparity & Disparity::operator= (const Disparity & theObj)
Copy operator.
Parameters
theObj reference to the object to copy
Definition at line 113 of file Disparity.cpp.
References disparity_, isSubpixelDisparity_, and score_.
 {
         disparity_ = obj.disparity_;
         score_ = obj.score_;
         isSubpixelDisparity_ = obj.isSubpixelDisparity_;
         return *this;
 }
void Disparity::setDisparity (const Vector2D * disp)
Assigns new disparity.
Parameters
disp displacement stored in an ImagePoint object
Definition at line 139 of file Disparity.cpp.
References disparity_, FAIL_CONDITION, uriVL::Vector2D::getX(), uriVL::Vector2D::getY(), isSubpixelDisparity_, uriVL::kInvalidParameterError, uriVL::kNullImagePointError, and uriVL::Vector2D_F::setCoordinates().
Referenced by uriVL::StereoMatcher::disparity().
 {
         try {
                 if (typeid(*disp) == typeid(uriVL::ImagePoint_F))
                         setDisparity(static_cast<const Vector2D_F*>(disp));
                 else
                 {
                         disparity_->setCoordinates(disp->getX(), disp->getY());
                         isSubpixelDisparity_ = true;
                 }
         }
         catch(...) {
                 FAIL_CONDITION( disp == NULL,
                                                 kNullImagePointError,
                                                 "NULL ImagePoint passed as parameter to Disparity::setDisparity");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
 }
void Disparity::setDisparity (const Vector2D_F * disp)
Assigns new disparity.
Parameters
disp displacement stored in an ImagePoint object
Definition at line 162 of file Disparity.cpp.
References disparity_, FAIL_CONDITION, uriVL::Vector2D_F::getXF(), uriVL::Vector2D_F::getYF(), isSubpixelDisparity_, uriVL::kInvalidParameterError, uriVL::kNullImagePointError, and uriVL::Vector2D_F::setCoordinates().
 {
         try {
                 disparity_->setCoordinates(disp->getXF(), disp->getYF());
                 isSubpixelDisparity_ = true;
         }
         catch(...) {
                 FAIL_CONDITION( disp == NULL,
                                                 kNullImagePointError,
                                                 "NULL ImagePoint passed as parameter to Disparity::setDisparity");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid coordinate pointer passed to ImagePoint_F::setCoordinates.");
         }
 }
void Disparity::setDisparity (int x, int y)
Assigns new disparity.
Parameters
x x component of the disparity
y y component of the disparity
isSubpixelDisp true if this object is in fact a float disparity
Definition at line 181 of file Disparity.cpp.
References disparity_, isSubpixelDisparity_, and uriVL::Vector2D_F::setCoordinates().
 {
         disparity_->setCoordinates(x, y);
         isSubpixelDisparity_ = false;
 }
void Disparity::setDisparity (float x, float y, bool isSubpixelDisp)
Assigns new subpixel disparity.
Parameters
x x component of the disparity
y y component of the disparity
isSubpixelDisp true if this object is in fact a float disparity
Definition at line 187 of file Disparity.cpp.
References disparity_, isSubpixelDisparity_, and uriVL::Vector2D_F::setCoordinates().
 {
         disparity_->setCoordinates(x, y);
         isSubpixelDisparity_ = isSubpixelDisp;
 }
void Disparity::setScore (float score) virtual
Assigns new confidence.
Parameters
score new confidence
Definition at line 199 of file Disparity.cpp.
References score_.
Referenced by uriVL::StereoMatcher::disparity().
 {
         score_ = conf;
 }
Member Data Documentation
Vector2D_F* uriVL::Disparity::disparity_ private
Stores displacement between the left and right matching points.
See also
isLeftToRight_
Definition at line 166 of file Disparity.h.
Referenced by getDisparity(), operator=(), setDisparity(), and ~Disparity().
bool uriVL::Disparity::isSubpixelDisparity_ private
Indicates whether the disparity is calculated with subpixel accuracy.
Definition at line 171 of file Disparity.h.
Referenced by isSubpixelDisparity(), operator=(), and setDisparity().
float uriVL::Disparity::score_ private
Matching confidence, in [0, 1].
Definition at line 175 of file Disparity.h.
Referenced by getScore(), operator=(), and setScore().
The documentation for this class was generated from the following files:
Disparity.h
Disparity.cpp