URIVisionLibrary: uriVL::TrackingState Class Reference
uriVL::TrackingState Class Reference
#include <TrackingState.h>
Public Member Functions
TrackingState (void)
Default constructor Creates a TrackingState.
TrackingState (float x, float y)
Constructor Creates a TrackingState.
TrackingState (const ImagePoint_F *pos)
Constructor Creates a TrackingState.
TrackingState (const TrackingState &ts)
Copy Constructor.
TrackingState (const TrackingState *ts)
Copy Constructor.
virtual ~TrackingState (void)
Destructor.
const TrackingState & operator= (const TrackingState &ts)
Copy operator.
const ImagePoint_F * getPos (void) const
get the position in state information
void setPos (const ImagePoint_F *pos)
set the position in state information
void setPos (float x, float y)
set the position in state information
Result getResult (void) const
get tracking result
void setResult (Result r)
set tracking result
bool getTargetGone (void) const
get targetGone_
void setTargetGone (bool tg)
set targetGone_
Private Attributes
ImagePoint_F * pos_
position of the target
Result result_
indicate tracking result
bool targetGone_
if fails up to failCounts times, targeGone = true
Detailed Description
Definition at line 50 of file TrackingState.h.
Constructor & Destructor Documentation
TrackingState::TrackingState (void)
Default constructor Creates a TrackingState.
Definition at line 25 of file TrackingState.cpp.
                         :       pos_(new ImagePoint_F(0.f, 0.f)),
                                 result_(TARGET_FOUND),
                                 targetGone_(false)
 {
 }
TrackingState::TrackingState (float x, float y)
Constructor Creates a TrackingState.
Parameters
x x coordinate of the target
y y coordinate of the target
Definition at line 32 of file TrackingState.cpp.
                         :       pos_(new ImagePoint_F(x, y)),
                                 result_(TARGET_FOUND),
                                 targetGone_(false)
 {
 }
TrackingState::TrackingState (const ImagePoint_F * pos)
Constructor Creates a TrackingState.
Parameters
pos position of the target
Definition at line 39 of file TrackingState.cpp.
                         :       pos_(new ImagePoint_F(pos)),
                                 result_(TARGET_FOUND),
                                 targetGone_(false)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by TrackingState constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kUnknown,
                                         "Unidentified error in TrackingState constructor");
 }
TrackingState::TrackingState (const TrackingState & ts)
Copy Constructor.
Parameters
ts TrackingState to copy
Definition at line 58 of file TrackingState.cpp.
                         :       pos_(new ImagePoint_F(ts.pos_)),
                                 result_(ts.result_),
                                 targetGone_(ts.targetGone_)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by TrackingState copy constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kUnknown,
                                         "Unidentified error in TrackingState copy constructor");
 }
TrackingState::TrackingState (const TrackingState * ts)
Copy Constructor.
Parameters
ts TrackingState to copy
Definition at line 77 of file TrackingState.cpp.
                         :       pos_(new ImagePoint_F(ts->pos_)),
                                 result_(ts->result_),
                                 targetGone_(ts->targetGone_)
 {
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by TrackingState copy constructor");
         throw e;
 }
 catch (...)
 {
         FAIL_CONDITION( true,
                                         kUnknown,
                                         "Unidentified error in TrackingState copy constructor");
 }
TrackingState::~TrackingState (void) virtual
Destructor.
Definition at line 96 of file TrackingState.cpp.
References pos_.
 {
         if (pos_ != NULL)
                 delete  pos_;
 }
Member Function Documentation
const ImagePoint_F * TrackingState::getPos (void) const
get the position in state information
Returns
position as an ImagePoint
Definition at line 155 of file TrackingState.cpp.
References pos_.
Referenced by uriVL::PatternTracker2DController::action(), myDisplay2(), myDisplay3(), myIdle(), operator=(), uriVL::PatternTracker2D::PatternTracker2D(), and uriVL::PatternTracker2D::track().
 {
         return pos_;
 }
Result TrackingState::getResult (void) const
get tracking result
Definition at line 135 of file TrackingState.cpp.
References result_.
Referenced by uriVL::BlobTracker2DController::action(), and operator=().
 {
         return result_;
 }
bool TrackingState::getTargetGone (void) const
get targetGone_
Definition at line 145 of file TrackingState.cpp.
References targetGone_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::BlobTracker2DController::action(), and operator=().
 {
         return targetGone_;
 }
const TrackingState & TrackingState::operator= (const TrackingState & ts)
Copy operator.
Parameters
ts TrackingState to copy
Definition at line 112 of file TrackingState.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, getPos(), getResult(), getTargetGone(), uriVL::kUnknown, pos_, result_, and targetGone_.
 {
         try
         {
                 pos_ = new ImagePoint_F(ts.getPos());
                 result_ = ts.getResult();
                 targetGone_ = ts.getTargetGone();
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by TrackingState copy operator");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( true,
                                                 kUnknown,
                                                 "Unidentified error in TrackingState copy operator");
         }
         return *this;
 }
void TrackingState::setPos (const ImagePoint_F * pos)
set the position in state information
Parameters
new position as an ImagePoint
Definition at line 160 of file TrackingState.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), pos_, and uriVL::ImagePoint_F::setCoordinates().
Referenced by uriVL::PatternTracker2D::track().
 {
         try
         {
                 pos_->setCoordinates(pos->getX(), pos->getY());
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by TrackingState::setPos");
                 throw e;
         }
 }
void TrackingState::setPos (float x, float y)
set the position in state information
Parameters
x
y
Definition at line 173 of file TrackingState.cpp.
References pos_, and uriVL::ImagePoint_F::setCoordinates().
 {
         pos_->setCoordinates(x, y);
 }
void TrackingState::setResult (Result r)
set tracking result
Parameters
new result
Definition at line 140 of file TrackingState.cpp.
References result_.
Referenced by uriVL::BlobTracker2D::track(), and uriVL::PatternTracker2D::track().
 {
         result_ = r;
 }
void TrackingState::setTargetGone (bool tg)
set targetGone_
Definition at line 150 of file TrackingState.cpp.
References targetGone_.
Referenced by uriVL::PatternTracker2D::track().
 {
         targetGone_ = tg;
 }
Member Data Documentation
ImagePoint_F* uriVL::TrackingState::pos_ private
position of the target
Definition at line 144 of file TrackingState.h.
Referenced by getPos(), operator=(), setPos(), and ~TrackingState().
Result uriVL::TrackingState::result_ private
indicate tracking result
See also
enum Result
Definition at line 150 of file TrackingState.h.
Referenced by getResult(), operator=(), and setResult().
bool uriVL::TrackingState::targetGone_ private
if fails up to failCounts times, targeGone = true
Definition at line 155 of file TrackingState.h.
Referenced by getTargetGone(), operator=(), and setTargetGone().
The documentation for this class was generated from the following files:
TrackingState.h
TrackingState.cpp