URIVisionLibrary: uriVL::GlUtils Class Reference
uriVL::GlUtils Class Reference
Contains various GL-related "utility" functions to allocate and delete "shifted" 1D and 2D arrays of GLxxx elements.
#include <GlUtils.h>
Static Public Member Functions
static GLfloat * glfVector (int nl, int nh)
Allocates a 1D array of GLfloat elements that uses the index range specified by the parameters received.
static GLdouble * gldVector (int nl, int nh)
Allocates a 1D array of GLdloat elements that uses the index range specified by the parameters received.
static GLuint * gluiVector (int nl, int nh)
Allocates a 1D array of GLuint elements that uses the index range specified by the parameters received.
static GLint * gliVector (int nl, int nh)
Allocates a 1D array of GLint elements that uses the index range specified by the parameters received.
static GLfloat ** glfMatrix (int nrl, int nrh, int ncl, int nch)
Allocates a 2D array of GLfloat elements that uses the index range specified by the parameters received.
static GLdouble ** gldMatrix (int nrl, int nrh, int ncl, int nch)
Allocates a 2D array of GLdouble elements that uses the index range specified by the parameters received.
static void free_glfVector (GLfloat *v, int nl, int nh)
Frees the 1D array of GLfloat elements received as parameter.
static void free_gldVector (GLdouble *v, int nl, int nh)
Frees the 1D array of GLdouble elements received as parameter.
static void free_gluiVector (GLuint *v, int nl, int nh)
Frees the 1D array of GLuint elements received as parameter.
static void free_gliVector (GLint *v, int nl, int nh)
Frees the 1D array of GLint elements received as parameter.
static void free_glfMatrix (GLfloat **m, int nrl, int nrh, int ncl, int nch)
Frees the 2D array of GLfloat elements received as parameter.
static void free_gldMatrix (GLdouble **m, int nrl, int nrh, int ncl, int nch)
Frees the 2D array of GLdouble elements received as parameter.
Private Member Functions
GlUtils (void)
~GlUtils (void)
Detailed Description
Contains various GL-related "utility" functions to allocate and delete "shifted" 1D and 2D arrays of GLxxx elements.
Definition at line 27 of file GlUtils.h.
Constructor & Destructor Documentation
uriVL::GlUtils::GlUtils (void) private
uriVL::GlUtils::~GlUtils (void) private
Member Function Documentation
void GlUtils::free_gldMatrix (GLdouble ** m, int nrl, int nrh, int ncl, int nch) static
Frees the 2D array of GLdouble elements received as parameter.
Parameters
nrl low row index value
nrh high row index value
ncl low column index value
nch high column index value
See also
gldMatrix
Definition at line 196 of file GlUtils.cpp.
 {
         int     i;
         if ( m!= NULL)
         {
                 for(i=nrh;i>=nrl;i--)
                 {
                         m[i] += ncl;
                         delete [] m[i];
                 }
                 m += nrl;
                 delete [] m;
         }
 }
void GlUtils::free_gldVector (GLdouble * v, int nl, int nh) static
Frees the 1D array of GLdouble elements received as parameter.
Parameters
nl low index value
nh high index value [not used by this function]
See also
gldVector
Definition at line 141 of file GlUtils.cpp.
 {
         if ( v!= NULL)
         {
                 v += nl;
                 delete []v;
         }
 }
void GlUtils::free_glfMatrix (GLfloat ** m, int nrl, int nrh, int ncl, int nch) static
Frees the 2D array of GLfloat elements received as parameter.
Parameters
nrl low row index value
nrh high row index value
ncl low column index value
nch high column index value
See also
glfMatrix
Definition at line 177 of file GlUtils.cpp.
Referenced by uriVL::Cone3D::Cone3D(), uriVL::Cylinder3D::Cylinder3D(), uriVL::Box3D::deleteArrays_(), uriVL::Prism3D::deleteArrays_(), uriVL::Cylinder3D::deleteArrays_(), uriVL::Cone3D::deleteArrays_(), uriVL::TubularSection3D::deleteArrays_(), uriVL::HalfCone3D::deleteArrays_(), uriVL::HalfCone3D::HalfCone3D(), uriVL::HalfCylinder3D::HalfCylinder3D(), uriVL::Prism3D::Prism3D(), uriVL::TubularSection3D::TubularSection3D(), and uriVL::PolyMesh3D::~PolyMesh3D().
 {
         int     i;
         if ( m!= NULL)
         {
                 for(i=nrh;i>=nrl;i--)
                 {
                         m[i] += ncl;
                         delete [] m[i];
                 }
                 m += nrl;
                 delete [] m;
         }
 }
void GlUtils::free_glfVector (GLfloat * v, int nl, int nh) static
Frees the 1D array of GLfloat elements received as parameter.
Parameters
nl low index value
nh high index value [not used by this function]
See also
glfVector
Definition at line 129 of file GlUtils.cpp.
 {
         if ( v!= NULL)
         {
                 v += nl;
                 delete []v;
         }
 }
void GlUtils::free_gliVector (GLint * v, int nl, int nh) static
Frees the 1D array of GLint elements received as parameter.
Parameters
nl low index value
nh high index value [not used by this function]
See also
gliVector
Definition at line 165 of file GlUtils.cpp.
 {
         if ( v!= NULL)
         {
                 v += nl;
                 delete [] v;
         }
 }
void GlUtils::free_gluiVector (GLuint * v, int nl, int nh) static
Frees the 1D array of GLuint elements received as parameter.
Parameters
nl low index value
nh high index value [not used by this function]
See also
gluiVector
Definition at line 153 of file GlUtils.cpp.
 {
         if ( v!= NULL)
         {
                 v += nl;
                 delete [] v;
         }
 }
GLdouble ** GlUtils::gldMatrix (int nrl, int nrh, int ncl, int nch) static
Allocates a 2D array of GLdouble elements that uses the index range specified by the parameters received.
Parameters
nrl low row index value
nrh high row index value
ncl low column index value
nch high column index value
Returns
new array
See also
free_gldMatrix
Definition at line 103 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
 {
         int      i;
         GLdouble** m;
         m = new GLdouble*[nrh-nrl+1];
         FAIL_CONDITION( m == NULL,
                         kOpenGLNumAllocError,
                         "level 1 allocation failure in gldMatrix");
         m -= nrl;
         for(i=nrl;i<=nrh;i++)
         {
                 m[i]= new GLdouble[nch-ncl+1];
         FAIL_CONDITION( m[i] == NULL,
                         kOpenGLNumAllocError,
                         "level 2 allocation failure in gldMatrix");
                 m[i] -= ncl;
         }
         return m;
 }
GLdouble * GlUtils::gldVector (int nl, int nh) static
Allocates a 1D array of GLdloat elements that uses the index range specified by the parameters received.
Parameters
nl low index value
nh high index value
Returns
new array
See also
free_gldVector
Definition at line 36 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
 {
         GLdouble* v;
         v = new GLdouble[nh-nl+1];
         FAIL_CONDITION( v == NULL,
                         kOpenGLNumAllocError,
                         "allocation failure in gldVector");
         return v-nl;
 }
GLfloat ** GlUtils::glfMatrix (int nrl, int nrh, int ncl, int nch) static
Allocates a 2D array of GLfloat elements that uses the index range specified by the parameters received.
Parameters
nrl low row index value
nrh high row index value
ncl low column index value
nch high column index value
Returns
new array
See also
free_glfMatrix
Definition at line 78 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
Referenced by uriVL::Cone3D::Cone3D(), uriVL::Cylinder3D::Cylinder3D(), uriVL::HalfCone3D::HalfCone3D(), uriVL::HalfCylinder3D::HalfCylinder3D(), uriVL::Prism3D::init_(), uriVL::Cylinder3D::init_(), uriVL::Cone3D::init_(), uriVL::TubularSection3D::init_(), uriVL::HalfCone3D::init_(), uriVL::Prism3D::Prism3D(), and uriVL::TubularSection3D::TubularSection3D().
 {
         int     i;
         GLfloat** m;
         m = new GLfloat*[nrh-nrl+1];
         FAIL_CONDITION( m == NULL,
                         kOpenGLNumAllocError,
                         "level 1 allocation failure in glfMatrix");
         m -= nrl;
         for(i=nrl;i<=nrh;i++)
         {
                 m[i]= new GLfloat[nch-ncl+1];
         FAIL_CONDITION( m[i] == NULL,
                         kOpenGLNumAllocError,
                         "level 2 allocation failure in glfMatrix");
                 m[i] -= ncl;
         }
         return m;
 }
GLfloat * GlUtils::glfVector (int nl, int nh) static
Allocates a 1D array of GLfloat elements that uses the index range specified by the parameters received.
Parameters
nl low index value
nh high index value
Returns
new array
See also
free_glfVector
Definition at line 22 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
 {
         GLfloat* v;
         v = new GLfloat[nh-nl+1];
         FAIL_CONDITION( v == NULL,
                         kOpenGLNumAllocError,
                         "allocation failure in glfVector");
         return v-nl;
 }
GLint * GlUtils::gliVector (int nl, int nh) static
Allocates a 1D array of GLint elements that uses the index range specified by the parameters received.
Parameters
nl low index value
nh high index value
Returns
new array
See also
free_gliVector
Definition at line 64 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
 {
         GLint   *v;
         v = new GLint[nh-nl+1];
         FAIL_CONDITION( v == NULL,
                         kOpenGLNumAllocError,
                         "allocation failure in gliVector");
         return v-nl;
 }
GLuint * GlUtils::gluiVector (int nl, int nh) static
Allocates a 1D array of GLuint elements that uses the index range specified by the parameters received.
Parameters
nl low index value
nh high index value
Returns
new array
See also
free_gluiVector
Definition at line 50 of file GlUtils.cpp.
References FAIL_CONDITION, and uriVL::kOpenGLNumAllocError.
 {
         GLuint  *v;
         v = new GLuint[nh-nl+1];
         FAIL_CONDITION( v == NULL,
                         kOpenGLNumAllocError,
                         "allocation failure in gluiVector");
         return v-nl;
 }
The documentation for this class was generated from the following files:
GlUtils.h
GlUtils.cpp