URIVisionLibrary: uriVL::ColorImageGradient Class Reference
uriVL::ColorImageGradient Class Reference abstract
Pure virtual parent class for an operator that computes the gradient of a color raster image.
#include <ColorImageGradient.h>
Public Member Functions
virtual ~ColorImageGradient (void)
Destructor.
int getWidth (void) const
Returns the width of the filter.
int getHeight (void) const
Returns the height of the filter.
virtual float getScale (void) const =0
Returns the scale of the operator.
void setColorGradientMode (ColorGradientMode colorGradientMode)
Sets the Computation mode for the color gradient.
ColorGradientMode getColorGradientMode (void) const
Returns the Computation mode for the color gradient.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual VectorField * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a VectorField.
virtual VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
virtual void applyInto (const RasterImage *imgIn, VectorField *vectOut)=0
Applies this operator to a RasterImage and writes the result into a VectorField received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)=0
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
ColorImageGradient (int theWidth, bool isIntOperator, ColorGradientMode theMode=GRAD_AVE_OF_COLOR_COMPONENTS)
Creates a ColorImageGradient operator with the specified width.
ColorImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator, ColorGradientMode theMode=GRAD_AVE_OF_COLOR_COMPONENTS)
Creates a ColorImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ColorImageGradient (const ColorImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRasters_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRasters_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D red temp raster.
float *const * getShiftedTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D green temp raster.
float *const * getShiftedTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D blue temp raster.
float *const * getShiftedAltTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate red temp raster.
float *const * getShiftedAltTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate green temp raster.
float *const * getShiftedAltTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D alternate blue temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
const ColorImageGradient & operator= (const ColorImageGradient &obj)
Copy operator: disabled.
Private Attributes
ColorGradientMode colorGradientMode_
Computation mode for the color gradient.
ImageRect * boundRect_
Bounding rectangle for pre-allocated temporary raster.
RasterImage_RGBa_F * tempRaster_
Temporary raster.
RasterImage_RGBa_F * altTempRaster_
Second temporary raster for computing the gradient.
double scale_
the scale sigma of this filter
Detailed Description
Pure virtual parent class for an operator that computes the gradient of a color raster image.
Author
jean-yves herve', 3D Group, URI
Definition at line 37 of file ColorImageGradient.h.
Constructor & Destructor Documentation
ColorImageGradient::~ColorImageGradient (void) virtual
Destructor.
Does nothing
Definition at line 79 of file ColorImageGradient.cpp.
References altTempRaster_, boundRect_, and tempRaster_.
 {
    if (boundRect_ != NULL)
         delete boundRect_;
     if (tempRaster_ != NULL)
         delete tempRaster_;
     if (altTempRaster_ != NULL)
         delete altTempRaster_;
 }
ColorImageGradient::ColorImageGradient (int theWidth, bool isIntOperator, ColorGradientMode theMode = GRAD_AVE_OF_COLOR_COMPONENTS) protected
Creates a ColorImageGradient operator with the specified width.
Parameters
theWidth desired width of the Gaussian filter
isIntOperator true if this operator produces only integer output
theMode how the r g b components should be used to compute the gradient
Definition at line 28 of file ColorImageGradient.cpp.
                         :       VectorOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1, isIntOperator),
                                 //
                                 colorGradientMode_(theMode),
                                 scale_(0.2f * (2*(theWidth/2) + 1)),
                                 boundRect_(NULL),
                                 tempRaster_(NULL),
                                 altTempRaster_(NULL)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient constructor");
         throw e;
 }
ColorImageGradient::ColorImageGradient (int theWidth, const ImageRect * theRect, bool isIntOperator, ColorGradientMode theMode = GRAD_AVE_OF_COLOR_COMPONENTS) protected
Creates a ColorImageGradient operator with the specified width and a temporary raster at the specified dimensions.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the ImageGradient
theRect bounding rectangle for the temporary raster
isIntOperator true if this operator produces only integer output
theMode how the r g b components should be used to compute the gradient
Definition at line 47 of file ColorImageGradient.cpp.
                         :       VectorOperator(-theWidth/2, -theWidth/2,
                                                           2*(theWidth/2) + 1, 2*(theWidth/2) + 1, isIntOperator),
                                 colorGradientMode_(theMode),
                                 scale_(0.2f * (2*(theWidth/2) + 1)),
                                 boundRect_(new ImageRect(theRect)),
                                 tempRaster_(new RasterImage_RGBa_F(theRect)),
                                 altTempRaster_(new RasterImage_RGBa_F(theRect))
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorImageGradient constructor");
         throw e;
 }
ColorImageGradient::ColorImageGradient (const ColorImageGradient & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 64 of file ColorImageGradient.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       VectorOperator(),
                                 //
                                 colorGradientMode_(GRAD_AVE_OF_COLOR_COMPONENTS),
                                 scale_(0.f),
                                 boundRect_(NULL),
                                 tempRaster_(NULL),
                                 altTempRaster_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient copy constructor not implemented.");
 }
Member Function Documentation
bool ColorImageGradient::allocateTempRasters_ (const ImageRect * rect) protected
Allocates the temporary raster associated with this object.
If the raster was already allocated, the function only reallocates it if it was smaller than the new rect.
Parameters
rect dimensions of the temp rect to allocate
Returns
true if a new raster was allocated or the old one was resized
Definition at line 143 of file ColorImageGradient.cpp.
References altTempRaster_, uriVL::DrawableObject2D::contains(), uriVL::DrawableObject2D::setBoundRect(), and tempRaster_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto().
 {
         bool newTempRaster = (tempRaster_ == NULL);
     if (newTempRaster) {
         tempRaster_ = new RasterImage_RGBa_F(theRect);
         altTempRaster_ = new RasterImage_RGBa_F(theRect);
         }
         //      Check if the user is a bonehead
     else if (!tempRaster_->contains(theRect)) {
                 tempRaster_->setBoundRect(theRect);
                 altTempRaster_->setBoundRect(theRect);
                 newTempRaster = true;
         }
         return newTempRaster;
 }
void ColorImageGradient::freeTempRasters_ (void) protected
Frees the temporary raster associated with this object.
Definition at line 160 of file ColorImageGradient.cpp.
References altTempRaster_, and tempRaster_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto().
 {
         if (tempRaster_ != NULL) {
                 delete tempRaster_;
                 tempRaster_ = NULL;
         }
         if (altTempRaster_ != NULL) {
                 delete altTempRaster_;
                 altTempRaster_ = NULL;
         }
 }
ColorGradientMode ColorImageGradient::getColorGradientMode (void) const
Returns the Computation mode for the color gradient.
Returns
the Computation mode for the color gradient
Definition at line 130 of file ColorImageGradient.cpp.
References colorGradientMode_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Sobel::applyIntoF_(), and uriVL::ColorImageGradient_Sobel::applyIntoI_().
 {
         return colorGradientMode_;
 }
int ColorImageGradient::getHeight (void) const
Returns the height of the filter.
Returns
height of the filter
Definition at line 112 of file ColorImageGradient.cpp.
References uriVL::ImageRect::getHeight(), and uriVL::VectorOperator::getRect().
 {
     return getRect()->getHeight();
 }
virtual float uriVL::ColorImageGradient::getScale (void) const pure virtual
Returns the scale of the operator.
Returns
scale of the operator
Implemented in uriVL::ColorImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_I, and uriVL::ColorImageGradient_Sobel.
float *const * ColorImageGradient::getShiftedAltTempBlueF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D alternate blue temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 201 of file ColorImageGradient.cpp.
References altTempRaster_, uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), and uriVL::R_W_ACCESS.
 {
         return altTempRaster_->getShiftedBlueF2D(R_W_ACCESS);
 }
float *const * ColorImageGradient::getShiftedAltTempGreenF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D alternate green temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 195 of file ColorImageGradient.cpp.
References altTempRaster_, uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), and uriVL::R_W_ACCESS.
 {
         return altTempRaster_->getShiftedGreenF2D(R_W_ACCESS);
 }
float *const * ColorImageGradient::getShiftedAltTempRedF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D alternate red temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 189 of file ColorImageGradient.cpp.
References altTempRaster_, uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), and uriVL::R_W_ACCESS.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_X_(), and uriVL::ColorImageGradient_Gaussian_F::applyInto_Y_().
 {
         return altTempRaster_->getShiftedRedF2D(R_W_ACCESS);
 }
float *const * ColorImageGradient::getShiftedTempBlueF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D blue temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 184 of file ColorImageGradient.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedBlueF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), and uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_().
 {
         return tempRaster_->getShiftedBlueF2D(R_W_ACCESS);
 }
float *const * ColorImageGradient::getShiftedTempGreenF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D green temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 178 of file ColorImageGradient.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedGreenF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), and uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_().
 {
         return tempRaster_->getShiftedGreenF2D(R_W_ACCESS);
 }
float *const * ColorImageGradient::getShiftedTempRedF2D_ (ReadWriteStatus rw) protected
Gives writing access to the shifted 2D red temp raster.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D gray temp raster
Definition at line 172 of file ColorImageGradient.cpp.
References uriVL::RasterImage_RGBa_F::getShiftedRedF2D(), uriVL::R_W_ACCESS, and tempRaster_.
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_11x11_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_13x13_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_3x3_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_5x5_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_7x7_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_9x9_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), and uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_().
 {
         return tempRaster_->getShiftedRedF2D(R_W_ACCESS);
 }
int ColorImageGradient::getWidth (void) const
Returns the width of the filter.
Returns
width of the filter
Definition at line 107 of file ColorImageGradient.cpp.
References uriVL::VectorOperator::getRect(), and uriVL::ImageRect::getWidth().
Referenced by uriVL::ColorImageGradient_Gaussian_F::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto_X_(), uriVL::ColorImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoF_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_X_(), uriVL::ColorImageGradient_Gaussian_F::applyIntoI_Y_(), uriVL::ColorImageGradient_Gaussian_F::applyTo(), and uriVL::ColorImageGradient_Gaussian_F::initializeFilter_().
 {
     return getRect()->getWidth();
 }
const ColorImageGradient & ColorImageGradient::operator= (const ColorImageGradient & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 90 of file ColorImageGradient.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorImageGradient copy operator not implemented.");
         return *this;
 }
void ColorImageGradient::setColorGradientMode (ColorGradientMode colorGradientMode)
Sets the Computation mode for the color gradient.
Parameters
colorGradientMode
Definition at line 125 of file ColorImageGradient.cpp.
References colorGradientMode_.
Referenced by uriVL::ActiveContourDetector_balloon::findContour(), myMenu2(), and myMenu3().
 {
     colorGradientMode_ = colorGradientMode;
 }
Member Data Documentation
RasterImage_RGBa_F* uriVL::ColorImageGradient::altTempRaster_ private
Second temporary raster for computing the gradient.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 194 of file ColorImageGradient.h.
Referenced by allocateTempRasters_(), freeTempRasters_(), getShiftedAltTempBlueF2D_(), getShiftedAltTempGreenF2D_(), getShiftedAltTempRedF2D_(), and ~ColorImageGradient().
ImageRect* uriVL::ColorImageGradient::boundRect_ private
Bounding rectangle for pre-allocated temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 176 of file ColorImageGradient.h.
Referenced by ~ColorImageGradient().
ColorGradientMode uriVL::ColorImageGradient::colorGradientMode_ private
Computation mode for the color gradient.
default mode is GRAD_AVE_OF_COLOR_COMPONENTS
Definition at line 167 of file ColorImageGradient.h.
Referenced by getColorGradientMode(), and setColorGradientMode().
double uriVL::ColorImageGradient::scale_ private
the scale sigma of this filter
Definition at line 199 of file ColorImageGradient.h.
RasterImage_RGBa_F* uriVL::ColorImageGradient::tempRaster_ private
Temporary raster.
This is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Definition at line 185 of file ColorImageGradient.h.
Referenced by allocateTempRasters_(), freeTempRasters_(), getShiftedTempBlueF2D_(), getShiftedTempGreenF2D_(), getShiftedTempRedF2D_(), and ~ColorImageGradient().
The documentation for this class was generated from the following files:
ColorImageGradient.h
ColorImageGradient.cpp