URIVisionLibrary: uriVL::RasterImage_HSV24 Class Reference
uriVL::RasterImage_HSV24 Class Reference
A RasterImage_HSV24 is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel using only an unsigned char to store the hue, which forces us to scale it from [0, 359] to [0, 255].
#include <RasterImage_HSV24.h>
Public Member Functions
RasterImage_HSV24 (int theRows, int theCols)
Creates a RasterImage_HSV24 object at the specified dimensions.
RasterImage_HSV24 (ImageRect *theRect)
Allocates an HSV24 raster image at the specified dimensions.
RasterImage_HSV24 (int theRows, int theCols, unsigned char *hue, unsigned char *sat, unsigned char *val)
Creates and initializes a raster image using the specified dimensions and values.
RasterImage_HSV24 (RasterImage *img)
Clonor constructor.
virtual ~RasterImage_HSV24 (void)
Destructor.
unsigned char * getHue (void)
unsigned char * getSat (void)
unsigned char * getVal (void)
unsigned char ** getHue2D (void)
unsigned char ** getSat2D (void)
unsigned char ** getVal2D (void)
unsigned char ** getShiftedHue2D (void)
unsigned char ** getShiftedSat2D (void)
unsigned char ** getShiftedVal2D (void)
Public Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
RasterImage_RGBa (const ImageRect *theRect)
Allocates a 32-bit RGBa color raster image at the specified dimensions.
RasterImage_RGBa (int nbRows, int nbCols, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const ImageRect *theRect, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (GraphWorld *gworld, bool keepThisGraphWorld=false)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img)
Initializes an rgba raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img, const ImageRect *theRect)
Initializes an rgba raster image at the specified dimensions and values.
virtual ~RasterImage_RGBa (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
virtual const unsigned char * getRGBa (void) const
Returns the 32-bit rgba base raster as a read-only 1D array.
virtual unsigned char * getRGBa (ReadWriteStatus rw)
Returns the 32-bit rgba base raster as a read-write 1D array.
virtual const unsigned char *const * getRGBa2D (void) const
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
virtual unsigned char *const * getRGBa2D (ReadWriteStatus rw)
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRGBa2D (void) const
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRGBa2D (ReadWriteStatus rw)
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void rgb2HSV (unsigned char r, unsigned char g, unsigned char b, unsigned char *hue, unsigned char *sat, unsigned char *val)
static void rgb2HSV (unsigned char rgb[], unsigned char *hue, unsigned char *sat, unsigned char *val)
Static Public Member Functions inherited from uriVL::RasterImage_RGBa
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Copies a 1D RGBa32 raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 16-bit aRGB16 raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, bool *localRGBa)
Allocates a read-only RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
void convertFromRGBa_ (void)
void convertFromRGBa_ (ImageRect *theRect)
Protected Member Functions inherited from uriVL::RasterImage_RGBa
RasterImage_RGBa (void)
Protected default constructor.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Protected Attributes
unsigned char * hue_
unsigned char * sat_
unsigned char * val_
unsigned char ** hue2D_
unsigned char ** sat2D_
unsigned char ** val2D_
unsigned char ** shiftedHue2D_
unsigned char ** shiftedSat2D_
unsigned char ** shiftedVal2D_
Private Member Functions
void allocateHSV_ (int theRows, int theCols)
void deleteHSV_ (void)
Detailed Description
A RasterImage_HSV24 is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel using only an unsigned char to store the hue, which forces us to scale it from [0, 359] to [0, 255].
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 33 of file RasterImage_HSV24.h.
Constructor & Destructor Documentation
RasterImage_HSV24::RasterImage_HSV24 (int theRows, int theCols)
Creates a RasterImage_HSV24 object at the specified dimensions.
Parameters
theRows number of rows of the raster image to create
theCols number of columns of the raster image to create
Definition at line 30 of file RasterImage_HSV24.cpp.
References allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::DrawableObject2D::boundRect_, uriVL::RasterImage::gworldIsReference_, and uriVL::RasterImage::referenceHasChanged_.
         :       RasterImage_RGBa( ),
                         //
                         hue_(NULL),
                         sat_(NULL),
                         val_(NULL),
                         hue2D_(NULL),
                         sat2D_(NULL),
                         val2D_(NULL),
                         shiftedHue2D_(NULL),
                         shiftedSat2D_(NULL),
                         shiftedVal2D_(NULL),
                         //
                         hsvIsReference_(false)
 {
     boundRect_ = new ImageRect(0, 0, theCols, theRows);
     gworldIsReference_ = false;
     referenceHasChanged_ = false;
     allocateRaster2D_( );
     allocateShiftedRaster2D_( );
 }
RasterImage_HSV24::RasterImage_HSV24 (ImageRect * theRect)
Allocates an HSV24 raster image at the specified dimensions.
Allocates an HSV24 color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 54 of file RasterImage_HSV24.cpp.
References allocateRaster2D_(), uriVL::DrawableObject2D::boundRect_, FAIL_CONDITION, uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, hue2D_, hue_, uriVL::kNullRectangleError, uriVL::RasterImage::referenceHasChanged_, sat2D_, sat_, shiftedHue2D_, shiftedSat2D_, shiftedVal2D_, val2D_, and val_.
         :       RasterImage_RGBa( )
 {
     gworld_ = NULL;
     hue_ = NULL;
     sat_ = val_ = NULL;
     hue2D_ = shiftedHue2D_ = NULL;
     sat2D_ = val2D_ = shiftedSat2D_ = shiftedVal2D_ = NULL;
     gworldIsReference_ = false;
     referenceHasChanged_ = false;
     boundRect_ = new ImageRect(theRect);
     FAIL_CONDITION( boundRect_ == NULL,
                     kNullRectangleError,
                     "ImageRect creation failed in RasterImage_HSV24 constructor");
     allocateRaster2D_( );
 }
RasterImage_HSV24::RasterImage_HSV24 (int theRows, int theCols, unsigned char * hue, unsigned char * sat, unsigned char * val)
Creates and initializes a raster image using the specified dimensions and values.
Parameters
theRows number of rows of the raster image to create
theCols number of columns of the raster image to create
hue 1D raster storing hue values in the range [0, 359]
sat 1D raster storing saturation values in the range [0, 100]
val 1D raster storing the value in the range [0, 255]
Definition at line 73 of file RasterImage_HSV24.cpp.
References allocateRaster2D_(), uriVL::DrawableObject2D::boundRect_, FAIL_CONDITION, hue2D_, hue_, uriVL::kNullRasterError, sat2D_, sat_, shiftedHue2D_, shiftedSat2D_, shiftedVal2D_, val2D_, and val_.
         : RasterImage_RGBa( )
 {
     FAIL_CONDITION(     (hue==NULL) || (sat==NULL) || (val==NULL),
                     kNullRasterError,
                     "NULL array passed to RasterImage_HSV24 constructor");
     boundRect_ = new ImageRect(0, 0, theCols, theRows);
     long        nbPixels = theRows * theCols;
     hue_ = NULL;
     sat_ = val_ = NULL;
     hue2D_ = shiftedHue2D_ = NULL;
     sat2D_ = val2D_ = shiftedSat2D_ = shiftedVal2D_ = NULL;
     allocateRaster2D_( );
     //  There is no padding for the H, S, & V arrays, so global memcpy calls are possible
     memcpy((char* ) hue_, (char* ) hue, nbPixels);
     memcpy((char* ) val_, (char* ) val, nbPixels);
     memcpy((char* ) sat_, (char* ) sat, nbPixels);
 }
RasterImage_HSV24::RasterImage_HSV24 (RasterImage * img)
Clonor constructor.
Parameters
img the image to clone
Definition at line 96 of file RasterImage_HSV24.cpp.
References FAIL_CONDITION, and uriVL::kRasterImageError.
         : RasterImage_RGBa( )
 {
     FAIL_CONDITION( true,
                     kRasterImageError,
                     "RasterImage_HSV24 cloning constructor not implemented yet");
 }
RasterImage_HSV24::~RasterImage_HSV24 (void) virtual
Destructor.
Definition at line 105 of file RasterImage_HSV24.cpp.
References deleteHSV_(), and deleteRaster2D_().
 {
     deleteHSV_( );
     deleteRaster2D_();
 }
Member Function Documentation
void uriVL::RasterImage_HSV24::allocateHSV_ (int theRows, int theCols) private
void RasterImage_HSV24::allocateRaster2D_ (int nbRows, int nbCols) protected virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Implements uriVL::RasterImage.
Definition at line 412 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::boundRect_, FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getWidth(), hue2D_, hue_, uriVL::kRasterAllocationFailure, sat2D_, sat_, val2D_, and val_.
Referenced by RasterImage_HSV24().
 {
     int   iLow  = boundRect_->getTop(),
                     iHigh = boundRect_->getBottom(),
                             jLow = boundRect_->getLeft(),
                                    jHigh = boundRect_->getRight(),
                                            nbRows = getHeight(),
                                                     nbCols = getWidth();
     long    nbPixels = nbRows*nbCols;
     if (hue_ == NULL)
     {
         hue_ = new unsigned char[nbPixels];
         FAIL_CONDITION( hue_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate hue_ in RasterImage allocateRaster2D_");
         hue2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( hue2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate hue2D_ in RasterImage allocateRaster2D_");
         hue2D_[0] = hue_;
         for (int i=1; i<nbRows; i++)
             hue2D_[i] = hue2D_[i-1] + nbCols;
     }
     if (sat_ == NULL)
     {
         sat_ = new unsigned char[nbPixels];
         FAIL_CONDITION( sat_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate sat_ in RasterImage allocateRaster2D_");
         sat2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( sat2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate sat2D_ in RasterImage allocateRaster2D_");
         sat2D_[0] = sat_;
         for (int i=1; i<nbRows; i++)
             sat2D_[i] = sat2D_[i-1] + nbCols;
     }
     if (val_ == NULL)
     {
         val_ = new unsigned char[nbPixels];
         FAIL_CONDITION( val_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate value in RasterImage allocateRaster2D_");
         val2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( val2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate val2D_ in RasterImage allocateRaster2D_");
         val2D_[0] = val_;
         for (int i=1; i<nbRows; i++)
             val2D_[i] = val2D_[i-1] + nbCols;
     }
 }
void RasterImage_HSV24::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) protected virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implements uriVL::RasterImage.
Definition at line 506 of file RasterImage_HSV24.cpp.
References FAIL_CONDITION, hue_, uriVL::kRasterAllocationFailure, sat_, shiftedHue2D_, shiftedSat2D_, shiftedVal2D_, and val_.
Referenced by RasterImage_HSV24().
 {
     const int   iHigh = iLow + nbRows - 1,
                                 jHigh = jLow + nbCols - 1;
     if (hue_ != NULL)
     {
         shiftedHue2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedHue2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedHue2D_ in RasterImage_HSV24::allocateRaster2D_");
         shiftedHue2D_[0] = hue_ - iLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedHue2D_[i+1] = shiftedHue2D_[i] + nbCols;
     }
     if (sat_ != NULL)
     {
         shiftedSat2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedSat2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedHue2D_ in RasterImage_HSV24::allocateRaster2D_");
         shiftedSat2D_[0] = sat_ - iLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedSat2D_[i+1] = shiftedSat2D_[i] + nbCols;
     }
     if (val_ != NULL)
     {
         shiftedVal2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedVal2D_==NULL,
                         kRasterAllocationFailure,
                         "Could not allocate shiftedVal2D_ in RasterImage_HSV24::allocateRaster2D_");
         shiftedVal2D_[0] = val_ - iLow;
         for (int i=iLow; i<iHigh; i++)
             shiftedVal2D_[i+1] = shiftedVal2D_[i] + nbCols;
     }
 }
void RasterImage_HSV24::convertFromRGBa_ (void) protected
Definition at line 118 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::gworldIsReference_, hue2D_, MAX, MIN, uriVL::RasterImage::referenceHasChanged_, sat2D_, and val2D_.
Referenced by convertFromRGBa_().
 {
     unsigned char       maxVal, minVal,
     pRed, pGreen, pBlue,
     **rgba = getRGBa2D();
     int           nbRows = getHeight(),
                              nbCols = getWidth();
     if (gworldIsReference_ && referenceHasChanged_)
     {
         for (int i=0; i<nbRows; i++)
         {
             for (int j=0, rgbaIndex=0; j<nbCols; j++, rgbaIndex++)
             {
                 pRed = rgba[i][rgbaIndex++];
                 pGreen = rgba[i][rgbaIndex++];
                 pBlue = rgba[i][rgbaIndex++];
                 maxVal = MAX(MAX(pRed, pGreen), pBlue);
                 minVal = MIN(MIN(pRed, pGreen), pBlue);
                 /*      HueSaturationV  */
                 val2D_[i][j] = (unsigned char) ((100 * maxVal) / 255);
                 if (maxVal != minVal)
                 {
                     sat2D_[i][j] = ((maxVal-minVal)*100)/maxVal;
                     if ( pRed == maxVal )
                         hue2D_[i][j] = (pGreen-pBlue)*42/(maxVal-minVal);
                     else if ( pGreen == maxVal )
                         hue2D_[i][j] = 83 + (pBlue-pRed)*43/(maxVal-minVal);
                     else
                         hue2D_[i][j] = 128 + (pRed-pGreen)*42/(maxVal-minVal);
                     //  we want the hue_ in the range [0, 255).
                     if ( hue2D_[i][j] < 0)
                         hue2D_[i][j] += 255;
                 }
                 else
                 {
                     sat2D_[i][j] = 0;
                     hue2D_[i][j] = 0;
                 }
             }
         }
     }
     referenceHasChanged_ = false;
 }
void RasterImage_HSV24::convertFromRGBa_ (ImageRect * theRect) protected
Definition at line 168 of file RasterImage_HSV24.cpp.
References convertFromRGBa_(), FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::ImageRect::getLeft(), uriVL::RasterImage_RGBa::getRGBa2D(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::gworldIsReference_, hue2D_, uriVL::kRasterDimensionsDontMatch, MAX, MIN, uriVL::RasterImage::referenceHasChanged_, sat2D_, and val2D_.
 {
     if (theRect == NULL)
         convertFromRGBa_( );
     else
     {
         unsigned char   maxVal, minVal,
         pRed, pGreen, pBlue,
         **rgba = getRGBa2D();
         int           nbRows = getHeight(),
                                  nbCols = getWidth(),
                                           iLow = theRect->getTop( ),
                                                  iHigh = theRect->getBottom( ),
                                                          jLow = theRect->getLeft( ),
                                                                 jHigh = theRect->getRight( );
         FAIL_CONDITION( (iLow < 0) || (iHigh > nbRows) || (jLow < 0) || (jHigh > nbCols),
                         kRasterDimensionsDontMatch,
                         "Invalid rectangle dimensions for RGB to HSV conversion");
         if (gworldIsReference_ && referenceHasChanged_)
         {
             for (int i=iLow; i<=iHigh; i++)
             {
                 for (int j=jLow, rgbaIndex=4*jLow; j<=jHigh; j++, rgbaIndex++)
                 {
                     pRed = rgba[i][rgbaIndex++];
                     pGreen = rgba[i][rgbaIndex++];
                     pBlue = rgba[i][rgbaIndex++];
                     maxVal = MAX(MAX(pRed, pGreen), pBlue);
                     minVal = MIN(MIN(pRed, pGreen), pBlue);
                     /*  HueSaturationV  */
                     val2D_[i][j] = (unsigned char) ((100 * maxVal) / 255);
                     if (maxVal != minVal)
                     {
                         sat2D_[i][j] = ((maxVal-minVal)*100)/maxVal;
                         if ( pRed == maxVal )
                             hue2D_[i][j] = (pGreen-pBlue)*42/(maxVal-minVal);
                         else if ( pGreen == maxVal )
                             hue2D_[i][j] = 83 + (pBlue-pRed)*42/(maxVal-minVal);
                         else
                             hue2D_[i][j] = 128 + (pRed-pGreen)*42/(maxVal-minVal);
                         //      we want the hue_ in the range [0, 255).
                         if ( hue2D_[i][j] < 0)
                             hue2D_[i][j] += 255;
                     }
                     else
                     {
                         sat2D_[i][j] = 0;
                         hue2D_[i][j] = 0;
                     }
                 }
             }
         }
         referenceHasChanged_ = false;
     }
 }
void RasterImage_HSV24::deleteHSV_ (void) private
Definition at line 468 of file RasterImage_HSV24.cpp.
References hue_, sat_, and val_.
Referenced by ~RasterImage_HSV24().
 {
     if (hue_ != NULL)
     {
         delete hue_;
         hue_ = NULL;
     }
     if (sat_ != NULL)
     {
         delete sat_;
         sat_ = NULL;
     }
     if (val_ != NULL)
     {
         delete val_;
         val_ = NULL;
     }
 }
void RasterImage_HSV24::deleteRaster2D_ (void) protected virtual
Deletes the 0-based 2D base raster.
Implements uriVL::RasterImage.
Definition at line 487 of file RasterImage_HSV24.cpp.
References hue2D_, sat2D_, and val2D_.
Referenced by ~RasterImage_HSV24().
 {
     if (hue2D_ != NULL)
     {
         delete hue2D_;
         hue2D_ = NULL;
     }
     if (sat2D_ != NULL)
     {
         delete sat2D_;
         sat2D_ = NULL;
     }
     if (val2D_ != NULL)
     {
         delete val2D_;
         val2D_ = NULL;
     }
 }
void RasterImage_HSV24::deleteShiftedRaster2D_ (int iLow) protected virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Implements uriVL::RasterImage.
Definition at line 546 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::boundRect_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getTop(), shiftedHue2D_, shiftedSat2D_, and shiftedVal2D_.
 {
     int   iLow  = boundRect_->getTop(),
                     iHigh = boundRect_->getBottom();
     if (shiftedHue2D_ != NULL)
     {
         shiftedHue2D_ += iLow;
         delete []shiftedHue2D_;
         shiftedHue2D_ = NULL;
     }
     if (shiftedSat2D_ != NULL)
     {
         shiftedSat2D_ += iLow;
         delete []shiftedSat2D_;
         shiftedSat2D_ = NULL;
     }
     if (shiftedVal2D_ != NULL)
     {
         shiftedVal2D_ += iLow;
         delete []shiftedVal2D_;
         shiftedVal2D_ = NULL;
     }
 }
unsigned char * RasterImage_HSV24::getHue (void)
Definition at line 310 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, hue_, uriVL::RasterImage::referenceHasChanged_, and uriVL::RasterImage_RGBa::updateRaster_().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return hue_;
 }
unsigned char ** RasterImage_HSV24::getHue2D (void)
Definition at line 334 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, hue2D_, uriVL::RasterImage::referenceHasChanged_, and uriVL::RasterImage_RGBa::updateRaster_().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return hue2D_;
 }
unsigned char * RasterImage_HSV24::getSat (void)
Definition at line 318 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, sat_, and uriVL::RasterImage_RGBa::updateRaster_().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return sat_;
 }
unsigned char ** RasterImage_HSV24::getSat2D (void)
Definition at line 342 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, sat2D_, and uriVL::RasterImage_RGBa::updateRaster_().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return sat2D_;
 }
unsigned char ** RasterImage_HSV24::getShiftedHue2D (void)
Definition at line 358 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::boundRect_, uriVL::RasterImage::gworldIsReference_, hue2D_, uriVL::RasterImage::referenceHasChanged_, shiftedHue2D_, uriVL::RasterImage_RGBa::updateRaster_(), and uriVL::ImageRect::upperLeftIsAtOrigin().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (boundRect_->upperLeftIsAtOrigin())
         return hue2D_;
     else
         return shiftedHue2D_;
 }
unsigned char ** RasterImage_HSV24::getShiftedSat2D (void)
Definition at line 373 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::boundRect_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, sat2D_, shiftedSat2D_, uriVL::RasterImage_RGBa::updateRaster_(), and uriVL::ImageRect::upperLeftIsAtOrigin().
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (boundRect_->upperLeftIsAtOrigin())
         return sat2D_;
     else
         return shiftedSat2D_;
 }
unsigned char ** RasterImage_HSV24::getShiftedVal2D (void)
Definition at line 388 of file RasterImage_HSV24.cpp.
References uriVL::DrawableObject2D::boundRect_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, shiftedVal2D_, uriVL::RasterImage_RGBa::updateRaster_(), uriVL::ImageRect::upperLeftIsAtOrigin(), and val2D_.
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (boundRect_->upperLeftIsAtOrigin())
         return val2D_;
     else
         return shiftedVal2D_;
 }
unsigned char * RasterImage_HSV24::getVal (void)
Definition at line 326 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, uriVL::RasterImage_RGBa::updateRaster_(), and val_.
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return val_;
 }
unsigned char ** RasterImage_HSV24::getVal2D (void)
Definition at line 350 of file RasterImage_HSV24.cpp.
References uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::referenceHasChanged_, uriVL::RasterImage_RGBa::updateRaster_(), and val2D_.
 {
     if (gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     return val2D_;
 }
void RasterImage_HSV24::rgb2HSV (unsigned char r, unsigned char g, unsigned char b, unsigned char * hue, unsigned char * sat, unsigned char * val) static
Definition at line 232 of file RasterImage_HSV24.cpp.
References MAX, and MIN.
 {
     unsigned char       maxVal = MAX(MAX(r, g), b),
                            minVal = MIN(MIN(r, g), b);
     /*  HueSaturationV  */
     *val = (unsigned char) ((100 * maxVal) / 255);
     if (maxVal != minVal)
     {
         *sat = ((maxVal-minVal)*100)/maxVal;
         if ( r == maxVal )
             *hue = (g-b)*42/(maxVal-minVal);
         else if ( g == maxVal )
             *hue = 83 + (b-r)*42/(maxVal-minVal);
         else
             *hue = 128 + (r-g)*42/(maxVal-minVal);
         //      we want the hue in the range [0, 255).
         if ( *hue < 0)
             *hue += 255;
     }
     else
     {
         *sat = 0;
         *hue = 0;
     }
 }
void RasterImage_HSV24::rgb2HSV (unsigned char rgb[], unsigned char * hue, unsigned char * sat, unsigned char * val) static
Definition at line 263 of file RasterImage_HSV24.cpp.
References MAX, and MIN.
 {
     unsigned char       maxVal = MAX(MAX(rgb[0], rgb[1]), rgb[2]),
                            minVal = MIN(MIN(rgb[0], rgb[1]), rgb[2]);
     /*  HueSaturationV  */
     *val = (unsigned char) ((100 * maxVal) / 255);
     if (maxVal != minVal)
     {
         *sat = ((maxVal-minVal)*100)/maxVal;
         if ( rgb[0] == maxVal )
             *hue = (rgb[1]-rgb[2])*42/(maxVal-minVal);
         else if ( rgb[1] == maxVal )
             *hue = 83 + (rgb[2]-rgb[0])*42/(maxVal-minVal);
         else
             *hue = 128 + (rgb[0]-rgb[1])*42/(maxVal-minVal);
         //      we want the hue in the range [0, 255).
         if ( *hue < 0)
             *hue += 255;
     }
     else
     {
         *sat = 0;
         *hue = 0;
     }
 }
Member Data Documentation
unsigned char** uriVL::RasterImage_HSV24::hue2D_ protected
Definition at line 94 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), convertFromRGBa_(), deleteRaster2D_(), getHue2D(), getShiftedHue2D(), and RasterImage_HSV24().
unsigned char* uriVL::RasterImage_HSV24::hue_ protected
Definition at line 91 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getHue(), and RasterImage_HSV24().
unsigned char** uriVL::RasterImage_HSV24::sat2D_ protected
Definition at line 95 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), convertFromRGBa_(), deleteRaster2D_(), getSat2D(), getShiftedSat2D(), and RasterImage_HSV24().
unsigned char* uriVL::RasterImage_HSV24::sat_ protected
Definition at line 92 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getSat(), and RasterImage_HSV24().
unsigned char** uriVL::RasterImage_HSV24::shiftedHue2D_ protected
Definition at line 97 of file RasterImage_HSV24.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), getShiftedHue2D(), and RasterImage_HSV24().
unsigned char** uriVL::RasterImage_HSV24::shiftedSat2D_ protected
Definition at line 98 of file RasterImage_HSV24.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), getShiftedSat2D(), and RasterImage_HSV24().
unsigned char** uriVL::RasterImage_HSV24::shiftedVal2D_ protected
Definition at line 99 of file RasterImage_HSV24.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), getShiftedVal2D(), and RasterImage_HSV24().
unsigned char** uriVL::RasterImage_HSV24::val2D_ protected
Definition at line 96 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), convertFromRGBa_(), deleteRaster2D_(), getShiftedVal2D(), getVal2D(), and RasterImage_HSV24().
unsigned char* uriVL::RasterImage_HSV24::val_ protected
Definition at line 93 of file RasterImage_HSV24.h.
Referenced by allocateRaster2D_(), allocateShiftedRaster2D_(), deleteHSV_(), getVal(), and RasterImage_HSV24().
The documentation for this class was generated from the following files:
RasterImage_HSV24.h
RasterImage_HSV24.cpp