URIVisionLibrary: uriVL::ColorGaussianFilter_I Class Reference
uriVL::ColorGaussianFilter_I Class Reference
ColorGaussianFilter_I class.
#include <ColorGaussianFilter_I.h>
Public Member Functions
ColorGaussianFilter_I (double theScale)
Defines a Gaussian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
ColorGaussianFilter_I (int theWidth)
Defines a Gaussian Filter with a specified "radius".
ColorGaussianFilter_I (double theScale, const ImageRect *theRect)
Creates a Gaussian filter with the specified scale.
ColorGaussianFilter_I (int theWidth, const ImageRect *theRect)
Creates a Gaussian filter with the specified width.
~ColorGaussianFilter_I (void)
Destructor.
RasterImage * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a RasterImage.
RasterImage * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
void applyInto (const RasterImage *imgIn, RasterImage *imgOut)
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Public Member Functions inherited from uriVL::ColorGaussianFilter
int getWidth (void) const
Returns the width of the filter.
int getHeight (void) const
Returns the height of the filter.
float getScale (void) const
Returns the scale of the filter.
Public Member Functions inherited from uriVL::ImageOperator
virtual ~ImageOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
void setFloatConversionMode (ConversionFromFloatMode theMode)
Sets the default conversion mode for this ImageOperator.
ConversionFromFloatMode getFloatConversionMode (void) const
Returns the image operator's conversion mode.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
ColorGaussianFilter_I (const ColorGaussianFilter_I &obj)
Copy constructor (disabled)
const ColorGaussianFilter_I & operator= (const ColorGaussianFilter_I &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
void applyInto_3x3_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 3x3 Gaussian filter.
void applyInto_5x5_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 5x5 Gaussian filter.
void applyInto_7x7_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 7x7 Gaussian filter.
void applyInto_9x9_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 9x9 Gaussian filter.
void applyInto_11x11_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 11x11 Gaussian filter.
void applyInto_13x13_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Hard-coded function that implements a 13x13 Gaussian filter.
void applyInto_ (const RasterImage *imgIn, const ImageRect *theRect, RasterImage *imgOut)
Function that implements a generic (width greater than 13) Gaussian filter.
Private Attributes
int * ig_
Stores into a 1D array (radial distances squared) the filter's coefficients.
int iDenum_
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Additional Inherited Members
Protected Member Functions inherited from uriVL::ColorGaussianFilter
ColorGaussianFilter (double theScale, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
ColorGaussianFilter (int theWidth, bool isIntOperator)
Creates a Gaussian filter with the specified width.
ColorGaussianFilter (double theScale, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified scale.
ColorGaussianFilter (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates a Gaussian filter with the specified width.
ColorGaussianFilter (const ColorGaussianFilter &obj)
Copy constructor (disabled)
~ColorGaussianFilter (void)
Destructor.
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempRedF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D red temp raster.
float *const * getShiftedTempGreenF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D green temp raster.
float *const * getShiftedTempBlueF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D blue temp raster.
Protected Member Functions inherited from uriVL::ImageOperator
ImageOperator (bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Constructor.
ImageOperator (const ImageRect *theRect, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false, ConversionFromFloatMode mode=kSignedFloat)
Sets the image rectangle this operator will work on.
ImageOperator (const ImageOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
ColorGaussianFilter_I class.
Implements the application of a Gaussian filter using only integer weights. Note that in the current implementation of this class the same scale is applied along the x and y directions. Implementing a more general form is a low-priority item at this point.
Definition at line 32 of file ColorGaussianFilter_I.h.
Constructor & Destructor Documentation
ColorGaussianFilter_I::ColorGaussianFilter_I (double theScale)
Defines a Gaussian Filter with a specified scale The relations between scale, radius and width of the filter are width = (int)(5*scale) and width = 2*radius+1.
Parameters
theScale scale parameter sigma of the 2D Gaussian filter
Definition at line 32 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ColorGaussianFilter(theScale, false),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a Gaussian filter is 0.8");
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter_I constructor");
         throw e;
 }
ColorGaussianFilter_I::ColorGaussianFilter_I (int theWidth)
Defines a Gaussian Filter with a specified "radius".
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Gaussian filter
Definition at line 50 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ColorGaussianFilter(theWidth, false),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a Gaussian filter is 3");
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter_I constructor");
         throw e;
 }
ColorGaussianFilter_I::ColorGaussianFilter_I (double theScale, const ImageRect * theRect)
Creates a Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 67 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, initializeFilter_(), and uriVL::kFilterAllocationError.
                         :       ColorGaussianFilter(theScale, theRect, false),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a Gaussian filter is 0.8");
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter_I constructor");
         throw e;
 }
ColorGaussianFilter_I::ColorGaussianFilter_I (int theWidth, const ImageRect * theRect)
Creates a Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 84 of file ColorGaussianFilter_I.cpp.
References initializeFilter_().
                         :       ColorGaussianFilter(theWidth, theRect, false),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     initializeFilter_( );
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter_I constructor");
         throw e;
 }
ColorGaussianFilter_I::~ColorGaussianFilter_I (void)
Destructor.
Definition at line 114 of file ColorGaussianFilter_I.cpp.
References ig_.
 {
         delete [] ig_;
 }
ColorGaussianFilter_I::ColorGaussianFilter_I (const ColorGaussianFilter_I & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 98 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ColorGaussianFilter(theObj),
                                 //
                                 ig_(NULL),
                                 iDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorGaussianFilter_I copy constructor not implemented.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ColorGaussianFilter_I constructor");
         throw e;
 }
Member Function Documentation
void ColorGaussianFilter_I::applyInto (const RasterImage * imgIn, RasterImage * imgOut) virtual
Applies this operator to a RasterImage and writes the result into a second RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 199 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
Referenced by applyTo().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to ColorGaussianFilter_I::applyInto");
     applyInto(imgIn, imgIn->getValidRect(), imgOut);
 }
void ColorGaussianFilter_I::applyInto (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the RasterImage received as parameter.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
imgOut the RasterImage into which the output is written
Implements uriVL::ImageOperator.
Definition at line 207 of file ColorGaussianFilter_I.cpp.
References uriVL::ColorGaussianFilter::allocateTempRaster_(), applyInto_(), applyInto_11x11_(), applyInto_13x13_(), applyInto_3x3_(), applyInto_5x5_(), applyInto_7x7_(), applyInto_9x9_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::ColorGaussianFilter::freeTempRaster_(), uriVL::RasterImage::getBaseRasterType(), uriVL::ImageOperator::getFloatConversionMode(), uriVL::DrawableObject2D::getValidRect(), uriVL::ColorGaussianFilter::getWidth(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kInvalidRasterType, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGBa32Raster, uriVL::DrawableObject2D::setBoundRect(), uriVL::ImageOperator::setFloatConversionMode(), and uriVL::DrawableObject2D::setValidRect().
 {
         //----------------------------------------------------------------
         //      STEP 0:         Test for null or invalid type parameters
         //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to ColorGaussianFilter_I::applyInto");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ColorGaussianFilter_I::applyInto");
     FAIL_CONDITION(     imgOut == NULL,
                                 kNullRasterImageError,
                                 "NULL output raster image passed as parameter to ColorGaussianFilter_I::applyInto");
     //  so far I only accept a RasterImage_RGBa or RasterImage_RGBa_F as a source
         FAIL_CONDITION( imgOut->getBaseRasterType() != kRGBa32Raster,
                         kInvalidRasterType,
                         "ColorGaussianFilter_F::applyInto only accepts RasterImage_RGBa or RasterImage_RGBa_F images as source");
     //  so far I only accept a RasterImage_RGBa or RasterImage_RGBa_F as a destination
         FAIL_CONDITION( imgOut->getBaseRasterType() != kRGBa32Raster,
                         kInvalidRasterType,
                         "ColorGaussianFilter_F::applyInto only accepts RasterImage_RGBa or RasterImage_RGBa_F images as destination");
         //----------------------------------------------------------------
         //      STEP 1:         Test for rectangle intersection
         //----------------------------------------------------------------
         //  determine the output rectangle that the input image can produce.
         //              Here, because we apply a filter of width&height (2m+1), we
         //              "lose m all around".
         ImageRect       *usableRect = new ImageRect(imgIn->getValidRect());
         const int       m = getWidth() / 2;
         usableRect->removeAllAround(m);
         //      ... and determine its intersection with the user-specified output rectangle
         ImageRect       *destRect = ImageRect::intersection(usableRect, theRect);
         delete usableRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle in ColorGaussianFilter_I::applyInto");
     //  if the output image does not contain the destination rect, it must be resized.
     if (!imgOut->contains(destRect))
         imgOut->setBoundRect(destRect);
         //----------------------------------------------------------------
         //      STEP 2:         Perform the calculations
         //----------------------------------------------------------------
     //  allocate a 2D raster for intermediate calculations if needed
     bool newTempRaster = allocateTempRaster_(imgIn->getValidRect());
     switch (getWidth())
     {
         case 3:
             applyInto_3x3_(imgIn, destRect, imgOut);
             break;
         case 5:
             applyInto_5x5_(imgIn, destRect, imgOut);
             break;
         case 7:
             applyInto_7x7_(imgIn, destRect, imgOut);
             break;
         case 9:
             applyInto_9x9_(imgIn, destRect, imgOut);
             break;
         case 11:
             applyInto_11x11_(imgIn, destRect, imgOut);
             break;
         case 13:
             applyInto_13x13_(imgIn, destRect, imgOut);
             break;
         default:
             applyInto_(imgIn, destRect, imgOut);
             break;
     }
         //----------------------------------------------------------------
         //      STEP 4:         Set rectangle
         //----------------------------------------------------------------
         //      Very important:  At the end of the computation, don't forget to set the
         //      output's valid data rectangle.  In "safe" mode, the library has no way to guess
         //      what the valid data rectangle should be and sets it to its minimum value... empty
         imgOut->setValidRect(destRect);
         if (imgOut->hasFloatRaster())
                 (static_cast<RasterImage_RGBa_F*>(imgOut))->setFloatConversionMode(getFloatConversionMode());
         //----------------------------------------------------------------
         //      STEP 5:         Free temporary storage (if needed)
         //----------------------------------------------------------------
 //      if (localRGBa)
 //          delete rgbaImg;
         delete destRect;
     if (newTempRaster)
                 freeTempRaster_();
 }
void ColorGaussianFilter_I::applyInto_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Function that implements a generic (width greater than 13) Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 408 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_11x11_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 11x11 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 377 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_13x13_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 13x13 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 392 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_3x3_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 3x3 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 317 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_5x5_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 5x5 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 332 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_7x7_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 7x7 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 347 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
void ColorGaussianFilter_I::applyInto_9x9_ (const RasterImage * imgIn, const ImageRect * theRect, RasterImage * imgOut) private
Hard-coded function that implements a 9x9 Gaussian filter.
Parameters
imgIn the input image (must be gray-level so far)
theRect the rectangle over which the filter must be applied (it must overlap imgIn's valid data rectangle)
imgOut the output image (must be gray-level so far)
Definition at line 362 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by applyInto().
 {
 // unused variables... -CJC
 //     int   iLow = theRect->getTop(),
 //             iHigh = theRect->getBottom(),
 //             jLow = theRect->getLeft(),
 //             jHigh = theRect->getRight();
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 }
RasterImage * ColorGaussianFilter_I::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a RasterImage.
The RasterImage returned is of the same base type as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 138 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
RasterImage * ColorGaussianFilter_I::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a RasterImage.
The RasterImage returned is of the same form as the input image. For example, if imgIn was RasterImage_Gray_F, then so is the image returned.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the RasterImage obtained by applying the operator to imgIn
Implements uriVL::ImageOperator.
Definition at line 147 of file ColorGaussianFilter_I.cpp.
References applyInto(), FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getValidRect(), uriVL::ColorGaussianFilter::getWidth(), uriVL::ImageRect::intersection(), uriVL::kFunctionNotImplemented, uriVL::kGrayRaster, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION(     imgIn == NULL,
                                 kNullRasterImageError,
                                 "NULL input raster image passed as parameter to ColorGaussianFilter_I::applyTo");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ColorGaussianFilter_I::applyTo");
         ImageRect       *usableRect = new ImageRect(imgIn->getValidRect());
         const int       m = getWidth() / 2;
         usableRect->removeAllAround(m);
         ImageRect       *destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle in ColorGaussianFilter_F::applyTo");
         RasterImage     *imgOut = NULL;
     switch (imgIn->getBaseRasterType())
     {
         case kGrayRaster:
             FAIL_CONDITION(     true,
                                         kFunctionNotImplemented,
                                         "image type not suported by color Gaussian filter yet");
             break;
         case kRGB24Raster:
             FAIL_CONDITION(     true,
                                         kFunctionNotImplemented,
                                         "image type not suported by color Gaussian filter yet");
             break;
         case kRGBa32Raster:
             imgOut = new RasterImage_RGBa_F(destRect);
             break;
         default:
             FAIL_CONDITION(     true,
                                         kFunctionNotImplemented,
                                         "image type not suported by Gaussian filter yet");
             break;
     }
     applyInto(imgIn, theRect, imgOut);
         delete destRect;
         delete usableRect;
         return imgOut;
 }
void ColorGaussianFilter_I::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
ig_
Definition at line 428 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, uriVL::ColorGaussianFilter::getScale(), uriVL::ColorGaussianFilter::getWidth(), iDenum_, ig_, uriVL::kFilterAllocationError, and PI.
Referenced by ColorGaussianFilter_I().
 {
     const int   m = getWidth()/2;
         const double scale = getScale();
     const double sigma2Scale = 1.L / (2.L * scale * scale);
     ig_ = new int[m+1];
     FAIL_CONDITION( ig_ == NULL,
                     kFilterAllocationError,
                     "filter allocation failed");
     //  the scaling denominator is the inverse of the smallest value of the
     //  "floating point filter"
     iDenum_ = static_cast<int>((sqrt(2*PI)*scale) / exp(-m*m*sigma2Scale));
     for (int r=0; r<=m; r++)
         ig_[r] = static_cast<int>(exp((m*m - -r*r)*sigma2Scale));
 }
const ColorGaussianFilter_I & ColorGaussianFilter_I::operator= (const ColorGaussianFilter_I & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 120 of file ColorGaussianFilter_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ColorGaussianFilter_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
int uriVL::ColorGaussianFilter_I::iDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Definition at line 147 of file ColorGaussianFilter_I.h.
Referenced by initializeFilter_().
int* uriVL::ColorGaussianFilter_I::ig_ private
Stores into a 1D array (radial distances squared) the filter's coefficients.
Definition at line 142 of file ColorGaussianFilter_I.h.
Referenced by initializeFilter_(), and ~ColorGaussianFilter_I().
The documentation for this class was generated from the following files:
ColorGaussianFilter_I.h
ColorGaussianFilter_I.cpp