URIVisionLibrary: uriVL::ImageGradient_Gaussian_I Class Reference
uriVL::ImageGradient_Gaussian_I Class Reference
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
#include <ImageGradient_Gaussian_I.h>
Public Member Functions
ImageGradient_Gaussian_I (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
ImageGradient_Gaussian_I (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
ImageGradient_Gaussian_I (double theScale, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
ImageGradient_Gaussian_I (int theWidth, const ImageRect *theRect)
Creates a gradient-of-Gaussian filter with the specified width.
~ImageGradient_Gaussian_I (void)
Destructor.
float getScale (void) const
Returns the scale of the operator.
Public Member Functions inherited from uriVL::ImageGradient
virtual ~ImageGradient (void)
Destructor.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual VectorField * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a VectorField.
virtual VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
virtual void applyInto (const RasterImage *imgIn, VectorField *vectOut)=0
Applies this operator to a RasterImage and writes the result into a VectorField received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)=0
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
ImageGradient_Gaussian_I (const ImageGradient_Gaussian_I &obj)
Copy constructor (disabled)
const ImageGradient_Gaussian_I & operator= (const ImageGradient_Gaussian_I &obj)
Copy operator: disabled.
void initializeFilter_ (void)
Initializes the coefficients' array.
Private Attributes
double scale_
Applies this operator to an image, returns the result as a VectorField.
int * ig_
Stores into a 1D array the filter coefficients for the Gaussian.
int * igD_
Stores into a 1D array the filter coefficients for the Gaussian's derivative.
int iDenum_
denumerator by which to divide the weighted summation computed using the coefficients of ig_
int iDevDenum_
denumerator by which to divide the weighted summation computed using the coefficients of igD_
Additional Inherited Members
Protected Member Functions inherited from uriVL::ImageGradient
ImageGradient (int theWidth, bool isIntOperator)
Creates an ImageGradient operator with the specified width.
ImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates an ImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ImageGradient (const ImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempGrayF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D gray temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
Objects of this class only operate on gray-level images. If a color image is sent as parameter, it gets converted to a gray-level image first. For operation on color images, see ColorImageGradient subclasses.
    Note that in the current implementation of this class the same scale is
    applied along the x and y directions.  Implementing a more general form
    is a low-priority item at this point.
    This class is currently not implemented.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 41 of file ImageGradient_Gaussian_I.h.
Constructor & Destructor Documentation
ImageGradient_Gaussian_I::ImageGradient_Gaussian_I (double theScale)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
Parameters
scale scale sigma of the Gaussian filter
Definition at line 28 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(2*(((int ) (5*theScale))/2) + 1, true),
                                 //
                                 scale_(theScale),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a Gaussian Gradient operator is 0.8");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_I constructor");
         throw e;
 }
ImageGradient_Gaussian_I::ImageGradient_Gaussian_I (int theWidth)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
Parameters
theWidth desired width of the Gaussian filter
Definition at line 80 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(theWidth, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_I constructor");
         throw e;
 }
ImageGradient_Gaussian_I::ImageGradient_Gaussian_I (double theScale, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified scale.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
scale scale sigma of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 54 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(2*(((int ) (5*theScale))/2) + 1, false),
                                 //
                                 scale_(theScale),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theScale < 0.8f,
                     kFilterAllocationError,
                     "The smallest scale admissible for a G Gradient filter is 0.8");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_I constructor");
         throw e;
 }
ImageGradient_Gaussian_I::ImageGradient_Gaussian_I (int theWidth, const ImageRect * theRect)
Creates a gradient-of-Gaussian filter with the specified width.
The scale of the filter is the square root of the variance of the associated distribution. It it also related to the width of the filter by the relation width = ceil(5*scale).
The actual width of the filter = 2*radius + 1
it is set to the smallest odd number greater or equal to the parameter received.
This constructor is useful when processing a set of images that have the same dimensions. It allows reusing the same temporary raster without losing time re-allocating and deleting each at each call.
Parameters
theWidth desired width of the Gaussian filter
theRect bounding rectangle for the temporary raster
Definition at line 106 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, initializeFilter_(), uriVL::kFilterAllocationError, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(theWidth, theRect, false),
                                 //
                                 scale_(0.2L*getWidth()),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I constructor not implemented.");
     FAIL_CONDITION( theWidth < 3,
                     kFilterAllocationError,
                     "The smallest width admissible for a G Gradient filter is 3");
         initializeFilter_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_I constructor");
         throw e;
 }
ImageGradient_Gaussian_I::~ImageGradient_Gaussian_I (void)
Destructor.
Definition at line 150 of file ImageGradient_Gaussian_I.cpp.
References ig_, and igD_.
 {
     delete []ig_;
     delete []igD_;
 }
ImageGradient_Gaussian_I::ImageGradient_Gaussian_I (const ImageGradient_Gaussian_I & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 131 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       ImageGradient(theObj),
                                 //
                                 scale_(theObj.scale_),
                                 ig_(NULL),
                                 igD_(NULL),
                                 iDenum_(1),
                                 iDevDenum_(1)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I copy constructor not implemented.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Gaussian_I constructor");
         throw e;
 }
Member Function Documentation
float ImageGradient_Gaussian_I::getScale (void) const virtual
Returns the scale of the operator.
Returns
scale of the operator
Implements uriVL::ImageGradient.
Definition at line 175 of file ImageGradient_Gaussian_I.cpp.
References scale_.
 {
     return static_cast<float>(scale_);
 }
void ImageGradient_Gaussian_I::initializeFilter_ (void) private
Initializes the coefficients' array.
See also
fg_
fgD_
Definition at line 256 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by ImageGradient_Gaussian_I().
 {
     FAIL_CONDITION(     true,
                                 kFunctionNotImplemented,
                                 "not implemented yet");
 //    const int  m = getWidth()/2;
 //    const double      sigma2Scale = 1.L / (2.L * scale_ * scale_),
 //                                      piSigma = 1.L / (sqrt(2*PI) * scale_),
 //                                      piSigma2 = piSigma/scale_;
 //
 //    ig_ = new int [m+1];
 //    FAIL_CONDITION( ig_ == NULL,
 //                    kFilterAllocationError,
 //                    "filter allocation failed in ImageGradient_Gaussian_I::initializeFilter_");
 //    igD_ = new int [m+1];
 //    FAIL_CONDITION( igD_ == NULL,
 //                    kFilterAllocationError,
 //                    "filter allocation failed in ImageGradient_Gaussian_I::initializeFilter_");
 //
 }
const ImageGradient_Gaussian_I & ImageGradient_Gaussian_I::operator= (const ImageGradient_Gaussian_I & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 157 of file ImageGradient_Gaussian_I.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "ImageGradient_Gaussian_I copy operator not implemented.");
         return *this;
 }
Member Data Documentation
int uriVL::ImageGradient_Gaussian_I::iDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of ig_
Definition at line 169 of file ImageGradient_Gaussian_I.h.
int uriVL::ImageGradient_Gaussian_I::iDevDenum_ private
denumerator by which to divide the weighted summation computed using the coefficients of igD_
Definition at line 174 of file ImageGradient_Gaussian_I.h.
int* uriVL::ImageGradient_Gaussian_I::ig_ private
Stores into a 1D array the filter coefficients for the Gaussian.
Definition at line 160 of file ImageGradient_Gaussian_I.h.
Referenced by ~ImageGradient_Gaussian_I().
int* uriVL::ImageGradient_Gaussian_I::igD_ private
Stores into a 1D array the filter coefficients for the Gaussian's derivative.
Definition at line 164 of file ImageGradient_Gaussian_I.h.
Referenced by ~ImageGradient_Gaussian_I().
double uriVL::ImageGradient_Gaussian_I::scale_ private
Applies this operator to an image, returns the result as a VectorField.
Since the operator is an "integer" operator, then the VectorField returned should have the type matching that of the input image
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgInApplies this operator to an image within the rectangle specified and returns the result as a VectorField.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgInApplies this operator to a RasterImage and writes the result into a VectorField received as second parameter.
Parameters
imgIn the RasterImage to which the operator is applied
vectOut the VectorField into which the output is writtenApplies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 156 of file ImageGradient_Gaussian_I.h.
Referenced by getScale().
The documentation for this class was generated from the following files:
ImageGradient_Gaussian_I.h
ImageGradient_Gaussian_I.cpp