URIVisionLibrary: uriVL::VectorOperator Class Reference
uriVL::VectorOperator Class Reference abstract
Virtual parent class for all vector operators (operators that are applied to a raster image and produce a vector field as their output).
#include <VectorOperator.h>
Public Member Functions
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
virtual VectorField * applyTo (const RasterImage *imgIn)=0
Applies this operator to an image, returns the result as a VectorField.
virtual VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)=0
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
virtual void applyInto (const RasterImage *imgIn, VectorField *vectOut)=0
Applies this operator to a RasterImage and writes the result into a VectorField received as parameter.
virtual void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)=0
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Protected Member Functions
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Private Member Functions
const VectorOperator & operator= (const VectorOperator &obj)
Copy operator: disabled.
Private Attributes
ImageRect * rect_
Neighborhood processing rectangle centered at the pixel to evaluate the operator at.
bool isIntegerOperator_
true if the filter is an "integer" operator
Detailed Description
Virtual parent class for all vector operators (operators that are applied to a raster image and produce a vector field as their output).
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 36 of file VectorOperator.h.
Constructor & Destructor Documentation
VectorOperator::~VectorOperator (void) virtual
Destructor.
Definition at line 68 of file VectorOperator.cpp.
References rect_.
 {
         delete rect_;
 }
VectorOperator::VectorOperator (bool isIntOperator = false) protected
Constructor.
Except for the conversion mode, this constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
    @param  isIntOperator   true if this operator produces only integer output
Definition at line 25 of file VectorOperator.cpp.
                         :       rect_(NULL),
                                 isIntegerOperator_(isIntOperator)
 {
 }
VectorOperator::VectorOperator (const ImageRect * theRect, bool isIntOperator = false) protected
Sets the image rectangle this operator will work on.
Parameters
theRect image rectangle this operator will work on
isIntOperator true if this operator produces only integer output
Definition at line 32 of file VectorOperator.cpp.
                         :       rect_(new ImageRect(theRect)),
                                 isIntegerOperator_(isIntOperator)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by VectorOperator constructor");
         throw e;
 }
VectorOperator::VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator = false) protected
Sets the image rectangle this operator will work on.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
isIntOperator true if this operator produces only integer output
Definition at line 43 of file VectorOperator.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
                         :       rect_(new ImageRect(theLeft, theTop, theWidth, theHeight)),
                                 isIntegerOperator_(isIntOperator)
 {
     FAIL_CONDITION( (theLeft > theTop) || (theWidth < 0) || (theHeight < 0),
                     kInvalidParameterError,
                     "Invalid dimensions passed to VectorOperator constructor.");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by VectorOperator constructor");
         throw e;
 }
VectorOperator::VectorOperator (const VectorOperator & obj) protected
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 58 of file VectorOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       rect_(NULL),
                                 isIntegerOperator_(true)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "VectorOperator copy constructor not implemented.");
 }
Member Function Documentation
virtual void uriVL::VectorOperator::applyInto (const RasterImage * imgIn, VectorField * vectOut) pure virtual
Applies this operator to a RasterImage and writes the result into a VectorField received as parameter.
This function will be overloaded by subclasses of VectorOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Implemented in uriVL::ImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_I, uriVL::ColorImageGradient_Gaussian_F, uriVL::ImageGradient_Sobel, and uriVL::ColorImageGradient_Sobel.
virtual void uriVL::VectorOperator::applyInto (const RasterImage * imgIn, const ImageRect * theRect, VectorField * vectOut) pure virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
This function will be overloaded by subclasses of VectorOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Implemented in uriVL::ImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_I, uriVL::ImageGradient_Sobel, and uriVL::ColorImageGradient_Sobel.
virtual VectorField* uriVL::VectorOperator::applyTo (const RasterImage * imgIn) pure virtual
Applies this operator to an image, returns the result as a VectorField.
This function will be overloaded by subclasses of VectorOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implemented in uriVL::ImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_I, uriVL::ColorImageGradient_Gaussian_F, uriVL::ImageGradient_Sobel, and uriVL::ColorImageGradient_Sobel.
virtual VectorField* uriVL::VectorOperator::applyTo (const RasterImage * imgIn, const ImageRect * theRect) pure virtual
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
This function will be overloaded by subclasses of VectorOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
Returns
the VectorField obtained by applying the operator to imgIn
Implemented in uriVL::ImageGradient_Gaussian_F, uriVL::ColorImageGradient_Gaussian_I, uriVL::ColorImageGradient_Gaussian_F, uriVL::ImageGradient_Sobel, and uriVL::ColorImageGradient_Sobel.
int VectorOperator::getHeight (void) const
Returns the height of this operator's operation rectangle.
Returns
height of this operator's operation rectangle
Definition at line 132 of file VectorOperator.cpp.
References uriVL::ImageRect::getHeight(), and rect_.
 {
     return rect_->getHeight();
 }
const ImageRect * VectorOperator::getRect (void) const
Returns a pointer to this operator's operation rectangle.
Returns
a pointer to this operator's operation rectangle
Definition at line 122 of file VectorOperator.cpp.
References rect_.
Referenced by uriVL::ColorImageGradient::getHeight(), and uriVL::ColorImageGradient::getWidth().
 {
         return rect_;
 }
int VectorOperator::getWidth (void) const
Returns the width of this operator's operation rectangle.
Returns
width of this operator's operation rectangle
Definition at line 127 of file VectorOperator.cpp.
References uriVL::ImageRect::getWidth(), and rect_.
Referenced by uriVL::ImageGradient_Gaussian_F::applyInto(), uriVL::ImageGradient_Gaussian_F::applyInto_X_(), uriVL::ImageGradient_Gaussian_F::applyInto_Y_(), uriVL::ImageGradient_Gaussian_F::applyTo(), and uriVL::ImageGradient_Gaussian_F::initializeFilter_().
 {
     return rect_->getWidth();
 }
bool VectorOperator::isFloatOperator (void) const
returns true if the filter is a "float" operator
Returns
true if the filter is a "float" operator
Definition at line 97 of file VectorOperator.cpp.
References isIntegerOperator_.
 {
     return !isIntegerOperator_;
 }
bool VectorOperator::isIntegerOperator (void) const
returns true if the filter is an "integer" operator
Returns
true if the filter is an "integer" operator
Definition at line 92 of file VectorOperator.cpp.
References isIntegerOperator_.
 {
     return isIntegerOperator_;
 }
const VectorOperator & VectorOperator::operator= (const VectorOperator & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 74 of file VectorOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "VectorOperator copy operator not implemented.");
         return *this;
 }
void VectorOperator::setRect (const ImageRect * theRect) protected
Sets the rectangle on which this operator uh...
operates.
Parameters
theRect image rectangle this operator will work on
Definition at line 115 of file VectorOperator.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "VectorOperator copy operator not implemented.");
 }
void VectorOperator::setRect (int theLeft, int theTop, int theWidth, int theHeight) protected
Sets the rectangle on which this operator uh...
operates.
Parameters
theLeft x coordinate of left column pixels
theTop y coordinate of top row pixels
theWidth number of pixels along a row (pixel-as-point)
theHeight number of pixels along a column (pixel-as-point)
Definition at line 102 of file VectorOperator.cpp.
References FAIL_CONDITION, uriVL::kImageProcessingError, rect_, and uriVL::ImageRect::setRect().
 {
         FAIL_CONDITION( (theWidth < 0) || (theHeight < 0),
                                         kImageProcessingError,
                                         "Error in the computation of MedianFilter_F::applyTo");
         if (rect_ == NULL)
                         rect_ = new ImageRect(theLeft, theTop, theWidth, theHeight);
         else
                 rect_->setRect(theLeft, theTop, theWidth, theHeight);
 }
Member Data Documentation
bool uriVL::VectorOperator::isIntegerOperator_ private
true if the filter is an "integer" operator
Definition at line 225 of file VectorOperator.h.
Referenced by isFloatOperator(), and isIntegerOperator().
ImageRect* uriVL::VectorOperator::rect_ private
Neighborhood processing rectangle centered at the pixel to evaluate the operator at.
Definition at line 220 of file VectorOperator.h.
Referenced by getHeight(), getRect(), getWidth(), setRect(), and ~VectorOperator().
The documentation for this class was generated from the following files:
VectorOperator.h
VectorOperator.cpp