URIVisionLibrary: uriVL::ContourForce Class Reference
uriVL::ContourForce Class Reference
A contour force is a connected set of pixels that share a comon characteristic.
#include <ContourForce.h>
Public Member Functions
ContourForce (void)
Constructor.
~ContourForce (void)
Destructor.
void setNeedleColor (float red, float green, float blue)
Assigns a rendering color to the contour force's needles (alpha is set to 1)
void setNeedleColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour force's needles (alpha is set to 1)
void setNeedleColor (const float theColor[])
Assigns a rendering color to the contour force's needles (alpha is set to 1)
void setNeedleColor (const unsigned char theColor[])
Assigns a rendering color to the contour force's needles (alpha is set to 1)
void setColor (float red, float green, float blue)
Assigns a rendering color to the contour force's contour (alpha is set to 1)
void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour force's contour (alpha is set to 1)
void setColor (const float theColor[])
Assigns a rendering color to the contour force's contour (alpha is set to 1)
void setColor (const unsigned char theColor[])
Assigns a rendering color to the contour force's contour (alpha is set to 1)
void setDrawPoints (bool drawPointCircle)
Sets whether to draw a point at each vertex of the contour.
const ImageRect * getBoundRect (void) const
Returns the contour's bounding rectangle.
const ImageRect * getValidRect (void) const
Returns the contour's valid data rectangle.
void insertIntoForceVector (int pointIndex, float valueX, float valueY)
Creates a new element in the force vector and assigns it to the values.
void addForce (ContourForce *cForce2)
Adds the force vector (element by element) to the class's force vector.
void setForcesToZero (void)
Sets the force's values to zero.
bool applyForceToContour (void)
Adds the force vector to contourforce's mapped contour.
void mapToContour (Contour_F *contourIn)
Assigns a contour to which the force is currently applied to.
const Contour_F * getContour (void) const
Returns a read-only pointer to the contour force's geometric contour (list of points)
const std::list< Vector2D_F * > * getForce (void) const
Returns a writable pointer to the contour force's geometric contour (list of points)
std::list< Vector2D_F * > * getForce (ReadWriteStatus rw)
Returns a writable pointer to the X and Y component vector of the force.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
void setRenderContour (bool isRendered)
Indicates whether the contour should be rendered (when false, only the needles are rendered).
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Private Member Functions
ContourForce (const ContourForce &theObj)
Copy Constructor.
const ContourForce & operator= (const ContourForce &theObj)
Copy operator.
void render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint *origin) const
Renders the contour at the depth and location specified.
void computeBoundingRect_ (ImageRect &rect) const
Calculates the object's bounding rect.
void computeValidRect_ (ImageRect &rect) const
Calculates the object's valid box.
void computeCentroid_ (ImagePoint_F &cent) const
Computes the contour's centroid.
void computeCenterOfMass_ (ImagePoint_F &cent) const
Computes the object's center of mass by calculating the average point.
void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Attempts (and fails) to a new bounding rectangle for the contour force.
void setValidRect_ (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the contour force.
Private Attributes
Contour_F * contourSubject2Force_
Stores a pointer to the contour which the force is mapped to.
std::list< Vector2D_F * > force_
Stores the force which can be applied to counter points x and y coordinates.
float needleColor_ [4]
The rendering color for the force's "needles".
bool renderContour_
Should the contour be rendered.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Detailed Description
A contour force is a connected set of pixels that share a comon characteristic.
Typically a contour force is detected after a labelling information (color regions, motion detection, etc.)
Author
Clifford Manzanillo Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file ContourForce.h.
Constructor & Destructor Documentation
ContourForce::ContourForce (void)
Constructor.
Definition at line 32 of file ContourForce.cpp.
References needleColor_.
         :   DrawableObject2D(),
                         contourSubject2Force_(NULL),
                         force_(list<Vector2D_F*>()),
                         renderContour_(true)
 {
     needleColor_[0] = needleColor_[1] = needleColor_[2] = 0.f;
     needleColor_[3] = 1.0f;
 }
ContourForce::~ContourForce (void)
Destructor.
Definition at line 54 of file ContourForce.cpp.
References contourSubject2Force_, and force_.
 {
         list<Vector2D_F*>::const_iterator       endList = force_.end();
         //delete each point in the list
         for(list<Vector2D_F*>::iterator iter = force_.begin(); iter!=endList; iter++)
                 delete (*iter);
         //and for good measure just clear the list
         force_.clear();
         delete contourSubject2Force_;
 }
ContourForce::ContourForce (const ContourForce & theObj) private
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 42 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :   DrawableObject2D(),
                         contourSubject2Force_(NULL),
                         force_(list<Vector2D_F*>()),
                         renderContour_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "ContourForce copy constructor not implemented");
 }
Member Function Documentation
void ContourForce::addForce (ContourForce * cForce2)
Adds the force vector (element by element) to the class's force vector.
Parameters
cForce2 The force which will be added to the class's force vector
Definition at line 159 of file ContourForce.cpp.
References contourSubject2Force_, FAIL_CONDITION, force_, getContour(), getForce(), uriVL::Contour_F::getNbPoints(), and uriVL::kNullParameterError.
Referenced by uriVL::ActiveContourDetector_balloon::oneStep_().
{
         int force1ContourPts = contourSubject2Force_->getNbPoints();
         int force2ContourPts = (cForce2->getContour())->getNbPoints();
         // double check and make sure they both have the same amount of pts
         // before you add force vectors
         FAIL_CONDITION( force1ContourPts != force2ContourPts,
                     kNullParameterError,
                     "Adding two forces which are not the same size");
         if(force1ContourPts == force2ContourPts){
                 const list<Vector2D_F*> *force2 = cForce2->getForce();
                 //list<ImagePoint_F*> force2 = cForce2->force_;
                 list<Vector2D_F*>::const_iterator iterF2 = (*force2).begin();
                 for(list<Vector2D_F*>::const_iterator iterF1 = force_.begin(); iterF1 != force_.end(); iterF1++, iterF2++){
                         (*iterF1)->setCoordinates((*iterF1)->getXF() + (*iterF2)->getXF(),
                                                                           (*iterF1)->getYF() + (*iterF2)->getYF());
                 }
         }
 }
bool ContourForce::applyForceToContour (void)
Adds the force vector to contourforce's mapped contour.
Returns
true or false based on whether contour has converged
Definition at line 191 of file ContourForce.cpp.
References contourSubject2Force_, force_, uriVL::Contour_F::getNbPoints(), uriVL::Contour_F::getPoints(), and uriVL::Contour::pointsHaveMoved().
Referenced by uriVL::ActiveContourDetector_balloon::oneStep_().
{
         float   avgDistance = 0.f,
                         maxDisp = 0.f,
                         minDisp = 100.f,
                         stoppingThreshold = .80f,
                         maxDispThreshold = 2.f;
         int numPts = contourSubject2Force_->getNbPoints();
         bool convergence = false;
         const list<ImagePoint_F*> *contourList = contourSubject2Force_->getPoints();
         list<Vector2D_F*>::iterator iterF = force_.begin();
         for(list<ImagePoint_F*>::const_iterator iter = contourList->begin(); iter != contourList->end(); iterF++, iter++)
         {
                 float distancePtMoved = 0.f;
                 distancePtMoved = sqrtf((*iterF)->getX()*(*iterF)->getX() + (*iterF)->getY()*(*iterF)->getY()) ;
                 avgDistance += distancePtMoved;
                 if(distancePtMoved > maxDisp)
                 {
                         maxDisp = distancePtMoved;
                 }
                 if(distancePtMoved < minDisp)
                 {
                         minDisp = distancePtMoved;
                 }
                 (*iter)->translate((*iterF)->getX(), (*iterF)->getY());
         }
         avgDistance /= numPts;
         // bottoms out at around .82f
         if((avgDistance < stoppingThreshold) && (maxDisp < maxDispThreshold)){
                 convergence = true;
         }
         contourSubject2Force_->pointsHaveMoved();
         return convergence;
 }
void ContourForce::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Implements uriVL::DrawableObject2D.
Definition at line 400 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void ContourForce::computeBoundingRect_ (ImageRect & rect) const private virtual
Calculates the object's bounding rect.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 372 of file ContourForce.cpp.
References contourSubject2Force_, uriVL::DrawableObject2D::getBoundRect(), and uriVL::ImageRect::setRect().
 {
         rect.setRect(contourSubject2Force_->getBoundRect());
 }
void ContourForce::computeCenterOfMass_ (ImagePoint_F & cent) const private virtual
Computes the object's center of mass by calculating the average point.
Parameters
cent the center of mass point to update
Implements uriVL::DrawableObject2D.
Definition at line 363 of file ContourForce.cpp.
References contourSubject2Force_, uriVL::DrawableObject2D::getCenterOfMass(), and uriVL::ImagePoint_F::setCoordinates().
{
         cent.setCoordinates(contourSubject2Force_->getCenterOfMass());
 }
void ContourForce::computeCentroid_ (ImagePoint_F & cent) const private virtual
Computes the contour's centroid.
Parameters
cent the centroid point to update
Implements uriVL::DrawableObject2D.
Definition at line 358 of file ContourForce.cpp.
References contourSubject2Force_, uriVL::DrawableObject2D::getCentroid(), and uriVL::ImagePoint_F::setCoordinates().
{
         cent.setCoordinates(contourSubject2Force_->getCentroid());
 }
void ContourForce::computeValidRect_ (ImageRect & rect) const private virtual
Calculates the object's valid box.
Parameters
rect the bounding box to update
Implements uriVL::DrawableObject2D.
Definition at line 377 of file ContourForce.cpp.
References contourSubject2Force_, uriVL::DrawableObject2D::getBoundRect(), and uriVL::ImageRect::setRect().
 {
         //      the valid rect is the same as the bounding rect.  If the bounding rect
         //      is up to date, use its dimensions, else recompute it first
         rect.setRect(contourSubject2Force_->getBoundRect());
 }
const ImageRect * ContourForce::getBoundRect (void) const virtual
Returns the contour's bounding rectangle.
Returns a pointer to the contour's bounding rectangle.
Reminder: the ImageRect class uses the pixel-as-rectangle convention.
Returns
pointer to the contour's bounding rectangle
See also
validRect_
boundRect_
getValidRect
Reimplemented from uriVL::DrawableObject2D.
Definition at line 83 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::getBoundRect().
 {
     return contourSubject2Force_->getBoundRect();
 }
const Contour_F * ContourForce::getContour (void) const
Returns a read-only pointer to the contour force's geometric contour (list of points)
Returns
a read-only pointer to the contour force's geometric contour
Definition at line 105 of file ContourForce.cpp.
References contourSubject2Force_.
Referenced by addForce(), and uriVL::ActiveContourDetector::calculateInternalForce_().
 {
     return contourSubject2Force_;
 }
const list< Vector2D_F * > * ContourForce::getForce (void) const
Returns a writable pointer to the contour force's geometric contour (list of points)
Returns
a writable pointer to the contour force's geometric contourReturns the X and Y component vector of the force
force_
Definition at line 95 of file ContourForce.cpp.
References force_.
Referenced by addForce(), uriVL::ActiveContourDetector_balloon::calculateEdgeForce_(), uriVL::ActiveContourDetector::calculateInternalForce_(), and uriVL::ActiveContourDetector_balloon::calculateShrinkForce_().
 {
     return &force_;
 }
list< Vector2D_F * > * ContourForce::getForce (ReadWriteStatus rw)
Returns a writable pointer to the X and Y component vector of the force.
Returns
force_
Definition at line 100 of file ContourForce.cpp.
References force_.
 {
     return &force_;
 }
const ImageRect * ContourForce::getValidRect (void) const virtual
Returns the contour's valid data rectangle.
Returns a pointer to the contour's valid data rectangle.
Reminder: the ImageRect class uses the pixel-as-rectangle convention.
Returns
pointer to the contour's valid data rectangle
See also
validRect_
boundRect_
getBoundRect
Reimplemented from uriVL::DrawableObject2D.
Definition at line 88 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::getValidRect().
 {
     return contourSubject2Force_->getValidRect();
 }
void ContourForce::insertIntoForceVector (int pointIndex, float valueX, float valueY)
Creates a new element in the force vector and assigns it to the values.
Parameters
pointNumber The position that the new vector will have (other elements will be pushed up or down accordingly)
valueX The value which will be assigned to forceX[pointNumber]
valueY The value which will be assigned to forceY[pointNumber]
Definition at line 148 of file ContourForce.cpp.
References force_.
Referenced by uriVL::ActiveContourDetector_balloon::searchAndInsertPoints_().
 {
         Vector2D_F *newPointForce = new Vector2D_F(valueX, valueY);
         list<Vector2D_F*>::iterator iterF = force_.begin();
         for(int i = 0; i < pointIndex; i++){
                 iterF++;
         }
         force_.insert(iterF, newPointForce);
 }
void ContourForce::mapToContour (Contour_F * contourIn)
Assigns a contour to which the force is currently applied to.
Parameters
contourIn A reference to the contour.
Definition at line 123 of file ContourForce.cpp.
References contourSubject2Force_, force_, and uriVL::Contour_F::getNbPoints().
Referenced by uriVL::ActiveContourDetector::ActiveContourDetector(), uriVL::ActiveContourDetector_balloon::findContour_(), and uriVL::ActiveContourDetector_balloon::setImageProperties().
{
         contourSubject2Force_ = contourIn;
         int   numPts = contourIn->getNbPoints();
         // basically if there was a force prior, delete em
         if(force_.size() > 0)
         {
                 list<Vector2D_F*>::const_iterator endList = force_.end();
                 //delete each point in the list
                 for(list<Vector2D_F*>::const_iterator   iter = force_.begin(); iter!=endList; iter++)
                         delete (*iter);
                 //and for good measure just clear the list
                 force_.clear();
         }
         Vector2D_F* myForce;
         for(int i = 0;i < numPts; i++)
         {
                 myForce = new Vector2D_F(0.f, 0.f);
                 force_.push_back(myForce);
         }
 }
const ContourForce & ContourForce::operator= (const ContourForce & theObj) private
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 65 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "ContourForce copy operator not implemented");
         return *this;
 }
void ContourForce::render_ (int scaledLeft, int scaledTop, int scaledRight, int scaledBottom, float theZ, bool shifted, const ImagePoint * origin) const private virtual
Renders the contour at the depth and location specified.
A drawable object can be rendered with its valid data rectangle's upper-left corner in the upper-left corner of the rendering window (shifted=false and origin=NULL), or using the absolute coordinates of its valid data rectangle's upper-left corner (shited=true and origin=NULL), or by setting its upper-left corner at the location specified (origin != NULL).
This function must be overridden by child classes.
Parameters
scaledLeft x coordinate of the object's upper-left corner when rendered scaled
scaledTop y coordinate of the object's upper-left corner when rendered scaled
scaledRight x coordinate of the object's lower-right corner when rendered scaled
scaledBottom y coordinate of the object's lower-right corner when rendered scaled
theZ Depth at which this object is to be rendered.
shifted true if the object should be rendered at its true ImageRect position, false if its upper left corner should be at 0,0.
origin location of the object's upper-left corner in the rendering
Implements uriVL::DrawableObject2D.
Definition at line 244 of file ContourForce.cpp.
References contourSubject2Force_, force_, uriVL::Contour_F::getPoints(), uriVL::DrawableObject2D::getRenderingScaleX(), uriVL::DrawableObject2D::getRenderingScaleY(), needleColor_, uriVL::DrawableObject2D::render(), and uriVL::VECTORSCALE.
 {
     //--------------------------------------------------------------
     //  Part 1: render the contour
     //--------------------------------------------------------------
     contourSubject2Force_->render(theZ, shifted, origin);
     //--------------------------------------------------------------
     //  Part 2: render the contour force's needles
     //--------------------------------------------------------------
     glLoadIdentity();
     //
         glPushMatrix();
         glLoadIdentity();
         glTranslatef(scaledLeft, scaledTop, theZ);
         glScalef(getRenderingScaleX(), -getRenderingScaleY(), 1.f);
     const list<ImagePoint_F*> *contourList = contourSubject2Force_->getPoints();
     list<ImagePoint_F*>::const_iterator endList = contourList->end();
         list<Vector2D_F*>::const_iterator iterF = force_.begin();
     for(list<ImagePoint_F*>::const_iterator iter = contourList->begin(); iter != endList; iterF++, iter++)
     {
         glPushMatrix();
         glTranslatef((*iter)->getX(), (*iter)->getY(), 0.f);
         glColor3f(needleColor_[0], needleColor_[1], needleColor_[2]);
         glBegin(GL_LINES);
         glVertex2f(0, 0);
         glVertex2f(((*iterF)->getX() * VECTORSCALE),
                    ((*iterF)->getY() * VECTORSCALE));
         glEnd();
         glPopMatrix();  //      restore the state that had been pushed
     }
     glPopMatrix();
 }
void ContourForce::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Implements uriVL::DrawableObject2D.
Definition at line 392 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
void ContourForce::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Attempts (and fails) to a new bounding rectangle for the contour force.
This function must be implemented since a contour force is a DrawableObject2D. However, it makes no sense forcing a change of bounding rectangle for a contour force (I may rethink this later as a form of clipping, though).
Parameters
x horizontal coordinate of upper left corner
y vertical coordinate of upper left corner
theWidth desired width of the contour
theHeight desired height of the contour
Implements uriVL::DrawableObject2D.
Definition at line 407 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void ContourForce::setColor (float red, float green, float blue) virtual
Assigns a rendering color to the contour force's contour (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Reimplemented from uriVL::DrawableObject2D.
Definition at line 289 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::setColor().
 {
     contourSubject2Force_->setColor(red, green, blue);
 }
void ContourForce::setColor (unsigned char red, unsigned char green, unsigned char blue) virtual
Assigns a rendering color to the contour force's contour (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Reimplemented from uriVL::DrawableObject2D.
Definition at line 300 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::setColor().
 {
     contourSubject2Force_->setColor(red, green, blue);
 }
void ContourForce::setColor (const float theColor[]) virtual
Assigns a rendering color to the contour force's contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Reimplemented from uriVL::DrawableObject2D.
Definition at line 294 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::setColor().
 {
     contourSubject2Force_->setColor(theColor);
 }
void ContourForce::setColor (const unsigned char theColor[]) virtual
Assigns a rendering color to the contour force's contour (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Reimplemented from uriVL::DrawableObject2D.
Definition at line 305 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::DrawableObject2D::setColor().
 {
     contourSubject2Force_->setColor(theColor);
 }
void ContourForce::setDrawPoints (bool drawPointCircle)
Sets whether to draw a point at each vertex of the contour.
Parameters
drawPointCircle
Definition at line 343 of file ContourForce.cpp.
References contourSubject2Force_, and uriVL::Contour::setDrawPoints().
 {
         contourSubject2Force_->setDrawPoints(drawPointCircle);
 }
void ContourForce::setForcesToZero (void)
Sets the force's values to zero.
Definition at line 183 of file ContourForce.cpp.
References force_.
Referenced by uriVL::ActiveContourDetector_balloon::oneStep_().
 {
         for(list<Vector2D_F*>::iterator iterF1 = force_.begin(); iterF1 != force_.end(); iterF1++)
         {
             (*iterF1)->setCoordinates(0.f, 0.f);
         }
 }
void ContourForce::setNeedleColor (float red, float green, float blue)
Assigns a rendering color to the contour force's needles (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 311 of file ContourForce.cpp.
References needleColor_.
Referenced by uriVL::ActiveContourDetector::ActiveContourDetector(), and uriVL::ActiveContourDetector_balloon::ActiveContourDetector_balloon().
 {
     needleColor_[0] = red;
     needleColor_[1] = green;
     needleColor_[2] = blue;
     needleColor_[3] = 1.f;
 }
void ContourForce::setNeedleColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the contour force's needles (alpha is set to 1)
Parameters
red red component of the rendering color
green green component of the rendering color
blue blue component of the rendering color
Definition at line 327 of file ContourForce.cpp.
References needleColor_.
 {
     needleColor_[0] = red/255.f;
     needleColor_[1] = green/255.f;
     needleColor_[2] = blue/255.f;
     needleColor_[3] = 1.f;
 }
void ContourForce::setNeedleColor (const float theColor[])
Assigns a rendering color to the contour force's needles (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 319 of file ContourForce.cpp.
References needleColor_.
 {
     needleColor_[0] = theColor[0];
     needleColor_[1] = theColor[1];
     needleColor_[2] = theColor[2];
     needleColor_[3] = 1.f;
 }
void ContourForce::setNeedleColor (const unsigned char theColor[])
Assigns a rendering color to the contour force's needles (alpha is set to 1)
Parameters
theColor rgb components of the rendering color
Definition at line 335 of file ContourForce.cpp.
References needleColor_.
 {
     needleColor_[0] = theColor[0]/255.f;
     needleColor_[1] = theColor[1]/255.f;
     needleColor_[2] = theColor[2]/255.f;
     needleColor_[3] = 1.f;
 }
void ContourForce::setRenderContour (bool isRendered)
Indicates whether the contour should be rendered (when false, only the needles are rendered).
Used when several ContourForce objects coincide on the same contour and only one needs to be rendered
Parameters
isRendered true if the contour should be rendered
Definition at line 284 of file ContourForce.cpp.
References renderContour_.
Referenced by uriVL::ActiveContourDetector::ActiveContourDetector().
 {
         renderContour_ = isRendered;
 }
void ContourForce::setValidRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new valid data rectangle for the contour force.
Not sure yet what this function should do
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Implements uriVL::DrawableObject2D.
Definition at line 416 of file ContourForce.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
Member Data Documentation
Contour_F* uriVL::ContourForce::contourSubject2Force_ private
Stores a pointer to the contour which the force is mapped to.
Definition at line 220 of file ContourForce.h.
Referenced by addForce(), applyForceToContour(), computeBoundingRect_(), computeCenterOfMass_(), computeCentroid_(), computeValidRect_(), getBoundRect(), getContour(), getValidRect(), mapToContour(), render_(), setColor(), setDrawPoints(), and ~ContourForce().
std::list<Vector2D_F*> uriVL::ContourForce::force_ private
Stores the force which can be applied to counter points x and y coordinates.
Definition at line 224 of file ContourForce.h.
Referenced by addForce(), applyForceToContour(), getForce(), insertIntoForceVector(), mapToContour(), render_(), setForcesToZero(), and ~ContourForce().
float uriVL::ContourForce::needleColor_[4] private
The rendering color for the force's "needles".
Definition at line 228 of file ContourForce.h.
Referenced by ContourForce(), render_(), and setNeedleColor().
bool uriVL::ContourForce::renderContour_ private
Should the contour be rendered.
Used when several ContourForce objects coincide on the same contour and only one needs to be rendered
Definition at line 233 of file ContourForce.h.
Referenced by setRenderContour().
The documentation for this class was generated from the following files:
ContourForce.h
ContourForce.cpp