URIVisionLibrary: uriVL::RasterImage_RGBa Class Reference
uriVL::RasterImage_RGBa Class Reference
Base 32-bit rgba color image class.
#include <RasterImage_RGBa.h>
Public Member Functions
RasterImage_RGBa (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
RasterImage_RGBa (const ImageRect *theRect)
Allocates a 32-bit RGBa color raster image at the specified dimensions.
RasterImage_RGBa (int nbRows, int nbCols, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const ImageRect *theRect, const unsigned char *theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (GraphWorld *gworld, bool keepThisGraphWorld=false)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img)
Initializes an rgba raster image at the specified dimensions and values.
RasterImage_RGBa (const RasterImage *img, const ImageRect *theRect)
Initializes an rgba raster image at the specified dimensions and values.
virtual ~RasterImage_RGBa (void)
Class destructor.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
virtual const unsigned char * getRGBa (void) const
Returns the 32-bit rgba base raster as a read-only 1D array.
virtual unsigned char * getRGBa (ReadWriteStatus rw)
Returns the 32-bit rgba base raster as a read-write 1D array.
virtual const unsigned char *const * getRGBa2D (void) const
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
virtual unsigned char *const * getRGBa2D (ReadWriteStatus rw)
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRGBa2D (void) const
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRGBa2D (ReadWriteStatus rw)
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, const float convWeight[])
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Copies a 1D RGBa32 raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D RGBa32 raster into a 1D 16-bit aRGB16 raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, bool *localRGBa)
Allocates a read-only RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static const RasterImage_RGBa * localRasterRGBa (const RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
static RasterImage_RGBa * localRasterRGBa (RasterImage *imgIn, const ImageRect *rect, bool *localRGBa)
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Protected Member Functions
RasterImage_RGBa (void)
Protected default constructor.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Private Member Functions
RasterImage_RGBa (RasterImage_RGBa &img)
Creates a new raster image based on the one received as parameter.
const RasterImage_RGBa & operator= (const RasterImage_RGBa &theImg)
Equal operator.
virtual void updateRaster_ (void) const
Forces an update of the base rgba raster if it is not the reference raster.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
Private Attributes
unsigned char ** rgba2D_
0-based 2D array mapped on the GraphWorld's 1D raster.
unsigned char ** shiftedRgba2D_
"shifted" 2D array (based on the image's rectangle bounds) mapped on the GraphWorld's 1D raster.
Friends
class _GraphWorld_gen
Detailed Description
Base 32-bit rgba color image class.
RasterImage_RGBa is the base class for all 32-bit rgba color image types. This class is built around a 32-bit color QuickTime GWorld buffer, which is itself wrapped into a GraphWorld object.
Since 24-bit color support in QuickTime is weak (only works for the Windows platform, and should not even do so, according to specifications), developers are encouraged to use RasterImage_RGBa rather than RasterImage_RGBa as the base class for image classes implementing other color spaces (HSL, HSV, Lab, etc.)
RasterImage_RGBa implements or overrides a number of methods of the base RasterImageClass, and in particular the convertTo<Gray,RGB,RGBa> methods.
Important: All subclasses of RasterImage_RGBa must override the following methods:
getRGB, which resturns the 1D base raster (8-bit gray level)
getRGB2D, which resturns the 2D base raster (8-bit gray level). These methods must be overloaded to force a conversion from the reference type to the base raster type (and possibly an allocation of the base raster) if the base raster is not the reference.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 51 of file RasterImage_RGBa.h.
Constructor & Destructor Documentation
RasterImage_RGBa::RasterImage_RGBa (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes this raster to zero values (black).
Parameters
nbRows number of rows of the rgba raster image
nbCols number of columns of the rgba raster image
Definition at line 44 of file RasterImage_RGBa.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::kDense, uriVL::RasterImage::referenceHasChanged_, uriVL::DrawableObject2D::setDrawableInformationType(), and uriVL::RasterImage::setGraphWorldAsReference_().
                 :       RasterImage(nbRows, nbCols),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
         try {
                 allocateGraphWorld_(nbRows, nbCols);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     //
         setDrawableInformationType(kDense);
     setGraphWorldAsReference_();
     referenceHasChanged_ = false;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (const ImageRect * theRect)
Allocates a 32-bit RGBa color raster image at the specified dimensions.
Allocates a 32-bit RGBa color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 115 of file RasterImage_RGBa.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::RasterImage::referenceHasChanged_, and uriVL::DrawableObject2D::setDrawableInformationType().
                 :       RasterImage(theRect),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
         try {
                 allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     allocateRaster2D_(theRect->getHeight(), theRect->getWidth());
     allocateShiftedRaster2D_(theRect->getHeight(), theRect->getWidth(), theRect->getTop(), theRect->getLeft());
         //
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = false;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (int nbRows, int nbCols, const unsigned char * theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes it with the contents of the raster received as parameter.
Parameters
nbRows number of rows of the rgba raster image
nbCols number of columns of the rgba raster image
theRGBa values to which the image should be initialized
Definition at line 71 of file RasterImage_RGBa.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::kMemoryCopyError, uriVL::RasterImage::referenceHasChanged_, rgba2D_, uriVL::DrawableObject2D::setDrawableInformationType(), and uriVL::DrawableObject2D::setValidRect().
                 :       RasterImage(nbRows, nbCols),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
         try {
                 allocateGraphWorld_(nbRows, nbCols);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
         try {
                 const unsigned char   *source = theRGBa;
                 for (int i=0; i<nbRows; i++)
                 {
                         memcpy(rgba2D_[i], source, static_cast<unsigned long>(4L*nbCols));
                         source += 4*nbCols;
                 }
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "Data copy failure in RasterImage_RGBa constructor");
         }
         setValidRect(0, 0, nbCols, nbRows);
     //
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (const ImageRect * theRect, const unsigned char * theRGBa)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 32-bit RGBa color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
theRGBa values to which the image should be initialized
Definition at line 142 of file RasterImage_RGBa.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::kMemoryCopyError, uriVL::RasterImage::referenceHasChanged_, rgba2D_, and uriVL::DrawableObject2D::setDrawableInformationType().
                 :       RasterImage(theRect),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
         try {
                 allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     const int   iLow = theRect->getTop(),
                         jLow = theRect->getLeft(),
                                 nbRows = theRect->getHeight(),
                                 nbCols = theRect->getWidth();
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, iLow, jLow);
         try {
                 const unsigned char   *source = theRGBa;
                 for (int i=0; i<nbRows; i++)
                 {
                         memcpy(rgba2D_[i], source, static_cast<unsigned long>(4L*nbCols));
                         source += 4*nbCols;
                 }
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "Data copy failure in RasterImage_RGBa constructor");
         }
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (GraphWorld * gworld, bool keepThisGraphWorld = false)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter.
Parameters
gworld the GraphWorld to use for dimensions and values
keepThisGraphWorld if true, then this new image raster object will simply store a reference to a pre-allocated GWorld instead of allocating its own (beware!)
Definition at line 189 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage(theGworld, keepThisGraphWorld),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "RasterImage_RGBa Constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (const RasterImage * img)
Initializes an rgba raster image at the specified dimensions and values.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
Definition at line 205 of file RasterImage_RGBa.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::gworldIsReference_, uriVL::kNullRasterImageError, and uriVL::RasterImage::referenceHasChanged_.
                 :       RasterImage( ),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGBa constructor");
         try {
                 img->copyInto(this, img->getValidRect());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     gworldIsReference_ = true;
     referenceHasChanged_ = false;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::RasterImage_RGBa (const RasterImage * img, const ImageRect * theRect)
Initializes an rgba raster image at the specified dimensions and values.
Allocates a 32-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 232 of file RasterImage_RGBa.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::RasterImage::gworldIsReference_, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::RasterImage::referenceHasChanged_.
                 :       RasterImage( ),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGBa constructor");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage_RGBa constructor");
         try {
                 img->copyInto(this, theRect);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGBa constructor");
                 throw e;
         }
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
RasterImage_RGBa::~RasterImage_RGBa (void) virtual
Class destructor.
Standard destructor (nothing fancy).
Definition at line 278 of file RasterImage_RGBa.cpp.
References deleteRaster2D_(), deleteShiftedRaster2D_(), and uriVL::DrawableObject2D::getTop().
 {
     deleteShiftedRaster2D_(getTop());
     deleteRaster2D_();
 }
RasterImage_RGBa::RasterImage_RGBa (void) protected
Protected default constructor.
Called by subclasses that don't need to allocate the base raster.
Definition at line 35 of file RasterImage_RGBa.cpp.
Referenced by localRasterRGBa().
                 :       RasterImage( ),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
 }
RasterImage_RGBa::RasterImage_RGBa (RasterImage_RGBa & img) private
Creates a new raster image based on the one received as parameter.
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the pervious one (constness).
Parameters
img pointer to the RasterImage_RGBa object to copy
Definition at line 263 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       RasterImage( ),
                         //
                         rgba2D_(NULL),
                         shiftedRgba2D_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_RGBa copy constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGBa constructor");
         throw e;
 }
Member Function Documentation
void RasterImage_RGBa::allocateGraphWorld_ (int nbRows, int nbCols) protected virtual
Alocates the GraphWorld for this object at the set dimensions.
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Implements uriVL::RasterImage.
Definition at line 884 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, and uriVL::kGWorldAllocationError.
Referenced by uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), RasterImage_RGBa(), setBoundRect_(), uriVL::RasterImage_HSV::updateRaster_(), and uriVL::RasterImage_RGBa_F::updateRaster_().
 {
         gworld_ = new GraphWorld(32, nbRows, nbCols);
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldAllocationError,
                     "GraphWorld allocation failed in RasterImage_RGBa::allocateGraphWorld_");
 }
void RasterImage_RGBa::allocateRaster2D_ (int nbRows, int nbCols) protected virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 893 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getBytesPerRow(), uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, uriVL::kRasterAllocationFailure, and rgba2D_.
Referenced by uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), RasterImage_RGBa(), and setBoundRect_().
 {
     unsigned char* rgba = gworld_->getRaster();
     const int     rowBytes = gworld_->getBytesPerRow();
     if (rgba2D_ != NULL)
         delete []rgba2D_;
     rgba2D_ = new unsigned char*[nbRows];
     FAIL_CONDITION(rgba2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate rgba2D_ array");
     rgba2D_[0] = rgba;
     for (int i=1; i<nbRows; i++)
         rgba2D_[i] = rgba2D_[i-1] + rowBytes;
 }
void RasterImage_RGBa::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) protected virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 921 of file RasterImage_RGBa.cpp.
References deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::RasterImage::getBytesPerRow(), uriVL::DrawableObject2D::getLeft(), getRGBa(), uriVL::DrawableObject2D::getTop(), uriVL::kRasterAllocationFailure, uriVL::R_W_ACCESS, and shiftedRgba2D_.
Referenced by uriVL::RasterImage_HSV::forceConversionToSaturatedRGBa(), RasterImage_RGBa(), and setBoundRect_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
     {
         const int   iHigh = iLow + nbRows - 1,
                     bytesPerRow = getBytesPerRow();
         deleteShiftedRaster2D_(iLow);
         shiftedRgba2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedRgba2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D RGBa color  raster allocation failed");
         shiftedRgba2D_ -= iLow;
         //
         shiftedRgba2D_[iLow] = getRGBa(R_W_ACCESS) - 4*jLow;
         for (int i = iLow; i < iHigh; i++)
             shiftedRgba2D_[i+1] = shiftedRgba2D_[i] + bytesPerRow;
     }
     else
         shiftedRgba2D_ = NULL;
 }
void RasterImage_RGBa::convertToARGB16 (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D RGBa32 raster into a 1D 16-bit aRGB16 raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 814 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
void RasterImage_RGBa::convertToGray (const unsigned char * theSource, unsigned char * theDestination, long nbPixels, ConversionToGrayMode myGrayConv = kAverageConversion) static
Converts a 1D RGBa32 raster into a 1D gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myGrayConv the gray conversion mode desired
Definition at line 631 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::defaultConvWeight_, FAIL_CONDITION, uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kRasterImageError, uriVL::kWeightedAverageConversion, and MAX.
Referenced by uriVL::_GraphWorld_gen::copyRGBa32Into_(), and writeInto_().
 {
     const unsigned char   *source = theSource;
     unsigned char   *dest = theDestination;
     int     sum;
     float   sumF;
     //  how do we convert from rgb to gray?
     switch (myGrayConv)
     {
         case kMaxFieldConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 //  optimization "in the small" left for a more clever programmer
                 unsigned char   red = *(source++),
                                 green = *(source++),
                                 blue = *(source++);
                 *(dest++) = MAX(red, MAX(green, blue));
                 source++;
             }
             break;
         case kAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = *(source++);
                 sum += *(source++);
                 sum += *(source++);
                 *(dest++) = static_cast<unsigned char>(sum/3);
                 source++;
             }
             break;
         case kWeightedAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sumF = defaultConvWeight_[0] ** (source++);
                 sumF += defaultConvWeight_[1] ** (source++);
                 sumF += defaultConvWeight_[2] ** (source++);
                 *(dest++) = static_cast<unsigned char>(sumF);
                 source++;
             }
             break;
         default:
             FAIL_CONDITION( true, kRasterImageError,
                             "unknown conversion to gray mode encountered");
             break;
     }
 }
void RasterImage_RGBa::convertToGray (const unsigned char * theSource, unsigned char * theDestination, long nbPixels, const float convWeight[]) static
Converts a 1D RGBa32 raster into a 1D gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
Definition at line 689 of file RasterImage_RGBa.cpp.
 {
     const unsigned char   *source = theSource;
     unsigned char   *dest = theDestination;
     float           sumF;
     dest = theDestination;
     for (long j=0; j<nbPixels; j++)
     {
         sumF = convWeight[0] ** (source++);
         sumF += convWeight[1] ** (source++);
         sumF += convWeight[2] ** (source++);
         *(dest++) = static_cast<unsigned char>(sumF);
         source++;
     }
 }
void RasterImage_RGBa::convertToGray (const unsigned char * theSource, float * theDestination, long nbPixels, ConversionToGrayMode myGrayConv = kAverageConversion) static
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myGrayConv the gray conversion mode desired
Definition at line 711 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::defaultConvWeight_, FAIL_CONDITION, uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kRasterImageError, uriVL::kWeightedAverageConversion, and MAX.
 {
     const unsigned char   *source = theSource;
     float           *dest = theDestination;
     float           sum;
     const float         div3 = 1.f/3.f;
     //  how do we convert from rgb to gray?
     switch (myGrayConv)
     {
         case kMaxFieldConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 //  optimization "in the small" left for a more clever programmer
                 float   red = *(source++),
                         green = *(source++),
                         blue = *(source++);
                 *(dest++) = MAX(red, MAX(green, blue));
                 source++;
             }
             break;
         case kAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = *(source++);
                 sum += *(source++);
                 sum += *(source++);
                 *(dest++) = sum*div3;
                 source++;
             }
             break;
         case kWeightedAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = defaultConvWeight_[0] ** (source++);
                 sum += defaultConvWeight_[1] ** (source++);
                 sum += defaultConvWeight_[2] ** (source++);
                 *(dest++) = sum;
                 source++;
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "unknown conversion to gray mode encountered");
             break;
     }
 }
void RasterImage_RGBa::convertToGray (const unsigned char * theSource, float * theDestination, long nbPixels, const float convWeight[]) static
Converts a 1D RGBa32 raster into a 1D float gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
Definition at line 770 of file RasterImage_RGBa.cpp.
 {
     const unsigned char   *source = theSource;
     float           *dest = theDestination;
     float           sum;
     for (long j=0; j<nbPixels; j++)
     {
         sum = convWeight[0] ** (source++);
         sum += convWeight[1] ** (source++);
         sum += convWeight[2] ** (source++);
         *(dest++) = sum;
         source++;
     }
 }
void RasterImage_RGBa::convertToRGB (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D RGBa32 raster into a 1D 24-bit rgb raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 798 of file RasterImage_RGBa.cpp.
Referenced by uriVL::_GraphWorld_gen::copyRGBa32Into_().
 {
     unsigned char   *dest = theDestination;
     const unsigned char* source = theSource;
     for (long j=0; j<nbPixels; j++)
     {
         *(dest++) = *(source++);        //  red
         *(dest++) = *(source++);        //  green
         *(dest++) = *(source++);        //  blue
         source++;
     }
 }
void RasterImage_RGBa::convertToRGBa (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Copies a 1D RGBa32 raster into a 1D 32-bit rgba raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 790 of file RasterImage_RGBa.cpp.
 {
     memcpy(theDestination, theSource, static_cast<unsigned long>(4L*nbPixels));
 }
void RasterImage_RGBa::copyInto (RasterImage * imgOut) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 428 of file RasterImage_RGBa.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by copyInto(), uriVL::RasterImage_RGBa_F::copyInto(), and myIdle().
 {
     copyInto(imgOut, getValidRect(), NULL);
 }
void RasterImage_RGBa::copyInto (RasterImage * imgOut, const ImageRect * theRect) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab).
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 433 of file RasterImage_RGBa.cpp.
References copyInto().
 {
     copyInto(imgOut, theRect, NULL);
 }
void RasterImage_RGBa::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 438 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::copyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kDense, uriVL::kUriBaseError, uriVL::DrawableObject2D::setDrawableInformationType(), and writeInto_().
 {
     //  All the rectangle testing and resizing is done in the parent class' function
     RasterImage::copyInto_(imgOut, theRect, origin);
     //  We only copy from the validRect_, so we need to calculate its intersection
     //  with theRect.
     ImageRect* copyRect = ImageRect::intersection(getValidRect(), theRect);
     FAIL_CONDITION( copyRect == NULL,
                     kUriBaseError,
                     "the copy rectangle specified is not within valid data");
     //  For the time being, we only handle regular dense rasters
     imgOut->setDrawableInformationType(kDense);
     writeInto_(imgOut, copyRect, origin);
     delete copyRect;
 }
void RasterImage_RGBa::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 912 of file RasterImage_RGBa.cpp.
References rgba2D_.
Referenced by setBoundRect_(), and ~RasterImage_RGBa().
 {
     if (rgba2D_ != NULL)
     {
         delete []rgba2D_;
         rgba2D_ = NULL;
     }
 }
void RasterImage_RGBa::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 949 of file RasterImage_RGBa.cpp.
References shiftedRgba2D_.
Referenced by allocateShiftedRaster2D_(), setBoundRect_(), and ~RasterImage_RGBa().
 {
     if (shiftedRgba2D_ != NULL)
     {
         shiftedRgba2D_ += iLow;
         delete []shiftedRgba2D_;
         shiftedRgba2D_ = NULL;
     }
 }
BaseRasterType RasterImage_RGBa::getBaseRasterType (void) const virtual
Returns the image's base raster type.
Returns the following value:
- kRGBa32Raster, since this image is based on the 32-bit rgba color format
Returns
the image's base raster type
Implements uriVL::RasterImage.
Definition at line 291 of file RasterImage_RGBa.cpp.
References uriVL::kRGBa32Raster.
 {
     return kRGBa32Raster;
 }
const unsigned char * RasterImage_RGBa::getRGBa (void) const virtual
Returns the 32-bit rgba base raster as a read-only 1D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
1D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 296 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, and uriVL::kGWorldIsNullError.
Referenced by allocateShiftedRaster2D_().
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa()");
     return gworld_->getRaster();
 }
unsigned char * RasterImage_RGBa::getRGBa (ReadWriteStatus rw) virtual
Returns the 32-bit rgba base raster as a read-write 1D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 306 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, and uriVL::RasterImage::referenceHasChanged_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return gworld_->getRaster();
 }
const unsigned char *const * RasterImage_RGBa::getRGBa2D (void) const virtual
Returns the 0-based 32-bit rgba base raster as a read-only 2D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
2D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 322 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, uriVL::kGWorldIsNullError, and rgba2D_.
Referenced by uriVL::RasterImage_HSV24::convertFromRGBa_(), uriVL::PatternMatcher2D_partCorr::covariance_(), uriVL::RasterImage_RGBa_F::getRGBa2D(), uriVL::RasterImage_HSV::getRGBa2D(), uriVL::PatternMatcher2D_corr::patternCorrScale_(), uriVL::PatternMatcher2D_scaledDiff::patternCorrScale_(), uriVL::PatternMatcher2D_medianDiff::patternCorrScale_(), and uriVL::PatternMatcher2D_partCorr::patternCorrScale_().
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     return rgba2D_;
 }
unsigned char *const * RasterImage_RGBa::getRGBa2D (ReadWriteStatus rw) virtual
Returns the 0-based 32-bit rgba base raster as a read-write 2D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 331 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, uriVL::RasterImage::referenceHasChanged_, and rgba2D_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return rgba2D_;
 }
const unsigned char *const * RasterImage_RGBa::getShiftedRGBa2D (void) const virtual
Returns the shifted 32-bit rgba base raster as a read-only 2D array.
The shifted raster has index bounds defined by the image's rectangle. This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
shifted 2D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 346 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::gworld_, uriVL::kGWorldIsNullError, rgba2D_, and shiftedRgba2D_.
Referenced by uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::RasterImage_HSV::convertFromRGBa_(), uriVL::PatternMatcher2D_corr::covariance(), uriVL::PatternMatcher2D_medianDiff::covariance(), uriVL::PatternMatcher2D_scaledDiff::covariance(), uriVL::PatternMatcher2D_partCorr::covariance_(), uriVL::ImageArithmetics::difference_(), uriVL::RasterImage_RGBa_F::getShiftedRGBa2D(), uriVL::RasterImage_HSV::getShiftedRGBa2D(), uriVL::PatternMatcher2D_corr::match_(), uriVL::PatternMatcher2D_scaledDiff::match_(), uriVL::PatternMatcher2D_medianDiff::match_(), and writeInto_().
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return rgba2D_;
     else
         return shiftedRgba2D_;
 }
unsigned char *const * RasterImage_RGBa::getShiftedRGBa2D (ReadWriteStatus rw) virtual
Returns the shifted 32-bit rgba base raster as a read-write 2D array.
The shifted raster has index bounds defined by the image's rectangle. This method is virtual and should be overridden by all subclasses of RasterImage_RGBa. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Reimplemented in uriVL::RasterImage_HSV, and uriVL::RasterImage_RGBa_F.
Definition at line 362 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, uriVL::RasterImage::referenceHasChanged_, rgba2D_, and shiftedRgba2D_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return rgba2D_;
     else
         return shiftedRgba2D_;
 }
const RasterImage_RGBa * RasterImage_RGBa::localRasterRGBa (const RasterImage * imgIn, bool * localRGBa) static
Allocates a read-only RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
This function should be used as follows: bool localRGBa;
const RasterImage_RGBa *imgRGBa = RasterImage_RGBa::localRasterRGBa(imgIn, &localRGBa);
... lots of high-quality, efficient code ...
if (localRGBa)
delete imgRGBa;
Parameters
img the image of which to make a local 32-bit RGBa copy
localRGBa will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to read-only RGBa image
Definition at line 833 of file RasterImage_RGBa.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by uriVL::ColorMedianFilter_F::applyInto(), uriVL::ColorMedianFilter_I::applyInto(), uriVL::ColorImageGradient_Sobel::applyInto(), uriVL::ColorGaussianFilter_F::applyInto(), uriVL::ColorImageGradient_Gaussian_F::applyInto(), and localRasterRGBa().
 {
     return localRasterRGBa(imgIn, imgIn->getValidRect(), localRGBa);
 }
const RasterImage_RGBa * RasterImage_RGBa::localRasterRGBa (const RasterImage * imgIn, const ImageRect * rect, bool * localRGBa) static
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
This function should be used as follows: bool localRGBa;
const RasterImage_RGBa *imgRGBa = RasterImage_RGBa::localRasterRGBa(imgIn, &localRGBa);
... lots of high-quality, efficient code ...
if (localRGBa)
delete imgRGBa;
Parameters
img the image of which to make a local 32-bit RGBa copy
rect the rectangle over which we want a gray-level image
localRGBa will be true if a local raster was allocated, true if the image returned is just img itself
Returns
pointer to read-only RGBa image
Definition at line 839 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::kRGBa32Raster, and RasterImage_RGBa().
 {
     const RasterImage_RGBa* rgbaImg = NULL;
     //  if imgIn is alread a ReasterImage_RGBa --> then just use its rasters
     if (imgIn->getBaseRasterType() == kRGBa32Raster)
     {
         rgbaImg = static_cast<const RasterImage_RGBa*>(imgIn);
         *localRGBa = false;
     }
     //  if imgIn was not a RasterImage_RGBa, we need to create a local rgba
     //  image that is converted from imgIn
     else
     {
         rgbaImg = new RasterImage_RGBa(imgIn, rect);
         *localRGBa = true;
     }
     return rgbaImg;
 }
RasterImage_RGBa * RasterImage_RGBa::localRasterRGBa (RasterImage * imgIn, bool * localRGBa) static
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
This function should be used as follows: bool localRGBa;
RasterImage_RGBa *imgRGBa = RasterImage_RGBa::localRasterRGBa(imgIn, &localRGBa);
... lots of high-quality, efficient code ...
if (localRGBa)
delete imgRGBa;
Parameters
img the image of which to make a local 32-bit RGBa copy
localRGBa will be true if a local raster was allocated, true if the image returned is just img itself
Definition at line 861 of file RasterImage_RGBa.cpp.
References uriVL::DrawableObject2D::getValidRect(), and localRasterRGBa().
 {
     return const_cast<RasterImage_RGBa*>(localRasterRGBa(static_cast<const RasterImage* >(imgIn),
                                                                                  imgIn->getValidRect(), localRGBa));
 }
RasterImage_RGBa * RasterImage_RGBa::localRasterRGBa (RasterImage * imgIn, const ImageRect * rect, bool * localRGBa) static
Allocates an RGBa32 copy of the image received as parameter if that image is not already some form of RGBa raster.
This function should be used as follows: bool localRGBa;
RasterImage_RGBa *imgRGBa = RasterImage_RGBa::localRasterRGBa(imgIn, &localRGBa);
... lots of high-quality, efficient code ...
if (localRGBa)
delete imgRGBa;
Parameters
img the image of which to make a local 32-bit RGBa copy
rect the rectangle over which we want a gray-level image
localRGBa will be true if a local raster was allocated, true if the image returned is just img itself
Definition at line 868 of file RasterImage_RGBa.cpp.
References localRasterRGBa().
 {
     return const_cast<RasterImage_RGBa*>(localRasterRGBa(static_cast<const RasterImage* >(imgIn),
                                                                                  rect, localRGBa));
 }
const RasterImage_RGBa & RasterImage_RGBa::operator= (const RasterImage_RGBa & theImg) private
Equal operator.
Created so that gcc will stop complaining. This RasterImage_RGBa object will retain its own id.
Parameters
theImg reference to the RasterImage_RGBa object to copy
Definition at line 421 of file RasterImage_RGBa.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
{
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_RGBa copy operator not implemented");
         return *this;
 }
void RasterImage_RGBa::setBoundRect_ (int x, int y, int theWidth, int theHeight) protected virtual
Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function may be called or overridden by child classes that have their own raster (eg. RGBa_F, HSV, etc.)
Parameters
x horizontal coordinate of upper left corner
y vertical coordinate of upper left corner
theWidth desired width of the image
theHeight desired height of the image
Implements uriVL::DrawableObject2D.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 966 of file RasterImage_RGBa.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::gworld_, uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked_, and shiftedRgba2D_.
Referenced by uriVL::RasterImage_RGBa_F::setBoundRect_().
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  if width and height have not changed, then the operation is just a translation.
     //  The ImageRect member has been updated in DrawableObject2D::setBoundRect, so we only need
         //      to update the "shifted" array (no re-allocation needed)
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             //  Since the rasters have the same dimensions, there is no need
             //  to delete and reallocate the shifted rasters.  Just apply a
             //  relative shift to them
             const int   iLow  = getTop(),
                                                 iHigh = getBottom(),
                                                 jLow = getLeft(),
                                                 rowShift = y - iLow,
                                                 colShift = 4*(x - jLow);
                         if(shiftedRgba2D_)
{
                                                 for (int i=iLow; i<=iHigh; i++)
                                                         shiftedRgba2D_[i] += colShift;
                                                 shiftedRgba2D_ += rowShift;
                         }
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangles are different, then we must delete
     //  and reallocate the GraphWorld as well as the 0-based 2D raster.
     else
     {
         //      I am not sure if this is the right thing to do: should subclasses completely
         //      reimplement this or call this function?  This is opting for the latter.
         if (!graphWorldIsNull_())
         {
             delete gworld_;
             deleteShiftedRaster2D_(y);
             deleteRaster2D_();
             allocateGraphWorld_(theHeight, theWidth);
             allocateRaster2D_(theHeight, theWidth);
             allocateShiftedRaster2D_(theHeight, theWidth, y, x);
         }
     }
 }
void RasterImage_RGBa::updateRaster_ (void) const private virtual
Forces an update of the base rgba raster if it is not the reference raster.
This virtual function should be overridden by all subclasses of RasterImage_RGBa.
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F, and uriVL::RasterImage_HSV.
Definition at line 389 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::floatRasterIsReference_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::hasFloatRaster_, uriVL::RasterImage::hasOtherRaster_, uriVL::RasterImage::referenceHasChanged_, uriVL::RasterImage_HSV::updateRaster_(), and uriVL::RasterImage_RGBa_F::updateRaster_().
Referenced by uriVL::RasterImage_HSV24::getHue(), uriVL::RasterImage_HSV24::getHue2D(), uriVL::RasterImage_HSV24::getSat(), uriVL::RasterImage_HSV24::getSat2D(), uriVL::RasterImage_HSV24::getShiftedHue2D(), uriVL::RasterImage_HSV24::getShiftedSat2D(), uriVL::RasterImage_HSV24::getShiftedVal2D(), uriVL::RasterImage_HSV24::getVal(), uriVL::RasterImage_HSV24::getVal2D(), and writeInto_().
 {
         //something is not right.  We end up here for an RGBa image!!
     if (hasFloatRaster_)
         {
                 if (floatRasterIsReference_)
                 {
                         RasterImage_RGBa_F* tempF = (RasterImage_RGBa_F*)this;
                         tempF->updateRaster_();
                 }
         }
         else
         {
                 //      ugly hack.  Change this ASAP
                 if (hasOtherRaster_ && !gworldIsReference_ && !referenceHasChanged_)
                 {
                         RasterImage_HSV* tempHSV = (RasterImage_HSV*)this;
                         tempHSV->updateRaster_();
                 }
         }
     referenceHasChanged_ = false;
 }
void RasterImage_RGBa::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const protected virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Reimplemented in uriVL::RasterImage_RGBa_F.
Definition at line 459 of file RasterImage_RGBa.cpp.
References uriVL::RasterImage::allocateRaster2D_(), uriVL::RasterImage::allocateShiftedRaster2D_(), convertToGray(), uriVL::GraphWorld::copyInto(), uriVL::RasterImage::defaultGrayConv_, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), getShiftedRGBa2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::hasFloatRaster(), uriVL::kaRGB16Raster, uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kSaturatedPositive, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
Referenced by copyInto(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
         //  The GWorld only works with unshifted rasters so we need to compute
         //  the "true" copy rectangles first
     ImageRect*  sourceRect = new ImageRect(copyRect->getLeft() - getLeft(),
                                                                                    copyRect->getTop() - getTop(),
                                                                                    copyRect->getWidth(), copyRect->getHeight());
         ImageRect*  destRect =  origin == NULL ?
                                                         new ImageRect(copyRect->getLeft() - imgOut->getLeft(),
                                           copyRect->getTop() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight())
                                                         :
                                                         new ImageRect(origin->getX() - imgOut->getLeft(),
                                           origin->getY() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight());
         const unsigned char* const* rgbaSource = getShiftedRGBa2D();
         const int   iLowSource = sourceRect->getTop(),
                                 iLowDest = destRect->getTop(),
                                 iHighSource = sourceRect->getBottom(),
                                 jLowSource = sourceRect->getLeft(),
                                 jHighSource = sourceRect->getRight(),
                                 jLowDest = destRect->getLeft();
         const int       nbRows = sourceRect->getHeight(),
                                 nbCols = sourceRect->getWidth();
     //  Subclasses should override this function, but in case they don't, we need to
     //  do the conversion through the base gray-level raster.
     if (!gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     switch( imgOut->getBaseRasterType() )
     {
         case kBinaryRaster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
             imgOut->gworldIsReference_ = true;
             imgOut->referenceHasChanged_ = true;
             break;
         case kGrayRaster:
             //  are we dealing with a gray, gray_F, or gray_D image?
             //
             //  The output image is a "regular" gray image [unsigned char]
             if (!imgOut->hasFloatRaster())
             {
                 //  At this point we are ready to perform the copy/conversion and we use
                 //  the CopyBits function of QuickDraw/QuickTime
                 gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
                 imgOut->gworldIsReference_ = true;
                 imgOut->referenceHasChanged_ = true;
             }
             //  if the image has a floating point raster, we have no choice but to do the
             //  conversion "by hand"
             else
             {
                 float* const* fltGrayDest= ((RasterImage_gray_F *)imgOut)->getShiftedGrayF2D(R_W_ACCESS);
                 for (int i=iLowSource, iDest=iLowDest; i<=iHighSource; i++, iDest++)
                     convertToGray(rgbaSource[i]+jLowSource, fltGrayDest[iDest]+jLowDest,
                                    nbCols, defaultGrayConv_);
                 ((RasterImage_gray_F *)imgOut)->setFloatConversionMode(kSaturatedPositive);
                 imgOut->gworldIsReference_ = false;
                 imgOut->referenceHasChanged_ = true;
             }
             break;
         case kRGB24Raster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
             imgOut->gworldIsReference_ = true;
             imgOut->referenceHasChanged_ = true;
             break;
         case kaRGB16Raster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
             imgOut->gworldIsReference_ = true;
             imgOut->referenceHasChanged_ = true;
             break;
         case kRGBa32Raster:
                 // imgOut has integer type
                         if (!imgOut->hasFloatRaster())
                 {
                 //  This is a temporary hack until we agree on a general strategy
                 //  for handling future (third-party) color space implementations
                 if (typeid(*imgOut) == typeid(uriVL::RasterImage_HSV))
                 {
                     //  we already know that imgOut is at least as large as the
                     //  copy region
                     //((RasterImage_HSV* ) imgOut)->convertFromRGBa_(this, copyRect);
                                         //
                                         //jyh 2012-12-01
                                         //We still copy the data into the gwordl
                     gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
                     imgOut->gworldIsReference_ = true;
                     imgOut->referenceHasChanged_ = true;
                 }
                 else
                 {
                     //  At this point we are ready to perform the copy/conversion and we use
                     //  the CopyBits function of QuickDraw/QuickTime
                     gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
                     imgOut->gworldIsReference_ = true;
                     imgOut->referenceHasChanged_ = true;
                 }
             }
             // imgOut has float type
             else
             {
                 float* const* fRedDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                 float* const* fGreenDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                 float* const* fBlueDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                 //      This call may have been made from within the RasterImage_RGBa_F constructor of imgOut,
                                 //      in which case grayDest has not been allocated yet
                                 if ((fRedDest == NULL) || (fGreenDest == NULL)  || (fBlueDest == NULL))
{
                                         imgOut->allocateRaster2D_(nbRows, nbCols);
                                         imgOut->allocateShiftedRaster2D_(nbRows, nbCols, iLowDest, jLowDest);
                                         fRedDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                                         fGreenDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                                         fBlueDest = (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                                 }
                 for (int i=iLowSource, iDest=iLowDest; i<=iHighSource; i++, iDest++)
                                 for(int j=jLowSource, k=4*jLowSource, jDest=jLowDest; j<=jHighSource; j++, k++, jDest++)
{
                             fRedDest[iDest][jDest] = rgbaSource[i][k++];
                                                 fGreenDest[iDest][jDest] = rgbaSource[i][k++];
                                                 fBlueDest[iDest][jDest] = rgbaSource[i][k++];
                                         }
                 static_cast<RasterImage_RGBa_F *>(imgOut)->setFloatConversionMode(kSaturatedPositive);
                 imgOut->gworldIsReference_ = false;
                 imgOut->referenceHasChanged_ = true;
             }
             break;
         default:
             break;
     }
     if (sourceRect != NULL)
         delete sourceRect;
     if (destRect != NULL)
         delete destRect;
 }
Friends And Related Function Documentation
friend class _GraphWorld_gen friend
Definition at line 564 of file RasterImage_RGBa.h.
Member Data Documentation
unsigned char** uriVL::RasterImage_RGBa::rgba2D_ private
0-based 2D array mapped on the GraphWorld's 1D raster.
Definition at line 520 of file RasterImage_RGBa.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getRGBa2D(), getShiftedRGBa2D(), and RasterImage_RGBa().
unsigned char** uriVL::RasterImage_RGBa::shiftedRgba2D_ private
"shifted" 2D array (based on the image's rectangle bounds) mapped on the GraphWorld's 1D raster.
Definition at line 526 of file RasterImage_RGBa.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), getShiftedRGBa2D(), and setBoundRect_().
The documentation for this class was generated from the following files:
RasterImage_RGBa.h
RasterImage_RGBa.cpp