URIVisionLibrary: uriVL::NonlinearOptimizerND_conjDir Class Reference
uriVL::NonlinearOptimizerND_conjDir Class Reference
Class that implements the conjugate directions line search optomization algorithm.
#include <NonlinearOptimizerND_conjDir.h>
Public Member Functions
NonlinearOptimizerND_conjDir (int n, DirectionUpdateMethod updateMethod, int reset=-1, DirectionResetMode resetMethod=CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the dimension.
NonlinearOptimizerND_conjDir (const FunctionND *fn, DirectionUpdateMethod updateMethod, int reset=-1, DirectionResetMode resetMethod=CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the function to optimize.
NonlinearOptimizerND_conjDir (const FunctionND_F *fn, DirectionUpdateMethod updateMethod, int reset=-1, DirectionResetMode resetMethod=CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the function to optimize.
virtual ~NonlinearOptimizerND_conjDir (void)
Destructor.
Public Member Functions inherited from uriVL::NonlinearOptimizerND
NonlinearOptimizerND (void)
Creates a new nD optimizer.
NonlinearOptimizerND (int n)
Creates a new n-dimensional nD optimizer.
NonlinearOptimizerND (const FunctionND *f)
Creates a new n-dimensional nD optimizer for a specific function.
NonlinearOptimizerND (const FunctionND_F *f)
Creates a new n-dimensional nD optimizer for a specific function.
virtual ~NonlinearOptimizerND (void)
Destructor.
void setFunction (const FunctionND *f)
Assigns a new nD function to this optimizer.
void setFunction (const FunctionND_F *f)
Assigns a new nD function to this optimizer.
bool isOptimizationFunction (const FunctionND *f)
Checks if the function passed as parameter is the one set for this optimization problem.
bool isOptimizationFunction (const FunctionND_F *f)
Checks if the function passed as parameter is the one set for this optimization problem.
int getDimension (void) const
Gives the dimension of this optimizer (if one has been set)
const OptimizerRecordND * minimize (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol)
Finds a (local) minimum for a function over a specific domain of R^n.
const OptimizerRecordND * minimize (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol)
Finds a (local) minimum for a function over a specific domain of R^n.
void minimize (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
Private Member Functions
NonlinearOptimizerND_conjDir (const NonlinearOptimizerND_conjDir &obj)
Disabled copy constructor.
const NonlinearOptimizerND_conjDir & operator= (const NonlinearOptimizerND_conjDir &obj)
Disabled copy operator.
void setFunction_ (const FunctionND *f)
Called by this class's public function prior to changing the value of the instance variable.
void setFunction_ (const FunctionND_F *f)
Called by this class's public function prior to changing the value of the instance variable.
void minimize_ (const FunctionND *f, const double *startX, const double *xMin, const double *xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize_ (const FunctionND_F *f, const float *startX, const float *xMin, const float *xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize_ (const FunctionND *f, const std::vector< double > &startX, const std::vector< double > &xMin, const std::vector< double > &xMax, double tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void minimize_ (const FunctionND_F *f, const std::vector< float > &startX, const std::vector< float > &xMin, const std::vector< float > &xMax, float tol, OptimizerRecordND *optRec)
Finds a (local) minimum for a function over a specific range.
void updateConjugateDirections_ (void)
Updates the set of conjugate directions of this optimizer.
void allocateInstanceArrays_ (const int n)
(re)allocates internal arrays following a change of function
void deleteInstanceArrays_ (const int n)
free internal arrays, called from destructor or following a change of function
Private Attributes
DirectionUpdateMethod updateMethod_
Method used to update the search directions.
int reset_
Reset directions after how many n-direction cycles.
DirectionResetMode resetMethod_
Method for reseting/initializing the directions.
double ** userDirections_
Initial/reset directions defined by the user (if any)
NonlinearOptimizer1D * lineMinimizer_
The 1D optimizer used by this nD optimizer to perform line minimization.
OptimizerRecord1D * lineRecord_
The 1D optimizer record returned by the 1D optimizer.
FunctionNDSection1D * ffSec1D_
1D section of the function to minimize (float version)
FunctionNDSection1D_F * fdSec1D_
1D section of the function to minimize (double version)
double ** u_
Set of conjugate directions for the optimization problem.
double * P0_
Origin of the search at the beginning of a cycle.
double * Pi_
Current origin of directional search.
int bestDirIndex_
Index of conjugate direction that produced the largest decrease of the function.
int cycleCounter_
Countes how many n-direction cycles the optimizer has gone through.
Friends
class NonlinearOptimizerND
Detailed Description
Class that implements the conjugate directions line search optomization algorithm.
The class implements different algorithms for choosing and updating the search directions. At some point in the future, the library may add support for sme sort of dynamic addition of a new update scheme, but for the time being the only way to add an update scheme is to add it statically in this class.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 78 of file NonlinearOptimizerND_conjDir.h.
Constructor & Destructor Documentation
NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir (int n, DirectionUpdateMethod updateMethod, int reset = -1, DirectionResetMode resetMethod = CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the dimension.
Parameters
n dimension of the optimizer
updateMethod scheme for updating the search directions
reset search directions are reset after how many n-direction cycles (n by default)
resetMethod how directions are reset
Definition at line 30 of file NonlinearOptimizerND_conjDir.cpp.
References allocateInstanceArrays_().
                         :   NonlinearOptimizerND(n),
                                 //
                                 updateMethod_(updateMethod),
                                 reset_(reset >= 0 ? reset : n),
                                 resetMethod_(resetMethod),
                                 userDirections_(NULL),
                                 lineMinimizer_(new NonlinearOptimizer1D_gss()),
                                 lineRecord_(new OptimizerRecord1D()),
                                 ffSec1D_(NULL),
                                 fdSec1D_(NULL),
                                 u_(NULL),
                                 P0_(NULL),
                                 Pi_(NULL),
                                 bestDirIndex_(0),
                                 cycleCounter_(0)
 {
         allocateInstanceArrays_(n);
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by NonlinearOptimizerND_conjDir constructor");
         throw e;
 }
NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir (const FunctionND * fn, DirectionUpdateMethod updateMethod, int reset = -1, DirectionResetMode resetMethod = CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the function to optimize.
Parameters
fn n-dimensional function of the optimization problem
updateMethod scheme for updating the search directions
reset search directions are reset after how many n-direction cycles (n by default)
resetMethod how directions are reset
Definition at line 56 of file NonlinearOptimizerND_conjDir.cpp.
References allocateInstanceArrays_(), and uriVL::FunctionND::getDimension().
                         :   NonlinearOptimizerND(fn),
                                 //
                                 updateMethod_(updateMethod),
                                 reset_(reset >= 0 ? reset : fn->getDimension()),
                                 resetMethod_(resetMethod),
                                 userDirections_(NULL),
                                 lineMinimizer_(new NonlinearOptimizer1D_gss()),
                                 lineRecord_(new OptimizerRecord1D()),
                                 ffSec1D_(NULL),
                                 fdSec1D_(NULL),
                                 u_(NULL),
                                 P0_(NULL),
                                 Pi_(NULL),
                                 bestDirIndex_(0),
                                 cycleCounter_(0)
 {
         allocateInstanceArrays_(fn->getDimension());
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by NonlinearOptimizerND_conjDir constructor");
         throw e;
 }
NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir (const FunctionND_F * fn, DirectionUpdateMethod updateMethod, int reset = -1, DirectionResetMode resetMethod = CANONICAL_DIRECTIONS)
Creates a new nD optimizer and specifies the function to optimize.
Parameters
fn n-dimensional function of the optimization problem
updateMethod scheme for updating the search directions
reset search directions are reset after how many n-direction cycles (n by default)
resetMethod how directions are reset
Definition at line 84 of file NonlinearOptimizerND_conjDir.cpp.
References allocateInstanceArrays_(), and uriVL::FunctionND_F::getDimension().
                         :   NonlinearOptimizerND(fn),
                                 //
                                 updateMethod_(updateMethod),
                                 reset_(reset >= 0 ? reset : fn->getDimension()),
                                 resetMethod_(resetMethod),
                                 userDirections_(NULL),
                                 lineMinimizer_(new NonlinearOptimizer1D_gss()),
                                 lineRecord_(new OptimizerRecord1D()),
                                 ffSec1D_(NULL),
                                 fdSec1D_(NULL),
                                 u_(NULL),
                                 P0_(NULL),
                                 Pi_(NULL),
                                 bestDirIndex_(0),
                                 cycleCounter_(0)
 {
         allocateInstanceArrays_(fn->getDimension());
 }
 catch (ErrorReport& e)
 {
         e.appendToMessage("called by NonlinearOptimizerND_conjDir constructor");
         throw e;
 }
NonlinearOptimizerND_conjDir::~NonlinearOptimizerND_conjDir (void) virtual
Destructor.
Definition at line 112 of file NonlinearOptimizerND_conjDir.cpp.
References deleteInstanceArrays_(), fdSec1D_, ffSec1D_, uriVL::NonlinearOptimizerND::getDimension(), lineMinimizer_, and lineRecord_.
 {
         deleteInstanceArrays_(getDimension());
         if (ffSec1D_ != NULL)
         delete ffSec1D_;
     if (fdSec1D_ != NULL)
         delete fdSec1D_;
         delete lineMinimizer_;
     delete lineRecord_;
 }
uriVL::NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir (const NonlinearOptimizerND_conjDir & obj) private
Disabled copy constructor.
Member Function Documentation
void NonlinearOptimizerND_conjDir::allocateInstanceArrays_ (const int n) private
(re)allocates internal arrays following a change of function
Parameters
n dimension of the new optimization problem
Definition at line 407 of file NonlinearOptimizerND_conjDir.cpp.
References P0_, Pi_, and u_.
Referenced by NonlinearOptimizerND_conjDir(), and setFunction_().
 {
     P0_ = new double[n];
         Pi_ = new double[n];
         u_ = new double*[n];
         for (int i=0; i<n; i++)
                 u_[i] = new double[n];
 }
void NonlinearOptimizerND_conjDir::deleteInstanceArrays_ (const int n) private
free internal arrays, called from destructor or following a change of function
Parameters
n current dimension of the optimization problem
Definition at line 418 of file NonlinearOptimizerND_conjDir.cpp.
References P0_, Pi_, u_, and userDirections_.
Referenced by ~NonlinearOptimizerND_conjDir().
 {
     if (P0_ != NULL)
         delete []P0_;
         P0_ = NULL;
     if (Pi_ != NULL)
         delete []Pi_;
         Pi_ = NULL;
     if (u_ != NULL)
     {
         for (int i=0; i<n; i++)
             delete []u_[i];
         delete []u_;
     }
         u_ = NULL;
     if (userDirections_ != NULL)
     {
         for (int i=0; i<n; i++)
             delete []userDirections_[i];
         delete []userDirections_;
     }
         userDirections_ = NULL;
 }
void NonlinearOptimizerND_conjDir::minimize_ (const FunctionND * f, const double * startX, const double * xMin, const double * xMax, double tol, OptimizerRecordND * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
move to the new point before changing direction
Implements uriVL::NonlinearOptimizerND.
Definition at line 182 of file NonlinearOptimizerND_conjDir.cpp.
References bestDirIndex_, uriVL::CANONICAL_DIRECTIONS, cycleCounter_, fdSec1D_, uriVL::FunctionND::func(), uriVL::NonlinearOptimizerND::getDimension(), uriVL::FunctionNDSection1D_F::getLowerBound(), uriVL::FunctionNDSection1D_F::getUpperBound(), uriVL::NonlinearOptimizerND::isOptimizationFunction(), uriVL::OptimizerRecord1D::isSuccess, uriVL::OptimizerRecordND::isSuccess, lineMinimizer_, lineRecord_, uriVL::NonlinearOptimizer1D::minimize(), uriVL::OptimizerRecordND::nbInnerIters, uriVL::OptimizerRecord1D::nbIters, uriVL::OptimizerRecordND::nbOuterIters, uriVL::OptimizerRecord1D::optVal, uriVL::OptimizerRecordND::optVal, uriVL::OptimizerRecord1D::optX, uriVL::OptimizerRecordND::optX, P0_, Pi_, resetMethod_, uriVL::NonlinearOptimizerND::setFunction(), u_, updateConjugateDirections_(), uriVL::USER_SPECIFIED_DIRECTIONS, and userDirections_.
 {
         //      If the function had not been pre-set we need to perform some allocations
         if (!isOptimizationFunction(f))
         {
                 setFunction(f);
         }
         //      if USER_SPECIFIED_DIRECTIONS was selected as direction update mode but the user has
         //      not set update directions, the mode is changed to CANONICAL_DIRECTIONS
         if ((resetMethod_ == USER_SPECIFIED_DIRECTIONS) && (userDirections_ == NULL))
                 resetMethod_ = CANONICAL_DIRECTIONS;
         updateConjugateDirections_();
         const int nDim = getDimension();
     //  set the starting position and the conjugate directions
     for (int i=0; i<nDim; i++)
     {
         Pi_[i] = P0_[i] = startX[i];
         //  the conjugate directions are initially the cardinal directions
         for (int j=0; j<nDim; j++)
             u_[i][j] = 0.L;
         u_[i][i] = 1.0L;
     }
 //jyh 2013-08-30
 //    //  inform the section function of the bounds for this search
 //    fdSec1D_->setBounds(xMin, xMax);
     //  the best value found so far is the one at our starting point
     double optVal = f->func(startX);
     cycleCounter_ = 0;
     optRec->nbOuterIters = 0;
     optRec->nbInnerIters = 0;
     optRec->isSuccess = true;   //  the power of positive thinking
     bool ongoingSearch = true;;
     //  repeat the cycle until a minimum is found or one of the
     //  line searches fail
     while (ongoingSearch)
     {
         //  One cycle over the conjugate directions
         cycleCounter_++;
         //  best direction so far
         bestDirIndex_ = -1;
         double   bestReduction = -1;
         double   inCycleOptVal = optVal;
         for (int i=0; (i<nDim) && ongoingSearch; i++)
         {
             //  perform line minimization along direction u[i]
 //jyh 2013-08-30
 //            fdSec1D_->setSection(Pi_, u_[i]);
             double   sMin = fdSec1D_->getLowerBound(),
                      sMax = fdSec1D_->getUpperBound();
             lineMinimizer_->minimize(fdSec1D_, 0, sMin, sMax, tol, lineRecord_);
             //  if the line minimization succeeded, we need to update the state to prepare
             //  for the next direction or cycle
             if (lineRecord_->isSuccess)
             {
                 float valReduction = inCycleOptVal - lineRecord_->optVal;
                 if (valReduction > bestReduction)
                 {
                     bestReduction  = valReduction;
                     bestDirIndex_ = i;
                 }
                 inCycleOptVal = lineRecord_->optVal;
                 optRec->nbInnerIters += lineRecord_->nbIters;
                 /// move to the new point before changing direction
                 double   s = lineRecord_->optX;
                 for (int j=0; j<nDim; j++)
                     Pi_[j] += s * u_[i][j];
             }
             //  if the line minimization failed, there is no need to search any further
             else
             {
                 optRec->isSuccess = false;
                 ongoingSearch = false;
             }
             optRec->nbOuterIters++;
         }
         //  are we done yet?  What fraction of its value did the function vary over a full
         //  cycle?
         if (tol*(fabs(inCycleOptVal) + fabs(optVal)) > 2.0*(optVal - inCycleOptVal))
             ongoingSearch = false;
         else
             updateConjugateDirections_();
         optVal = inCycleOptVal;
     }
     //  we store the results of our iteration in the optimizer record.
     //  The numbers of iterations are already up-to-date
     for (int j=0; j<nDim; j++)
         optRec->optX[j] = Pi_[j];
     optRec->optVal = optVal;
 }
void NonlinearOptimizerND_conjDir::minimize_ (const FunctionND_F * f, const float * startX, const float * xMin, const float * xMax, float tol, OptimizerRecordND * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized array of lower bounds of the search domain
xMax n-sized array of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implements uriVL::NonlinearOptimizerND.
Definition at line 295 of file NonlinearOptimizerND_conjDir.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Float forms of NonlinearOptimizerND_conjDir::minimize_ not implemented.  Will be translated from double versions once the latter works fine.");
 }
void NonlinearOptimizerND_conjDir::minimize_ (const FunctionND * f, const std::vector< double > & startX, const std::vector< double > & xMin, const std::vector< double > & xMax, double tol, OptimizerRecordND * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implements uriVL::NonlinearOptimizerND.
Definition at line 308 of file NonlinearOptimizerND_conjDir.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Vector forms of NonlinearOptimizerND_conjDir::minimize_ not implemented.  Will be translated from array version once the latter works fine.");
 }
void NonlinearOptimizerND_conjDir::minimize_ (const FunctionND_F * f, const std::vector< float > & startX, const std::vector< float > & xMin, const std::vector< float > & xMax, float tol, OptimizerRecordND * optRec) private virtual
Finds a (local) minimum for a function over a specific range.
Parameters
f the function to optimize
startX startting point of the search
xMin n-sized vector of lower bounds of the search domain
xMax n-sized vector of upper bounds of the search domain
tol tolerance of the search
optRec result of the optimization
Implements uriVL::NonlinearOptimizerND.
Definition at line 318 of file NonlinearOptimizerND_conjDir.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Vector forms of NonlinearOptimizerND_conjDir::minimize_ not implemented.  Will be translated from array version once the latter works fine.");
 }
const NonlinearOptimizerND_conjDir& uriVL::NonlinearOptimizerND_conjDir::operator= (const NonlinearOptimizerND_conjDir & obj) private
Disabled copy operator.
void NonlinearOptimizerND_conjDir::setFunction_ (const FunctionND * f) private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Reimplemented from uriVL::NonlinearOptimizerND.
Definition at line 133 of file NonlinearOptimizerND_conjDir.cpp.
References allocateInstanceArrays_(), FAIL_CONDITION, fdSec1D_, ffSec1D_, uriVL::FunctionND::getDimension(), and uriVL::kNullFunctionError.
 {
     FAIL_CONDITION( fn == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND_conjDir::setFunction");
     allocateInstanceArrays_(fn->getDimension());
     //  (re-)allocate the 1D section function if needed.
     if (fdSec1D_ != NULL)
     {
         delete fdSec1D_;
         fdSec1D_ = NULL;
     }
     if (ffSec1D_ == NULL)
         delete ffSec1D_;
     ffSec1D_ = new FunctionNDSection1D(fn);
 }
void NonlinearOptimizerND_conjDir::setFunction_ (const FunctionND_F * f) private virtual
Called by this class's public function prior to changing the value of the instance variable.
Any subclass that needs special allocation or preprocessing when a new function is set should override this function.
Parameters
f the new function of the optimization problem
Reimplemented from uriVL::NonlinearOptimizerND.
Definition at line 153 of file NonlinearOptimizerND_conjDir.cpp.
References allocateInstanceArrays_(), FAIL_CONDITION, fdSec1D_, ffSec1D_, uriVL::FunctionND_F::getDimension(), and uriVL::kNullFunctionError.
 {
     FAIL_CONDITION( fn == NULL,
                     kNullFunctionError,
                     "null function as parameter in NonlinearOptimizerND_conjDir::setFunction");
     allocateInstanceArrays_(fn->getDimension());
     //  (re-)allocate the 1D section function if needed.
     if (ffSec1D_ != NULL)
     {
         delete ffSec1D_;
         ffSec1D_ = NULL;
     }
     if (fdSec1D_ == NULL)
         delete fdSec1D_;
     fdSec1D_ = new FunctionNDSection1D_F(fn);
 }
void NonlinearOptimizerND_conjDir::updateConjugateDirections_ (void) private
Updates the set of conjugate directions of this optimizer.
Definition at line 330 of file NonlinearOptimizerND_conjDir.cpp.
References uriVL::CANONICAL_DIRECTIONS, cycleCounter_, FAIL_CONDITION, uriVL::NonlinearOptimizerND::getDimension(), uriVL::kCaseNotImplemented, uriVL::NO_UPDATE, P0_, Pi_, uriVL::POWELL_DISCARD_LARGEST_DECREASE_DIR, uriVL::POWELL_UN_IS_XN_X0, uriVL::RANDOM_ORTHOGONAL_DIRECTIONS, reset_, resetMethod_, u_, updateMethod_, and uriVL::USER_SPECIFIED_DIRECTIONS.
Referenced by minimize_().
 {
         const int nDim = getDimension();
         //      First, if we have regular reset, check if it's time to do one
         if ((updateMethod_ != NO_UPDATE) && ((cycleCounter_ % (reset_ * nDim)) == 0))
         {
                 switch (resetMethod_)
                 {
                         case USER_SPECIFIED_DIRECTIONS:
                                 FAIL_CONDITION( true,
                                                                 kCaseNotImplemented,
                                                                 "case not implemented yet in NonlinearOptimizerND_conjDir::updateConjugateDirections_");
                                 break;
                         RANDOM_ORTHOGONAL_DIRECTIONS:
                                 FAIL_CONDITION( true,
                                                                 kCaseNotImplemented,
                                                                 "case not implemented yet in NonlinearOptimizerND_conjDir::updateConjugateDirections_");
                                 break;
                         CANONICAL_DIRECTIONS:
                         default:
                 for (int i=0; i<nDim; i++)
                 {
                     for (int j=0; j<nDim; j++)
                         u_[i][j] = 0.L;
                     u_[i][i] = 1.0L;
                 }
                         break;
                 }
         }
         //      else, go for regular update
         else
         {
                 switch (updateMethod_)
                 {
                         case NO_UPDATE:
                                 //
                                 //      do nothing
                                 break;
                         case POWELL_UN_IS_XN_X0:
                                 //  simply permutate the pointers
                                 for (int i=0; i<nDim-1; i++)
                                         u_[i] = u_[i+1];
                                 //  new direction is given by P0-PN
                                 for (int j=0; j<nDim-1; j++)
                                         u_[nDim-1][j] = Pi_[j] - P0_[j];
                                 break;
                         case POWELL_DISCARD_LARGEST_DECREASE_DIR:
                                 FAIL_CONDITION( true,
                                                                 kCaseNotImplemented,
                                                                 "case not implemented yet in NonlinearOptimizerND_conjDir::updateConjugateDirections_");
                                 break;
                         default:
                                 FAIL_CONDITION( true,
                                                                 kCaseNotImplemented,
                                                                 "case not implemented yet in NonlinearOptimizerND_conjDir::updateConjugateDirections_");
                 }
         }
 }
Friends And Related Function Documentation
friend class NonlinearOptimizerND friend
Definition at line 270 of file NonlinearOptimizerND_conjDir.h.
Member Data Documentation
int uriVL::NonlinearOptimizerND_conjDir::bestDirIndex_ private
Index of conjugate direction that produced the largest decrease of the function.
Definition at line 167 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_().
int uriVL::NonlinearOptimizerND_conjDir::cycleCounter_ private
Countes how many n-direction cycles the optimizer has gone through.
Definition at line 172 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_(), and updateConjugateDirections_().
FunctionNDSection1D_F* uriVL::NonlinearOptimizerND_conjDir::fdSec1D_ private
1D section of the function to minimize (double version)
Definition at line 151 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_(), setFunction_(), and ~NonlinearOptimizerND_conjDir().
FunctionNDSection1D* uriVL::NonlinearOptimizerND_conjDir::ffSec1D_ private
1D section of the function to minimize (float version)
Definition at line 147 of file NonlinearOptimizerND_conjDir.h.
Referenced by setFunction_(), and ~NonlinearOptimizerND_conjDir().
NonlinearOptimizer1D* uriVL::NonlinearOptimizerND_conjDir::lineMinimizer_ private
The 1D optimizer used by this nD optimizer to perform line minimization.
Definition at line 139 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_(), and ~NonlinearOptimizerND_conjDir().
OptimizerRecord1D* uriVL::NonlinearOptimizerND_conjDir::lineRecord_ private
The 1D optimizer record returned by the 1D optimizer.
Definition at line 143 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_(), and ~NonlinearOptimizerND_conjDir().
double* uriVL::NonlinearOptimizerND_conjDir::P0_ private
Origin of the search at the beginning of a cycle.
Definition at line 159 of file NonlinearOptimizerND_conjDir.h.
Referenced by allocateInstanceArrays_(), deleteInstanceArrays_(), minimize_(), and updateConjugateDirections_().
double* uriVL::NonlinearOptimizerND_conjDir::Pi_ private
Current origin of directional search.
Definition at line 163 of file NonlinearOptimizerND_conjDir.h.
Referenced by allocateInstanceArrays_(), deleteInstanceArrays_(), minimize_(), and updateConjugateDirections_().
int uriVL::NonlinearOptimizerND_conjDir::reset_ private
Reset directions after how many n-direction cycles.
Definition at line 127 of file NonlinearOptimizerND_conjDir.h.
Referenced by updateConjugateDirections_().
DirectionResetMode uriVL::NonlinearOptimizerND_conjDir::resetMethod_ private
Method for reseting/initializing the directions.
Definition at line 131 of file NonlinearOptimizerND_conjDir.h.
Referenced by minimize_(), and updateConjugateDirections_().
double** uriVL::NonlinearOptimizerND_conjDir::u_ private
Set of conjugate directions for the optimization problem.
Definition at line 155 of file NonlinearOptimizerND_conjDir.h.
Referenced by allocateInstanceArrays_(), deleteInstanceArrays_(), minimize_(), and updateConjugateDirections_().
DirectionUpdateMethod uriVL::NonlinearOptimizerND_conjDir::updateMethod_ private
Method used to update the search directions.
Definition at line 123 of file NonlinearOptimizerND_conjDir.h.
Referenced by updateConjugateDirections_().
double** uriVL::NonlinearOptimizerND_conjDir::userDirections_ private
Initial/reset directions defined by the user (if any)
Definition at line 135 of file NonlinearOptimizerND_conjDir.h.
Referenced by deleteInstanceArrays_(), and minimize_().
The documentation for this class was generated from the following files:
NonlinearOptimizerND_conjDir.h
NonlinearOptimizerND_conjDir.cpp