URIVisionLibrary: uriVL::HomogeneousMatrix Class Reference
uriVL::HomogeneousMatrix Class Reference
Implements 4x4 homogeneous matrices used to represent 3D transformations.
#include <HomogeneousMatrix.h>
Public Member Functions
HomogeneousMatrix (void)
Creates an identity 4x4 matrix.
HomogeneousMatrix (const HomogeneousMatrix *theMat)
Copy constructor.
HomogeneousMatrix (const double *glMat)
Initializes the new matrix with the values of a flat, "GL-style" matrix.
HomogeneousMatrix (const double theMat[][4])
Initializes this matrix with the values of the one received as parameter.
~HomogeneousMatrix (void)
Destructor.
const GLfloat * getGLMatrix (void)
Returns a read-only pointer to the matrix data.
GLfloat * getGLMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
Public Member Functions inherited from uriVL::Matrix
Matrix (int nbRows, int nbCols)
Creates a nbRows x nbCols matrix whose elements have not been initialized.
Matrix (int nbRows, int nbCols, double v)
"v-valued" constructor of Matrix class.
Matrix (const Matrix *b)
Copy constructor.
Matrix (const Matrix &b)
Copy constructor.
Matrix (int nbRows, int nbCols, double **m, bool safe=true, const MatrixIndicators *matrixIndic=NULL)
"array" constructor of Matrix class.
virtual ~Matrix (void)
Destructor.
int getNbRows (void) const
This function returns a int corresponding to the number of rows in this
int getNbCols (void) const
This function returns a int corresponding to the number of columns in this
const double *const * getMatrix (void) const
Returns a read-only pointer to the matrix data.
double *const * getMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
TriState isSymmetric (void)
Check whether the matrix is symmetric.
TriState isAntisymmetric (void)
Check whether the matrix is antisymmetric.
TriState isOrthogonal (void)
Check whether the matrix is orthogonal.
TriState isDiagonal (void)
Check whether the matrix is diagonal.
TriState isIdentity (void)
Check whether the matrix is an identity matrix.
TriState isUpperTriangular (void)
Check whether the matrix is upper-triangular.
TriState isLowerTriangular (void)
Check whether the matrix is lower-triangular.
double checkSymmetryStatus (void)
Check whether the matrix is symmetric.
double checkAntisymmetryStatus (void)
Check whether the matrix is antisymmetric.
double checkOrthogonalityStatus (void)
Check whether the matrix is orthogonal.
double checkDiagonalityStatus (void)
Check whether the matrix is diagonal.
double checkIdentityStatus (void)
Check whether the matrix is an identity matrix.
double checkUpperTriangularityStatus (void)
Check whether the matrix is upper-triangular.
double checkLowerTriangularityStatus (void)
Check whether the matrix is lower-triangular.
double checkNormalization1Status (void)
Check whether the matrix is normalized according to Norm 1.
double checkNormalization2Status (void)
Check whether the matrix is normalized according to Norm 2.
double checkNormalizationInfStatus (void)
Check whether the matrix is normalized according to Norm 1.
void enforceSymmetry (void)
Forces a matrix that passes the test for symmetry of checkIsSymmetric_ to be exactly symmetric.
void enforcesAntisymmetry (void)
Forces a matrix that passes the test for antisymmetry of checkIsAntisymmetric_ to be exactly antisymmetric.
void enforceOthogonality (void)
Forces a matrix that passes the test for orthogonality of checkIsSymmetric_ to be exactly orthogonality.
void enforceDiagonality (void)
Forces a matrix that passes the test for diagonality of checkIsDiagonal_ to be exactly diagonal.
void enforceIdentity (void)
Forces a matrix that passes the test for identity of checkIsIdentity_ to be exactly identity.
void enforceUpperTriangularity (void)
Forces a matrix that passes the test for upper-triangularity of checkIsUpperTriangular_ to be exactly upper-triangular.
void enforceLowerTriangularity (void)
Forces a matrix that passes the test for lower-triangularity of checkIsLowerTriangular_ to be exactly lower-triangular.
void operator+= (const Matrix &b)
This function adds the parameter Matrix b to this thereby modifying this.
virtual void operator-= (const Matrix &b)
This function subtracts the parameter Matrix from this thereby modifying this.
virtual void operator*= (const double s)
This function multiplies every element of this by the scalar parameter thereby modifying this.
virtual void operator*= (const Matrix &b)
This function premultiplies the parameter Matrix b by this thereby modifying this.
virtual void preMultiplyBy (const Matrix *b)
This function premultiplies this by the parameter Matrix b thereby modifying this
virtual void postMultiplyBy (const Matrix *b)
This function postmultiplies this by the parameter Matrix b thereby modifying this
const Matrix & operator= (const Matrix &b)
Assigns to this matrix the matrix received as parameter (resizes it if necessary.
TriState operator== (const Matrix &b) const
This function does an element-wise comparison to the parameter Matrix b with this.
double operator() (int theRow, int theCol) const
This function returns the element of the Matrix at row theRow and column theCol.
void rowSwap (int r1, int r2)
This function swaps rows of the Matrix (rather, of mat_)
void colSwap (int c1, int c2)
This function swaps columns of the Matrix (rather, of mat_)
double norm1 (void) const
This function returns a double corresponding to the "1" norm of the Matrix this.
double normInf (void) const
This function returns a double corresponding to the "Infinity" norm of the Matrix this.
double determinant (void) const
This function returns a double corresponding to the determinant of the Matrix this.
virtual Matrix * transposition (void) const
This function returns a reference to a new Matrix object, the transposition of this matrix.
virtual void transpose (void)
This function transposes this, thereby altering this.
virtual Matrix * inverse (void) const
This function creates a new Matrix corresponding to the inverse of this (if nonsingular).
virtual void invert (void)
This function inverts this (if nonsingular), thereby modifying this.
string toString (void) const
This function returns a string corresponding to the matrix using the static delimiting strings for the Matrix class.
string toString (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor) const
This function returns a string corresponding to the matrix using the parameters as delimiting strings.
Protected Attributes
GLfloat glMat_ [16]
copy of the mat_ matrix used for OpenGL transformations
Additional Inherited Members
Static Public Member Functions inherited from uriVL::Matrix
static Matrix * copyMatrix (int nbRows, int nbCols, const double *const *m)
Creates a new nbRows x nbCols matrix and copies into it the elements of the 2D array referenced by m.
static Matrix * nullMatrix (int nbRows, int nbCols)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements to zero.
static Matrix * diagonalMatrix (int nbRows, int nbCols, double v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * diagonalMatrix (int nbRows, int nbCols, const double *v)
Produces a new diagonal matrix at the dimensions specified and initializes all diagonal elements with the value specified.
static Matrix * identityMatrix (int n)
Produces a new identity matrix at the dimensions specified.
static Matrix * randomMatrix (int nbRows, int nbCols, double lowerBound, double upperBound)
produces a new matrix filled with random values between lowerBound (inclusive) and upperBound (exclusive)
static void setToStringFormat (string theBeginArrayStr, string theEndArrayStr, string theElmtSepStr, bool theEolAtEor)
This function resets the delimiting strings used when generating a string representation for a given matrix.
Detailed Description
Implements 4x4 homogeneous matrices used to represent 3D transformations.
Definition at line 30 of file HomogeneousMatrix.h.
Constructor & Destructor Documentation
HomogeneousMatrix::HomogeneousMatrix (void)
Creates an identity 4x4 matrix.
Definition at line 22 of file HomogeneousMatrix.cpp.
References uriVL::Matrix::mat_.
         :       Matrix(4, 4)
 {
     mat_[3][3] = 1.;
 }
HomogeneousMatrix::HomogeneousMatrix (const HomogeneousMatrix * theMat)
Copy constructor.
Parameters
theMat the matrix to copy
Definition at line 50 of file HomogeneousMatrix.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       Matrix(theMat)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "constructor not open for business yet");
 /*
     double** zeMat = theMat->getMatrix();
     for (int j=0; j<4; j++)
         for (int i=0; i<4; i++)
             mat_[i][j] = zeMat[i][j];
   isDiagonal_ = theMat->isDiagonal_;
   isUpperTriangular_ = theMat->isUpperTriangular_;
   isLowerTriangular_ = theMat->isLowerTriangular_;
   isSymmetric_ = theMat->isSymmetric_;
   isFullRank_ = theMat->isFullRank_;
   isAntisymmetric_ = theMat->isAntisymmetric_;
   isOrthogonal_ = theMat->isOrthogonal_;
 */
 }
HomogeneousMatrix::HomogeneousMatrix (const double * glMat)
Initializes the new matrix with the values of a flat, "GL-style" matrix.
Parameters
glMat a flat, column-ordered 16-element GL matrix
Definition at line 29 of file HomogeneousMatrix.cpp.
References uriVL::Matrix::mat_.
         :       Matrix(4, 4)
 {
     int k = 0;
     for (int j=0; j<4; j++)
         for (int i=0; i<4; i++)
             mat_[i][j] = glMat[k++];
 }
HomogeneousMatrix::HomogeneousMatrix (const double theMat[][4])
Initializes this matrix with the values of the one received as parameter.
Parameters
theMat a 4x4 homogeneous matrix
Definition at line 39 of file HomogeneousMatrix.cpp.
References uriVL::Matrix::mat_.
         :       Matrix(4, 4)
 {
     for (int j=0; j<4; j++)
         for (int i=0; i<4; i++)
             mat_[i][j] = theMat[i][j];
 }
HomogeneousMatrix::~HomogeneousMatrix (void)
Destructor.
Definition at line 73 of file HomogeneousMatrix.cpp.
 {
 }
Member Function Documentation
const GLfloat * HomogeneousMatrix::getGLMatrix (void)
Returns a read-only pointer to the matrix data.
If you want to have full read-write access to the data, call instead getMatrixRW.
Returns
the matrice's private read-only 2D array of data
Definition at line 77 of file HomogeneousMatrix.cpp.
References glMat_, and uriVL::Matrix::mat_.
Referenced by getGLMatrix(), and uriVL::Transformation3D::getGLMatrix().
 {
         glMat_[0] = static_cast<GLfloat>(mat_[0][0]);
         glMat_[1] = static_cast<GLfloat>(mat_[1][0]);
         glMat_[2] = static_cast<GLfloat>(mat_[2][0]);
         glMat_[3] = static_cast<GLfloat>(mat_[3][0]);
         glMat_[4] = static_cast<GLfloat>(mat_[0][1]);
         glMat_[5] = static_cast<GLfloat>(mat_[1][1]);
         glMat_[6] = static_cast<GLfloat>(mat_[2][1]);
         glMat_[7] = static_cast<GLfloat>(mat_[3][1]);
         glMat_[8] = static_cast<GLfloat>(mat_[0][2]);
         glMat_[9] = static_cast<GLfloat>(mat_[1][2]);
         glMat_[10] = static_cast<GLfloat>(mat_[2][2]);
         glMat_[11] = static_cast<GLfloat>(mat_[3][2]);
         glMat_[12] = static_cast<GLfloat>(mat_[0][3]);
         glMat_[13] = static_cast<GLfloat>(mat_[1][3]);
         glMat_[14] = static_cast<GLfloat>(mat_[2][3]);
         glMat_[15] = static_cast<GLfloat>(mat_[3][3]);
         return glMat_;
 }
GLfloat * HomogeneousMatrix::getGLMatrix (ReadWriteStatus rwa)
Returns a pointer to the matrix data that allows to set new values to the matrix's elements.
As a side effect, this function sets to IS_UNKNOWN all the matrix's indicators.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the matrix's private read-write 2D array of data
Definition at line 99 of file HomogeneousMatrix.cpp.
References getGLMatrix().
 {
     return const_cast<GLfloat* >(getGLMatrix());
 }
Member Data Documentation
GLfloat uriVL::HomogeneousMatrix::glMat_[16] protected
copy of the mat_ matrix used for OpenGL transformations
Definition at line 75 of file HomogeneousMatrix.h.
Referenced by getGLMatrix().
The documentation for this class was generated from the following files:
HomogeneousMatrix.h
HomogeneousMatrix.cpp