URIVisionLibrary: uriVL::ImagePoint Class Reference
uriVL::ImagePoint Class Reference
Implements the ImagePoint class.
#include <ImagePoint.h>
Public Member Functions
ImagePoint (bool hasSubpixelPrecision=false)
Default Constructor.
ImagePoint (int x, int y, bool hasSubpixelPrecision=false)
Constructor.
ImagePoint (const int xy[], bool hasSubpixelPrecision=false)
Constructor.
ImagePoint (const ImagePoint *thePt)
Copy constructor.
ImagePoint (const ImagePoint &thePt)
Copy constructor.
virtual ~ImagePoint (void)
Destructor.
const ImagePoint & operator= (const ImagePoint &thePt)
Equal operator.
int getX (void) const
Returns the point's x coordinate.
int getY (void) const
Returns the point's y coordinate.
int getID (void) const
Returns the point's id.
virtual void setX (int val)
Assigns new x coordinate to the pixel.
virtual void setY (int val)
Assigns new y coordinate to the pixel.
virtual void setCoordinates (int valX, int valY)
Assigns new coordinates to the pixel.
virtual void setCoordinates (const int xy[])
Assigns new coordinates to the pixel.
virtual void setCoordinates (const ImagePoint *thePt)
Assigns new coordinates to the pixel.
virtual void setCoordinates (const ImagePoint &thePt)
Assigns new coordinates to the pixel.
virtual void shiftX (int dx)
Shifts the existing x coordinate by the amount specified.
virtual void shiftY (int dy)
Shifts the existing y coordinate by the amount specified.
virtual void translate (int dx, int dy)
Shifts the existing x and y coordinates by the amount specified.
virtual void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
virtual void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation, which for a point does not make much sense.
virtual bool hasSubpixelPrecision (void) const
Indicates whether the image point has subpixel precision coordinates (is in fact an ImagePoint_F object)
float distanceTo (const ImagePoint *pt)
Computes the distance between this point and the one passed as parameter.
Static Public Member Functions
static float distance (const ImagePoint *pt1, const ImagePoint *pt2)
Computes the distance between two points.
Private Attributes
int x_
The point's x coordinate.
int y_
The point's y coordinate.
int id_
The point's id.
Static Private Attributes
static int ptCounter_ = 0
Class variable used to attribute a unique id to each Point object.
Friends
class ImagePoint_F
Detailed Description
Implements the ImagePoint class.
The ImagePoint class is based on the notion of a pixel as a dimensionless point. By opposition, QuickTime sees a pixel as a little square that hangs between the points (xLeft, yTop) and (xLeft+1, yTop+1).
Version history
2004/04/27 [jyh] fixed the pixel-as-point vs. pixel-as-rectangle issue.
2004/02/20 [jyh] first implementation.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 43 of file ImagePoint.h.
Constructor & Destructor Documentation
ImagePoint::ImagePoint (bool hasSubpixelPrecision = false)
Default Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Parameters
hasSubpixelPrecision = true if the image point has subpixel precision
Definition at line 38 of file ImagePoint.cpp.
                 :       x_(0),
                         y_(0),
                         id_(ptCounter_++)
 {
 }
ImagePoint::ImagePoint (int x, int y, bool hasSubpixelPrecision = false)
Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Parameters
x x coordinate of the point
y y coordinate of the point
hasSubpixelPrecision = true if the image point has subpixel precision
Definition at line 46 of file ImagePoint.cpp.
                 :       x_(theX),
                         y_(theY),
                         id_(ptCounter_++)
 {
 }
uriVL::ImagePoint::ImagePoint (const int xy[], bool hasSubpixelPrecision = false)
Constructor.
Creates an image point (pixel) using the pixel-as-point convention.
Parameters
xy coordinate array of the point
hasSubpixelPrecision = true if the image point has subpixel precision
ImagePoint::ImagePoint (const ImagePoint * thePt)
Copy constructor.
Creates a clone of the ImagePoint object passed as parameter.
Parameters
thePt pointer to the ImagePoint object to copy
Definition at line 69 of file ImagePoint.cpp.
             :   x_(thePt->x_),
                         y_(thePt->y_),
                         id_(ptCounter_++)
 {
 }
 catch(...) {
         FAIL_CONDITION( thePt == NULL,
                                         kNullParameterError,
                                         "null ImagePoint pointer passed to ImagePoint constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint pointer passed to ImagePoint constructor.");
 }
ImagePoint::ImagePoint (const ImagePoint & thePt)
Copy constructor.
Creates a copy of the ImagePoint object passed as parameter. Note that the copy will have a new id.
Parameters
thePt reference to the ImagePoint object to copy
Definition at line 85 of file ImagePoint.cpp.
             :   x_(thePt.x_),
                         y_(thePt.y_),
                         id_(ptCounter_++)
 {
 }
 catch(...) {
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid  ImagePoint reference passed to ImagePoint copy constructor.");
 }
ImagePoint::~ImagePoint (void) virtual
Destructor.
Definition at line 97 of file ImagePoint.cpp.
 {
 }
Member Function Documentation
void ImagePoint::applyTransformation (const Transformation2D * theTransf) virtual
Applies a Transformation2D to this object.
Parameters
theTransf the Transformation2D to apply to this object
Reimplemented in uriVL::ImagePoint_F.
Definition at line 254 of file ImagePoint.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Function not implemented yet");
 }
float ImagePoint::distance (const ImagePoint * pt1, const ImagePoint * pt2) static
Computes the distance between two points.
Parameters
pt1 pointer to the first point
pt2 pointer to the second point
Returns
distance between the two points
Definition at line 262 of file ImagePoint.cpp.
References getX(), uriVL::ImagePoint_F::getXF(), getY(), and uriVL::ImagePoint_F::getYF().
 {
 //      try
 //      {
                 float x1, x2, y1, y2;
                 if (typeid(*pt1) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F* pt1F = static_cast<const ImagePoint_F*>(pt1);
                         x1 = pt1F->getXF();
                         y1 = pt1F->getYF();
                 }
                 else
                 {
                         x1 = pt1->getX();
                         y1 = pt1->getY();
                 }
                 if (typeid(*pt2) == typeid(uriVL::ImagePoint_F))
                 {
                         const ImagePoint_F* pt2F = static_cast<const ImagePoint_F*>(pt2);
                         x2 = pt2F->getXF();
                         y2 = pt2F->getYF();
                 }
                 else
                 {
                         x2 = pt2->getX();
                         y2 = pt2->getY();
                 }
                 float dx = x1 - x2, dy = y1 - y2;
                 return sqrtf(dx*dx + dy*dy);
 //      }
 //      catch(...)
 //      {
 //
 //      }
 }
float uriVL::ImagePoint::distanceTo (const ImagePoint * pt) inline
Computes the distance between this point and the one passed as parameter.
Parameters
pt pointer to the point we want the distance to
Returns
distance to the point
Definition at line 201 of file ImagePoint.h.
{
                                 return distance(this, pt);
                         }
int ImagePoint::getID (void) const
Returns the point's id.
Returns
id of the point
Definition at line 138 of file ImagePoint.cpp.
References id_.
 {
         return id_;
 }
int ImagePoint::getX (void) const
Returns the point's x coordinate.
Returns
x coordinate of the point
Definition at line 128 of file ImagePoint.cpp.
References x_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::BlobTracker2DController::action(), uriVL::Blob::Blob(), uriVL::DrawableObject2D::computeScaledCorners_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::Contour_F::contains(), uriVL::DrawableObject2D::contains(), uriVL::Blob::contains(), uriVL::Pattern2D::contains(), uriVL::ImageRect::contains(), uriVL::RasterImage::copyInto_(), uriVL::StereoMatcher::disparity(), uriVL::Cluster::distance(), distance(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findBlobAbout(), uriVL::PatternTracker2D::findLeft_(), uriVL::BlobFinder::findLeft_(), uriVL::PatternTracker2D::findRight_(), uriVL::BlobFinder::findRight_(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::grab(), uriVL::ImageRect::ImageRect(), uriVL::StereoMatcher::match(), uriVL::RectifiedStereoMatcher_corr::match_(), myDisplay2(), myDisplay3(), myIdle(), uriVL::PatternTracker2D::PatternTracker2D(), performMatching(), uriVL::PatternMatcher2D_warp::reverseWarp_(), uriVL::ImagePoint_F::rotate(), uriVL::Pattern2DMatchRecord::setBestMatch(), uriVL::StereoMatchRecord::setBestMatch(), uriVL::Vector2D::setCoordinates(), uriVL::Vector2D_F::setCoordinates(), uriVL::ImagePoint_F::setCoordinates(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::TrackingState::setPos(), uriVL::ImageRect::setRect(), uriVL::BlobFinder::spiralSearch_(), uriVL::PatternTracker2D::track(), uriVL::Pattern2D::writeInto(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return x_;
 }
int ImagePoint::getY (void) const
Returns the point's y coordinate.
Returns
y coordinate of the point
Definition at line 133 of file ImagePoint.cpp.
References y_.
Referenced by uriVL::PatternTracker2DController::action(), uriVL::BlobTracker2DController::action(), uriVL::Blob::Blob(), uriVL::DrawableObject2D::computeScaledCorners_(), uriVL::RectifiedStereoMatcher_corr::computeSearchRects_(), uriVL::Contour_F::contains(), uriVL::DrawableObject2D::contains(), uriVL::Blob::contains(), uriVL::Pattern2D::contains(), uriVL::ImageRect::contains(), uriVL::RasterImage::copyInto_(), uriVL::StereoMatcher::disparity(), uriVL::Cluster::distance(), distance(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findBlobAbout(), uriVL::PatternTracker2D::findLeft_(), uriVL::BlobFinder::findLeft_(), uriVL::PatternTracker2D::findRight_(), uriVL::BlobFinder::findRight_(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getTop(), uriVL::RasterImage::grab(), uriVL::ImageRect::ImageRect(), uriVL::StereoMatcher::match(), uriVL::RectifiedStereoMatcher_corr::match_(), myDisplay2(), myDisplay3(), uriVL::PatternTracker2D::PatternTracker2D(), performMatching(), uriVL::PatternMatcher2D_warp::reverseWarp_(), uriVL::ImagePoint_F::rotate(), uriVL::Pattern2DMatchRecord::setBestMatch(), uriVL::StereoMatchRecord::setBestMatch(), uriVL::Vector2D::setCoordinates(), uriVL::Vector2D_F::setCoordinates(), uriVL::ImagePoint_F::setCoordinates(), uriVL::WarpMatchScoreFunctionND::setImage(), uriVL::TrackingState::setPos(), uriVL::ImageRect::setRect(), uriVL::BlobFinder::spiralSearch_(), uriVL::PatternTracker2D::track(), uriVL::Pattern2D::writeInto(), uriVL::RasterImage::writeInto(), uriVL::RasterImage_aRGB16::writeInto_(), uriVL::RasterImage_RGB::writeInto_(), uriVL::RasterImage_RGBa::writeInto_(), uriVL::RasterImage_gray::writeInto_(), uriVL::RasterImage_gray_F::writeInto_(), uriVL::RasterImage_binary::writeInto_(), and uriVL::RasterImage_RGBa_F::writeInto_().
 {
     return y_;
 }
bool ImagePoint::hasSubpixelPrecision (void) const virtual
Indicates whether the image point has subpixel precision coordinates (is in fact an ImagePoint_F object)
Returns
true if image point has subpixel precision
Reimplemented in uriVL::ImagePoint_F.
Definition at line 122 of file ImagePoint.cpp.
 {
         return false;
 }
const ImagePoint & ImagePoint::operator= (const ImagePoint & thePt)
Equal operator.
Created so that gcc will stop complaining. This Point object will retain its own id.
Parameters
thePt reference to the ImagePoint object to copy
Definition at line 101 of file ImagePoint.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, x_, and y_.
 {
         try {
                 x_ = thePt.x_;
                 y_ = thePt.y_;
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid  ImagePoint reference passed to ImagePoint = operator.");
         }
         return *this;
 }
void ImagePoint::rotate (float angle, const ImagePoint * rotCenter = NULL) virtual
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation, which for a point does not make much sense.
Parameters
angle the angle of the rotation (in radians)
rotCenter the center of the rotation
Reimplemented in uriVL::ImagePoint_F.
Definition at line 217 of file ImagePoint.cpp.
References uriVL::ImagePoint_F::getXF(), uriVL::ImagePoint_F::getYF(), x_, and y_.
 {
     const float cT = cosf(angle),
                 sT = sinf(angle);
     //  if the rotation center is null we rotate around the origin
     if (rotCenter == NULL)
     {
         const int x = static_cast<int>(cT*x_ - sT*y_);
         y_ = static_cast<int>(sT*x_ + cT*y_);
         x_ = x;
     }
     else
     {
         if (typeid(*rotCenter) == typeid(uriVL::ImagePoint_F))
         {
                 const ImagePoint_F      *rotCenterF = (ImagePoint_F*) rotCenter;
                 const float xcf = rotCenterF->getXF();
                 const float ycf = rotCenterF->getYF();
                 const float dx = x_ - xcf;
                 const float dy = y_ - ycf;
                 x_ = static_cast<int>(xcf + cT*dx - sT*dy);
                 y_ = static_cast<int>(ycf + sT*dx + cT*dy);
         }
         else
         {
                 const int xc = rotCenter->x_;
                 const int yc = rotCenter->y_;
                 const float dx = x_ - xc;
                 const float dy = y_ - yc;
                 x_ = xc + static_cast<int>(cT*dx - sT*dy);
                 y_ = yc + static_cast<int>(sT*dx + cT*dy);
         }
     }
 }
void ImagePoint::setCoordinates (int valX, int valY) virtual
Assigns new coordinates to the pixel.
Parameters
valY new x coordinate for the point
valY new y coordinate for the point
Reimplemented in uriVL::ImagePoint_F.
Definition at line 153 of file ImagePoint.cpp.
References x_, and y_.
Referenced by uriVL::ImageRect::addAllAround(), uriVL::BlobFinder::fillThisBlob_(), uriVL::BlobFinder::findAllBlobs(), uriVL::PatternTracker2D::grabImage_(), handleMouseDrag(), uriVL::ImageRect::operator=(), performMatching(), uriVL::ImageRect::removeAllAround(), uriVL::StereoMatchRecord::setBestMatch(), uriVL::ImageRect::setOrigin(), uriVL::ImageRect::setRect(), uriVL::ImageRect::translate(), and uriVL::PatternTracker2D::verticalExtend_().
 {
     x_ = valX;
     y_ = valY;
 }
void ImagePoint::setCoordinates (const int xy[]) virtual
Assigns new coordinates to the pixel.
Parameters
xy coordinate array of the point
Definition at line 159 of file ImagePoint.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, x_, and y_.
 {
     FAIL_CONDITION( xy == NULL,
                     kNullParameterError,
                     "null coordinate array passed to ImagePoint::setCoordinates");
     x_ = xy[0];
     y_ = xy[1];
 }
void ImagePoint::setCoordinates (const ImagePoint * thePt) virtual
Assigns new coordinates to the pixel.
Parameters
thePt pointer to the ImagePoint object to copy
Reimplemented in uriVL::ImagePoint_F.
Definition at line 169 of file ImagePoint.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, x_, and y_.
 {
     FAIL_CONDITION( thePt == NULL,
                     kNullParameterError,
                     "null ImagePoint passed to ImagePoint::setCoordinates");
     x_ = thePt->x_;
     y_ = thePt->y_;
 }
void ImagePoint::setCoordinates (const ImagePoint & thePt) virtual
Assigns new coordinates to the pixel.
Parameters
thePt reference to the ImagePoint object to copy
Reimplemented in uriVL::ImagePoint_F.
Definition at line 179 of file ImagePoint.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, x_, and y_.
 {
         try {
                 x_ = thePt.x_;
                 y_ = thePt.y_;
         }
         catch(...) {
             FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "invalid ImagePoint reference passed to ImagePoint::setCoordinates");
         }
 }
void ImagePoint::setX (int val) virtual
Assigns new x coordinate to the pixel.
Parameters
val new x coordinate for the point
Reimplemented in uriVL::ImagePoint_F.
Definition at line 143 of file ImagePoint.cpp.
References x_.
Referenced by uriVL::BlobFinder::findBlobAbout(), uriVL::ImageRect::setCenter(), uriVL::ImagePoint_F::setCoordinates(), and uriVL::BlobFinder::spiralSearch_().
 {
     x_ = theX;
 }
void ImagePoint::setY (int val) virtual
Assigns new y coordinate to the pixel.
Parameters
val new y coordinate for the point
Reimplemented in uriVL::ImagePoint_F.
Definition at line 148 of file ImagePoint.cpp.
References y_.
Referenced by uriVL::BlobFinder::findBlobAbout(), uriVL::ImageRect::setCenter(), uriVL::ImagePoint_F::setCoordinates(), and uriVL::BlobFinder::spiralSearch_().
 {
     y_ = theY;
 }
void ImagePoint::shiftX (int dx) virtual
Shifts the existing x coordinate by the amount specified.
Parameters
dx a positive or negative x displacement
Reimplemented in uriVL::ImagePoint_F.
Definition at line 201 of file ImagePoint.cpp.
References x_.
Referenced by mySpecialKeys().
 {
     x_ += dx;
 }
void ImagePoint::shiftY (int dy) virtual
Shifts the existing y coordinate by the amount specified.
Parameters
dy a positive or negative y displacement
Reimplemented in uriVL::ImagePoint_F.
Definition at line 206 of file ImagePoint.cpp.
References y_.
Referenced by mySpecialKeys().
 {
     y_ += dy;
 }
void ImagePoint::translate (int dx, int dy) virtual
Shifts the existing x and y coordinates by the amount specified.
Parameters
dx a positive or negative x displacement
dy a positive or negative y displacement
Reimplemented in uriVL::ImagePoint_F.
Definition at line 211 of file ImagePoint.cpp.
References x_, and y_.
Referenced by uriVL::ImageRect::ImageRect().
 {
     x_ += dx;
     y_ += dy;
 }
Friends And Related Function Documentation
friend class ImagePoint_F friend
Definition at line 236 of file ImagePoint.h.
Member Data Documentation
int uriVL::ImagePoint::id_ private
The point's id.
Definition at line 228 of file ImagePoint.h.
Referenced by getID().
int ImagePoint::ptCounter_ = 0 static private
Class variable used to attribute a unique id to each Point object.
Definition at line 232 of file ImagePoint.h.
int uriVL::ImagePoint::x_ private
The point's x coordinate.
Definition at line 217 of file ImagePoint.h.
Referenced by getX(), operator=(), rotate(), uriVL::ImagePoint_F::rotate(), setCoordinates(), uriVL::ImagePoint_F::setCoordinates(), setX(), uriVL::ImagePoint_F::setX(), shiftX(), uriVL::ImagePoint_F::shiftX(), translate(), and uriVL::ImagePoint_F::translate().
int uriVL::ImagePoint::y_ private
The point's y coordinate.
Definition at line 222 of file ImagePoint.h.
Referenced by getY(), operator=(), rotate(), uriVL::ImagePoint_F::rotate(), setCoordinates(), uriVL::ImagePoint_F::setCoordinates(), setY(), uriVL::ImagePoint_F::setY(), shiftY(), uriVL::ImagePoint_F::shiftY(), translate(), and uriVL::ImagePoint_F::translate().
The documentation for this class was generated from the following files:
ImagePoint.h
ImagePoint.cpp