URIVisionLibrary: uriVL::ImageGradient_Sobel Class Reference
uriVL::ImageGradient_Sobel Class Reference
Vector operator that computes the gradient of a raster image using Sobel-like masks.
#include <ImageGradient_Sobel.h>
Public Member Functions
ImageGradient_Sobel (void)
Default constructor.
~ImageGradient_Sobel (void)
Destructor.
float getScale (void) const
Implements the pure virtual function defined in the parent class to return the value 0.6f (or width/5 = 3/5.f) even though this is not really the "scale" of anything, just an analogy to the Gaussian version.
VectorField * applyTo (const RasterImage *imgIn)
Applies this operator to an image, returns the result as a VectorField.
VectorField * applyTo (const RasterImage *imgIn, const ImageRect *theRect)
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
void applyInto (const RasterImage *imgIn, VectorField *vectOut)
Applies this operator to a RasterImage and writes the result into a VectorField received as second parameter.
void applyInto (const RasterImage *imgIn, const ImageRect *theRect, VectorField *vectOut)
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
Public Member Functions inherited from uriVL::ImageGradient
virtual ~ImageGradient (void)
Destructor.
Public Member Functions inherited from uriVL::VectorOperator
virtual ~VectorOperator (void)
Destructor.
bool isIntegerOperator (void) const
returns true if the filter is an "integer" operator
bool isFloatOperator (void) const
returns true if the filter is a "float" operator
const ImageRect * getRect (void) const
Returns a pointer to this operator's operation rectangle.
int getWidth (void) const
Returns the width of this operator's operation rectangle.
int getHeight (void) const
Returns the height of this operator's operation rectangle.
Private Member Functions
void applyIntoF_ (const RasterImage_gray_F *imgIn, const ImageRect *theRect, VectorField_F *vectOut)
Effectively implements the Sobel gradient mask on a float gray-level image and writes the results in a float vector field.
void applyIntoF_ (const RasterImage_gray_F *imgIn, const ImageRect *theRect, VectorField_I *vectOut)
Effectively implements the Sobel gradient mask on a float gray-level image and writes the results in an integer vector field.
void applyIntoI_ (const RasterImage_gray *imgIn, const ImageRect *theRect, VectorField_F *vectOut)
Effectively implements the Sobel gradient mask on an "integer" gray-level image and writes the results in a float vector field.
void applyIntoI_ (const RasterImage_gray *imgIn, const ImageRect *theRect, VectorField_I *vectOut)
Effectively implements the Sobel gradient mask on an "integer" gray-level image and writes the results in an integer vector field.
Additional Inherited Members
Protected Member Functions inherited from uriVL::ImageGradient
ImageGradient (int theWidth, bool isIntOperator)
Creates an ImageGradient operator with the specified width.
ImageGradient (int theWidth, const ImageRect *theRect, bool isIntOperator)
Creates an ImageGradient operator with the specified width and a temporary raster at the specified dimensions.
ImageGradient (const ImageGradient &obj)
Copy constructor (disabled)
bool allocateTempRaster_ (const ImageRect *rect)
Allocates the temporary raster associated with this object.
void freeTempRaster_ (void)
Frees the temporary raster associated with this object.
float *const * getShiftedTempGrayF2D_ (ReadWriteStatus rw)
Gives writing access to the shifted 2D gray temp raster.
Protected Member Functions inherited from uriVL::VectorOperator
VectorOperator (bool isIntOperator=false)
Constructor.
VectorOperator (const ImageRect *theRect, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (int theLeft, int theTop, int theWidth, int theHeight, bool isIntOperator=false)
Sets the image rectangle this operator will work on.
VectorOperator (const VectorOperator &obj)
Copy constructor (disabled)
void setRect (const ImageRect *theRect)
Sets the rectangle on which this operator uh...
void setRect (int theLeft, int theTop, int theWidth, int theHeight)
Sets the rectangle on which this operator uh...
Detailed Description
Vector operator that computes the gradient of a raster image using Sobel-like masks.
Objects of this class only operate on gray-level images. If a color image is sent as parameter, it gets converted to a gray-level image first. For operation on color images, see ColorImageGradient subclasses.
@author jean-yves herve', 3D Group,
                        Department of Computer Science and Statistics,
                        University of Rhode Island
Definition at line 37 of file ImageGradient_Sobel.h.
Constructor & Destructor Documentation
ImageGradient_Sobel::ImageGradient_Sobel (void)
Default constructor.
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
Definition at line 29 of file ImageGradient_Sobel.cpp.
                         :       ImageGradient(1, true)
 {
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by ImageGradient_Sobel constructor");
         throw e;
 }
ImageGradient_Sobel::~ImageGradient_Sobel (void)
Destructor.
Definition at line 39 of file ImageGradient_Sobel.cpp.
 {
 }
Member Function Documentation
void ImageGradient_Sobel::applyInto (const RasterImage * imgIn, VectorField * vectOut) virtual
Applies this operator to a RasterImage and writes the result into a VectorField received as second parameter.
Parameters
imgIn the RasterImage to which the operator is applied
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 105 of file ImageGradient_Sobel.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRasterImageError, and uriVL::kNullVectorFieldError.
Referenced by applyTo(), and myMenu3().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( vectOut == NULL,
                     kNullVectorFieldError,
                     "null VectorField passed as destination to ImageGradient_Sobel::applyInto");
     applyInto(imgIn, imgIn->getValidRect(), vectOut);
 }
void ImageGradient_Sobel::applyInto (const RasterImage * imgIn, const ImageRect * theRect, VectorField * vectOut) virtual
Applies this operator to a RasterImage within the rectangle specified and writes the result into the VectorField received as parameter.
If the input image was not a gray-level image, then a local grey-level copy is first made, then the operator is applied.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Implements uriVL::VectorOperator.
Definition at line 117 of file ImageGradient_Sobel.cpp.
References applyIntoF_(), applyIntoI_(), uriVL::DrawableObject2D::contains(), FAIL_CONDITION, uriVL::VectorField::forceRasterUpdate(), uriVL::DrawableObject2D::getValidRect(), grayImg, uriVL::VectorField::hasFloatRaster(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kNullRasterImageError, uriVL::kNullRectangleError, uriVL::kNullVectorFieldError, uriVL::RasterImage_gray::localRasterGray(), uriVL::ImageRect::removeAllAround(), uriVL::DrawableObject2D::setBoundRect(), uriVL::VectorField::setRasterAsReference(), and uriVL::DrawableObject2D::setValidRect().
 {
     //----------------------------------------------------------------
     //  STEP 0:         Test for null or invalid type parameters
     //----------------------------------------------------------------
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in VectorField_F::copyInto");
     FAIL_CONDITION(     vectOut == NULL,
                     kNullVectorFieldError,
                     "NULL output vector field passed as parameter");
     //----------------------------------------------------------------
     //  STEP 1:         Test for rectangle intersection
     //----------------------------------------------------------------
     //  determine the output rectangle that the input image can produce.
     //          Here, because we apply a filter of width&height (2m+1), we
     //          "lose 1 all around".
     ImageRect   *usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     //  ... and determine its intersection with the user-specified output rectangle
     ImageRect   *destRect = ImageRect::intersection(theRect, usableRect);
     delete usableRect;
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     //  if the output field does not contain the destination rect, it must be resized.
     if (!vectOut->contains(destRect))
         vectOut->setBoundRect(destRect);
     //----------------------------------------------------------------
     //  STEP 2:         Operate only on a gray-level image
     //----------------------------------------------------------------
     bool localGray;
     const RasterImage_gray      *grayImg = RasterImage_gray::localRasterGray(imgIn, &localGray);
     //----------------------------------------------------------------
     //  STEP 3:         Perform the calculations
     //----------------------------------------------------------------
     //  There are 4 cases, depending on the presence of a float raster
     //  in the input and the destination
     if (grayImg->hasFloatRaster())
         if (vectOut->hasFloatRaster())
             applyIntoF_(static_cast<const RasterImage_gray_F*>(grayImg), destRect,
                         static_cast<VectorField_F*>(vectOut));
         else
             applyIntoF_(static_cast<const RasterImage_gray_F*>(grayImg), destRect,
                         static_cast<VectorField_I*>(vectOut));
     else
         if (vectOut->hasFloatRaster())
             applyIntoI_(grayImg, destRect, static_cast<VectorField_F*>(vectOut));
         else
             applyIntoI_(grayImg, destRect, static_cast<VectorField_I*>(vectOut));
     //----------------------------------------------------------------
     //  STEP 4:         Set rectangle
     //----------------------------------------------------------------
     //  Very important:  At the end of the computation, don't forget to set the
     //  output's valid data rectangle.  In "safe" mode, the library has no way to guess
     //  what the valid data rectangle should be and sets it to its minimum value... empty
     vectOut->setValidRect(destRect);
     vectOut->setRasterAsReference();
     vectOut->forceRasterUpdate();
     //----------------------------------------------------------------
     //  STEP 5:         Free temporary storage (if needed)
     //----------------------------------------------------------------
     if (localGray)
         delete grayImg;
     delete destRect;
 }
void ImageGradient_Sobel::applyIntoF_ (const RasterImage_gray_F * imgIn, const ImageRect * theRect, VectorField_F * vectOut) private
Effectively implements the Sobel gradient mask on a float gray-level image and writes the results in a float vector field.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 205 of file ImageGradient_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     const int   iLow  = theRect->getTop(),
             iHigh = theRect->getBottom(),
             jLow = theRect->getLeft(),
             jHigh = theRect->getRight();
     int i, im1, ip1, j, jm1, jp1;
     const float* const* fGray = grayImg->getShiftedGrayF2D();
     float   **fvx = (float**) (vectOut->getShiftedRasterX2D(R_W_ACCESS));
     float   **fvy = (float**) (vectOut->getShiftedRasterY2D(R_W_ACCESS));
     //  compute convolution over the processing rectangle
     im1 = iLow-1;
     ip1 = iLow+1;
     for (i=iLow; i<=iHigh; i++)
     {
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             fvx[i][j] = 0.25f*(fGray[i][jp1] - fGray[i][jm1]) +
                         0.125f*((fGray[im1][jp1] - fGray[im1][jm1]) +
                                 (fGray[ip1][jp1] - fGray[ip1][jm1]));
             fvy[i][j] = 0.25f*(fGray[ip1][j] - fGray[im1][j]) +
                         0.125f*((fGray[ip1][jp1] - fGray[im1][jp1]) +
                                 (fGray[ip1][jm1] - fGray[im1][jm1]));
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
         }
         //  shift the i indexes (i itself is taken care of in the loop
         //  statement)
         im1 = i;
         ip1++;
     }
 }
void ImageGradient_Sobel::applyIntoF_ (const RasterImage_gray_F * imgIn, const ImageRect * theRect, VectorField_I * vectOut) private
Effectively implements the Sobel gradient mask on a float gray-level image and writes the results in an integer vector field.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 248 of file ImageGradient_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
 {
     int iLow  = theRect->getTop(),
         iHigh = theRect->getBottom(),
         jLow = theRect->getLeft(),
         jHigh = theRect->getRight(),
         i, im1, ip1, j, jm1, jp1;
     const float* const* fGray = grayImg->getShiftedGrayF2D();
     int   **vx = (int**) (vectOut->getShiftedRasterX2D(R_W_ACCESS));
     int   **vy = (int**) (vectOut->getShiftedRasterY2D(R_W_ACCESS));
     //  compute convolution over the processing rectangle
     im1 = iLow-1;
     ip1 = iLow+1;
     for (i=iLow; i<=iHigh; i++)
     {
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             vx[i][j] = static_cast<int>(0.25f*(fGray[i][jp1] - fGray[i][jm1]) +
                                         0.125f*((fGray[im1][jp1] - fGray[im1][jm1]) +
                                                 (fGray[ip1][jp1] - fGray[ip1][jm1])));
             vy[i][j] = static_cast<int>(0.25f*(fGray[ip1][j] - fGray[im1][j]) +
                                         0.125f*((fGray[ip1][jp1] - fGray[im1][jp1]) +
                                                 (fGray[ip1][jm1] - fGray[im1][jm1])));
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
         }
         //  shift the i indexes (i itself is taken care of in the loop
         //  statement)
         im1 = i;
         ip1++;
     }
 }
void ImageGradient_Sobel::applyIntoI_ (const RasterImage_gray * imgIn, const ImageRect * theRect, VectorField_F * vectOut) private
Effectively implements the Sobel gradient mask on an "integer" gray-level image and writes the results in a float vector field.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 291 of file ImageGradient_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::VectorField_F::getShiftedRasterX2D(), uriVL::VectorField_F::getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
Referenced by applyInto().
 {
     int iLow  = theRect->getTop(),
         iHigh = theRect->getBottom(),
         jLow = theRect->getLeft(),
         jHigh = theRect->getRight(),
         i, im1, ip1, j, jm1, jp1;
     const unsigned char* const* iGray = grayImg->getShiftedGray2D();
     float   **fvx = (float**) (vectOut->getShiftedRasterX2D(R_W_ACCESS));
     float   **fvy = (float**) (vectOut->getShiftedRasterY2D(R_W_ACCESS));
     //  compute convolution over the processing rectangle
     im1 = iLow-1;
     ip1 = iLow+1;
     for (i=iLow; i<=iHigh; i++)
     {
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             fvx[i][j] = 0.25f*(iGray[i][jp1] - iGray[i][jm1]) +
                         0.125f*((iGray[im1][jp1] - iGray[im1][jm1]) +
                                 (iGray[ip1][jp1] - iGray[ip1][jm1]));
             fvy[i][j] = 0.25f*(iGray[ip1][j] - iGray[im1][j]) +
                         0.125f*((iGray[ip1][jp1] - iGray[im1][jp1]) +
                                 (iGray[ip1][jm1] - iGray[im1][jm1]));
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
         }
         //  shift the i indexes (i itself is taken care of in the loop
         //  statement)
         im1 = i;
         ip1++;
     }
 }
void ImageGradient_Sobel::applyIntoI_ (const RasterImage_gray * imgIn, const ImageRect * theRect, VectorField_I * vectOut) private
Effectively implements the Sobel gradient mask on an "integer" gray-level image and writes the results in an integer vector field.
Parameters
imgIn the RasterImage to which the operator is applied
theRect the rectangle within which to apply the filter
vectOut the VectorField into which the output is written
Definition at line 335 of file ImageGradient_Sobel.cpp.
References uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage::getShiftedRaster2D(), uriVL::VectorField_I::getShiftedRasterX2D(), uriVL::VectorField_I::getShiftedRasterY2D(), uriVL::ImageRect::getTop(), and uriVL::R_W_ACCESS.
 {
     int iLow  = theRect->getTop(),
         iHigh = theRect->getBottom(),
         jLow = theRect->getLeft(),
         jHigh = theRect->getRight(),
         i, im1, ip1, j, jm1, jp1;
     const unsigned char* const* iGray = grayImg->getShiftedRaster2D();
     int** vx = (int**) (vectOut->getShiftedRasterX2D(R_W_ACCESS));
     int** vy = (int**) (vectOut->getShiftedRasterY2D(R_W_ACCESS));
     //  compute convolution over the processing rectangle
     im1 = iLow-1;
     ip1 = iLow+1;
     for (i=iLow; i<=iHigh; i++)
     {
         jm1 = jLow-1;
         jp1 = jLow+1;
         for (j=jLow; j<=jHigh; j++)
         {
             vx[i][j] = (2*(iGray[i][jp1] - iGray[i][jm1]) +
                         (iGray[im1][jp1] - iGray[im1][jm1]) +
                         (iGray[ip1][jp1] - iGray[ip1][jm1]))/8;
             vy[i][j] = (2*(iGray[ip1][j] - iGray[im1][j]) +
                         (iGray[ip1][jp1] - iGray[im1][jp1]) +
                         (iGray[ip1][jm1] - iGray[im1][jm1]))/8;
             //  shift the j indexes (j itself is taken care of in the loop
             //  statement)
             jm1 = j;
             jp1++;
         }
         //  shift the i indexes (i itself is taken care of in the loop
         //  statement)
         im1 = i;
         ip1++;
     }
 }
VectorField * ImageGradient_Sobel::applyTo (const RasterImage * imgIn) virtual
Applies this operator to an image, returns the result as a VectorField.
Since the operator is an "integer" operator, then the VectorField returned should have the type matching that of the input image
Parameters
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 66 of file ImageGradient_Sobel.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     return applyTo(imgIn, imgIn->getValidRect());
 }
VectorField * ImageGradient_Sobel::applyTo (const RasterImage * imgIn, const ImageRect * theRect) virtual
Applies this operator to an image within the rectangle specified and returns the result as a VectorField.
This function will be overloaded by subclasses of VectorOperator. These subclasses should follow the following rules:
if the operator is an "integer" operator, then the RasterImage returned should have the same type as the input image
if the operator is a "float" or "double" operator, then the RasterImage returned should be of the "float" form of the input image. For example, if imgIn was RasterImage_Gray, then the image returned should be RasterImage_Gray_F.
Parameters
theRect the rectangle within which to apply the filter
imgIn the RasterImage to which the operator is applied
Returns
the VectorField obtained by applying the operator to imgIn
Implements uriVL::VectorOperator.
Definition at line 75 of file ImageGradient_Sobel.cpp.
References applyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::hasFloatRaster(), uriVL::ImageRect::intersection(), uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::ImageRect::removeAllAround().
 {
     FAIL_CONDITION(     imgIn == NULL,
                     kNullRasterImageError,
                     "NULL input raster image passed as parameter");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in ImageGradient_Sobel::ApplyTo");
     ImageRect   *usableRect = new ImageRect(imgIn->getValidRect());
     usableRect->removeAllAround(1);
     ImageRect   *destRect = ImageRect::intersection(usableRect, theRect);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "Destination rectangle does not intersect valid data rectangle");
     VectorField         *vectOut;
     if (imgIn->hasFloatRaster())
         vectOut = new VectorField_F(destRect);
     else
         vectOut = new VectorField_I(destRect);
     applyInto(imgIn, theRect, vectOut);
     delete destRect;
     delete usableRect;
     return vectOut;
 }
float ImageGradient_Sobel::getScale (void) const virtual
Implements the pure virtual function defined in the parent class to return the value 0.6f (or width/5 = 3/5.f) even though this is not really the "scale" of anything, just an analogy to the Gaussian version.
Returns
0.6f
Implements uriVL::ImageGradient.
Definition at line 52 of file ImageGradient_Sobel.cpp.
 {
     return 0.6f;
 }
The documentation for this class was generated from the following files:
ImageGradient_Sobel.h
ImageGradient_Sobel.cpp