URIVisionLibrary: uriVL::BackgroundRemover Class Reference
uriVL::BackgroundRemover Class Reference abstract
BackgroundRemover is an abstract class (with pure virtual member function) Inherited by BackgroundRemover_static, BackgroundRemover_dynamic.
#include <BackgroundRemover.h>
Public Member Functions
BackgroundRemover (void)
Default constructor.
virtual ~BackgroundRemover (void)
Destructor.
virtual void setBackground (RasterImage *img)=0
Different implementations between BackgroundRemover_static & BackgroundRemover_dynamic.
RasterImage_gray * removeBackground (RasterImage *imgIn)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images)
RasterImage_gray * removeBackground (RasterImage *imgIn, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images) into a gray-level raster image received as parameter.
void removeBackground (RasterImage *imgIn, RasterImage_gray *imgOut, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background into a gray-level raster image received as parameter.
void setColorDifferenceMode (ColorDifferenceMode mode)
Sets the default color difference mode for this object.
RasterImage * getBackground (void)
get background_;
ColorDifferenceMode getColorDifferenceMode (void)
Reports what is the color difference mode for this object.
Protected Member Functions
void assignBackground_ (RasterImage *img)
Private Member Functions
BackgroundRemover (const BackgroundRemover &obj)
Copy constructor disabled.
const BackgroundRemover & operator= (const BackgroundRemover &obj)
Copy operator disabled.
Private Attributes
RasterImage * background_
Stores the raster image used as background.
ColorDifferenceMode mode_
Default color difference mode for this object.
Detailed Description
BackgroundRemover is an abstract class (with pure virtual member function) Inherited by BackgroundRemover_static, BackgroundRemover_dynamic.
Definition at line 38 of file BackgroundRemover.h.
Constructor & Destructor Documentation
BackgroundRemover::BackgroundRemover (void)
Default constructor.
Definition at line 28 of file BackgroundRemover.cpp.
         :       background_(NULL),
                 mode_(MAX_DIFFERENCE)    //     default color difference mode
 {
 }
BackgroundRemover::~BackgroundRemover (void) virtual
Destructor.
Definition at line 47 of file BackgroundRemover.cpp.
References background_.
 {
     if (background_ != NULL)
         delete background_;
 }
BackgroundRemover::BackgroundRemover (const BackgroundRemover & obj) private
Copy constructor disabled.
Parameters
obj the object to copy
Definition at line 35 of file BackgroundRemover.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       background_(NULL),
                 mode_(MAX_DIFFERENCE)    //     default color difference mode
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "BackgroundRemover copy constructor disabled");
 }
Member Function Documentation
void BackgroundRemover::assignBackground_ (RasterImage * img) protected
Definition at line 79 of file BackgroundRemover.cpp.
References background_, uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::RasterImage::floatRasterIsReference(), uriVL::RasterImage::getBaseRasterType(), uriVL::RasterImage::hasFloatRaster(), uriVL::kGrayRaster, uriVL::kNullRasterImageError, uriVL::kRasterImageError, uriVL::kRGB24Raster, and uriVL::kRGBa32Raster.
Referenced by uriVL::BackgroundRemover_static::setBackground().
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "null RasterImage as parameter in BackgroundRemover::setBackground");
     switch (img->getBaseRasterType())
     {
         case kGrayRaster:
             if(background_ != NULL)
{
                 if (background_->getBaseRasterType() == kGrayRaster)
                 {
                     if (img->hasFloatRaster() && img->floatRasterIsReference() &&
                             !background_->hasFloatRaster())
                     {
                         delete background_;
                         background_ = NULL;
                     }
                     else
                         img->copyInto(background_);
                 }
                 else
                 {
                     delete background_;
                     background_ = NULL;
                 }
                         }
             if(background_ == NULL)
{
                 if (img->hasFloatRaster() && img->floatRasterIsReference())
                     background_ = new RasterImage_gray_F(img);
                 else
                     background_ = new RasterImage_gray(img);
                         }
             break;
         case kRGB24Raster:
             if(background_ != NULL)
{
                 if (background_->getBaseRasterType() == kRGB24Raster)
                     img->copyInto(background_);
                 else
                 {
                     delete background_;
                     background_ = NULL;
                 }
                         }
             if(background_ == NULL)
                 background_ = new RasterImage_RGBa(img);
             break;
         case kRGBa32Raster:
             if(background_ != NULL)
{
                 if (background_->getBaseRasterType() == kRGBa32Raster)
                     img->copyInto(background_);
                 else
                 {
                     delete background_;
                     background_ = NULL;
                 }
                         }
             if(background_ == NULL)
                 background_ = new RasterImage_RGBa(img);
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in BackgroundRemover_static::setBackground");
             break;
     }
 }
RasterImage * BackgroundRemover::getBackground (void)
get background_;
Definition at line 67 of file BackgroundRemover.cpp.
References background_.
Referenced by uriVL::PatternTracker2DController::action(), and uriVL::PatternTracker2DController::getCurrentBackground().
 {
         return background_;
 }
ColorDifferenceMode BackgroundRemover::getColorDifferenceMode (void)
Reports what is the color difference mode for this object.
Returns
the color difference mode for this object
Definition at line 72 of file BackgroundRemover.cpp.
References mode_.
 {
     return mode_;
 }
const BackgroundRemover & BackgroundRemover::operator= (const BackgroundRemover & obj) private
Copy operator disabled.
Parameters
obj the object to copy
Definition at line 54 of file BackgroundRemover.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "BackgroundRemover copy operator disabled");
     return *this;
 }
RasterImage_gray * BackgroundRemover::removeBackground (RasterImage * imgIn)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images)
Parameters
imgIn input image
Returns
the difference |imgIn - background|
Definition at line 172 of file BackgroundRemover.cpp.
References background_, uriVL::ImageArithmetics::difference(), FAIL_CONDITION, uriVL::kNullRasterImageError, and mode_.
Referenced by uriVL::BlobTracker2DController::action(), and uriVL::PatternTracker2D::mergeBlob_().
 {
     FAIL_CONDITION( background_ == NULL,
                     kNullRasterImageError,
                     "Background was not set properly for this object");
     return ImageArithmetics::difference(imgIn, background_, mode_);
 }
RasterImage_gray * BackgroundRemover::removeBackground (RasterImage * imgIn, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background.
Parameters
imgIn input image
mode indicates the algorithm used to compute the difference between two color values
Returns
the difference |imgIn - background|
Definition at line 182 of file BackgroundRemover.cpp.
References background_, uriVL::ImageArithmetics::difference(), FAIL_CONDITION, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( background_ == NULL,
                     kNullRasterImageError,
                     "Background was not set properly for this object");
     return ImageArithmetics::difference(imgIn, background_, mode);
 }
void BackgroundRemover::removeBackground (RasterImage * imgIn, RasterImage_gray * imgOut)
Computes the difference between this raster image and the one stored as background (using the default mode if the input images are color images) into a gray-level raster image received as parameter.
Parameters
imgIn input image
imgOut the difference |imgIn - background|
Definition at line 192 of file BackgroundRemover.cpp.
References background_, uriVL::ImageArithmetics::difference(), FAIL_CONDITION, uriVL::kNullRasterImageError, and mode_.
 {
     FAIL_CONDITION( background_ == NULL,
                     kNullRasterImageError,
                     "Background was not set properly for this object");
     ImageArithmetics::difference(imgIn, background_, imgOut, mode_);
 }
void BackgroundRemover::removeBackground (RasterImage * imgIn, RasterImage_gray * imgOut, ColorDifferenceMode mode)
Computes the difference between this raster image and the one stored as background into a gray-level raster image received as parameter.
Parameters
imgIn input image
mode indicates the algorithm used to compute the difference between two color values
imgOut the difference |imgIn - background|
Definition at line 201 of file BackgroundRemover.cpp.
References background_, uriVL::ImageArithmetics::difference(), FAIL_CONDITION, and uriVL::kNullRasterImageError.
 {
     FAIL_CONDITION( background_ == NULL,
                     kNullRasterImageError,
                     "Background was not set properly for this object");
     ImageArithmetics::difference(imgIn, background_, imgOut, mode);
 }
virtual void uriVL::BackgroundRemover::setBackground (RasterImage * img) pure virtual
Different implementations between BackgroundRemover_static & BackgroundRemover_dynamic.
Stores a copy of img to use as background for future image difference computations
Parameters
img raster image to store as background image
Implemented in uriVL::BackgroundRemover_static, uriVL::BackgroundRemover_dynamic_MW, and uriVL::BackgroundRemover_dynamic.
void BackgroundRemover::setColorDifferenceMode (ColorDifferenceMode mode)
Sets the default color difference mode for this object.
See also
mode_
Definition at line 160 of file BackgroundRemover.cpp.
References mode_.
Referenced by uriVL::BackgroundRemover_static::BackgroundRemover_static().
 {
     mode_ = mode;
 }
Member Data Documentation
RasterImage* uriVL::BackgroundRemover::background_ private
Stores the raster image used as background.
Definition at line 120 of file BackgroundRemover.h.
Referenced by assignBackground_(), getBackground(), removeBackground(), uriVL::BackgroundRemover_dynamic_MW::updateBackground(), uriVL::BackgroundRemover_dynamic_MW::updateBackground_(), and ~BackgroundRemover().
ColorDifferenceMode uriVL::BackgroundRemover::mode_ private
Default color difference mode for this object.
Definition at line 124 of file BackgroundRemover.h.
Referenced by getColorDifferenceMode(), removeBackground(), and setColorDifferenceMode().
The documentation for this class was generated from the following files:
BackgroundRemover.h
BackgroundRemover.cpp