URIVisionLibrary: uriVL::Pattern2DMatchRecord_part Class Reference
uriVL::Pattern2DMatchRecord_part Class Reference
Holds the records of a 2D matching result (matching performed by a "partial match" matcher).
#include <Pattern2DMatchRecord_part.h>
Public Member Functions
Pattern2DMatchRecord_part (void)
Default constructor.
~Pattern2DMatchRecord_part (void)
Destructor.
Pattern2DMatchRecord * getMatchRecord (QuadrantIndex quad)
Returns the matchng record of a specific quadrant.
float getScore (QuadrantIndex quad)
Returns the score of the best match found.
ImagePoint * getBestMatch (QuadrantIndex quad)
Returns the location of the best match.
void setScore (QuadrantIndex quad, float score)
Sets the score.
void setBestMatch (QuadrantIndex quad, int x, int y)
Sets the coordinates of the best match.
void setBestMatch (QuadrantIndex quad, ImagePoint *bestMatch)
Sets the coordinates of the best match.
Public Member Functions inherited from uriVL::Pattern2DMatchRecord
Pattern2DMatchRecord (void)
Default constructor.
Pattern2DMatchRecord (const ImagePoint *bestMatch, float score)
Creates a new match record with the best matching point and score specified.
Pattern2DMatchRecord (int x, int y, float score)
Creates a new match record with the best matching point and score specified.
~Pattern2DMatchRecord (void)
Destructor.
float getScore (void)
Returns the score of the best match found.
ImagePoint * getBestMatch (void)
Returns the location of the best match.
void setScore (float score)
Sets the score.
void setBestMatch (int x, int y)
Sets the coordinates of the best match.
void setBestMatch (const ImagePoint *bestMatch)
Sets the coordinates of the best match.
const std::string getRecordType (void) const
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Protected Attributes
Pattern2DMatchRecord ** quadMatch_
Matching records for the 4 quadrants.
Protected Attributes inherited from uriVL::Pattern2DMatchRecord
ImagePoint * bestMatch_
best matching point
float score_
confidence score
bool isSubpixelMatch_
Indicates whether the match was calculated with subpixel accuracy (false by default)
std::string recordType_
Temporary solution until I understand why polymorphism doesn't seem to be working with the Pattern2DMatchRecord class hierarchy.
Detailed Description
Holds the records of a 2D matching result (matching performed by a "partial match" matcher).
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 32 of file Pattern2DMatchRecord_part.h.
Constructor & Destructor Documentation
Pattern2DMatchRecord_part::Pattern2DMatchRecord_part (void)
Default constructor.
Definition at line 21 of file Pattern2DMatchRecord_part.cpp.
References uriVL::Pattern2DMatchRecord::Pattern2DMatchRecord(), quadMatch_, and uriVL::Pattern2DMatchRecord::recordType_.
     :   Pattern2DMatchRecord()
 {
     quadMatch_ = new Pattern2DMatchRecord*[4];
     for (int i=0; i<4; i++)
         quadMatch_[i] = new Pattern2DMatchRecord();
         recordType_ = "partial match record";
 }
Pattern2DMatchRecord_part::~Pattern2DMatchRecord_part (void)
Destructor.
Definition at line 32 of file Pattern2DMatchRecord_part.cpp.
References quadMatch_.
 {
     for (int i=0; i<4; i++)
         delete quadMatch_[i];
     delete []quadMatch_;
 }
Member Function Documentation
ImagePoint * Pattern2DMatchRecord_part::getBestMatch (QuadrantIndex quad)
Returns the location of the best match.
Parameters
quad index of the quadrant of which we want the best match's score
Definition at line 58 of file Pattern2DMatchRecord_part.cpp.
References uriVL::Pattern2DMatchRecord::getBestMatch(), and quadMatch_.
 {
     return quadMatch_[quad]->getBestMatch();
 }
Pattern2DMatchRecord * Pattern2DMatchRecord_part::getMatchRecord (QuadrantIndex quad)
Returns the matchng record of a specific quadrant.
Parameters
quad index of the quadrant of which we want the matching record
Definition at line 48 of file Pattern2DMatchRecord_part.cpp.
References quadMatch_.
Referenced by performMatching().
 {
     return quadMatch_[quad];
 }
float Pattern2DMatchRecord_part::getScore (QuadrantIndex quad)
Returns the score of the best match found.
Parameters
quad index of the quadrant of which we want the best match's score
Definition at line 53 of file Pattern2DMatchRecord_part.cpp.
References uriVL::Pattern2DMatchRecord::getScore(), and quadMatch_.
 {
     return quadMatch_[quad]->getScore();
 }
void Pattern2DMatchRecord_part::setBestMatch (QuadrantIndex quad, int x, int y)
Sets the coordinates of the best match.
Parameters
quad index of the quadrant for which to set the best match
x new x coordinate for this record's best match point
y new y coordinate for this record's best match point
Definition at line 70 of file Pattern2DMatchRecord_part.cpp.
References quadMatch_, and uriVL::Pattern2DMatchRecord::setBestMatch().
Referenced by uriVL::PatternMatcher2D_partCorr::match_().
 {
     quadMatch_[quad]->setBestMatch(x, y);
 }
void Pattern2DMatchRecord_part::setBestMatch (QuadrantIndex quad, ImagePoint * bestMatch)
Sets the coordinates of the best match.
Parameters
quad index of the quadrant for which to set the best match
bestMatch new best match point for this record
Definition at line 75 of file Pattern2DMatchRecord_part.cpp.
References quadMatch_, and uriVL::Pattern2DMatchRecord::setBestMatch().
 {
     quadMatch_[quad]->setBestMatch(bestMatch);
 }
void Pattern2DMatchRecord_part::setScore (QuadrantIndex quad, float score)
Sets the score.
Parameters
quad index of the quadrant for which to set the best match's score
score the new score for this record
Definition at line 64 of file Pattern2DMatchRecord_part.cpp.
References quadMatch_, and uriVL::Pattern2DMatchRecord::setScore().
Referenced by uriVL::PatternMatcher2D_partCorr::match_().
 {
     quadMatch_[quad]->setScore(score);
 }
Member Data Documentation
Pattern2DMatchRecord* * uriVL::Pattern2DMatchRecord_part::quadMatch_ protected
Matching records for the 4 quadrants.
Definition at line 85 of file Pattern2DMatchRecord_part.h.
Referenced by getBestMatch(), getMatchRecord(), getScore(), Pattern2DMatchRecord_part(), setBestMatch(), setScore(), and ~Pattern2DMatchRecord_part().
The documentation for this class was generated from the following files:
Pattern2DMatchRecord_part.h
Pattern2DMatchRecord_part.cpp