URIVisionLibrary: uriVL::HalfCylinder3D Class Reference
uriVL::HalfCylinder3D Class Reference
HalfCylinder3D class.
#include <HalfCylinder3D.h>
Public Member Functions
HalfCylinder3D (GLfloat *origin, GLfloat **axes, bool LengthSideIsClosed, bool sidesAreClosed)
Constructor.
HalfCylinder3D (GLfloat *origin, GLfloat *dirAxis, GLfloat radius, bool LengthSideIsClosed, bool sidesAreClosed)
Constructor.
~HalfCylinder3D (void)
Destructor.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::TubularSection3D
TubularSection3D (GLfloat *origin, GLfloat **axes, GLfloat theta0, GLfloat thetaf)
Constructor.
TubularSection3D (GLfloat *origin, GLfloat *dirAxis, GLfloat radius, GLfloat theta0, GLfloat thetaf)
Constructor.
~TubularSection3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
HalfCylinder3D (const HalfCylinder3D &obj)
Copy constructor (disabled)
const HalfCylinder3D & operator= (const HalfCylinder3D &obj)
Copy operator: disabled.
void init_ (GLfloat **axes)
Initialize the half-cylinder.
Private Attributes
GLfloat normalTop_ [3]
Normal to the top face.
GLfloat normalBottom_ [3]
Normal to the bottom face.
GLfloat normalLength_ [3]
Normal to the length-side face.
bool closedLength_
Is the length-side face drawn?
bool closedSides_
Are the top and bottom faces drawn?
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
HalfCylinder3D class.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 49 of file HalfCylinder3D.h.
Constructor & Destructor Documentation
HalfCylinder3D::HalfCylinder3D (GLfloat * origin, GLfloat ** axes, bool LengthSideIsClosed, bool sidesAreClosed)
Constructor.
Creates a half-cylinder from the location of its origin, the directions of the 2 axes of its elliptic bottom face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the half-cylinder
lengthIsClosed true if the half-cylinder's length face should be drawn
sideClosed true if the half-cylinder's bottom face should be drawn
Definition at line 39 of file HalfCylinder3D.cpp.
References uriVL::ErrorReport::appendToMessage(), and init_().
                 :       TubularSection3D(origin, axes, 0.f, PI_F),
                         //
                         closedLength_(lengthIsClosed),
                         closedSides_(sidesAreClosed)
 {
         try {
                 init_(axes);
         }
         catch (ErrorReport& e) {
 //              deleteArrays_();
                 e.appendToMessage("called from Cone constructor.");
                 throw e;
         }
 }
HalfCylinder3D::HalfCylinder3D (GLfloat * origin, GLfloat * dirAxis, GLfloat radius, bool LengthSideIsClosed, bool sidesAreClosed)
Constructor.
Creates a half-cylinder from the loation of its origin, direction of main axis, and radii of top and bottom faces.
Parameters
origin coordinates of the box's origin (at one corner of the box)
dirAxis the direction of the half-cylinder's main axis
bottomRadius the radius of the half-cylinder's circular bottom face
topRadius the radius of the half-cylinder's circular top face
lengthIsClosed true if the half-cylinder's length face should be drawn
sidesAreClosed true if the half-cylinder's top and bottom faces should be drawn
Definition at line 70 of file HalfCylinder3D.cpp.
References uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), and init_().
                 :       TubularSection3D(origin, dirAxis, radius, 0.f, PI_F),
                         //
                         closedLength_(lengthIsClosed),
                         closedSides_(sidesAreClosed)
 {
         GLfloat         **axes = GlUtils::glfMatrix(0, 2, 0, 2);
         //
         //      dirAxis is the direction axis of the cylinder
         axes[2][0] = dirAxis[0];
         axes[2][1] = dirAxis[1];
         axes[2][2] = dirAxis[2];
         //
         //      For the major axis, we need to build a vector orthogonal to dirAxis.
         if ((dirAxis[0]!= 0.f) || (dirAxis[2]!= 0.f))   //      this is not the local Y axis
         {
                 GLfloat         w[3] = {0.f, 1.f, 0.f};
                 commonNormalVector(w, dirAxis, axes[0]);                //      "X" = "Y" x "Z"
                 commonNormalVector(dirAxis, axes[0], axes[1]);  //      "Y" = "Z" x "X"
                 //
                 //      and now we can multiply by the radius
                 axes[0][0] *= radius;
                 axes[1][0] *= radius;
                 //
                 axes[0][1] *= radius;
                 axes[1][1] *= radius;
                 //
                 axes[0][2] *= radius;
                 axes[1][2] *= radius;
         }
         //      if dirAxis was the local Y axis, then I can take Z and X as major and minor
         else
         {
                 axes[0][0] = axes[0][1] = axes[1][1] = axes[1][2] = 0.f;
                 axes[0][2] = axes[1][0] = radius;
         }
         init_(axes);
         GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
 }
HalfCylinder3D::~HalfCylinder3D (void)
Destructor.
Definition at line 142 of file HalfCylinder3D.cpp.
 {
 /*      int i;
         if (vertex_!=NULL)
         {
                 for (i=0; i<=kVeryHighDefSlabs; i++)
                         free_glfMatrix(vertex_[i], 0,  kVeryHighDefCircPts-1, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (normal!=NULL)
         {
                 free_glfMatrix(normal_, 0,  kVeryHighDefCircPts-1, 0, 2);
                 normal_ = NULL;
         }
 */
 }
HalfCylinder3D::HalfCylinder3D (const HalfCylinder3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 113 of file HalfCylinder3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 : TubularSection3D(NULL, NULL, 0.f, 0.f, 0.f),
                         //
                         closedLength_(false),
                         closedSides_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "HalfCylinder3D copy constructor not implemented.");
 }
Member Function Documentation
void HalfCylinder3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 182 of file HalfCylinder3D.cpp.
References uriVL::TubularSection3D::draw().
 {
         TubularSection3D::draw();
 /*      if (closedSides_)
         {
                 glNormal3fv(normalTop_);
                 glBegin(GL_POLYGON);
                         for (int j=0; j<=nbCircSegs; j+=circStep_)
                                 glVertex3fv(vertex_[kVeryHighDefSlabs][j]);
                 glEnd();
                 //
                 glNormal3fv(normalBottom_);
                 glBegin(GL_POLYGON);
                         for (int j=nbCircSegs; j>=0; j-=circStep_)
                                 glVertex3fv(vertex_[0][j]);
                 glEnd();
         }
         if (closedLength_)
         {
                 glNormal3fv(normalLength_);
                 glBegin(GL_QUADS);
                         glVertex3fv(vertex_[0][0]);
                         glVertex3fv(vertex_[kVeryHighDefSlabs][0]);
                         glVertex3fv(vertex_[kVeryHighDefSlabs][nbCircSegs]);
                         glVertex3fv(vertex_[0][nbCircSegs]);
                 glEnd();
         }
 */
 }
void HalfCylinder3D::init_ (GLfloat ** axes) private
Initialize the half-cylinder.
Parameters
axes the 3 axes of the half-cylinder
Definition at line 236 of file HalfCylinder3D.cpp.
References closedLength_, closedSides_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), kVeryHighDefSlabs, normalBottom_, normalLength_, and normalTop_.
Referenced by HalfCylinder3D().
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         dir[kVeryHighDefSlabs+1][3],
                         majCross[3], minCross[3];
         //      majCross = a[0] x a[2] (major axis x direction)
         crossProduct(a[0], a[2], majCross);
         //      minCross = a[1] x a[2] (minor axis x direction)
         crossProduct(a[1], a[2], minCross);
         //      First, we precompute the graduation steps for the slabs along
         //      the "direction" axis (a[2]).
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 for (int k=0; k<3; k++)
                         dir[i][k] = i*dirStep*a[2][k];
         //      if the top and bottom sides are filled, normal vectors must be computed
         //      for these sides
         if (closedSides_)
         {
                 //      topNormal = major x minor / ||major x minor||
                 commonNormalVector(a[0], a[1], normalTop_);
                 normalBottom_[0] = -normalTop_[0];
                 normalBottom_[1] = -normalTop_[1];
                 normalBottom_[2] = -normalTop_[2];
         }
         //      Same thing for the length side
         if (closedLength_)
                 //      normalLength = major x direction / ||major x direction||
                 commonNormalVector(a[0], a[2], normalLength_);
 }
const HalfCylinder3D & HalfCylinder3D::operator= (const HalfCylinder3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 125 of file HalfCylinder3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "HalfCylinder3D copy operator not implemented.");
         return *this;
 }
Member Data Documentation
bool uriVL::HalfCylinder3D::closedLength_ private
Is the length-side face drawn?
Definition at line 101 of file HalfCylinder3D.h.
Referenced by init_().
bool uriVL::HalfCylinder3D::closedSides_ private
Are the top and bottom faces drawn?
Definition at line 105 of file HalfCylinder3D.h.
Referenced by init_().
GLfloat uriVL::HalfCylinder3D::normalBottom_[3] private
Normal to the bottom face.
Definition at line 92 of file HalfCylinder3D.h.
Referenced by init_().
GLfloat uriVL::HalfCylinder3D::normalLength_[3] private
Normal to the length-side face.
Definition at line 96 of file HalfCylinder3D.h.
Referenced by init_().
GLfloat uriVL::HalfCylinder3D::normalTop_[3] private
Normal to the top face.
Definition at line 88 of file HalfCylinder3D.h.
Referenced by init_().
The documentation for this class was generated from the following files:
HalfCylinder3D.h
HalfCylinder3D.cpp