URIVisionLibrary: uriVL::LabelRaster Class Reference
uriVL::LabelRaster Class Reference
Base label raster class.
#include <LabelRaster.h>
Public Member Functions
LabelRaster (int nbRows, int nbCols)
Allocates an 8-bit label raster image at the specified dimensions.
LabelRaster (const ImageRect *theRect)
Allocates a label raster at the specified dimensions.
LabelRaster (const LabelRaster *label)
Copy Constructor.
~LabelRaster (void)
Class destructor.
void copyInto (LabelRaster *label) const
Copies this label raster into the one received as parameter.
const char * getLabel (void) const
Returns the 8-bit base label raster as a read-only 1D array.
char * getLabel (ReadWriteStatus rw) const
Returns the 8-bit base label raster as a read-write 1D array.
const char *const * getLabel2D (void) const
Returns the 8-bit base label raster as a read-only 2D array.
char ** getLabel2D (ReadWriteStatus rw) const
Returns the 8-bit base label raster as a read-write 2D array.
const char *const * getShiftedLabel2D (void) const
Returns the label raster's read-only shifted 2D array.
char ** getShiftedLabel2D (ReadWriteStatus rw) const
Returns the label raster's read-write shifted 2D array.
bool overlaps (const LabelRaster *img) const
Indicates whether this raster's bounding rectangle and that of the label raster received as parameter overlap.
bool coincidesWith (const LabelRaster *img) const
Indicates whether this raster's bounding rectangle and that of the image received as parameter coincide.
bool contains (const LabelRaster *img) const
Indicates whether this image's bounding rectangle contains that of the image received as parameter.
bool isContainedBy (const LabelRaster *img) const
Indicates whether this image's bounding rectangle is contained by that of the image received as parameter.
int getHeight (void) const
Returns the number of rows for the image.
int getWidth (void) const
Returns the number of columns for the image.
const ImageRect * getBoundRect (void) const
Returns the label raster's bounding rectangle.
const ImageRect * getValidRect (void) const
Returns the label raster's valid data rectangle.
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
void setRect (const ImageRect *theRect)
Sets a new bounding rectangle for the label raster.
void setRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the label raster.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the label raster.
void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the label raster.
Protected Member Functions
void allocateRasters_ (void)
Allocates the label rasters.
void allocateShiftedRaster2D_ (void)
Allocates the 2D label raster.
LabelRaster (const LabelRaster &label)
Copy constructor.
const LabelRaster & operator= (const LabelRaster &label)
Copy operator.
Protected Attributes
char * label_
1D label raster.
char ** label2D_
2D array mapped on the 1D label raster.
char ** shiftedLabel2D_
2D shifted array mapped on the 1D label raster.
ImageRect * boundRect_
Bounding rectangle for this label raster.
ImageRect * validRect_
Bounding rectangle of the valid data region for this label raster.
Detailed Description
Base label raster class.
LabelRaster is inspired from LabelRaster (LabelRaster_gray in particular). it simply stores an array of 8-bit labels and provides acces functions to this array.
Author
Fang Han and jean-yves herv
Version
I%, G%
Definition at line 34 of file LabelRaster.h.
Constructor & Destructor Documentation
LabelRaster::LabelRaster (int nbRows, int nbCols)
Allocates an 8-bit label raster image at the specified dimensions.
Allocates an 8-bit label raster at the specified dimensions and initializes this raster to zero values.
Parameters
nbRows number of rows of the label raster
nbCols number of columns of the label raster
Definition at line 30 of file LabelRaster.cpp.
References allocateRasters_().
                 :       label_(NULL),
                         label2D_(NULL),
                         shiftedLabel2D_(NULL),
                         boundRect_ (new ImageRect(0, 0, nbCols, nbRows)),
                         validRect_(boundRect_)
 {
     allocateRasters_();
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LabelRaster constructor");
         throw e;
 }
 catch(...) {
     FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "Failure in LabelRaster constructor");
 }
LabelRaster::LabelRaster (const ImageRect * theRect)
Allocates a label raster at the specified dimensions.
Initializes some instance variables (in particular the ImageRect).
Parameters
theRect image rectangle indicating the desired dimensions
Definition at line 53 of file LabelRaster.cpp.
References allocateRasters_(), uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), uriVL::kNullRectangleError, uriVL::UriVL::validDataRectIsSafe(), and validRect_.
                 :       label_(NULL),
                         label2D_(NULL),
                         shiftedLabel2D_(NULL),
                         boundRect_ (NULL),
                         validRect_(NULL)
 {
         try {
                 boundRect_ = new ImageRect(theRect);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called from LabelRaster constructor.");
                 throw e;
         }
     FAIL_CONDITION( boundRect_ == NULL,
                     kNullRectangleError,
                     "ImageRect creation failed in LabelRaster constructor");
     if (UriVL::validDataRectIsSafe())
     {
         validRect_ = new ImageRect(theRect->getLeft(), theRect->getTop(), 0, 0);
         FAIL_CONDITION( validRect_ == NULL,
                         kNullRectangleError,
                         "ImageRect creation failed in LabelRaster constructor");
     }
     else
         validRect_ = boundRect_;
     allocateRasters_();
 }
LabelRaster::LabelRaster (const LabelRaster * label)
Copy Constructor.
Parameters
label the LabelRaster object to copy
Definition at line 86 of file LabelRaster.cpp.
References allocateRasters_(), uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, getBoundRect(), getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), getWidth(), uriVL::kInvalidParameterError, uriVL::kMemoryCopyError, uriVL::kNullLabelRasterError, uriVL::kNullRectangleError, label_, uriVL::UriVL::validDataRectIsSafe(), and validRect_.
                 :       label_(NULL),
                         label2D_(NULL),
                         shiftedLabel2D_(NULL),
                         boundRect_ (new ImageRect(label->getBoundRect())),
                         validRect_(NULL)
 {
     FAIL_CONDITION( label == NULL,
                     kNullLabelRasterError,
                     "NULL LabelRaster parameter in LabelRaster constructor");
         try {
                 boundRect_ = new ImageRect(label->getBoundRect());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called from LabelRaster constructor.");
                 throw e;
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid pointer to a LabelRaster passed to LabelRaster constructor");
         }
     FAIL_CONDITION( boundRect_ == NULL,
                     kNullRectangleError,
                     "ImageRect creation failed in LabelRaster constructor");
     if (UriVL::validDataRectIsSafe())
     {
                 const ImageRect* rect = label->getBoundRect();
         validRect_ = new ImageRect(rect->getLeft(), rect->getTop(), 0, 0);
         FAIL_CONDITION( validRect_ == NULL,
                         kNullRectangleError,
                         "ImageRect creation failed in LabelRaster constructor");
     }
     else
         validRect_ = boundRect_;
     allocateRasters_();
         //      copy the data
         try {
                 memcpy(label_, label->label_, getHeight()*getWidth());
         }
         catch (...) {
     FAIL_CONDITION( true,
                     kMemoryCopyError,
                     "Memory copy error in LabelRaster constructor");
         }
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by LabelRaster copy constructor");
         throw e;
 }
 catch(...) {
     FAIL_CONDITION( label == NULL,
                     kNullParameterError,
                     "NULL LabelRaster parameter in LabelRaster constructor");
     FAIL_CONDITION( true,
                     kInvalidParameterError,
                     "Failure in LabelRaster constructor");
 }
LabelRaster::~LabelRaster (void)
Class destructor.
Standard destructor (nothing fancy).
Definition at line 164 of file LabelRaster.cpp.
References label2D_, label_, and shiftedLabel2D_.
 {
     if (label2D_ != NULL)
         delete []label2D_;
     if (shiftedLabel2D_ != NULL)
         delete []shiftedLabel2D_;
     delete []label_;
 }
LabelRaster::LabelRaster (const LabelRaster & label) protected
Copy constructor.
Allocates a label raster at the specified dimensions. Not implemented. Just added so that Xcode will not gove warnings.
Initializes some instance variables (in particular the ImageRect).
Parameters
label the LabelRaster object to copy
Definition at line 150 of file LabelRaster.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       label_(NULL),
                         label2D_(NULL),
                         shiftedLabel2D_(NULL),
                         boundRect_ (NULL),
                         validRect_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Copy contructor of LabelRaster class not implemented");
 }
Member Function Documentation
void LabelRaster::allocateRasters_ (void) protected
Allocates the label rasters.
Definition at line 450 of file LabelRaster.cpp.
References allocateShiftedRaster2D_(), boundRect_, FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), uriVL::kRasterAllocationFailure, label2D_, and label_.
Referenced by LabelRaster(), and setRect().
 {
     int nbRows = boundRect_->getHeight(),
                 nbCols = boundRect_->getWidth();
     //---------------
     //  allocate 1D raster
     //---------------
     label_ = new char[nbRows*nbCols];
     FAIL_CONDITION( label_ == NULL,
                     kRasterAllocationFailure,
                     "Label raster allocation failed in LabelRaster constructor");
     //---------------
     //  allocate 2D raster
     //---------------
     if (label2D_ != NULL)
         delete []label2D_;
     label2D_ = new char*[nbRows];
     FAIL_CONDITION(label2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate label2D_ array");
     label2D_[0] = label_;
     for (int i=1; i<nbRows; i++)
         label2D_[i] = label2D_[i-1] + nbCols;
     //---------------
     //  allocate shifted raster (if needed)
     //---------------
     allocateShiftedRaster2D_();
 }
void LabelRaster::allocateShiftedRaster2D_ (void) protected
Allocates the 2D label raster.
Definition at line 483 of file LabelRaster.cpp.
References boundRect_, FAIL_CONDITION, uriVL::ImageRect::getBottom(), getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), getWidth(), uriVL::kRasterAllocationFailure, label2D_, shiftedLabel2D_, and uriVL::ImageRect::upperLeftIsAtOrigin().
Referenced by allocateRasters_(), and setRect().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (!boundRect_->upperLeftIsAtOrigin())
     {
         const int   iLow  = boundRect_->getTop(),
                     iHigh = boundRect_->getBottom(),
                                         jLow  = boundRect_->getLeft(),
                     nbRows = getHeight(),
                     nbCols = getWidth();
         if (shiftedLabel2D_ != NULL)
             delete shiftedLabel2D_;
         shiftedLabel2D_ = new char*[nbRows];
         FAIL_CONDITION( shiftedLabel2D_ == NULL,
                         kRasterAllocationFailure,
                         "label  raster allocation failed");
         shiftedLabel2D_ -= iLow;
         shiftedLabel2D_[iLow] = label2D_[0] - jLow;
         for (int i = iLow; i < iHigh; i++)
             shiftedLabel2D_[i+1] = shiftedLabel2D_[i] + nbCols;
     }
     else
         shiftedLabel2D_ = NULL;
 }
bool LabelRaster::coincidesWith (const LabelRaster * img) const
Indicates whether this raster's bounding rectangle and that of the image received as parameter coincide.
Parameters
img the image to test agains this image
Returns
true if the two rectangles coincide, false otherwise
Definition at line 237 of file LabelRaster.cpp.
References boundRect_, uriVL::ImageRect::coincidesWith(), FAIL_CONDITION, getBoundRect(), uriVL::kNullLabelRasterError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( img == NULL,
                     kNullLabelRasterError,
                     "Test of null LabelRaster in LabelRaster::coincidesWith");
     const ImageRect* theRect = img->getBoundRect();
     FAIL_CONDITION( (boundRect_ == NULL) || (theRect == NULL),
                     kNullRectangleError,
                     "Test of null ImageRect member in LabelRaster::coincidesWith");
     return  boundRect_->coincidesWith(theRect);
 }
bool LabelRaster::contains (const LabelRaster * img) const
Indicates whether this image's bounding rectangle contains that of the image received as parameter.
Parameters
img the image to test agains this image
Returns
true if theRect is contained within this rectangle, false otherwise
Definition at line 263 of file LabelRaster.cpp.
References boundRect_, uriVL::ImageRect::contains(), FAIL_CONDITION, getBoundRect(), uriVL::kNullLabelRasterError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( img == NULL,
                     kNullLabelRasterError,
                     "Test of null LabelRaster in LabelRaster::coincidesWith");
     const ImageRect* theRect = img->getBoundRect();
     FAIL_CONDITION( (boundRect_ == NULL) || (theRect == NULL),
                     kNullRectangleError,
                     "Test of null ImageRect member in LabelRaster::contains");
     return  boundRect_->contains(theRect);
 }
void LabelRaster::copyInto (LabelRaster * label) const
Copies this label raster into the one received as parameter.
The destination label raster is resized if needed
Parameters
label the destination LabelRaster object
Definition at line 182 of file LabelRaster.cpp.
References uriVL::ErrorReport::appendToMessage(), boundRect_, FAIL_CONDITION, getHeight(), getWidth(), uriVL::kMemoryCopyError, uriVL::kNullLabelRasterError, label_, and setRect().
 {
     FAIL_CONDITION( label == NULL,
                     kNullLabelRasterError,
                     "NULL LabelRaster parameter in LabelRaster::copyInto");
         try {
                 label->setRect(boundRect_);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by LabelRaster::copyInto");
                 throw e;
         }
         //      copy the data
         try {
                 memcpy(label_, label->label_, getHeight()*getWidth());
         }
         catch (...) {
     FAIL_CONDITION( true,
                     kMemoryCopyError,
                     "Memory copy error in LabelRaster::copyInto");
         }
 }
const ImageRect * LabelRaster::getBoundRect (void) const
Returns the label raster's bounding rectangle.
Returns a pointer to the label raster's bounding rectangle.
Reminder: the ImageRect class uses the pixel-as-rectangle convention.
Returns
pointer to the label raster's bouding rectangle
See also
validRect_
boundRect_
getValidRect
Definition at line 224 of file LabelRaster.cpp.
References boundRect_.
Referenced by coincidesWith(), contains(), isContainedBy(), LabelRaster(), overlaps(), and uriVL::BlobTracker2D::track().
 {
     //    return new ImageRect(boundRect_);
     return boundRect_;
 }
int LabelRaster::getHeight (void) const
Returns the number of rows for the image.
Returns
number of rows for the image
Definition at line 289 of file LabelRaster.cpp.
References boundRect_, and uriVL::ImageRect::getHeight().
Referenced by allocateShiftedRaster2D_(), copyInto(), LabelRaster(), and setRect().
 {
     return boundRect_->getHeight( );
 }
const char * LabelRaster::getLabel (void) const
Returns the 8-bit base label raster as a read-only 1D array.
Returns
1D base raster for this image
Definition at line 395 of file LabelRaster.cpp.
References label_.
 {
     return label_;
 }
char * LabelRaster::getLabel (ReadWriteStatus rw) const
Returns the 8-bit base label raster as a read-write 1D array.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Definition at line 401 of file LabelRaster.cpp.
References label_.
 {
     return label_;
 }
const char *const * LabelRaster::getLabel2D (void) const
Returns the 8-bit base label raster as a read-only 2D array.
Returns
2D base raster for this label raster
Definition at line 407 of file LabelRaster.cpp.
References label2D_.
Referenced by uriVL::HysteresisLabeler::applyInto(), uriVL::HysteresisLabeler::applyTo(), loadImage(), myMenu3(), resetCells(), and updateState().
 {
     return label2D_;
 }
char ** LabelRaster::getLabel2D (ReadWriteStatus rw) const
Returns the 8-bit base label raster as a read-write 2D array.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this label raster
Definition at line 412 of file LabelRaster.cpp.
References label2D_.
 {
     return label2D_;
 }
const char *const * LabelRaster::getShiftedLabel2D (void) const
Returns the label raster's read-only shifted 2D array.
Returns
shifted 2D raster for this label raster
Definition at line 417 of file LabelRaster.cpp.
References boundRect_, label2D_, shiftedLabel2D_, and uriVL::ImageRect::upperLeftIsAtOrigin().
Referenced by uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), uriVL::ZeroCrossingDetector::applyInto_(), uriVL::ColorInverseThresholdLabeler::connectNeighbor_(), uriVL::ColorThresholdLabeler::connectNeighbors_(), uriVL::GrayThresholdLabeler::connectNeighbors_(), uriVL::BlobFinder::findAllBlobs(), and uriVL::BlobFinder::findBlobAbout().
 {
     //  if the label raster has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (boundRect_->upperLeftIsAtOrigin())
         return label2D_;
     else
         return shiftedLabel2D_;
 }
char ** LabelRaster::getShiftedLabel2D (ReadWriteStatus rw) const
Returns the label raster's read-write shifted 2D array.
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D raster for this label raster
Definition at line 429 of file LabelRaster.cpp.
References boundRect_, label2D_, shiftedLabel2D_, and uriVL::ImageRect::upperLeftIsAtOrigin().
 {
     //  if the label raster has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if (boundRect_->upperLeftIsAtOrigin())
         return label2D_;
     else
         return shiftedLabel2D_;
 }
const ImageRect * LabelRaster::getValidRect (void) const
Returns the label raster's valid data rectangle.
Returns a pointer to the label raster's valid data rectangle.
Reminder: the ImageRect class uses the pixel-as-rectangle convention.
Returns
pointer to the label raster's valid data rectangle
See also
validRect_
boundRect_
getBoundRect
getShiftedLabel2D
Definition at line 230 of file LabelRaster.cpp.
References validRect_.
Referenced by uriVL::BlobFinder::findAllBlobs(), and uriVL::BlobFinder::findBlobAbout().
 {
     //    return new ImageRect(validRect_);
     return validRect_;
 }
int LabelRaster::getWidth (void) const
Returns the number of columns for the image.
Beware: Base rasters have padded rows. You cannot rely on the fact that the number of bytes in a row is equal to the number of columns multiplied by by the number of bytes per pixel.
Returns
number of columns for the image
Definition at line 294 of file LabelRaster.cpp.
References boundRect_, and uriVL::ImageRect::getWidth().
Referenced by allocateShiftedRaster2D_(), copyInto(), LabelRaster(), and setRect().
 {
     return boundRect_->getWidth( );
 }
bool LabelRaster::isContainedBy (const LabelRaster * img) const
Indicates whether this image's bounding rectangle is contained by that of the image received as parameter.
Parameters
img the image to test agains this image
Returns
true if this image contains img, false otherwise
Definition at line 276 of file LabelRaster.cpp.
References boundRect_, FAIL_CONDITION, getBoundRect(), uriVL::ImageRect::isContainedBy(), uriVL::kNullLabelRasterError, and uriVL::kNullRectangleError.
 {
     FAIL_CONDITION( img == NULL,
                     kNullLabelRasterError,
                     "Test of null LabelRaster in LabelRaster::coincidesWith");
     const ImageRect* theRect = img->getBoundRect();
     FAIL_CONDITION( (boundRect_ == NULL) || (theRect == NULL),
                     kNullRectangleError,
                     "Test of null ImageRect member in LabelRaster::isContainedBy");
     return  boundRect_->isContainedBy(theRect);
 }
const LabelRaster & LabelRaster::operator= (const LabelRaster & label) protected
Copy operator.
Not implemented. Just added so that Xcode will not gove warnings.
Parameters
label the LabelRaster object to copy
Definition at line 207 of file LabelRaster.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Copy operator of LabelRaster class not implemented yet");
         return *this;
 }
bool LabelRaster::overlaps (const LabelRaster * img) const
Indicates whether this raster's bounding rectangle and that of the label raster received as parameter overlap.
Parameters
img the label raster to test agains this image
Returns
true if the two rectangles overlap, false otherwise
Definition at line 250 of file LabelRaster.cpp.
References boundRect_, FAIL_CONDITION, getBoundRect(), uriVL::kNullLabelRasterError, uriVL::kNullRectangleError, and uriVL::ImageRect::overlaps().
 {
     FAIL_CONDITION( img == NULL,
                     kNullLabelRasterError,
                     "Test of null LabelRaster in LabelRaster::coincidesWith");
     const ImageRect* theRect = img->getBoundRect();
     FAIL_CONDITION( (boundRect_ == NULL) || (theRect == NULL),
                     kNullRectangleError,
                     "Test of null ImageRect member in LabelRaster::overlaps");
     return  boundRect_->overlaps(theRect);
 }
void LabelRaster::setOrigin (int x = 0, int y = 0)
Sets a new origin for the raster image.
A raster image occupies a rectangle within the global image space. For example, a LabelRaster could be defined as a subimage of another image. This operation does not result in a reallocation of the image.
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
Definition at line 300 of file LabelRaster.cpp.
References boundRect_, and uriVL::ImageRect::setOrigin().
 {
     boundRect_->setOrigin(x, y);
 }
void LabelRaster::setRect (const ImageRect * theRect)
Sets a new bounding rectangle for the label raster.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the image.
This function should be overridden by child classes that have their own raster (eg. HSV, gray_F, etc.)
Parameters
theRect new bounding rectangle for the image
Definition at line 310 of file LabelRaster.cpp.
References uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), and uriVL::ImageRect::getWidth().
Referenced by copyInto().
 {
     setRect(theRect->getLeft(), theRect->getTop(), theRect->getWidth(), theRect->getHeight());
 }
void LabelRaster::setRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the label raster.
A raster image occupies a rectangle within the global image space. For example, a RasterImage could be defined as a subimage of another image. This operation may require a reallocation of the label raster.
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Definition at line 315 of file LabelRaster.cpp.
References allocateRasters_(), allocateShiftedRaster2D_(), boundRect_, getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::ImageRect::getTop(), getWidth(), label2D_, label_, uriVL::ImageRect::setRect(), shiftedLabel2D_, uriVL::ImageRect::translate(), and validRect_.
 {
     //  if width and height have not changed, then all we need to do is update the
     //  ImageRect member and reallocate the "shifted" array.
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != boundRect_->getLeft()) || (y != boundRect_->getTop()))
         {
             if (shiftedLabel2D_ != NULL)
                 delete []shiftedLabel2D_;
             //  if the valid rect was equal to the bounding rect, we simply
             //  reassign validRect_, otherwise we have to translate it first
             if (validRect_ != boundRect_)
                 validRect_->translate(x - boundRect_->getLeft(), y - boundRect_->getRight());
             boundRect_->setRect(x, y, theWidth, theHeight);
             allocateShiftedRaster2D_();
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangle are different, then we must delete
     //  and reallocate the GraphWorld as well as the 0-based 2D raster.
     else
     {
         //  First we delete the rasters
         if (label2D_ != NULL)
             delete []label2D_;
         if (shiftedLabel2D_ != NULL)
             delete []shiftedLabel2D_;
         delete []label_;
         //  if the valid rect was equal to the bounding rect, we simply
         //  reassign validRect_, otherwise we have to translate it first
         if (validRect_ != boundRect_)
             delete validRect_;
         validRect_ = boundRect_;
         boundRect_->setRect(x, y, theWidth, theHeight);
         //  then we allocate the rasters
         allocateRasters_();
     }
 }
void LabelRaster::setValidRect (const ImageRect * theRect)
Sets a new valid data rectangle for the label raster.
A raster image or vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the label raster's bounding rectangle
Parameters
theRect new valid data rectangle for the label raster
Definition at line 363 of file LabelRaster.cpp.
References uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), and uriVL::ImageRect::getWidth().
Referenced by uriVL::EdgeDetector_Canny_F::applyInto(), uriVL::HysteresisLabeler::applyInto(), uriVL::ColorInverseThresholdLabeler::applyInto_(), uriVL::GrayThresholdLabeler::applyInto_(), uriVL::ColorThresholdLabeler::applyInto_(), and uriVL::ZeroCrossingDetector::applyInto_().
 {
     setValidRect(theRect->getLeft(), theRect->getTop(), theRect->getWidth(), theRect->getHeight());
 }
void LabelRaster::setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the label raster.
A raster image or vector field occupies a rectangle within the global image space. For example, a vector field could be defined as a subpart of another. Only part of the image may contain valid data (for example after application of a filter). The function call will fail if the new valid data rect is not contained by the label raster's bounding rectangle
Parameters
x X coordinate of the valid data upper left corner
y Y coordinate of the valid data upper left corner
theWidth number of valid columns
theHeight number of valid rows
Definition at line 368 of file LabelRaster.cpp.
References boundRect_, FAIL_CONDITION, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getRight(), uriVL::kInvalidRectangleError, uriVL::ImageRect::setRect(), and validRect_.
 {
     //  The new valid data rect must be contained by the bounding rectangle
     FAIL_CONDITION(     ( x < boundRect_->getLeft() ) ||
                     ( x + theWidth - 1 > boundRect_->getRight() ) ||
                     ( y < boundRect_->getTop() ) ||
                     ( y + theHeight - 1 > boundRect_->getBottom() ),
                     kInvalidRectangleError,
                     "New valid data rectangle must be within the bounding rectangle");
     //  if the valid data rect used to coincide with the bounding rect, we must allocate
     //  a new rectangle
     if (validRect_ == boundRect_)
         validRect_ = new ImageRect(x, y, theWidth, theHeight);
     else
         validRect_->setRect(x, y, theWidth, theHeight);
 }
void LabelRaster::translate (int dx = 0, int dy = 0)
Translates the raster image by the specified amount.
A raster image occupies a rectangle within the global image space. For example, a LabelRaster could be defined as a subimage of another image. This operation does not result in a reallocation of the image.
Parameters
dx horizontal displacement of the image's origin
dy vertical displacement of the image's origin
Definition at line 305 of file LabelRaster.cpp.
References boundRect_, and uriVL::ImageRect::translate().
 {
     boundRect_->translate(dx, dy);
 }
Member Data Documentation
ImageRect* uriVL::LabelRaster::boundRect_ protected
Bounding rectangle for this label raster.
This rectangle defines the dimensions of the space actually allocated to store this label raster. The upper left corner of the rectangle is not necessarily at (0,0).
See also
validRect_
getBoundRect
getValidRect
getShiftedRaster2D
Definition at line 340 of file LabelRaster.h.
Referenced by allocateRasters_(), allocateShiftedRaster2D_(), coincidesWith(), contains(), copyInto(), getBoundRect(), getHeight(), getShiftedLabel2D(), getWidth(), isContainedBy(), LabelRaster(), overlaps(), setOrigin(), setRect(), setValidRect(), and translate().
char** uriVL::LabelRaster::label2D_ protected
2D array mapped on the 1D label raster.
Definition at line 317 of file LabelRaster.h.
Referenced by allocateRasters_(), allocateShiftedRaster2D_(), getLabel2D(), getShiftedLabel2D(), setRect(), and ~LabelRaster().
char* uriVL::LabelRaster::label_ protected
1D label raster.
Definition at line 312 of file LabelRaster.h.
Referenced by allocateRasters_(), copyInto(), getLabel(), LabelRaster(), setRect(), and ~LabelRaster().
char** uriVL::LabelRaster::shiftedLabel2D_ protected
2D shifted array mapped on the 1D label raster.
Definition at line 322 of file LabelRaster.h.
Referenced by allocateShiftedRaster2D_(), getShiftedLabel2D(), setRect(), and ~LabelRaster().
ImageRect* uriVL::LabelRaster::validRect_ protected
Bounding rectangle of the valid data region for this label raster.
This rectangle defines the subregion of the bounding rectangle (boundRect_) that contains valid data.
See also
boundRect_
getBoundRect
getValidRect
getShiftedRaster2D
Definition at line 353 of file LabelRaster.h.
Referenced by getValidRect(), LabelRaster(), setRect(), and setValidRect().
The documentation for this class was generated from the following files:
LabelRaster.h
LabelRaster.cpp