URIVisionLibrary: WXGL_IO_Canvas Class Reference
WXGL_IO_Canvas Class Reference
#include <WXGL_IO_canvas.h>
Public Member Functions
WXGL_IO_Canvas (wxWindow *parent, const wxWindowID id=-1, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0, const wxString &name="GLCanvas")
virtual ~WXGL_IO_Canvas ()
void MakeFake_ImageRGBa (RasterImage *ptImage)
void MakeFake_ImageGS (RasterImage *ptImage)
void MakeFake_ImageGSF (RasterImage *ptImage)
void MakeFake_ImageBinary (RasterImage *ptImage)
void DrawSquare (void)
void DrawSquare (int nX, int xY)
bool OnCloseCanvas ()
void OnMouseEvent (wxMouseEvent &event)
void OnCharEvent (wxKeyEvent &event)
void OnFocusEvent (wxFocusEvent &event)
void OnKillFocusEvent (wxFocusEvent &event)
void OnActivateEvent (wxActivateEvent &event)
void OnShowEvent (wxShowEvent &event)
void OnPaintEvent (wxPaintEvent &event)
void SetUpCamera (void)
void UpdateCanvas (void)
void CreateTestImage (void)
void SetTestImageRows (unsigned long ulR)
unsigned long GetTestImageRows ()
void SetTestImageCols (unsigned long ulC)
unsigned long GetTestImageCols ()
void SetFileType (unsigned long ulFT)
unsigned long GetFileType ()
void SetRasterType (unsigned long ulRT)
unsigned long GetRasterType ()
Protected Types
enum MenuCommands {
MENU_ID_EXT_BMP = 100,
MENU_ID_EXT_JPG,
MENU_ID_EXT_PNG,
MENU_ID_EXT_TIF,
MENU_ID_IMAGE_BINARY,
MENU_ID_IMAGE_GRAY,
MENU_ID_IMAGE_GRAY_F,
MENU_ID_IMAGE_RGBA
}
Protected Attributes
DECLARE_EVENT_TABLE() private RasterImage * pmtReadInImage
RasterImage * pmtDifferenceImage
unsigned long mulRows
unsigned long mulCols
unsigned long mulFileType
unsigned long mulRasterType
Detailed Description
Definition at line 37 of file WXGL_IO_canvas.h.
Member Enumeration Documentation
enum WXGL_IO_Canvas::MenuCommands protected
Enumerator
MENU_ID_EXT_BMP
MENU_ID_EXT_JPG
MENU_ID_EXT_PNG
MENU_ID_EXT_TIF
MENU_ID_IMAGE_BINARY
MENU_ID_IMAGE_GRAY
MENU_ID_IMAGE_GRAY_F
MENU_ID_IMAGE_RGBA
Definition at line 95 of file WXGL_IO_canvas.h.
{
                          // file extension types
                         MENU_ID_EXT_BMP = 100, // copies are made in frame so these have to match
                         MENU_ID_EXT_JPG,
                         MENU_ID_EXT_PNG,
                         MENU_ID_EXT_TIF,
                          // raster types
                         MENU_ID_IMAGE_BINARY,
                         MENU_ID_IMAGE_GRAY,
                         MENU_ID_IMAGE_GRAY_F,
                         MENU_ID_IMAGE_RGBA,
     };
Constructor & Destructor Documentation
WXGL_IO_Canvas::WXGL_IO_Canvas (wxWindow * parent, const wxWindowID id = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, const wxString & name = "GLCanvas")
Definition at line 72 of file WXGL_IO_canvas.cpp.
                                                                                  : wxGLCanvas(parent, id, pos, size, style, name)
 // : wxScrolledWindow(parent, wxID_ANY, pos, size)
 {
         pmtOriginalImage = pmtReadInImage = pmtDifferenceImage = 0;
         mulRows = 480;
         mulCols = 644;
         mulFileType = MENU_ID_EXT_BMP;
         mulRasterType = MENU_ID_IMAGE_RGBA;
         CreateTestImage();
 }
WXGL_IO_Canvas::~WXGL_IO_Canvas () virtual
Definition at line 164 of file WXGL_IO_canvas.cpp.
 {
 }
Member Function Documentation
void WXGL_IO_Canvas::CreateTestImage (void)
Definition at line 90 of file WXGL_IO_canvas.cpp.
References uriVL::ImageWriter::outputFrame().
Referenced by WXGL_IO_Frame::ParamSize(), WXGL_IO_Frame::RasterType(), and WXGL_IO_Frame::TypeExtension().
 {
         wxString strExtension, strFileName;
 // set up file stuff
         switch (mulFileType)
         {
                 case MENU_ID_EXT_BMP:
                         strExtension = ".BMP";
                         break;
                 case MENU_ID_EXT_JPG:
                         strExtension = ".JPG";
                         break;
                 case MENU_ID_EXT_PNG:
                         strExtension = ".PNG";
                         break;
                 case MENU_ID_EXT_TIF:
                 default:
                         mulFileType = MENU_ID_EXT_TIF; // just in case we got here by default :)
                         strExtension = ".TIF";
                         break;
         } // end switch over file type
         strFileName = "TestFile"+strExtension;
 // set up image stuff
         if (pmtOriginalImage!=0)
         {
                 delete pmtOriginalImage;
         }
         switch (mulRasterType)
         {
                 case MENU_ID_IMAGE_BINARY:
                         pmtOriginalImage = new RasterImage_binary(mulRows, mulCols);
                         MakeFake_ImageBinary(pmtOriginalImage);
                         break;
                 case MENU_ID_IMAGE_GRAY:
                         pmtOriginalImage   = new RasterImage_gray(mulRows, mulCols);
                         MakeFake_ImageGS(pmtOriginalImage);
                         break;
                 case MENU_ID_IMAGE_GRAY_F:
                         pmtOriginalImage   = new RasterImage_gray_F(mulRows, mulCols);
                         MakeFake_ImageGSF(pmtOriginalImage);
                         break;
                 case MENU_ID_IMAGE_RGBA:
                 default:
                         mulRasterType = MENU_ID_IMAGE_RGBA; // just in case we got here by default :)
                         pmtOriginalImage   = new RasterImage_RGB(mulRows, mulCols);
                         MakeFake_ImageRGBa(pmtOriginalImage);
                         break;
         } // end switch over image type
         // write the image then read it back in
         ImageWriter *pmyWriter = new ImageWriter(strFileName.c_str());
         ImageReader *pmyReader = new ImageReader();
         pmyWriter->outputFrame(pmtOriginalImage,false);
         if (pmtReadInImage!=0)
         {
                 delete pmtReadInImage;
         }
         pmtReadInImage = pmyReader->readImage(strFileName.c_str(),true);
         // FIXME :: YES, this is a memory leak since readImage keeps allocating new images
 }
void WXGL_IO_Canvas::DrawSquare (void)
Definition at line 334 of file WXGL_IO_canvas.cpp.
 {
         static int nClear = 0, nPos = 0;
            SetCurrent();
                 SetUpCamera();
                 if (nClear==0)
                 {
                    glClearColor(0.0, 0.0, 0.0, 1.0);
                         nClear = 1;
                 }
                 else
                 {
                    glClearColor(192.0, 192.0, 192.0, 1.0);
                         nClear = 0;
                         nPos = (nPos==0?1:0);
                 }
                 if (nPos==0)
                 {
                         glMatrixMode(GL_MODELVIEW);
                         glLoadIdentity();
                         glClear(GL_COLOR_BUFFER_BIT);
                         glBegin(GL_LINE_LOOP);
                                 glColor3f(1.0, 0.0, 0.0);
                                 glVertex2i(500, 500);
                                 glVertex2i(500, 600);
                                 glVertex2i(600, 600);
                                 glVertex2i(600, 500);
                         glEnd();
                 }
                 else
                 {
                         glMatrixMode(GL_MODELVIEW);
                         glLoadIdentity();
                         glClear(GL_COLOR_BUFFER_BIT);
                         glBegin(GL_LINE_LOOP);
                                 glColor3f(0.0, 1.0, 0.0);
                                 glVertex2i(100, 100);
                                 glVertex2i(100, 200);
                                 glVertex2i(200, 200);
                                 glVertex2i(200, 100);
                         glEnd();
                 }
         //glFlush();
         SwapBuffers();
    SetCurrent();
 }
void WXGL_IO_Canvas::DrawSquare (int nX, int xY)
Definition at line 300 of file WXGL_IO_canvas.cpp.
 {
         static int nClear = 0;
         int nCanvasWidth, nCanvasHeight;
         this->GetClientSize(&nCanvasWidth, &nCanvasHeight);
         if (nClear==0)
         {
            glClearColor(0.0, 0.0, 0.0, 1.0);
                 nClear = 1;
         }
         else
         {
            glClearColor(192.0, 192.0, 192.0, 1.0);
                 nClear = 0;
         }
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glClear(GL_COLOR_BUFFER_BIT);
         glBegin(GL_LINE_LOOP);
                 glColor3f(1.0, 0.0, 0.0);
                 glVertex2i(nX, nCanvasHeight-(nY));
                 glVertex2i(nX, nCanvasHeight-(nY+100));
                 glVertex2i(nX+100, nCanvasHeight-(nY+100));
                 glVertex2i(nX+100, nCanvasHeight-(nY));
         glEnd();
         SwapBuffers();
    SetCurrent();
 }
unsigned long WXGL_IO_Canvas::GetFileType () inline
Definition at line 80 of file WXGL_IO_canvas.h.
 {return mulFileType;}
unsigned long WXGL_IO_Canvas::GetRasterType () inline
Definition at line 82 of file WXGL_IO_canvas.h.
 {return mulRasterType;}
unsigned long WXGL_IO_Canvas::GetTestImageCols () inline
Definition at line 78 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::ParamSize().
 {return mulCols;}
unsigned long WXGL_IO_Canvas::GetTestImageRows () inline
Definition at line 76 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::ParamSize().
 {return mulRows;}
void WXGL_IO_Canvas::MakeFake_ImageBinary (RasterImage * ptImage)
Definition at line 618 of file WXGL_IO_canvas.cpp.
References uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), uriVL::R_W_ACCESS, and uriVL::DrawableObject2D::setValidRect().
 {
     //-------------------------------------------------------------
     //  Image 1 is created by computation --> fill the array with GS values
     //   This code fragment demonstrate how to get direct access to the image's
     //   raster for initialization and other IP calculations
          //
          //   This code was lifted from SimpleIO demo program
     //-------------------------------------------------------------
     //
     //  the raster image is created at the desired dimensions
     if (ptImage != NULL)
     {
         //  we get a reference to the image's base raster
         //  Here, we use the version of the getRaster family of functions that return a
         //  read-write reference
         unsigned char *pubRaster = ((RasterImage_binary*)ptImage)->getRaster(R_W_ACCESS);
         int   nbRows = ptImage->getHeight(),
               nbCols = ptImage->getWidth();
         //  from this point on
         for (int i=0; i<nbRows; i++)
                   {
             for (int j=0; j<nbCols; j++)
             {
                                         if (( (j%3)==0 )&&( (i%8)==0)) // set every 3rd column in every 8th row
{
                                                 *pubRaster++ = 255;
                                         }
                                         else
{
                                                 *pubRaster++ = 0;
                                         }
             }
                   }
         //      By default, the RasterImage class adopts the "safe" mode for the definition
         //      of the valid data rectangle.  Since image1 was just allocated not initialized,
         //      its valid data rectangle was located at the upper left corner of the bounding
         //      rectangle, with width and height 0.  We must now set the correct values.
         ptImage->setValidRect(0, 0, nbCols, nbRows);
     }
     else
     {
         printf("Generation of image 1 failed.");
     }
 }
void WXGL_IO_Canvas::MakeFake_ImageGS (RasterImage * ptImage)
Definition at line 477 of file WXGL_IO_canvas.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage::getRaster2D(), uriVL::DrawableObject2D::getWidth(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kLongGrayRaster, uriVL::R_W_ACCESS, and uriVL::DrawableObject2D::setValidRect().
 {
         int  nBytesPerPixel;
     //-------------------------------------------------------------
     //  Image 1 is created by computation --> fill the array with GS values
     //   This code fragment demonstrate how to get direct access to the image's
     //   raster for initialization and other IP calculations
          //
          //   This code was lifted from SimpleIO demo program
     //-------------------------------------------------------------
     //
     //  the raster image is created at the desired dimensions
     if (ptImage != NULL)
     {
                  // get base raster type so we know if to fill in alpha values
                  int nRasterType = ptImage->getBaseRasterType();
                  if (nRasterType==kBinaryRaster)
                  {
                          nBytesPerPixel=1;
                  }
                  else if (nRasterType==kGrayRaster)
                  {
                          nBytesPerPixel=1;
                  }
                  else if (nRasterType==kLongGrayRaster)
                  {
                          nBytesPerPixel=2;
                          return; // since this class does not exist yet
                  }
                  else
                  {
                          return; // error
                  }
         //  we get a reference to the image's base raster
         //  Here, we use the version of the getRaster family of functions that return a
         //  read-write reference
         unsigned char *const* rgba = ptImage->getRaster2D(R_W_ACCESS);
         int   nbRows = ptImage->getHeight(),
               nbCols = ptImage->getWidth();
         //  from this point on
         for (int i=0; i<nbRows; i++)
                   {
             for (int j=0, l=0; j<nbCols; j++, l+=nBytesPerPixel)
             {
                                          unsigned char ubTemp[3];
                 ubTemp[0] = static_cast<unsigned char>(i/4);
                 ubTemp[1] = static_cast<unsigned char>(j/4);
                 ubTemp[2] = static_cast<unsigned char>(floor(127*(cos(0.06*i)*sin(0.1*j)+0.5)));
                                          unsigned short uhTemp = ubTemp[0]/4 + ubTemp[1]/2 + ubTemp[2]/4;
                                          if (nBytesPerPixel==1)
{
                                                 rgba[i][l] = uhTemp;
                                          }
                                          else
{
                                                 rgba[i][l] = uhTemp/256;
                                                 rgba[i][l+1] = uhTemp&0xff;
                                          }
             }
                   }
         //      By default, the RasterImage class adopts the "safe" mode for the definition
         //      of the valid data rectangle.  Since image1 was just allocated not initialized,
         //      its valid data rectangle was located at the upper left corner of the bounding
         //      rectangle, with width and height 0.  We must now set the correct values.
         ptImage->setValidRect(0, 0, nbCols, nbRows);
     }
     else
     {
         printf("Generation of image 1 failed.");
     }
 } // end of MakeFake_ImageGS
void WXGL_IO_Canvas::MakeFake_ImageGSF (RasterImage * ptImage)
Definition at line 555 of file WXGL_IO_canvas.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::hasFloatRaster(), uriVL::kGrayRaster, uriVL::R_W_ACCESS, and uriVL::DrawableObject2D::setValidRect().
 {
         int  nBytesPerPixel;
     //-------------------------------------------------------------
     //  Image 1 is created by computation --> fill the array with GS values
     //   This code fragment demonstrate how to get direct access to the image's
     //   raster for initialization and other IP calculations
          //
          //   This code was lifted from SimpleIO demo program
     //-------------------------------------------------------------
     //
     //  the raster image is created at the desired dimensions
     if (ptImage != NULL)
     {
                  // get base raster type so we know if to fill in alpha values
                  int nRasterType = ptImage->getBaseRasterType();
                  if ((nRasterType==kGrayRaster) && (ptImage->hasFloatRaster()))
                  {
                          nBytesPerPixel=4;
                  }
                  else
                  {
                          return; // error if not a gray float raster
                  }
         //  we get a reference to the image's base raster
         //  Here, we use the version of the getRaster family of functions that return a
         //  read-write reference
         float *pixels = ((RasterImage_gray_F*)ptImage)->getGrayF(R_W_ACCESS);
                   int nThisPixel = 0;
                   int   nbRows = ptImage->getHeight(),
               nbCols = ptImage->getWidth();
         //  from this point on
         for (int i=0; i<nbRows; i++)
                   {
             for (int j=0, l=0; j<nbCols; j++, l+=nBytesPerPixel)
             {
                                          unsigned char ubTemp[3];
                 ubTemp[0] = static_cast<unsigned char>(i/4);
                 ubTemp[1] = static_cast<unsigned char>(j/4);
                 ubTemp[2] = static_cast<unsigned char>(floor(127*(cos(0.06*i)*sin(0.1*j)+0.5)));
                                          unsigned short uhTemp = ubTemp[0]/4 + ubTemp[1]/2 + ubTemp[2]/4;
                                          pixels[nThisPixel] = float(uhTemp/65536.0f);
                                          nThisPixel++;
             }
                   }
         //      By default, the RasterImage class adopts the "safe" mode for the definition
         //      of the valid data rectangle.  Since image1 was just allocated not initialized,
         //      its valid data rectangle was located at the upper left corner of the bounding
         //      rectangle, with width and height 0.  We must now set the correct values.
         ptImage->setValidRect(0, 0, nbCols, nbRows);
     }
     else
     {
         printf("Generation of image 1 failed.");
     }
 } // end of MakeFake_ImageGSF
void WXGL_IO_Canvas::MakeFake_ImageRGBa (RasterImage * ptImage)
Definition at line 402 of file WXGL_IO_canvas.cpp.
References uriVL::RasterImage::getBaseRasterType(), uriVL::DrawableObject2D::getHeight(), uriVL::RasterImage::getRaster2D(), uriVL::DrawableObject2D::getWidth(), uriVL::kaRGB32Raster, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::R_W_ACCESS, and uriVL::DrawableObject2D::setValidRect().
 {
         bool boFillAlpha;
         int  nBytesPerPixel;
     //-------------------------------------------------------------
     //  Image 1 is created by computation --> fill the array with RGBA values
     //   This code fragment demonstrate how to get direct access to the image's
     //   raster for initialization and other IP calculations
          //
          //   This code was lifted from SimpleIO demo program
     //-------------------------------------------------------------
     //
     //  the raster image is created at the desired dimensions
     if (ptImage != NULL)
     {
                  // get base raster type so we know if to fill in alpha values
                  int nRasterType = ptImage->getBaseRasterType();
                  if (nRasterType==kRGB24Raster)
                  {
                          boFillAlpha=false;
                          nBytesPerPixel=3;
                  }
                  else if (nRasterType==kRGBa32Raster)
                  {
                          boFillAlpha=true;
                          nBytesPerPixel=4;
                  }
                  else if (nRasterType==kaRGB32Raster)
                  {
                          //boFillAlpha=true;
                          //nBytesPerPixel=4;
                          return; // since this class does not exist yet
                  }
                  else
                  {
                          return; // error
                  }
         //  we get a reference to the image's base raster
         //  Here, we use the version of the getRaster family of functions that return a
         //  read-write reference
         unsigned char *const* rgba = ptImage->getRaster2D(R_W_ACCESS);
         int   nbRows = ptImage->getHeight(),
               nbCols = ptImage->getWidth();
         //  from this point on
         for (int i=0; i<nbRows; i++)
                   {
             for (int j=0, l=0; j<nbCols; j++, l+=nBytesPerPixel)
             {
                 rgba[i][l] = static_cast<unsigned char>(i/4);
                 rgba[i][l+1] = static_cast<unsigned char>(j/4);
                 rgba[i][l+2] = static_cast<unsigned char>(floor(127*(cos(0.06*i)*sin(0.1*j)+0.5)));
                                          if (boFillAlpha)
{
                                                 rgba[i][l+3] = static_cast<unsigned char>(255);
                                          }
             }
                   }
         //      By default, the RasterImage class adopts the "safe" mode for the definition
         //      of the valid data rectangle.  Since image1 was just allocated not initialized,
         //      its valid data rectangle was located at the upper left corner of the bounding
         //      rectangle, with width and height 0.  We must now set the correct values.
         ptImage->setValidRect(0, 0, nbCols, nbRows);
     }
     else
     {
         printf("Generation of image 1 failed.");
     }
 } // end of MakeFake_ImageRGBa
void WXGL_IO_Canvas::OnActivateEvent (wxActivateEvent & event)
Definition at line 188 of file WXGL_IO_canvas.cpp.
 {
         UpdateCanvas();
         event.Skip();
 }
void WXGL_IO_Canvas::OnCharEvent (wxKeyEvent & event)
Definition at line 244 of file WXGL_IO_canvas.cpp.
 {
         wxInt32 nCanvasWidth, nCanvasHeight;
         this->GetClientSize(&nCanvasWidth, &nCanvasHeight);
         wxFloat32 fAmt = 1.0f;
         wxInt32 nChar = event.GetKeyCode();
         switch (nChar)
         {
                 case WXK_PAGEDOWN:
                         // do nothing, just showing how to handle a special key
                         break;
                 case 'A':
                 case 'a':
                         // do nothing, just showing how to handle a letter key
                         break;
                 default:
                         // ignore character
                         break;
         } // End switch over input key char
         UpdateCanvas();
 }
bool WXGL_IO_Canvas::OnCloseCanvas ()
Definition at line 172 of file WXGL_IO_canvas.cpp.
Referenced by WXGL_IO_Frame::OnCloseWindow().
 {
     return true;
 }
void WXGL_IO_Canvas::OnFocusEvent (wxFocusEvent & event)
Definition at line 178 of file WXGL_IO_canvas.cpp.
 {
         UpdateCanvas();
 }
void WXGL_IO_Canvas::OnKillFocusEvent (wxFocusEvent & event)
Definition at line 183 of file WXGL_IO_canvas.cpp.
 {
         UpdateCanvas();
 }
void WXGL_IO_Canvas::OnMouseEvent (wxMouseEvent & event)
Definition at line 210 of file WXGL_IO_canvas.cpp.
 {
     int mouseX = (int)event.GetX();
     int mouseY = (int)event.GetY();
     if (event.LeftDClick())
     {
     }
     else if (event.LeftDown())
     {
     }
     else if (event.LeftUp())
     {
                 DrawSquare(mouseX, mouseY);
     }
     else if (event.RightDown() && !event.LeftIsDown())
     {
     }
     else if (event.Dragging())
     {
     }
     if (!event.LeftIsDown())
     {
     }
          // not doing UpdateCanvas so you can see how the mouse event handler works
          // remove the example code and do what you want here
          // then uncomment the UpdateCanvas() call below
          // UpdateCanvas();
 }
void WXGL_IO_Canvas::OnPaintEvent (wxPaintEvent & event)
Definition at line 201 of file WXGL_IO_canvas.cpp.
 {
         wxPaintDC dc(this);
         SetFocus();
         UpdateCanvas();
 }
void WXGL_IO_Canvas::OnShowEvent (wxShowEvent & event)
Definition at line 195 of file WXGL_IO_canvas.cpp.
 {
         UpdateCanvas();
 }
void WXGL_IO_Canvas::SetFileType (unsigned long ulFT) inline
Definition at line 79 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::TypeExtension().
 {mulFileType=ulFT;}
void WXGL_IO_Canvas::SetRasterType (unsigned long ulRT) inline
Definition at line 81 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::RasterType().
 {mulRasterType=ulRT;}
void WXGL_IO_Canvas::SetTestImageCols (unsigned long ulC) inline
Definition at line 77 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::ParamSize().
 {mulCols=ulC;}
void WXGL_IO_Canvas::SetTestImageRows (unsigned long ulR) inline
Definition at line 75 of file WXGL_IO_canvas.h.
Referenced by WXGL_IO_Frame::ParamSize().
 {mulRows=ulR;}
void WXGL_IO_Canvas::SetUpCamera (void)
Definition at line 387 of file WXGL_IO_canvas.cpp.
Referenced by WXGL_IO_Frame::InitCanvas().
 {
         // {fixme} this really needs to be size of canvas
         // but all I know is wxDisplaySize:)
         int nCanvasWidth, nCanvasHeight;
         wxDisplaySize(&nCanvasWidth, &nCanvasHeight);
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) nCanvasWidth, 0.0f, (GLfloat) nCanvasHeight);
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glViewport(0, 0, nCanvasWidth, nCanvasHeight);
 }
void WXGL_IO_Canvas::UpdateCanvas (void)
Definition at line 272 of file WXGL_IO_canvas.cpp.
Referenced by WXGL_IO_Frame::ParamSize(), WXGL_IO_Frame::RasterType(), and WXGL_IO_Frame::TypeExtension().
 {
         int nCanvasWidth, nCanvasHeight;
         this->GetClientSize(&nCanvasWidth, &nCanvasHeight);
         DrawableObject2D::setDefaultWindowDimensions(nCanvasWidth, nCanvasHeight);
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glClear(GL_COLOR_BUFFER_BIT);
         //glViewport(nX, nCanvasHeight-nY-gMyImage->getHeight()/2, gMyImage->getWidth(), gMyImage->getHeight());
         ImagePoint *ptPoint1 = new ImagePoint(50,50);
         pmtOriginalImage->render(ptPoint1);
         ImagePoint *ptPoint2 = new ImagePoint(50+10+pmtOriginalImage->getWidth(),50);
         pmtReadInImage->render(ptPoint2);
         SwapBuffers();
         SetCurrent();
 }
Member Data Documentation
unsigned long WXGL_IO_Canvas::mulCols protected
Definition at line 92 of file WXGL_IO_canvas.h.
unsigned long WXGL_IO_Canvas::mulFileType protected
Definition at line 93 of file WXGL_IO_canvas.h.
unsigned long WXGL_IO_Canvas::mulRasterType protected
Definition at line 93 of file WXGL_IO_canvas.h.
unsigned long WXGL_IO_Canvas::mulRows protected
Definition at line 92 of file WXGL_IO_canvas.h.
RasterImage* WXGL_IO_Canvas::pmtDifferenceImage protected
Definition at line 90 of file WXGL_IO_canvas.h.
DECLARE_EVENT_TABLE () private RasterImage* WXGL_IO_Canvas::pmtReadInImage protected
Definition at line 85 of file WXGL_IO_canvas.h.
The documentation for this class was generated from the following files:
WXGL_IO_canvas.h
WXGL_IO_canvas.cpp