URIVisionLibrary: uriVL::Function1D Class Reference
uriVL::Function1D Class Reference abstract
Pure virtual parent class for all 1-dimensional functions.
#include <Function1D.h>
Public Member Functions
Function1D (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Function1D (double xMin, double xMax)
Creates a new function defined over the interval ]xMin, xMax[.
virtual ~Function1D (void)
Destructor.
virtual double func (double x) const =0
Evaluates the function at the point specified.
virtual double dfunc (double x) const
Evaluates the first derivative of the function at the point specified.
double dfunc (double x, int n) const
Evaluates the first derivative of the function at the point specified.
virtual double d2func (double x) const
Evaluates the second derivative of the function at the point specified.
double getLowerBound (void) const
returns the lower bound of this function's domain of definition
double getUpperBound (void) const
returns the upper bound of this function's domain of definition
virtual bool firstDerivativeIsImplemented (void) const =0
Indicates whether the function implements its own first derivative function.
virtual bool secondDerivativeIsImplemented (void) const =0
Indicates whether the function implements its own second derivative function.
bool isDefinedAt (double x) const
Indicates whther a point is within the domain of definition of this function.
Private Attributes
double xMin_
lower bound of this function's domain of definition
double xMax_
upper bound of this function's domain of definition
bool isBounded_
True if finite bounds were set for the function.
Detailed Description
Pure virtual parent class for all 1-dimensional functions.
The function's actual implementation will be done in the child class and it will always be hard-coded.
Note that, contrary to a mathematical function, a Function is always defined on an interval that could be -∞ to +∞, but cannot have "holes" in it.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 35 of file Function1D.h.
Constructor & Destructor Documentation
Function1D::Function1D (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Definition at line 20 of file Function1D.cpp.
                 :       xMin_(-HUGE_VALF),
                         xMax_(HUGE_VALF),
                         isBounded_(false)
 {
 }
Function1D::Function1D (double xMin, double xMax)
Creates a new function defined over the interval ]xMin, xMax[.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
Definition at line 28 of file Function1D.cpp.
                 :       xMin_(xMin),
                         xMax_(xMax),
                         isBounded_(true)
 {
 }
Function1D::~Function1D (void) virtual
Destructor.
Definition at line 35 of file Function1D.cpp.
 {
 }
Member Function Documentation
double Function1D::d2func (double x) const virtual
Evaluates the second derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements the second-order difference approximation.
Parameters
x where the function should be evaluated
Returns
the derivative of the function at x
Reimplemented in uriVL::FunctionNDSection1D, and uriVL::PolynomialFunction1D.
Definition at line 77 of file Function1D.cpp.
References FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, and LARGE_RELATIVE_TOLERANCE.
Referenced by main().
 {
     FAIL_CONDITION( isBounded_&& !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D::d2func");
         const double DX = fabs(x) > LARGE_RELATIVE_TOLERANCE ? fabs(x)*LARGE_RELATIVE_TOLERANCE : LARGE_RELATIVE_TOLERANCE;
         return (func(x+ DX) - 2.0*func(x) + func(x-DX)) / (DX*DX);
 }
double Function1D::dfunc (double x) const virtual
Evaluates the first derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements the second-order central difference approximation
Parameters
x where the function should be evaluated
Returns
the derivative of the function at x
Reimplemented in uriVL::FunctionNDSection1D, uriVL::PolynomialFunction1D, MyFunction1D, and OtherFunction1D.
Definition at line 51 of file Function1D.cpp.
References FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, and LARGE_RELATIVE_TOLERANCE.
Referenced by main().
 {
     FAIL_CONDITION( isBounded_ && !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D::dfunc");
         const double DX = fabs(x) > LARGE_RELATIVE_TOLERANCE ? fabs(x)*LARGE_RELATIVE_TOLERANCE : LARGE_RELATIVE_TOLERANCE;
         return (0.5*(func(x+ DX) - func(x-DX))/DX);
 }
double Function1D::dfunc (double x, int n) const
Evaluates the first derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements an n-th order Richardson interpolation.
Parameters
x where the function should be evaluated
n the degree of the Richardson approximation (n=1 is the basic
Returns
the derivative of the function at x
Definition at line 63 of file Function1D.cpp.
References FAIL_CONDITION, isBounded_, isDefinedAt(), uriVL::kDataRangeError, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     FAIL_CONDITION( isBounded_ && !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D::dfunc");
    return HUGE_VAL;
 }
virtual bool uriVL::Function1D::firstDerivativeIsImplemented (void) const pure virtual
Indicates whether the function implements its own first derivative function.
Returns
true if the function implements its own derivative function
Implemented in uriVL::FunctionNDSection1D, uriVL::PolynomialFunction1D, MyFunction1D, OtherFunction1D, and YetAnotherFunction1D.
virtual double uriVL::Function1D::func (double x) const pure virtual
Evaluates the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implemented in uriVL::FunctionNDSection1D, uriVL::PolynomialFunction1D, MyFunction1D, OtherFunction1D, and YetAnotherFunction1D.
Referenced by d2func(), dfunc(), uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), uriVL::NonlinearOptimizer1D_parab::initSearchBracket_(), uriVL::NonlinearOptimizer1D_Brent::initSearchBracket_(), main(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
double Function1D::getLowerBound (void) const
returns the lower bound of this function's domain of definition
Definition at line 93 of file Function1D.cpp.
References xMin_.
Referenced by uriVL::NonlinearOptimizer1D_Brent::minimize_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
 {
     return xMin_;
 }
double Function1D::getUpperBound (void) const
returns the upper bound of this function's domain of definition
Definition at line 99 of file Function1D.cpp.
References xMax_.
Referenced by uriVL::NonlinearOptimizer1D_Brent::minimize_(), and uriVL::NonlinearOptimizer1D_gss::minimize_().
 {
     return xMax_;
 }
bool Function1D::isDefinedAt (double x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
Definition at line 44 of file Function1D.cpp.
References xMax_, and xMin_.
Referenced by uriVL::PolynomialFunction1D::d2func(), d2func(), dfunc(), uriVL::PolynomialFunction1D::dfunc(), uriVL::PolynomialFunction1D::dnfunc(), uriVL::PolynomialFunction1D::func(), and uriVL::NonlinearOptimizer1D::minimize().
 {
     return (x >= xMin_) && (x <= xMax_);
 }
virtual bool uriVL::Function1D::secondDerivativeIsImplemented (void) const pure virtual
Indicates whether the function implements its own second derivative function.
Returns
true if the function implements its own derivative function
Implemented in uriVL::FunctionNDSection1D, uriVL::PolynomialFunction1D, MyFunction1D, OtherFunction1D, and YetAnotherFunction1D.
Member Data Documentation
bool uriVL::Function1D::isBounded_ private
True if finite bounds were set for the function.
Definition at line 129 of file Function1D.h.
Referenced by d2func(), and dfunc().
double uriVL::Function1D::xMax_ private
upper bound of this function's domain of definition
Definition at line 125 of file Function1D.h.
Referenced by getUpperBound(), and isDefinedAt().
double uriVL::Function1D::xMin_ private
lower bound of this function's domain of definition
Definition at line 121 of file Function1D.h.
Referenced by getLowerBound(), and isDefinedAt().
The documentation for this class was generated from the following files:
Function1D.h
Function1D.cpp