URIVisionLibrary: uriVL::Cone3D Class Reference
uriVL::Cone3D Class Reference
Cone3D class.
#include <Cone3D.h>
Public Member Functions
Cone3D (GLfloat *origin, GLfloat **axes, bool isClosed)
Constructor.
Cone3D (GLfloat *origin, GLfloat **botAxes, GLfloat *dirAxis, GLfloat **topAxes, bool isClosed)
Constructor.
Cone3D (GLfloat *origin, GLfloat *dirAxis, GLfloat bottomRadius, GLfloat topRadius, bool isClosed)
Constructor.
~Cone3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
Cone3D (const Cone3D &obj)
Copy constructor (disabled)
const Cone3D & operator= (const Cone3D &obj)
Copy operator: disabled.
void init_ (GLfloat *origin, GLfloat **axes)
Initialize the cone.
void init_ (GLfloat *origin, GLfloat **botAxes, GLfloat *dirAxis, GLfloat **topAxes)
Initialize the cone.
void deleteArrays_ (void)
Delete all allocated arrays.
Static Private Member Functions
static void initStatic_ (void)
Initializes the classe's static variables.
Private Attributes
GLfloat *** vertex_
0-based list of vertices
GLfloat ** normal_
0-based list of normals
GLfloat normalTop_ [3]
Normal to the top face.
GLfloat normalBottom_ [3]
Normal to the bottom face.
int circStep_
Display resolution along a circular/elliptic face.
int slabStep_
Display resolution along a slab (main axis)
bool closedBottom_
Is the bottom face drawn?
bool closedTop_
Is the top face drawn?
Static Private Attributes
static bool initCtSt_ = false
Have the static variables been initialized?
static GLfloat ct_ [kVeryHighDefCircPts]
Precomputed array of cosine values.
static GLfloat st_ [kVeryHighDefCircPts]
Precomputed array of sine values.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
Cone3D class.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 44 of file Cone3D.h.
Constructor & Destructor Documentation
Cone3D::Cone3D (GLfloat * origin, GLfloat ** axes, bool isClosed)
Constructor.
Creates a pointed cone from the location of its origin, the directions of the 2 axes of its elliptic bottom face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
isClosed true if the cone's bottom face should be drawn
Definition at line 48 of file Cone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), init_(), initCtSt_, and initStatic_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(isClosed),
                         closedTop_(false)
 {
         if (!initCtSt_)
                 initStatic_();
         try {
                 init_(origin, axes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from Cone3D constructor.");
                 throw e;
         }
 }
Cone3D::Cone3D (GLfloat * origin, GLfloat ** botAxes, GLfloat * dirAxis, GLfloat ** topAxes, bool isClosed)
Constructor.
Creates a truncated cone from the location of its origin, the directions of the 2 axes of its elliptic bottom face, that of its elliptic top face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
botAxes the 2 axes of the cone bottom face
dirAxis the direction of the cone's main axis
topAxes the 2 axes of the cone's top face
isClosed true if the cone's top and bottom faces should be drawn
Definition at line 84 of file Cone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), init_(), initCtSt_, and initStatic_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(isClosed),
                         closedTop_(isClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         try {
                 init_(origin, botAxes, dirAxis, topAxes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from Cone3D constructor.");
                 throw e;
         }
 }
Cone3D::Cone3D (GLfloat * origin, GLfloat * dirAxis, GLfloat bottomRadius, GLfloat topRadius, bool isClosed)
Constructor.
Creates a truncated circular cone from the loation of its origin, direction of main axis, and radii of top and bottom faces.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
dirAxis the direction of the cone's main axis
bottomRadius the radius of the cone's circular bottom face
topRadius the radius of the cone's circular top face
isClosed true if the cone's top and bottom faces should be drawn
Definition at line 122 of file Cone3D.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::GraphicComponent3D::commonNormalVector(), deleteArrays_(), FAIL_CONDITION, uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), init_(), initCtSt_, initStatic_(), and uriVL::kInvalidParameterError.
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedBottom_(isClosed),
                         closedTop_(isClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         GLfloat         **botAxes, **topAxes, w[3];
         botAxes = GlUtils::glfMatrix(0, 2, 0, 2);
         topAxes = GlUtils::glfMatrix(0, 2, 0, 2);
         try {
                 //      For the major axis, we need to build a vector orthogonal to dirAxis.
                 if ((dirAxis[0]!= 0.f) || (dirAxis[2]!= 0.f))   //      this is not the local Y axis
                 {
                         w[0] = 0.f; w[1] = 1.f; w[2] = 0.f;
                         commonNormalVector(w, dirAxis, botAxes[0]);                             //      "X" = "Y" x "Z"
                         commonNormalVector(dirAxis, botAxes[0], botAxes[1]);    //      "Y" = "Z" x "X"
                         //
                         //      and now we can multiply by the radius
                         for (int i=0; i<3; i++)
{
                                 topAxes[0][i] = botAxes[0][i]*topRad;
                                 topAxes[1][i] = botAxes[1][i]*topRad;
                                 //
                                 botAxes[0][i] *= bottomRad;
                                 botAxes[1][i] *= bottomRad;
                         }
                 }
                 //      if dirAxis was the local Y axis, then I can take Z and X as major and minor
                 else
                 {
                         topAxes[0][0] = topAxes[0][1] = topAxes[1][1] = topAxes[1][2] = 0.f;
                         botAxes[0][0] = botAxes[0][1] = botAxes[1][1] = botAxes[1][2] = 0.f;
                         topAxes[0][2] = topAxes[1][0] = topRad;
                         botAxes[0][2] = botAxes[1][0] = bottomRad;
                 }
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
                 GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to Cone3D constructor");
         }
         try {
                 init_(origin, botAxes, dirAxis, topAxes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
                 GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
                 e.appendToMessage("called from Cone3D constructor.");
                 throw e;
         }
         GlUtils::free_glfMatrix(topAxes, 0, 2, 0, 2);
         GlUtils::free_glfMatrix(botAxes, 0, 2, 0, 2);
 }
Cone3D::~Cone3D (void)
Destructor.
Definition at line 217 of file Cone3D.cpp.
References deleteArrays_().
 {
         deleteArrays_();
 }
Cone3D::Cone3D (const Cone3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 193 of file Cone3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         circStep_(kCoarseResolution),
                         slabStep_(kCoarseResolution),
                         closedBottom_(false),
                         closedTop_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cone3D copy constructor not implemented.");
 }
Member Function Documentation
void Cone3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 540 of file Cone3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, and vertex_.
Referenced by Cone3D(), and ~Cone3D().
 {
         if (vertex_!=NULL)
         {
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         GlUtils::free_glfMatrix(vertex_[i], 0,  kVeryHighDefCircPts-1, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (normal_!=NULL)
         {
                 GlUtils::free_glfMatrix(normal_, 0,  kVeryHighDefCircPts-1, 0, 2);
                 normal_ = NULL;
         }
 }
void Cone3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 343 of file Cone3D.cpp.
References circStep_, closedBottom_, closedTop_, uriVL::GraphicComponent3D::draw(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, normalBottom_, normalTop_, slabStep_, and vertex_.
 {
         GraphicComponent3D::draw();
         for (int i=0; i<=kVeryHighDefSlabs-slabStep_; i+=slabStep_)
         {
                 glBegin(GL_TRIANGLE_STRIP);
                         for (int j=0; j<kVeryHighDefCircPts; j+=circStep_)
{
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i+slabStep_][j]);
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i][j]);
                         }
                         glNormal3fv(normal_[0]);
                         glVertex3fv(vertex_[i+slabStep_][0]);
                         glNormal3fv(normal_[0]);
                         glVertex3fv(vertex_[i][0]);
                 glEnd();
         }
         if (closedTop_)
         {
                 glNormal3fv(normalTop_);
                 glBegin(GL_POLYGON);
                         for (int j=0; j<kVeryHighDefCircPts; j+=circStep_)
                                 glVertex3fv(vertex_[kVeryHighDefSlabs][j]);
                 glEnd();
         }
         if (closedBottom_)
         {
                 glNormal3fv(normalBottom_);
                 glBegin(GL_POLYGON);
                         for (int j=kVeryHighDefCircPts-circStep_; j>=0; j-=circStep_)
                                 glVertex3fv(vertex_[0][j]);
                 glEnd();
         }
 }
void Cone3D::init_ (GLfloat * origin, GLfloat ** axes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
Definition at line 409 of file Cone3D.cpp.
References closedBottom_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), ct_, kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, normalBottom_, uriVL::GraphicComponent3D::normalizeVector(), st_, and vertex_.
Referenced by Cone3D().
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         d[3],
                         //      The summit of the cone is = origin + axes[2]
                         summit[3] = {   origin[0] + a[2][0],
                                                         origin[1] + a[2][1],
                                                         origin[2] + a[2][2]},
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radial_j[3],
                         majCross[3], minCross[3];
         //      majCross = a[0] x a[2] (major axis x direction)
         crossProduct(a[0], a[2], majCross);
         //      minCross = a[1] x a[2] (minor axis x direction)
         crossProduct(a[1], a[2], minCross);
         for (int j=0; j< kVeryHighDefCircPts; j++)
         {
                 for (int k=0; k<3; k++)
                 {
                         //      coordinates of the radial vector for that angle
                         radial_j[k] = ct_[j]*a[0][k] + st_[j]*a[1][k];
                         //      coordinates of the bottom point for that angle
                         vertex_[0][j][k] = origin[k] + radial_j[k];
                         //      the "top vertex" is at the summit of the cone
                         vertex_[kVeryHighDefSlabs][j][k] = summit[k];
                         //      coordinates of the "step displacement towards the summit.
                         d[k] = dirStep*(a[2][k] - radial_j[k]);
                         //      coordinates of the normal vector for that angle
                         normal_[j][k] = ct_[j]*minCross[k] - st_[j]*majCross[k];
                 }
                 normalizeVector(normal_[j]);
                 for (int i=1; i<kVeryHighDefSlabs; i++)
                 {
                         vertex_[i][j][0] = vertex_[i-1][j][0] + d[0];
                         vertex_[i][j][1] = vertex_[i-1][j][1] + d[1];
                         vertex_[i][j][2] = vertex_[i-1][j][2] + d[2];
                 }
         }
         //      if this is a closed cone, then we must also compute the normal
         //      vector for the bottom face.
         //      normalBottom = -major x minor / ||major x minor||
         //
         if (closedBottom_)
                 commonNormalVector(a[1], a[0], normalBottom_);
 }
void Cone3D::init_ (GLfloat * origin, GLfloat ** botAxes, GLfloat * dirAxis, GLfloat ** topAxes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
botAxes the 2 axes of the cone bottom face
dirAxis the direction of the cones main axis
topAxes the 2 axes of the cone top face
Definition at line 483 of file Cone3D.cpp.
References closedBottom_, closedTop_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), ct_, uriVL::GlUtils::glfMatrix(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, normalBottom_, uriVL::GraphicComponent3D::normalizeVector(), normalTop_, st_, and vertex_.
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radialTop_j[3], radialBot_j[3],
                         d[3],
                         majCross[3], minCross[3];
         GLfloat origTop[3] = {  origin[0] + dirAxis[0],
                                                         origin[1] + dirAxis[1],
                                                         origin[2] + dirAxis[2]};
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2);
         for (int j=0; j< kVeryHighDefCircPts; j++)
         {
                 for (int k=0; k<3; k++)
                 {
                         radialTop_j[k] = ct_[j]*topAxes[0][k] + st_[j]*topAxes[1][k];
                         radialBot_j[k] = ct_[j]*botAxes[0][k] + st_[j]*botAxes[1][k];
                         vertex_[0][j][k] = origin[k] + radialBot_j[k];
                         vertex_[kVeryHighDefSlabs][j][k] = origTop[k] + radialTop_j[k];
                         d[k] = dirStep*(vertex_[kVeryHighDefSlabs][j][k] - vertex_[0][j][k]);
                 }
                 //      Ready to compute the coordinates of the cones "inner" vertices
                 for (int i=1; i<kVeryHighDefSlabs; i++)
                 {
                         vertex_[i][j][0] = vertex_[i-1][j][0] + d[0];
                         vertex_[i][j][1] = vertex_[i-1][j][1] + d[1];
                         vertex_[i][j][2] = vertex_[i-1][j][2] + d[2];
                 }
                 //       We can also compute the normal vector for each angular section of the cone
                 crossProduct(botAxes[0], d, majCross);
                 crossProduct(botAxes[1], d, minCross);
                 for (int k=0; k<3; k++)
                         normal_[j][k] = ct_[j]*minCross[k] - st_[j]*majCross[k];
                 //
                 normalizeVector(normal_[j]);
         }
         //      if this is a closed cone, then we must also compute the normal
         //      vector for the top and bottom faces.
         if (closedTop_)
                 //      normalTop = major x minor / ||major x minor||
                 commonNormalVector(topAxes[0], topAxes[1], normalTop_);
         //
         if (closedBottom_)
                 //      normalBottom = -major x minor / ||major x minor||
                 commonNormalVector(botAxes[1], botAxes[0], normalBottom_);
 }
void Cone3D::initStatic_ (void) static private
Initializes the classe's static variables.
Definition at line 568 of file Cone3D.cpp.
References ct_, initCtSt_, kVeryHighDefCircPts, PI, and st_.
Referenced by Cone3D().
 {
         GLfloat dTheta = static_cast<GLfloat>(2.f*PI/kVeryHighDefCircPts);
         for (int j=0; j<kVeryHighDefCircPts; j++)
         {
                 ct_[j] = cosf(j*dTheta);
                 st_[j] = sinf(j*dTheta);
         }
         initCtSt_ = true;
 }
const Cone3D & Cone3D::operator= (const Cone3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 222 of file Cone3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cone3D copy operator not implemented.");
         return *this;
 }
void Cone3D::setResolution (ResolutionLevel res) virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 252 of file Cone3D.cpp.
 {
         setResolution(res, res);
 }
void Cone3D::setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
Parameters
circRes resolution to assign along a circular/elliptic face
slabRes resolution to assign along the main axis
Definition at line 273 of file Cone3D.cpp.
References circStep_, kCoarseDefCircScale, kCoarseDefSlabScale, uriVL::kCoarseResolution, kFineDefCircScale, kFineDefSlabScale, uriVL::kFineResolution, kMediumDefCircScale, kMediumDefSlabScale, uriVL::kMediumResolution, uriVL::kVeryHighResolution, kVeryLowDefCircScale, kVeryLowDefSlabScale, uriVL::kVeryLowResolution, and slabStep_.
 {
         switch (circRes)
         {
                 case kVeryHighResolution:
                         circStep_ = 1;
                         break;
                 case kFineResolution:
                         circStep_ = kFineDefCircScale;
                         break;
                 case kMediumResolution:
                         circStep_ = kMediumDefCircScale;
                         break;
                 case kCoarseResolution:
                         circStep_ = kCoarseDefCircScale;
                         break;
                 case kVeryLowResolution:
                         circStep_ = kVeryLowDefCircScale;
                         break;
                 default:
                         circStep_ = kMediumDefCircScale;
                         break;
         }
         switch (slabRes)
         {
                 case kVeryHighResolution:
                         slabStep_ = 1;
                         break;
                 case kFineResolution:
                         slabStep_ = kFineDefSlabScale;
                         break;
                 case kMediumResolution:
                         slabStep_ = kMediumDefSlabScale;
                         break;
                 case kCoarseResolution:
                         slabStep_ = kCoarseDefSlabScale;
                         break;
                 case kVeryLowResolution:
                         slabStep_ = kVeryLowDefSlabScale;
                         break;
                 default:
                         slabStep_ = kMediumDefSlabScale;
                         break;
         }
 }
Member Data Documentation
int uriVL::Cone3D::circStep_ private
Display resolution along a circular/elliptic face.
Definition at line 120 of file Cone3D.h.
Referenced by draw(), and setResolution().
bool uriVL::Cone3D::closedBottom_ private
Is the bottom face drawn?
Definition at line 128 of file Cone3D.h.
Referenced by draw(), and init_().
bool uriVL::Cone3D::closedTop_ private
Is the top face drawn?
Definition at line 132 of file Cone3D.h.
Referenced by draw(), and init_().
GLfloat Cone3D::ct_ static private
Precomputed array of cosine values.
Definition at line 140 of file Cone3D.h.
Referenced by init_(), and initStatic_().
bool Cone3D::initCtSt_ = false static private
Have the static variables been initialized?
Definition at line 136 of file Cone3D.h.
Referenced by Cone3D(), and initStatic_().
GLfloat** uriVL::Cone3D::normal_ private
0-based list of normals
Definition at line 108 of file Cone3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::Cone3D::normalBottom_[3] private
Normal to the bottom face.
Definition at line 116 of file Cone3D.h.
Referenced by draw(), and init_().
GLfloat uriVL::Cone3D::normalTop_[3] private
Normal to the top face.
Definition at line 112 of file Cone3D.h.
Referenced by draw(), and init_().
int uriVL::Cone3D::slabStep_ private
Display resolution along a slab (main axis)
Definition at line 124 of file Cone3D.h.
Referenced by draw(), and setResolution().
GLfloat Cone3D::st_ static private
Precomputed array of sine values.
Definition at line 144 of file Cone3D.h.
Referenced by init_(), and initStatic_().
GLfloat*** uriVL::Cone3D::vertex_ private
0-based list of vertices
Definition at line 104 of file Cone3D.h.
Referenced by deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
Cone3D.h
Cone3D.cpp