URIVisionLibrary: SimpleFunction1D Class Reference
SimpleFunction1D Class Reference
Examle of a 1D function to test the optimizer with.
#include <SimpleFunction1D.h>
Public Member Functions
SimpleFunction1D (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
~SimpleFunction1D (void)
Destructor.
float func (float x) const
Evaluates the function at the point specified.
bool firstDerivativeIsImplemented (void) const
Indicates that the function implements its own first derivative function.
bool secondDerivativeIsImplemented (void) const
Indicates whether the function implements its own second derivative function.
Public Member Functions inherited from uriVL::Function1D_F
Function1D_F (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Function1D_F (float xMin, float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
virtual ~Function1D_F (void)
Destructor.
virtual float dfunc (float x) const
Evaluates the first derivative of the function at the point specified.
virtual float dfunc (float x, int n) const
Evaluates the first derivative of the function at the point specified.
virtual float d2func (float x) const
Evaluates the second derivative of the function at the point specified.
float getLowerBound (void) const
returns the lower bound of this function's domain of definition
float getUpperBound (void) const
returns the upper bound of this function's domain of definition
bool isDefinedAt (float x) const
Indicates whther a point is within the domain of definition of this function.
Additional Inherited Members
Protected Attributes inherited from uriVL::Function1D_F
float xMin_
lower bound of this function's domain of definition
float xMax_
upper bound of this function's domain of definition
bool isBounded_
True if finite bounds were set for the function.
Detailed Description
Examle of a 1D function to test the optimizer with.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 25 of file SimpleFunction1D.h.
Constructor & Destructor Documentation
SimpleFunction1D::SimpleFunction1D (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Definition at line 33 of file SimpleFunction1D.cpp.
     :   Function1D_F()
 {
 }
SimpleFunction1D::~SimpleFunction1D (void)
Destructor.
Definition at line 39 of file SimpleFunction1D.cpp.
 {
 }
Member Function Documentation
bool SimpleFunction1D::firstDerivativeIsImplemented (void) const inline virtual
Indicates that the function implements its own first derivative function.
Returns
true
Implements uriVL::Function1D_F.
Definition at line 49 of file SimpleFunction1D.h.
                 {
                         return false;
                 }
float SimpleFunction1D::func (float x) const virtual
Evaluates the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implements uriVL::Function1D_F.
Definition at line 43 of file SimpleFunction1D.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::Function1D_F::isDefinedAt(), uriVL::kDataRangeError, and uriVL::kNumericalError.
Referenced by main().
 {
         //-----------------------------------------------------
         //      Optional:  If you want to play it safe
         //-----------------------------------------------------
         bool isDefined = false;
         try
         {
                 isDefined = isDefinedAt(x);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by SimpleFunction1D::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in SimpleFunction1D::func");
         }
     FAIL_CONDITION( !isDefined,
                     kDataRangeError,
                     "x not within domain of definition in SimpleFunction1D::func");
         //-----------------------------------------------------
         //      Then evaluate the function at x
         //-----------------------------------------------------
     return (1.0f + (cosf(0.2f*x)/sqrtf(fabsf(x+12.f)+1.f)))*(x/6.f - 3.f)*(x/6.f - 3.f) -
                 sqrtf(fabsf(0.5f*x + 1.f));
 }
bool SimpleFunction1D::secondDerivativeIsImplemented (void) const inline virtual
Indicates whether the function implements its own second derivative function.
Returns
true
Implements uriVL::Function1D_F.
Definition at line 57 of file SimpleFunction1D.h.
                 {
                         return false;
                 }
The documentation for this class was generated from the following files:
SimpleFunction1D.h
SimpleFunction1D.cpp