URIVisionLibrary: uriVL::Function1D_F Class Reference
uriVL::Function1D_F Class Reference abstract
Pure virtual parent class for all 1-dimensional functions.
#include <Function1D_F.h>
Public Member Functions
Function1D_F (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Function1D_F (float xMin, float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
virtual ~Function1D_F (void)
Destructor.
virtual float func (float x) const =0
Evaluates the function at the point specified.
virtual float dfunc (float x) const
Evaluates the first derivative of the function at the point specified.
virtual float dfunc (float x, int n) const
Evaluates the first derivative of the function at the point specified.
virtual float d2func (float x) const
Evaluates the second derivative of the function at the point specified.
float getLowerBound (void) const
returns the lower bound of this function's domain of definition
float getUpperBound (void) const
returns the upper bound of this function's domain of definition
virtual bool firstDerivativeIsImplemented (void) const =0
Indicates whether the function implements its own first derivative function.
virtual bool secondDerivativeIsImplemented (void) const =0
Indicates whether the function implements its own second derivative function.
bool isDefinedAt (float x) const
Indicates whther a point is within the domain of definition of this function.
Protected Attributes
float xMin_
lower bound of this function's domain of definition
float xMax_
upper bound of this function's domain of definition
bool isBounded_
True if finite bounds were set for the function.
Detailed Description
Pure virtual parent class for all 1-dimensional functions.
The function's actual implementation will be done in the child class and it will always be hard-coded.
Note that, contrary to a mathematical function, a Function is always defined on an interval that could be -∞ to +∞, but cannot have "holes" in it.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 35 of file Function1D_F.h.
Constructor & Destructor Documentation
Function1D_F::Function1D_F (void)
Creates a new function defined over the set of real numbers, ]-infinity, +infinity[.
Definition at line 20 of file Function1D_F.cpp.
                 :       xMin_(-HUGE_VALF),
                         xMax_(HUGE_VALF),
                         isBounded_(false)
 {
 }
Function1D_F::Function1D_F (float xMin, float xMax)
Creates a new function defined over the interval ]xMin, xMax[.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
Definition at line 28 of file Function1D_F.cpp.
                 :       xMin_(xMin),
                         xMax_(xMax),
                         isBounded_(false)
 {
 }
Function1D_F::~Function1D_F (void) virtual
Destructor.
Definition at line 35 of file Function1D_F.cpp.
 {
 }
Member Function Documentation
float Function1D_F::d2func (float x) const virtual
Evaluates the second derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements the second-order difference approximation.
Parameters
x where the function should be evaluated
Returns
the derivative of the function at x
Reimplemented in uriVL::FunctionNDSection1D_F, and uriVL::PolynomialFunction1D_F.
Definition at line 77 of file Function1D_F.cpp.
References FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, and LARGE_RELATIVE_TOLERANCE_F.
Referenced by main().
 {
     FAIL_CONDITION( isBounded_ && !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D_F::d2func");
         const float DX = fabsf(x) > LARGE_RELATIVE_TOLERANCE_F ? fabsf(x)*LARGE_RELATIVE_TOLERANCE_F : LARGE_RELATIVE_TOLERANCE_F;
         return (func(x+ DX) - 2.f*func(x) + func(x-DX)) / (DX*DX);
 }
float Function1D_F::dfunc (float x) const virtual
Evaluates the first derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements the second-order central difference approximation
Parameters
x where the function should be evaluated
Returns
the derivative of the function at x
Reimplemented in uriVL::FunctionNDSection1D_F, and uriVL::PolynomialFunction1D_F.
Definition at line 51 of file Function1D_F.cpp.
References FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, and LARGE_RELATIVE_TOLERANCE_F.
Referenced by main().
 {
     FAIL_CONDITION( isBounded_ && !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D_F::dfunc");
         const float DX = fabsf(x) > LARGE_RELATIVE_TOLERANCE_F ? fabsf(x)*LARGE_RELATIVE_TOLERANCE_F : LARGE_RELATIVE_TOLERANCE_F;
         return (0.5f*(func(x+ DX) - func(x-DX))/DX);
 }
float Function1D_F::dfunc (float x, int n) const virtual
Evaluates the first derivative of the function at the point specified.
If the subclass does not implement its own derivative, then this function will be called instead, which implements an n-th order Richardson interpolation.
Parameters
x where the function should be evaluated
n the degree of the Richardson approximation (n=1 is the basic
Returns
the derivative of the function at x
Definition at line 63 of file Function1D_F.cpp.
References FAIL_CONDITION, HUGE_VALF, isBounded_, isDefinedAt(), uriVL::kDataRangeError, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
     FAIL_CONDITION( isBounded_ && !isDefinedAt(x),
                     kDataRangeError,
                     "x not within domain of definition in Function1D_F::dfunc");
    return HUGE_VALF;
 }
virtual bool uriVL::Function1D_F::firstDerivativeIsImplemented (void) const pure virtual
Indicates whether the function implements its own first derivative function.
Returns
true if the function implements its own derivative function
Implemented in uriVL::PolynomialFunction1D_F, uriVL::FunctionNDSection1D_F, and SimpleFunction1D.
virtual float uriVL::Function1D_F::func (float x) const pure virtual
Evaluates the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implemented in uriVL::FunctionNDSection1D_F, uriVL::PolynomialFunction1D_F, and SimpleFunction1D.
Referenced by d2func(), dfunc(), uriVL::NonlinearOptimizer1D_gss::initSearchBracket_(), uriVL::NonlinearOptimizer1D_parab::initSearchBracket_(), uriVL::NonlinearOptimizer1D_Brent::initSearchBracket_(), main(), uriVL::NonlinearOptimizer1D_gss::minimize_(), and uriVL::NonlinearOptimizer1D_parab::minimize_().
float Function1D_F::getLowerBound (void) const
returns the lower bound of this function's domain of definition
Definition at line 94 of file Function1D_F.cpp.
References xMin_.
Referenced by uriVL::NonlinearOptimizer1D_Brent::minimize_(), uriVL::NonlinearOptimizer1D_gss::minimize_(), and uriVL::NonlinearOptimizer1D_parab::minimize_().
 {
     return xMin_;
 }
float Function1D_F::getUpperBound (void) const
returns the upper bound of this function's domain of definition
Definition at line 100 of file Function1D_F.cpp.
References xMax_.
Referenced by uriVL::NonlinearOptimizer1D_Brent::minimize_(), uriVL::NonlinearOptimizer1D_gss::minimize_(), and uriVL::NonlinearOptimizer1D_parab::minimize_().
 {
     return xMax_;
 }
bool Function1D_F::isDefinedAt (float x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
Definition at line 44 of file Function1D_F.cpp.
References xMax_, and xMin_.
Referenced by uriVL::PolynomialFunction1D_F::d2func(), d2func(), dfunc(), uriVL::PolynomialFunction1D_F::dfunc(), uriVL::PolynomialFunction1D_F::dnfunc(), SimpleFunction1D::func(), uriVL::PolynomialFunction1D_F::func(), and uriVL::NonlinearOptimizer1D::minimize().
 {
     return (x >= xMin_) && (x <= xMax_);
 }
virtual bool uriVL::Function1D_F::secondDerivativeIsImplemented (void) const pure virtual
Indicates whether the function implements its own second derivative function.
Returns
true if the function implements its own derivative function
Implemented in uriVL::PolynomialFunction1D_F, uriVL::FunctionNDSection1D_F, and SimpleFunction1D.
Member Data Documentation
bool uriVL::Function1D_F::isBounded_ protected
True if finite bounds were set for the function.
Definition at line 128 of file Function1D_F.h.
Referenced by d2func(), and dfunc().
float uriVL::Function1D_F::xMax_ protected
upper bound of this function's domain of definition
Definition at line 124 of file Function1D_F.h.
Referenced by getUpperBound(), and isDefinedAt().
float uriVL::Function1D_F::xMin_ protected
lower bound of this function's domain of definition
Definition at line 120 of file Function1D_F.h.
Referenced by getLowerBound(), and isDefinedAt().
The documentation for this class was generated from the following files:
Function1D_F.h
Function1D_F.cpp