URIVisionLibrary: uriVL::Cylinder3D Class Reference
uriVL::Cylinder3D Class Reference
Cylinder3D class.
#include <Cylinder3D.h>
Public Member Functions
Cylinder3D (GLfloat *origin, GLfloat **axes, bool isClosed)
Constructor.
Cylinder3D (GLfloat *origin, GLfloat *dirAxis, GLfloat radius, bool isClosed)
Constructor.
~Cylinder3D (void)
Destructor.
void setResolution (ResolutionLevel res)
Assigns a new drawing resolution to the object.
void setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
void draw (void)
Draw the object in the current graphic context.
Public Member Functions inherited from uriVL::GraphicComponent3D
virtual ~GraphicComponent3D (void)
Destructor.
void setMaterial (float params[])
void setMaterial (GLfloat ambRed, GLfloat ambGreen, GLfloat ambBlue, GLfloat difRed, GLfloat difGreen, GLfloat difBlue, GLfloat specRed, GLfloat specGreen, GLfloat specBlue, GLfloat shine)
Private Member Functions
Cylinder3D (const Cylinder3D &obj)
Copy constructor (disabled)
const Cylinder3D & operator= (const Cylinder3D &obj)
Copy operator: disabled.
void init_ (GLfloat *origin, GLfloat **axes)
Initialize the cone.
void init_ (GLfloat *origin, GLfloat **botAxes, GLfloat *dirAxis, GLfloat **topAxes)
Initialize the cone.
void deleteArrays_ (void)
Delete all allocated arrays.
Static Private Member Functions
static void initStatic_ (void)
Initializes the classe's static variables.
Private Attributes
GLfloat *** vertex_
0-based list of vertices
GLfloat ** normal_
0-based list of normals
GLfloat normalTop_ [3]
Normal to the top faced.
GLfloat normalBottom_ [3]
Normal to the bottom faced.
int circStep_
Display resolution along a circular/elliptic face.
int slabStep_
Display resolution along a slab (main axis)
bool closedCyl_
Are the top and bottom faces drawn?
Static Private Attributes
static bool initCtSt_ = false
Have the static variables been initialized?
static GLfloat ct_ [kVeryHighDefCircPts]
Precomputed array of cosine values.
static GLfloat st_ [kVeryHighDefCircPts]
Precomputed array of sine values.
Additional Inherited Members
Static Public Member Functions inherited from uriVL::GraphicComponent3D
static GLfloat norm (GLfloat *V)
static void normalizeVector (GLfloat *V)
static GLfloat dotProduct (GLfloat *e1, GLfloat *e2)
static void crossProduct (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void commonNormalVector (GLfloat *e1, GLfloat *e2, GLfloat *nv)
static void faceExactNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *nVect)
static void faceAverageNormal (GLuint n, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLuint *index, GLfloat **v, GLfloat *nVect)
static void faceAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *v3, GLfloat *nVect)
static void vertexAverageNormal (GLfloat *v0, GLfloat *v1, GLfloat *v2, GLfloat *d, GLfloat *nVect)
Protected Member Functions inherited from uriVL::GraphicComponent3D
GraphicComponent3D (void)
Default constructor.
void setReflectionParameters_ (void)
Protected Attributes inherited from uriVL::GraphicComponent3D
GLfloat ambientMat_ [3]
stores "ambient" light material property for this object
GLfloat diffuseMat_ [3]
stores "diffuse" light material property for this object
GLfloat specularMat_ [3]
stores "specular" light material property for this object
GLfloat shiny_
stores "shininess" light material property for this object
Detailed Description
Cylinder3D class.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Version history
        - 2005/04/27 [jyh]              adapted and brought into the uriVisionLib
        - 2010/07/2x [jyh]              massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 48 of file Cylinder3D.h.
Constructor & Destructor Documentation
Cylinder3D::Cylinder3D (GLfloat * origin, GLfloat ** axes, bool isClosed)
Constructor.
Creates a cylinder from the location of its origin, the directions of the 2 axes of its elliptic bottom face, and the direction of its main axis.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
isClosed true if the cone's bottom face should be drawn
Definition at line 46 of file Cylinder3D.cpp.
References uriVL::ErrorReport::appendToMessage(), deleteArrays_(), init_(), initCtSt_, and initStatic_().
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedCyl_(isClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         try {
                 init_(origin, axes);
         }
         catch (ErrorReport& e) {
                 deleteArrays_();
                 e.appendToMessage("called from Cylinder3D constructor.");
                 throw e;
         }
 }
Cylinder3D::Cylinder3D (GLfloat * origin, GLfloat * dirAxis, GLfloat radius, bool isClosed)
Constructor.
Creates a cylinder from the loation of its origin, direction of main axis, and radius
Parameters
origin coordinates of the box's origin (at one corner of the box)
dirAxis the direction of the cones main axis
radius the radius of the cylinder
isClosed true if the cylinder's top and bottom faces should be drawn
Definition at line 80 of file Cylinder3D.cpp.
References uriVL::GraphicComponent3D::commonNormalVector(), deleteArrays_(), FAIL_CONDITION, uriVL::GlUtils::free_glfMatrix(), uriVL::GlUtils::glfMatrix(), init_(), initCtSt_, initStatic_(), uriVL::kInvalidParameterError, kVeryHighDefCircPts, kVeryHighDefSlabs, and vertex_.
                 :       GraphicComponent3D(),
                         //
                         vertex_(new GLfloat** [kVeryHighDefSlabs+1]),
                         normal_(GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2)),
                         circStep_(kFineResolution),
                         slabStep_(kMediumResolution),
                         closedCyl_(isClosed)
 {
         if (!initCtSt_)
                 initStatic_();
         GLfloat         **axes, w[3];
         axes = GlUtils::glfMatrix(0, 2, 0, 2);
         try {
                 //      dirAxis is the direction axis of the cylinder
                 axes[2][0] = dirAxis[0];
                 axes[2][1] = dirAxis[1];
                 axes[2][2] = dirAxis[2];
                 //      For the major axis, we need to build a vector orthogonal to dirAxis.
                 if ((dirAxis[0]!= 0.f) || (dirAxis[2]!= 0.f))   //      this is not the local Y axis
                 {
                         w[0] = 0.f; w[1] = 1.f; w[2] = 0.f;
                         commonNormalVector(w, dirAxis, axes[0]);                //      "X" = "Y" x "Z"
                         commonNormalVector(dirAxis, axes[0], axes[1]);  //      "Y" = "Z" x "X"
                         //
                         //      and now we can multiply by the radius
                         for (int i=0; i<3; i++)
{
                                 axes[0][i] *= radius;
                                 axes[1][i] *= radius;
                         }
                 }
                 //      if dirAxis was the local Y axis, then I can take Z and X as major and minor
                 else
                 {
                         axes[0][0] = axes[0][1] = axes[1][1] = axes[1][2] = 0.f;
                         axes[0][2] = axes[1][0] = radius;
                 }
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to Cylinder3D constructor");
         }
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2);
         try {
                 init_(origin, axes);
         }
         catch (...)
         {
                 deleteArrays_();
                 GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid array passed to Cylinder3D constructor");
         }
         GlUtils::free_glfMatrix(axes, 0, 2, 0, 2);
 }
Cylinder3D::~Cylinder3D (void)
Destructor.
Definition at line 174 of file Cylinder3D.cpp.
References deleteArrays_().
 {
         deleteArrays_();
 }
Cylinder3D::Cylinder3D (const Cylinder3D & obj) private
Copy constructor (disabled)
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
obj reference of the object to copy
Definition at line 151 of file Cylinder3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       GraphicComponent3D(),
                         //
                         vertex_(NULL),
                         normal_(NULL),
                         circStep_(kCoarseResolution),
                         slabStep_(kCoarseResolution),
                         closedCyl_(false)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cylinder3D copy constructor not implemented.");
 }
Member Function Documentation
void Cylinder3D::deleteArrays_ (void) private
Delete all allocated arrays.
Definition at line 424 of file Cylinder3D.cpp.
References uriVL::GlUtils::free_glfMatrix(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, and vertex_.
Referenced by Cylinder3D(), and ~Cylinder3D().
 {
         if (vertex_!=NULL)
         {
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                         GlUtils::free_glfMatrix(vertex_[i], 0,  kVeryHighDefCircPts-1, 0, 2);
                 delete [] vertex_;
                 vertex_ = NULL;
         }
         if (normal_!=NULL)
         {
                 GlUtils::free_glfMatrix(normal_, 0,  kVeryHighDefCircPts-1, 0, 2);
                 normal_ = NULL;
         }
 }
void Cylinder3D::draw (void) virtual
Draw the object in the current graphic context.
Reimplemented from uriVL::GraphicComponent3D.
Definition at line 299 of file Cylinder3D.cpp.
References circStep_, closedCyl_, uriVL::GraphicComponent3D::draw(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, normalBottom_, normalTop_, slabStep_, and vertex_.
 {
         GraphicComponent3D::draw();
         //      I draw the cylinders as a series of one-slab-high crowns
         //      Each crown is defined as a quad strip.
         //      It might be a better idea to draw then the other way around (as a ring
         //      of linear quad strips).  --> check
         for (int i=0; i<=kVeryHighDefSlabs-slabStep_; i+=slabStep_)
         {
                 glBegin(GL_TRIANGLE_STRIP);
                         for (int j=0; j<kVeryHighDefCircPts; j+=circStep_)
{
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i+slabStep_][j]);
                                 glNormal3fv(normal_[j]);
                                 glVertex3fv(vertex_[i][j]);
                         }
                         glNormal3fv(normal_[0]);
                         glVertex3fv(vertex_[i+slabStep_][0]);
                         glNormal3fv(normal_[0]);
                         glVertex3fv(vertex_[i][0]);
                 glEnd();
         }
         //      If this is a closed cylinder, then we also draw the top and bottom
         //      sides at the same resolution as the rest)
         if (closedCyl_)
         {
                 glNormal3fv(normalTop_);
                 glBegin(GL_POLYGON);
                         for (int j=0; j<kVeryHighDefCircPts; j+=circStep_)
                                 glVertex3fv(vertex_[kVeryHighDefSlabs][j]);
                 glEnd();
                 //
                 glNormal3fv(normalBottom_);
                 glBegin(GL_POLYGON);
                         for (int j=kVeryHighDefCircPts-circStep_; j>=0; j-=circStep_)
                                 glVertex3fv(vertex_[0][j]);
                 glEnd();
         }
 }
void Cylinder3D::init_ (GLfloat * origin, GLfloat ** axes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
axes the 3 axes of the cone
Definition at line 365 of file Cylinder3D.cpp.
References closedCyl_, uriVL::GraphicComponent3D::commonNormalVector(), uriVL::GraphicComponent3D::crossProduct(), ct_, uriVL::GlUtils::glfMatrix(), kVeryHighDefCircPts, kVeryHighDefSlabs, normal_, normalBottom_, uriVL::GraphicComponent3D::normalizeVector(), normalTop_, st_, and vertex_.
Referenced by Cylinder3D().
 {
         GLfloat dirStep = 1.f/kVeryHighDefSlabs,
                         dir[kVeryHighDefSlabs+1][3],
                         //      X, Y, and Z coordinates of the radial and normal directions.
                         radial_j[3],
                         majCross[3], minCross[3];
         for (int i=0; i<=kVeryHighDefSlabs; i++)
                 vertex_[i] = GlUtils::glfMatrix(0, kVeryHighDefCircPts-1, 0, 2);
         //      majCross = a[0] x a[2] (major axis x direction)
         crossProduct(a[0], a[2], majCross);
         //      minCross = a[1] x a[2] (minor axis x direction)
         crossProduct(a[1], a[2], minCross);
         //      First, we precompute the graduation steps for the slabs along
         //      the "direction" axis (a[2]).
         for (int i=0; i<=kVeryHighDefSlabs; i++)
         {
                 dir[i][0] = i*dirStep*a[2][0];
                 dir[i][1] = i*dirStep*a[2][1];
                 dir[i][2] = i*dirStep*a[2][2];
         }
         for (int j=0; j< kVeryHighDefCircPts; j++)
         {
                 radial_j[0] = ct_[j]*a[0][0] + st_[j]*a[1][0];
                 normal_[j][0] = ct_[j]*minCross[0] - st_[j]*majCross[0];
                 //
                 radial_j[1] = ct_[j]*a[0][1] + st_[j]*a[1][1];
                 normal_[j][1] = ct_[j]*minCross[1] - st_[j]*majCross[1];
                 //
                 radial_j[2] = ct_[j]*a[0][2] + st_[j]*a[1][2];
                 normal_[j][2] = ct_[j]*minCross[2] - st_[j]*majCross[2];
                 normalizeVector(normal_[j]);
                 for (int i=0; i<=kVeryHighDefSlabs; i++)
                 {
                                 //      M = origin + cos[u] major + sin[u] minor + v direction
                                 vertex_[i][j][0] = origin[0] + radial_j[0] + dir[i][0];
                                 vertex_[i][j][1] = origin[1] + radial_j[1] + dir[i][1];
                                 vertex_[i][j][2] = origin[2] + radial_j[2] + dir[i][2];
                 }
         }
         //      if this is a closed cylinder, then we must also compute the normal
         //      vector for the top and bottom faces.
         if (closedCyl_)
         {
                 //      topNormal = major x minor / ||major x minor||
                 commonNormalVector(a[0], a[1], normalTop_);
                 normalBottom_[0] = -normalTop_[0];
                 normalBottom_[1] = -normalTop_[1];
                 normalBottom_[2] = -normalTop_[2];
         }
 }
void uriVL::Cylinder3D::init_ (GLfloat * origin, GLfloat ** botAxes, GLfloat * dirAxis, GLfloat ** topAxes) private
Initialize the cone.
Parameters
origin coordinates of the cone's origin (at one corner of the box)
botAxes the 2 axes of the cone bottom face
dirAxis the direction of the cones main axis
topAxes the 2 axes of the cone top face
void Cylinder3D::initStatic_ (void) static private
Initializes the classe's static variables.
Definition at line 453 of file Cylinder3D.cpp.
References ct_, initCtSt_, kVeryHighDefCircPts, PI, and st_.
Referenced by Cylinder3D().
 {
         GLfloat dTheta = static_cast<GLfloat>(2.f*PI/kVeryHighDefCircPts);
         for (int j=0; j<kVeryHighDefCircPts; j++)
         {
                 ct_[j] = cosf(j*dTheta);
                 st_[j] = sinf(j*dTheta);
         }
         initCtSt_ = true;
 }
const Cylinder3D & Cylinder3D::operator= (const Cylinder3D & obj) private
Copy operator: disabled.
This operator is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the copy constructor (constness).
Parameters
obj reference of the object to copy
Definition at line 179 of file Cylinder3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Cylinder3D copy operator not implemented.");
         return *this;
 }
void Cylinder3D::setResolution (ResolutionLevel res) virtual
Assigns a new drawing resolution to the object.
Parameters
res resolution to assign to the object
Implements uriVL::GraphicComponent3D.
Definition at line 208 of file Cylinder3D.cpp.
 {
         setResolution(res, res);
 }
void Cylinder3D::setResolution (ResolutionLevel circRes, ResolutionLevel slabRes)
Assigns a new drawing resolution to the object.
Parameters
circRes resolution to assign along a circular/elliptic face
slabRes resolution to assign along the main axis
Definition at line 229 of file Cylinder3D.cpp.
References circStep_, kCoarseDefCircScale, kCoarseDefSlabScale, uriVL::kCoarseResolution, kFineDefCircScale, kFineDefSlabScale, uriVL::kFineResolution, kMediumDefCircScale, kMediumDefSlabScale, uriVL::kMediumResolution, uriVL::kVeryHighResolution, kVeryLowDefCircScale, kVeryLowDefSlabScale, uriVL::kVeryLowResolution, and slabStep_.
 {
         switch (circRes)
         {
                 case kVeryHighResolution:
                         circStep_ = 1;
                         break;
                 case kFineResolution:
                         circStep_ = kFineDefCircScale;
                         break;
                 case kMediumResolution:
                         circStep_ = kMediumDefCircScale;
                         break;
                 case kCoarseResolution:
                         circStep_ = kCoarseDefCircScale;
                         break;
                 case kVeryLowResolution:
                         circStep_ = kVeryLowDefCircScale;
                         break;
                 default:
                         circStep_ = kMediumDefCircScale;
                         break;
         }
         switch (slabRes)
         {
                 case kVeryHighResolution:
                         slabStep_ = 1;
                         break;
                 case kFineResolution:
                         slabStep_ = kFineDefSlabScale;
                         break;
                 case kMediumResolution:
                         slabStep_ = kMediumDefSlabScale;
                         break;
                 case kCoarseResolution:
                         slabStep_ = kCoarseDefSlabScale;
                         break;
                 case kVeryLowResolution:
                         slabStep_ = kVeryLowDefSlabScale;
                         break;
                 default:
                         slabStep_ = kMediumDefSlabScale;
                         break;
         }
 }
Member Data Documentation
int uriVL::Cylinder3D::circStep_ private
Display resolution along a circular/elliptic face.
Definition at line 111 of file Cylinder3D.h.
Referenced by draw(), and setResolution().
bool uriVL::Cylinder3D::closedCyl_ private
Are the top and bottom faces drawn?
Definition at line 119 of file Cylinder3D.h.
Referenced by draw(), and init_().
GLfloat Cylinder3D::ct_ static private
Precomputed array of cosine values.
Definition at line 127 of file Cylinder3D.h.
Referenced by init_(), and initStatic_().
bool Cylinder3D::initCtSt_ = false static private
Have the static variables been initialized?
Definition at line 123 of file Cylinder3D.h.
Referenced by Cylinder3D(), and initStatic_().
GLfloat** uriVL::Cylinder3D::normal_ private
0-based list of normals
Definition at line 99 of file Cylinder3D.h.
Referenced by deleteArrays_(), draw(), and init_().
GLfloat uriVL::Cylinder3D::normalBottom_[3] private
Normal to the bottom faced.
Definition at line 107 of file Cylinder3D.h.
Referenced by draw(), and init_().
GLfloat uriVL::Cylinder3D::normalTop_[3] private
Normal to the top faced.
Definition at line 103 of file Cylinder3D.h.
Referenced by draw(), and init_().
int uriVL::Cylinder3D::slabStep_ private
Display resolution along a slab (main axis)
Definition at line 115 of file Cylinder3D.h.
Referenced by draw(), and setResolution().
GLfloat Cylinder3D::st_ static private
Precomputed array of sine values.
Definition at line 131 of file Cylinder3D.h.
Referenced by init_(), and initStatic_().
GLfloat*** uriVL::Cylinder3D::vertex_ private
0-based list of vertices
Definition at line 95 of file Cylinder3D.h.
Referenced by Cylinder3D(), deleteArrays_(), draw(), and init_().
The documentation for this class was generated from the following files:
Cylinder3D.h
Cylinder3D.cpp