URIVisionLibrary: uriVL::RasterImage_RGB Class Reference
uriVL::RasterImage_RGB Class Reference
Base rgb color image class.
#include <RasterImage_RGB.h>
Public Member Functions
RasterImage_RGB (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
RasterImage_RGB (const ImageRect *theRect)
Allocates a 24-bit RGB color raster image at the specified dimensions.
RasterImage_RGB (int nbRows, int nbCols, const unsigned char *theRGB)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGB (GraphWorld *gworld, bool keepThisGraphWorld)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGB (const GraphWorld *gworld)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGB (const RasterImage *img)
Initializes an rgb raster image at the specified dimensions and values.
RasterImage_RGB (RasterImage *img, const ImageRect *theRect)
Initializes an rgb raster image at the specified dimensions and values.
~RasterImage_RGB (void)
Class destructor.
void copyInto (RasterImage *imgOut) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect) const
Copies this image into the one received as parameter.
void copyInto (RasterImage *imgOut, const ImageRect *theRect, const ImagePoint *origin) const
Copies this image into the one received as parameter.
BaseRasterType getBaseRasterType (void) const
Returns the image's base raster type.
const unsigned char * getRGB (void) const
Returns the 24-bit rgb base raster as a read-only 1D array.
unsigned char * getRGB (ReadWriteStatus rw)
Returns the 24-bit rgb base raster as a read-write 1D array.
const unsigned char *const * getRGB2D (void) const
Returns the 24-bit rgb base raster as a read-only 2D array.
unsigned char *const * getRGB2D (ReadWriteStatus rw)
Returns the 24-bit rgb base raster as a read-write 2D array.
const unsigned char *const * getShiftedRGB2D (void) const
Returns the shifted 24-bit rgba base raster as a constant2D array.
unsigned char *const * getShiftedRGB2D (ReadWriteStatus rw)
Returns the shifted 24-bit rgba base raster as a read-write 2D array.
Public Member Functions inherited from uriVL::RasterImage
virtual ~RasterImage (void)
Destructor.
virtual const unsigned char * getRaster (void) const
Returns the base raster as a read-only 1D array.
virtual unsigned char * getRaster (ReadWriteStatus rw)
Returns the base raster as a read-write 1D array.
virtual const unsigned char *const * getRaster2D (void) const
Returns the base raster as a read-only 2D array.
virtual unsigned char *const * getRaster2D (ReadWriteStatus rw)
Returns the base raster as a read-write 2D array.
virtual const unsigned char *const * getShiftedRaster2D (void) const
Returns the shifted base raster as a read-only 2D array.
virtual unsigned char *const * getShiftedRaster2D (ReadWriteStatus rw)
Returns the shifted base raster as a read-write 2D array.
void overlay (const RasterImage *imgIn)
Writes another image over part of this image.
void overlay (const RasterImage *imgIn, const ImagePoint *origin)
Writes another image over part of this image, using the point specified as origin for this image's valid rectangle's upper-left corner.
void overlay (const RasterImage *imgIn, const ImageRect *rect)
Writes over this image the part of another image specified by a rectangle.
void overlay (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes over this image the part of another image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut) const
Writes this image into another image.
void writeInto (RasterImage *imgOut, const ImageRect *rect) const
Writes into another image the part of this image specified by a rectangle.
void writeInto (RasterImage *imgOut, const ImagePoint *origin) const
Writes this image into another image using the point specified as origin for this image's valid rectangle's upper-left corner.
void writeInto (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
RasterImage * grab (const ImageRect *rect) const
Writes into a new raster image the part of this image specified by a rectangle.
RasterImage * grab (const ImageRect *rect, const ImagePoint *origin) const
Writes into a new raster image the part of this image specified by a rectangle, and at the location specified by the image point.
RasterImage * createCopy (void) const
Creates a new raster image that is a copy of this image.
int getBytesPerRow (void) const
Returns the number of bytes on each row of the image.
long getTotalByteCount (void) const
Returns the number of total number of bytes in the image.
int getPixelDepth (void) const
Returns the number of bytes per pixel (pixel depth)
long getTimeStamp (void) const
Get the time stamp of this image.
void setTimeStamp (long timeStamp)
Sets the time stamp of this image.
unsigned int getID (void)
Gives this image's unique id this image's id.
void requestRasterUpdate (void) const
Forces a refresh of nonreference raster according to the reference raster.
void lockProperties (void *key)
Locks the geometry and pixel depth of the image.
void unlockProperties (void *key)
Unlocks the geometry and pixel depth of the image.
bool propertiesAreLocked (void) const
Indicates whether the RasterImage object's properties are locked.
void lockPixels (void *key)
Locks the pixel map of the image so that calls to the read-write version of getRaster will fail until the image is unlocked.
void unlockPixels (void *key)
Unlocks the pixel map of the image.
bool pixelsAreLocked (void) const
Indicates whether the RasterImage object's pixmap is locked.
void setAsCurrentGraphWorld (void)
Sets this RasterImage as destination for global blitting/drawing.
void setAsMovieGraphWorld (Movie theMovie)
Sets this RasterImage as destination for movie playing.
void setAsImporterGraphWorld (GraphicsImportComponent importer)
Sets this RasterImage as destination for a video capture.
void restoreGraphWorld (void)
Adds this image to the video digitizer record of a buffer ring.
bool graphWorldIsReference (void) const
Indicates whether or not the raster stored in the GraphWorld (if it exists) contains the reference values for this image.
bool referenceHasChanged (void) const
Indicates whether or not the reference raster for this image has been modified.
bool hasFloatRaster (void) const
Indicates whether or not the raster image stores a float raster (eg this would be true for a Raster_Image_gray_F object)
bool floatRasterIsReference (void) const
Indicates whether or not the float raster (for a raster that does have a float raster, eg Raster_Image_gray_F stores the reference values for the raster image.
void applyTransformation (const Transformation2D *theTransf)
Applies a Transformation2D to this object.
void rotate (float angle, const ImagePoint *rotCenter=NULL)
Rotates the object by the angle specified (in radians) If rotationCenter is null, then the centroid of the object is used as center of rotation.
const float * getConversionWeights (void) const
Returns the to-gray conversion coefficients for this image.
Public Member Functions inherited from uriVL::DrawableObject2D
virtual ~DrawableObject2D (void)
Destructor.
virtual const ImageRect * getBoundRect (void) const
Returns the object's bounding rectangle.
bool boundRectIsEmpty (void) const
Indicates whether the boinding rect is empty.
virtual const ImageRect * getValidRect (void) const
Returns the object's valid data rectangle.
const ImagePoint_F * getCentroid (void) const
Returns the object's centroid.
const ImagePoint_F * getCenterOfMass (void) const
Returns the object's center of mass.
virtual bool overlaps (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the drawable object received as parameter overlap.
virtual bool overlaps (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter overlap.
virtual bool coincidesWith (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle and that of the image received as parameter coincide.
virtual bool coincidesWith (const ImageRect *rect) const
Indicates whether this image's bounding rectangle and the one received as parameter coincide.
virtual bool contains (const DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle contains that of the drawable object received as parameter.
virtual bool contains (const ImageRect *rect) const
Indicates whether this image's bounding rectangle contains the one received as parameter.
virtual bool contains (const ImagePoint *pt, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool contains (int x, int y, int padding=0) const
Checks whether the point passed as parameter belongs to the rectangle.
virtual bool isContainedBy (DrawableObject2D *obj) const
Indicates whether this image's bounding rectangle is contained by that of the drawable object received as parameter.
virtual bool isContainedBy (const ImageRect *rect) const
Indicates whether this image's bounding rectangle is contained by the received as parameter.
virtual int getHeight (void) const
Returns the number of rows for the image.
virtual int getWidth (void) const
Returns the number of columns for the image.
int getLeft (void) const
Returns the minimum x coordinate of the bounding rectangle.
int getRight (void) const
Returns the maximum x coordinate of the bounding rectangle.
int getTop (void) const
Returns the minimum y coordinate of the bounding rectangle.
int getBottom (void) const
Returns the maximum y coordinate of the bounding rectangle.
virtual const ImagePoint * getUpperLeft (void) const
returns the coordinates of the upper left corner of the object
void setOrigin (int x=0, int y=0)
Sets a new origin for the raster image.
virtual void translate (int dx=0, int dy=0)
Translates the raster image by the specified amount.
virtual void translate (float dx=0.f, float dy=0.f)
Translates the raster image by the specified amount.
void setBoundRect (const ImageRect *theRect)
Sets a new bounding rectangle for the raster image.
virtual void setBoundRect (int x, int y, int theWidth, int theHeight)
Sets a new bounding rectangle for the raster image.
void setValidRect (const ImageRect *theRect)
Sets a new valid data rectangle for the drawable object.
virtual void setValidRect (int x, int y, int theWidth, int theHeight)
Sets a new valid data rectangle for the drawable object.
void render (void) const
Renders the object at the default depth and (0, 0) location.
void render (bool shifted) const
Renders the "shifted" object at the default depth and (0, 0) location.
void render (float theZ) const
Renders the object's base raster at the depth specified and (0, 0) location.
void render (float theZ, bool shifted) const
Renders the drawable object at the depth specified and (0, 0) location.
void render (const ImagePoint *origin) const
Renders the drawable object at the default depth and at the location specified.
void render (float theZ, bool shifted, const ImagePoint *origin) const
Renders the drawable object at the depth and location specified.
void setRenderDepth (float theZ)
Specifies the depth at which the RasterImage's base raster should be rendered.
virtual void setColor (float red, float green, float blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const float theColor[])
Assigns a rendering color to the object (alpha is set to 1)
virtual void setColor (const unsigned char theColor[])
Assigns a rendering color to the object (alpha is set to 1)
const float * getColor (void) const
Returns a read-only pointer to the object's color data.
void setFrameColor (float frameRed=0.f, float frameGreen=0.f, float frameBlue=0.f)
Specifies the a color for the frame of this object.
void setFrameColor (unsigned char red, unsigned char green, unsigned char blue)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const float *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setFrameColor (const unsigned char *theColor)
Assigns a rendering color to the frame (alpha is set to 1)
void setDrawFrame (bool drawFrame)
Indicates whether this image's bounding rectangle should be indicated by a color frame.
void setDrawValidDataFrame (bool drawFrame)
Indicates whether this image's valid data rectangle should be indicated by a color frame.
virtual void setRenderingScale (float scale) const
Sets a uniform scale at which this object should be rendered.
virtual void setRenderingScale (float scaleX, float scaleY) const
Sets horizontal and vertical scales at which this object should be rendered.
float getRenderingScaleX (void) const
Returns the horizontal rendering scale set for this object.
float getRenderingScaleY (void) const
Returns the horizontal rendering scale set for this object.
virtual void setWindowDimensions (int theWidth, int theHeight)
Informs the vector field object of the dimensions of graphic context used for its rendering.
int getWindowWidth (void) const
Gives the window width for this object.
int getWindowHeight (void) const
Gives the window height for this object.
bool hasIndividualWindowDimensions (void) const
Indicates whether this object has individual window dimensions (or uses the default class values.
DrawableInformationType getDrawableInformationType (void) const
Returns the type of information stored in this object.
void setDrawableInformationType (DrawableInformationType type)
Defines the type of information stored in this object (dense, sparse, interpoalted, etc.)
Static Public Member Functions
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, unsigned char *theDestination, long nbPixels, const float convWeight[])
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, ConversionToGrayMode myGrayConv=kAverageConversion)
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
static void convertToGray (const unsigned char *theSource, float *theDestination, long nbPixels, const float convWeight[])
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
static void convertToRGBa (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D 24-bit RGB raster into a 1D 32-bit rgba raster.
static void convertToRGB (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts (copies) a 1D 24-bit RGB raster into a 1D 24-bit rgb raster.
static void convertToARGB16 (const unsigned char *theSource, unsigned char *theDestination, long nbPixels)
Converts a 1D 24-bit RGB raster into a 1D 16-bit argb raster.
Static Public Member Functions inherited from uriVL::RasterImage
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * grab (const RasterImage *imgIn, const ImageRect *rect, const ImagePoint *origin)
Writes into a new raster image the part of the input image specified by a rectangle.
static RasterImage * createCopy (const RasterImage *imgIn)
Creates a new raster image that is a copy of the image received as parameter.
static const float * getDefaultConversionWeights (void)
Returns the default to-gray conversion coefficients for this image.
static void setDefaultGrayConversionMode (const ConversionToGrayMode theMode)
Sets the default mode for color to gray conversion for the entire RasterImage class.
static void setDefaultConversionWeights (const float redW, const float greenW, const float blueW)
When the default gray conversion mode for the class is kWeightedAverageConversion, this function allows to set the weights of the three color components.
Static Public Member Functions inherited from uriVL::DrawableObject2D
static void setDefaultWindowDimensions (int theWidth, int theHeight)
Informs the class of the dimensions of the default graphic context used for rendering.
Private Member Functions
RasterImage_RGB (void)
Protected default constructor.
RasterImage_RGB (RasterImage_RGB &img)
Creates a new raster image based on the one received as parameter.
const RasterImage_RGB & operator= (const RasterImage_RGB &theImg)
Equal operator.
virtual void writeInto_ (RasterImage *imgOut, const ImageRect *rect, const ImagePoint *origin) const
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
virtual void setBoundRect_ (int x, int y, int theWidth, int theHeight)
Sets a new Sets a new bounding rectangle for the raster image.
virtual void updateRaster_ (void) const
Forces an update of the base rgb raster if it is not the reference raster.
void allocateGraphWorld_ (int nbRows, int nbCols)
Alocates the GraphWorld for this object at the set dimensions.
void deleteRaster2D_ (void)
Deletes the 0-based 2D base raster.
void deleteShiftedRaster2D_ (int iLow)
Deletes the 2D shifted base raster.
void allocateRaster2D_ (int nbRows, int nbCols)
Allocates the 2D gray-level base raster.
void allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow)
Allocates the 2D shifted base raster.
Private Attributes
unsigned char ** rgb2D_
2D array mapped on the GraphWorld's 1D raster.
unsigned char ** shiftedRgb2D_
"shifted" 2D array (based on the image's rectangle bounds) mapped on the GraphWorld's 1D raster.
Friends
class _GraphWorld_gen
Additional Inherited Members
Protected Member Functions inherited from uriVL::RasterImage
void setHasFloatRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has a float raster (false by default)
void setHasOtherRaster_ (bool hasRaster)
Called by a derived class to indicate whether one of its instances has another (other than float) raster, e.g.
void setFloatRasterAsReference_ (void) const
Sets this image's float raster as the reference (fails if it was NULL)
void setGraphWorldAsReference_ (void) const
Sets this image's gworld as the reference (and allocates if it was NULL)
void setOtherRasterAsReference_ (void) const
Called by a subclass that provides another type of raster (for example, RasterImage_binary), when that other raster becomes the reference.
void setReferenceHasChanged_ (bool hasChanged) const
To be called by a child class that has modified the graphworld or one of the secondary rasters, or updated a secondary raster.
bool graphWorldIsNull_ (void) const
Indicates whether the GraphWorld was allocated for this object.
Protected Member Functions inherited from uriVL::DrawableObject2D
DrawableObject2D (DrawableInformationType drawableInfoType=kUndetermined)
This constructor simply sets all instance variables to 0, NULL, or the appropriate default value.
DrawableObject2D (const ImageRect &rect, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (int nbRows, int nbCols, DrawableInformationType drawableInfoType=kUndetermined)
This constructor also sets the bounding rectangle of the object.
DrawableObject2D (const DrawableObject2D &thePt)
Copy constructor.
void setCentroidIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the centroid.
void setCenterOfMassIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the center of mass.
void setBoundingRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the bounding rectangle.
void setValidRectIsUpToDate_ (bool isUpToDate) const
Allows a child class whose content has been changed to force recomputation of the valid rectangle.
Detailed Description
Base rgb color image class.
RasterImage_RGB is the base class for all gray-level image types. This class is built around an 8-bit gray-level QuickTime GWorld buffer, which is itself wrapped into a GraphWorld object.
RasterImage_RGB implements or overrides a number of methods of the base RasterImageClass, and in particular the convertTo<Gray,RGB,RGBa> methods.
Note to class developers: Do not subclass RasterImage_RGB but rather RasterImage_RGBa. Support for RasterImage_RGB is now minimal. Images of this type should not be relied upon for more than reading and displaying. The reason for this is that QuickTime does not officially support 24-bits buffers. So, some function work todays but may break down with a future update of QT. Right now fixing the implementation of 24-bits images is a very low priority for me.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 45 of file RasterImage_RGB.h.
Constructor & Destructor Documentation
RasterImage_RGB::RasterImage_RGB (int nbRows, int nbCols)
Initializes an rgb raster image at the specified dimensions.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes this raster to zero values (black).
Parameters
nbRows number of rows of the rgb raster image
nbCols number of columns of the rgb raster image
Definition at line 41 of file RasterImage_RGB.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::RasterImage::referenceHasChanged_, and uriVL::DrawableObject2D::setDrawableInformationType().
                 :       RasterImage(nbRows, nbCols),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
         try {
                 allocateGraphWorld_(nbRows, nbCols);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGB constructor");
                 throw e;
         }
     allocateRaster2D_(nbRows, nbCols);
     allocateShiftedRaster2D_(nbRows, nbCols, 0, 0);
     //
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (const ImageRect * theRect)
Allocates a 24-bit RGB color raster image at the specified dimensions.
Allocates a 24-bit RGB color raster at the specified dimensions and initializes this raster to zero values (black).
Parameters
theRect ImageRect specifying the image's bounding rectangle
Definition at line 68 of file RasterImage_RGB.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), uriVL::ImageRect::getHeight(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::RasterImage::referenceHasChanged_, and uriVL::DrawableObject2D::setDrawableInformationType().
                 :       RasterImage(theRect),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
         try {
                 allocateGraphWorld_(theRect->getHeight(), theRect->getWidth());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGB constructor");
                 throw e;
         }
     allocateRaster2D_(getHeight(), getWidth());
     allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     //
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (int nbRows, int nbCols, const unsigned char * theRGB)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes it using the raster received as parameter.
Parameters
nbRows number of rows of the rgb raster image
nbCols number of columns of the rgb raster image
theRGBA values to which the image should be initialized
Definition at line 95 of file RasterImage_RGB.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::gworldIsReference_, uriVL::kDense, uriVL::kMemoryCopyError, uriVL::RasterImage::referenceHasChanged_, rgb2D_, uriVL::DrawableObject2D::setDrawableInformationType(), and uriVL::DrawableObject2D::setValidRect().
                 :       RasterImage(nbRows, nbCols),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
         try {
                 allocateGraphWorld_(nbRows, nbCols);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGB constructor");
                 throw e;
         }
     allocateRaster2D_(getHeight(), getWidth());
     allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
     //
         setDrawableInformationType(kDense);
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
         try {
                 const unsigned char   *source = theRGB;
                 for (int i=0; i<nbRows; i++)
                 {
                         memcpy(rgb2D_[i], source, static_cast<unsigned long>(3*nbCols));
                         source += 3*nbCols;
                 }
         }
         catch (...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "Data copy failure in RasterImage_RGB constructor");
         }
         setValidRect(0, 0, nbCols, nbRows);
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (GraphWorld * gworld, bool keepThisGraphWorld)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter.
Parameters
gworld the GraphWorld to use for dimensions and values
keepThisGraphWorld if true, then this new image raster object will simply store a reference to a pre-allocated GWorld instead of allocating its own (beware!)
Definition at line 161 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage(theGworld, keepThisGraphWorld),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
 //    allocateRaster2D_(getHeight(), getWidth());
 //    allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
 //    //
 //      setDrawableInformationType(kDense);
 //    gworldIsReference_ = true;
 //    referenceHasChanged_ = true;
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "RasterImage_RGB Constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (const GraphWorld * gworld)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the GraphWorld received as parameter. Possibly keeps the GraphWorld received as parameter rather than making a copy of it.
Parameters
gworld the GraphWorld to use for dimensions and values
keepThisGraphWorld true if the pointer is to be used, false if data shouold be copied (clone)
Definition at line 138 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :       RasterImage(theGworld),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
 //    allocateRaster2D_(getHeight(), getWidth());
 //    allocateShiftedRaster2D_(getHeight(), getWidth(), getTop(), getLeft());
 //    //
 //      setDrawableInformationType(kDense);
 //    gworldIsReference_ = true;
 //    referenceHasChanged_ = true;
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "RasterImage_RGB Constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (const RasterImage * img)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
Definition at line 184 of file RasterImage_RGB.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::RasterImage::gworldIsReference_, uriVL::kNullRasterImageError, and uriVL::RasterImage::referenceHasChanged_.
                 :       RasterImage( ),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGB constructor");
         try {
                 img->copyInto(this, img->getValidRect());
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGB constructor");
                 throw e;
         }
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::RasterImage_RGB (RasterImage * img, const ImageRect * theRect)
Initializes an rgb raster image at the specified dimensions and values.
Allocates a 24-bit color GraphWorld at the specified dimensions and initializes this raster to the values specified by the RasterImage received as parameter.
Parameters
img the RasterImage to use for dimensions and values
theRect ImageRect specifying the image's bounding rectangle
Definition at line 211 of file RasterImage_RGB.cpp.
References uriVL::ErrorReport::appendToMessage(), uriVL::RasterImage::copyInto(), FAIL_CONDITION, uriVL::RasterImage::gworldIsReference_, uriVL::kNullRasterImageError, uriVL::kNullRectangleError, and uriVL::RasterImage::referenceHasChanged_.
                 :       RasterImage( ),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
     FAIL_CONDITION( img == NULL,
                     kNullRasterImageError,
                     "Attempt to clone a null RasterImage in RasterImage_RGB constructor");
     FAIL_CONDITION( theRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RasterImage_RGB constructor");
         try {
                 img->copyInto(this, theRect);
         }
         catch (ErrorReport& e) {
                 e.appendToMessage("called by RasterImage_RGB constructor");
                 throw e;
         }
     gworldIsReference_ = true;
     referenceHasChanged_ = true;
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
RasterImage_RGB::~RasterImage_RGB (void)
Class destructor.
Standard destructor (nothing fancy).
Definition at line 258 of file RasterImage_RGB.cpp.
References deleteRaster2D_(), deleteShiftedRaster2D_(), and uriVL::DrawableObject2D::getTop().
 {
     deleteShiftedRaster2D_(getTop());
     deleteRaster2D_();
 }
RasterImage_RGB::RasterImage_RGB (void) private
Protected default constructor.
Called by subclasses that don't need to allocate the base raster.
Definition at line 32 of file RasterImage_RGB.cpp.
                 :       RasterImage( ),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
 }
RasterImage_RGB::RasterImage_RGB (RasterImage_RGB & img) private
Creates a new raster image based on the one received as parameter.
This constructor is disabled. I created it to eliminate compiler warnings, but it cannot be implemented for the same reasons as for the prvious one (constness).
Parameters
img pointer to the RasterImage_RGB object to copy
Definition at line 242 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
         :       RasterImage( ),
                         //
                         rgb2D_(NULL),
                         shiftedRgb2D_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_RGB copy constructor not implemented");
 }
 catch (ErrorReport& e) {
         e.appendToMessage("called by RasterImage_RGB constructor");
         throw e;
 }
Member Function Documentation
void RasterImage_RGB::allocateGraphWorld_ (int nbRows, int nbCols) private virtual
Alocates the GraphWorld for this object at the set dimensions.
Parameters
nbRows number of rows of the gray-level raster image
nbCols number of columns of the gray-level raster image
Implements uriVL::RasterImage.
Definition at line 852 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, and uriVL::kGWorldAllocationError.
Referenced by RasterImage_RGB(), and setBoundRect_().
 {
         gworld_ = new GraphWorld(24, nbRows, nbCols);
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldAllocationError,
                     "GraphWorld allocation failed in RasterImage_gray constructor");
 }
void RasterImage_RGB::allocateRaster2D_ (int nbRows, int nbCols) private virtual
Allocates the 2D gray-level base raster.
Parameters
nbCols number of columns of the image
nbRows number of rows of the image
Implements uriVL::RasterImage.
Definition at line 861 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getBytesPerRow(), uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, uriVL::kRasterAllocationFailure, and rgb2D_.
Referenced by RasterImage_RGB(), and setBoundRect_().
 {
     unsigned char* rgb = gworld_->getRaster();
     const int   rowBytes = gworld_->getBytesPerRow();
     if (rgb2D_ != NULL)
         delete []rgb2D_;
     rgb2D_ = new unsigned char*[nbRows];
     FAIL_CONDITION(rgb2D_ == NULL, kRasterAllocationFailure,
                    "Could not allocate rgb2D_ array");
     rgb2D_[0] = rgb;
     for (int i=1; i<nbRows; i++)
         rgb2D_[i] = rgb2D_[i-1] + rowBytes;
 }
void RasterImage_RGB::allocateShiftedRaster2D_ (int nbRows, int nbCols, int iLow, int jLow) private virtual
Allocates the 2D shifted base raster.
Parameters
nbRows number of rows of the image
nbCols number of columns of the image
iLow Y coordinate of the image's origin
jLow X coordinate of the image's origin
Implements uriVL::RasterImage.
Definition at line 888 of file RasterImage_RGB.cpp.
References deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::RasterImage::getBytesPerRow(), uriVL::DrawableObject2D::getLeft(), getRGB(), uriVL::DrawableObject2D::getTop(), uriVL::kRasterAllocationFailure, uriVL::R_W_ACCESS, and shiftedRgb2D_.
Referenced by RasterImage_RGB(), and setBoundRect_().
 {
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop() != 0) || (getLeft() != 0))
     {
         const int   iHigh = iLow + nbRows - 1,
                     bytesPerRow = getBytesPerRow();
         deleteShiftedRaster2D_(iLow);
         shiftedRgb2D_ = new unsigned char*[nbRows];
         FAIL_CONDITION( shiftedRgb2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D RGB color  raster allocation failed");
         shiftedRgb2D_ -= iLow;
         //
         shiftedRgb2D_[iLow] = getRGB(R_W_ACCESS) - 3*jLow;
         FAIL_CONDITION( shiftedRgb2D_ == NULL,
                         kRasterAllocationFailure,
                         "2D RGB color  raster allocation failed");
         for (int i = iLow; i < iHigh; i++)
             shiftedRgb2D_[i+1] = shiftedRgb2D_[i] + bytesPerRow;
     }
     else
         shiftedRgb2D_ = NULL;
 }
void RasterImage_RGB::convertToARGB16 (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D 24-bit RGB raster into a 1D 16-bit argb raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 778 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "function not implemented yet");
 }
void RasterImage_RGB::convertToGray (const unsigned char * theSource, unsigned char * theDestination, long nbPixels, ConversionToGrayMode myGrayConv = kAverageConversion) static
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myGrayConv the gray conversion mode desired
Definition at line 586 of file RasterImage_RGB.cpp.
References uriVL::RasterImage::defaultConvWeight_, FAIL_CONDITION, uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kRasterImageError, uriVL::kWeightedAverageConversion, and MAX.
Referenced by uriVL::_GraphWorld_gen::copyRGB24Into_(), and writeInto_().
 {
     const unsigned char   *source = theSource;
     unsigned char   *dest = theDestination;
     int             sum;
     float           sumF;
     //  how do we convert from rgb to gray?
     switch (myGrayConv)
     {
         case kMaxFieldConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 //  optimization "in the small" left for a more clever programmer
                 unsigned char   red = *(source++),
                                 green = *(source++),
                                 blue = *(source++);
                 *(dest++) = MAX(red, MAX(green, blue));
             }
             break;
         case kAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = *(source++);
                 sum += *(source++);
                 sum += *(source++);
                 *(dest++) = static_cast<unsigned char>(sum/3);
             }
             break;
         case kWeightedAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sumF = defaultConvWeight_[0] ** (source++);
                 sumF += defaultConvWeight_[1] ** (source++);
                 sumF += defaultConvWeight_[2] ** (source++);
                 *(dest++) = static_cast<unsigned char>(sumF);
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "unknown conversion to gray mode encountered");
             break;
     }
 }
void RasterImage_RGB::convertToGray (const unsigned char * theSource, unsigned char * theDestination, long nbPixels, const float convWeight[]) static
Converts a 1D 24-bit RGB raster into a 1D gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
Definition at line 644 of file RasterImage_RGB.cpp.
 {
     const unsigned char   *source = theSource;
     unsigned char   *dest = theDestination;
     float           sumF;
     for (long j=0; j<nbPixels; j++)
     {
         sumF = convWeight[0] ** (source++);
         sumF += convWeight[1] ** (source++);
         sumF += convWeight[2] ** (source++);
         *(dest++) = static_cast<unsigned char>(sumF);
     }
 }
void RasterImage_RGB::convertToGray (const unsigned char * theSource, float * theDestination, long nbPixels, ConversionToGrayMode myGrayConv = kAverageConversion) static
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
myGrayConv the gray conversion mode desired
Definition at line 664 of file RasterImage_RGB.cpp.
References uriVL::RasterImage::defaultConvWeight_, FAIL_CONDITION, uriVL::kAverageConversion, uriVL::kMaxFieldConversion, uriVL::kRasterImageError, uriVL::kWeightedAverageConversion, and MAX.
 {
     const unsigned char* source = theSource;
     float           *dest = theDestination;
     float           sum;
     const float         div3 = 1.f/3.f;
     //  how do we convert from rgb to gray?
     switch (myGrayConv)
     {
         case kMaxFieldConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 //  optimization "in the small" left for a more clever programmer
                 float   red = *(source++),
                         green = *(source++),
                         blue = *(source++);
                 *(dest++) = MAX(red, MAX(green, blue));
             }
             break;
         case kAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = *(source++);
                 sum += *(source++);
                 sum += *(source++);
                 *(dest++) = sum*div3;
             }
             break;
         case kWeightedAverageConversion:
             for (long j=0; j<nbPixels; j++)
             {
                 sum = defaultConvWeight_[0] ** (source++);
                 sum += defaultConvWeight_[1] ** (source++);
                 sum += defaultConvWeight_[2] ** (source++);
                 *(dest++) = sum;
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "unknown conversion to gray mode encountered");
             break;
     }
 }
void RasterImage_RGB::convertToGray (const unsigned char * theSource, float * theDestination, long nbPixels, const float convWeight[]) static
Converts a 1D 24-bit RGB raster into a 1D float gray-level raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
convWeight normalized weights to apply for the conversion
Definition at line 720 of file RasterImage_RGB.cpp.
 {
     const unsigned char   *source = theSource;
     float           *dest = theDestination;
     float           sum;
     for (long j=0; j<nbPixels; j++)
     {
         sum = convWeight[0] ** (source++);
         sum += convWeight[1] ** (source++);
         sum += convWeight[2] ** (source++);
         *(dest++) = sum;
     }
 }
void RasterImage_RGB::convertToRGB (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts (copies) a 1D 24-bit RGB raster into a 1D 24-bit rgb raster.
The raster returned is not a clone of this image's base raster since it does not contain any padding of the rows.
Will be called by convertToRGB and copyInto.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 761 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kMemoryCopyError.
 {
         try {
                 //  copy the data (including possible padding bytes)
                 memcpy(theDestination, theSource, static_cast<unsigned long>(3L*nbPixels));
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "memcopy failed in RasterImage_RGB::convertToRGB");
         }
 }
void RasterImage_RGB::convertToRGBa (const unsigned char * theSource, unsigned char * theDestination, long nbPixels) static
Converts a 1D 24-bit RGB raster into a 1D 32-bit rgba raster.
Parameters
theSource starting point of the raster to convert
theDestination starting point of the destination raster
nbPixels number of pixels to convert
Definition at line 738 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kMemoryCopyError.
Referenced by uriVL::_GraphWorld_gen::copyRGB24Into_().
 {
     unsigned char   *dest = theDestination;
     const unsigned char* source = theSource;
         try {
                 for (long j=0; j<nbPixels; j++)
                 {
                         *(dest++) = *(source++);            //  red
                         *(dest++) = *(source++);            //  green
                         *(dest++) = *(source++);            //  blue
                         *(dest++) = static_cast<unsigned char>(255);    //  alpha
                 }
         }
         catch(...) {
                 FAIL_CONDITION( true,
                                                 kMemoryCopyError,
                                                 "memcopy failed in RasterImage_RGB::convertToRGBa");
         }
 }
void RasterImage_RGB::copyInto (RasterImage * imgOut) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
Implements uriVL::RasterImage.
Definition at line 387 of file RasterImage_RGB.cpp.
References uriVL::DrawableObject2D::getValidRect().
Referenced by copyInto().
 {
     copyInto(imgOut, getValidRect(), NULL);
 }
void RasterImage_RGB::copyInto (RasterImage * imgOut, const ImageRect * theRect) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab).
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
Implements uriVL::RasterImage.
Definition at line 392 of file RasterImage_RGB.cpp.
References copyInto().
 {
     copyInto(imgOut, theRect, NULL);
 }
void RasterImage_RGB::copyInto (RasterImage * imgOut, const ImageRect * theRect, const ImagePoint * origin) const virtual
Copies this image into the one received as parameter.
Copies (rather than clones) this image into the destination image received as parameter. Depending on the types of this image and of the destination image, the copy may require some data conversion (for example, HSV to Lab). If the raster(s) of the destination image does not have the same dimensions as the source, then the destination image's raster are re-allocated.
Parameters
imgOut pointer to the destination image
theRect region of the image to copy
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Definition at line 397 of file RasterImage_RGB.cpp.
References uriVL::RasterImage::copyInto_(), FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::ImageRect::intersection(), uriVL::kDense, uriVL::kUriBaseError, uriVL::DrawableObject2D::setDrawableInformationType(), uriVL::DrawableObject2D::setValidRect(), and writeInto_().
 {
     //  All the rectangle testing and resizing is done in the parent class' function
     RasterImage::copyInto_(imgOut, theRect, origin);
     //  We only copy from the validRect_, so we need to calculate its intersection
     //  with theRect.
     ImageRect* copyRect = ImageRect::intersection(getValidRect(), theRect);
     FAIL_CONDITION( copyRect == NULL,
                     kUriBaseError,
                     "the copy rectangle specified is not within valid data");
     //  For the time being, we only handle regular dense rasters
     imgOut->setDrawableInformationType(kDense);
     writeInto_(imgOut, copyRect, origin);
         imgOut->setValidRect(copyRect);
     delete copyRect;
 }
void RasterImage_RGB::deleteRaster2D_ (void) private virtual
Deletes the 0-based 2D base raster.
Implements uriVL::RasterImage.
Definition at line 879 of file RasterImage_RGB.cpp.
References rgb2D_.
Referenced by setBoundRect_(), and ~RasterImage_RGB().
 {
     if (rgb2D_ != NULL)
     {
         delete []rgb2D_;
         rgb2D_ = NULL;
     }
 }
void RasterImage_RGB::deleteShiftedRaster2D_ (int iLow) private virtual
Deletes the 2D shifted base raster.
Parameters
iLow start index for rows
Implements uriVL::RasterImage.
Definition at line 919 of file RasterImage_RGB.cpp.
References shiftedRgb2D_.
Referenced by allocateShiftedRaster2D_(), setBoundRect_(), and ~RasterImage_RGB().
 {
     if (shiftedRgb2D_ != NULL)
     {
         shiftedRgb2D_ += iLow;
         delete []shiftedRgb2D_;
         shiftedRgb2D_ = NULL;
     }
 }
BaseRasterType RasterImage_RGB::getBaseRasterType (void) const virtual
Returns the image's base raster type.
Returns the following value:
- kRGB24Raster, since this image is based on the 24-bit rgb color format
Returns
the image's base raster type
Implements uriVL::RasterImage.
Definition at line 271 of file RasterImage_RGB.cpp.
References uriVL::kRGB24Raster.
 {
     return kRGB24Raster;
 }
const unsigned char * RasterImage_RGB::getRGB (void) const
Returns the 24-bit rgb base raster as a read-only 1D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGB. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGB data in the 1D base raster).
Returns
1D base raster for this image
Definition at line 276 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, and uriVL::kGWorldIsNullError.
Referenced by allocateShiftedRaster2D_().
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGB subclass did not properly override getGray()");
     return gworld_->getRaster();
 }
unsigned char * RasterImage_RGB::getRGB (ReadWriteStatus rw)
Returns the 24-bit rgb base raster as a read-write 1D array.
This method is virtual and should be overridden by all subclasses of RasterImage_RGB. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGB data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
1D base raster for this image
Definition at line 285 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::GraphWorld::getRaster(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, and uriVL::RasterImage::referenceHasChanged_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGB subclass did not properly override getGray()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return gworld_->getRaster();
 }
const unsigned char *const * RasterImage_RGB::getRGB2D (void) const
Returns the 24-bit rgb base raster as a read-only 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGB data in the 1D base raster).
Returns
2D base raster for this image
Definition at line 302 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, uriVL::kGWorldIsNullError, and rgb2D_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGB subclass did not properly override getGray()");
     return rgb2D_;
 }
unsigned char *const * RasterImage_RGB::getRGB2D (ReadWriteStatus rw)
Returns the 24-bit rgb base raster as a read-write 2D array.
If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGB data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
2D base raster for this image
Definition at line 311 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, uriVL::RasterImage::referenceHasChanged_, and rgb2D_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGB subclass did not properly override getGray()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     return rgb2D_;
 }
const unsigned char *const * RasterImage_RGB::getShiftedRGB2D (void) const
Returns the shifted 24-bit rgba base raster as a constant2D array.
The shifted raster has index bounds defined by the image's rectangle. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
Returns
shifted 2D base raster for this image
Definition at line 326 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::gworld_, uriVL::kGWorldIsNullError, rgb2D_, and shiftedRgb2D_.
Referenced by uriVL::RasterImage_HSV::convertFromRGB_(), uriVL::ImageArithmetics::difference_(), and writeInto_().
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return rgb2D_;
     else
         return shiftedRgb2D_;
 }
unsigned char *const * RasterImage_RGB::getShiftedRGB2D (ReadWriteStatus rw)
Returns the shifted 24-bit rgba base raster as a read-write 2D array.
The shifted raster has index bounds defined by the image's rectangle. If the base raster has not already been allocated, then it should be allocated and initialized using the reference information for the image (for example, HSV data should be converted into RGBA data in the 1D base raster).
A side-effect of calling the read-write version of a getRaster function is that the base (GraphWorld) raster is set to be the reference and is marked as 'changed'
Parameters
rw R_W_ACCESS is the only acceptable value
Returns
shifted 2D base raster for this image
Definition at line 341 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::kGWorldIsNullError, uriVL::RasterImage::referenceHasChanged_, rgb2D_, and shiftedRgb2D_.
 {
     FAIL_CONDITION( gworld_ == NULL,
                     kGWorldIsNullError,
                     "RasterImage_RGBa subclass did not properly override getRGBa2D()");
     //  A side-effect of calling the read-write version of a getRaster function is
     //  that the base (GraphWorld) raster is set to be the reference and is marked
     //  as 'changed'
     gworldIsReference_= true;
     referenceHasChanged_ = true;
     //  if the image has its upper left corner at the origin, then
     //  the shifted raster is just a copy of the unshifted one.
     //  no point wasting space.
     if ((getTop()==0) && (getLeft()==0))
         return rgb2D_;
     else
         return shiftedRgb2D_;
 }
const RasterImage_RGB & RasterImage_RGB::operator= (const RasterImage_RGB & theImg) private
Equal operator.
Created so that gcc will stop complaining. This RasterImage_RGB object will retain its own id.
Parameters
theImg reference to the RasterImage_RGB object to copy
Definition at line 379 of file RasterImage_RGB.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
{
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "RasterImage_RGB copy operator not implemented");
         return *this;
 }
void RasterImage_RGB::setBoundRect_ (int x, int y, int theWidth, int theHeight) private virtual
Sets a new Sets a new bounding rectangle for the raster image.
A raster image occupies a rectangle within the global image space. For example, a raster image could be defined as a subpart of another. This operation may require a reallocation of the raster image.
This function could be overridden by child classes
Parameters
x X coordinate of the image's origin
y Y coordinate of the image's origin
theWidth desired width of the image
theHeight desired height of the image
(no re-allocation needed)
Implements uriVL::DrawableObject2D.
Definition at line 797 of file RasterImage_RGB.cpp.
References allocateGraphWorld_(), allocateRaster2D_(), allocateShiftedRaster2D_(), deleteRaster2D_(), deleteShiftedRaster2D_(), FAIL_CONDITION, uriVL::DrawableObject2D::getBottom(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getLeft(), uriVL::DrawableObject2D::getTop(), uriVL::DrawableObject2D::getWidth(), uriVL::RasterImage::graphWorldIsNull_(), uriVL::RasterImage::gworld_, uriVL::kAccessToLockedData, uriVL::RasterImage::propertiesAreLocked_, and shiftedRgb2D_.
 {
     FAIL_CONDITION( propertiesAreLocked_,
                     kAccessToLockedData,
                     "Attempt to resize a RasterImage with locked properties");
     //  if width and height have not changed, then the operation is just a translation.
     //  All we need to do is update the ImageRect member and update the "shifted" array
     /// (no re-allocation needed)
     if ((theWidth == getWidth()) && (theHeight == getHeight()))
     {
         if ((x != getLeft()) || (y != getTop()))
         {
             //  Since the rasters have the same dimensions, there is no need
             //  to delete and reallocate the shifted rasters.  Just apply a
             //  relative shift to them
             const int   iLow  = getTop(),
                                                 iHigh = getBottom(),
                                                 jLow = getLeft(),
                                                 rowShift = y - iLow,
                                                 colShift = 3*(x - jLow);
 if(shiftedRgb2D_)
 {
             for (int i=iLow; i<=iHigh; i++)
                 shiftedRgb2D_[i] += colShift;
             shiftedRgb2D_ += rowShift;
 }
         }
         //  if nothing has changed, there is nothing to do
     }
     //  if the dimensions of the rectangles are different, then we must delete
     //  and reallocate the GraphWorld as well as the 0-based 2D raster.
     else
     {
         //      I am not sure if this is the right thing to do: should subclasses completely
         //      reimplement this or call this function?  This is opting for the latter.
         if (!graphWorldIsNull_())
         {
             delete gworld_;
             deleteShiftedRaster2D_(y);
             deleteRaster2D_();
             allocateGraphWorld_(theHeight, theWidth);
             allocateRaster2D_(theHeight, theWidth);
             allocateShiftedRaster2D_(theHeight, theWidth, y, x);
         }
     }
 }
void RasterImage_RGB::updateRaster_ (void) const private virtual
Forces an update of the base rgb raster if it is not the reference raster.
This virtual function should be overridden by all subclasses of RasterImage_RGB.
Implements uriVL::RasterImage.
Definition at line 367 of file RasterImage_RGB.cpp.
References uriVL::RasterImage::referenceHasChanged_.
Referenced by writeInto_().
 {
     referenceHasChanged_ = false;
 }
void RasterImage_RGB::writeInto_ (RasterImage * imgOut, const ImageRect * rect, const ImagePoint * origin) const private virtual
Writes into another image the part of this image specified by a rectangle, using the point specified as origin for this image's valid rectangle's upper-left corner.
Contrary to copyInto this function does not resize the destination image if it is smaller than the source. It does not even modify the valid data rectangle of the destination image. It just writes in the intersection of the destination rectangle and of this image's valid data rectangle. Fails if the destination rectangle is not contained by the source image.
Parameters
imgOut the image to write into
rect specifies the part of the source to write into the destination
origin the point to use as origin for this image's valid data rectangle's upper-left corner.
Implements uriVL::RasterImage.
Definition at line 420 of file RasterImage_RGB.cpp.
References convertToGray(), uriVL::GraphWorld::copyInto(), uriVL::RasterImage::defaultGrayConv_, FAIL_CONDITION, uriVL::RasterImage::getBaseRasterType(), uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::DrawableObject2D::getLeft(), uriVL::ImageRect::getRight(), getShiftedRGB2D(), uriVL::ImageRect::getTop(), uriVL::DrawableObject2D::getTop(), uriVL::ImageRect::getWidth(), uriVL::DrawableObject2D::getWidth(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), uriVL::RasterImage::gworld_, uriVL::RasterImage::gworldIsReference_, uriVL::RasterImage::hasFloatRaster(), uriVL::kBinaryRaster, uriVL::kGrayRaster, uriVL::kRasterImageError, uriVL::kRGB24Raster, uriVL::kRGBa32Raster, uriVL::kSaturatedPositive, uriVL::R_W_ACCESS, uriVL::RasterImage::referenceHasChanged_, and updateRaster_().
Referenced by copyInto().
 {
         //  The GWorld only works with unshifted rasters so we need to compute
         //  the "true" copy rectangles first
     ImageRect*  sourceRect = new ImageRect(copyRect->getLeft() - getLeft(),
                                                                                    copyRect->getTop() - getTop(),
                                                                                    copyRect->getWidth(), copyRect->getHeight());
         ImageRect*  destRect =  origin == NULL ?
                                                         new ImageRect(copyRect->getLeft() - imgOut->getLeft(),
                                           copyRect->getTop() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight())
                                                         :
                                                         new ImageRect(origin->getX() - imgOut->getLeft(),
                                           origin->getY() - imgOut->getTop(),
                                           copyRect->getWidth(), copyRect->getHeight());
     //  Subclasses should override this function, but in case they don't, we need to
     //  do the conversion through the base rgb raster.
     if (!gworldIsReference_ && referenceHasChanged_)
         updateRaster_( );
     switch( imgOut->getBaseRasterType() )
     {
         case kBinaryRaster:
             //  The GWorld only works with unshifted rasters so we need to compute
             //  the "true" copy rectangles first
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
             imgOut->gworldIsReference_ = true;
             imgOut->referenceHasChanged_ = true;
             break;
         case kGrayRaster:
             //  are we dealing with a gray or gray_F image?
             //
             //  The output image is a "regular" gray image [unsigned char]
             if (!imgOut->hasFloatRaster())
             {
                 //  At this point we are ready to perform the copy/conversion and we use
                 //  the CopyBits function of QuickDraw/QuickTime
                 gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, true);
                 imgOut->gworldIsReference_ = true;
                 imgOut->referenceHasChanged_ = true;
               }
             //  if the image has a floating point raster, we write into it.
                         //      why???
                                 else
             {
                 const int   iLowSource = copyRect->getTop(),
                             iHighSource = copyRect->getBottom(),
                             jLowSource = copyRect->getLeft();
                 int    iLowDest, jLowDest;
                 //
                 if (origin==NULL)
                 {
                     iLowDest = iLowSource;
                     jLowDest = jLowSource;
                 }
                 else
                 {
                     iLowDest = origin->getY();
                     jLowDest = origin->getX();
                 }
                 const int nbCols = getWidth();
                 const unsigned char* const* rgbSource = getShiftedRGB2D();
                 float* const* fltGrayDest= (static_cast<RasterImage_gray_F*>(imgOut))->getShiftedGrayF2D(R_W_ACCESS);
                 for (int i=iLowSource, iDest=iLowDest; i<=iHighSource; i++, iDest++)
                     convertToGray(rgbSource[i]+jLowSource, fltGrayDest[iDest]+jLowDest,
                                    nbCols, defaultGrayConv_);
                 (static_cast<RasterImage_gray_F*>(imgOut))->setFloatConversionMode(kSaturatedPositive);
                 imgOut->gworldIsReference_ = false;
                 imgOut->referenceHasChanged_ = true;
             }
             break;
         case kRGB24Raster:
             //  At this point we are ready to perform the copy/conversion and we use
             //  the CopyBits function of QuickDraw/QuickTime
             gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
             imgOut->gworldIsReference_ = true;
             imgOut->referenceHasChanged_ = true;
              break;
         case kRGBa32Raster:
             //  are we dealing with a RGB or RGB_F image?
             //
             //  The output image is a "regular" RGB image [unsigned char]
             if (!imgOut->hasFloatRaster())
             {
                  //  At this point we are ready to perform the copy/conversion and we use
                 //  the CopyBits function of QuickDraw/QuickTime
                 gworld_->copyInto(imgOut->gworld_, sourceRect, destRect, false);
                 imgOut->gworldIsReference_ = true;
                 imgOut->referenceHasChanged_ = true;
             }
             // imgOut has float type
             else
             {
                 const int   iLowSource = copyRect->getTop(),
                             iHighSource = copyRect->getBottom(),
                             jLowSource = copyRect->getLeft(),
                             jHighSource = copyRect->getRight();
                 int iLowDest, jLowDest;
                 //
                 if (origin==NULL)
                 {
                     iLowDest = iLowSource;
                     jLowDest = jLowSource;
                 }
                 else
                 {
                     iLowDest = origin->getY();
                     jLowDest = origin->getX();
                 }
                 const unsigned char* const* rgbSource = getShiftedRGB2D();
                 float* const* fltRedDest= (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedRedF2D(R_W_ACCESS);
                 float* const* fltGreenDest= (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedGreenF2D(R_W_ACCESS);
                 float* const* fltBlueDest= (static_cast<RasterImage_RGBa_F*>(imgOut))->getShiftedBlueF2D(R_W_ACCESS);
                 for (int i=iLowSource, iDest=iLowDest; i<=iHighSource; i++, iDest++)
                                 for(int j=jLowSource, k=3*jLowSource, jDest=jLowDest; j<=jHighSource; j++, jDest++)
{
                             fltRedDest[iDest][jDest] = rgbSource[i][k++];
                                                 fltGreenDest[iDest][jDest] = rgbSource[i][k++];
                                                 fltBlueDest[iDest][jDest] = rgbSource[i][k++];
                                         }
                 (static_cast<RasterImage_RGBa_F*>(imgOut))->setFloatConversionMode(kSaturatedPositive);
                 imgOut->gworldIsReference_ = false;
                 imgOut->referenceHasChanged_ = true;
             }
             break;
         default:
             FAIL_CONDITION( true,
                             kRasterImageError,
                             "Invalid image type in RasterImage_gray::writeInto_");
             break;
     }
     if (sourceRect != NULL)
         delete sourceRect;
     if (destRect != NULL)
         delete destRect;
 }
Friends And Related Function Documentation
friend class _GraphWorld_gen friend
Definition at line 494 of file RasterImage_RGB.h.
Member Data Documentation
unsigned char** uriVL::RasterImage_RGB::rgb2D_ private
2D array mapped on the GraphWorld's 1D raster.
Definition at line 383 of file RasterImage_RGB.h.
Referenced by allocateRaster2D_(), deleteRaster2D_(), getRGB2D(), getShiftedRGB2D(), and RasterImage_RGB().
unsigned char** uriVL::RasterImage_RGB::shiftedRgb2D_ private
"shifted" 2D array (based on the image's rectangle bounds) mapped on the GraphWorld's 1D raster.
Definition at line 389 of file RasterImage_RGB.h.
Referenced by allocateShiftedRaster2D_(), deleteShiftedRaster2D_(), getShiftedRGB2D(), and setBoundRect_().
The documentation for this class was generated from the following files:
RasterImage_RGB.h
RasterImage_RGB.cpp