URIVisionLibrary: uriVL::Transformation2D Class Reference
uriVL::Transformation2D Class Reference
Virtual base class for all 2D transformation that can be represented by a 3 by 3 homogenous matrix.
#include <Transformation2D.h>
Public Member Functions
Transformation2D (bool isRigid=false)
Constructor.
Transformation2D (const float theMat[][3])
Constructor.
Transformation2D (const float *const *theMat)
Constructor.
Transformation2D (const Transformation2D *theTransf)
Copy constructor.
Transformation2D (const Transformation2D &theTransf)
Copy constructor.
virtual ~Transformation2D (void)
Destructor.
const Transformation2D & operator= (const Transformation2D &theTransf)
Equal operator.
virtual void setMatrix (const float theMat[][3])
Assign a new matrix to this transformation.
virtual void setMatrix (const float *const *theMat)
Assign a new matrix to this transformation.
const float *const *const getMatrix (void) const
Returns a read-only pointer to the transformation's matrix data.
float *const *const getMatrix (ReadWriteStatus rwa)
Returns a pointer to the transformation's's matrix data that allows to set new values to the matrix's elements.
ImagePoint_F * applyTo (const ImagePoint *pt)
Applies this transformation to the image point received as parameter.
ImagePoint_F * applyInto (const ImagePoint *pt, const ImagePoint *transfPt)
Applies this transformation to the image point received as parameter.
bool isRigidTransformation (void) const
Indicates whether this transftormation is rigid (rotation + translation)
Protected Member Functions
bool checkOrthogonality_ (void) const
Check whether the matrix is orthogonal.
Private Attributes
float ** mat_
the 3x3 homogeneous matrix that stores the transformation.
bool isRigidTransformation_
Indicates whether this transftormation is rigid (rotation + translation)
TransformationQuality quality_
Store an indicator of the transformation's quality.
Detailed Description
Virtual base class for all 2D transformation that can be represented by a 3 by 3 homogenous matrix.
Author
jean-yves herv
Version
I%, G%
Definition at line 40 of file Transformation2D.h.
Constructor & Destructor Documentation
Transformation2D::Transformation2D (bool isRigid = false)
Constructor.
Creates an identity transformation 3D.
Parameters
isRigid indicates whether this is a rigid transformation
Definition at line 29 of file Transformation2D.cpp.
References mat_.
                 :       mat_(new float*[3]),
                     isRigidTransformation_(isRigid),
                         quality_(kUnknown)
 {
     //  initializes an identity transformation matrix
     for (int i=0; i<3; i++)
         mat_[i] = new float[3];
     mat_[0][1] = mat_[0][2] = 0;
     mat_[1][0] = mat_[1][2] = 0;
     mat_[2][0] = mat_[2][1] = 0;
     mat_[0][0] = mat_[1][1] = mat_[2][2] = 1;
 }
Transformation2D::Transformation2D (const float theMat[][3])
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat 3 by 3 transformation matrix
Definition at line 46 of file Transformation2D.cpp.
References checkOrthogonality_(), isRigidTransformation_, mat_, and setMatrix().
                 :       mat_(new float*[3]),
                     isRigidTransformation_(false),
                         quality_(kUnknown)
 {
     for (int i=0; i<3; i++)
         mat_[i] = new float[3];
     setMatrix(theMat);
     isRigidTransformation_ = checkOrthogonality_();
 }
Transformation2D::Transformation2D (const float *const * theMat)
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat 3 by 3 transformation matrix
Definition at line 59 of file Transformation2D.cpp.
References uriVL::ErrorReport::appendToMessage(), checkOrthogonality_(), FAIL_CONDITION, isRigidTransformation_, uriVL::kNullParameterError, mat_, and setMatrix().
                 :       mat_(NULL),
                     isRigidTransformation_(false),
                         quality_(kUnknown)
 {
         FAIL_CONDITION( theMat == NULL,
                                         kNullParameterError,
                                         "Null 2d pointer passed to Transformation2D constructor.");
         mat_ = new float*[3];
         for (int i=0; i<3; i++)
         mat_[i] = new float[3];
         try {
                 setMatrix(theMat);
         }
         catch (ErrorReport& e) {
                 for (int i=0; i<3; i++)
                         delete []mat_[i];
                 delete []mat_;
                 e.appendToMessage("called from Transformation2D constructor.");
                 throw e;
         }
     isRigidTransformation_ = checkOrthogonality_();
 }
Transformation2D::Transformation2D (const Transformation2D * theTransf)
Copy constructor.
Creates a 3D transformation identical to the one received as parameter
Parameters
theTransf transformation to copy
Definition at line 87 of file Transformation2D.cpp.
References checkOrthogonality_(), FAIL_CONDITION, isRigidTransformation_, uriVL::kInvalidParameterError, uriVL::kNullParameterError, and mat_.
                 :       mat_(NULL),
                     isRigidTransformation_(false),
                         quality_(kUnknown)
 {
         FAIL_CONDITION( theTransf==NULL,
                                         kNullParameterError,
                                         "NULL Transformation2D passed to Transformation2D copy constructor");
     //  this class can only work with matrices.  If subclasses want to
     //  be smarter, they will have to provide code for that
         try {
                 mat_ = new float*[3];
                 for (int i=0; i<3; i++)
                 {
                         mat_[i] = new float[3];
                         for (int j=0; j<3; j++)
                                 mat_[i][j] = theTransf->mat_[i][j];
                 }
     }
         catch (...) {
                 for (int i=0; i<3; i++)
                         delete []mat_[i];
                 delete []mat_;
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid Transformation2D passed to Transformation2D copy constructor");
         }
     //  if the transformation to copy is orthofgonal, use this info, otherwise verify
         //      the matrix.
     isRigidTransformation_ = theTransf->isRigidTransformation_ ? true : checkOrthogonality_();
 }
Transformation2D::Transformation2D (const Transformation2D & theTransf)
Copy constructor.
Creates a 3D transformation identical to the one received as parameter.
            Not implemented yet while we try to settle issue regarding constness and
            mutability of mat_ and related flags
Parameters
theTransf transformation to copy
Definition at line 125 of file Transformation2D.cpp.
References checkOrthogonality_(), FAIL_CONDITION, isRigidTransformation_, uriVL::kInvalidParameterError, and mat_.
                 :       mat_(NULL),
                     isRigidTransformation_(false),
                         quality_(kUnknown)
 {
     //  this class can only work with matrices.  If subclasses want to
     //  be smarter, they will have to provide code for that
         try {
                 mat_ = new float*[3];
                 for (int i=0; i<3; i++)
                 {
                         mat_[i] = new float[3];
                         for (int j=0; j<3; j++)
                                 mat_[i][j] = theTransf.mat_[i][j];
                 }
     }
         catch (...) {
                 for (int i=0; i<3; i++)
                         delete []mat_[i];
                 delete []mat_;
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid Transformation2D passed to Transformation2D copy constructor");
         }
     //  if the transformation to copy is orthofgonal, use this info, otherwise verify
         //      the matrix.
     isRigidTransformation_ = theTransf.isRigidTransformation_ ? true : checkOrthogonality_();
 }
Transformation2D::~Transformation2D (void) virtual
Destructor.
Definition at line 159 of file Transformation2D.cpp.
References mat_.
 {
     for (int i=0; i<3; i++)
         delete []mat_[i];
     delete []mat_;
 }
Member Function Documentation
ImagePoint_F* uriVL::Transformation2D::applyInto (const ImagePoint * pt, const ImagePoint * transfPt)
Applies this transformation to the image point received as parameter.
Parameters
pt the image point to apply this transformation to
transfPt the image point resulting from applying this transformation to pt
ImagePoint_F* uriVL::Transformation2D::applyTo (const ImagePoint * pt)
Applies this transformation to the image point received as parameter.
Parameters
pt the image point to apply this transformation to
Returns
a new ImagePoint_F object
bool Transformation2D::checkOrthogonality_ (void) const protected
Check whether the matrix is orthogonal.
Returns
true if the matrix is orthogonal
Definition at line 183 of file Transformation2D.cpp.
References mat_.
Referenced by uriVL::RigidTransformation2D::setMatrix(), and Transformation2D().
 {
         // last row must be  0 0 1
         if ((mat_[2][0] != 0.f) || (mat_[2][1] != 0.f) || (mat_[2][2] != 1.f))
                 return false;
         const float SMALL_VAL = (float) 1.0E-5;
         const float dotProd01 = mat_[0][0]*mat_[0][1] + mat_[1][0]*mat_[1][1];
         if (fabsf(dotProd01) > SMALL_VAL)
                 return false;
         const float norm0 = mat_[0][0]*mat_[0][0] + mat_[1][0]*mat_[1][0];
         if (fabsf(norm0 - 1.f) > SMALL_VAL)
                 return false;
         const float norm1 = mat_[0][1]*mat_[0][1] + mat_[1][1]*mat_[1][1];
         if (fabsf(norm1 - 1.f) > SMALL_VAL)
                 return false;
         return true;
 }
const float *const *const Transformation2D::getMatrix (void) const
Returns a read-only pointer to the transformation's matrix data.
If you want to have full read-write access to the data, call instead getMatrixRW.
Returns
the matrice's private read-only 2D array of data
Definition at line 241 of file Transformation2D.cpp.
References mat_.
Referenced by uriVL::Registration2D_ICP::costFunc_SAD_(), uriVL::Registration2D_ICP::costFunc_SSD_(), uriVL::Registration2D_ICP::findBestMatch_(), uriVL::RigidTransformation2D::getTransX(), uriVL::RigidTransformation2D::getTransY(), uriVL::Registration2D_ICP::llsSolutionTransformation(), uriVL::RigidTransformation2D::orthogonalizeMatrix_(), uriVL::RigidTransformation2D::setAngle(), and uriVL::RigidTransformation2D::setTranslation().
 {
     return mat_;
 }
float *const *const Transformation2D::getMatrix (ReadWriteStatus rwa)
Returns a pointer to the transformation's's matrix data that allows to set new values to the matrix's elements.
As a side effect, this function sets the matrix to become the reference for this transformation.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the matrix's private read-write 2D array of data
Definition at line 236 of file Transformation2D.cpp.
References mat_.
 {
     return mat_;
 }
bool Transformation2D::isRigidTransformation (void) const
Indicates whether this transftormation is rigid (rotation + translation)
Definition at line 255 of file Transformation2D.cpp.
References isRigidTransformation_.
Referenced by uriVL::Contour_F::applyTransformation(), uriVL::Contour_I::applyTransformation(), uriVL::Blob::applyTransformation(), uriVL::Registration2D_ICP::costFunc_SAD_(), uriVL::Registration2D_ICP::costFunc_SSD_(), uriVL::Registration2D_ICP::findBestMatch_(), and uriVL::RigidTransformation2D::RigidTransformation2D().
 {
     return isRigidTransformation_;
 }
const Transformation2D & Transformation2D::operator= (const Transformation2D & theTransf)
Equal operator.
Created so that gcc will stop complaining.
            Not implemented yet while we try to settle issue regarding constness and
            mutability of mat_ and related flags
Parameters
theTransf reference to the Transformation2D object to copy
Definition at line 167 of file Transformation2D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "Transformation2D = operator not implemented yet");
         return *this;
 }
void Transformation2D::setMatrix (const float theMat[][3]) virtual
Assign a new matrix to this transformation.
The new matrix is now the reference for this transformation.
Parameters
theMat 3x3 transformation matrix
Reimplemented in uriVL::RigidTransformation2D.
Definition at line 216 of file Transformation2D.cpp.
References mat_.
Referenced by uriVL::RigidTransformation2D::setMatrix(), and Transformation2D().
 {
     for (int i=0; i<3; i++)
         for (int j=0; j<3; j++)
             mat_[i][j] = theMat[i][j];
 }
void Transformation2D::setMatrix (const float *const * theMat) virtual
Assign a new matrix to this transformation.
The new matrix is now the reference for this transformation.
Parameters
theMat 3x3 transformation matrix
Definition at line 224 of file Transformation2D.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, and mat_.
 {
     FAIL_CONDITION( theMat == NULL,
                     kNullParameterError,
                     "NULL matrix passed to Transformation2D::setMatrix");
     for (int i=0; i<3; i++)
         for (int j=0; j<3; j++)
             mat_[i][j] = theMat[i][j];
 }
Member Data Documentation
bool uriVL::Transformation2D::isRigidTransformation_ private
Indicates whether this transftormation is rigid (rotation + translation)
Definition at line 169 of file Transformation2D.h.
Referenced by isRigidTransformation(), and Transformation2D().
float** uriVL::Transformation2D::mat_ mutable private
the 3x3 homogeneous matrix that stores the transformation.
This matrix is the reference by default (unless explicitely changed by the user)
Definition at line 165 of file Transformation2D.h.
Referenced by checkOrthogonality_(), getMatrix(), setMatrix(), Transformation2D(), and ~Transformation2D().
TransformationQuality uriVL::Transformation2D::quality_ private
Store an indicator of the transformation's quality.
Where does it come from? Is it the result of a composition of good quality transformations, of registration calculations?
Definition at line 175 of file Transformation2D.h.
The documentation for this class was generated from the following files:
Transformation2D.h
Transformation2D.cpp