URIVisionLibrary: uriVL::IntrinsicParameters Class Reference
uriVL::IntrinsicParameters Class Reference abstract
Parent class for all descriptors of a camera's intrinsic parameters.
#include <IntrinsicParameters.h>
Public Member Functions
IntrinsicParameters (const IntrinsicParameters *theParams)
Cloner constructor.
IntrinsicParameters (int theWidth, int theHeight)
Constructor.
virtual ~IntrinsicParameters (void)
Destructor.
int getWidth (void) const
Returns the width (in pixels) of the raster digitized.
int getHeight (void) const
Returns the height (in pixels) of the raster digitized.
virtual bool hasDistortion (void) const =0
Indicates whether this object has a forward distortion calculation function.
virtual bool hasUndistortion (void) const =0
Indicates whether this object has an undistortion calculation function.
virtual void distortPixels (double ux, double uy, double *dx, double *dy) const
Applies distortion to an image point (pixels).
virtual void distortMetric (double ux, double uy, double *dx, double *dy) const
Applies distortion to an image point (m)
virtual void undistortPixel (double dx, double dy, double *ux, double *uy) const
Applies undistortion to an image point (pixels)
virtual void undistortMetric (double dx, double dy, double *ux, double *uy) const
Applies undistortion to an image point (m)
virtual void metricToPixel (double mx, double my, double *px, double *py) const
Transforms metric coordinates into pixel coordinates.
virtual void pixelToMetric (double px, double py, double *mx, double *my) const
Transforms pixel coordinates into metric coordinates.
Protected Attributes
int Nfx_
number of frame grabber elements horizontally
int Nfy_
number of frame grabber elements vertically
Detailed Description
Parent class for all descriptors of a camera's intrinsic parameters.
A "camera" is a device (physical or virtual) that digitizes data to produce a raster. One could select to produce a raster for a small subpart of the available surface, but this would be a characteristic of the raster image produced, not of the camera.
Since calculating the intrinsic parameters of a camera is an operation that is performed unfrequently, I have decided not to provide any "setVariable" method. The use desiring modify the value of a particular parameter should therefore create a new IntrinsicParameter object initialized with the proper values for all the parameters.
The basic geometric properties of a camera are the dimensions of the digitizable rectangle. Subclasses will add information relative to the optics of the camera (focal length, coordinates of the origin, distortion) and the details of the digitizing device (number and size of sensor elements).
I have hesitated a long time about it, moving instance variables and functions relative to distortion and transformations between "pixel" and "world" coordinates back and forth between this class and its subclassses. I have finally decided to define at the root class the following functions:
pixelToMetric
metricToPixel
distortMetric
distortPixel
undistortMetric
undistortPixel
Users of these functions should however be aware that
unless coordinates of the image center have been defined (IntrinsicParameters_pinhole and its subclasses), the image center is assumed to be at (0, 0).
unless dimensions of pixels have been defined (IntrinsicParameters_CCD and its subclasses), pixel and "metric" units are identical
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 69 of file IntrinsicParameters.h.
Constructor & Destructor Documentation
IntrinsicParameters::IntrinsicParameters (const IntrinsicParameters * theParams)
Cloner constructor.
Parameters
theParams object to clone
Definition at line 22 of file IntrinsicParameters.cpp.
References FAIL_CONDITION, and uriVL::kNullParameterError.
                 :       Nfx_(theParams->Nfx_),
                         Nfy_(theParams->Nfy_)
 {
         FAIL_CONDITION( theParams == NULL,
                                         kNullParameterError,
                                         "Attempt to clone a null IntrinsicParameters object");
 }
 catch(...) {
         FAIL_CONDITION( theParams == NULL,
                                         kNullParameterError,
                                         "null pointer passed to IntrinsicParameters copy constructor.");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "invalid parameter passed to IntrinsicParameters copy constructor.");
 }
IntrinsicParameters::IntrinsicParameters (int theWidth, int theHeight)
Constructor.
Parameters
theWidth width of digitizable area (in pixels)
theHeight height of digitizable area (in pixels)
Definition at line 41 of file IntrinsicParameters.cpp.
References FAIL_CONDITION, and uriVL::kInvalidParameterError.
                 :       Nfx_(theWidth),
                         Nfy_(theHeight)
 {
         FAIL_CONDITION( (theWidth < 3) || (theHeight < 3),
                                         kInvalidParameterError,
                                         "invalid dimensions passed to IntrinsicParameters constructor.");
 cout << "IntrinsicParameters int-int constructor" << endl;
 }
IntrinsicParameters::~IntrinsicParameters (void) virtual
Destructor.
Definition at line 61 of file IntrinsicParameters.cpp.
 {
 }
Member Function Documentation
void IntrinsicParameters::distortMetric (double ux, double uy, double * dx, double * dy) const virtual
Applies distortion to an image point (m)
Should be overridden by classes that have distortion parameters
Parameters
ux x coordinate (m) of the input undistorted point
uy y coordinate (m) of the input undistorted point
dx x coordinate (m) of the output distorted point
dy y coordinate (m) of the output distorted point
See also
hasDistortion
Reimplemented in uriVL::IntrinsicParameters_DLT, and uriVL::IntrinsicParameters_TsaiW.
Definition at line 91 of file IntrinsicParameters.cpp.
 {
         *dx = ux;
         *dy = uy;
 }
void IntrinsicParameters::distortPixels (double ux, double uy, double * dx, double * dy) const virtual
Applies distortion to an image point (pixels).
Should be overridden by classes that have distortion parameters
Parameters
ux x coordinate (pixel) of the input undistorted point
uy y coordinate (pixel) of the input undistorted point
dx x coordinate (pixel) of the output distorted point
dy y coordinate (pixel) of the output distorted point
See also
hasDistortion
Reimplemented in uriVL::IntrinsicParameters_DLT, and uriVL::IntrinsicParameters_TsaiW.
Definition at line 81 of file IntrinsicParameters.cpp.
 {
         *dx = ux;
         *dy = uy;
 }
int IntrinsicParameters::getHeight (void) const
Returns the height (in pixels) of the raster digitized.
Returns
height (in pixels) of the raster digitized
Definition at line 70 of file IntrinsicParameters.cpp.
References Nfy_.
Referenced by uriVL::Calibration3D_Kim::calibrate(), and uriVL::Camera::getHeight().
 {
         return Nfy_;
 }
int IntrinsicParameters::getWidth (void) const
Returns the width (in pixels) of the raster digitized.
Returns
width (in pixels) of the raster digitized
Definition at line 65 of file IntrinsicParameters.cpp.
References Nfx_.
Referenced by uriVL::Calibration3D_Kim::calibrate(), and uriVL::Camera::getWidth().
 {
         return Nfx_;
 }
virtual bool uriVL::IntrinsicParameters::hasDistortion (void) const pure virtual
Indicates whether this object has a forward distortion calculation function.
Must be implemented by subclasses.
Returns
true if this object has a forward distortion calculation function
See also
distortMetric
distortPixel
Implemented in uriVL::IntrinsicParameters_TsaiW, uriVL::IntrinsicParameters_pinhole, and uriVL::IntrinsicParameters_CCD.
virtual bool uriVL::IntrinsicParameters::hasUndistortion (void) const pure virtual
Indicates whether this object has an undistortion calculation function.
Must be implemented by subclasses.
Returns
true if this object has ann undistortion calculation function
See also
undistortMetric
undistortPixel
Implemented in uriVL::IntrinsicParameters_TsaiW, uriVL::IntrinsicParameters_pinhole, and uriVL::IntrinsicParameters_CCD.
void IntrinsicParameters::metricToPixel (double mx, double my, double * px, double * py) const virtual
Transforms metric coordinates into pixel coordinates.
Should be overridden by subclasses that introduce the notion of a projection center, for example, IntrinsicParameters_TsaiW, or pixel dimensions, for example, IntrinsicParameters_CCD.
Parameters
mx metrix x coordinate of a point
my metrix y coordinate of a point
px pixel x coordinate of that point
py pixel y coordinate of that point
Reimplemented in uriVL::IntrinsicParameters_DLT, uriVL::IntrinsicParameters_TsaiW, uriVL::IntrinsicParameters_pinhole, and uriVL::IntrinsicParameters_CCD.
Definition at line 122 of file IntrinsicParameters.cpp.
 {
     *px = mx;
     *py = my;
 }
void IntrinsicParameters::pixelToMetric (double px, double py, double * mx, double * my) const virtual
Transforms pixel coordinates into metric coordinates.
Should be overridden by subclasses that introduce the notion of a projection center, for example, IntrinsicParameters_TsaiW, or pixel dimensions, for example, IntrinsicParameters_CCD.
Parameters
px pixel x coordinate of a point
py pixel y coordinate of a point
mx metrix x coordinate of that point
my metrix y coordinate of that point
Reimplemented in uriVL::IntrinsicParameters_DLT, uriVL::IntrinsicParameters_TsaiW, uriVL::IntrinsicParameters_pinhole, and uriVL::IntrinsicParameters_CCD.
Definition at line 132 of file IntrinsicParameters.cpp.
 {
     //  apply scale
     *mx = px;
     *my = py;
 }
void IntrinsicParameters::undistortMetric (double dx, double dy, double * ux, double * uy) const virtual
Applies undistortion to an image point (m)
Should be overridden by classes that have distortion parameters
Parameters
dx x coordinate (m) of the input distorted point
dy y coordinate (m) of the input distorted point
ux x coordinate (m) of the output undistorted point
uy y coordinate (m) of the output undistorted point
See also
hasunDistortion
Reimplemented in uriVL::IntrinsicParameters_DLT, and uriVL::IntrinsicParameters_TsaiW.
Definition at line 112 of file IntrinsicParameters.cpp.
 {
         *ux = dx;
         *uy = dy;
 }
void IntrinsicParameters::undistortPixel (double dx, double dy, double * ux, double * uy) const virtual
Applies undistortion to an image point (pixels)
Should be overridden by classes that have distortion parameters
Parameters
dx x coordinate (pixel) of the input distorted point
dy y coordinate (pixel) of the input distorted point
ux x coordinate (pixel) of the output undistorted point
uy y coordinate (pixel) of the output undistorted point
See also
hasunDistortion
Reimplemented in uriVL::IntrinsicParameters_DLT, and uriVL::IntrinsicParameters_TsaiW.
Definition at line 101 of file IntrinsicParameters.cpp.
 {
         *ux = dx;
         *uy = dy;
 }
Member Data Documentation
int uriVL::IntrinsicParameters::Nfx_ protected
number of frame grabber elements horizontally
Definition at line 198 of file IntrinsicParameters.h.
Referenced by getWidth().
int uriVL::IntrinsicParameters::Nfy_ protected
number of frame grabber elements vertically
Definition at line 202 of file IntrinsicParameters.h.
Referenced by getHeight().
The documentation for this class was generated from the following files:
IntrinsicParameters.h
IntrinsicParameters.cpp