URIVisionLibrary: uriVL::StereoPair Class Reference
uriVL::StereoPair Class Reference
Future versions of this class will/should include information about the cameras corresponding to each image (and their relative transformations and respective parameters)
#include <StereoPair.h>
Public Member Functions
StereoPair (RasterImage *leftImg, RasterImage *rightImg, RigidTransformation3D *transf, bool isRect=false)
For the time being the class does not store private copies of the left and right images Constructor.
StereoPair (Camera *leftCamera, Camera *rightCamera, bool isRect=false)
Constructor.
StereoPair (RasterImage *leftImg, RasterImage *rightImg, Camera *leftCamera, Camera *rightCamera, bool isRect=false)
Constructor.
~StereoPair (void)
Destructor.
void setImages (RasterImage *leftImg, RasterImage *rightImg)
Assigns the stereo pair with left image and right image.
RasterImage * getLeftImage (void)
Returns left image of the stereo pair.
RasterImage * getRightImage (void)
Returns right image of the stereo pair.
RasterImage * getImage (StereoImageID l_or_r)
Returns image.
const ImageRect * getValidRect (StereoImageID l_or_r)
Returns image rectangle.
Camera * getLeftCamera (void)
Indicates whethher this stereo pair is rectified.
Camera * getRightCamera (void)
Returns right Camera of the stereo pair.
bool isRectified (void)
Returns image.
Public Member Functions inherited from uriVL::Entity3D
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Protected Member Functions
StereoPair (bool isRect=false)
Default constructor.
Protected Member Functions inherited from uriVL::Entity3D
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Private Member Functions
StereoPair (const StereoPair &theObj)
Copy Constructor.
const StereoPair & operator= (const StereoPair &theObj)
Copy operator.
Private Attributes
Camera * leftCamera_
left camera of stereo pair
Camera * rightCamera_
right camera of stereo pair
RasterImage * leftImg_
left image of stereo pair
RasterImage * rightImg_
right image of stereo pair
RigidTransformation3D * transf_
Rigid transformation (rotation & translation between the two cameras)
bool isRectified_
Indicates whethher this stereo pair is rectified.
Detailed Description
Future versions of this class will/should include information about the cameras corresponding to each image (and their relative transformations and respective parameters)
Definition at line 39 of file StereoPair.h.
Constructor & Destructor Documentation
StereoPair::StereoPair (RasterImage * leftImg, RasterImage * rightImg, RigidTransformation3D * transf, bool isRect = false)
For the time being the class does not store private copies of the left and right images Constructor.
Creates a stereo pair with left image, right image and transformation
Parameters
leftImg left image of stereo pair
rightImg right image of stereo pair
transf Rigid transformation between the left and right cameras
isRect true if the pair of images has been rectified
Definition at line 30 of file StereoPair.cpp.
References FAIL_CONDITION, and uriVL::kComputerVisionError.
                 :           leftCamera_(NULL),
                                 rightCamera_(NULL),
                                 leftImg_(leftImg),
                                 rightImg_(rightImg),
                                 transf_(transf),
                                 isRectified_(isRect)
 {
     FAIL_CONDITION( true,
                     kComputerVisionError,
                     "function not implemented yet");
     //  The cameras are assumed to be orthographic
 }
StereoPair::StereoPair (Camera * leftCamera, Camera * rightCamera, bool isRect = false)
Constructor.
Creates a stereo pair with left camera, right camera and rectangle
Parameters
leftCamera left camera
rightCamera right camera
isRect true if the pair of images has been rectified
Definition at line 45 of file StereoPair.cpp.
References FAIL_CONDITION, and uriVL::kComputerVisionError.
                 :           leftCamera_(leftCamera),
                                 rightCamera_(rightCamera),
                                 leftImg_(NULL),
                                 rightImg_(NULL),
                                 transf_(NULL),
                                 isRectified_(isRect)
 {
     FAIL_CONDITION( true,
                     kComputerVisionError,
                     "function not implemented yet");
 }
StereoPair::StereoPair (RasterImage * leftImg, RasterImage * rightImg, Camera * leftCamera, Camera * rightCamera, bool isRect = false)
Constructor.
Creates a stereo pair with left camera, right camera, left image and right image
Parameters
leftImg left image of stereo pair
rightImg right image of stereo pair
leftCamera left camera
rightCamera right camera
isRect true if the pair of images has been rectified
Definition at line 58 of file StereoPair.cpp.
References FAIL_CONDITION, and uriVL::kComputerVisionError.
                 :           leftCamera_(leftCamera),
                                 rightCamera_(rightCamera),
                                 leftImg_(leftImg),
                                 rightImg_(rightImg),
                                 transf_(NULL),
                                 isRectified_(isRect)
 {
     FAIL_CONDITION( true,
                     kComputerVisionError,
                     "function not implemented yet");
 }
StereoPair::~StereoPair (void)
Destructor.
Definition at line 86 of file StereoPair.cpp.
 {
 }
StereoPair::StereoPair (bool isRect = false) protected
Default constructor.
Parameters
isRect true if the pair of images has been rectified
Definition at line 19 of file StereoPair.cpp.
                 :           leftCamera_(NULL),
                                 rightCamera_(NULL),
                                 leftImg_(NULL),
                                 rightImg_(NULL),
                                 transf_(NULL),
                                 isRectified_(isRect)
 {
 }
StereoPair::StereoPair (const StereoPair & theObj) private
Copy Constructor.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 72 of file StereoPair.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                 :           leftCamera_(NULL),
                                 rightCamera_(NULL),
                                 leftImg_(NULL),
                                 rightImg_(NULL),
                                 transf_(NULL),
                                 isRectified_(false)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoPair copy constructor not implemented");
 }
Member Function Documentation
RasterImage * StereoPair::getImage (StereoImageID l_or_r)
Returns image.
Returns
left image if l_or_r is 0, otherwise, return right image
Definition at line 122 of file StereoPair.cpp.
References uriVL::LEFT_IMAGE, leftImg_, and rightImg_.
 {
         if (l_or_r == LEFT_IMAGE)
                 return leftImg_;
         else
                 return rightImg_;
 }
Camera * StereoPair::getLeftCamera (void)
Indicates whethher this stereo pair is rectified.
Returns left Camera of the stereo pair
Returns
left Camera
Definition at line 140 of file StereoPair.cpp.
References leftCamera_.
 {
         return leftCamera_;
 }
RasterImage * StereoPair::getLeftImage (void)
Returns left image of the stereo pair.
Returns
left image
Definition at line 112 of file StereoPair.cpp.
References leftImg_.
Referenced by uriVL::RectifiedStereoMatcher_corr::match_(), and uriVL::RectifiedStereoMatcher_JJL::setStereoPair().
 {
         return leftImg_;
 }
Camera * StereoPair::getRightCamera (void)
Returns right Camera of the stereo pair.
Returns
right Camera
Definition at line 144 of file StereoPair.cpp.
References rightCamera_.
 {
         return rightCamera_;
 }
RasterImage * StereoPair::getRightImage (void)
Returns right image of the stereo pair.
Returns
right image
Definition at line 117 of file StereoPair.cpp.
References rightImg_.
Referenced by uriVL::RectifiedStereoMatcher_corr::match_(), and uriVL::RectifiedStereoMatcher_JJL::setStereoPair().
 {
         return rightImg_;
 }
const ImageRect * StereoPair::getValidRect (StereoImageID l_or_r)
Returns image rectangle.
Returns
image rectangle acoording to l_or_r
Definition at line 131 of file StereoPair.cpp.
References uriVL::DrawableObject2D::getValidRect(), uriVL::LEFT_IMAGE, leftImg_, and rightImg_.
Referenced by uriVL::RectifiedStereoMatcher_JJL::match(), uriVL::StereoMatcher::match(), and uriVL::RectifiedStereoMatcher_JJL::setStereoPair().
 {
         if (l_or_r == LEFT_IMAGE)
                 return leftImg_->getValidRect();
         else
                 return rightImg_->getValidRect();
 }
bool StereoPair::isRectified (void)
Returns image.
Returns
left image if l_or_r is 0, otherwise, return right image
Definition at line 149 of file StereoPair.cpp.
References isRectified_.
Referenced by uriVL::RectifiedStereoMatcher_corr::match_(), and uriVL::RectifiedStereoMatcher::setStereoPair().
 {
         return isRectified_;
 }
const StereoPair & StereoPair::operator= (const StereoPair & theObj) private
Copy operator.
Disabled
Parameters
theObj reference to the object to copy
Definition at line 90 of file StereoPair.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "StereoPair copy operator not implemented");
         return *this;
 }
void StereoPair::setImages (RasterImage * leftImg, RasterImage * rightImg)
Assigns the stereo pair with left image and right image.
Parameters
leftImg left image of stereo pair
rightImg right image of stereo pair
Definition at line 99 of file StereoPair.cpp.
References FAIL_CONDITION, uriVL::kNullRasterImageError, leftImg_, and rightImg_.
 {
          FAIL_CONDITION( leftImg == NULL,
                     kNullRasterImageError,
                     "null left RasterImage as parameter in StereoPair::setImages");
          FAIL_CONDITION( rightImg == NULL,
                     kNullRasterImageError,
                     "null right RasterImage as parameter in StereoPair::setImages");
      leftImg_ = leftImg;
      rightImg_ = rightImg;
 }
Member Data Documentation
bool uriVL::StereoPair::isRectified_ private
Indicates whethher this stereo pair is rectified.
Definition at line 160 of file StereoPair.h.
Referenced by isRectified().
Camera* uriVL::StereoPair::leftCamera_ private
left camera of stereo pair
Definition at line 138 of file StereoPair.h.
Referenced by getLeftCamera().
RasterImage* uriVL::StereoPair::leftImg_ private
left image of stereo pair
Definition at line 147 of file StereoPair.h.
Referenced by getImage(), getLeftImage(), getValidRect(), and setImages().
Camera* uriVL::StereoPair::rightCamera_ private
right camera of stereo pair
Definition at line 142 of file StereoPair.h.
Referenced by getRightCamera().
RasterImage* uriVL::StereoPair::rightImg_ private
right image of stereo pair
Definition at line 151 of file StereoPair.h.
Referenced by getImage(), getRightImage(), getValidRect(), and setImages().
RigidTransformation3D* uriVL::StereoPair::transf_ private
Rigid transformation (rotation & translation between the two cameras)
Definition at line 156 of file StereoPair.h.
The documentation for this class was generated from the following files:
StereoPair.h
StereoPair.cpp