URIVisionLibrary: uriVL::Transformation3D Class Reference
uriVL::Transformation3D Class Reference abstract
Virtual base class for all 3D transformation that can be represented by a 4 by 4 homogenous matrix.
#include <Transformation3D.h>
Public Member Functions
Transformation3D (void)
Constructor.
Transformation3D (const double *glMat)
Constructor.
Transformation3D (const double theMat[][4])
Constructor.
Transformation3D (const HomogeneousMatrix *theMat)
Constructor.
Transformation3D (const Transformation3D *theTransf)
Clone constructor.
virtual ~Transformation3D (void)
Destructor.
const HomogeneousMatrix * getMatrix (void) const
Returns a read-only reference frame to this transformation's matrix.
HomogeneousMatrix * getMatrix (ReadWriteStatus rwa)
Returns a writable reference frame to this transformation's matrix.
const GLfloat * getGLMatrix (void) const
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a read-only "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
Protected Member Functions
void setMatrixAsReference_ (bool state)
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
virtual void updateMatrix_ (void) const =0
Updates the transformation matrix if it was not the reference.
Protected Attributes
HomogeneousMatrix * homMat_
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a writable "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
bool matrixIsReference_
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
bool referenceHasChanged_
Indicates that whatever constitues the reference for this object (e.g.
Private Member Functions
Transformation3D (const Transformation3D &obj)
Copy constructor.
const Transformation3D & operator= (const Transformation3D &obj)
Copy operator.
Detailed Description
Virtual base class for all 3D transformation that can be represented by a 4 by 4 homogenous matrix.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 34 of file Transformation3D.h.
Constructor & Destructor Documentation
Transformation3D::Transformation3D (void)
Constructor.
Creates an identity transformation 3D.
Definition at line 19 of file Transformation3D.cpp.
     :       homMat_(new HomogeneousMatrix()),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
 }
Transformation3D::Transformation3D (const double * glMat)
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
glMat a flat, GL-style (transposed) transformation matrix
Definition at line 26 of file Transformation3D.cpp.
     :       homMat_(new HomogeneousMatrix(glMat)),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
 }
Transformation3D::Transformation3D (const double theMat[][4])
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat 4 by 4 transformation matrix
Definition at line 33 of file Transformation3D.cpp.
     :       homMat_(new HomogeneousMatrix(theMat)),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
 }
Transformation3D::Transformation3D (const HomogeneousMatrix * theMat)
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat homogeneous transformation matrix
Definition at line 40 of file Transformation3D.cpp.
     :       homMat_(new HomogeneousMatrix(theMat)),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
 }
Transformation3D::Transformation3D (const Transformation3D * theTransf)
Clone constructor.
Creates a 3D transformation identical to the one received as parameter
Parameters
theTransf transformation to clone
Definition at line 48 of file Transformation3D.cpp.
References FAIL_CONDITION, homMat_, uriVL::kNullTransformation3D, matrixIsReference_, referenceHasChanged_, and updateMatrix_().
     :       homMat_(NULL),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
     FAIL_CONDITION( theTransf==NULL,
                     kNullTransformation3D,
                     "Attempt to clone a NULL Transformation3D");
     //  this class can only work with matrices.  If subclasses want to
     //  be smarter, they will have to provide code for that
     if (!theTransf->matrixIsReference_)
         theTransf->updateMatrix_();
     //  and now we can copy the matrix.
     homMat_ = new HomogeneousMatrix(theTransf->homMat_);
     matrixIsReference_ = true;
     referenceHasChanged_ = true;
 }
Transformation3D::~Transformation3D (void) virtual
Destructor.
Definition at line 80 of file Transformation3D.cpp.
References homMat_.
 {
         delete homMat_;
 }
Transformation3D::Transformation3D (const Transformation3D & obj) private
Copy constructor.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 69 of file Transformation3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
     :       homMat_(NULL),
             matrixIsReference_(true),
             referenceHasChanged_(true)
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "Transformation3D copy constructor not implemented");
 }
Member Function Documentation
const GLfloat * Transformation3D::getGLMatrix (void) const
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a read-only "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
Returns
the OpenGL transformation matrix of this transformation
Definition at line 128 of file Transformation3D.cpp.
References uriVL::HomogeneousMatrix::getGLMatrix(), homMat_, matrixIsReference_, referenceHasChanged_, and updateMatrix_().
 {
     if (!matrixIsReference_  &&referenceHasChanged_)
         updateMatrix_();
     return homMat_->getGLMatrix();
 }
const HomogeneousMatrix * Transformation3D::getMatrix (void) const
Returns a read-only reference frame to this transformation's matrix.
If the matrix was not the reference and not up-to-date, its value is updated first.
Returns
the transformation matrix of this transformation
Definition at line 111 of file Transformation3D.cpp.
References homMat_, matrixIsReference_, referenceHasChanged_, and updateMatrix_().
Referenced by uriVL::RigidTransformation3D::postComposeTransformation().
 {
     if (!matrixIsReference_  && referenceHasChanged_)
         updateMatrix_();
     return homMat_;
 }
HomogeneousMatrix * Transformation3D::getMatrix (ReadWriteStatus rwa)
Returns a writable reference frame to this transformation's matrix.
If the matrix was not the reference and not up-to-date, its value is updated first.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the transformation matrix of this transformation
Definition at line 119 of file Transformation3D.cpp.
References homMat_, matrixIsReference_, referenceHasChanged_, and updateMatrix_().
 {
     if (!matrixIsReference_  &&referenceHasChanged_)
         updateMatrix_();
     referenceHasChanged_ = true;
     return homMat_;
 }
const Transformation3D & Transformation3D::operator= (const Transformation3D & obj) private
Copy operator.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 90 of file Transformation3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "Transformation3D copy operator not implemented");
     return *this;
 }
void Transformation3D::setMatrixAsReference_ (bool state) protected
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
Whenever redundant storage is used in this library, as with the transformation matrix and the Rotation3D and Translation3D objects of a RigidTransformation3D, a boolean variable is used to indicate which is the current "true" value.
Parameters
state true if the matrix should be used as reference
Definition at line 99 of file Transformation3D.cpp.
References matrixIsReference_, and referenceHasChanged_.
 {
     matrixIsReference_ = state;
     referenceHasChanged_ = true;
 }
virtual void uriVL::Transformation3D::updateMatrix_ (void) const protected pure virtual
Updates the transformation matrix if it was not the reference.
This virtual function should be implemented by all subclasses.
Implemented in uriVL::RigidTransformation3D.
Referenced by getGLMatrix(), getMatrix(), and Transformation3D().
Member Data Documentation
HomogeneousMatrix* uriVL::Transformation3D::homMat_ mutable protected
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a writable "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the OpenGL transformation matrix of this transformationthe 4x4 homogeneous matrix that stores the transformation. This matrix is the reference by default (unless explicitely changed by the user). This variable is mutalbe because if it is not the reference then it can be updated without any real change to the object
Definition at line 117 of file Transformation3D.h.
Referenced by getGLMatrix(), getMatrix(), uriVL::RigidTransformation3D::RigidTransformation3D(), Transformation3D(), uriVL::RigidTransformation3D::updateMatrix_(), and ~Transformation3D().
bool uriVL::Transformation3D::matrixIsReference_ protected
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
Whenever redundant storage is used in this library, as with the transformation matrix and the Rotation3D and Translation3D objects of a RigidTransformation3D, a boolean variable us used to indicate which is the current "true" value.
Definition at line 125 of file Transformation3D.h.
Referenced by getGLMatrix(), getMatrix(), uriVL::RigidTransformation3D::RigidTransformation3D(), setMatrixAsReference_(), Transformation3D(), and uriVL::RigidTransformation3D::updateMatrix_().
bool uriVL::Transformation3D::referenceHasChanged_ mutable protected
Indicates that whatever constitues the reference for this object (e.g.
matrix, rotation angles + translation) ha been modified. When this is true, non-reference representations must be updated before they are used
Definition at line 131 of file Transformation3D.h.
Referenced by getGLMatrix(), getMatrix(), uriVL::RigidTransformation3D::RigidTransformation3D(), setMatrixAsReference_(), Transformation3D(), and uriVL::RigidTransformation3D::updateMatrix_().
The documentation for this class was generated from the following files:
Transformation3D.h
Transformation3D.cpp