URIVisionLibrary: uriVL::VirtualPoint3D Class Reference
uriVL::VirtualPoint3D Class Reference
Implements the VirtualPoint3D class.
#include <VirtualPoint3D.h>
Public Member Functions
VirtualPoint3D (double X, double Y, double Z, VirtualPart3D *thePart)
Constructor.
VirtualPoint3D (const double theXYZ[], VirtualPart3D *thePart)
Constructor.
VirtualPoint3D (const Point3D *thePt)
Cloner constructor.
~VirtualPoint3D (void)
Destructor.
double getX (void) const
Returns the point's X coordinate.
double getY (void) const
Returns the point's Y coordinate.
double getZ (void) const
Returns the point's Z coordinate.
const double * getXYZ (void) const
Returns the point's coordinates vector.
void setPosition (const double XYZ[])
Assigns new x coordinate to the point.
void setPosition (double X, double Y, double Z)
Assigns new x coordinate to the point.
double distanceTo (const VirtualPoint3D *p) const
Returns the distance between this point and the one received as parameter.
const VisibilityStatus * getVisibility (int camIndex) const
Reports the visibility status of the virtual point relatve to a specific camera.
void setVisibility (int camIndex, const VisibilityStatus *vis)
Sets the visibility status of the virtual point relatve to a specific camera.
void setColor (float theRed, float theGreen, float theBlue)
void setColor (const float rgb[])
void addNeighbor (VirtualPoint3D *pt)
Adds neighbor points to the 3D point.
void addFaceInfo (int faceIndex, int uvIndex, int normalIndex)
Adds information about a virtual face the point belongs to.
void setSelected (bool selected)
Called to select/deselect a VirtualPoint3D.
bool isSelected (void) const
void setSelectedNeighbor (bool selectedNeighbor)
Called to select/deselect a VirtualPoint3D.
void setRenderScale (GLfloat renderScale)
Assigns a new rendering scale to this virtual point.
Public Member Functions inherited from uriVL::Entity3D
virtual ~Entity3D (void)
Non-operative destructor.
void setReferenceFrame (const ReferenceFrame3D *ref)
Sets the reference frame relative to which the 3D entity is defined.
const ReferenceFrame3D * getReferenceFrame (void) const
Returns the reference frame relative to which the 3D entity is defined.
bool isGrouped (void) const
Indicates whether this object belongs to a group.
void addToGroup (const Entity3D *group)
Function to invoke to add this Entity3D to a group.
void addMember (const Entity3D *member)
Function to invoke to add an Entity3D to this group.
void leaveGroup (void)
This function releases this object from the group it belongs to.
Static Public Member Functions
static void setRenderMode (VirtualRenderMode mode)
Private Member Functions
VirtualPoint3D (const VirtualPoint3D &obj)
Copy constructor.
const VirtualPoint3D & operator= (const VirtualPoint3D &obj)
Copy operator.
void setNbCameras_ (int n)
void render_ (int camIndex) const
Private Attributes
Point3D * point_
The Point3D this object is based on.
VirtualPart3D * part_
Reference to the VirtualPart3D (of a VirtualObject3D) that the point belongs to.
VisibilityStatus ** visibility_
Stores visibility status relatrive to each known camera.
std::vector< int > normalIndex_
std::vector< int > uvIndex_
std::vector< VirtualPoint3D * > neighbors_
GLfloat * color_
the point's RGB color
bool isSelected_
bool isSelectedNeighbor_
GLfloat renderScale_
Rendering scale for this virtual point.
bool hasIndividualRenderScale_
Does this virtual point have its own rendering scale?
Static Private Attributes
static VirtualPoint3D * currentSelected_ = NULL
static const GLfloat defaultRenderScale_ = 0.005f
Default scale to use to render the Point3D as a small cube.
static const GLfloat defaultColor_ [4] = {0.f, 1.f, 0.f, 1.f}
static VirtualRenderMode renderMode_ = INTERPOSE
Friends
class VirtualPart3D
class VirtualObject3D
Additional Inherited Members
Protected Member Functions inherited from uriVL::Entity3D
Entity3D (const ReferenceFrame3D *theFrame)
Contructor.
Entity3D (void)
Default contructor.
Detailed Description
Implements the VirtualPoint3D class.
A VirtualPoint3D belongs to a VirtualPart3D to be embedded into a real scene for 1-n cameras. A VirtualPoint3D object stores the 3D coordinates of a point as well as information about normal directions, visibility relative ot cameras, etc.
Author
Fang Han, 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 67 of file VirtualPoint3D.h.
Constructor & Destructor Documentation
VirtualPoint3D::VirtualPoint3D (double X, double Y, double Z, VirtualPart3D * thePart)
Constructor.
Creates a 3D point belonging to the VirtualPart3D passed as parameter
Parameters
X X coordinate of the point
Y Y coordinate of the point
Z Z coordinate of the point
thePart the part of a virtual object this point is created relative to
Definition at line 39 of file VirtualPoint3D.cpp.
References uriVL::VirtualPart3D::addVertex().
                         :       Entity3D(thePart->getReferenceFrame()),
                                 //
                                 point_(new Point3D(X, Y, Z, thePart->getReferenceFrame())),
                                 part_(NULL),
                                 visibility_(NULL),
                                 normalIndex_(vector<int>(0)),
                                 uvIndex_(vector<int>(0)),
                                 neighbors_(vector<VirtualPoint3D*>(0)),
                                 color_(NULL),
                                 isSelected_(false),
                                 isSelectedNeighbor_(false),
                                 renderScale_(1.f),
                                 hasIndividualRenderScale_(false)
 {
     thePart->addVertex(this);
 }
 catch (...)
 {
     FAIL_CONDITION( thePart==NULL,
                     kNullEntity3D,
                     "null VirtualPart3D passed to VirtualPoint3D constructor");
 }
VirtualPoint3D::VirtualPoint3D (const double theXYZ[], VirtualPart3D * thePart)
Constructor.
Creates a 3D point in the reference frame received as parameter
Parameters
theXYZ coordinate array of the point
thePart the part of a virtual object this point is created relative to
Definition at line 63 of file VirtualPoint3D.cpp.
References uriVL::VirtualPart3D::addVertex().
                         :       Entity3D(thePart->getReferenceFrame()),
                                 //
                                 point_(new Point3D(theXYZ, thePart->getReferenceFrame())),
                                 part_(NULL),
                                 visibility_(NULL),
                                 normalIndex_(vector<int>(0)),
                                 uvIndex_(vector<int>(0)),
                                 neighbors_(vector<VirtualPoint3D*>(0)),
                                 color_(NULL),
                                 isSelected_(false),
                                 isSelectedNeighbor_(false),
                                 renderScale_(1.f),
                                 hasIndividualRenderScale_(false)
 {
     thePart->addVertex(this);
 }
 catch (...)
 {
     FAIL_CONDITION( thePart==NULL,
                     kNullEntity3D,
                     "null VirtualPart3D passed to VirtualPoint3D constructor");
 }
VirtualPoint3D::VirtualPoint3D (const Point3D * thePt)
Cloner constructor.
Creates a clone of the VirtualPoint3D object passed as parameter (including that point's reference frame).
Parameters
thePt pointer to the Point3D object to clone
Definition at line 87 of file VirtualPoint3D.cpp.
                         :       Entity3D(thePt->getReferenceFrame()),
                                 //
                                 point_(new Point3D(thePt)),
                                 part_(NULL),
                                 visibility_(NULL),
                                 normalIndex_(vector<int>(0)),
                                 uvIndex_(vector<int>(0)),
                                 neighbors_(vector<VirtualPoint3D*>(0)),
                                 color_(NULL),
                                 isSelected_(false),
                                 isSelectedNeighbor_(false),
                                 renderScale_(1.f),
                                 hasIndividualRenderScale_(false)
 {
 }
 catch (...)
 {
     FAIL_CONDITION( thePt==NULL,
                     kNullEntity3D,
                     "null Point3D passed to VirtualPoint3D constructor");
 }
VirtualPoint3D::~VirtualPoint3D (void)
Destructor.
Definition at line 140 of file VirtualPoint3D.cpp.
References point_.
 {
         delete point_;
 }
VirtualPoint3D::VirtualPoint3D (const VirtualPoint3D & obj) private
Copy constructor.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 111 of file VirtualPoint3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       Entity3D(),
                                 //
                                 point_(NULL),
                                 part_(NULL),
                                 visibility_(NULL),
                                 normalIndex_(),
                                 uvIndex_(),
                                 neighbors_(),
                                 color_(NULL),
                                 isSelected_(false),
                                 isSelectedNeighbor_(false),
                                 renderScale_(1.f),
                                 hasIndividualRenderScale_(false)
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "VirtualPoint3D copy constructor not implemented");
 }
Member Function Documentation
void VirtualPoint3D::addFaceInfo (int faceIndex, int uvIndex, int normalIndex)
Adds information about a virtual face the point belongs to.
Parameters
faceIndex index of the face we are adding information about
uvIndex uh??? not sure anymore
normalIndex same here
Definition at line 207 of file VirtualPoint3D.cpp.
References normalIndex_, and uvIndex_.
 {
     //  if the face index vector is too small, resize it to be able to add an element
     //  at the new faceIndex
     if (faceIndex >= static_cast<int>(normalIndex_.size())) {
         for (int i=normalIndex_.size(); i<=faceIndex; i++)
         {
             normalIndex_.push_back(-1);
             uvIndex_.push_back(-1);
         }
     }
     vector<int>::iterator normal = normalIndex_.begin();
     vector<int>::iterator uv = uvIndex_.begin();
     normal[faceIndex] = normalIndex;
     uv[faceIndex] = uvIndex;
 }
void VirtualPoint3D::addNeighbor (VirtualPoint3D * pt)
Adds neighbor points to the 3D point.
Parameters
pt the 3D point
Definition at line 201 of file VirtualPoint3D.cpp.
References neighbors_.
 {
         neighbors_.push_back(pt);
 }
double VirtualPoint3D::distanceTo (const VirtualPoint3D * p) const
Returns the distance between this point and the one received as parameter.
Parameters
p the point to which the distance must be computed
Returns
the distnace between this point and p
Definition at line 175 of file VirtualPoint3D.cpp.
References uriVL::Point3D::distanceTo(), FAIL_CONDITION, uriVL::kNullEntity3D, and point_.
 {
     FAIL_CONDITION( p==NULL,
                     kNullEntity3D,
                     "Attempt to calculate distance to a NULL Point3D");
     return point_->distanceTo(p->point_);
 }
const VisibilityStatus * VirtualPoint3D::getVisibility (int camIndex) const
Reports the visibility status of the virtual point relatve to a specific camera.
Parameters
camIndex index of the camera rwlative to which we inquire about visibility
Returns
visibility status relative to this camera
Definition at line 280 of file VirtualPoint3D.cpp.
References visibility_.
Referenced by uriVL::VirtualPart3D::render().
 {
     return visibility_[camIndex];
 }
double VirtualPoint3D::getX (void) const
Returns the point's X coordinate.
Returns
X coordinate of the point
Definition at line 145 of file VirtualPoint3D.cpp.
References uriVL::Point3D::getX(), and point_.
 {
     return point_->getX();
 }
const double * VirtualPoint3D::getXYZ (void) const
Returns the point's coordinates vector.
Returns
a pointer to the object's private coordinate vector.
Definition at line 160 of file VirtualPoint3D.cpp.
References uriVL::Point3D::getXYZ(), and point_.
Referenced by uriVL::VirtualPart3D::render().
 {
     return point_->getXYZ();
 }
double VirtualPoint3D::getY (void) const
Returns the point's Y coordinate.
Returns
Y coordinate of the point
Definition at line 150 of file VirtualPoint3D.cpp.
References uriVL::Point3D::getY(), and point_.
 {
     return point_->getY();
 }
double VirtualPoint3D::getZ (void) const
Returns the point's Z coordinate.
Returns
Z coordinate of the point
Definition at line 155 of file VirtualPoint3D.cpp.
References uriVL::Point3D::getZ(), and point_.
 {
     return point_->getZ();
 }
bool VirtualPoint3D::isSelected (void) const
Definition at line 261 of file VirtualPoint3D.cpp.
References isSelected_.
 {
         return isSelected_;
 }
const VirtualPoint3D & VirtualPoint3D::operator= (const VirtualPoint3D & obj) private
Copy operator.
Disabled.
Parameters
obj reference to the object to copy
Definition at line 132 of file VirtualPoint3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION (true,
                     kFunctionNotImplemented,
                     "VirtualPoint3D copy operator not implemented");
     return *this;
 }
void VirtualPoint3D::render_ (int camIndex) const private
Definition at line 298 of file VirtualPoint3D.cpp.
References color_, defaultColor_, defaultRenderScale_, uriVL::Point3D::getX(), uriVL::Point3D::getY(), uriVL::Point3D::getZ(), hasIndividualRenderScale_, uriVL::INTERPOSE, isSelected_, isSelectedNeighbor_, point_, renderMode_, and renderScale_.
 {
         //  drawing a small square
         glPushMatrix();
         //  Move from the reference frame to this point
         glTranslatef(static_cast<float>(point_->getX()),
                                  static_cast<float>(point_->getY()),
                                  static_cast<float>(point_->getZ()));
         if (renderMode_ == INTERPOSE)
                 if (color_ != NULL)
                         glColor4fv(color_);
                 else
                         glColor4fv(defaultColor_);
         else if (isSelected_)
                         glColor4f(1.f, 0.f, 0.f, 1.f);
         else if (isSelectedNeighbor_)
                 glColor4f(1.f, 1.f, 0.f, 1.f);
         else
                 glColor4fv(defaultColor_);
         if (hasIndividualRenderScale_)
                 glScalef(renderScale_, renderScale_, renderScale_);
         else
                 glScalef(defaultRenderScale_, defaultRenderScale_, defaultRenderScale_);
         glBegin(GL_QUAD_STRIP);
                 glVertex3f(-1.f, -1.f, 1.f);
                 glVertex3f(-1.f, -1.f, -1.f);
                 glVertex3f(1.f, -1.f, 1.f);
                 glVertex3f(1.f, -1.f, -1.f);
                 glVertex3f(1.f, 1.f, 1.f);
                 glVertex3f(1.f, 1.f, -1.f);
                 glVertex3f(-1.f, 1.f, 1.f);
                 glVertex3f(-1.f, 1.f, -1.f);
                 glVertex3f(-1.f, -1.f, 1.f);
                 glVertex3f(-1.f, -1.f, -1.f);
         glEnd();
         glBegin(GL_QUADS);
                 glVertex3f(-1.f, -1.f, 1.f);
                 glVertex3f(1.f, -1.f, 1.f);
                 glVertex3f(1.f, 1.f, 1.f);
                 glVertex3f(-1.f, 1.f, 1.f);
                 glVertex3f(-1.f, -1.f, -1.f);
                 glVertex3f(-1.f, 1.f, -1.f);
                 glVertex3f(1.f, 1.f, -1.f);
                 glVertex3f(1.f, -1.f, -1.f);
         glEnd();
         glPopMatrix();
 }
void VirtualPoint3D::setColor (float theRed, float theGreen, float theBlue)
Definition at line 184 of file VirtualPoint3D.cpp.
References color_.
Referenced by setColor().
 {
     if (color_ == NULL)
         color_ = new GLfloat[4];
     color_[0] = theRed;
     color_[1] = theGreen;
     color_[2] = theBlue;
     color_[3] = 1.f;
 }
void VirtualPoint3D::setColor (const float rgb[])
Definition at line 195 of file VirtualPoint3D.cpp.
References setColor().
 {
     if (rgb!=NULL)
         setColor(rgb[0], rgb[1], rgb[2]);
 }
void VirtualPoint3D::setNbCameras_ (int n) private
Definition at line 271 of file VirtualPoint3D.cpp.
References visibility_.
 {
         if (visibility_ != NULL)
                 delete visibility_;
         visibility_ = new VisibilityStatus *[n];
         for (int i=0; i<n; i++)
                 visibility_[i] = new VisibilityStatus();
 }
void VirtualPoint3D::setPosition (const double XYZ[])
Assigns new x coordinate to the point.
Parameters
XYZ new coordinate array for the 3D point
Definition at line 165 of file VirtualPoint3D.cpp.
References point_, and uriVL::Point3D::setPosition().
 {
     point_->setPosition(XYZ);
 }
void VirtualPoint3D::setPosition (double X, double Y, double Z)
Assigns new x coordinate to the point.
Parameters
X X coordinate of the point
Y Y coordinate of the point
Z Z coordinate of the point
Definition at line 170 of file VirtualPoint3D.cpp.
References point_, and uriVL::Point3D::setPosition().
 {
     point_->setPosition(X, Y, Z);
 }
void VirtualPoint3D::setRenderMode (VirtualRenderMode mode) static
Definition at line 266 of file VirtualPoint3D.cpp.
References renderMode_.
Referenced by uriVL::VirtualObject3D::setRenderMode().
 {
         renderMode_ = mode;
 }
void VirtualPoint3D::setRenderScale (GLfloat renderScale)
Assigns a new rendering scale to this virtual point.
Parameters
renderScale new rendering scale for this virtual point
Definition at line 285 of file VirtualPoint3D.cpp.
References hasIndividualRenderScale_, and renderScale_.
 {
     hasIndividualRenderScale_ = true;
     renderScale_ = renderScale;
 }
void VirtualPoint3D::setSelected (bool selected)
Called to select/deselect a VirtualPoint3D.
Parameters
selected tells whether the point should be selected
Definition at line 225 of file VirtualPoint3D.cpp.
References currentSelected_, isSelected_, neighbors_, and setSelected().
Referenced by setSelected().
 {
         if (selected == true){
                 //  if a point was selected before, deselect it
                 if (currentSelected_ != NULL)
                     currentSelected_->setSelected(false);
                 //  this point is selected
                 isSelected_ = true;
                 currentSelected_ = this;
                 //  all its neighbors are selected neighbors
                 vector <VirtualPoint3D*>:: iterator nb, endNeighbor = neighbors_.end();
                 for (nb = neighbors_.begin(); nb != endNeighbor; nb++)
                     (*nb)->setSelectedNeighbor(true);
         }
         else{
             //  deselect this point
                 isSelected_ = false;
                 //  deselect all neighbors as selected neighbors
                 //  all its neighbors are selected neighbors
                 vector <VirtualPoint3D*>:: iterator nb, endNeighbor = neighbors_.end();
                 for (nb = neighbors_.begin(); nb != endNeighbor; nb++)
                     (*nb)->setSelectedNeighbor(false);
         }
 }
void VirtualPoint3D::setSelectedNeighbor (bool selectedNeighbor)
Called to select/deselect a VirtualPoint3D.
Parameters
selected
Definition at line 256 of file VirtualPoint3D.cpp.
References isSelectedNeighbor_.
 {
         isSelectedNeighbor_ = selectedNeighbor;
 }
void VirtualPoint3D::setVisibility (int camIndex, const VisibilityStatus * vis)
Sets the visibility status of the virtual point relatve to a specific camera.
Parameters
camIndex index of the camera rwlative to which we inquire about visibility
vis visibility status relative to this camera
Definition at line 291 of file VirtualPoint3D.cpp.
References uriVL::VisibilityStatus::code, uriVL::VisibilityStatus::confidence, and visibility_.
 {
         visibility_[camIndex]->code = vis->code;
         visibility_[camIndex]->confidence = vis->confidence;
 }
Friends And Related Function Documentation
friend class VirtualObject3D friend
Definition at line 268 of file VirtualPoint3D.h.
friend class VirtualPart3D friend
Definition at line 267 of file VirtualPoint3D.h.
Member Data Documentation
GLfloat* uriVL::VirtualPoint3D::color_ private
the point's RGB color
Definition at line 227 of file VirtualPoint3D.h.
Referenced by render_(), and setColor().
VirtualPoint3D * VirtualPoint3D::currentSelected_ = NULL static private
Definition at line 223 of file VirtualPoint3D.h.
Referenced by setSelected().
const GLfloat VirtualPoint3D::defaultColor_ = {0.f, 1.f, 0.f, 1.f} static private
Definition at line 245 of file VirtualPoint3D.h.
Referenced by render_().
const GLfloat VirtualPoint3D::defaultRenderScale_ = 0.005f static private
Default scale to use to render the Point3D as a small cube.
Definition at line 243 of file VirtualPoint3D.h.
Referenced by render_().
bool uriVL::VirtualPoint3D::hasIndividualRenderScale_ private
Does this virtual point have its own rendering scale?
Definition at line 239 of file VirtualPoint3D.h.
Referenced by render_(), and setRenderScale().
bool uriVL::VirtualPoint3D::isSelected_ private
Definition at line 229 of file VirtualPoint3D.h.
Referenced by isSelected(), render_(), and setSelected().
bool uriVL::VirtualPoint3D::isSelectedNeighbor_ private
Definition at line 231 of file VirtualPoint3D.h.
Referenced by render_(), and setSelectedNeighbor().
std::vector<VirtualPoint3D*> uriVL::VirtualPoint3D::neighbors_ private
Definition at line 221 of file VirtualPoint3D.h.
Referenced by addNeighbor(), and setSelected().
std::vector<int> uriVL::VirtualPoint3D::normalIndex_ private
Definition at line 219 of file VirtualPoint3D.h.
Referenced by addFaceInfo(), and uriVL::VirtualPart3D::render().
VirtualPart3D* uriVL::VirtualPoint3D::part_ private
Reference to the VirtualPart3D (of a VirtualObject3D) that the point belongs to.
Definition at line 212 of file VirtualPoint3D.h.
Referenced by uriVL::VirtualPart3D::addVertex().
Point3D* uriVL::VirtualPoint3D::point_ private
The Point3D this object is based on.
Definition at line 207 of file VirtualPoint3D.h.
Referenced by distanceTo(), getX(), getXYZ(), getY(), getZ(), render_(), setPosition(), and ~VirtualPoint3D().
VirtualRenderMode VirtualPoint3D::renderMode_ = INTERPOSE static private
Definition at line 247 of file VirtualPoint3D.h.
Referenced by render_(), and setRenderMode().
GLfloat uriVL::VirtualPoint3D::renderScale_ private
Rendering scale for this virtual point.
Definition at line 235 of file VirtualPoint3D.h.
Referenced by render_(), and setRenderScale().
std::vector<int> uriVL::VirtualPoint3D::uvIndex_ private
Definition at line 220 of file VirtualPoint3D.h.
Referenced by addFaceInfo().
VisibilityStatus** uriVL::VirtualPoint3D::visibility_ private
Stores visibility status relatrive to each known camera.
Definition at line 217 of file VirtualPoint3D.h.
Referenced by getVisibility(), setNbCameras_(), and setVisibility().
The documentation for this class was generated from the following files:
VirtualPoint3D.h
VirtualPoint3D.cpp