URIVisionLibrary: uriVL::RectifiedStereoMatcher_JJL Class Reference
uriVL::RectifiedStereoMatcher_JJL Class Reference
#include <RectifiedStereoMatcher_JJL.h>
Public Member Functions
RectifiedStereoMatcher_JJL (ImageRect *rect, int minWinWidth, int maxWinWidth, int minWinHeight, int maxWinHeight, int maxDisp)
Constructor.
virtual ~RectifiedStereoMatcher_JJL (void)
Destructor.
float match (RectifiedStereoPair *pair, StereoImageID l_or_r, ImagePoint *pt)
void match (RectifiedStereoPair *pair, StereoImageID l_or_r, ImageRect *rect, RasterImage_gray_F *disparityMap)
float match (StereoImageID l_or_r, ImagePoint *pt)
void match (StereoImageID l_or_r, ImageRect *rect, RasterImage_gray_F *disparityMap)
void setStereoPair (RectifiedStereoPair *pair)
void setStereoPair (RectifiedStereoPair *pair, ImageRect *rect)
Assigns the stereo pair and processing rectangle for this matcher object.
RasterImage_gray_F * getIntegralImage (int d)
Public Member Functions inherited from uriVL::RectifiedStereoMatcher
RectifiedStereoMatcher (RectifiedStereoPair *pair)
Creates a new rectified stereo matcher and set the rectified stereo pair on which to operate.
virtual ~RectifiedStereoMatcher (void)
Destructor.
virtual void setStereoPair (StereoPair *pair)
Assigns the stereo pair and processing rectangle for this matcher object.
void setMaxDisparity (int maxDisparity)
assigns a maximum value to the disparity to restrict the search rectangle
Public Member Functions inherited from uriVL::StereoMatcher
StereoMatcher (const StereoPair *stereoPair)
Creates a new stereo matcher and set the stereo pair on which to operate.
~StereoMatcher (void)
Destructor.
virtual void setStereoPair (const StereoPair *stereoPair)
Assigns the stereo pair and processing rectangle for this matcher object.
StereoMatchRecord * match (const StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated.
StereoMatchRecord * match (ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
void match (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated.
void match (ImagePoint *pt, StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)
Computes the stereo match for the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
StereoDisparity * disparity (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated.
StereoDisparity * disparity (ImagePoint *pt, StereoImageID l_or_r, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
void disparity (StereoPair *stereoPair, ImagePoint *pt, StereoImageID l_or_r, StereoDisparity *disp, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated.
void disparity (ImagePoint *pt, StereoImageID l_or_r, StereoDisparity *disp, const ImageRect *searchRect=NULL)
Computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
bool isSubpixelMatcher (void)
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
Protected Member Functions
void computeIntegralImage_ (int disp)
void calculateError_ (unsigned char **leftGray, unsigned char **rightGray, int d, int iLow, int iHigh, int jLow, int jHigh)
Protected Member Functions inherited from uriVL::RectifiedStereoMatcher
RectifiedStereoMatcher (void)
Default Constructor.
Protected Member Functions inherited from uriVL::StereoMatcher
StereoMatcher (void)
Default Constructor.
StereoMatcher (const StereoPair &theObj)
Copy Constructor.
const StereoMatcher & operator= (const StereoMatcher &theObj)
Copy operator.
virtual void computeSearchRect_ (ImagePoint *pt, const ImageRect *imgRect, const StereoImageID l_or_r, ImageRect *rect=NULL)=0
Computes a search rectangle for the target point.
virtual void match_ (StereoPair *stereoPair, ImagePoint *pt, const StereoImageID l_or_r, StereoMatchRecord *matchRec, const ImageRect *searchRect=NULL)=0
Function implemented by subclasses that computes the stereo disparity at the point indicated for the stereo pair set by an earlier call to setStereoPair (hopefully).
Protected Attributes
ImageRect * rect_
RasterImage_gray * leftImage_
RasterImage_gray * rightImage_
int minWinWidth_
Minimum width of the window.
int maxWinWidth_
Maximum width of the window.
int minWinHeight_
Minimum height of the window.
int maxWinHeight_
Maximum height of the window.
int maxDisp_
Maximum number of disparity.
RasterImage_gray_F ** errorIntegralImage_
error intergral image
RasterImage_gray_F ** sqrErrorIntegralImage_
square error intergral image
float *** integralError_
float *** integralSqrError_
float * prevRowSum_
float * prevRowSqSum_
float * prevColSum_
float * prevColSqSum_
Protected Attributes inherited from uriVL::RectifiedStereoMatcher
int maxDisparity_
upper bound for the disparity
Protected Attributes inherited from uriVL::StereoMatcher
PatternMatcher2D * matcher_
a stereo match
StereoPair * stereoPair_
StereoPair for this matcher to operate on (if one was set)
ImageRect * searchRect_
Search rectangle stored during a call to match.
StereoMatchRecord * matchRecord_
StereoMatchRecord record used to call private match function.
bool isSubpixelMatcher_
Indicates whether this stereo matcher computes integer or float (subpixel) disparity values.
Detailed Description
Definition at line 26 of file RectifiedStereoMatcher_JJL.h.
Constructor & Destructor Documentation
RectifiedStereoMatcher_JJL::RectifiedStereoMatcher_JJL (ImageRect * rect, int minWinWidth, int maxWinWidth, int minWinHeight, int maxWinHeight, int maxDisp)
Constructor.
Creates an image stereo matcher.
Parameters
rect image rectangle for the matching
minWinWidth Minimum width of the window
maxWinWidth Maximum width of the window
minWinHeight Minimum height of the window
maxWinHeight Maximum height of the window
maxDisp Maximum number of disparity
Definition at line 22 of file RectifiedStereoMatcher_JJL.cpp.
References errorIntegralImage_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getLeft(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), uriVL::ImageRect::getTop(), uriVL::ImageRect::getWidth(), integralError_, integralSqrError_, maxDisp_, maxWinHeight_, maxWinWidth_, minWinHeight_, minWinWidth_, prevColSqSum_, prevColSum_, prevRowSqSum_, prevRowSum_, rect_, and sqrErrorIntegralImage_.
     :   RectifiedStereoMatcher()
 {
     //  Clone operation rectangle
         rect_ = new ImageRect(rect);
         //  copy min and max matching window dimensions
         minWinWidth_ = minWinWidth,
         maxWinWidth_ = maxWinWidth,
     minWinHeight_ = minWinHeight,
     maxWinHeight_ = maxWinHeight,
     maxDisp_ = maxDisp;
     //  allocate integral images
     errorIntegralImage_ = new RasterImage_gray_F*[maxDisp+1];
     sqrErrorIntegralImage_ = new RasterImage_gray_F*[maxDisp+1];
     for (int i=0; i<=maxDisp; i++)
     {
         errorIntegralImage_[i] = new RasterImage_gray_F(rect_);
         sqrErrorIntegralImage_[i] = new RasterImage_gray_F(rect_);
     }
     //  then store the 2D rasters of these integral images
     //  (so that we won't have to reallocate/initialize them
     //  in the match functions
     integralError_ = new float** [maxDisp+1];
     integralSqrError_ = new float** [maxDisp+1];
     for (int i=0; i<=maxDisp; i++)
     {
         integralError_[i] = errorIntegralImage_[i]->getShiftedGrayF2D();
         integralSqrError_[i] = sqrErrorIntegralImage_[i]->getShiftedGrayF2D();
     }
     prevColSum_ = new float[rect_->getHeight()];
     prevColSum_ -= rect_->getTop();
     prevColSqSum_ = new float[rect_->getHeight()];
     prevColSqSum_ -= rect_->getBottom();
     prevRowSum_ = new float[rect_->getWidth()];
     prevRowSum_ -= rect_->getLeft();
     prevRowSqSum_ = new float[rect_->getWidth()];
     prevRowSqSum_ -= rect_->getLeft();
 }
RectifiedStereoMatcher_JJL::~RectifiedStereoMatcher_JJL (void) virtual
Destructor.
Definition at line 68 of file RectifiedStereoMatcher_JJL.cpp.
References uriVL::ImageRect::getLeft(), uriVL::ImageRect::getTop(), integralError_, integralSqrError_, maxDisp_, prevColSqSum_, prevColSum_, prevRowSqSum_, prevRowSum_, and rect_.
 {
         if (rect_ != NULL)
                 delete rect_;
         if (integralError_ != NULL)
         {
             for (int i = 0; i<=maxDisp_; i++)
                 delete integralError_[i];
                 delete []integralError_;
         }
         if (integralSqrError_ != NULL)
         {
             for (int i = 0; i<=maxDisp_; i++)
                 delete integralSqrError_[i];
                 delete []integralSqrError_;
         }
     if (integralError_ != NULL)
         delete []integralError_;
     if (integralSqrError_ != NULL)
         delete []integralSqrError_;
     if (prevRowSum_ != NULL)
     {
         prevRowSum_ += rect_->getLeft();
         delete []prevRowSum_;
     }
     if (prevRowSqSum_ != NULL)
     {
         prevRowSqSum_ += rect_->getLeft();
         delete []prevRowSqSum_;
     }
     if (prevColSum_ != NULL)
     {
         prevColSum_ += rect_->getTop();
         delete []prevColSum_;
     }
     if (prevColSqSum_ != NULL)
     {
         prevColSqSum_ += rect_->getTop();
         delete []prevColSqSum_;
     }
 }
Member Function Documentation
void RectifiedStereoMatcher_JJL::calculateError_ (unsigned char ** leftGray, unsigned char ** rightGray, int d, int iLow, int iHigh, int jLow, int jHigh) protected
Definition at line 289 of file RectifiedStereoMatcher_JJL.cpp.
References integralError_, integralSqrError_, and MIN.
Referenced by computeIntegralImage_().
 {
     int i,j;
         float a,b,c,errorL,errorR,minError;
         for (i=iLow; i<=iHigh; i++)
         {
                 for (j=jLow; j<=jHigh; j++)
                 {
                         a = abs(leftGray[i][j] - rightGray[i][j]);
                         if (j != jLow)
                         b = abs(leftGray[i][j] - (rightGray[i][j-d] + rightGray[i][j-d-1])*0.5);
                         else
                         b = a;
                         if (j != jHigh)
                             c = abs(leftGray[i][j] - (rightGray[i][j-d] + rightGray[i][j-d+1])*0.5);
                         else
                             c = a;
                         errorL = MIN(a,c);
                         if (b <errorL)
                             errorL = b;
                         if (j != jLow)
                             b = abs((leftGray[i][j] + leftGray[i][j-1])*0.5 - rightGray[i][j-d]);
                         else
                             b = a;
                         if ( j != jHigh)
                             c = abs((leftGray[i][j] + leftGray[i][j+1])*0.5 - rightGray[i][j-d]);
                         else
                             c = a;
                         errorR = MIN(a,c);
                         if (b <errorR)
                             errorR = b;
                         minError = MIN(errorL,errorR);
                         integralError_[d][i][j] = minError;
                         integralSqrError_[d][i][j] = minError*minError;
                 }
         }
 }
void RectifiedStereoMatcher_JJL::computeIntegralImage_ (int disp) protected
Definition at line 224 of file RectifiedStereoMatcher_JJL.cpp.
References calculateError_(), errorIntegralImage_, uriVL::ImageRect::getBottom(), uriVL::ImageRect::getLeft(), uriVL::ImageRect::getRight(), uriVL::RasterImage_gray::getShiftedGray2D(), uriVL::ImageRect::getTop(), integralError_, integralSqrError_, uriVL::kPositiveFloat, leftImage_, maxDisp_, prevColSqSum_, prevColSum_, prevRowSqSum_, prevRowSum_, rect_, rightImage_, uriVL::RasterImage_gray_F::setFloatConversionMode(), uriVL::DrawableObject2D::setValidRect(), and sqrErrorIntegralImage_.
Referenced by setStereoPair().
 {
     int   iLow = rect_->getTop(),
             iHigh = rect_->getBottom(),
             jLow = rect_->getLeft() + disp,
             jHigh = rect_->getRight(),
             newWidth = jHigh - jLow + 1,
             height = iHigh - iLow + 1,
             i, j;
     unsigned char   **leftGray = leftImage_->getShiftedGray2D();
     unsigned char   **rightGray = rightImage_->getShiftedGray2D();
     //  For each disparity considered
     for (int d=0; d<=maxDisp_; d++)
     {
         //  calculate the error at each pixel
         calculateError_(leftGray, rightGray, d, iLow, iHigh, jLow, jHigh);
         //  perform the summation along the columns
         for (i=iLow;i<=iHigh; i++)
         {
             prevColSum_[i]= 0;
             prevColSqSum_[i] = 0;
         }
         for (j=jLow;j<=jHigh; j++)
         {
             for (i=iLow;i<=iHigh; i++)
             {
                 integralError_[disp][i][j] += prevColSum_[j];
                 integralSqrError_[disp][i][j] += prevColSqSum_[j];
                 prevColSum_[j] = integralError_[disp][i][j];
                 prevColSqSum_[j] = integralSqrError_[disp][i][j];
             }
         }
         //  perform the summation along the rows
         for (j=jLow;j<=jHigh; j++)
         {
             prevRowSum_[j]= 0;
             prevRowSqSum_[j] = 0;
         }
         for (i=iLow;i<=iHigh; i++)
         {
             for (j=jLow;j<=jHigh; j++)
             {
                 integralError_[disp][i][j] += prevRowSum_[j];
                 integralSqrError_[disp][i][j] += prevRowSqSum_[j];
                 prevRowSum_[j] = integralError_[disp][i][j];
                 prevRowSqSum_[j] = integralSqrError_[disp][i][j];
             }
         }
         //  set valid data rectangles
             errorIntegralImage_[d]->setValidRect(jLow, iLow, newWidth, height);
             sqrErrorIntegralImage_[d]->setValidRect(jLow, iLow, newWidth, height);
             errorIntegralImage_[d]->setFloatConversionMode(kPositiveFloat);
             sqrErrorIntegralImage_[d]->setFloatConversionMode(kPositiveFloat);
     }
 }
RasterImage_gray_F * RectifiedStereoMatcher_JJL::getIntegralImage (int d)
Definition at line 284 of file RectifiedStereoMatcher_JJL.cpp.
References errorIntegralImage_.
 {
     return errorIntegralImage_[d];
 }
float RectifiedStereoMatcher_JJL::match (RectifiedStereoPair * pair, StereoImageID l_or_r, ImagePoint * pt)
Definition at line 117 of file RectifiedStereoMatcher_JJL.cpp.
References FAIL_CONDITION, uriVL::StereoPair::getValidRect(), uriVL::kFunctionNotImplemented, uriVL::kNullRectangleError, and setStereoPair().
Referenced by match().
 {
         FAIL_CONDITION( imgPair == NULL,
                                 kNullStereoPairError,
                                 "NULL stereo pair passed as parameter");
         ImageRect       *destRect = imgPair->getValidRect(l_or_r);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RectifiedStereoMatcher_JJL::setStereoPair");
         setStereoPair(imgPair, destRect);
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "not implemented yet");
         match(l_or_r, pt);
 }
void RectifiedStereoMatcher_JJL::match (RectifiedStereoPair * pair, StereoImageID l_or_r, ImageRect * rect, RasterImage_gray_F * disparityMap)
Definition at line 136 of file RectifiedStereoMatcher_JJL.cpp.
References FAIL_CONDITION, match(), and setStereoPair().
 {
         FAIL_CONDITION( imgPair == NULL,
                                 kNullStereoPairError,
                                 "NULL stereo pair passed as parameter");
         setStereoPair(imgPair, rect);
         //      calculate disparity
         match(l_or_r, rect, disparityMap);
 }
float RectifiedStereoMatcher_JJL::match (StereoImageID l_or_r, ImagePoint * pt)
Definition at line 149 of file RectifiedStereoMatcher_JJL.cpp.
References FAIL_CONDITION, uriVL::DrawableObject2D::getValidRect(), uriVL::kNullRectangleError, leftImage_, and rightImage_.
 {
         FAIL_CONDITION( pt == NULL,
                                 kNullStereoPairError,
                                 "NULL point passed as parameter");
         ImageRect       *destRect;
         if (l_or_r == 0)
                 destRect = leftImage_->getValidRect();
         else
                 destRect = rightImage_->getValidRect();
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RectifiedStereoMatcher_JJL::setStereoPair");
         //      calculate disparity at this point
 }
void RectifiedStereoMatcher_JJL::match (StereoImageID l_or_r, ImageRect * rect, RasterImage_gray_F * disparityMap)
Definition at line 168 of file RectifiedStereoMatcher_JJL.cpp.
References FAIL_CONDITION.
 {
         FAIL_CONDITION( disparityMap == NULL,
                                 kNullStereoPairError,
                                 "NULL disparity map passed as destination");
         //      calculate disparity map
 }
void RectifiedStereoMatcher_JJL::setStereoPair (RectifiedStereoPair * pair)
Definition at line 182 of file RectifiedStereoMatcher_JJL.cpp.
References FAIL_CONDITION, uriVL::StereoPair::getValidRect(), uriVL::kNullRectangleError, and uriVL::LEFT_IMAGE.
Referenced by match().
 {
         FAIL_CONDITION( imgPair == NULL,
                                 kNullStereoPairError,
                                 "NULL stereo pair passed as parameter");
         ImageRect       *destRect = imgPair->getValidRect(LEFT_IMAGE);
     FAIL_CONDITION( destRect == NULL,
                     kNullRectangleError,
                     "NULL ImageRect parameter in RectifiedStereoMatcher_JJL::setStereoPair");
         setStereoPair(imgPair, destRect);
 }
void RectifiedStereoMatcher_JJL::setStereoPair (RectifiedStereoPair * pair, ImageRect * rect)
Assigns the stereo pair and processing rectangle for this matcher object.
Parameters
pair reference to the image pair to process
rect image rectangle for the match
Definition at line 195 of file RectifiedStereoMatcher_JJL.cpp.
References computeIntegralImage_(), uriVL::ImageRect::contains(), errorIntegralImage_, uriVL::StereoPair::getLeftImage(), uriVL::StereoPair::getRightImage(), uriVL::RasterImage_gray_F::getShiftedGrayF2D(), integralError_, integralSqrError_, leftImage_, maxDisp_, rect_, rightImage_, uriVL::DrawableObject2D::setBoundRect(), uriVL::DrawableObject2D::setValidRect(), and sqrErrorIntegralImage_.
 {
     int d;
         if (!rect_->contains(rect))
         {
         for (d=0; d<=maxDisp_; d++)
             {
                     errorIntegralImage_[d]->setBoundRect(rect);
                     sqrErrorIntegralImage_[d]->setBoundRect(rect);
                 integralError_[d] = errorIntegralImage_[d]->getShiftedGrayF2D();
                 integralSqrError_[d] = sqrErrorIntegralImage_[d]->getShiftedGrayF2D();
         }
         }
         leftImage_ = (RasterImage_gray* ) (imgPair->getLeftImage());
         rightImage_ = (RasterImage_gray* ) (imgPair->getRightImage());
         //      calculate integral image
         for (d=0; d<=maxDisp_; d++)
             computeIntegralImage_(d);
         //  update valid data rectangles
         for (d=0; d<=maxDisp_; d++)
             errorIntegralImage_[d]->setValidRect(rect);
             sqrErrorIntegralImage_[d]->setValidRect(rect);
 }
Member Data Documentation
RasterImage_gray_F** uriVL::RectifiedStereoMatcher_JJL::errorIntegralImage_ protected
error intergral image
Definition at line 86 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), getIntegralImage(), RectifiedStereoMatcher_JJL(), and setStereoPair().
float*** uriVL::RectifiedStereoMatcher_JJL::integralError_ protected
Definition at line 92 of file RectifiedStereoMatcher_JJL.h.
Referenced by calculateError_(), computeIntegralImage_(), RectifiedStereoMatcher_JJL(), setStereoPair(), and ~RectifiedStereoMatcher_JJL().
float*** uriVL::RectifiedStereoMatcher_JJL::integralSqrError_ protected
Definition at line 94 of file RectifiedStereoMatcher_JJL.h.
Referenced by calculateError_(), computeIntegralImage_(), RectifiedStereoMatcher_JJL(), setStereoPair(), and ~RectifiedStereoMatcher_JJL().
RasterImage_gray* uriVL::RectifiedStereoMatcher_JJL::leftImage_ protected
Definition at line 65 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), match(), and setStereoPair().
int uriVL::RectifiedStereoMatcher_JJL::maxDisp_ protected
Maximum number of disparity.
Definition at line 83 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), setStereoPair(), and ~RectifiedStereoMatcher_JJL().
int uriVL::RectifiedStereoMatcher_JJL::maxWinHeight_ protected
Maximum height of the window.
Definition at line 80 of file RectifiedStereoMatcher_JJL.h.
Referenced by RectifiedStereoMatcher_JJL().
int uriVL::RectifiedStereoMatcher_JJL::maxWinWidth_ protected
Maximum width of the window.
Definition at line 74 of file RectifiedStereoMatcher_JJL.h.
Referenced by RectifiedStereoMatcher_JJL().
int uriVL::RectifiedStereoMatcher_JJL::minWinHeight_ protected
Minimum height of the window.
Definition at line 77 of file RectifiedStereoMatcher_JJL.h.
Referenced by RectifiedStereoMatcher_JJL().
int uriVL::RectifiedStereoMatcher_JJL::minWinWidth_ protected
Minimum width of the window.
Definition at line 71 of file RectifiedStereoMatcher_JJL.h.
Referenced by RectifiedStereoMatcher_JJL().
float* uriVL::RectifiedStereoMatcher_JJL::prevColSqSum_ protected
Definition at line 102 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), and ~RectifiedStereoMatcher_JJL().
float* uriVL::RectifiedStereoMatcher_JJL::prevColSum_ protected
Definition at line 100 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), and ~RectifiedStereoMatcher_JJL().
float* uriVL::RectifiedStereoMatcher_JJL::prevRowSqSum_ protected
Definition at line 98 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), and ~RectifiedStereoMatcher_JJL().
float* uriVL::RectifiedStereoMatcher_JJL::prevRowSum_ protected
Definition at line 96 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), and ~RectifiedStereoMatcher_JJL().
ImageRect* uriVL::RectifiedStereoMatcher_JJL::rect_ protected
Definition at line 63 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), setStereoPair(), and ~RectifiedStereoMatcher_JJL().
RasterImage_gray* uriVL::RectifiedStereoMatcher_JJL::rightImage_ protected
Definition at line 67 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), match(), and setStereoPair().
RasterImage_gray_F** uriVL::RectifiedStereoMatcher_JJL::sqrErrorIntegralImage_ protected
square error intergral image
Definition at line 90 of file RectifiedStereoMatcher_JJL.h.
Referenced by computeIntegralImage_(), RectifiedStereoMatcher_JJL(), and setStereoPair().
The documentation for this class was generated from the following files:
RectifiedStereoMatcher_JJL.h
RectifiedStereoMatcher_JJL.cpp