URIVisionLibrary: uriVL::FunctionND Class Reference
uriVL::FunctionND Class Reference abstract
Pure virtual parent class for all n-dimensional functions.
#include <FunctionND.h>
Public Member Functions
FunctionND (int n)
Creates a new n-dimensional function defined over ]-infinity, +infinity[^n.
FunctionND (int n, const double *xMin, const double *xMax)
Creates a new n-dimensional function defined over the range specified.
virtual ~FunctionND (void)
Destructor.
virtual double func (const double *x) const =0
Evaluates the function at the nD point specified.
virtual double func (const std::vector< double > &x) const
Evaluates the function at the nD point specified.
virtual double func (const ColumnVector *x) const
Evaluates the function at the nD point specified.
virtual void gradient (const double *x, double *gradVect) const
Evaluates the gradient of the function at the point specified.
virtual void gradient (const ColumnVector *x, ColumnVector *gradVect) const
Evaluates the gradient of the function at the point specified.
const ColumnVector * gradient (const ColumnVector *x) const
Evaluates the gradient of the function at the point specified.
virtual void hessian (const double *x, double *const *hessianMat) const
Evaluates the Hessian matrix of the function at the point specified.
virtual void hessian (const ColumnVector *x, Matrix *hess) const
Evaluates the gradient of the function at the point specified.
const Matrix * hessian (const ColumnVector *x) const
Evaluates the gradient of the function at the point specified.
virtual bool gradientIsImplemented (void) const =0
Indicates whether the function implements its own gradient function.
virtual bool hessianIsImplemented (void) const =0
Indicates whether the function implements its own Hessian function.
bool isDefinedAt (const double *x) const
Indicates whther a point is within the domain of definition of this function.
bool isDefinedAt (const std::vector< double > &x) const
Indicates whther a point is within the domain of definition of this function.
bool isDefinedAt (const ColumnVector *x) const
Indicates whther a point is within the domain of definition of this function.
const double * getLowerBound (void) const
Returns the lower bounds of this function's domain of definition.
const double * getUpperBound (void) const
Returns the upper bounds of this function's domain of definition.
int getDimension (void) const
Returns the dimension of this function's domain.
Protected Attributes
int nDim_
Dimension of the source space of this function.
bool isBounded_
Is set true when bounds xMin_ and xMax_ were set for the domain of definition of the function.
double * xMin_
nDim-sized array of lower bounds of the domain of definition.
double * xMax_
nDim-sized array of upper bounds of the domain of definition.
double * xLocal_
Array that stores a copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function)
double * xLocal2_
Array that stores another copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function and derivative)
Private Member Functions
FunctionND (const FunctionND &obj)
Copy constructor.
const FunctionND & operator= (const FunctionND &obj)
Copy operator.
Detailed Description
Pure virtual parent class for all n-dimensional functions.
The function's actual implementation will be done in the child class and it will always be hard-coded.
Note that, contrary to a mathematical function, a Function is always defined on an interval that could be -∞ to +∞, but cannot have "holes" in it.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 40 of file FunctionND.h.
Constructor & Destructor Documentation
FunctionND::FunctionND (int n)
Creates a new n-dimensional function defined over ]-infinity, +infinity[^n.
Definition at line 29 of file FunctionND.cpp.
References HUGE_VALF, xMax_, and xMin_.
                         :       nDim_(n),
                                 isBounded_(false),
                                 xMin_(new double[n]),
                                 xMax_(new double[n]),
                                 xLocal_(new double[n]),
                                 xLocal2_(new double[n])
 {
     for (int i=0; i<n; i++)
     {
         xMin_[i] = -HUGE_VALF;
         xMax_[i] = HUGE_VALF;
     }
 }
 catch (...)
 {
         FAIL_CONDITION( n <= 0,
                                         kInvalidParameterError,
                                         "Invalid dimension passed to FunctionND constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter passed to FunctionND constructor");
 }
FunctionND::FunctionND (int n, const double * xMin, const double * xMax)
Creates a new n-dimensional function defined over the range specified.
Parameters
xMin lower bound of the domain of definition
xMax upper bound of the domain of definition
Definition at line 54 of file FunctionND.cpp.
References FAIL_CONDITION, uriVL::kInvalidParameterError, uriVL::kNullParameterError, xMax_, and xMin_.
                         :       nDim_(n),
                                 isBounded_(true),
                                 xMin_(new double[n]),
                                 xMax_(new double[n]),
                                 xLocal_(new double[n]),
                                 xLocal2_(new double[n])
 {
         try
         {
                 for (int i=0; i<n; i++)
                 {
                         xMin_[i] = xMin[i];
                         xMax_[i] = xMax[i];
                 }
         }
         catch(...)
         {
                 FAIL_CONDITION( (xMin == NULL) || (xMax == NULL),
                                                 kNullParameterError,
                                                 "Null bound vector passed to FunctionND constructor");
                 FAIL_CONDITION( true,
                                                 kInvalidParameterError,
                                                 "Invalid bound vector passed to FunctionND constructor");
         }
 }
 catch (...)
 {
         FAIL_CONDITION( n <= 0,
                                         kInvalidParameterError,
                                         "Invalid dimension passed to FunctionND constructor");
         FAIL_CONDITION( true,
                                         kInvalidParameterError,
                                         "Invalid parameter passed to FunctionND constructor");
 }
FunctionND::~FunctionND (void) virtual
Destructor.
Definition at line 106 of file FunctionND.cpp.
References xLocal2_, xLocal_, xMax_, and xMin_.
 {
     delete []xMin_;
     delete []xMax_;
         delete [] xLocal_;
         delete [] xLocal2_;
 }
FunctionND::FunctionND (const FunctionND & obj) private
Copy constructor.
Parameters
obj object to copy
Definition at line 91 of file FunctionND.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
                         :       nDim_(0),
                                 isBounded_(false),
                                 xMin_(NULL),
                                 xMax_(NULL),
                                 xLocal_(NULL),
                                 xLocal2_(NULL)
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "FunctionND copy constructor not implemented");
 }
Member Function Documentation
virtual double uriVL::FunctionND::func (const double * x) const pure virtual
Evaluates the function at the nD point specified.
This is the only version of func that must be implemented in the child class.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Implemented in NotSoSimpleFunctionND, and SimpleFunctionND.
Referenced by uriVL::FunctionNDSection1D::func(), func(), gradient(), and uriVL::NonlinearOptimizerND_conjDir::minimize_().
double FunctionND::func (const std::vector< double > & x) const virtual
Evaluates the function at the nD point specified.
If you are going to use this function a lot you should override it in your custom child class because this implementation is (by necessity) very inefficient: It copies all the data into an array before calling the array version of func.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Reimplemented in NotSoSimpleFunctionND.
Definition at line 130 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, uriVL::kNumericalError, nDim_, and xLocal_.
 {
         //-----------------------------------------------------
         //      First check that the function is defined at x
         //-----------------------------------------------------
         if (isBounded_)
         {
                 bool isDefined = false;
                 try
                 {
                         isDefined = isDefinedAt(x);
                 }
                 catch (ErrorReport& e)
                 {
                         e.appendToMessage("called by FunctionND::func");
                         throw e;
                 }
                 catch(...)
                 {
                         FAIL_CONDITION( true,
                                                         kNumericalError,
                                                         "Unexpected error in FunctionND::func");
                 }
                 FAIL_CONDITION( !isDefined,
                                                 kDataRangeError,
                                                 "x not within domain of definition in FunctionND::func");
         }
         //-----------------------------------------------------
         //      Make local copy of x
         //-----------------------------------------------------
         try
         {
                 for (int k=0; k<nDim_; k++)
                         xLocal_[k] = x[k];
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error while copying input data in in FunctionND::func");
         }
         //-----------------------------------------------------
         //      Finally evaluate the function at x
         //-----------------------------------------------------
         double val = 0;
         try
         {
                 val  = func(xLocal_);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::func");
         }
         return val;
 }
double FunctionND::func (const ColumnVector * x) const virtual
Evaluates the function at the nD point specified.
If you are going to use this function a lot, you should override it in your custom child class because this implementation is (by necessity) very inefficient: It copies all the data into an array before calling the array version of func.
Parameters
x where the function should be evaluated
Returns
the value of the function at x
Definition at line 208 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, func(), uriVL::Matrix::getMatrix(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, uriVL::kNumericalError, nDim_, and xLocal_.
 {
         //-----------------------------------------------------
         //      First check that the function is defined at x
         //-----------------------------------------------------
         if (isBounded_)
         {
                 bool isDefined = false;
                 try
                 {
                         isDefined = isDefinedAt(x);
                 }
                 catch (ErrorReport& e)
                 {
                         e.appendToMessage("called by FunctionND::func");
                         throw e;
                 }
                 catch(...)
                 {
                         FAIL_CONDITION( true,
                                                         kNumericalError,
                                                         "Unexpected error in FunctionND::func");
                 }
                 FAIL_CONDITION( !isDefined,
                                                 kDataRangeError,
                                                 "x not within domain of definition in FunctionND::func");
         }
         //-----------------------------------------------------
         //      make a copy of x into a 1D double array
         //-----------------------------------------------------
         try
         {
                 const double *const* xV = x->getMatrix();
                 for (int k=0; k<nDim_; k++)
                 {
                         xLocal_[k] = xV[k][0];
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error copying data in FunctionND::func");
         }
         //-----------------------------------------------------
         //      Finally evaluate the function at x
         //-----------------------------------------------------
         double val = 0;
         try
         {
                 val  = func(xLocal_);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND_F::func");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "FunctionND_F::func");
         }
         return val;
 }
int FunctionND::getDimension (void) const
Returns the dimension of this function's domain.
Definition at line 599 of file FunctionND.cpp.
References nDim_.
Referenced by checkIfSearchStartPointIsValid_(), uriVL::NonlinearOptimizerND::minimize(), uriVL::WarpMatchScoreFunctionND::newVarArray(), uriVL::NonlinearOptimizerND_conjDir::NonlinearOptimizerND_conjDir(), and uriVL::NonlinearOptimizerND_conjDir::setFunction_().
 {
     return nDim_;
 }
const double * FunctionND::getLowerBound (void) const
Returns the lower bounds of this function's domain of definition.
Definition at line 683 of file FunctionND.cpp.
References xMin_.
Referenced by uriVL::FunctionNDSection1D::getLowerBound(), and uriVL::FunctionNDSection1D::getUpperBound().
 {
     return xMin_;
 }
const double * FunctionND::getUpperBound (void) const
Returns the upper bounds of this function's domain of definition.
Definition at line 689 of file FunctionND.cpp.
References xMax_.
Referenced by uriVL::FunctionNDSection1D::getLowerBound(), and uriVL::FunctionNDSection1D::getUpperBound().
 {
     return xMax_;
 }
void FunctionND::gradient (const double * x, double * gradVect) const virtual
Evaluates the gradient of the function at the point specified.
If the subclass does not implement its own gradient function, then this function will be called instead, which implements the second-order central difference approximation for all directions.
Parameters
x where the function should be evaluated
gradVect the gradient of the function at x
Definition at line 297 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, func(), isBounded_, isDefinedAt(), uriVL::kDataRangeError, uriVL::kNumericalError, LARGE_RELATIVE_TOLERANCE, nDim_, xLocal2_, and xLocal_.
Referenced by gradient().
 {
         //-----------------------------------------------------
         //      First check that the function is defined at x
         //-----------------------------------------------------
         if (isBounded_)
         {
                 bool isDefined = false;
                 try
                 {
                         isDefined = isDefinedAt(x);
                 }
                 catch (ErrorReport& e)
                 {
                         e.appendToMessage("called by FunctionND::gradient");
                         throw e;
                 }
                 catch(...)
                 {
                         FAIL_CONDITION( true,
                                                         kNumericalError,
                                                         "Unexpected error in FunctionND::gradient");
                 }
                 FAIL_CONDITION( !isDefined,
                                                 kDataRangeError,
                                                 "x not within domain of definition in FunctionND::gradient");
         }
         //-----------------------------------------------------
         //      Make local copies of x
         //-----------------------------------------------------
         double* xPlus = xLocal_;
         double* xMinus = xLocal2_;
         try
         {
                 //      for each variable of x --> derivative
                 for (int k=0; k<nDim_; k++)
                 {
                         //      compute a small discrete displacement along kth direction
                         const double DX = fabs(x[k]) > LARGE_RELATIVE_TOLERANCE ?
                                                                 fabs(x[k])*LARGE_RELATIVE_TOLERANCE
                                                                 :
                                                                 LARGE_RELATIVE_TOLERANCE;
                         const double TWO_OVER_DX = 2.0 / DX;
                         //      initialize the "plus" and "minus" arrays
                         for (int i=0; i<nDim_; i++)
{
                                 if (i!= k)
{
                                         xPlus[k] = xMinus[k] = x[k];
                                 }
                                 else
{
                                         xPlus[k] = x[k] + DX;
                                         xMinus[k] = x[k] - DX;
                                 }
                         }
                         gradVect[k] = TWO_OVER_DX * (func(xPlus) - func(xMinus));
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::gradient");
         }
 }
void FunctionND::gradient (const ColumnVector * x, ColumnVector * gradVect) const virtual
Evaluates the gradient of the function at the point specified.
If you are going to use this function a lot, you should override it in your custom child class because this implementation is (by necessity) very inefficient: It copies all the data into an array before calling the array version of gradient.
Parameters
x where the function should be evaluated
gradVect the gradient of the function at x
Definition at line 380 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), gradient(), uriVL::kNullParameterError, uriVL::kNumericalError, nDim_, uriVL::R_W_ACCESS, xLocal2_, and xLocal_.
 {
     FAIL_CONDITION( x == NULL,
                     kNullParameterError,
                     "Null parameter passed to FunctionND::gradient");
     FAIL_CONDITION( grad == NULL,
                     kNullParameterError,
                     "Null parameter passed to FunctionND::gradient");
         //-----------------------------------------------------
         //      make a copy of x into a 1D array of double
         //-----------------------------------------------------
         double* xLocal = xLocal_;
         try
         {
                 const double *const* xV = x->getMatrix();
                 for (int k=0; k<nDim_; k++)
                 {
                         xLocal[k] = xV[k][0];
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error copying data in FunctionND::gradient");
         }
         //-----------------------------------------------------
         //      compute the gradient
         //-----------------------------------------------------
         double* gradLocal = xLocal2_;
         try
         {
                 gradient(xLocal, gradLocal);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::gradient");
         }
         //-----------------------------------------------------
         //      copy back gradient values
         //-----------------------------------------------------
         try
         {
                 double *const* gradVect = grad->getMatrix(R_W_ACCESS);
                 for (int k=0; k<nDim_; k++)
                 {
                         gradVect[k][0] = gradLocal[k];
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error copying back data in FunctionND::gradient");
         }
 }
const ColumnVector * FunctionND::gradient (const ColumnVector * x) const
Evaluates the gradient of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the gradient of the function at x
Definition at line 463 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, grad, gradient(), uriVL::kNumericalError, and nDim_.
 {
         ColumnVector* grad = NULL;
         try
         {
                 grad = new ColumnVector(nDim_);
                 gradient(x, grad);
         }
         catch (ErrorReport& e)
         {
                 delete grad;
                 grad = NULL;
                 e.appendToMessage("called by FunctionND::gradient");
                 throw e;
         }
         catch(...)
         {
                 delete grad;
                 grad = NULL;
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::gradient");
         }
         return grad;
 }
virtual bool uriVL::FunctionND::gradientIsImplemented (void) const pure virtual
Indicates whether the function implements its own gradient function.
Returns
true if the function implements its own gradient function
Implemented in NotSoSimpleFunctionND, and SimpleFunctionND.
void FunctionND::hessian (const double * x, double *const * hessianMat) const virtual
Evaluates the Hessian matrix of the function at the point specified.
If the subclass does not implement its own hessian function, then this function will be called instead, which implements the second-order difference approximation for all directions.
Parameters
x where the function should be evaluated
hessianMat the Hessian matrix of the function at x
Definition at line 502 of file FunctionND.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
Referenced by hessian().
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "not implemented yet");
 }
void FunctionND::hessian (const ColumnVector * x, Matrix * hess) const virtual
Evaluates the gradient of the function at the point specified.
If you are going to use this function a lot, you should override it in your custom child class because this implementation is (by necessity) very inefficient: It copies all the data into an array before calling the array version of hessian.
Parameters
x where the function should be evaluated
hess the Hessian matrix of the function at x
Definition at line 510 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), hessian(), uriVL::kNullParameterError, uriVL::kNumericalError, nDim_, uriVL::R_W_ACCESS, and xLocal_.
 {
     FAIL_CONDITION( x == NULL,
                     kNullParameterError,
                     "Null parameter passed to FunctionND::hessian");
     FAIL_CONDITION( hess == NULL,
                     kNullParameterError,
                     "Null parameter passed to FunctionND::hessian");
         //      make a copy of x into a 1D double array
         try
         {
                 const double *const* xV = x->getMatrix();
                 for (int k=0; k<nDim_; k++)
                         xLocal_[k] = xV[k][0];
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::hessian");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error while copying data in FunctionND::hessian");
         }
         //      compute the hessian
         try
         {
                 double *const* hessMat = hess->getMatrix(R_W_ACCESS);
                 hessian(xLocal_, hessMat);
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::hessian");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::hessian");
         }
 }
const Matrix * FunctionND::hessian (const ColumnVector * x) const
Evaluates the gradient of the function at the point specified.
Parameters
x where the function should be evaluated
Returns
the Hessian matrix of the function at x
Definition at line 560 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, hessian(), uriVL::kNumericalError, and nDim_.
 {
         Matrix* hess = NULL;
         try
         {
                 hess = new Matrix(nDim_, nDim_);
                 hessian(x, hess);
         }
         catch (ErrorReport& e)
         {
                 delete hess;
                 hess = NULL;
                 e.appendToMessage("called by FunctionND::hessian");
                 throw e;
         }
         catch(...)
         {
                 delete hess;
                 hess = NULL;
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in FunctionND::hessian");
         }
         return hess;
 }
virtual bool uriVL::FunctionND::hessianIsImplemented (void) const pure virtual
Indicates whether the function implements its own Hessian function.
Returns
true if the function implements its own Hessian function
Implemented in NotSoSimpleFunctionND, and SimpleFunctionND.
bool FunctionND::isDefinedAt (const double * x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
Definition at line 605 of file FunctionND.cpp.
References FAIL_CONDITION, uriVL::kNullParameterError, uriVL::kNumericalError, nDim_, xMax_, and xMin_.
Referenced by checkIfSearchStartPointIsValid_(), SimpleFunctionND::func(), func(), gradient(), and uriVL::FunctionNDSection1D::isDefinedAt().
 {
         bool isDefined = true;
         try
         {
                 for (int i=0; (i<nDim_) && isDefined; i++)
                         if ((x[i] < xMin_[i]) || (x[i] > xMax_[i]))
                                 isDefined = false;
         }
         catch (...)
         {
                 FAIL_CONDITION( x == NULL,
                                                 kNullParameterError,
                                                 "Null pointer passed to FunctionND::isDefinedAt");
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error encountered in FunctionND::isDefinedAt");
         }
     return isDefined;
 }
bool uriVL::FunctionND::isDefinedAt (const std::vector< double > & x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
bool FunctionND::isDefinedAt (const ColumnVector * x) const
Indicates whther a point is within the domain of definition of this function.
Parameters
x the point to test
Returns
true if this function is defined at x
Definition at line 651 of file FunctionND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::kNullParameterError, uriVL::kNumericalError, nDim_, xMax_, and xMin_.
 {
         bool isDefined = true;
         try
         {
                 const double *const* xv = x->getMatrix();
                 for (int i=0; (i<nDim_) && isDefined; i++)
                         if ((xv[i][0] < xMin_[i]) || (xv[i][0] > xMax_[i]))
                                 isDefined = false;
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by FunctionND::isDefinedAt");
                 throw e;
         }
         catch (...)
         {
                 FAIL_CONDITION( x == NULL,
                                                 kNullParameterError,
                                                 "Null pointer passed to FunctionND::isDefinedAt");
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error encountered in FunctionND::isDefinedAt");
         }
     return isDefined;
 }
const FunctionND & FunctionND::operator= (const FunctionND & obj) private
Copy operator.
Parameters
obj object to copy
Definition at line 114 of file FunctionND.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
         FAIL_CONDITION( true,
                                         kFunctionNotImplemented,
                                         "FunctionND copy operator not implemented");
         return *this;
 }
Member Data Documentation
bool uriVL::FunctionND::isBounded_ protected
Is set true when bounds xMin_ and xMax_ were set for the domain of definition of the function.
Definition at line 198 of file FunctionND.h.
Referenced by func(), and gradient().
int uriVL::FunctionND::nDim_ protected
Dimension of the source space of this function.
Definition at line 193 of file FunctionND.h.
Referenced by func(), getDimension(), gradient(), hessian(), and isDefinedAt().
double* uriVL::FunctionND::xLocal2_ mutable protected
Array that stores another copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function and derivative)
Definition at line 222 of file FunctionND.h.
Referenced by gradient(), and ~FunctionND().
double* uriVL::FunctionND::xLocal_ mutable protected
Array that stores a copy of the point where the function is evaluated (for std::vector and ColumnVector versions of the function)
Definition at line 217 of file FunctionND.h.
Referenced by func(), gradient(), hessian(), and ~FunctionND().
double* uriVL::FunctionND::xMax_ protected
nDim-sized array of upper bounds of the domain of definition.
Admitedly, this is a somewhat naive/restrictive form of domain of definition, but let's not forget that our underlying space is based on rectangular images.
Definition at line 212 of file FunctionND.h.
Referenced by FunctionND(), getUpperBound(), isDefinedAt(), and ~FunctionND().
double* uriVL::FunctionND::xMin_ protected
nDim-sized array of lower bounds of the domain of definition.
Admitedly, this is a somewhat naive/restrictive form of domain of definition, but let's not forget that our underlying space is based on rectangular images.
Definition at line 205 of file FunctionND.h.
Referenced by FunctionND(), getLowerBound(), isDefinedAt(), and ~FunctionND().
The documentation for this class was generated from the following files:
FunctionND.h
FunctionND.cpp