URIVisionLibrary: uriVL::RigidTransformation3D Class Reference
uriVL::RigidTransformation3D Class Reference
A RigidTransformation is a transformation between reference frames that preserves angles and lengths.
#include <RigidTransformation3D.h>
Public Member Functions
RigidTransformation3D (void)
Constructor.
RigidTransformation3D (const double *glMat)
Constructor.
RigidTransformation3D (const double theMat[][4])
Constructor.
RigidTransformation3D (const HomogeneousMatrix *theMat)
Constructor.
RigidTransformation3D (const RigidTransformation3D *theTransf)
Clone constructor.
RigidTransformation3D (const ReferenceFrame3D *startFrame, const ReferenceFrame3D *endFrame)
Constructor.
RigidTransformation3D (RotationRef rotDataType, const double *rotData, const double *transData)
Creates a new RigidTransformation3D object specified by a GL-style matrix, a quaternion and a translation vector, a triplet of R-P-Y angles and a translation vector, or a triplet of Euler angles and a translation vector.
RigidTransformation3D (const Rotation3D *theRot, const Translation3D *theTrans)
Constructor.
RigidTransformation3D (const Rotation3D *theRot)
Constructor.
RigidTransformation3D (const Translation3D *theTrans)
Constructor.
virtual ~RigidTransformation3D (void)
Destructor.
const Rotation3D * getRotationComponent (void)
Returns a read-only version of the rotation component of the rigid transformation.
Rotation3D * getRotationComponent (ReadWriteStatus rwa)
Returns a writable version of the rotation component of the rigid transformation.
const Translation3D * getTranslationComponent (void)
Returns a read-only version of the translation component of the rigid transformation.
Translation3D * getTranslationComponent (ReadWriteStatus rwa)
Returns a writable version of the translation component of the rigid transformation.
void postComposeTransformation (const RigidTransformation3D *theTransf)
composes a new rigid transformation with this rigid transformation.
void postComposeTransformation (const Rotation3D *theRot)
composes a new rigid transformation with this rigid transformation.
void postComposeTransformation (const Translation3D *theTrans)
composes a new rigid transformation with this rigid transformation.
Public Member Functions inherited from uriVL::Transformation3D
Transformation3D (void)
Constructor.
Transformation3D (const double *glMat)
Constructor.
Transformation3D (const double theMat[][4])
Constructor.
Transformation3D (const HomogeneousMatrix *theMat)
Constructor.
Transformation3D (const Transformation3D *theTransf)
Clone constructor.
virtual ~Transformation3D (void)
Destructor.
const HomogeneousMatrix * getMatrix (void) const
Returns a read-only reference frame to this transformation's matrix.
HomogeneousMatrix * getMatrix (ReadWriteStatus rwa)
Returns a writable reference frame to this transformation's matrix.
const GLfloat * getGLMatrix (void) const
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a read-only "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
Private Member Functions
RigidTransformation3D (const RigidTransformation3D &theField)
Copy Constructor.
const RigidTransformation3D & operator= (const RigidTransformation3D &theField)
Copy operator.
void updateMatrix_ (void) const
Updates the transformation matrix if it was not the reference.
void orthogonalizeMatrix_ (void)
Ensures that the transformation matrix is still that of a rotation.
Private Attributes
Rotation3D * rot_
Rotation component of the 3D transformation.
Translation3D * trans_
Translation component of the 3D transformation.
Additional Inherited Members
Protected Member Functions inherited from uriVL::Transformation3D
void setMatrixAsReference_ (bool state)
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
Protected Attributes inherited from uriVL::Transformation3D
HomogeneousMatrix * homMat_
Updates the transformation matrix if it was not the reference and it has been changed and then returns it as a writable "GL" matrix (a 1D array of 16 elements, read column by column, left to right).
bool matrixIsReference_
Indicates whether the transformation matrix (inherited from the parent class) stores the reference values for the transformation.
bool referenceHasChanged_
Indicates that whatever constitues the reference for this object (e.g.
Detailed Description
A RigidTransformation is a transformation between reference frames that preserves angles and lengths.
A RigidTransformation is composed of a rotation and a translation and can be represented either by an object of each type or by a 4x4 homogeneous transformation matrix.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Definition at line 39 of file RigidTransformation3D.h.
Constructor & Destructor Documentation
RigidTransformation3D::RigidTransformation3D (void)
Constructor.
Creates an identity transformation.
Definition at line 20 of file RigidTransformation3D.cpp.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
 }
RigidTransformation3D::RigidTransformation3D (const double * glMat)
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
glMat a flat, GL-style transformation matrix
Definition at line 28 of file RigidTransformation3D.cpp.
References rot_, and trans_.
             :   Transformation3D(glMat),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     rot_ = NULL;
     trans_ = NULL;
 }
 catch(ErrorReport& e)
 {
         e.appendToMessage("called by RigidTransformation3D constructor");
         throw e;
 }
RigidTransformation3D::RigidTransformation3D (const double theMat[][4])
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat 4 by 4 transformation matrix
Definition at line 43 of file RigidTransformation3D.cpp.
             :   Transformation3D(theMat),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
 }
 catch(ErrorReport& e)
 {
         e.appendToMessage("called by RigidTransformation3D constructor");
         throw e;
 }
RigidTransformation3D::RigidTransformation3D (const HomogeneousMatrix * theMat)
Constructor.
Creates a 3D transformation based on the transformation matrix received as parameter
Parameters
theMat homogeneous transformation matrix
Definition at line 58 of file RigidTransformation3D.cpp.
             :   Transformation3D(theMat),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
 }
 catch(ErrorReport& e)
 {
         e.appendToMessage("called by RigidTransformation3D constructor");
         throw e;
 }
RigidTransformation3D::RigidTransformation3D (const RigidTransformation3D * theTransf)
Clone constructor.
Creates a 3D transformation identical to the one received as parameter
Parameters
theTransf transformation to clone
Definition at line 72 of file RigidTransformation3D.cpp.
References FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Transformation3D::homMat_, uriVL::kNullParameterError, uriVL::Transformation3D::matrixIsReference_, uriVL::R_W_ACCESS, uriVL::Transformation3D::referenceHasChanged_, rot_, and trans_.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     FAIL_CONDITION( theTransf == NULL,
                     kNullParameterError,
                     "Null pointer passed to RigidTransformation3D copy constructor");
     matrixIsReference_ = theTransf->matrixIsReference_;
     referenceHasChanged_ = true;
     if (matrixIsReference_)
     {
         double* const*const mat = homMat_->getMatrix(R_W_ACCESS);
         const double*const* theMat = theTransf->homMat_->getMatrix();
         for (int i=0; i<4; i++)
             for (int j=0; j<4; j++)
                 mat[i][j] = theMat[i][j];
     }
     else
     {
         //  Copy the components
         if (theTransf->rot_ != NULL)
             rot_ = new Rotation3D(theTransf->rot_);
         else
             rot_ = new Rotation3D();;
         if (theTransf->trans_ != NULL)
             trans_ = new Translation3D(theTransf->trans_);
         else
             trans_ = new Translation3D();
     }
 }
RigidTransformation3D::RigidTransformation3D (const ReferenceFrame3D * startFrame, const ReferenceFrame3D * endFrame)
Constructor.
Creates the 3D rigid transformation betwen the two reference frames received as parameters. Throws an exception if such a transformation cannot be defined. reference frame.
Parameters
startFrame reference frame relative to which the transformation is defined
endFrame reference frame after the transformation
Definition at line 111 of file RigidTransformation3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "constructor not open for business yet");
 }
RigidTransformation3D::RigidTransformation3D (RotationRef rotDataType, const double * rotData, const double * transData)
Creates a new RigidTransformation3D object specified by a GL-style matrix, a quaternion and a translation vector, a triplet of R-P-Y angles and a translation vector, or a triplet of Euler angles and a translation vector.
Parameters
rotDataType indicates what kind of data is stored in the first double array
rotData 1D array of double storing a representation for the rotation
transData 1D array of double storing a representation for the translation.
Definition at line 183 of file RigidTransformation3D.cpp.
     :   rot_(new Rotation3D(rotDataType, rotData)),
         trans_(new Translation3D(transData))
 {
 }
RigidTransformation3D::RigidTransformation3D (const Rotation3D * theRot, const Translation3D * theTrans)
Constructor.
Creates a 3D transformation based on the rotation and translation received as parameters
Parameters
theRot the rotation transformation
theTrans the translation transformation
Definition at line 123 of file RigidTransformation3D.cpp.
References uriVL::Transformation3D::matrixIsReference_, uriVL::Transformation3D::referenceHasChanged_, rot_, and trans_.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     matrixIsReference_ = false;
     referenceHasChanged_ = true;
     //  Copy the components
     if (theRot != NULL)
         rot_ = new Rotation3D(theRot);
     else
         rot_ = new Rotation3D();;
     if (theTrans != NULL)
         trans_ = new Translation3D(theTrans);
     else
         trans_ = new Translation3D();
 }
RigidTransformation3D::RigidTransformation3D (const Rotation3D * theRot)
Constructor.
Creates a 3D transformation based on the rotation and translation received as parameters
Parameters
theRot the rotation transformation
Definition at line 145 of file RigidTransformation3D.cpp.
References uriVL::Transformation3D::matrixIsReference_, uriVL::Transformation3D::referenceHasChanged_, rot_, and trans_.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     matrixIsReference_ = false;
     referenceHasChanged_ = true;
     //  Copy the components
     if (theRot != NULL)
         rot_ = new Rotation3D(theRot);
     else
         rot_ = new Rotation3D();;
     trans_ = new Translation3D();
 }
RigidTransformation3D::RigidTransformation3D (const Translation3D * theTrans)
Constructor.
Creates a 3D transformation based on the rotation and translation received as parameters
Parameters
theTrans the translation transformation
Definition at line 164 of file RigidTransformation3D.cpp.
References uriVL::Transformation3D::matrixIsReference_, uriVL::Transformation3D::referenceHasChanged_, rot_, and trans_.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     matrixIsReference_ = false;
     referenceHasChanged_ = true;
     //  Copy the components
     rot_ = new Rotation3D();;
     if (theTrans != NULL)
         trans_ = new Translation3D(theTrans);
     else
         trans_ = new Translation3D();
 }
RigidTransformation3D::~RigidTransformation3D (void) virtual
Destructor.
Definition at line 203 of file RigidTransformation3D.cpp.
References rot_, and trans_.
 {
     if (rot_ != NULL)
         delete rot_;
     if (trans_ != NULL)
         delete trans_;
 }
RigidTransformation3D::RigidTransformation3D (const RigidTransformation3D & theField) private
Copy Constructor.
Disabled
Parameters
theField reference to the object to copy
Definition at line 192 of file RigidTransformation3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
             :   Transformation3D( ),
                 //
                 rot_(NULL),
                 trans_(NULL)
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Copy constructor not implemented.");
 }
Member Function Documentation
const Rotation3D * RigidTransformation3D::getRotationComponent (void)
Returns a read-only version of the rotation component of the rigid transformation.
Returns
the rotation component of the rigid transformation
Definition at line 227 of file RigidTransformation3D.cpp.
References rot_.
 {
     return rot_;
 }
Rotation3D * RigidTransformation3D::getRotationComponent (ReadWriteStatus rwa)
Returns a writable version of the rotation component of the rigid transformation.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
the rotation component of the rigid transformation
Definition at line 232 of file RigidTransformation3D.cpp.
References rot_.
 {
     return rot_;
 }
const Translation3D * RigidTransformation3D::getTranslationComponent (void)
Returns a read-only version of the translation component of the rigid transformation.
Returns
translation rotation component of the rigid transformation
Definition at line 237 of file RigidTransformation3D.cpp.
References trans_.
 {
     return trans_;
 }
Translation3D * RigidTransformation3D::getTranslationComponent (ReadWriteStatus rwa)
Returns a writable version of the translation component of the rigid transformation.
Parameters
rwa the sole possible value for this parameter is R_W_ACCESS
Returns
translation rotation component of the rigid transformation
Definition at line 242 of file RigidTransformation3D.cpp.
References trans_.
 {
     return trans_;
 }
const RigidTransformation3D & RigidTransformation3D::operator= (const RigidTransformation3D & theField) private
Copy operator.
Disabled
Parameters
theField reference to the object to copy
Definition at line 216 of file RigidTransformation3D.cpp.
References FAIL_CONDITION, and uriVL::kFunctionNotImplemented.
 {
     FAIL_CONDITION( true,
                     kFunctionNotImplemented,
                     "Copy constructor not implemented.");
     return *this;
 }
void uriVL::RigidTransformation3D::orthogonalizeMatrix_ (void) private
Ensures that the transformation matrix is still that of a rotation.
void RigidTransformation3D::postComposeTransformation (const RigidTransformation3D * theTransf)
composes a new rigid transformation with this rigid transformation.
The transformation to apply must be defined relative to the current/moving frame.
Parameters
theTransf the transformation to compose with this transformation
Definition at line 277 of file RigidTransformation3D.cpp.
References uriVL::Transformation3D::getMatrix(), and uriVL::R_W_ACCESS.
 {
     (getMatrix(R_W_ACCESS))->postMultiplyBy(transf->getMatrix());
 }
void RigidTransformation3D::postComposeTransformation (const Rotation3D * theRot)
composes a new rigid transformation with this rigid transformation.
The transformation to apply must be defined relative to the current/moving frame.
Parameters
theRot the rotation to compose with this transformation
Definition at line 282 of file RigidTransformation3D.cpp.
References uriVL::Rotation3D::getMatrix(), uriVL::Transformation3D::getMatrix(), and uriVL::R_W_ACCESS.
 {
     (getMatrix(R_W_ACCESS))->postMultiplyBy(theRot->getMatrix());
 }
void RigidTransformation3D::postComposeTransformation (const Translation3D * theTrans)
composes a new rigid transformation with this rigid transformation.
The transformation to apply must be defined relative to the current/moving frame.
Parameters
theTrans the translation to compose with this transformation
Definition at line 287 of file RigidTransformation3D.cpp.
References uriVL::Transformation3D::getMatrix(), uriVL::Matrix::getMatrix(), uriVL::Translation3D::getVector(), and uriVL::R_W_ACCESS.
 {
     double* const *const A = getMatrix(R_W_ACCESS)->getMatrix(R_W_ACCESS);
     const double* T = theTrans->getVector();
     //  add to the 4th column of A the elements of the product Rot(A).T
     for (int i=0; i<3; i++)
         A[i][3] += A[i][0]*T[0] + A[i][1]*T[1] + A[i][2]*T[2];
 }
void RigidTransformation3D::updateMatrix_ (void) const private virtual
Updates the transformation matrix if it was not the reference.
Implements uriVL::Transformation3D.
Definition at line 251 of file RigidTransformation3D.cpp.
References FAIL_CONDITION, uriVL::Matrix::getMatrix(), uriVL::Translation3D::getVector(), uriVL::Transformation3D::homMat_, uriVL::kFunctionNotImplemented, uriVL::Transformation3D::matrixIsReference_, uriVL::R_W_ACCESS, uriVL::Transformation3D::referenceHasChanged_, and trans_.
 {
     if (referenceHasChanged_ && !matrixIsReference_)
     {
         double* const*const mat = homMat_->getMatrix(R_W_ACCESS);
         //  get the translation component
         const double* tXYZ  = trans_->getVector();
         mat[0][2] = tXYZ[0];
         mat[1][2] = tXYZ[1];
         mat[2][2] = tXYZ[2];
         //  compute the rotation
         referenceHasChanged_ = false;
     }
     else if (matrixIsReference_ && referenceHasChanged_)
     {
         //  orthogonalize the matrix
         FAIL_CONDITION( true,
                         kFunctionNotImplemented,
                         "constructor not open for business yet");
     }
 }
Member Data Documentation
Rotation3D* uriVL::RigidTransformation3D::rot_ private
Rotation component of the 3D transformation.
Definition at line 180 of file RigidTransformation3D.h.
Referenced by getRotationComponent(), RigidTransformation3D(), and ~RigidTransformation3D().
Translation3D* uriVL::RigidTransformation3D::trans_ private
Translation component of the 3D transformation.
Definition at line 184 of file RigidTransformation3D.h.
Referenced by getTranslationComponent(), RigidTransformation3D(), updateMatrix_(), and ~RigidTransformation3D().
The documentation for this class was generated from the following files:
RigidTransformation3D.h
RigidTransformation3D.cpp