URIVisionLibrary: ColorGaussianAndMedian.cpp File Reference
ColorGaussianAndMedian.cpp File Reference
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_gray_F.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "ColorMedianFilter_I.h"
#include "ColorGaussianFilter_F.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void resetImages (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string filePath = color_dir + "mandrill_256x256.tga"
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int QUIT_MENU = 0
const int RESET_IMAGES_MENU = 1
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gCurrentFieldRes = 30
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
bool gDrawStuff = false
bool gDrawVectField = false
unsigned char gImageTreshold = 100
RasterImage ** gMyImage = NULL
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 47 of file ColorGaussianAndMedian.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 48 of file ColorGaussianAndMedian.cpp.
#define kDefaultWidth 256
Definition at line 49 of file ColorGaussianAndMedian.cpp.
#define kMaxWindowHeight 640
Definition at line 51 of file ColorGaussianAndMedian.cpp.
#define kMaxWindowWidth 900
Definition at line 50 of file ColorGaussianAndMedian.cpp.
#define kNbBckgndCols 5
Definition at line 118 of file ColorGaussianAndMedian.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 43 of file ColorGaussianAndMedian.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 45 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 42 of file ColorGaussianAndMedian.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 44 of file ColorGaussianAndMedian.cpp.
Referenced by myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 162 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 138 of file ColorGaussianAndMedian.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 177 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit(), filePath, uriVL::ImageReader::getFrame(), kNbImages, LOWER_LEFT, LOWER_RIGHT, myReader, uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     gMyImage = new RasterImage*[kNbImages];
     //-------------------------------------------------------------
     //  We read Image 0 from a file
     //-------------------------------------------------------------
     ImageReader myReader(const_cast<char*>(filePath.c_str()));
     gMyImage[UPPER_LEFT] = myReader.getFrame(true);
     if (gMyImage[UPPER_LEFT] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath << endl;
         cleanupAndQuit(-1);
     }
     //  Image 1 is just Image 0 converted to gray level
     gMyImage[UPPER_RIGHT] = new RasterImage_RGBa(gMyImage[UPPER_LEFT]);
     gMyImage[UPPER_RIGHT]->setDrawValidDataFrame(true);
     gMyImage[UPPER_RIGHT]->setFrameColor(0.f, 1.f, 1.f);
     //  Images 2 and 3 are created with as RGBa_F images with the same bounding rectangle
     //  as image 0.  Initialized with the same values as Image 1
     gMyImage[LOWER_LEFT] = new RasterImage_RGBa_F(gMyImage[UPPER_RIGHT]);
     gMyImage[LOWER_LEFT]->setDrawValidDataFrame(true);
     gMyImage[LOWER_LEFT]->setFrameColor(0.f, 1.f, 1.f);
     gMyImage[LOWER_RIGHT] = new RasterImage_RGBa_F(gMyImage[UPPER_RIGHT]);
     gMyImage[LOWER_RIGHT]->setDrawValidDataFrame(true);
     gMyImage[LOWER_RIGHT]->setFrameColor(0.f, 1.f, 1.f);
 }
int main (int argc, char ** argv)
Definition at line 602 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), myReshape(), setupCamera(), and UPPER_LEFT.
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[4])() = {myDisplay0, myDisplay1,
                                         myDisplay2, myDisplay3};
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
         initializeQTEnvironment();
         //      I load my images
         loadImage();
         int     imgHeight = gMyImage[UPPER_LEFT]->getHeight(),
             imgWidth = gMyImage[UPPER_LEFT]->getWidth();
         //      I inform all drawable objects of the dimensions of their subwindow
         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
         //      I initialize my window's dimensions
         gWinHeight = kNbRowsSubwindows * (imgHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows * (imgWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Color Gaussian and Median Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
         glClearColor(0.f, 0.f, 0.f, 1.f);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(imgWidth + kBorder) + kBorder,
                                                         i*(imgHeight + kBorder) + kBorder,
                                                         imgWidth, imgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(imgWidth, imgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
         glutMainLoop();
         cleanupAndQuit(0);
     }
     catch (uriVL::ErrorReport & e)
         {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
         return 0;
 }
void myColorSubmenu (int value)
Definition at line 489 of file ColorGaussianAndMedian.cpp.
References gMainWindow, kBackgroundColor, kNbBckgndCols, and myDisplay0().
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         myDisplay0();
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 238 of file ColorGaussianAndMedian.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), myColorSubmenu(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[UPPER_LEFT]->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 256 of file ColorGaussianAndMedian.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[UPPER_RIGHT]->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay2 (void)
Definition at line 274 of file ColorGaussianAndMedian.cpp.
References gInitDone, gMainWindow, gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[LOWER_LEFT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 291 of file ColorGaussianAndMedian.cpp.
References gInitDone, gMainWindow, gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[LOWER_RIGHT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 223 of file ColorGaussianAndMedian.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 591 of file ColorGaussianAndMedian.cpp.
References gInitDone, and gMainWindow.
Referenced by main().
 {
         if (gInitDone)
         {
                 glutSetWindow(gMainWindow);
             glutPostRedisplay();
         }
 }
void myInit (void)
Definition at line 507 of file ColorGaussianAndMedian.cpp.
References gInitDone, gMainWindow, gSubwindow, kBckgndColStr, kNbBckgndCols, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), QUIT_MENU, RESET_IMAGES_MENU, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu, gaussMenu, medianMenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.f, 0.f, 0.f, 1.f);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", 0);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("Reset Images", RESET_IMAGES_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("Reset Images", RESET_IMAGES_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     //
     gaussMenu = glutCreateMenu(myMenu2);
     glutAddMenuEntry("3x3 color Gaussian", 3);
     glutAddMenuEntry("5x5 color Gaussian", 5);
     glutAddMenuEntry("7x7 color Gaussian", 7);
     glutAddMenuEntry("9x9 color Gaussian", 9);
     glutAddMenuEntry("11x11 color Gaussian", 11);
     glutAddMenuEntry("13x13 color Gaussian", 13);
     glutAddMenuEntry("21x21 color Gaussian", 21);
     //
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Apply Filter", gaussMenu);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     //
     medianMenu = glutCreateMenu(myMenu3);
     glutAddMenuEntry("3x3 color median", 3);
     glutAddMenuEntry("5x5 color median", 5);
     glutAddMenuEntry("7x7 color median", 7);
     glutAddMenuEntry("9x9 color median", 9);
     glutAddMenuEntry("11x11 color median", 11);
     glutAddMenuEntry("13x13 color median", 13);
     //
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Apply Filter", medianMenu);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 344 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         //      [ and ] do something to the images
         case '[':
             break;
         case ']':
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 386 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit(), gMainWindow, QUIT_MENU, RESET_IMAGES_MENU, and resetImages().
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case RESET_IMAGES_MENU:
             resetImages();
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 407 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit(), gMainWindow, QUIT_MENU, RESET_IMAGES_MENU, and resetImages().
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case RESET_IMAGES_MENU:
             resetImages();
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 428 of file ColorGaussianAndMedian.cpp.
References uriVL::ColorGaussianFilter_F::applyInto(), cleanupAndQuit(), gMainWindow, and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case 3:
         case 5:
         case 7:
         case 9:
         case 11:
         case 13:
         case 21:
             ColorGaussianFilter_F    *gauss;
             gauss = new ColorGaussianFilter_F((int) value);
             gauss->applyInto(gMyImage[1], gMyImage[2]);
             delete gauss;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 459 of file ColorGaussianAndMedian.cpp.
References uriVL::ColorMedianFilter_I::applyInto(), cleanupAndQuit(), gMainWindow, and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case 3:
         case 5:
         case 7:
         case 9:
         case 11:
         case 13:
             ColorMedianFilter_I    *median;
             median = new ColorMedianFilter_I((int) value);
             median->applyInto(gMyImage[1], gMyImage[3]);
             delete median;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 371 of file ColorGaussianAndMedian.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 365 of file ColorGaussianAndMedian.cpp.
 {
 }
void myReshape (int w, int h)
Definition at line 311 of file ColorGaussianAndMedian.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void resetImages (void)
Definition at line 207 of file ColorGaussianAndMedian.cpp.
References uriVL::RasterImage::copyInto(), LOWER_LEFT, LOWER_RIGHT, and UPPER_RIGHT.
Referenced by myMenu0(), and myMenu1().
 {
     gMyImage[UPPER_RIGHT]->copyInto(gMyImage[LOWER_LEFT]);
     gMyImage[UPPER_RIGHT]->copyInto(gMyImage[LOWER_RIGHT]);
 }
void setupCamera (int w, int h)
Definition at line 330 of file ColorGaussianAndMedian.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 34 of file ColorGaussianAndMedian.cpp.
const string filePath = color_dir + "mandrill_256x256.tga"
Definition at line 36 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage().
int gCurrentFieldRes = 30
Definition at line 101 of file ColorGaussianAndMedian.cpp.
bool gDrawStuff = false
Definition at line 107 of file ColorGaussianAndMedian.cpp.
bool gDrawVectField = false
Definition at line 108 of file ColorGaussianAndMedian.cpp.
int gImageHeight = kDefaultHeight
Definition at line 99 of file ColorGaussianAndMedian.cpp.
unsigned char gImageTreshold = 100
Definition at line 110 of file ColorGaussianAndMedian.cpp.
int gImageWidth = kDefaultWidth
Definition at line 98 of file ColorGaussianAndMedian.cpp.
bool gInitDone = false
Definition at line 106 of file ColorGaussianAndMedian.cpp.
Referenced by myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myIdle(), and myInit().
int gMainWindow
Definition at line 103 of file ColorGaussianAndMedian.cpp.
Referenced by main(), myColorSubmenu(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myMenu0(), myMenu1(), myMenu2(), and myMenu3().
RasterImage** gMyImage = NULL
Definition at line 112 of file ColorGaussianAndMedian.cpp.
int gSubwindow[kNbSubwindows]
Definition at line 103 of file ColorGaussianAndMedian.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
int gWinHeight
Definition at line 96 of file ColorGaussianAndMedian.cpp.
Referenced by main().
int gWinWidth
Definition at line 96 of file ColorGaussianAndMedian.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 120 of file ColorGaussianAndMedian.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 126 of file ColorGaussianAndMedian.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 55 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage(), myDisplay2(), myInit(), and resetImages().
const int LOWER_RIGHT = 3
Definition at line 56 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage(), myDisplay3(), myInit(), and resetImages().
const int QUIT_MENU = 0
Definition at line 58 of file ColorGaussianAndMedian.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int RESET_IMAGES_MENU = 1
Definition at line 59 of file ColorGaussianAndMedian.cpp.
Referenced by myInit(), myMenu0(), and myMenu1().
const int UPPER_LEFT = 0
Definition at line 53 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage(), main(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 54 of file ColorGaussianAndMedian.cpp.
Referenced by loadImage(), myDisplay1(), myInit(), and resetImages().