URIVisionLibrary: main_IO.cpp File Reference
Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp File Reference
#include <iostream>
#include <cmath>
#include "ImageReader.h"
#include "ImageWriter.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray_F.h"
Macros
#define kNbImages 9
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImages (void)
void myDisplay (void)
void myReshape (int w, int h)
void myMenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
int main (int argc, char **argv)
Variables
int gCurrentImg = 0
RasterImage ** gMyImage = NULL
bool gInitDone = false
const int QUIT_MENU = 0
const int NEXT_IMAGE_MENU = 1
const int PREVIOUS_IMAGE_MENU = 2
Macro Definition Documentation
#define kNbImages 9
Definition at line 51 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by loadImages(), myKeyboard(), myMenu(), and myMouse().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 122 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by loadImages(), main(), myKeyboard(), and myMenu().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 98 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myInit().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImages (void)
Definition at line 137 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References cleanupAndQuit(), gMyImage, kNameFile2, kNameFile3, kNameFile4, kNbImages, and myReader.
Referenced by myInit().
 {
     long        idx;
     int     n;
     ImageReader         *myReader;
     ImageWriter         *myWriter;
     gMyImage = new RasterImage *[kNbImages];
     //-------------------------------------------------------------
     //  Image 0 is created by computation --> fill the array with RGB values
     //-------------------------------------------------------------
     n = 256;
     //
     unsigned char       *tempBuf = new unsigned char[n * n * 3];
     if (tempBuf !=NULL)
     {
         for (int i=0; i<n; i++)
         {
             idx = 3 * n * i;
             for (int j=0; j<n; j++)
             {
                 tempBuf[idx++] = static_cast<unsigned char>(i);
                 tempBuf[idx++] = static_cast<unsigned char>(255-j);
                 tempBuf[idx++] = static_cast<unsigned char>(0);
             }
         }
         gMyImage[0] = new RasterImage_RGB(n, n, tempBuf);
         delete tempBuf;
     }
     else
     {
         cout << "Generation of image 0 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 1 is created by computation --> fill the array with RGBA values
     //  This code fragment demonstrate how to get direct access to the image's
     //  raster for initialization and other IP calculations
     //-------------------------------------------------------------
     n = 256;
     //
     //  the raster image is created at the desired dimensions
     gMyImage[1] = new RasterImage_RGBa(n, n);
     if (gMyImage[1] != NULL)
     {
         //  we get a reference to the image's base raster
         unsigned char   **rgba = gMyImage[1]->getRaster2D();
         //  just to play nice, we get the image's dimensions, although
         //  they should be both equal to n
         int   nbRows = gMyImage[1]->getHeight(),
               nbCols = gMyImage[1]->getWidth();
         //  from this point on
         for (int i=0; i<nbRows; i++)
             for (int j=0; j<nbCols; j++)
             {
                 rgba[i][4*j] = static_cast<unsigned char>(floor((i-n/2.)*(i-n/2.)/120. + 20));
                 rgba[i][4*j+1] = static_cast<unsigned char>(j/4 + 30);
                 rgba[i][4*j+2] = static_cast<unsigned char>(floor(127*(cos(0.06*i)*sin(0.1*j)+0.5)));
                 rgba[i][4*j+3] = static_cast<unsigned char>(255);
             }
         //      By default, the RasterImage class adopts the "safe" mode for the definition
         //      of the valid data rectangle.  Since image1 was just allocated not initialized,
         //      its valid data rectangle was located at the upper left corner of the bounding
         //      rectangle, with width and height 0.  We must now set the correct values.
         gMyImage[1]->setValidRect(0, 0, nbCols, nbRows);
     }
     else
     {
         cout << "Generation of image 1 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 2 is created by computation --> fill the array with Gray values
     //-------------------------------------------------------------
     n = 256;
     //
     gMyImage[2] = new RasterImage_gray(n, n);
     if (gMyImage[2] !=NULL)
     {
         unsigned char **gray = gMyImage[2]->getRaster2D();
         for (int i=0; i<n; i++)
             for (int j=0; j<n; j++)
                 gray[i][j] = static_cast<unsigned char>(i>j ? i : j);
     }
     else
     {
         cout << "Generation of image 3 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 3 is read from a TGA file
     //-------------------------------------------------------------
     //  I can create a reader by passing a file path
     myReader = new ImageReader(kNameFile2);
     gMyImage[3] = myReader->getFrame(false);
     delete myReader;
     if (gMyImage[3] ==NULL)
     {
         cout << "Generation of image 3 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 4 is read from a PPM file
     //-------------------------------------------------------------
     //  I can also create the reader w/o passing any file info
     myReader = new ImageReader( );
     //  and later on specify a file path, FSSPec, or select the file to read
     //  through a GUI dialog
     myReader->setSource(kNameFile3);
     gMyImage[4] = myReader->getFrame(false);
     if (gMyImage[4] ==NULL)
     {
         cout << "Generation of image 4 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 5 is read from a PGM file (gray-level image)
     //-------------------------------------------------------------
     //  I can also reuse the same ImageReader and simply set a new source
     myReader->setSource(kNameFile4);
     gMyImage[5] = myReader->getFrame(true);
     if (gMyImage[5] ==NULL)
     {
         cout << "Generation of image 5 failed.";
         cleanupAndQuit(-1);
     }
     //-------------------------------------------------------------
     //  Image 6 is an RGBa copy of a gray-level image, using directly the
     //  copyInto function.
     //-------------------------------------------------------------
     //  Let's say that I want to reuse a RasterImage allocated earlier.
     //  This one has bogus dimensions
     gMyImage[6] = new RasterImage_RGBa(100, 250);
     if (gMyImage[6] ==NULL)
     {
         cout << "Generation of image 6 failed.";
         cleanupAndQuit(-1);
     }
     //  since the destination of the copy does not have the same dimensions
     //  as the source, its base raster will get reallocated.
     gMyImage[5]->copyInto(gMyImage[6]);
     //-------------------------------------------------------------
     //  Image 7 is a gray-level copy of an RGBa  image
     //-------------------------------------------------------------
     n = 256;
     gMyImage[7] = new RasterImage_gray(n, n);
     if (gMyImage[7] ==NULL)
     {
         cout << "Generation of image 7 failed.";
         cleanupAndQuit(-1);
     }
     gMyImage[3]->copyInto(gMyImage[7]);
     //-------------------------------------------------------------
     //  Image 8 is a gray-level copy of an RGBa  image, initialized by the constructor
     //-------------------------------------------------------------
     gMyImage[8] = new RasterImage_gray(gMyImage[4]);
     if (gMyImage[8] ==NULL)
     {
         cout << "Generation of image 8 failed.";
         cleanupAndQuit(-1);
     }
     //  Tests of image output
 #if URIVL_OS_MACOS
     //  Similarly, I can create an ImageWriter with a destination specified by a path
     myWriter = new ImageWriter(":Output:im0.ppm");
     myWriter->outputFrame(gMyImage[0]);
     delete myWriter;
     //  or w/o any argument and set the destination later
     myWriter = new ImageWriter( );
     myWriter->setDestination(":Output:im0.tga");
     myWriter->outputFrame(gMyImage[0]);
     //  and I can reuse the same ImageWriter with a new destination
     myWriter->setDestination(":Output:im5.tga");
     myWriter->outputFrame(gMyImage[5]);
     //  and I can reuse the same ImageWriter with a new destination
     myWriter->setDestination(":Output:im4.ppm");
     myWriter->outputFrame(gMyImage[4]);
     myWriter->setDestination(":Output:im4.tga");
     //  I can choose to write the image upside down
     myWriter->outputFrame(gMyImage[4]);
     delete myWriter;
 #else
     //  Similarly, I can create an ImageWriter with a destination specified by a path
     myWriter = new ImageWriter("./Output/im0.ppm");
     myWriter->outputFrame(gMyImage[0]);
     delete myWriter;
     //  or w/o any argument and set the destination later
     myWriter = new ImageWriter( );
     myWriter->setDestination("./Output/im0.tga");
     myWriter->outputFrame(gMyImage[0]);
     //  and I can reuse the same ImageWriter with a new destination
     myWriter->setDestination("./Output/im1.ppm");
     myWriter->outputFrame(gMyImage[1]);
     //  and I can reuse the same ImageWriter with a new destination
     myWriter->setDestination("./Output/im4.ppm");
     myWriter->outputFrame(gMyImage[4]);
     myWriter->setDestination("./Output/im4.tga");
     //  I can choose to write the image upside down
     myWriter->outputFrame(gMyImage[4]);
     delete myWriter;
 #endif
     delete myReader;
 }
int main (int argc, char ** argv)
Definition at line 531 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References cleanupAndQuit(), gMyImage, myDisplay(), myInit(), myKeyboard(), myMouse(), and myReshape().
 {
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
     glutInitWindowSize(100,100);
     glutCreateWindow("Image IO & Display Demo");
     //  defines glut callback functions that will interrupt the glut loop
     glutDisplayFunc(myDisplay);
     glutReshapeFunc(myReshape);
     glutMouseFunc(myMouse);
     glutKeyboardFunc(myKeyboard);
     //  Initializes QuickTime and loads the images
     myInit();
     //  Having read the images, I can now resize my window to the appropriate dimensions
     glutReshapeWindow(gMyImage[0]->getWidth(),
                       gMyImage[0]->getHeight());
     //  Enter infinite glut loop
     glutMainLoop();
     //  Normally this code should never be placed since the only way to leave the
     //  glut loop is to quit
     cleanupAndQuit(0);
     return 0;
 }
void myDisplay (void)
Definition at line 384 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References gCurrentImg, gInitDone, and gMyImage.
Referenced by main().
 {
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
         gMyImage[gCurrentImg]->render( );
     glutSwapBuffers();
 }
void myInit (void)
Definition at line 497 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References gInitDone, initializeQTEnvironment(), loadImages(), myMenu(), NEXT_IMAGE_MENU, PREVIOUS_IMAGE_MENU, and QUIT_MENU.
Referenced by main().
 {
     initializeQTEnvironment();
     loadImages();
     glClearColor(0.0, 0.0, 0.0, 1.0);
     // Create Menus
     int menu, imageSubmenu;
     //  Submenu for direct image selection
     //  This is to show that I can use the same function to handle all submenus
     //  as long as they have unique indexes.  Still, it is probably a good idea
     //  to break down menu handling into several manageable-size functions.
     imageSubmenu = glutCreateMenu(myMenu);
     glutAddMenuEntry("0", 10);
     glutAddMenuEntry("1", 11);
     glutAddMenuEntry("2", 12);
     glutAddMenuEntry("3", 13);
     glutAddMenuEntry("4", 14);
     // Main menu that the submenus are connected to
     menu = glutCreateMenu(myMenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Image", imageSubmenu);
     glutAddMenuEntry("Next Image", NEXT_IMAGE_MENU);
     glutAddMenuEntry("Previous Image", PREVIOUS_IMAGE_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 415 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References cleanupAndQuit(), gCurrentImg, gMyImage, and kNbImages.
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
             //  [ and ] let me cycle through the images
         case '[':
             gCurrentImg = (gCurrentImg+kNbImages-1) % kNbImages;
             glutReshapeWindow(  gMyImage[gCurrentImg]->getWidth(),
                                gMyImage[gCurrentImg]->getHeight());
             break;
         case ']':
             gCurrentImg = (gCurrentImg + 1) % kNbImages;
             glutReshapeWindow(  gMyImage[gCurrentImg]->getWidth(),
                                gMyImage[gCurrentImg]->getHeight());
             break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myMenu (int value)
Definition at line 461 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References cleanupAndQuit(), gCurrentImg, gMyImage, kNbImages, NEXT_IMAGE_MENU, PREVIOUS_IMAGE_MENU, and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case NEXT_IMAGE_MENU:
             gCurrentImg = (gCurrentImg + 1) % kNbImages;
             glutReshapeWindow(  gMyImage[gCurrentImg]->getWidth(),
                                gMyImage[gCurrentImg]->getHeight());
             break;
         case PREVIOUS_IMAGE_MENU:
             gCurrentImg = (gCurrentImg+kNbImages-1) % kNbImages;
             glutReshapeWindow(  gMyImage[gCurrentImg]->getWidth(),
                                gMyImage[gCurrentImg]->getHeight());
             break;
         //      10-14 --> image selection
         case 10:
         case 11:
         case 12:
         case 13:
         case 14:
             gCurrentImg = value - 10;
             glutReshapeWindow(  gMyImage[gCurrentImg]->getWidth(),
                                gMyImage[gCurrentImg]->getHeight());
             break;
     }
     glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 444 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References gCurrentImg, gMyImage, and kNbImages.
Referenced by main().
 {
     // if the left mouse button is clicked, do something
     if(state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
         gCurrentImg = (gCurrentImg+kNbImages-1) % kNbImages;
         glutReshapeWindow(      gMyImage[gCurrentImg]->getWidth(),
                            gMyImage[gCurrentImg]->getHeight());
     }
     //  ...and then refresh the display
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 395 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
References gCurrentImg, and gMyImage.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
     //  and I inform drawable object of these dimensions (in case they want to
     //  get rendered "shifted")
     DrawableObject2D::setDefaultWindowDimensions(gMyImage[gCurrentImg]->getWidth(),
                                                  gMyImage[gCurrentImg]->getHeight());
 }
Variable Documentation
int gCurrentImg = 0
Definition at line 83 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myDisplay(), myKeyboard(), myMenu(), myMouse(), and myReshape().
bool gInitDone = false
Definition at line 87 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myDisplay(), and myInit().
RasterImage** gMyImage = NULL
Definition at line 85 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by loadImages(), main(), myDisplay(), myKeyboard(), myMenu(), myMouse(), and myReshape().
const int NEXT_IMAGE_MENU = 1
Definition at line 90 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myInit(), and myMenu().
const int PREVIOUS_IMAGE_MENU = 2
Definition at line 91 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myInit(), and myMenu().
const int QUIT_MENU = 0
Definition at line 89 of file Computer_Vision/Calibration_3D/Projects/XCode/main_IO.cpp.
Referenced by myInit(), and myMenu().