URIVisionLibrary: edgePixels.cpp File Reference
edgePixels.cpp File Reference
#include <fstream>
#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_gray_F.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "VectorField_I.h"
#include "VectorField_F.h"
#include "ImageGradient_Gaussian_F.h"
#include "ImageLaplacian_Gaussian_F.h"
#include "GaussianFilter_F.h"
#include "ImageGradient_Sobel.h"
#include "ImageLaplacian_Sobel.h"
#include "ZeroCrossingDetector.h"
#include "NonMaximumSuppressor.h"
#include "HistogramCalculator.h"
#include "LabelRaster.h"
#include "HysteresisLabeler.h"
Macros
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages kNbSubwindows
#define kNbBckgndCols 5
#define UPSIDE_DOWN true
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
int main (int argc, char **argv)
Variables
const string filePath = gray_dir + "Lena_256x256.tga"
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int QUIT_APPL = 0
const int NO_FILTER = 1
const int SEPARATOR = 1000
const int ORIGINAL_IMAGE = 51
const int LAPLACIAN_SOBEL_FORM_1_MENU = 31
const int LAPLACIAN_SOBEL_FORM_2_MENU = 32
const int LAPLACIAN_SOBEL_FORM_3_MENU = 33
const int LAPLACIAN_OF_GAUSSIAN_5x5 = 5
const int LAPLACIAN_OF_GAUSSIAN_7x7 = 7
const int LAPLACIAN_OF_GAUSSIAN_9x9 = 9
const int LAPLACIAN_OF_GAUSSIAN_11x11 = 11
const int LAPLACIAN_OF_GAUSSIAN_13x13 = 13
const int LAPLACIAN_OF_GAUSSIAN_21x21 = 21
const int TOGGLE_ZERO_CROSSINGS = 50
const int TOGGLE_COLORED_LAPLACIAN = 55
const int GoG_3x3 = 3
const int GoG_5x5 = 5
const int GoG_7x7 = 7
const int GoG_9x9 = 9
const int GoG_11x11 = 11
const int GoG_13x13 = 13
const int GoG_21x21 = 21
const int GoG = 61
const int NONMAX_SUPPR_GoG = 62
const int HYST_THRESH_GoG = 63
const int NORM_GoG = 52
const int NONMAX_SUPPR_NoGoG = 53
const int HYST_THRESH_NoGoG = 54
const int COARSER_VECT_RESOLUTION = 71
const int FINER_VECT_RESOLUTION = 72
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
int gWinWidth
int gWinHeight
int gImageWidth = kDefaultWidth
int gImageHeight = kDefaultHeight
int gCurrentFieldRes = 30
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
bool gDrawStuff = false
bool gDrawVectField = false
unsigned char gImageTreshold = 100
RasterImage * gMyImage = NULL
RasterImage_gray * gImgGray = NULL
RasterImage_gray_F * gSmoothedImg = NULL
VectorField_F * gMyGradient = NULL
VectorField_F * gNonMaxSupprGrad = NULL
RasterImage_gray_F * gGradientNorm = NULL
RasterImage_gray * gZeroCrossImg = NULL
RasterImage_gray_F * gNonMaxSupprGradNorm = NULL
RasterImage_gray * gHistoThresholdedImg = NULL
RasterImage_gray_F * gLplcImg = NULL
RasterImage_gray_F * gLplcImgSobel = NULL
RasterImage_gray_F * gLplcImgGauss = NULL
RasterImage_gray * gCannyRas = NULL
RasterImage_RGBa * gColoredLaplacian = NULL
LabelRaster * gLabel = NULL
bool gradComputed = false
bool gDisplayZeroCrossings = false
bool gDisplayColoredLaplacian = false
RasterImage * gImageDisplayed [kNbSubwindows] = {NULL, NULL, NULL, NULL}
VectorField * gVFieldDisplayed [kNbSubwindows] = {NULL, NULL, NULL, NULL}
Macro Definition Documentation
#define kBorder 8
Definition at line 86 of file edgePixels.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 87 of file edgePixels.cpp.
#define kDefaultWidth 256
Definition at line 88 of file edgePixels.cpp.
#define kMaxWindowHeight 640
Definition at line 90 of file edgePixels.cpp.
#define kMaxWindowWidth 900
Definition at line 89 of file edgePixels.cpp.
#define kNbBckgndCols 5
Definition at line 147 of file edgePixels.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 93 of file edgePixels.cpp.
Referenced by main().
#define kNbImages kNbSubwindows
Definition at line 95 of file edgePixels.cpp.
#define kNbRowsSubwindows 2
Definition at line 92 of file edgePixels.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 94 of file edgePixels.cpp.
Referenced by main().
#define UPSIDE_DOWN true
Definition at line 170 of file edgePixels.cpp.
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 275 of file edgePixels.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 251 of file edgePixels.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 290 of file edgePixels.cpp.
References cleanupAndQuit(), filePath, uriVL::DrawableObject2D::getBoundRect(), uriVL::ImageReader::getFrame(), gImgGray, gMyGradient, gMyImage, LOWER_LEFT, LOWER_RIGHT, myReader, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     //-------------------------------------------------------------
     //  We read from a file the image to process
     //-------------------------------------------------------------
     ImageReader myReader(const_cast<char*>(filePath.c_str()));
     gMyImage = myReader.getFrame(true);
     if (gMyImage ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath << endl;
         cleanupAndQuit(-1);
     }
     //  we convert the image to gray level
     gImgGray = new RasterImage_gray(gMyImage);
     //  initially the "smoothed" gray level image is just a copy of gImgGray
     gSmoothedImg = new RasterImage_gray_F(gImgGray);
     //  The other images and vector fields are just allocated at the same dimensions
     //  as the input image
     const ImageRect     *rect = gMyImage->getBoundRect();
     gLplcImgSobel = new RasterImage_gray_F(rect);
     gLplcImgGauss = new RasterImage_gray_F(rect);
     gMyGradient = new VectorField_F(rect);
     gNonMaxSupprGrad = new VectorField_F(rect);
     gGradientNorm = new RasterImage_gray_F(rect);
     gZeroCrossImg = new RasterImage_gray(rect);
     gColoredLaplacian = new RasterImage_RGBa(rect);
         gCannyRas = new RasterImage_gray(rect);
         gLabel = new LabelRaster(rect);
     gImageDisplayed[UPPER_LEFT] = gMyImage;
     gImageDisplayed[UPPER_RIGHT] = gImgGray;
     gImageDisplayed[LOWER_LEFT] = gImgGray;
     gImageDisplayed[LOWER_RIGHT] = gImgGray;
     //
     gVFieldDisplayed[LOWER_RIGHT] = gMyGradient;
 }
int main (int argc, char ** argv)
Definition at line 959 of file edgePixels.cpp.
References cleanupAndQuit(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myInit(), myKeyboard(), myReshape(), and setupCamera().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                                     myDisplay2, myDisplay3};
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         //      I load my images
         loadImage();
         int     imgHeight = gMyImage->getHeight(),
             imgWidth = gMyImage->getWidth();
         //      I inform all drawable objects of the dimensions of their subwindow
         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
         //      I initialize my window's dimensions
         gWinHeight = kNbRowsSubwindows * (imgHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows * (imgWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Edge Pixels Detection Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
         glClearColor(0.0, 0.0, 0.0, 1.0);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(imgWidth + kBorder) + kBorder,
                                                         i*(imgHeight + kBorder) + kBorder,
                                                         imgWidth, imgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(imgWidth, imgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         glutSetWindow(gMainWindow);
         myDisplayMain();
         glutMainLoop();
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myColorSubmenu (int value)
Definition at line 826 of file edgePixels.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 356 of file edgePixels.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gImageDisplayed[UPPER_LEFT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 374 of file edgePixels.cpp.
References gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gImageDisplayed[UPPER_RIGHT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay2 (void)
Definition at line 392 of file edgePixels.cpp.
References gInitDone, gMainWindow, gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gImageDisplayed[LOWER_LEFT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 410 of file edgePixels.cpp.
References gInitDone, gMainWindow, gradComputed, gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gImageDisplayed[LOWER_RIGHT]->render(true);
         if (gradComputed)
             gVFieldDisplayed[LOWER_RIGHT]->render(true);
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 341 of file edgePixels.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myInit (void)
Definition at line 843 of file edgePixels.cpp.
References COARSER_VECT_RESOLUTION, FINER_VECT_RESOLUTION, gInitDone, gMainWindow, GoG, GoG_11x11, GoG_13x13, GoG_21x21, GoG_3x3, GoG_5x5, GoG_7x7, GoG_9x9, gSubwindow, HYST_THRESH_GoG, HYST_THRESH_NoGoG, kBckgndColStr, kNbBckgndCols, LAPLACIAN_OF_GAUSSIAN_11x11, LAPLACIAN_OF_GAUSSIAN_13x13, LAPLACIAN_OF_GAUSSIAN_21x21, LAPLACIAN_OF_GAUSSIAN_5x5, LAPLACIAN_OF_GAUSSIAN_7x7, LAPLACIAN_OF_GAUSSIAN_9x9, LAPLACIAN_SOBEL_FORM_1_MENU, LAPLACIAN_SOBEL_FORM_2_MENU, LAPLACIAN_SOBEL_FORM_3_MENU, LOWER_LEFT, LOWER_RIGHT, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), NO_FILTER, NONMAX_SUPPR_GoG, NONMAX_SUPPR_NoGoG, NORM_GoG, ORIGINAL_IMAGE, QUIT_APPL, SEPARATOR, TOGGLE_COLORED_LAPLACIAN, TOGGLE_ZERO_CROSSINGS, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[4], colorSubmenu, gaussMenu, laplacianGaussianMenu,
     laplacianSobelMenu, gradientMenu, gradBackgroundMenu, gradVecDisplayMenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", 0);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //  Setup menus for upper-left subwindow
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     //
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_APPL);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //  Setup menus for upper-right subwindow
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     //
     gaussMenu = glutCreateMenu(myMenu1);
     glutAddMenuEntry("3x3 Gaussian", 3);
     glutAddMenuEntry("5x5 Gaussian", 5);
     glutAddMenuEntry("7x7 Gaussian", 7);
     glutAddMenuEntry("9x9 Gaussian", 9);
     glutAddMenuEntry("11x11 Gaussian", 11);
     glutAddMenuEntry("13x13 Gaussian", 13);
     glutAddMenuEntry("21x21 Gaussian", 21);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_APPL);
     glutAddMenuEntry("No Filter", NO_FILTER);
     glutAddSubMenu("Apply Filter", gaussMenu);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //  Setup menus for lower-left subwindow
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     //
     laplacianSobelMenu = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Form 1", LAPLACIAN_SOBEL_FORM_1_MENU);
     glutAddMenuEntry("Form 2", LAPLACIAN_SOBEL_FORM_2_MENU);
     glutAddMenuEntry("Form 3", LAPLACIAN_SOBEL_FORM_3_MENU);
     laplacianGaussianMenu = glutCreateMenu(myMenu2);
     glutAddMenuEntry("5x5 LoG", LAPLACIAN_OF_GAUSSIAN_5x5);
     glutAddMenuEntry("7x7 LoG", LAPLACIAN_OF_GAUSSIAN_7x7);
     glutAddMenuEntry("9x9 LoG", LAPLACIAN_OF_GAUSSIAN_9x9);
     glutAddMenuEntry("11x11 LoG", LAPLACIAN_OF_GAUSSIAN_11x11);
     glutAddMenuEntry("13x13 LoG", LAPLACIAN_OF_GAUSSIAN_13x13);
     glutAddMenuEntry("21x21 LoG", LAPLACIAN_OF_GAUSSIAN_21x21);
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddSubMenu("Laplacian Sobel", laplacianSobelMenu);
     glutAddSubMenu("Laplacian of Gaussian", laplacianGaussianMenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Toggle zero crossings", TOGGLE_ZERO_CROSSINGS);
     glutAddMenuEntry("Toggle colored Laplacian", TOGGLE_COLORED_LAPLACIAN);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Quit", QUIT_APPL);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //  Setup menus for lower-right subwindow
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     //
     gradientMenu = glutCreateMenu(myMenu3);
     glutAddMenuEntry("3x3 GoG", GoG_3x3);
     glutAddMenuEntry("5x5 GoG", GoG_5x5);
     glutAddMenuEntry("7x7 GoG", GoG_7x7);
     glutAddMenuEntry("9x9 GoG", GoG_9x9);
     glutAddMenuEntry("11x11 GoG", GoG_11x11);
     glutAddMenuEntry("13x13 GoG", GoG_13x13);
     glutAddMenuEntry("21x21 GoG", GoG_21x21);
     //
     gradVecDisplayMenu = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Gradient of Gaussian", GoG);
     glutAddMenuEntry("Nonmaximum suppressed GoG", NONMAX_SUPPR_GoG);
     glutAddMenuEntry("Hysteresis thresholded GoG", HYST_THRESH_GoG);
     //
     gradBackgroundMenu = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Original image", ORIGINAL_IMAGE);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Norm of GoG", NORM_GoG);
     glutAddMenuEntry("Nonmaximum suppressed NoGoG", NONMAX_SUPPR_NoGoG);
     glutAddMenuEntry("Hysteresis thresholded NoGoG", HYST_THRESH_NoGoG);
     //
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddSubMenu("Apply gradient of Gaussian", gradientMenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Vector field displayed", gradVecDisplayMenu);
     glutAddMenuEntry("Coarser resolution", COARSER_VECT_RESOLUTION);
     glutAddMenuEntry("Finer resolution", FINER_VECT_RESOLUTION);
     glutAddSubMenu("Select background image", gradBackgroundMenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Quit", QUIT_APPL);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 464 of file edgePixels.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 494 of file edgePixels.cpp.
References cleanupAndQuit(), and QUIT_APPL.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_APPL:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 509 of file edgePixels.cpp.
References uriVL::GaussianFilter_F::applyInto(), cleanupAndQuit(), uriVL::RasterImage_gray::copyInto(), gImgGray, gMainWindow, gSmoothedImg, NO_FILTER, QUIT_APPL, and UPPER_RIGHT.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_APPL:
             cleanupAndQuit(0);
             break;
         case NO_FILTER:
             gImageDisplayed[UPPER_RIGHT] = gImgGray;
             gImgGray->copyInto(gSmoothedImg);
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         case 3:
         case 5:
         case 7:
         case 9:
         case 11:
         case 13:
         case 21:
             //  apply the Gaussian filter to the image
             GaussianFilter_F    *gauss;
             gauss = new GaussianFilter_F((int) value);
             gauss->applyInto(gImgGray, gSmoothedImg);
             gImageDisplayed[UPPER_RIGHT] = gSmoothedImg;
             delete gauss;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 548 of file edgePixels.cpp.
References uriVL::ImageLaplacian_Gaussian_F::applyInto(), uriVL::ImageLaplacian_Sobel::applyInto(), cleanupAndQuit(), gColoredLaplacian, gDisplayColoredLaplacian, gDisplayZeroCrossings, gLplcImg, gLplcImgGauss, gLplcImgSobel, gMainWindow, gZeroCrossImg, LAPLACIAN_OF_GAUSSIAN_11x11, LAPLACIAN_OF_GAUSSIAN_13x13, LAPLACIAN_OF_GAUSSIAN_21x21, LAPLACIAN_OF_GAUSSIAN_5x5, LAPLACIAN_OF_GAUSSIAN_7x7, LAPLACIAN_OF_GAUSSIAN_9x9, uriVL::LAPLACIAN_SOBEL_FORM_1, LAPLACIAN_SOBEL_FORM_1_MENU, uriVL::LAPLACIAN_SOBEL_FORM_2, LAPLACIAN_SOBEL_FORM_2_MENU, uriVL::LAPLACIAN_SOBEL_FORM_3, LAPLACIAN_SOBEL_FORM_3_MENU, LOWER_LEFT, QUIT_APPL, TOGGLE_COLORED_LAPLACIAN, and TOGGLE_ZERO_CROSSINGS.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_APPL:
             cleanupAndQuit(0);
             break;
         case LAPLACIAN_SOBEL_FORM_1_MENU:
         case LAPLACIAN_SOBEL_FORM_2_MENU:
         case LAPLACIAN_SOBEL_FORM_3_MENU:
             ImageLaplacian_Sobel *laplaceSobel;
             if (value == LAPLACIAN_SOBEL_FORM_1_MENU)
                 laplaceSobel = new ImageLaplacian_Sobel(LAPLACIAN_SOBEL_FORM_1);
             else if (value == LAPLACIAN_SOBEL_FORM_2_MENU)
                 laplaceSobel = new ImageLaplacian_Sobel(LAPLACIAN_SOBEL_FORM_2);
             else        //if (value == LAPLACIAN_SOBEL_FORM_3_MENU)
                 laplaceSobel = new ImageLaplacian_Sobel(LAPLACIAN_SOBEL_FORM_3);
             laplaceSobel->applyInto(gSmoothedImg, gLplcImgSobel);
             gLplcImg = gLplcImgSobel;
             delete laplaceSobel;
             ZeroCrossingDetector::applyInto_st(gLplcImgSobel, gZeroCrossImg);
             unsigned char colorChoice[3][3];
             colorChoice[0][0] = 0;
             colorChoice[0][1] = 255;
             colorChoice[0][2] = 0;
             colorChoice[1][0] = 0;
             colorChoice[1][1] = 0;
             colorChoice[1][2] = 255;
             colorChoice[2][0] = 255;
             colorChoice[2][1] = 0;
             colorChoice[2][2] = 0;
             ZeroCrossingDetector::showSignAsColor(gLplcImgSobel, gColoredLaplacian, colorChoice);
             if (gDisplayZeroCrossings)
                 gImageDisplayed[LOWER_LEFT] = gZeroCrossImg;
             else
                 gImageDisplayed[LOWER_LEFT] = gLplcImg;
            glutSetWindow(gMainWindow);
            glutPostRedisplay();
            break;
         case LAPLACIAN_OF_GAUSSIAN_5x5:
         case LAPLACIAN_OF_GAUSSIAN_7x7:
         case LAPLACIAN_OF_GAUSSIAN_9x9:
         case LAPLACIAN_OF_GAUSSIAN_11x11:
         case LAPLACIAN_OF_GAUSSIAN_13x13:
         case LAPLACIAN_OF_GAUSSIAN_21x21:
             //  apply the Laplacian filter to the image
             ImageLaplacian_Gaussian_F *laplaceGauss;
             laplaceGauss = new ImageLaplacian_Gaussian_F((int) value);
             laplaceGauss->applyInto(gSmoothedImg, gLplcImgGauss);
             gLplcImg = gLplcImgGauss;
             delete laplaceGauss;
             ZeroCrossingDetector::applyInto_st(gLplcImgGauss, gZeroCrossImg);
             unsigned char colorChoice2[3][3];
             colorChoice2[0][0] = 0;
             colorChoice2[0][1] = 255;
             colorChoice2[0][2] = 0;
             colorChoice2[1][0] = 0;
             colorChoice2[1][1] = 0;
             colorChoice2[1][2] = 255;
             colorChoice2[2][0] = 255;
             colorChoice2[2][1] = 0;
             colorChoice2[2][2] = 0;
             ZeroCrossingDetector::showSignAsColor(gLplcImgGauss, gColoredLaplacian, colorChoice2);
             if (gDisplayZeroCrossings)
                 gImageDisplayed[LOWER_LEFT] = gZeroCrossImg;
             else
                 gImageDisplayed[LOWER_LEFT] = gLplcImg;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         //      Toggle zero crossing display
         case TOGGLE_ZERO_CROSSINGS:
             gDisplayZeroCrossings = !gDisplayZeroCrossings;
             gDisplayColoredLaplacian = false;
             if (gDisplayZeroCrossings)
                 gImageDisplayed[LOWER_LEFT] = gZeroCrossImg;
             else
                 gImageDisplayed[LOWER_LEFT] = gLplcImg;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         //      Toggle colored Laplacian display
         case TOGGLE_COLORED_LAPLACIAN:
             gDisplayColoredLaplacian = !gDisplayColoredLaplacian;
             gDisplayZeroCrossings = false;
             if (gDisplayColoredLaplacian)
                 gImageDisplayed[LOWER_LEFT] = gColoredLaplacian;
             else
                 gImageDisplayed[LOWER_LEFT] = gLplcImg;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 662 of file edgePixels.cpp.
References uriVL::ImageGradient_Gaussian_F::applyInto(), cleanupAndQuit(), COARSER_VECT_RESOLUTION, uriVL::HistogramCalculator::computeHistogram(), FINER_VECT_RESOLUTION, uriVL::VectorField::forceRasterUpdate(), gCannyRas, gCurrentFieldRes, uriVL::RasterImage_gray::getGray2D(), uriVL::LabelRaster::getLabel2D(), uriVL::VectorField::getNormAsRasterImage(), gGradientNorm, gImageHeight, gImageWidth, gMainWindow, gMyGradient, gMyImage, gNonMaxSupprGrad, gNonMaxSupprGradNorm, GoG, GoG_11x11, GoG_13x13, GoG_21x21, GoG_3x3, GoG_5x5, GoG_7x7, GoG_9x9, grad, gradComputed, HYST_THRESH_GoG, HYST_THRESH_NoGoG, LOWER_RIGHT, NONMAX_SUPPR_GoG, NONMAX_SUPPR_NoGoG, NORM_GoG, ORIGINAL_IMAGE, QUIT_APPL, uriVL::R_W_ACCESS, uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), and uriVL::VectorField::setVectResolution().
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_APPL:
             cleanupAndQuit(0);
             break;
         //---------------------------------------------------------------
         //  "operator" menu selections
         //---------------------------------------------------------------
         //  Computation of gradient of gaussian for gray-level image
         case GoG_3x3:
         case GoG_5x5:
         case GoG_7x7:
         case GoG_9x9:
         case GoG_11x11:
         case GoG_13x13:
         case GoG_21x21:
                 {
             //  apply the gradient filter to the image
             ImageGradient_Gaussian_F    *grad;
             grad = new ImageGradient_Gaussian_F((int) value);
             grad->applyInto(gImgGray, gMyGradient);
             delete grad;
             gMyGradient->setDrawValidDataFrame(true);
             gMyGradient->setFrameColor(0.f, 0.f, 1.f);
             gradComputed = true;
             //
             //  also get the gradient's norm as a rasterimage
             gMyGradient->getNormAsRasterImage(gGradientNorm);
             //
             //  apply a nonmaximum suppression
             NonMaximumSuppressor::applyInto_st(gMyGradient, gNonMaxSupprGrad);
             gNonMaxSupprGradNorm = gNonMaxSupprGrad->getNormAsRasterImage(R_W_ACCESS);
             //
             //  And then apply hysteresis thresholding
             HistogramCalculator *histCalc;
             histCalc = new HistogramCalculator();
             histCalc->computeHistogram(gImgGray);
                         HysteresisLabeler::applyInto(500,100,gNonMaxSupprGrad,gLabel);
                         unsigned char *const*canny = gCannyRas->getGray2D(R_W_ACCESS);
                         char const*const* label = gLabel->getLabel2D();
                         for (int i = 0; i < gImageHeight; i++)
{
                                 for (int j = 0; j < gImageWidth; j++)
{
                                         canny[i][j] = label[i][j] == 0 ? 0 : (unsigned char) 255;
                                 }
                         }
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
                 }break;
         //---------------------------------------------------------------
         //  Selection of background image (below gradient vector field)
         //---------------------------------------------------------------
         case ORIGINAL_IMAGE:
             gImageDisplayed[LOWER_RIGHT] = gMyImage;
             glutSetWindow(gMainWindow);
             glutPostRedisplay();
             break;
         case NORM_GoG:
             if (gradComputed)
             {
                 gImageDisplayed[LOWER_RIGHT] = gGradientNorm;
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         case NONMAX_SUPPR_NoGoG:
             if (gradComputed)
             {
                 gImageDisplayed[LOWER_RIGHT] = gNonMaxSupprGradNorm;
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         case HYST_THRESH_NoGoG:
             if (gradComputed)
             {
                                 gImageDisplayed[LOWER_RIGHT] = gCannyRas;
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         //---------------------------------------------------------------
         //  Selection of gradient vector field to display
         //---------------------------------------------------------------
         case GoG:
             if (gradComputed)
             {
                 gVFieldDisplayed[LOWER_RIGHT] = gMyGradient;
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         case NONMAX_SUPPR_GoG:
             if (gradComputed)
             {
                 gVFieldDisplayed[LOWER_RIGHT] = gNonMaxSupprGrad;
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         case HYST_THRESH_GoG:
             if (gradComputed)
             {
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         //      coarser vector field resolution
         case COARSER_VECT_RESOLUTION:
             if (gradComputed)
             {
                 if (gCurrentFieldRes < 60)
                     gCurrentFieldRes += 5;
                 gVFieldDisplayed[LOWER_RIGHT]->setVectResolution(gCurrentFieldRes);
                 gVFieldDisplayed[LOWER_RIGHT]->forceRasterUpdate();
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         //      finer vector field resolution
         case FINER_VECT_RESOLUTION:
             if (gradComputed)
             {
                 if (gCurrentFieldRes > 10)
                     gCurrentFieldRes -= 5;
                 gVFieldDisplayed[LOWER_RIGHT]->setVectResolution(gCurrentFieldRes);
                 gVFieldDisplayed[LOWER_RIGHT]->forceRasterUpdate();
                 glutSetWindow(gMainWindow);
                 glutPostRedisplay();
             }
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 479 of file edgePixels.cpp.
References cleanupAndQuit(), and QUIT_APPL.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_APPL:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myReshape (int w, int h)
Definition at line 433 of file edgePixels.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 452 of file edgePixels.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const int COARSER_VECT_RESOLUTION = 71
Definition at line 140 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const string filePath = gray_dir + "Lena_256x256.tga"
Definition at line 81 of file edgePixels.cpp.
Referenced by loadImage().
const int FINER_VECT_RESOLUTION = 72
Definition at line 141 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
RasterImage_gray* gCannyRas = NULL
Definition at line 234 of file edgePixels.cpp.
Referenced by myMenu3().
RasterImage_RGBa* gColoredLaplacian = NULL
Definition at line 235 of file edgePixels.cpp.
Referenced by myMenu2().
int gCurrentFieldRes = 30
Definition at line 209 of file edgePixels.cpp.
Referenced by myMenu3().
bool gDisplayColoredLaplacian = false
Definition at line 240 of file edgePixels.cpp.
Referenced by myMenu2().
bool gDisplayZeroCrossings = false
Definition at line 239 of file edgePixels.cpp.
Referenced by myMenu2().
bool gDrawStuff = false
Definition at line 215 of file edgePixels.cpp.
bool gDrawVectField = false
Definition at line 216 of file edgePixels.cpp.
RasterImage_gray_F* gGradientNorm = NULL
Definition at line 226 of file edgePixels.cpp.
Referenced by myMenu3().
RasterImage_gray* gHistoThresholdedImg = NULL
Definition at line 229 of file edgePixels.cpp.
RasterImage* gImageDisplayed[kNbSubwindows] = {NULL, NULL, NULL, NULL}
Definition at line 242 of file edgePixels.cpp.
int gImageHeight = kDefaultHeight
Definition at line 207 of file edgePixels.cpp.
Referenced by myMenu3().
unsigned char gImageTreshold = 100
Definition at line 218 of file edgePixels.cpp.
int gImageWidth = kDefaultWidth
Definition at line 206 of file edgePixels.cpp.
Referenced by myMenu3().
RasterImage_gray* gImgGray = NULL
Definition at line 221 of file edgePixels.cpp.
Referenced by loadImage(), and myMenu1().
bool gInitDone = false
Definition at line 214 of file edgePixels.cpp.
Referenced by myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
LabelRaster* gLabel = NULL
Definition at line 236 of file edgePixels.cpp.
RasterImage_gray_F* gLplcImg = NULL
Definition at line 231 of file edgePixels.cpp.
Referenced by myMenu2().
RasterImage_gray_F* gLplcImgGauss = NULL
Definition at line 233 of file edgePixels.cpp.
Referenced by myMenu2().
RasterImage_gray_F* gLplcImgSobel = NULL
Definition at line 232 of file edgePixels.cpp.
Referenced by myMenu2().
int gMainWindow
Definition at line 211 of file edgePixels.cpp.
Referenced by main(), myColorSubmenu(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myInit(), myMenu1(), myMenu2(), and myMenu3().
VectorField_F* gMyGradient = NULL
Definition at line 224 of file edgePixels.cpp.
Referenced by loadImage(), and myMenu3().
RasterImage* gMyImage = NULL
Definition at line 220 of file edgePixels.cpp.
Referenced by loadImage(), and myMenu3().
VectorField_F* gNonMaxSupprGrad = NULL
Definition at line 225 of file edgePixels.cpp.
Referenced by myMenu3().
RasterImage_gray_F* gNonMaxSupprGradNorm = NULL
Definition at line 228 of file edgePixels.cpp.
Referenced by myMenu3().
const int GoG = 61
Definition at line 132 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_11x11 = 11
Definition at line 128 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_13x13 = 13
Definition at line 129 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_21x21 = 21
Definition at line 130 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_3x3 = 3
Definition at line 124 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_5x5 = 5
Definition at line 125 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_7x7 = 7
Definition at line 126 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int GoG_9x9 = 9
Definition at line 127 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
bool gradComputed = false
Definition at line 238 of file edgePixels.cpp.
Referenced by myDisplay3(), and myMenu3().
RasterImage_gray_F* gSmoothedImg = NULL
Definition at line 223 of file edgePixels.cpp.
Referenced by myMenu1().
int gSubwindow[kNbSubwindows]
Definition at line 211 of file edgePixels.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
VectorField* gVFieldDisplayed[kNbSubwindows] = {NULL, NULL, NULL, NULL}
Definition at line 243 of file edgePixels.cpp.
int gWinHeight
Definition at line 204 of file edgePixels.cpp.
Referenced by main().
int gWinWidth
Definition at line 204 of file edgePixels.cpp.
Referenced by main().
RasterImage_gray* gZeroCrossImg = NULL
Definition at line 227 of file edgePixels.cpp.
Referenced by myMenu2().
const int HYST_THRESH_GoG = 63
Definition at line 134 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int HYST_THRESH_NoGoG = 54
Definition at line 138 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 149 of file edgePixels.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 155 of file edgePixels.cpp.
Referenced by myInit().
const int LAPLACIAN_OF_GAUSSIAN_11x11 = 11
Definition at line 116 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_OF_GAUSSIAN_13x13 = 13
Definition at line 117 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_OF_GAUSSIAN_21x21 = 21
Definition at line 118 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_OF_GAUSSIAN_5x5 = 5
Definition at line 113 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_OF_GAUSSIAN_7x7 = 7
Definition at line 114 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_OF_GAUSSIAN_9x9 = 9
Definition at line 115 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_SOBEL_FORM_1_MENU = 31
Definition at line 110 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_SOBEL_FORM_2_MENU = 32
Definition at line 111 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LAPLACIAN_SOBEL_FORM_3_MENU = 33
Definition at line 112 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int LOWER_LEFT = 2
Definition at line 100 of file edgePixels.cpp.
Referenced by loadImage(), myDisplay2(), myInit(), and myMenu2().
const int LOWER_RIGHT = 3
Definition at line 101 of file edgePixels.cpp.
Referenced by loadImage(), myDisplay3(), myInit(), and myMenu3().
const int NO_FILTER = 1
Definition at line 105 of file edgePixels.cpp.
Referenced by myInit(), and myMenu1().
const int NONMAX_SUPPR_GoG = 62
Definition at line 133 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int NONMAX_SUPPR_NoGoG = 53
Definition at line 137 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int NORM_GoG = 52
Definition at line 136 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int ORIGINAL_IMAGE = 51
Definition at line 107 of file edgePixels.cpp.
Referenced by myInit(), and myMenu3().
const int QUIT_APPL = 0
Definition at line 104 of file edgePixels.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int SEPARATOR = 1000
Definition at line 106 of file edgePixels.cpp.
Referenced by myInit().
const int TOGGLE_COLORED_LAPLACIAN = 55
Definition at line 121 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int TOGGLE_ZERO_CROSSINGS = 50
Definition at line 120 of file edgePixels.cpp.
Referenced by myInit(), and myMenu2().
const int UPPER_LEFT = 0
Definition at line 98 of file edgePixels.cpp.
Referenced by loadImage(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 99 of file edgePixels.cpp.
Referenced by loadImage(), myDisplay1(), myInit(), and myMenu1().