URIVisionLibrary: imageGradients.cpp File Reference
imageGradients.cpp File Reference
#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>
#include "ImageReader.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_gray_F.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "VectorField_I.h"
#include "VectorField_F.h"
#include "ImageGradient_Gaussian_F.h"
#include "ImageGradient_Sobel.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages 2
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void myKeyboard (unsigned char c, int x, int y)
void myInit (void)
void myIdle (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const string filePath = gray_dir + "Lena_256x256.tga"
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int GAUSSIAN = 0
const int SOBEL = 1
const int QUIT_MENU = 0
const int SEPARATOR = 1000
const int RESET_IMAGES_MENU = 1
const int COARSER_RES_MENU = 101
const int FINER_RES_MENU = 102
const int NORM_AS_BKGND_MENU = 50
const int GRAD_AVE_OF_COLOR_COMPONENTS_MENU = 60
const int GRAD_LARGEST_COLOR_COMPONENT_MENU = 61
const int APPLY_SOBEL_MENU = 3
short gWinWidth
short gWinHeight
short gImageWidth = kDefaultWidth
short gImageHeight = kDefaultHeight
short gCurrentFieldRes [2] = {30, 30}
int gMainWindow
int gSubwindow [kNbRowsSubwindows *kNbColsSubwindows]
bool gInitDone = false
bool gDrawStuff = false
bool gDrawVectField = false
unsigned char gImageTreshold = 100
RasterImage ** gMyImage = NULL
RasterImage_gray ** gGradientNorm = NULL
RasterImage ** gBackgroundImage = NULL
VectorField ** gMyGradient = NULL
bool gradComputed [2] = {false, false}
bool gradNormIsBackground [2] = {false, false}
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 72 of file imageGradients.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 73 of file imageGradients.cpp.
#define kDefaultWidth 256
Definition at line 74 of file imageGradients.cpp.
#define kMaxWindowHeight 640
Definition at line 76 of file imageGradients.cpp.
#define kMaxWindowWidth 900
Definition at line 75 of file imageGradients.cpp.
#define kNbBckgndCols 5
Definition at line 160 of file imageGradients.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 68 of file imageGradients.cpp.
Referenced by main().
#define kNbImages 2
Definition at line 70 of file imageGradients.cpp.
Referenced by loadImage().
#define kNbRowsSubwindows 2
Definition at line 67 of file imageGradients.cpp.
Referenced by main().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 69 of file imageGradients.cpp.
Referenced by main(), and myInit().
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 205 of file imageGradients.cpp.
Referenced by loadImage(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void initializeQTEnvironment (void)
Definition at line 181 of file imageGradients.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 220 of file imageGradients.cpp.
References cleanupAndQuit(), filePath, GAUSSIAN, uriVL::ImageReader::getFrame(), kNbImages, myReader, SOBEL, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     ImageReader myReader(const_cast<char*>(filePath.c_str()));
     gMyImage = new RasterImage*[kNbImages];
     //-------------------------------------------------------------
     //  We read Image 0 from a file
     //-------------------------------------------------------------
     gMyImage[UPPER_LEFT] = myReader.getFrame(true);
     if (gMyImage[UPPER_LEFT] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath << endl;
         cleanupAndQuit(-1);
     }
     //  Image 1 is just Image 0 converted to gray level
     gMyImage[UPPER_RIGHT] = new RasterImage_gray(gMyImage[UPPER_LEFT]);
     gBackgroundImage = new RasterImage*[2];
     gBackgroundImage[GAUSSIAN] = gMyImage[UPPER_RIGHT];
     gBackgroundImage[SOBEL] = gMyImage[UPPER_RIGHT];
     gMyGradient = new VectorField*[2];
     gMyGradient[GAUSSIAN] = new VectorField_F(gMyImage[UPPER_RIGHT]->getBoundRect());
     gMyGradient[SOBEL] = new VectorField_I(gMyImage[UPPER_RIGHT]->getBoundRect());
     gGradientNorm = new RasterImage_gray*[2];
     gGradientNorm[GAUSSIAN] = gGradientNorm[SOBEL] = NULL;
 }
int main (int argc, char ** argv)
Definition at line 699 of file imageGradients.cpp.
References cleanupAndQuit(), uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, loadImage(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myInit(), myKeyboard(), myReshape(), setupCamera(), and UPPER_LEFT.
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() = {myDisplay0, myDisplay1,
                                                     myDisplay2, myDisplay3};
    try
    {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
         initializeQTEnvironment();
         //      I load my images
         loadImage();
         int     imgHeight = gMyImage[UPPER_LEFT]->getHeight(),
             imgWidth = gMyImage[UPPER_LEFT]->getWidth();
         //      I inform all drawable objects of the dimensions of their subwindow
         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
         //      I initialize my window's dimensions
         gWinHeight = kNbRowsSubwindows * (imgHeight + kBorder) + kBorder;
         gWinWidth = kNbColsSubwindows * (imgWidth + kBorder) + kBorder;
         glutInitWindowSize(gWinWidth,gWinHeight);
         gMainWindow = glutCreateWindow("Image Gradients Demo");
         glutKeyboardFunc(myKeyboard);
         glutDisplayFunc(myDisplayMain);
         glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
         glClearColor(0.f, 0.f, 0.f, 1.f);
         winID = 0;
         glutSetWindow(gMainWindow);
         for (int i=0; i<kNbRowsSubwindows; i++)
             for (int j=0; j<kNbColsSubwindows; j++)
             {
                 gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                         j*(imgWidth + kBorder) + kBorder,
                                                         i*(imgHeight + kBorder) + kBorder,
                                                         imgWidth, imgHeight);
                 //      I don't need to do this.  I just set a different "clear" color for
                 //      each subwindow.
                 backColor = kBackgroundColor[winID];
                 glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
                 //      This *has* to be defined:  a "display" callback function for each subwindow
                 glutDisplayFunc(displayFuncTable[winID++]);
                 glutKeyboardFunc(myKeyboard);
                 //      This calls maps "world" coordinates to "screen" coordinates.
                 //      In this particular case I make them coincide.
                 setupCamera(imgWidth, imgHeight);
                 //
                 glutSetWindow(gMainWindow);
             }
         myInit();
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
         glutMainLoop();
         cleanupAndQuit(0);
     }
     catch (uriVL::ErrorReport & e)
         {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
         return 0;
 }
void myColorSubmenu (int value)
Definition at line 590 of file imageGradients.cpp.
References gMainWindow, kBackgroundColor, and kNbBckgndCols.
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 275 of file imageGradients.cpp.
References gInitDone, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[UPPER_LEFT]->render();
     }
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 291 of file imageGradients.cpp.
References gInitDone, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage[UPPER_RIGHT]->render();
     }
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 307 of file imageGradients.cpp.
References GAUSSIAN, gInitDone, gradComputed, gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
         gBackgroundImage[GAUSSIAN]->render(true);
     if (gradComputed[GAUSSIAN])
         gMyGradient[GAUSSIAN]->render(true);
     glutSwapBuffers();
 }
void myDisplay3 (void)
Definition at line 324 of file imageGradients.cpp.
References gInitDone, gradComputed, gSubwindow, LOWER_RIGHT, uriVL::DrawableObject2D::render(), and SOBEL.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
         gBackgroundImage[SOBEL]->render(true);
     if (gradComputed[SOBEL])
         gMyGradient[SOBEL]->render(true);
     glutSwapBuffers();
 }
void myDisplayMain (void)
Definition at line 260 of file imageGradients.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 688 of file imageGradients.cpp.
References gInitDone, and gMainWindow.
Referenced by main().
 {
         if (gInitDone)
         {
                 glutSetWindow(gMainWindow);
             glutPostRedisplay();
         }
 }
void myInit (void)
Definition at line 607 of file imageGradients.cpp.
References APPLY_SOBEL_MENU, COARSER_RES_MENU, FINER_RES_MENU, gInitDone, gMainWindow, gSubwindow, kBckgndColStr, kNbBckgndCols, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), NORM_AS_BKGND_MENU, QUIT_MENU, SEPARATOR, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[kNbSubwindows], colorSubmenu, gaussMenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.f, 0.f, 0.f, 1.f);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for upper-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-left quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     gaussMenu = glutCreateMenu(myMenu2);
     glutAddMenuEntry("3x3 gradient of Gaussian", 3);
     glutAddMenuEntry("5x5 gradient of Gaussian", 5);
     glutAddMenuEntry("7x7 gradient of Gaussian", 7);
     glutAddMenuEntry("9x9 gradient of Gaussian", 9);
     glutAddMenuEntry("11x11 gradient of Gaussian", 11);
     glutAddMenuEntry("21x21 gradient of Gaussian", 21);
     //
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Apply Filter", gaussMenu);
     glutAddMenuEntry("Coarser resolution", COARSER_RES_MENU);
     glutAddMenuEntry("Finer resolution", FINER_RES_MENU);
     glutAddMenuEntry("Toggle image-gradient's norm as background", NORM_AS_BKGND_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     //------------------------------------
     //  menus for lower-right quadrant
     //------------------------------------
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddMenuEntry("Apply Sobel image gradient", APPLY_SOBEL_MENU);
     glutAddMenuEntry("Coarser resolution", COARSER_RES_MENU);
     glutAddMenuEntry("Finer resolution", FINER_RES_MENU);
     glutAddMenuEntry("Toggle image-gradient's norm as background", NORM_AS_BKGND_MENU);
     glutAddMenuEntry("-", SEPARATOR);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 373 of file imageGradients.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         default:
             break;
     }
 }
void myMenu0 (int value)
Definition at line 404 of file imageGradients.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 419 of file imageGradients.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 434 of file imageGradients.cpp.
References uriVL::ImageGradient_Gaussian_F::applyInto(), cleanupAndQuit(), COARSER_RES_MENU, FINER_RES_MENU, uriVL::VectorField::forceRasterUpdate(), GAUSSIAN, gCurrentFieldRes, uriVL::VectorField::getNormAsRasterImage(), gMainWindow, grad, gradComputed, gradNormIsBackground, NORM_AS_BKGND_MENU, QUIT_MENU, uriVL::DrawableObject2D::setColor(), uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), uriVL::VectorField::setVectResolution(), and UPPER_RIGHT.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         //  Gaussian filter width selection
         case 3:
         case 5:
         case 7:
         case 9:
         case 11:
         case 21: {
                                 //  apply the gradient filter to the image
                                 ImageGradient_Gaussian_F grad(static_cast<int>(value));
                                 grad.applyInto(gMyImage[UPPER_RIGHT], gMyGradient[GAUSSIAN]);
                                 gMyGradient[GAUSSIAN]->forceRasterUpdate();
                                 gMyGradient[GAUSSIAN]->setDrawValidDataFrame(true);
                                 gMyGradient[GAUSSIAN]->setFrameColor(0.f, 0.f, 1.f);
                                 gMyGradient[GAUSSIAN]->setColor(0.f, 1.f, 1.f);
                                 gradComputed[GAUSSIAN] = true;
                                 //  also get the gradient's norm as a rasterimage
                                 //  The first time around, return a new RI_g_F, after that just write into
                                 //  the existing raster image
                                 if (gGradientNorm[GAUSSIAN] == NULL)
                                         gGradientNorm[GAUSSIAN] = new RasterImage_gray_F(gMyImage[UPPER_RIGHT]->getBoundRect());
                                 gMyGradient[GAUSSIAN]->getNormAsRasterImage(gGradientNorm[GAUSSIAN]);
             }
                         break;
         case NORM_AS_BKGND_MENU:
             if (gradComputed[GAUSSIAN])
             {
                 if (gradNormIsBackground[GAUSSIAN])
                 {
                     gBackgroundImage[GAUSSIAN] = gMyImage[UPPER_RIGHT];
                     gradNormIsBackground[GAUSSIAN] = false;
                 }
                 else
                 {
                     gBackgroundImage[GAUSSIAN] = gGradientNorm[0];
                     gradNormIsBackground[GAUSSIAN] = true;
                 }
             }
             break;
         //      coarser resolution
         case COARSER_RES_MENU:
             if (gradComputed[GAUSSIAN])
             {
                 if (gCurrentFieldRes[GAUSSIAN] < 60)
                     gCurrentFieldRes[GAUSSIAN] += 5;
                 gMyGradient[GAUSSIAN]->setVectResolution(gCurrentFieldRes[GAUSSIAN]);
                 gMyGradient[GAUSSIAN]->forceRasterUpdate();
             }
             break;
         //      finer resolution
         case FINER_RES_MENU:
             if (gradComputed[GAUSSIAN])
             {
                 if (gCurrentFieldRes[GAUSSIAN] > 10)
                     gCurrentFieldRes[GAUSSIAN] -= 5;
                 gMyGradient[GAUSSIAN]->setVectResolution(gCurrentFieldRes[GAUSSIAN]);
                 gMyGradient[GAUSSIAN]->forceRasterUpdate();
             }
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
 }
void myMenu3 (int value)
Definition at line 516 of file imageGradients.cpp.
References APPLY_SOBEL_MENU, uriVL::ImageGradient_Sobel::applyInto(), cleanupAndQuit(), COARSER_RES_MENU, FINER_RES_MENU, uriVL::VectorField::forceRasterUpdate(), gCurrentFieldRes, uriVL::VectorField::getNormAsRasterImage(), gMainWindow, grad, gradComputed, gradNormIsBackground, NORM_AS_BKGND_MENU, QUIT_MENU, uriVL::DrawableObject2D::setColor(), uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), uriVL::VectorField::setVectResolution(), SOBEL, and UPPER_RIGHT.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         case APPLY_SOBEL_MENU: {
                                 //  apply the gradient filter to the image
                                 ImageGradient_Sobel grad;
                                 grad.applyInto(gMyImage[UPPER_RIGHT], gMyGradient[SOBEL]);
                                 gMyGradient[SOBEL]->forceRasterUpdate();
                                 gMyGradient[SOBEL]->setDrawValidDataFrame(true);
                                 gMyGradient[SOBEL]->setFrameColor(0.f, 0.f, 1.f);
                                 gMyGradient[SOBEL]->setColor(0.f, 1.f, 1.f);
                                 gradComputed[SOBEL] = true;
                                 //  also get the gradient's norm as a rasterimage
                                 //  The first time around, return a new RI_g_F, after that just write into
                                 //  the existing raster image
                                 if (gGradientNorm[SOBEL] == NULL)
                                         gGradientNorm[SOBEL] = new RasterImage_gray_F(gMyImage[UPPER_RIGHT]->getBoundRect());
                                 gMyGradient[SOBEL]->getNormAsRasterImage(gGradientNorm[SOBEL]);
             }
                         break;
         case NORM_AS_BKGND_MENU:
             if (gradComputed[SOBEL])
                 if (gradNormIsBackground[SOBEL])
                 {
                     gBackgroundImage[SOBEL] = gMyImage[UPPER_RIGHT];
                     gradNormIsBackground[SOBEL] = false;
                 }
                 else
                 {
                     gBackgroundImage[SOBEL] = gGradientNorm[1];
                     gradNormIsBackground[SOBEL] = true;
                 }
             break;
         //      coarser resolution
         case COARSER_RES_MENU:
             if (gradComputed[SOBEL])
             {
                 if (gCurrentFieldRes[SOBEL] < 60)
                     gCurrentFieldRes[SOBEL] += 5;
                 gMyGradient[SOBEL]->setVectResolution(gCurrentFieldRes[SOBEL]);
                 gMyGradient[SOBEL]->forceRasterUpdate();
             }
             break;
         //      finer resolution
         case FINER_RES_MENU:
             if (gradComputed[SOBEL])
             {
                 if (gCurrentFieldRes[SOBEL] > 10)
                     gCurrentFieldRes[SOBEL] -= 5;
                 gMyGradient[SOBEL]->setVectResolution(gCurrentFieldRes[SOBEL]);
                 gMyGradient[SOBEL]->forceRasterUpdate();
             }
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
         glutSetWindow(gMainWindow);
         glutPostRedisplay();
 }
void myMenuMain (int value)
Definition at line 388 of file imageGradients.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         // This is not happening.  This is not happening. This is not...
         default:
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myReshape (int w, int h)
Definition at line 342 of file imageGradients.cpp.
Referenced by main().
 {
     if (gMyImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
void setupCamera (int w, int h)
Definition at line 361 of file imageGradients.cpp.
Referenced by main().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const int APPLY_SOBEL_MENU = 3
Definition at line 98 of file imageGradients.cpp.
Referenced by myInit(), and myMenu3().
const int COARSER_RES_MENU = 101
Definition at line 90 of file imageGradients.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
const string color_dir = COLOR_DIR_PATH
Definition at line 58 of file imageGradients.cpp.
const string filePath = gray_dir + "Lena_256x256.tga"
Definition at line 61 of file imageGradients.cpp.
Referenced by loadImage().
const int FINER_RES_MENU = 102
Definition at line 91 of file imageGradients.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
const int GAUSSIAN = 0
Definition at line 83 of file imageGradients.cpp.
Referenced by loadImage(), myDisplay2(), and myMenu2().
RasterImage** gBackgroundImage = NULL
Definition at line 151 of file imageGradients.cpp.
short gCurrentFieldRes[2] = {30, 30}
Definition at line 138 of file imageGradients.cpp.
Referenced by myMenu2(), and myMenu3().
bool gDrawStuff = false
Definition at line 144 of file imageGradients.cpp.
bool gDrawVectField = false
Definition at line 145 of file imageGradients.cpp.
RasterImage_gray** gGradientNorm = NULL
Definition at line 150 of file imageGradients.cpp.
short gImageHeight = kDefaultHeight
Definition at line 136 of file imageGradients.cpp.
unsigned char gImageTreshold = 100
Definition at line 147 of file imageGradients.cpp.
short gImageWidth = kDefaultWidth
Definition at line 135 of file imageGradients.cpp.
bool gInitDone = false
Definition at line 143 of file imageGradients.cpp.
Referenced by myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myIdle(), and myInit().
int gMainWindow
Definition at line 140 of file imageGradients.cpp.
Referenced by main(), myColorSubmenu(), myDisplayMain(), myIdle(), myInit(), myMenu2(), and myMenu3().
VectorField** gMyGradient = NULL
Definition at line 152 of file imageGradients.cpp.
RasterImage** gMyImage = NULL
Definition at line 149 of file imageGradients.cpp.
const int GRAD_AVE_OF_COLOR_COMPONENTS_MENU = 60
Definition at line 95 of file imageGradients.cpp.
const int GRAD_LARGEST_COLOR_COMPONENT_MENU = 61
Definition at line 96 of file imageGradients.cpp.
bool gradComputed[2] = {false, false}
Definition at line 153 of file imageGradients.cpp.
Referenced by myDisplay2(), myDisplay3(), myMenu2(), and myMenu3().
bool gradNormIsBackground[2] = {false, false}
Definition at line 154 of file imageGradients.cpp.
Referenced by myMenu2(), and myMenu3().
const string gray_dir = GRAY_DIR_PATH
Definition at line 59 of file imageGradients.cpp.
int gSubwindow[kNbRowsSubwindows *kNbColsSubwindows]
Definition at line 140 of file imageGradients.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
short gWinHeight
Definition at line 133 of file imageGradients.cpp.
Referenced by main().
short gWinWidth
Definition at line 133 of file imageGradients.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 162 of file imageGradients.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 168 of file imageGradients.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 80 of file imageGradients.cpp.
Referenced by myDisplay2(), and myInit().
const int LOWER_RIGHT = 3
Definition at line 81 of file imageGradients.cpp.
Referenced by myDisplay3(), and myInit().
const int NORM_AS_BKGND_MENU = 50
Definition at line 93 of file imageGradients.cpp.
Referenced by myInit(), myMenu2(), and myMenu3().
const int QUIT_MENU = 0
Definition at line 86 of file imageGradients.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int RESET_IMAGES_MENU = 1
Definition at line 88 of file imageGradients.cpp.
const int SEPARATOR = 1000
Definition at line 87 of file imageGradients.cpp.
Referenced by myInit().
const int SOBEL = 1
Definition at line 84 of file imageGradients.cpp.
Referenced by loadImage(), myDisplay3(), and myMenu3().
const int UPPER_LEFT = 0
Definition at line 78 of file imageGradients.cpp.
Referenced by loadImage(), main(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 79 of file imageGradients.cpp.
Referenced by loadImage(), myDisplay1(), myInit(), myMenu2(), and myMenu3().