URIVisionLibrary: main_movieVideoHybrid.cpp File Reference
main_movieVideoHybrid.cpp File Reference
#include <string>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ErrorReport.h"
#include "RasterImage.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray.h"
#include "FrameGrabber.h"
#include "MoviePlayer.h"
#include "Demos/dataFolderPath.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define READ_IN_GRAY_IMAGE 0
#define DEMO_LIVE_INPUT 1
#define DEMO_MOVIE_INPUT 0
#define DEMO_ONE_PANEL_OUTPUT 1
#define DEMO_FOUR_PANEL_OUTPUT 0
Enumerations
enum Quadrant {
UPPER_LEFT = 0,
UPPER_RIGHT = 1,
LOWER_LEFT = 2,
LOWER_RIGHT = 3
}
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void myDisplay (void)
void setupOrthoCam (int w, int h)
void myIdle (void)
void myIdleDone (void)
void myReshape (int w, int h)
void myKeyboard (unsigned char c, int x, int y)
void myMouse (int button, int state, int ix, int iy)
void initializeApplication (void)
void initGlut (void)
int main (int argc, char **argv)
Variables
const string movie_dir = MOVIE_DIR_PATH
const int IMG_WIDTH = 640
const int IMG_HEIGHT = 480
long gFrameIndex = 0
const ImageRect * gInputRect = NULL
bool gInitDone = false
RasterImage_RGBa * gInputImage = NULL
FrameGrabber * gMyGrabber = NULL
VideoSource * gMySource = NULL
int gWinWidth
int gWinHeight
int gMainWindow
const float SCALE_FACTOR = 1.0f
const int kNbRowsSubwindows = 1
const int kNbColsSubwindows = 1
Macro Definition Documentation
#define DEMO_FOUR_PANEL_OUTPUT 0
Definition at line 79 of file main_movieVideoHybrid.cpp.
#define DEMO_LIVE_INPUT 1
Definition at line 72 of file main_movieVideoHybrid.cpp.
#define DEMO_MOVIE_INPUT 0
Definition at line 73 of file main_movieVideoHybrid.cpp.
#define DEMO_ONE_PANEL_OUTPUT 1
Definition at line 78 of file main_movieVideoHybrid.cpp.
#define READ_IN_GRAY_IMAGE 0
Definition at line 67 of file main_movieVideoHybrid.cpp.
#define READ_IN_RGB_IMAGE 0
Definition at line 66 of file main_movieVideoHybrid.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 65 of file main_movieVideoHybrid.cpp.
Enumeration Type Documentation
enum Quadrant
Enumerator
UPPER_LEFT
UPPER_RIGHT
LOWER_LEFT
LOWER_RIGHT
Definition at line 114 of file main_movieVideoHybrid.cpp.
               { UPPER_LEFT = 0,
                                 UPPER_RIGHT = 1,
                                 LOWER_LEFT = 2,
                                 LOWER_RIGHT = 3
 };
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 254 of file main_movieVideoHybrid.cpp.
Referenced by main(), and myKeyboard().
 {
         #if URIVL_USE_QUICKTIME
             // terminate the QuickTime Media Layer
             ExitMovies();
             #if URIVL_OS_WIN32
                 TerminateQTML();
             #endif
         #endif
     std::exit(exitCode);
 }
void initGlut (void)
Definition at line 303 of file videoGrabbing_main.cpp.
References IMG_HEIGHT, IMG_WIDTH, myDisplay(), myIdle(), myKeyboard(), myReshape(), and setupOrthoCam().
Referenced by main().
 {
                 glClearColor(0.f, 0.f, 0.f, 1.f);
                 glutDisplayFunc(myDisplay);
                 setupOrthoCam(IMG_WIDTH, IMG_HEIGHT);
                 glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
                 glutKeyboardFunc(myKeyboard);
 }
void initializeApplication (void)
Definition at line 499 of file main_movieVideoHybrid.cpp.
References gInitDone, gMyGrabber, gMyPlayer, IMG_HEIGHT, IMG_WIDTH, and uriVL::DrawableObject2D::setValidRect().
Referenced by main().
 {
         #if DEMO_LIVE_INPUT
                 gInputRect = new ImageRect(0, 0, IMG_WIDTH, IMG_HEIGHT);
                 gMyGrabber = new FrameGrabber(gInputRect);
                 gMyGrabber->setSource();
                 gMySource = gMyGrabber;
         #else
         gMyPlayer = new MoviePlayer();
         gMyPlayer->setSource();
                 gMySource = gMyPlayer;
                 gInputRect = gMyPlayer->getRect();
         #endif
         #if READ_IN_RGBA_IMAGE
                 gInputImage = new RasterImage_RGBa(gInputRect);
         #elif READ_IN_RGB_IMAGE
                 gInputImage = new RasterImage_RGB(gInputRect);
         #else READ_IN_GRAY_IMAGE
                 gInputImage = new RasterImage_gray(gInputRect);
         #endif
         gInputImage->setValidRect(gInputRect);
         gInitDone = true;
 }
void initializeQTEnvironment (void)
Definition at line 225 of file main_movieVideoHybrid.cpp.
References FAIL_CONDITION, uriVL::kEnterMoviesError, and uriVL::kQuickTimeNotInstalled.
Referenced by main().
 {
         #if URIVL_USE_QUICKTIME
                 printf("using quicktime\n");
             OSErr       myErr = noErr;
             #if URIVL_OS_WIN32
                 myErr = InitializeQTML(kQTMLNoIdleEvents);
             #else
                 #if URIVL_OS_MACOS
                     long        myAttrs;
                     myErr = Gestalt(gestaltQuickTime, &myAttrs);
                 #endif
             #endif
             FAIL_CONDITION(     myErr != noErr,
                             kQuickTimeNotInstalled,
                             "QuickTime is not installed on this computer");
             myErr = EnterMovies();
             FAIL_CONDITION(     myErr != noErr,
                             kEnterMoviesError,
                             "Problems with EnterMovies, returning errors (exit)");
          #else
                 //do nothing?
          #endif
 }
int main (int argc, char ** argv)
Definition at line 531 of file main_movieVideoHybrid.cpp.
References cleanupAndQuit(), uriVL::ImageRect::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::ImageRect::getWidth(), gInputRect, gMainWindow, gMyGrabber, gSubwindow, gWinHeight, gWinWidth, initializeApplication(), initializeQTEnvironment(), kBorder, kNbColsSubwindows, kNbRowsSubwindows, myDisplay(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myIdle(), myKeyboard(), myMouse(), myReshape(), SCALE_FACTOR, and setupOrthoCam().
 {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA | GLUT_DEPTH);
     try {
                 initializeQTEnvironment();
                 initializeApplication();
                 //      I initialize my window's dimensions
                 #if DEMO_FOUR_PANEL_OUTPUT
                         int imgHeight = static_cast<int>(SCALE_FACTOR * gInputRect->getHeight()),
                                 imgWidth = static_cast<int>(SCALE_FACTOR * gInputRect->getWidth());
                         DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
                         gWinHeight = 2 * imgHeight + 3 * kBorder;
                         gWinWidth = 2 * imgWidth + 3 * kBorder;
                 #else
                         gWinHeight = gInputRect->getHeight();
                         gWinWidth = gInputRect->getWidth();
                         DrawableObject2D::setDefaultWindowDimensions(gWinWidth, gWinHeight);
                 #endif
                 //      Create the Main Window and set up its callback functions
                 glutInitWindowSize(gWinWidth, gWinHeight);
                 gMainWindow = glutCreateWindow("Live/Canned Video Hybrid Demo");
                 glClearColor(0.1f, 0.3f, 0.3f, 1.f);
                 glutDisplayFunc(myDisplay);
                 setupOrthoCam(gWinWidth, gWinHeight);
                 glutReshapeFunc(myReshape);
                 glutIdleFunc(myIdle);
                 glutMouseFunc(myMouse);
                 glutKeyboardFunc(myKeyboard);
                 //      Then (if needed) create the 4 quadrant subwindows
                 #if DEMO_FOUR_PANEL_OUTPUT
                         void    (*displayFuncTable[])() = {myDisplay0, myDisplay1,
                                                                                            myDisplay2, myDisplay3};
                         int winID = 0;
                         glutSetWindow(gMainWindow);
                         for (int i=0; i<kNbRowsSubwindows; i++)
                                 for (int j=0; j<kNbColsSubwindows; j++)
{
                                         gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                                                                                         j*(imgWidth + kBorder) + kBorder,
                                                                                                                         i*(imgHeight + kBorder) + kBorder,
                                                                                                                         imgWidth, imgHeight);
                                         glClearColor(0.f, 0.f, 0.f, 1.f);
                                         //      This *has* to be defined:  a "display" callback function for each subwindow
                                         glutDisplayFunc(displayFuncTable[winID++]);
                                         glutMouseFunc(myMouse);
                                         glutKeyboardFunc(myKeyboard);
                                         //      This calls maps "world" coordinates to "screen" coordinates.
                                         //      In this particular case I make them coincide.
                                         setupOrthoCam(imgWidth, imgHeight);
                                         //
                                         glutSetWindow(gMainWindow);
                                 }
                 #endif
                 #if DEMO_LIVE_INPUT
                         gMyGrabber->start();
                 #endif
                 glutMainLoop();
                 #if DEMO_LIVE_INPUT
                         delete gInputRect;
                 #endif
                 cleanupAndQuit(0);
                 return 0;
         }
     catch (uriVL::ErrorReport & e) {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myDisplay (void)
Definition at line 311 of file main_movieVideoHybrid.cpp.
References gFrameIndex, gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and uriVL::DrawableObject2D::render().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
         #if DEMO_FOUR_PANEL_OUTPUT
                 myDisplay0();
                 myDisplay1();
                 myDisplay2();
                 myDisplay3();
         #else
                 if (gFrameIndex>0)
                 {
                         gInputImage->render( );
                 }
         #endif
     glutSwapBuffers();
 }
void myIdle (void)
Definition at line 282 of file main_movieVideoHybrid.cpp.
References uriVL::VideoSource::getFrame(), and gFrameIndex.
Referenced by main().
 {
     gMySource->getFrame(gInputImage);
         gFrameIndex++;
         cout << "frame " << gFrameIndex << endl;
         //  do something cool
     glutPostRedisplay();
 }
void myIdleDone (void)
Definition at line 300 of file main_movieVideoHybrid.cpp.
 {
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 458 of file main_movieVideoHybrid.cpp.
References cleanupAndQuit().
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
     }
     //    glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 479 of file main_movieVideoHybrid.cpp.
Referenced by main().
 {
     // stop start the playing of the images/movie in the display
     // if the left mouse button is clicked, do something
     if (state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
         }
 }
void myReshape (int w, int h)
Definition at line 443 of file main_movieVideoHybrid.cpp.
References gWinHeight, and gWinWidth.
Referenced by main().
 {
     if ((w != gWinWidth) || (h != gWinHeight))
         glutReshapeWindow(gWinWidth, gWinHeight);
     glutPostRedisplay();
 }
void setupOrthoCam (int w, int h)
Definition at line 427 of file main_movieVideoHybrid.cpp.
Referenced by main().
 {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
         glMatrixMode(GL_MODELVIEW);
         glLoadIdentity();
         glViewport(0, 0, w, h);
 }
Variable Documentation
long gFrameIndex = 0
Definition at line 159 of file main_movieVideoHybrid.cpp.
Referenced by myDisplay(), and myIdle().
bool gInitDone = false
Definition at line 161 of file main_movieVideoHybrid.cpp.
Referenced by initializeApplication().
RasterImage_RGBa* gInputImage = NULL
Definition at line 164 of file main_movieVideoHybrid.cpp.
const ImageRect* gInputRect = NULL
Definition at line 160 of file main_movieVideoHybrid.cpp.
Referenced by main().
int gMainWindow
Definition at line 187 of file main_movieVideoHybrid.cpp.
Referenced by main(), and myDisplay().
FrameGrabber* gMyGrabber = NULL
Definition at line 174 of file main_movieVideoHybrid.cpp.
Referenced by initializeApplication(), and main().
VideoSource* gMySource = NULL
Definition at line 179 of file main_movieVideoHybrid.cpp.
int gWinHeight
Definition at line 185 of file main_movieVideoHybrid.cpp.
Referenced by main(), and myReshape().
int gWinWidth
Definition at line 185 of file main_movieVideoHybrid.cpp.
Referenced by main(), and myReshape().
const int IMG_HEIGHT = 480
Definition at line 124 of file main_movieVideoHybrid.cpp.
Referenced by initializeApplication().
const int IMG_WIDTH = 640
Definition at line 123 of file main_movieVideoHybrid.cpp.
Referenced by initializeApplication().
const int kNbColsSubwindows = 1
Definition at line 209 of file main_movieVideoHybrid.cpp.
Referenced by main().
const int kNbRowsSubwindows = 1
Definition at line 208 of file main_movieVideoHybrid.cpp.
Referenced by main().
const string movie_dir = MOVIE_DIR_PATH
Definition at line 57 of file main_movieVideoHybrid.cpp.
Referenced by main().
const float SCALE_FACTOR = 1.0f
Definition at line 206 of file main_movieVideoHybrid.cpp.
Referenced by main().