URIVisionLibrary: main_GameOfLife.cpp File Reference
main_GameOfLife.cpp File Reference
#include <iostream>
#include <cmath>
#include "ImageReader.h"
#include "LabelRaster.h"
#include "ImageWriter.h"
#include "RasterImage_gray.h"
#include "RasterImage_gray_F.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RandomGenerator_C.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbImages 9
#define DISPLAY_FONT GLUT_BITMAP_HELVETICA_12
Typedefs
typedef enum GlutMenuSelect GlutMenuSelect
Enumerations
enum GlutMenuSelect {
QUIT_MENU = 0,
RESET_MENU,
SEPARATOR_MENU,
LIFE_B23_S3 = 10,
CORAL_B3_S45678,
MAZE_B3_S12345,
ASSIMILATION_B345_S4567,
AMOEBA_B357_S1358,
SEEDS_B2_
}
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImage (void)
void myDisplay (void)
void displayTextualInfo (const char *infoStr)
void myReshape (int w, int h)
void myMenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void resetCells (void)
void myInit (void)
void updateState (int val)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string kNameFile = color_dir + "mandrill_256x256.jpg"
RasterImage_RGBa * gInputImage = NULL
RasterImage_RGBa * gOutputImage = NULL
LabelRaster * gLabelOld = NULL
LabelRaster * gLabelNew = NULL
bool gInitDone = false
bool gRunningLife = false
const string RULE_STR []
const int NB_RANDOM_RATES = 10
const float RANDOM_RATE []
int gRandomRateIndex = 6
GlutMenuSelect gRule = LIFE_B23_S3
float gUt = 0.f
const unsigned int LOWER_BOUND_1_DT = 10
const unsigned int UPPER_BOUND_1_DT = 100
const unsigned int LOWER_BOUND_2_DT = UPPER_BOUND_1_DT
const unsigned int UPPER_BOUND_2_DT = 1000
const unsigned int LOWER_BOUND_3_DT = UPPER_BOUND_2_DT
const unsigned int UPPER_BOUND_3_DT = 10000
const unsigned int INCREMENT_1_DT = 10
const unsigned int INCREMENT_2_DT = 100
const unsigned int INCREMENT_3_DT = 1000
float gDt = 1000
const int FONT_HEIGHT = 12
const int TEXT_PADDING = 2
const float kTextColor [3] = {1.f, 1.f, 1.f}
const float kTextBackgroundColor [3] = {0.0f, 0.2f, 0.0f}
Macro Definition Documentation
#define DISPLAY_FONT GLUT_BITMAP_HELVETICA_12
Definition at line 137 of file main_GameOfLife.cpp.
Referenced by displayTextualInfo().
#define kNbImages 9
Definition at line 52 of file main_GameOfLife.cpp.
Typedef Documentation
typedef enum GlutMenuSelect GlutMenuSelect
Enumeration Type Documentation
enum GlutMenuSelect
Enumerator
QUIT_MENU
RESET_MENU
SEPARATOR_MENU
LIFE_B23_S3
CORAL_B3_S45678
MAZE_B3_S12345
ASSIMILATION_B345_S4567
AMOEBA_B357_S1358
SEEDS_B2_
Definition at line 87 of file main_GameOfLife.cpp.
                             {   QUIT_MENU = 0,
                                                                 RESET_MENU,
                                                                 SEPARATOR_MENU,
                                                                 //
                                                                 LIFE_B23_S3 = 10,
                                                                 CORAL_B3_S45678,
                                                                 MAZE_B3_S12345,
                                                                 ASSIMILATION_B345_S4567,
                                                                 AMOEBA_B357_S1358,
                                                                 SEEDS_B2_
 } GlutMenuSelect;
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 173 of file main_GameOfLife.cpp.
Referenced by loadImage(), main(), myKeyboard(), and myMenu().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
         #if __profile__
                 ProfilerDump("\pProfilerData");
                 ProfilerTerm();
         #endif
     #endif
     std::exit(exitCode);
 }
void displayTextualInfo (const char * infoStr)
Definition at line 497 of file main_GameOfLife.cpp.
References DISPLAY_FONT, FONT_HEIGHT, uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), kTextBackgroundColor, kTextColor, and TEXT_PADDING.
Referenced by myDisplay().
 {
     //-----------------------------------------------
     //  0.  get current material properties
     //-----------------------------------------------
     float oldAmb[4], oldDif[4], oldSpec[4], oldShiny;
     glGetMaterialfv(GL_FRONT, GL_AMBIENT, oldAmb);
     glGetMaterialfv(GL_FRONT, GL_DIFFUSE, oldDif);
     glGetMaterialfv(GL_FRONT, GL_SPECULAR, oldSpec);
     glGetMaterialfv(GL_FRONT, GL_SHININESS, &oldShiny);
     glPushMatrix();
     //-----------------------------------------------
     //  1.  Build the string to display <-- parameter
     //-----------------------------------------------
     int infoLn = strlen(infoStr);
     //-----------------------------------------------
     //  2.  Determine the string's length (in pixels)
     //-----------------------------------------------
     int textWidth = 0;
     for (int k=0; k<infoLn; k++)
         textWidth += glutBitmapWidth(DISPLAY_FONT, infoStr[k]);
     //  add a few pixels of padding
     textWidth += 2*TEXT_PADDING;
     //-----------------------------------------------
     //  3.  Clear background rectangle
     //-----------------------------------------------
         const int imgHeight = 3*gInputImage->getHeight()/2;
         const int imgWidth = 3*gInputImage->getWidth()/2;
         glColor3f(kTextBackgroundColor[0], kTextBackgroundColor[1], kTextBackgroundColor[2]);
     glBegin(GL_POLYGON);
         glVertex2i(0, imgHeight);
         glVertex2i(imgWidth, imgHeight);
         glVertex2i(imgWidth, imgHeight - FONT_HEIGHT - 4);
         glVertex2i(0, imgHeight - FONT_HEIGHT - 4);
     glEnd();
         glTranslatef(0.f, 0.f, 1.f);
     //-----------------------------------------------
     //  4.  Draw the string
     //-----------------------------------------------
     glColor3f(kTextColor[0], kTextColor[1], kTextColor[2]);
     int xPos = TEXT_PADDING,
         yPos = imgHeight - FONT_HEIGHT;
     for (int k=0; k<infoLn; k++)
     {
         glRasterPos2i(xPos, yPos);
         glutBitmapCharacter(DISPLAY_FONT, infoStr[k]);
         xPos += glutBitmapWidth(DISPLAY_FONT, infoStr[k]);
     }
     //-----------------------------------------------
     //  5.  Restore old material properties
     //-----------------------------------------------
         glMaterialfv(GL_FRONT, GL_AMBIENT, oldAmb);
         glMaterialfv(GL_FRONT, GL_DIFFUSE, oldDif);
         glMaterialfv(GL_FRONT, GL_SPECULAR, oldSpec);
         glMaterialf(GL_FRONT, GL_SHININESS, oldShiny);
     //-----------------------------------------------
     //  6.  Restore reference frame
     //-----------------------------------------------
     glPopMatrix();
 }
void initializeQTEnvironment (void)
Definition at line 149 of file main_GameOfLife.cpp.
Referenced by myInit().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImage (void)
Definition at line 192 of file main_GameOfLife.cpp.
References cleanupAndQuit(), uriVL::ImageReader::getFrame(), uriVL::LabelRaster::getLabel2D(), kNameFile, myReader, and uriVL::R_W_ACCESS.
Referenced by myInit().
 {
     //-------------------------------------------------------------
     //  Read image from a file
     //-------------------------------------------------------------
     //  I can create a reader by passing a file path
     ImageReader myReader(kNameFile.c_str());
     gInputImage = (RasterImage_RGBa*) myReader.getFrame(true);
         gOutputImage = new RasterImage_RGBa(gInputImage);
         gLabelOld = new LabelRaster(gInputImage->getHeight(), gInputImage->getWidth());
         gLabelNew = new LabelRaster(gInputImage->getHeight(), gInputImage->getWidth());
     if (gInputImage ==NULL)
     {
         cout << "Loading of image failed.";
         cleanupAndQuit(-1);
     }
         const int nbRows = gInputImage->getHeight();
         const int nbCols = gInputImage->getWidth();
         char *const* oldL = gLabelOld->getLabel2D(R_W_ACCESS);
         char *const* newL = gLabelNew->getLabel2D(R_W_ACCESS);
         for (int i=0; i<nbRows; i++)
         {
                 for (int j=0; j<nbCols; j++)
                 {
                         oldL[i][j] = newL[i][j] = static_cast<char>(1);
                 }
         }
 }
int main (int argc, char ** argv)
Definition at line 739 of file main_GameOfLife.cpp.
References cleanupAndQuit(), gDt, uriVL::DrawableObject2D::getHeight(), uriVL::ErrorReport::getMessage(), uriVL::DrawableObject2D::getWidth(), myDisplay(), myInit(), myKeyboard(), myMouse(), myReshape(), uriVL::DrawableObject2D::setRenderingScale(), and updateState().
 {
         try {
                 glutInit(&argc, argv);
                 glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
                 glutInitWindowSize(10, 30);
                 glutCreateWindow("Image IO & Display Demo");
                 //  defines glut callback functions that will interrupt the glut loop
                 glutDisplayFunc(myDisplay);
                 glutReshapeFunc(myReshape);
                 glutMouseFunc(myMouse);
                 glutKeyboardFunc(myKeyboard);
                 glutTimerFunc(gDt, updateState, 0);
                 //  Initializes QuickTime and loads the images
                 myInit();
                 //  Having read the images, I can now resize my window to the appropriate dimensions
                 gOutputImage->setRenderingScale(1.5f);
                 glutReshapeWindow(3*gInputImage->getWidth()/2,
                                                   3*gInputImage->getHeight()/2);
                 //  Enter infinite glut loop
                 glutMainLoop();
                 //  Normally this code should never be placed since the only way to leave the
                 //  glut loop is to quit
                 cleanupAndQuit(0);
         }
         catch (uriVL::ErrorReport & e)
         {
                 cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
                 return 1;
         }
     return 0;
 }
void myDisplay (void)
Definition at line 479 of file main_GameOfLife.cpp.
References displayTextualInfo(), gDt, gInitDone, gRandomRateIndex, gRule, RANDOM_RATE, uriVL::DrawableObject2D::render(), and RULE_STR.
Referenced by main().
 {
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
         gOutputImage->render( );
     //  Build the string to display
         char infoStr[256];
         sprintf(infoStr, "Rule %s, Gen. Prob. =  %f, Anim. period = %d ms",
                                                         RULE_STR[gRule-10].c_str(), RANDOM_RATE[gRandomRateIndex],
                                                         static_cast<int>(gDt));
         displayTextualInfo(infoStr);
     glutSwapBuffers();
 }
void myInit (void)
Definition at line 704 of file main_GameOfLife.cpp.
References AMOEBA_B357_S1358, ASSIMILATION_B345_S4567, CORAL_B3_S45678, gInitDone, initializeQTEnvironment(), LIFE_B23_S3, loadImage(), MAZE_B3_S12345, myMenu(), QUIT_MENU, RESET_MENU, SEEDS_B2_, and SEPARATOR_MENU.
Referenced by main().
 {
     initializeQTEnvironment();
     loadImage();
     glClearColor(0.f, 0.f, 0.f, 1.f);
     // Create Menus
     int menu, ruleSubmenu;
     //  Submenu for direct image selection
     //  This is to show that I can use the same function to handle all submenus
     //  as long as they have unique indexes.  Still, it is probably a good idea
     //  to break down menu handling into several manageable-size functions.
     ruleSubmenu = glutCreateMenu(myMenu);
     glutAddMenuEntry("Life: B3/S23", LIFE_B23_S3);
     glutAddMenuEntry("Coral: B3/S45678", CORAL_B3_S45678);
     glutAddMenuEntry("Maze: B3/S12345", MAZE_B3_S12345);
     glutAddMenuEntry("Assimilation: B345/S4567", ASSIMILATION_B345_S4567);
     glutAddMenuEntry("Amoeba: B357/S1358", AMOEBA_B357_S1358);
     glutAddMenuEntry("Seeds: B2/", SEEDS_B2_);
     // Main menu that the submenus are connected to
     menu = glutCreateMenu(myMenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddMenuEntry("Reset", RESET_MENU);
     glutAddMenuEntry("--", SEPARATOR_MENU);
     glutAddSubMenu("Rule", ruleSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 588 of file main_GameOfLife.cpp.
References cleanupAndQuit(), gDt, gRandomRateIndex, INCREMENT_1_DT, INCREMENT_2_DT, INCREMENT_3_DT, LOWER_BOUND_1_DT, LOWER_BOUND_2_DT, NB_RANDOM_RATES, resetCells(), UPPER_BOUND_1_DT, UPPER_BOUND_2_DT, and UPPER_BOUND_3_DT.
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
                 //      run simulation faster: decrement period
         case '.':
         case '>':
                         if ((gDt > LOWER_BOUND_1_DT) && (gDt <= UPPER_BOUND_1_DT))
                                 gDt -= INCREMENT_1_DT;
                         else if ((gDt > LOWER_BOUND_2_DT) && (gDt <= UPPER_BOUND_2_DT))
                                 gDt -= INCREMENT_2_DT;
                         else if (gDt < UPPER_BOUND_3_DT)
                                 gDt -= INCREMENT_3_DT;
                         //
                         if (gDt < LOWER_BOUND_1_DT)
                                 gDt = LOWER_BOUND_1_DT;
             break;
                 //      run simulation slower: increment period
         case ',':
         case '<':
                         if ((gDt >= LOWER_BOUND_1_DT) && (gDt < UPPER_BOUND_1_DT))
                                 gDt += INCREMENT_1_DT;
                         else if ((gDt >= LOWER_BOUND_2_DT) && (gDt < UPPER_BOUND_2_DT))
                                 gDt += INCREMENT_2_DT;
                         else if (gDt < UPPER_BOUND_3_DT)
                                 gDt += INCREMENT_3_DT;
                         //
                         if (gDt > UPPER_BOUND_3_DT)
                                 gDt = UPPER_BOUND_3_DT;
             break;
                 case ' ':
                         resetCells();
                         break;
                 case '[':
                         if (gRandomRateIndex > 0)
                                 gRandomRateIndex--;
                         break;
                 case ']':
                         if (gRandomRateIndex < NB_RANDOM_RATES-1)
                                 gRandomRateIndex++;
                         break;
         default:
             break;
     }
     glutPostRedisplay();
 }
void myMenu (int value)
Definition at line 664 of file main_GameOfLife.cpp.
References AMOEBA_B357_S1358, ASSIMILATION_B345_S4567, cleanupAndQuit(), CORAL_B3_S45678, gRule, LIFE_B23_S3, MAZE_B3_S12345, QUIT_MENU, and SEEDS_B2_.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
                 case LIFE_B23_S3:
                         gRule = LIFE_B23_S3;
                         break;
                 case CORAL_B3_S45678:
                         gRule = CORAL_B3_S45678;
                         break;
                 case MAZE_B3_S12345:
                         gRule = MAZE_B3_S12345;
                         break;
                 case ASSIMILATION_B345_S4567:
                         gRule = ASSIMILATION_B345_S4567;
                         break;
                 case AMOEBA_B357_S1358:
                         gRule = AMOEBA_B357_S1358;
                         break;
                 case SEEDS_B2_:
                         gRule = SEEDS_B2_;
                         break;
                 default:
             break;
     }
     glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 647 of file main_GameOfLife.cpp.
Referenced by main().
 {
     // if the left mouse button is clicked, do something
     if(state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
 //        gCurrentImg = (gCurrentImg+kNbImages-1) % kNbImages;
 //        glutReshapeWindow(    gMyImage[gCurrentImg]->getWidth(),
 //                           gMyImage[gCurrentImg]->getHeight());
     }
     //  ...and then refresh the display
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 567 of file main_GameOfLife.cpp.
Referenced by main().
 {
     if (gOutputImage != NULL)
     {
         glMatrixMode(GL_PROJECTION);
         glLoadIdentity();
         gluOrtho2D(     0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     }
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
     //  and I inform drawable object of these dimensions (in case they want to
     //  get rendered "shifted")
 //    DrawableObject2D::setDefaultWindowDimensions(gInputImage->getWidth(),
 //                                                 gInputImage->getHeight());
     DrawableObject2D::setDefaultWindowDimensions(w, h);
 }
void resetCells (void)
Definition at line 453 of file main_GameOfLife.cpp.
References uriVL::DrawableObject2D::getHeight(), uriVL::LabelRaster::getLabel2D(), uriVL::DrawableObject2D::getWidth(), gRandomRateIndex, gRunningLife, uriVL::R_W_ACCESS, and RANDOM_RATE.
Referenced by myKeyboard().
 {
         gRunningLife = false;
         const int nbRows = gInputImage->getHeight();
         const int nbCols = gInputImage->getWidth();
         char *const* oldL = gLabelOld->getLabel2D(R_W_ACCESS);
         char *const* newL = gLabelNew->getLabel2D(R_W_ACCESS);
         for (int i=0; i<nbRows; i++)
         {
                 for (int j=0; j<nbCols; j++)
                 {
                         float val = RandomGenerator_C::nextFloat_st(0.f, 1.f);
                         oldL[i][j] = newL[i][j] = static_cast<char>((val < RANDOM_RATE[gRandomRateIndex] ? 1 : 0));
                 }
         }
                 gRunningLife = true;
 }
void updateState (int val)
Definition at line 227 of file main_GameOfLife.cpp.
References AMOEBA_B357_S1358, ASSIMILATION_B345_S4567, CORAL_B3_S45678, gDt, uriVL::DrawableObject2D::getHeight(), uriVL::LabelRaster::getLabel2D(), uriVL::RasterImage::getRaster2D(), uriVL::DrawableObject2D::getWidth(), gLabelNew, gLabelOld, gRule, gRunningLife, LIFE_B23_S3, MAZE_B3_S12345, uriVL::R_W_ACCESS, and SEEDS_B2_.
Referenced by main().
 {
         if (gRunningLife)
         {
                 const int nbRows = gInputImage->getHeight();
                 const int nbCols = gInputImage->getWidth();
                 char *const* newL = gLabelNew->getLabel2D(R_W_ACCESS);
                 const char *const* oldL = gLabelOld->getLabel2D();
                 const unsigned char *const* rgbaIn = gInputImage->getRaster2D();
                 unsigned char *const* rgbaOut = gOutputImage->getRaster2D(R_W_ACCESS);
                 //      apply the rule
                 switch (gRule)
                 {
                         case LIFE_B23_S3:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if (count == 3)
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule
                                                 else if (oldL[i][j] &&
                                                                  ((count == 2) || (count == 3)))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         case CORAL_B3_S45678:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if (count == 3)
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule
                                                 else if (oldL[i][j] &&
                                                                  ((count == 4) || (count == 5) || (count == 6) || (count == 7) || (count == 8)))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         case MAZE_B3_S12345:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if (count == 3)
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule
                                                 else if (oldL[i][j] &&
                                                                  ((count == 1) || (count == 2) || (count == 3) || (count == 4) || (count == 5)))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         case ASSIMILATION_B345_S4567:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if ((count == 3) || (count == 4) || (count == 5))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule
                                                 else if (oldL[i][j] &&
                                                                  ((count == 4) || (count == 5) || (count == 6) || (count == 7)))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         case AMOEBA_B357_S1358:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if ((count == 3) || (count == 5) || (count == 7))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule
                                                 else if (oldL[i][j] &&
                                                                  ((count == 1) || (count == 3) || (count == 5) || (count == 8)))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         case SEEDS_B2_:
                                 for (int i=1; i<nbRows-1; i++)
{
                                         for (int j=1; j<nbCols-1; j++)
{
                                                 int count = oldL[i-1][j-1] + oldL[i-1][j] + oldL[i-1][j+1] +
                                                                         oldL[i][j-1] + oldL[i][j+1] +
                                                                         oldL[i+1][j-1] + oldL[i+1][j] + oldL[i+1][j+1];
                                                 //      Birth rule
                                                 if ((count == 2))
{
                                                         newL[i][j] = static_cast<char>(1);
                                                 }
                                                 //      Survival rule --> none
                                                 //else if (oldL[i][j] &&
                                                 //               ((count == 1) || (count == 3) || (count == 5) || (count == 8)))
                                                 //{
                                                 //      newL[i][j] = static_cast<char>(1);
                                                 //}
                                                 else
{
                                                         newL[i][j] = static_cast<char>(0);
                                                 }
                                         }
                                 }
                                 break;
                         default:
                                 break;
                 }
                 //      Compute the new image
                 for (int i=0; i<nbRows; i++)
                 {
                         for (int j=0; j<nbCols-1; j++)
{
                                 if (newL[i][j] == 1)
{
                                         rgbaOut[i][4*j] = rgbaIn[i][4*j];
                                         rgbaOut[i][4*j+1] = rgbaIn[i][4*j+1];
                                         rgbaOut[i][4*j+2] = rgbaIn[i][4*j+2];
                                         rgbaOut[i][4*j+3] = static_cast<unsigned char>(255);
                                 }
                                 else
{
                                         rgbaOut[i][4*j] = static_cast<unsigned char>(0);
                                         rgbaOut[i][4*j+1] = static_cast<unsigned char>(0);
                                         rgbaOut[i][4*j+2] = static_cast<unsigned char>(0);
                                         rgbaOut[i][4*j+3] = static_cast<unsigned char>(255);
                                 }
                         }
                 }
                 //      swap old and new
                 {
                         LabelRaster* tempLabel = gLabelNew;
                         gLabelNew = gLabelOld;
                         gLabelOld=  tempLabel;
                 }
         }
     glutPostRedisplay();
         glutTimerFunc(gDt, updateState, 0);
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 54 of file main_GameOfLife.cpp.
const int FONT_HEIGHT = 12
Definition at line 138 of file main_GameOfLife.cpp.
Referenced by displayTextualInfo().
float gDt = 1000
Definition at line 135 of file main_GameOfLife.cpp.
Referenced by main(), myDisplay(), myKeyboard(), and updateState().
bool gInitDone = false
Definition at line 84 of file main_GameOfLife.cpp.
Referenced by myDisplay(), and myInit().
RasterImage_RGBa* gInputImage = NULL
Definition at line 79 of file main_GameOfLife.cpp.
LabelRaster* gLabelNew = NULL
Definition at line 82 of file main_GameOfLife.cpp.
Referenced by updateState().
LabelRaster* gLabelOld = NULL
Definition at line 81 of file main_GameOfLife.cpp.
Referenced by updateState().
RasterImage_RGBa* gOutputImage = NULL
Definition at line 80 of file main_GameOfLife.cpp.
int gRandomRateIndex = 6
Definition at line 119 of file main_GameOfLife.cpp.
Referenced by myDisplay(), myKeyboard(), and resetCells().
GlutMenuSelect gRule = LIFE_B23_S3
Definition at line 122 of file main_GameOfLife.cpp.
Referenced by myDisplay(), myMenu(), and updateState().
bool gRunningLife = false
Definition at line 85 of file main_GameOfLife.cpp.
Referenced by resetCells(), and updateState().
float gUt = 0.f
Definition at line 123 of file main_GameOfLife.cpp.
const unsigned int INCREMENT_1_DT = 10
Definition at line 131 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int INCREMENT_2_DT = 100
Definition at line 132 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int INCREMENT_3_DT = 1000
Definition at line 133 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const string kNameFile = color_dir + "mandrill_256x256.jpg"
Definition at line 56 of file main_GameOfLife.cpp.
Referenced by loadImage().
const float kTextBackgroundColor[3] = {0.0f, 0.2f, 0.0f}
Definition at line 141 of file main_GameOfLife.cpp.
Referenced by displayTextualInfo().
const float kTextColor[3] = {1.f, 1.f, 1.f}
Definition at line 140 of file main_GameOfLife.cpp.
Referenced by displayTextualInfo().
const unsigned int LOWER_BOUND_1_DT = 10
Definition at line 125 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int LOWER_BOUND_2_DT = UPPER_BOUND_1_DT
Definition at line 127 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int LOWER_BOUND_3_DT = UPPER_BOUND_2_DT
Definition at line 129 of file main_GameOfLife.cpp.
const int NB_RANDOM_RATES = 10
Definition at line 108 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const float RANDOM_RATE[]
Initial value:
= {     0.01f,
                                                                0.02f,
                                                                0.05f,
                                                                0.1f,
                                                                0.2f,
                                                                0.3f,
                                                                0.4f,
                                                                0.5f,
                                                                0.6f,
                                                                0.7f}
Definition at line 109 of file main_GameOfLife.cpp.
Referenced by myDisplay(), and resetCells().
const string RULE_STR[]
Initial value:
= {     "Life: B23/S3",
                                                        "Coral: B3_S45678",
                                                        "MAZE_B3_S12345",
                                                        "Assimilation: B345/S4567",
                                                        "Amoeba: B357/S1358",
                                                        "Seeds: B2/"
}
Definition at line 99 of file main_GameOfLife.cpp.
Referenced by myDisplay().
const int TEXT_PADDING = 2
Definition at line 139 of file main_GameOfLife.cpp.
Referenced by displayTextualInfo().
const unsigned int UPPER_BOUND_1_DT = 100
Definition at line 126 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int UPPER_BOUND_2_DT = 1000
Definition at line 128 of file main_GameOfLife.cpp.
Referenced by myKeyboard().
const unsigned int UPPER_BOUND_3_DT = 10000
Definition at line 130 of file main_GameOfLife.cpp.
Referenced by myKeyboard().