URIVisionLibrary: uriVL Namespace Reference
uriVL Namespace Reference
Classes
class _FrameGrabber_libvidcap
"Generic" implementation of the reading of video data from a live video source.
class _GraphWorld_gen
Implements the _GraphWorld_gen class.
class _ImageWriter_FreeImage
This class uses the Freeimage library to read/write images.
class ActiveContourDetector
Parent class for all implementations of active contour algorithms for seeking closed contours in an image.
class ActiveContourDetector_balloon
A Function Class which searches for a closed contour in a given image by applying the "balloon" active contour algorithm of L.
class ActiveContourDetector_GVF
A Function Class which searches for a closed contour in a given image by applying the GVF (gradient vector field) active contour algorithm of Xu & Price.
class BackgroundRemover
BackgroundRemover is an abstract class (with pure virtual member function) Inherited by BackgroundRemover_static, BackgroundRemover_dynamic.
class BackgroundRemover_dynamic
This class cannot be instantiated Inherited from: BackgroundRemover_dynamic Deal with changing background.
class BackgroundRemover_dynamic_MW
Inherited from: BackgroundRemover_dynamic Deal with changing background using a certain linear model.
class BackgroundRemover_static
Image operator that computes differences between images.
class Blob
XPair is used in fillHoles(), indicating each covered segment upstairs/downstairs for each line of HorizontalSegment.
class BlobFinder
Blob Finder class.
struct BlobSearchParams
Data structure that defines the conditions of a blob search.
class BlobTracker2D
class BlobTracker2DController
class BlobTrackingState
class Box3D
Box3D class.
class BufferRing
The purpose of this class is to provide a tri-indexed Buffer Ring for use of storing and reading Raster Images grabbed from a video input source.
class Calibration3D
The base virtual Calibration3D class.
class Calibration3D_dyn
Class that implements a dynamic algorithm for the calibration of a camera.
class Calibration3D_Kim
Class that implements the Kim algorithm for the calibration of a camera.
class Calibration3D_TsaiW
Class that implements the Tsai-Wilsson algorithm for the calibration of a camera.
struct CalibrationPair
Struct that stores a "calibration pair", that is, a 3D point and the corresponding image point observed.
class Camera
The base virtual Camera class.
class Cluster
Cluster using average distance.
class ColorGaussianFilter
Pure Virtual parent class for the Gaussian filter classes _F and _I.
class ColorGaussianFilter_F
Gaussian filter class (float operator).
class ColorGaussianFilter_I
ColorGaussianFilter_I class.
class ColorImageGradient
Pure virtual parent class for an operator that computes the gradient of a color raster image.
class ColorImageGradient_Gaussian_F
Vector operator that computes the gradient of a color raster image using a "gradient of Gaussian" filter.
class ColorImageGradient_Gaussian_I
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
class ColorImageGradient_Sobel
Vector operator that computes the gradient of a raster image using Sobel-like masks.
class ColorImageHistogram
So far only a place holder for the ColorImageHistogram class.
class ColorImageLaplacian
Operator that computes the Laplacian of an RGBa color image.
class ColorInverseThresholdLabeler
A ColorInverseThresholdLabeler segments an image into regions based on a set of predefined color threshold-based modes.
class ColorMedianFilter
ColorMedianFilter class.
class ColorMedianFilter_F
ColorMedianFilter class.
class ColorMedianFilter_I
ColorMedianFilter class.
struct ColorRegion
A ColorRegion is defined as a rectangular domain in the HSV space.
class ColorSegParams
Data structure that stores parameters for a color/gray-based segmentation.
class ColorThresholdLabeler
A ColorThresholdLabeler segments an image into regions based on a set of predefined color threshold-based modes.
class ColumnVector
ColumnVector implements the ColumnVector class of Linear Algebra column vectors.
class Cone3D
Cone3D class.
class ConfidenceRecord
class Contour
Set of ImagePoint objects which form a closed curve.
class Contour_F
Set of float ImagePoint objects which compose a closed curve.
class Contour_I
A Countour_I is a set of ImagePoint objects (intetger coordinates) which compose a closed curve.
class ContourDetector
Virtual parent class for all contour detector objects.
class ContourForce
A contour force is a connected set of pixels that share a comon characteristic.
class Corner
class CornerTrackingState
class Cylinder3D
Cylinder3D class.
class DepthMap
depth map class A depth map is a form of raster image that instead of storing an image itensity at each image point stores a depth value.
class Disparity
Generic class for all sort of disparities (stereo, motion in particular).
class DrawableObject2D
Virtual base DrawableObject2D class.
struct Edge
class EdgeDetector
EdgeDetector class.
class EdgeDetector_Canny_F
EdgeDetector_Canny_F class.
class EdgeDetector_Canny_I
EdgeDetector_Canny_I.
class ElevationMap
ElevationMap class An elevation map stores information relative to a surface of the form Z(X, Y), where X, Y, Z, are the coordinates of 3D points.
class Entity3D
The base virtual Entity3D class.
class ErrorReport
Implements the ErrorReport class.
class FeatureDetector
FeatureDetector class.
class Function1D
Pure virtual parent class for all 1-dimensional functions.
class Function1D_F
Pure virtual parent class for all 1-dimensional functions.
class FunctionND
Pure virtual parent class for all n-dimensional functions.
class FunctionND_F
Pure virtual parent class for all n-dimensional functions.
class FunctionNDSection1D
Class defining a 1D section of an n-dimensional function.
class FunctionNDSection1D_F
Class defining a 1D section of an n-dimensional function.
class GaussianFilter
Pure Virtual parent class for the Gaussian filter classes _F and _I.
class GaussianFilter_F
Gaussian filter class (float operator).
class GaussianFilter_I
GaussianFilter_I class.
class GlUtils
Contains various GL-related "utility" functions to allocate and delete "shifted" 1D and 2D arrays of GLxxx elements.
class GraphicComponent3D
This is the parent class for all basic 3D shapes (boxes, cylinders, quad and triangle meshes, generic polyhedra.
class GraphWorld
Implements the GraphWorld class.
struct GrayRegion
A GrayRegion is defined as a range of gray-level values.
class GrayThresholdLabeler
A GrayThresholdLabeler segments an image into regions based on a set of predefined gray-level modes.
class HalfCone3D
HalfCone3D class.
class HalfCylinder3D
HalfCylinder3D class.
class Histogram
Implements the Histogram class.
class HistogramCalculator
An HistogramCalculator computes the histogram of RasterImage objects.
class HomogeneousMatrix
Implements 4x4 homogeneous matrices used to represent 3D transformations.
struct HorizontalSegment
This is the data structure returned by the filling algorithm: a linked list of horizontal segments constitutes a blob.
class HysteresisLabeler
A HysteresisLabeler is a component of the Canny edge detector.
class ImageArithmetics
ImageArithmetics is a class made up of static functions.
class ImageFeature
Abstract base class of Blob, Segment, Corner...
class ImageGradient
Pure virtual parent class for an operator that computes the gradient of a raster image.
class ImageGradient_Gaussian_F
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
class ImageGradient_Gaussian_I
Vector operator that computes the gradient of a raster image using a "gradient of Gaussian" filter.
class ImageGradient_Sobel
Vector operator that computes the gradient of a raster image using Sobel-like masks.
class ImageHistogram
Implements the ImageHistogram class.
class ImageLaplacian
Operator that computes the Laplacian of a raster image.
class ImageLaplacian_Gaussian_F
Image operator that computes the Laplacian of an RGBa color image using a "Laplacian of Gaussian" filter.
class ImageLaplacian_Gaussian_I
Image operator that computes the Laplacian of a raster image using a "Laplacian of Gaussian" filter.
class ImageLaplacian_Sobel
ImageLaplacian_Sobel class.
class ImageOperator
Virtual parent class for all image operators (operators that are applied to a raster image and produce a raster image as their output).
class ImagePoint
Implements the ImagePoint class.
class ImagePoint_F
Implements the ImagePoint_F class.
class ImagePyramid
An ImagePyramid object stores an array of RasterImage objects that represent the image at different scales, scale 0 being a copy of the original image and scale i being a 2^i scaled down version.
class ImageReader
ImageReader objects read a raster image from an image file specified either by its file path or FSSpec descriptor, or selected via a dialog window.
class ImageRect
Implements the ImageRect class.
class ImageStitcher
An ImageStitcher positions correctly relative to one another a set of RasterImage objects (translation only).
class ImageTransformation
This class only contains static functions to rotate, scale, skew, and translate images.
class ImageWarper
Virtual parent class for all image warper object.
class ImageWarper_GL
holds the records of 2D matching result
class ImageWriter
A simple/lame class that writes image objects to files.
class IntrinsicParameters
Parent class for all descriptors of a camera's intrinsic parameters.
class IntrinsicParameters_CCD
Implements the IntrinsicParameters_CCD class.
class IntrinsicParameters_DLT
Implements the IntrinsicParameters_DLT class.
class IntrinsicParameters_pinhole
Implements the IntrinsicParameters_pinhole class.
class IntrinsicParameters_TsaiW
Implements the IntrinsicParameters_TsaiW class.
class IterationStatus
Class that stores the status of an ongoing iteration and/or the results of a finished iteration.
class Labeler
A Labeler object assigns a label to each pixel of its input image.
class LabelRaster
Base label raster class.
class LinearSolver
Parent class to all classes that implement an algorithm for solving a system of linear equations.
class LinearSolver_Cholesky
class LinearSolver_GaussSeidel
Class that implement the Gauss-Seidel iterative algorithm for solving SLEs.
class LinearSolver_Jacobi
Class that implement the Jacobi iterative algorithm for solving SLEs.
class LinearSolver_LU
Class that implement Crout's version of the LU factorization algorithm for solving SLEs.
class LinearSolver_QR
Class that implement the Householder QR factorization algorithm for solving overdetermined SLEs.
class LinearSolver_SOR
Class that implement the Successive Over-relaxation (SOR) iterative algorithm for solving SLEs.
class LinearSolver_SVD
Class that implement the Singular Value Decomposition algorithm for solving arbitrary SLEs.
class LinearSolverRecord
A simple structure to hold the results of an SLE solution process.
class ManualStitcher
A ManualStitcher uses user input to position correctly relative to one another a set of RasterImage objects.
class Matrix
Implements the Matrix class of Linear Algebra matrices.
struct MatrixIndicators
Struct to hold all the TriState indicators of a matrix to create.
class MedianFilter
MedianFilter class.
class MedianFilter_F
MedianFilter class.
class MedianFilter_I
MedianFilter class.
class NonlinearOptimizer1D
Pure virtual parent class for all 1-dimensional optimizers Its subclasses will actually implement an optimization algorithm, i.e.
class NonlinearOptimizer1D_Brent
1-dimensional optimizer that implements the Brent optimization algorithm (combining parabolic and golden section searches).
class NonlinearOptimizer1D_gss
1-dimensional optimizerimplementing the golden section search.
class NonlinearOptimizer1D_parab
1-dimensional optimizer that implements my own version of combining parabolic interposlation and golden section searches.
class NonlinearOptimizerND
Pure virtual parent class for all n-dimensional optimizers.
class NonlinearOptimizerND_conjDir
Class that implements the conjugate directions line search optomization algorithm.
class NonMaximumSuppressor
Implementation of the NonMaximumSuppressor class.
class NormalFlowCalculator
struct NormalVector
Stores the normal vector at a point.
class Object3D
The base virtual class for 3D objects.
class ObjectLoader3D
Virtual parent class for all object loaders.
class ObjectLoader_3jy
Implements an object loader for files in the "3jy" format, a file format that I created to represent robots (manipulator, mobile, hybrid).
class ObjectLoader_obj
Implements a virtual object loader for files in the "obj" format.
class OptimizerRecord1D
A simple structure to hold the results of a 1D optimization process.
class OptimizerRecordND
A simple structure to hold the results of a nD optimization process.
class OrthographicCamera
Implements the OrthographicCamera class.
class Pattern2D
A Pattern2D is defined as a connected set of pixels.
class Pattern2DMatchRecord
Holds the records of a 2D matching result.
class Pattern2DMatchRecord_part
Holds the records of a 2D matching result (matching performed by a "partial match" matcher).
class Pattern2DMatchRecord_scale
holds the records of 2D matching result
class Pattern2DMatchRecord_warp
Holds the records of a 2D warp-based matching result.
class PatternMatcher2D
Parent class for all 2D pattern matchers.
class PatternMatcher2D_corr
One of the simplest possible subclasses of PatternMatcher2D.
class PatternMatcher2D_medianDiff
One of the simplest possible subclasses of PatternMatcher2D.
class PatternMatcher2D_partCorr
Hopefully occlusion-resistant subclass of PatternMatcher2D.
class PatternMatcher2D_scaledDiff
One of the simplest possible subclasses of PatternMatcher2D.
class PatternMatcher2D_warp
Pattern matcher that uses an image warper to compute a best match for a deformable template.
class PatternTracker2D
class PatternTracker2DController
class PatternTrackingState
class PerspectiveCamera
Implements the PerspectiveCamera class.
class Point3D
Implements the Point3D class.
class PolyMesh3D
The base PolyMesh3D class.
class PolynomialFunction1D
Class that implements 1-dimensional polynomial functions and their derivatives.
class PolynomialFunction1D_F
Class that implements 1-dimensional polynomial functions and their derivative.
class Prism3D
Prism3D class.
class Quaternion
Quaternion Class.
class RandomGenerator
Pure virtual parent class for pseudorandom number generators.
class RandomGenerator_C
Pseudorandom number generator wrapper class for the awful standard C function.
class RandomGenerator_Knuth
Random number generator class that implements Knuth's algorithm (by way of the Numerical Recipes in C).
class RandomGenerator_MT
Random number generator class that uses the Mersenne Twister algorithm of Matsumoto and Nishimura implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
class RandomGenerator_R250_R521
Random number generator class that uses the combined R250-R521 algorithm implemented by Michael Brundage http://www.qbrundage.com/michaelb/index.html.
class RangeMap
RangeMap class A range map stores information relative to a surface of the form Z(X, Y), where X, Y, Z, are the coordinates of 3D points.
class RasterImage
Virtual base image class.
class RasterImage_aRGB16
Base 16-bit argb color image class.
class RasterImage_binary
Base binary image class.
class RasterImage_gray
Base gray-level image class.
class RasterImage_gray_F
Floating point gray-level image class.
class RasterImage_HSV
A RasterImage_HSV is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel.
class RasterImage_HSV24
A RasterImage_HSV24 is a RasterImage_RGBa that also stores the hue, saturation, and value for each pixel using only an unsigned char to store the hue, which forces us to scale it from [0, 359] to [0, 255].
class RasterImage_Lab
class RasterImage_RGB
Base rgb color image class.
class RasterImage_RGBa
Base 32-bit rgba color image class.
class RasterImage_RGBa_F
RasterImage_RGBa_F class.
class RectifiedStereoDisparity
class RectifiedStereoMatch
class RectifiedStereoMatcher
Pure virtual parent class for all classes that implement a stereo matching algorithm for rectified stereo pairs.
class RectifiedStereoMatcher_corr
class RectifiedStereoMatcher_JJL
class RectifiedStereoPair
Future versions of this class will/should include information about the cameras corresponding to each image (and their relative transformations and respective parameters)
class ReferenceFrame3D
A ReferenceFrame3D is the object relative to which any Entity3D is defined.
class Registration2D
Virtual parent class for objects that register two sets of image points or (later) two image regions.
class Registration2D_ICP
Class for objects that register two sets of image points using the Iterated Closest Point (ICP) algorithm of Besl and McKay.
class Registration2D_LMICP
Class for objects that register two sets of image points using the Levenberg-Marquardt formulation of the Iterated Closest Point (ICP) algorithm, as proposed by Fitzgibbon (2001)
class Registration2D_LPCD
Class for objects that register two sets of image points using the Local Consistency of Point Data (LCPD) algorithm of Urano, Kaneko, and Tanak (2006).
class RigidTransformation2D
Class for all 2D transformation composed of a translation and a rotation.
class RigidTransformation3D
A RigidTransformation is a transformation between reference frames that preserves angles and lengths.
class Rotation2D
Class that implements 2D rotation transformations.
class Rotation3D
A Rotation3D is a component of any RigidTransformation3D.
class RowVector
Implements the RowVector class of Linear Algebra row vectors.
struct ScaleParameter
class Segment
class SegmentDetector
This provides fast detection of horizontal or vertical line segment in the image.
class Segmenter
Generic, abstract Segmenter class.
class SegmentTrackingState
class SequenceGrabber
Class that handles the reading of video data from a live video source.
class ShapeTrackingState
class SimpleGraphicObject2D
A SimpleGraphicObject2D is essentially a DrawableObject2D madeup of a single 2D shape.
class StereoDisparity
A StereoDisparity is established between two static cameras.
class StereoMatch
class StereoMatcher
Pure virtual parent class for all classes that implement a stereo matching algorithm.
class StereoMatchRecord
A StereoMatchRecord stores a matching point and matching score resulting from a call to a stereo matcher.
class StereoPair
Future versions of this class will/should include information about the cameras corresponding to each image (and their relative transformations and respective parameters)
struct StitchPattern
class ThresholdLabeler
Pure virtual parent class for objects that segment an image into regions based on a set of predefined threshold-based modes.
class Tracker2D
Right now I am confused as to what the Tracker2D class is really supposed to be doing: Track a single object/feature or a collection of these?
class Tracker2D_PID
class Tracker2DController
class TrackingState
class Transformation2D
Virtual base class for all 2D transformation that can be represented by a 3 by 3 homogenous matrix.
class Transformation3D
Virtual base class for all 3D transformation that can be represented by a 4 by 4 homogenous matrix.
class Translation2D
Virtual base class for all 2D transformation that can be represented by a 4 by 4 homogenous matrix.
class Translation3D
A Translation object is always stored as an array of three double numbers for the X, Y, and Z translation components.
class TubularSection3D
TubularSection3D class.
class UriVL
UriVL class only contains static functions.
struct URIVL_Rect
For platforms not supported by Quicktime, we need to define Rect.
class Vector2D
Implements the Vector2D class.
class Vector2D_F
Implements the Vector2D_F class.
class VectorField
VectorField class.
class VectorField_F
VectorField_F class.
class VectorField_I
VectorField_I class.
class VectorOperator
Virtual parent class for all vector operators (operators that are applied to a raster image and produce a vector field as their output).
class VideoDestination
Parent class for all objects that output raster image objects to files, videos, VTRs, etc.
class VideoSource
VideoSource pure virtual parent class.
class VirtualFace3D
Implements the VirtualFace3D class.
class VirtualObject3D
The base virtual class for 3D objects.
class VirtualObjectLoader
A simple class to load 3D models from a file.
class VirtualPart3D
Implements the VirtualPart3D class.
class VirtualPoint3D
Implements the VirtualPoint3D class.
struct VisibilityStatus
class WarpMatchScoreFunctionND
Warping Matching Score Function nD.
class WeakPerspectiveCamera
Implements the WeakPerspectiveCamera class.
class ZeroCrossingDetector
ZeroCrossingDetector class.
Typedefs
typedef enum uriVL::ColorImageHistogramType ColorImageHistogramType
Enumerated types for all kinds of histogram computations supported by this class.
typedef enum uriVL::DrawableInformationType DrawableInformationType
Enumerated type that lists the type of data that could be found in a drawable object.
typedef enum uriVL::BaseRasterType BaseRasterType
Enumerates the base image raster types.
typedef char * Movie
Placeholder until we define the Movie type.
typedef char * GDHandle
Placeholder until we define the GDHandle type (if ever)
typedef char * GraphicsImportComponent
Placeholder until we define the GraphicsImportComponent type (if ever)
typedef char * SeqGrabComponent
Placeholder until we define the GraphicsImportComponent type (if ever)
typedef char * SGChannel
Placeholder until we define the GraphicsImportComponent type (if ever)
typedef char * ImageSequence
Placeholder until we define the GraphicsImportComponent type (if ever)
typedef enum uriVL::HistogramRenderMode HistogramRenderMode
Enumerated types for all histogram rendering modes supported by this class.
typedef enum uriVL::HistogramDataType HistogramDataType
Tists the types of data supported by this class.
typedef std::list< ImagePoint * > ImagePointList
typedef std::list< const ImagePoint * > ConstImagePointList
typedef std::list< ImagePoint * > ImagePoint_FList
typedef std::list< const ImagePoint * > ConstImagePoint_FList
typedef struct uriVL::URIVL_Rect URIVL_Rect
For platforms not supported by Quicktime, we need to define Rect.
typedef std::list< ImageRect * > RectList
typedef std::list< const ImageRect * > ConstRectList
typedef enum uriVL::ConversionToGrayMode ConversionToGrayMode
Enumerated type of modes for color to gray conversion.
typedef enum uriVL::ConversionFromFloatMode ConversionFromFloatMode
Enumerated type of modes for float to unsigned char gray conversion.
typedef enum uriVL::ReadWriteStatus ReadWriteStatus
typedef enum uriVL::TriState TriState
Enum type for true/false/unknown ternary state variables.
typedef std::list< Vector2D * > Vector2DList
typedef std::list< const Vector2D * > ConstVector2DList
typedef struct uriVL::CalibrationPair CalibrationPair
Struct that stores a "calibration pair", that is, a 3D point and the corresponding image point observed.
typedef struct uriVL::NormalVector NormalVector
Stores the normal vector at a point.
typedef enum uriVL::ReferenceFrameShortcut ReferenceFrameShortcut
Enum type that define shortcuts for accessing particular reference frames from an Entity3D.
typedef enum uriVL::RotationRef RotationRef
typedef enum uriVL::StereoDisparityType StereoDisparityType
Possible configurations for two cameras that can lead to a stereo disparity.
typedef enum uriVL::StereoImageID StereoImageID
Enumerated type for image identification.
typedef enum uriVL::VisibilityCode VisibilityCode
typedef enum uriVL::VirtualRenderMode VirtualRenderMode
typedef struct uriVL::VisibilityStatus VisibilityStatus
typedef enum uriVL::ResolutionLevel ResolutionLevel
typedef enum uriVL::GraphicalComponentType GraphicalComponentType
Basic types of graphical components.
typedef enum uriVL::TubeType TubeType
Enum that defines what kind of partial tube we are dealing with.
typedef enum uriVL::BalloonType BalloonType
A balloon can be inflating or contracting depending on the sign of the "shrink force" applied to its vertices.
typedef enum uriVL::QuadrantIndex QuadrantIndex
enumerated type for indices of quadrants.
typedef struct uriVL::HorizontalSegment HorizontalSegment
This is the data structure returned by the filling algorithm: a linked list of horizontal segments constitutes a blob.
typedef std::list< HorizontalSegment * >::iterator HSegIterator
Iterator for a list of pointers to HorizontalSegment objects.
typedef std::list< HorizontalSegment * >::const_iterator const_HSegIterator
Constant iterator for a list of pointers to HorizontalSegment objects.
typedef std::deque< std::list< HorizontalSegment * > * > LineSegDeque
The data structure used to hold of the segments of a blob: A deque that store the data doe each line of the blob, sorted top to bottom.
typedef struct uriVL::Edge Edge
typedef std::list< Blob * > BlobList
A BlobList is a list of Blob pointers.
typedef enum uriVL::MoveDirection MoveDirection
Displacement directions along the search spiral.
typedef struct uriVL::BlobSearchParams BlobSearchParams
Data structure that defines the conditions of a blob search.
typedef std::list< Cluster * > ClusterList
typedef enum uriVL::ColorGradientMode ColorGradientMode
Diffferent ways of computing a color gradient.
typedef enum uriVL::LaplacianSobelForm LaplacianSobelForm
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
typedef enum uriVL::FillingMode FillingMode
A FillingMode specifies how part of an image that fall outside of color/gray regions should be filled in the output raster.
typedef struct uriVL::ColorRegion ColorRegion
A ColorRegion is defined as a rectangular domain in the HSV space.
typedef struct uriVL::GrayRegion GrayRegion
A GrayRegion is defined as a range of gray-level values.
typedef enum uriVL::ContourInitializer ContourInitializer
Types of initial contour shapes for an active contour.
typedef std::list< ImageFeature * > FeatureList
typedef enum uriVL::ColorDifferenceMode ColorDifferenceMode
Defines the three possible modes for computing image differences between color images:
typedef struct uriVL::StitchPattern StitchPattern
typedef enum uriVL::ImageWarperType ImageWarperType
Enumarated type listing the types of image warpers supported by the library.
typedef enum uriVL::InnerWarpingMode InnerWarpingMode
Enumerated type for the different modes of warping (as determined by inner grid point motion) supported.
typedef enum uriVL::BorderWarpingMode BorderWarpingMode
Enumerated type for the different modes of warping (as determined by outer grid point motion) supported.
typedef enum uriVL::Pattern2DUpdateMode Pattern2DUpdateMode
Standard update modes for a Pattern2D.
typedef std::list< Pattern2D * > Pattern2DList
typedef struct uriVL::ScaleParameter ScaleParameter
typedef enum uriVL::BasePatternMatcher2DType BasePatternMatcher2DType
Defines the basic types of pattern matching supported by the library.
typedef enum uriVL::Registration2DType Registration2DType
Basic types of 2D registrations supported by this class.
typedef enum uriVL::Point2DSelectionMode Point2DSelectionMode
Defines the different data point selection modes supported.
typedef enum uriVL::Point2DMatchingMetric Point2DMatchingMetric
Defines the different matching metric types supported.
typedef enum uriVL::Point2DPairRejectMode Point2DPairRejectMode
Defines the matching pair rejection modes supported by the registration algorithm.
typedef enum uriVL::MatchPairWeightingMode MatchPairWeightingMode
Defines the weighting schemes for pairs of matching points that the registration algorithm supports.
typedef enum uriVL::SegmentDetectorType SegmentDetectorType
typedef enum uriVL::TransformationQuality TransformationQuality
typedef void * FSSpec
Placeholder until we define the FSSpec type (if ever)
typedef int OSErr
Placeholder until we define the OSErr type (if ever)
typedef enum uriVL::ConvergenceCriterion ConvergenceCriterion
Criteria for deciding that an iteration has converged.
typedef enum uriVL::LinearSolverRecordStatus LinearSolverRecordStatus
Tri-state enumerated type generally set by a factorization method.
typedef struct uriVL::MatrixIndicators MatrixIndicators
Struct to hold all the TriState indicators of a matrix to create.
typedef enum uriVL::DirectionUpdateMethod DirectionUpdateMethod
Codes for the various conjugate direction updating schemes supported.
typedef enum uriVL::DirectionResetMode DirectionResetMode
Codes for the different ways to initialize/reset the search directions.
typedef std::list< BlobTracker2D * > BlobTracker2DList
typedef std::list< BlobTrackingState * > BlobTrackingStateList
typedef list< PatternTracker2D * > PatternTracker2DList
typedef std::list< PatternTrackingState * > PatternTrackingStateList
typedef std::list< TrackingState * > TrackingStateList
typedef enum uriVL::CompressionMode CompressionMode
typedef enum uriVL::ImageFileType ImageFileType
Enumerations
enum ColorImageHistogramType {
DEFAULT_TYPE = 100,
RGB_HISTOGRAM,
HSV_HISTOGRAM
}
Enumerated types for all kinds of histogram computations supported by this class.
enum DrawableInformationType {
kUndetermined = -1,
kDense = 0,
kSparse,
kInterpolated,
kDenseUncertain,
kSparseUncertain,
kInterpolatedUncertain
}
Enumerated type that lists the type of data that could be found in a drawable object.
enum ErrorCode {
kNoError = 0,
kUnknownError = 1,
kNoCode = 2,
kNullParameterError,
kInvalidReferenceError,
kInvalidParameterError,
kNoninitializedObjectError,
kFunctionNotImplemented,
kCaseNotImplemented,
kMemoryCopyError,
kMiscError,
kNullArrayError,
kInvalidLockAccess,
kAccessToLockedData,
kUriBaseError = 1000,
kRasterImageError = 1100,
kNullRasterImageError,
kNullVectorFieldError,
kRasterAllocationFailure = 1110,
kRasterInvalidDimensions,
kRasterDimensionsDontMatch = 1120,
kNullRasterError = 1130,
kNullRectangleError = 1140,
kNullImagePointError,
kInvalidRectangleError,
kInvalidRasterType,
kGWorldRelatedError = 1200,
kGWorldAllocationError = 1201,
kGWorldIsNullError = 1202,
kGWorldNullPixMapError,
kGWorldInvalidPixelDepth = 1210,
kGWorldIncompatiblePixelDepth,
kGWorldInvalidCLUT = 1220,
kGWorldCannotLockPixels = 1230,
kGWorldCannotUnlockPixels = 1231,
kQuickTime_relatedError = 1500,
kQuickTimeNotInstalled,
kPixMapLockFailed,
kEnterMoviesError,
kImageProcessingError = 2000,
kFilterAllocationError,
kNullLabelRasterError,
kNullTransformation2D = 2100,
kInvalidTransformation2D = 2110,
kComputerVisionError = 3000,
kNullTransformation3D = 3100,
kInvalidTransformation3D,
kNullEntity3D = 3110,
kInvalidEntity3D,
kCameraError = 3200,
kInvalidCameraType = 3210,
kInvalidIntrisicParameterType = 3220,
kStereoMatchingError = 3400,
kTrackingError = 4000,
kVideoSourceError = 5000,
kVideoSourceNotSetError = 5010,
kVideoSourceFileNotFoundError = 5020,
kVideoInitializingError = 5100,
kOpenVideoComponentError = 5110,
kInvalidGrabRectDimensions = 5120,
kVideoBufferAllocError = 5200,
kVideoAcquisitionError = 5300,
kVideoDigitizerComponentError = 5310,
kUnsupportedImageFormatError = 5400,
kMovieEditingError = 6000,
kInitializeMovieError,
kMovieToolboxError,
kMovieStartPointError,
kFileIOError = 6100,
kDirectoryNullPathError,
kFileNullPathError,
kDirectoryListError,
kDirectoryNotFoundError = 6120,
kFileNotFoundError,
kDirectoryCloseError = 6130,
kFileOpenWriteError,
kFileOpenReadError,
kFileCloseError,
kWrongFileTypeError = 6140,
kUnknownFileTypeError,
kFileReadingError = 6150,
kFileWritingError,
kEndOfFileError,
kNumericalError = 7000,
kMatrixCalculationError = 7100,
kNullMatrixError,
kMatrixIncorrectDimensionsError,
kSingularMatrixError,
kIllConditionedMatrixError,
kCalculusError = 7200,
kNullFunctionError,
kDataRangeError,
kGraphicsError = 8000,
kOpenGLNumAllocError,
kOpenGL_relatedError = 8100,
kOpenGLDrawModuleError,
kGLUT_relatedError = 8200,
kMaxErrorCodeID
}
List of all the error codes for the library.
enum BaseRasterType {
kUndefRasterType = -1,
kBinaryRaster =1,
kGrayRaster,
kLongGrayRaster,
kaRGB16Raster,
kRGB24Raster,
kaRGB32Raster,
kRGBa32Raster
}
Enumerates the base image raster types.
enum HistogramRenderMode {
LIN_LIN = 200,
LIN_LOG,
LIN_POLAR,
LOG_POLAR
}
Enumerated types for all histogram rendering modes supported by this class.
enum HistogramDataType {
NO_TYPE_HIST = -1,
FLOAT_HIST = 300,
INT_HIST,
UCHAR_HIST
}
Tists the types of data supported by this class.
enum ConversionToGrayMode {
kMaxFieldConversion = 0,
kAverageConversion,
kWeightedAverageConversion
}
Enumerated type of modes for color to gray conversion.
enum ConversionFromFloatMode {
kUndefFloatConv = -1,
kSignedFloat = 0,
kPositiveFloat,
kRangeFloat,
kSaturatedPositive,
kSaturatedSigned
}
Enumerated type of modes for float to unsigned char gray conversion.
enum ReadWriteStatus { R_W_ACCESS }
enum TriState {
IS_FALSE = 0,
IS_TRUE = 1,
IS_UNKNOWN = -1
}
Enum type for true/false/unknown ternary state variables.
enum ReferenceFrameShortcut {
WORLD_FRAME = 0,
VIEWER_FRAME = 1,
PARENT_FRAME
}
Enum type that define shortcuts for accessing particular reference frames from an Entity3D.
enum RotationRef {
MATRIX_REF = 0,
QUATERNION_REF,
ROLL_PITCH_YAW_REF,
EULER_ANGLES_REF
}
enum StereoDisparityType {
HORIZONTAL_L2R = 0,
HORIZONTAL_R2L,
VERTICAL_T2B,
VERTICAL_B2T,
GENERIC_1_2,
GENERIC_2_1
}
Possible configurations for two cameras that can lead to a stereo disparity.
enum StereoImageID {
LEFT_IMAGE = 0,
RIGHT_IMAGE = 1
}
Enumerated type for image identification.
enum VisibilityCode {
UNKNOWN = -1,
VISIBLE,
INVISIBLE,
CONTACT
}
enum VirtualRenderMode {
INTERPOSE = 1,
GEOMETRY_TEST = 2
}
enum ResolutionLevel {
kVeryHighResolution,
kFineResolution,
kMediumResolution,
kCoarseResolution,
kVeryLowResolution
}
enum GraphicalComponentType {
kOpenBoxObject = 0,
kClosedBoxObject,
kOpenCylinderObject,
kClosedCylinderObject,
kTubularSectionObject,
kOpenHalfCylinderObject,
kClosedHalfCylinderObject,
kOpenPrismObject,
kClosedPrismObject,
kOpenConeObject,
kClosedConeObject,
kOpenHalfConeObject,
kClosedHalfConeObject,
kPolyhedronObject,
kNbComponentTypes
}
Basic types of graphical components.
enum TubeType {
FULL_TUBE = -1,
NEARLY_FULL_TUBE = 0,
ABOUT_3_QUARTER_TUBE,
ABOUT_HALF_TUBE,
ABOUT_QUARTER_CUBE,
LESS_THAN_QUARTER_CUBE
}
Enum that defines what kind of partial tube we are dealing with.
enum BalloonType {
EXPANDING_BALLOON = 0,
CONTRACTING_BALLOON
}
A balloon can be inflating or contracting depending on the sign of the "shrink force" applied to its vertices.
enum QuadrantIndex {
UPPER_LEFT_QUAD = 0,
UPPER_RIGHT_QUAD,
LOWER_LEFT_QUAD,
LOWER_RIGHT_QUAD
}
enumerated type for indices of quadrants.
enum MoveDirection {
MOVE_LEFT = 0,
MOVE_DOWN,
MOVE_RIGHT,
MOVE_UP
}
Displacement directions along the search spiral.
enum ColorGradientMode {
GRAD_AVE_OF_COLOR_COMPONENTS = 0,
GRAD_LARGEST_COLOR_COMPONENT
}
Diffferent ways of computing a color gradient.
enum LaplacianSobelForm {
LAPLACIAN_SOBEL_FORM_1 = 1,
LAPLACIAN_SOBEL_FORM_2 = 2,
LAPLACIAN_SOBEL_FORM_3 = 3,
LAPLACIAN_SOBEL_FORM_1 = 1,
LAPLACIAN_SOBEL_FORM_2 = 2,
LAPLACIAN_SOBEL_FORM_3 = 3
}
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
enum FillingMode {
kIdentityFill = 0,
kOrigColorFill,
kOrigGrayFill,
kBlackFill,
kWhiteFill,
kMediumGrayFill
}
A FillingMode specifies how part of an image that fall outside of color/gray regions should be filled in the output raster.
enum ContourInitializer {
ELLIPTIC_CONTOUR = 0,
BOX_CONTOUR
}
Types of initial contour shapes for an active contour.
enum ColorDifferenceMode {
AVERAGE_DIFFERENCE,
MAX_DIFFERENCE,
HUE_DIFFERENCE
}
Defines the three possible modes for computing image differences between color images:
enum LaplacianSobelForm {
LAPLACIAN_SOBEL_FORM_1 = 1,
LAPLACIAN_SOBEL_FORM_2 = 2,
LAPLACIAN_SOBEL_FORM_3 = 3,
LAPLACIAN_SOBEL_FORM_1 = 1,
LAPLACIAN_SOBEL_FORM_2 = 2,
LAPLACIAN_SOBEL_FORM_3 = 3
}
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
enum ImageWarperType { GL_WARPER = 0 }
Enumarated type listing the types of image warpers supported by the library.
enum InnerWarpingMode {
INNER_FREE = 0,
INNER_TOPOLOGY,
INNER_CONVEX,
INNER_BOUNDS
}
Enumerated type for the different modes of warping (as determined by inner grid point motion) supported.
enum BorderWarpingMode {
BORDER_FREE = 0,
BORDER_INWARD,
BORDER_SLIDE,
BORDER_FIXED
}
Enumerated type for the different modes of warping (as determined by outer grid point motion) supported.
enum Pattern2DUpdateMode {
REPLACE_PATTERN = 0,
UNION_BLOBS_REPLACE_IMG,
UNION_BLOBS_AVG_IMG,
INTERSECT_BLOBS_REPLACE_IMG,
INTERSECT_BLOBS_AVG_IMG,
AVERAGE_PATTERNS
}
Standard update modes for a Pattern2D.
enum BasePatternMatcher2DType {
PATTERN_MATCHER_2D_CORR,
PATTERN_MATCHER_2D_PART_CORR,
PATTERN_MATCHER_2D_MEDIAN,
PATTERN_MATCHER_2D_SCALED_DIFF,
PATTERN_MATCHER_2D_NON_BASIC
}
Defines the basic types of pattern matching supported by the library.
enum Registration2DType {
RIGID_LINEAR_REG_2D = 0,
RIGID_NONLINEAR_REG_2D,
AFFINE_REG_2D
}
Basic types of 2D registrations supported by this class.
enum Point2DSelectionMode {
SELECT_ALL_POINTS = 0,
SELECT_RANDOM_POINT_SAMPLE,
MAX_GRADIENT_DISTRIBUTION
}
Defines the different data point selection modes supported.
enum Point2DMatchingMetric {
POINT_POINT_DISTANCE,
POINT_POINT_NORMAL_DISTANCE,
POINT_POINT_DISTANCE_SQ,
POINT_POINT_NORMAL_DISTANCE_SQ,
POINT_EDGE_DISTANCE,
POINT_EDGE_NORMAL_DISTANCE,
POINT_EDGE_DISTANCE_SQ,
POINT_EDGE_NORMAL_DISTANCE_SQ
}
Defines the different matching metric types supported.
enum Point2DPairRejectMode {
RETAIN_ALL_PAIRS,
THRESHOLD_BASED_REJECT,
PERCENTAGE_REJECT,
STANDARD_DEV_REJECT,
NEIGHBOR_INCONSISTENCY_REJECT
}
Defines the matching pair rejection modes supported by the registration algorithm.
enum MatchPairWeightingMode {
EQUAL_WEIGHT = 0,
DISTANCE_BASED_WEIGHT,
ANGLE_BASED_WEIGHT,
COLOR_BASED_WEIGHT
}
Defines the weighting schemes for pairs of matching points that the registration algorithm supports.
enum SegmentDetectorType {
kVertical = 0,
kHorizontal
}
enum TransformationQuality {
kUnknown = -1,
kDefinition = 0,
kReliable,
kUnreliable
}
enum ConvergenceCriterion {
SUM_OF_ABSOLUTE_DISPLCT = 0,
SUM_OF_SQUARED_DISPLCT,
AVERAGE_DISPLCT,
MAXIMUM_DISPLCT
}
Criteria for deciding that an iteration has converged.
enum LinearSolverRecordStatus {
UNKNOWN_STATUS = -1,
REGULAR_MATRIX = 0,
SINGULAR_MATRIX = 1,
ILL_CONDITIONED_MATRIX = 2,
LINEAR_SOLVER_SUCCEDED = 3,
LINEAR_SOLVER_FAILED = 4
}
Tri-state enumerated type generally set by a factorization method.
enum DirectionUpdateMethod {
NO_UPDATE = 0,
POWELL_UN_IS_XN_X0,
POWELL_DISCARD_LARGEST_DECREASE_DIR
}
Codes for the various conjugate direction updating schemes supported.
enum DirectionResetMode {
CANONICAL_DIRECTIONS = 0,
RANDOM_ORTHOGONAL_DIRECTIONS,
USER_SPECIFIED_DIRECTIONS
}
Codes for the different ways to initialize/reset the search directions.
enum Result {
TARGET_MATCH_LIST,
TARGET_FOUND,
TARGET_NOT_FOUND,
WRONG_TARGET_FOUND
}
enum CompressionMode {
kUncompressed = 0,
kRLE4Bits,
kRLE8Bits
}
enum ImageFileType {
kUnknownImgFileType = -1,
kTGA,
kPPM,
kPGM,
kBMP,
kNbImageFileExtensions
}
Functions
void drawRect (float x, float y, float width, float height)
Draws the contour of a rectangle specified by the coordinates of it upper-left corner, width, and height.
void fillRect (float x, float y, float width, float height)
Fills a rectangle specified by the coordinates of it upper-left corner, width, and height.
void drawCenteredRect (float cx, float cy, float width, float height, float angle=0.f)
Draws the contour of a rectangle specified by the coordinates of it center, width, and height, and by a rotation angle (in degree).
void fillCenteredRect (float cx, float cy, float width, float height, float angle=0.f)
Fills a rectangle specified by the coordinates of it center, width, and height, and by a rotation angle (in degree).
void drawOval (float x, float y, float width, float height)
Draws the contour of an ellipse specified by the coordinates of it upper-left corner, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
void fillOval (float x, float y, float width, float height)
Fills an ellipse specified by the coordinates of it upper-left corner, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
void drawCenteredOval (float cx, float cy, float width, float height, float angle=0.f)
Draws an ellipse specified by the coordinates of it center, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
void fillCenteredOval (float cx, float cy, float width, float height, float angle=0.f)
Fills an ellipse specified by the coordinates of it center, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
void drawCircularDot (void)
Draws a unit circular "dot" at the current location.
void fillCircularDot (void)
Fills a unit circular "dot" at the current location.
void drawSquareDot (void)
Draws a unit square "dot" at the current location.
void fillSquareDot (void)
Fills a unit square "dot" at the current location.
void drawDiamondDot (void)
Draws a unit diamond "dot" at the current location.
void fillDiamondDot (void)
Fills a unit diamond "dot" at the current location.
void drawPoint_disk (float cx, float cy, float rad, const float *color)
Free function to draw a point as a disk.
void drawPoint_square (float cx, float cy, float rad, const float *color)
Free function to draw a point as a square.
void drawPoint_diamond (float cx, float cy, float rad, const float *color)
Free function to draw a point as a diamond.
Variables
const int IMAGE_SPACE_BOUND = 32767
const float VECTORSCALE = 5.f
static const int R250_LEN = 250
static const int R521_LEN = 521
Typedef Documentation
typedef enum uriVL::BalloonType uriVL::BalloonType
A balloon can be inflating or contracting depending on the sign of the "shrink force" applied to its vertices.
typedef enum uriVL::BasePatternMatcher2DType uriVL::BasePatternMatcher2DType
Defines the basic types of pattern matching supported by the library.
Other, more sophisticated pattern matching techniques (e.g. warping-based matching) may be based on one of these types
typedef enum uriVL::BaseRasterType uriVL::BaseRasterType
Enumerates the base image raster types.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef std::list<Blob*> uriVL::BlobList
A BlobList is a list of Blob pointers.
Definition at line 505 of file Blob.h.
typedef struct uriVL::BlobSearchParams uriVL::BlobSearchParams
Data structure that defines the conditions of a blob search.
typedef std::list<BlobTracker2D*> uriVL::BlobTracker2DList
Definition at line 121 of file BlobTracker2D.h.
typedef std::list<BlobTrackingState*> uriVL::BlobTrackingStateList
Definition at line 90 of file BlobTrackingState.h.
typedef enum uriVL::BorderWarpingMode uriVL::BorderWarpingMode
Enumerated type for the different modes of warping (as determined by outer grid point motion) supported.
This is just a first stab at organizing this.
typedef struct uriVL::CalibrationPair uriVL::CalibrationPair
Struct that stores a "calibration pair", that is, a 3D point and the corresponding image point observed.
typedef std::list<Cluster*> uriVL::ClusterList
Definition at line 103 of file Cluster.h.
typedef enum uriVL::ColorDifferenceMode uriVL::ColorDifferenceMode
Defines the three possible modes for computing image differences between color images:
AVERAGE_DIFFERENCE – average of the differences in the r, g, and b channels
MAX_DIFFERENCE – maximum of the differences in the r, g, and b channels
HUE_DIFFERENCE – hue difference rescaled to 0-255
Other modes will be added as more image types are implemented (e.g. L*a*b).
Note that image differences are always positive unsigned char
typedef enum uriVL::ColorGradientMode uriVL::ColorGradientMode
Diffferent ways of computing a color gradient.
typedef enum uriVL::ColorImageHistogramType uriVL::ColorImageHistogramType
Enumerated types for all kinds of histogram computations supported by this class.
RGB_HISTOGRAM - three separate histogram for r, g, b components
HSV_HISTOGRAM - three separate histograms for hue, sat, val
typedef struct uriVL::ColorRegion uriVL::ColorRegion
A ColorRegion is defined as a rectangular domain in the HSV space.
typedef enum uriVL::CompressionMode uriVL::CompressionMode
typedef std::list<HorizontalSegment*>::const_iterator uriVL::const_HSegIterator
Constant iterator for a list of pointers to HorizontalSegment objects.
Definition at line 66 of file Blob.h.
typedef std::list<const ImagePoint*> uriVL::ConstImagePoint_FList
Definition at line 245 of file ImagePoint_F.h.
typedef std::list<const ImagePoint*> uriVL::ConstImagePointList
Definition at line 241 of file ImagePoint.h.
typedef std::list<const ImageRect*> uriVL::ConstRectList
Definition at line 428 of file ImageRect.h.
typedef std::list<const Vector2D*> uriVL::ConstVector2DList
Definition at line 173 of file Vector2D.h.
typedef enum uriVL::ContourInitializer uriVL::ContourInitializer
Types of initial contour shapes for an active contour.
typedef enum uriVL::ConvergenceCriterion uriVL::ConvergenceCriterion
Criteria for deciding that an iteration has converged.
typedef enum uriVL::ConversionFromFloatMode uriVL::ConversionFromFloatMode
Enumerated type of modes for float to unsigned char gray conversion.
Enumerated type of modes for float to unsigned char conversion. Currently five conversion modes are supported:
- kPositiveFloat:     [0, MAX] --> [0, 255]
- kSignedFloat:       [MIN, MAX] --> [-MAX', MAX'] --> [0, 255], 0 at 128
- kRangeFloat:        [MIN, MAX] --> [0, 255]
- kSaturatedPositive  v < 0 set to 0, v > 255 set to 255, v otherwise
- kSaturatedSigned    0 at 128, v < -128 set to 0, v > 127 set to 127,
                      v otherwise
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef enum uriVL::ConversionToGrayMode uriVL::ConversionToGrayMode
Enumerated type of modes for color to gray conversion.
Enumerated type of modes for color to gray conversion. Currently three conversion modes are supported:
- kMaxFieldConversion:          gray = max(red, green, blue)
- kAverageConversion:           gray = (red + green + blue) / 3
- kWeightedAverageConversion:   gray = (wr*red + wg*green + wb*blue)
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef enum uriVL::DirectionResetMode uriVL::DirectionResetMode
Codes for the different ways to initialize/reset the search directions.
typedef enum uriVL::DirectionUpdateMethod uriVL::DirectionUpdateMethod
Codes for the various conjugate direction updating schemes supported.
typedef enum uriVL::DrawableInformationType uriVL::DrawableInformationType
Enumerated type that lists the type of data that could be found in a drawable object.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef struct uriVL::Edge uriVL::Edge
typedef std::list< ImageFeature * > uriVL::FeatureList
Definition at line 38 of file Corner.h.
typedef enum uriVL::FillingMode uriVL::FillingMode
A FillingMode specifies how part of an image that fall outside of color/gray regions should be filled in the output raster.
typedef void * uriVL::FSSpec
Placeholder until we define the FSSpec type (if ever)
Definition at line 35 of file VideoDestination.h.
typedef char* uriVL::GDHandle
Placeholder until we define the GDHandle type (if ever)
Definition at line 56 of file GraphWorld.h.
typedef enum uriVL::GraphicalComponentType uriVL::GraphicalComponentType
Basic types of graphical components.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Comments: The normal computation members of this class are only called when the objects are created or if/when their shape is modified (rare). Optimization is therefore not a major issue, which explains why I went overboard into decomposing the computation into very small pieces, each of which is defined as a function. Even if the compiler screws up the inlining, the penalty won't be too heavy.
Version history
2001/05/01 [jyh] last version of the old telerobotics code
2005/04/27 [jyh] adapted and brought into the uriVisionLib
2010/07/2x [jyh] massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef char* uriVL::GraphicsImportComponent
Placeholder until we define the GraphicsImportComponent type (if ever)
Definition at line 60 of file GraphWorld.h.
typedef struct uriVL::GrayRegion uriVL::GrayRegion
A GrayRegion is defined as a range of gray-level values.
typedef enum uriVL::HistogramDataType uriVL::HistogramDataType
Tists the types of data supported by this class.
typedef enum uriVL::HistogramRenderMode uriVL::HistogramRenderMode
Enumerated types for all histogram rendering modes supported by this class.
LIN_LIN - x and y both linear (classical plot)
LIN_LOG - x is linear, y is log
LOG_LIN - x kkis log, y is linear
LOG_LOG - x and y are both both log
LIN-POLAR - linear radius polar plot
LOG_POLAR - log-polar plot
typedef struct uriVL::HorizontalSegment uriVL::HorizontalSegment
This is the data structure returned by the filling algorithm: a linked list of horizontal segments constitutes a blob.
typedef std::list<HorizontalSegment*>::iterator uriVL::HSegIterator
Iterator for a list of pointers to HorizontalSegment objects.
Definition at line 62 of file Blob.h.
typedef enum uriVL::ImageFileType uriVL::ImageFileType
typedef std::list<ImagePoint*> uriVL::ImagePoint_FList
Definition at line 244 of file ImagePoint_F.h.
typedef std::list<ImagePoint*> uriVL::ImagePointList
Definition at line 240 of file ImagePoint.h.
typedef char* uriVL::ImageSequence
Placeholder until we define the GraphicsImportComponent type (if ever)
Definition at line 73 of file GraphWorld.h.
typedef enum uriVL::ImageWarperType uriVL::ImageWarperType
Enumarated type listing the types of image warpers supported by the library.
typedef enum uriVL::InnerWarpingMode uriVL::InnerWarpingMode
Enumerated type for the different modes of warping (as determined by inner grid point motion) supported.
This is just a first stab at organizing this. If a mode other than
typedef enum uriVL::LaplacianSobelForm uriVL::LaplacianSobelForm
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
This class has not been implemented yet
Note that currently the scaling parameter (1/2 for LAPLACIAN_SOBEL_FORM_2, 1/6 for LAPLACIAN_SOBEL_FORM_3) is not applied because the main use we have for the Laplacian in our applications is the determination of edge pixels. This may be changed in the future if a good case can be made for such a change.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Note that currently the scaling parameter (1/2 for LAPLACIAN_SOBEL_FORM_2, 1/6 for LAPLACIAN_SOBEL_FORM_3) is not applied because the main use we have for the Laplacian in our applications is the determination of edge pixels. This may be changed in the future if a good case can be made for such a change.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
typedef enum uriVL::LinearSolverRecordStatus uriVL::LinearSolverRecordStatus
Tri-state enumerated type generally set by a factorization method.
typedef std::deque< std::list<HorizontalSegment*> *> uriVL::LineSegDeque
The data structure used to hold of the segments of a blob: A deque that store the data doe each line of the blob, sorted top to bottom.
The info for each line is a (pointer to a) list of pointers to HorizontalSegment structs. The segments are sorted left to right on the line. This allows for pretty fast access on the blob
Definition at line 74 of file Blob.h.
typedef enum uriVL::MatchPairWeightingMode uriVL::MatchPairWeightingMode
Defines the weighting schemes for pairs of matching points that the registration algorithm supports.
typedef struct uriVL::MatrixIndicators uriVL::MatrixIndicators
Struct to hold all the TriState indicators of a matrix to create.
typedef enum uriVL::MoveDirection uriVL::MoveDirection
Displacement directions along the search spiral.
typedef char* uriVL::Movie
Placeholder until we define the Movie type.
Definition at line 48 of file GraphWorld.h.
typedef struct uriVL::NormalVector uriVL::NormalVector
Stores the normal vector at a point.
typedef int uriVL::OSErr
Placeholder until we define the OSErr type (if ever)
Definition at line 39 of file VideoDestination.h.
typedef std::list<Pattern2D* > uriVL::Pattern2DList
Definition at line 512 of file Pattern2D.h.
typedef enum uriVL::Pattern2DUpdateMode uriVL::Pattern2DUpdateMode
Standard update modes for a Pattern2D.
typedef list<PatternTracker2D*> uriVL::PatternTracker2DList
Definition at line 243 of file PatternTracker2D.h.
typedef std::list<PatternTrackingState*> uriVL::PatternTrackingStateList
Definition at line 92 of file PatternTrackingState.h.
typedef enum uriVL::Point2DMatchingMetric uriVL::Point2DMatchingMetric
Defines the different matching metric types supported.
typedef enum uriVL::Point2DPairRejectMode uriVL::Point2DPairRejectMode
Defines the matching pair rejection modes supported by the registration algorithm.
typedef enum uriVL::Point2DSelectionMode uriVL::Point2DSelectionMode
Defines the different data point selection modes supported.
typedef enum uriVL::QuadrantIndex uriVL::QuadrantIndex
enumerated type for indices of quadrants.
This is probably not the best place for that declaration.
typedef enum uriVL::ReadWriteStatus uriVL::ReadWriteStatus
typedef std::list<ImageRect*> uriVL::RectList
Definition at line 427 of file ImageRect.h.
typedef enum uriVL::ReferenceFrameShortcut uriVL::ReferenceFrameShortcut
Enum type that define shortcuts for accessing particular reference frames from an Entity3D.
typedef enum uriVL::Registration2DType uriVL::Registration2DType
Basic types of 2D registrations supported by this class.
typedef enum uriVL::ResolutionLevel uriVL::ResolutionLevel
typedef enum uriVL::RotationRef uriVL::RotationRef
typedef struct uriVL::ScaleParameter uriVL::ScaleParameter
typedef enum uriVL::SegmentDetectorType uriVL::SegmentDetectorType
typedef char* uriVL::SeqGrabComponent
Placeholder until we define the GraphicsImportComponent type (if ever)
Definition at line 64 of file GraphWorld.h.
typedef char* uriVL::SGChannel
Placeholder until we define the GraphicsImportComponent type (if ever)
Definition at line 69 of file GraphWorld.h.
typedef enum uriVL::StereoDisparityType uriVL::StereoDisparityType
Possible configurations for two cameras that can lead to a stereo disparity.
Generally in stereo systems one camera is the "left camera" and the other is the "right camera." In that case I may want to compute the disparity "left to right or right to left." But the cameras could also be disposed in a vertical configuration with a "top camera" and a "bottom camera," in which case the disparity could be computed "top to bottom" or "botom to top." Finally, for those other "Generic" configurations the disparity can be computed " from image 1 to image 2 or from image 2 to image 1.
typedef enum uriVL::StereoImageID uriVL::StereoImageID
Enumerated type for image identification.
typedef struct uriVL::StitchPattern uriVL::StitchPattern
typedef std::list<TrackingState *> uriVL::TrackingStateList
Definition at line 158 of file TrackingState.h.
typedef enum uriVL::TransformationQuality uriVL::TransformationQuality
typedef enum uriVL::TriState uriVL::TriState
Enum type for true/false/unknown ternary state variables.
This one is probably going to move to a more general position in the library.
typedef enum uriVL::TubeType uriVL::TubeType
Enum that defines what kind of partial tube we are dealing with.
typedef struct uriVL::URIVL_Rect uriVL::URIVL_Rect
For platforms not supported by Quicktime, we need to define Rect.
QuickTime sees a pixel as a little square that hangs between the points (xLeft, yTop) and (xLeft+1, yTop+1). This pixel occuppies the QuickTime Rect {xLeft, yTop, xLeft+1, yTop+1}. So the width and height of a QuickTime Rect are simply the differences between xBottom - xLeft and yBottom - yTop.
typedef std::list<Vector2D*> uriVL::Vector2DList
Definition at line 172 of file Vector2D.h.
typedef enum uriVL::VirtualRenderMode uriVL::VirtualRenderMode
typedef enum uriVL::VisibilityCode uriVL::VisibilityCode
typedef struct uriVL::VisibilityStatus uriVL::VisibilityStatus
Enumeration Type Documentation
enum uriVL::BalloonType
A balloon can be inflating or contracting depending on the sign of the "shrink force" applied to its vertices.
Enumerator
EXPANDING_BALLOON
CONTRACTING_BALLOON
Definition at line 43 of file ActiveContourDetector_balloon.h.
{
                                                                 EXPANDING_BALLOON = 0,
                                                                 CONTRACTING_BALLOON
         } BalloonType;
enum uriVL::BasePatternMatcher2DType
Defines the basic types of pattern matching supported by the library.
Other, more sophisticated pattern matching techniques (e.g. warping-based matching) may be based on one of these types
Enumerator
PATTERN_MATCHER_2D_CORR
PATTERN_MATCHER_2D_PART_CORR
PATTERN_MATCHER_2D_MEDIAN
PATTERN_MATCHER_2D_SCALED_DIFF
PATTERN_MATCHER_2D_NON_BASIC
Definition at line 37 of file PatternMatcher2D.h.
{
                     PATTERN_MATCHER_2D_CORR,
                     PATTERN_MATCHER_2D_PART_CORR,
                     PATTERN_MATCHER_2D_MEDIAN,
                     PATTERN_MATCHER_2D_SCALED_DIFF,
                     //
                     PATTERN_MATCHER_2D_NON_BASIC
      } BasePatternMatcher2DType;
enum uriVL::BaseRasterType
Enumerates the base image raster types.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kUndefRasterType
kBinaryRaster
kGrayRaster
kLongGrayRaster
kaRGB16Raster
kRGB24Raster
kaRGB32Raster
24 bits per pixel color (8r-8g-8b)
kRGBa32Raster
32 bits per pixel color (8r-8g-8b-8a)
Definition at line 30 of file GraphWorld.h.
{
             kUndefRasterType = -1,
             kBinaryRaster=1,
             kGrayRaster,        //  8 bits per pixel gray-level
             kLongGrayRaster,    //  12-16 bits per pixel gray-level
             kaRGB16Raster,      //  16 bits per pixel color (1a-5r-5g-5b)
             kRGB24Raster,       /// 24 bits per pixel color (8r-8g-8b)
             kaRGB32Raster,      //  32 bits per pixel color (8a-8r-8g-8b)
             kRGBa32Raster       /// 32 bits per pixel color (8r-8g-8b-8a)
     } BaseRasterType;
enum uriVL::BorderWarpingMode
Enumerated type for the different modes of warping (as determined by outer grid point motion) supported.
This is just a first stab at organizing this.
Enumerator
BORDER_FREE
BORDER_INWARD
BORDER_SLIDE
BORDER_FIXED
Definition at line 47 of file ImageWarper.h.
                                    {BORDER_FREE = 0,    //   no constraints on motion
                                     BORDER_INWARD,      //  grid border points can move inward
                                     BORDER_SLIDE,       //  grid border points slide along border
                                     BORDER_FIXED        //  grid border points are fixed
     } BorderWarpingMode;
enum uriVL::ColorDifferenceMode
Defines the three possible modes for computing image differences between color images:
AVERAGE_DIFFERENCE – average of the differences in the r, g, and b channels
MAX_DIFFERENCE – maximum of the differences in the r, g, and b channels
HUE_DIFFERENCE – hue difference rescaled to 0-255
Other modes will be added as more image types are implemented (e.g. L*a*b).
Note that image differences are always positive unsigned char
Enumerator
AVERAGE_DIFFERENCE
MAX_DIFFERENCE
HUE_DIFFERENCE
Definition at line 46 of file ImageArithmetics.h.
{
                                                                                 AVERAGE_DIFFERENCE,
                                                                                 MAX_DIFFERENCE,
                                                                                 HUE_DIFFERENCE
     } ColorDifferenceMode;
enum uriVL::ColorGradientMode
Diffferent ways of computing a color gradient.
Enumerator
GRAD_AVE_OF_COLOR_COMPONENTS
GRAD_LARGEST_COLOR_COMPONENT
Definition at line 28 of file ColorImageGradient.h.
{
                     GRAD_AVE_OF_COLOR_COMPONENTS = 0,   //  average red, green, blue grads
                     GRAD_LARGEST_COLOR_COMPONENT        //  r-g-b grad with largest norm
     } ColorGradientMode;
enum uriVL::ColorImageHistogramType
Enumerated types for all kinds of histogram computations supported by this class.
RGB_HISTOGRAM - three separate histogram for r, g, b components
HSV_HISTOGRAM - three separate histograms for hue, sat, val
Enumerator
DEFAULT_TYPE
RGB_HISTOGRAM
HSV_HISTOGRAM
Definition at line 33 of file ColorImageHistogram.h.
{
                                     DEFAULT_TYPE = 100,
                                     RGB_HISTOGRAM,
                                     HSV_HISTOGRAM
     } ColorImageHistogramType;
enum uriVL::CompressionMode
Enumerator
kUncompressed
kRLE4Bits
kRLE8Bits
Definition at line 31 of file ImageReader.h.
     {
         kUncompressed = 0,
         kRLE4Bits,
         kRLE8Bits
     } CompressionMode;
enum uriVL::ContourInitializer
Types of initial contour shapes for an active contour.
Enumerator
ELLIPTIC_CONTOUR
BOX_CONTOUR
Definition at line 34 of file Contour.h.
{
                                                                                         ELLIPTIC_CONTOUR = 0,
                                                                                         BOX_CONTOUR
         } ContourInitializer;
enum uriVL::ConvergenceCriterion
Criteria for deciding that an iteration has converged.
Enumerator
SUM_OF_ABSOLUTE_DISPLCT
SUM_OF_SQUARED_DISPLCT
AVERAGE_DISPLCT
MAXIMUM_DISPLCT
Definition at line 28 of file IterationStatus.h.
{
                                                                                 SUM_OF_ABSOLUTE_DISPLCT = 0,
                                                                                 SUM_OF_SQUARED_DISPLCT,
                                                                                 AVERAGE_DISPLCT,
                                                                                 MAXIMUM_DISPLCT
         } ConvergenceCriterion;
enum uriVL::ConversionFromFloatMode
Enumerated type of modes for float to unsigned char gray conversion.
Enumerated type of modes for float to unsigned char conversion. Currently five conversion modes are supported:
- kPositiveFloat:     [0, MAX] --> [0, 255]
- kSignedFloat:       [MIN, MAX] --> [-MAX', MAX'] --> [0, 255], 0 at 128
- kRangeFloat:        [MIN, MAX] --> [0, 255]
- kSaturatedPositive  v < 0 set to 0, v > 255 set to 255, v otherwise
- kSaturatedSigned    0 at 128, v < -128 set to 0, v > 127 set to 127,
                      v otherwise
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kUndefFloatConv
kSignedFloat
kPositiveFloat
kRangeFloat
kSaturatedPositive
kSaturatedSigned
Definition at line 64 of file RasterImage.h.
{
                                             kUndefFloatConv = -1,
                                             kSignedFloat = 0,
                                             kPositiveFloat,
                                             kRangeFloat,
                                             kSaturatedPositive,
                                             kSaturatedSigned
     } ConversionFromFloatMode;
enum uriVL::ConversionToGrayMode
Enumerated type of modes for color to gray conversion.
Enumerated type of modes for color to gray conversion. Currently three conversion modes are supported:
- kMaxFieldConversion:          gray = max(red, green, blue)
- kAverageConversion:           gray = (red + green + blue) / 3
- kWeightedAverageConversion:   gray = (wr*red + wg*green + wb*blue)
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kMaxFieldConversion
kAverageConversion
kWeightedAverageConversion
Definition at line 41 of file RasterImage.h.
{
                                             kMaxFieldConversion = 0,
                                             kAverageConversion,
                                             kWeightedAverageConversion
     } ConversionToGrayMode;
enum uriVL::DirectionResetMode
Codes for the different ways to initialize/reset the search directions.
Enumerator
CANONICAL_DIRECTIONS
canonical (coordinate) directions
RANDOM_ORTHOGONAL_DIRECTIONS
generate mutually orthogonal unit vectors
USER_SPECIFIED_DIRECTIONS
Uses directions set by the user.
If no directions were set, then canonical directions will be used instead
Definition at line 50 of file NonlinearOptimizerND_conjDir.h.
     {
                 /** canonical (coordinate) directions
                  */
         CANONICAL_DIRECTIONS = 0,
                 /** generate mutually orthogonal unit vectors
                  */
         RANDOM_ORTHOGONAL_DIRECTIONS,
                 /** Uses directions set by the user.  If no directions were set, then canonical
                  *      directions will be used instead
                  */
         USER_SPECIFIED_DIRECTIONS
     } DirectionResetMode;
enum uriVL::DirectionUpdateMethod
Codes for the various conjugate direction updating schemes supported.
Enumerator
NO_UPDATE
implements coordinate descent
POWELL_UN_IS_XN_X0
Powell alg., new direction is displacement over a full cycle.
POWELL_DISCARD_LARGEST_DECREASE_DIR
Powell, alg., discard direction of largest decrease.
Definition at line 31 of file NonlinearOptimizerND_conjDir.h.
     {
                 /** implements coordinate descent
                  */
         NO_UPDATE = 0,
         /** Powell alg., new direction is displacement over a full cycle
                  */
                 POWELL_UN_IS_XN_X0,
         /** Powell, alg., discard direction of largest decrease
                  */
                 POWELL_DISCARD_LARGEST_DECREASE_DIR
     } DirectionUpdateMethod;
enum uriVL::DrawableInformationType
Enumerated type that lists the type of data that could be found in a drawable object.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kUndetermined
kDense
kSparse
kInterpolated
kDenseUncertain
kSparseUncertain
kInterpolatedUncertain
Definition at line 35 of file DrawableObject2D.h.
     {
             kUndetermined = -1,
             kDense = 0,
             kSparse,
             kInterpolated,
             kDenseUncertain,
             kSparseUncertain,
             kInterpolatedUncertain
     } DrawableInformationType;
enum uriVL::ErrorCode
List of all the error codes for the library.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kNoError
kUnknownError
kNoCode
kNullParameterError
kInvalidReferenceError
kInvalidParameterError
kNoninitializedObjectError
kFunctionNotImplemented
kCaseNotImplemented
kMemoryCopyError
kMiscError
kNullArrayError
kInvalidLockAccess
kAccessToLockedData
kUriBaseError
kRasterImageError
kNullRasterImageError
kNullVectorFieldError
kRasterAllocationFailure
kRasterInvalidDimensions
kRasterDimensionsDontMatch
kNullRasterError
kNullRectangleError
kNullImagePointError
kInvalidRectangleError
kInvalidRasterType
kGWorldRelatedError
kGWorldAllocationError
kGWorldIsNullError
kGWorldNullPixMapError
kGWorldInvalidPixelDepth
kGWorldIncompatiblePixelDepth
kGWorldInvalidCLUT
kGWorldCannotLockPixels
kGWorldCannotUnlockPixels
kQuickTime_relatedError
kQuickTimeNotInstalled
kPixMapLockFailed
kEnterMoviesError
kImageProcessingError
kFilterAllocationError
kNullLabelRasterError
kNullTransformation2D
kInvalidTransformation2D
kComputerVisionError
kNullTransformation3D
kInvalidTransformation3D
kNullEntity3D
kInvalidEntity3D
kCameraError
kInvalidCameraType
kInvalidIntrisicParameterType
kStereoMatchingError
kTrackingError
kVideoSourceError
kVideoSourceNotSetError
kVideoSourceFileNotFoundError
kVideoInitializingError
kOpenVideoComponentError
kInvalidGrabRectDimensions
kVideoBufferAllocError
kVideoAcquisitionError
kVideoDigitizerComponentError
kUnsupportedImageFormatError
kMovieEditingError
kInitializeMovieError
kMovieToolboxError
kMovieStartPointError
kFileIOError
kDirectoryNullPathError
kFileNullPathError
kDirectoryListError
kDirectoryNotFoundError
kFileNotFoundError
kDirectoryCloseError
kFileOpenWriteError
kFileOpenReadError
kFileCloseError
kWrongFileTypeError
kUnknownFileTypeError
kFileReadingError
kFileWritingError
kEndOfFileError
kNumericalError
kMatrixCalculationError
kNullMatrixError
kMatrixIncorrectDimensionsError
kSingularMatrixError
kIllConditionedMatrixError
kCalculusError
kNullFunctionError
kDataRangeError
kGraphicsError
kOpenGLNumAllocError
kOpenGL_relatedError
kOpenGLDrawModuleError
kGLUT_relatedError
kMaxErrorCodeID
Definition at line 33 of file ErrorReport.h.
     {
         kNoError = 0,
         //
                 kUnknownError = 1,
                 kNoCode = 2,                        //  Generic error
                 //
         kNullParameterError,
         kInvalidReferenceError,
         kInvalidParameterError,
         kNoninitializedObjectError,
         kFunctionNotImplemented,
         kCaseNotImplemented,
                 kMemoryCopyError,
         kMiscError,
         kNullArrayError,
         kInvalidLockAccess,
         kAccessToLockedData,
         //
         //----------------------------
         //
         kUriBaseError = 1000,               //  uriBase-related errors ---------------> 1xxx
         //
         kRasterImageError = 1100,               //  Error in the bowels of RasterImage
         kNullRasterImageError,
         kNullVectorFieldError,
         kRasterAllocationFailure = 1110,
         kRasterInvalidDimensions,
         kRasterDimensionsDontMatch = 1120,
         kNullRasterError = 1130,
         kNullRectangleError = 1140,
         kNullImagePointError,
         kInvalidRectangleError,
         kInvalidRasterType,
         //
         kGWorldRelatedError = 1200,
         kGWorldAllocationError = 1201,
         kGWorldIsNullError = 1202,
         kGWorldNullPixMapError,
         kGWorldInvalidPixelDepth = 1210,        //  the pixel depth is not 8, 16, [24], or 32
         kGWorldIncompatiblePixelDepth,          //  Mac OS & 24 bit GWorlds <--> movies
         kGWorldInvalidCLUT = 1220,
         kGWorldCannotLockPixels = 1230,
         kGWorldCannotUnlockPixels = 1231,
         //
         kQuickTime_relatedError = 1500,         //  QuickTime related error codes --->  14xx
         kQuickTimeNotInstalled,
         kPixMapLockFailed,
         kEnterMoviesError,
         //
         //----------------------------
         //
         kImageProcessingError = 2000,       //  uriImageProcessing error codes -------> 2xxx
         //
         kFilterAllocationError,
         kNullLabelRasterError,
         //
         kNullTransformation2D = 2100,
         kInvalidTransformation2D = 2110,
         //
         //----------------------------
         //
         kComputerVisionError = 3000,        //  uriComputerVision error codes --------> 3xxx
         //
         kNullTransformation3D = 3100,           //  transformation3D-related errors --> 31xx
         kInvalidTransformation3D,
         kNullEntity3D = 3110,
         kInvalidEntity3D,
         //
         kCameraError = 3200,                    //  camera-related errors ------------> 32xx
         kInvalidCameraType = 3210,
         kInvalidIntrisicParameterType = 3220,
         //
         kStereoMatchingError = 3400,            //  stereo-related errors ------------> 34xx
         //
         //----------------------------
         //
         kTrackingError = 4000,              //  uriTracking error codes --------------> 4xxx
         //
         //----------------------------
         //
         kVideoSourceError = 5000,           //  uriVideoSource error codes -----------> 5xxx
         kVideoSourceNotSetError = 5010,
         kVideoSourceFileNotFoundError = 5020,
         //
         kVideoInitializingError = 5100,
                 kOpenVideoComponentError = 5110,
                 kInvalidGrabRectDimensions = 5120,
         //
         kVideoBufferAllocError = 5200,
         //
         kVideoAcquisitionError = 5300,
                 kVideoDigitizerComponentError = 5310,
         //
         kUnsupportedImageFormatError = 5400,
         //
         //----------------------------
         //
         kMovieEditingError = 6000,          //  uriMovieEditing error codes ----------> 6xxx
         kInitializeMovieError,
         kMovieToolboxError,
         kMovieStartPointError,
         kFileIOError = 6100,                    //  File IO error codes --------------> 61xx
                 kDirectoryNullPathError,
                 kFileNullPathError,
                 kDirectoryListError,
         kDirectoryNotFoundError = 6120,                         //      Not found errors -------------> 612x
         kFileNotFoundError,
                 kDirectoryCloseError = 6130,                            //      Open-close errors ------------> 613x
         kFileOpenWriteError,
         kFileOpenReadError,
                 kFileCloseError,
         kWrongFileTypeError = 6140,                                     //      File type errors -------------> 614x
         kUnknownFileTypeError,
         kFileReadingError = 6150,                                       //      Read-write errors ------------> 615x
         kFileWritingError,
         kEndOfFileError,
         //
         //----------------------------
         //
         kNumericalError = 7000,             //  uriNumerical error codes -------------> 7xxx
         //
         kMatrixCalculationError = 7100,          //  Matrix calculation error codes --> 71xx
         kNullMatrixError,
         kMatrixIncorrectDimensionsError,
         kSingularMatrixError,
         kIllConditionedMatrixError,
         //
         kCalculusError = 7200,
         kNullFunctionError,
         kDataRangeError,
         //
         //
         //----------------------------
         //
         kGraphicsError = 8000,              //  uriGraphics error codes --------------> 8xxx
         kOpenGLNumAllocError,
         //
         kOpenGL_relatedError = 8100,            //  OpenGL-related error codes -------> 81xx
         kOpenGLDrawModuleError,
         //
         kGLUT_relatedError = 8200,              //  GLUT-related error codes ---------> 82xx
         //
         //----------------------------
         //
         //
         kMaxErrorCodeID
     };
enum uriVL::FillingMode
A FillingMode specifies how part of an image that fall outside of color/gray regions should be filled in the output raster.
Enumerator
kIdentityFill
kOrigColorFill
kOrigGrayFill
kBlackFill
kWhiteFill
kMediumGrayFill
Definition at line 28 of file ColorRegions.h.
     {
         kIdentityFill = 0,
         kOrigColorFill,
         kOrigGrayFill,
         kBlackFill,
         kWhiteFill,
         kMediumGrayFill
     } FillingMode;
enum uriVL::GraphicalComponentType
Basic types of graphical components.
This code is derived from the one I wrote for my personal "multiple-site" version of the SMART telerobotics project I did while at Ecole Poytechnique de Montreal. I co-wrote (with the interns I supervised) the initial OpenGL C code, then rewrote the whole thing as C++ classes and defined my own 3D format (mostly useful to define models of robots) to match these classes. There is absolutely nothing left of the original stuff, except for the file format and object loader, which were mine to begin with.
Older versions of this code have been used (and will continued to be used) as demos for my computer graphics courses.
Comments: The normal computation members of this class are only called when the objects are created or if/when their shape is modified (rare). Optimization is therefore not a major issue, which explains why I went overboard into decomposing the computation into very small pieces, each of which is defined as a function. Even if the compiler screws up the inlining, the penalty won't be too heavy.
Version history
2001/05/01 [jyh] last version of the old telerobotics code
2005/04/27 [jyh] adapted and brought into the uriVisionLib
2010/07/2x [jyh] massive cleanup of C++ code, with 0-warning objective
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
kOpenBoxObject
kClosedBoxObject
kOpenCylinderObject
kClosedCylinderObject
kTubularSectionObject
kOpenHalfCylinderObject
kClosedHalfCylinderObject
kOpenPrismObject
kClosedPrismObject
kOpenConeObject
kClosedConeObject
kOpenHalfConeObject
kClosedHalfConeObject
kPolyhedronObject
kNbComponentTypes
Definition at line 85 of file GraphicComponent3D.h.
     {
         kOpenBoxObject = 0,
         kClosedBoxObject,
         kOpenCylinderObject,
         kClosedCylinderObject,
         kTubularSectionObject,
         kOpenHalfCylinderObject,
         kClosedHalfCylinderObject,
         kOpenPrismObject,
         kClosedPrismObject,
         kOpenConeObject,
         kClosedConeObject,
         kOpenHalfConeObject,
         kClosedHalfConeObject,
         kPolyhedronObject,
         //
         kNbComponentTypes
     }
enum uriVL::HistogramDataType
Tists the types of data supported by this class.
Enumerator
NO_TYPE_HIST
FLOAT_HIST
INT_HIST
UCHAR_HIST
Definition at line 60 of file Histogram.h.
{
                                         NO_TYPE_HIST = -1,
                                         FLOAT_HIST = 300,
                                         INT_HIST,
                                         UCHAR_HIST
     } HistogramDataType;
enum uriVL::HistogramRenderMode
Enumerated types for all histogram rendering modes supported by this class.
LIN_LIN - x and y both linear (classical plot)
LIN_LOG - x is linear, y is log
LOG_LIN - x kkis log, y is linear
LOG_LOG - x and y are both both log
LIN-POLAR - linear radius polar plot
LOG_POLAR - log-polar plot
Enumerator
LIN_LIN
LIN_LOG
LIN_POLAR
LOG_POLAR
Definition at line 48 of file Histogram.h.
{
                                         LIN_LIN = 200,
                                         LIN_LOG,
                                         //LOG_LIN,
                                         //LOG_LOG,
                                         LIN_POLAR,
                                         LOG_POLAR
     } HistogramRenderMode;
enum uriVL::ImageFileType
Enumerator
kUnknownImgFileType
kTGA
kPPM
kPGM
kBMP
kNbImageFileExtensions
Definition at line 38 of file ImageReader.h.
     {
         kUnknownImgFileType = -1,
         kTGA,
         kPPM,                   //  24-bit color image
         kPGM,                   //  8-bit gray-level image
         kBMP,
         //
         kNbImageFileExtensions
     } ImageFileType;
enum uriVL::ImageWarperType
Enumarated type listing the types of image warpers supported by the library.
Enumerator
GL_WARPER
Definition at line 31 of file ImageWarper.h.
                                  {  GL_WARPER = 0
     } ImageWarperType;
enum uriVL::InnerWarpingMode
Enumerated type for the different modes of warping (as determined by inner grid point motion) supported.
This is just a first stab at organizing this. If a mode other than
Enumerator
INNER_FREE
INNER_TOPOLOGY
INNER_CONVEX
INNER_BOUNDS
Definition at line 38 of file ImageWarper.h.
                                   { INNER_FREE = 0,  //  unconstrained inner grid point motion
                                     INNER_TOPOLOGY,  //  no grid crossings
                                     INNER_CONVEX,    //  grid quads must remain convex
                                     INNER_BOUNDS     //  rectangular bounds for all grid points
     } InnerWarpingMode;
enum uriVL::LaplacianSobelForm
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
Note that currently the scaling parameter (1/2 for LAPLACIAN_SOBEL_FORM_2, 1/6 for LAPLACIAN_SOBEL_FORM_3) is not applied because the main use we have for the Laplacian in our applications is the determination of edge pixels. This may be changed in the future if a good case can be made for such a change.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
LAPLACIAN_SOBEL_FORM_1
LAPLACIAN_SOBEL_FORM_2
LAPLACIAN_SOBEL_FORM_3
LAPLACIAN_SOBEL_FORM_1
LAPLACIAN_SOBEL_FORM_2
LAPLACIAN_SOBEL_FORM_3
Definition at line 36 of file ImageLaplacian_Sobel.h.
     {
                                         //      0    1   0
         LAPLACIAN_SOBEL_FORM_1 = 1,     //      1   -4   1
                                         //      0    1   0
                                         //      1    0   1
         LAPLACIAN_SOBEL_FORM_2 = 2,     //      0   -4   0    *   1/2
                                         //      1    0   1
                                         //      1    4   1
         LAPLACIAN_SOBEL_FORM_3 = 3      //      4   -20  4    *   1/6
                                         //      1    4   1
     } LaplacianSobelForm;
enum typedef enum uriVL::LaplacianSobelForm uriVL::LaplacianSobelForm
Forms of the "Sobel" Laplacian operators implemented in the ImageLaplacian_Sobel class.
This class has not been implemented yet
Note that currently the scaling parameter (1/2 for LAPLACIAN_SOBEL_FORM_2, 1/6 for LAPLACIAN_SOBEL_FORM_3) is not applied because the main use we have for the Laplacian in our applications is the determination of edge pixels. This may be changed in the future if a good case can be made for such a change.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Note that currently the scaling parameter (1/2 for LAPLACIAN_SOBEL_FORM_2, 1/6 for LAPLACIAN_SOBEL_FORM_3) is not applied because the main use we have for the Laplacian in our applications is the determination of edge pixels. This may be changed in the future if a good case can be made for such a change.
Author
jean-yves herve', 3D Group, Department of Computer Science and Statistics, University of Rhode Island
Enumerator
LAPLACIAN_SOBEL_FORM_1
LAPLACIAN_SOBEL_FORM_2
LAPLACIAN_SOBEL_FORM_3
LAPLACIAN_SOBEL_FORM_1
LAPLACIAN_SOBEL_FORM_2
LAPLACIAN_SOBEL_FORM_3
Definition at line 38 of file ColorImageLaplacian_Sobel.h.
     {
                                         //      0    1   0
         LAPLACIAN_SOBEL_FORM_1 = 1,     //      1   -4   1
                                         //      0    1   0
                                         //      1    0   1
         LAPLACIAN_SOBEL_FORM_2 = 2,     //      0   -4   0    *   1/2
                                         //      1    0   1
                                         //      1    4   1
         LAPLACIAN_SOBEL_FORM_3 = 3      //      4   -20  4    *   1/6
                                         //      1    4   1
     } LaplacianSobelForm;
enum uriVL::LinearSolverRecordStatus
Tri-state enumerated type generally set by a factorization method.
Enumerator
UNKNOWN_STATUS
REGULAR_MATRIX
SINGULAR_MATRIX
ILL_CONDITIONED_MATRIX
LINEAR_SOLVER_SUCCEDED
LINEAR_SOLVER_FAILED
Definition at line 27 of file LinearSolverRecord.h.
{
                                             UNKNOWN_STATUS = -1,
                                                                                         //
                                                                                         REGULAR_MATRIX = 0,
                                             SINGULAR_MATRIX = 1,
                                             ILL_CONDITIONED_MATRIX = 2,
                                                                                         //
                                                                                         LINEAR_SOLVER_SUCCEDED = 3,
                                                                                         LINEAR_SOLVER_FAILED = 4
     } LinearSolverRecordStatus;
enum uriVL::MatchPairWeightingMode
Defines the weighting schemes for pairs of matching points that the registration algorithm supports.
Enumerator
EQUAL_WEIGHT
DISTANCE_BASED_WEIGHT
ANGLE_BASED_WEIGHT
COLOR_BASED_WEIGHT
Definition at line 98 of file Registration2D.h.
     {
         EQUAL_WEIGHT = 0,           //  all retained pairs weigh 1
         DISTANCE_BASED_WEIGHT,      //  1 - d(p, q) / dMax
         ANGLE_BASED_WEIGHT,         //  1 - normal(p) . normal(q)
         COLOR_BASED_WEIGHT          //  When a color or gray level was assigned to each point,
                                     //      1 - |col(p) - col(q)|/range(col)
     } MatchPairWeightingMode;
enum uriVL::MoveDirection
Displacement directions along the search spiral.
Enumerator
MOVE_LEFT
MOVE_DOWN
MOVE_RIGHT
MOVE_UP
Definition at line 41 of file BlobFinder.h.
     {
         MOVE_LEFT = 0,
         MOVE_DOWN,
         MOVE_RIGHT,
         MOVE_UP
     } MoveDirection;
enum uriVL::Pattern2DUpdateMode
Standard update modes for a Pattern2D.
Enumerator
REPLACE_PATTERN
UNION_BLOBS_REPLACE_IMG
UNION_BLOBS_AVG_IMG
INTERSECT_BLOBS_REPLACE_IMG
INTERSECT_BLOBS_AVG_IMG
AVERAGE_PATTERNS
Definition at line 34 of file Pattern2D.h.
{
                                         REPLACE_PATTERN = 0,
                                         UNION_BLOBS_REPLACE_IMG,
                                         UNION_BLOBS_AVG_IMG,
                                         INTERSECT_BLOBS_REPLACE_IMG,
                                         INTERSECT_BLOBS_AVG_IMG,
                                         AVERAGE_PATTERNS
     } Pattern2DUpdateMode;
enum uriVL::Point2DMatchingMetric
Defines the different matching metric types supported.
Enumerator
POINT_POINT_DISTANCE
POINT_POINT_NORMAL_DISTANCE
POINT_POINT_DISTANCE_SQ
POINT_POINT_NORMAL_DISTANCE_SQ
POINT_EDGE_DISTANCE
POINT_EDGE_NORMAL_DISTANCE
POINT_EDGE_DISTANCE_SQ
POINT_EDGE_NORMAL_DISTANCE_SQ
Definition at line 58 of file Registration2D.h.
     {
         POINT_POINT_DISTANCE,           //  Euclidean distance between data point and transformed ref point
         POINT_POINT_NORMAL_DISTANCE,    //  Euclidean distance between data point and transformed ref point
                                         //      measured along normal at data point (only for contour reg)
         POINT_POINT_DISTANCE_SQ,        //  Square of Euclidean distance between data point and transformed ref point
         POINT_POINT_NORMAL_DISTANCE_SQ, //  Square of Euclidean distance between data point and transformed ref point
                                         //      measured along normal at data point (only for contour reg)
         POINT_EDGE_DISTANCE,            //  Euclidean distance between data point and transformed edge
                                         //      (only for contour reg)
         POINT_EDGE_NORMAL_DISTANCE,     //  Euclidean distance between data point and transformed edge
                                         //      measured along normal at data point (only for contour reg)
         POINT_EDGE_DISTANCE_SQ,         //  Square of Euclidean distance between data point and transformed edge
                                         //      (only for contour reg)
         POINT_EDGE_NORMAL_DISTANCE_SQ   //  Square of Euclidean distance between data point and transformed edge
                                         //      measured along normal at data point (only for contour reg)
     } Point2DMatchingMetric;
enum uriVL::Point2DPairRejectMode
Defines the matching pair rejection modes supported by the registration algorithm.
Enumerator
RETAIN_ALL_PAIRS
THRESHOLD_BASED_REJECT
PERCENTAGE_REJECT
STANDARD_DEV_REJECT
NEIGHBOR_INCONSISTENCY_REJECT
Definition at line 82 of file Registration2D.h.
     {
         RETAIN_ALL_PAIRS,               //  retain all match pairs
         THRESHOLD_BASED_REJECT,         //  reject pair (p, q) if d(p, q) > D
         PERCENTAGE_REJECT,              //  reject n% worst matches
         STANDARD_DEV_REJECT,            //  reject (p, q) id d(p, q) > s StandardDev(d(p', q'))
         NEIGHBOR_INCONSISTENCY_REJECT   //  reject (p, q) if for more than n out m match pairs (p', q')
                                         //     |d(p, p') - d(q,q')| > s . max(d(p, p'), d(q,q'))
     } Point2DPairRejectMode;
enum uriVL::Point2DSelectionMode
Defines the different data point selection modes supported.
Enumerator
SELECT_ALL_POINTS
SELECT_RANDOM_POINT_SAMPLE
MAX_GRADIENT_DISTRIBUTION
Definition at line 46 of file Registration2D.h.
     {
         SELECT_ALL_POINTS = 0,          //  all data points are used
         SELECT_RANDOM_POINT_SAMPLE,     //  a different random sample of points is used at each iteration
         MAX_GRADIENT_DISTRIBUTION       //  points chosen so that the distrution of normal vector directions
                                         //      is as large as possible
     } Point2DSelectionMode;
enum uriVL::QuadrantIndex
enumerated type for indices of quadrants.
This is probably not the best place for that declaration.
Enumerator
UPPER_LEFT_QUAD
UPPER_RIGHT_QUAD
LOWER_LEFT_QUAD
LOWER_RIGHT_QUAD
Definition at line 42 of file Blob.h.
     {
         UPPER_LEFT_QUAD = 0,
         UPPER_RIGHT_QUAD,
         LOWER_LEFT_QUAD,
         LOWER_RIGHT_QUAD
     } QuadrantIndex;
enum uriVL::ReadWriteStatus
Enumerator
R_W_ACCESS
Definition at line 573 of file uriVisionLib.h.
         {
                                     R_W_ACCESS
     } ReadWriteStatus;
enum uriVL::ReferenceFrameShortcut
Enum type that define shortcuts for accessing particular reference frames from an Entity3D.
Enumerator
WORLD_FRAME
VIEWER_FRAME
PARENT_FRAME
Definition at line 31 of file ReferenceFrame3D.h.
{
                                                                         WORLD_FRAME = 0,
                                                                         VIEWER_FRAME = 1,       //      current GL camera
                                                                         PARENT_FRAME
         } ReferenceFrameShortcut;
enum uriVL::Registration2DType
Basic types of 2D registrations supported by this class.
Enumerator
RIGID_LINEAR_REG_2D
RIGID_NONLINEAR_REG_2D
AFFINE_REG_2D
Definition at line 34 of file Registration2D.h.
     {
         RIGID_LINEAR_REG_2D = 0,        //  rigid (Euclidean), using cos(theta) sin(theta) as independent variables
         RIGID_NONLINEAR_REG_2D,         //  rigid (Euclidean), using theta variable
         AFFINE_REG_2D                   //  affine registration (6 parameters of transf. matrix as variables)
         //  WARPING_REG_2D
     } Registration2DType;
enum uriVL::ResolutionLevel
Enumerator
kVeryHighResolution
kFineResolution
kMediumResolution
kCoarseResolution
kVeryLowResolution
Definition at line 46 of file GraphicComponent3D.h.
     {
         kVeryHighResolution,
         kFineResolution,
         kMediumResolution,
         kCoarseResolution,
         kVeryLowResolution
     }
enum uriVL::Result
Enumerator
TARGET_MATCH_LIST
TARGET_FOUND
TARGET_NOT_FOUND
WRONG_TARGET_FOUND
Definition at line 40 of file TrackingState.h.
                    {
                 TARGET_MATCH_LIST,
                 TARGET_FOUND,
                 TARGET_NOT_FOUND,
                 WRONG_TARGET_FOUND
         };
enum uriVL::RotationRef
Enumerator
MATRIX_REF
QUATERNION_REF
ROLL_PITCH_YAW_REF
EULER_ANGLES_REF
Definition at line 27 of file Rotation3D.h.
{
             MATRIX_REF = 0,
             QUATERNION_REF,
             ROLL_PITCH_YAW_REF,
             EULER_ANGLES_REF
     } RotationRef;
enum uriVL::SegmentDetectorType
Enumerator
kVertical
kHorizontal
Definition at line 29 of file SegmentDetector.h.
     {
             kVertical = 0,
             kHorizontal
     } SegmentDetectorType;
enum uriVL::StereoDisparityType
Possible configurations for two cameras that can lead to a stereo disparity.
Generally in stereo systems one camera is the "left camera" and the other is the "right camera." In that case I may want to compute the disparity "left to right or right to left." But the cameras could also be disposed in a vertical configuration with a "top camera" and a "bottom camera," in which case the disparity could be computed "top to bottom" or "botom to top." Finally, for those other "Generic" configurations the disparity can be computed " from image 1 to image 2 or from image 2 to image 1.
Enumerator
HORIZONTAL_L2R
HORIZONTAL_R2L
VERTICAL_T2B
VERTICAL_B2T
GENERIC_1_2
GENERIC_2_1
Definition at line 35 of file StereoDisparity.h.
{
                                                                                 HORIZONTAL_L2R = 0,
                                                                                 HORIZONTAL_R2L,
                                                                                 VERTICAL_T2B,
                                                                                 VERTICAL_B2T,
                                                                                 //      In the following 2 configs, one camera is artitrarily
                                                                                 //      identified as "left camera" and the other as "right camera"
                                                                                 GENERIC_1_2,
                                                                                 GENERIC_2_1
         } StereoDisparityType;
enum uriVL::StereoImageID
Enumerated type for image identification.
Enumerator
LEFT_IMAGE
RIGHT_IMAGE
Definition at line 30 of file StereoPair.h.
{
                 LEFT_IMAGE = 0,
                 RIGHT_IMAGE = 1
         } StereoImageID;
enum uriVL::TransformationQuality
Enumerator
kUnknown
kDefinition
kReliable
kUnreliable
Definition at line 26 of file Transformation2D.h.
{
                                     kUnknown = -1,
                                     kDefinition = 0,
                                     kReliable,
                                     kUnreliable
     } TransformationQuality;
enum uriVL::TriState
Enum type for true/false/unknown ternary state variables.
This one is probably going to move to a more general position in the library.
Enumerator
IS_FALSE
IS_TRUE
IS_UNKNOWN
Definition at line 583 of file uriVisionLib.h.
         {
                                  IS_FALSE = 0,
                                  IS_TRUE = 1,   //      within STD_RELATIVE_TOLERANCE
                                  IS_UNKNOWN = -1
     } TriState;
enum uriVL::TubeType
Enum that defines what kind of partial tube we are dealing with.
Enumerator
FULL_TUBE
NEARLY_FULL_TUBE
ABOUT_3_QUARTER_TUBE
ABOUT_HALF_TUBE
ABOUT_QUARTER_CUBE
LESS_THAN_QUARTER_CUBE
Definition at line 29 of file TubularSection3D.h.
{
                                                         FULL_TUBE = -1,
                                                         //
                                                         NEARLY_FULL_TUBE = 0,
                                                         ABOUT_3_QUARTER_TUBE,
                                                         ABOUT_HALF_TUBE,
                                                         ABOUT_QUARTER_CUBE,
                                                         LESS_THAN_QUARTER_CUBE
         } TubeType;
enum uriVL::VirtualRenderMode
Enumerator
INTERPOSE
GEOMETRY_TEST
Definition at line 41 of file VirtualPoint3D.h.
     {
             INTERPOSE = 1,
             GEOMETRY_TEST = 2
     } VirtualRenderMode;
enum uriVL::VisibilityCode
Enumerator
UNKNOWN
VISIBLE
INVISIBLE
CONTACT
Definition at line 32 of file VirtualPoint3D.h.
     {
             UNKNOWN = -1,
             VISIBLE,
             INVISIBLE,
             CONTACT
     } VisibilityCode;
Function Documentation
void uriVL::drawCenteredOval (float cx, float cy, float width, float height, float angle = 0.f)
Draws an ellipse specified by the coordinates of it center, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
cx x coordinate of the ellipse's center
cy y coordinate of the ellipse's center
width the ellipse's major diameter
height the ellipse's minor diameter
angle orientation of the ellipse
Definition at line 1095 of file DrawableObject2D.cpp.
References drawCircularDot().
 {
         const float HALF_WIDTH = 0.5f*width, HALF_HEIGHT = 0.5f*height;
         glPushMatrix();
                 glTranslatef(cx, cy, 0.f);
                 glRotatef(angle, 0.f, 0.f, 1.f);
                 glScalef(HALF_WIDTH, HALF_HEIGHT, 1.f);
                 drawCircularDot();
         glPopMatrix();
 }
void uriVL::drawCenteredRect (float cx, float cy, float width, float height, float angle = 0.f)
Draws the contour of a rectangle specified by the coordinates of it center, width, and height, and by a rotation angle (in degree).
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
cx x coordinate of the rectangle's center
cy y coordinate of the rectangle's center
width width of the rectangle
height height of the rectangle
angle orientation of the rectangle
Definition at line 1041 of file DrawableObject2D.cpp.
 {
         glPushMatrix();
                 glTranslatef(cx, cy, 0.f);
                 glRotatef(angle, 0.f, 0.f, 1.f);
                 glScalef(width, height, 1.f);
                 glBegin(GL_LINE_LOOP);
                         glVertex2f(-0.5f, -0.5f);
                         glVertex2f(0.5f, -0.5f);
                         glVertex2f(0.5f, 0.5f);
                         glVertex2f(-0.5f, 0.5f);
                 glEnd();
         glPopMatrix();
 }
void uriVL::drawCircularDot (void)
Draws a unit circular "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1119 of file DrawableObject2D.cpp.
Referenced by drawCenteredOval(), and drawOval().
 {
         const int NB_PTS = 16;
         const float xy[NB_PTS][2] = {{1.f, 0.f}, {0.92388f, 0.382683f}, {0.707107f, 0.707107f},
                                                                 {0.382683f, 0.92388f}, {0.f, 1.f}, {-0.382683f, 0.92388f},
                                                                 {-0.707107f, 0.707107f}, {-0.92388f, 0.382683f},
                                                                 {-1.f, 0.f}, {-0.92388f, -0.382683f}, {-0.707107f, -0.707107f},
                                                                 {-0.382683f, -0.92388f}, {0.f, -1.f}, {0.382683f, -0.92388f},
                                                                 {0.707107f, -0.707107f}, {0.92388f, -0.382683f}};
         glBegin(GL_LINE_LOOP);
                 for (int k=0; k<NB_PTS; k++)
                         glVertex2fv(xy[k]);
         glEnd();
 }
void uriVL::drawDiamondDot (void)
Draws a unit diamond "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1173 of file DrawableObject2D.cpp.
 {
         glBegin(GL_LINE_LOOP);
                 glVertex2f(0.f, 1.f);
                 glVertex2f(-1.f, 0.f);
                 glVertex2f(0.f, -1.f);
                 glVertex2f(1.f, 0.f);
         glEnd();
 }
void uriVL::drawOval (float x, float y, float width, float height)
Draws the contour of an ellipse specified by the coordinates of it upper-left corner, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
We simply use the name "oval" for similaroty to the Java API. Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
x x coordinate of the ellipse's bounding rectangle's upper-left corner
y y coordinate of the ellipse's bounding rectangle's upper-left corner
width the ellipse's major diameter
height the ellipse's minor diameter
Definition at line 1073 of file DrawableObject2D.cpp.
References drawCircularDot().
 {
         const float HALF_WIDTH = 0.5f*width, HALF_HEIGHT = 0.5f*height;
         glPushMatrix();
                 glTranslatef(x + HALF_WIDTH, y - HALF_HEIGHT, 0.f);
                 glScalef(HALF_WIDTH, HALF_HEIGHT, 1.f);
                 drawCircularDot();
         glPopMatrix();
 }
void uriVL::drawPoint_diamond (float cx, float cy, float rad, const float * color)
Free function to draw a point as a diamond.
Parameters
cx x coordinate of the circle's center
cy y coordinate of the circle's center
rad the diamond's "radius" (half diagonal)
color the filling color of the disk
Definition at line 335 of file ImagePoint.cpp.
 {
 }
void uriVL::drawPoint_disk (float cx, float cy, float rad, const float * color)
Free function to draw a point as a disk.
Parameters
cx x coordinate of the circle's center
cy y coordinate of the circle's center
rad the circle's radius
color the filling color of the disk
Definition at line 313 of file ImagePoint.cpp.
 {
 //      // draw a circle
 //    float nPolygonAngle = 0.f;
 //    float nRotationAmount = 360.f / DRAW_POINT_SIDES;
 //    float** circlePts = new float*[DRAW_POINT_SIDES];
 //
 //    for(int i = 0; i < DRAW_POINT_SIDES; i++ )
 //    {
 //        circlePts[i] = new float[2];
 //        circlePts[i][0] = 1.5f * cosf(nPolygonAngle);
 //        circlePts[i][1] = 1.5f * sinf(nPolygonAngle);
 //        nPolygonAngle += static_cast<float>((nRotationAmount*PI)/180.f);
 //    }
 }
void uriVL::drawPoint_square (float cx, float cy, float rad, const float * color)
Free function to draw a point as a square.
Parameters
cx x coordinate of the circle's center
cy y coordinate of the circle's center
rad the square's "radius" (half side)
color the filling color of the disk
Definition at line 331 of file ImagePoint.cpp.
 {
 }
void uriVL::drawRect (float x, float y, float width, float height)
Draws the contour of a rectangle specified by the coordinates of it upper-left corner, width, and height.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
x x coordinate of the rectangle's upper-left corner
y y coordinate of the rectangle's upper-left corner
width width of the rectangle
height height of the rectangle
Definition at line 1020 of file DrawableObject2D.cpp.
 {
         glBegin(GL_LINE_LOOP);
                 glVertex2f(x, y);
                 glVertex2f(x, y - height);
                 glVertex2f(x + width, y - height);
                 glVertex2f(x + width, y);
         glEnd();
 }
void uriVL::drawSquareDot (void)
Draws a unit square "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1151 of file DrawableObject2D.cpp.
 {
         glBegin(GL_LINE_LOOP);
                 glVertex2f(-0.7071f, 0.7071f);
                 glVertex2f(-0.7071f, -0.7071f);
                 glVertex2f(0.7071f, -0.7071f);
                 glVertex2f(0.7071f, 0.7071f);
         glEnd();
 }
void uriVL::fillCenteredOval (float cx, float cy, float width, float height, float angle = 0.f)
Fills an ellipse specified by the coordinates of it center, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
cx x coordinate of the ellipse's center
cy y coordinate of the ellipse's center
width the ellipse's major diameter
height the ellipse's minor diameter
angle orientation of the ellipse
Definition at line 1107 of file DrawableObject2D.cpp.
References fillCircularDot().
 {
         const float HALF_WIDTH = 0.5f*width, HALF_HEIGHT = 0.5f*height;
         glPushMatrix();
                 glTranslatef(cx, cy, 0.f);
                 glRotatef(angle, 0.f, 0.f, 1.f);
                 glScalef(HALF_WIDTH, HALF_HEIGHT, 1.f);
                 fillCircularDot();
         glPopMatrix();
 }
void uriVL::fillCenteredRect (float cx, float cy, float width, float height, float angle = 0.f)
Fills a rectangle specified by the coordinates of it center, width, and height, and by a rotation angle (in degree).
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
cx x coordinate of the rectangle's center
cy y coordinate of the rectangle's center
width width of the rectangle
height height of the rectangle
angle orientation of the rectangle
Definition at line 1057 of file DrawableObject2D.cpp.
 {
         glPushMatrix();
                 glTranslatef(cx, cy, 0.f);
                 glRotatef(angle, 0.f, 0.f, 1.f);
                 glScalef(width, height, 1.f);
                 glBegin(GL_POLYGON);
                         glVertex2f(-0.5f, -0.5f);
                         glVertex2f(0.5f, -0.5f);
                         glVertex2f(0.5f, 0.5f);
                         glVertex2f(-0.5f, 0.5f);
                 glEnd();
         glPopMatrix();
 }
void uriVL::fillCircularDot (void)
Fills a unit circular "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1135 of file DrawableObject2D.cpp.
Referenced by fillCenteredOval(), fillOval(), uriVL::Contour_F::render_(), uriVL::Contour_I::render_(), uriVL::VectorField_I::renderNeedles_(), and uriVL::VectorField_F::renderNeedles_().
 {
         const int NB_PTS = 16;
         const float xy[NB_PTS][2] = {{1.f, 0.f}, {0.92388f, 0.382683f}, {0.707107f, 0.707107f},
                                                                 {0.382683f, 0.92388f}, {0.f, 1.f}, {-0.382683f, 0.92388f},
                                                                 {-0.707107f, 0.707107f}, {-0.92388f, 0.382683f},
                                                                 {-1.f, 0.f}, {-0.92388f, -0.382683f}, {-0.707107f, -0.707107f},
                                                                 {-0.382683f, -0.92388f}, {0.f, -1.f}, {0.382683f, -0.92388f},
                                                                 {0.707107f, -0.707107f}, {0.92388f, -0.382683f}};
         glBegin(GL_POLYGON);
                 for (int k=0; k<NB_PTS; k++)
                         glVertex2fv(xy[k]);
         glEnd();
 }
void uriVL::fillDiamondDot (void)
Fills a unit diamond "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1184 of file DrawableObject2D.cpp.
 {
         glBegin(GL_POLYGON);
                 glVertex2f(0.f, 1.f);
                 glVertex2f(-1.f, 0.f);
                 glVertex2f(0.f, -1.f);
                 glVertex2f(1.f, 0.f);
         glEnd();
 }
void uriVL::fillOval (float x, float y, float width, float height)
Fills an ellipse specified by the coordinates of it upper-left corner, and the width and height of its bounding rectangle (major and minor diameters of the ellipse).
We simply use the name "oval" for similaroty to the Java API. Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
x x coordinate of the ellipse's bounding rectangle's upper-left corner
y y coordinate of the ellipse's bounding rectangle's upper-left corner
width the ellipse's major diameter
height the ellipse's minor diameter
Definition at line 1084 of file DrawableObject2D.cpp.
References fillCircularDot().
 {
         const float HALF_WIDTH = 0.5f*width, HALF_HEIGHT = 0.5f*height;
         glPushMatrix();
                 glTranslatef(x + HALF_WIDTH, y - HALF_HEIGHT, 0.f);
                 glScalef(HALF_WIDTH, HALF_HEIGHT, 1.f);
                 fillCircularDot();
         glPopMatrix();
 }
void uriVL::fillRect (float x, float y, float width, float height)
Fills a rectangle specified by the coordinates of it upper-left corner, width, and height.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Parameters
x x coordinate of the rectangle's upper-left corner
y y coordinate of the rectangle's upper-left corner
width width of the rectangle
height height of the rectangle
Definition at line 1030 of file DrawableObject2D.cpp.
 {
         glBegin(GL_POLYGON);
                 glVertex2f(x, y);
                 glVertex2f(x, y - height);
                 glVertex2f(x + width, y - height);
                 glVertex2f(x + width, y);
         glEnd();
 }
void uriVL::fillSquareDot (void)
Fills a unit square "dot" at the current location.
Like all the free functions defined here
this makes no pretention of being super-efficient. It simply provides a simple way to draw a basic shape. In any case, the main purpose of this library is image processing, not rendering. The latter is generally only performed for debugging/validation purposes.
It is up to the user to set the color before making the call to this function
Definition at line 1162 of file DrawableObject2D.cpp.
 {
         glBegin(GL_POLYGON);
                 glVertex2f(-0.7071f, 0.7071f);
                 glVertex2f(-0.7071f, -0.7071f);
                 glVertex2f(0.7071f, -0.7071f);
                 glVertex2f(0.7071f, 0.7071f);
         glEnd();
 }
Variable Documentation
const int uriVL::IMAGE_SPACE_BOUND = 32767
Definition at line 26 of file DrawableObject2D.h.
Referenced by uriVL::Blob::computeBoundingRect_().
const int uriVL::R250_LEN = 250 static
Definition at line 27 of file RandomGenerator_R250_521.h.
Referenced by uriVL::RandomGenerator_R250_R521::nextULong(), and uriVL::RandomGenerator_R250_R521::setSeed().
const int uriVL::R521_LEN = 521 static
Definition at line 28 of file RandomGenerator_R250_521.h.
Referenced by uriVL::RandomGenerator_R250_R521::nextULong(), and uriVL::RandomGenerator_R250_R521::setSeed().
const float uriVL::VECTORSCALE = 5.f
Definition at line 31 of file ContourForce.h.
Referenced by uriVL::ContourForce::render_().