URIVisionLibrary: NonlinearOptimizerND.cpp File Reference
NonlinearOptimizerND.cpp File Reference
#include "NonlinearOptimizerND.h"
Functions
void checkIfSearchStartPointIsValid_ (const FunctionND_F *f, const float *xMin, const float *xMax, const float *startX)
void checkIfSearchStartPointIsValid_ (const FunctionND_F *f, const vector< float > &xMin, const vector< float > &xMax, const vector< float > &startX)
void checkIfSearchStartPointIsValid_ (const FunctionND *f, const double *xMin, const double *xMax, const double *startX)
void checkIfSearchStartPointIsValid_ (const FunctionND *f, const vector< double > &xMin, const vector< double > &xMax, const vector< double > &startX)
Function Documentation
void checkIfSearchStartPointIsValid_ (const FunctionND_F * f, const float * xMin, const float * xMax, const float * startX)
Definition at line 798 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::FunctionND_F::getDimension(), uriVL::FunctionND_F::isDefinedAt(), uriVL::kDataRangeError, and uriVL::kNumericalError.
Referenced by uriVL::NonlinearOptimizerND::minimize().
 {
         bool inDomain = false;
         bool inSearchRange = true;
         try
         {
                 inDomain = f->isDefinedAt(startX);
                 int nDim = f->getDimension();
                 inSearchRange = true;
                 for (int k=0; inSearchRange && (k<nDim); k++)
                 {
                         inSearchRange = (startX[k] >= xMin[k]) && (startX[k] <= xMax[k]);
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by uriVL::checkIfSearchStartPointIsValid_");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in uriVL::checkIfSearchStartPointIsValid_");
         }
     FAIL_CONDITION( !inDomain,
                     kDataRangeError,
                     "start point not within function domain of definition in uriVL::checkIfSearchStartPointIsValid_");
     FAIL_CONDITION( !inSearchRange,
                     kDataRangeError,
                     "start point not within search range in uriVL::checkIfSearchStartPointIsValid_");
 }
void checkIfSearchStartPointIsValid_ (const FunctionND_F * f, const vector< float > & xMin, const vector< float > & xMax, const vector< float > & startX)
Definition at line 837 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::FunctionND_F::getDimension(), uriVL::FunctionND_F::isDefinedAt(), uriVL::kDataRangeError, and uriVL::kNumericalError.
 {
         bool inDomain = false;
         bool inSearchRange = true;
         try
         {
                 inDomain = f->isDefinedAt(startX);
                 int nDim = f->getDimension();
                 inSearchRange = true;
                 for (int k=0; inSearchRange && (k<nDim); k++)
                 {
                         inSearchRange = (startX[k] >= xMin[k]) && (startX[k] <= xMax[k]);
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by uriVL::checkIfSearchStartPointIsValid_");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in uriVL::checkIfSearchStartPointIsValid_");
         }
     FAIL_CONDITION( !inDomain,
                     kDataRangeError,
                     "start point not within function domain of definition in uriVL::checkIfSearchStartPointIsValid_");
     FAIL_CONDITION( !inSearchRange,
                     kDataRangeError,
                     "start point not within search range in uriVL::checkIfSearchStartPointIsValid_");
 }
void checkIfSearchStartPointIsValid_ (const FunctionND * f, const double * xMin, const double * xMax, const double * startX)
Definition at line 878 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::FunctionND::getDimension(), uriVL::FunctionND::isDefinedAt(), uriVL::kDataRangeError, and uriVL::kNumericalError.
 {
         bool inDomain = false;
         bool inSearchRange = true;
         try
         {
                 inDomain = f->isDefinedAt(startX);
                 int nDim = f->getDimension();
                 inSearchRange = true;
                 for (int k=0; inSearchRange && (k<nDim); k++)
                 {
                         inSearchRange = (startX[k] >= xMin[k]) && (startX[k] <= xMax[k]);
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by uriVL::checkIfSearchStartPointIsValid_");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in uriVL::checkIfSearchStartPointIsValid_");
         }
     FAIL_CONDITION( !inDomain,
                     kDataRangeError,
                     "start point not within function domain of definition in uriVL::checkIfSearchStartPointIsValid_");
     FAIL_CONDITION( !inSearchRange,
                     kDataRangeError,
                     "start point not within search range in uriVL::checkIfSearchStartPointIsValid_");
 }
void checkIfSearchStartPointIsValid_ (const FunctionND * f, const vector< double > & xMin, const vector< double > & xMax, const vector< double > & startX)
Definition at line 919 of file NonlinearOptimizerND.cpp.
References uriVL::ErrorReport::appendToMessage(), FAIL_CONDITION, uriVL::FunctionND::getDimension(), uriVL::FunctionND::isDefinedAt(), uriVL::kDataRangeError, and uriVL::kNumericalError.
 {
         bool inDomain = false;
         bool inSearchRange = true;
         try
         {
                 inDomain = f->isDefinedAt(startX);
                 int nDim = f->getDimension();
                 inSearchRange = true;
                 for (int k=0; inSearchRange && (k<nDim); k++)
                 {
                         inSearchRange = (startX[k] >= xMin[k]) && (startX[k] <= xMax[k]);
                 }
         }
         catch (ErrorReport& e)
         {
                 e.appendToMessage("called by uriVL::checkIfSearchStartPointIsValid_");
                 throw e;
         }
         catch(...)
         {
                 FAIL_CONDITION( true,
                                                 kNumericalError,
                                                 "Unexpected error in uriVL::checkIfSearchStartPointIsValid_");
         }
     FAIL_CONDITION( !inDomain,
                     kDataRangeError,
                     "start point not within function domain of definition in uriVL::checkIfSearchStartPointIsValid_");
     FAIL_CONDITION( !inSearchRange,
                     kDataRangeError,
                     "start point not within search range in uriVL::checkIfSearchStartPointIsValid_");
 }