URIVisionLibrary: playMovie_main.cpp File Reference
playMovie_main.cpp File Reference
#include <string>
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include "ErrorReport.h"
#include "RasterImage.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray.h"
#include "MoviePlayer.h"
#include "Demos/dataFolderPath.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define READ_IN_GRAY_IMAGE 0
#define kNbRowsSubwindows 1
#define kNbColsSubwindows 1
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 6
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void myDisplay (void)
void setupOrthoCam (int w, int h)
void myIdle (void)
void myIdleDone (void)
void myReshape (int w, int h)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void createRasterImageObj (void)
void glSetupAndRun (void)
int main (int argc, char **argv)
Variables
const string movie_dir = MOVIE_DIR_PATH
bool stepByStep = false
long gFrameIndex = 0
int gWinWidth
int gWinHeight
RasterImage_RGBa * gMyImage = NULL
MoviePlayer * gMyPlayer = NULL
GLfloat kBackgroundColor [4] = {0.f, 0.f, 0.f, 1.f}
bool gInitDone = false
Macro Definition Documentation
#define kBorder 8
Definition at line 82 of file playMovie_main.cpp.
#define kDefaultHeight 256
Definition at line 83 of file playMovie_main.cpp.
#define kDefaultWidth 256
Definition at line 84 of file playMovie_main.cpp.
#define kMaxWindowHeight 640
Definition at line 86 of file playMovie_main.cpp.
#define kMaxWindowWidth 900
Definition at line 85 of file playMovie_main.cpp.
#define kNbBckgndCols 6
Definition at line 136 of file playMovie_main.cpp.
#define kNbColsSubwindows 1
Definition at line 80 of file playMovie_main.cpp.
#define kNbRowsSubwindows 1
Definition at line 79 of file playMovie_main.cpp.
#define READ_IN_GRAY_IMAGE 0
Definition at line 59 of file playMovie_main.cpp.
#define READ_IN_RGB_IMAGE 0
Definition at line 58 of file playMovie_main.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 57 of file playMovie_main.cpp.
Function Documentation
void cleanupAndQuit (int exitCode)
Definition at line 180 of file playMovie_main.cpp.
Referenced by main(), and myKeyboard().
 {
         #if URIVL_USE_QUICKTIME
             // terminate the QuickTime Media Layer
             ExitMovies();
             #if URIVL_OS_WIN32
                 TerminateQTML();
             #endif
         #endif
     std::exit(exitCode);
 }
void createRasterImageObj (void)
Definition at line 204 of file playMovie_main.cpp.
References FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), gMyPlayer, and uriVL::kRasterImageError.
Referenced by glSetupAndRun().
 {
     const ImageRect *myRect = gMyPlayer->getRect();
     int nbRows = myRect->getHeight();
     int nbCols = myRect->getWidth();
     #if READ_IN_RGBA_IMAGE
         gMyImage = new RasterImage_RGBa(nbRows, nbCols);
     #elif READ_IN_RGB_IMAGE
         gMyImage = new RasterImage_RGB(nbRows, nbCols);
     #else
         gMyImage = new RasterImage_gray(nbRows, nbCols);
     #endif
     FAIL_CONDITION(     gMyImage == NULL,
                     kRasterImageError,
                     "Failed to allocate RasterImage");
 }
void glSetupAndRun (void)
Definition at line 413 of file playMovie_main.cpp.
References createRasterImageObj(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gWinHeight, gWinWidth, kBackgroundColor, myDisplay(), myIdle(), myKeyboard(), myMouse(), myReshape(), and setupOrthoCam().
Referenced by main().
 {
     createRasterImageObj();
     //  I initialize my window's dimensions at the default values
     int     imgHeight = gMyImage->getHeight(),
             imgWidth = gMyImage->getWidth();
     //  I initialize my window's dimensions
     gWinHeight = imgHeight;
     gWinWidth = imgWidth;
     DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
     glutInitWindowSize(gWinWidth, gWinHeight);
     glutCreateWindow("Movie Playing in a RasterImage Demo");
     glClearColor(kBackgroundColor[0], kBackgroundColor[1], kBackgroundColor[2], kBackgroundColor[3]);
     glutDisplayFunc(myDisplay);
     setupOrthoCam(imgWidth, imgHeight);
     glutReshapeFunc(myReshape);
     glutIdleFunc(myIdle);
     glutMouseFunc(myMouse);
     glutKeyboardFunc(myKeyboard);
     //  Enter infinite glut loop
     glutMainLoop();
 }
void initializeQTEnvironment (void)
Definition at line 151 of file playMovie_main.cpp.
References FAIL_CONDITION, uriVL::kEnterMoviesError, and uriVL::kQuickTimeNotInstalled.
Referenced by main().
 {
         #if URIVL_USE_QUICKTIME
                 printf("using quicktime\n");
             OSErr       myErr = noErr;
             #if URIVL_OS_WIN32
                 myErr = InitializeQTML(kQTMLNoIdleEvents);
             #else
                 #if URIVL_OS_MACOS
                     long        myAttrs;
                     myErr = Gestalt(gestaltQuickTime, &myAttrs);
                 #endif
             #endif
             FAIL_CONDITION(     myErr != noErr,
                             kQuickTimeNotInstalled,
                             "QuickTime is not installed on this computer");
             myErr = EnterMovies();
             FAIL_CONDITION(     myErr != noErr,
                             kEnterMoviesError,
                             "Problems with EnterMovies, returning errors (exit)");
          #else
                 //do nothing?
          #endif
 }
int main (int argc, char ** argv)
Definition at line 449 of file playMovie_main.cpp.
References cleanupAndQuit(), uriVL::ErrorReport::getMessage(), glSetupAndRun(), gMyPlayer, and initializeQTEnvironment().
 {
     try {
         glutInit(&argc, argv);
         glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
         initializeQTEnvironment();
         gMyPlayer = new MoviePlayer();
 string outPath = "../../../out.txt"; //movie_dir + "out.txt";
 ofstream outFile(outPath.c_str());
 outFile << "test" << endl;
 outFile.close();
                 //      QuickTime for Mac and Windows includes a rudimentary GUI file selector
                 #if URIVL_USE_QUICKTIME
                         gMyPlayer->setSource();
                 //      at this point, for any other implementation, a file path is the only way
         #else
 //                      const string moviePath = movie_dir + "TFGreen1.mov";
                         const string moviePath = "/SDKs/uriVisionLib/SDK/Data_Samples/Movies/TFGreen1.mov";
 //                      const string moviePath = "/Volumes/Development/SDKs/uriVisionLib/SDK/Data_Samples/Movies/TFGreen1.mov";
                         gMyPlayer->setSource(moviePath.c_str());
                 #endif
         glSetupAndRun();
         //  Normally this call should never be placed since the only way to leave the
         //  glut loop is to quit
         cleanupAndQuit(0);
         return 0;
     }
     catch (uriVL::ErrorReport & e)
         {
         cerr << "Error: caught ErrorReport: " << e.getMessage() << endl;
     }
 }
void myDisplay (void)
Definition at line 282 of file playMovie_main.cpp.
References gFrameIndex, and uriVL::DrawableObject2D::render().
Referenced by glSetupAndRun().
 {
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     if (gFrameIndex>0)
     {
         gMyImage->render( );
     }
     glutSwapBuffers();
 }
void myIdle (void)
Definition at line 238 of file playMovie_main.cpp.
References gFrameIndex, gMyPlayer, myIdleDone(), and stepByStep.
Referenced by glSetupAndRun(), myKeyboard(), and myMouse().
 {
     if (!gMyPlayer->isFinished())
     {
         gMyPlayer->getFrame(gMyImage);
         gFrameIndex++;
         //  do something cool
     }
     else
         {
                 //      do this to stop playing when we reach movie's end
         glutIdleFunc(myIdleDone);
                 //      do that to go back to the beginning of the movie instead
                 //      gFrameIndex = 0;
                 //      gMyPlayer->goToBeginning();
         }
     glutPostRedisplay();
     if (stepByStep)
         glutIdleFunc(myIdleDone);
 }
void myIdleDone (void)
Definition at line 270 of file playMovie_main.cpp.
Referenced by myIdle().
 {
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 344 of file playMovie_main.cpp.
References cleanupAndQuit(), gMyPlayer, myIdle(), and stepByStep.
Referenced by glSetupAndRun().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
                 //      's' pauses the movie playing
         case 's':
             glutIdleFunc(NULL);
             break;
                 //      'a' resumes the movie playing
         case 'a':
             stepByStep = false;
             glutIdleFunc(myIdle);
             break;
                 //      'r' restarts the movie at beginning
         case 'r':
                         gMyPlayer->goToBeginning();
             glutIdleFunc(myIdle);
             break;
         default:
             break;
     }
     //    glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 386 of file playMovie_main.cpp.
References myIdle(), and stepByStep.
Referenced by glSetupAndRun().
 {
     // stop start the playing of the images/movie in the display
     // if the left mouse button is clicked, do something
     if (state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
         stepByStep = true;
         myIdle();
     }
     if (state == GLUT_DOWN && button == GLUT_MIDDLE_BUTTON)
     {
         glutIdleFunc(NULL);
     }
     //  ...and then refresh the display
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 304 of file playMovie_main.cpp.
References gWinHeight, and gWinWidth.
Referenced by glSetupAndRun().
 {
     if ((w != gWinWidth) || (h != gWinHeight))
         glutReshapeWindow(gWinWidth, gWinHeight);
     glutPostRedisplay();
 }
void setupOrthoCam (int w, int h)
Definition at line 321 of file playMovie_main.cpp.
Referenced by glSetupAndRun().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
long gFrameIndex = 0
Definition at line 115 of file playMovie_main.cpp.
Referenced by myDisplay(), and myIdle().
bool gInitDone = false
Definition at line 140 of file playMovie_main.cpp.
RasterImage_RGBa* gMyImage = NULL
Definition at line 121 of file playMovie_main.cpp.
MoviePlayer* gMyPlayer = NULL
Definition at line 130 of file playMovie_main.cpp.
Referenced by createRasterImageObj(), initializeApplication(), main(), myIdle(), and myKeyboard().
int gWinHeight
Definition at line 117 of file playMovie_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
int gWinWidth
Definition at line 117 of file playMovie_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
GLfloat kBackgroundColor[4] = {0.f, 0.f, 0.f, 1.f}
Definition at line 138 of file playMovie_main.cpp.
Referenced by glSetupAndRun().
const string movie_dir = MOVIE_DIR_PATH
Definition at line 72 of file playMovie_main.cpp.
bool stepByStep = false
Definition at line 114 of file playMovie_main.cpp.
Referenced by myIdle(), myKeyboard(), and myMouse().