URIVisionLibrary: spriteOverlay_main.cpp File Reference
spriteOverlay_main.cpp File Reference
#include <string>
#include <fstream>
#include <iostream>
#include <cmath>
#include "RasterImage_gray.h"
#include "RasterImage_RGBa.h"
#include "ImageReader.h"
#include "Demos/dataFolderPath.h"
Macros
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
#define kNbImages 4
#define kNbSprites 4
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kNbBckgndCols 5
Functions
void initializeQTEnvironment (void)
void cleanupAndQuit (int exitCode)
void loadImages (void)
void applyOverlays (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void setupCamera (int w, int h)
void myMenuMain (int value)
void myMenu0 (int value)
void myMenu1 (int value)
void myMenu2 (int value)
void myMenu3 (int value)
void myColorSubmenu (int value)
void mySpecialKeys (int c, int x, int y)
void myKeyboard (unsigned char c, int x, int y)
void cleanupAndQuit (void)
void myInit (void)
int main (int argc, char **argv)
Variables
const string color_dir = COLOR_DIR_PATH
const string gray_dir = GRAY_DIR_PATH
const string filePath0 = color_dir + "bottles_256x256.tga"
const string filePath1 = gray_dir + "Lena_256x256.tga"
const string filePath2 = color_dir + "umbrellas_480x400.tga"
const string filePath3 = gray_dir + "camera_256x256.tga"
short gWinWidth
short gWinHeight
short gImageWidth = kDefaultWidth
short gImageHeight = kDefaultHeight
int gMainWindow
int gSubwindow [kNbSubwindows]
bool gInitDone = false
RasterImage ** gInputImage = NULL
RasterImage ** gDisplayImage = NULL
RasterImage ** gSprite = NULL
ImagePoint ** gSpriteOrigin
int gActiveSprite = 0
bool gSpriteUseOrigin = false
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
const int QUIT_MENU = 0
const int SPRITE_DISPLCT = 5
GLfloat kBackgroundColor [kNbBckgndCols][4]
string kBckgndColStr []
Macro Definition Documentation
#define kBorder 8
Definition at line 72 of file spriteOverlay_main.cpp.
Referenced by main().
#define kDefaultHeight 256
Definition at line 73 of file spriteOverlay_main.cpp.
#define kDefaultWidth 256
Definition at line 74 of file spriteOverlay_main.cpp.
#define kMaxWindowHeight 640
Definition at line 76 of file spriteOverlay_main.cpp.
#define kMaxWindowWidth 900
Definition at line 75 of file spriteOverlay_main.cpp.
#define kNbBckgndCols 5
Definition at line 143 of file spriteOverlay_main.cpp.
Referenced by myColorSubmenu(), and myInit().
#define kNbColsSubwindows 2
Definition at line 66 of file spriteOverlay_main.cpp.
Referenced by main().
#define kNbImages 4
Definition at line 69 of file spriteOverlay_main.cpp.
Referenced by loadImages().
#define kNbRowsSubwindows 2
Definition at line 65 of file spriteOverlay_main.cpp.
Referenced by main().
#define kNbSprites 4
Definition at line 70 of file spriteOverlay_main.cpp.
Referenced by applyOverlays(), loadImages(), and myKeyboard().
#define kNbSubwindows kNbRowsSubwindows*kNbColsSubwindows
Definition at line 67 of file spriteOverlay_main.cpp.
Referenced by loadImages().
Function Documentation
void applyOverlays (void)
Definition at line 284 of file spriteOverlay_main.cpp.
References uriVL::RasterImage::copyInto(), gSpriteUseOrigin, kNbSprites, LOWER_LEFT, LOWER_RIGHT, uriVL::RasterImage::overlay(), and uriVL::RasterImage::writeInto().
Referenced by loadImages(), myKeyboard(), and mySpecialKeys().
 {
     //  In the lower-left quadrant we display image 0  + overlays
     gInputImage[0]->copyInto(gDisplayImage[LOWER_LEFT]);
     //
     //  we do the overlays by using the function writeInto
     for (int i=0; i<kNbSprites; i++)
         if (gSpriteUseOrigin)
             gSprite[i]->writeInto(gDisplayImage[LOWER_LEFT], gSpriteOrigin[i]);
         else
             gSprite[i]->writeInto(gDisplayImage[LOWER_LEFT]);
     //  In the lower-right quadrant we display image 1  + overlays
     gInputImage[1]->copyInto(gDisplayImage[LOWER_RIGHT]);
     //
     //  we do the overlays by using the function overlay
     for (int i=0; i<kNbSprites; i++)
         if (gSpriteUseOrigin)
             gDisplayImage[LOWER_RIGHT]->overlay(gSprite[i], gSpriteOrigin[i]);
         else
             gDisplayImage[LOWER_RIGHT]->overlay(gSprite[i]);
 }
void cleanupAndQuit (int exitCode)
Definition at line 189 of file spriteOverlay_main.cpp.
Referenced by loadImages(), main(), myKeyboard(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
 {
     #if URIVL_USE_QUICKTIME
         // terminate the QuickTime Media Layer
         ExitMovies();
         #if URIVL_OS_WIN32
             TerminateQTML();
         #endif
     #endif
     std::exit(exitCode);
 }
void cleanupAndQuit (void)
void initializeQTEnvironment (void)
Definition at line 165 of file spriteOverlay_main.cpp.
Referenced by main().
 {
     #if URIVL_USE_QUICKTIME
         #if     URIVL_OS_WIN32
             OSErr       anErr = noErr;
             anErr = InitializeQTML(kQTMLNoIdleEvents);
             if (anErr != noErr)
             {
                 cerr <<"\pQuickTime is not installed on this computer";
                 ExitToShell();
             }
             anErr = EnterMovies();
             if(anErr != noErr)
             {
                 cerr <<"\pProblems with EnterMovies, returning errors (exit)";
                 ExitToShell();
             }
         #endif
     #endif
 }
void loadImages (void)
Definition at line 204 of file spriteOverlay_main.cpp.
References applyOverlays(), cleanupAndQuit(), filePath0, filePath1, filePath2, filePath3, uriVL::ImageReader::getFrame(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gImageHeight, gImageWidth, uriVL::RasterImage::grab(), kNbImages, kNbSprites, kNbSubwindows, LOWER_LEFT, LOWER_RIGHT, myReader, uriVL::ImageRect::setRect(), uriVL::ImageReader::setSource(), UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     ImageReader myReader;
     gInputImage = new RasterImage*[kNbImages];
     //-------------------------------------------------------------
     //  We read Images 0-2 from a file
     //-------------------------------------------------------------
     myReader.setSource(const_cast<char*>(filePath0.c_str()));
     gInputImage[0] = myReader.getFrame(true);
     if (gInputImage[0] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath0 << endl;
         cleanupAndQuit(-1);
     }
     myReader.setSource(const_cast<char*>(filePath1.c_str()));
     gInputImage[1] = myReader.getFrame(false);
     if (gInputImage[1] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath1 << endl;
         cleanupAndQuit(-1);
     }
     myReader.setSource(const_cast<char*>(filePath2.c_str()));
     gInputImage[2] = myReader.getFrame(true);
     if (gInputImage[2] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath2 << endl;
         cleanupAndQuit(-1);
     }
     myReader.setSource(const_cast<char*>(filePath3.c_str()));
     gInputImage[3] = myReader.getFrame(true);
     if (gInputImage[3] ==NULL)
     {
         cout << "Error encountered while reading image file " << filePath3 << endl;
         cleanupAndQuit(-1);
     }
     gImageWidth = gInputImage[0]->getWidth();
     gImageHeight = gInputImage[0]->getHeight();
     //-------------------------------------------------------------
     //  We allocate the array of display images
     //-------------------------------------------------------------
     gDisplayImage = new RasterImage*[kNbSubwindows];
     //
     gDisplayImage[UPPER_LEFT] = gInputImage[0];
     gDisplayImage[UPPER_RIGHT] = gInputImage[1];
     gDisplayImage[LOWER_LEFT] = new RasterImage_RGBa(gImageHeight, gImageWidth);
     gDisplayImage[LOWER_RIGHT] = new RasterImage_gray(gImageHeight, gImageWidth);
     //-------------------------------------------------------------
     //  We "grab" the sprites and assign them origins
     //-------------------------------------------------------------
     gSprite = new RasterImage*[kNbSprites];
     gSpriteOrigin = new ImagePoint*[kNbSprites];
     //
     ImageRect   rect(50, 70, 100, 60);
     gSprite[0] = gInputImage[2]->grab(&rect);
     gSpriteOrigin[0] = new ImagePoint(120, 30);
     rect.setRect(180, 200, 50, 50);
     gSprite[1] = gInputImage[2]->grab(&rect);
     gSpriteOrigin[1] = new ImagePoint(90, 150);
     rect.setRect(100, 40, 60, 40);
     gSprite[2] = gInputImage[3]->grab(&rect);
     gSpriteOrigin[2] = new ImagePoint(30, 120);
     rect.setRect(20, 175, 30, 70);
     gSprite[3] = gInputImage[3]->grab(&rect);
     gSpriteOrigin[3] = new ImagePoint(60, 60);
     applyOverlays();
 }
int main (int argc, char ** argv)
Definition at line 636 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), gImageHeight, gImageWidth, gMainWindow, gSubwindow, gWinHeight, gWinWidth, initializeQTEnvironment(), kBackgroundColor, kBorder, kNbColsSubwindows, kNbRowsSubwindows, loadImages(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myInit(), myKeyboard(), myReshape(), mySpecialKeys(), and setupCamera().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[5])() = {myDisplayMain, myDisplay0, myDisplay1,
                                         myDisplay2, myDisplay3};
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGB);
     initializeQTEnvironment();
     loadImages();
     //  I initialize my window's dimensions at the default values
     gWinWidth = kNbColsSubwindows*(gImageWidth + kBorder) + kBorder;
     gWinHeight = kNbRowsSubwindows*(gImageHeight + kBorder) + kBorder;
     glutInitWindowSize(gWinWidth,gWinHeight);
     gMainWindow = glutCreateWindow("Sprite Overlay Demo");
     glutKeyboardFunc(myKeyboard);
     glutSpecialFunc(mySpecialKeys);
     glutDisplayFunc(myDisplayMain);
     glutReshapeFunc(myReshape);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     winID = 0;
     glutSetWindow(gMainWindow);
     for (int i=0; i<kNbRowsSubwindows; i++)
         for (int j=0; j<kNbColsSubwindows; j++)
         {
             gSubwindow[winID] = glutCreateSubWindow(
                                     gMainWindow,
                                     j*(gImageWidth + kBorder) + kBorder,
                                     i*(gImageHeight + kBorder) + kBorder,
                                     gImageWidth,
                                     gImageHeight);
             //  I don't need to do this.  I just set a different "clear" color for
             //  each subwindow.
             backColor = kBackgroundColor[winID];
             glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
             //  This *has* to be defined:  a "display" callback function for each subwindow
             glutDisplayFunc(displayFuncTable[winID++]);
             //  Here I use the same keyboard function for my 4 subwindows, but I could
             //  set up different ones.
             glutSpecialFunc(mySpecialKeys);
             glutKeyboardFunc(myKeyboard);
             //  This calls maps "world" coordinates to "screen" coordinates.
             //  In this particular case I make them coincide.
             setupCamera(gImageWidth, gImageHeight);
             //
             glutSetWindow(gMainWindow);
         }
     //  Initializes QuickTime and loads the image
     myInit();
     //  Enter infinite glut loop
     glutMainLoop();
     //  Normally this code should never be placed since the only way to leave the
     //  glut loop is to quit
     cleanupAndQuit(0);
     return 0;
 }
void myColorSubmenu (int value)
Definition at line 569 of file spriteOverlay_main.cpp.
References gMainWindow, kBackgroundColor, kNbBckgndCols, and myDisplay0().
Referenced by myInit().
 {
     GLfloat             *backColor;
     if ((colorIndex >= 0) && (colorIndex < kNbBckgndCols))
     {
         glutSetWindow(gMainWindow);
         backColor = kBackgroundColor[colorIndex];
         glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
         myDisplay0();
         glutPostRedisplay();
     }
 }
void myDisplay0 (void)
Definition at line 337 of file spriteOverlay_main.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by main(), myColorSubmenu(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[UPPER_LEFT]!= NULL)
     {
         gDisplayImage[UPPER_LEFT]->render(true);
     }
     glutSwapBuffers();
 }
void myDisplay1 (void)
Definition at line 353 of file spriteOverlay_main.cpp.
References gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[UPPER_RIGHT]!= NULL)
     {
         gDisplayImage[UPPER_RIGHT]->render(true);
     }
     glutSwapBuffers();
 }
void myDisplay2 (void)
Definition at line 369 of file spriteOverlay_main.cpp.
References gSubwindow, LOWER_LEFT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[LOWER_LEFT]!= NULL)
     {
         gDisplayImage[LOWER_LEFT]->render(false);
     }
     glutSwapBuffers();
 }
void myDisplay3 (void)
Definition at line 386 of file spriteOverlay_main.cpp.
References gSubwindow, LOWER_RIGHT, and uriVL::DrawableObject2D::render().
Referenced by main(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT);
     if (gDisplayImage[LOWER_RIGHT]!= NULL)
     {
         gDisplayImage[LOWER_RIGHT]->render(true);
     }
     glutSwapBuffers();
 }
void myDisplayMain (void)
Definition at line 320 of file spriteOverlay_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
     glutSetWindow(gMainWindow);
 }
void myInit (void)
Definition at line 586 of file spriteOverlay_main.cpp.
References gInitDone, gMainWindow, gSubwindow, kBckgndColStr, kNbBckgndCols, LOWER_LEFT, LOWER_RIGHT, myColorSubmenu(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), myMenuMain(), QUIT_MENU, UPPER_LEFT, and UPPER_RIGHT.
Referenced by main().
 {
     // Create Menus
     int menuMain, menu[4], colorSubmenu;
     //  Set a general menu for the main window
     glutSetWindow(gMainWindow);
     glClearColor(0.0, 0.0, 0.0, 1.0);
     //  Submenu for background color selection choices
     colorSubmenu = glutCreateMenu(myColorSubmenu);
     for (int i=0; i<kNbBckgndCols; i++)
         glutAddMenuEntry(kBckgndColStr[i].c_str(), i);
     // Main menu that the submenus are connected to
     glutSetWindow(gMainWindow);
     menuMain = glutCreateMenu(myMenuMain);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     menu[UPPER_LEFT] = glutCreateMenu(myMenu0);
     glutAddSubMenu("Color", colorSubmenu);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     menu[UPPER_RIGHT] = glutCreateMenu(myMenu1);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     menu[LOWER_LEFT] = glutCreateMenu(myMenu2);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     menu[LOWER_RIGHT] = glutCreateMenu(myMenu3);
     glutAddMenuEntry("Quit", QUIT_MENU);
     glutAddSubMenu("Frame color", colorSubmenu);
     glutAttachMenu(GLUT_RIGHT_BUTTON);
     glutSetWindow(gMainWindow);
     gInitDone = true;
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 465 of file spriteOverlay_main.cpp.
References applyOverlays(), cleanupAndQuit(), gActiveSprite, gMainWindow, gSpriteUseOrigin, and kNbSprites.
Referenced by main().
 {
     switch (c)
     {
         case 'q':
             cleanupAndQuit(0);
             break;
         case '[':
             gActiveSprite = (gActiveSprite + kNbSprites - 1) % kNbSprites;
             break;
         case ']':
             gActiveSprite = (gActiveSprite + 1) % kNbSprites;
             break;
         case ' ':
             gSpriteUseOrigin = !gSpriteUseOrigin;
             applyOverlays();
             break;
         default:
             break;
     }
     glutSetWindow(gMainWindow);
     glutPostRedisplay();
 }
void myMenu0 (int value)
Definition at line 509 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu1 (int value)
Definition at line 524 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why is this happening?" << endl;
             break;
     }
 }
void myMenu2 (int value)
Definition at line 539 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenu3 (int value)
Definition at line 554 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myMenuMain (int value)
Definition at line 494 of file spriteOverlay_main.cpp.
References cleanupAndQuit(), and QUIT_MENU.
Referenced by myInit().
 {
     switch (value)
     {
         case QUIT_MENU:
             cleanupAndQuit(0);
             break;
         default:        // This is not happening.  This is not happening. This is not...
             cout << "Why/how did this happen?" << endl;
             break;
     }
 }
void myReshape (int w, int h)
Definition at line 403 of file spriteOverlay_main.cpp.
References gImageHeight, gImageWidth, gMainWindow, and setupCamera().
Referenced by main().
 {
     glutSetWindow(gMainWindow);
     setupCamera(w, h);
     //  and I inform drawable object of these dimensions (in case they want to get rendered
     //  "shifted")
     DrawableObject2D::setDefaultWindowDimensions(gImageWidth, gImageHeight);
     glutPostRedisplay();
 }
void mySpecialKeys (int c, int x, int y)
Definition at line 432 of file spriteOverlay_main.cpp.
References applyOverlays(), gActiveSprite, gMainWindow, uriVL::ImagePoint::shiftX(), uriVL::ImagePoint::shiftY(), and SPRITE_DISPLCT.
Referenced by main().
 {
     switch (c)
     {
         case GLUT_KEY_LEFT:
             gSpriteOrigin[gActiveSprite]->shiftX(-SPRITE_DISPLCT);
             applyOverlays();
             break;
         case GLUT_KEY_RIGHT:
             gSpriteOrigin[gActiveSprite]->shiftX(+SPRITE_DISPLCT);
             applyOverlays();
             break;
         case GLUT_KEY_UP:
             gSpriteOrigin[gActiveSprite]->shiftY(-SPRITE_DISPLCT);
             applyOverlays();
             break;
         case GLUT_KEY_DOWN:
             gSpriteOrigin[gActiveSprite]->shiftY(+SPRITE_DISPLCT);
             applyOverlays();
             break;
         default:
             break;
     }
     glutSetWindow(gMainWindow);
     glutPostRedisplay();
 }
void setupCamera (int w, int h)
Definition at line 420 of file spriteOverlay_main.cpp.
Referenced by main(), and myReshape().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
const string color_dir = COLOR_DIR_PATH
Definition at line 53 of file spriteOverlay_main.cpp.
const string filePath0 = color_dir + "bottles_256x256.tga"
Definition at line 56 of file spriteOverlay_main.cpp.
Referenced by loadImages().
const string filePath1 = gray_dir + "Lena_256x256.tga"
Definition at line 57 of file spriteOverlay_main.cpp.
Referenced by loadImages().
const string filePath2 = color_dir + "umbrellas_480x400.tga"
Definition at line 58 of file spriteOverlay_main.cpp.
Referenced by loadImages().
const string filePath3 = gray_dir + "camera_256x256.tga"
Definition at line 59 of file spriteOverlay_main.cpp.
Referenced by loadImages().
int gActiveSprite = 0
Definition at line 128 of file spriteOverlay_main.cpp.
Referenced by myKeyboard(), and mySpecialKeys().
RasterImage** gDisplayImage = NULL
Definition at line 125 of file spriteOverlay_main.cpp.
short gImageHeight = kDefaultHeight
Definition at line 117 of file spriteOverlay_main.cpp.
Referenced by loadImages(), main(), and myReshape().
short gImageWidth = kDefaultWidth
Definition at line 116 of file spriteOverlay_main.cpp.
Referenced by loadImages(), main(), and myReshape().
bool gInitDone = false
Definition at line 122 of file spriteOverlay_main.cpp.
Referenced by myInit().
RasterImage** gInputImage = NULL
Definition at line 124 of file spriteOverlay_main.cpp.
int gMainWindow
Definition at line 119 of file spriteOverlay_main.cpp.
Referenced by main(), myColorSubmenu(), myDisplayMain(), myInit(), myKeyboard(), myReshape(), and mySpecialKeys().
const string gray_dir = GRAY_DIR_PATH
Definition at line 54 of file spriteOverlay_main.cpp.
RasterImage** gSprite = NULL
Definition at line 126 of file spriteOverlay_main.cpp.
ImagePoint** gSpriteOrigin
Definition at line 127 of file spriteOverlay_main.cpp.
bool gSpriteUseOrigin = false
Definition at line 129 of file spriteOverlay_main.cpp.
Referenced by applyOverlays(), and myKeyboard().
int gSubwindow[kNbSubwindows]
Definition at line 119 of file spriteOverlay_main.cpp.
Referenced by main(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myInit().
short gWinHeight
Definition at line 114 of file spriteOverlay_main.cpp.
Referenced by main().
short gWinWidth
Definition at line 114 of file spriteOverlay_main.cpp.
Referenced by main().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
=       {       {0.f, 0.f, 0.f, 1.f},
                                                    {1.f, 0.f, 0.f, 1.f},
                                                    {0.f, 1.f, 0.f, 1.f},
                                                    {1.f, 1.f, 0.f, 1.f},
                                                    {0.f, 1.f, 1.f, 1.f}
                                             }
Definition at line 145 of file spriteOverlay_main.cpp.
Referenced by main(), and myColorSubmenu().
string kBckgndColStr[]
Initial value:
=       {
                                "Black",
                                "Red",
                                "Green" ,
                                "Yellow",
                                "Cyan"
                            }
Definition at line 151 of file spriteOverlay_main.cpp.
Referenced by myInit().
const int LOWER_LEFT = 2
Definition at line 134 of file spriteOverlay_main.cpp.
Referenced by applyOverlays(), loadImages(), myDisplay2(), and myInit().
const int LOWER_RIGHT = 3
Definition at line 135 of file spriteOverlay_main.cpp.
Referenced by applyOverlays(), loadImages(), myDisplay3(), and myInit().
const int QUIT_MENU = 0
Definition at line 138 of file spriteOverlay_main.cpp.
Referenced by myInit(), myMenu0(), myMenu1(), myMenu2(), myMenu3(), and myMenuMain().
const int SPRITE_DISPLCT = 5
Definition at line 140 of file spriteOverlay_main.cpp.
Referenced by mySpecialKeys().
const int UPPER_LEFT = 0
Definition at line 132 of file spriteOverlay_main.cpp.
Referenced by loadImages(), myDisplay0(), and myInit().
const int UPPER_RIGHT = 1
Definition at line 133 of file spriteOverlay_main.cpp.
Referenced by loadImages(), myDisplay1(), and myInit().