URIVisionLibrary: Tracking2DDynamic_main.cpp File Reference
Tracking2DDynamic_main.cpp File Reference
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <glut.h>
#include "comFramework.h"
#include "ErrorReport.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray_F.h"
#include "VectorField_F.h"
#include "MoviePlayer.h"
#include "ImageReader.h"
#include "BlobTracker2DController.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define READ_IN_GRAY_IMAGE 0
#define kNbRowsSubwindows 2
#define kNbColsSubwindows 2
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kRootPath "./"
#define kPathSeparator "/"
#define kUpRoot "../"
#define kUpNext "../"
#define PI 3.14159265
#define filePath "../../../../Data_Samples/Movies/backgroundScene.tga"
#define DEBUG
#define kNbBckgndCols 6
#define kBlackBackground 0
#define kGrayBackground 5
Functions
void initializeQTEnvironment (void)
void cleanupQT (void)
void setupOrthoCam (int w, int h)
void myIdle (void)
void myIdleDone (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void myReshape (int w, int h)
void myMenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void createRasterImageObj (void)
void glSetupAndRun (void)
int main (int argc, char **argv)
Variables
int gWinWidth
int gWinHeight
int gMainWindow
int gSubwindow [kNbRowsSubwindows *kNbColsSubwindows]
bool stepByStep = false
long gFrameIndex = 0
ImageRect * gMyRect = NULL
RasterImage_RGBa * gMyImage = NULL
ImageReader * myReader
RasterImage * gBackgroundImage
RasterImage * gEstimatedBackImg
MoviePlayer * gMyPlayer = NULL
ImagePoint_F ** gCurrentPos = NULL
BlobTracker2DList gTrackerList
BlobTracker2DController * gController = NULL
GLfloat kBackgroundColor [kNbBckgndCols][4]
bool gInitDone = false
Macro Definition Documentation
#define DEBUG
Definition at line 187 of file Tracking2DDynamic_main.cpp.
#define filePath "../../../../Data_Samples/Movies/backgroundScene.tga"
Definition at line 168 of file Tracking2DDynamic_main.cpp.
Referenced by createRasterImageObj().
#define kBlackBackground 0
Definition at line 210 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
#define kBorder 8
Definition at line 84 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
#define kBorder 8
Definition at line 84 of file Tracking2DDynamic_main.cpp.
#define kDefaultHeight 256
Definition at line 85 of file Tracking2DDynamic_main.cpp.
#define kDefaultHeight 256
Definition at line 85 of file Tracking2DDynamic_main.cpp.
#define kDefaultWidth 256
Definition at line 86 of file Tracking2DDynamic_main.cpp.
#define kDefaultWidth 256
Definition at line 86 of file Tracking2DDynamic_main.cpp.
#define kGrayBackground 5
Definition at line 211 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
#define kMaxWindowHeight 640
Definition at line 88 of file Tracking2DDynamic_main.cpp.
#define kMaxWindowHeight 640
Definition at line 88 of file Tracking2DDynamic_main.cpp.
#define kMaxWindowWidth 900
Definition at line 87 of file Tracking2DDynamic_main.cpp.
#define kMaxWindowWidth 900
Definition at line 87 of file Tracking2DDynamic_main.cpp.
#define kNbBckgndCols 6
Definition at line 200 of file Tracking2DDynamic_main.cpp.
#define kNbColsSubwindows 2
Definition at line 76 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
#define kNbRowsSubwindows 2
Definition at line 75 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
#define kPathSeparator "/"
Definition at line 101 of file Tracking2DDynamic_main.cpp.
#define kRootPath "./"
Definition at line 100 of file Tracking2DDynamic_main.cpp.
#define kUpNext "../"
Definition at line 103 of file Tracking2DDynamic_main.cpp.
#define kUpRoot "../"
Definition at line 102 of file Tracking2DDynamic_main.cpp.
#define PI 3.14159265
Definition at line 108 of file Tracking2DDynamic_main.cpp.
Referenced by myDisplay2().
#define READ_IN_GRAY_IMAGE 0
Definition at line 62 of file Tracking2DDynamic_main.cpp.
#define READ_IN_RGB_IMAGE 0
Definition at line 61 of file Tracking2DDynamic_main.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 60 of file Tracking2DDynamic_main.cpp.
Function Documentation
void cleanupQT (void)
Definition at line 247 of file Tracking2DDynamic_main.cpp.
Referenced by main(), and myKeyboard().
 {
     // terminate the QuickTime Media Layer
     ExitMovies();
 #if URIVL_OS_WIN32
     TerminateQTML();
 #endif
 }
void createRasterImageObj (void)
Definition at line 589 of file Tracking2DDynamic_main.cpp.
References FAIL_CONDITION, filePath, uriVL::ImageReader::getFrame(), uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), gMyPlayer, and uriVL::kRasterImageError.
Referenced by glSetupAndRun().
 {
         myReader = new ImageReader(filePath);
         gBackgroundImage = myReader->getFrame(true);
         gController = new BlobTracker2DController(gBackgroundImage);
     gMyPlayer = new MoviePlayer();
     gMyPlayer->setSource();
     gMyRect = gMyPlayer->getRect();
     int nbRows = gMyRect->getHeight();
     int nbCols = gMyRect->getWidth();
 #if READ_IN_RGBA_IMAGE
     gMyImage = new RasterImage_RGBa(nbRows, nbCols);
 #else
 #if READ_IN_RGB_IMAGE
     gMyImage = new RasterImage_RGB(nbRows, nbCols);
 #else
     gMyImage = new RasterImage_gray(nbRows, nbCols);
 #endif
 #endif
     FAIL_CONDITION(     gMyImage == NULL,
                     kRasterImageError,
                     "Failed to allocate RasterImage");
     FAIL_CONDITION(     gBackgroundImage == NULL,
                     kRasterImageError,
                     "Failed to allocate RasterImage");
 }
void glSetupAndRun (void)
Definition at line 630 of file Tracking2DDynamic_main.cpp.
References createRasterImageObj(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gInitDone, gMainWindow, gSubwindow, gWinHeight, gWinWidth, kBackgroundColor, kBlackBackground, kBorder, kGrayBackground, kNbColsSubwindows, kNbRowsSubwindows, myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myKeyboard(), myMouse(), myReshape(), and setupOrthoCam().
Referenced by main().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbRowsSubwindows*kNbColsSubwindows+1])() =
         {myDisplayMain, myDisplay0, myDisplay1, myDisplay2, myDisplay3};
     createRasterImageObj( );
     //  I initialize my window's dimensions at the default values
     int imgHeight = gMyImage->getHeight();//320;
     int imgWidth = gMyImage->getWidth();//240;
     //  I initialize my window's dimensions
     gWinHeight = 2 * imgHeight + 3 * kBorder;
   gWinWidth = 2 * imgWidth + 3 * kBorder;
     glutInitWindowSize(gWinWidth, gWinHeight);
     gMainWindow = glutCreateWindow("Movie Processing Demo");
     backColor = kBackgroundColor[kBlackBackground];
     glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
     glutDisplayFunc(myDisplayMain);
     setupOrthoCam(imgWidth, imgHeight);
     glutReshapeFunc(myReshape);
     glutIdleFunc(myIdle);
     glutMouseFunc(myMouse);
     glutKeyboardFunc(myKeyboard);
     winID = 0;
     glutSetWindow(gMainWindow);
     for (int i=0; i<kNbRowsSubwindows; i++)
         for (int j=0; j<kNbColsSubwindows; j++)
         {
             gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                     j*(imgWidth + kBorder) + kBorder,
                                                     i*(imgHeight + kBorder) + kBorder,
                                                     imgWidth, imgHeight);
             //  I don't need to do this.  I just set a different "clear" color for
             //  each subwindow.
             backColor = kBackgroundColor[kGrayBackground];
             glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
             //  This *has* to be defined:  a "display" callback function for each subwindow
             glutDisplayFunc(displayFuncTable[winID++]);
             glutMouseFunc(myMouse);
             //  This calls maps "world" coordinates to "screen" coordinates.
             //  In this particular case I make them coincide.
             setupOrthoCam(imgWidth, imgHeight);
             //
             glutSetWindow(gMainWindow);
         }
     DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
 //
 //       grayImg = new RasterImage_gray(gCurrentImage->getBoundRect());
 //    grad = new ImageGradient_Gaussian_F(2.0);
 //    gradient = new VectorField_F(gCurrentImage->getBoundRect());
 //       gNormGrad = new RasterImage_gray_F(gCurrentImage->getBoundRect());
 //       gThresholdedImg = new RasterImage_RGBa(gCurrentImage->getBoundRect());
 //
     gInitDone = true;
     glutMainLoop();
 }
void initializeQTEnvironment (void)
Definition at line 223 of file Tracking2DDynamic_main.cpp.
References FAIL_CONDITION, uriVL::kEnterMoviesError, and uriVL::kQuickTimeNotInstalled.
Referenced by main().
 {
     OSErr       myErr = noErr;
 #if URIVL_OS_WIN32
     myErr = InitializeQTML(kQTMLNoIdleEvents);
 #else
 #if URIVL_OS_MACOS
     long        myAttrs;
     myErr = Gestalt(gestaltQuickTime, &myAttrs);
 #endif
 #endif
     FAIL_CONDITION(     myErr != noErr,
                     kQuickTimeNotInstalled,
                     "QuickTime is not installed on this computer");
     myErr = EnterMovies();
     FAIL_CONDITION(     myErr != noErr,
                     kEnterMoviesError,
                     "Problems with EnterMovies, returning errors (exit)");
 }
int main (int argc, char ** argv)
Definition at line 707 of file Tracking2DDynamic_main.cpp.
References cleanupQT(), glSetupAndRun(), and initializeQTEnvironment().
 {
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
     initializeQTEnvironment( );
     glSetupAndRun( );
     cleanupQT( );
     return 0;
 }
void myDisplay0 (void)
Definition at line 366 of file Tracking2DDynamic_main.cpp.
References gInitDone, gMainWindow, gSubwindow, and uriVL::DrawableObject2D::render().
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[0]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone)
     {
         gMyImage->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 384 of file Tracking2DDynamic_main.cpp.
References uriVL::BlobTracker2DController::getDifferImg(), gFrameIndex, gInitDone, gMainWindow, and gSubwindow.
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[1]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     if (gInitDone && gFrameIndex > 5)
     {
                 (gController->getDifferImg())->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay2 (void)
Definition at line 401 of file Tracking2DDynamic_main.cpp.
References uriVL::DrawableObject2D::getHeight(), gFrameIndex, gInitDone, gMainWindow, gSubwindow, gTrackerList, PI, and uriVL::DrawableObject2D::render().
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     int imgHeight = gMyImage->getHeight();
     glutSetWindow(gSubwindow[2]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     if (gInitDone && gFrameIndex > 5)
     {
         gEstimatedBackImg->render();
             glLoadIdentity();
             glTranslatef(0.f, imgHeight, -0.5);
             glColor3f(1., 0, 0);
             glScalef(1, -1, 1.f);
         BlobTracker2DList::iterator iter = gTrackerList.begin();
         for( ; iter != gTrackerList.end(); iter++)
                         glTranslatef((*iter)->getCurrState()->getPos()->getX(),
                                                         (*iter)->getCurrState()->getPos()->getY(),
                                                                 0);
                 const int nbPts = 12;
                 glBegin(GL_POLYGON);
                         for (int i=0; i<12; i++)
                                 glVertex3d(3*cos(2*PI*i/nbPts), 3*sin(2*PI*i/nbPts), 0);
                 glEnd();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 437 of file Tracking2DDynamic_main.cpp.
References gMainWindow, and gSubwindow.
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[3]);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
 /*
     if (gInitDone)
     {
         gMyImage->render();
     }
 */
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 352 of file Tracking2DDynamic_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by glSetupAndRun().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 272 of file Tracking2DDynamic_main.cpp.
References uriVL::BlobTracker2DController::action(), uriVL::BlobTracker2DController::getCurrentBackground(), uriVL::BlobTracker2DController::getCurrTrackerList(), gFrameIndex, gMyPlayer, gTrackerList, myIdleDone(), and stepByStep.
Referenced by glSetupAndRun(), myKeyboard(), and myMouse().
 {
     static int  frameNum=0;
     OSErr                       anErr = noErr;
     OSType                      mediaType = VideoMediaType;
     TimeValue           nextTime = -1;
     nextTime = gMyPlayer->getNextTime();
     if (nextTime > -1)
     {
         gMyPlayer->getFrame(gMyImage);
         gFrameIndex++;
         //  apply BlobTracker2DController to render the trace of the moving objects
                 if(gFrameIndex > 5)
                 {
                         gController->action(gMyImage);
                         gTrackerList = gController->getCurrTrackerList();
                         gEstimatedBackImg = gController->getCurrentBackground();
                 #ifdef DEBUG
                 cout << "gTrackerList.size() = " << gTrackerList.size() << endl;
                 /*
                 BlobTracker2DList::iterator iter = gTrackerList.begin();
                 for( ; iter != gTrackerList.end(); iter++)
                         cout << "\n xi = " << (*iter)->getCurrState()->getPos()->getX() << endl;
                 cout << "new frame !" << endl;
                 */
                 #endif
             }
     }
     else
         glutIdleFunc(myIdleDone);
     glutPostRedisplay();
     if (stepByStep)
         glutIdleFunc(myIdleDone);
 }
void myIdleDone (void)
Definition at line 321 of file Tracking2DDynamic_main.cpp.
Referenced by myIdle().
 {
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 464 of file Tracking2DDynamic_main.cpp.
References cleanupQT(), and myIdle().
Referenced by glSetupAndRun().
 {
     switch (c)
     {
         case 'q':
             cleanupQT();
             std::exit(0);
             break;
         case 'a':
             glutIdleFunc(myIdle);
             break;
         case 's':
             glutIdleFunc(NULL);
             break;
         default:
             break;
     }
     //    glutPostRedisplay();
 }
void myMenu (int value)
Definition at line 522 of file Tracking2DDynamic_main.cpp.
 {
     switch (value)
     {
             //  0 --> Exit/Quit
         case 0:
             std::exit(0);
             break;
             //  1 --> Next image
         case 1:
             break;
             //  2 --> Previous image
         case 2:
             break;
             //  10-14 --> image selection
         case 10:
         case 11:
         case 12:
         case 13:
         case 14:
             break;
     }
     glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 498 of file Tracking2DDynamic_main.cpp.
References myIdle(), and stepByStep.
Referenced by glSetupAndRun().
 {
     // stop start the playing of the images/movie in the display
     // if the left mouse button is clicked, do something
     if (state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
         stepByStep = true;
         myIdle();
     }
     if (state == GLUT_DOWN && button == GLUT_MIDDLE_BUTTON)
     {
         glutIdleFunc(NULL);
     }
     //  ...and then refresh the display
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 335 of file Tracking2DDynamic_main.cpp.
References gWinHeight, and gWinWidth.
Referenced by glSetupAndRun().
 {
     if ((w != gWinWidth) || (h != gWinHeight))
         glutReshapeWindow(gWinWidth, gWinHeight);
     glutPostRedisplay();
 }
void setupOrthoCam (int w, int h)
Definition at line 567 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
RasterImage* gBackgroundImage
Definition at line 171 of file Tracking2DDynamic_main.cpp.
BlobTracker2DController* gController = NULL
Definition at line 185 of file Tracking2DDynamic_main.cpp.
ImagePoint_F** gCurrentPos = NULL
Definition at line 183 of file Tracking2DDynamic_main.cpp.
RasterImage * gEstimatedBackImg
Definition at line 171 of file Tracking2DDynamic_main.cpp.
long gFrameIndex = 0
Definition at line 152 of file Tracking2DDynamic_main.cpp.
Referenced by myDisplay1(), myDisplay2(), and myIdle().
bool gInitDone = false
Definition at line 209 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), and myDisplay2().
int gMainWindow
Definition at line 147 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myDisplayMain().
RasterImage_RGBa* gMyImage = NULL
Definition at line 156 of file Tracking2DDynamic_main.cpp.
MoviePlayer* gMyPlayer = NULL
Definition at line 175 of file Tracking2DDynamic_main.cpp.
Referenced by createRasterImageObj(), and myIdle().
ImageRect* gMyRect = NULL
Definition at line 153 of file Tracking2DDynamic_main.cpp.
int gSubwindow[kNbRowsSubwindows *kNbColsSubwindows]
Definition at line 147 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
BlobTracker2DList gTrackerList
Definition at line 184 of file Tracking2DDynamic_main.cpp.
Referenced by myDisplay2(), and myIdle().
int gWinHeight
Definition at line 144 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
int gWinWidth
Definition at line 144 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
= {     {0.f, 0.f, 0.f, 1.f},
        {1.f, 0.f, 0.f, 1.f},
        {0.f, 1.f, 0.f, 1.f},
        {1.f, 1.f, 0.f, 1.f},
        {0.f, 1.f, 1.f, 1.f},
        {.1f, .1f, .1f, 1.f}
                                             }
Definition at line 202 of file Tracking2DDynamic_main.cpp.
Referenced by glSetupAndRun().
ImageReader* myReader
Definition at line 170 of file Tracking2DDynamic_main.cpp.
bool stepByStep = false
Definition at line 151 of file Tracking2DDynamic_main.cpp.
Referenced by myIdle(), and myMouse().