URIVisionLibrary: Tracking2DPattern_main.cpp File Reference
Tracking2DPattern_main.cpp File Reference
#include <fstream>
#include <iostream>
#include <cstdlib>
#include <cmath>
#include <cstring>
#include <glut.h>
#include "ComFramework.h"
#include "ErrorReport.h"
#include "RasterImage.h"
#include "RasterImage_gray.h"
#include "RasterImage_RGB.h"
#include "RasterImage_RGBa.h"
#include "RasterImage_gray_F.h"
#include "VectorField_F.h"
#include "MoviePlayer.h"
#include "ImageReader.h"
#include "PatternTracker2DController.h"
Macros
#define READ_IN_RGBA_IMAGE 1
#define READ_IN_RGB_IMAGE 0
#define READ_IN_GRAY_IMAGE 0
#define FIRST_FRAME_INDEX 1
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kBorder 8
#define kDefaultHeight 256
#define kDefaultWidth 256
#define kMaxWindowWidth 900
#define kMaxWindowHeight 640
#define kRootPath "./"
#define kPathSeparator "/"
#define kUpRoot "../"
#define kUpNext "../"
#define PI 3.14159265
#define filePath "../../../../Data_Samples/Movies/trackingS02.tga"
#define DEBUG
#define kNbBckgndCols 6
#define kBlackBackground 0
#define kGrayBackground 5
Functions
void initializeQTEnvironment (void)
void cleanupQT (void)
void setupOrthoCam (int w, int h)
void myIdle (void)
void myIdleDone (void)
void myDisplayMain (void)
void myDisplay0 (void)
void myDisplay1 (void)
void myDisplay2 (void)
void myDisplay3 (void)
void printBlobs (void)
void myReshape (int w, int h)
void myMenu (int value)
void myMouse (int button, int state, int ix, int iy)
void myKeyboard (unsigned char c, int x, int y)
void createRasterImageObj (void)
void glSetupAndRun (void)
int main (int argc, char **argv)
Variables
const int kNbRowsSubwindows = 2
const int kNbColsSubwindows = 2
const int kNbSubwindows = kNbRowsSubwindows * kNbColsSubwindows
const int UPPER_LEFT = 0
const int UPPER_RIGHT = 1
const int LOWER_LEFT = 2
const int LOWER_RIGHT = 3
int gWinWidth
int gWinHeight
GLuint gMainWindow
GLuint gSubwindow [kNbSubwindows]
bool stepByStep = false
long gFrameIndex = 0
long gLastPrintedFrame = -1
ImageRect * gMyRect = NULL
RasterImage_RGBa * gMyImage = NULL
ImageReader * myReader
RasterImage * gBackgroundImage
RasterImage * gEstimatedBackImg
MoviePlayer * gMyPlayer = NULL
ImagePoint_F ** gCurrentPos = NULL
PatternTracker2DList * gTrackerList = NULL
PatternTracker2DController * gController = NULL
ImagePoint * gNewObjPoint = NULL
VectorField_F * gMyField = NULL
const float RENDER_SCALE = 5.f
GLfloat kBackgroundColor [kNbBckgndCols][4]
bool gInitDone = false
Macro Definition Documentation
#define DEBUG
Definition at line 222 of file Tracking2DPattern_main.cpp.
#define filePath "../../../../Data_Samples/Movies/trackingS02.tga"
Definition at line 208 of file Tracking2DPattern_main.cpp.
#define FIRST_FRAME_INDEX 1
Definition at line 103 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myIdle().
#define kBlackBackground 0
Definition at line 245 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
#define kBorder 8
Definition at line 123 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
#define kBorder 8
Definition at line 123 of file Tracking2DPattern_main.cpp.
#define kDefaultHeight 256
Definition at line 124 of file Tracking2DPattern_main.cpp.
#define kDefaultHeight 256
Definition at line 124 of file Tracking2DPattern_main.cpp.
#define kDefaultWidth 256
Definition at line 125 of file Tracking2DPattern_main.cpp.
#define kDefaultWidth 256
Definition at line 125 of file Tracking2DPattern_main.cpp.
#define kGrayBackground 5
Definition at line 246 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
#define kMaxWindowHeight 640
Definition at line 127 of file Tracking2DPattern_main.cpp.
#define kMaxWindowHeight 640
Definition at line 127 of file Tracking2DPattern_main.cpp.
#define kMaxWindowWidth 900
Definition at line 126 of file Tracking2DPattern_main.cpp.
#define kMaxWindowWidth 900
Definition at line 126 of file Tracking2DPattern_main.cpp.
#define kNbBckgndCols 6
Definition at line 235 of file Tracking2DPattern_main.cpp.
#define kPathSeparator "/"
Definition at line 140 of file Tracking2DPattern_main.cpp.
#define kRootPath "./"
Definition at line 139 of file Tracking2DPattern_main.cpp.
#define kUpNext "../"
Definition at line 142 of file Tracking2DPattern_main.cpp.
#define kUpRoot "../"
Definition at line 141 of file Tracking2DPattern_main.cpp.
#define PI 3.14159265
Definition at line 147 of file Tracking2DPattern_main.cpp.
#define READ_IN_GRAY_IMAGE 0
Definition at line 62 of file Tracking2DPattern_main.cpp.
#define READ_IN_RGB_IMAGE 0
Definition at line 61 of file Tracking2DPattern_main.cpp.
#define READ_IN_RGBA_IMAGE 1
Definition at line 60 of file Tracking2DPattern_main.cpp.
Function Documentation
void cleanupQT (void)
Definition at line 282 of file Tracking2DPattern_main.cpp.
Referenced by main(), myKeyboard(), and myMouse().
 {
     // terminate the QuickTime Media Layer
     ExitMovies();
 #if URIVL_OS_WIN32
     TerminateQTML();
 #endif
 }
void createRasterImageObj (void)
Definition at line 710 of file Tracking2DPattern_main.cpp.
References FAIL_CONDITION, uriVL::ImageRect::getHeight(), uriVL::ImageRect::getWidth(), gMyPlayer, and uriVL::kRasterImageError.
Referenced by glSetupAndRun().
 {
         /* ONLY not for ISORA PAPER
         myReader = new ImageReader(filePath);
         gBackgroundImage = myReader->getFrame(true);
         gController = new PatternTracker2DController(gBackgroundImage);
         */
     gMyPlayer = new MoviePlayer();
     gMyPlayer->setSource();
     gMyRect = gMyPlayer->getRect();
     int nbRows = gMyRect->getHeight();
     int nbCols = gMyRect->getWidth();
         gNewObjPoint = new ImagePoint(0, 0);
 #if READ_IN_RGBA_IMAGE
     gMyImage = new RasterImage_RGBa(nbRows, nbCols);
     //gMyImage = new RasterImage_HSV(nbRows, nbCols);
 #else
 #if READ_IN_RGB_IMAGE
     gMyImage = new RasterImage_RGB(nbRows, nbCols);
 #else
     gMyImage = new RasterImage_gray(nbRows, nbCols);
 #endif
 #endif
     FAIL_CONDITION(     gMyImage == NULL,
                     kRasterImageError,
                     "Failed to allocate RasterImage");
     /* ONLY not for ISORA PAPER
     FAIL_CONDITION(     gBackgroundImage == NULL,
                     kRasterImageError,
                     "Failed to allocate RasterImage");
         */
 }
void glSetupAndRun (void)
Definition at line 756 of file Tracking2DPattern_main.cpp.
References createRasterImageObj(), uriVL::DrawableObject2D::getHeight(), uriVL::DrawableObject2D::getWidth(), gInitDone, gMainWindow, gSubwindow, gWinHeight, gWinWidth, kBackgroundColor, kBlackBackground, kBorder, kGrayBackground, kNbColsSubwindows, kNbRowsSubwindows, kNbSubwindows, myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myDisplayMain(), myIdle(), myKeyboard(), myMouse(), myReshape(), and setupOrthoCam().
Referenced by main().
 {
     int         winID;
     GLfloat     *backColor;
     void        (*displayFuncTable[kNbSubwindows])() =
                                 {myDisplay0, myDisplay1, myDisplay2, myDisplay3};
     createRasterImageObj( );
     //  I initialize my window's dimensions at the default values
     int imgHeight = gMyImage->getHeight();//320;
     int imgWidth = gMyImage->getWidth();//240;
     //  I initialize my window's dimensions
     gWinHeight = 2 * imgHeight + 3 * kBorder;
     gWinWidth = 2 * imgWidth + 3 * kBorder;
     glutInitWindowSize(gWinWidth, gWinHeight);
     gMainWindow = glutCreateWindow("2D Pattern Tracking");
     backColor = kBackgroundColor[kBlackBackground];
     glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
     glutDisplayFunc(myDisplayMain);
     setupOrthoCam(imgWidth, imgHeight);
     glutReshapeFunc(myReshape);
     glutIdleFunc(myIdle);
     glutMouseFunc(myMouse);
     glutKeyboardFunc(myKeyboard);
     winID = 0;
     glutSetWindow(gMainWindow);
     for (int i=0; i<kNbRowsSubwindows; i++)
         for (int j=0; j<kNbColsSubwindows; j++)
         {
             gSubwindow[winID] = glutCreateSubWindow(gMainWindow,
                                                     j*(imgWidth + kBorder) + kBorder,
                                                     i*(imgHeight + kBorder) + kBorder,
                                                     imgWidth, imgHeight);
             //  I don't need to do this.  I just set a different "clear" color for
             //  each subwindow.
             backColor = kBackgroundColor[kGrayBackground];
             glClearColor(backColor[0], backColor[1], backColor[2], backColor[3]);
             //  This *has* to be defined:  a "display" callback function for each subwindow
             glutDisplayFunc(displayFuncTable[winID]);
             glutMouseFunc(myMouse);
             glutKeyboardFunc(myKeyboard);
             winID++;
             //  This calls maps "world" coordinates to "screen" coordinates.
             //  In this particular case I make them coincide.
             setupOrthoCam(imgWidth, imgHeight);
             //
             glutSetWindow(gMainWindow);
         }
     DrawableObject2D::setDefaultWindowDimensions(imgWidth, imgHeight);
 //
 //       grayImg = new RasterImage_gray(gCurrentImage->getBoundRect());
 //    grad = new ImageGradient_Gaussian_F(2.0);
 //    gradient = new VectorField_F(gCurrentImage->getBoundRect());
 //       gNormGrad = new RasterImage_gray_F(gCurrentImage->getBoundRect());
 //       gThresholdedImg = new RasterImage_RGBa(gCurrentImage->getBoundRect());
 //
     gInitDone = true;
     glutMainLoop();
 }
void initializeQTEnvironment (void)
Definition at line 258 of file Tracking2DPattern_main.cpp.
References FAIL_CONDITION, uriVL::kEnterMoviesError, and uriVL::kQuickTimeNotInstalled.
Referenced by main().
 {
     OSErr       myErr = noErr;
 #if URIVL_OS_WIN32
     myErr = InitializeQTML(kQTMLNoIdleEvents);
 #else
 #if URIVL_OS_MACOS
     long        myAttrs;
     myErr = Gestalt(gestaltQuickTime, &myAttrs);
 #endif
 #endif
     FAIL_CONDITION(     myErr != noErr,
                     kQuickTimeNotInstalled,
                     "QuickTime is not installed on this computer");
     myErr = EnterMovies();
     FAIL_CONDITION(     myErr != noErr,
                     kEnterMoviesError,
                     "Problems with EnterMovies, returning errors (exit)");
 }
int main (int argc, char ** argv)
Definition at line 835 of file Tracking2DPattern_main.cpp.
References cleanupQT(), glSetupAndRun(), and initializeQTEnvironment().
 {
     glutInit(&argc, argv);
     glutInitDisplayMode(GLUT_DOUBLE | GLUT_RGBA);
     initializeQTEnvironment( );
     glSetupAndRun( );
     cleanupQT( );
     return 0;
 }
void myDisplay0 (void)
for ICPR paper
Definition at line 413 of file Tracking2DPattern_main.cpp.
References FIRST_FRAME_INDEX, gFrameIndex, gInitDone, gMainWindow, gSubwindow, uriVL::DrawableObject2D::render(), and UPPER_LEFT.
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT);
     if (gInitDone && gFrameIndex > FIRST_FRAME_INDEX)
     {
         gMyImage->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay1 (void)
Definition at line 431 of file Tracking2DPattern_main.cpp.
References FIRST_FRAME_INDEX, uriVL::PatternTracker2DController::getDifferImg(), gFrameIndex, gInitDone, gMainWindow, gSubwindow, gTrackerList, uriVL::DrawableObject2D::render(), and UPPER_RIGHT.
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[UPPER_RIGHT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
         RasterImage_gray        *diffImage = NULL;
     if (gInitDone && gFrameIndex > FIRST_FRAME_INDEX)
     {
         if (gTrackerList->size() >= 1)
         {
                 PatternTracker2DList::iterator iter = gTrackerList->begin();
                 diffImage = (*iter)->getDifferenceImage();
         }
         if (diffImage == NULL)
                         diffImage = (gController->getDifferImg());
                 diffImage->render();
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay2 (void)
Definition at line 458 of file Tracking2DPattern_main.cpp.
References FIRST_FRAME_INDEX, uriVL::PatternTracker2DController::getCurrTrackerList(), uriVL::DrawableObject2D::getHeight(), uriVL::TrackingState::getPos(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), gFrameIndex, gInitDone, gMainWindow, gSubwindow, LOWER_LEFT, uriVL::DrawableObject2D::render(), RENDER_SCALE, uriVL::Pattern2D::setContourColor(), uriVL::Pattern2D::setDrawContour(), uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), and uriVL::Pattern2D::setRenderingScale().
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     int imgHeight = gMyImage->getHeight();
     glutSetWindow(gSubwindow[LOWER_LEFT]);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
      if (gInitDone && gFrameIndex > FIRST_FRAME_INDEX)
     {
                 list<PatternTracker2D *> *currTrackerList = gController->getCurrTrackerList();
                 list<PatternTracker2D *>::iterator      iter = currTrackerList->begin(),
                                                                                         endIter = currTrackerList->end();
                 for ( ; iter!=endIter; iter++)
                 {
                         Pattern2D *pat = (*iter)->getCurrPattern();
                         TrackingState *currState = (*iter)->getCurrState();
                         pat->setContourColor(1.f, 1.f, 0.f);
                         pat->setDrawContour(true);
                     pat->setDrawValidDataFrame(true);
                     pat->setFrameColor(1.f, 1.f, 0.f);
                     ImagePoint origin((int)(currState->getPos()->getX()),
                                                   (int)(currState->getPos()->getY()));
             pat->setRenderingScale(RENDER_SCALE, RENDER_SCALE);
                         pat->render(-1.f, false);
             pat->setRenderingScale(1, 1);
                 }
         }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplay3 (void)
Definition at line 495 of file Tracking2DPattern_main.cpp.
References FIRST_FRAME_INDEX, uriVL::PatternTracker2DController::getCurrTrackerList(), uriVL::TrackingState::getPos(), uriVL::PatternTracker2DController::getUpperBackground(), uriVL::ImagePoint::getX(), uriVL::ImagePoint::getY(), gFrameIndex, gInitDone, gMainWindow, gSubwindow, LOWER_RIGHT, uriVL::DrawableObject2D::render(), uriVL::DrawableObject2D::setColor(), uriVL::DrawableObject2D::setDrawValidDataFrame(), uriVL::DrawableObject2D::setFrameColor(), and uriVL::DrawableObject2D::setRenderingScale().
Referenced by glSetupAndRun(), and myDisplayMain().
 {
     glutSetWindow(gSubwindow[LOWER_RIGHT]);
     glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
     if (gInitDone && gFrameIndex > FIRST_FRAME_INDEX)
     {
         //      display the tracked object on current background
                 (gController->getUpperBackground())->render();
                 //      display bounding rectangle
                 list<PatternTracker2D *> *currTrackerList = gController->getCurrTrackerList();
                 list<PatternTracker2D *>::iterator      iter = currTrackerList->begin(),
                                                                                         endIter = currTrackerList->end();
                 TrackingState *currState = NULL;
                 Contour_I       *ct = NULL;
                 for ( ; iter!=endIter; iter++)
                 {
                         currState = (*iter)->getCurrState();
                         ct = (*iter)->getCurrPattern()->getBlob()->getContour();
                         ct->setColor(1.f, 1.f, 0.f);
                     ct->setDrawValidDataFrame(true);
                     ct->setFrameColor(1.f, 1.f, 0.f);
                     ImagePoint origin((int)(currState->getPos()->getX()),
                                                   (int)(currState->getPos()->getY()));
             ct->setRenderingScale(1, 1);
                         ct->render(-1.f, true, &origin);
                 }
     }
     glutSwapBuffers();
     glutSetWindow(gMainWindow);
 }
void myDisplayMain (void)
Definition at line 397 of file Tracking2DPattern_main.cpp.
References gMainWindow, myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
Referenced by glSetupAndRun().
 {
     glutSetWindow(gMainWindow);
     glMatrixMode(GL_MODELVIEW);
     glClear(GL_COLOR_BUFFER_BIT);
     glutSwapBuffers();
     myDisplay0();
     myDisplay1();
     myDisplay2();
     myDisplay3();
 }
void myIdle (void)
Definition at line 307 of file Tracking2DPattern_main.cpp.
References uriVL::PatternTracker2DController::action(), FIRST_FRAME_INDEX, uriVL::PatternTracker2DController::getCurrentBackground(), uriVL::PatternTracker2DController::getCurrTrackerList(), gFrameIndex, gMyPlayer, gTrackerList, myIdleDone(), and stepByStep.
Referenced by glSetupAndRun(), myKeyboard(), and myMouse().
 {
     static int  frameNum=0;
     OSErr                       anErr = noErr;
     OSType                      mediaType = VideoMediaType;
     TimeValue           nextTime = -1;
     nextTime = gMyPlayer->getNextTime();
     if (nextTime > -1)
     {
         gMyPlayer->getFrame(gMyImage);
         gFrameIndex++;
 cout << "Frame " << gFrameIndex << endl;
                 ///*
                 // only for ISORA PAPER, which reads first bkgd img from video
                 if (gFrameIndex == 1) //530)//780)
                         gController = new PatternTracker2DController(gMyImage);
                 //*/
         //  apply PatternTracker2DController to render the trace of the moving objects
                 if (gFrameIndex > FIRST_FRAME_INDEX)
                 {
                         gController->action(gMyImage);
                         gTrackerList = gController->getCurrTrackerList();
                         gEstimatedBackImg = gController->getCurrentBackground();
                 #ifdef DEBUG
                 cout << "gTrackerList->size() = " << gTrackerList->size() << endl;
 //if (gTrackerList->size() > 0)
 //    printBlobs();
                 /*
                 PatternTracker2DList::iterator iter = gTrackerList->begin();
                 for( ; iter != gTrackerList->end(); iter++)
                         cout << "\n xi = " << (*iter)->getCurrState()->getPos()->getX() << endl;
                 cout << "new frame !" << endl;
                 */
                 #endif
             }
     }
     else
         glutIdleFunc(myIdleDone);
     glutPostRedisplay();
     if (stepByStep)
         glutIdleFunc(myIdleDone);
 }
void myIdleDone (void)
Definition at line 366 of file Tracking2DPattern_main.cpp.
Referenced by myIdle(), and myKeyboard().
 {
     glutPostRedisplay();
 }
void myKeyboard (unsigned char c, int x, int y)
Definition at line 581 of file Tracking2DPattern_main.cpp.
References cleanupQT(), myIdle(), myIdleDone(), printBlobs(), and stepByStep.
Referenced by glSetupAndRun().
 {
     switch (c)
     {
         case 'q':
             cleanupQT();
             std::exit(0);
             break;
         case 'a':
             stepByStep = false;
             glutIdleFunc(myIdle);
             break;
         case 's':
             glutIdleFunc(myIdleDone);
             break;
         case 'b':
             printBlobs();
             break;
         default:
             break;
     }
     //    glutPostRedisplay();
 }
void myMenu (int value)
Definition at line 643 of file Tracking2DPattern_main.cpp.
 {
     switch (value)
     {
             //  0 --> Exit/Quit
         case 0:
             std::exit(0);
             break;
             //  1 --> Next image
         case 1:
             break;
             //  2 --> Previous image
         case 2:
             break;
             //  10-14 --> image selection
         case 10:
         case 11:
         case 12:
         case 13:
         case 14:
             break;
     }
     glutPostRedisplay();
 }
void myMouse (int button, int state, int ix, int iy)
Definition at line 619 of file Tracking2DPattern_main.cpp.
References gDragWin, gMouseDown, gStartDragX, gStartDragY, kMinSearchDim, MAX, MIN, myDisplayMain(), myIdle(), uriVL::ImageHistogram::setImage(), stepByStep, and withinBounds().
Referenced by glSetupAndRun().
 {
     // stop start the playing of the images/movie in the display
     // if the left mouse button is clicked, do something
     if (state == GLUT_DOWN && button == GLUT_LEFT_BUTTON)
     {
         stepByStep = true;
         myIdle();
     }
     if (state == GLUT_DOWN && button == GLUT_MIDDLE_BUTTON)
     {
         glutIdleFunc(NULL);
     }
     //  ...and then refresh the display
     glutPostRedisplay();
 }
void myReshape (int w, int h)
Definition at line 380 of file Tracking2DPattern_main.cpp.
References gWinHeight, and gWinWidth.
Referenced by glSetupAndRun().
 {
     if ((w != gWinWidth) || (h != gWinHeight))
         glutReshapeWindow(gWinWidth, gWinHeight);
     glutPostRedisplay();
 }
void printBlobs (void)
Definition at line 535 of file Tracking2DPattern_main.cpp.
References uriVL::Pattern2D::getBlob(), uriVL::PatternTracker2DController::getCurrTrackerList(), uriVL::Blob::getSegDeque(), gFrameIndex, gLastPrintedFrame, uriVL::HorizontalSegment::leftX, and uriVL::HorizontalSegment::rightX.
Referenced by myKeyboard().
 {
     if (gFrameIndex != gLastPrintedFrame)
     {
         list<PatternTracker2D *> *currTrackerList = gController->getCurrTrackerList();
         list<PatternTracker2D *>::iterator      iter = currTrackerList->begin(),
                                                                                 endIter = currTrackerList->end();
         //  For each pattern currently tracked
         for ( ; iter!=endIter; iter++)
         {
                 Pattern2D *pat = (*iter)->getCurrPattern();
             LineSegDeque *segDeque = pat->getBlob()->getSegDeque();
             //  print info about that pattern's blob
             cout << "\t----------------------------------"<<endl;
             deque< list<HorizontalSegment*> *>::iterator lineIter, lastLine = segDeque->end();
             for (lineIter = segDeque->begin(); lineIter != lastLine; lineIter++)
             {
                 cout << "\t\ty = " << (*((*lineIter)->begin()))->y << ": ";
                 list<HorizontalSegment*>::iterator  segIter, lastSeg = (*lineIter)->end();
                 for (segIter = (*lineIter)->begin(); segIter != lastSeg; segIter++)
                 {
                     HorizontalSegment   *theSeg;
                     theSeg = (*segIter);
                     cout << "<" << theSeg->leftX << ", " << theSeg->rightX << ">  ";
                 }
                 cout << endl << flush;
             }
             cout << "\t----------------------------------"<<endl;
         }
         gLastPrintedFrame = gFrameIndex;
     }
 }
void setupOrthoCam (int w, int h)
Definition at line 688 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
 {
     glMatrixMode(GL_PROJECTION);
     glLoadIdentity();
     gluOrtho2D( 0.0f, (GLfloat) w, 0.0f, (GLfloat) h);
     glMatrixMode(GL_MODELVIEW);
     glLoadIdentity();
     glViewport(0, 0, w, h);
 }
Variable Documentation
RasterImage* gBackgroundImage
Definition at line 211 of file Tracking2DPattern_main.cpp.
PatternTracker2DController* gController = NULL
Definition at line 216 of file Tracking2DPattern_main.cpp.
ImagePoint_F** gCurrentPos = NULL
Definition at line 214 of file Tracking2DPattern_main.cpp.
RasterImage * gEstimatedBackImg
Definition at line 211 of file Tracking2DPattern_main.cpp.
long gFrameIndex = 0
Definition at line 191 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), myIdle(), and printBlobs().
bool gInitDone = false
Definition at line 244 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
long gLastPrintedFrame = -1
Definition at line 192 of file Tracking2DPattern_main.cpp.
Referenced by printBlobs().
GLuint gMainWindow
Definition at line 187 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), myDisplay2(), myDisplay3(), and myDisplayMain().
VectorField_F* gMyField = NULL
Definition at line 218 of file Tracking2DPattern_main.cpp.
RasterImage_RGBa* gMyImage = NULL
Definition at line 196 of file Tracking2DPattern_main.cpp.
MoviePlayer* gMyPlayer = NULL
Definition at line 213 of file Tracking2DPattern_main.cpp.
Referenced by createRasterImageObj(), and myIdle().
ImageRect* gMyRect = NULL
Definition at line 193 of file Tracking2DPattern_main.cpp.
ImagePoint* gNewObjPoint = NULL
Definition at line 217 of file Tracking2DPattern_main.cpp.
GLuint gSubwindow[kNbSubwindows]
Definition at line 187 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun(), myDisplay0(), myDisplay1(), myDisplay2(), and myDisplay3().
PatternTracker2DList* gTrackerList = NULL
Definition at line 215 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay1(), and myIdle().
int gWinHeight
Definition at line 184 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
int gWinWidth
Definition at line 184 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun(), and myReshape().
GLfloat kBackgroundColor[kNbBckgndCols][4]
Initial value:
= {     {0.f, 0.f, 0.f, 1.f},
                                                {1.f, 0.f, 0.f, 1.f},
                                                {0.f, 1.f, 0.f, 1.f},
                                                {1.f, 1.f, 0.f, 1.f},
                                                {0.f, 1.f, 1.f, 1.f},
                                                {.1f, .1f, .1f, 1.f}
                                             }
Definition at line 237 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
const int kNbColsSubwindows = 2
Definition at line 109 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
const int kNbRowsSubwindows = 2
Definition at line 108 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
const int kNbSubwindows = kNbRowsSubwindows * kNbColsSubwindows
Definition at line 110 of file Tracking2DPattern_main.cpp.
Referenced by glSetupAndRun().
const int LOWER_LEFT = 2
Definition at line 114 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay2().
const int LOWER_RIGHT = 3
Definition at line 115 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay3().
ImageReader* myReader
Definition at line 210 of file Tracking2DPattern_main.cpp.
const float RENDER_SCALE = 5.f
Definition at line 220 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay2().
bool stepByStep = false
Definition at line 190 of file Tracking2DPattern_main.cpp.
Referenced by myIdle(), myKeyboard(), and myMouse().
const int UPPER_LEFT = 0
Definition at line 112 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay0().
const int UPPER_RIGHT = 1
Definition at line 113 of file Tracking2DPattern_main.cpp.
Referenced by myDisplay1().